### PR TITLE
storage: Replace all "var" keywords with "let" or "const"

### PR DESCRIPTION
**Pull request by mvollmer**
So that we don't mix old and new styles.

### CODE REVIEW

**Comment by mvollmer** [comment]
This was done with sed and eslint:fix.

**Comment by martinpitt** [comment]
@mvollmer : No point in `packit build` -- your branch is out of date, so with packit's current "rebase to latest origin/main" behaviour there just won't be a matching cached dist build. @allisonkarlitskaya and I need to talk about what to do there (I think she had a plan already), but until then it's "rebase or ignore" (ignore seems fine here)

**Comment by martinpitt** [comment]
This PR includes an update to test/reference, why? Is that just a git rebase/pilot error?

**Comment by mvollmer** [comment]
> This PR includes an update to test/reference, why? Is that just a git rebase/pilot error?

Oh, yes!

**Review by martinpitt — APPROVED** [review]
Clever approach! Feels like we should do this throughout cockpit, and then add some eslint rule that yells on using `var`.

**Comment by martinpitt** [comment]
BTW, `"no-var": "warn",` in .eslintrc.json does just that, and works fine.

**Pull request merged**
