### PR TITLE
subscriptions: Install insights-client on demand

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
This needs a test.

**Comment by martinpitt** [comment]
I'm fixing the "missing intltool" failure in https://github.com/cockpit-project/cockpituous/pull/297

**Comment by martinpitt** [comment]
centos-7 and rhel-7-8 are fine now wrt. intltool; fedora-30 tests are doomed now, as the fedora 30 image's mock doesn't have intltool any more. For that we either need to hack the image to add a manual list of extra build deps, or backport the intltool change.

**Comment by mvollmer** [comment]
Demo: https://www.youtube.com/watch?v=k6F2sbW99J8

**Comment by andreasn** [comment]
TODO for me to fix up some whitespace issues.

**Comment by mvollmer** [comment]
I don't know what to make of https://209.132.184.41:8493/logs/pull-13027-20191030-074040-809e38ca-cockpit-project-cockpit--rhel-7-8/log.html#56-2 ...

**Comment by mvollmer** [comment]
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1768917

**Comment by mvollmer** [comment]
> Also, should this also be proposed as a PR to subscription-manager(-cockpit), or is insights-client a dependency of subscription-manager in RHEL 8?

It's installed by default.

**Pull request merged**
