### PR TITLE
vagrant: Fix version check failing

### PR DESCRIPTION
**Pull request by mvollmer**
By moving fail.html into a location that is actually synched into the
virtual machine.

### CODE REVIEW

**Comment by dperpeet** [comment]
Just to be clear, this doesn't do anything about the failure, it just makes the notification clearer, right?

**Comment by mvollmer** [comment]
> Just to be clear, this doesn't do anything about the failure, it just makes the notification clearer, right?

Yes.

**Comment by dperpeet** [comment]
How does the sync work? Can we symlink `fail.html`?

**Comment by mvollmer** [comment]
> Can we symlink fail.html?

Yes, a symlink works as well.  Done.

**Pull request closed without merging**
