### PR TITLE
update Patternfly to version 1.3.0

### PR DESCRIPTION
**Pull request by andreasn**
Still a small issue with the checkboxes that I'm trying to figure out

### CODE REVIEW

**Comment by stefwalter** [comment]
We need to skip the object-describer changes.

**Comment by andreasn** [comment]
This is the messed up checkbox.
It works if you put both the checkbox and the label inside a label tag apparently.

screenshot from 2015-06-08 17-16-11

**Comment by andreasn** [comment]
Another issue I ran into

screenshot from 2015-06-08 18-36-58

**Comment by andreasn** [comment]
All of the above should be fixed now.

**Comment by stefwalter** [comment]
I think this test failure has to do with this change:

```
======================================================================
ERROR: testBasic (__main__.TestRoles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-roles", line 59, in testBasic
    b.wait_present("#account-locked[disabled]")
  File "/home/hubbot/hubbot/a462d1edf83063ae438cb452734cad1a8be943f4_f22_x86-64/test/testlib.py", line 226, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/home/hubbot/hubbot/a462d1edf83063ae438cb452734cad1a8be943f4_f22_x86-64/test/testlib.py", line 223, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))), timeout=self.phantom_wait_timeout)
  File "/home/hubbot/hubbot/a462d1edf83063ae438cb452734cad1a8be943f4_f22_x86-64/test/testlib.py", line 629, in wait
    return self.run({'cmd': 'wait', 'cond': cond, 'timeout': timeout*1000})
  File "/home/hubbot/hubbot/a462d1edf83063ae438cb452734cad1a8be943f4_f22_x86-64/test/testlib.py", line 592, in run
    raise Error("timeout")
Error: timeout
```

@dperpeet Do you have time to investigate that at some point?

**Comment by dperpeet** [comment]
> Do you have time to investigate that at some point?

Adding the label to the checkbox meant that for users without superuser privileges we had to disable children-input elements recursively, not just for one level (jquery .find instead of .children)
https://github.com/cockpit-project/cockpit/pull/2408/files#diff-aae7d24f786b85d06ed993757922b637R49

**Comment by stefwalter** [comment]
> Adding the label to the checkbox meant that for users without superuser privileges we had to disable children-input elements recursively

Makes sense. @dperpeet I'll leave the rest of the review of this to you.

**Pull request closed without merging**
