### PR TITLE
tests: Stop allowing to click on invisible buttons

### PR DESCRIPTION
**Pull request by marusak**
`mouse` function had option `force` which made it possible to click on
invisible buttons. However this is a bad practice.

This was in the code mostly because in `check-active-pages` the dropdown
menu was needed to be opened while holding `alt` key down.

This commit teaches the mouse function to also simulate holding down
special keys.

In three other tests `force` was used pointlessly.

I just grepd where `click` with force was used. Possibly I missed some other places - but full test run should show me what I forgot.

### CODE REVIEW

**Comment by marusak** [comment]
One real fail in `testVlan` - We need to open dropdown before selecting value from it. I have fix locally but push force when I see more results of already running tests.

**Comment by martinpitt** [comment]
Hmm, no, [testVlan](https://209.132.184.41:8493/logs/pull-11812-20190513-135555-d67ba5c9-verify-debian-stable/log.html#216) still fails everywhere.

**Comment by martinpitt** [comment]
The test failures all look unrelated, but I'll have a few more retries for good measure.

**Comment by martinpitt** [comment]
The [avocado/fedora](https://209.132.184.41:8493/logs/pull-11812-20190514-073636-8f42f5ca-avocado-fedora/log.html) test timeout (124 is `timeout`'s exit code) is really curious -- the avocado tests don't run a browser, but then again this test practically never fails. And the log doesn't give any hint about what's wrong. I'll retry once more for comparison.

**Comment by marusak** [comment]
> The avocado/fedora test timeout (124 is timeout's exit code) is really curious

 Does not happen only in this PR, for example see https://209.132.184.41:8493/logs/pull-11813-20190514-065656-2208aba8-avocado-fedora/log.html

This seems like a different problem affecting current master. Most likely caused by `fedora-30` image refresh in https://github.com/cockpit-project/cockpit/pull/11819 which I stupidly approved since I did not realized that `avocado/fedora` is running already on F30. I'll look into this outside of this PR.

**Comment by martinpitt** [comment]
OK, remaining test failures are all accounted for elsewhere. Thanks!

**Pull request merged**
