### PR TITLE
Readme: add master build status

### PR DESCRIPTION
**Pull request by dperpeet**
Show our master build status on the github front page

### CODE REVIEW

**Comment by dperpeet** [comment]
Look at it [here](https://github.com/dperpeet/cockpit/tree/build_status)

**Comment by mvollmer** [comment]
Nice!

Personally, I would like this better if it would be right at the top of the README without any extra header or other text, like this: https://github.com/mvollmer/cockpit/tree/build_status

**Comment by mvollmer** [comment]
Also, what about removing the "hubbot" part from the status badges?

**Comment by andreasn** [comment]
https://github.com/mvollmer/cockpit/tree/build_status looks a bit cleaner, and makes it a bit straight forward to get directly to what's the project is about. I've seen other projects on github do their build status in a similar fashion.
Marius version still have a header called "CI status for master" in the text though.

**Pull request closed without merging**
