### PR TITLE
get rid of pixmaps for play, stop and eject. Fixes issue #2219

### PR DESCRIPTION
**Pull request by andreasn**

### CODE REVIEW

**Comment by stefwalter** [comment]
Incorrect icons being shown in the Containers page:

screenshot from 2015-04-29 15-32-55

**Comment by andreasn** [comment]
A piece of code further down in the code was looking for the now removed classes, so changed those to the new fa-play and fa-stop

**Comment by stefwalter** [comment]
The tests fail with:

```
Page error: #containers-images tr:contains("busybox") button.btn-play not found

======================================================================
ERROR: testBasic (__main__.TestDocker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-docker", line 73, in testBasic
    b.click('#containers-images tr:contains("busybox") button.btn-play')
  File "/home/hubbot/hubbot/4088ce0e90cbf2d0fba54d1da43b7294847ac6b3_r7_x86-64/test/testlib.py", line 170, in click
    self.call_js_func('ph_click', selector)
  File "/home/hubbot/hubbot/4088ce0e90cbf2d0fba54d1da43b7294847ac6b3_r7_x86-64/test/testlib.py", line 162, in call_js_func
    return self.phantom.do("return %s(%s);" % (func, ','.join(map(jsquote, args))))
  File "/home/hubbot/hubbot/4088ce0e90cbf2d0fba54d1da43b7294847ac6b3_r7_x86-64/test/testlib.py", line 550, in do
    return self.run({'cmd': 'do', 'code': code})
  File "/home/hubbot/hubbot/4088ce0e90cbf2d0fba54d1da43b7294847ac6b3_r7_x86-64/test/testlib.py", line 517, in run
    raise Error(res['error'])
Error: #containers-images tr:contains("busybox") button.btn-play not found
```

**Comment by stefwalter** [comment]
Another failure:

```
OK
Wrote check-docker-testExpose-FAIL.png
Journal database copied to check-docker-testExpose-10.111.111.13-FAIL.journal
> monitor for docker directory failed: access-denied
.> monitor for docker directory failed: access-denied
Page error: #containers-images tr:contains("test/container-probe") button.btn-play not found
EWarning: Permanently added '10.111.111.13' (ECDSA) to the list of known hosts.

======================================================================
ERROR: testExpose (__main__.TestDocker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-docker", line 204, in testExpose
    b.click("#containers-images tr:contains(\"%s\") button.btn-play" % (image_name))
  File "/home/hubbot/hubbot/8d2010c1155c7f8db969e7234615c47f772c0520_r7_x86-64/test/testlib.py", line 170, in click
    self.call_js_func('ph_click', selector)
  File "/home/hubbot/hubbot/8d2010c1155c7f8db969e7234615c47f772c0520_r7_x86-64/test/testlib.py", line 162, in call_js_func
    return self.phantom.do("return %s(%s);" % (func, ','.join(map(jsquote, args))))
  File "/home/hubbot/hubbot/8d2010c1155c7f8db969e7234615c47f772c0520_r7_x86-64/test/testlib.py", line 550, in do
    return self.run({'cmd': 'do', 'code': code})
  File "/home/hubbot/hubbot/8d2010c1155c7f8db969e7234615c47f772c0520_r7_x86-64/test/testlib.py", line 517, in run
    raise Error(res['error'])
Error: #containers-images tr:contains("test/container-probe") button.btn-play not found
```

**Comment by stefwalter** [comment]
Fixed and merged.

**Pull request closed without merging**
