### PR TITLE
bots: Install tuned on debian-testing and ubuntu-stable images

### PR DESCRIPTION
**Pull request by martinpitt**
Enable check-tuned on these images.

 * [x] image-refresh debian-testing
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-3hwcj.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9262-20180529-091616/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-stable-20180529-094646

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-c0903.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9262-20180529-095151/

**Comment by martinpitt** [comment]
Seems [checkMachines](https://fedorapeople.org/groups/cockpit/logs/pull-9262-20180529-115050-cc72f985-verify-ubuntu-stable/log.html#12) got broken by the image rebuild.

**Comment by martinpitt** [comment]
Filed a [bug](https://launchpad.net/bugs/1774000) for the qemu failure and pushed a workaround.

**Pull request merged**
