### PR TITLE
containers: move the ws container to Fedora 39

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Comment by martinpitt** [comment]
Note that this change will not influence CI *at all*. It needs to be built and tested manually locally. (Hence, this could have been no-test).

**Comment by jelly** [comment]
> Note that this change will not influence CI _at all_. It needs to be built and tested manually locally. (Hence, this could have been no-test).

Hmmm I thought from reading ostree.install it would build it.

**Comment by martinpitt** [comment]
Yup:
```
make ws-container
# avoid local 9090 port conflict
podman run -d --name cockpit-bastion -p 9999:9090 quay.io/cockpit/ws
```

and test unpriv bastion host at https://localhost:9999/ . You can log into your laptop on `host.containers.internal`. 

I also tested privileged mode on a rhel4edge image:
```
podman save quay.io/cockpit/ws:latest | ssh c podman load -
ssh c podman container runlabel --name cockpit-ws RUN quay.io/cockpit/ws
```

and tested https://127.0.0.2:9091/

So this looks good!

**Review by martinpitt — APPROVED** [review]

**Comment by martinpitt** [comment]
I [triggered a new build](https://github.com/cockpit-project/cockpit/actions/runs/6849965183), [got a new build](https://quay.io/repository/cockpit/ws?tab=tags) and in a fresh rhel4edge I ran
```
podman rmi --all
podman container runlabel --name cockpit-ws RUN quay.io/cockpit/ws
# podman exec cockpit-ws cat /etc/fedora-release
Fedora release 39 (Thirty Nine)
```
So now we can refresh the fcos image, AFAICS.

**Pull request merged**
