### PR TITLE
examples: Add kubernetes nginx example that works on openshift

### PR DESCRIPTION
**Pull request by stefwalter**
The upstream nginx examples don't work on openshift or
atomic platform.

### CODE REVIEW

**Comment by stefwalter** [comment]
@andreasn This should help with our work trying out the cluster.

**Comment by petervo** [comment]
While i agree with setting RunAsAny for helping with manual testing other's examples. It would be good to run our tests with this setting off to make sure all of our containers work without this. I never would have caught all the issues with cockpit/kubernetes if all the tests had run as root.

**Comment by andreasn** [comment]
Cool!

**Comment by stefwalter** [comment]
Added lines to force the tests to use the default restrictive openshift permitted UID behavior.

**Pull request closed without merging**
