### PR TITLE
bridge: Add extra parameters on fslist

### PR DESCRIPTION
**Pull request by leomoty**
For #14170, This is just the starting point for running strace, I added a few basic attributes that are usually available for ls. 

This PR also does not do anything regarding the watch on fslist, I'd be happy to have any guidance how to handle it.

### CODE REVIEW

**Comment by leomoty** [comment]
Just so I don't forget, @martinpitt can you take a look?

**Comment by leomoty** [comment]
Hey @allisonkarlitskaya, any thoughts about it? been quite a while

**Comment by martinpitt** [comment]
Ugh, sorry that this slipped through the cracks for so long! I rebased this to current master, added simple unit test cases, and adjusted the documentation. I took the liberty to force-push to your branch to avoid extra roundtrips.

**Review by martinpitt — APPROVED** [review]
Thanks! @allisonkarlitskaya or @marusak, if you want to have another look, as I dabbled with this PR now.

**Pull request merged**
