### PR TITLE
WIP: Introduce unattended installation for VM creation

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
This is still a work in progress, but some initial design feedback would be valuable.
In order to use this feature you need virt-install 2.2.0 which is not available in fedora-30 yet.

If you want to test this please use the following repository:
```
$ cat /etc/yum.repos.d/_copr_@virtmaint-sig-virt-preview.repo 
[group_virtmaint-sig-virt-preview]
name=Copr repo for virt-preview owned by @virtmaint-sig
baseurl=https://copr-be.cloud.fedoraproject.org/results/@virtmaint-sig/virt-preview/fedora-$releasever-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/@virtmaint-sig/virt-preview/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
```

And update osinfo-db, libosindo, virt-install packages.

unattended-installation

**Comment by andreasn** [comment]
I keep getting this error when I try running this:
`WARNING Using unattended profile 'desktop' ERROR 'InstallConfig' object has no attribute 'set_installation_url' Domain installation does not appear to have been successful. If it was, you can restart your domain by running: virsh --connect qemu:///system start asdf otherwise, please restart your installation.`

But this might be a missing dependency on my side?

**Comment by KKoukiou** [comment]
> I keep getting this error when I try running this:
> `WARNING Using unattended profile 'desktop' ERROR 'InstallConfig' object has no attribute 'set_installation_url' Domain installation does not appear to have been successful. If it was, you can restart your domain by running: virsh --connect qemu:///system start asdf otherwise, please restart your installation.`
> 
> But this might be a missing dependency on my side?

What operating system did you choose?

**Comment by garrett** [comment]
Thanks for working on this! I think we can use the functionality to make the create VM workflow better. 

That said:

1. What is "unattended mode"? I don't think our users will know what that is or what it does. (I know it does templates and lets you add username and password and such. But people outside of Red Hat or the FOSS dev community will not know this.)
2. The related UI is not all in once place. There's a toggle at the top that affects the bottom? Weird.
3. I think we have the opportunity to simply things here, but, instead, we're making it more complex. Can we re-think this? We have the hackfest in a month and can discuss it face-to-face — I've added it to the agenda document.
4. Meanwhile, in the next month, I can try to sketch up what I think the create VM flow and dialog can be. If we agree on things before the hackfest, that's great. If not, we still have the hackfest to talk about it. :wink:

**Comment by garrett** [comment]
FWIW, you can enable copr repos & install the packages like this (as root):

```
dnf copr enable @virtmaint-sig/virt-preview
dnf distro-sync -y osinfo-db libosinfo virt-install
```

**Comment by garrett** [comment]
After installing all the stuff and compiling, I do have UI elements in the screenshots in this PR but don't have a profile selector. Is that expected?

What are typical profiles? What do they do? How are they customized? Where do they come from?

**Comment by andreasn** [comment]
> I do have UI elements in the screenshots in this PR but don't have a profile selector. Is that expected?

I only got them when selecting certain OSes. Debian will ask you for a profile I think, but I'm not quite sure what it does.

**Comment by KKoukiou** [comment]
> > I do have UI elements in the screenshots in this PR but don't have a profile selector. Is that expected?
> 
> I only got them when selecting certain OSes. Debian will ask you for a profile I think, but I'm not quite sure what it does.

You should be able to see a profile element when selecting an OS entry that supports unattended installation. All OSes that do not support unattended mode should be disabled and you won't be able to select them. The default selection, which is here 'Other OS' of course doesn't support this mode, since this OS is just the empty choice name from us.
This is one of the reasons I don't like the dropdown for the OS, because it doesn't allow you to show clearly the empty state of the OS selection.

**Comment by KKoukiou** [comment]
> After installing all the stuff and compiling, I do have UI elements in the screenshots in this PR but don't have a profile selector. Is that expected?
> 
> What are typical profiles? What do they do? How are they customized? Where do they come from?

The are two profile types, desktop and jeos (Just Enough Operating System). You can imagine them as desktop - server variants for the same OS. (jeos is meant to be minimal install for cloud deployments)
They information for available profiles for each OS comes from libosinfo.

**Comment by KKoukiou** [comment]
> Thanks for working on this! I think we can use the functionality to make the create VM workflow better.
> 
> That said:
> 
>     1. What is "unattended mode"? I don't think our users will know what that is or what it does. (I know it does templates and lets you add username and password and such. But people outside of Red Hat or the FOSS dev community will not know this.)

As the name implies unattended mode, is non interactive installation. Which means that after the user click the create button in the dialog, they won't have to do something else to get an up and running OS.
Otherwise the user will need to insert user/password credentials for the admin and normal user and also do disk partitioning.
It has nothing to do with templates.

> 
>     2. The related UI is not all in once place. There's a toggle at the top that affects the bottom? Weird.

I find it weird as well, let's find a better UI for it!

> 
>     3. I think we have the opportunity to simply things here, but, instead, we're making it more complex. Can we re-think this? We have the hackfest in a month and can discuss it face-to-face — I've added it to the agenda document.



> 
>     4. Meanwhile, in the next month, I can try to sketch up what I think the create VM flow and dialog can be. If we agree on things before the hackfest, that's great. If not, we still have the hackfest to talk about it. wink

I would really like to work on this from now, let's do the templates in the hackfest, this is something else though. So let's get clear on what this functionality is supposed to offer, and get to some acceptable solution, and once we redesign during hackfest the create dialog, with template based solution, I will be happy to move the components around

**Comment by garrett** [comment]
I thought profiles would be selected first, and the appropriate OS would be selected for the profile.

That is, it would say the OS name and the profile in one group:

- Fedora 30: Server
- Fedora 30: Silverblue
- Fedora 30: Workstation
- Red Hat Enterprise 8.1: Server
- Red Hat Enterprise 8.1: Workstation
- Ubuntu: 19.04
- Ubuntu: 18.04 LTS
- Custom

**Comment by KKoukiou** [comment]
> I thought profiles would be selected first, and the appropriate OS would be selected for the profile.
> 
> That is, it would say the OS name and the profile in one group:
> 
>     * Fedora 30: Server
> 
>     * Fedora 30: Silverblue
> 
>     * Fedora 30: Workstation
> 
>     * Red Hat Enterprise 8.1: Server
> 
>     * Red Hat Enterprise 8.1: Workstation
> 
>     * Ubuntu: 19.04
> 
>     * Ubuntu: 18.04 LTS
> 
>     * Custom

I am ok with these accept the 'Server' replacing the JEOS. JEOS is a naming used by OSes to indicate a stripped down version of the server variant. Which means using server is kinda misleading.
See https://help.ubuntu.com/community/JeOS

**Comment by KKoukiou** [comment]
> > I thought profiles would be selected first, and the appropriate OS would be selected for the profile.
> > That is, it would say the OS name and the profile in one group:
> > ```
> > * Fedora 30: Server
> > 
> > * Fedora 30: Silverblue
> > 
> > * Fedora 30: Workstation
> > 
> > * Red Hat Enterprise 8.1: Server
> > 
> > * Red Hat Enterprise 8.1: Workstation
> > 
> > * Ubuntu: 19.04
> > 
> > * Ubuntu: 18.04 LTS
> > 
> > * Custom
> > ```
> 
> I am ok with these except the 'Server' replacing the JEOS. JEOS is a naming used by OSes to indicate a stripped down version of the server variant. Which means using server is kinda misleading.
> See https://help.ubuntu.com/community/JeOS

@garrett I was wrong sorry, see conversation bellow.
```
(03:35:06 PM) fidencio: kkoukiou: jeos means just enough os (basically just what is needed for a server to boot up)
(03:35:49 PM) kkoukiou: fidencio: ubuntu says JEOS is stripped down server variant 
(03:35:49 PM) kkoukiou: ...
(03:36:00 PM) kkoukiou: Which made me confused 
(03:37:00 PM) fidencio: kkoukiou: yeah, the name adopted is confusing indeed. it made sense back in ~2010.
(03:37:44 PM) mmarusak left the room (quit: Ping timeout: 604 seconds).
(03:37:56 PM) fidencio: kkoukiou: I'd be really, really happy if apps as cockpit would adopt "Workstation" vs "Server" instead of "Desktop" vc "JeOS" when displaying this to the users
```

**Comment by KKoukiou** [comment]
This needs radical design ammendments, will discuss in person during HACKFEST, and I will either reopen this one or create a new PR.

**Pull request closed without merging**
