### PR TITLE
Update translations from Fedora Zanata

### PR DESCRIPTION
**Pull request by marusak**

### CODE REVIEW

**Comment by marusak** [comment]
Ehm, I did not expect this to happen :D I just ran `./bots/po-update` locally and it opened PR.
But this at least shows that it works just fine - as oppose to https://github.com/cockpit-project/cockpit/pull/12856

We can do either:
1. Land this, close #12856 and hope that next week it is going to magically work again
2. Close this and try to trigger po-refresh from task container and see if it breaks

**Comment by martinpitt** [comment]
@marusak: How did you trigger this? The most plausible explanation is that current zanata tools expect some locale that doesn't exist in our cockpit/tasks container? Can you reproduce the crash in that?

**Comment by marusak** [comment]
> How did you trigger this? 

I just executed `./bots/po-update` locally on my machine

> The most plausible explanation is that current zanata tools expect some locale that doesn't exist in our cockpit/tasks container? Can you reproduce the crash in that?

I noticed warning in [logs](https://209.132.184.41:8493/logs/po-refresh-12856-20190920-133939/log) from #12856 that says:
```
LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 zanata-cli -B push --includes cockpit.pot --project-config "../po/zanata.xml" \
	-s "./po"
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

Possibly missing some langpacks, but not sure why it would get missing suddenly. Were there some changes in tasks containers?

**Comment by marusak** [comment]
Hopefully obsoleted by #12867

**Pull request closed without merging**
