### PR TITLE
python: clean up subprocess signal handling, shutdown

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
This is my attempt at half of #18340, plus some bonus cleanups.

### CODE REVIEW

**Comment by martinpitt** [comment]
Ugh, a lot of failures:
```
os.kill(self._process.pid, sig)
^^^^^^^^^^^^^
AttributeError: 'SubprocessTransport' object has no attribute '_process'
```

Aside from that, this is really nice cleanup! Looking forward to bringing back the unit tests after this!

**Comment by allisonkarlitskaya** [comment]
The test failures are really obvious: if the subprocess spawn throws then we end up with a half-initialized object that still gets `__del__()` called on it.  We need to deal with that by detecting the half-initialization.

It's a little bit annoying and I'm not clear what the "correct" way to deal with this is in terms of mypy.  It's happy if you unconditionally assign the values in `__init__()` but it doesn't consider exceptions.

**Comment by martinpitt** [comment]
Thanks! So, this is the time and place where we can cheer for TestActivePages to go green, err todo-red? :tada:

**Comment by martinpitt** [comment]
Hmm, sad, [TestActivePages still fails](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18359-20230216-133732-12b8e86c-fedora-37-pybridge/log.html)

**Comment by allisonkarlitskaya** [comment]
> Hmm, sad, [TestActivePages still fails](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18359-20230216-133732-12b8e86c-fedora-37-pybridge/log.html)

This PR isn't trying to fix that.  See #18292.

**Comment by allisonkarlitskaya** [comment]
I bet it's because we `SIGKILL` now rather than `SIGTERM`.  Probably something else would clean up those processes before, but it no longer gets the chance to.... hrmph.

**Comment by allisonkarlitskaya** [comment]
> I bet it's because we `SIGKILL` now rather than `SIGTERM`. Probably something else would clean up those processes before, but it no longer gets the chance to.... hrmph.

Yup.

**Comment by allisonkarlitskaya** [comment]
> I bet it's because we `SIGKILL` now rather than `SIGTERM`. Probably something else would clean up those processes before, but it no longer gets the chance to.... hrmph.

@mvollmer says "let's do SIGTERM", and I'm inclined to agree.

**Review by martinpitt — APPROVED** [review]
Unchanged opinion: This is still a great PR and nice cleanup! Crossing fingers for the last few meters of the tests.. :checkered_flag:

**Pull request merged**
