### PR TITLE
storaged: Automatically teardown used devices

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
> What changed that I should look for?

Try this:

- Make two partitions on a disk, one with a filesystem, one without.
- Mount the filesystem.
- Create a volume group that uses one of the blank partitions as a physical volume
- Now try formatting the disk.

The filesystem should be automaticall unmounted, and the volume group should be automatically removed.

Also:

- Make a blank partition on a disk
- Create a volume group that uses the blank partitions as a physical volume
- Create a logical volume in the volume group
- Now try formatting the disk.

The formatting will fail because the volume group is not totally empty.

**Comment by dperpeet** [comment]
@andreasn have you had time to look at this? Also I think the commit messages can be a bit clearer.

**Comment by andreasn** [comment]
Screenshot:
screenshot from 2017-05-03 11-41-25

**Comment by andreasn** [comment]
I think it might make more sense to add the new content below Erase and Partioning.
This makes the dialog look more similar to it's "default state" and hence more recognizable.
Apart from that, looks good to me. Wording and layout makes sense, and works as expected.

**Comment by andreasn** [comment]
Second screenshot, just for reference:
screenshot from 2017-05-05 11-28-33

**Comment by mvollmer** [comment]
Second scenario, where the formatting is denied:

screenshot from 2017-05-05 12-32-45

**Comment by mvollmer** [comment]
> I think it might make more sense to add the new content below Erase and Partioning.

Done.

**Comment by cockpituous** [comment]
[storage: Tear down used devices before re-use](https://trello.com/c/78lN5M9i/485-storage-tear-down-used-devices-before-re-use)

**Pull request closed without merging**
