### PR TITLE
bots: Add lorax-composer to rhel-7-6 image

### PR DESCRIPTION
**Pull request by martinpitt**
Necessary for testing composer. It cannot install packages any more, as
this now requires a subscription.

 * [x] image-refresh rhel-7-6

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-tk8mq.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10485-20181031-092929/

**Comment by cockpituous** [comment]
image-refresh rhel-7-6 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-6-20181031-100303

**Comment by martinpitt** [comment]
This indeed did fix the package installation failure on the cockpit/rhel-7-6/* tests. But the tests now fail in the actual selenium tests, like `Single Word Blueprint Name Scenario "before each" hook for "should have all sanity attributes when shown"`. @henrywang, does the log tell you anything by chance?

But at least this is progress, before the rhel-7-6/welder-web tests failed on the inability to install gcc-c++ and lorax-composer.

**Comment by martinpitt** [comment]
Need to [remove realmd harder](https://fedorapeople.org/groups/cockpit/logs/pull-10485-20181031-100606-45e77623-verify-rhel-7-6/log.html#186), as it now has a reverse dependency.

**Comment by martinpitt** [comment]
Fixed.

**Comment by henrywang** [comment]
@martinpitt. after went through the debug log, the failed is because "available components" is empty. Looks lorax-composer cannot loaded.

**Pull request merged**
