### PR TITLE
pkg: fix typos found by codespell

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Thanks! Lots of failures, but presumably just flakes due to 3x affected. I do a round of retries.

**Comment by martinpitt** [comment]
Also: yay. firewalld in c10s was finally fixed! https://artifacts.dev.testing-farm.io/ef643298-5d63-4237-b247-0bd64cae528c/

**Comment by jelly** [comment]
> Thanks! Lots of failures, but presumably just flakes due to 3x affected. I do a round of retries.

Yup, was afraid of that

**Comment by martinpitt** [comment]
@jelly This pixel failure is real: https://cockpit-logs.us-east-1.linodeobjects.com/pull-20830-defa473a-20240802-065308-fedora-40-storage/log.html

**Comment by jelly** [comment]
> @jelly This pixel failure is real: https://cockpit-logs.us-east-1.linodeobjects.com/pull-20830-defa473a-20240802-065308-fedora-40-storage/log.html

A real fix!

**Comment by jelly** [comment]
To not let this rot, force pushed with pixel test fixes

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
