### PR TITLE
machines: Make vmLastMessage parameterizable for different tabs

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
test was not added since I can't find a standarized way to make deviceupdate call fail.

**Comment by KKoukiou** [comment]
Now network errors will appear in network tab like in screen shot bellow, and not in the overview tab.

networktab-fail

**Comment by martinpitt** [comment]
Nevermind, push-rewrite can't yet deal with foreign branches. But you can try for yourself! Look at bots/push-rewrite, the header comment explains it.

**Comment by martinpitt** [comment]
@KKoukiou : As for the test, how did you manually trigger the network error in the screenshot?

**Comment by KKoukiou** [comment]
> @KKoukiou : As for the test, how did you manually trigger the network error in the screenshot?



> @KKoukiou : As for the test, how did you manually trigger the network error in the screenshot?

I changed the method name when calling the API. So the call failed with `unknown` method or something similiar.

**Comment by KKoukiou** [comment]
@martinpitt  can you reclick approve, I just used push-rewrite to update commit message with closes line,and lost the review :?

**Comment by martinpitt** [comment]
@KKoukiou: As per your IRC question: The idea was that upon force-push with push-rewrite, the previous test results would be copied, so that they would immediately appear as pass/fail, including logs, instead of getting re-tested. Did that not work?

**Pull request merged**
