### PR TITLE
New centos-7 image

### PR DESCRIPTION
**Pull request by mvollmer**
We need to fix/tune various things for a new centos 7 image.  Let's do this all here.

 * [x] image-refresh centos-7

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-7jsv1.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8943-20180404-110909/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-t9m4t.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8943-20180404-110909/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20180404-120303

**Comment by martinpitt** [comment]
[testHiddenLuks failure](https://fedorapeople.org/groups/cockpit/logs/pull-8943-20180405-090909-629693ab-verify-centos-7/log.html#130) could be real, retrying for comparison.

**Pull request closed without merging**
