### PR TITLE
fmf: Really force EPEL 8 on RHEL 9

### PR DESCRIPTION
**Pull request by martinpitt**
Do the same as in cockpit-machines:
https://github.com/cockpit-project/cockpit-machines/blob/main/test/browser/browser.sh#L23

### CODE REVIEW

**Comment by martinpitt** [comment]
I'm frankly quite stunned how this ever worked without this sed in RHEL 9.. Testing this in https://src.osci.redhat.com/rpms/cockpit/pull-request/71#

**Review by marusak — APPROVED** [review]
Thanks!
Have you seen it failing? Because if it works without it, then possibly we don't need the whole special epel case?

**Comment by martinpitt** [comment]
@marusak : Yes, I did. See the linked OSCI PR.

**Comment by martinpitt** [comment]
Even though the test results are a disaster now, installing chromium at least went fine :grin:

**Pull request merged**
