### PR TITLE
Check for NPM dependency updates

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [ ] FAIL: npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
npm-update @patternfly/react-console done: https://github.com/cockpituous/cockpit/commits/npm-update-@patternfly/react-console-20190612-072626

**Comment by cockpituous** [comment]
Error accessing /repos/cockpit-project/cockpit/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value"None,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}: https://209.132.184.41:8493/logs/npm-update-12052-20190612-072525/

**Comment by cockpituous** [comment]
npm-update @patternfly/react-console done: https://github.com/cockpituous/cockpit/commits/npm-update-@patternfly/react-console-20190612-072626

**Comment by cockpituous** [comment]
Error accessing /repos/cockpit-project/cockpit/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value"None,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}: https://209.132.184.41:8493/logs/npm-update-12052-20190612-072525/

**Comment by cockpituous** [comment]
npm-update @patternfly/react-console done: https://github.com/cockpituous/cockpit/commits/npm-update-@patternfly/react-console-20190612-071818

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "patternfly-react": "2.36.1",
pkg/kdump/kdump-view.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/lib/cockpit-components-inline-notification.jsx:import { Alert } from 'patternfly-react';
pkg/machines/app.jsx:import { ToastNotificationList, ToastNotification } from 'patternfly-react';
pkg/machines/components/aggregateStatusCards.jsx:} from 'patternfly-react';
pkg/machines/components/create-vm-dialog/createVmDialog.jsx:import { Button, FormGroup, HelpBlock, Modal } from 'patternfly-react';
pkg/machines/components/deleteDialog.jsx:import { Modal, Button } from 'patternfly-react';
pkg/machines/components/diskAdd.jsx:import { Button, Modal } from 'patternfly-react';
pkg/machines/components/diskRemove.jsx:import { Tooltip, OverlayTrigger } from 'patternfly-react';
pkg/machines/components/infoRecord.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/machines/components/networks/network.jsx:import { Button } from 'patternfly-react';
pkg/machines/components/networks/networkList.jsx:import { Breadcrumb } from 'patternfly-react';
pkg/machines/components/nicEdit.jsx:} from 'patternfly-react';
pkg/machines/components/storagePools/createStoragePoolDialog.jsx:import { Button, FormGroup, HelpBlock, Modal } from 'patternfly-react';
pkg/machines/components/storagePools/storagePool.jsx:import { Button, Tooltip, UtilizationBar } from 'patternfly-react';
pkg/machines/components/storagePools/storagePoolDelete.jsx:import { Button, Modal } from 'patternfly-react';
pkg/machines/components/storagePools/storagePoolList.jsx:import { Breadcrumb } from 'patternfly-react';
pkg/machines/components/storagePools/storageVolumeDelete.jsx:} from 'patternfly-react';
pkg/machines/components/vcpuModal.jsx:import { Button, Modal } from 'patternfly-react';
pkg/machines/components/vm/bootOrderModal.jsx:} from 'patternfly-react';
pkg/machines/components/vm/memoryModal.jsx:} from 'patternfly-react';
pkg/machines/components/warningInactive.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/machines/machines.less:// For patternfly-react and @patternfly/react-console
pkg/machines/machines.less:@import "~patternfly-react/dist/less/patternfly-react.less";
pkg/networkmanager/firewall.jsx:} from "patternfly-react";
pkg/ovirt/components/App.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/ovirt/components/infoRecord.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/packagekit/history.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/packagekit/updates.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/storaged/dialog.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/storaged/storage-controls.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/systemd/hwinfo.jsx:import { Alert, Button, ListView, Modal, OverlayTrigger, Tooltip } from 'patternfly-react';
```

**Comment by martinpitt** [comment]
Seems the new PF-React breaks API:
```
    Property '$color-pf-black-900' is undefined
          in undefined (line undefined, column undefined)
```

Fun thing is, we don't even use that in cockpit, that must be a bug within PF-React or some component we import.

**Comment by martinpitt** [comment]
I tried to update patternfly to the latest 3.59.1 together with this, but this doesn't help either. This is genuinely broken.

**Comment by marusak** [comment]
This is the same npm update as in #12104, I'll close this one

**Pull request closed without merging**
