### PR TITLE
containers: Detect fedora version when building cockpit/ws

### PR DESCRIPTION
**Pull request by petervo**

### CODE REVIEW

**Comment by stefwalter** [comment]
Do the integration tests cover this path?

**Comment by petervo** [comment]
No, we don't build in this way during integration tests. Mainly because we want to test the wip build, but also we try not to pull from the internet during tests runs. I'm not sure there is a way to test this without doing that.

**Comment by stefwalter** [comment]
Did you test it manually against multiple Fedora versions? If so, which ones?

**Comment by petervo** [comment]
Yes I've tested this change using f23 and f24 as the base. There is some strangeness with this dockerfile and the ADD rpms/* line. But since it was working before I didn't change that.

**Pull request closed without merging**
