### PR TITLE
base: race conditions and compatibility with Internet Explorer 11

### LINKED ISSUE #2565: race: internet explorer 11
After login (current master), internet explorer 11 seems to be locked into endlessly trying to connect to the server. It looks like a race in the storage-cache code.
race_ie11

### PR DESCRIPTION
**Pull request by dperpeet**
fixes #2565

### CODE REVIEW

**Comment by dperpeet** [comment]
fixes #2564

**Comment by dperpeet** [comment]
this should be tested for different brandings in different browsers

**Comment by stefwalter** [comment]
Now we see lots of "couldn't load os data: cancelled" in the tests. That seems like a bad side effect.

**Comment by dperpeet** [comment]
> Now we see lots of "couldn't load os data: cancelled" in the tests. That seems like a bad side effect.

as you mentioned on irc, this is apparently not caused by these changes and happens in other pull requests

**Pull request closed without merging**
