### PR TITLE
GZip compression and content negotiation

### PR DESCRIPTION
**Pull request by stefwalter**
This implements the way to install and consume gzip compressed files and do content negotiation for minified files.

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #1892 

Remaining:
 * Squashing cleanup
 * Remove Accept-Language logic from cockpitwebservice
 * Reimplement language logic as a requirejs loader plugin

**Comment by stefwalter** [comment]
This only compressed .js and .woff files for now.

Initial size change is 2.2MB of network traffic -> 945K

**Comment by stefwalter** [comment]
Fixed this bug:

```
src/bridge/cockpithttpstream.c:733:7: error: variable 'had_encoding' is used uninitialized whenever 'if' condition is false
```

**Comment by stefwalter** [comment]
Fixed this:

```
src/common/cockpitwebserver.c:714:19: error: variable 'value' is uninitialized when used here [-Werror,-Wuninitialized]
```

**Comment by stefwalter** [comment]
Fixed a bunch of distccheck issues.

**Comment by mvollmer** [comment]
check-pages produces this when run locally here:

```
Page error: Error: Script error for: playground/po
http://requirejs.org/docs/errors.html#scripterror
http://10.111.111.10:9090/cockpit/$7fefd4a3e5cd3f0c91de77d49c6f3cb5a15f2f6e/base1/require.js 141 defaultOnError
http://10.111.111.10:9090/cockpit/$7fefd4a3e5cd3f0c91de77d49c6f3cb5a15f2f6e/base1/require.js 545 onError
http://10.111.111.10:9090/cockpit/$7fefd4a3e5cd3f0c91de77d49c6f3cb5a15f2f6e/base1/require.js 1696 
EWrote check-pages-testBasic-FAIL.png
Warning: Permanently added '10.111.111.10' (ECDSA) to the list of known hosts.
system.journal                                                                                                                                                100% 8192KB   8.0MB/s   00:01    
user-1000.journal                                                                                                                                             100% 8192KB   8.0MB/s   00:00    
Journal database copied to check-pages-testBasic-10.111.111.10-FAIL.journal

======================================================================
ERROR: testBasic (__main__.TestPages)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-pages", line 60, in testBasic
    b.enter_page("/playground/test")
  File "/home/mvo/work/cockpit/test/testlib.py", line 291, in enter_page
    self.wait_visible("body")
  File "/home/mvo/work/cockpit/test/testlib.py", line 215, in wait_visible
    return self.wait_js_func('ph_is_visible', selector)
  File "/home/mvo/work/cockpit/test/testlib.py", line 206, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))), timeout=self.phantom_wait_timeout)
  File "/home/mvo/work/cockpit/test/testlib.py", line 537, in wait
    return self.run({'cmd': 'wait', 'cond': cond, 'timeout': timeout*1000})
  File "/home/mvo/work/cockpit/test/testlib.py", line 503, in run
    raise Error("timeout")
Error: timeout

----------------------------------------------------------------------
```

**Comment by stefwalter** [comment]
Fixed issues and regressions. Ready for review again.

**Pull request closed without merging**
