### PR TITLE
 Set upper limit for VM's memory in the VM creation dialog

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
> Nice, thanks! Please add a Closes # to the commit message.

Re-pushed.

**Comment by KKoukiou** [comment]
OHH, debian-stable virsh tests broke, https://209.132.184.41:8493/logs/pull-11491-20190329-095050-54de5eb6-verify-debian-stable/log.html#91 
Tested only fedora-29 locally, I need to check this failure.

**Comment by Gundersanne** [comment]
This looks good to me but I got `"Up to 0 GiB available on the host"`

image

**Comment by KKoukiou** [comment]
> This looks good to me but I got `"Up to 0 GiB available on the host"`
> nvm didn't have `libvirt-dbus` installed, works well now!

This means that I broke virsh only users. I will fix and repost! Thanks @Gundersanne for catching this!

**Comment by martinpitt** [comment]
[This rhel-7-7 failure](https://209.132.184.41:8493/logs/pull-11491-20190401-194646-e149770e-verify-rhel-7-7/log.html#91) looks a bit suspicious, retrying.

**Comment by martinpitt** [comment]
@KKoukiou : This [failed again](https://209.132.184.41:8493/logs/pull-11491-20190402-072222-e149770e-verify-rhel-7-7/log.html#212) on rhel-7-7, I'm afraid this is real.

**Comment by KKoukiou** [comment]
This is clean from Machines errors now, please re-review.

**Pull request merged**
