### PR TITLE
selinux: Build JSX files properly during make

### PR DESCRIPTION
**Pull request by stefwalter**
This builds .jsx files into .js files during make. However
it doesn't yet allow loading of JSX files during a browser
session.

### CODE REVIEW

**Comment by stefwalter** [comment]
Babel is just too big to distribute in our node_modules/ directory. At least for the forseeable future.

**Comment by dperpeet** [comment]
debian build failure https://fedorapeople.org/groups/cockpit/logs/pull-4132-c69e7e86-verify-debian-unstable/build-results/build.log

**Comment by dperpeet** [comment]
This doesn't install the setroubleshoot-view.js into the correct directory in maintainer mode (no linked dev dir).

**Comment by dperpeet** [comment]
file looks good, but this line needs to change (remove `/views`)
https://github.com/cockpit-project/cockpit/blob/fc18b6f08b2d32799dcc36769071bb27b852e0e5/pkg/selinux/setroubleshoot.js#L24

**Comment by dperpeet** [comment]
Problem with travis check:
https://travis-ci.org/cockpit-project/cockpit/jobs/120628145#L7118
```
Refusing to distribute minified files without original
```

**Comment by dperpeet** [comment]
selinux troubleshooting seems to work (tested on f23), also the check error is resolved here

**Comment by dperpeet** [comment]
debian test is still failing

**Pull request closed without merging**
