### PR TITLE
Various cleanup of the Kubernetes Client

### PR DESCRIPTION
**Pull request by stefwalter**
Pretty self explanatory on the various commits.

### CODE REVIEW

**Comment by stefwalter** [comment]
resourceVersion change needs a test.

**Comment by stefwalter** [comment]
Tests added.

**Comment by stefwalter** [comment]
@sub-mod This is ready for review.

**Comment by sub-mod** [comment]
@stefwalter code looks ok , will test and reply

**Comment by sub-mod** [comment]
@stefwalter testing passed

**Pull request closed without merging**
