### PR TITLE
Implement basic graph for kubernetes cluster page

### PR DESCRIPTION
**Pull request by stefwalter**
This is based on D3, with the goal that eventually it can be shared with other Kubernetes UIs.

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #2205

**Comment by stefwalter** [comment]
Replaces #2131

**Comment by stefwalter** [comment]
No events implementation yet, will do another pull request for that.

screenshot from 2015-05-04 11-18-29

**Comment by stefwalter** [comment]
Highlighting of various things on the page on hover is a follow up.

**Comment by stefwalter** [comment]
Fixed issue with cAdvisor not containing docker ids sometimes.

**Comment by stefwalter** [comment]
Rebased for changes in #2205

**Comment by stefwalter** [comment]
Rebased. There are still artifacts in the graph, but i'll fix them on follow up.

**Comment by stefwalter** [comment]
Rebased.

**Comment by mvollmer** [comment]
Works!

The graphs do not extend to the right edge of the plot area for me, though:

d3

Also, the plot walks asynchronously to the appearance of new samples.

**Comment by mvollmer** [comment]
The font of the tick labels and for the headings doesn't match the rest of the page.

**Pull request closed without merging**
