### PR TITLE
Add RHEL 7.6 nightly image

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh rhel-7-6
 * [x] put back atomic-openshift-clients
 * [x] report and add naughty override for /usr/libexec/postfix/local map SELinux denial
 * [x] investigate storage tests failing on `bd_fs_*' called, but not implemented!`
 * [x] fix IPA setup failure due to C locale (PR #9637)
 * [x] fix `check-networking-team TestNetworking.testTeamActive`

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-4p5bk.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9580-20180704-141010/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9580-20180704-141010/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-452nw.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9580-20180704-170606/

**Comment by cockpituous** [comment]
image-refresh rhel-7-6 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-6-20180704-174040

**Comment by martinpitt** [comment]
Next push, with atomic-openshift-clients being back, and naughty overrides for the two most apparent regressions. Wash, rinse, repeat.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-tqkqc.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9580-20180705-125656/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-tqkqc.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9580-20180705-160202/

**Comment by cockpituous** [comment]
image-refresh rhel-7-6 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-6-20180705-164141

**Comment by martinpitt** [comment]
As for the kerberos error:

    Failed to join domain: cockpit.lan: ipa: ERROR: System encoding must be UTF-8, 'ANSI_X3.4-1968' is not supported. Set LC_ALL="C.UTF-8", or LC_ALL="" and LC_CTYPE="C.UTF-8".

This *only* happens when running the headless chrome, not when running the interactive one, even when running it with `LC_ALL=C.UTF-8` (as the headless one is run). The difference is that with headless the privileged bridge on the rhel-7-6 instance runs with `LANG=C`, while it is `en_US.UTF-8` with the interactive chrome. I have absolutely no idea why this happens. Note that the unprivileged bridge has no `LANG` or `LC_*` in its environment, and in an ssh shell both `pkexec locale` and `sudo locale` have `en_US.UTF-8` (like what /etc/locale.conf says).

But this explains the visible error - the post-join actions in `install_ws_credentials()` call some `ipa-*` CLI programs, and in recent IPA versions they refuse to run under a C locale.

I can make the tests work with this patch:
```diff
--- a/pkg/realmd/operation.js
+++ b/pkg/realmd/operation.js
@@ -351,6 +351,9 @@
             // if kinit fails, we can't handle this setup, exit cleanly
             script += 'kinit ' + user + '@' + kerberos.RealmName + ' || exit 0; ';
 
+            // ensure this gets run with a non-C locale; ipa fails otherwise
+            script += "if [ $(sh -c 'eval `locale`; echo $LC_CTYPE') = 'C' ]; then export LC_CTYPE=en_US.UTF-8; fi; ";
+
             // create a kerberos Service Principal Name for cockpit-ws, unless already present
             script += 'service="HTTP/${HOST}@' + kerberos.RealmName + '"; ' +
                       'ipa service-show "$service" || ipa service-add --ok-as-delegate=true --force "$service"; ';
diff --git a/test/verify/check-realms b/test/verify/check-realms
index 9724ffae8..00c5f875c 100755
--- a/test/verify/check-realms
+++ b/test/verify/check-realms
@@ -366,7 +366,7 @@ done
 
 # create SPN and keytab for ws
 if type ipa >/dev/null 2>&1; then
-    LC_ALL=C.UTF-8 ipa service-add --ok-as-delegate=true --force HTTP/x0.cockpit.lan@COCKPIT.LAN
+    LC_ALL=en_US.UTF-8 ipa service-add --ok-as-delegate=true --force HTTP/x0.cockpit.lan@COCKPIT.LAN
 else
     curl --insecure -s --negotiate -u : https://f0.cockpit.lan/ipa/json --header 'Referer: https://f0.cockpit.lan/ipa' --header "Content-Type: application/json" --header "Accept: application/json" --data '{"params": [["HTTP/x0.cockpit.lan@COCKPIT.LAN"], {"raw": false, "all": false, "version": "2.101", "force": true, "no_members": false, "ipakrbokasdelegate": true}], "method": "service_add", "id": 0}'
 fi
```

The first part in pkg/realmd/operation.js is justifiable and we should land this as a robustification anyway. But C.UTF-8 is not available in RHEL 7 (also not in 7.5), which explains the second part in the test, and this is an ugly hack.

**Comment by martinpitt** [comment]
This now passes everything but the usual `testSerialConsole`. @larskarlitski , are you okay with landing this like it? Note that we *won't* run rhel-7-6 tests for every PR so far, just get the automatic rebuilds every week to keep track of progress. (Although I think we should enable that soon)

**Pull request merged**
