### PR TITLE
vagrant: Update to fedora 24

### LINKED ISSUE #4641: Vagrantfile is using Fedora 23
Now that Fedora 24 is released, it's a good time to update the vagrantfile to use that instead of Fedora 23.

### PR DESCRIPTION
**Pull request by larsu**
There's no need to override URLs anymore, because fedora now publishes
both libvirt and virtualbox images to vagrant's registry.

Fixes #4641 

**NOTE** This doesn't actually work yet, because selinux denies systemd from executing `git-version-check`:

    type=AVC msg=audit(1467098544.821:939): avc:  denied  { execute } for  pid=19874 comm="(on-check)" name="git-version-check" dev="vda1" ino=2232874 scontext=system_u:system_r:init_t:s0 tcontext=unconfined_u:object_r:default_t:s0 tclass=file permissive=0

Can someone with more knowledge about selinux please let me know what the correct way of fixing this is?

### CODE REVIEW

**Comment by stefwalter** [comment]
Lets get rid of the git-version-check stuff in the vagrant code. If our APIs are supposed to be stable, then we don't need it.

**Comment by larsu** [comment]
> Lets get rid of the git-version-check stuff in the vagrant code. If our APIs are supposed to be stable, then we don't need it.

Ironically, we do right now because of the raw/data change. That should be fixed soon though, I've already scheduled a copr build for 0.113. (When will that work automatically with the release again?)

Updated this branch to remove the check.

**Comment by stefwalter** [comment]
Blocked on #4696

**Comment by larsu** [comment]
#4696 is merged.

**Comment by dperpeet** [comment]
@larsu is this still a work in progress?

**Comment by stefwalter** [comment]
Now that the 0.114 release is done, this should no longer be blocked. In addition it should be possible to remove the version check logic.

**Comment by larsu** [comment]
> @larsu is this still a work in progress?

No, it isn't. Thanks, renaming.

> Now that the 0.114 release is done, this should no longer be blocked. In addition it should be possible to remove the version check logic.

I've removed that in c661480.

**Pull request closed without merging**
