### PR TITLE
test: RHEL Atomic Host has OSTree now

### PR DESCRIPTION
**Pull request by stefwalter**
We should enable the appropriate tests.

This also fixes a test failure we see in check-system-info
related to OSTree now being relevant.

### CODE REVIEW

**Comment by stefwalter** [comment]
Need help from @petervo to make this actually work.

I see "is chronologicalcly older than current revision" and "use --allow-downgrade to permit"

**Comment by stefwalter** [comment]
Switch to cockpit-kubernetes and cockpit-docker since cockpit-networkmanager and cockpit-sosreport are not available on rhel-atomic.

**Comment by petervo** [comment]
@stefwalter this looks like a regression in ostree, working on tracking it down in the meantime we should split off the test fix into a new PR.

**Comment by petervo** [comment]
Turns out this wasn't ostree's fault but rhsmcertd. Adding these lines to the test makes it pass.

```
m.execute("systemctl disable rhsmcertd")
m.execute("systemctl stop rhsmcertd")
```

**Comment by petervo** [comment]
For anyone who wants to follow along:

https://github.com/candlepin/subscription-manager/issues/1404

**Comment by dperpeet** [comment]
two weeks since the last update on the linked issue, any updates?

**Comment by petervo** [comment]
Looks good, except I think we need to remove ```verify/files/cockpit-networkmanager-wip-2.noarch.rpm```

Want me to do that when merging?

**Comment by stefwalter** [comment]
> Want me to do that when merging?

Sure.

**Pull request closed without merging**
