### PR TITLE
bots: Put atomic back into rhel-7-8 image

### PR DESCRIPTION
**Pull request by marusak**
https://bugzilla.redhat.com/show_bug.cgi?id=1746750 was resolved

TODOs:
 * [x] image-refresh rhel-7-8
- [x] Fix tests in rhel-7.8 branch (introduced in https://github.com/cockpit-project/cockpit/commit/d5b547f6b01c874d16699b3d1e1ec2244369606b) - but we cannot test it - so one needs to land first :(

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-12755-20190910-063232/

**Comment by cockpituous** [comment]
image-refresh rhel-7-8 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-8-20190910-065656

**Comment by marusak** [comment]
Image refresh was successful. I triggered `rhel-7-8@cockpit-project/cockpit/rhel-7.8` as for general refresh, when green we can land this and then I'll send followup where I'll re-enable tests in rhel-7.8 branch.

**Comment by martinpitt** [comment]
[check-docker-storage](https://209.132.184.41:8493/logs/pull-12755-20190910-074040-9a273219-cockpit-project-cockpit-rhel-7.8-rhel-7-8/log.html#198-2) fails now, presumably it detects that "atomic" command is available again. But I suppose that's what you mean with the follow-up. Thank you!

**Comment by marusak** [comment]
>  presumably it detects that "atomic" command is available again. But I suppose that's what you mean with the follow-up

indeed, I opened https://github.com/cockpit-project/cockpit/pull/12757

**Pull request merged**
