### PR TITLE
Use our terminal implementation in vms

### PR DESCRIPTION
**Pull request by marusak**
Our console:
1. Is accessible
2. Does not use deprecated react methods
3. Supports copy and paste
4. Does not depend on old xterm.js
5. Is simpler to use

This would also hopefully unblock https://github.com/cockpit-project/cockpit/pull/12736 (hopefully because I hope that webpack is smart enough not to get dirty with serialConsole when we don't import it, but we import other components from the same package).
EDIT: - no, it does not unblock #12736 : 
```
ERROR in ./node_modules/@patternfly/react-console/dist/esm/SerialConsole/XTerm.js
Module not found: Error: Can't resolve 'xterm/lib/addons/fit/fit' in '/home/mmarusak/cockpit/cockpit1/node_modules/@patternfly/react-console/dist/esm/SerialConsole'
```
is there way how to stop compiling SerialConsole?

### CODE REVIEW

**Comment by marusak** [comment]
> You are missing a Closes

fixed

**Comment by martinpitt** [comment]
I agree to the change, but shouldn't this also drop @patternfly/react-console from package.json then?

**Comment by marusak** [comment]
> but shouldn't this also drop @patternfly/react-console from package.json then?

We still use the other two consoles from there.

**Comment by martinpitt** [comment]
@marusak: This needs a rebase due to the eslint SNAFU. 

I see, we still need it for the VncConsole. So does this actually make our webhook any smaller? (The SerialConsole was added to pf-react for our benefit, and by our team..)

**Comment by marusak** [comment]
> @marusak: This needs a rebase due to the eslint SNAFU.

There is already new version, I hoped it would pick it up already :) But I'll rebase.

> I see, we still need it for the VncConsole. So does this actually make our webhook any smaller?

I don't think so. I listed why our component is better than the one from patternfly in the commit message.
I was (and still not am) sure if we should use our component or try to make the patternfly one better (and then maintain it). It would be significant work to get their component to match ours, but I can do it. WDYT?

**Comment by martinpitt** [comment]
@marusak: Sorry for the misunderstanding -- as I said, I do agree to the change here to unify our terminals. I just wanted to give a little historic background. If nobody else uses SerialConsole, it should probably just be removed from PF-react then.

**Comment by marusak** [comment]
Selenium test does not work ideally. I'll make it a bit better

**Pull request merged**
