### PR TITLE
Don't distribute jshint due to its non-free license

### PR DESCRIPTION
**Pull request by stefwalter**

### CODE REVIEW

**Comment by stefwalter** [comment]
@larsu This is probably something you're interested in.

**Comment by dperpeet** [comment]
travis-ci failed on distcheck:
```
node_modules/requirejs/require.js
printf '#!/bin/sh\ntrue' > cockpit-0.100.x/node_modules/.bin/jshint
/bin/bash: cockpit-0.100.x/node_modules/.bin/jshint: Permission denied
make[3]: *** [dist-hook] Error 1
make[3]: Leaving directory `/home/travis/build/cockpit-project/cockpit/cockpit-0.100.x/_build'
make[2]: *** [distdir] Error 2
make[2]: Leaving directory `/home/travis/build/cockpit-project/cockpit/cockpit-0.100.x/_build'
make[1]: *** [dist] Error 2
make[1]: Leaving directory `/home/travis/build/cockpit-project/cockpit/cockpit-0.100.x/_build'
make: *** [distcheck] Error 1
```

**Comment by gruberjuliannama** [comment]
_modules/hawk/lib/browser.js line length is 3835 characters (>512)
E: cockpit source: source-is-missing node_modules/less/node_modules/request/node_modules/qs/dist/qs.js line length is 842 characters (>512)
E: cockpit source: source-is-missing node_modules/less/node_modules/request/node_modules/tough-cookie/lib/pubsuffix.js line length is 29445 characters (>512)
E: cockpit source: source-is-missing node_modules/less/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/formats.js line length is 1099 characters (>512)
E: cockpit source: source-is-missing node_modules/po2json/node_modules/gettext-parser/node_modules/encoding/node_modules/iconv-lite/encodings/sbcs-data-generated.js line length is 633 characters (>512)
E: cockpit source: source-is-missing node_modules/less/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property/is-property.js line length is 10942 characters (>512)
This one is a packaging bug. Shame on me. ;)

W: cockpit source: restriction-formula-with-debhelper-without-debhelper-version,,

**Comment by petervo** [comment]
@gruberjuliannama this PR was just closed. I'm unsure exactly what problem you are reporting is, but it would probably be better to open a new issue for it or comment here #4159.

**Pull request closed without merging**
