### PR TITLE
Image refresh for fedora-24

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for fedora-24 in process on host37-rack09.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-24-2016-05-09/

### CODE REVIEW

**Comment by cockpituous** [comment]
Image creation done.

**Comment by dperpeet** [comment]
@mvollmer LUKS still an issue, storage failures

**Comment by mvollmer** [comment]
I think the fix in storaged 2.5.1 for https://bugs.freedesktop.org/show_bug.cgi?id=85477 is bogus.  I'll try to make a better one.

**Comment by mvollmer** [comment]
> I think the fix in storaged 2.5.1 for https://bugs.freedesktop.org/show_bug.cgi?id=85477 is bogus. I'll try to make a better one.

This makes `check-storage-luks` pass: https://github.com/storaged-project/storaged/pull/61

**Comment by dperpeet** [comment]
replaced by #4423

**Pull request closed without merging**
