### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by martinpitt** [comment]
@Gundersanne, @marusak: Meh, seems image refreshes are still broken - this should have triggered *only* verify/fedora-testing (and the  externals), now it triggerd the standard tests which are everything *except* f-testing. Triggering that one manually.

**Comment by martinpitt** [comment]
bah, something in fedora-testing breaks kubernetes. Log says

    /usr/bin/etcd: line 1: syntax error near unexpected token `newline'
    /usr/bin/etcd: line 1: `!<arch>'

**Comment by martinpitt** [comment]
I raised a red flag in the corresponding bodhi update: https://bodhi.fedoraproject.org/updates/FEDORA-2019-33646297af

Still need to investigate this locally to give more details there.

**Comment by eclipseo** [comment]
Hi team,
The fedora 29 etcd in updates-testing seemed to have a binary corrupted. I have pushed a new update: https://bodhi.fedoraproject.org/updates/FEDORA-2019-185e366042 which will be available soon.
The binary seems to be valid this time. Please retest with this new update.

**Comment by martinpitt** [comment]
@eclipseo : Thanks! Closing this PR to let the bots create a new image.

**Pull request closed without merging**
