### PR TITLE
package.json: Update patternfly-react package dependency

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "patternfly-react": "2.39.7",
pkg/kdump/kdump-view.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/lib/cockpit-components-file-autocomplete.jsx:import { FormGroup, HelpBlock, TypeAheadSelect } from "patternfly-react";
pkg/lib/cockpit-components-inline-notification.jsx:import { Alert } from 'patternfly-react';
pkg/lib/cockpit-components-modifications.jsx:import { Button, Modal, Nav, NavItem, TabContent, TabPane, TabContainer } from 'patternfly-react';
pkg/lib/cockpit-components-table.jsx:        // We need the following because of: https://github.com/patternfly/patternfly-react/issues/3090
pkg/machines/app.jsx:import { ToastNotificationList, ToastNotification } from 'patternfly-react';
pkg/machines/components/aggregateStatusCards.jsx:} from 'patternfly-react';
pkg/machines/components/create-vm-dialog/createVmDialog.jsx:import { Button, FormGroup, HelpBlock, Modal, OverlayTrigger, Tooltip, TypeAheadSelect } from 'patternfly-react';
pkg/machines/components/deleteDialog.jsx:import { Modal, Button } from 'patternfly-react';
pkg/machines/components/deleteResource.jsx:import { Button, Modal, OverlayTrigger, Tooltip } from 'patternfly-react';
pkg/machines/components/diskAdd.jsx:import { Button, Modal } from 'patternfly-react';
pkg/machines/components/diskEdit.jsx:import { Button, Modal } from 'patternfly-react';
pkg/machines/components/networks/createNetworkDialog.jsx:import { Button, FormGroup, HelpBlock, Modal } from 'patternfly-react';
pkg/machines/components/networks/network.jsx:import { Button } from 'patternfly-react';
pkg/machines/components/nicAdd.jsx:import { Modal, Button } from 'patternfly-react';
pkg/machines/components/nicEdit.jsx:} from 'patternfly-react';
pkg/machines/components/storagePools/createStoragePoolDialog.jsx:import { Button, FormGroup, HelpBlock, Modal } from 'patternfly-react';
pkg/machines/components/storagePools/storagePool.jsx:import { Button, Tooltip, OverlayTrigger, UtilizationBar } from 'patternfly-react';
pkg/machines/components/storagePools/storagePoolDelete.jsx:import { Button, Modal, OverlayTrigger, Tooltip } from 'patternfly-react';
pkg/machines/components/storagePools/storageVolumeCreate.jsx:import { Button, Modal, OverlayTrigger, Tooltip } from 'patternfly-react';
pkg/machines/components/storagePools/storageVolumeDelete.jsx:} from 'patternfly-react';
pkg/machines/components/vcpuModal.jsx:import { Button, Modal } from 'patternfly-react';
pkg/machines/components/vm/bootOrderModal.jsx:} from 'patternfly-react';
pkg/machines/components/vm/memoryModal.jsx:} from 'patternfly-react';
pkg/machines/components/vmDisksTab.jsx:import { Button } from 'patternfly-react';
pkg/machines/components/warningInactive.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/machines/machines.less:// For patternfly-react and @patternfly/react-console
pkg/networkmanager/firewall.jsx:} from "patternfly-react";
pkg/packagekit/history.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/packagekit/updates.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/storaged/dialog.jsx:import { OverlayTrigger, Tooltip, TypeAheadSelect } from "patternfly-react";
pkg/storaged/storage-controls.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/systemd/hwinfo.jsx:import { Alert, Button, ListView, Modal, OverlayTrigger, Tooltip } from 'patternfly-react';
pkg/systemd/service-details.jsx:import { Button, Modal, OverlayTrigger, Tooltip, DropdownKebab, MenuItem } from 'patternfly-react';
pkg/systemd/services.jsx:import { Tabs, Tab } from 'patternfly-react';
```

**Comment by marusak** [comment]
ech, when I just edited package.json and ran `autogen && make` it worked just fine. Then I noticed all builds in tests fail so I did `git clean -dfx && autogen && make` and now it fails also locally :(

**Comment by marusak** [comment]
Needed to update also `react-bootstrap`. Did that and pushed here.
I checked for visual regressions and noticed a few, but then realized they come from PR that was removing duplicate css :) (like height of lines in VM page, services table has borders...)
This possibly may have some issues with functionality, so lets get tests properly green.
And FINALLY it should remove those deprecated warning about react lifecycle methods :)

**Comment by martinpitt** [comment]
Only [104 failures](https://209.132.184.41:8493/logs/pull-13110-20191107-161111-946a5b0b-cockpit-project-cockpit--fedora-coreos/log.html), easy peasy! :-)

**Comment by martinpitt** [comment]
Tired of retrying [testLibvirt](https://209.132.184.41:8493/logs/pull-13106-20191107-192727-1d8614c1-cockpit-project-cockpit--fedora-30/log.html#219-2). @skobyda , can you please have a look what fails here? This has been pretty persistent in the last week or two.

**Comment by skobyda** [comment]
Oh testLibvirt flake was not fixed :( . I'm gonna try to debug that all over again :(

**Pull request merged**
