### PR TITLE
Make tests pass on Fedora Rawhide

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
Depends on #2430.

**Comment by mvollmer** [comment]
check-accounts and check-roles also suffer from https://bugzilla.redhat.com/show_bug.cgi?id=1225957

**Comment by mvollmer** [comment]
Let's have one more good shot at fixing https://bugzilla.redhat.com/show_bug.cgi?id=1225957.

**Comment by mvollmer** [comment]
The network manager workarounds should not be needed.

**Comment by mvollmer** [comment]
Blocked by https://bugzilla.redhat.com/show_bug.cgi?id=1225957.

**Comment by mvollmer** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1232411 is fixed, so let's make new images and then remove workarounds as appropriate.

**Comment by mvollmer** [comment]
Bootstrapping Rawhide via virt-install doesn't seem to be the right approach.  This very frequently doesn't work, either because the needed images are not on the server temporarily, or the packages in the repo have temporarily broken dependencies.  I think this is all fair game for Rawhide, and we should not rely on virt-install succeeding.

I'll try upgrading f22 to rawhide instead.

**Comment by stefwalter** [comment]
I wonder if we should give up on rawhide, and instead test against the two latest branches of Fedora, including the one in development. That would be f22 and f23 right now.

**Comment by mvollmer** [comment]
> I wonder if we should give up on rawhide, and instead test against the two latest branches of Fedora, including the one in development. That would be f22 and f23 right now.

That probably makes more sense.  I'll also ask around for opinions.

**Comment by mvollmer** [comment]
Let's not try to make the tests pass on Rawhide.  Let's just monitor the failures.

**Pull request closed without merging**
