### PR TITLE
Network: Show all the things

### PR DESCRIPTION
**Pull request by mvollmer**
This works pretty well, actually, but needs more testing.

### CODE REVIEW

**Comment by stefwalter** [comment]
Looks like this is missing integration tests.

**Comment by mvollmer** [comment]
> Looks like this is missing integration tests.

Yes, we can probably make a tun device and check that it shows up and can be configured.

**Comment by mvollmer** [comment]
Added integration test.

**Comment by stefwalter** [comment]
Related failure on centos-7

```
# testOther (check_networking.TestNetworking)
#
Error: Failed to add/activate new connection: Device class NMDeviceTun had no complete_connection method
Wrote TestNetworking-testOther-FAIL.png
Journal extracted to TestNetworking-testOther-10.111.112.119-FAIL.log
not ok 94 testOther (check_networking.TestNetworking) duration: 25s
Traceback (most recent call last):
  File "./verify/check-networking", line 305, in testOther
    m.execute("nmcli --wait 0 dev con %s" % iface)
  File "/build/cockpit/test/common/testvm.py", line 403, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'nmcli --wait 0 dev con tun0' returned non-zero exit status 4
```

**Comment by stefwalter** [comment]
Related failure on fedora-24:

```
# testBasic (check_networking.TestNetworking)
#
52:54:00:9e:00:F2 -> ens6
52:54:00:9e:00:F2 -> ens6
> Hiding unmanaged interface: lo
Wrote TestNetworking-testBasic-FAIL.png
Journal extracted to TestNetworking-testBasic-10.111.112.244-FAIL.log
not ok 16 testBasic (check_networking.TestNetworking) duration: 117s
Traceback (most recent call last):
  File "./verify/check-networking", line 171, in testBasic
    wait(lambda: "mtu 1400" in m.execute("ip link show %s" % iface))
  File "/build/cockpit/test/common/testlib.py", line 1111, in wait
    raise Error(msg or "Condition did not become true.")
Error: Condition did not become true.
```

**Comment by mvollmer** [comment]
> Related failure on fedora-24

I can't reproduce this locally.  I might be unrelated after all.

**Comment by mvollmer** [comment]
> Related failure on centos-7 and rhel-7 and fedora-atomic

NetworkManager is too old and doesn't support "tun" devices on these OSes.

**Comment by stefwalter** [comment]
Needs a rebase.

**Comment by mvollmer** [comment]
Rebased.

**Pull request closed without merging**
