### PR TITLE
containers: Use fedora 24 as the base image

### PR DESCRIPTION
**Pull request by petervo**

### CODE REVIEW

**Comment by petervo** [comment]
bot: Image refresh for fedora-24

**Comment by cockpituous** [comment]
Image creation for fedora-24 in process on cockpit-9.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-24-40ca6444560920b2d496f81a41951f9b4eab4de2/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by petervo** [comment]
bot: Image refresh for fedora-testing

**Comment by cockpituous** [comment]
Image creation for fedora-testing in process on cockpit-8.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-testing-40ca6444560920b2d496f81a41951f9b4eab4de2/

**Comment by cockpituous** [comment]
Image creation failed.

**Pull request closed without merging**
