### PR TITLE
doc: Fix regressions that made building guide too noisy

### PR DESCRIPTION
**Pull request by stefwalter**
The Makefile for building the guide respected the V=1 and automake
silent rules. Fix the regression introduced in #5834

CC @dperpeet

### CODE REVIEW

**Comment by martinpitt** [comment]
I get why we'd replace `mv` with `$(MV)`, but what difference does it make to use `&& \` instead of separate commands? Logically it should be the same, and if we don't want to see the commands run they should be prefixed with `@` (but ISTM that it's much more useful to actually do see the commands in the build log).

**Comment by mvollmer** [comment]
@martinpitt, the difference is the $(V_COPY) prefix, for example, which produces different output for `make V=1` vs  `make V=0`.

**Comment by stefwalter** [comment]
@mvollmer Answered the question. In many cases these multiple commands are logically a single command, but require the intermediate tmp file + move in order to not race in parallel make scenarios.

**Comment by martinpitt** [comment]
@mvollmer: Yes, as I wrote I do get the `$(cmd)` stuff -- I don't get why we need these ugly long chained `&& \` lines, as that should make no difference and only makes it harder to see in the log which of the five chained commands actually failed.

**Comment by stefwalter** [comment]
> @mvollmer: Yes, as I wrote I do get the $(cmd) stuff -- I don't get why we need these ugly long chained && \ lines, as that should make no difference and only makes it harder to see in the log which of the five chained commands actually failed.

But when you want to do that, you use ```make V=1``` to also see the command lines. That's what the test runners do so the logs are fully there.

**Comment by stefwalter** [comment]
Or you can use ```$(V_XXXX)``` or ```$(AM_V_GEN)``` or similar if you would really like to see the blow by blow of each part of the command.

In addition I believe @dperpeet's changes should not be during build, but during check anyway. I'll do a follow up for that as well.

**Comment by stefwalter** [comment]
I've added more commits to cleanup the Makefile further, use ```check-local::``` target appropriately, and remove duplicated rules. However the intent still remains that we have ```$(AM_V_GEN)``` and ```$(V_COPY)``` for silent building on each logical command.

**Pull request closed without merging**
