### PR TITLE
bridge: Invalidate value cache in metrics channel as necessary

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by stefwalter** [comment]
So this is a work around right. The real bug is that one can lose information whenever a meta message is sent?

**Comment by mvollmer** [comment]
> So this is a work around right. The real bug is that one can lose information whenever a meta
> message is sent?

Yeah.  We could set a flag and then be more careful about finding the instances in the old value.  Good point.

**Comment by stefwalter** [comment]
I'm working on consolidating the derive code (delta and rate) into the CockpitMetrics base class. Should i handle this then?

**Comment by mvollmer** [comment]
> I'm working on consolidating the derive code (delta and rate) into the CockpitMetrics base class. Should i handle this then?

Yes, please.

**Pull request closed without merging**
