### PR TITLE
shell: Use new patternfly style sidebar

### PR DESCRIPTION
**Pull request by stefwalter**

### CODE REVIEW

**Comment by stefwalter** [comment]
screenshot from 2015-03-04 09 40 35

**Comment by stefwalter** [comment]
@andreasn FYI, this commit uses the new patternfly for the sidebar. The design is here:

https://www.patternfly.org/wp-content/uploads/patternfly/tests/tab.html#

**Comment by stefwalter** [comment]
This doesn't yet implement the tools expander: #1868

**Comment by andreasn** [comment]
:+1:

**Pull request closed without merging**
