### PR TITLE
test: Add gdb to debian test image

### PR DESCRIPTION
**Pull request by petervo**

### CODE REVIEW

**Comment by petervo** [comment]
bot: Image refresh for debian-unstable

**Comment by cockpituous** [comment]
Image creation for debian-unstable in process on host32-rack06.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-unstable-a1111eaf095bc80bb011dd8bf890afbfb464f4c3/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by petervo** [comment]
bot: Image refresh for debian-unstable

**Comment by cockpituous** [comment]
Image creation for debian-unstable in process on host37-rack09.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-unstable-a1111eaf095bc80bb011dd8bf890afbfb464f4c3/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by dperpeet** [comment]
bot: Image refresh for debian-unstable

**Comment by cockpituous** [comment]
Image creation for debian-unstable in process on host37-rack09.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-unstable-a1111eaf095bc80bb011dd8bf890afbfb464f4c3/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by petervo** [comment]
bot: Image refresh for debian-unstable

**Comment by cockpituous** [comment]
Image creation for debian-unstable in process on host32-rack06.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-unstable-a1111eaf095bc80bb011dd8bf890afbfb464f4c3/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-debian-unstable-a1111eaf095bc80bb011dd8bf890afbfb464f4c3

**Pull request closed without merging**
