### PR TITLE
Move VM/machine specific files and code from test/common to bots

### PR DESCRIPTION
**Pull request by martinpitt**
These commits clean up the symlinks in bots/machines/, which make it harder (and error prone) to re-use cockpit's test machinery in third-party modules. After landing this, we can also clean up the symlink-to-real-files mangling from bots/make-checkout.

As this changes the bot scripts, I will rebuild one image for each respective debian.bootstrap/virt-builder-fedora/virt-install-fedora script.

 * [x] image-refresh debian-stable
 * [x] image-refresh centos-7
 * [x] image-refresh fedora-27

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-k37dx.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8595-20180212-102424/

**Comment by martinpitt** [comment]
As git isn't clever enough to meaningfully display a diff for the moved test/common/testvm.py to bots/machines/testvm.py, here it is for convenience:

```diff
--- test/common/testvm.py	2018-02-12 11:16:53.547515344 +0100
+++ bots/machine/testvm.py	2018-02-12 11:17:01.706613561 +0100
@@ -39,7 +39,8 @@
 # Images which are Atomic based
 ATOMIC_IMAGES = ["rhel-atomic", "fedora-atomic", "continuous-atomic"]
 
-LOCAL_DIR = os.path.dirname(__file__)
+BOTS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
+TEST_DIR = os.path.join(os.path.dirname(BOTS_DIR), "test")
 
 # based on http://stackoverflow.com/a/17753573
 # we use this to quieten down calls
@@ -509,7 +510,7 @@
             cmd += [ "-q" ]
 
         def relative_to_test_dir(path):
-            return os.path.join(LOCAL_DIR, "..", path)
+            return os.path.join(TEST_DIR, path)
         cmd += map(relative_to_test_dir, sources)
 
         cmd += [ "%s@[%s]:%s" % (self.ssh_user, self.ssh_address, dest) ]
@@ -525,7 +526,7 @@
         assert self.ssh_address
 
         self._ensure_ssh_master()
-        dest = os.path.join(LOCAL_DIR, "..", dest)
+        dest = os.path.join(TEST_DIR, dest)
 
         cmd = [
             "scp", "-B",
@@ -550,7 +551,7 @@
         assert self.ssh_address
 
         self._ensure_ssh_master()
-        dest = os.path.join(LOCAL_DIR, "..", dest)
+        dest = os.path.join(TEST_DIR, dest)
 
         cmd = [
             "scp", "-B",
@@ -601,7 +602,7 @@
         return int(self.execute("{ (%s) >/var/log/%s 2>&1 & }; echo $!" % (shell_cmd, log_id)))
 
     def _calc_identity(self):
-        identity = os.path.join(LOCAL_DIR, "identity")
+        identity = os.path.join(BOTS_DIR, "machine", "identity")
         os.chmod(identity, 0o600)
         return identity
 
@@ -943,14 +944,14 @@
         if "/" in image:
             self.image_file = image = os.path.abspath(image)
         else:
-            self.image_file = os.path.join(LOCAL_DIR, "..", "images", image)
+            self.image_file = os.path.join(TEST_DIR, "images", image)
             if not os.path.lexists(self.image_file):
-                self.image_file = os.path.join(LOCAL_DIR, "..", "..", "bots", "images", image)
+                self.image_file = os.path.join(BOTS_DIR, "images", image)
         (image, extension) = os.path.splitext(os.path.basename(image))
 
         Machine.__init__(self, image=image, **args)
 
-        base_dir = os.path.join(LOCAL_DIR, "..", "..")
+        base_dir = os.path.dirname(BOTS_DIR)
         self.run_dir = os.path.join(os.environ.get("TEST_DATA", base_dir), "tmp", "run")
 
         self.virt_connection = self._libvirt_connection(hypervisor = "qemu:///session")
@@ -1010,7 +1011,7 @@
             "cpus": self.cpus,
             "memory_in_mib": self.memory_mb,
             "drive": image_to_use,
-            "iso": os.path.join(LOCAL_DIR, "cloud-init.iso"),
+            "iso": os.path.join(BOTS_DIR, "machine", "cloud-init.iso"),
         }
 
         if os.path.exists("/dev/kvm"):
@@ -1107,7 +1108,7 @@
         if "/" in image:
             image_file = os.path.abspath(image)
         else:
-            image_file = os.path.join(LOCAL_DIR, "..", "..", "bots", "images", image)
+            image_file = os.path.join(BOTS_DIR, "images", image)
         if not os.path.exists(image_file):
             try:
                 subprocess.check_call([ "image-download", image_file ])

```

**Comment by cockpituous** [comment]
image-refresh fedora-26 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-26-20180212-111111

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-k37dx.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8595-20180212-111111/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-v27b0.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8595-20180212-111111/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-stable-20180212-114444

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-3gm3q.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8595-20180212-114545/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20180212-122525

**Comment by martinpitt** [comment]
Images rebuilt, I pushed their commits and also added a Closes #.

**Comment by martinpitt** [comment]
fedora-26 rebuild clashes with #8590, so let's rebuild fedora-27 instead.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-pgzb4.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8595-20180212-162626/

**Comment by cockpituous** [comment]
image-refresh fedora-27 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-27-20180212-170909

**Pull request merged**
