### PR TITLE
test: selenium, changes name of created files via terminal tab to mor…

### PR DESCRIPTION
**Pull request by jscotka**
in some testing env this causes failing, because there exists files like /tmp/test* so that this cause false issues.

### CODE REVIEW

**Comment by stefwalter** [comment]
Looks like it's hanging here?

```
Traceback (most recent call last):
  File "./avocado/run-tests", line 256, in <module>
    sys.exit(main())
  File "./avocado/run-tests", line 250, in main
    if run_avocado(opts.tests, opts.verbosity, opts.browser, opts.download_logs):
  File "./avocado/run-tests", line 187, in run_avocado
    success = run_avocado_tests(machine, avocado_tests, env=env)
  File "./avocado/run-tests", line 122, in run_avocado_tests
    tap_output(machine)
  File "./avocado/run-tests", line 70, in tap_output
    print machine.execute(command="cat " + test_log, quiet=True)
IOError: [Errno 11] Resource temporarily unavailable
```

**Comment by jscotka** [comment]
This bug is strange, and it seems that machine. execute command return strange error. do @dperpeet think that machine.execute is okay to return this error, or machine.execute should handle it and return some better error? It is possible that machine is somehow disconnected, or down.
I tried to workaround that by error handling inside run-tests, but from my POV it should be fixed inside machine class

**Comment by stefwalter** [comment]
This is about EAGAIN handling. likely machine.execute() in testlib.py doesn't do it properly.

**Comment by jscotka** [comment]
Yes @stefwalter , it seems like that. So although I workarounded that it for now in run-test, it is better to have proper log, that hang, and some IOerror. We should fix it in machine execute too, probably not in this PR

**Pull request closed without merging**
