### PR TITLE
bots: Put back golang into rhel/centos-7 images

### PR DESCRIPTION
**Pull request by martinpitt**
We still need these for running builds/tests for the stable rhel-7.x
branches.

 * [x] image-refresh rhel-7-7
 * [x] image-refresh centos-7

### CODE REVIEW

**Comment by martinpitt** [comment]
Example failure from PR #12344: https://209.132.184.41:8493/logs/pull-12344-20190717-094040-b5aa78f7-verify-rhel-7-7/log

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-01.
Log: https://209.132.184.41:8493/logs/image-refresh-12351-20190717-140000/

**Comment by cockpituous** [comment]
image-refresh rhel-7-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-7-20190717-143232

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-12351-20190717-143333/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20190717-155757

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://209.132.184.41:8493/logs/image-refresh-12351-20190717-143333/

**Pull request merged**
