### PR TITLE
test: Don't connect additional interfaces to the test network

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
Another try.  Let's leave cockpit1 (almost) completely alone.

**Comment by dperpeet** [comment]
On rhel-7 and fedora-25 the checkpointing test failed... I think this may be related as it seems a fairly stable test.

**Comment by mvollmer** [comment]
> On rhel-7 and fedora-25 the checkpointing test failed... I think this may be related as it seems a fairly stable test.

Yes, those tests need some changes.

**Comment by mvollmer** [comment]
This didn't help.

**Pull request closed without merging**
