### PR TITLE
Use eslint for .jsx and .es6 files

### PR DESCRIPTION
**Pull request by mareklibra**
Since new JS introduced to Cockpit code follows ES6 syntax, this PR is focused on definition of codestyle.

ESLint is used for both `.jsx` and `.es6` files.
Standard rules for React and ES6 are set.

The eslint is still executed as `webpack preloader` to enforce checking.

Convenient scripts are added to the `package.json` to either `run`
or automatically `fix` the issues via:
```
  npm run eslint
  npm run eslint:fix
```

__Temporarily__ only, rules not met in recent codebase are disabled and listed in the `.eslintrc.json`.
Some of them might point to bugs.

I don't think we need to strictly adopt all rules from the "standard" sets since Cockpit is a mixture of various JavaScript styles already. But majority of them make sense.

The boundary is about to be set within this PR discussion.
As a staring point, I set those which make sense to me explicitly to `error` or `warn`. Once agreed, they can be "unlisted" from `.eslintrc.json` so enforced by default.

Once agreed, fixes to meet the new rules will be provided as additional commits to this PR.
Some of them can be performed automatically, some will need manual inspection.

### CODE REVIEW

**Comment by mareklibra** [comment]
Since big amount of lines is expected to be affected by fixes meeting the new rules, we can merge the `eslint` for `.jsx` and `.es6` with all conflicting rules disabled (means those already identified in recent https://github.com/cockpit-project/cockpit/pull/9000/commits/9f2bdccbfe62345edef5cc1c9182367da4e91adf).

So recent codebase will stay as is and passing eslint.

Within later PRs, selected rules can be re-enabled one-by-one along related fixes.

**Comment by martinpitt** [comment]
I think long term it's beneficial to enable these, to get a more consistent code style. But indeed it might be better to enable them one by one, with the corresponding code changes, to make things easier to review. We might also want to disable some of them entirely, like `curly` - this is an example of a rule that just blows up the code unnecessarily without improving readability.

Right now this causes all builds to fail due to an enormous list of eslint violations. Can we put this into a global "reporting" mode, or do all the rules need to be put into "warn" mode?

**Comment by mareklibra** [comment]
I can set all the rules to `off`. Using `warn` at this state would cause the build logs unreadable - too many violations.

**Comment by martinpitt** [comment]
> Can we put this into a global "reporting" mode

On second thought we don't actually want this, as it would get in the way once we actually start to fix these issues.

**Comment by mareklibra** [comment]
All conflicting rules are set to `off`.
As an example, commit enabling and fixing `no-multiple-empty-lines` is added.

**Pull request closed without merging**
