### PR TITLE
machines: change AddDisk dialog

### PR DESCRIPTION
**Pull request by anyaharter97**
change unordered list to radio buttons for selecting "Create New" or "Use Existing"

fix vertical alignment of labels

update check-machines test to represent changes

Follow-up for #9166

Part of #9681 fix

### CODE REVIEW

**Comment by anyaharter97** [comment]
radiobuttonsandverticalalignment

**Comment by garrett** [comment]
Thanks! That looks better! :+1: 

Regarding alignment; I found that there's a problem in Bootstrap, which PatternFly uses, which Cockpit uses. We were having similar issues with other PRs, including the LUKS PR @ #9465.

I've investigated it, figured out a fix that works cross-browser, and have filed the issue upstream @ https://github.com/patternfly/patternfly/issues/1122. (There are bunch of examples demos of fixes.)

Meanwhile, I'll look to see about incorporating this fix across all of Cockpit.

Could you remove the local alignment changes in this PR please? Thanks!

**Comment by anyaharter97** [comment]
I'm not entirely sure if I did it right but I think I may have updated the pull request? Can you check it out?

**Comment by martinpitt** [comment]
Tests are green, and CSS refinements can be done in a follow-up. @garrett is on PTO now, so let's not block this on him. Thanks!

**Pull request merged**
