### PR TITLE
Use qcow2 images instead of tarballs and kernel/initrd/root.

### PR DESCRIPTION
**Pull request by mvollmer**
Continuation of #2283.

### CODE REVIEW

**Comment by mvollmer** [comment]
I'll merge this once we have some smoke testing from hubbot.

**Comment by stefwalter** [comment]
This pull request breaks tracing the VM boot. Is that intentional?

**Comment by mvollmer** [comment]
> This pull request breaks tracing the VM boot. Is that intentional?

I am assuming so, but it is not completely bad.  You can't see the kernel boot messages with "./check-dbus -t" anymore, for example, but you can see them with "./vm-run -s".

Seeing the kernel boot messages was unreliable on f22 as we know and rhel-7 has never shown them, I think, even without this PR.

**Comment by stefwalter** [comment]
I see it as a big drawback to debugging. We're just piling on more failure modes into our tests without actually resolving anything for real.

That said, the current situation is really bad, so if this helps us get out of that, I guess it's worth it.

**Comment by mvollmer** [comment]
> That said, the current situation is really bad, so if this helps us get out of that, I guess it's worth it.

It's a simplification and thus a step in the right direction, I would say.  I could say that we lose a feature that has stopped working anyway.  Debugging via a real console in a window should be feasible and closer to reality.

**Pull request closed without merging**
