### PR TITLE
bots: Move ipa, avocado, and selenium images to Fedora 26

### PR DESCRIPTION
**Pull request by martinpitt**
Fedora 25 is EOL now.

 * [x] update avocado test name (PR #8116)
 * [x] image-refresh ipa
 * [x] image-refresh selenium
 * [x] image-refresh fedora-26

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-4qmbt.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-151010/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-151010/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-6pq8f.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-152929/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-khkrv.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-152929/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-6pq8f.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-160505/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-7pcvn.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-160505/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-3pt25.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-160606/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-160606/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-45fsm.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-162626/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-khkrv.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-162626/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-162626/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-2dgd3.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-163232/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-7pcvn.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-163232/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-163232/

**Comment by martinpitt** [comment]
image refreshes on the bots fail on curl trying to download the virt-builder image, and a local fedora-27 image refresh for adding avocado fails due to:
```
+ npm -g install phantomjs-prebuilt
/usr/bin/phantomjs -> /usr/lib/node_modules/phantomjs-prebuilt/bin/phantomjs
[...]
chmod failed: phantomjs was not successfully copied to /usr/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
```
I've seen a similar error when trying to build a fedora-27 container with it (bumping cockpit/tests).

**Comment by petervo** [comment]
Why are we jumping to 27 instead of sticking with 26?

**Comment by martinpitt** [comment]
It's not "sticking" with F26, these images are currently based on F25 (which is EOL). Moving to the latest release makes more sense to me, then we don't need to do another version update in half a year again.

**Comment by petervo** [comment]
stick was the wrong word, but I don't want to jump 2 versions. Keeping these on f26 increases our regularly run test coverage to include f26 without having extra runs and gives us more time to finish the move away from phantomjs.

**Comment by martinpitt** [comment]
Hm, ok; I'll change it to F26 then.

**Comment by petervo** [comment]
I should clarify i was talking about avocado selenium, I don't mind bumping ipa and openshift to f27.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-45fsm.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-203838/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-3pt25.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-203838/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-203838/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-1rdk9.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-205656/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-khkrv.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-205656/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-4qmbt.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-205656/

**Comment by cockpituous** [comment]
image-refresh selenium done: https://github.com/cockpituous/cockpit/commits/image-refresh-selenium-20171117-214444

**Comment by cockpituous** [comment]
image-refresh in progress on verifymachine4.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-213838/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171117-213838/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-gqv88.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-171111/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-jsls4.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-171111/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-swfm4.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-171111/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-171111/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-45fsm.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-174040/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-6pq8f.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-174040/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-4qmbt.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-174040/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-174040/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-7pcvn.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-193333/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-4qmbt.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-193333/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-193333/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-998rh.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-195656/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-195656/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-3pt25.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-201212/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-7pcvn.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-201212/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-2dgd3.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-201212/

**Comment by cockpituous** [comment]
image-refresh fedora-26 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-26-20171118-204646

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-hplv9.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-211818/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-2213v.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-211919/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-jl1pt.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-211919/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-gfg50.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-211919/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-211919/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-1rdk9.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-220404/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-gqv88.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-220202/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-hsgq6.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-220404/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-xpb0f.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-220202/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-7pcvn.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-220404/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-wq58b.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-220505/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171118-220505/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-v1mpw.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171119-090303/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8115-20171119-090303/

**Comment by martinpitt** [comment]
I'll handle openshift in a separate PR, image building causes some trouble.

**Comment by martinpitt** [comment]
All green, dropping needswork.

**Pull request closed without merging**
