### PR TITLE
bots: Install unattended-upgrades on Debian/Ubuntu images

### PR DESCRIPTION
**Pull request by martinpitt**
In preparation for implementing automatic update support on Debian.

 * [x] image-refresh debian-stable
 * [x] image-refresh debian-testing
 * [x] image-refresh ubuntu-1804
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-4vscg.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10891-20181230-075858/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-stable-20181230-082222

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-rrbh7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10891-20181230-082020/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-testing-20181230-084646

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-4wkwn.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10891-20181230-084848/

**Comment by cockpituous** [comment]
image-refresh ubuntu-1804 done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-1804-20181230-111818

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-hrn3p.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10891-20181230-112222/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-stable-20181230-114949

**Comment by martinpitt** [comment]
@larskarlitski : This is utterly trivial, if you have a second for approving I'd appreciate. (Of course I'll wait for the last test to go green). Guten Rutsch! :tada:

**Pull request merged**
