### PR TITLE
services: Enable restarting static services

### PR DESCRIPTION
**Pull request by marusak**
If static service is active then enable stopping/restarting and
reloading.

@mvollmer does this make more sense for you?

### CODE REVIEW

**Comment by martinpitt** [comment]
LGTM, but leaving review to @mvollmer.

**Comment by mvollmer** [comment]
> does this make more sense for you?

Yes, it does, but let's also hear from @garrett.

**Comment by martinpitt** [comment]
@garrett, can you please confirm?

**Comment by garrett** [comment]
Yeah, I _think_ this makes sense.

**Pull request merged**
