### PR TITLE
Remove some workarounds in tests

### PR DESCRIPTION
**Pull request by mvollmer**
Fingers crossed.

### CODE REVIEW

**Comment by stefwalter** [comment]
I don't see the minimum dependencies being bumped in configure.ac or tools/cockpit.spec. We should also draft an anouncement to cockpit-devel explaining bumping the required versions.

**Comment by mvollmer** [comment]
> I don't see the minimum dependencies being bumped in configure.ac or tools/cockpit.spec. We should also draft an anouncement to cockpit-devel explaining bumping the required versions.

This PR only removes workarounds in our tests, not in the production code.  (Except for gdbus-codegen).  So I think we don't need to bump versions (except for glib2).

**Comment by mvollmer** [comment]
Increased glib2 requirement to >= 2.39.1

**Comment by stefwalter** [comment]
@mvollmer Do you have a summary of operating systems we will no longer build on due to the increased glib2 requirement?

**Comment by mvollmer** [comment]
> @mvollmer Do you have a summary of operating systems we will no longer build on due to the increased glib2 requirement?

No... Fedora 21 has glib2 2.42.

Should we just keep the gdbus-codegen workaround?

**Comment by stefwalter** [comment]
What about RHEL, CentOS, Ubuntu, OpenSuSE, Arch?

I'm hesitant just to bump the glib dep without some data on what it means, especially since it's just a build workaround. Unless we're ready to do the research work, I would suggest keeping the workaround until we have time to make a more informed decision.

**Comment by mvollmer** [comment]
> I'm hesitant just to bump the glib dep without some data on what it means, especially since it's just a build workaround. 

Yes, very good.  I agree.

**Comment by mvollmer** [comment]
Left the gdbus-codegen workaround in place.

**Comment by stefwalter** [comment]
Thanks. I also don't think we should remove the ```src/ws``` workarounds, even in unit tests. People run these as part of their build ... and we don't want that to regress until we bump the glib2 dep.

**Comment by stefwalter** [comment]
Merged without the ```src/ws``` changes. Hope that's okay.

**Pull request closed without merging**
