### PR TITLE
Revert "tools: Require shadow-utils also on Fedora/RHEL"

### PR DESCRIPTION
**Pull request by lnussel**
This reverts commit 5eb6af26402d059b0d2f23ace45c8e1ee7b1524f.

### CODE REVIEW

**Comment by lnussel** [comment]
I think you misread the logic when removing the conditionals. `shadow-utils` does not exist on openSUSE. Meanwhile I've also submitted a change to the `shadow-utils` spec file in Fedora to provide a compat `shadow` symbol for compatibility. So as soon as that one is in `shadow-utils` can be replaced by `shadow`.

**Comment by Gundersanne** [comment]
This was probably the result of an overenthusiastic code removal session in #14585. Thank you for catching that :)

I on a related note, since you're using the cockpit spec file to build cockpit for suse, it might make sense to start testing on opensuse, wdyt?

**Review by Gundersanne — APPROVED** [review]

**Comment by lnussel** [comment]
> On a related note, since you're using the cockpit spec file to build cockpit for suse, it might make sense to start testing on opensuse, wdyt?

I don't know what that involves. I can't really keep up with development (I'm not assigned to this work) so I wouldn't want to become the bottleneck for anyone.

**Comment by Gundersanne** [comment]
> > On a related note, since you're using the cockpit spec file to build cockpit for suse, it might make sense to start testing on opensuse, wdyt?
> 
> I don't know what that involves. I can't really keep up with development (I'm not assigned to this work) so I wouldn't want to become the bottleneck for anyone.

So it wouldn't require actual development work on cockpit. Does cockpit on OpenSUSE have a maintainer? We'd mostly need a contact person (ideally the package maintainer?) in case we'd have questions or something very suse-specific was broken. Maybe long term we could also hook it into our release script somehow to make releasing it easier. It would mostly be about helping us maintain the suse-specific directives in the spec file (which you already seem to do :)).

Also we'd need some help in deciding which exact flavour/image to build a test image out of (probably tumbleweed but maybe there's a tiny cloud specific image for VMs?).

If you would like to discuss this I'm on freenode (nick croissanne), in the #cockpit channel there. Also happy to discuss it on one of the suse channels.

**Pull request merged**
