### PR TITLE
Changed label for adding ssh public key

### PR DESCRIPTION
**Pull request by abhishekgupta5**
Fix for #3454

### CODE REVIEW

**Comment by andreasn** [comment]
Thanks for picking this up and hacking on it so quickly, @abhishekgupta5 !

Sorry for being a bit unclear in the issue where the text would go.
I would suggest to keep the header of the dialog as "Add public key", but then make the authorized-keys-text text area have the placeholder tag "Paste the contents of your public ssh key file here" (here being that text field).

**Comment by abhishekgupta5** [comment]
@andreasn Exactly. In fact I was wondering that only. Let me get back to you with the needed

**Comment by andreasn** [comment]
17e87981cfd11490869665e81cb27cea2d4b11fa looks good.
4fc923b2302c0396e1b19a6de0c7fb6d98a2a446 still changes the dialog title in this pull request though.

**Comment by abhishekgupta5** [comment]
@andreasn  Yeah sorry, I mistakenly pulled from my local repo and merged. Corrected it in the latest commit

**Comment by andreasn** [comment]
Looks good, thanks!

**Comment by stefwalter** [comment]
Thanks! Merged into master. This will be part of Cockpit 0.92

**Comment by abhishekgupta5** [comment]
stefwalter, andreasn Thank you both for mentoring me on this bug :) Looking forward to more contributions

**Comment by stefwalter** [comment]
@abhishekgupta5 Thanks for contributing :+1:

**Pull request closed without merging**
