### PR TITLE
package.json: Update jquery to current 2.x version

### PR DESCRIPTION
**Pull request by martinpitt**
This is providing a nice bunch of bug fixes and keeps us closer to supported versions.

### CODE REVIEW

**Comment by petervo** [comment]
Why is welder using both jquery and react. Generally we've tried to avoid using both in the same package. Is there a way to get out of requiring jquery there?

**Comment by martinpitt** [comment]
@petervo: Not sure about the "why", it just uses it all over the place. I do think that we should get rid of it there. However, using a more current jQuery wouldn't be wrong for our existing cockpit components either.

The test failures reproduce the Network crash, the rest looks okay-ish.

**Comment by petervo** [comment]
But a change like this, bumping a major version is pretty risky from the cockpit side. Plus it's a violation of our backwards compatibility guarantee as we distribute jquery in base, again for backwards compatibility. 

So if we have to bring this in we need to either isolate it to the welder version only. Or we need to continue distributing a 2.x version in base.

**Comment by martinpitt** [comment]
> Plus it's a violation of our backwards compatibility guarantee as we distribute jquery in base

Indeed, I keep forgetting that we don't webpack jquery, but ship it as a separate file. Let's not do that then, instead I'll see to make welder work with 2.2 or even our 2.1. Would bumping to 2.2 be acceptable?

**Comment by martinpitt** [comment]
2.2.4 seems to work fine and not change API, so I changed this to move to 2.2.4 instead. Let's see what the tests have to say about that. In parallel I'll see to lowering welder to 2.x too.

**Comment by petervo** [comment]
This seems a lot safer to me. I think this should be good, but can you see if jquery has any documented backwards incompatibilities between 2.2 and 2.1?

**Comment by martinpitt** [comment]
@petervo: I went through the [2.2 release notes and changelog](http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/). There are tons of bug fixes, a few API additions (which should be fine). There are some potential API changes:

 * Remove workaround for IE6/7
 * Don’t expose jQuery.access
 * privatize internal domManip() function
 * privatize buildFragment() function

The last three have always been internal API only which was "accidentally" public (but not documented). I verified that we don't use any of these.

So this seems safe enough to me.

**Comment by petervo** [comment]
I agree, if tests pass i think we are good with this change.

**Pull request closed without merging**
