### PR TITLE
Fix TestStorageHidden.testHiddenLuks OOM, fix crash if block device lacks Encrypted interface

### PR DESCRIPTION
**Pull request by martinpitt**
This sometimes runs into out of memory errors with the default VM size. Split it out into its own test class and increase memory like we do in check-storage-{luks,resize}.

----

See https://cockpit-logs.us-east-1.linodeobjects.com/pull-18662-20230421-050018-6ed1ae43-rhel-8-9/log.html#341 and https://cockpit-logs.us-east-1.linodeobjects.com/pull-18662-20230421-054212-ae04049b-debian-testing/log.html#341

After fixing OOM, the [undefined ChildConfiguration still happens](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18686-20230421-194249-fd65ffa3-centos-8-stream/log.html#348-2)

### CODE REVIEW

**Comment by martinpitt** [comment]
@mvollmer tests are just barely starting, but do you have an opinion about this array_find() fix? do you think it's too broad, and you'd rather have the page crash and debug/fix the failure more locally? (Personally I think I'd rather make the pages mroe robust).

**Comment by martinpitt** [comment]
Hmm, [still crashed](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18686-20230421-085828-ccb2be9e-debian-testing/log.html#348-1) -- so my theory about what caused the crash was wrong.

**Comment by martinpitt** [comment]
I suppose that error means that it's trying to read the .ChildConfiguration property from undefined, instead of ChildConfiguration itself being undefined. So I figure it's rather the `crypto` or `client.blocks_crypto[block.path]` objects which are undefined. Anyway, let's just fix the OOM for now.

**Comment by martinpitt** [comment]
@mvollmer I fixed the crash now, so ready for review.

**Review by mvollmer — CHANGES_REQUESTED** [review]
LGTM, but the explanation for " storaged: Fix crash if crypto block device lacks ChildConfiguration attribute" is not accurate.  What is missing is not the ChildConfiguration property, but the whole "Encrypted" D-Bus interface for the object path of the block device.

That interface might well be missing because everything is damn asynchronous, but if it exists, it really should have the ChildConfiguration property.

**Review by mvollmer — DISMISSED** [review]

**Review by mvollmer — APPROVED** [review]

**Pull request merged**
