### PR TITLE
test: Support rhel4edge

### PR DESCRIPTION
**Pull request by marusak**

### CODE REVIEW

**Comment by marusak** [comment]
The last remaining one [test/verify/check-ws-bastion TestWsBastionContainer.testKeyLogin](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18282-20230206-102838-965812ba-rhel4edge-bots-4351/log.html).

**Comment by martinpitt** [comment]
* It's not SELinux.
 * `/id_bastion` aka. `$COCKPIT_SSH_KEY_PATH` is readable.
 * `ssh -vv -i /id_bastion admin@host.containers.internal` inside the container does not work either:
```
debug1: Next authentication method: publickey
debug1: Trying private key: /id_bastion
Enter passphrase for key '/id_bastion': 
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug2: we did not send a packet, disable method
debug1: Next authentication method: password
admin@host.containers.internal's password: 
```
... while sshd on the host doesn't log anything. When changing `LogLevel DEBUG` in /etc/ssh/sshd_config and `systemctl restart sshd`, I get:
```
sshd[6093]: debug1: userauth-request for user admin service ssh-connection method publickey [preauth]
sshd[6093]: debug1: attempt 1 failures 0 [preauth]
sshd[6093]: debug1: temporarily_use_uid: 1000/1000 (e=0/0)
sshd[6093]: debug1: trying public key file /var/home/admin/.ssh/authorized_keys
sshd[6093]: debug1: fd 5 clearing O_NONBLOCK
sshd[6093]: debug1: restore_uid: 0/0
sshd[6093]: Failed publickey for admin from 10.88.0.3 port 35088 ssh2: RSA SHA256:HZzc1b6gjZFMJ8v6h8W8r0v21LCTU57qTxN6VRvfx5I
```

 * `ssh -vv -i /root/id_bastion admin@localhost` on the host does not work either, so this is not an issue with cockpit or the container.
 * It works after this: `cat ~admin/.ssh/authorized_keys.d/bastion >> ~admin/.ssh/authorized_keys`

Ergo, rhel4edge does not support `~/.ssh/authorized_keys.d`. We can change that in the test of course, but I'd consider this a bug in rhel4edge (it seems to work fine in plain RHEL 9.1, after all). I am not actually sure where this is configured in ssh -- in Fedora 37 I don't see `authorized_keys.d` being mentioned explicitly in any  config file.

**Review by martinpitt — APPROVED** [review]
Thanks! `m.ostree_image` could be used in a lot of places, but not important enough to re-push. The TestAccounts failure is a known flake, feel free to retry.

**Comment by martinpitt** [comment]
I think @KKoukiou was looking into [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18282-20230208-150156-c4053286-fedora-37/log.html), retrying

**Pull request merged**
