### PR TITLE
bots: Update candlepin and ovirt images to latest CentOS 7

### PR DESCRIPTION
**Pull request by martinpitt**
Use centos-7.boostrap, which already picks the latest available
centos-7.x version. This will update them from 7.3 to 7.4.

 * [x] image-refresh candlepin
 * [x] image-refresh ovirt

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-3xzmh.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8695-20180223-083232/

**Comment by cockpituous** [comment]
image-refresh candlepin done: https://github.com/cockpituous/cockpit/commits/image-refresh-candlepin-20180223-092626

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-3xzmh.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8695-20180223-092626/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-jpw1d.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8695-20180223-092727/

**Comment by cockpituous** [comment]
image-refresh ovirt done: https://github.com/cockpituous/cockpit/commits/image-refresh-ovirt-20180223-100404

**Comment by martinpitt** [comment]
I pushed the refreshed images.

**Pull request merged**
