### PR TITLE
docker: Align the filter bar elements correctly

### PR DESCRIPTION
**Pull request by stefwalter**
This is a follow up to #5195. Missed committing this on my laptop.

### CODE REVIEW

**Comment by stefwalter** [comment]
debian-unstable check-machines issue fixed by #5222. All other tests have passed.

**Comment by dperpeet** [comment]
I think it looks better with 2px:
screenshot from 2016-10-25 10-54-18

**Comment by dperpeet** [comment]
not pixel perfect, but almost

**Comment by stefwalter** [comment]
Changed to 2px.

**Pull request merged**
