### PR TITLE
Image refresh for rhel-8-0

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-0
 * [x] image-refresh rhel-8-0

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-11879-20190520-200606/

**Comment by cockpituous** [comment]
image-refresh rhel-8-0 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-0-20190520-203939

**Comment by KKoukiou** [comment]
[testIpa failed](https://209.132.184.41:8493/logs/pull-11879-20190520-202626-12565b92-verify-rhel-8-0/log.html)

**Comment by marusak** [comment]
[ipa](https://209.132.184.41:8493/logs/pull-11879-20190520-230505-12565b92-verify-rhel-8-0/log.html) different tests. One more go, since in these two runs different tests failed.

**Pull request merged**
