### PR TITLE
test: add selenium tests for firewall page

### PR DESCRIPTION
**Pull request by jscotka**

### CODE REVIEW

**Comment by martinpitt** [comment]
Thanks! Looks ok, but please remove the f-string. Semaphore fails on it:
```
FAIL: tools/test-static-code 2 pyflakes test
        self.machine.execute(f"sudo firewall-cmd --remove-service={service}")
```
A simple `+` does fine here. :-)

**Comment by martinpitt** [comment]
[edge test](https://209.132.184.41:8493/logs/pull-12060-20190617-081919-8892f80e-selenium-edge/log.html) is a sea of red, retrying.

**Comment by martinpitt** [comment]
Still [two failures on edge](https://209.132.184.41:8493/logs/pull-12060-20190618-091515-8892f80e-selenium-edge/log.html), retrying.

**Comment by martinpitt** [comment]
Sorry @jscotka, the edge tests just keep [timing out](https://209.132.184.41:8493/logs/pull-12060-20190618-121818-8892f80e-selenium-edge/log.html) or failing.

**Comment by jscotka** [comment]
> Sorry @jscotka, the edge tests just keep [timing out](https://209.132.184.41:8493/logs/pull-12060-20190618-121818-8892f80e-selenium-edge/log.html) or failing.

I know probably where is problem. when selenium stops working. it is restarted, but cockpit machine has some setup done and there is not done proper cleanup, so that next round causes, that if some test does same setup, on the cockpit machine, it fails, because already set up, so that I have to restart also cockpit machine to clean state

**Comment by martinpitt** [comment]
@jscotka, can you please rebase this to current master? (Long story)

**Comment by martinpitt** [comment]
Force-pushed to rebase and squash the fixups.

**Comment by martinpitt** [comment]
One [chrome](https://209.132.184.41:8493/logs/pull-12060-20190621-205757-692707df-selenium-chrome/log.html) failure, retrying

**Pull request merged**
