### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for debian-testing in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-testing-2017-02-15/

### CODE REVIEW

**Comment by martinpitt** [comment]
"curl: (7) Failed to connect to file.rdu.redhat.com port 80: Connection timed out": looks like a flake, let's try again.

**Comment by martinpitt** [comment]
bot: Image refresh for debian-testing

**Comment by cockpituous** [comment]
Image creation for debian-testing in process on cockpit-10.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-testing-7f5d58a61816af4f9bc277c800ffe04638b098f8/

**Comment by cockpituous** [comment]
Image creation done.
Branch creation failed.

**Comment by dperpeet** [comment]
thanks for restarting, replaced by #5901

**Pull request closed without merging**
