### PR TITLE
Rework the login layout further

### PR DESCRIPTION
**Pull request by stefwalter**
Reworking the login layout so that it's more inline with what Patternfly recommends, and also what we need in order to add another option to the login screen.
    
 * The error messages are displayed above
 * Spinner is displayed in the login button
 * Login button is properly disabled
 * 'Other Options' aligned to the left
 * Login button is collapsed next to 'Other Options'
 * Line between sides is drawn properly

Depends on:

 * [x] #5520 
 * [x] #5510

### CODE REVIEW

**Comment by stefwalter** [comment]
Needs review from @petervo (for conversations) and @andreasn

**Comment by stefwalter** [comment]
screenshot from 2016-12-01 11-41-33
screenshot from 2016-12-01 11-42-40
screenshot from 2016-12-01 11-43-04
screenshot from 2016-12-01 11-43-12
screenshot from 2016-12-01 11-44-01
screenshot from 2016-12-01 11-44-18
screenshot from 2016-12-01 11-45-53
screenshot from 2016-12-01 11-45-59
screenshot from 2016-12-01 11-46-05

**Comment by andreasn** [comment]
"Cannot" instead of "Can not" stood out to me a bit, but it seems consistent with how we use it in the rest of Cockpit, so better to keep it "Cannot" for now

**Comment by andreasn** [comment]
The waiting spinner is usually outside the button in most other places, so perhaps best to keep it outside the button here too, and make the button insensitive.

**Comment by stefwalter** [comment]
> "Cannot" instead of "Can not" stood out to me a bit, but it seems consistent with how we use it in the rest of Cockpit, so better to keep it "Cannot" for now

This wording did not change. It was merely moved.

**Comment by stefwalter** [comment]
> The waiting spinner is usually outside the button in most other places, so perhaps best to keep it outside the button here too, and make the button insensitive.

There is no room to have it outside the button in the collapsed narrow width view.

**Comment by andreasn** [comment]
Patternfly specifies to also outline the field where the error happened.
http://www.patternfly.org/pattern-library/application-framework/login-page/

**Comment by stefwalter** [comment]
> Patternfly specifies to also outline the field where the error happened.

Linux authentication does not and should not tell users whether the login name, server name or password was the thing that was false. So I think a Linux login screen has an exception on this point.

**Comment by andreasn** [comment]
Makes sense.
Looks good to me in that case.

**Comment by stefwalter** [comment]
I'm open to follow ups that continue the work on the login screen. But I hope this is a big step in the right direction. Especially when #5522 is happening.

**Comment by stefwalter** [comment]
Rebased

**Comment by petervo** [comment]
For me the "Log In" text on the button stays visible while the spinner is running. Makes the button look a little weird. Other than that, i think this is good.

**Comment by stefwalter** [comment]
> For me the "Log In" text on the button stays visible while the spinner is running. Makes the button look a little weird. Other than that, i think this is good.

Good catch. Fixed.

**Pull request closed without merging**
