### PR TITLE
networking: Don't use "master" or "slave" in the code

### PR DESCRIPTION
**Pull request by mvollmer**
Use "group" and "member" instead.

### CODE REVIEW

**Comment by martinpitt** [comment]
These terms are a bit confusing IMHO. If I have a bond with `name` "bond0", which consists of two interfaces eth0 and eth1, and one of them (say, eth0) is the primary/default one -- then in the  old nomenclature, "bond0" is the name of the virtual interface, and that sounds like it would be the "group"; and eth0 and eth1 are the members. But is that really what master and slave were about? I thought that "master" was eth0 and "slave" was eth1?

If that is so, then maybe primary/secondary or default/fallback are more descriptive?

**Comment by mvollmer** [comment]
> These terms are a bit confusing IMHO. If I have a bond with `name` "bond0", which consists of two interfaces eth0 and eth1, and one of them (say, eth0) is the primary/default one -- then in the old nomenclature, "bond0" is the name of the virtual interface, and that sounds like it would be the "group"; and eth0 and eth1 are the members. But is that really what master and slave were about? I thought that "master" was eth0 and "slave" was eth1?
> 
> If that is so, then maybe primary/secondary or default/fallback are more descriptive?

No, bond0 is the master, and eth0 and eth1 are the slaves.

**Comment by mvollmer** [comment]
> No, bond0 is the master, and eth0 and eth1 are the slaves.

In our code and in the NM API, I can't say that the terms are used like that everywhere.

**Comment by martinpitt** [comment]
@mvollmer : Thanks; then this indeed makes much more sense and master/slave is even confusing. Still needs test adjustments, so not +1'ing yet.

**Comment by martinpitt** [comment]
@mvollmer: Still [some failures](https://logs.cockpit-project.org/logs/pull-14322-20200709-064802-aa7dd150-fedora-coreos/log.html#300-2)

**Comment by mvollmer** [comment]
Still some failures on the Debians.

**Comment by martinpitt** [comment]
FTR, I retried the tests already, and still the same failure. It's hard to imagine how this could aggravate the current test flakiness (PR #14342), but then again we don't understand that yet.

**Comment by martinpitt** [comment]
Retrying after #14345, to see which of these were flakes and which were real.

**Pull request merged**
