### PR TITLE
insights: Correctly align Insights status

### PR DESCRIPTION
**Pull request by marusak**
Before:
Screenshot from 2021-06-08 13-48-39currentinsights

After:
Screenshot from 2021-06-08 14-05-40aftyerinsights

### CODE REVIEW

**Review by KKoukiou — DISMISSED** [review]

**Comment by marusak** [comment]
Should this also have icon for external link? And also `target="_blank" rel="noopener noreferrer"` for security reasons?

**Comment by KKoukiou** [comment]
> Should this also have icon for external link? And also `target="_blank" rel="noopener noreferrer"` for security reasons?

Both true. So, ExternalLinkSquareAltIcon. Feel free to repost.

**Comment by marusak** [comment]
Screenshot from 2021-06-08 14-20-04redirection

**Comment by marusak** [comment]
Isn't that icon too disruptive?

**Comment by KKoukiou** [comment]
> Isn't that icon too disruptive?

it is actually :( how about you remove the description ou of the link. so '2 hits, including moderate' and then next two it add a link 'View insights', maybe with the external link icon.

**Comment by marusak** [comment]
> it is actually :( how about you remove the description ou of the link. so '2 hits, including moderate' and then next two it add a link 'View insights', maybe with the external link icon.

That could work, but it would be too much for a single line... Maybe @garrett has a good idea about this?

**Comment by garrett** [comment]
ExternalLinkSquareAltIcon can be used at the end of links too, BTW: https://www.patternfly.org/v4/components/button/design-guidelines/#link-button

If that alone doesn't help, we could do something like:

```
🗷 Insights: 2 hits, including moderate
   View details ⍈
```

Or perhaps:
```
🗷 Moderate hits; 2 total
   View Insights ⍈
```

We could even try to make that fit on one line?

> 🗷 Moderate hits; 2 total [View Insights ⍈](#)

And if there's just one, it could be like this?

> 🗷 Moderate hit [View Insights ⍈](#)

**Comment by marusak** [comment]
Screenshot from 2021-06-09 09-42-03includingimportnat

Having it at the end seems fine? @KKoukiou @garrett WDYT?

**Comment by KKoukiou** [comment]
> Screenshot from 2021-06-09 09-42-03includingimportnat
> 
> Having it at the end seems fine? @KKoukiou @garrett WDYT?

Looks fine to me. Make sure to use it like in the docs:
```
    <Button variant="link" icon={<ExternalLinkSquareAltIcon />} iconPosition="right">
      Link
    </Button>
```
In order to get proper spacing.

**Comment by marusak** [comment]
> Looks fine to me. Make sure to use it like in the docs:

Thats how I used it here. I havn't yet pushed as I want to get ack first.

**Review by garrett — APPROVED** [review]
Works for me. Thanks!

**Review by KKoukiou — APPROVED** [review]

**Comment by martinpitt** [comment]
packit failure is most likely because the proposed branch is 45 commits behind master, so let's ignore that here.

**Comment by martinpitt** [comment]
Today's tasks container refresh (inevitable due to moving webhook) brought a new firefox which is now [failing two metrics tests](https://logs.cockpit-project.org/logs/pull-15911-20210609-134050-0295530f-fedora-33-firefox/log.html#271-2). We need to investigate them, but no need to block PRs.

**Pull request merged**
