### PR TITLE
fix anonymous project group assignment

### LINKED ISSUE #4922: Registry: anonymous pulls need to assign group system:unauthenticated
Currently the registry UI assigns and looks for status using group `system:anonymous`. This needs to be `system:unauthenticated`.

### PR DESCRIPTION
**Pull request by aweiteka**
Fixes #4922

### CODE REVIEW

**Comment by petervo** [comment]
Tests are failing. Is this something that changed upstream? do we need a new image for it to work?

**Comment by aweiteka** [comment]
> Tests are failing. Is this something that changed upstream? do we need a new image for it to work?

Yes, support for this is pretty new so that is probably the issue.

**Comment by petervo** [comment]
I can refresh the image, but is there a way in the code we can figure out which group to use, to avoid breaking on older setups?

**Comment by petervo** [comment]
Turns out the problem here isn't the openshift image but that when we write the anonymous group we don't remove the shared group. The code that checks for the group aborts early when it finds one of the two. So it keeps returning 'shared' when the object has both groups. So because order matters it's now doing it wrong.

So we either need to change the way we calculate which type it is calculated in ```sharedImages``. Or we need to remove the shared group before writing the anonymous one in ```shareImages`` . Or both. I don't know why it was does like this originally so I'm not sure which one is correct.

**Comment by aweiteka** [comment]
> So we either need to change the way we calculate which type it is calculated in sharedImages.

@petervo Thanks for digging into this. It is valid to have both `system:authenticated` and `system:unauthenticated` assigned (albeit useless) so I think the solution is to fix the way we calc sharedImages.

**Pull request closed without merging**
