### PR TITLE
shell: Set server time implementation

### PR DESCRIPTION
**Pull request by fridex**
Implemented setting time using systemd-timedated - a user can enable NTP synchronization or adjust time manually.

### CODE REVIEW

**Comment by stefwalter** [comment]
Nice. Thanks for working on this. Some screenshots so our designer @andreasn can review as well:

screenshot from 2015-02-19 17 49 38

screenshot from 2015-02-19 17 50 36

**Comment by stefwalter** [comment]
@rhamilto is the glyphicons font part of Patternfly? It seems we need to include them to make bootstrap-datepicker work. Have you played around in this area?

**Comment by rhamilto** [comment]
@stefwalter Glyphicons are part of Bootstrap, which is part of PatternFly.  I've not played with bootstrap-datepicker, but my guess is that the pathing is incorrect to the Glyphicons web fonts (which you may need to override for your specific app).  See https://github.com/patternfly/patternfly/blob/master/less/variables.less#L127

**Comment by stefwalter** [comment]
@rhamilto Thanks. Will look into what the problem is and why those fonts were not showing up.

**Comment by stefwalter** [comment]
Replaced by #1840

**Pull request closed without merging**
