### PR TITLE
Image refresh for fedora-26

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-26
 * [x] image-refresh fedora-26

### CODE REVIEW

**Comment by martinpitt** [comment]
@mvollmer: It seems it expects the new sosreport appstream data to *not* be present on Fedora 26, and fails? Supposedly fedora-26 just needs to be added to the "positive" list here?

https://fedorapeople.org/groups/cockpit/logs/pull-8463-20180121-231212-ac4e5615-verify-fedora-26/log.html#97

**Comment by martinpitt** [comment]
I pushed the test update. @mvollmer, can you please review (once it gets green)?

**Comment by martinpitt** [comment]
@mvollmer: This is green now, I just fat-fingered the "fedora-atomic" test (invalid name, missing verify/ prefix) so that one will never be handled.

**Comment by mvollmer** [comment]
> Supposedly fedora-26 just needs to be added to the "positive" list here?

Yes, that looks right.  We don't normally test with fedora-26, and that's how this wasn't detected earlier.

**Pull request merged**
