### PR TITLE
common: Fix two test races that are failing in Travis

### PR DESCRIPTION
**Pull request by stefwalter**
Well, at least try to fix them, that's how these things go.

In one case writev is failing with -1. I'm guessing that this
is EAGAIN or EINTR and we are now handling those.

The other case is where the close of file descriptores raced
with the closing of the stream. Put these in the right order.

Fingers crossed.

In any case these are not indications of real bugs, but problems in the tests.

### CODE REVIEW

**Comment by mvollmer** [comment]
Looks good.

**Comment by stefwalter** [comment]
No actual question here, but I have it on my list to continue work on this. Usually fixing Travis failures is an iterative process, with several pull requests. @petervo Or would you prefer if I leave this open?

**Comment by petervo** [comment]
@stefwalter guess i commented in the wrong place: https://github.com/cockpit-project/cockpit/commit/e955bb8cfaab01fa2588c01ffb7e2764ff559c49#commitcomment-11241520

**Comment by petervo** [comment]
Replaced by #2316

**Pull request closed without merging**
