### PR TITLE
containers: Bump to f25

### PR DESCRIPTION
**Pull request by petervo**
We stopped building f24 in koji.

### CODE REVIEW

**Comment by petervo** [comment]
bot: Image refresh for fedora-25

**Comment by petervo** [comment]
bot: Image refresh for openshift

**Comment by cockpituous** [comment]
Image creation for fedora-25 in process on cockpit-9.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-25-35059e8b1aceabced532de42518f260074cb17d1/

**Comment by cockpituous** [comment]
Image creation for openshift in process on cockpit-10.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-openshift-35059e8b1aceabced532de42518f260074cb17d1/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-openshift-35059e8b1aceabced532de42518f260074cb17d1

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-fedora-25-35059e8b1aceabced532de42518f260074cb17d1

**Comment by petervo** [comment]
testlib change isn't picked by the test runner, so the container tests won't run. Ran ```./containers/run-tests -i``` locally and everything passes.

**Pull request closed without merging**
