### PR TITLE
bots: Include clevis/tang in all RHELish images 

### PR DESCRIPTION
**Pull request by mvollmer**
The goal is to get clevis into as many images as we can.  Let's see what happens.

- [x] #9894
- [x] #9465

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-1b1s4.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9800-20180806-113535/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20180806-120404

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-f8zm2.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9800-20180806-120505/

**Comment by cockpituous** [comment]
image-refresh rhel-7-5 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-5-20180806-125151

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-l7c6p.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9800-20180806-124949/

**Comment by mvollmer** [comment]
Rebased, and retriggered image builds.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-1b1s4.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9800-20180806-190101/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9800-20180806-190101/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-9tbpp.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9800-20180806-192626/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9800-20180806-192626/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-d43kk.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9800-20180806-200202/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9800-20180806-200202/

**Comment by mvollmer** [comment]
The spec file as broken on #9465.  Rebased again and retriggered again.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-wdc9l.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9800-20180806-203434/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20180806-210505

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-1b1s4.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9800-20180806-212323/

**Comment by cockpituous** [comment]
image-refresh rhel-7-5 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-5-20180806-220909

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-tdm4j.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9800-20180806-220909/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9800-20180806-220909/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-jwbj7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9800-20180807-075757/

**Comment by cockpituous** [comment]
image-refresh rhel-7-6 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-6-20180807-082828

**Comment by mvollmer** [comment]
All images done, let's see what the tests say.

**Comment by mvollmer** [comment]
This will fail images that don't have python3.  We need to port luksmeta-monitor-hack.py to work with both python2 and python3.

**Comment by martinpitt** [comment]
Pulled into #9894, then the only thing left is to enable the tests on the other images and fix potential fallout.

**Comment by mvollmer** [comment]
Let's start over in a new pull request.

**Pull request closed without merging**
