### PR TITLE
Test: add alternate way to detect system reboot

### LINKED ISSUE #2915: Failure: system didn't notify us about a reboot
#2909 f22 failed like this:

http://files.cockpit-project.org/hubbot/34ebb7c32adf83914dd45699a5d9db17c262745d_f22_x86-64/hubbot.html

```
Read from socket failed: Connection reset by peer

======================================================================
ERROR: testBasic (__main__.TestShutdownRestart)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-shutdown-restart", line 45, in testBasic
    m.wait_reboot()
  File "/home/hubbot/hubbot/34ebb7c32adf83914dd45699a5d9db17c262745d_f22_x86-64/test/testvm.py", line 857, in wait_reboot
    raise Failure("system didn't notify us about a reboot")
Failure: system didn't notify us about a reboot
```

### PR DESCRIPTION
**Pull request by dperpeet**
The libvirt "reboot" event doesn't always get sent.
When waiting for a reboot, wait for this event
or port 22 to be closed - whichever comes first.

Fixes #2915

### CODE REVIEW

**Comment by dperpeet** [comment]
error still happens with alternate - is something wrong with reboot?

**Comment by stefwalter** [comment]
Maybe looking at the system logs would tell us something? 

```
Journal database copied to check-shutdown-restart-testBasic-10.111.112.103-FAIL.journal
```

**Comment by dperpeet** [comment]
> Maybe looking at the system logs would tell us something?

yeah... except that the journal didn't get copied. I'll look through the other cases and see if one of them has a journal

**Comment by stefwalter** [comment]
I think the problem is that we're shutting down the system before it is booted:

```
Okt 10 13:08:14 f3 cockpit-bridge[1789]: Reauthorizing unix-user:admin
Okt 10 13:08:14 f3 cockpit-bridge[1789]: cockpit-polkit: user admin was reauthorized
Okt 10 13:08:14 f3 cockpit-bridge[1789]: cockpit-polkit helper exited with status: 0
Okt 10 13:08:14 f3 polkitd[523]: Operator of unix-session:3 successfully authenticated as unix-user:admin to gain ONE-SHOT authorization for action org.free
Okt 10 13:08:14 f3 pkexec[2018]: pam_unix(polkit-1:session): session opened for user root by (uid=1000)
Okt 10 13:08:14 f3 pkexec[2018]: admin: Executing command [USER=root] [TTY=unknown] [CWD=/run/user/1000] [COMMAND=/bin/cockpit-bridge]
Okt 10 13:08:14 f3 cockpit-ws[1711]: localhost: remove channel 1:2!16 for session
Okt 10 13:08:14 f3 cockpit-ws[1711]: localhost: removed channel 1:2!16 for session
Okt 10 13:08:14 f3 cockpit-ws[1711]: 1: remove channel 1:2!16 for socket
Okt 10 13:08:15 f3 kdumpctl[860]: No memory reserved for crash kernel.
Okt 10 13:08:15 f3 kdumpctl[860]: Starting kdump: [FAILED]
Okt 10 13:08:15 f3 systemd[1]: kdump.service: main process exited, code=exited, status=1/FAILURE
Okt 10 13:08:15 f3 systemd[1]: Failed to start Crash recovery kernel arming.
Okt 10 13:08:15 f3 systemd[1]: Unit kdump.service entered failed state.
Okt 10 13:08:15 f3 systemd[1]: Starting Multi-User System.
Okt 10 13:08:15 f3 systemd[1]: Reached target Multi-User System.
Okt 10 13:08:15 f3 systemd[1]: Starting Update UTMP about System Runlevel Changes...
Okt 10 13:08:15 f3 systemd[1]: Started Stop Read-Ahead Data Collection 10s After Completed Startup.
Okt 10 13:08:15 f3 systemd[1]: Started Update UTMP about System Runlevel Changes.
Okt 10 13:08:15 f3 systemd[1]: Startup finished in 1.639s (kernel) + 7.156s (initrd) + 16.362s (userspace) = 25.157s.
Okt 10 13:10:14 f3 systemd[1]: Started OpenSSH Server Key Generation.
Okt 10 13:10:14 f3 systemd[1]: Starting OpenSSH per-connection server daemon...
Okt 10 13:10:14 f3 systemd[1]: Started OpenSSH per-connection server daemon.
Okt 10 13:10:14 f3 sshd[2227]: Accepted publickey for root from 10.111.112.1 port 53433 ssh2: RSA 9f:92:a1:54:9f:32:f7:40:17:39:0f:bc:4e:0c:39:90
Okt 10 13:10:14 f3 systemd[1]: Created slice user-0.slice.
Okt 10 13:10:14 f3 systemd[1]: Starting Session 4 of user root.
Okt 10 13:10:14 f3 systemd[1]: Started Session 4 of user root.
Okt 10 13:10:14 f3 systemd-logind[405]: New session 4 of user root.
Okt 10 13:10:14 f3 sshd[2227]: pam_unix(sshd:session): session opened for user root by (uid=0)
```

**Comment by dperpeet** [comment]
#2948 worked better

**Pull request closed without merging**
