### PR TITLE
test: Handle "\n" specially with Browser.set_text_input

### PR DESCRIPTION
**Pull request by mvollmer**
This allows us to use it to enter multi-line text directly into a TextArea.

Note that Browser.val() will return multiple lines separated by "\n" characters, so it is natural to allow them also with Browser.set_input_text.

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
WFM. I suggest to convert some of our tests to it, we have quite a lot of instances that type terminal commands, like
```
b.input_text("klist")
b.key("Enter")

b.focus('.terminal')
b.input_text('"')
b.key("Enter")
```

(But can be a follow-up)

**Comment by martinpitt** [comment]
When you land this, please squash&merge and fix the method name in the commit message. It's `input_text()`, not `set_text_input` (that doesn't exist at all)

**Comment by mvollmer** [comment]
> I suggest to convert some of our tests to it

I did that in a separate commit.

**Review by martinpitt — APPROVED** [review]
Ack! It dilutes the separation between .input_text() and .key(), and I really don't want to allow special-casing any other escapes. But indeed newline is common enough to justify the quality-of-life improvement. Thanks!

**Pull request merged**
