### PR TITLE
tools: Install phantomjs in mock.

### PR DESCRIPTION
**Pull request by mvollmer**
So that we don't skip the HTML tests in make check.

### CODE REVIEW

**Comment by stefwalter** [comment]
This spec file will fail in Koji and Brew ... neither of which have network access during build.

**Comment by stefwalter** [comment]
If we start doing this (and perhaps check-memory) then we probably need to make the --quick option to VERIFY and testsuite-prepare the default.

**Comment by mvollmer** [comment]
> This spec file will fail in Koji and Brew ... neither of which have network access during build.

Do they run "make check"?  Would it be enough to install phantomjs only in "%check"?

The fundamental problem is that phantomjs is not packaged for Fedora.  Would it work to get a non-official package from somewhere that is pulled in via BuildRequires?

**Comment by stefwalter** [comment]
> Do they run "make check"? Would it be enough to install phantomjs only in "%check"?

Yup.

> The fundamental problem is that phantomjs is not packaged for Fedora. Would it work to get a non-official package from somewhere that is pulled in via BuildRequires?

I believe that goes against the packaging guidelines of both Fedora and RHEL.

**Comment by mvollmer** [comment]
As discussed on IRC, let's keep "make check" simple.

**Pull request closed without merging**
