### PR TITLE
lib/forms: Remove margin from labels

### LINKED ISSUE #11229: When using ct-form-layout all labels apart from the first have smaller up margin than they should (only in narrow mode)
This is how the labels look now in narrow mode - apart from the first, all the others have smaller upper margin than the first.
current-label-misallignment

If I disable the margin overwritting from ct-form-layout class all labels get the same margin now.
Like here:
expected-label-allignment

It's this line that sets this margins, https://github.com/cockpit-project/cockpit/blob/master/pkg/lib/form-layout.less#L337

### PR DESCRIPTION
**Pull request by garrett**
Fixes #11229

### CODE REVIEW

**Comment by martinpitt** [comment]
@mvollmer: FYI, fedora-30/selenium is no more, it moved to fedora-31. But I think this is green enough, it just needs a visual review now.

**Comment by mvollmer** [comment]
> fedora-30/selenium is no more, it moved to fedora-31.

Ah, I need to update my bots/

**Comment by garrett** [comment]
Note: This only impacts forms in compact mobile mode. I should've specified that.

**Comment by garrett** [comment]
It's very minor. You can see the before/after here: https://github.com/cockpit-project/cockpit/issues/11229#issuecomment-585871423

**Comment by mvollmer** [comment]
I can't find any regression.

**Pull request merged**
