### PR TITLE
Split basic/optional package build on RHEL

### PR DESCRIPTION
**Pull request by martinpitt**
On RHEL/CentOS, cockpit is delivered as two mostly identical source
packages.  "cockpit" with build_basic=1, and "cockpit-appstream" with
build_optional=1.

Do that split upstream, so that upstream testing better reflects what
actually happens downstream in RHEL. This will also finally exercise the 
`build_*=0` code paths, so that we stop breaking them:

 - Check the OS and source package name in the spec to provide the 
   correct values for build_*. This minimizes the downstream delta to
   just Name: and %changelog.

 - Adjust make-srpm to build a separate cockpit-appstream.spec on
   RHEL/CentOS, and build srpms for all generated specs.

### CODE REVIEW

**Comment by martinpitt** [comment]
Without the first commit, the build now properly fails, like it would downstream. This avoids us having to do hacks and follow-up fixes after releases. With that we can also reproduce https://bugzilla.redhat.com/show_bug.cgi?id=1870521 . Both -debuginfo packages get installed, so they don't actually collide (which, coming from a .deb world, is really distracting). But we can now add an extra check that each file belongs to one package only.

**Comment by martinpitt** [comment]
Note that this is still a bit inefficient -- for -distropkg we build cockpit.srpm with the basic packages, and then just ignore most of these rpms (except for the "cockpit" metapackage). It would be faster to just build/install cockpit-appstream in this case. However, that would introduce more special cases into the code. We may or may not decide to do that in the future, but for now I propose to just live with the extra few minutes of build time.

**Comment by martinpitt** [comment]
> (except for the "cockpit" metapackage)

Lies -- on -distropkg we actually *do* use the "cockpit" metapackage from the distro as well.

**Comment by marusak** [comment]
so `cockpit` and `cockpit-appstream` rhel dist-gits are both going to be based on `cockpit` fedora distgit?  And based purely on it being rhel and then name being cockpit or not we decide what we want to builld? What about fedora-eln? Is there also defined `rhel` macro?

**Comment by martinpitt** [comment]
@marusak: Not "are going to", but "have been forever". Downstream *literally* looks like that -- we copy fedora's cockpit srpm/dist-git to rhel, disable build_optional, and copy the exact same source to cockpit-appstream and disable build_basic. I.e. this PR reflects what already happens downstream to also happen in our upstream CI.

**Comment by martinpitt** [comment]
AFAICS fedora-eln should *not* have that split, as the BaseOS/AppStream division does not exist in Fedora, even ELN. It's strictly on the RHEL/CentOS side.

**Review by marusak — APPROVED** [review]
Thank, it looks good!

**Pull request merged**
