### PR TITLE
WIP: machines, lib: Use SelectableListing for VM boot order

### PR DESCRIPTION
**Pull request by skobyda**
**Work in Progress.**

Use cockpit custom PF4-based listing with clickable rows for VM boot order.

Currently will try to figure out here with @garrett  how to organize row content if checkbox, name, description and actions are needed in a row.
Screenshot from 2020-03-26 15-23-54

### CODE REVIEW

**Comment by garrett** [comment]
Perhaps we should try out https://www.patternfly.org/v4/documentation/react/layouts/flex

Related items should be implemented like the nesting demo and then also please refer to the "canGrow" and "column widths" demos. The "aligning right" demo might also help, perhaps.

The inline JSX demo code for the nested one looks pretty simple:

```jsx
import React from 'react';
import { Flex, FlexItem } from '@patternfly/react-core';

NestingFlexExample = () => (
  <Flex>
    <Flex>
      <FlexItem>Flex item</FlexItem>
      <FlexItem>Flex item</FlexItem>
    </Flex>
    <Flex>
      <FlexItem>Flex item</FlexItem>
      <FlexItem>Flex item</FlexItem>
      <FlexItem>Flex item</FlexItem>
    </Flex>
  </Flex>
);
```

**Comment by skobyda** [comment]
Good. I reworked it using PF4 Flex. But I get problems with splitting words if word is too long to be in one line. `word-break: break-all;` doesn't seem to take any effect.


Screenshot from 2020-03-29 19-47-49

**Comment by garrett** [comment]
>  I reworked it using PF4 Flex.

It looks like a good start! I guess we'll need to play around with what's set for each part. If PF4 isn't flexible enough, we can do some custom overrides with CSS too.

FWIW: The buttons shouldn't be marked as primary. (In other words, the up/down buttons shouldn't be that primary blue.)

I think in another place where we have up/down arrows, we hide the ones that cannot be moved at all... Oh, that's probably boot order before this PR. :wink:

**Comment by skobyda** [comment]
Changing buttons from primary to secondary is no problem.
I wonder about hiding disabled buttons. Wouldn't it make the situation when some device can be moved up but not down (or vice versa) look weird? since only one button would be present.
Screenshot from 2020-03-30 14-54-58

**Comment by garrett** [comment]
When hiding, you're supposed to have a placeholder, think setting it to disabled and a visibility: hidden, not a display: none, so the size and placing is maintained. The existing dialog implements this, right?

**Comment by garrett** [comment]
Screenshot of current boot dialog (not in this PR), for reference:

Screenshot_2020-03-30 Virtual Machines - Rain

When row is unchecked, the up/down buttons are disabled and hidden (with visibility none, so they still take up space).

When the row is checked, the up/down buttons are shown, but if an action cannot be done, it is disabled (yet visible).

Note: The buttons are set to primary, but they shouldn't be. (Mentioned above for this PR.)

The way I thought the PF4 flex object would work was this:

Key:
[] are flex objects
() are comments

* [ check ] 
* [ ... ] (nested flex, vertical)
   * [ name ]  [ [ extra ] [ info ] ]  (extra info is back to horizontal)
* [ up / down ]

**Comment by garrett** [comment]
The current extra info is a little weird looking; we can do better on the key value display in the new dialog. The flex arrangement of items should be similar though (outlined above) so it should work on all sizes.

**Comment by skobyda** [comment]
Oh right, when the row is not selected, the there are no buttons at all, so it's not hidden but the buttons are not rendered at all.
Is this approach okay?

**Comment by skobyda** [comment]
Screenshot from 2020-03-30 19-29-49

**Comment by garrett** [comment]
It's looking better!

In fact, I think I'll switch over to this branch a little later today to see if I can work on the layout a bit. :wink:

**Comment by KKoukiou** [comment]
@skobyda @garrett PF4 has a draggable DataList component since last release. I think it's ideal for our usecase here.
I tried it out, and it looks like this:
Screen Shot 2020-10-23 at 10 43 52

Shall we go with that instead of our up/down buttons?

**Comment by skobyda** [comment]
@KKoukiou I think that was the initial idea when boot order was even implemented: Implementing drag and drop was way too much at that time, so we used up and down arrows. But now since PF4 has a component, that would be much better solution what's here now (and making this PR obsolete)

**Comment by garrett** [comment]
The idea is nice, but the layout is still extremely bad and would definitely need some work.

I guess the PF4 list should handle keyboard manipulation too?

**Comment by KKoukiou** [comment]
> The idea is nice, but the layout is still extremely bad and would definitely need some work.
> 
> I guess the PF4 list should handle keyboard manipulation too?

I does handle keyboard manipulation. You can test it here. https://www.patternfly.org/v4/components/data-list#draggable

**Comment by garrett** [comment]
> I does handle keyboard manipulation.

Cool! That's what I assumed, as it's in PF4 proper now.

> You can test it here.

1. First attempt: It.... crashed? And all the data went away.
2. Second attempt, with tabbing: Focus gets stuck on the first item, no keys (even tab) works. Mouse also now has a problem.
3. Third attempt, back with the mouse: It worked to drag and move things around.

It seems buggy at best. :cry: This is on Firefox, but it _should_ work across all browsers.

**Comment by KKoukiou** [comment]
@skobyda could you please check this when you have time? After my open PR for form fields, this is the last thing in machines page which is blocking us to drop PF3. 
I can do it as well if you are busy.

**Comment by KKoukiou** [comment]
I will take over this one, I will create another Pr, this is using some obsolete components anyway

**Pull request closed without merging**
