### PR TITLE
ws: Include bridge debug messages in testing logs

### PR DESCRIPTION
**Pull request by stefwalter**

### CODE REVIEW

**Comment by stefwalter** [comment]
I'll look into these test failures.

**Comment by stefwalter** [comment]
I've duplicated this issue locally. I can't see anything odd in the logs (besides the increased debug output).

**Comment by stefwalter** [comment]
@mvollmer Most of the storage tests fail when I set G_MESSAGES_DEBUG=cockpit-bridge. Any idea why that might be?
 * I can't see how this environment variable might be transferred to storaged
 * I don't see any crash or something like that in the logs.
 * This has to be in the CockpitDBusJson code or CockpitDBusCache code.

**Comment by mvollmer** [comment]
> @mvollmer Most of the storage tests fail when I set G_MESSAGES_DEBUG=cockpit-bridge. Any idea why that might be?

I'll check.

**Comment by stefwalter** [comment]
Rebased onto #3110

**Pull request closed without merging**
