### PR TITLE
storage: Synchronously check for mountedness during resizing

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
The test will still fail because the unmount triggered by resizing the LUKS container is still unexpected (and wrong). However, this change here will make it so that the user is left with a fully resized (but unexpectedly unmounted filesystem), instead of a half resized one.

**Comment by mvollmer** [comment]
Grr, is findmnt not generally available?

**Comment by mvollmer** [comment]
> Grr, is findmnt not generally available?

No, the code was checking the wrong block device for mountedness.

**Review by martinpitt — APPROVED** [review]
Nasty hack, but :man_shrugging: what can you do.. it doesn't affect the on-disk end result, so we can live with this well. Thanks for tracking this down!

**Pull request merged**
