### PR TITLE
Image refresh for fedora-23

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for fedora-23 in process on host37-rack09.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-23-2016-02-02/

### CODE REVIEW

**Comment by stefwalter** [comment]
I just merged a pull request like this. There shouldn't be another opened for at least a week, no?

**Comment by mvollmer** [comment]
> I just merged a pull request like this. There shouldn't be another opened for at least a week, no?

That is true.  I'll check.

But the situation is stable now, right?  We didn't get flooded with image creation issues, correct?

**Comment by mvollmer** [comment]
>> I just merged a pull request like this. There shouldn't be another opened for at least a week, no?

> That is true.  I'll check.

Should be fixed by #3671

**Comment by stefwalter** [comment]
Closing now that #3671 is merged.

**Pull request closed without merging**
