### PR TITLE
WIP: TTY output displayed in Cockpit

### PR DESCRIPTION
**Pull request by stefwalter**
For sudo, polkit and likely for cockpit-ssh we need a way to have the frontend respond to password prompts when reauthorize support is enabled.

This is implemented in a Unixy way by just implementing TTY channels, and we'll be having specially formatted prompts 

 * [x] TTY channels
 * [x] TTY channel unit tests
 * [x] Make sudo work fully
 * [x] Sudo based integration test
 * [x] Polkit over TTY prompting
 * [x] Remove old bad ideas.

### CODE REVIEW

**Comment by stefwalter** [comment]
Reworked to serialize the polkit agent prompts.

**Comment by dperpeet** [comment]
adding needswork because of the WIP commit

**Comment by stefwalter** [comment]
I'll be leaving one #if 0 in ... but removed others. I'll be fixing the startup race that seems to cause the migration issue.

**Comment by martinpitt** [comment]
@stefwalter: Is this even conceptually relevant still? AFAIK the authorization plumbing was completely changed and simplified later on. With both sudo and polkit having an agent protocol, I'm fairly sure we don't want to talk to them through a PTY..

**Comment by marusak** [comment]
Needs to rebase to master since #12367 changed tests names

**Comment by martinpitt** [comment]
Closing for now, to clean up our stale PR list. This would be a great feature to have, but in the next months we have more urgent issues to address. It will take someone else quite some time to get up to speed with this code, so this will be quite a large project.

**Pull request closed without merging**
