### PR TITLE
bridge: Set the bridge LC_ALL locale for user language choice

### PR DESCRIPTION
**Pull request by stefwalter**
The bridge itself doesn't do any translation of strings, but calling setlocale() and setting the LANG environment variable here allows:
    
 * Strings to be translated in libraries.
 * Spawned processes to be translated correctly.
    
Note that we find out about the front end's language choice via the cockpitlang cookie and the Accept-Language HTTP header on package requests.
    
We make sure to track what the language was set to and only change it if we receive a different header here.

Since setlocale() is rather strict about what kind of locales it accepts we have to be more verbose about locales in shell/manifest.json and rather than setting just languages, set entire locales.

Add tests for this functionality.

### CODE REVIEW

**Comment by stefwalter** [comment]
Test needs this to pass on Ubuntu:

```
sudo locale-gen zh_CN
sudo locale-gen zh_CN.UTF-8
sudo updatelocale
```

**Comment by stefwalter** [comment]
Skip testing locale setting when we don't have a locale available.

**Comment by stefwalter** [comment]
Need to check why check-pages is failing.

**Comment by stefwalter** [comment]
I added the ```locale-gen``` logic to the integration tests.

**Comment by stefwalter** [comment]
Only run updatelocale on ubuntu.

**Comment by stefwalter** [comment]
Rebased.

**Comment by stefwalter** [comment]
Fixed for the atomics.

**Comment by stefwalter** [comment]
Marking priority so we can get this in before the next release. With this and a Zanata update, translations are "Done" and we can call for translators.

**Comment by petervo** [comment]
Unit tests fail for me, I think this is because I don't have those locales installed on my system. 

```
cockpit-protocol:ERROR:../src/common/test-locale.c:132:test_set_language: assertion failed (dgettext ("test", "Unavailable") == fixture->string): ("Unavailable" == "Nicht verf\303\274gbar")
./test-locale terminated with SIGABRT
FAIL: test-locale 8 /locale/set-language/de-de
**
cockpit-protocol:ERROR:../src/common/test-locale.c:132:test_set_language: assertion failed (dgettext ("test", "Unavailable") == fixture->string): ("Unavailable" == "\344\270\215\345\217\257\347\224\250")
FAIL: test-locale 9 /locale/set-language/zh-cn
invalid or unusable locale: __xx;%%%.UTF-8
invalid or unusable locale: __xx;%%%.UTF-8
```

Should we check and skip tests that can't be run because locale's are not installed?

**Comment by stefwalter** [comment]
> Unit tests fail for me, I think this is because I don't have those locales installed on my system.

What is the output of ```locale -a ``` ? I have code in there to skip tests when the locales are not available. It must be that the check is not accounting for something on your system.

**Comment by petervo** [comment]
The act of running ```locale -a``` fixed my locales and made the tests pass. Something must have been messed up on my system. I'll go ahead and merge

**Pull request closed without merging**
