### PR TITLE
package.json: Update react-dom package dependency

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```package.json:    "react-dom": "16.6.1",
pkg/apps/index.jsx:import ReactDOM from 'react-dom';
pkg/docker/image.js:    var ReactDOM = require("react-dom");
pkg/docker/overview.js:    var ReactDOM = require("react-dom");
pkg/docker/storage.jsx:import ReactDOM from "react-dom";
pkg/kdump/kdump.js:var ReactDOM = require("react-dom");
pkg/lib/cockpit-components-dialog.jsx:import ReactDOM from "react-dom";
pkg/lib/cockpit-components-select.jsx:import ReactDOM from 'react-dom';
pkg/lib/cockpit-components-terminal.jsx:import ReactDOM from "react-dom";
pkg/machines/index.es6:import ReactDOM from 'react-dom';
pkg/networkmanager/firewall.jsx:import ReactDOM from "react-dom";
pkg/ovirt/index.es6:import ReactDOM from 'react-dom';
pkg/packagekit/updates.jsx:import ReactDOM from 'react-dom';
pkg/playground/react-demo-file-autocomplete.jsx:import ReactDOM from "react-dom";
pkg/playground/react-demo-listing.jsx:import ReactDOM from "react-dom";
pkg/playground/react-demo-onoff.jsx:import ReactDOM from "react-dom";
pkg/selinux/setroubleshoot.js:var ReactDOM = require("react-dom");
pkg/shell/ssh-file-autocomplete.jsx:import ReactDOM from "react-dom";
pkg/storaged/details.jsx:import ReactDOM from 'react-dom';
pkg/storaged/overview.jsx:import ReactDOM from 'react-dom';
pkg/subscriptions/main.js:var ReactDOM = require("react-dom");
pkg/systemd/hwinfo.jsx:import ReactDOM from 'react-dom';
pkg/systemd/terminal.jsx:import ReactDOM from "react-dom";
pkg/users/local.es6:import ReactDOM from 'react-dom';
```

**Comment by martinpitt** [comment]
Lots of 
```
testlib.Error: error: Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s the componentWillUnmount method 
    in VncConsole (created by Vnc)
    in Vnc (created by Consoles)
```
We already blacklist a similar warning, the pattern needs some adjustment.

**Comment by martinpitt** [comment]
This is the place that needs to be adjusted: https://github.com/cockpit-project/cockpit/blob/master/test/common/testlib.py#L766

**Comment by martinpitt** [comment]
Pushed a rebase, and adjusted the commit message  a bit.

**Pull request merged**
