### PR TITLE
bots: Update rhel-7-7 image extra repo to latest-EXTRAS-7-RHEL-7

### PR DESCRIPTION
**Pull request by henrywang**
We have extras repo for rhel 7.7, so this PR just remove rhel 7.6 extras repo and use latest-EXTRAS-7-RHEL-7 instead.
Image refresh for rhel-7-7
 * [x] image-refresh rhel-7-7

### CODE REVIEW

**Comment by marusak** [comment]
Setup script is run on image create time (I hope, I am always confused with install vs setup scripts :D ), so this needs image refresh for rhel-7-7. Can you, please, request it in this PR? It is done with checkbox, something like in https://github.com/cockpit-project/cockpit/pull/11887 for example. And then please add `bot` label, in order for bots to catch it.

**Comment by henrywang** [comment]
Thanks @marusak!
Image refresh for rhel-7-7
 * [x] image-refresh rhel-7-7

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-04.
Log: https://209.132.184.41:8493/logs/image-refresh-11889-20190521-070707/

**Comment by martinpitt** [comment]
Thanks indeed! I labelled this as no-test. Once the image is refreshed, please do the following:

 * Fix the commit message to prepend "bots:", and add a Closes #
 * Grab the commit from cockpituous and add it here, then force-push.
 * We manually trigger the verify/rhel-7-7 test (no need to run all of them).

**Comment by cockpituous** [comment]
image-refresh rhel-7-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-7-20190521-073838

**Comment by martinpitt** [comment]
I added the image rebuild commit and fixed up the commit message. Starting tests now.

**Comment by henrywang** [comment]
@martinpitt, sorry, I forgot to update rhel-7-7 image name in my last commit. Thanks for correcting me.

**Pull request merged**
