### PR TITLE
test: Enable rhel-7.3 testing

### PR DESCRIPTION
**Pull request by dperpeet**

### CODE REVIEW

**Comment by dperpeet** [comment]
bot: Image refresh for rhel-7

**Comment by cockpituous** [comment]
Image creation for rhel-7 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-7-c8ec10b81d19cca9ab6624febe5ae6cb70fb2b00/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by dperpeet** [comment]
bot: Image refresh for rhel-7

**Comment by cockpituous** [comment]
Image creation for rhel-7 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-7-0737ecd377b09711ef1c1be847298393ee75e7aa/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by dperpeet** [comment]
bot: Image refresh for rhel-7

**Comment by cockpituous** [comment]
Image creation for rhel-7 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-7-0737ecd377b09711ef1c1be847298393ee75e7aa/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by dperpeet** [comment]
bot: Image refresh for rhel-7

**Comment by cockpituous** [comment]
Image creation for rhel-7 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-7-0737ecd377b09711ef1c1be847298393ee75e7aa/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by dperpeet** [comment]
bot: Image refresh for rhel-7

**Comment by cockpituous** [comment]
Image creation for rhel-7 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-7-0737ecd377b09711ef1c1be847298393ee75e7aa/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by mvollmer** [comment]
The upload of the image seems to fail due to
```
Host key verification failed.
```

**Comment by dperpeet** [comment]
bot: Image refresh for rhel-7

**Comment by cockpituous** [comment]
Image creation for rhel-7 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-7-0737ecd377b09711ef1c1be847298393ee75e7aa/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by dperpeet** [comment]
bot: Image refresh for rhel-7

**Comment by cockpituous** [comment]
Image creation for rhel-7 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-7-0737ecd377b09711ef1c1be847298393ee75e7aa/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by dperpeet** [comment]
I logged into the test runner and uploaded the image manually. The host key was added, so it should work in the future, but it seems image creation is a bit flaky right now.

**Comment by dperpeet** [comment]
I ensure a different test runner picked up the task, we are sure they can download the correct image.

**Pull request merged**
