### PR TITLE
Image refresh for ubuntu-1604

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for ubuntu-1604 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-ubuntu-1604-2017-02-13/

### CODE REVIEW

**Comment by martinpitt** [comment]
bot: Image refresh for rhel-atomic

**Comment by cockpituous** [comment]
Image creation for rhel-atomic in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-atomic-6fa105c64b43797e6d4ab9f86d7e1e3d99e1ddad/

**Comment by martinpitt** [comment]
Sorry, the above rhel-atomic creation was pilot error (wrong github-trigger from bash history). I meant to retry the test, done now.

**Comment by cockpituous** [comment]
Image creation failed.

**Pull request merged**
