### PR TITLE
Update translations from Fedora Zanata

### PR DESCRIPTION
**Pull request by cockpituous**
* [x] po-refresh

### CODE REVIEW

**Comment by stefwalter** [comment]
@petervo Could you check what happens when you run ```make download-po```. For me (and also for the bots) any non-ascii character is turned into question marks.

**Comment by petervo** [comment]
Ran it here:
https://github.com/petervo/cockpit/commit/81c65882bde37af7c79ae58b097ae5e5c2e21b40

Didn't see any lost chars. Seems ok to me.

**Comment by petervo** [comment]
What version of of zanata are you using? I'm on 3.9.1

**Comment by stefwalter** [comment]
Waiting for #6886

**Comment by stefwalter** [comment]
Fixed the encoding in #6886 ... so I'm closing this and the bots can try again now.

**Pull request closed without merging**
