### PR TITLE
Trim strings in Usage card

### PR DESCRIPTION
**Pull request by martinpitt**
Now looks like this:

usage

### CODE REVIEW

**Comment by martinpitt** [comment]
This [needs a little test adjustment](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-13395-20200114-151515-f5854f76-cockpit-project-cockpit--fedora-coreos/log.html#116-2), fix pushed.

**Comment by martinpitt** [comment]
@KKoukiou or @garrett: This needed a little test adjustment, can you please re-approve?

**Comment by marusak** [comment]
Blocked: Let's not merge this until we branch rhel-8.2 as this should not land there

**Comment by garrett** [comment]
The long strings interfere with the UI in various resolutions, as they push the progress bar to be too small, especially in some languages.

**Pull request merged**
