### PR TITLE
shell: minor visual tweaks to new navigation

### PR DESCRIPTION
**Pull request by garrett**
While taking screenshots for the release announcements, I realized I missed some minor details compared to the navigation mockups and PatternFly.

This is a follow-up to #7482.

### CODE REVIEW

**Comment by garrett** [comment]
These commits should probably be squashed, but I've left them separate in case you (mainly @andreasn) want to see the individual things I adjusted.

**Comment by garrett** [comment]
# Screenshots

## Desktop

screenshot-2017-11-15 storage - sunny

## Mobile

| Initial | Menu |
|---|---|
| screenshot_20171115-134846 |screenshot_20171115-134849 |

**Comment by garrett** [comment]
I've checked everything in the following browsers, and it all works here:

- Firefox, desktop
- Chrome, desktop
- Internet Explorer (in a VM)
- Edge
- Firefox, mobile
- Chrome, mobile

**Comment by garrett** [comment]
In commit a8132d9db, I constrained the width of icons to 33% of screen for the maximum, when in mobile mode.

It looks like this (mobile mode emulation in Firefox desktop):

|1 nav|2 nav|
|---|---|
| 370dc189-164e-4dbd-8df0-ad0bbeea2fac | db573806-2b7b-4a12-b228-96520dd1dd0e |

In addition, it's worth sharing a screenshot of what Cockpit looks like without additional dashboards to switch between. (Host only)

0d643d53-45c9-452c-8f8c-7b28bc60146d

**Comment by andreasn** [comment]
Screenshot of the hover state of System.

screenshot from 2017-11-15 16-55-03

**Comment by garrett** [comment]
This PR is also for issue #8035.

**Pull request closed without merging**
