### PR TITLE
test: Add kexec-tools also to fedora-testing

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
bot: Image refresh for fedora-testing

**Comment by cockpituous** [comment]
Image creation for fedora-testing in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-testing-1a1665f387b3ad32b811355a132a4fb4a7005c98/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-fedora-testing-1a1665f387b3ad32b811355a132a4fb4a7005c98

**Comment by mvollmer** [comment]
I _think_ all the test failures are known issues.

**Comment by dperpeet** [comment]
replaced by #5822

**Pull request closed without merging**
