### PR TITLE
login: Fix layout for "connect to" for requireHost

### LINKED ISSUE #15255: Layout bug on login page re RequireHost
Cockpit version: 236
Page: Login

When `RequireHost` is true and there is no remote host in the URL yet, the login page looks like this:

image

### PR DESCRIPTION
**Pull request by garrett**
Fixes #15255

### CODE REVIEW

**Comment by garrett** [comment]
I tested locally in-browser only, by modifying the CSS live in Firefox.

I tried using bind mounts to test this (how I usually test the login page), but got some weird error when trying to load the page. I guess the installed version of Cockpit and what's in tree aren't compatible?

Also, I could build a VM, but I don't know how to flip the RequireHost = true for a VM, so that line of testing is also not available to me.

Therefore, I've marked this as a draft. Please test in the normal mode and with RequireHost = true and share screenshots here. It _should_ work, but I really want to see it in action to be certain it does. Thanks!

**Comment by mvollmer** [comment]
To test this, add this to /etc/cockpit/cockpit.conf:

```
[WebService]
RequireHost=true
```

and then open the login page for "/", i.e., without any "/=host" part already in it.

**Comment by mvollmer** [comment]
> and then open the login page for "/", i.e., without any "/=host" part already in it.

You also need to restart Cockpit after changing cockpit.conf, `systemctl restart cockpit`.

**Comment by mvollmer** [comment]
Looks like this for me:

image

There seems to be more space above "Connect to" than above "Password".

**Review by mvollmer — APPROVED** [review]

**Comment by garrett** [comment]
> There seems to be more space above "Connect to" than above "Password".

That's 100% intentional. That's how it is by default too, with the expander.

User name & password are related. Connect to is not.

**Comment by garrett** [comment]
> To test this, add this to /etc/cockpit/cockpit.conf:
...
> You also need to restart Cockpit after changing cockpit.conf, systemctl restart cockpit.

Right, I said I did that and it didn't work. I get an error.

Can you also post a default screen w/o the requireHost? I want to make sure I didn't break that too.

**Comment by garrett** [comment]
Marking as ready for review, but I'd still like to see the default log in as a screenshot before this is merged.

**Comment by mvollmer** [comment]
> Marking as ready for review, but I'd still like to see the default log in as a screenshot before this is merged.

Here:

image

image

**Comment by garrett** [comment]
Awesome! Thanks! Looks good to me. :+1:  I'm glad I did this correctly. :grin:

**Pull request merged**
