### PR TITLE
session: Add support for GSSAPI S_CONTINUE

### PR DESCRIPTION
**Pull request by stefwalter**
This pull request finishes support for GSSAPI in cockpit-session, by properly using the same authentication context across multiple requests.

Issue #4538

Blocked on:

 * [ ] #5280

### CODE REVIEW

**Comment by dperpeet** [comment]
> This happens on Fedora 25 and RHEL 7
> 
> Issue #4538

The issue has occurrences for debian-unstable, fedora-23, fedora-24, fedora-25, centos-7 and rhel-7.
At least the debian one also occurred recently. Did you check the dates?

**Comment by stefwalter** [comment]
> The issue has occurrences for debian-unstable, fedora-23, fedora-24, fedora-25, centos-7 and rhel-7.
At least the debian one also occurred recently. Did you check the dates?

Those are a fundamentally different issue, just ends up failing at the same place in the code.

This is a known issue that resulted from gss-proxy in fedora-25 and RHEL Extras. We need to fix Cockpit to account for it.

**Comment by stefwalter** [comment]
I'll try and see if I can make a fix for the actual problem. Since this isn't an issue with the operating system, as far as I can tell, but an issue with Cockpit not being compatible with certain uses of GSSAPI.

**Comment by petervo** [comment]
Replaced by #5483

**Pull request closed without merging**
