### PR TITLE
pkg: Ensure cockpit.jump uses have a host

### PR DESCRIPTION
**Pull request by petervo**

### CODE REVIEW

**Comment by stefwalter** [comment]
Have you seen: https://trello.com/c/7WuCtGti/550-base-make-cockpitjump-jump-to-defaulthost-by-default

It seems to want to solve the same problem.

**Comment by martinpitt** [comment]
It seems to me that fixing the default behaviour of `jump()` without a host argument makes more sense than fixing all invocations? (We can't do that for third-party code).

**Comment by stefwalter** [comment]
> It seems to me that fixing the default behaviour of jump() without a host argument makes more sense than fixing all invocations? (We can't do that for third-party code).

That's correct, but some operating systems like RHEL won't get that fix right away. So at least the packagekit changes here make sense.

**Comment by petervo** [comment]
>It seems to me that fixing the default behaviour of jump() without a host argument makes more sense than fixing all invocations? (We can't do that for third-party code).

While I agree this would have been better, this is a backwards compatibility issue. We will be changing behavior, while we weren't relying on it, others may have been. So i'm not sure we should make that change.

**Comment by petervo** [comment]
Based on #7661 for rhel-7-4 naughty fixes.

**Pull request closed without merging**
