### PR TITLE
bots: Remove SELinux autorelabel stuff from image creation

### PR DESCRIPTION
**Pull request by stefwalter**
This should not be necessary. The correct SELinux policy should
be present in an image. And if not, we should use the
virt-builder --selinux-relabel option.

 * [x] image-refresh fedora-26
 * [x] image-refresh centos-7
 * [x] image-refresh fedora-25
 * [x] image-refresh fedora-24
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-6wbrj.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7336-20170720-061717/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-v2m01.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7336-20170720-061717/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20170720-065252

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-js48n.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7336-20170720-065353/

**Comment by cockpituous** [comment]
image-refresh fedora-26 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-26-20170720-075050

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-kk5pv.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7336-20170720-075959/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-testing-20170720-084747

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-cc9f5.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7336-20170720-090606/

**Comment by cockpituous** [comment]
image-refresh fedora-24 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-24-20170720-100000

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-cc9f5.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7336-20170720-100000/

**Comment by cockpituous** [comment]
image-refresh fedora-25 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-25-20170720-105555

**Comment by stefwalter** [comment]
We wanted to test that the image rebuilds work without autorelabel ... And we've built a sufficient number of them here.

**Comment by stefwalter** [comment]
I've included those images built without autorelabel in this pull request, so the CI will now run against those new images to validate that SELinux is working as expected.

**Comment by stefwalter** [comment]
rhel-7-4 is broken, and candlepin is not usually regenerated. Are you sure you want to block on those?

**Comment by martinpitt** [comment]
I thought *you* (or rather PR #7337) was blocking on those, and that not rebuilding rhel-7-4 would keep the libvirt monitor API that you are trying to drop? Not rebuilding candlepin should be alright.

**Pull request merged**
