### PR TITLE
bots: Fix broken Fedora image builds due to missing yum-utils

### LINKED ISSUE #7108: Test bots get stuck on "packet_write_wait: Broken pipe" on missing yum-utils
For the past few days our test bots keep dying, both the two "manual" ones on cockpit-{7,11} and also the OpenShift ones. cockpit-tests.service is still running and the docker container is up, but it's not  doing anything. This causes test request queues to build up quickly and reduce slowly.

Not much info from the journal:
```
Jun 25 01:10:49 cockpit-7.e2e.bos.redhat.com sh[65567]: [109B blob data]
Jun 25 01:10:49 cockpit-7.e2e.bos.redhat.com sh[65567]: [122B blob data]
Jun 25 01:10:49 cockpit-7.e2e.bos.redhat.com sh[65567]: [48B blob data]
Jun 25 03:10:49 cockpit-7.e2e.bos.redhat.com sh[65567]: packet_write_wait: Connection to 152.19.134.199 port 22: Broken pipe
```
This looks similar on the other machine and the OpenShift pods. It commonly seems to be exactly two hours between the previous messsage and the "broken pipe", which might indicate some kind of timeout.

For now it helps a bit to restart the service/pods, but they seem to break again after a short time.

So there are two things to fix:

 * Track down the reason for the timeout and fix it
 * Intercept this kind of failure and kill the bot, so that systemd/Openshift will automatically restart it.

### PR DESCRIPTION
**Pull request by martinpitt**
Commit 9620ff416 added yum-utils to the anaconda kickstarter config,
which apparently does not exist yet at this early stage. This caused
Fedora image builds to hang with a "Would you like to ignore this
package and continue with installation?" question.

Revert this part, and instead rely on rhel-7-4.setup to install
yum-utils.

Fixes #7108 

 * [x] image-refresh fedora-25
 * [x] image-refresh fedora-26
 - ~[ ] image-refresh rhel-7-4~ - currently uninstallable and no effective difference

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-929m2.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7109-20170625-091212/

**Comment by cockpituous** [comment]
image-refresh fedora-26 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-26-20170625-100404

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-3n7z5.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7109-20170625-101212/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-5tn1g.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7109-20170625-101212/

**Comment by cockpituous** [comment]
image-refresh fedora-25 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-25-20170625-104545

**Comment by martinpitt** [comment]
Not sure why the bot doesn't pick this up, but I locally ran `bots/image-create rhel-7-4` and it got past the point where it installed `yum-utils` from rhel-7-4.setup, which proves that it shouldn't be necessary to install it that early. Unfortunately it breaks later on on uninstallability:
```
+ yum -y --disablerepo=rhel-7-server-htb-rpms --disablerepo=rhel-sjis-for-rhel-7-server-rpms install yum-utils
[...]
Installed:
  yum-utils.noarch 0:1.1.31-40.el7                                              

Dependency Installed:
  python-chardet.noarch 0:2.2.1-1.el7_1   python-kitchen.noarch 0:1.1.1-5.el7  

Complete!
[...]
Error: Package: krb5-workstation-1.14.1-27.el7_3.x86_64 (rhel-7-server-rpms)
           Requires: krb5-libs(x86-64) = 1.14.1-27.el7_3
           Installed: krb5-libs-1.15.1-8.el7.x86_64 (@anaconda/7.4)
               krb5-libs(x86-64) = 1.15.1-8.el7
           Available: krb5-libs-1.11.3-49.el7.x86_64 (rhel-7-server-aus-rpms)
               krb5-libs(x86-64) = 1.11.3-49.el7
           Available: krb5-libs-1.12.2-14.el7.x86_64 (rhel-7-server-aus-rpms)
               krb5-libs(x86-64) = 1.12.2-14.el7
           Available: krb5-libs-1.12.2-15.el7_1.x86_64 (rhel-7-server-aus-rpms)
               krb5-libs(x86-64) = 1.12.2-15.el7_1
           Available: krb5-libs-1.13.2-10.el7.x86_64 (rhel-7-server-aus-rpms)
               krb5-libs(x86-64) = 1.13.2-10.el7
           Available: krb5-libs-1.13.2-12.el7_2.x86_64 (rhel-7-server-aus-rpms)
               krb5-libs(x86-64) = 1.13.2-12.el7_2
           Available: krb5-libs-1.14.1-26.el7.x86_64 (rhel-7-server-rpms)
               krb5-libs(x86-64) = 1.14.1-26.el7
           Available: krb5-libs-1.14.1-27.el7_3.x86_64 (rhel-7-server-rpms)
               krb5-libs(x86-64) = 1.14.1-27.el7_3
```
Plus a dozen more packages.

So I propose to not rebuild rhel-7.4 right now - the resulting image wouldn't change anyway as yum-install gets installed either way. But we need to land this to unbreak the other Fedora builds and unbreak the test bots.

**Pull request merged**
