### PR TITLE
networking: Handle really slow changes better

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by stefwalter** [comment]
How do we test for this? It seems really important to have a solid test for this.

**Comment by stefwalter** [comment]
So next question: Should we have a way of turning off health checks in subframes completely and leaving them just in the top level?

**Comment by stefwalter** [comment]
Next suggestion. Once we have health checks turned off in the subframes I would suggest sending the notification using a "hint" control message. Similar to how we do "restart" and "hidden". You can see ```process_hints()```.

Then you can use the ```cockpit.hint()``` API to send the hint.

**Comment by stefwalter** [comment]
At the end of the day, this shouldn't need to add public API. So I'll mark this needswork.

**Comment by mvollmer** [comment]
Couple of thoughts:

- Slightly bad things happen if the health check is turned off but never turned on, maybe because the subframe that turned it off has crashed.  (I'll use some try/catch to make the code more robust.)

- There are compatibility issues here since this adds to the protocol between shell and components.  I think it's okay since health_check_control is optional in a sense: nothing crashes or misbehaves severely without it, the user just can't perform a hopefully rare use case.

- It would be better to hoist the "Testing connectivity" curtain from the networking page to the shell (or maybe even to the index).  While test connection is down, the user shouldn't navigate around on that machine at all (and maybe not even to other machines).  This needs new API and a dependency of the networking component on that API.  (I put that in my backlog.)

**Comment by mvollmer** [comment]
> Should we have a way of turning off health checks in subframes completely and leaving them just in the top level?

Can you elaborate?  The health check on the websocket should be disabled, and as far as I can see, the subframes don't have a health check currently.  Am I confused?

If a component is used stand-alone, without the shell, the health check happens and might fail, but there is not immediate reaction to that.  (No curtain coming up.)  We could improve that, I guess.

**Comment by mvollmer** [comment]
> Then you can use the cockpit.hint() API to send the hint.

Yes, good point.

**Comment by stefwalter** [comment]
> Can you elaborate? The health check on the websocket should be disabled, and as far as I can see, the subframes don't have a health check currently. Am I confused?

You're right. I was confused about this point.

> If a component is used stand-alone, without the shell, the health check happens and might fail, but there is not immediate reaction to that. (No curtain coming up.) We could improve that, I guess.

There's also going to be more stuff moving out of the bridge, such as the polkit agent. Together there may need to be a sort of shell helper library that components use. Lets consider this again once everything has moved.

**Comment by mvollmer** [comment]
> How do we test for this? It seems really important to have a solid test for this.

Yes, I add a test.  We can simulate a slow DHCP response by replacing /usr/sbin/dhclient with a script that sleeps a bit and then execs the real dhclient.

**Comment by mvollmer** [comment]
> (I'll use some try/catch to make the code more robust.)

I think its actually okay as it is.  Exceptions should be routed to the reject handlers by the promise mechanism itself, and if one gets through, the user needs to reload anyway.

**Comment by stefwalter** [comment]
> Exceptions should be routed to the reject handlers by the promise mechanism itself, and if one gets through, the user needs to reload anyway.

Does that happen yet? I don't think it does.

**Comment by mvollmer** [comment]
>> Exceptions should be routed to the reject handlers by the promise mechanism itself, and if one gets through, the user needs to reload anyway.

> Does that happen yet? I don't think it does.

I don't know, but there is not much point in hacking that on from the outside, no?

**Comment by mvollmer** [comment]
> Yes, I add a test.  We can simulate a slow DHCP response by replacing /usr/sbin/dhclient with a script that sleeps a bit and then execs the real dhclient.

Now the test should be almost okay.  Holy testing tar pit, bat man.

**Comment by stefwalter** [comment]
Needs a rebase.

**Comment by stefwalter** [comment]
I've helped refactor the first commit. We already have all the API we need there, at least as far as I can tell. I think you would just use: ```cockpit.hint('ignore-health-check')``` or similar to invoke.

**Comment by mvollmer** [comment]
> I think you would just use: cockpit.hint('ignore-health-check', { data: val }) or similar to invoke.

Sounds okay, but there are some problems with #5560.  I'll change this PR here to use `cockpit.hint` instead of `cockpit.transport.ignore_health_check`, okay?

**Pull request closed without merging**
