### PR TITLE
Test fixes

### PR DESCRIPTION
**Pull request by marusak**

### CODE REVIEW

**Comment by marusak** [comment]
Example of the machines unexpected message: https://logs.cockpit-project.org/logs/pull-14917-20201123-165707-9efe9a26-rhel-8-3-distropkg/log.html#108
Example of that journal order problem: https://logs.cockpit-project.org/logs/pull-14917-20201123-165707-9efe9a26-ubuntu-2004/log.html#222-2

**Comment by marusak** [comment]
I want to send here one or two more fixes. Saving here a few logs to compare:

[ubuntu-2004](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-14948-20201123-191328-821e1f08-ubuntu-2004/log.html#259)
[debian-testing](https://logs.cockpit-project.org/logs/pull-14948-20201123-191328-821e1f08-debian-testing/log.html#260)
[f-33](https://logs.cockpit-project.org/logs/pull-14948-20201123-191328-821e1f08-fedora-33/log.html)
[8.3](https://logs.cockpit-project.org/logs/pull-14948-20201123-191328-821e1f08-rhel-8-3/log.html)

**Comment by marusak** [comment]
Here is comparision for patch `test: Show messages just once per test`
Original: 8208 characters
With the patch: 3158 characters

```
# ----------------------------------------------------------------------
# testAddDiskDirPool (__main__.TestMachines)
error: Failed to start network default
error: Requested operation is not valid: network is already active

DevTools listening on ws://127.0.0.1:9889/devtools/browser/2cef77b1-c853-4004-9069-85aa51dd2064
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9091/cockpit/$56b720beac26426061fc3d60255e8c1b75941a5a0fa653c220849c42a6f1dace/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1606164097457.853,"url":"http://127.0.0.2:9091/machines"}
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> error: Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s the componentWillUnmount method 
    in CreateVmAction (created by App)
    in div (created by ToolbarItem)
    in ToolbarItem (created by HostVmsList)
    in div (created by Context.Consumer)
    in div (created by ToolbarContent)
    in ToolbarContent (created by HostVmsList)
    in div (created by GenerateId)
    in GenerateId (created by Toolbar)
    in Toolbar (created by HostVmsList)
    in div (created by CardActions)
    in CardActions (created by HostVmsList)
    in div (created by Context.Consumer)
    in CardHeader (created by HostVmsList)
    in article (created by Card)
    in Card (created by HostVmsList)
    in section (created by PageSection)
    in PageSection (created by HostVmsList)
    in main (created by Page)
    in div (created by Page)
    in Page (created by HostVmsList)
    in HostVmsList (created by App)
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9091/cockpit/$56b720beac26426061fc3d60255e8c1b75941a5a0fa653c220849c42a6f1dace/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1606164149401.195,"url":"http://127.0.0.2:9091/machines#vm?name=subVmTest1&connection=system"}
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_2c4052c8_2083_4efd_a751_be934b924646 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document's URL has a fragment '#vm?name=subVmTest1&connection=system'.","timestamp":1606164159620.251,"url":"http://127.0.0.2:9091/machines#vm?name=subVmTest1&connection=system"}
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd-admin.socket
  libvirtd.socket
  libvirtd-ro.socket
# Result testAddDiskDirPool (__main__.TestMachines) succeeded
# 1 TEST PASSED [98s on vypocetnik]
```

```
# ----------------------------------------------------------------------
# testAddDiskDirPool (__main__.TestMachines)
error: Failed to start network default
error: Requested operation is not valid: network is already active

DevTools listening on ws://127.0.0.1:9421/devtools/browser/b38c2c0c-53fe-458d-8839-4d918a0f7c39
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9091/cockpit/$56b720beac26426061fc3d60255e8c1b75941a5a0fa653c220849c42a6f1dace/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":0,"url":"http://127.0.0.2:9091/machines"}
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_8f54774a_df98_4763_af54_fbc3d1ca0a4f {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> error: Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s the componentWillUnmount method 
    in CreateVmAction (created by App)
    in div (created by ToolbarItem)
    in ToolbarItem (created by HostVmsList)
    in div (created by Context.Consumer)
    in div (created by ToolbarContent)
    in ToolbarContent (created by HostVmsList)
    in div (created by GenerateId)
    in GenerateId (created by Toolbar)
    in Toolbar (created by HostVmsList)
    in div (created by CardActions)
    in CardActions (created by HostVmsList)
    in div (created by Context.Consumer)
    in CardHeader (created by HostVmsList)
    in article (created by Card)
    in Card (created by HostVmsList)
    in section (created by PageSection)
    in PageSection (created by HostVmsList)
    in main (created by Page)
    in div (created by Page)
    in Page (created by HostVmsList)
    in HostVmsList (created by App)
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9091/cockpit/$56b720beac26426061fc3d60255e8c1b75941a5a0fa653c220849c42a6f1dace/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":0,"url":"http://127.0.0.2:9091/machines#vm?name=subVmTest1&connection=system"}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document's URL has a fragment '#vm?name=subVmTest1&connection=system'.","timestamp":0,"url":"http://127.0.0.2:9091/machines#vm?name=subVmTest1&connection=system"}
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd.socket
  libvirtd-admin.socket
  libvirtd-ro.socket
# Result testAddDiskDirPool (__main__.TestMachines) succeeded
# 1 TEST PASSED [93s on vypocetnik]
```

**Comment by marusak** [comment]
The last commit saves on average 10%

**Review by KKoukiou — APPROVED** [review]
I wonder if it makes sense to also squash multiple same logs from console.log from the js code. Like https://logs.cockpit-project.org/logs/pull-14948-20201124-063433-45d1ef9b-ubuntu-2004/log.html#259

or I guess that's better that we just print the useful info in the tests.

**Pull request merged**
