### PR TITLE
WIP: terminal: Port to xterm.js

### PR DESCRIPTION
**Pull request by larskarlitski**
Xterm.js has the same API (minus a few constructor options) as term.js.
It also ships its own css file.

There's a couple of issues with it right now:
- it always shows a scroll bar
- it uses some inline styles and thus generates CSP warnings (can I whitelist those?)
- it requires quite new versions of broswers, we would need to update our requirements as well:
    * Chrome 48+
    * Edge 13+
    * Firefox 44+
    * Internet Explorer 11+
    * Opera 35+
    * Safari 8+

### CODE REVIEW

**Comment by dperpeet** [comment]
Comparting with our [running Cockpit page](http://cockpit-project.org/running.html) I see the following requirement changes:
Firefox 11 -> 44
IE 10 -> 11
Safari 6.1 -> 8
Chrome 16 -> 48
Opera 21.1 -> 35
Edge ? -> 13
Android Browser 4.4 -> ?

Why is this worth pushing our requirements so much?

**Comment by larskarlitski** [comment]
> Why is this worth pushing our requirements so much?

I don't know if it is. Just starting the discussion here. I do think that we should revise our minimum requirements or at least regularly test on them to make sure they work.

**Comment by stefwalter** [comment]
Reasons in favor, because those were missing:

 * The Kubernetes container-terminal and Openshift project are making this move too. 
 * term.js unsupported.

Reasons against:

 * Bumping dependencies.
 * Anything else?

**Comment by stefwalter** [comment]
> it uses some inline styles and thus generates CSP warnings (can I whitelist those?)

@larskarlitski Nope, we need to get those fixed upstream and/or fork our own NPM module.

**Comment by larskarlitski** [comment]
Update to keep term.js for kubernetes-container-terminal, as that hasn't moved yet (not sure why this built locally).

> @larskarlitski Nope, we need to get those fixed upstream and/or fork our own NPM module.

That's what I feared. I'll look into that if we decide it's worth it to bump dependencies.

**Comment by martinpitt** [comment]
These old Safari/Chromium/Firefox/Opera versions haven't been supported in a long time, so I wouldn't worry about these too much. [IE 10 is also not supported any more](https://venturebeat.com/2016/01/12/microsoft-ends-support-for-ie8-ie9-ie10-and-windows-8/). Not sure about Edge, but isn't that basically "Internet Exporer 13"?

**Comment by dperpeet** [comment]
> These old Safari/Chromium/Firefox/Opera versions haven't been supported in a long time, so I wouldn't worry about these too much. IE 10 is also not supported any more. Not sure about Edge, but isn't that basically "Internet Exporer 13"?

For the record, I don't mind bumping the versions. To be honest, there's rarely a good reason to use very old browsers these days due to security risks. The versions required by the proposed change aren't nearly cutting edge.

We do need to address the CSP issues though.

**Comment by larskarlitski** [comment]
Xterm.js recently bumped their dependencies to "latest" for all browsers ([upstream commit 8e07af](https://github.com/sourcelair/xterm.js/commit/8e07af04e37d7765da9e63c015ea33f9401a2b75#diff-04c6e90faac2675aa89e2176d2eec7d8)). They are also rewriting a good chunk by porting it to canvas, which is awesome, but might leave some older browsers not working.

Feels a bit too fast-moving for cockpit. So I suggest staying with term.js as long as it works for us. Feel free to reopen if you disagree.

**Pull request closed without merging**
