### PR TITLE
machines: Support bus type configuration for disks

### PR DESCRIPTION
**Pull request by skobyda**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1671144

Explanation of disk bus from libvirt documentation:
`The optional bus attribute specifies the type of disk device to emulate`

I also changed Show/Hide Performance Options -> Show/Hide Additional Options. People who want to change cache options do not need to be told that it's "Performance" option, and I think having it as Additinal Options makes more sense.

Screenshot from 2019-11-28 12-43-28

Screenshot from 2019-11-28 12-44-49

### CODE REVIEW

**Comment by skobyda** [comment]
The default value when creating a new disk will be virtio.

Also disk's bus cannot be configured for a running VM. In that case, dropdown is disabled:
Screenshot from 2019-11-28 12-55-33

**Comment by skobyda** [comment]
No machines-related failures

**Comment by garrett** [comment]
Overall, the modifications make sense.

Ideally, you should be able to do one of two things:
- have an explanation why the dropdown cannot be currently changed
- change it while it's running and have a notification that it only applies after the machine is rebooted

This setting should be consistent with changing the access (in the same dialog) and, ideally, with other things that can be changed too.

**Comment by skobyda** [comment]
I agree that a consistency with access configuration would be nice, but the problem of changing is bus is that sometimes when changing bus type we also need to change target of disk (e.g.: vda -> sda).
We use target to identify a disk, so changing target during runtime brings problems, because we would no longer be able to identify the same disk in live configuration and in offline configuration (which would result in user not being able to edit the same disk twice until reboot, detach the disk after editing it...)

So I think a best way to avoid these problems is to just not allow bus type editing during runtime. Yeah it will be inconsistent with the access configuration, but it's best solution I can think of.

**Comment by garrett** [comment]
> So I think a best way to avoid these problems is to just not allow bus type editing during runtime.

Then please add an indication why it cannot be changed at runtime.

Something as simple as:
"Machine must be shut off before changing bus type"

It could be either as some subtext with `pf-c-form__helper-text`, similar to the "Please provide your full name" text on [the horizontal forms demo](https://www.patternfly.org/v4/documentation/core/demos/basicforms#horizontal) ([here's the React version too](https://www.patternfly.org/v4/documentation/react/components/form#horizontal)) or as a tooltip when hovering (and also focusing) the little blue (i) icon.

If it's an icon + tooltip, make sure it's accessible.

My thoughts on which one to use:
- It might look like an error if we display the text directly below the dropdown
- Even if it isn't an error, it might look like an action someone has to do (they may think they need to shut down the VM regardless of whether they are going to change bus type or not — they might think Cockpit is going to change the bus type for them behind the scenes)

Therefore, I think the icon + tooltip is better in this case (again: make sure it's accessible).

**Comment by KKoukiou** [comment]
@skobyda Garrett had some comments here - just raising your attention in case you missed it.

**Comment by skobyda** [comment]
@garrett 
So I added tooltip (used patternfly 4 Tooltip and added aria-label). Let me know if I forgot about something in order to make it accessible.

Screenshot from 2020-01-07 16-19-09

**Comment by KKoukiou** [comment]
> @garrett
> So I added tooltip (used patternfly 4 Tooltip and added aria-label). Let me know if I forgot about something in order to make it accessible.
> 
> Screenshot from 2020-01-07 16-19-09

We deliberately haven't started to use PF4 tooltips so far. In addition we probably don't want part of our code to be using the old tooltips and part of it the new ones, for consistency reasons.
Do you mind to continue using the PF3 tooltips here? Else we need to ask @garrett  to write some overwrite CSS for this, to make it look like the old tooltip.

**Pull request merged**
