### PR TITLE
Image refresh for continuous-atomic

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for continuous-atomic in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-continuous-atomic-2016-08-29/

### CODE REVIEW

**Comment by cockpituous** [comment]
Image creation done.

**Comment by petervo** [comment]
Kubernetes has been removed from the continuous atomic builds, https://github.com/CentOS/sig-atomic-buildscripts/pull/144. So we need to change the way we install kubernetes on atomic.

**Comment by dperpeet** [comment]
> Kubernetes has been removed from the continuous atomic builds, CentOS/sig-atomic-buildscripts#144. So we need to change the way we install kubernetes on atomic.

Should we switch to using a container?

**Comment by petervo** [comment]
Replaced by #5187

**Pull request closed without merging**
