### PR TITLE
tools: Enable docker subpackage on openSUSE

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by martinpitt** [comment]
I'd strongly recommend to not do this. We are going to drop cockpit-docker from master as soon as Fedora 31 goes end-of-life, i. e. in a few months. Do you really want to introduce this package into SUSE only for a short time?

**Comment by lnussel** [comment]
ah, ok. Good to know. I don't mind really. It's for Tumbleweed only and useful for demoing purposes atm. So if the docker module gets dropped later so it be.
Will it be replaced by the so far external podman module then?

**Comment by martinpitt** [comment]
@lnussel: cockpit-podman is and will stay its own project. We want to move away from bundling so much into cockpit.git, it's so much easier to develop independent pages separately.

**Comment by martinpitt** [comment]
Closing this then. Please yell/reopen if you still want this, of course.

**Pull request closed without merging**
