### PR TITLE
users: Replace moment with Intl.DateTimeFormat

### PR DESCRIPTION
**Pull request by martinpitt**
moment is deprecated, and the users page only uses absolute dates/times.

See #15979

-----

This is the first page for trying this, it's easy to convert. Let's discuss general style/coding issues here, then I'm happy to port some more pages.

The difference is negligible, with Intl it even looks a tiny bit better in "last login", and it's identical for "Access":

Master, English:
user-master-en

This PR, English:
image

Master, German:
user-master-de

This PR, German:
image

### CODE REVIEW

**Comment by martinpitt** [comment]
f34 tests were happy, so let's run them all.

**Comment by martinpitt** [comment]
Oof, all tests fail now. My branch is up to date, so node_modules is not actually outdated. Supposedly the master branch renaming still needs some adjustments? That's something for tomorrow then.

**Review by allisonkarlitskaya — CHANGES_REQUESTED** [review]
The failure is caused by `node_modules` being updated by this commit.

**Comment by martinpitt** [comment]
Thanks. No idea how that went in, repushed with cleaning this up.

**Comment by martinpitt** [comment]
This now mysteriously [fails](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-16002-20210627-122048-006c2362-debian-stable/log.html#275-2) `test/verify/check-testlib TestRunTest.testRetry`. It didn't before, so somehow we broke something unrelated. My hunch is the `env["BASE_BRANCH"] = "master"` which needs to be adjusted for the rename to "main".

**Comment by martinpitt** [comment]
Nevermind, Allison already did it in #16006.

**Review by KKoukiou — APPROVED** [review]

**Review by KKoukiou — APPROVED** [review]
I am fine with the new module and also how you use it here.

**Pull request merged**
