### PR TITLE
test: Wait for session termination before the next non-destructive test

### LINKED ISSUE #15544: TestLogin.testConversation sometimes invokes sudo
Recently I saw several instances of [this test failure](https://logs.cockpit-project.org/logs/pull-15543-20210317-032630-7a4e80e4-debian-testing/log.html#197):
```
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
sudo: 3 incorrect password attempts
```
The [journal](https://logs.cockpit-project.org/logs/pull-15543-20210317-032630-7a4e80e4-debian-testing/TestLogin-testConversation-debian-testing-127.0.0.2-2301-FAIL.log.gz) confirms this:
```
Mar 17 03:52:05 debian root[31264]: COCKPITTEST: start TestLogin.testConversation
Mar 17 03:52:05 debian sudo[31188]:    admin : 3 incorrect password attempts ; PWD=/run/user/1002 ; USER=root ; COMMAND=/usr/bin/cockpit-bridge --privileged
Mar 17 03:52:05 debian cockpit-ws[31188]: sudo: 3 incorrect password attempts
Mar 17 03:52:05 debian sudo[31199]:    admin : a password is required ; PWD=/run/user/1002 ; USER=root ; COMMAND=validate
Mar 17 03:52:05 debian systemd[1]: systemd-timedated.service: Succeeded.
Mar 17 03:52:05 debian systemd[1]: session-132.scope: Succeeded.
Mar 17 03:52:05 debian systemd[1]: Stopped Session 132 of user admin.
```
This also happened on CentOS 8 and other OSes, it's not OS specific. 

This is a bit hard to reproduce locally. But I don't understand it conceptually -- this test is not *meant* to attempt sudo authentication. It just checks the initial login page.

*If* this test legitimately does superuser escalation, then fixing it is trivial (`self.allow_failed_sudo_journal_messages()`), but I don't see a good justification for it.

@mvollmer, do you have any idea about this?

### PR DESCRIPTION
**Pull request by mvollmer**
Otherwise the last few journal messages of the current test might leak
into the next and wrongly be considered as part of it.

Fixes #15544

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Many thanks for tracking this down!

**Review by martinpitt — CHANGES_REQUESTED** [review]
Oops! that breaks $OMGmany tests. Should we start applying this to testExpire only for now?

**Comment by mvollmer** [comment]
> Oops! that breaks $OMGmany tests. Should we start applying this to testExpire only for now?

I do some spot tests to see why the sessions don't terminate...

**Comment by mvollmer** [comment]
I couldn't get it to fail locally, so I put some debug output into testlib. Let's see. But the plan is to wait only a limited time, and then just continue instead of failing. The idea is that lingering sessions are blocked on something and wont produce any more output, and the waiting period takes care of slow things like sudo.

**Comment by mvollmer** [comment]
> But the plan is to wait only a limited time, and then just continue instead of failing.

Better plan: declare the global machine to be broken and restart it.

**Comment by mvollmer** [comment]
The only sessions that keep stuck are ones for "alice" on fedora-33... so that might be deterministic and fixable...

**Comment by mvollmer** [comment]
`test/verify/check-static-login TestLogin.testClientCertAuthentication` seems to produce the stuck session.

**Comment by mvollmer** [comment]
> test/verify/check-static-login TestLogin.testClientCertAuthentication seems to produce the stuck session.

This is a known thing and the test itself ignores stuck sessions, let's do the same in testlib.py.

But, isn't this the thing that Linux, cgroups, and systemd are supposed to be good at? *shrug*

**Comment by martinpitt** [comment]
@mvollmer: Sure,  but we don't enable logind's `KillUserProcesses=` option. That *would* do the cleanup, but distros have never enabled it by default as it breaks screen, tmux and the like. Without that, login keeps sessions around as long as they still have processes.

**Comment by mvollmer** [comment]
> Without that, login keeps sessions around as long as they still have processes.

The stuck sessions here have no processes. This must be some bug somewhere, similar to https://bugs.freedesktop.org/show_bug.cgi?id=89024

**Comment by martinpitt** [comment]
Current [fedora-33 run](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-15680-20210419-065427-0bb1666b-fedora-33/log.html#87) failed with an unexpected message in `TestHostSwitching.testNoAutoconnect`: "/system/overview.css: external channel failed: terminated". This is already on the weather report, and thus unrelated. Thanks for figuring this out!

**Review by martinpitt — APPROVED** [review]

**Comment by martinpitt** [comment]
I sent PR #15715 to fix the above flake.

**Pull request merged**
