### PR TITLE
Enable Fedora 35 in packit, drop/clean up Fedora 33 packit/test/doc

### PR DESCRIPTION
**Pull request by martinpitt**
- [x] PR #16288
 - [x] PR #16289
 - [x] disable fedora-33 (already disabled in release/CI)
 - [x] https://github.com/cockpit-project/bots/pull/2368

### CODE REVIEW

**Comment by martinpitt** [comment]
Unfortunately this is a bit hard to reproduce locally:

    $ tmt run --until report provision --how virtual.testcloud --image fedora:35
    Could not map 'fedora:35' to compose.

**Comment by martinpitt** [comment]
The [current run](http://artifacts.dev.testing-farm.io/e76f2ea5-8429-42ad-91dc-26e8e07e37e6/) has two problems:
 - Firewall tests failing to restart virsh network. I attempt to fix that in #16287.
 - Networking tests (here `TestTeam.testBasic`) timing out waiting for the MAC address. This has plagued us for a long time already in gating, and I can reproduce locally with `tmt run --until report` (on Fedora 34).

**Comment by martinpitt** [comment]
Oops, we still trigger fedora-33 tests. Sent https://github.com/cockpit-project/bots/pull/2368 to drop them.

**Comment by martinpitt** [comment]
@jelly : Do you feel comfortable reviewing this kind of maintenance PR? They are generally simple, but supposedly require some understanding of our CI infra. Please ask plenty of questions (this is a learning/teaching opportunity), or feel free to say if this is over your head still -- happy to ask someone else.

**Review by KKoukiou — APPROVED** [review]

**Review by jelly — APPROVED** [review]

**Pull request merged**
