### PR TITLE
shell: Permissions on host management UI.

### LINKED ISSUE #1096: Error when removing machines with non-root user
When I tried to remove a machine from the dashboard page with non-root account, I got this:
screenshot from 2014-08-28 11_29_31
screenshot from 2014-08-28 11_29_56

### PR DESCRIPTION
**Pull request by petervo**
Fixes #1096.

The host management is going to be reworked in #1867.  That will solve some bigger issues with host managment, but for now disabling the buttons for users who don't have permission is a better experience.

### CODE REVIEW

**Comment by stefwalter** [comment]
The 'Add Server' button is disabled, but no the edit checkbox button, or the delete button etc...

**Comment by petervo** [comment]
Works for me, that was how it was without the patch. Did you test the right one? What browser?

**Comment by dperpeet** [comment]
same here, only the "Add Server" button is disabled properly. 
screenshot from 2015-03-19 14 51 40

**Comment by stefwalter** [comment]
Works for me now. I must have had a bad mixed up install.

**Pull request closed without merging**
