### PR TITLE
shell: Only draw graphs for connected machines

### PR DESCRIPTION
**Pull request by petervo**

### CODE REVIEW

**Comment by stefwalter** [comment]
This seems to fail the integration test sometimes:

```
Wrote check-multi-machine-testBasic-FAIL.png
Journal database copied to check-multi-machine-testBasic-10.111.111.13-FAIL.journal
Journal database copied to check-multi-machine-testBasic-10.111.111.15-FAIL.journal
Journal database copied to check-multi-machine-testBasic-10.111.111.17-FAIL.journal
EWarning: Permanently added '10.111.111.13' (ECDSA) to the list of known hosts.
Warning: Permanently added '10.111.111.15' (ECDSA) to the list of known hosts.
Warning: Permanently added '10.111.111.17' (ECDSA) to the list of known hosts.

======================================================================
ERROR: testBasic (__main__.TestMultiMachine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-multi-machine", line 134, in testBasic
    b.enter_page("server", m3.address)
  File "/home/hubbot/hubbot/dd9df618423d97525566f18fda2efecc772d6428_r7_x86-64/test/testlib.py", line 347, in enter_page
    self.wait_visible('#' + id)
  File "/home/hubbot/hubbot/dd9df618423d97525566f18fda2efecc772d6428_r7_x86-64/test/testlib.py", line 236, in wait_visible
    return self.wait_js_func('ph_is_visible', selector)
  File "/home/hubbot/hubbot/dd9df618423d97525566f18fda2efecc772d6428_r7_x86-64/test/testlib.py", line 224, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))), timeout=self.phantom_wait_timeout)
  File "/home/hubbot/hubbot/dd9df618423d97525566f18fda2efecc772d6428_r7_x86-64/test/testlib.py", line 650, in wait
    return self.run({'cmd': 'wait', 'cond': cond, 'timeout': timeout*1000})
  File "/home/hubbot/hubbot/dd9df618423d97525566f18fda2efecc772d6428_r7_x86-64/test/testlib.py", line 613, in run
    raise Error("timeout")
Error: timeout
```

http://files.cockpit-project.org/hubbot/dd9df618423d97525566f18fda2efecc772d6428_r7_x86-64/hubbot.html

**Comment by petervo** [comment]
I'll try to confirm tomorrow but i don't think that this is caused by this change, but more of the same sporadic error.

**Comment by stefwalter** [comment]
This caused lots of other failures in the tests. Reopening.

**Comment by stefwalter** [comment]
Included in #2767 and #2756

**Comment by petervo** [comment]
This made it in with #2756

**Pull request closed without merging**
