### PR TITLE
bots: Fix EPEL install on rhel-7* images

### LINKED ISSUE #8253: Image refresh for rhel-7-4
Image refresh for rhel-7-4
 * [ ] FAIL: image-refresh rhel-7-4

### PR DESCRIPTION
**Pull request by martinpitt**
`yum install -y epel-release` works on CentOS 7, but not on RHEL 7. Move
the wget-based enabling of EPEL to an earlier place so that it works
everywhere.

Fixes #8253 

 * [x] image-refresh centos-7
 * [x] image-refresh rhel-7
 * [x] image-refresh rhel-7-4
 * [x] image-refresh rhel-7-5

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-5dbh6.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8283-20171217-103636/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-wmqkd.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8283-20171217-103636/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-gtx74.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8283-20171217-103939/

**Comment by martinpitt** [comment]
This time I refresh all images that use rhel-7.setup right away, to avoid another regression.

**Comment by cockpituous** [comment]
image-refresh rhel-7-5 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-5-20171217-111010

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-ftptk.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8283-20171217-111111/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-25z0q.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8283-20171217-111212/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-5fb82.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8283-20171217-111212/

**Comment by cockpituous** [comment]
image-refresh rhel-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-20171217-113939

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-5fb82.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8283-20171217-113939/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8283-20171217-113939/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-tbs4m.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8283-20171217-113737/

**Comment by cockpituous** [comment]
image-refresh rhel-7-4 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-4-20171217-120606

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-6zrlx.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8283-20171217-143232/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20171217-150101

**Comment by martinpitt** [comment]
All image builds worked, I pushed the images here.

**Comment by martinpitt** [comment]
@mvollmer: It seems something VDO related in RHEL 7.5 regressed; could you please take a look?

**Comment by martinpitt** [comment]
The regression in recent rhel-7-5 should not block unbreaking the other centos/rhel images, so I removed  the rhel-7-5 image refresh from this PR again. The above proves that the image generally works (the VDO regression is unrelated to installing lorax-composer).

**Pull request merged**
