### PR TITLE
test: Enable skipped timesyncd tests

### PR DESCRIPTION
**Pull request by jelly**
The testTime test works without skipping, for the testTimeServers test
enable the by default disabled ntp service in timesyncd so the test is
able to set specific time servers

### CODE REVIEW

**Comment by jelly** [comment]
Ok, further debugging shows that `TestSystemInfo-testTimeServers` does not require any modifications but that `timedate.cal('SetNTP', [val, true])` either fails or times out, the console logs:

```
re {problem: null, name: 'org.freedesktop.DBus.Error.UnknownInterface', message: "Unknown interface 'org.freedesktop.systemd1.Service'.", toString: ƒ}message: "Unknown interface 'org.freedesktop.systemd1.Service'."name: "org.freedesktop.DBus.Error.UnknownInterface"problem: nulltoString: ƒ ()[[Prototype]]: Object```

**Comment by martinpitt** [comment]
CLI reproducer:

 - `timedatectl set-ntp on` is fast, `systemctl status systemd-timesyncd` shows that it starts quickly.
 -  `timedatectl set-ntp off` → timesyncd stuck in "stopping" for a long time

This can also be done more directly with `systemctl start systemd-timesyncd` and `systemctl stop systemd-timesyncd` - the latter hangs.

**Comment by jelly** [comment]
Let's also retest it when systemd 250 has landed in the image refresh https://github.com/cockpit-project/bots/pull/2796

**Comment by KKoukiou** [comment]
Just rebased and let the arch tests rerun to check the current state.

**Comment by jelly** [comment]
As testPmProxySettings works, let's get that merged in a separate PR.

**Comment by jelly** [comment]
Done in https://github.com/cockpit-project/cockpit/pull/18071

**Comment by jelly** [comment]
This needs more work, closing.

**Pull request closed without merging**
