### PR TITLE
fix table formatting in ABRT log reports

### PR DESCRIPTION
**Pull request by clime**
Hello, this fixes table formatting in ABRT reports in logs panel. Partially related to 0ca254db.

screenshot from 2018-10-12 20-45-55
screenshot from 2018-10-12 20-45-45

### CODE REVIEW

**Comment by leomoty** [comment]
This is related to #9481 and #10098

**Comment by martinpitt** [comment]
This apparently breaks the [Abrt test cases](https://fedorapeople.org/groups/cockpit/logs/pull-10286-20181015-143232-6461f980-verify-fedora-28/log.html#3). The screenshot of that test looks rather curious.

**Comment by clime** [comment]
@martinpitt hello Martin, please, could you give me some tips how to reproduce it locally?

**Comment by martinpitt** [comment]
@clime: This is described in detail in https://github.com/cockpit-project/cockpit/blob/master/test/README.md . In short:

    bots/image-prepare fedora-28
    test/verify/check-journal TestJournal.testAbrtSegv -stv

should download the fedora 28 test VM image, prepare a VM, and run the test there. It will then sit at the failure and tell you how to connect your browser and ssh to it for inspection and debugging. I'm happy to talk you through on IRC (#cockpit on Freenode).

You can't reproduce the situation in the screenshot and test code interactively?

**Comment by clime** [comment]
> You can't reproduce the situation in the screenshot and test code interactively?

Well, the screenshort looks quite ok to me. I probably understand why this condition is not satisfied:
```
wait_js_cond(ph_is_present("#journal-entry-fields #accordion-markup .panel .panel-heading .panel-title .accordion-toggle:contains('core_backtrace')"))
```

but I have no idea about the forth failing tests:

50: testMtu (check_networking_mtu.TestNetworking)

which reports something about IP substring not being found. I might try to revert and try if my changes are the culrprit.

```
bots/image-prepare fedora-28
test/verify/check-journal TestJournal.testAbrtSegv -stv
```
Will give it a try!

**Comment by martinpitt** [comment]
Please ignore the check-networking test, that's an unrelated unstable test.

**Comment by clime** [comment]
I fixed the accordion structure.

**Comment by clime** [comment]
Thank you!

**Pull request merged**
