### PR TITLE
package.json: Update @patternfly/react-core package dependency

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "@patternfly/react-core": "3.120.8",
pkg/lib/cockpit-components-empty-state.jsx:} from '@patternfly/react-core';
pkg/machines/components/networks/networkList.jsx:import { Breadcrumb, BreadcrumbItem } from '@patternfly/react-core';
pkg/machines/components/storagePools/storagePoolList.jsx:import { Breadcrumb, BreadcrumbItem } from '@patternfly/react-core';
pkg/machines/components/vcpuModal.jsx:import { Tooltip } from '@patternfly/react-core';
pkg/storaged/storage-controls.jsx:import { Progress, ProgressMeasureLocation, ProgressVariant } from '@patternfly/react-core';
src/base1/Makefile.am:	$(AM_V_GEN) sed '/^@font-face/,/^$$/d' $(srcdir)/node_modules/@patternfly/react-core/dist/styles/base.css > $@.tmp && mv $@.tmp $@
```

**Comment by martinpitt** [comment]
@KKoukiou : Can you please check this for visual regressions?

**Comment by marusak** [comment]
> @KKoukiou : Can you please check this for visual regressions?

sorry @KKoukiou I was just checking it when Martin commented :)

**Comment by KKoukiou** [comment]
> > @KKoukiou : Can you please check this for visual regressions?
> 
> sorry @KKoukiou I was just checking it when Martin commented :)

So you already verified that there are no visual regressions?

**Comment by marusak** [comment]
> So you already verified that there are no visual regressions?

Yes, at least the basic check I always do with these updates.

**Pull request merged**
