### PR TITLE
Start minimizing the CSS for production

### LINKED ISSUE #5512: Minimized css files
@vansloswang says: Also there are some duplicated css style for different pkgs, for example, there are four pieces of a same log panel style in ./dist/networkmanager/network.css and ./dist/storaged/storage.css and ./dist/systemd/system.css and ./pkg/lib/journal.css, which named '.cockpit-log-panel .panel-heading'.

### PR DESCRIPTION
**Pull request by KKoukiou**
For CSS minimization mini-css-extract-plugin plugin is used, and for JS
minimization optimize-css-assets-webpack-plugin is used.

Followed the DOCS from here
https://webpack.js.org/plugins/mini-css-extract-plugin/#minimizing-for-production

Fixes #5512

### CODE REVIEW

**Comment by KKoukiou** [comment]
I found this suggestions in webpack documentation and thought to give it a try.

@martinpitt I am not sure how to check the size difference for production mode though.

The whole dist directory includes more files than what we include in the RPMs of course.

**Comment by martinpitt** [comment]
I just built without `--enable-debug` and compared the sizes of some sample dists. master:
```
❱❱❱ du -hsc dist/machines/*.{js,css}
1,4M	dist/machines/machines.min.js
80K	dist/machines/test-machines.min.js
80K	dist/machines/machines.css
8,0K	dist/machines/test-machines.css
1,6M	total

❱❱❱ du -hsc dist/systemd/*.{js,css}
544K	dist/systemd/hwinfo.min.js
28K	dist/systemd/logs.min.js
612K	dist/systemd/services.min.js
284K	dist/systemd/system.min.js
336K	dist/systemd/terminal.min.js
20K	dist/systemd/hwinfo.css
12K	dist/systemd/services.css
40K	dist/systemd/system.css
24K	dist/systemd/terminal.css
1,9M	total
```

This PR:
```
❱❱❱ du -hsc dist/machines/*.{js,css}
1,4M	dist/machines/machines.min.js
80K	dist/machines/test-machines.min.js
48K	dist/machines/machines.css
8,0K	dist/machines/test-machines.css
1,5M	total

❱❱❱ du -hsc dist/systemd/*.{js,css}
544K	dist/systemd/hwinfo.min.js
28K	dist/systemd/logs.min.js
612K	dist/systemd/services.min.js
284K	dist/systemd/system.min.js
336K	dist/systemd/terminal.min.js
16K	dist/systemd/hwinfo.css
8,0K	dist/systemd/services.css
28K	dist/systemd/system.css
16K	dist/systemd/terminal.css
1,9M	total
```
So it makes no measusable difference for the .js files, but the .css files go get quite a bit smaller as all whitespace gets removed.

I also tested a `make install` tree, where the files get gzipped, to see how much of that saving is left. master:
```
❱❱❱ du -hsc machines/*.{min.js,css}.gz
368K	machines/machines.min.js.gz
20K	machines/machines.css.gz
388K	total

❱❱❱ du -hsc systemd/*.{min.js,css}.gz
148K	systemd/hwinfo.min.js.gz
12K	systemd/logs.min.js.gz
168K	systemd/services.min.js.gz
88K	systemd/system.min.js.gz
92K	systemd/terminal.min.js.gz
8.0K	systemd/hwinfo.css.gz
4.0K	systemd/services.css.gz
12K	systemd/system.css.gz
8.0K	systemd/terminal.css.gz
540K	total
```

This PR:
```
❱❱❱ du -hsc machines/*.{min.js,css}.gz
368K	machines/machines.min.js.gz
12K	machines/machines.css.gz
380K	total

❱❱❱ du -hsc systemd/*.{min.js,css}.gz
148K	systemd/hwinfo.min.js.gz
12K	systemd/logs.min.js.gz
168K	systemd/services.min.js.gz
88K	systemd/system.min.js.gz
92K	systemd/terminal.min.js.gz
4.0K	systemd/hwinfo.css.gz
4.0K	systemd/services.css.gz
8.0K	systemd/system.css.gz
8.0K	systemd/terminal.css.gz
532K	total
```
So indeed it still helps a bit with the css. It seems terser-webpack-plugin doesn't help, and it's not worth adding it?

The commit message is confusing -- we already minimize JS for production (just apparently not the css, we just gzip it), and we already use mini-css-extract-plugin. So with the above it should just document the css minimization.

Finally, please change the webpack config to only do this in production mode. In development mode it's better to keep the original CSS, otherwise we go crazy when we look at it. :-)

Thanks!

**Comment by martinpitt** [comment]
This sentence makes me a bit nervous:

> Setting optimization.minimizer overrides the defaults provided by webpack, so make sure to also specify a JS minimizer:

Is our .js still getting properly minimized with that? did you check the sizes in a production build? Also, I don't see the `minimize:` boolean documented there; I suppose that just toggles it off and on? (If so, that's a neater way to write it than adding it to the object only `if (production):`).

**Comment by KKoukiou** [comment]
> This sentence makes me a bit nervous:
> 
> > Setting optimization.minimizer overrides the defaults provided by webpack, so make sure to also specify a JS minimizer:
> 
> Is our .js still getting properly minimized with that? did you check the sizes in a production build? Also, I don't see the `minimize:` boolean documented there; I suppose that just toggles it off and on? (If so, that's a neater way to write it than adding it to the object only `if (production):`).

Oh good catch.
So by overwriting the minimizer values we stop getting the JS minimized, which was by default minimized by TerserWebpackPlugin on production mode. And we didn't notice any size decrease in the JS because it was already processes with the Terser.
So in order to get the css minimization we need to explicitly have in the config the Terser plugin as well.

**Comment by martinpitt** [comment]
Is there a way how this could use the default `optimization.minimizer` setting and just amend to that? Or at least use whatever JS minifier we already use by default? It seems weird having to pull in a new npm module just to replicate what webpack already does anyway without it?

**Comment by KKoukiou** [comment]
> Ack, I understand this now, thanks! LGTM now. Just please make double-sure that this doesn't break development mode.

With development mode I don't see any *min* files,
[kkoukiou@sequoia cockpit-bak]$ ls -lh dist/machines/
total 17M
-rw-rw-r--. 1 kkoukiou kkoukiou  625 Sep  6 16:23 index.html
-rw-rw-r--. 1 kkoukiou kkoukiou  80K Sep  6 16:23 machines.css
-rw-rw-r--. 1 kkoukiou kkoukiou  99K Sep  6 16:23 machines.css.map
-rw-rw-r--. 1 kkoukiou kkoukiou 7.7M Sep  6 16:23 machines.js
-rw-rw-r--. 1 kkoukiou kkoukiou 7.9M Sep  6 16:23 machines.js.map
-rw-rw-r--. 1 kkoukiou kkoukiou 146K Sep  6 16:23 Makefile.deps
-rw-rw-r--. 1 kkoukiou kkoukiou  283 Sep  6 16:23 manifest.json
-rw-rw-r--. 1 kkoukiou kkoukiou    0 Sep  6 16:23 stamp
-rw-rw-r--. 1 kkoukiou kkoukiou 7.8K Sep  6 16:23 test-machines.css
-rw-rw-r--. 1 kkoukiou kkoukiou  11K Sep  6 16:23 test-machines.css.map
-rw-rw-r--. 1 kkoukiou kkoukiou 1.4K Sep  6 16:23 test-machines.html
-rw-rw-r--. 1 kkoukiou kkoukiou 242K Sep  6 16:23 test-machines.js
-rw-rw-r--. 1 kkoukiou kkoukiou 313K Sep  6 16:23 test-machines.js.map

**Comment by martinpitt** [comment]
Triggering tests now.

**Comment by martinpitt** [comment]
This breaks the build system in an interesting way:

    tar: Cowardly refusing to create an empty archive

**Comment by marusak** [comment]
Does this implement https://github.com/cockpit-project/cockpit/issues/5512 ?

**Comment by KKoukiou** [comment]
> Does this implement #5512 ?

According to the README of the module it does not remove duplicate CSS - no;
But I will confirm once again when I get back to this - thanks for pointing out this issue.

**Comment by martinpitt** [comment]
I pushed a rebase/conflict resolution. `make distcheck` works fine locally, and the semaphore logs seem gone, so let's get a new set of test results.

**Comment by martinpitt** [comment]
Hah, it works on Fedora 30 only, because there we run `--enable-debug`. This breaks production mode, and without that flag it's easy to reproduce.

**Pull request closed without merging**
