### PR TITLE
package.json: Update patternfly-react package dependency

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
npm-update in progress on 1-cockpit-7.
Log: https://209.132.184.41:8493/logs/npm-update-12104-20190619-110707/

**Comment by cockpituous** [comment]
npm-update in progress on 2-cockpit-8.
Log: https://209.132.184.41:8493/logs/npm-update-12104-20190619-105050/

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "patternfly-react": "2.36.1",
pkg/kdump/kdump-view.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/lib/cockpit-components-inline-notification.jsx:import { Alert } from 'patternfly-react';
pkg/machines/app.jsx:import { ToastNotificationList, ToastNotification } from 'patternfly-react';
pkg/machines/components/aggregateStatusCards.jsx:} from 'patternfly-react';
pkg/machines/components/create-vm-dialog/createVmDialog.jsx:import { Button, FormGroup, HelpBlock, Modal } from 'patternfly-react';
pkg/machines/components/deleteDialog.jsx:import { Modal, Button } from 'patternfly-react';
pkg/machines/components/diskAdd.jsx:import { Button, Modal } from 'patternfly-react';
pkg/machines/components/diskRemove.jsx:import { Tooltip, OverlayTrigger } from 'patternfly-react';
pkg/machines/components/infoRecord.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/machines/components/networks/network.jsx:import { Button } from 'patternfly-react';
pkg/machines/components/networks/networkList.jsx:import { Breadcrumb } from 'patternfly-react';
pkg/machines/components/nicEdit.jsx:} from 'patternfly-react';
pkg/machines/components/storagePools/createStoragePoolDialog.jsx:import { Button, FormGroup, HelpBlock, Modal } from 'patternfly-react';
pkg/machines/components/storagePools/storagePool.jsx:import { Button, Tooltip, OverlayTrigger, UtilizationBar } from 'patternfly-react';
pkg/machines/components/storagePools/storagePoolDelete.jsx:import { Button, Modal } from 'patternfly-react';
pkg/machines/components/storagePools/storagePoolList.jsx:import { Breadcrumb } from 'patternfly-react';
pkg/machines/components/storagePools/storageVolumeDelete.jsx:} from 'patternfly-react';
pkg/machines/components/vcpuModal.jsx:import { Button, Modal } from 'patternfly-react';
pkg/machines/components/vm/bootOrderModal.jsx:} from 'patternfly-react';
pkg/machines/components/vm/memoryModal.jsx:} from 'patternfly-react';
pkg/machines/components/warningInactive.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/machines/machines.less:// For patternfly-react and @patternfly/react-console
pkg/machines/machines.less:@import "~patternfly-react/dist/less/patternfly-react.less";
pkg/networkmanager/firewall.jsx:} from "patternfly-react";
pkg/ovirt/components/App.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/ovirt/components/infoRecord.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/packagekit/history.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/packagekit/updates.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/storaged/dialog.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/storaged/storage-controls.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/systemd/hwinfo.jsx:import { Alert, Button, ListView, Modal, OverlayTrigger, Tooltip } from 'patternfly-react';
```

**Comment by cockpituous** [comment]
npm-update in progress on 4-ci-srv-01.
Log: https://209.132.184.41:8493/logs/npm-update-12104-20190619-105555/

**Comment by cockpituous** [comment]
npm-update xterm done: https://github.com/cockpituous/cockpit/commits/npm-update-xterm-20190619-105656

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "xterm": "3.14.2"
pkg/docker/docker.js:import { Terminal } from "xterm";
pkg/lib/cockpit-components-terminal.jsx:import { Terminal as Term } from "xterm";
pkg/lib/console.css:@import "~xterm/lib/xterm.css";
pkg/lib/context-menu.css:    /* xterm accessibility tree has z-index 100 and we need to be in front of it
pkg/machines/machines.less:@import "~xterm/lib/xterm.css";
pkg/systemd/terminal.jsx:                    "TERM=xterm-256color",
test/avocado/selenium-base.py:        terminal = self.wait_xpath("//*[contains(@class, 'terminal xterm')]")
test/avocado/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer')
test/avocado/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer', cond=invisible)
test/avocado/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer')
test/avocado/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer', cond=invisible)
test/avocado/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer')
test/verify/check-active-pages:                return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-pages:            return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-realms:                return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-terminal:                return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-terminal:            b.wait_attr(".xterm-viewport", "style", style)
test/verify/check-terminal:        b.wait_attr(".xterm-viewport", "style", white_style)
test/verify/machineslib.py:        b.wait_present("div.terminal canvas.xterm-text-layer") # if connected the xterm canvas is rendered
test/verify/machineslib.py:        b.wait_present("div.terminal canvas.xterm-text-layer")
test/verify/machineslib.py:        b.wait_not_present("div.terminal canvas.xterm-text-layer")
test/verify/machineslib.py:        b.wait_present("div.terminal canvas.xterm-text-layer")
```

**Comment by marusak** [comment]
```
ERROR in ./pkg/machines/machines.less (./node_modules/css-loader?sourceMap&minimize=!./node_modules/less-loader/dist/cjs.js?sourceMap&compress=false!./pkg/machines/machines.less)
    Module build failed (from ./node_modules/less-loader/dist/cjs.js):
    
    
    Property '$color-pf-black-900' is undefined
          in undefined (line undefined, column undefined)
```

**Comment by marusak** [comment]
The difference is that patternfly-react now introduces date-time-picker and it needs this variable. This is defined only in patternfly package. But other components in patternfly react use different colors defined in patternfly package only as well and it works.
Needs more investigation if the problem is on our side or if this version is really broken.

**Comment by martinpitt** [comment]
@KKoukiou : Thanks for fixing! Can you please resolve the conflict?

**Comment by allisonkarlitskaya** [comment]
This is failing on semaphore because it needs to be rebased on master to include the commits from #12255.

**Comment by martinpitt** [comment]
Rebased.

**Pull request merged**
