### PR TITLE
tools: Allow make-srpm and make-rpms to be used without git clone

### PR DESCRIPTION
**Pull request by stefwalter**
We just use all the files in the directory for the sources of
the RPM.

### CODE REVIEW

**Comment by stefwalter** [comment]
@jscotka This should help with using tools/make-rpms to build on the CI target VM, if that's what you want to do.

**Comment by jscotka** [comment]
Cool, it is also good for another people who would like to compile cockpit from zip archive without .git
Thanks

**Comment by dperpeet** [comment]
Is there a reason why we want to keep the behavior that we only use committed files?

**Comment by stefwalter** [comment]
> Is there a reason why we want to keep the behavior that we only use committed files?

Because we each have gigabytes of data sitting around in our checkouts.

**Pull request closed without merging**
