### PR TITLE
Use external libgsystem

### PR DESCRIPTION
**Pull request by cgwalters**
See https://mail.gnome.org/archives/desktop-devel-list/2014-February/msg00028.html
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
npm-update in progress on 2-cockpit-10.
Log: https://209.132.184.41:8493/logs/npm-update-196-20190711-100101/

**Comment by cockpituous** [comment]
npm-update redux done: https://github.com/cockpituous/cockpit/commits/npm-update-redux-20190711-100202

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "react-redux": "6.0.1",
package.json:    "redux": "4.0.4",
package.json:    "redux-thunk": "2.3.0",
pkg/machines/reducers.js:import { combineReducers } from 'redux/dist/redux';
pkg/machines/selectors.js: * Reference: http://redux.js.org/docs/recipes/ComputingDerivedData.html
pkg/machines/store.js:import { createStore, applyMiddleware, compose } from 'redux';
pkg/machines/store.js:import thunkMiddleware from 'redux-thunk';
webpack.config.js:/* HACK: To get around redux warning about reminimizing code */
webpack.config.js:    aliases["redux/dist/redux"] = "redux/dist/redux.min.js";
```

**Comment by martinpitt** [comment]
Please ignore the last three comments -- that's a bug in our reworking of our bots.

**Pull request closed without merging**
