### PR TITLE
Use noVNC via patternfly-react

### PR DESCRIPTION
**Pull request by mareklibra**
The in-browser VNC component is externalized to patternfly-react for it's wider reuse by other projects.

With this change, the noVNC dependency version is updated to `1.0.0` from recent `0.6.2`.

Checklist: 
- [x] depends on https://github.com/patternfly/patternfly-react/pull/288 (`VncConsole` in patternfly-react); increase patternfly-react version accordingly
- [x] depends on https://github.com/cockpit-project/cockpit/pull/8402 (SerialConsole)
- [x] replace other noVNC occurances by the `VncConsole` component
- [x] #9263 - `React` instead of `react-lite` since later versions of patternfly-react require it (i.e. use of `<Fragment>`)

### CODE REVIEW

**Comment by mareklibra** [comment]
Rebased, since #8402 and https://github.com/patternfly/patternfly-react/pull/288 changed

**Comment by mareklibra** [comment]
This requires full `react` (#9263)

**Comment by martinpitt** [comment]
#9263 landed, so this can now go forward. This is also important to avoid pulling in two different noVNCs now, see commit ccb6c5ce856f388d .

**Comment by martinpitt** [comment]
Looks like this breaks [testInlineConsole](https://fedorapeople.org/groups/cockpit/logs/pull-8894-20180923-091515-c8a200aa-verify-debian-stable/log.html#109), this probably changed identifiers and such which needs to be adjusted in the tests.

**Comment by martinpitt** [comment]
Adjusted the tests.

**Pull request merged**
