### PR TITLE
images: Install libosinfo-bin on debian OSes

### PR DESCRIPTION
**Pull request by petervo**
* [x] image-refresh ubuntu-stable
 * [x] image-refresh debian-stable
 * [x] image-refresh ubuntu-1604
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-4vwr9.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8353-20180103-214747/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-stable-20180103-222222

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-k8sq1.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8353-20180103-222323/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-stable-20180103-225555

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-c4qg4.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8353-20180103-225555/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-testing-20180103-232727

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-vg1cw.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8353-20180103-232929/

**Comment by cockpituous** [comment]
image-refresh ubuntu-1604 done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-1604-20180103-235555

**Comment by petervo** [comment]
@mvollmer the storage errors here in debian-testing are related to the upgrade same as #8323. Mounts and unmounts happen but then seem to revert state. Though running the commands on the command line work.

**Comment by mvollmer** [comment]
I can't find `debian-testing-2566b6eeb53893bc619e26f9e0d64bceb48320f23830a3f5422cd377f932a11f.qcow2`... Where would it be?

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-ff5xz.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8353-20180109-101919/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-testing-20180109-104747

**Comment by mvollmer** [comment]
> @mvollmer the storage errors here in debian-testing are related to the upgrade same as #8323. Mounts and unmounts happen but then seem to revert state. Though running the commands on the command line work.

This looks like mount namespace bogosity to me.  I can't be sure, but it looks like sshd is running in its own "mnt" namespace:

```
# lsns 
        NS TYPE   NPROCS   PID USER             COMMAND
...
4026532316 mnt         6   503 root             /usr/sbin/sshd -D
...
```

This would mean that one can't mount/unmount filesystems for the rest of the system in a ssh session, no?  Doesn't make sense to me.  If this is a bug, let's use "known issue" instead of the workaround I pushed here.

**Comment by martinpitt** [comment]
> This would mean that one can't mount/unmount filesystems for the rest of the system in a ssh session, no?

Only if its mount namespace is "private" or "slave". A shared namespace would still work. Also, you should check the process in the login session, not the master sshd; while it's unlikely that it does that, the session child could re-join the "host" namespace, and just the daemon gets isolated (although I wouldn't know what purpose that would serve). Either way, if ssh sessions now run in a disjoint mount namespace that's definitively a bug (or unintended side effect).

**Comment by martinpitt** [comment]
[This failure](https://fedorapeople.org/groups/cockpit/logs/pull-8353-20180110-133838-71fa5629-verify-debian-testing/log.html#96) might need a naughty override here (if it's new) or in a separate PR (if it's a flake):
```
# testDelete (check_machines.TestMachines)
#
Warning: Permanently added '[127.0.0.2]:2401' (ECDSA) to the list of known hosts.
Started /usr/bin/chromium-browser (pid 37399) on port 10099
ftruncate() failed: Permission denied

DevTools listening on ws://127.0.0.1:10099/devtools/browser/95651ac1-3de9-40b8-a09c-3fb6094d9a48
[0110/135006.671567:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 37666: Permission denied (13)
[0110/135007.563221:ERROR:zygote_host_impl_linux.cc(268)] Failed to adjust OOM score of renderer with pid 37769: Permission denied (13)
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 401 (Authentication failed)","timestamp":1515592208059.24,"url":"http://127.0.0.2:9291/cockpit/login","networkRequestId":"37769.8"}
Unexpected journal message 'audit: type=1400 audit(1515592209.900:38): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=962 comm="libvirtd" requested_mask="send" denied_mask="send" signal=kill peer="unconfined"'
Unexpected journal message 'audit: type=1400 audit(1515592210.092:39): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=962 comm="libvirtd" requested_mask="send" denied_mask="send" signal=kill peer="unconfined"'
Unexpected journal message 'audit: type=1400 audit(1515592210.316:40): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=962 comm="libvirtd" requested_mask="send" denied_mask="send" signal=kill peer="unconfined"'
Journal extracted to TestMachines-testDelete-debian-testing-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 671, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 806, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1515592209.900:38): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=962 comm="libvirtd" requested_mask="send" denied_mask="send" signal=kill peer="unconfined"
```

**Comment by martinpitt** [comment]
[testUsed](https://fedorapeople.org/groups/cockpit/logs/pull-8353-20180110-143434-71fa5629-verify-debian-testing/log.html#70) failed again the same way, retrying again to make sure.

**Comment by martinpitt** [comment]
OK, so [testUsed](https://fedorapeople.org/groups/cockpit/logs/pull-8353-20180110-151515-71fa5629-verify-debian-testing/log.html#70) is busted. @mvollmer, any idea?

**Comment by mvollmer** [comment]
> OK, so testUsed is busted. @mvollmer, any idea?

Same issue, the "mount ..." done earlier via SSH is not seen by udisksd.

**Comment by martinpitt** [comment]
There is a  weird race condition in `distcheck` which sometimes makes semaphore fail like this:
```
 ( cd '/tmp/source/cockpit-154.x/_inst/share/cockpit/static' && rm -f login.min.html login.po.html login.po.ca.html login.po.cs.html login.po.da.html login.po.de.html login.po.es.html login.po.fi.html login.po.fr.html login.po.hr.html login.po.hu.html login.po.ja.html login.po.ko.html login.po.my.html login.po.nl.html login.po.pa.html login.po.pl.html login.po.pt.html login.po.pt_BR.html login.po.tr.html login.po.uk.html login.po.zh_CN.html )
/bin/bash: line 2: cd: /tmp/source/cockpit-154.x/_inst/share/cockpit/static: No such file or directory
 ( cd '/tmp/source/cockpit-154.x/_inst/lib/systemd/system' && rm -f cockpit.socket cockpit.service )
Makefile:7364: recipe for target 'uninstall-nodist_staticDATA' failed
make[1]: *** [uninstall-nodist_staticDATA] Error 1
make[1]: *** Waiting for unfinished jobs....
```

This isn't new from this PR, it has happened every now and then for a long time. But this PR seems to be exceptionally unlucky, it's the third time I retry semaphore for this :-( Any takers?

**Pull request closed without merging**
