### PR TITLE
storage: Remove old dialog framework

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by martinpitt** [comment]
I have a really hard time getting the [debian-stable tests](https://fedorapeople.org/groups/cockpit/logs/pull-10168-20181009-053030-a5a3e09e-verify-debian-stable/log.html) to succeed. Retrying once more for log comparison, but this needs fixing even if it's not a direct regression from this PR.

**Comment by martinpitt** [comment]
Exactly the same failures on retry :-(

**Comment by mvollmer** [comment]
> Exactly the same failures on retry :-(

I'll try to reproduce.  The failures themselves look like known flakes, and maybe we can finally get to the bottom of them...

**Comment by mvollmer** [comment]
There was a bug in the code that retries starting/stopping until it works.  UDisks2 seems to be pretty crashy, though, and not all crashes are caught by the pattern for #7854, I think.

**Comment by martinpitt** [comment]
Thanks, nice catch! The only relevant failure now is [this one](https://fedorapeople.org/groups/cockpit/logs/pull-10168-20181009-133434-0736f3a7-verify-debian-testing/log.html#108), retrying.

**Comment by martinpitt** [comment]
@mvollmer: As we can't push to master any more, and push-rewrite currently only works for your own branch (or am I missing something?), can you please run push-rewrite yourself to fold in the fixup and add a Closes#?

**Comment by mvollmer** [comment]
@martinpitt I used `push-rewrite`, but:

```
./bots/push-rewrite mvollmer 
+ git rev-parse --abbrev-ref HEAD
+ git rev-parse storage-remove-old-dialog-framework
+ git rev-parse mvollmer/storage-remove-old-dialog-framework
+ git diff --stat 0775a03da7a1861a15b5e15923b8b6918ee14f62 0736f3a76ab6c062cc2bc428d43af925ae1b34bc
+ git push --force-with-lease=storage-remove-old-dialog-framework:0736f3a76ab6c062cc2bc428d43af925ae1b34bc mvollmer storage-remove-old-dialog-framework:storage-remove-old-dialog-framework
Counting objects: 38, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (38/38), done.
Writing objects: 100% (38/38), 12.33 KiB | 4.11 MiB/s, done.
Total 38 (delta 35), reused 0 (delta 0)
remote: Resolving deltas: 100% (35/35), completed with 31 local objects.
To github.com:mvollmer/cockpit.git
 + 0736f3a76...0775a03da storage-remove-old-dialog-framework -> storage-remove-old-dialog-framework (forced update)
Copying results for container/kubernetes
statuses/0775a03da7a1861a15b5e15923b8b6918ee14f62
{"message":"No commit found for SHA: 0775a03da7a1861a15b5e15923b8b6918ee14f62","documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}
Traceback (most recent call last):
  File "./bots/push-rewrite", line 64, in <module>
    sys.exit(main())
  File "./bots/push-rewrite", line 61, in main
    api.post("statuses/" + local, old_statuses[key])
  File "/home/mvo/work/cockpit/bots/task/github.py", line 201, in post
    raise RuntimeError("GitHub API problem: {0}".format(response['reason'] or status))
RuntimeError: GitHub API problem: Unprocessable Entity
```

So the new commit wasn't yet visible from the GitHub API.  We need to retry a couple of times in push-rewrite, I guess.

**Pull request merged**
