### PR TITLE
machines: Fix storage pool and network icons

### PR DESCRIPTION
**Pull request by garrett**
Split the icon fixes for the storage pool and network cards out from #14686.

### CODE REVIEW

**Review by marusak — CHANGES_REQUESTED** [review]
Right, I remember when I saw PR that introduced this I was asking if we want it to look like that, so apparently we don't :) But improving step by step is the way how to actually see changes gradually building up.

This PR overwrites **only** PF classes, which indicates that there is some problem in PF. Could it then be in `pkg/lib/patternfly/patternfly-4-overrides.scss` with also some report so we know once we can drop it? (I feel like when we define custom css we should target our custom classes and ids or whatnot so we can later grab if those elements are still being used [good example was when I was rewriting navigation I dropped huge amount of css but pretty sure there is bunch dangling around that I was not confident do drop as it was targeting PF3 classes])

**Comment by garrett** [comment]
1. We want larger icons here. To do that, we need to use `--pf-global--icon--FontSize--lg`.
   - The docs are wrong, so I filed an issue @ https://github.com/patternfly/patternfly-org/issues/2236

2. The alignment is wrong, as this is hardcoded to a smaller size icon _and_ uses inline CSS, which our CSP forbids.
   - I've filed a bug @ https://github.com/patternfly/patternfly/issues/3628.

3. The icons shouldn't be blue by default.
   - Icons are generally not a link color in PF. This is a usage issue, therefore it's Cockpit-related.

4. The icons don't have a margin between the icon and the text.
   - I don't see this as an issue in PF upstream; it's a Cockpit bug here, I guess?
   - I didn't file a bug in PF, as it looks like a Cockpit issue.

**Comment by KKoukiou** [comment]
>     1. We want larger icons here. To do that, we need to use `--pf-global--icon--FontSize--lg`.
>        
>        * The docs are wrong, so I filed an issue @ [patternfly/patternfly-org#2236](https://github.com/patternfly/patternfly-org/issues/2236)
> 
>     2. The alignment is wrong, as this is hardcoded to a smaller size icon _and_ uses inline CSS, which our CSP forbids.
>        
>        * I've filed a bug @ [patternfly/patternfly#3628](https://github.com/patternfly/patternfly/issues/3628).

We have a local override for that allready, I had reported this bug some time ago. 
https://github.com/cockpit-project/cockpit/blob/master/pkg/lib/patternfly/patternfly-4-overrides.scss#L35..L40

If the override does not work for you, maybe I have something wrong and that has to be fixed in that file.

> 
>     3. The icons shouldn't be blue by default.
>        
>        * Icons are generally not a link color in PF. This is a usage issue, therefore it's Cockpit-related.

You are right, they are blue because they are part of the link. If we want them black we should take them out of the button. Which I can do, if you don't know how.
> 
>     4. The icons don't have a margin between the icon and the text.
>        
>        * I don't see this as an issue in PF upstream; it's a Cockpit bug here, I guess?
>        * I didn't file a bug in PF, as it looks like a Cockpit issue.

I see the link button with icon from here:
https://www.patternfly.org/v4/components/button
Is the spacing different?

**Comment by marusak** [comment]
> You are right, they are blue because they are part of the link. If we want them black we should take them out of the button. Which I can do, if you don't know how.

right. It should be out of button or if icon in buttons should be black (what this PR overwrites) then it should be reported, as it uses standard `icon` property for PF4 buttons.

**Review by KKoukiou — COMMENTED** [review]
I will send a commit to take the icons out of the buttons.
Then the overrides code should go in pkg/machines/components/aggregateStatusCards.scss

**Comment by KKoukiou** [comment]
@garrett I sent a commit above yours, achieving 'almost' the same design you wanted without CSS (one line only).
I also made the while cards selectable. I did not like how before the Icon was part of the button, thus clickable, but th color of it indicated the opposite. It was black like the icons on the right of the cards, which are not responsive.

So now the while card is clickable.

**Comment by garrett** [comment]
@KKoukiou: This looks great! Thanks for turning it into PF widgets instead of CSS overrides!

(I'd approve, but I'm the author of the PR, so I cannot. :wink:)

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
