### PR TITLE
shell: Move UDisks2 storage into its own package.

### PR DESCRIPTION
**Pull request by mvollmer**
This makes it optional and we can provide alternative storage packages
or leave it out completely.  The code is all still in the same place
in the "shell" package to keep this change small.

### CODE REVIEW

**Comment by mvollmer** [comment]
Does this make sense?

**Comment by stefwalter** [comment]
Lots to discuss here, heh. I guess lets start with the broad questions.

 * Are we keeping the udisks2 based UI long term?
 * Can both the udisks2 and storaged based UI be usable at the same time on a given system?

**Comment by mvollmer** [comment]
> Are we keeping the udisks2 based UI long term?

I don't know... That depends on how soon storaged 2 appears in the places where we want to have a storage UI, of course.

> Can both the udisks2 and storaged based UI be usable at the same time on a given system?

Technically yes, I do that during development, but it doesn't really make sense.

**Comment by stefwalter** [comment]
> I don't know... That depends on how soon storaged 2 appears in the places where we want to have a storage UI, of course. Technically yes, I do that during development, but it doesn't really make sense.I don't know... 

So I guess we need to decide on these things before we merge this right?

For example, this commit hard codes 'udisks2' into URIs and doesn't use the generic term in 'storage'. That would only make sense if we wanted to include both at the same time, and keep them that way long term.

Normally when we have alternatives, not usable at the same time, I think we decided to use symlinks to claim the generic name (like 'storage').

**Comment by mvollmer** [comment]
> For example, this commit hard codes 'udisks2' into URIs and doesn't use the generic term in 'storage'.

Yes, that is a wart.  To remove it, I think we need to change the logic in index.js a bit for detecting legacy pages. Also, we would need to make the choice between udisk2 and storaged a configure option.

That would be a worthwhile improvement in any case, I think.

**Comment by mvollmer** [comment]
> So I guess we need to decide on these things before we merge this right?

It would help, but we can always adapt later.  The choice is between making the old  code optional and remove it later, or removing it immediately.  Making it optional gives us more flexibility, and doesn't have a terribly high cost (other than keeping unloved code alive).

**Comment by stefwalter** [comment]
> The choice is between making the old code optional and remove it later, or removing it immediately. Making it optional gives us more flexibility, and doesn't have a terribly high cost (other than keeping unloved code alive).

I think my choice would be to merge the new storage code and remove the old. That would mean the new code would need to be ready and dependencies be ready, etc. The storaged dependency is only runtime right? It would just be nice to make sure we don't create more work for ourselves on the distros where we have to do packaging ourselves.

**Comment by mvollmer** [comment]
Let's close this since we don't want this.

**Pull request closed without merging**
