### PR TITLE
ws: Only set language on login

### PR DESCRIPTION
**Pull request by petervo**
Alternative to #7695. Launch the new session with a language. This allows the bridge to be translated
as well as fixes cache issues like #4784

Reopening as we need to figure out what to do about Oauth or kerberos authentication flows where users don't see the login form and thus are unable to select a language.

### CODE REVIEW

**Comment by martinpitt** [comment]
Random idea: we could keep the language selector in the user menu as it is today for these cases, but point out that it only affects the next login. Although I figure that wouldn't actually be simple to implement? As soon as you update the cookie, the next page load would already use the new language, we'd run into the caching issues again, and we might end up with a wild mix of old and new language?

**Comment by petervo** [comment]
We wouldn't end up with a mix because this PR removes the package language detection logic from cockpitpackages. Might be a little anyoning to the user though, an alternative might be to log them out from that dialog when they the select a new language. Though i'm not sure that's ideal either.

**Comment by garrett** [comment]
> we could keep the language selector in the user menu as it is today for these cases, but point out that it only affects the next login

If language switching is implemented in this way, it would be a nice touch to use the select language's string for the notification and action works (such as a "Sign Out" button), to make it clearer what will happen.

**Comment by marusak** [comment]
Needs to rebase to master since #12367 changed tests names

**Comment by martinpitt** [comment]
Closing for now, to clean up our stale PR list. This is a great fix, but in the next months we have more urgent issues to address. This is mostly blocked on the fundamental design problem that with any SSO authentication there won't be a login page. That doesn't seem that bad, as the browser's requested language should usually be fine, but it was raised above as a concern.

**Pull request closed without merging**
