### PR TITLE
machines: replace PF-3 breadcrumbs with the PF-4 component

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
Previously: 
Screen Shot 2019-10-15 at 10 11 09

Now:
Screen Shot 2019-10-15 at 11 14 21

There is indeed some difference in the padding above the component.
@andreasn should this be adjusted to how it was before?

**Comment by andreasn** [comment]
> There is indeed some difference in the padding above the component.
> @andreasn should this be adjusted to how it was before?

I think this is because it doesn't have the padding from the `breadcrumb` class in [patternfly-overrides](https://github.com/cockpit-project/cockpit/blob/3e697de5eddebc9c59af9c2764d5ac481fe9349f/src/base1/patternfly-overrides.less#L651) any more.

I was looking at a [Patternfly example page](https://www.patternfly.org/v4/documentation/react/demos/pagelayout/pagelayoutdefaultnav/), and it seems it puts the `nav` element in a `section` element that adds the needed padding.
`<section class="pf-c-page__main-breadcrumb"></section>`

**Comment by andreasn** [comment]
But yeah, if you want to add that padding by hand, and not involve the section element, I think that's OK too.

**Comment by KKoukiou** [comment]
> But yeah, if you want to add that padding by hand, and not involve the section element, I think that's OK too.

Fixed.

**Pull request merged**
