### PR TITLE
Drop cockpit-kubernetes

### PR DESCRIPTION
**Pull request by martinpitt**
It's not built any more in any distribution supported by master.

This also finally allows us to drop angular.

### CODE REVIEW

**Comment by marusak** [comment]
`cockpit-stub` is not packaged (most likely needs to be removed as well). On Fedora `error: Installed (but unpackaged) file(s) found: /usr/libexec/cockpit-stub`, on Debian ` usr/lib/cockpit/cockpit-stub exists in debian/tmp but is not installed to anywhere`

**Comment by martinpitt** [comment]
Thanks @marusak! still downloading images, then I can locally test/run image-prepare *brown paperbag*

**Comment by martinpitt** [comment]
Breaks the playground/translate page, needswork.

**Comment by KKoukiou** [comment]
@martinpitt I just did checkout your branch locally, git grep kube still gives a lot of results. But maybe they are totally unrelated.
For example:
bots/images/scripts/lib/kubernetes.setup
bots/tests-scan

I am not familiar with the package at all, so it's hard to say if these are related.

**Comment by martinpitt** [comment]
@KKoukiou : We keep the openshift image in bots/, as we still have that code (and want to test it) in the stable rhel-x.y branches. There's also some example which is about running cockpit/ws in kubernetes, not maintaining kubernetes with cockpit, so that's also legit.

**Comment by KKoukiou** [comment]
> @KKoukiou : We keep the openshift image in bots/, as we still have that code (and want to test it) in the stable rhel-x.y branches. There's also some example which is about running cockpit/ws in kubernetes, not maintaining kubernetes with cockpit, so that's also legit.

Makes sense. What I find a bit confusing is that we use the script from master to create images that are meant for testing rhel-x.y branches. It would be more sensible workflow to my head if we would use the script from that rhel-x.y branch to test the code there.
But I am sure there is good enough reason we don't have it that way :)

**Comment by martinpitt** [comment]
@KKoukiou : It doesn't make sense to have stable bots/ branches. There is no such a thing like a "stable rhel-8-1" or a "stable debian-testing", as these change in reality all the time. So even our stable branches must be able to run on current images.

What we ideally *should* do is to run the stable branch tests when we refresh images. We don't right now, but once we split bots/ into a separate project, it would actually be possible to do that.

**Comment by martinpitt** [comment]
Tests are good enough, remaining failures are unrelated.

**Comment by martinpitt** [comment]
@larskarlitski : I googled around, and I couldn't find any other user.

**Pull request merged**
