### PR TITLE
Update the CSS for on-off to hide inactive text

### PR DESCRIPTION
**Pull request by stefwalter**
Don't show both 'On' and 'Off'. Use a look more like patternfly
where only the currently selected option is shown.

### CODE REVIEW

**Comment by stefwalter** [comment]
This could be a fix for #4462

**Comment by stefwalter** [comment]
screenshot from 2016-05-25 14-36-39

**Comment by andreasn** [comment]
Still looks and functions slightly different from the switch in Patternfly.
https://www.patternfly.org/widgets/#bootstrap-switch

I can do a separate pull request that changes from On/Off to ON/OFF and fixes the button to look more similar. It would also be good if we could make the hit target bigger, so that it's easier to change the state, regardless where on the widget you're clicking, but I have no idea how to achieve that.

But regardless of those other changes, I think this is a good change and can go in like this.

**Comment by andreasn** [comment]
Code-wise I'm a little concerned about using the big !important hammer here, but if it's the only way, that's how it is.

**Comment by stefwalter** [comment]
> Code-wise I'm a little concerned about using the big !important hammer here, but if it's the only way, that's how it is.

We're overriding the btn-group stuff from bootstrap (which is why this is a CSS only widget), and I couldn't figure out how to make that work with out ```!important```

**Comment by andreasn** [comment]
I'll poke at the css a bit and see if I can find a way to do it without !important
If not, important it is

**Comment by dperpeet** [comment]
closed in 5d43f1dc11e1f1379e52123a034818b998b2b58c

**Comment by dperpeet** [comment]
@andreasn I closed this a bit prematurely, by accident. Let me know if we should fix the css up.

**Comment by andreasn** [comment]
No worries.
I've made a followup pull request addressing the !important rules that stood out to me in the review. #4493

Please try that out and see that it didn't cause any regressions.

**Pull request closed without merging**
