### PR TITLE
networkmanager: Don't show unmanaged interfaces

### PR DESCRIPTION
**Pull request by stefwalter**
Don't show them in the Devices listing

### CODE REVIEW

**Comment by dperpeet** [comment]
Why do we want to remove these from the listing?

**Comment by stefwalter** [comment]
People mark interfaces with NM_CONTROLLED=no to take their life into ... no I mean ... tell NetworkManager to stop auto-configuring or involving itself in a given interface. The intent is that they want to configure this interface elsewhere (either via scripts, tools, or another daemon), without NetworkManager.

Since the current network interface is a UI for NetworkManager, we should respect those wishes.

This is a bug reported by people trying to use Cockpit on nodes where another network configuration service (vdsm) is in play:

https://bugzilla.redhat.com/show_bug.cgi?id=1330552

But the actual case is broader. NM_CONTROLLED=no is the way to tell NetworkManager "hands off".

**Comment by stefwalter** [comment]
Added link to the commit message. Also added a note to the feature-networkmanager documentation about NM_CONTROLLED=no.

**Comment by dperpeet** [comment]
That makes sense! Adding the link is good.

**Comment by mvollmer** [comment]
Also see https://github.com/cockpit-project/cockpit/issues/1308

**Pull request closed without merging**
