### PR TITLE
debian: Relax lintian source overrides

### PR DESCRIPTION
**Pull request by martinpitt**
Currently testsuite-prepare for debian-testing fails on

    E: cockpit source: source-is-missing dist/kdump/test-config-client.js line length is 566 characters (>512)
    E: cockpit source: source-is-missing dist/sosreport/sosreport.js line length is 687 characters (>512)
    E: cockpit source: source-is-missing dist/kubernetes/scripts/test-images.js line length is 12352 characters (>512)

Relax the override to cover these files too. As the entirety of dist/ is
autogenerated, all *.js files are okay to not be preferred form of
modification.

----
Note: It's not entirely clear why this failure doesn't break CI. E. g. PR #5809 ran recently and lintian succeeds there. But this always happens locally, both for @mvollmer and myself.

### CODE REVIEW

**Comment by dperpeet** [comment]
failure on debian testing, let's see if it happens again:
```
+ lintian /var/tmp/build-results/cockpit_0-1_amd64.changes
warning: the authors of lintian do not recommend running it with root privileges!
Command 'cd /var/tmp; ./debian-testing.install --build --install --skip 'cockpit-ostree' 'cockpit-130.x.tar.gz'' returned non-zero exit status 1
Traceback (most recent call last):
  File "./verify/run-tests", line 39, in install
    subprocess.check_call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['/build/cockpit/test/verify/testsuite-prepare']' returned non-zero exit status 2
```

**Comment by dperpeet** [comment]
problem happens again

**Comment by martinpitt** [comment]
I did some debugging/ramblings in PR #5826, pushed another commit to make the lintian errors appear at all and on the right place. Let's use 5826 to discuss possible more general logging changes.

**Comment by martinpitt** [comment]
Ah, with the stderr fix I actually see the lintian errors now, stupid little thing (it was expecting `dist/*.js *`, but in production the error messages end in `.js`, i. e. no space). I wonder why locally I get the " ... line length.." suffix always..

Fix pushed.

**Comment by dperpeet** [comment]
tests pass for debian-8 and debian-testing

**Pull request closed without merging**
