### PR TITLE
ovirt: disable Create VM Dialog for oVirt

### PR DESCRIPTION
**Pull request by mareklibra**
The dialog is not yet implemented for oVirt, so let's disable it.

Fixes: https://github.com/cockpit-project/cockpit/issues/8767

### CODE REVIEW

**Comment by mareklibra** [comment]
From `pkg/ovirt`:
01_ovirt

---
For reference `pkg/machines`:
02_libvirt

**Comment by martinpitt** [comment]
@mareklibra: Instead of showing the button with a tooltip and making it not do anything, can it just be hidden entirely?

**Comment by mareklibra** [comment]
Discussion in https://github.com/cockpit-project/cockpit/issues/8767 suggested to not hide it.

The "Create oVirt VM" feature is planed (without a time-frame ATM). 
The `pkg/ovirt` is presented as a "superset" of `pkg/machines`, so from this POV it might make sense to not hide it.

@andreasn , @garrett ?

**Comment by mareklibra** [comment]
Rebased.

**Comment by garrett** [comment]
1. What does "Host to Maintenance" mean?
2. Having create is still wrong here, as it is an action link and you cannot perform the action.

Perhaps there should be a message in the top-right that states something about being managed externally with a details link. Or a link to go to oVirt / CloudForms / or whatever is managing the VMs. (I'm saying perhaps here, because I don't know enough details.)

**Comment by mareklibra** [comment]
> What does "Host to Maintenance" mean?

It's an oVirt action evacuating VMs from particular host (means migrating them elsewhere in cluster) and removing the host from scheduling so the administrator can perform his tasks while not influencing processing of VMs (like shut down the host).

> Having create is still wrong here, as it is an action link and you cannot perform the action.

I'm fine redesigning the actions but can we split it to another issue / PR, please?

The Create VM dialog implementation for oVirt in Cockpit is planed, this is just a temporarily solution.
The FQDN of oVirt engine is in most cases known to the `pkg/ovirt`, so even link to external application might be feasible.

**Pull request merged**
