### PR TITLE
bots: Put rhel-8 images into the RedHat store

### PR DESCRIPTION
**Pull request by martinpitt**
This is not a public image.

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-c31xh.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8985-20180412-100202/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8985-20180412-100202/

**Comment by martinpitt** [comment]
For heaven's sake, what's up with our bots now :-(
```
ERROR    Error: --disk path=/build/tmp/rhel-8d1lgz31i.qcow2,format=qcow2: too many remote strings: 24996 > 16384,in parameter 'names' for 'virStoragePoolListVolumes'
```
This hit me in #8984 too.

**Comment by martinpitt** [comment]
Actually, no reason to force an image refresh here - I just moved the current rhel-8 image into the private store, and retriggered the rhel-8 test to prove that it still works from there. The current image-refresh failure on the bot should not block this.

**Pull request merged**
