### PR TITLE
bots: Update selenium hub and chrome to latest 3.x version

### PR DESCRIPTION
**Pull request by martinpitt**
bots: Update selenium hub and chrome to latest 3.x version

2.x is two years old, testing with these old browsers isn't really
useful any more. Upgrade hub and chrome to the latest 3.x version, which
can now  use the "3" tag.

Unfortunately node-firefoxNone does not work with our tests, it causes a
`KeyError: 'sessionId'` with Fedora 27's python2-selenium. (See the PR
for debug information). So keep firefox at the old 2.x for now, until we
run the Selenium tests on Fedora 28. 

The chrome browser name changed in the Grid Console (`googlechrome` →
`chrome`). To avoid false positives, check for the `browserName:` prefix
in the JSON dump.

 * [x] image-refresh selenium

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh selenium done: https://github.com/cockpituous/cockpit/commits/image-refresh-selenium-20180515-093535

**Comment by martinpitt** [comment]
I'm unable to get `selenium/node-firefox:3` to work. The test always times out with "Unable to attach remote Browser on hub". On the grid console I see

grid-firefox-3

The firefox logo is grayed out, the tooltip bubble says "POST - /session executing ...".

With tag `:2.53.1` the firefox tests still work. There it seems to use, or at least offer, the obsolete "Remote Control" protocol:

grid-firefox-2

But I'm unable to see where this gets set. Our test/avocado/seleniumlib.py doesn't have a specific setting for that. I tried to force it with

```diff
-- a/test/avocado/seleniumlib.py
+++ b/test/avocado/seleniumlib.py
@@ -68,7 +68,7 @@ class SeleniumTest(Test):
             guest_machine = os.environ["GUEST"]
             @Retry(attempts = 3, timeout = 30, error = Exception('Timeout: Unable to attach remote Browser on hub'))
             def connectbrowser():
-                self.driver = selenium.webdriver.Remote(command_executor='http://%s:4444/wd/hub' % selenium_hub, desired_capabilities={'browserName': browser})
+                self.driver = selenium.webdriver.Remote(command_executor='http://%s:4444/wd/hub' % selenium_hub, desired_capabilities={'seleniumProtocol': 'WebDriver', 'browserName': browser})
             connectbrowser()
         self.driver.set_window_size(1400, 1200)
         self.driver.set_page_load_timeout(90)
```
But that doesn't help.

**Comment by cockpituous** [comment]
image-refresh selenium done: https://github.com/cockpituous/cockpit/commits/image-refresh-selenium-20180517-081818

**Comment by martinpitt** [comment]
This is interesting: When I run stuff interactively in the python console, I see a proper exception:

```
>>> driver = webdriver.Remote(command_executor='http://10.111.112.10:4444/wd/hub', desired_capabilities={'browserName': 'firefox'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 178, in start_session
    self.session_id = response['sessionId']
KeyError: 'sessionId'
```
This is due to a sloppy handling of *all* exceptions in `timeoutlib.Retry`. When fixing that, the test now fails fast and meaningfully:

```
# selenium-storage.py:StorageTestSuite.test10Storage duration: 7s
#
04:24:46 ERROR| 
04:24:46 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:576
04:24:46 ERROR| Traceback (most recent call last):
04:24:46 ERROR|   File "/tmp/avocado_tests/seleniumlib.py", line 72, in setUp
04:24:46 ERROR|     connectbrowser()
04:24:46 ERROR|   File "/tmp/avocado_tests/timeoutlib.py", line 131, in __wrap
04:24:46 ERROR|     raise e
04:24:46 ERROR| KeyError: 'sessionId'
```

**Comment by martinpitt** [comment]
The `KeyError` has some google juice, but no solutions other than "update your python-selenium". Indeed `rpm -e python2-selenium; pip install selenium` fixes the `KeyError`, but then causes the firefox tests to fail differently with a timeout in `connectbrowser()` (no further info written).

chrome tests still work fine with the 3.12 version from pip.

This is taking too much time and frustration. Let's keep firefox at the old version for now and revisit this when we update the selenium tests to Fedora 28 (which ships python-selenium 3.7).

**Comment by martinpitt** [comment]
The new hub now breaks explorer tests. I give up :-(

**Comment by martinpitt** [comment]
I don't find time to deep-dive into this. I sent PR #9369 to salvage the two fixes here, and close this for the time being.

**Comment by martinpitt** [comment]
Turns out that with the additional fixes in #9369 it actually works fine now! \o/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-pccdx.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9178-20180614-064646/

**Comment by cockpituous** [comment]
image-refresh selenium done: https://github.com/cockpituous/cockpit/commits/image-refresh-selenium-20180614-065959

**Comment by martinpitt** [comment]
@larskarlitski : One semaphore test is still hanging (what Stef is currently debugging), but the rest is green. \o/

**Pull request merged**
