### PR TITLE
machines: Fix gap in Disks list header

### LINKED ISSUE #10751: machines: Gap in Disks list header
screenshot from 2018-12-04 12-08-36

It seems to be due to the fact that the header is missing a th.
The number of th's is 8, while the number of td's are 9.

### PR DESCRIPTION
**Pull request by KKoukiou**
Fixes #10751

### CODE REVIEW

**Comment by KKoukiou** [comment]
Screenshot with the fix.
disks-gap

**Comment by martinpitt** [comment]
Is this really intended? Before, the "Source" th and the corresponding values in the table were both right-aligned. Now "Source" th is left aligned, but the values are still right-aligned, so they are not visually connected any more.

**Comment by KKoukiou** [comment]
> Is this really intended? Before, the "Source" th and the corresponding values in the table were both right-aligned. Now "Source" th is left aligned, but the values are still right-aligned, so they are not visually connected any more.

Oh I just looked at the header line that was fixed and ignored that source broke. Thanks for noticing.

**Comment by KKoukiou** [comment]
disk-tab

As discussed with garret and andreas on IRC the left allignment is ok.
The default behavior was that the last column with we rigth alligned, but now the last column is the [-] button.

**Pull request merged**
