### PR TITLE
bots: Move fedora-i386 image to Fedora 28

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh fedora-i386

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-i386 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-i386-20180724-120101

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-znhrt.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9719-20180724-120808/

**Comment by cockpituous** [comment]
image-refresh fedora-i386 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-i386-20180724-124646

**Comment by martinpitt** [comment]
Tons of tests fail on a new SELinux regression

    audit: type=1400 audit(1532436766.301:278): avc:  denied  { getattr } for  pid=1544 comm="which" path="/usr/sbin/setfiles" dev="vda4" ino=4879957 scontext=system_u:system_r:pcp_pmlogger_t:s0 tcontext=system_u:object_r:setfiles_exec_t:s0 tclass=file permissive=0

**Comment by martinpitt** [comment]
Pushed fix for `TestRealms.testIpaUnqualifiedUsers`.

**Comment by martinpitt** [comment]
Fixed the trivial conflict.

**Pull request merged**
