### PR TITLE
bots: Add ubuntu-1804 image

### PR DESCRIPTION
**Pull request by martinpitt**
This is more or less identical to the current ubuntu-stable image, copy
the naughty overrides and test skips.

 - [x] Declare ubuntu-1804 image (PR #10336)
 * [x] image-refresh ubuntu-1804

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-db661.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10337-20181019-063434/

**Comment by cockpituous** [comment]
image-refresh ubuntu-1804 done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-1804-20181019-065151

**Comment by martinpitt** [comment]
Seems the new image breaks docker.

**Comment by martinpitt** [comment]
Forgot to copy the hacks in the .install file, fixed now.

**Comment by martinpitt** [comment]
Forgot to copy the hacks in the .install file, fixed now.

**Comment by martinpitt** [comment]
Forgot to copy the hacks in the .install file, fixed now.

**Pull request merged**
