### PR TITLE
sosreport: Use support-tools container instead of rhel-tools

### LINKED ISSUE #7462: RHEL Atomic: rhel-tools sosreport command hangs and locks up system
https://bugzilla.redhat.com/show_bug.cgi?id=1478998

### PR DESCRIPTION
**Pull request by marusak**
* [x] image-refresh rhel-atomic

Quiet some time ago `sosreport` has been dropped from `rhel-tools`
image (as the image was too big) and it is advised to use
`support-tools` image  instead.

Also I drop naughty for issue #7462 - as the underlying issue has been
fixed a long time ago but this naughty has been catching this missing
command.

Closes #7462

### CODE REVIEW

**Comment by martinpitt** [comment]
Thanks for catching this! When you update for the new image, please fix "Quiet"  → "Quite", and "Closes" → "Fixes". (Plus the Closes # for this PR, of course)

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-9ghqx.
Log: https://209.132.184.41:8493/logs/image-refresh-11666-20190425-090101/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-11666-20190425-090101/

**Comment by martinpitt** [comment]
Retrying

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-sc1n5.
Log: https://209.132.184.41:8493/logs/image-refresh-11666-20190425-094343/

**Comment by cockpituous** [comment]
image-refresh rhel-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-atomic-20190425-101313

**Comment by martinpitt** [comment]
The first test run [fails](https://209.132.184.41:8493/logs/pull-11666-20190425-112929-d8b1cec0-verify-rhel-atomic/log.html#217) on a SELinux violation:

    testlib.Error: type=1400 audit(1556193465.335:5): avc:  denied  { sendto } for  pid=2765 comm="chronyd" path="/host/run/chrony/chronyc.5492.sock" scontext=system_u:system_r:chronyd_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=unix_dgram_socket permissive=0

At first sight this might just be bad luck with timing, so retrying for comparison. This should still be reported and naughtied, though.

**Comment by martinpitt** [comment]
No, this is a persistent failure, so needswork. :crying_cat_face:

**Comment by marusak** [comment]
> No, this is a persistent failure, so needswork. :crying_cat_face:

Known, but fixed a year ago - see [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1470150). I'll check if this is regression or never landed in version we use. I'll prepare naughty anyway and if new BZ is needed I'll open one.

**Comment by marusak** [comment]
Naughty worked and rhel-atomic tests passed.

**Pull request merged**
