### PR TITLE
Image refresh for fedora-atomic

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-atomic
 * [x] image-refresh fedora-atomic

### CODE REVIEW

**Comment by marusak** [comment]
3 times `cockpit/fedora-atomic@cockpit-project/cockpit-ostree` failed the same way, needs work I am afraid.

```
[Errno 2] No such file or directory: '/var/lib/atomic/install.json.lock'
```

**Comment by martinpitt** [comment]
@marusak: This is a bug in the "atomic" tool. Doing the docker run install command directly succeeds, and doing `mkdir /var/lib/atomic` before the "atomic install" call works around this. So that mkdir is a good enough workaround until then.

**Comment by martinpitt** [comment]
Moving to "blocked". This already affects the current fedora-atomic image, let's fix it in c-ostree and then just retry this run.

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit-ostree/pull/16

**Pull request merged**
