### PR TITLE
lib: remove obsolete overrides

### PR DESCRIPTION
**Pull request by KKoukiou**
These fixes are included already upstream in patternfly.

### CODE REVIEW

**Comment by martinpitt** [comment]
c8s failures are flakes, but there's lots of pixel diffs. They look mostly reasonable, and indeed [this one](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18673-20230419-125358-538e8d94-fedora-37/pixeldiff.html#TestStorageLuks-testLuks-format-mobile) is even a slight improvement -- one can at least see the first letter of the dropdown, instead of none at all.

**Comment by garrett** [comment]
> [this one](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18673-20230419-125358-538e8d94-fedora-37/pixeldiff.html#TestStorageLuks-testLuks-format-mobile) is even a slight improvement -- one can at least see the first letter of the dropdown, instead of none at all.

That's _most definitely_ a bug (which should be handled outside of this PR). The slider doesn't need to be that big, but you need to see what you're setting.

It really should be like this:

Storage slider

(Again: This should be outside this PR.)

**Review by garrett — CHANGES_REQUESTED** [review]
Select override is apparently still needed. The left and right of different selects do not line up consistently. See the bond settings on the networking page as an example:

image

**Comment by KKoukiou** [comment]
Still needed.

**Pull request closed without merging**
