### PR TITLE
README: Link to new badge location for f22, f23, and r7

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by stefwalter** [comment]
fedora-22 and rhel-7 look strange here: https://github.com/mvollmer/cockpit/blob/readme-new-badges/README.md

**Comment by dperpeet** [comment]
How is the caching set on the target server for these images? I remember that on files.cockpit-project.org we had to manually change the webserver configuration to let these expire. Github caching is very aggressive!

**Comment by mvollmer** [comment]
> fedora-22 and rhel-7 look strange here

Yeah, I used a fixed width so that we don't need to do text measurements while generating the badge.
The strange "fedora-22222" shadow text was just me checking whether caching is correctly disabled.

**Comment by mvollmer** [comment]
> How is the caching set on the target server for these images?

There is a .htaccess file with `Header set Cache-Control "no-cache"`.

**Comment by mvollmer** [comment]
F23 also has a badge already.

**Comment by mvollmer** [comment]
> fedora-22 and rhel-7 look strange

How should they be improved?  I am not sure what 'needswork'. :)

**Comment by stefwalter** [comment]
They look good now.

**Pull request closed without merging**
