### PR TITLE
bots: remove phantomjs-prebuilt from Fedora 26

### PR DESCRIPTION
**Pull request by larskarlitski**
All integration and unit tests are using chromium-browser with the
chrome remote interface instead of phantomjs now.

 * [x] image-refresh fedora-26

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-b3stq.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8412-20180112-085252/

**Comment by cockpituous** [comment]
image-refresh fedora-26 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-26-20180112-092828

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-h0jkf.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8412-20180112-154343/

**Comment by cockpituous** [comment]
image-refresh fedora-26 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-26-20180112-163838

**Comment by petervo** [comment]
I've rerun the semaphore tests a couple of times and seen the fd test fail a few times.

```
expected: "protocol-error", got: undefined, test: receive readable fd and ensure writing fails, module: , source: at Object.equal (http://localhost:55288/dist/base1/qunit.js:2194:12)
```

I've seen it on all three types of tests (not just i386) on different runs.

**Comment by martinpitt** [comment]
rhel-7-5 is still running, but irrelevant for the fedora-26 image, and the rest is green now.

Semaphore tests are indeed rather brittle now, but this is fallout from the chrome migration, not from this PR.

**Pull request merged**
