### PR TITLE
Image refresh for continuous-atomic

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for continuous-atomic
 * [x] image-refresh continuous-atomic

### CODE REVIEW

**Comment by martinpitt** [comment]
OSTree tests fail repeatedly, so this needs to be investigated.

**Comment by mvollmer** [comment]
On it.

**Comment by mvollmer** [comment]
I think the `GetCachedRebaseRpmDiff` method of rpm-ostreed has regressed.  When called for our "zremote" remote, it returns the default deployment (or something like that, not sure about the terms) instead of data for the branch in the remote.

**Comment by mvollmer** [comment]
The signature is not checked anymore immediately after "Check for Updates", but a "rpm-ostree upgrade" will check it.  I'll investigate further.

**Comment by mvollmer** [comment]
The `testRebase` is likely also caused by the `GetCachedRebaseRpmDiff` regression.

**Comment by mvollmer** [comment]
> I think the GetCachedRebaseRpmDiff method of rpm-ostreed has regressed.

Reported as https://github.com/projectatomic/rpm-ostree/issues/1250 and fixed by https://github.com/projectatomic/rpm-ostree/pull/1253.

I'll make a known issue for this.

**Comment by mvollmer** [comment]
> The signature is not checked anymore immediately after "Check for Updates", but a "rpm-ostree upgrade" will check it. I'll investigate further.

Filed as https://github.com/projectatomic/rpm-ostree/issues/1254

**Pull request closed without merging**
