### PR TITLE
shell: Add iframe sandbox to restrict frame Origin

### PR DESCRIPTION
**Pull request by stefwalter**
This prevents one frame from accessing stuff in another frame.
Models the security model that we're going for better, where stuff
loaded from one server should not access stuff in another server.

 * [x] #6258 
 * [x] #6259 
 * [ ] #6301

### CODE REVIEW

**Comment by stefwalter** [comment]
@petervo Do you think we should leave this sandbox off for frames on the localhost?

**Comment by petervo** [comment]
Doesn't this block the parent cookie from being sent along with the http requests from the iframe? The cookie is needed there for the html/js files to load.

**Comment by stefwalter** [comment]
> Doesn't this block the parent cookie from being sent along with the http requests from the iframe? The cookie is needed there for the html/js files to load.

I don't think so. It prevents the javascript from accessing  the cookies, but not use in the request. At least that's what I understood, and saw in practice here.

**Comment by marusak** [comment]
Needs to rebase to master since #12367 changed tests names

**Comment by martinpitt** [comment]
Closing for now, to clean up our stale PR list. This would be a great feature to have, but in the next months we have more urgent issues to address. It will take someone else quite some time to get up to speed with this code, so this will be quite a large project.

**Pull request closed without merging**
