### PR TITLE
test: Download compressed coredump files after test fail

### PR DESCRIPTION
**Pull request by stefwalter**
This allows us to later copy the files into the same image and then examine the core dump futher.
    
The motivation here is the storaged crashes on CentOS 7.

### CODE REVIEW

**Comment by stefwalter** [comment]
Rebuilding fedora-24, fedora-25 and fedora-testing.

**Comment by stefwalter** [comment]
Doesn't work on Ubuntu.

**Comment by stefwalter** [comment]
Priority becuase this prevents us from debugging storaged crashes on CentOS and Fedora 25

**Comment by stefwalter** [comment]
The ubuntu image needs a tweak to make this work.

**Comment by mvollmer** [comment]
> The motivation here is the storaged crashes on CentOS 7.

A crasher bug was recently fixed: https://github.com/storaged-project/storaged/issues/100

**Comment by stefwalter** [comment]
> A crasher bug was recently fixed: storaged-project/storaged#100

That's good, but it's not the same backtrace I'm looking at, which crashes in ```poll_with_variant()```. In any case in Fedora 25 storaged also started crashing too ... but don't remember exactly what the trace was there.

**Pull request closed without merging**
