### PR TITLE
[rhel-8.4] Sync up tests

### PR DESCRIPTION
**Pull request by marusak**
As seen in https://github.com/cockpit-project/bots/pull/1742

Possibly we need a few more backports, but lets start with this to get overview of what is broken and then add more commits (as master is green).

### CODE REVIEW

**Review by martinpitt — DISMISSED** [review]
Oops, yes -- let's get these in ASAP, thanks!

**Comment by marusak** [comment]
ehm, why are packagekit and apps tests considered to be affected?

**Comment by marusak** [comment]
Bummer, we do `git diff origin/master` to get diff for checking affected tests/files. This is not what we want in stable branches. I'll take a look how we can proceed and fix this.

**Comment by marusak** [comment]
Sent https://github.com/cockpit-project/bots/pull/1744 and https://github.com/cockpit-project/cockpit/pull/15466
The latter then needs to be synced here as well.

**Comment by martinpitt** [comment]
Ugh, our branch protection rules didn't cover the rhel-8.4 branch yet. I just fixed that, but FTR, my approval still stands, changes LGTM. Thanks!

**Comment by marusak** [comment]
Tests in bots#1742  are still not green. They need to be looked at. Mostly packagekit. Isn't this somehow related to your recent changes @martinpitt ?

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit/commit/de780972ad9dbb08c6fb8c05579193b1b83e2421 this one?

**Comment by martinpitt** [comment]
@marusak : That's exactly it, we need to cherry-pick that. The current rhel-8-4 image has the behaviour change that uncovered the bug that was fixed with https://github.com/cockpit-project/cockpit/commit/de780972ad9dbb08c6fb8c05579193b1b83e2421.

I just wonder why we didn't catch that in https://github.com/cockpit-project/bots/pull/1710 -- presumably we set up the rhel-8.4 branch around the same time as that behaviour change occurred, so we just didn't have that in the testmap yet 8 days ago?

**Comment by marusak** [comment]
> That's exactly it, we need to cherry-pick that. 

I'll do that. But https://bugzilla.redhat.com/show_bug.cgi?id=1931429 says it is going to be fixed in 8.5, should we deal with that?

> I just wonder why we didn't catch that in cockpit-project/bots#1710 -- presumably we set up the rhel-8.4 branch around the same time as that behaviour change occurred, so we just didn't have that in the testmap yet 8 days ago?

Seems like it. Github says on that branch `Updated 9 days ago by marusak` and also 9 days ago I sent https://github.com/cockpit-project/bots/commit/a3fec8bf5f54c2a3

**Comment by martinpitt** [comment]
@marusak: Honestly, I'd sneak it in. It's a *really* good fix that unbreaks subscription management..

**Comment by marusak** [comment]
hmm, journal tests failed a bunch of times.

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit/commit/40f8e0df6d40dca3d84e54e003be4e3500dee376 likely?

**Comment by martinpitt** [comment]
@marusak : Yes, we absolutely want/need that fix. Not sure if it's 100% sufficient, but for sure required.

**Comment by marusak** [comment]
Down to one failure: https://logs.cockpit-project.org/logs/pull-15463-20210304-165058-0ab2b166-rhel-8-4-distropkg-bots-1742/log.html

I'll first retry

**Review by martinpitt — APPROVED** [review]
Nice work, thank you!

**Pull request merged**
