### PR TITLE
Check for NPM dependency updates

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [ ] FAIL: npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```package.json:    "react-lite": "0.15.39",
webpack.config.js:    "react": "react-lite/dist/react-lite.js",
```

**Comment by cockpituous** [comment]
npm-update in progress on cockpit-tasks-8czrx.
Log: http://fedorapeople.org/groups/cockpit/logs/npm-update-7784-20171003-070606/

**Comment by cockpituous** [comment]
npm-update react-lite done: https://github.com/cockpituous/cockpit/commits/npm-update-react-lite-20171003-070606

**Comment by cockpituous** [comment]
Task threw an exception: http://fedorapeople.org/groups/cockpit/logs/npm-update-7784-20171003-070606/

**Comment by cockpituous** [comment]
npm-update react-lite done: https://github.com/cockpituous/cockpit/commits/npm-update-react-lite-20171003-070707

**Comment by cockpituous** [comment]
Task threw an exception: http://fedorapeople.org/groups/cockpit/logs/npm-update-7784-20171003-070606/

**Comment by petervo** [comment]
Dup

**Pull request closed without merging**
