### PR TITLE
Image refresh for fedora-28 - fixed in #9969

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-28
 * [x] image-refresh fedora-28 
 * [ ] update libssh in Fedora cockpit/ws container (either officially or with a workaround)

### CODE REVIEW

**Comment by martinpitt** [comment]
@Gundersanne: Can you please have a look here? Might this be a regression from your recent continuous-atomic fix?

    error: Failed dependencies:
	libssh.so.4(LIBSSH_4_5_0)(64bit) is needed by cockpit-bridge-175.x-1.wip.fc28.x86_64

**Comment by Gundersanne** [comment]
Blocked on new fedora-atomic base image with libssh 0.8.x being installed by default.

Check https://ftp-stud.hs-esslingen.de/pub/Mirrors/alt.fedoraproject.org/atomic/stable/ for an image older than 06/08/2018.

**Comment by martinpitt** [comment]
On latest fedora-atomic there is libssh-0.8.1-3.fc28.x86_64 which should actually be enough? Retrying tests.

**Comment by martinpitt** [comment]
This fedora-28 image has libssh-0.8.1-4.fc28.x86_64, while fedora-atomic has libssh-0.8.1-3.fc28.x86_64 . If the dependencies are *that* strict, this is a bug in the Fedora packaging. Built package:
```
❱❱❱ rpm -q --requires $TEST_DATA/tmp/build-results/cockpit-bridge-176.x-1.wip.fc28.x86_64.rpm | grep libssh
libssh >= 0.7.1
libssh.so.4()(64bit)
libssh.so.4(LIBSSH_4_5_0)(64bit)
```

On fedora-atomic:
```
# rpm -q --provides libssh
libssh = 0.8.1-3.fc28
libssh(x86-64) = 0.8.1-3.fc28
libssh.so.4()(64bit)
libssh.so.4(LIBSSH_4_5_0)(64bit)
libssh_threads.so.4()(64bit)
```
which ought to match. And indeed it does, as the  ostree *did* get updated:
```
# rpm-ostree db diff 
ostree diff commit old: booted deployment (c6b1e97b93424c260baa98518277d87f7f4ebf036c09a9a0aeb7097c33c2099c)
ostree diff commit new: pending deployment (0666a87f1555582df6b70192fc02a0729440977dd9db086bf7c1297d059c0e15)
Upgraded:
  cockpit-bridge 175-1.fc28 -> 176.x-1.wip.fc28
  cockpit-docker 175-1.fc28 -> 176.x-1.wip.fc28
  cockpit-networkmanager 175-1.fc28 -> 176.x-1.wip.fc28
  cockpit-system 175-1.fc28 -> 176.x-1.wip.fc28
Removed:
  cockpit-ostree-175-1.fc28.noarch
Added:
  cockpit-machines-176.x-1.wip.fc28.noarch
  cockpit-machines-ovirt-176.x-1.wip.fc28.noarch
  cockpit-sosreport-176.x-1.wip.fc28.noarch
  cockpit-tests-176.x-1.wip.fc28.x86_64
```

The thing that failed is the cockpit/ws container update:
```
subprocess.CalledProcessError: Command '['docker', 'exec', 'build-cockpit', 'rpm', '--freshen', '--verbose', '--force', '/host/var/tmp/build-results/cockpit-bridge-176.x-1.wip.fc28.x86_64.rpm', '/host/var/tmp/build-results/cockpit-dashboard-176.x-1.wip.fc28.noarch.rpm', '/host/var/tmp/build-results/cockpit-ws-176.x-1.wip.fc28.x86_64.rpm']' returned non-zero exit status 3
```
So this is #9941 again.

**Pull request closed without merging**
