### PR TITLE
test: Add an ubuntu image

### PR DESCRIPTION
**Pull request by dperpeet**
follow-up to #4901, rebase

### CODE REVIEW

**Comment by dperpeet** [comment]
@stefwalter should I add known issues for ubuntu? that way it would be easier to tackle them one by one and we can make sure that it (at the very least) doesn't get worse

**Comment by stefwalter** [comment]
Well lets not package storaged first, and skip all the storaged tests ... if I'm understanding correctly, that's the case of most of the failures. The other ones need to be judged individually. For example the SSL one is something that needs to be accounted for in the test.

**Comment by stefwalter** [comment]
In general we only create known issues for things that are supposed to work for users, but are broken for those users.

If storaged is not packaged on Ubuntu (yet) then it's not supposed to work, and our tests should just skip that.

**Comment by stefwalter** [comment]
#4901 is rebased, and further work done on making yet more tests work. So I'll close this one.

**Pull request closed without merging**
