### PR TITLE
test: Fix regression in check-multi-machine-key test

### PR DESCRIPTION
**Pull request by stefwalter**
This test was broken during the recent rename of wait_ssh()
to wait_execute(). Fix it back.

### CODE REVIEW

**Comment by stefwalter** [comment]
Priority because this fixes integration testing.

**Comment by stefwalter** [comment]
Doesn't seem to fix the issue in rhel-7

**Comment by cockpituous** [comment]
Is that because wait_execute isn't checking the connection after the restart but preserving it's connection? Which means the ssh might not be up yet causing it to fail when accessed from machine1 that doesn't have a persistent connection.

**Comment by stefwalter** [comment]
> Is that because wait_execute isn't checking the connection after the restart but preserving it's connection? Which means the ssh might not be up yet causing it to fail when accessed from machine1 that doesn't have a persistent connection.

If so, then ```self.machine2.disconnect()``` is not working.

**Comment by stefwalter** [comment]
```
Mar 09 07:34:31 localhost.localdomain sshd[1151]: error: Bind to port 22 on 0.0.0.0 failed: Address already in use.
Mar 09 07:34:31 localhost.localdomain sshd[1151]: error: Bind to port 22 on :: failed: Address already in use.
Mar 09 07:34:31 localhost.localdomain sshd[1151]: fatal: Cannot bind any address.
```

**Pull request closed without merging**
