### PR TITLE
Shell patternfly migration v2

### PR DESCRIPTION
**Pull request by andreasn**

### CODE REVIEW

**Comment by stefwalter** [comment]
I see these strange boxes on the 'Containers' page as I click buttons.

screenshot from 2015-03-30 21-45-46

**Comment by andreasn** [comment]
Those are the waiting spinners. I thought I had cleaned all those out, but apparently not. Will fix.

**Comment by andreasn** [comment]
The waiting spinners should be in there, according to https://github.com/andreasn/cockpit/commit/745eedcd45eb3b715c17f98d98f10c91518b7ecd

**Comment by stefwalter** [comment]
Odd, the spinner problem went away. It must have been a problem on my end.

**Pull request closed without merging**
