### PR TITLE
WIP: Polyfill cleanup

### PR DESCRIPTION
**Pull request by martinpitt**
See issue #12151

### CODE REVIEW

**Comment by garrett** [comment]
Oh, for finally, we'd also need to bump up our other browser versions too. According to https://caniuse.com/#feat=promise-finally:


  | Website | Promise.prototype.finally | Current
-- | -- | -- | --
Firefox | 52 | 58 | 69
Chrome | 63 | 63 | 77
Edge | 16 | 18 | 18
Safari (macOS) | 10.3 | 11.1 | 13
Safari (iOS) | 10.3 | 11.3 | 13.1
Opera | 44 | 50 | 62

**Comment by martinpitt** [comment]
Whoops! This [breaks Edge](https://209.132.184.41:8493/logs/pull-13020-20191021-120101-12c3e227-cockpit-project-cockpit--fedora-30-selenium-edge/screenshot-test10Base-370418.png), apparently our version is too old, *sigh*.

**Comment by garrett** [comment]
The one I really see as possibly problematic is dropping all versions of Edge but the current. That said, it's been in Edge 18 since Nov 2018 (almost a year). Edge is in a weird transition state at the moment, with Edge 76 showing up... _soonish_? But it would a current + 1 back minimum browser support.

**Comment by martinpitt** [comment]
I dropped the third commit that drops the polyfill, and just keep the two others. I think the login page should still be okay, as we have the polyfill. Now that I force-pushed, I realize that we probably don't import the polyfill on the login page, but I'll fix that after the Edge test ran.

**Comment by martinpitt** [comment]
Dusting this off again. I tested with our old edge locally, and ran selenium-base, and it works fine.

**Comment by martinpitt** [comment]
This still breaks Edge, and is not important. I sent #13428 with the error message fix, and ignore the rest here for the time being. We can just bump the Edge requirement and drop the polyfill once we move to chrome based Edge.

**Comment by garrett** [comment]
> We can just bump the Edge requirement and drop the polyfill once we move to chrome based Edge.

Perhaps we should talk* about when we should drop non-Chromium Edge — and if that's even possible for the forseeable future.

\* (at the face-to-face?)

**Pull request closed without merging**
