### PR TITLE
storage: Do Clevis stuff in JavaScript, official look

### PR DESCRIPTION
**Pull request by mvollmer**
We still have a (much smaller) python hack that does the udev monitoring until UDisks2 provides an API.

We keep this behind the magic `clevis-feature` switch until we use the "sss" pin to do the 1-out-of-N logic. 

Todo:
- [ ] Make it work for non-root users
- [ ] Fix tests
- [ ] Only react to udev events for the device that is being monitored

### CODE REVIEW

**Comment by mvollmer** [comment]
New UDisks2 API: https://github.com/storaged-project/udisks/pull/539

**Comment by mvollmer** [comment]
My idea re luksmeta-monitor-hack is that we carry it only until we have the necessary UDisks2 API to replace it in at least one image.  If we have that, we can run the tests and require the UDisks2 API from then on.

**Comment by mvollmer** [comment]
@sabbaka, fyi.

**Comment by sabbaka** [comment]
Thanks for that. Should I wait till you finish it or is it finished already?

**Comment by mvollmer** [comment]
> Should I wait till you finish it or is it finished already?

I will move this forward as far as I get in the next two days, and then you can take over. @martinpitt et all will help you with testing machinery etc.

**Comment by mvollmer** [comment]
I have merged #9445 into this.

**Comment by mvollmer** [comment]
Replaced by #9465.

**Pull request closed without merging**
