### PR TITLE
Added cockpit-fedora.pam and cockpit-suse.pam

### PR DESCRIPTION
**Pull request by kkaempf**
This fixes issue #1780

### CODE REVIEW

**Comment by stefwalter** [comment]
Hmmm, I think we did this on purpose because of the possibility for getting it wrong on various distros and opening up security holes. On Fedora we ship the pam file in the packaging repo. @mvollmer I wonder if we should reconsider?

**Comment by mvollmer** [comment]
@sgallagher might be the best person to answer this.

I actually now think that we should install a pam config during `make install`, and try to do adapt to different systems, just as we do by making the systemd unit file optional.

**Comment by stefwalter** [comment]
> I actually now think that we should install a pam config during make install, and try to do adapt to different systems, just as we do by making the systemd unit file optional.

I disagree here. The PAM config is hopelessly system specific. We need packagers to be the ones responsible for curating the PAM config for their platform.

**Comment by stefwalter** [comment]
Unless and until we do CI for OpenSUSE builds upstream here in the cockpit-project.org (we're not ready to do multiple OS CI yet), I don't think we need to host the PAM configs for the various distros.

Obviously help to get our CI running across a select number distros is very welcome, but not something anyone has had time to tackle yet.

**Comment by stefwalter** [comment]
I accidentally closed this. Had meant to allow further discussion. @kkaempf  happy to reopen it if you think it needs to be reopened.

**Comment by kkaempf** [comment]
I'm fine with keeping cockpit-suse.pam with me. But in general, I'd rather see Cockpit (and any other project) to provide everything to build a package. Now a "git clone" only allows for "make; sudo make install" but not for "rpmbuild".

**Comment by sgallagher** [comment]
In other projects, I've seen people include the differing PAM/spec etc. in the $srcdir/contrib/<platform> directory and then add a configure flag that will be used to tell 'make install' which contrib directory to draw the files from. The idea was that a maintainer from the different OSes would be responsible for maintaining those directories, of course.

**Pull request closed without merging**
