### PR TITLE
Expanded listing rows shouldn't be navigatable

### PR DESCRIPTION
**Pull request by stefwalter**
Clicking on an expanded row in a listing view shouldn't make it
navigate to the detailed target.

### CODE REVIEW

**Comment by petervo** [comment]
Leaving them clickable was intentional, @andreasn you ok with this?

**Comment by dperpeet** [comment]
As discussed on irc, we originally decided to leave the row clickable. I don't care much either way. A good argument for keeping it clickable is the mindset that the row should remain as "constant" as possible when expanding/collapsing. We did this visually, but now you're proposing to change the behavior.

**Comment by stefwalter** [comment]
I'm fine with dropping this for now until we have more experience with more folks using the pattern and what reactions are.

**Comment by dperpeet** [comment]
@andreasn mentioned a good point: the "annoyance" factor when navigating by accident is probably higher than the inconvenience of not being able to navigate for expanded items.

**Comment by andreasn** [comment]
I think I like the new behaviour that got introduced in this pull.
It creates more of a mode between "dive-in-state" and "expand-inline-state". This works well in the case where the use case is to compare different objects, but is a bit harder when the use case is to use the expander to quickly identify an object to later dive into it

**Comment by stefwalter** [comment]
I just ran into this again, and things nagivated unexpectedly. I'm trying to decide whether my expectations are based on previous knowledge.

**Comment by stefwalter** [comment]
@dperpeet @andreasn Agree with the annoyance factor comment ... the unexpected navigation made me annoyed :)

**Comment by petervo** [comment]
I think the consensus is that we want this, needs a rebase.

**Comment by stefwalter** [comment]
Rebased.

**Comment by petervo** [comment]
This breaks the case where we don't have a inner page to click into. See "Expandable Listing: Panel header is row" in Design Patterns or the authentication dialog.

**Comment by stefwalter** [comment]
Blocked on #4376

**Comment by dperpeet** [comment]
needs rebase

Note that with the react pattern, we agreed on exactly this behavior: If an item is expanded, clicking on the original row just collapses it.

**Comment by stefwalter** [comment]
Rebased.

> Note that with the react pattern, we agreed on exactly this behavior: If an item is expanded, clicking on the original row just collapses it.

Willing to try that out. Updated the pull request to do that. Although my first reaction is that it makes it unclear to intuitively know whether navigation or collapse will happen, until you know the rules.

**Comment by dperpeet** [comment]
> Willing to try that out. Updated the pull request to do that. Although my first reaction is that it makes it unclear to intuitively know whether navigation or collapse will happen, until you know the rules.

The blue highlight shows what will happen, check out the react playground: If you hover over an expanded row, only the blue caret is highlighted in blue, the row remains grey.

**Comment by petervo** [comment]
I asked @andreasn when originally doing it, and he did not like the idea of that main bar collapsing because then if you click it again it does something totally different. But i'll let you sort it out.

**Comment by stefwalter** [comment]
@dperpeet Can you decide with @andreasn? I'll implement whatever is decided for the kube stuff.

By the way, we shouldn't need to add ```.listing-ct-navigate``` to everything that is open. Lets just use ```tbody:not(.open)``` since we're already having to toggle that style. But I'll let you guys decide on behavior first.

**Comment by dperpeet** [comment]
> By the way, we shouldn't need to add .listing-ct-navigate to everything that is open. Lets just use tbody:not(.open) since we're already having to toggle that style. But I'll let you guys decide on behavior first.

Do you mean `listing-ct-nonavigate`? This is for more than behavior when the row is expanded or not - some listings don't allow navigation at all. The negative is because we decided that the default behavior is for a listing to allow navigation, so we'll have fewer classes and less clutter in those cases.

**Comment by dperpeet** [comment]
@andreasn What do you think?

**Comment by dperpeet** [comment]
@stefwalter for consistency, the hover when expanded shouldn't indicate that navigation will occur
If you look at the react playground, you can see it happen there: When hovering over an expanded row, only the caret will highlight blue, not the entire row.

**Pull request closed without merging**
