### PR TITLE
ssh: Use ssh_userauth_pubkey_auto instead of custom code

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
This only has the test now that shows what doesn't work.  TDD!

**Comment by mvollmer** [comment]
This will not work, unfortunately.

When the prompt callbackis called, we can't determine what key it is for.  The hack of inspecting the error message does not work since the error message might be anything and can not be relied to be about the private key that failed to be loaded because it was protected.

The alternative is to explicitly iterate over all identities like ssh_userauth_publickey_auto does, but that is not possible with the public API.

This might be made to work without patching libssg by hooking into the logging machinery. That would be very desperate, though, and should probably only be done once we have a path to libssh on the way that will make it possible to remove that hack again.

**Comment by mvollmer** [comment]
>  That would be very desperate, though,

Not more desperate than the inspecting the error message, I guess.

**Comment by mvollmer** [comment]
This should probably replace do_key_identity_auth instead of do_agent_auth, but the logic of what function does what confuses me a bit right now.

The two entry points are `do_key_auth` and `do_agent_auth`.

- `do_key_auth` tries the keys on disk and then a specified private key. This might be used by integrations with ManageIQ and Foreman, etc.
- `do_agent_auth` tries the keys on disk and then the keys in the agent. This is used by the connections done by Cockpit dashboard etc.

I don't understand why `do_key_auth` tries the keys on disk, and then why doesn't it also try the keys in the agent?

I don't think we can properly test changes to `do_key_auth`, so making it try fewer keys is risky. Let's just make it also try the keys in the agent.

**Comment by mvollmer** [comment]
> This should probably replace do_key_identity_auth instead of do_agent_auth

Done.

**Comment by mvollmer** [comment]
Alright. I think ssh_userauth_publickey_auto is the right thing to use. We can leave it to libssh to try the right keys.
However, because of the API limitations mentioned above, we can't yet use it yet. Working around the API limitation by inspecting debug log messages or error messages is more brittle than hardcoding a list of keys into Cockpit.
Thus, I propose we go with the hardocded list in #14344 as the workaround until the API limitation is lifted.
I will propose a new function for libssh, something like `ssh_userauth_publickey_auto_get_current_identity` that can be used in `auth_function` callback to get the path to the key that the passphrase is for.

**Comment by martinpitt** [comment]
@mvollmer : FTR, that makes complete sense to me. The hardcoded list isn't too evil, and it'll last for a few years. Improving the libssh API is certainly appreciated!

**Comment by mvollmer** [comment]
Continued in #14551 and #14562.

**Pull request closed without merging**
