### PR TITLE
Update reference images for new Fedora image

### PR DESCRIPTION
**Pull request by marusak**
This image fixed https://github.com/cockpit-project/bots/issues/2323 and it does not have failing service anymore

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Oops! We should ignore the hostname in the terminal screenshot, but this is fine for now. Thank you!

**Comment by marusak** [comment]
> We should ignore the hostname in the terminal screenshot, but this is fine for now

Did that as I forgot to update desktop pixel reference the first time.

**Review by martinpitt — APPROVED** [review]
Cheers!

**Comment by martinpitt** [comment]
Ugh @ [c9s failure](https://download.copr.fedorainfracloud.org/results/packit/cockpit-project-cockpit-16836/centos-stream-9-x86_64/03188061-cockpit/builder-live.log.gz):
```
Error: 
 Problem 1: cannot install the best candidate for the job
  - nothing provides libgomp = 11.2.1-7.4.el9 needed by gcc-11.2.1-7.4.el9.x86_64
  - nothing provides libgcc >= 11.2.1-7.4.el9 needed by gcc-11.2.1-7.4.el9.x86_64
 Problem 2: cannot install the best candidate for the job
  - nothing provides openssl-libs(x86-64) = 1:3.0.0-6.el9 needed by openssl-devel-1:3.0.0-6.el9.x86_64
 Problem 3: cannot install the best candidate for the job
  - nothing provides selinux-policy = 34.1.22-1.el9 needed by selinux-policy-devel-34.1.22-1.el9.noarch
```
Someone Else's Problem™, let's ignore that one.

**Comment by marusak** [comment]
`fedora-35` and `fedora-35/mobile` failed as expected. But `fedora-35/mobile@bots#2804 ` and `fedora-35@bots#2804` succeeded so landing in lockstep with https://github.com/cockpit-project/bots/pull/2804

**Comment by marusak** [comment]
Oh no, f35 is required status :/ I'll do the dance with disabling it then for a second

**Pull request merged**
