### PR TITLE
Image refresh for openshift

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for openshift
 * [x] image-refresh openshift

### CODE REVIEW

**Comment by marusak** [comment]
Ok, so we can now test branches so we can test this as well.
Buuut, what tests do we want to ran this on? (and on which branches?)

**Comment by marusak** [comment]
Something went very badly with `fedora-30/container-kubernetes@cockpit-project/cockpit/rhel-7.7`

**Comment by martinpitt** [comment]
> Buuut, what tests do we want to ran this on? (and on which branches?)

The ones that we want are:
 * rhel-atomic@cockpit-project/cockpit/rhel-7.{7,8}
 * fedora-30/container-kubernetes@cockpit-project/cockpit/rhel-7.{7,8}
 * rhel-7-{7,8}@cockpit-project/cockpit/rhel-7.{7,8}

**Comment by marusak** [comment]
today I learned that I have really poor knowladge of openshift :D 
Anyway, at least I'll write whats the problem since nothing I tried worked and someone else may have some ideas what else I could try or what could be the problem.

So we create `openshift-cockpit` service with:
```
+ $ oc process -f /tmp/cockpit-openshift-template.json -p COCKPIT_KUBE_INSECURE=true -p COCKPIT_KUBE_URL=http://127.0.0.2:30001 -p OPENSHIFT_OAUTH_PROVIDER_URL=https://127.0.0.2:8444 -p REGISTRY_ONLY=true > out.json
+ $ oc create -f out.json
replicationcontroller "openshift-cockpit" created
service "openshift-cockpit" created
oauthclient.oauth.openshift.io "cockpit-oauth-client" created
```
 where ` /tmp/cockpit-openshift-template.json` is [this](https://github.com/cockpit-project/cockpit/blob/rhel-7.8/test/containers/files/cockpit-openshift-template.json) file.

```
$ oc get all
NAME                          READY     STATUS    RESTARTS   AGE
pod/docker-registry-1-572cb   1/1       Running   0          45d

NAME                                      DESIRED   CURRENT   READY     AGE
replicationcontroller/docker-registry-1   1         1         1         45d
replicationcontroller/openshift-cockpit   1         0         0         0s

NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                 AGE
service/docker-registry     ClusterIP   172.30.194.218   <none>        5000/TCP                45d
service/kubernetes          ClusterIP   172.30.0.1       <none>        443/TCP,53/UDP,53/TCP   45d
service/openshift-cockpit   NodePort    172.30.2.57      <none>        9000:30000/TCP          0s

NAME                                                 REVISION   DESIRED   CURRENT   TRIGGERED BY
deploymentconfig.apps.openshift.io/docker-registry   1          1         1         config

NAME                                     DOCKER REPO   TAGS                                 UPDATED
imagestream.image.openshift.io/busybox   busybox       latest,1.31,1.31-glibc + 2 more...   6 weeks ago
```

and then tests wait for 10.111.112.101:30000 with
```
curl --insecure --silent --connect-timeout 2 --max-time 3 http://10.111.112.101:30000
```
 but it never succeeds.

`http://10.111.112.101:8443` is up and reachable.
Also we try to check cockpit on `http://127.0.0.2:30001/registry`, which is also not reachable (obviously).

**Comment by martinpitt** [comment]
I see nothing wrong with this image. It triggers the completely wrong set of tests of course (I sent a fix in #12690). I triggered the right ones here, but they won't run for a while until our RHEL CI comes back.

I ran the rhel-7-8 check-kubernetes tests locally, and they succeed.

**Pull request merged**
