### PR TITLE
test: Update openshift images for multiple openshift-node instances

### PR DESCRIPTION
**Pull request by stefwalter**
It should be possible now run ```test/vm-run openshift``` and then ```test/vm-run openshift-node``` more than once and have them all register with the the API server.

### CODE REVIEW

**Comment by stefwalter** [comment]
Uploading the image

**Comment by petervo** [comment]
Looks like the oadm commands need to be updated everywhere.

**Comment by stefwalter** [comment]
I filed: https://github.com/openshift/origin/issues/9000

@petervo What are the new oadm commands to workaround the above regression?

**Comment by petervo** [comment]
I thought we work around this, but i guess we can't without granting more privileges and that sort of defeats the point of the tests.

**Comment by stefwalter** [comment]
Updated the image with a new openshift that hopefully includes the upstream fix to openshift/origin#9000

**Comment by stefwalter** [comment]
More regressions. Needs looking into.

**Comment by petervo** [comment]
Fixed the -t / --template issue here https://github.com/petervo/cockpit/commit/5f8ff8f6c3cc5eeae777132d6d627ab9db57778f but the other failure is because dockerImageManifest is missing. Still looking into why that is

**Comment by petervo** [comment]
Replaced by #4610

**Pull request closed without merging**
