### PR TITLE
[no-test] Services - bunch or random ideas

### PR DESCRIPTION
**Pull request by marusak**
This is set of possible improvements in services page. Some of them are ideas that came up in #11241 some just random stuff. I don't expect that all of them would be accepted (two even implement the same thing two different ways), it is mostly to open some discussion and see what is suitable and what is bad idea or bad design :)

I hope most of the commits are self-explanatory. To some I provide some context.

`Break top bar nicely on small screen` - before this commit nav bar breaks into two rows which does not make sense. Also buttons on right break into rows as well in ugly way. After this commit on small screen the navigation panel is split into two rows. Top contains buttons from right side and bottom one contains buttons. This layout should never break any further. (I am not sure if the top row should float right or left, implemented with floating left)

`Focus elements` - this was suggested by @garrett but he nor me are entirely sure if this is good thing to do. Now focus follows basic workflow - pick type of unit first and then search in it.

Commits `Make units type accessible` and `Navtabs navigatable by arrows` implement the same thing - accessible navtabs. First represents it as bunch of toggle buttons. Which may be confusing as only one of them can really be in state ON. Second one implements it as tabs which makes real sense. Second one makes it also possible to navigate between panels with left and right arrows. These commits do the same thing in different way. If first is right then second can be dropped. If second is right then they just need to be squashed. Buuut possibly I do it wrongly from start and smart people of Cockpit will explain me how to do it properly :)

`Show 'System Services' first` - I am just wondering why it is second and not first. Is there some good reason?

Screenshot showing visible changes:
loading
smallscreen

P.S.  forgot to add [no-test] at first, added it now but tests already run. Will they run on repush as well?

### CODE REVIEW

**Comment by andreasn** [comment]
I have no idea about the order. I was looking through the systemd documentation, but couldn't find any good reason for the current order, and I haven't been able to find if the CLI has any preferences here, because it would be good to stay consistent with that. @martinpitt do you have any strong opinions on this?

It might be good to split the layout fixes and the ordering out into separate PRs, because they address very different problems. The layout changes I think are great, the ordering, I am less certain about, and the more focused a PR is, the easier it is to review.

**Comment by andreasn** [comment]
I've put @garrett on review for the mobile and accessibility parts, since that's his area of expertise.

**Comment by andreasn** [comment]
Maybe good to also have a spinner together with the loading text, like we do on the Containers page
screenshot from 2019-03-01 17-01-17

**Comment by andreasn** [comment]
I also noticed you changed the name for _id_ to _name_ and I'm trying to figure out what the best name would be for this column. I can't find any mention of _Id_ anywhere. It seems it's either called _Name_ or _Unit_. It would be good to be able to transition from the UI to the CLI and maintain the same wording, so I wonder if Unit is more correct here, see the systemctl --help command for example. It's full of the word _unit_.
[RHEL systemd documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/chap-managing_services_with_systemd)
[systemd upstream documentation](https://www.freedesktop.org/software/systemd/man/systemd.unit.html)

So that's another thing I'm a little bit on the fence about.

**Comment by marusak** [comment]
ok, I think you are right and separate PRs would be much better. I will do that and will include your comments there.
Thank you for looking at this @andreasn

**Pull request closed without merging**
