### PR TITLE
Prepare for PhantomJS 2

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by stefwalter** [comment]
I ported the playground patterns as a prerequisite for including CSP in Cockpit. Seems like this is a step backwards. Likely we should port the playground to support CSP properly.

**Comment by mvollmer** [comment]
> Likely we should port the playground to support CSP properly.

Good point. Done.

**Comment by mvollmer** [comment]
This was done with PhantomJS 2: http://mvo.fedorapeople.org/logs/test-fd04ec4f-verify-fedora-23/log.html

**Comment by mvollmer** [comment]
With PhantomJS 2: https://mvo.fedorapeople.org/logs/test-b5e3c90a-verify-fedora-23/log.html

**Comment by mvollmer** [comment]
PhantomJS 2 passed: http://mvo.fedorapeople.org/logs/test-6ea6d5d8-verify-fedora-23/log.html

**Pull request closed without merging**
