### PR TITLE
test: Enable firewall tests on the atomics

### PR DESCRIPTION
**Pull request by larskarlitski**
Depends on

- [ ] ~#9125 (these are the first images on which firewalld is disabled by default, which is broken)~

### CODE REVIEW

**Comment by martinpitt** [comment]
@larskarlitski : I believe this ought to work now without #9125. I recently fixed the on/off button in #10511. So this just needs to be rebased.

**Comment by martinpitt** [comment]
Bugger, continuous-atomic is still broken for unrelated reasons, see #10531. The uninstallability is actually from commit d7dc7943, we just didn't notice it there as we don't run continuous-atomic regularly. So let's just ignore that one.

**Comment by martinpitt** [comment]
However, [testAddServices](https://fedorapeople.org/groups/cockpit/logs/pull-9126-20181120-181212-4484b086-verify-fedora-atomic/log.html) shows a timeout in the dialog, so it doesn't really work there. This needs to be investigated.

**Comment by larskarlitski** [comment]
I am happy. Thanks very much for taking care of this!

**Pull request merged**
