### PR TITLE
HACKING.md: updates

### PR DESCRIPTION
**Pull request by martinpitt**
Full tests, this validates the new tasks container from https://github.com/cockpit-project/cockpituous/pull/498

### CODE REVIEW

**Comment by martinpitt** [comment]
[changed pixel](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17447-20220613-072848-8f11aeb7-fedora-36/log.html#64); possibly from refreshed container image, possibly a flake. I'll retry once to tell me which one it is, and then update the pixel test if appropriate.

**Comment by martinpitt** [comment]
Pushed updated pixel tests for new container. no-tests now, as everything else was green before.

**Comment by marusak** [comment]
I have seen the same pixel test failed today in different PR and also thought it was flake, but you might be right, it may due to different container image.

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
