### PR TITLE
storage: Don't leave udevadm processes behind on page reload

### PR DESCRIPTION
**Pull request by mvollmer**
When reloading a page, Cockpit correctly closes all channels, which
will correctly kill all processes spawned via cockpit.spawn.  Child
processes of those processes will usually also exit on their own
because they get their stdin/stdout closed.

The "udevadm monitor" process spawned by luksmeta-monitor-hack would
not get killed on a page reload however, since it doesn't immediately
react to having its pipes closed, since it doesn't read from stdin and
doesn't write to stdout frequently enough.

Thus we make sure it is killed explicitly.

### CODE REVIEW

**Comment by mvollmer** [comment]
> I would have thought that `atexit` is easier,

`atexit` doesn't run when the process is killed by a signal, unfortunately.

**Comment by martinpitt** [comment]
@mvollmer: Ah, too bad. I had assumed Python handled `SIGTERM` internally to clean up (there's that warning in the [docs](https://docs.python.org/3/library/atexit.html), but it doesn't mention which signals work).

**Comment by mvollmer** [comment]
I have added a test.

**Comment by mvollmer** [comment]
> I have added a test.

We might think of checking for lingering processes after each test.

**Comment by mvollmer** [comment]
fedora-32 shows a new unexpected journal message: https://logs.cockpit-project.org/logs/pull-13983-20200428-114321-b04b1f16-fedora-32/log.html#263-2

I have added a commit to fix that.

**Comment by martinpitt** [comment]
On [centos-8](https://logs.cockpit-project.org/logs/pull-13983-20200428-140258-343b84c2-centos-8-stream/log.html#200-2), a lot of LVM storage tests fail, which smells suspicious?

**Comment by mvollmer** [comment]
> On centos-8, a lot of LVM storage tests fail, which smells suspicious?

The newly added test fails, which needs investigation.  The other two don't seem to be related.

**Comment by mvollmer** [comment]
> The newly added test fails, which needs investigation.

The script was getting killed by SIGHUP somehow instead of SIGTERM.  I made the exit catching code more general.

**Pull request merged**
