### PR TITLE
images: Enable CORS support in ovirt image

### PR DESCRIPTION
**Pull request by mareklibra**
CORS support must be enabled on oVirt's engine to
allow access of API from firefox/chrome (means from cockpit-ovirt).

### CODE REVIEW

**Comment by stefwalter** [comment]
@mareklibra Will CORS be enabled by default in future versions of oVirt? How is this mitigated for end users? Cockpit is not "configure-ware" where you have to fiddle with it to get it to work. How can we make this work from the GUI?

**Comment by stefwalter** [comment]
Added and uploaded a new ovirt image

**Comment by petervo** [comment]
@mareklibra are these requests made the ovirt api by the browser something we can route through cockpit by using the cockpit.http api and thus avoid CORS? Or do they have to be made by the browser directly?

**Comment by mareklibra** [comment]
Closing, since #7139 has been changed to proxy HTTP requests via cockpit.http(), this PR is no more needed.

**Pull request closed without merging**
