### PR TITLE
Firewalld redesign

### PR DESCRIPTION
**Pull request by jelly**
Firewall page improvements from https://github.com/cockpit-project/cockpit/issues/9047#issuecomment-1026005844

### CODE REVIEW

**Comment by garrett** [comment]
Is this mainly for converting the delete icon to the ... kebab menus? (That's what it looks like here when I build it locally.)

Will it also include
- the message about incoming traffic at the top?
- changing the toggle to include "enabled"

Basically this:

image
...or should that be a separate PR?

**Comment by garrett** [comment]
Mobile needs work:

image

After thinking about it for a bit, can we have the incoming message at the top and the enabled switch in a separate PR to fast track those changes? It'd allow us to make sure we get this PR right while having simpler changes go through more quickly.

**Comment by garrett** [comment]
The text should probably be aligned to the baseline.

Screenshot from 2022-03-10 14-23-37

The padding between items feels wrong and it should really be gap to fix the issues in desktop and mobile wrapping. I think I'll probably have to dig into the code to adjust this.

**Comment by jelly** [comment]
> Mobile needs work:
> 
> image
> 
> I see if we do add "Enabled", it'd cause the button to wrap. Perhaps we should add the incoming/outgoing string and not "Enabled" / "Disabled".
> 
> Horizontal alignment is off. It's inconsistent between the header and table, but more importantly, the interface is way over to the right. And there's probably too much space between the Zone header and Interface. We should align these with gaps, not margin.
> 
> Screenshot from 2022-03-10 14-25-28
> 
> After thinking about it for a bit, can we have the incoming message at the top and the enabled switch in a separate PR to fast track those changes? It'd allow us to make sure we get this PR right while having simpler changes go through more quickly.
> 
> The incoming message at the top is mean to be a placeholder until we have incoming and outgoing traffic listed. This PR has incoming traffic and doesn't handle outgoing (as far as I can see).
> 
> But I think we'll want to work on this PR and it might not make it in for the next release. So I'm fine with adding some text in a quick PR and adjusting the UI later. (I don't consider adding the text as much UI churn, as it's just adding a string and not really changing the UI.)
> 
> For desktop:
> 
> The text should probably be aligned to the baseline.
> 
> Screenshot from 2022-03-10 14-23-37
> 
> The padding between items feels wrong and it should really be gap to fix the issues in desktop and mobile wrapping. I think I'll probably have to dig into the code to adjust this.

Switched this to use PF's Flex so we can get rid of all css classes and no gap seems to be required.

image

**Comment by garrett** [comment]
> should this also appear on the network page, it also has a firewall switch? 

Yes.

The issue was originally with the services page in the metrics study, which needs this as well. (However, that also needs some additional improvements too.) People generally did not see the Firewall page there (but the same principle of discoverability of the switch applies).

> And what element is the small text again? It's not a as far as I know.

Helper text?

- https://www.patternfly.org/v4/components/helper-text/

If helper text doesn't work for whatever reason, it could just be text with a small font size helper applied:

- https://www.patternfly.org/v4/components/text/
- https://www.patternfly.org/v4/utilities/text/#font-size

**Review by garrett — APPROVED** [review]
Looks great! :+1: 

I did notice it's still not quite right in smaller modes, but it's still better than what we have in main at the moment, so we can optimize things in a follow-up.

Screen Shot 2022-03-16 at 11 40 34


Screen Shot 2022-03-16 at 11 41 01

**Pull request merged**
