### PR TITLE
metrics: Make better use of space

### PR DESCRIPTION
**Pull request by garrett**
Addressing https://github.com/cockpit-project/cockpit/issues/16435

Currently a work in progress. I'm trying to keep each change separate, at least for now, in case any are controversial.

The goal is to optimize in several places to make the page better overall on smaller screens (and more optimal on larger screens too).

### CODE REVIEW

**Comment by marusak** [comment]
It seems all good to me, thanks! Are you still working on this?

**Comment by garrett** [comment]
Yep, I'm still working on it. Oh! I even have a few local commits that I didn't push related to the top header breadcrumb bar.

**Comment by garrett** [comment]
I did some number crunching on some semi-reliable stats, and came up with a visualization of the likely screen availabilty of our users (as we don't track, this is pretty wild speculation, but it's based on assumptions and available statistics from non-Cockpit sources):

screen-resolution-heatmap

View this at 1:1 (open in new tab and click to expand to 1:1) to see how it compares to the screen you're using. This is definitely an empathy check to feel how little our users can see at one time versus what we can see at one time. Quite a difference, yeah?

This is an auto-levels-adjusted overlay of all the screen sizes. I think the vertical oddness is from iPad usage? Otherwise obvious mobile sizes have been excluded. This visualization is a useful anonymized way of showing the stats. It aligns with what we're seeing elsewhere, although we may have users with slightly higher resolutions than other sites (but not by much... certainly not enough to count).

It's aligned to the top-left. This isn't a direct comparison of resolutions, but a visualization of available screen pixel real estate available to our users. Also, this doesn't take into account browser UI (tabs, bookmarks, etc.) or persistent operating system UI (Windows taskbar, GNOME top bar, macOS menubar, etc.)... so the actual content area is lower.

The darkest landscape rectangle is 1980x720 ("720p" in media terms).

The top 7 most popular screen resolutions are, in order:

Resolution | Marketing term
-- | --
1920 x 1080 | FHD / 1080p
1600 x 864 |  ??? probably some popular laptops and/or screens ???
1366 x 768 | FWXGA
1280 x 720 | HD / WXGA / 720p
2560 x 1440 | (W)QHD
1920 x 1200 | WUXGA
1680 x 1050 | WSXGA+

This is similar to other resolution charts for 2021 on the Internet, but a little bit better resolution wise.

So, sadly, we need to make sure 1280 x 720 is properly supported everywhere, as it's the 4th most common resolution. (And third place is not that far off!) 

But even these larger resolutions are useful, as they are target resolutions to check from time to time to make sure everyone sees optimized content when possible.

**Comment by garrett** [comment]
Rebased

**Comment by garrett** [comment]
Note: When the flex workaround (#17043) lands, it'll fix up the button in the header, so it'll look like this:

Screen Shot 2022-02-24 at 10 52 17

Otherwise, PF's `<Flex>` is problematic for wrapped items. But this flex change affects all of Cockpit (in a good way), not just Metrics.

**Review by martinpitt — APPROVED** [review]
Thanks! I tested this in various situations, and it behaves better now. Especially for the sticky historical header!

**Pull request merged**
