### PR TITLE
Use a JSON file for storing machines

### PR DESCRIPTION
**Pull request by stefwalter**
And remove the Machines and Machine code from cockpitd.

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #2015

**Comment by stefwalter** [comment]
@mvollmer I need help with diagnosing the VERIFY failure here. I get an 'Operation Cancelled' from phantomjs. And I have no idea what couses this.

**Comment by mvollmer** [comment]
Merged to hastily.

**Comment by mvollmer** [comment]
> @mvollmer I need help with diagnosing the VERIFY failure here. I get an 'Operation Cancelled' from phantomjs. And I have no idea what couses this.

This happened to me reliably with check-login, although I think the last hubbot run doesn't show it.

I know how to cure it, but I can't really explain why it is happending now, nor do I know precisely why it happens at all.

The cure:

```
diff --git a/test/check-login b/test/check-login
index f15c9d2..1b955dd 100755
--- a/test/check-login
+++ b/test/check-login
@@ -85,7 +85,10 @@ class TestLogin(MachineCase):
         b.wait_present("#content")
         b.wait_text('#content-user-name', 'Administrator')
 
-        # reload, which should log us in with the cookie
+        # Reload, which should log us in with the cookie.  We wait for
+        # everything to be stable before reloading.  This avoids
+        # "Operation cancelled" errors.
+        b.enter_page("server")
         b.reload()
         b.wait_present("#content")
         b.wait_text('#content-user-name', 'Administrator')
```

So, my theory is that the `reload` causes the ongoing #server loads to be cancelled (reasonable), and the resulting error somehow get charged to the page.

Maybe we could try reverting eb755512a35b.

**Comment by stefwalter** [comment]
Depends on #2034

**Comment by stefwalter** [comment]
This is fixed if merged after #2034 

> Maybe we could try reverting eb75551.

That commit merely exposes the reason behind the failure. Even without that commit things still fail. But they fail with the rather frustrating "fail" message.

**Comment by mvollmer** [comment]
I got this for big avatar images:

```
Mar 27 14:22:32 f22 cockpit-ws[24919]: server is trying to frame of size 136350 or greater, but max supported size is 128KiB
Mar 27 14:22:32 f22 cockpit-ws[24919]: Received extremely large WebSocket data from the server
```

**Comment by stefwalter** [comment]
> I got this for big avatar images:

That's a separate issue. It already existed in the old code.

**Comment by mvollmer** [comment]
> That's a separate issue. It already existed in the old code.

Yep.  We hit it easier now when trying to send multiple base64 avatars in a single message, though.

**Comment by stefwalter** [comment]
Why is the fsread1 channel sending such big messages?

**Comment by mvollmer** [comment]
> Why is the fsread1 channel sending such big messages?

It's File.replace().  It sends the whole content in one go:

```
            /* TODO - don't flood the channel when file_content is
             *        very large.
             */
            if (file_content !== null)
                replace_channel.send(file_content);
            replace_channel.control({ command: "done" });
```

**Comment by stefwalter** [comment]
> It's File.replace(). It sends the whole content in one go:

Aha good catch.

**Comment by stefwalter** [comment]
@mvollmer i filled a follow up #2042

**Pull request closed without merging**
