### PR TITLE
Image refresh for rhel-7 (superseded by/fixed in #7466)

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-7
 * [x] image-refresh rhel-7

### CODE REVIEW

**Comment by stefwalter** [comment]
The image was created without certain packages:

```
Loaded plugins: product-id, search-disabled-repos, subscription-manager
No package systemtap-runtime-virtguest available.
Package yum-utils-1.1.31-42.el7.noarch already installed and latest version
No package qemu-system-x86 available.
No package atomic available.
No package docker available.
No package etcd available.
Package glib-networking-2.50.0-1.el7.x86_64 already installed and latest version
Package kexec-tools-2.0.14-17.el7.x86_64 already installed and latest version
No package kubernetes available.
No package libssh available.
Package 1:NetworkManager-team-1.8.0-9.el7.x86_64 already installed and latest version
No package python-pip available.
No package qemu available.
Package selinux-policy-targeted-3.13.1-166.el7.noarch already installed and latest version
Package subscription-manager-1.19.21-1.el7.x86_64 already installed and latest version
No package storaged available.
No package storaged-lvm2 available.
No package storaged-iscsi available.
Package tuned-2.8.0-5.el7.noarch already installed and latest version
Resolving Dependencies
```

**Comment by martinpitt** [comment]
I did a local rhel-7 image build and run into the same issue, so it's not just a flake. The image build itself should already fail, we shouldn't silently ignore these package installation failures. But we already run the script with `set -e`, so it seems yum just silently ignores these missing packages ☹

I'll look into it.

**Comment by martinpitt** [comment]
I have code to abort the image build on missing packages.

The root cause for these is that the rhel extras repository is missing on the image. `yum-config-manager --enable rhel-7-server-extras-rpms` succeeds and /etc/yum.repos.d/redhat.repo does have rhel-7-server-extras-rpms, but it doesn't work for some reason. `yum list | grep extras-rpms` has plenty of packages in the current master image, but not in this one (or my locally built one).

**Comment by martinpitt** [comment]
Fix is in PR #7466. Keeping this one open for now to avoid the bots creating a new one in vain.

**Pull request closed without merging**
