### PR TITLE
networkmanager: Use active-backup as default for new bonds

### PR DESCRIPTION
**Pull request by mvollmer**
This is the safe choice.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1348066

### CODE REVIEW

**Comment by dperpeet** [comment]
@andreasn have you looked at the discussion on the bug page?
do we need to give any more info here, or should we just change the default and leave the rest as it is?

**Comment by andreasn** [comment]
I haven't seen this before, no. I'll check it out.

**Comment by mvollmer** [comment]
Priority because https://bugzilla.redhat.com/show_bug.cgi?id=1348066 is targeted at 7.2

**Comment by mvollmer** [comment]
I think the question has been answered at https://bugzilla.redhat.com/show_bug.cgi?id=1348066:

> The initial list order probably came from this order:
> https://en.wikipedia.org/wiki/Link_aggregation#Driver_modes
> 
> If active-backup is a safer choice I'll trust your word on it.

...

> Another reason might have been that round-robin gives both load balancing and fault tolerance, and that kind of gave you a good outcome if you wasn't super good at what all the modes does.
But we do not want the defaults to result in something that just breaks setups, so I'm good at switching to active-backup.

**Pull request closed without merging**
