### PR TITLE
test: Update pixel test references after Chromium update

### PR DESCRIPTION
**Pull request by mvollmer**
Some whitespace got bigger, mostly.

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Many thanks! Pre-approving even though tests are still running, as I'll be AFK soon today. Please anybody, land this as soon as green, as it blocks every other PR.

**Comment by mvollmer** [comment]
For reviewing the changes to the reference images: https://github.com/cockpit-project/pixel-test-reference/compare/e497f5ef850f9a18d65072617f4491c70feb15f7..5e88f633c74de21a8f6067abf77da8a0c3bf3d45

**Comment by mvollmer** [comment]
> Some whitespace got bigger, mostly.

Actually, most changes are in how button corners are rendered, I think, but the whitespace changes are the actually visible ones.

**Comment by mvollmer** [comment]
> > Some whitespace got bigger, mostly.
> 
> Actually, most changes are in how button corners are rendered, I think, but the whitespace changes are the actually visible ones.

And many pictures got one pixel wider.

**Pull request merged**
