### PR TITLE
Prettier graphs

### PR DESCRIPTION
**Pull request by mvollmer**
The default colors are a bit light now.   Should we maybe just use a few strong and happy colors, as with the dashboard?

### CODE REVIEW

**Comment by mvollmer** [comment]
Stacked graphs look funny now.

**Comment by mvollmer** [comment]
Stacked plots look better now.

**Comment by andreasn** [comment]
It seems % is not above the numbers, as in the other graphs.

screenshot from 2015-10-12 17-27-21

**Comment by andreasn** [comment]
How come storage is green?

screenshot from 2015-10-12 17-30-13

**Comment by mvollmer** [comment]
> How come storage is green?

This is caused by the "DBG - use stronger colors" commit.  By chance, the active disk got the green color assigned.

If we decide to go with stronger colors, we should put little color markers into the relevant boxes, like we do on the dashboard.

**Comment by mvollmer** [comment]
I can't believe it's green! :-)  (The tests.)

**Comment by mvollmer** [comment]
> It seems % is not above the numbers, as in the other graphs.

Fixed.

**Comment by mvollmer** [comment]
> How come storage is green?

Now this branch uses the standard blueish colors again.

**Comment by mvollmer** [comment]
@andreasn, please check this out again.  Page titles are missing, and I am happy to put them in if you want them, of course.

**Comment by andreasn** [comment]
Sorry for all the pixel obsession, but I feel that the left graph is a bit too much to the right and doesn't align up with the object below on the storage page.

Current:
graph-controls-v2

Adjusted:
graph-controls-v3

**Comment by andreasn** [comment]
Discussed a bit with @mvollmer on IRC with regards to lines under the controls.
http://pasteboard.co/1liIVibn.png vs http://pasteboard.co/1liHmWjH.png

But in the end, I think the lines just adds more noise and doesn't add much additional balance to the page

**Comment by stefwalter** [comment]
This has a WIP commit, so assuming it's WIP.

**Comment by mvollmer** [comment]
> This has a WIP commit, so assuming it's WIP.

We decided to go without titles and with the controls closer to the plots, so this is no longer WIP.

**Comment by mvollmer** [comment]
> Sorry for all the pixel obsession, but I feel that the left graph is a bit too much to the right and doesn't align up with the object below on the storage page.

What exactly should align with what?  Note that aligning the left edge of the unit text with the panel header below is problematic since the unit text might change, and the graphs would need to start moving left and right.

**Comment by andreasn** [comment]
> What exactly should align with what?

The left side of the letter "K" with the left side of the panel below.
b1d23e08-71a5-11e5-97d4-44f50ab0880d

Do you mean it messes up with labels such as "Kbps" etc?

**Comment by mvollmer** [comment]
> Do you mean it messes up with labels such as "Kbps" etc?

Heh, I am stupid.  Right now the unit is right-aligned with a fixed distance to the title text, but we can of course change it to be left aligned.  I'll do that.

**Comment by mvollmer** [comment]
> Heh, I am stupid. Right now the unit is right-aligned with a fixed distance to the title text, but we can of course change it to be left aligned. I'll do that.

Nope, then the unit is misaligned with the axis labels, of course, which is worse.

**Comment by andreasn** [comment]
This should help to align the graphs also in lower resolutions, so it's fully responsive:
https://github.com/andreasn/cockpit/tree/prettier-graphs-responsive

**Comment by mvollmer** [comment]
> This should help to align the graphs also in lower resolutions, ...

Included.

**Comment by dperpeet** [comment]
There's a single quote that needs escaping in [the docker index.html](https://github.com/cockpit-project/cockpit/blob/master/pkg/docker/index.html#L71), in case you're wondering why the highlighting is all messed up. Alternate proposal: "Unable to connect to Docker"

**Comment by stefwalter** [comment]
During testing, lines seem to overlap a lot, is this intentional?

screenshot from 2015-10-16 18-02-31

Aren't these supposed to be stacked graphs?

**Comment by mvollmer** [comment]
> Aren't these supposed to be stacked graphs?

Yes, and I think they are.  It looks like there is a lot of read traffic on one disk, and relatively little on the rest.

The same effect was visible with network interfaces: they would all have a few bytes/s of traffic which caused them all to be stacked on top of each other, but so close together that the lines would overlap.

To fix that for the network interfaces, everything below 200 bytes/s is set to zero and not shown.  Should we do something similar for disks?

Ideally, flot would have an option to only plot a piece of a stacked graphs if it is wider than, say, 3 pixels and not plot it at all otherwise.  I'll look into this.

**Comment by mvollmer** [comment]
Also, the screenshot in https://github.com/cockpit-project/cockpit/pull/2947#issuecomment-148755528 shows the weird label placement: 128 and 64 are inside the grid.  I haven't yet found a way to reproduce this, nor did I find the code in flat that might be responsible for this.  I'll try harder.

**Comment by mvollmer** [comment]
> To fix that for the network interfaces, everything below 200 bytes/s is set to zero and not shown. Should we do something similar for disks?

I have added a threshold of 1000 B/s now for the storage plots.  How does it look now for you?

To be able to specify the threshold in pixels, we would need to add a post-processing step instead of trying to do it ahead of time when filling the data rows.  I'll play with that.

**Comment by mvollmer** [comment]
> To be able to specify the threshold in pixels, we would need to add a post-processing step instead of trying to do it ahead of time when filling the data rows. I'll play with that.

This would require a lot of duplicated computation, afaics.  Let's keep the thresholds.

**Comment by dperpeet** [comment]
> I have added a threshold of 1000 B/s now for the storage plots. How does it look now for you?

Should we notify the user about this somehow? Say, once it happens show an info element near the title which explains what happened when hovering over it? I'm sure we're well into corner-cases here, but it's a small step from "smart help" to hiding information the user would actually like to see.

**Comment by stefwalter** [comment]
There's a hover-over-graph style which displays the series values in patternfly and we'll adopt that once we move to those graphs. Until then, this is good enough.

**Pull request closed without merging**
