### PR TITLE
ws: Use cockpitmemory allocation functions

### PR DESCRIPTION
**Pull request by martinpitt**
The previous dup_string() copied strings containing NUL bytes (and an
explicit length). We don't require that for user or display names, as
they are not allowed to contain NUL bytes, so normal strndup() behaviour
is fine for these.

### CODE REVIEW

**Review by allisonkarlitskaya — CHANGES_REQUESTED** [review]
Note that `dup_string()` isn't exactly `strndup()`, but something more like memdup+x.  I think it's fine in this case, but it deserves a mention in the commit message at least.

**Comment by martinpitt** [comment]
@allisonkarlitskaya : I'll gladly update the commit message, I'm just afraid I don't know where the difference is between strndup() and memcpy() plus extra NUL?

**Comment by allisonkarlitskaya** [comment]
> @allisonkarlitskaya : I'll gladly update the commit message, I'm just afraid I don't know where the difference is between strndup() and memcpy() plus extra NUL?

`strncpy()` copies the given length, or up to the first nul, whatever is less, plus 1 (for nul).  `memdup()` does the whole thing, regardless of any nuls in the input.  So if you wanted to use the given length parameter to index into the string after the copy, that would be fine with `memdup()`, but an error with `strndup()`.

**Comment by martinpitt** [comment]
Ah, of course -- I am aware of memcpu() copying null bytes, but somehow I thought that dup_string() called strlen() itself -- it doesn't. Added a comment and updated the commit message.

**Review by allisonkarlitskaya — APPROVED** [review]
Would have been okay without the code # comments, but doesn't hurt with, either.

**Pull request merged**
