### PR TITLE
package.json: Update PatternFly to 5.0.0-prerelease.16

### PR DESCRIPTION
**Pull request by martinpitt**
As promised in #19111, immediate follow-up to update to the current PF versions and bring them back in sync. I reverted a few hacks from the previous round which should now be fixed properly. But we need to go through pkg/lib/patternfly/patternfly-5-overrides.scss and drop a few more, there are loads of hacks which point to closed issues.

  - :heavy_check_mark:  [expensive](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044608-85599617-fedora-38-expensive/log.html) is an actual improvement for the [top bar separators in dark mode](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044608-85599617-fedora-38-expensive/pixeldiff.html#TestSuperuser-testBasic-topnav-privileged-dark), the others are minor font noise
 - [x] networking also regresses the [firewall dialog radio buttons](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044612-85599617-fedora-38-networking/pixeldiff.html#TestFirewall-testAddServices-firewall-add-services-to-zone-modal); we already saw that in #19111, that was one of the reasons why we held back on the latest versions.
 - [x] networking: [MTU dialog input](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044612-85599617-fedora-38-networking/pixeldiff.html#TestNetworkingMTU-testMtu-networking-mtu-settings-dialog) is too wide now
 - [x] other: [metrics history colors](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230731-042541-fd1e607f-fedora-38-other/pixeldiff.html#TestHistoryMetrics-testEvents-metrics-history-expanded-hour-dark ) are lighter now in dark mode. Looks acceptable for better contrast, but should at least get Garret's sign-off. The rest is okay, and just shows the same minor check box/radio button alignment improvement.
 - [x] networking shows that the [dialog check boxes](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044612-85599617-fedora-38-networking/pixeldiff.html#TestBridge-testBasic-networking-bridge-settings-dialog) are further apart. This may be a regression, maybe an improvement, but at least needs checking
- [x] all checkboxes and radio buttons are now [differently misaligned](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230731-042548-fd1e607f-fedora-38-networking/pixeldiff.html#TestBridge-testBasic-networking-bridge-settings-dialog): before they were slightly off to the top, now a little less slightly off to the bottom:
    before: image
    after: image
    it's IMHO an improvement, but maybe we can get this pixel-perfect? 
[another example](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230731-042544-fd1e607f-fedora-38-storage/pixeldiff.html#TestStorageUsed-testUsed-format)
- [x] [horizontal alignment of firewall "add zone" dialog is broken](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230803-135418-eb91c8e2-fedora-38-networking/pixeldiff.html#TestFirewall-testMultipleZones-firewall-add-zone-dialog); hopefully fixed in https://github.com/patternfly/patternfly/pull/5788
- [x] Fix the radios so that they're also fixed by the check fix. (They need a little bit of extra work, but could rely on the same technique.)
- [x] Add an issue for the radio and check alignment upstream in PF: https://github.com/patternfly/patternfly/issues/5802  and add a comment in PF5 overrides.

[pixel diff review](https://github.com/cockpit-project/pixel-test-reference/compare/ccf0d43bb2e80cf9eb1ac3729e9304bcefd6a317..1f6b16a7bcd1817c84c85a96f7c9ec906f52d678)

### CODE REVIEW

**Comment by martinpitt** [comment]
Review of the first round:

  - :heavy_check_mark:  [expensive](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044608-85599617-fedora-38-expensive/log.html) is an actual improvement for the [top bar separators in dark mode](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044608-85599617-fedora-38-expensive/pixeldiff.html#TestSuperuser-testBasic-topnav-privileged-dark), the others are minor font noise
 - [ ] networking shows that the [dialog check boxes](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044612-85599617-fedora-38-networking/pixeldiff.html#TestBridge-testBasic-networking-bridge-settings-dialog) are further apart. This may be a regression, maybe an improvement, but at least needs checking
 - [ ] networking also regresses the [firewall dialog radio buttons](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044612-85599617-fedora-38-networking/pixeldiff.html#TestFirewall-testAddServices-firewall-add-services-to-zone-modal); we already saw that in #19111, that was one of the reasons why we held back on the latest versions.
 - [ ] networking: [MTU dialog input](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044612-85599617-fedora-38-networking/pixeldiff.html#TestNetworkingMTU-testMtu-networking-mtu-settings-dialog) is too wide now
 - :heavy_check_mark: storage: [luks dialog checkbox](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044610-85599617-fedora-38-storage/pixeldiff.html#TestStorageLuks-testLuks-format) is an improvement (base line aligned), although still not perfectly centered; the other dialogs are exactly the same
 - [ ] other: [metrics history colors](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044610-85599617-fedora-38-other/pixeldiff.html#TestHistoryMetrics-testEvents-metrics-history-expanded-hour-dark) are lighter now in dark mode. Looks acceptable for better contrast, but should at least get Garret's sign-off. The rest is okay, and just shows the same minor check box/radio button alignment improvement.

**Comment by jelly** [comment]
> 



> Review of the first round:
> 
>     * ✔️  [expensive](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044608-85599617-fedora-38-expensive/log.html) is an actual improvement for the [top bar separators in dark mode](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044608-85599617-fedora-38-expensive/pixeldiff.html#TestSuperuser-testBasic-topnav-privileged-dark), the others are minor font noise
> 
>     * [ ]  networking shows that the [dialog check boxes](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044612-85599617-fedora-38-networking/pixeldiff.html#TestBridge-testBasic-networking-bridge-settings-dialog) are further apart. This may be a regression, maybe an improvement, but at least needs checking
> 
>     * [ ]  networking also regresses the [firewall dialog radio buttons](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044612-85599617-fedora-38-networking/pixeldiff.html#TestFirewall-testAddServices-firewall-add-services-to-zone-modal); we already saw that in [package.json: Update @patternfly/patternfly to 5.0.0-prerelease.8 #19111](https://github.com/cockpit-project/cockpit/pull/19111), that was one of the reasons why we held back on the latest versions.

The checkboxes look way off to me, we need to figure out what caused this.

>     * [ ]  networking: [MTU dialog input](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044612-85599617-fedora-38-networking/pixeldiff.html#TestNetworkingMTU-testMtu-networking-mtu-settings-dialog) is too wide now
> 
>     * heavy_check_mark storage: [luks dialog checkbox](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044610-85599617-fedora-38-storage/pixeldiff.html#TestStorageLuks-testLuks-format) is an improvement (base line aligned), although still not perfectly centered; the other dialogs are exactly the same
> 
>     * [ ]  other: [metrics history colors](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044610-85599617-fedora-38-other/pixeldiff.html#TestHistoryMetrics-testEvents-metrics-history-expanded-hour-dark) are lighter now in dark mode. Looks acceptable for better contrast, but should at least get Garret's sign-off. The rest is okay, and just shows the same minor check box/radio button alignment improvement.

**Comment by martinpitt** [comment]
@jelly Your quoting was a bit odd, but I suppose you mean the [checkbox label alignment](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230726-044610-85599617-fedora-38-storage/pixeldiff.html#TestStorageLuks-testLuks-format). To me the baseline alignment 

image

looks better than the one in current main, which is completely off:

image

but of course a proper centering would be even better. I turned the checkmark into a todo item.

**Comment by martinpitt** [comment]
@garrett Do you have some time to look at the check boxes here? I've been trying for a while, but I can't make sense of them. IMHO they look better than current main, so we could already land it as-is. (Same with the slightly different metrics colors). But I'd like you to at least have a look. Thank you!

**Comment by garrett** [comment]
After lots of playing of all sorts of different combinations of CSS, I managed to find a combo that mostly works across browsers, at least for the checks. I have it applied to checks and radios at the moment; I need to verify in radios too.

Here's what it looks like (zommed in crops) with Chromium, WebKit, Gecko:
image

It can't be perfectly aligned everywhere, as there are different heights of pixels (some even, some odd) across the browsers. When it doubt, I let it render a little taller (as the check inside the box is weighted that way anyway), and this makes it so Chrome is correct and the others are consistent.

I'll push up a commit that does this now. We'll need to run it through the tests, and I need to look to see what it does with radios (and ideally it'll be the same).

**Comment by garrett** [comment]
Same order: Blink (Chrome), WebKit (Safari/GNOME Web), Gecko (Firefox):

image

It seems the height for Firefox is different from the other two? Everything is aligned top-heavy again, but perhaps it should all be shifted down a pixel?

Sigh... to be continued. At least we're a lot closer now?

**Comment by martinpitt** [comment]
@garrett: E. g. the [bond dialog](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230731-172656-7d8573fc-fedora-38-networking/pixeldiff.html#TestBonding-testBasic-networking-bond-settings-dialog) or the [sos dialog](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19138-20230731-172656-7d8573fc-fedora-38-other/pixeldiff.html#TestSOS-testBasic-dialog) show some effect: The alignment is much  better indeed! The checkboxes have much less space in between them in the networking dialog now, though; curiously, they have a bit more in the sos dialog (which is good, they were too crammed before).

**Comment by garrett** [comment]
With radios, Firefox has align-items: baseline 2px off per item. Centered would (probably) work in most cases and make it the same, but it would break checks/radios in some cases (long text that wraps), so it really should be baseline. Normal, the default, also works with the CSS changes I made. It does fix up Firefox some, but it's still off by 1px instead of two.

Apologies for the shift in order (it's just the order of the browsers of the moment on my screen)... here's WebKit (Web), Gecko (Firefox), Blink (Chrome) _after_ changing baseline to normal:

image

It's closer. It's still a pixel off, and that adds up over time, as you can see by each baseline marked by a guide in the above zoomed-in screenshot.

(WebKit and Blink render it the same. Firefox, the one in the middle, is off a little on each.)

Normal brings us closer, but I haven't _checked_ checks everywhere. :wink:  I wonder what the tests would say about this change.

Curiously, radios are differently sized on "Allowed addresses" than "Trust level"... was this always the case?

image

(This is WebKit, but they're smaller in Firefox and Chrome too...?!?!)

**Comment by martinpitt** [comment]
@garrett That's already the case on main, so not a regression. This is on Firefox:

image

**Comment by martinpitt** [comment]
At least in a local rpm mock build, the version is still broken. The included dbusmock/_version.py seems correct, though.

**Comment by martinpitt** [comment]
Meh, I was very sure I update to final 5.0 (and my `git reflog` still has that), but it's not the current state here. As all the remaining pixel diffs are good, let's land this and update to final in a new PR. I'm currently working on the PF issue for the checkboxes.

**Comment by martinpitt** [comment]
I went through all the pixel diffs again, and they are universally better now. Garrett's patches did an enormous improvement to our broken check boxes everywhere :smile: I reported the issue upstream, added the refs, refreshed node_modules and updated pixels. :crossed_fingers:

**Review by jelly — APPROVED** [review]

**Pull request merged**
