### PR TITLE
Image refresh for {fedora,rhel,continuous}-atomic

### PR DESCRIPTION
**Pull request by cockpituous**
* [x] image-refresh fedora-atomic
 * [x] image-refresh rhel-atomic
 * [x] image-refresh continuous-atomic

### CODE REVIEW

**Comment by petervo** [comment]
We need to add libcrypto somehow.

**Comment by mvollmer** [comment]
`rpm-ostree install` can download dependencies itself, so we should be able to just let it install the cockpit-dashboard rpm.  Do we already know why this wont work?

**Comment by mvollmer** [comment]
> rpm-ostree install can download dependencies itself, so we should be able to just let it install the cockpit-dashboard rpm. Do we already know why this wont work?

D'oh, we don't want to go to the network during tests...

**Comment by mvollmer** [comment]
Let's turn '/root/rpms` into a proper repo and let rpm-ostree satisfy dependencies from it.  I'll work on that.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-dhswd.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171011-122929/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171011-122929/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-0v88p.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171011-134545/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171011-134545/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-cxl2k.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171011-222525/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171011-222525/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-6dtgz.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171012-063333/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171012-063333/

**Comment by martinpitt** [comment]
@mvollmer: meh, no idea what goes wrong with uploading right now :-(

**Comment by martinpitt** [comment]
I updated htpasswd for the changed github token everywhere, so it ought to work better now.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-f0fhb.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171012-081717/

**Comment by cockpituous** [comment]
image-refresh fedora-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-atomic-20171012-082929

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-0954d.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171012-083232/

**Comment by mvollmer** [comment]
Hrr, continuous-atomic has its own setup script...

**Comment by cockpituous** [comment]
image-refresh continuous-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-continuous-atomic-20171012-084545

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171012-090707/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171012-090707/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-72m05.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171012-095353/

**Comment by cockpituous** [comment]
image-refresh continuous-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-continuous-atomic-20171012-100606

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171012-115353/

**Comment by cockpituous** [comment]
image-refresh rhel-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-atomic-20171012-121414

**Comment by mvollmer** [comment]
Something went wrong with the continuous-atomic image... Did I include the wrong commit?

**Comment by mvollmer** [comment]
> Something went wrong with the continuous-atomic image... Did I include the wrong commit?

Current theory: Changes to /etc are lost when booting into a new ostree deployment, if these changes are made after the new deployment was created.

**Comment by mvollmer** [comment]
```
# fully upgrade host. Anything past this point can't touch /etc
```

Aha.  :-)

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-1hc2p.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171012-133030/

**Comment by cockpituous** [comment]
image-refresh fedora-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-atomic-20171012-134545

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-m5x3x.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171012-140202/

**Comment by cockpituous** [comment]
image-refresh continuous-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-continuous-atomic-20171012-141919

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7834-20171012-144444/

**Comment by cockpituous** [comment]
image-refresh rhel-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-atomic-20171012-150101

**Comment by martinpitt** [comment]
`testNonDefaultBondSettings (check_networking_bond.TestNetworking)` [failed](https://fedorapeople.org/groups/cockpit/logs/pull-7834-20171012-211414-42ea19f8-verify-continuous-atomic/log.html#25) three times in a row on continuous-atomic... But trying once more.

**Comment by martinpitt** [comment]
Some more restarts, the `testNonDefaultBondSettings` failure is real.

**Comment by mvollmer** [comment]
> Some more restarts, the testNonDefaultBondSettings failure is real.

Interesting, I haven't seen that failure ever before.

**Comment by mvollmer** [comment]
> Some more restarts, the testNonDefaultBondSettings failure is real.

Apparently, `ipv4.method shared` needs `dnsmasq` locally, which is missing from cockpituous-atomic.  Let's use `link-local` instead of `shared`, since we just need some interesting non-default value.

**Comment by mvollmer** [comment]
I am afraid we have to test all images since the last commit affects them all.

**Comment by martinpitt** [comment]
`testBondingMain()` gets/got skipped on ubuntu-stable, so it's not affected, all other tests succeeded. For some reason the last few tests hang for a long time, but that doesn't need to block this PR.

**Pull request closed without merging**
