### PR TITLE
WIP: Image refresh for rhel-atomic

### PR DESCRIPTION
**Pull request by dperpeet**
blocked on #5152

### CODE REVIEW

**Comment by dperpeet** [comment]
bot: Image refresh for rhel-atomic

**Comment by stefwalter** [comment]
This also blocks on #5175

**Comment by dperpeet** [comment]
> This also blocks on #5175

right.
I'm adding the kubernetes containers for this image and creating it on my machine.

**Comment by cockpituous** [comment]
Image creation for rhel-atomic in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-atomic-dae63142b669c08301d49876cf48633d79a4c14e/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by stefwalter** [comment]
This conflicts with recent changes. We've changed what's tested on Atomic. Lets close it.

**Pull request closed without merging**
