### PR TITLE
Update to Patternfly v2.2.0

### PR DESCRIPTION
**Pull request by stefwalter**
Update to Patternfly v2.

The actual driving issue here is new icons. However the new icons come with a whole lot of baggage. I thought I'd try and see what it would be like to update to Patternfly v2.

### CODE REVIEW

**Comment by mvollmer** [comment]
We seem to have lost the selectpicker jQuery plugin.

**Comment by stefwalter** [comment]
bootstrap-select has become AMD aware, and so I guess it shouldn't be bundled with jquery any longer. I'll see if we can figure out how to solve this.

**Comment by stefwalter** [comment]
Depends on #2718

**Comment by stefwalter** [comment]
screenshot from 2015-09-08 12-30-18

@rhamilto @andreasn Styling of Cockpit navigation is completely broken by Patternfly v2. See above screenshot, or try out this pull request.

**Comment by rhamilto** [comment]
@stefwalter, with PatternFly 2.0.0, you need to include 2 stylesheets.  My guess is that you're not including patternfly-additions.*css in addition to patternfly.*css.  See https://github.com/patternfly/patternfly/releases/tag/v2.0.0.

**Comment by stefwalter** [comment]
@rhamilto Thanks. Can we use an @import instead (on IE 10 and later)?

**Comment by rhamilto** [comment]
@stefwalter PatternFly uses separate stylesheets linked from &lt;head&gt; because @import is less performant than &lt;link&gt;.  http://www.stevesouders.com/blog/2009/04/09/dont-use-import/

**Comment by stefwalter** [comment]
> @stefwalter PatternFly uses separate stylesheets linked from <head> because @import is less performant than <link>. http://www.stevesouders.com/blog/2009/04/09/dont-use-import/

We use @import during development, and then collapse everything into a large stylesheets for production. So I think that will continue to work, especially since we don't support IE before version 10.

FWIW, we have to munge patternfly's stylesheets with `sed` anyway ... because as is, even using less, they're not ready for use directly. For example we take out all the unnecessary font formats, and haven't found a way to do that via less.

**Comment by rhamilto** [comment]
> For example we take out all the unnecessary font formats, and haven't found a way to do that via less.

Unnecessary font formats?

**Comment by stefwalter** [comment]
> Unnecessary font formats?

As far as I know, all the browsers we support can consume woff.

**Comment by stefwalter** [comment]
@rhamilto By the way, one for the v2.0.0 release notes?

 * bootstrap-select now registers itself as an AMD module if requirejs (or similar) is available.

**Comment by rhamilto** [comment]
@stefwalter, Hmm.  I'm a little leery of putting dependency specifics in the release notes if they don't impact PatternFly markup or CSS.  It seems like it could be a slippery slope otherwise.  Thoughts?

**Comment by stefwalter** [comment]
> @stefwalter, Hmm. I'm a little leery of putting dependency specifics in the release notes if they don't impact PatternFly markup or CSS. It seems like it could be a slippery slope otherwise. Thoughts?

Up to you. But it's the sort of thing that broke our upgrade, and I spent a while reworking things in 2 pull requests to accomodate.

**Comment by stefwalter** [comment]
@andreasn This is ready for review. Thanks @rhamilto for your help. I've also updated the icons used in the kubernetes Cockpit component in a commit in this pull request.

**Pull request closed without merging**
