### PR TITLE
kubernetes: Count containers not pods

### PR DESCRIPTION
**Pull request by stefwalter**
On the dashboard we should count containers, not pods.
    
Multi-container pods aren't *that* common, but we should reflect the number of containers in the 'Kubernetes Services' and 'Kubernetes Nodes' listings correctly.

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #2257

**Comment by stefwalter** [comment]
Rebased.

**Comment by stefwalter** [comment]
Rebased.

**Comment by mvollmer** [comment]
Would it make sense to add a test for this now?

**Comment by stefwalter** [comment]
> Would it make sense to add a test for this now?

Not unless we can actually pull images and have them start for real. This would take the kubernetes testing to the next level. I think we agreed not to do this in our last discussion right?

**Pull request closed without merging**
