### PR TITLE
test: Compress journals

### PR DESCRIPTION
**Pull request by martinpitt**
They take up 60% of our total log space and compress really well. E. g.
20 MB → 380 kB gzipped.

 - [x] Support compressed logs in logs.html: https://github.com/cockpit-project/bots/pull/657

### CODE REVIEW

**Comment by martinpitt** [comment]
Moreover, this will also significantly reduce the network traffic and sink latency.

**Comment by martinpitt** [comment]
So [the current test](https://logs.cockpit-project.org/logs/pull-13755-20200319-091829-92f9bae4-fedora-32/log.html) lacks "journal" links in the html as the depending cockpit-project/bots#657 hasn't landed yet. But they are fine in the [results directory](https://logs.cockpit-project.org/logs/pull-13755-20200319-091829-92f9bae4-fedora-32/).

**Comment by marusak** [comment]
> So the current test lacks "journal" links in the html as the depending cockpit-project/bots#657 hasn't landed yet. But they are fine in the results directory.

We can trigger `fedora-32@bots#657` to make sure things works as expected :)

**Comment by martinpitt** [comment]
I just retriggered it now, as the bots PR landed now.

**Comment by martinpitt** [comment]
Retry finished (passed even), and the journal log.gz links work fine.

**Pull request merged**
