### PR TITLE
PackageKit updates: headerbar mobile

### PR DESCRIPTION
**Pull request by garrett**
Depends on:
 - [x] #9292 
 - [x] #9243

### CODE REVIEW

**Comment by garrett** [comment]
**WIP**: needs to be rebased on #9292 and #9243.

**Comment by garrett** [comment]
Removes tables for layout, allows for better accessibility and mobile friendliness.

**Comment by garrett** [comment]
Have been optimizing and testing cross-browser. So far, so good. Haven't tested IE/Edge yet.

This reworks the headings and the info bar at the top, even in a desktop size. (Although, on larger widths, the area looks about the same, even though it's a different implementation.)

**Comment by garrett** [comment]
Found some issues in Edge (and corrected them); now testing in IE.

**Comment by garrett** [comment]
Rebased.

The Edge edge case is list related, not part of the headerbar changes. I'm happy to split it out to another PR if you'd like. It's small, but not really part of the headerbar work (and that's why it's still on its own commit). Same goes for the indentation.

**Comment by martinpitt** [comment]
Actually, this still needs some work. The test suite is making some assumptions about `<td>` being in the header bar, that needs to be adjusted.

**Comment by martinpitt** [comment]
Tests adjusted, rebased to master, force-pushed to your branch.

**Pull request merged**
