### PR TITLE
Add projectData and containsSubject selector

### PR DESCRIPTION
**Pull request by stefwalter**
This adds a selector to which you can pass users or groups,
or their names ... and it'll match objects that have these
as their subject.

### CODE REVIEW

**Comment by stefwalter** [comment]
This is untested so probably doesn't work yet.

@subin I need some policybinding examples to make sure the code I wrote works
as expected. Could you send me some JSON files to create users, and add
the relevant roles, and policybindings  for them as we're expecting for
the registry?

**Comment by stefwalter** [comment]
Here is the command to add more stuff to the policy bindings in our test openshift vm:

```
oc patch --namespace=marmalade policybinding ':default' -p '{"roleBindings":[{"name":"admin","roleBinding":{"metadata":{"name":"admin","namespace":"financeproj","uid":"6cd9233f-da2a-11e5-a83c-5254009e00f1","resourceVersion":"10324","creationTimestamp":"2016-02-23T12:39:05Z"},"userNames":["myadmin"],"groupNames":null,"subjects":[{"kind":"User","name":"myadmin"}],"roleRef":{"name":"admin"}}},{"name":"edit","roleBinding":{"metadata":{"name":"edit","namespace":"financeproj","uid":"6c8b34da-da2a-11e5-a83c-5254009e00f1","resourceVersion":"10326","creationTimestamp":"2016-02-23T12:39:04Z"},"userNames":["myadmin","amanda"],"groupNames":null,"subjects":[{"kind":"User","name":"myadmin"},{"kind":"User","name":"amanda"}],"roleRef":{"name":"edit"}}},{"name":"view","roleBinding":{"metadata":{"name":"view","namespace":"financeproj","uid":"6cb6e140-da2a-11e5-a83c-5254009e00f1","resourceVersion":"10329","creationTimestamp":"2016-02-23T12:39:05Z"},"userNames":["myadmin","tom","amanda"],"groupNames":["sports"],"subjects":[{"kind":"User","name":"myadmin"},{"kind":"User","name":"tom"},{"kind":"User","name":"amanda"},{"kind":"Group","name":"sports"}],"roleRef":{"name":"view"}}}]}'
```

**Comment by sub-mod** [comment]
waiting for tests to pass
but so far LGTM

**Comment by stefwalter** [comment]
Fixed test-projects.html failures

**Pull request closed without merging**
