### PR TITLE
bots: Adjust RHEL 8.0 bootstrap URL

### LINKED ISSUE #11611: Image refresh for rhel-8-0
Image refresh for rhel-8-0
 * [ ] FAIL: image-refresh rhel-8-0

### PR DESCRIPTION
**Pull request by martinpitt**
The current nightlies don't have images any more as they moved to
z-Stream. Use the last 8.0.0 compose that still has an image, and let
the setup script upgrade to the latest versions.

See RCM-55538 and RCM-55988.

Fixes #11611

 * [x] image-refresh rhel-8-0

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-pj109.
Log: https://209.132.184.41:8493/logs/image-refresh-11694-20190429-064141/

**Comment by cockpituous** [comment]
image-refresh rhel-8-0 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-0-20190429-070404

**Comment by martinpitt** [comment]
[resize failures](https://209.132.184.41:8493/logs/pull-11694-20190429-073939-5c37fb56-verify-rhel-8-0/log.html), retrying for comparison

**Comment by martinpitt** [comment]
Locally all tests succeed sometimes, but I can reproduce the resize flake sometimes.

**Comment by martinpitt** [comment]
I filed issue #11697 about the resize flakes.

**Comment by martinpitt** [comment]
Good enough; the remaining failure is being debugged in PR #11698.

**Comment by martinpitt** [comment]
Between this run and the previous one, all tests succeeded.

**Pull request merged**
