### PR TITLE
Run cockpit-bridge under valgrind for phantomjs tests

### PR DESCRIPTION
**Pull request by stefwalter**
This will hopefully let us catch more problems.

### CODE REVIEW

**Comment by stefwalter** [comment]
Initial rough testing on my machine with this branch did not expose the cause of the error of #2618. However I think this is a good change to have nonetheless.

**Comment by petervo** [comment]
I tested this and would have merged but i wasn't able to reproduce the travis error, not sure it's related.

**Comment by stefwalter** [comment]
f22 failure is #2618

**Comment by stefwalter** [comment]
Cherry picked #2646 into this, as well.

**Comment by stefwalter** [comment]
Rebased to include the docker fix.

**Pull request closed without merging**
