### PR TITLE
Easy branding

### PR DESCRIPTION
**Pull request by stefwalter**
Make it easier to maintain branding diffs between Fedora, upstream cockpit, and other distros.

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #1910

**Comment by stefwalter** [comment]
@jscotka @mvollmer How can we see more details on the test failure?

**Comment by jscotka** [comment]
Hi,
you can check: 
http://files.cockpit-project.org/home/hubbot/avocado/job-results/job-2015-03-16T09.46-a34957c/html/results.html 
it is linked in output 
there is: http://files.cockpit-project.org/home/hubbot/avocado/job-results/job-2015-03-16T09.46-a34957c/test-results/root/avocado/tests/home/hubbot/hubbot/71b96d339e0097102e5ca1ca6b9a5e2c6118637a.1/test-avocado/checklogin-basic.py/debug.log

05:48:36 ERROR| FAIL /root/avocado/tests/home/hubbot/hubbot/71b96d339e0097102e5ca1ca6b9a5e2c6118637a.1/test-avocado/checklogin-basic.py -> AssertionError: There were unexpected journal messages

I'm not sure if it is bug in test or it is caused by some runtime error

**Comment by andreasn** [comment]
Works great!
It would need some documentation about how it works with the configure flag, as it's only mentioned in the commit as far as I can see. Maybe in the HACKING file.

**Comment by stefwalter** [comment]
```
error: Domain snapshot not found: no domain snapshot with matching name 'initialized'
```

**Comment by mvollmer** [comment]
> error: Domain snapshot not found: no domain snapshot with matching name 'initialized'

This is not actually an error but a side-effect of checking whether the snapshot exists.  This message should be hidden.

**Comment by stefwalter** [comment]
Failing due to unrelated bug:

```
[stef@falcon ~]$ python
Python 2.7.8 (default, Nov 10 2014, 08:19:18) 
[GCC 4.9.2 20141101 (Red Hat 4.9.2-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import base64
>>> base64.b64decode('MA0KDQpIVFRQLzEuMSAyMDAgT0sNCkNhY2hlLUNvbnRyb2w6IG1heC1hZ2U9MzE1NTY5MjYsIHB1YmxpYw0KQ29udGVudC1UeXBlOiB0ZXh0L2Nzcw0KVHJhbnNmZXItRW5jb2Rpbmc6IGNodW5rZWQNCg0K')
'0\r\n\r\nHTTP/1.1 200 OK\r\nCache-Control: max-age=31556926, public\r\nContent-Type: text/css\r\nTransfer-Encoding: chunked\r\n\r\n'
```

**Comment by stefwalter** [comment]
Successful testing depends on #1936

**Pull request closed without merging**
