### PR TITLE
Kubernetes Filter Bar

### PR DESCRIPTION
**Pull request by stefwalter**
Basic implementation button of the filter button on the filter bar. Refactor the filter bar. The URL is not yet affected.

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #2705

**Comment by petervo** [comment]
We probably want to get rid of the selectWatcher directive in app.js.

Should clear selection also remove "view only selected" restriction as well?

**Comment by stefwalter** [comment]
> We probably want to get rid of the selectWatcher directive in app.js.

Yup.

> Should clear selection also remove "view only selected" restriction as well?

Yes it should. Good catch.

**Comment by stefwalter** [comment]
Needs an addition to the integration test.

**Comment by stefwalter** [comment]
Integration tests fixed up.

**Pull request closed without merging**
