### PR TITLE
package.json: Update patternfly package dependency

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```Makefile.am:	cp -L $(subst dist/fonts,$(srcdir)/node_modules/patternfly/dist/fonts,$@) $@.tmp && $(MV) $@.tmp $@
doc/guide/api-base1.xml:  <refentry id="api-base1-patternfly">
doc/guide/api-base1.xml:      <refentrytitle>patternfly.css</refentrytitle>
doc/guide/api-base1.xml:      <refname>patternfly.css</refname>
doc/guide/api-base1.xml:    <refsection id="api-base1-patternfly-description">
doc/guide/api-base1.xml:&lt;link href="../base1/patternfly.css" type="text/css" rel="stylesheet"&gt;
doc/guide/api-base1.xml:@import url('../base1/patternfly.css');
doc/guide/api-base1.xml:      <para>The standard <ulink url="https://www.patternfly.org/">PatternFly</ulink> CSS stylesheets.
package.json:    "patternfly": "3.27.7",
package.json:    "patternfly-bootstrap-combobox": "1.1.7",
pkg/apps/index.html:    <link href="../base1/patternfly.css" rel="stylesheet">
pkg/dashboard/index.html:    <link href="../base1/patternfly.css" rel="stylesheet">
pkg/docker/console.html:    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
pkg/docker/docker.css:/* workaround: make text red for select if contained in has-error, not in patternfly */
pkg/docker/index.html:    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
pkg/kdump/index.html:    <link rel="stylesheet" href="../base1/patternfly.css">
pkg/kubernetes/index.html:  <link rel="stylesheet" href="../base1/patternfly.css">
pkg/kubernetes/registry.html:<link rel="stylesheet" href="../base1/patternfly.css">
pkg/lib/cockpit-components-listing.jsx: * https://www.patternfly.org/list-view/
pkg/lib/page.css:/* HACK: Workaround for https://github.com/patternfly/patternfly/issues/174*/
pkg/lib/page.css:/* HACK: word-wrap workaround for long alerts https://github.com/patternfly/patternfly/issues/491 */
pkg/lib/page.css:/* HACK: https://github.com/patternfly/patternfly/issues/255 */
pkg/lib/table.css:/* Override patternfly to fit buttons and such */
pkg/lib/table.css:/* Override the heavy patternfly headers */
pkg/lib/variables.less:@import (less) "../../node_modules/patternfly/src/less/variables.less";
pkg/machines/index.html:  <link rel="stylesheet" href="../base1/patternfly.css">
pkg/networkmanager/index.html:    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
pkg/ostree/index.html:  <link href="../base1/patternfly.css" rel="stylesheet">
pkg/packagekit/index.html:  <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
pkg/packagekit/updates.css:/* http://www.patternfly.org/pattern-library/communication/empty-state/ has a
pkg/playground/jquery-patterns.html:    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
pkg/playground/metrics.html:    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
pkg/playground/pkgs.html:    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
pkg/playground/plot.html:    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
pkg/playground/react-patterns.html:    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
pkg/playground/service.html:    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
pkg/playground/speed.html:    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
pkg/playground/test.html:    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
pkg/playground/translate.html:    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
pkg/selinux/setroubleshoot-view.jsx: * https://www.patternfly.org/patterns/empty-state/
pkg/selinux/setroubleshoot.css:/* from patternfly .list-view-pf-actions
pkg/selinux/setroubleshoot.css: * update this when we update patternfly
pkg/selinux/setroubleshoot.html:    <link rel="stylesheet" href="../base1/patternfly.css">
pkg/shell/index.html:    <link href="../base1/patternfly.css" rel="stylesheet">
pkg/shell/shell.less:/* workaround: make text red for select if contained in has-error, not in patternfly */
pkg/shell/simple.html:    <link href="../base1/patternfly.css" rel="stylesheet">
pkg/shell/stub.html:    <link href="../base1/patternfly.css" rel="stylesheet">
pkg/sosreport/index.html:    <link href="../base1/patternfly.css" rel="stylesheet">
pkg/storaged/index.html:    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
pkg/subscriptions/index.html:    <link rel="stylesheet" href="../base1/patternfly.css">
pkg/subscriptions/subscriptions-view.jsx: * https://www.patternfly.org/patterns/empty-state/
pkg/systemd/host.js:require("patternfly-bootstrap-combobox/js/bootstrap-combobox");
pkg/systemd/index.html:    <link href="../base1/patternfly.css" rel="stylesheet">
pkg/systemd/logs.html:  <link href="../base1/patternfly.css" rel="stylesheet">
pkg/systemd/services.html:    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
pkg/systemd/terminal.html:    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
pkg/users/index.html:    <link href="../base1/patternfly.css" type="text/css" rel="stylesheet">
src/base1/Makefile.am:	dist/base1/patternfly.min.css.gz \
src/base1/Makefile.am:	dist/base1/patternfly.min.css.map \
src/base1/Makefile.am:dist/base1/patternfly.min.css: dist/base1/patternfly-base.css dist/base1/patternfly-additions.css
src/base1/Makefile.am:	cat $(srcdir)/node_modules/jquery/dist/jquery.js $(srcdir)/node_modules/bootstrap/dist/js/bootstrap.js $(srcdir)/node_modules/patternfly/dist/js/patternfly.js > $@.tmp && $(MV) $@.tmp $@
src/base1/Makefile.am:dist/base1/patternfly.min.css.map: dist/base1/patternfly.min.css
src/base1/Makefile.am:# Modify the patternfly files appropriately
src/base1/Makefile.am:dist/base1/patternfly-base.css: dist/base1/patternfly.css.map
src/base1/Makefile.am:	sed -f $(srcdir)/tools/patternfly.sed $(srcdir)/node_modules/patternfly/dist/css/patternfly.css > $@.tmp && $(MV) $@.tmp $@
src/base1/Makefile.am:dist/base1/patternfly.css.map:
src/base1/Makefile.am:	cp $(srcdir)/node_modules/patternfly/dist/css/patternfly.css.map $@.tmp && $(MV) $@.tmp $@
src/base1/Makefile.am:dist/base1/patternfly-additions.css: dist/base1/patternfly-additions.css.map
src/base1/Makefile.am:	sed -f $(srcdir)/tools/patternfly.sed $(srcdir)/node_modules/patternfly/dist/css/patternfly-additions.css > $@.tmp && $(MV) $@.tmp $@
src/base1/Makefile.am:dist/base1/patternfly-additions.css.map:
src/base1/Makefile.am:	cp $(srcdir)/node_modules/patternfly/dist/css/patternfly-additions.css.map $@.tmp && $(MV) $@.tmp $@
src/base1/Makefile.am:	cp $(srcdir)/node_modules/patternfly/dist/fonts/fontawesome-webfont.woff $@.tmp && $(MV) $@.tmp $@
src/base1/Makefile.am:	cp $(srcdir)/node_modules/patternfly/dist/fonts/glyphicons-halflings-regular.woff $@.tmp && $(MV) $@.tmp $@
src/base1/Makefile.am:dist/base1/fonts/patternfly.woff:
src/base1/Makefile.am:	cp $(srcdir)/node_modules/patternfly/dist/fonts/PatternFlyIcons-webfont.woff $@.tmp && $(MV) $@.tmp $@
src/base1/Makefile.am:	dist/base1/fonts/patternfly.woff \
src/base1/Makefile.am:	dist/base1/patternfly-base.css \
src/base1/Makefile.am:	dist/base1/patternfly.min.css \
src/base1/Makefile.am:	dist/base1/patternfly.min.css.map \
src/base1/Makefile.am:	dist/base1/patternfly.css.map \
src/base1/Makefile.am:	dist/base1/patternfly-additions.css \
src/base1/Makefile.am:	dist/base1/patternfly-additions.css.map \
src/base1/Makefile.am:	dist/base1/fonts/patternfly.woff \
src/base1/Makefile.am:	dist/base1/patternfly-base.css \
src/base1/Makefile.am:	dist/base1/patternfly.min.css \
src/base1/Makefile.am:	dist/base1/patternfly.min.css.gz \
src/base1/Makefile.am:	dist/base1/patternfly.min.css.map \
src/base1/Makefile.am:	dist/base1/patternfly.css.map \
src/base1/Makefile.am:	dist/base1/patternfly-additions.css \
src/base1/Makefile.am:	dist/base1/patternfly-additions.css.map \
src/base1/cockpit.css:@import url('patternfly.css');
src/base1/cockpit.css:/* HACK: Workaround for https://github.com/patternfly/patternfly/issues/174*/
src/base1/cockpit.css:/* Override patternfly to fit buttons and such */
src/base1/cockpit.css:/* Override the heavy patternfly headers */
src/base1/cockpit.css:/* HACK: word-wrap workaround for long alerts https://github.com/patternfly/patternfly/issues/491 */
src/base1/cockpit.css:/* HACK: https://github.com/patternfly/patternfly/issues/255 */
test/verify/files/embed-cockpit.html:    <base href="https://rawgit.com/patternfly/patternfly/master/tests/cards.html">
test/verify/files/embed-cockpit.html:    <link href="../dist/css/patternfly.min.css" rel="stylesheet" media="screen, print">
test/verify/files/embed-cockpit.html:    <link href="../dist/css/patternfly-additions.min.css" rel="stylesheet" media="screen, print">
test/verify/files/embed-cockpit.html:    <script src="../dist/js/patternfly.min.js"></script>
tools/build-debian-copyright:            if mod == 'patternfly':
tools/patternfly.sed:s/src: url.*PatternFlyIcons-webfont.woff.*/src: url('fonts\/patternfly.woff') format('woff');/
tools/test-static-code:# Bad paths or modifications in patternfly for fonts
tools/test-static-code:    echo "ERROR: invalid patternfly fonts paths found" >&2
tools/test-static-code:    echo "not ok 5 patternfly-font-paths"
tools/test-static-code:    echo "ok 5 patternfly-font-paths"
```

**Comment by cockpituous** [comment]
npm-update patternfly done: https://github.com/cockpituous/cockpit/commits/npm-update-patternfly-20171009-204545

**Comment by cockpituous** [comment]
Task threw an exception: http://fedorapeople.org/groups/cockpit/logs/npm-update-7845-20171009-204545/

**Comment by martinpitt** [comment]
[Changelog](https://github.com/patternfly/patternfly/releases/tag/v3.27.7) only has one [fix](https://github.com/patternfly/patternfly/commit/47d91216) which looks safe.

**Pull request merged**
