### PR TITLE
test: Enable storage tests on Debian

### PR DESCRIPTION
**Pull request by mvollmer**
Depdends on #4108

### CODE REVIEW

**Comment by mvollmer** [comment]
Creating a partition with parted results in a add/remove/add sequence of udev events.  This confuses storaged when it tries to create and immediately format a new partition.

**Comment by stefwalter** [comment]
```
 1: testLuks (check_storage_luks.TestStorage) screenshot journal
16: testBasic (check_storage_multipath.TestStorage) screenshot journal
65: testISCSI (check_storage_iscsi.TestStorage) screenshot journal 
```

**Comment by mvollmer** [comment]
> ```
16: testBasic (check_storage_multipath.TestStorage) screenshot journal
65: testISCSI (check_storage_iscsi.TestStorage) screenshot journal 
```

I have skipped these: iSCSI isn't supported yet in storaged on Debian, and installing multipath-tools seems to change a lot of things.

**Comment by mvollmer** [comment]
> installing multipath-tools seems to change a lot of things.

Hmm, just the serial number of hotplugged drives isn't picked up by storaged, which looks like a storaged bug.  So I'll look at that.

**Comment by mvollmer** [comment]
> Hmm, just the serial number of hotplugged drives isn't picked up by storaged, which looks like a storaged bug. So I'll look at that.

https://github.com/storaged-project/storaged/pull/54

Let's skip multipath for now and get back to it once the serial numbers aren't lost anymore.

**Comment by mvollmer** [comment]
> Let's skip multipath for now and get back to it once the serial numbers aren't lost anymore.

Maybe to elaborate on the consequences of the bug: In order to support/test multipath on Debian, we need to install multipath-tools, which brings in sg3-utils-udev, which causes all serial numbers to disappear from the storaged API, which causes all our tests to break since they use (fake) serial numbers to identify the hotplugged drives.

**Comment by mvollmer** [comment]
> Creating a partition with parted results in a add/remove/add sequence of udev events. This confuses storaged when it tries to create and immediately format a new partition.

This also happens on Fedora, but we don't hit that race condition for some reason.  A simple ">/dev/sda" in bash is enough to see the "remove/add" event sequence.

If any partition of a block device is mounted, the "remove/add" events for a partition don't happen and there is a single "change" event.

**Comment by mvollmer** [comment]
>> Creating a partition with parted results in a add/remove/add sequence of udev events. This confuses storaged when it tries to create and immediately format a new partition.

> This also happens on Fedora, but we don't hit that race condition for some reason.  A simple ">/dev/sda" in bash is enough to see the "remove/add" event sequence.

This has probably just been fixed: https://github.com/storaged-project/storaged/commit/eb4b994c8a12c77744431f1a8459126889c647f9

**Pull request closed without merging**
