### PR TITLE
Small test cleanups

### PR DESCRIPTION
**Pull request by martinpitt**
This doesn't change much yet, but these are some common commits between my experimental electron+nightmare and chromium-headless branches which apply to our current tests as well.

Wrt. renaming phantom-lib.js: At some point we should rename its `ph_*()` functions to `cockpit_test_*()` or `ct_*()` or similar, as these have nothing to do specifically with Phantom. But this would be much more intrusive, and we can do that clarification later.

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-ch43v.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8051-20171109-132323/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8051-20171109-132323/

**Comment by martinpitt** [comment]
Oh no, not again ☹
```
curl: (7) Failed to connect to cockpit-tests port 8493: No route to host
image-upload: unable to upload image: https://209.132.184.69:8493/
```

**Comment by martinpitt** [comment]
PR #8055 fixes image uploads (for the time being, at least while we don't lose both verifymachines again), so once that lands I'll retry the image build.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-9bkd4.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8051-20171110-063232/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-37ghx.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8051-20171110-063232/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-38r4x.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8051-20171110-063333/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8051-20171110-063333/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-m4sjl.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8051-20171110-082727/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-s0z4j.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8051-20171110-082727/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8051-20171110-082727/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-x7tk6.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8051-20171113-071010/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-v7ksh.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8051-20171113-071111/

**Comment by martinpitt** [comment]
For comparison and saving the link: the [test run against the current image](https://fedorapeople.org/groups/cockpit/logs/pull-8051-20171109-131818-d274c1af-verify-fedora-25/log.html) looks rather sad. So failures here might have regressed earlier already.

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8051-20171113-071111/

**Comment by martinpitt** [comment]
I don't understand the image upload failure. In `oc rsh cockpit-tasks-v7ksh` I manually ran `bots/image-upload fedora-25`, this worked fine. And in PR #8073 the bot successfully uploaded an automatically built image. Thus I pushed the symlink update myself.

**Comment by martinpitt** [comment]
I just realized  that phantomjs is required on the fedora-25 image for the avocado tests. I dropped that commit, and cleaned up all the related image refresh comments.

**Comment by petervo** [comment]
Renaming seems premature. I'm ok with removing the unused function though.

**Comment by martinpitt** [comment]
OOI, why premature? Anyway, this isn't very important, it was mostly a check that nothing else depends on the old name. I'm fine with folding this into #8069 if you prefer.

**Comment by petervo** [comment]
Yeah, lets fold https://github.com/cockpit-project/cockpit/pull/8051/commits/6aba503bcd79e1dcc4cefc3c5e73f13b8ca3989a into #8069

**Pull request closed without merging**
