### PR TITLE
7.4 backports: fix build in nspawn, bug fixes

### LINKED ISSUE #6291: Failed to add machine: Unexpected type 'int' in argument
Hello,

First of all, many thanks for your work.

I have a problem and no clue how to deal with.

Let's assume that i have my Ubuntu laptop (Ubuntu 16.04 / Cockpit 137-0 via ppa) and a server (Debian Jessie / cockpit 136-0 via repository).

I want to connect my Laptop to the server (like if i have a vsphere client connecting an esxi). The main goal is to have a basic management tool on my laptop for my server without exposing cockpit on the server.

I install cockpit 137-0 on my laptop, then on the server (136-0) and i try to add the server into the dashboard on the laptop.

My ssh port isn't 22 but a port above 1024. (as example i will use 1337)

First step : 
```
Adresse : my.server.com:1337 
Seem to be ok.
```

Second step : 
```
username : USER
password : PASSWORD
```

Result : 
`Failed to add machine: Unexpected type 'int' in argument.`

I try to look in /etc/cockpit.conf but the file is not present.
I don't really know were to look for clues.

I will continue to troubleshoot.

Any help will be appreciated.

Thanks in advance. :)

### PR DESCRIPTION
**Pull request by martinpitt**
* Fix building in nspawn (otherwise the [build fails](https://fedorapeople.org/groups/cockpit/logs/pull-7705-20170918-151111-dff84ca0-verify-rhel-7/log.html) on current images)
 * Fix non-standard ssh ports (https://bugzilla.redhat.com/show_bug.cgi?id=1478828)
 * Fix timers (https://bugzilla.redhat.com/show_bug.cgi?id=1478832)

### CODE REVIEW

**Comment by martinpitt** [comment]
Sigh, we *just* got rhel-7.4 branch tests working a few weeks ago, and now it seems the package build got broken (there's no build log in the results directory). I can actually reproduce that locally, and it appears to be a really strange tar error:
```
DEBUG: + cd /builddir/build/BUILD
DEBUG: + cd /builddir/build/BUILD
DEBUG: + rm -rf cockpit-138.x
DEBUG: + /usr/bin/gzip -dc /builddir/build/SOURCES/cockpit-138.x.tar.gz
DEBUG: + /usr/bin/tar -xf -
DEBUG: gzip: /builddir/build/SOURCES/cockpit-138.x.tar.gz: unexpected end of file
DEBUG: /usr/bin/tar: Unexpected EOF in archive
DEBUG: /usr/bin/tar: Unexpected EOF in archive
DEBUG: /usr/bin/tar: Error is not recoverable: exiting now
DEBUG: Fehler beim Bauen des RPM:
DEBUG: Fehler: Fehler-Status beim Beenden von /var/tmp/rpm-tmp.F44XVJ (%prep)
DEBUG:     Fehler-Status beim Beenden von /var/tmp/rpm-tmp.F44XVJ (%prep)
DEBUG: Child return code was: 1
INFO: EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 590, in do
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
Error: Command failed: 
 # /usr/bin/systemd-nspawn -q -M 8ae2add60e7e47c484be076ae9c51cc6 -D /var/lib/mock/epel-7-x86_64/root --setenv=LANG=de_DE.UTF-8 --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOSTNAME=mock --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=HOME=/builddir --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PS1=<mock-chroot> \s-\v\$  -u mockbuild bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/cockpit.spec
```

**Comment by martinpitt** [comment]
On second run I didn't hit the weird tar EOF error, but got some test failures instead; these sound like issue #7395, we aren't prepared yet for building in nspawn, at least not on the rhel-7.4 branch. Our rhel-7 images now have nspawn enabled in mock, so I take it these got fixed on master, but I'm not sure if that's worth backporting.

**Comment by martinpitt** [comment]
I backported the [test fix for nspawn](https://github.com/cockpit-project/cockpit/commit/b186e4c233ac), which seems harmless enough - in exchange cockpit can be built on the default RHEL 7.4 mock configuration, which is no small win. I also backported the timers fix, so this PR now contains both changes which we want to make to 7.4 base.

**Comment by petervo** [comment]
So this is interesting, the rhel-7-4 tests fail because this PR is patching packages that are part of base on so not installed on that system. So it looks like we might need changes to the way that image is built when it is run on the rhel-7-4 branch.

**Comment by martinpitt** [comment]
@petervo: Right; I was going to explain that once the rhel-7 tests pass (there is a flake). The rhel-7 tests prove that the fixes (and accompanying test changes) work once these fixes land in RHEL 7.4. While the rhel-7-4 test failures prove that the test cases actually detect/reproduce the bug and that these two features are really broken in current RHEL.

My gut feeling is that for updates to RHEL base (i. e. this branch) the "rhel-7" tests are definitive and should stay green, while the rhel-7-4 tests should be definitive for PRs to RHEL extras (we don't currently have/need a branch for that, but we might again), and of course for master. I would like that better than crippling the rhel-7-4 tests in that branch, only to uncripple them in a couple of weeks when the fixes land. WDYT?

**Comment by petervo** [comment]
That makes sense. I kind of would like something better than having red x for 7.4 meaning things are good here. But I don't have a better suggestion ATM.

**Comment by martinpitt** [comment]
`testNegotiate` is really hard to get green on rhel-7; after some 5 retries this repeatedly failed. Can we investigate this separately and ignore  for now?

**Pull request merged**
