### PR TITLE
[no-test] bots: Add insights-client to rhel-7-8

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh rhel-7-8

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-12695-20190903-133232/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-01.
Log: https://209.132.184.41:8493/logs/image-refresh-12695-20190903-133333/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-12695-20190903-133333/

**Comment by martinpitt** [comment]
Failure looks like a network flake, retrying.

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-12695-20190903-135555/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-12695-20190903-135555/

**Comment by marusak** [comment]
`http://download.devel.redhat.com/rhel-7/nightly/EXTRAS-7/latest-EXTRAS-7.8-RHEL-7/compose/Server/x86_64/os/repodata/repomd.xml: [Errno 14] HTTP Error 403 - Forbidden`

It really is not available, there is no `latest-EXTRAS-7.8-RHEL-7` in `http://download.devel.redhat.com/rhel-7/nightly/EXTRAS-7`.

**Comment by martinpitt** [comment]
@marusak: Weird -- it was introduced just a few days ago, and apparently built on Aug 29..

**Comment by marusak** [comment]
It definitely existed back then - both I checked it manually and it built. 
If this would be image refresh I would just wait few day.
This is bit urgent I guess but I am not sure if we can do something about it. ( don't see any extras for rhel-7.8 there which would be complete)

**Comment by martinpitt** [comment]
Interestingly, issue #12680 fails with yet another reason:
```
+ dnf install -y --setopt=install_weak_deps=False mock
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Fedora 28 - x86_64                              464  B/s | 196  B     00:00    
Failed to download metadata for repo 'fedora'
Error: Failed to download metadata for repo 'fedora'
```

We still grab the `mock` package from Fedora 28 apparently? We should change that to EPEL.

**Comment by martinpitt** [comment]
As an intermediate hack we could use extras from RHEL 7.7, to unblock the image refresh?

**Comment by marusak** [comment]
> As an intermediate hack we could use extras from RHEL 7.7, to unblock the image refresh?

If it won't cause any dependencies problems, then surely we can

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://209.132.184.41:8493/logs/image-refresh-12695-20190904-102222/

**Comment by cockpituous** [comment]
image-refresh rhel-7-8 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-8-20190904-105252

**Comment by martinpitt** [comment]
Looks good. But this is still missing a Closes #. Also, you can't run the rhel-7-8 test here, you need to trigger the stable branch `rhel-7-8@cockpit-project/cockpit/rhel-7.8` (see bots/image-refresh)

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-12695-20190904-140101/

**Comment by mvollmer** [comment]
EXTRAS-7.8 is back, so let's drop the hack.

**Comment by cockpituous** [comment]
image-refresh rhel-7-8 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-8-20190904-143838

**Pull request merged**
