### PR TITLE
package.json: Update @patternfly/react-styles, @patternfly/react-table, @patternfly/patternfly, @patternfly/react-core

### PR DESCRIPTION
**Pull request by cockpituous**

### CODE REVIEW

**Review by KKoukiou — APPROVED** [review]

**Comment by KKoukiou** [comment]
@marusak I don't want to self approve my changes - wanna take a quick look when you have time?

**Comment by martinpitt** [comment]
The new terminal pixel test isn't happy, and there's apparently some subtle change in the LUKS dialog? [log](https://logs.cockpit-project.org/logs/pull-16270-20210831-140945-a8ec5b27-fedora-34/log.html) (I can't see any red pixels, must be rather subtle)

**Review by marusak — APPROVED** [review]
Thank you!

**Pull request merged**
