### PR TITLE
build: Move to Babel 7

### PR DESCRIPTION
**Pull request by martinpitt**
Enable the "commonjs" modules option as we still have tons of non-ES6
`module.exports`.

 - [x] Move to webpack 4: PR #10826
 - [x] Prepare for top-level exports: PR #10851
 - [x] Move to  preset-env: PR #10858

### CODE REVIEW

**Comment by martinpitt** [comment]
It worked fine for me locally, but it seems it fails without `--enable-debug`. Investigating.

**Comment by martinpitt** [comment]
It seems we need to update to webpack 4 first, before progressing with this.

**Comment by martinpitt** [comment]
This finally works now. It took me a while to realize why pkg/machines was completely broken, there is a separate cleanup commit now.

**Comment by mvollmer** [comment]
Rebased.

**Comment by martinpitt** [comment]
@mvollmer: Thanks for reviewing/merging the two other PRs! This works fine locally (both with and without debug), but apparently not in our cockpit/tests container (this is why I renamed back to WIP). I investigate.

**Comment by mvollmer** [comment]
> I found the reason and a solution

Yay!  This worked for me locally, too, so that was confusing.  Thanks!

**Pull request merged**
