### PR TITLE
test: Move check-* into new "verify/" directory

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by dperpeet** [comment]
```
1..0
# TESTS PASSED [0s on files]
```
I think this needs some work

**Comment by mvollmer** [comment]
> ```
> 1..0
> # TESTS PASSED [0s on files]
> ```
> I think this needs some work

Yep.  Replaced the `check-verify` symlink with a wrapper.

**Comment by mvollmer** [comment]
Looks like the known issues are not recognized properly.

**Comment by stefwalter** [comment]
```
ImportError: No module named kubelib
```

**Comment by mvollmer** [comment]
> ImportError: No module named kubelib

Fixed.

**Comment by stefwalter** [comment]
Rebase needed.

**Pull request closed without merging**
