### PR TITLE
bot: Fix openshift{,-prerelease} image rebuilds for OpenShift 3.9.0 and kubevirt 0.3.0

### LINKED ISSUE #8866: Image refresh for openshift
Image refresh for openshift
 * [ ] FAIL: image-refresh openshift

### LINKED ISSUE #8924: Image refresh for openshift-prerelease - fixed in #8947
Image refresh for openshift-prerelease
 * [ ] FAIL: image-refresh openshift-prerelease

### PR DESCRIPTION
**Pull request by martinpitt**
kubevirt recently got a 0.3.0 release, but virt-migrator is not part of
it any more, causing an install failure. As we don't need it, just
remove it.

Fixes #8866
Fixes #8924

 * [x] image-refresh openshift
 * [x] image-refresh openshift-prerelease

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-dmgl2.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180405-080303/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-vm5v8.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180405-080303/

**Comment by martinpitt** [comment]
CC @rmohr @jniederm : Does this make sense?

**Comment by martinpitt** [comment]
The previous image refresh [seems stuck at zerodisk](https://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180405-080303/log), so retrying.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-sb8z5.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180405-104949/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-xvqcj.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180405-104949/

**Comment by rmohr** [comment]
> CC @rmohr @jniederm : Does this make sense?

I fear not really. It is simply not part of the project in newer versions. You could simply remove it.

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-p36c1.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180405-105555/

**Comment by martinpitt** [comment]
> You could simply remove it.

Oh, even better :-) Pushed that variant, let's see how far it goes.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-8qldp.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180405-110101/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-5wv91.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180405-110101/

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-20180405-115858

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-c31xh.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180405-115959/

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-20180405-120303

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-p36c1.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180405-120707/

**Comment by cockpituous** [comment]
image-refresh openshift-prerelease done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-prerelease-20180405-120808

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-5wv91.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180405-120808/

**Comment by cockpituous** [comment]
image-refresh openshift-prerelease done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-prerelease-20180405-124545

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-20180405-130000

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-j4925.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180405-130909/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-b5g9g.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180405-130909/

**Comment by martinpitt** [comment]
Oops, editing the description reset the image-refresh checkboxes, that wasn't intended.

**Comment by cockpituous** [comment]
image-refresh openshift-prerelease done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-prerelease-20180405-142626

**Comment by martinpitt** [comment]
Seems openshift fails to start up (openshift-prerelease seems to work). This is unrelated to the change here, but the latest [release](https://github.com/openshift/origin/releases) is now 3.9.0; previous one was 3.7.0. So supposedly some changes from openshift-prerelease now need to be applied to the "proper" openshift image too.

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-20180406-100505

**Comment by martinpitt** [comment]
testKubevirtMachinesList still fails:
```
error: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"namespace":interface {}(nil)}
```

**Comment by martinpitt** [comment]
I fixed the above error, it was a missing (new) macro substition in the  .yaml.in. But after that, the test  fails with
```
virt-launcher-testvm-vl7m2         0/2       ContainerCreating   0          1m
+ oc get pods | grep virt-launcher-testvm
virt-launcher-testvm-vl7m2         0/2       ContainerCreating   0          1m
+ oc get pods | grep virt-launcher-testvm
virt-launcher-testvm-vl7m2         0/2       ContainerCreating   0          1m
Traceback (most recent call last):
  File "test/verify/check-openshift", line 411, in testKubevirtMachinesList
    wait(lambda: "Running" in o.execute("oc get pods | grep virt-launcher-testvm"))
  File "/home/martin/upstream/c2/test/common/testlib.py", line 1281, in wait
    raise Error(msg or "Condition did not become true.")
Error: Condition did not become true.
```

After several minutes, the state changes to
```
 virt-launcher-testvm-vl7m2         1/2       ImagePullBackOff   0          3m
```

The details show what's wrong:
```
# oc describe pod virt-launcher-testvm-vl7m2
Name:         virt-launcher-testvm-vl7m2
Namespace:    kube-system
Node:         f1.cockpit.lan/10.111.112.101
Start Time:   Fri, 06 Apr 2018 09:20:12 -0400
Labels:       kubevirt.io=virt-launcher
              kubevirt.io/domain=testvm
              kubevirt.io/vmUID=3cbb1554-399d-11e8-a8f5-525400123456
Annotations:  openshift.io/scc=privileged
Status:       Pending
IP:           172.17.0.5
Containers:
  volumeregistryvolume:
    Container ID:  
    Image:         kubevirt/cirros-registry-disk-demo:devel
    Image ID:      
    Port:          <none>
    Command:
      /entry-point.sh
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Readiness:      exec [cat /tmp/healthy] delay=2s timeout=5s period=5s #success=2 #failure=5
    Environment:
      COPY_PATH:  /var/run/libvirt/kubevirt-ephemeral-disk/registry-disk-data/kube-system/testvm/disk_registryvolume/disk-image
    Mounts:
      /var/run/libvirt from libvirt-runtime (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-djbpp (ro)
  compute:
    Container ID:  docker://da19e7b9d4b0e01ed320072ceb3e233eb4f57a6dcd16da312f00c296bd758c69
    Image:         kubevirt/virt-launcher:v0.3.0
    Image ID:      docker-pullable://docker.io/kubevirt/virt-launcher@sha256:4274016b1bc831d8ab304cdf52296727aa5561af34acca7fe3bc8ff24aa5c680
    Port:          <none>
    Command:
      /entrypoint.sh
      --qemu-timeout
      5m
      --name
      testvm
      --namespace
      kube-system
      --kubevirt-share-dir
      /var/run/kubevirt
      --readiness-file
      /tmp/healthy
      --grace-period-seconds
      45
    State:          Running
      Started:      Fri, 06 Apr 2018 09:22:46 -0400
    Ready:          True
    Restart Count:  0
    Requests:
      memory:     161679432
    Readiness:    exec [cat /tmp/healthy] delay=2s timeout=5s period=2s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /host-dev from host-dev (rw)
      /var/run/kubevirt from virt-share-dir (rw)
      /var/run/libvirt from libvirt-runtime (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-djbpp (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  virt-share-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt
    HostPathType:  
  libvirt-runtime:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  host-dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  
  default-token-djbpp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-djbpp
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
Events:
  Type     Reason                 Age               From                     Message
  ----     ------                 ----              ----                     -------
  Normal   Scheduled              6m                default-scheduler        Successfully assigned virt-launcher-testvm-vl7m2 to f1.cockpit.lan
  Normal   SuccessfulMountVolume  6m                kubelet, f1.cockpit.lan  MountVolume.SetUp succeeded for volume "libvirt-runtime"
  Normal   SuccessfulMountVolume  6m                kubelet, f1.cockpit.lan  MountVolume.SetUp succeeded for volume "host-dev"
  Normal   SuccessfulMountVolume  6m                kubelet, f1.cockpit.lan  MountVolume.SetUp succeeded for volume "default-token-djbpp"
  Normal   SuccessfulMountVolume  6m                kubelet, f1.cockpit.lan  MountVolume.SetUp succeeded for volume "virt-share-dir"
  Normal   Pulled                 3m                kubelet, f1.cockpit.lan  Container image "kubevirt/virt-launcher:v0.3.0" already present on machine
  Normal   Started                3m                kubelet, f1.cockpit.lan  Started container
  Normal   Created                3m                kubelet, f1.cockpit.lan  Created container
  Warning  Unhealthy              3m (x5 over 3m)   kubelet, f1.cockpit.lan  Readiness probe failed: cat: /tmp/healthy: No such file or directory
  Warning  Failed                 1m (x2 over 3m)   kubelet, f1.cockpit.lan  Failed to pull image "kubevirt/cirros-registry-disk-demo:devel": rpc error: code = Unknown desc = Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed                 1m (x2 over 3m)   kubelet, f1.cockpit.lan  Error: ErrImagePull
  Normal   BackOff                49s (x3 over 3m)  kubelet, f1.cockpit.lan  Back-off pulling image "kubevirt/cirros-registry-disk-demo:devel"
  Warning  Failed                 49s (x3 over 3m)  kubelet, f1.cockpit.lan  Error: ImagePullBackOff
  Normal   Pulling                35s (x3 over 6m)  kubelet, f1.cockpit.lan  pulling image "kubevirt/cirros-registry-disk-demo:devel"
```

So we need to pull the kubevirt/cirros-registry-disk-demo:devel image onto the openshift image.

**Comment by martinpitt** [comment]
I filed https://github.com/kubevirt/kubevirt/issues/874 for the wrong `:devel` tag, and now I'm stuck at a failure with deploying vm.yaml:
```
# oc create -f /kubevirt/vm.yaml
error: unable to recognize "/kubevirt/vm.yaml": no matches for kubevirt.io/, Kind=VirtualMachine
```
Any idea about that?

**Comment by martinpitt** [comment]
> Any idea about that?

nevermind, pilot error.

This now seems to work fine, with my local hacks. I pushed the fixes and workarounds, now wash/rinse/repeat on the image refreshes.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-sb8z5.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180406-143333/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-09rf2.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180406-143333/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-mlmql.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180406-143434/

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-20180406-153535

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-try-38rtl.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180406-153535/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-6ctnb.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8947-20180406-180808/

**Comment by cockpituous** [comment]
image-refresh openshift-prerelease done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-prerelease-20180406-185252

**Comment by martinpitt** [comment]
@suomiy , @mareklibra: With kubevirt 0.3.0, the test project's disk now looks like this:

registrydisk

```
# oc describe vm testvm
[...]
  Volumes:
    Name:  registryvolume
    Registry Disk:
      Image:  kubevirt/cirros-registry-disk-demo:v0.3.0
```

So there is no iSCSI or capacity any more, it's much more like a normal openshift/kube/docker volume. That seems a little odd for a demo project called "iscsi-demo-target.yaml" - is that intended?

**Comment by martinpitt** [comment]
@mareklibra: Does that "use ansible" approach apply to setting up iscsi-demo-target.yaml as well? The problem here is not actually its setup (that works reasonably well), just that it doesn't do (any more) what it says on the tin. If there's an ansible script for setting this up, I'm happy to use this of course.

Also, if you would prefer to disable the kubevirt functionality for now, I can do that, too.

The bigger blocker here is the new openshift 3.9 behaviour wrt. the registry whitelist anyway.

**Comment by mareklibra** [comment]
@martinpitt indeed, the `iscsi-demo-target` is not used anymore.

In spare time, I'm preparing PR rebasing kubevirt to the latest. Deployment will be based on probably the most tested installation flow recently. Test VM will be changed to latest template as well.

**Comment by mareklibra** [comment]
@martinpitt , tracked here: https://github.com/cockpit-project/cockpit/pull/9012

Most important changes are in different kubevirt deployment (via kubevirt-ansible and kubevirt-apb) and different test VM (vm-template-fedora.yaml).

**Comment by martinpitt** [comment]
Let's use #9012 to fix the openshift images.

**Pull request closed without merging**
