### PR TITLE
[no-test] bots: Add insights-client to rhel-8 images

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh rhel-8-0
 * [x] image-refresh rhel-8-1

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-11981-20190603-072121/

**Comment by cockpituous** [comment]
image-refresh rhel-8-0 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-0-20190603-074848

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-04.
Log: https://209.132.184.41:8493/logs/image-refresh-11981-20190603-075252/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-04.
Log: https://209.132.184.41:8493/logs/image-refresh-11981-20190603-075353/

**Comment by cockpituous** [comment]
image-refresh rhel-8-1 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-1-20190603-082323

**Comment by martinpitt** [comment]
I triggered the two missing tests.

**Comment by martinpitt** [comment]
[rhel-8-1 flake](https://209.132.184.41:8493/logs/pull-11981-20190603-100202-ca3adefa-verify-rhel-8-1/log.html), retrying

**Comment by martinpitt** [comment]
[Two rhel-8-0 flakes](https://209.132.184.41:8493/logs/pull-11981-20190603-120101-ca3adefa-verify-rhel-8-0/log.html), retrying.

**Pull request merged**
