### PR TITLE
tests: remove no_retry_when_changed from  check-machines-storage-pools

### PR DESCRIPTION
**Pull request by KKoukiou**
Let's see how this behaves.

### CODE REVIEW

**Comment by martinpitt** [comment]
@KKoukiou : This doesn't work. We only do the "run tests three times" if ≤ 3 tests got changed in the PR. Otherwise we consider it a "PR that does a major test reorganization" and don't penalize it by requiring that basically *all* tests have to succeed three times in a row. You need to split this up into several smaller PRs. That makes sense anyway, to be able to investigate things in smaller bites.

**Comment by KKoukiou** [comment]
> @KKoukiou : This doesn't work. We only do the "run tests three times" if ≤ 3 tests got changed in the PR. Otherwise we consider it a "PR that does a major test reorganization" and don't penalize it by requiring that basically _all_ tests have to succeed three times in a row. You need to split this up into several smaller PRs. That makes sense anyway, to be able to investigate things in smaller bites.

Oh did not know what, thanks for the clarification.

**Comment by martinpitt** [comment]
@KKoukiou : FYI, that is done [here](https://github.com/cockpit-project/cockpit/blob/master/test/common/run-tests#L216)

**Comment by marusak** [comment]
> We only do the "run tests three times" if ≤ 3 tests got changed in the PR.

3 files not tests, so you can do it in 3 files at once here.

**Comment by KKoukiou** [comment]
> > We only do the "run tests three times" if ≤ 3 tests got changed in the PR.
> 
> 3 files not tests, so you can do it in 3 files at once here.

sure I understood it, I just actually think it makes sense to merge one by one the PRs for the removal of the decorators for the machines tests. I don't have high expectation for their stability.

**Review by martinpitt — APPROVED** [review]
Very nice! One down, 8 to go -- and it's good to start with the ones that are already stable, to avoid regressing those. Tests have not fully finished yet, but are looking good so far.

**Review by martinpitt — APPROVED** [review]
Epharisto!

**Pull request merged**
