### PR TITLE
Revert "test: Speed up CI runs with our jumpstart cache", revert recent PF update

### PR DESCRIPTION
**Pull request by martinpitt**
`webpack-jumpstart --partial` is not currently clever enough to skip the download if package.json changed. This caused PRs with only package.json changes (such as PatternFly updates) to use the cached webpacks, and thus old pixel tests.

Commit b1712355afce updated PatternFly (PR #17623), but due to the previous bug the pixel tests ran against the old webpacks. Now they [fail on main](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17624-20220808-061611-13d26217-fedora-36-bots-3706/).

[pixel diff review](https://github.com/cockpit-project/pixel-test-reference/compare/fe4f1b8ff6e0c98cccfccb8f18c3ffe50a95553e..999b6edce8174e083bb7347524c31e2c4b02ff39) -- only minor spacing changes, acceptable.

### CODE REVIEW

**Review by marusak — APPROVED** [review]
Thank you!

**Comment by martinpitt** [comment]
Meh, [another one](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17625-20220808-072842-60a98313-fedora-36/log.html#207) -- seems this dialog is a bit unstable.

**Comment by martinpitt** [comment]
@marusak : It failed twice on the NFS dialog. I don't have the nerve/capacity to deal with this right now under pressure, let's rather re-do the PF update in a PR in an orderly fashion. I just reverted the PF update instead.

**Review by marusak — APPROVED** [review]
Fair enough, thanks!

**Comment by martinpitt** [comment]
@allisonkarlitskaya : Do you know why [reposchutz failed](https://github.com/cockpit-project/cockpit/runs/7721491640?check_suite_focus=true) here? This was a clean revert of commit b1712355afce8b368c with no commits in between that touched package.json..

This PR just hates me -- I'm just pushing a fresh node_modules/ rebuild to pacify reposchutz, and run tests everywhere.

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
