### PR TITLE
apps: fix buttons jumping around (epiphany) and reimplement to work nicely in small screens

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by garrett** [comment]
I can't compile this. I get errors:

```
/var/home/garrett/Project/cockpit/cockpit/pkg/apps/application-list.jsx
  66:13  error  Unexpected constant condition  no-constant-condition
...
/var/home/garrett/Project/cockpit/cockpit/pkg/apps/utils.jsx
  59:9  error  Unexpected constant condition  no-constant-condition
```

**Comment by garrett** [comment]
I did a hard reset to the current penultimate commit in the PR (basically dropping the DON'T MERGE commit, which seems to break compilation here) and tested the header in WebKit. The two commits definitely fix the header issue.

I can't see the progress bar however, so was unable to test that.

**Comment by garrett** [comment]
> If you refresh the list from the refresh icon on the header you can see the progress bar.

Nope.

I guess it has to do with being on Silverblue?

I'll build a VM. Hopefully that'll work.

**Comment by KKoukiou** [comment]
Before:
Screen Shot 2020-07-23 at 13 51 43

Screen Shot 2020-07-23 at 15 58 13


After:
Screen Shot 2020-07-23 at 15 18 59

Screen Shot 2020-07-23 at 15 18 32

**Comment by garrett** [comment]
We fixed the WebKit jumping thing a few times already. Why is it back? I thought it was previously fixed here too? (Was that not committed?) Ah well, this would supersede that anyway.

Thanks for fixing the mobile view!

Checking out and building it now. (It might take a while... meetings, multitasking, and such.)

**Comment by KKoukiou** [comment]
> We fixed the WebKit jumping thing a few times already. Why is it back? I thought it was previously fixed here too? (Was that not committed?) Ah well, this would supersede that anyway.

It was not commited (the fix for this page specifically)

> 
> Thanks for fixing the mobile view!
> 
> Checking out and building it now. (It might take a while... meetings, multitasking, and such.)

**Comment by KKoukiou** [comment]
Can squash on merge if not changes are required.

**Pull request merged**
