### PR TITLE
firewall: Only reload firewall when adding custom services

### PR DESCRIPTION
**Pull request by Gundersanne**
Add a warning as well that adding a custom service will reload
firewalld, resulting in a loss of runtime-only configuration.

This addresses https://bugzilla.redhat.com/show_bug.cgi?id=1725094 as
well.

### CODE REVIEW

**Comment by Gundersanne** [comment]
image

**Comment by marusak** [comment]
Is #12195 related?

**Comment by Gundersanne** [comment]
@marusak  Yup, also a bz. I made it so we only reload the firewall when adding custom services. The signal we subscribed to to reload was to generous; so now it'll subscribe + unsubscribe after 1 reload.

**Comment by Gundersanne** [comment]
needswork because the test I added doesn't actually fail on master, I want the current test to fail on master of course.

**Comment by garrett** [comment]
We should rephrase this. I didn't understand what the message meant until I re-read it a few times and also looked at the bug in bugzilla.

I have a few* questions:
1. Is there a way to check for unsaved temporary rules?
2. Is there a way we could somehow display these temporary rules?
3. Does it make sense to be able to convert these temporary rules into saved ones?
4. Can we display the disconnect on the page itself instead of just in the dialog? (This might help address some of the above, and it would make things more obvious.)
5. Perhaps if we detect temporary rules, we should make the firewall page go into a "lockdown" read-only mode until it's acknowledged and editing is manually enabled.

(* OK, perhaps _several_ questions. :grin:)

**Comment by Gundersanne** [comment]
>     1. Is there a way to check for unsaved temporary rules?
I don't think so, I just checked again and couldn't find anything. The only way to do this would be to retrieve both configs and compare them.

>     2. Is there a way we could somehow display these temporary rules?
We'd have to make the comparison, and then yes.

>     3. Does it make sense to be able to convert these temporary rules into saved ones?
This is not something we want to do without the user explicitly demanding it I think. So this would be a separate feature.

>     4. Can we display the disconnect on the page itself instead of just in the dialog? (This might help address some of the above, and it would make things more obvious.)
 Again this would require that we do the comparison. And then mark the services that are runtime-only, but then we'd also have to list to separately if that same service is in a permanent configuration of another zone.

Personally I think it makes sense that what we display is the runtime configuration at all times, which may or may not be permanent as well. The whole complexity of the other gui for firewalld stems from this duality, I think it would be best if we could still avoid this.

>     5. Perhaps if we detect temporary rules, we should make the firewall page go into a "lockdown" read-only mode until it's acknowledged and editing is manually enabled.
This would be possible but again would require the comparison to be made between the two configurations. And then I would opt rather for triage first, then adding this as a feature, as I consider the bug to be quite bad.

Regardless of what we do here, with custom services we have to communicate to the user about the runtime/permanent split within firewalld, as it's impossible to enable a custom service without reloading. Personally I would try to minimize this communication as much as possible and only display it when it's relevant. As I think the role of cockpit in this is to abstract some of the complexity for the user (of course this shouldn't result in erroneous configurations).

**Comment by garrett** [comment]
1. How long does the comparison take?
2. If someone does firewalling exclusively from Cockpit, they'd never see this split — right?
3. I think having a lockdown mode (that can be turned off) with a warning and showing manual rules is probably OK, at least for a first pass.

> So this would be a separate feature. We shouldn't do this in the background.

Agreed. I didn't mean we should do this automatically. (I should've been more clear. Whoops.)

**Comment by Gundersanne** [comment]
>     1. How long does the comparison take?
No idea haven't made it yet :D Probably not too long, it involves checking the zones for each enabled service.

>     2. If someone does firewalling exclusively from Cockpit, they'd never see this split — right?
Depends on the default configurations of the distribution I think. But they probably wouldn't see it.

>     3. I think having a lockdown mode (that can be turned off) with a warning and showing manual rules is probably OK, at least for a first pass.
This would only affect custom services though, so could the button be in the AddServices dialog?

**Comment by garrett** [comment]
> This would only affect custom services though, so could the button be in the AddServices dialog? Could we maybe do this in a future patch then? And have the warning message as a triage?

Aha, yeah. That makes sense. I see; this would be a hotfix to mitigate the problem. Good call.

It still would be nice if we could do the comparison check quickly to determine if there's an issue and only show the warning if it actually applies.

But, yeah, I agree with you that doing something other than a simple "there might be an issue" check should go into another future PR.

**Pull request merged**
