### PR TITLE
Fix Fedora 27 image build, unify Fedora setup scripts, work around Fedora 26/27 mock regression, adjust to kubernetes 1.9

### PR DESCRIPTION
**Pull request by martinpitt**
fedora-27 image build is currently broken (issue #8651), and I took the opportunity to clean up our diverging setup scripts (long-standing TODO item of mine..)

 * [x] image-refresh fedora-26
 * [x] image-refresh fedora-27
 * [x] image-refresh fedora-i386

regressions on new image:
 * [x] work around `mock --offline` failure (https://bugzilla.redhat.com/show_bug.cgi?id=1549291)
 * [x] fix unreadable /proc/timer_list
 * [x] fix missing nodes error in k8s test

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-xfgb2.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8693-20180223-074343/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8693-20180223-074343/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-dzlzv.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8693-20180223-075555/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8693-20180223-075555/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-v1b8d.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8693-20180223-080707/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-nl5ff.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8693-20180223-081717/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-mnx9r.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8693-20180223-082323/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-1hj38.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8693-20180223-082323/

**Comment by cockpituous** [comment]
image-refresh fedora-i386 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-i386-20180223-085656

**Comment by cockpituous** [comment]
image-refresh fedora-26 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-26-20180223-090202

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-dhv61.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8693-20180223-090404/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-xfgb2.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8693-20180223-091313/

**Comment by cockpituous** [comment]
image-refresh fedora-27 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-27-20180223-093939

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-nl5ff.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8693-20180223-093939/

**Comment by cockpituous** [comment]
image-refresh fedora-i386 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-i386-20180223-094646

**Comment by martinpitt** [comment]
All images pushed. I triggered an extra fedora-26 test.

**Comment by cockpituous** [comment]
image-refresh fedora-27 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-27-20180223-095454

**Comment by cockpituous** [comment]
image-refresh fedora-26 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-26-20180223-102424

**Comment by martinpitt** [comment]
still needs work; for some reason an image refresh now produces a broken mock:
```
[root@m1 ~]# mock --offline --no-clean --shell
[...]
Start: dnf install
Error: Cache-only enabled but no cache for 'fedora'
ERROR: Command failed: 
 # /usr/bin/dnf --installroot /var/lib/mock/fedora-26-x86_64/root/ --releasever 26 -C --disableplugin=local --setopt=deltarpm=False install @buildsys-build
Error: Cache-only enabled but no cache for 'fedora'
```

**Comment by martinpitt** [comment]
When booting the pristine image, `mock --offline --shell` works fine. But after image-prepare's mock build command, the mock gets destroyed somehow , and after that the shell command fails with that error.

**Comment by martinpitt** [comment]
FTR, rebuilding the fedora-27 image with just the "Update fedora-27 virt-install location" fix fails in the same way, so it's not an issue with the refactored scripts.

**Comment by martinpitt** [comment]
Some notes and observations, on current F26 image:

* Reproducer: `su builder -c '/usr/bin/mock --offline --no-clean --resultdir /tmp/build-results --define='\''os_version_id 26'\'' --no-bootstrap-chroot --verbose --rebuild cockpit-161.x-1.wip.fc26.src.rpm'`
* both mock and dnf have the same version on the new F26 image as on the current one.
* The only significant package in `dnf update` is `mock-core-configs: 27.4-1.fc26 → 28.2-1.fc26. Installing that breaks mock. The relevant diff is (this applies to each repository):
```diff
--- /etc/mock.prev/default.cfg  2017-10-09 02:41:44.000000000 -0400
+++ /etc/mock/default.cfg       2018-01-22 11:57:39.000000000 -0500
@@ -29,44 +29,45 @@
 [fedora]
 name=fedora
 metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
-failovermethod=priority
 gpgkey=file:///usr/share/distribution-gpg-keys/fedora/RPM-GPG-KEY-fedora-26-primary
 gpgcheck=1
+skip_if_unavailable=False
```
* Doing `sed --follow-symlinks -i '/skip_if_unavailable=False/d' /etc/mock/default.cfg` fixes this.

I'll file a Fedora bugzilla and add this workaround here.

**Comment by martinpitt** [comment]
So there are at least two more regressions on the current images:
 * various tests (all failed ones on fedora-i386) fail with `Unexpected journal message 'grep: timer_list: Permission denied'
 * kubernetes tests fail with
```
> warning: error: current-context must exist in order to minify
> warning: received invalid kubectl config 
```

**Comment by martinpitt** [comment]
/proc/timer_list is 400 root:root now, presumably as a mitigation against Spectre, as it contains high-resolution timers. I propose to move to /proc/uptime instead, which still has 1/100 s precision, which should be more than enough for Cockpit's display purposes.

**Comment by martinpitt** [comment]
I can see this on my host system on the dnf-makecache.timer Timer page; "Next Run" says "Invalid date" as `clock_monotonic_now` is undefined and `system_boot_time` is NaN. We apparently don't catch this in the tests, we should test this functionality properly.

**Comment by martinpitt** [comment]
I pushed a fix and a proper test for the timer issue.

**Comment by martinpitt** [comment]
The `received invalid kubectl config` was a red herring. That's the part of the test that covers errors when not yet having a valid .kube/config.

kubelet.service fails on the new image:
```
Error: failed to run Kubelet: Running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false. /proc/swaps contained: [Filename				Type		Size	Used	Priority /dev/dm-1                               partition	839676	7180	-2]
```
This is easy enough to fix, but still doesn't fix the problem that there are no nodes in kubernetes:
```
$ kubectl get nodes
No resources found.
```
On current image I get
```
NAME        STATUS    AGE       VERSION
127.0.0.1   Ready     3m        v1.7.3
```

**Comment by martinpitt** [comment]
I adjusted our tests for the [deprecated and finally removed --api-server](https://github.com/kubernetes/kubernetes/blob/v1.4.0/cmd/kubelet/app/options/options.go#L84-L85) option.

**Comment by martinpitt** [comment]
timer test fails on Fedora 26: https://fedorapeople.org/groups/cockpit/logs/pull-8693-20180227-140707-ef9a6828-verify-fedora-26/log.html#145

Next run is "unknown" there.

**Comment by martinpitt** [comment]
I ran the fedora-26 test a handful of times locally and it works fine. Retrying

**Pull request merged**
