### PR TITLE
bots: Update CentOS Atomic cloud image download

### LINKED ISSUE #9971: Image refresh for continuous-atomic
Image refresh for continuous-atomic
 * [ ] FAIL: image-refresh continuous-atomic

### PR DESCRIPTION
**Pull request by martinpitt**
The file name dropped the "-7". Also move to https:// URL.

Fixes #9971

 * [x] image-refresh continuous-atomic

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-5k2th.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10590-20181115-202323/

**Comment by cockpituous** [comment]
image-refresh continuous-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-continuous-atomic-20181115-204949

**Comment by martinpitt** [comment]
[current cockpit-ostree test](https://fedorapeople.org/groups/cockpit/logs/pull-10590-20181115-212525-fc1d21de-cockpit-project-cockpit-ostree-cockpit-continuous-atomic/log) for comparison with retry

**Comment by martinpitt** [comment]
This seems to consistently fail cockpit-ostree's `testRebase`.

**Comment by martinpitt** [comment]
The error here is that the state is forever stuck in "Updating.." with a spinner, which disables the "Rebase and Reboot" button:

running

This apparently happens while `isRunning` is true, but there is no `scope.progressMsg`. So perhaps the new rpm-ostree now changed/regressed some D-Bus API, this needs to be debugged.

**Comment by martinpitt** [comment]
Closing this for now until I have time to work on this again.

**Pull request closed without merging**
