### PR TITLE
bots: Fix ovirt image build

### LINKED ISSUE #9480: Image refresh for ovirt
Image refresh for ovirt
 * [ ] FAIL: image-refresh ovirt

### LINKED ISSUE #10700: subscription-manager crashes: the 'dbus-python' distribution was not found
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1651669

### PR DESCRIPTION
**Pull request by KKoukiou**
* [x] image-refresh ovirt

ovirt-release41.rpm requires the gluster-3.8 repository which does not
exist any more; so update to the latest ovirt-release42.rpm. This does
not pull in the PostgreSQL client any more, so install that explicitly.

Local postgresql.service is not running after the setup, don't make this
fatal.

Slightly relax the expected error message in the test, as the line break
changed.

Fixes #9480
Closes #10700

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-4vscg.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10701-20181129-122222/

**Comment by cockpituous** [comment]
image-refresh ovirt done: https://github.com/cockpituous/cockpit/commits/image-refresh-ovirt-20181129-125353

**Comment by martinpitt** [comment]
ovirt tests fail :(

**Comment by KKoukiou** [comment]
Adding some debugging notes in case in case someone else wants to take a look as well.

I started with debugging testVCPU. Test ovirt-engine status is up, I can connect to the ovirt engine UI, and I see the VM that we expect to be running is down.
I try manually to start it, and it fails with some error about the libvirt XML.
From the engine.log

```
2018-11-30 08:09:31,145-05 INFO  [org.ovirt.engine.core.vdsbroker.monitoring.VmAnalyzer] (ForkJoinPool-1-worker-3) [] VM 'c1f02d38-2cbe-4273-93d1-c9b3e027d018'(VM) moved from 'WaitForLaunch' --> 'Down'
2018-11-30 08:09:31,247-05 ERROR [org.ovirt.engine.core.dal.dbbroker.auditloghandling.AuditLogDirector] (ForkJoinPool-1-worker-3) [] EVENT_ID: VM_DOWN_ERROR(119), VM VM is down with error. Exit message: XML error: Non-empty feature list specified without CPU model.
2018-11-30 08:09:31,248-05 INFO  [org.ovirt.engine.core.vdsbroker.monitoring.VmAnalyzer] (ForkJoinPool-1-worker-3) [] add VM 'c1f02d38-2cbe-4273-93d1-c9b3e027d018'(VM) to rerun treatment
2018-11-30 08:09:31,256-05 ERROR [org.ovirt.engine.core.vdsbroker.monitoring.VmsMonitoring] (ForkJoinPool-1-worker-3) [] Rerun VM 'c1f02d38-2cbe-4273-93d1-c9b3e027d018'. Called from VDS 'host'
2018-11-30 08:09:31,297-05 WARN  [org.ovirt.engine.core.dal.dbbroker.auditloghandling.AuditLogDirector] (EE-ManagedThreadFactory-engine-Thread-346) [] EVENT_ID: USER_INITIATED_RUN_VM_FAILED(151), Failed to run VM VM on Host host.
```

And a bit more up in the logs there is the VM XML, (which I can't see from the virsh command line, so maybe ovirt VMs are transient or something?)

```
2018-11-30 08:09:30,931-05 INFO  [org.ovirt.engine.core.vdsbroker.vdsbroker.CreateBrokerVDSCommand] (EE-ManagedThreadFactory-engine-Thread-345) [e244e23a-926d-4f60-a01d-eebe2b29292c] VM <?xml version="1.0" encoding="UTF-8"?><domain type="kvm" xmlns:ovirt-tune="http://ovirt.org/vm/tune/1.0" xmlns:ovirt-vm="http://ovirt.org/vm/1.0">
  <name>VM</name>
  <uuid>c1f02d38-2cbe-4273-93d1-c9b3e027d018</uuid>
  <memory>1048576</memory>
  <currentMemory>1048576</currentMemory>
  <iothreads>1</iothreads>
  <maxMemory slots="16">4194304</maxMemory>
  <vcpu current="1">16</vcpu>
  <sysinfo type="smbios">
    <system>
      <entry name="manufacturer">oVirt</entry>
      <entry name="product">OS-NAME:</entry>
      <entry name="version">OS-VERSION:</entry>
      <entry name="serial">HOST-SERIAL:</entry>
      <entry name="uuid">c1f02d38-2cbe-4273-93d1-c9b3e027d018</entry>
    </system>
  </sysinfo>
  <clock offset="variable" adjustment="0">
    <timer name="rtc" tickpolicy="catchup"/>
    <timer name="pit" tickpolicy="delay"/>
    <timer name="hpet" present="no"/>
  </clock>
  <features>
    <acpi/>
  </features>
  <cpu match="exact">
    <model>Nehalem</model>
    <feature policy="require" name="spec-ctrl"/>
    <topology cores="1" threads="1" sockets="16"/>
    <numa>
      <cell id="0" cpus="0" memory="1048576"/>
    </numa>
  </cpu>
  <cputune/>
  <devices>
    <input type="mouse" bus="ps2"/>
    <channel type="unix">
      <target type="virtio" name="ovirt-guest-agent.0"/>
      <source mode="bind" path="/var/lib/libvirt/qemu/channels/c1f02d38-2cbe-4273-93d1-c9b3e027d018.ovirt-guest-agent.0"/>
    </channel>
    <channel type="unix">
      <target type="virtio" name="org.qemu.guest_agent.0"/>
      <source mode="bind" path="/var/lib/libvirt/qemu/channels/c1f02d38-2cbe-4273-93d1-c9b3e027d018.org.qemu.guest_agent.0"/>
    </channel>
    <video>
      <model type="qxl" vram="8192" heads="1" ram="65536" vgamem="16384"/>
      <alias name="ua-2fe70c15-f929-4dec-b694-f0bb2e8e7000"/>
    </video>
    <memballoon model="virtio">
      <stats period="5"/>
      <alias name="ua-3942eebe-4d38-4c63-a204-47c3edb830b7"/>
    </memballoon>
    <sound model="ich6">
      <alias name="ua-4050e358-85be-416a-936f-9ec69afb0866"/>
    </sound>
    <controller type="virtio-serial" index="0" ports="16">
      <alias name="ua-bc7ca53c-450a-4adb-b6b6-e261066a604c"/>
    </controller>
    <controller type="usb" model="piix3-uhci" index="0"/>
    <graphics type="spice" port="-1" autoport="yes" passwd="*****" passwdValidTo="1970-01-01T00:00:01" tlsPort="-1">
      <channel name="main" mode="secure"/>
      <channel name="inputs" mode="secure"/>
      <channel name="cursor" mode="secure"/>
      <channel name="playback" mode="secure"/>
      <channel name="record" mode="secure"/>
      <channel name="display" mode="secure"/>
      <channel name="smartcard" mode="secure"/>
      <channel name="usbredir" mode="secure"/>
      <listen type="network" network="vdsm-ovirtmgmt"/>
    </graphics>
    <rng model="virtio">
      <backend model="random">/dev/urandom</backend>
      <alias name="ua-ea4f5ba9-20f2-4ada-a370-5962a75fa2ef"/>
    </rng>
    <controller type="scsi" model="virtio-scsi" index="0">
      <driver iothread="1"/>
      <alias name="ua-f9138ec7-d5a1-4f5c-9149-3997fbbf9544"/>
    </controller>
    <channel type="spicevmc">
      <target type="virtio" name="com.redhat.spice.0"/>
    </channel>
    <interface type="bridge">
      <model type="virtio"/>
      <link state="down"/>
      <source bridge=";vdsmdummy;"/>
      <alias name="ua-0b24c7ca-e56c-47d6-be00-7416e66c440f"/>
      <boot order="1"/>
      <mac address="56:6f:1b:81:00:00"/>
      <bandwidth/>
    </interface>
    <disk type="file" device="cdrom" snapshot="no">
      <driver name="qemu" type="raw" error_policy="report"/>
      <source file="" startupPolicy="optional"/>
      <target dev="hdc" bus="ide"/>
      <readonly/>
      <alias name="ua-625b9b11-183d-4c12-930c-bacef8d0df4d"/>
    </disk>
  </devices>
  <pm>
    <suspend-to-disk enabled="no"/>
    <suspend-to-mem enabled="no"/>
  </pm>
  <os>
    <type arch="x86_64" machine="pc-i440fx-rhel7.3.0">hvm</type>
    <smbios mode="sysinfo"/>
  </os>
  <metadata>
    <ovirt-tune:qos/>
    <ovirt-vm:vm>
      <minGuaranteedMemoryMb type="int">1024</minGuaranteedMemoryMb>
      <clusterVersion>4.2</clusterVersion>
      <ovirt-vm:custom/>
      <launchPaused>false</launchPaused>
      <resumeBehavior>auto_resume</resumeBehavior>
    </ovirt-vm:vm>
  </metadata>
</domain>
```

**Comment by KKoukiou** [comment]
The error we get ```XML error: Non-empty feature list specified without CPU model``` doesn't make any sense for the XML that's it's printed in  the output, since cpu Model is present in the XML.

On the other hand I don't know to debug further because libvirt doesn't seem to be aware of that VM thst oVirt sees. I can't even define it and start it since in the oVirt host only virsh in readonly mode is available.

**Comment by KKoukiou** [comment]
answer from mlibra on IRC, just to have all information here,
```
(03:32:30 PM) mlibra: kkoukiou, it has been already long time since I was looking into this code
(03:32:45 PM) mlibra: it's most probably pointing to an issue out of the cockpit code base
(03:33:11 PM) mlibra: it _might_ be related to the fake_qemu which is used in the testing ovirt image in cockpit```

**Comment by martinpitt** [comment]
This PR currently breaks our CI as it needs rebasing against current master (missing `bots/tests-invoke --pull-request`). It's also quite stalled, so I close this for now. Let's reopen once we have time to work on this again.

**Pull request closed without merging**
