### PR TITLE
tuned: Support tuned descriptions

### PR DESCRIPTION
**Pull request by stefwalter**
These are retrieved by pulling from the profiles2() function.
    
In addition bring the use of tags closer to how bootstrap and patternfly want list-groups with headings to look.

### CODE REVIEW

**Comment by stefwalter** [comment]
screenshot from 2016-01-25 17-44-53

**Comment by mvollmer** [comment]
Nitpick: If profile descriptions are not available, we still use title and description for the artificial "none" profile.  Is that ok?

https://fedorapeople.org/groups/cockpit/logs/pull-3558-6735b274-verify-rhel-7/TestTuned-testBasic-FAIL.png

**Comment by mvollmer** [comment]
Test fixes here: https://github.com/mvollmer/cockpit/commit/46c8bb0ce3cb0526867c1c54a984e89a4e017724

**Comment by mvollmer** [comment]
I made the changes requested by @andreasn: https://github.com/mvollmer/cockpit/commits/tuned-with-descriptions

**Comment by mvollmer** [comment]
Continues in #3606

**Comment by dperpeet** [comment]
replaced by #3606

**Pull request closed without merging**
