### PR TITLE
Convert low hanging fruit to @nd

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Comment by martinpitt** [comment]
> wait_js_cond(ph_is_visible("#journal-box .cockpit-logline .cockpit-log-message:contains('CHECK-ERROR-INSIDE')")): Uncaught (in promise) Error: #journal-box .cockpit-logline .cockpit-log-message:contains('CHECK-ERROR-INSIDE') is ambiguous

Ah, that test assumes a clean journal, so that requires some saving/restoring (gets caught by 3x affected retries)

**Comment by jelly** [comment]
> > wait_js_cond(ph_is_visible("#journal-box .cockpit-logline .cockpit-log-message:contains('CHECK-ERROR-INSIDE')")): Uncaught (in promise) Error: #journal-box .cockpit-logline .cockpit-log-message:contains('CHECK-ERROR-INSIDE') is ambiguous
> 
> Ah, that test assumes a clean journal, so that requires some saving/restoring (gets caught by 3x affected retries)

Thanks! Didn't had time to look into that yet. We should have a helper for resetting the journal already I assume so that should be easy.

**Review by martinpitt — APPROVED** [review]
This is a nice fix, thanks! (Assuming green)

**Comment by jelly** [comment]
TF does not run TestJournal tests and are known issues (except F39 this is a new TF intermittent failure *hopefully*)

**Pull request merged**
