### PR TITLE
Update de.po

### PR DESCRIPTION
**Pull request by stefanleh**
Corrected german translation of "Drives".

### CODE REVIEW

**Comment by marusak** [comment]
Thank you for this contribution!
This however (also) needs to be updated in [zanata](https://fedora.zanata.org/iteration/view/cockpit/master/languages/de?dswid=-3666) otherwise on the next refresh it is going to be rewritten back.

I cannot update it in Zanata (not for German). Either someone who is in german translator group can do it (If you would be interested [how to become german translator](https://fedoraproject.org/wiki/L10N/Translate_on_Zanata#Find_your_language_team_and_join_in)) or someone who manages cockpit project in zanata. I think both of these hats wears @martinpitt.

**Comment by stefanleh** [comment]
Thanks for the hint. I will try to get into the translator group for german language.
Should i close the PR or is it somehow useful despite the need to add the translations via zanata?

**Comment by marusak** [comment]
> Should i close the PR or is it somehow useful despite the need to add the translations via zanata?

It is the best to do it in zanata and then we can pull this new improved translation (it is done automatically every week). Editing these files manually should be exception. I would close this as it is not going to be released for the next two weeks anyway.

**Comment by martinpitt** [comment]
Eww, what an embarrassing error -- this clearly was done with some translator software, not by a human. I fixed it in Zanata, thank you!

**Pull request closed without merging**
