### PR TITLE
lib: allow showing an in progress action in EmptyStatePanel component

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by marusak** [comment]
So it would change label of the submit button to something like "Downloading..."? That seems odd.

**Comment by KKoukiou** [comment]
> So it would change label of the submit button to something like "Downloading..."? That seems odd.

Now that you say it, we don't really change the button string anywhere, so removing this.

**Comment by marusak** [comment]
```
ERROR in /home/node/cockpit/pkg/lib/cockpit-components-empty-state.jsx
  46:52  error  '?' should be placed at the beginning of the line         operator-linebreak
  47:1   error  Expected indentation of 16 spaces but found 12            indent
  47:13  error  Expected indentation of 16 space characters but found 12  react/jsx-indent
```

**Comment by KKoukiou** [comment]
> ```
> ERROR in /home/node/cockpit/pkg/lib/cockpit-components-empty-state.jsx
>   46:52  error  '?' should be placed at the beginning of the line         operator-linebreak
>   47:1   error  Expected indentation of 16 spaces but found 12            indent
>   47:13  error  Expected indentation of 16 space characters but found 12  react/jsx-indent
> ```

I force pushed some hours ago to fix these. I will force push again, some tests indeed got confused.

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
