### PR TITLE
increase image versions to download new  nulecule app image

### PR DESCRIPTION
**Pull request by sub-mod**
needed for https://github.com/cockpit-project/cockpit/pull/2921

### CODE REVIEW

**Comment by stefwalter** [comment]
@sub-mod Could you tag the images explictly, and pull them down by tag?

**Comment by stefwalter** [comment]
This has been done for fedora-22 ... other images will follow.

**Comment by stefwalter** [comment]
I've been having a real hard time regenerating the atomic image. Will look into this when I get more time.

**Comment by petervo** [comment]
We've moved away from this way of doing things and images have all been updated

**Pull request closed without merging**
