### PR TITLE
test: add Fedora-36

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Comment by jelly** [comment]
https://fedoraproject.org/wiki/Changes/Package_information_on_ELF_objects explains the packagekit issues

**Comment by jelly** [comment]
Abort tests fail due to SELinux:

```
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=cockpit-motd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=cockpit-motd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 abrt-server[2966]: Retrieving coredump with coredumpctl
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 audit[3014]: AVC avc:  denied  { read } for  pid=3014 comm="coredumpctl" name="core.sleep.0.cf86376f90444b499c18591b408eec2f.2896.1645526501000000.zst" dev="vda5" ino=195307 scontext=system_u:system_r:abrt_t:s0-s0:c0.c1023 tcontext=system_u:object_r:systemd_coredump_var_lib_t:s0 tclass=file permissive=0
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 audit[3014]: SYSCALL arch=c000003e syscall=21 success=no exit=-13 a0=7ffc82b17010 a1=4 a2=0 a3=7ffc82b16d56 items=0 ppid=3013 pid=3014 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="coredumpctl" exe="/usr/bin/coredumpctl" subj=system_u:system_r:abrt_t:s0-s0:c0.c1023 key=(null)
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 audit: PROCTITLE proctitle=2F7573722F62696E2F636F726564756D7063746C0064756D7000313634353532363530310032383936002F7573722F62696E2F736C656570002D2D6F75747075743D2E2F636F726564756D70
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 audit[3014]: AVC avc:  denied  { read } for  pid=3014 comm="coredumpctl" name="core.sleep.0.cf86376f90444b499c18591b408eec2f.2896.1645526501000000.zst" dev="vda5" ino=195307 scontext=system_u:system_r:abrt_t:s0-s0:c0.c1023 tcontext=system_u:object_r:systemd_coredump_var_lib_t:s0 tclass=file permissive=0
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 audit[3014]: SYSCALL arch=c000003e syscall=21 success=no exit=-13 a0=562c1a9fff40 a1=4 a2=61 a3=73 items=0 ppid=3013 pid=3014 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="coredumpctl" exe="/usr/bin/coredumpctl" subj=system_u:system_r:abrt_t:s0-s0:c0.c1023 key=(null)
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 audit: PROCTITLE proctitle=2F7573722F62696E2F636F726564756D7063746C0064756D7000313634353532363530310032383936002F7573722F62696E2F736C656570002D2D6F75747075743D2E2F636F726564756D70
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 abrt-server[2966]: Error: File './coredump' is not a coredump
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 abrt-server[2966]: eu-readelf: input file is empty
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 abrt-server[2966]: Error while running gdb:
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 abrt-server[2966]: /usr/libexec/gdb: warning: Couldn't determine a path for the index cache directory.
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 abrt-server[2966]: "/var/spool/abrt/ccpp-2022-02-22-10:41:41.545763-2896/./coredump" is not a core dump: file format not recognized
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 abrt-server[2966]: Python Exception <class 'ValueError'>: invalid literal for int() with base 10: ''
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 abrt-server[2966]: Error occurred in Python: invalid literal for int() with base 10: ''
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 abrt-server[2966]: eu-unstrip: cannot read ELF core file: not a valid ELF file
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 abrt-server[2966]: Can't open file 'core_backtrace' for reading: No such file or directory
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 systemd[1]: Created slice system-dbus\x2d:1.6\x2dorg.freedesktop.problems.slice - Slice /system/dbus-:1.6-org.freedesktop.problems.
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 systemd[1]: Started dbus-:1.6-org.freedesktop.problems@0.service.
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dbus-:1.6-org.freedesktop.problems@0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 abrt-notification[3039]: [🡕] Process 2896 (sleep) crashed in ??()
```

**Comment by jelly** [comment]
New breakage:

```
  sos (4.2-2.fc36 -> 4.3-1.fc36)
```

```
ModuleNotFoundError: No module named 'sos.help'
```

**Review by martinpitt — APPROVED** [review]
Thanks! Triggering a few more tests to be sure that this doesn't regress.

**Pull request merged**
