### PR TITLE
test: Install NetworkManager team plugin

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
I'll let the bot produce the images.

**Comment by mvollmer** [comment]
bot: Image refresh for fedora-24

**Comment by cockpituous** [comment]
Image creation for fedora-24 in process on host32-rack06.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-24-e98be08d08c69e7e7daeebcc9de40783933bb7e9/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-fedora-24-e98be08d08c69e7e7daeebcc9de40783933bb7e9

**Comment by mvollmer** [comment]
bot: Image refresh for fedora-23

**Comment by mvollmer** [comment]
bot: Image refresh for fedora-testing

**Comment by cockpituous** [comment]
Image creation for fedora-23 in process on host32-rack06.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-23-e98be08d08c69e7e7daeebcc9de40783933bb7e9/

**Comment by cockpituous** [comment]
Image creation for fedora-testing in process on host37-rack09.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-testing-ac53e877503548bbe2e9905c84cb64bd560eea53/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-fedora-23-e98be08d08c69e7e7daeebcc9de40783933bb7e9

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-fedora-testing-ac53e877503548bbe2e9905c84cb64bd560eea53

**Comment by mvollmer** [comment]
All images except debian-unstable done.

**Comment by dperpeet** [comment]
also triggering test for `verify/fedora-23` since that has a new image

**Comment by mvollmer** [comment]
I check this:

```
# testMounting (check_storage_mounting.TestStorage)
#
Wrote TestStorage-testMounting-FAIL.png
Journal extracted to TestStorage-testMounting-10.111.122.151-FAIL.log
not ok 92 testMounting (check_storage_mounting.TestStorage)
Traceback (most recent call last):
  File "./verify/check-storage-mounting", line 97, in testMounting
    wait_ratio_in_range(bar_selector, 0.5, 1.0)
  File "./verify/check-storage-mounting", line 90, in wait_ratio_in_range
    })""", sel, low, high)
  File "/build/cockpit/test/common/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 660, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 683, in _invoke
    raise Error(res['error'])
Error: timeout
```

I have seen this a couple of times now.

**Comment by mvollmer** [comment]
> I check this:
> 
> ```
> # testMounting (check_storage_mounting.TestStorage)
> ...
> ```

I couldn't reproduce this locally, not even with lots of load on the machine.  I have retriggered the test, and now this one has passed.

One theory is that the m.execute("dd ...") takes a really long time and that this somehow causes the browser to lose contact with the bridge.  The bridge keeps running during m.execute, but the browser is stopped and doesn't read from the websocket, for example. 

I make a known issue.

**Comment by dperpeet** [comment]
fedora-24 failure:
```
not ok 17 testBridge (check_networking.TestNetworking)
Traceback (most recent call last):
  File "./verify/check-networking", line 258, in testBridge
    b.wait_visible("#networking")
  File "/build/cockpit/test/common/testlib.py", line 225, in wait_visible
    return self.wait_js_func('ph_is_visible', selector)
  File "/build/cockpit/test/common/testlib.py", line 210, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 660, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 683, in _invoke
    raise Error(res['error'])
Error: TypeError: null is not an object (evaluating 'i.Settings.connection')
```

**Comment by mvollmer** [comment]
> `TypeError: null is not an object (evaluating 'i.Settings.connection')`

Hmm, there are a lot of places that assume that Settings is not null, so I added some code that avoids this altogether.

**Comment by dperpeet** [comment]
needs rebase

**Comment by mvollmer** [comment]
bot: Image refresh for rhel-7

**Comment by mvollmer** [comment]
bot: Image refresh for fedora-23

**Comment by mvollmer** [comment]
bot: Image refresh for fedora-testing

**Comment by cockpituous** [comment]
Image creation for fedora-23 in process on host37-rack09.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-23-c37c8d39520a2faf822d200a068ba996488d9b6e/

**Comment by cockpituous** [comment]
Image creation for fedora-testing in process on host32-rack06.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-testing-c37c8d39520a2faf822d200a068ba996488d9b6e/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-fedora-testing-c37c8d39520a2faf822d200a068ba996488d9b6e

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-fedora-23-c37c8d39520a2faf822d200a068ba996488d9b6e

**Comment by mvollmer** [comment]
Images have been refreshed.

**Comment by mvollmer** [comment]
check-realms on fedora-24 has this in the logs:

```
Cannot connect to the IPA server RPC interface: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529638949): Clock skew too great
```

I think we can ignore that for this PR and get back to it when it happens more often.  The tests pass locally.

**Comment by mvollmer** [comment]
check-storage-mounting on fedora-24 is known issue #4574 which didn't get detected here.

**Comment by mvollmer** [comment]
check-storage-mdraid on debian-unstable is known issue #4141 in a different context.

**Pull request closed without merging**
