### PR TITLE
base: Move select react pattern into base

### PR DESCRIPTION
**Pull request by dperpeet**
This is reusable. Also make it easier to use and improve
handling of undefined data.
The dropdown now closes when losing focus.

### CODE REVIEW

**Comment by larsu** [comment]
Cool! Works as advertised and reads much better to me with child elements.

Why did you include the value as first parameter in the onChanged() callback? The data is probably what client code will make decisions on right? Value is translated most of the time anyway.

Stef and I talked about indenting everything inside the define callback in modules. We have started doing that for new modules. If you agree, can you please change this one as well?

**Comment by dperpeet** [comment]
> Why did you include the value as first parameter in the onChanged() callback? The data is probably what client code will make decisions on right? Value is translated most of the time anyway.
I didn't want to not include this and then somebody needs it. But I guess I can remove it for now and just add it in if it's actually needed.

> Stef and I talked about indenting everything inside the define callback in modules. We have started doing that for new modules. If you agree, can you please change this one as well?
Yes, I like that much better. I didn't indent because that's how the other files seemed to be in cockpit.

**Comment by dperpeet** [comment]
done
I also added a commit to fix indentation for the existing react code.

**Comment by dperpeet** [comment]
Note that I added another change that I needed for the docker image run dialog: the top dom node in the select component will receive all the props of the select component.
This is useful for adding extra things like `id`.
https://github.com/cockpit-project/cockpit/pull/4386/files#diff-5177d6e4028668aec8d2e5c2d7030a2fR35

**Comment by dperpeet** [comment]
I changed the select pattern to just get an optional id (not blindly pass through lots of props) and fixed a bug where the select value was passed to onChange instead of the data.

**Comment by dperpeet** [comment]
openshift test failures are fixed in #4395

**Comment by larsu** [comment]
All great, thanks!

**Pull request closed without merging**
