### PR TITLE
Image refresh for ubuntu-1804

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for ubuntu-1804
 * [x] image-refresh ubuntu-1804

### CODE REVIEW

**Comment by marusak** [comment]
@martinpitt @Gundersanne tests again were not triggered. Can you please look into logs with verbose tests-scan? Thank you
I am triggering tests here manually

**Comment by martinpitt** [comment]
@marusak: After tests-scan, you still need to run bots/tests-trigger -f, to "convert" the "pending" to "pending (direct trigger)". I did that for ubuntu-1804 only.

**Comment by martinpitt** [comment]
Logs confirm that the webhook still sees the PR as [no-test] when it gets force-pushed:
```
INFO:root:repo: cockpit-project/cockpit; title: WIP: centosci-tasks-41gc5: [no-test] Image refresh for ubuntu-1804; number: 11548; action: opened
INFO:root:Processing #11548 titled 'WIP: centosci-tasks-41gc5: [no-test] Image refresh for ubuntu-1804' on revision 00a77e05f78cb23eccd701e285fe356ec37e1011
INFO:root:Skipping 'avocado/fedora' on #11548 because it is no-test
[... same for the umpteen other contexts ... ]
INFO:root:repo: cockpit-project/cockpit; title: Image refresh for ubuntu-1804; number: 11548; action: edited
INFO:root:repo: cockpit-project/cockpit; title: Image refresh for ubuntu-1804; number: 11548; action: labeled
INFO:root:repo: cockpit-project/cockpit; title: Image refresh for ubuntu-1804; number: 11548; action: synchronize
INFO:root:Processing #11548 titled 'WIP: centosci-tasks-41gc5: [no-test] Image refresh for ubuntu-1804' on revision 00a77e05f78cb23eccd701e285fe356ec37e1011
INFO:root:Skipping 'avocado/fedora' on #11548 because it is no-test
```
This confirms that the webhook POST data is up to date, but test-scan still sees old data.

**Comment by martinpitt** [comment]
@marusak, @Gundersanne : I worked around a similar problem in https://github.com/cockpit-project/cockpituous/pull/257 . It seems we need to extend that to look at the title as well, i. e. effectively revert https://github.com/cockpit-project/cockpituous/commit/218c363fd095c165ed1f3 . I considered this cleanup of duplicated logic back then, but apparently we need to deal with the "eventual consistency" property of the API.

**Comment by martinpitt** [comment]
Ah no, just reverting https://github.com/cockpit-project/cockpituous/commit/218c363fd095c165ed1f3 won't help at all, as we have the *opposite* problem -- we don't miss the no-test, we miss its removal. We can't completely drop the no-test handling from tests-scan, as it needs to work for a "cold start" of the pod and scan existing PRs. But it seems we need to be able to override/disable its no-test handling with a command line option that `webhook` uses.

So, this should work: (1) Bring back [no-test] handling to webhook and call tests-scan with an option to disable [no-test] checks, (2) implement that option in test-scan. Does either of you two want to work on this?

**Comment by marusak** [comment]
> So, this should work: (1) Bring back [no-test] handling to webhook and call tests-scan with an option to disable [no-test] checks, (2) implement that option in test-scan. Does either of you two want to work on this?

Seems like hack to me. But also it sees a wrong revision - wouldn't that trigger tests against wrong commit? (surely in our case it is just adding Closes line, but in general if someone force-push fast different code all together)

Maybe we could pass from webhook as argument the revision (which is [avaialble](https://developer.github.com/v3/activity/events/types/#pullrequestevent)).  And when tests-scan gets revision and it does not match the one it gets from API, it can retry 3 times getting it from API with some backoff and if still cannot get the correct revision, then give up and log it as "Skipping because revision <...> is not available"

**Comment by martinpitt** [comment]
I filed issue #11554 for this bug, so that it doesn't get lost in various PRs.

**Pull request merged**
