### PR TITLE
Image refresh for rhel-atomic

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for rhel-atomic in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-atomic-2017-02-13/

### CODE REVIEW

**Comment by dperpeet** [comment]
Image creation failed, there's no image.

**Comment by martinpitt** [comment]
```
[1486977801.48] EVENT: Domain 'rhel-atomic-1wxt' (ID 1) Started Booted
+ TEST_OS=rhel-atomic
+ export TEST_OS
+ TEST_SOURCE=/var/tmp/cockpit-131.x.tar.gz
+ export TEST_SOURCE
+ /var/tmp/SETUP
[1486977847.83] EVENT: Domain 'rhel-atomic-1wxt' (ID 1) Shutdown Finished
vm-create: setup failed with code 1
```
Not sure what that means; re-trying to see if it reproduces.

**Comment by martinpitt** [comment]
bot: Image refresh for rhel-atomic

**Comment by cockpituous** [comment]
Image creation for rhel-atomic in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-atomic-e278d2a223f14348e75d9eaf5846f70c2bb6420f/

**Comment by dperpeet** [comment]
If this doesn't work we should increase the timeout for image creation.

**Comment by cockpituous** [comment]
Image creation done.
Branch creation failed.

**Comment by dperpeet** [comment]
replaced by #5883

**Pull request closed without merging**
