### PR TITLE
registry: Implement the filter bar with project selector

### PR DESCRIPTION
**Pull request by stefwalter**
A basic filter bar with the project selector

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #3431

**Comment by petervo** [comment]
We should preserve the namespace selection between tabs.

**Comment by stefwalter** [comment]
Fixed keeping the namespace between tabs, and double checked that behavior is correct on initial load with a namespace as well.

**Comment by dperpeet** [comment]
@stefwalter some of the commits have been merged previously, I think

**Comment by stefwalter** [comment]
Rebased

**Comment by dperpeet** [comment]
I use debug mode and install to the directory and get this:
screenshot from 2016-01-12 11 41 07

**Comment by stefwalter** [comment]
Added missing filter.less file to Makefile.am

**Comment by dperpeet** [comment]
The views seem to be missing in debug mode, e.g.:
`"Error: [$compile:tpload] Failed to load template: views/imagestream-panel.html`

**Comment by dperpeet** [comment]
When selecting a filter in Images and switching to the Overview and back, the filter reset. This may be related to the issue of missing views.

**Comment by stefwalter** [comment]
Fixed distribution of panel files, and also fixed namespace behavior when going to dashboard and back.

**Pull request closed without merging**
