### PR TITLE
Fix the Fedora 22 atomic tests

### PR DESCRIPTION
**Pull request by stefwalter**
* Fix real bug with terminal home directory.

### CODE REVIEW

**Comment by mvollmer** [comment]
> * Account for additional users.

Which change is this?  I can only see the home dir fix.

**Comment by stefwalter** [comment]
Oh, that was moved to #2636

**Comment by stefwalter** [comment]
Filed an issue about test failure here: #2648

**Comment by stefwalter** [comment]
Cherry picked from #2646 into this pull request.

**Pull request closed without merging**
