### PR TITLE
Journal patternfly migration

### PR DESCRIPTION
**Pull request by andreasn**
Port to Patternfly 1.1.3 and clean out some custom css.

### CODE REVIEW

**Comment by andreasn** [comment]
I would like to all the cockpit-logline classes to just using tables and cells as well, like we do on the network page, but I can't for the life of me figure out how to wrap a table around all the lines.

**Comment by dperpeet** [comment]
there's currently an error that I'm following up on (not introduced by these commits, but still there)

`ReferenceError: cockpit is not defined` in `terminal.html`

**Comment by dperpeet** [comment]
ok, I addressed the error in #1956
looks good otherwise

**Comment by dperpeet** [comment]
the changes made require adaptation of the tests - I added the fix in #1961

**Comment by andreasn** [comment]
Closing, since there is #1961

**Pull request closed without merging**
