### PR TITLE
Update ko.po

### PR DESCRIPTION
**Pull request by simmon-nplob**
update translation

### CODE REVIEW

**Comment by marusak** [comment]
Is this serious change? If so, then there is no reason to remove authors.
Anyway, if you are interested in translating Cockpit you can do so in https://translate.fedoraproject.org/projects/cockpit/master/

**Comment by martinpitt** [comment]
@marusak : We've had several spam PRs with bogus changes recently. That account is very new, and the only other "contribution" was https://github.com/fedora-infra/asknot-ng/pull/138 with a similarly bogus change. My hunch is that this is some kind of "collecting fake credits" for $whatever purpose..

**Comment by simmon-nplob** [comment]
I have translated cockpit, and I want to do an optimized translation. Since there was no previous translation, I want to correct it. 
It won't be big for that project, but it makes sense for me. Thanks you co-operation..by simmon

**Comment by simmon-nplob** [comment]
fedora-infra/asknot-ng#138.... No! The web part needs to be applied, and the translation part needs to be applied. That part is not spam. This is the part I requested so that the web applied in the middle of the translation will be operated and the part will be applied. If the service is serviced while the translation has not been completed, it will be in a strange state.

**Comment by marusak** [comment]
> I have translated cockpit

Right, I [see](https://translate.fedoraproject.org/user/simmon/#changes) that you are active translator, thanks for that!

> I want to do an optimized translation. Since there was no previous translation, I want to correct it.

What does optimized mean in this case? And how does removing mention of previous translators fixes anything?

**Pull request closed without merging**
