### PR TITLE
Fix terminal csp warning

### PR DESCRIPTION
**Pull request by larskarlitski**
This should be reviewed together with https://github.com/cockpit-project/term.js/pull/1 and landed after term.js-cockpit 0.0.8 is released.

### CODE REVIEW

**Comment by larskarlitski** [comment]
Note: the tests are all failing because term.js-cockpit 0.0.8 doesn't exist on npm yet.

**Comment by stefwalter** [comment]
Retriggered the tests.

**Comment by martinpitt** [comment]
I don't see any CSP warning in the browser console, neither with "Terminal" nor docker terminals, with current master in Firefox. Where should I look?

That said, I tested that both terminals behave the same in master and with this PR, so this seems good.

**Comment by larskarlitski** [comment]
> I don't see any CSP warning in the browser console, neither with "Terminal" nor docker terminals, with current master in Firefox. Where should I look?

The warning doesn't appear in Firefox for me either. I've seen it in Chrome and Safari on macOS.

**Pull request merged**
