### PR TITLE
Remove unused variables

### PR DESCRIPTION
**Pull request by dperpeet**
In some cases these are actual errors or indicate them.

This also changes the build settings to treat unused variables as errors in the future.

To ignore a single line one can use `// jshint ignore:line`

### CODE REVIEW

**Comment by dperpeet** [comment]
I'm unsure about https://github.com/cockpit-project/cockpit/blob/master/pkg/lib/plot.js#L1100
The function `setup_plot_x` doesn't seem to be used, but is it part of the API?

**Comment by dperpeet** [comment]
In kubernetes:
- I'm not sure if [these functions](https://github.com/cockpit-project/cockpit/blob/master/pkg/kubernetes/scripts/graphs.js#L782) need to be applied, but the resulting variable isn't used
- I'm fairly certain we still need [this timer](https://github.com/cockpit-project/cockpit/blob/master/pkg/kubernetes/scripts/graphs.js#L817) Should we just ignore the error there or assign it to be part of something else? Is it ever cleared?

**Comment by dperpeet** [comment]
In [ostree](https://github.com/cockpit-project/cockpit/blob/master/pkg/ostree/client.js#L271) it looks like the variable should be used. Maybe `os_names[proxy.Name] = path;`?

**Comment by dperpeet** [comment]
In [networkmanager](https://github.com/cockpit-project/cockpit/blob/master/pkg/networkmanager/interfaces.js#L39), do we need `nm_debug`?

**Comment by dperpeet** [comment]
@petervo I believe you had a better solution for [this in shell](https://github.com/cockpit-project/cockpit/pull/5603/files#diff-69f6788a3c219d30591a2d89413a585bL537)

**Comment by dperpeet** [comment]
I split them apart in case we have to patch anything or want to cherry-pick individual commits.

**Comment by petervo** [comment]
Fixed up the ones i know about here.

https://github.com/petervo/cockpit/commit/95b675b5bd56982830e9b2a5f75791d7a2d7fd94

For networkmanager and plot I think you should just mark them and keep them to be safe

**Comment by dperpeet** [comment]
> Fixed up the ones i know about here.
> 
> petervo@95b675b

thanks, included the changes



> For networkmanager and plot I think you should just mark them and keep them to be safe

done

**Pull request closed without merging**
