### PR TITLE
networkmanager: Reset static addresses when switching to DHCP

### PR DESCRIPTION
**Pull request by mvollmer**
This is what people expect.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1401426

### CODE REVIEW

**Comment by dperpeet** [comment]
I'm not entirely sure about this. The [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1401426) contains both opinions also.

Resetting the list of addresses means they have to be entered again - from memory? Or from another source? If we leave them, they can be easily deleted by clicking on a button per address, which is much easier. Cockpit doesn't hide the fact that there are static addresses in addition to the automatically assigned one.

Before we change this behavior, we should probably consider the user stories and see whether we might just have to clarify the way cockpit presents these cases. @garrett

**Comment by dperpeet** [comment]
I'm setting this to blocked until the discussion is resolved

**Comment by andreasn** [comment]
Sorry for adding more complexities to this. It seems that selecting some of the items in the dropdown will clear the IP address, while other won't.
This is what I did:
* I changed from DHCP to Manual. Entered the IP address.
* Changed back to DHCP. Address remains.
* Changed to Link Local. Address is gone. Even if I switch back to Manual or DHCP.

**Comment by andreasn** [comment]
The UI suggests I get the Address automatically if I select DHCP, but I still set a manual address? What address do I get? The automatic or the custom one? Do I get both?

I think selecting DHCP clearing the manual address sounds like a good behaviour.

**Comment by andreasn** [comment]
Because the Manual address fields belong to the Manual parent dropdown.
The children of DHCP is a separate thing.

**Comment by martinpitt** [comment]
@mvollmer: Is this still relevant? By now this sounds like it could be established behaviour which is hard to change?

**Comment by mvollmer** [comment]
I can't really answer this, I am afraid.  But absent stronger evidence that the current UI behavior is unexpected and confusing, I would not make any changes.

@andreasn, can we get usability testing for this?  Scenario would be something like this:

- Configure a static IP address for a network interface
- Now change the same interface to use DHCP

If they remove the manual IP address by themselves: Did you expect that you have to do this extra step?  Would you want Cockpit to do this step automatically for you?

If they don't remove the manual IP address: Are you aware that the interface now has _both_ DHCP and a manual address?  Is that what you want?  How can Cockpit help you?

**Comment by mvollmer** [comment]
I can't really answer this, I am afraid.  But absent stronger evidence that the current UI behavior is unexpected and confusing, I would not make any changes.

@andreasn, can we get usability testing for this?  Scenario would be something like this:

- Configure a static IP address for a network interface
- Now change the same interface to use DHCP

If they remove the manual IP address by themselves: Did you expect that you have to do this extra step?  Would you want Cockpit to do this step automatically for you?

If they don't remove the manual IP address: Are you aware that the interface now has _both_ DHCP and a manual address?  Is that what you want?  How can Cockpit help you?

**Comment by andreasn** [comment]
@mvollmer sure, I've added it to this page:
https://github.com/cockpit-project/cockpit/wiki/Usability-Testing

**Comment by marusak** [comment]
Needs to rebase to master since #12367 changed tests names

**Comment by martinpitt** [comment]
Closing for now, this is way too stale, and until someone complains let's not change this.

**Pull request closed without merging**
