### PR TITLE
bots: Move to openshift 3.7

### PR DESCRIPTION
**Pull request by petervo**

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-cwcg1.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8202-20171204-160202/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-g3w8b.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8202-20171204-161616/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8202-20171204-161616/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-lc9t6.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8202-20171204-165858/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-b1685.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8202-20171204-165959/

**Comment by thomasmckay** [comment]
Ran locally and successfully built image.

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8202-20171204-165959/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-zkvtg.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8202-20171204-175757/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8202-20171204-175757/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-9bn90.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8202-20171204-212222/

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-20171204-215959

**Comment by petervo** [comment]
On fedora-27 openshift needed more memory

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-g3w8b.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8202-20171205-004545/

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-20171205-012929

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-6zw6c.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8202-20171206-032929/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-hqs99.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8202-20171206-035151/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8202-20171206-035151/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-m0hq6.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8202-20171206-044646/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8202-20171206-044646/

**Comment by petervo** [comment]
Tried to bump to fedora 27 as well but something is different with the networking on f26 and f27 that makes our way of accessing the nodeport durning the container tests not work. Needs more investigation but since people are blocking on having a 3.7 image i figured it would be better to get this in now.

**Pull request merged**
