### PR TITLE
Migrate graphs away from cockpitd

### PR DESCRIPTION
**Pull request by stefwalter**
This implements internal metric channels, and moves graphs to the new code.

### CODE REVIEW

**Comment by stefwalter** [comment]
Ready for review. This pull request limits the scope, so we can make progress. Follow ups:

 * Migrate remainder of graphs
 * Come up with a sane model for loading graph data, rather than plots.js
 * Remove the resource monitors from cockpitd
 * Cache data we have loaded to the browser in sessionStorage, so graphs show data when you switch to them.

**Comment by mvollmer** [comment]
Instance filtering in CockpitInternalMetrics is missing.

We probably don't need it immediately, but any attempt to pass "instances" or "omit-instances" options could be an error.

**Comment by mvollmer** [comment]
The `archive_channel` in plot.js is now using internal metric names with a "pcp-archive" source.  That will never work.

Also, if you have PCP archives, to ugly zoom buttons will appear, but they wont give you access to your archives, of course.

**Comment by mvollmer** [comment]
This disables PCP, rather than merely making it optional.  For example, #1816 will become pointless (and untestable) when this is merged.

If we make PCP optional as a followup, then we also need #1834 so that the server and dashboard plots have similar behavior again.

**Comment by stefwalter** [comment]
> This disables PCP, rather than merely making it optional. For example, #1816 will become pointless (and untestable) when this is merged.

I'll do the work to resolve this. I think the regression isn't good. But I don't think we need to invest too much further work on PCP until after the Fedora 22 release.

**Comment by stefwalter** [comment]
PCP is now the default, fallback to internal metrics when it is not available.

**Pull request closed without merging**
