### PR TITLE
shell: Display a message when there are no disks

### LINKED ISSUE #1758: LVM - no other disks to join
Running on a VM with only one disk in it.
Under Physical volumes I pressed Add.
Got presented with an empty dialog. Either the Add button needs to be disabled or there should be some kind of helper message in the dialog.

### PR DESCRIPTION
**Pull request by petervo**
Fixes #1758

### CODE REVIEW

**Comment by andreasn** [comment]
Looks good!

**Comment by dperpeet** [comment]
If I open the dialog, dismiss the warning and open it again, the warning is missing.

You could use the inherent dismissable-functionality from http://getbootstrap.com/components/#alerts-dismissible and generate the warning.

@andreasn Does the warning have to be dismissable here? I think it would make more sense if it weren't. If you dismiss it and the dialog is empty, it looks a bit strange.

**Comment by petervo** [comment]
I did it that way to match the other one in storage, creating volume groups.

@andreasn, let me know if you want me to change both?

**Comment by petervo** [comment]
the show/hide issue is fixed i think the dissmissable thing is a different ticket.

**Comment by dperpeet** [comment]
ok, this works for me now (even with adding/removing disks)

**Pull request closed without merging**
