### PR TITLE
storage: Check if the python process has terminated before reading da…

### PR DESCRIPTION
**Pull request by KKoukiou**
…ta from udevadm

### CODE REVIEW

**Comment by martinpitt** [comment]
What's the effect of this? Is this related to issue #13348? At first sight it's not, but as that issue and this PR happened around the same time, I may miss something?

**Comment by KKoukiou** [comment]
> What's the effect of this? Is this related to issue #13348? At first sight it's not, but as that issue and this PR happened around the same time, I may miss something?

It's not related to that issue no, but I saw this exactly because of that issue. (I didn't figure out the root cause of that issue though, and also it's an issue on another package, docker vs storage.

**Comment by KKoukiou** [comment]
> udevadm is not supposed to exit while this script runs. If it does anyway, this script crashes visibly. If we now catch premature exits of udevadm, we swallow the failure.

So shall I leave it as it wall or raise an Exception if we exit the loop? In this case I don't see any advantage of this PR, thus I will be happy to close it actually.

**Comment by mvollmer** [comment]
> In this case I don't see any advantage of this PR, thus I will be happy to close it actually.

Yeah, let's close this.  Thanks anyway, of course!

**Pull request closed without merging**
