### PR TITLE
Cleanup tests-scan

### PR DESCRIPTION
**Pull request by marusak**

### CODE REVIEW

**Comment by Gundersanne** [comment]
Can we have a test run on this before merging? Its tests-invoke so we can actually test this one :D

**Comment by marusak** [comment]
I pushed one more commit. The problem is that `test-scan` still adds one more argument to `tests-invoke` which causes error while parsing arguments. If it works with this commit then safe to land (after this dummy commit is removed).

**Comment by martinpitt** [comment]
I checked our bots if they crash on this:

```
INFO:root:Consuming message with command: PRIORITY=0005 bots/make-checkout --verbose --base=master --repo=weldr/lorax --bots-ref=pull/12555/head '' && TEST_PROJECT=weldr/lorax TEST_NAME=pull-12555-20190812-155050 TEST_REVISION=77d2cc bots/tests-invoke --pull-number=12555  --rebase=master --remote=test fedora-30/vmware ''
[...]
usage: tests-invoke [-h] [--rebase REBASE] [--remote REMOTE] [-o]
Aug 12 15:53:11 cockpit-7 docker[136020]: [--publish PUBLISH] [-v] [--pull-number PULL_NUMBER]
Aug 12 15:53:11 cockpit-7 docker[136020]: [--html-logs]
Aug 12 15:53:11 cockpit-7 docker[136020]: context
Aug 12 15:53:11 cockpit-7 docker[136020]: tests-invoke: error: unrecognized arguments:

```
Note the two empty arguments there, not sure what they are.

**Comment by martinpitt** [comment]
@marusak : Aha, we overlapped :) yes, this is indeed the problem, and tests are running now.

**Comment by marusak** [comment]
Dropped the last commit. Ready for review

**Pull request merged**
