### PR TITLE
bots: Drop rhel-7-6 image, switch rhel-7-7 to stable

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh rhel-7-7

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-05.
Log: https://209.132.184.41:8493/logs/image-refresh-12506-20190806-194848/

**Comment by cockpituous** [comment]
image-refresh rhel-7-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-7-20190806-202020

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-9.
Log: https://209.132.184.41:8493/logs/image-refresh-12506-20190806-204848/

**Comment by martinpitt** [comment]
I changed my mind. Let's not use the CDN, it will just make life harder for current non-cockpit projects that use our rhel-7-7 image.

**Comment by cockpituous** [comment]
image-refresh rhel-7-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-7-20190806-211515

**Pull request merged**
