### PR TITLE
Namespace the higlight-ct CSS class

### PR DESCRIPTION
**Pull request by stefwalter**

### CODE REVIEW

**Comment by dperpeet** [comment]
Not sure about less in the kubernetes package: does https://github.com/cockpit-project/cockpit/blob/876a45079847a7c02f5be4d163a9be361c99f4e3/pkg/kubernetes/styles/app.less#L37 need to be changed?

**Comment by dperpeet** [comment]
and (this)[https://github.com/cockpit-project/cockpit/blob/876a45079847a7c02f5be4d163a9be361c99f4e3/pkg/kubernetes/scripts/graphs.js#L782] is just the internal notification called `highlight`, correct?

**Comment by stefwalter** [comment]
> and (this)[https://github.com/cockpit-project/cockpit/blob/876a45079847a7c02f5be4d163a9be361c99f4e3/pkg/kubernetes/scripts/graphs.js#L782] is just the internal notification called highlight, correct?

This is a separate highlight class in the SVG stuff.

**Comment by dperpeet** [comment]
tuned failure is fixed in #4382

**Pull request closed without merging**
