### PR TITLE
Image refresh for fedora-29

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-29
 * [x] image-refresh fedora-29

### CODE REVIEW

**Comment by marusak** [comment]
[check-realms failed](https://209.132.184.41:8493/logs/pull-11573-20190411-100606-ec162728-verify-fedora-29/log.html) but that is rather flaky tests. But let's retry that.
And since this is for podman, do we expect that `cockpit/fedora-29@cockpit-project/cockpit-podman` is gonna pass? ([failed now](https://209.132.184.41:8493/logs/pull-11573-20190411-100606-ec162728-cockpit-project-cockpit-podman-cockpit-fedora-29/log))

**Comment by martinpitt** [comment]
[testDownloadImage](https://209.132.184.41:8493/logs/pull-11573-20190411-134242-ec162728-cockpit-project-cockpit-podman-cockpit-fedora-29/log) keeps causing a podman crash, so this is a regression in the new  version. The [bodhi update](https://bodhi.fedoraproject.org/updates/FEDORA-2019-8875ae3cff) already complained about two crash regressions, but they sound unrelated -- so we found a third.

**Comment by KKoukiou** [comment]
> [testDownloadImage](https://209.132.184.41:8493/logs/pull-11573-20190411-134242-ec162728-cockpit-project-cockpit-podman-cockpit-fedora-29/log) keeps causing a podman crash, so this is a regression in the new version. The [bodhi update](https://bodhi.fedoraproject.org/updates/FEDORA-2019-8875ae3cff) already complained about two crash regressions, but they sound unrelated -- so we found a third.

@martinpitt @marusak  I am aware of that podman regression, I already reported an issue a week ago.
Podman crashes when trying to pull image with tag that does not exist:

Here is the issue, https://github.com/containers/libpod/issues/2860 already closed but I guess fix not included in current release. 
I have commented out the test in my open PR for events.


And to confirm that this is the issue, here is the test journal
```
Apr 11 09:55:43 localhost.localdomain systemd[1]: io.podman.service: Failed with result 'signal'.
Apr 11 09:55:43 localhost.localdomain systemd[1]: io.podman.service: Consumed 756ms CPU time
Apr 11 09:55:43 localhost.localdomain systemd-coredump[7218]: Process 7151 (podman) of user 0 dumped core.
                                                              
                                                              Stack trace of thread 7199:
                                                              #0  0x000055aa47a106b4 n/a (podman)
                                                              #1  0x000055aa479f6d58 n/a (podman)
                                                              #2  0x000055aa479f5fe8 n/a (podman)
                                                              #3  0x000055aa47a109a3 n/a (podman)
                                                              #4  0x00007fd7e66d6070 __restore_rt (libpthread.so.0)
                                                              #5  0x000055aa47a106b4 n/a (podman)
                                                              #6  0x000055aa479f696a n/a (podman)
                                                              #7  0x000055aa479e0ad9 n/a (podman)
                                                              #8  0x000055aa479e048f n/a (podman)
                                                              #9  0x000055aa479df490 n/a (podman)
                                                              #10 0x000055aa479f65e6 n/a (podman)
                                                              #11 0x000055aa4888af17 n/a (podman)
                                                              #12 0x000055aa47a0ed81 n/a (podman)
Apr 11 09:55:43 localhost.localdomain kernel: audit: type=1131 audit(1554990943.860:335): pid=1 uid=
```

**Comment by marusak** [comment]
Can we have naughty for external projects? It should not be a problem, right?

**Comment by KKoukiou** [comment]
> Can we have naughty for external projects? It should not be a problem, right?

Sure, just I waited for the image to be updated to add the naughty. Otherwise it does not make sense :)

**Comment by martinpitt** [comment]
Yes, naughty overrides apply to all tested projects

**Comment by KKoukiou** [comment]
I can't push changes in the PR, closing an reopening another.

**Pull request closed without merging**
