### PR TITLE
storaged: Don't allow removing of last MDRAID disk

### LINKED ISSUE #1054: Don't allow removing the last disk of a RAID device
We should not remove the last disk of a RAID device, otherwise it will cause an error, which leaves an empty RAID device without any disk, and we cannot delete the RAID device. The device is also showed up in the Disks utitlity provided by Fedora, also cannot be deleted. Rebooting seems like the only way to get rid of thie "Zombie" device.
screenshot from 2014-08-20 10 15 52

When I try to delete it, it says:
screenshot from 2014-08-20 15 02 03

### PR DESCRIPTION
**Pull request by mvollmer**
Fixes #1054

### CODE REVIEW

**Comment by dperpeet** [comment]
Can we add a check to verify this in the integration test?

**Comment by mvollmer** [comment]
> Can we add a check to verify this in the integration test?

Yes, done.

**Comment by dperpeet** [comment]
> Yes, done.

I would also have been happy to see this at the end of another test, but this is good - thanks!

**Comment by dperpeet** [comment]
fedora-25 reauthorize failure (almost certainly not related to this pr):
```
# testSuper (check_reauthorize.TestReauthorize)
#
> done
> Error opening directory '/home/admin/.ssh': No such file or directory
> --: line 8: cd: /home/admin/.ssh: No such file or directory

> done
not ok 120 testSuper (check_reauthorize.TestReauthorize) duration: 23s
Traceback (most recent call last):
  File "./verify/check-reauthorize", line 82, in testSuper
    self.assertEqual(b.text(".super-channel span"), 'result: access-denied')
AssertionError: u'result: ' != 'result: access-denied'
Wrote TestReauthorize-testSuper-FAIL.png
Journal extracted to TestReauthorize-testSuper-10.111.121.249-FAIL.log

```

**Comment by martinpitt** [comment]
@mvollmer : fedora-25 failed in testRaid(), related?

**Comment by mvollmer** [comment]
> fedora-25 failed in testRaid(), related?

No, this used to happen also earlier...

**Pull request merged**
