### PR TITLE
Image refresh for rhel-atomic

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for rhel-atomic in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-atomic-2016-09-21/

### CODE REVIEW

**Comment by dperpeet** [comment]
@mvollmer I think your account may be out of disk space - creation was successful, but upload failed. Can you prune?

**Comment by mvollmer** [comment]
>  I think your account may be out of disk space - creation was successful, but upload failed. Can you prune?

Done.

**Comment by dperpeet** [comment]
bot: Image refresh for rhel-atomic

**Comment by dperpeet** [comment]
bot: Image refresh for rhel-atomic

**Comment by dperpeet** [comment]
> Done.

thanks! I'll just close this and we can wait for the next regular refresh.

**Pull request closed without merging**
