### PR TITLE
test: Don't logout in machines tests

### PR DESCRIPTION
**Pull request by marusak**
Honestly I don't see point in doing this - it can only produce unexpected messages.

@KKoukiou or @skobyda do you know why was the case?

### CODE REVIEW

**Comment by KKoukiou** [comment]
> Honestly I don't see point in doing this - it can only produce unexpected messages.
> 
> @KKoukiou or @skobyda do you know why was the case?

I think you added it in one place and then somehow it was copied over in many.

See commit 3a634b8ecc7e30224417c3a00a3fc8250d551dc7
Author: Matej Marusak <mmarusak@redhat.com>
Date:   Tue Mar 10 13:49:48 2020 +0100

    test: Make testAddDisk nondestructive

**Comment by marusak** [comment]
> I think you added it

:open_mouth: hmm, I don't recall that at all. Looking into PR that introduced I think it was some kind of collaboration with Martin. Lets see what tests think about this.

**Comment by marusak** [comment]
Oh, maybe I know why it is there - to stop any pending connections so we can remove resources. But it should then have `allow_authorize_messages` or one of those functions.

**Comment by KKoukiou** [comment]
> Oh, maybe I know why it is there - to stop any pending connections so we can remove resources. But it should then have `allow_authorize_messages` or one of those functions.

How about we do it int he TestMachines class teardown, Or add is as first cleanup function? logout, allow_browser_errors and then perform the resource cleanup.

**Comment by marusak** [comment]
Broke `TestMachines.testExternalConsole` and also a lot of coredumps on debian (unrelated).

**Review by KKoukiou — APPROVED** [review]
Let's wait for the tests to get little bit greener.

**Pull request merged**
