### PR TITLE
test: Split and fix TestServices.testBasic, fix with current ruff 0.0.274

### PR DESCRIPTION
**Pull request by martinpitt**
We've had [this one](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18656-20230419-120249-8715af15-fedora-37-pybridge/log.html#274) for ages, but it becomes more pressing now that the pybridge is in production.

### CODE REVIEW

**Comment by martinpitt** [comment]
I tried to [move the "udev reload burst" to the end](https://github.com/cockpit-project/cockpit/pull/18969/commits/5dafb4ac565bc3bfbe121aad1966ad4d00cf5cd6) (that commit is broken, but I fixed it locally), and interestingly this still happens. It makes the error easier to debug, but it's not the root cause.

TestServices.testBasic is annoying, it's way too big. I'll invest some time to split it up.

**Comment by martinpitt** [comment]
Meh, ruff doesn't allow me to [ignore future rules](https://github.com/cockpit-project/cockpit/actions/runs/5333598067/jobs/9664271535?pr=18968)

**Review by jelly — APPROVED** [review]
Quite some changes required to unflake! Splitting up the tests more seems sensible :+1:

**Comment by martinpitt** [comment]
Good enough -- I'll look at [this flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18968-20230621-203459-0814b3d3-ubuntu-stable/log.html) tomorrow, looks quite straightforward. We also need to adjust our tests to dnf5 for [rawhide](https://artifacts.dev.testing-farm.io/958c5148-f22a-4a23-aa91-5e37a8f26188/)

**Pull request merged**
