### PR TITLE
test: Suppress "Refused to apply inline style" logs

### PR DESCRIPTION
**Pull request by martinpitt**
PatternFly's usage of Emotion causes tons of "Refused to apply inline
style" errors, which are unfortunately hard to work around. So at least
filter them out, which will bring our test logs back from ~ 8 to ~ 1 MB
and helps developers to not get drowned in log spam.

With unminified webpacks (`--enable-debug`, what we run in CI on
fedora-30) we can reliably identify that particular bug. Without a stack
trace, just show the message once per test. We don't want to ignore it
entirely as that would hide inline styles that we accidentally bring in
from somewhere else.

### CODE REVIEW

**Comment by martinpitt** [comment]
Now there's no log spam at all in debug builds, and non-debug builds look quite a bit more reasonable:

```
❱❱❱ TEST_OS=fedora-31 test/verify/check-storage-ignored 
1..1
# ----------------------------------------------------------------------
# testIgnored (__main__.TestStorage)
#

DevTools listening on ws://127.0.0.1:10049/devtools/browser/f3aedc3c-f0a4-4cb6-929d-0d1768f19250
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1581073184457.802,"url":"http://127.0.0.2:9091/cockpit/$7e77233a6d8fca73d7c913a3477e61da9c51376359c9042385becef5500d330e/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error
ok 1 testIgnored (__main__.TestStorage) # duration: 34s

# TESTS PASSED [35s on toolbox]
```

(This is ignoring the ~ 60 "No protocol specified" lines that chromium spits out for me, but they don't seem to affect CI)

**Comment by martinpitt** [comment]
[non-debug log](https://209.132.184.41:8493/logs/pull-13508-20200207-110404-db3d81ca-rhel-8-2-distropkg/log) is now much smaller and has the expected "one message per test", with `"stackTrace":"(minified)"`.

The [fedora-30 log](https://209.132.184.41:8493/logs/pull-13508-20200207-110404-db3d81ca-fedora-30/log) (debug-enabled) has none of the inline style warnings any more.

**Comment by marusak** [comment]
Very nice, thanks! Do you plan to do it also in firefox-cdp-driver?

**Comment by martinpitt** [comment]
> Do you plan to do it also in firefox-cdp-driver?

Ah, can do that next. I'd like to do that as a follow-up to get this in ASAP (unless you find a bug here)

**Comment by martinpitt** [comment]
@marusak: Slightly different messages though, and I want to test debug and non-debug builds locally. I'll prepare the follow-up now.

**Pull request merged**
