### PR TITLE
test: Work around selenium Edge driver bug (change service version)

### PR DESCRIPTION
**Pull request by martinpitt**
Commit 9113eb5f60 triggered the old Edge selenium driver bug again where
elements that are scrolled off-page too far are not "visible" to
Selenium any more. Instead, look at units which starts much earlier in
the alphabet -- cockpit.socket, basic.target, and abrtd are on the top
of the page.

### CODE REVIEW

**Comment by martinpitt** [comment]
Alternate version for #15286 in case that one doesn't play out.

**Comment by martinpitt** [comment]
Based on [screenshot](https://logs.cockpit-project.org/logs/pull-15285-20210205-075720-008bd2c4-fedora-32-selenium- edge/screenshot-test30ChangeTabServices-525778712.png) from [failed test](https://logs.cockpit-project.org/logs/pull-15285-20210205-075720-008bd2c4-fedora-32-selenium-edge/log.html#3)

**Comment by martinpitt** [comment]
It [got a little further](https://logs.cockpit-project.org/logs/pull-15287-20210205-092424-5e4dab5f-fedora-32-selenium-edge/log.html)

**Comment by martinpitt** [comment]
This works, and my attempt in #15286 failed. Go and pick your poison :grin:

**Review by marusak — APPROVED** [review]
> This works, and my attempt in #15286 failed.

There is still chance to make #15286 work as it was just thinko. But This one is completely fine for me as well.

**Pull request merged**
