### PR TITLE
[no-test] bots: Update CentOS Atomic cloud image download

### LINKED ISSUE #9971: Image refresh for continuous-atomic
Image refresh for continuous-atomic
 * [ ] FAIL: image-refresh continuous-atomic

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
The file name dropped the "-7". Also move to https:// URL.

Fixes #9971
Closes #11765

 * [x] image-refresh continuous-atomic

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-h2590.
Log: https://209.132.184.41:8493/logs/image-refresh-11765-20190507-074646/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-sbkzh.
Log: https://209.132.184.41:8493/logs/image-refresh-11765-20190507-074444/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-jhhqm.
Log: https://209.132.184.41:8493/logs/image-refresh-11765-20190507-093939/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-11765-20190507-074646/

**Comment by cockpituous** [comment]
image-refresh continuous-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-continuous-atomic-20190507-094949

**Comment by martinpitt** [comment]
One [failure](https://209.132.184.41:8493/logs/pull-11765-20190507-110707-d12ea81b-verify-continuous-atomic/log.html#219) which could be real, but retrying for comparison.

**Comment by martinpitt** [comment]
... and triggering the right test for cockpit-ostree :grin:

**Comment by martinpitt** [comment]
The `testTroubleshooting` failure looks real :-(

**Comment by martinpitt** [comment]
Ah, since we haven't had continuous-atomic tests for so long, the entry is just missing in the "OSes with a too old libssh" special-case array.

**Comment by martinpitt** [comment]
[another failure](https://209.132.184.41:8493/logs/pull-11765-20190507-153939-880b9396-verify-continuous-atomic/log.html#184), needs to copy a naughty from rhel-atomic

**Pull request merged**
