### PR TITLE
storage: Fix scrollbar issue; change pre display

### PR DESCRIPTION
**Pull request by garrett**
Fixes the scrollbar issue introduced in https://github.com/cockpit-project/cockpit/pull/15844

### CODE REVIEW

**Comment by garrett** [comment]
luks-verify-key-modal

**Comment by garrett** [comment]
Whoops. Button is clicked for some reason.

**Comment by garrett** [comment]
storage-luks-verify-key-modal

**Review by allisonkarlitskaya — APPROVED** [review]
Scroll bar is gone for me.

I don't actually understand the CSS change, but I guess you do :)

**Review by mvollmer — APPROVED** [review]

**Comment by martinpitt** [comment]
[this failure](https://logs.cockpit-project.org/logs/pull-15870-20210526-120558-c8cf7ffb-ubuntu-2004/log.html#55-2) is unrelated. I am debugging/fixing it in PR #15869, retrying.

**Pull request merged**
