### PR TITLE
Use the external kubernetes-image-widgets component

### PR DESCRIPTION
**Pull request by stefwalter**
This is a bower component shared with Openshift Web Console
- [x] Implementation
- [x] https://github.com/cockpit-project/cockpit/pull/4771
- [x] #4805 Consistent display of external `docker` commands  with Openshift Web Console 
* [x] https://github.com/openshift/registry-image-widgets/pull/2
* [x] registry-image-widgets 0.0.3
* [x] #5326 
* [x] #5418 
* [x] #5420 
* [x] #5421

### CODE REVIEW

**Comment by stefwalter** [comment]
Related to: https://github.com/openshift/origin-web-console/pull/235

**Comment by petervo** [comment]
Needs a rebase.

**Comment by stefwalter** [comment]
Need to figure out sharing of localization markings here.

**Comment by stefwalter** [comment]
This is done, but majorly b locked on merging other pull requests.

**Comment by stefwalter** [comment]
Rebased.

**Comment by stefwalter** [comment]
Rebased and removed gettextLocale usage due to changes in #5420

**Pull request closed without merging**
