### PR TITLE
bots: Move fedora-testing to Fedora 27, use unified setup script

### PR DESCRIPTION
**Pull request by martinpitt**
If we want to test the latest incoming bits, then it makes much more
sense to test the current Fedora release instead of an old one.

Adjust fedora.setup to enable the updates-testing repository if the
image name ends with "-testing".

 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-975mp.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8751-20180302-063737/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8751-20180302-063737/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-rx3wf.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8751-20180302-063838/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8751-20180302-063838/

**Comment by martinpitt** [comment]
Wrt. the [failed image build](https://fedorapeople.org/groups/cockpit/logs/image-refresh-8751-20180302-063838/log): I ran `mock --no-bootstrap-chroot --verbose --installdeps /root/cockpit-162.x-1.wip.fc27.src.rpm` locally in a rebuilt fedora-testing image, and it worked fine.

Curiously the local image build failed for me too, but a little bit later and for a different reason:
```
DEBUG: Child return code was: 0
Finish: dnf install
DEBUG: touching file: /var/lib/mock/fedora-27-x86_64/root/etc/os-release
DEBUG: child environment: None
DEBUG: Executing command: ['/usr/bin/systemd-nspawn', '-q', '-M', '3f602f1583624b15b64910c6cbd687ec', '-D', '/var/lib/mock/fedora-27-x86_64/root', '-a', '--setenv=TERM=vt100', '--setenv=SHELL=/bin/bash', '--setenv=HOME=/builddir', '--setenv=HOSTNAME=mock', '--setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin', '--setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007"', '--setenv=PS1=<mock-chroot> \\s-\\v\\$ ', '--setenv=LANG=de_DE.UTF-8', '/usr/sbin/userdel', '-r', '-f', 'mockbuild'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'de_DE.UTF-8'} and shell False
DEBUG: BUILDSTDERR: DEBUG: Unsharing. Flags: 134217728
DEBUG: BUILDSTDERR: userdel: Benutzer \ufffd\ufffdmockbuild\ufffd\ufffd ist nicht vorhanden.
DEBUG: Child return code was: 6
DEBUG: child environment: None
DEBUG: Executing command: ['/usr/bin/systemd-nspawn', '-q', '-M', 'cb0f04ce8d044b71aab210b2d861783c', '-D', '/var/lib/mock/fedora-27-x86_64/root', '-a', '--setenv=TERM=vt100', '--setenv=SHELL=/bin/bash', '--setenv=HOME=/builddir', '--setenv=HOSTNAME=mock', '--setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin', '--setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007"', '--setenv=PS1=<mock-chroot> \\s-\\v\\$ ', '--setenv=LANG=de_DE.UTF-8', '/usr/sbin/groupdel', 'mock'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'de_DE.UTF-8'} and shell False
DEBUG: BUILDSTDERR: DEBUG: Unsharing. Flags: 134217728
DEBUG: BUILDSTDERR: groupdel: Gruppe \ufffd\ufffdmock\ufffd\ufffd existiert nicht.
DEBUG: Child return code was: 6
DEBUG: child environment: None
DEBUG: Executing command: ['/usr/bin/systemd-nspawn', '-q', '-M', '0ca79890048a4f80a9302ab6286b3471', '-D', '/var/lib/mock/fedora-27-x86_64/root', '-a', '--setenv=TERM=vt100', '--setenv=SHELL=/bin/bash', '--setenv=HOME=/builddir', '--setenv=HOSTNAME=mock', '--setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin', '--setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007"', '--setenv=PS1=<mock-chroot> \\s-\\v\\$ ', '--setenv=LANG=de_DE.UTF-8', '/usr/sbin/groupadd', '-g', '135', 'mock'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'de_DE.UTF-8'} and shell False
DEBUG: BUILDSTDERR: DEBUG: Unsharing. Flags: 134217728
DEBUG: Child return code was: 0
DEBUG: child environment: None
DEBUG: Executing command: ['/usr/bin/systemd-nspawn', '-q', '-M', 'edeb867e24ec475c94e0478a005145de', '-D', '/var/lib/mock/fedora-27-x86_64/root', '-a', '--setenv=TERM=vt100', '--setenv=SHELL=/bin/bash', '--setenv=HOME=/builddir', '--setenv=HOSTNAME=mock', '--setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin', '--setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007"', '--setenv=PS1=<mock-chroot> \\s-\\v\\$ ', '--setenv=LANG=de_DE.UTF-8', '/usr/sbin/useradd', '-o', '-m', '-u', '1001', '-g', '135', '-d', '/builddir', '-n', 'mockbuild'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'de_DE.UTF-8'} and shell False
DEBUG: BUILDSTDERR: DEBUG: Unsharing. Flags: 134217728
DEBUG: Child return code was: 0
DEBUG: ensuring that dir exists: /var/lib/mock/fedora-27-x86_64/root/builddir/build/RPMS
DEBUG: creating dir: /var/lib/mock/fedora-27-x86_64/root/builddir/build/RPMS
DEBUG: ensuring that dir exists: /var/lib/mock/fedora-27-x86_64/root/builddir/build/SPECS
DEBUG: creating dir: /var/lib/mock/fedora-27-x86_64/root/builddir/build/SPECS
DEBUG: ensuring that dir exists: /var/lib/mock/fedora-27-x86_64/root/builddir/build/SRPMS
DEBUG: creating dir: /var/lib/mock/fedora-27-x86_64/root/builddir/build/SRPMS
DEBUG: ensuring that dir exists: /var/lib/mock/fedora-27-x86_64/root/builddir/build/SOURCES
DEBUG: creating dir: /var/lib/mock/fedora-27-x86_64/root/builddir/build/SOURCES
DEBUG: ensuring that dir exists: /var/lib/mock/fedora-27-x86_64/root/builddir/build/BUILD
DEBUG: creating dir: /var/lib/mock/fedora-27-x86_64/root/builddir/build/BUILD
DEBUG: ensuring that dir exists: /var/lib/mock/fedora-27-x86_64/root/builddir/build/BUILDROOT
DEBUG: creating dir: /var/lib/mock/fedora-27-x86_64/root/builddir/build/BUILDROOT
DEBUG: ensuring that dir exists: /var/lib/mock/fedora-27-x86_64/root/builddir/build/originals
DEBUG: creating dir: /var/lib/mock/fedora-27-x86_64/root/builddir/build/originals
DEBUG: touching file: /var/lib/mock/fedora-27-x86_64/root/.initialized
DEBUG: child environment: None
DEBUG: Executing command: ['sync'] with env {'TERM': 'vt100', 'SHELL': '/bin/sh', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'LANG': 'de_DE.UTF-8'} and shell False
DEBUG: Child return code was: 0
Start: creating root cache
DEBUG: child environment: None
DEBUG: Executing command: ['tar', '--one-file-system', '--exclude-caches', '--exclude-caches-under', '--use-compress-program', 'pigz', '-cf', '/var/cache/mock/fedora-27-x86_64/root_cache/cache.tar.gz', '-C', '/var/lib/mock/fedora-27-x86_64/root', '--exclude=./proc', '--exclude=./sys', '--exclude=./dev', '--exclude=./tmp/ccache', '--exclude=./var/cache/yum', '--exclude=./var/cache/dnf', '--exclude=./proc', '--exclude=./sys', '--exclude=./dev/shm', '--exclude=./dev/pts', '--exclude=./var/cache/dnf/', '.'] with env {'TERM': 'vt100', 'SHELL': '/bin/sh', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'LANG': 'de_DE.UTF-8'} and shell False
DEBUG: Child return code was: 0
DEBUG: kill orphans
DEBUG: child environment: None
DEBUG: Executing command: ['/bin/umount', '-n', '/var/lib/mock/fedora-27-x86_64/root/var/cache/dnf/'] with env {'TERM': 'vt100', 'SHELL': '/bin/sh', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'LANG': 'de_DE.UTF-8'} and shell False
DEBUG: Child return code was: 0
ERROR: 'ascii' codec can't encode characters in position 294-295: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 959, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 759, in main
    run_command(options, args, config_opts, commands, buildroot, state)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/libexec/mock/mock", line 815, in run_command
    commands.init()
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/backend.py", line 164, in init
    self.buildroot.initialize(**kwargs)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/buildroot.py", line 92, in initialize
    self._init(prebuild=prebuild, do_log=do_log)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/buildroot.py", line 182, in _init
    self.plugins.call_hooks('postinit')
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/plugin.py", line 78, in call_hooks
    hook(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/plugins/root_cache.py", line 163, in _rootCachePostInitHook
    self._rebuild_root_cache()
  File "/usr/lib/python3.6/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/mockbuild/plugins/root_cache.py", line 200, in _rebuild_root_cache
    l.write(self.buildroot.pkg_manager.init_install_output)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 294-295: ordinal not in range(128)
```
Presumably because I'm running on `LANG=de_DE.UTF-8`. I pushed a fix.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-1hj38.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8751-20180302-080606/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-testing-20180302-085252

**Comment by martinpitt** [comment]
OK, so that was just a network flake, a rebuild worked. A local build now also works without meddling with the locale. I think the changes to fedora.setup are specific enough to not require rebuilds of fedora-{26,27,i386}, but please let me know if you disagree and you'd rather have me rebuild them.

**Comment by martinpitt** [comment]
Still the same [check-sosreport failure](https://fedorapeople.org/groups/cockpit/logs/pull-8751-20180302-085858-59035c94-verify-fedora-testing/log.html#103) as three months ago in #8325, so this isn't specific to Fedora 26 vs. 27, but rather whether or not  updates-testing is enabled. Taking a closer look.

**Comment by martinpitt** [comment]
This was a simple and obvious one for a change, fix pushed.

**Comment by martinpitt** [comment]
@larskarlitski : This is by and large ready now (just  had a flaky test on fedora-27, but this is unrelated). Can you please have a look? Thanks!

**Pull request merged**
