### PR TITLE
bots: Stop triggering fedora-27 on PRs, start triggering rhel-8

### PR DESCRIPTION
**Pull request by martinpitt**
Fedora 28 is the current release,  we are not focussing on or releasing
to 27 any more. As such the weekly refreshes are sufficient, we don't
need to trigger fedora-27 on every PR any more.

rhel-8 is a major development target right now, so trigger that on every
PR instead.

 - [x] land and rebase to #9088

### CODE REVIEW

**Comment by martinpitt** [comment]
This will almost certainly conflict with #9088, and I want to land that first, so setting blocked.

**Comment by martinpitt** [comment]
Oops, and here we have living proof that we should have done this earlier: [testNfsMissingPackages](https://fedorapeople.org/groups/cockpit/logs/pull-9232-20180525-112121-ed52e25d-verify-rhel-8/log.html#115) fails as we didn't adjust the test for rhel-8.

CC @mvollmer

**Comment by mvollmer** [comment]
> testNfsMissingPackages fails as we didn't adjust the test for rhel-8.

Seems like PackageKit is not installed.

**Comment by martinpitt** [comment]
Thanks, I pushed a skip.

**Comment by martinpitt** [comment]
@larskarlitski : This isn't green yet, but I'd appreciate a review already so that I can self-land tonight and unblock #9248.

**Pull request merged**
