### PR TITLE
bots: Move centos-7 image to virt-install-fedora

### PR DESCRIPTION
**Pull request by martinpitt**
This builds centos-7 the same way we build all RHEL images.

Let's deprecate virt-builder-fedora and eventually drop the libguestfs
dependency.

 - [x] PR #12543 
 - [x] image-refresh centos-7

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-12549-20190813-050808/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20190813-055959

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-0mtl2.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12549-20190813-060404/

**Comment by martinpitt** [comment]
Oops, editing the description unticked the image refresh. Aborting that, sorry for the noise.

**Pull request merged**
