### PR TITLE
bots: Declare rhel-7-5-distropkg test

### PR DESCRIPTION
**Pull request by martinpitt**
Prerequisite for PR #9672

### CODE REVIEW

**Comment by martinpitt** [comment]
This PR itself is trivial, but please have a look at PR #9672 about the rationale. In paricular, the bikeshedding about the name (-distropkg, -preinstall, -os-cockpit, other ideas?) should happen here.

**Comment by martinpitt** [comment]
@stefwalter , @larskarlitski : Any opinion about the name, and the general idea?

**Comment by stefwalter** [comment]
I don't understand what the intent of this change is.

 * I thought the ```rhel-7``` image is targetting delivery in the next 7.y version of RHEL
 * I thought the ```rhel-7-5``` image is targetting delivery in the next 7.5.z version of RHEL

**Comment by martinpitt** [comment]
Right, this is confusing everyone. In the future, with this we should have one rhel-7-y image with just that, and we can decide which of these we want to test in "OS cockpit" vs. "master cockpit" vs. "both" modes.

**Pull request merged**
