### PR TITLE
pkg: Fix cockpit-components-log-panel some

### PR DESCRIPTION
**Pull request by mvollmer**
When limiting the log display, we want to cut off at the end, not the
start.  Ouch.

### CODE REVIEW

**Comment by mvollmer** [comment]
No, this isn't right either... something seems still off.

**Comment by KKoukiou** [comment]
@mvollmer it correct - why you say it's not? I cherry-picked it in my PR as well - just increased the slid e to max+1 because we used to have 10 logs entries -  not 9.

**Comment by martinpitt** [comment]
So can we close this PR, as it's part of #13695 now? Or do you want to rebase that one again?

**Comment by mvollmer** [comment]
> why you say it's not?

I am still seeing duplicate entries at the top of the log.  `max+1` is a good point, though...

**Comment by mvollmer** [comment]
The keys of the react components were not unique...

**Comment by martinpitt** [comment]
@mvollmer , @KKoukiou : This broke unit tests (`make check TESTS=dist/base1/test-http.html`). Please always have a look at semaphore failures -- if all three fail, then something is wrong.

**Comment by martinpitt** [comment]
Test fixed in PR #13924

**Pull request merged**
