### PR TITLE
Waiting selenium started

### PR DESCRIPTION
**Pull request by jscotka**
added longer timeout and check exact URLs on selenium HUB page

### CODE REVIEW

**Comment by stefwalter** [comment]
Unfortunately this is still failing. See the test failure above.

http://fedorapeople.org/groups/cockpit/logs/pull-3329-f1a9ac53-rhel-7/log.html

**Comment by stefwalter** [comment]
Looks like there's a journal message we need to whitelist. See the fedora-23 test above: 

```
Unexpected journal message 'Error sending data: Connection reset by peer'
```

**Comment by jscotka** [comment]
Now it should be ready
 * warning ffrom docker supressed
 * added avocado run log to stderr to see it in log
 * make starting docker selenum images more reliable

**Comment by dperpeet** [comment]
thanks for the work, @jscotka 
I added your (squashed) commits to #3261

**Pull request closed without merging**
