### PR TITLE
bridge: Send "ready" and "done" on fsread1 channel when file doesn't exist

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by stefwalter** [comment]
This seems incorrect. Shouldn't we be sending ```{ "command": "close", "problem": "not-found" }``` instead?

**Comment by mvollmer** [comment]
> This seems incorrect. Shouldn't we be sending { "command": "close", "problem": "not-found" } instead?

No, this is how fsread1 is specified: Non-existing files are not an error, but deliver empty content and a tag of "-".

**Comment by mvollmer** [comment]
In fact, I think we also need to send "ready".

**Comment by mvollmer** [comment]
I bumped into this when testing external channels.  Using fsread1 with a non-existing file triggers "invalid state while serving external channel" messages otherwise.

**Comment by stefwalter** [comment]
The general intent of the "ready" message is that we're ready to receive data on the channel, or the channel is in a stable open state. The intent of the "done" message is that no further data will be sent. Neither of these are true for fsread1 in this case.

I thought that the fs* channels empty files are represented by with a "done" message, whereas without a "done" message there will be nothing like that.

**Comment by mvollmer** [comment]
> The general intent of the "ready" message is that we're ready to receive data on the channel, or the channel is in a stable open state. The intent of the "done" message is that no further data will be sent. Neither of these are true for fsread1 in this case.

That makes sense to me.

**Pull request closed without merging**
