### PR TITLE
Port bots to python3

### PR DESCRIPTION
**Pull request by stefwalter**
Python 3.x is an important milestone in python usage. Without
migrating to it, python use becomes rather unsustainable long term.

 * [x] cockpit-project/cockpituous#163
 * [x] #8209
 * [x] image-refresh fedora-27
 * [x] npm-update
 * [x] koji-build
 * [x] naughty-prune
 * [x] po-refresh

### CODE REVIEW

**Comment by stefwalter** [comment]
I had to create a new pull request to test this out again, since #8193 cannot be reopened.

**Comment by martinpitt** [comment]
This now causes a different kind of trouble -  pretty much *all* bots are currently testing this PR, but none report their status to GitHub and "claim" the test.

**Comment by martinpitt** [comment]
Adding WIP and blocked to lower priority to avoid starvation again.

**Comment by martinpitt** [comment]
Seems that was it, thanks @stefwalter! Indeed I faintly remember some issues with `universal_newlines` not (always?) applying to stdin. Reverting the priority lowering and retrying, seems mostly flakes now.

**Comment by martinpitt** [comment]
This fails to build on all the RHELs and CentOS, presumably because they don't have Python 3 and thus the pyflakes check fails? I suppose this needs to be blacklisted there.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-1d4qt.
Log: http://209.132.184.41/logs/image-refresh-8226-20171208-101313/

**Comment by cockpituous** [comment]
Task failed: http://209.132.184.41/logs/image-refresh-8226-20171208-101313/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-kf9mf.
Log: http://209.132.184.41/logs/image-refresh-8226-20171208-104141/

**Comment by cockpituous** [comment]
image-refresh fedora-27 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-27-20171208-111616

**Comment by cockpituous** [comment]
npm-update in progress on cockpit-tasks-cjmss.
Log: http://209.132.184.41/logs/npm-update-8226-20171208-112020/

**Comment by cockpituous** [comment]
npm-update in progress on cockpit-tasks-6pggz.
Log: http://209.132.184.41/logs/npm-update-8226-20171208-112020/

**Comment by cockpituous** [comment]
npm-update moment done: https://github.com/cockpituous/cockpit/commits/npm-update-moment-20171208-112020

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```package.json:    "moment": "2.19.3",
pkg/docker/atomic.js:var moment = require("moment");
pkg/docker/atomic.js:        finishedTime: moment(info.FinishedTime),
pkg/docker/containers-view.jsx:var moment = require('moment');
pkg/docker/containers-view.jsx:        var created = moment.unix(image.Created);
pkg/docker/containers-view.jsx:            moment.unix(image.Created).fromNow(),
pkg/kubernetes/scripts/date.js:    var moment = require('moment');
pkg/kubernetes/scripts/date.js:            return moment;
pkg/kubernetes/scripts/date.js:                return moment(timestamp).fromNow();
pkg/machines/actions.es6: * the refresh interval starts counting since that moment.
pkg/ostree/app.js:    var moment = require('moment');
pkg/ostree/app.js:                    return moment.unix(when).fromNow();
pkg/packagekit/updates.jsx:var moment = require("moment");
pkg/packagekit/updates.jsx:                    { cockpit.format(_("Last checked: $0 ago"), moment.duration(props.timeSinceRefresh * 1000).humanize()) }
pkg/packagekit/updates.jsx:            return cockpit.format(_("The following packages were updated $0:"), moment(time).fromNow());
pkg/packagekit/updates.jsx:                            { this.state.timeRemaining !== null ? <span>{moment.duration(this.state.timeRemaining * 1000).humanize()}</span> : null }
pkg/selinux/setroubleshoot-client.js:var moment = require("moment");
pkg/selinux/setroubleshoot-client.js:                    // so moment.js can parse them correctly by default
pkg/selinux/setroubleshoot-client.js:                    details.firstSeen = moment(result[5]);
pkg/selinux/setroubleshoot-client.js:                    details.lastSeen = moment(result[6]);
pkg/systemd/host.js:         * it wasn't, or we loaded a library like moment.js, there is no
pkg/systemd/init.js:    var moment = require("moment");
pkg/systemd/init.js:            unit.LastTriggerTime = moment(timer_unit.LastTriggerUSec/1000).calendar();
pkg/systemd/init.js:            unit.NextRunTime = moment(next_run_time/1000).calendar();
pkg/systemd/init.js:                clock_realtime_now = moment(time, "ddd, DD MMM YYYY HH:mm:ss ZZ"); // rfc822 date
pkg/systemd/init.js:            date: moment().format("YYYY-MM-DD")
pkg/systemd/init.js:                repeat_array[i].date = moment(repeat_array[i].date_to_parse).format('YYYY-MM-DD');
pkg/systemd/init.js:                return "OnCalendar=*-" + moment(item.date_to_parse).format('MM') + "-" + moment(item.date_to_parse).format('DD') + " " +Number(item.hours) + ":" + Number(item.minutes) + ":00";
webpack.config.js:    "moment": "moment/moment.js",
```

**Comment by cockpituous** [comment]
npm-update moment done: https://github.com/cockpituous/cockpit/commits/npm-update-moment-20171208-112121

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```package.json:    "moment": "2.19.3",
pkg/docker/atomic.js:var moment = require("moment");
pkg/docker/atomic.js:        finishedTime: moment(info.FinishedTime),
pkg/docker/containers-view.jsx:var moment = require('moment');
pkg/docker/containers-view.jsx:        var created = moment.unix(image.Created);
pkg/docker/containers-view.jsx:            moment.unix(image.Created).fromNow(),
pkg/kubernetes/scripts/date.js:    var moment = require('moment');
pkg/kubernetes/scripts/date.js:            return moment;
pkg/kubernetes/scripts/date.js:                return moment(timestamp).fromNow();
pkg/machines/actions.es6: * the refresh interval starts counting since that moment.
pkg/ostree/app.js:    var moment = require('moment');
pkg/ostree/app.js:                    return moment.unix(when).fromNow();
pkg/packagekit/updates.jsx:var moment = require("moment");
pkg/packagekit/updates.jsx:                    { cockpit.format(_("Last checked: $0 ago"), moment.duration(props.timeSinceRefresh * 1000).humanize()) }
pkg/packagekit/updates.jsx:            return cockpit.format(_("The following packages were updated $0:"), moment(time).fromNow());
pkg/packagekit/updates.jsx:                            { this.state.timeRemaining !== null ? <span>{moment.duration(this.state.timeRemaining * 1000).humanize()}</span> : null }
pkg/selinux/setroubleshoot-client.js:var moment = require("moment");
pkg/selinux/setroubleshoot-client.js:                    // so moment.js can parse them correctly by default
pkg/selinux/setroubleshoot-client.js:                    details.firstSeen = moment(result[5]);
pkg/selinux/setroubleshoot-client.js:                    details.lastSeen = moment(result[6]);
pkg/systemd/host.js:         * it wasn't, or we loaded a library like moment.js, there is no
pkg/systemd/init.js:    var moment = require("moment");
pkg/systemd/init.js:            unit.LastTriggerTime = moment(timer_unit.LastTriggerUSec/1000).calendar();
pkg/systemd/init.js:            unit.NextRunTime = moment(next_run_time/1000).calendar();
pkg/systemd/init.js:                clock_realtime_now = moment(time, "ddd, DD MMM YYYY HH:mm:ss ZZ"); // rfc822 date
pkg/systemd/init.js:            date: moment().format("YYYY-MM-DD")
pkg/systemd/init.js:                repeat_array[i].date = moment(repeat_array[i].date_to_parse).format('YYYY-MM-DD');
pkg/systemd/init.js:                return "OnCalendar=*-" + moment(item.date_to_parse).format('MM') + "-" + moment(item.date_to_parse).format('DD') + " " +Number(item.hours) + ":" + Number(item.minutes) + ":00";
webpack.config.js:    "moment": "moment/moment.js",
```

**Comment by cockpituous** [comment]
naughty-prune in progress on cockpit-tasks-tm1t7.
Log: http://209.132.184.41/logs/naughty-prune-8226-20171208-141111/

**Comment by cockpituous** [comment]
naughty-prune in progress on cockpit-tasks-jt92k.
Log: http://209.132.184.41/logs/naughty-prune-8226-20171208-141111/

**Comment by cockpituous** [comment]
po-refresh in progress on cockpit-tasks-zlc5f.
Log: http://209.132.184.41/logs/po-refresh-8226-20171208-142424/

**Comment by cockpituous** [comment]
po-refresh  done: https://github.com/cockpituous/cockpit/commits/po-refresh-20171208-142727

**Comment by stefwalter** [comment]
Fixed to skip test-bots on systems without python3

**Comment by martinpitt** [comment]
@stefwalter: The output of the triggered bots look good except for the [naughty-prune log](http://209.132.184.41/logs/naughty-prune-8226-20171208-141111/log) (`TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'`), but this doesn't appear to be specific to the Python 3 migration at first sight?

**Comment by martinpitt** [comment]
The `TypeError` got fixed by https://github.com/cockpit-project/cockpituous/pull/166

**Pull request closed without merging**
