### PR TITLE
machines: Replace PF4 Cards and other components with PF4 equivalent

### LINKED ISSUE #14686: machines: Port to card-based layout
The machines page should be card-based like the other pages.

We could have 3 cards, with the top two each having their own width, like they are now. The bottom card would be the VM list and span completely across the page.

The layout placement would be basically the same.

This can land before, after, or as a part of the VM subpage redesign @ #14346.

### PR DESCRIPTION
**Pull request by KKoukiou**
pkg/lib/cards.scss was not used anywhere apart from machines so move it
there.

Fixes #14686

### CODE REVIEW

**Comment by KKoukiou** [comment]
The UI difference it not that big:
Screen Shot 2020-10-19 at 18 37 08
Screen Shot 2020-10-19 at 18 35 52

**Review by marusak — CHANGES_REQUESTED** [review]
It needs rebase.
And should the icon be a part of the clickable part?

**Comment by KKoukiou** [comment]
> It needs rebase.
> And should the icon be a part of the clickable part?

I used Buttons showed as links from PF4 and these have an integrated icon, so from this perpective it's expected. If you think it should not, I can try to find another solution :)

**Comment by marusak** [comment]
> If you think it should not, I can try to find another solution :)

I am fine with it, was just asking :)

**Review by marusak — APPROVED** [review]
Thanks, looks good!
Retrying tests although I expect still a lot of machines failures.

**Pull request merged**
