### PR TITLE
po: Also include pkg/lib translations

### PR DESCRIPTION
**Pull request by marusak**
Package specific translation files (e.g ./usr/share/cockpit/storaged/po.zh_CN.js.gz) do not include translations for imported components from pkg/lib.

Some reproducers for example are (switch to chinese for example as this is almost 100% translated):
- Try to add-hoc install anything (cockpit-pcp, realmd...)
- Try to reboot machine
- Try to change system time
- Try to change password for user

@martinpitt or @allisonkarlitskaya I think you were making changes to translations lately. This already landed in 8.8/9.2 so this is at least a couple of months old. I consider this PR a hack and I believe there is better solution. Do you have better idea what can be broken?

### CODE REVIEW

**Comment by KKoukiou** [comment]
> Ideally we would need a list of files that the bunlders loads for each package. I don't see this being easy to fix and I think this solution is fine, even if sub-optimal.

Also we very easy test this bug. Would be great to add this as part of the existing translation tests.

**Review by martinpitt — COMMENTED** [review]
I agree, what Katerina says -- let's please cover this in check-pages.

**Comment by marusak** [comment]
Ok, if you think this fix is good enough let's go with it :) I've added a test

**Review by martinpitt — DISMISSED** [review]
Cheers!

**Review by allisonkarlitskaya — COMMENTED** [review]
Quick question/idea for alternate approach:

At this point in the compilation process, are we able to find out all of the input/dependency files?  If so, it might make sense to use that to build the list of places that we'd like to include translations from...

**Comment by martinpitt** [comment]
@allisonkarlitskaya : I'm not sure, needs some exploration of the esbuild API. As this is a clear regression, let's land this as-is for now. I created issue #18833 to track your idea. Thanks!

**Comment by martinpitt** [comment]
[This failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18824-20230523-053841-70e0bdeb-centos-8-stream/log.html#330-1) is pretty persistent. I added a fix for this. I also rebased to current main to fix the packit tests.

**Review by martinpitt — APPROVED** [review]

**Comment by martinpitt** [comment]
[This TestService](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18824-20230523-062934-913e9904-centos-8-stream/log.html#281) failure also happens a lot. I can even reproduce this locally at the first shot. At least in RHEL 8 it seems to take very long for the initial memory to appear, apparently it isn't sampled very often.

The unexpected python message in [TestUpdates.testTracer](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18824-20230523-072539-913e9904-fedora-38-pybridge/log.html#111) is also becoming too annoying, added a fix as well.

The [c8s/pybridge failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18824-20230523-062934-913e9904-centos-8-stream-pybridge/log.html) are both "hard" (I already spent a few hours on them), not addressing them here.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
