### PR TITLE
Accounts: show sane error message if account can't be found

### PR DESCRIPTION
**Pull request by dperpeet**
@andreasn What would be a proper message here?

screenshot from 2015-03-20 12 23 17

### CODE REVIEW

**Comment by andreasn** [comment]
For the root account, the only setting that would apply would be "Set password", so we should have a button in there for that (and that would fix the other bug you mentioned on IRC).

Are there any other cases where this would happen? Domain users? Something else?

**Comment by dperpeet** [comment]
This pull does not affect the account settings for root. Scope: handle if the account id passed to the page can't be handled via our accounts-code and show a graceful error message instead of getting an unexpected error.

You can get this if you log in as root, go to account settings (in the top-right menu) and change the id to a user that doesn't exist.

Old:
user_old
New:
user_new

**Comment by stefwalter** [comment]
There's some work here on error messages. I wonder if we would use something similar for 404 (which is pretty much what this is): #2083

**Comment by stefwalter** [comment]
@andreasn What do you think?

**Comment by andreasn** [comment]
Yeah, makes sense.

**Comment by andreasn** [comment]
Depends on newer patternfly version

**Comment by stefwalter** [comment]
Replaced by #2675

**Pull request closed without merging**
