### PR TITLE
shell: Set server time implementation - revisited

### PR DESCRIPTION
**Pull request by fridex**
Based on previous #1840 pull request:
 * removed cockpitd needless code.
 * adjusted make update-jquery target in pkg/base/Makefile.am
 * documented moment.js in the commit message

Implemented setting time using systemd-timedated - a user can enable NTP synchronization or adjust time manually.

### CODE REVIEW

**Comment by stefwalter** [comment]
@fridex Thanks!

By the way, in the future, feel free to ```git push --force systime``` to update this pull request, rather than open another one.

I'm worried about the moment.js dependency. It's global code, large, and adds global functions. I took a look, and I can't see a moment.js dependency here:

https://github.com/eternicode/bootstrap-datepicker

or here:

http://bootstrap-datepicker.readthedocs.org/en/release/

Which version of bootstrap-datepicker did you use? Where did you get it from?

CC: @rhamilto

**Comment by fridex** [comment]
@stefwalter Thank you for pull request advice. This patch does not use bootstrap-datepicker, but bootstrap-date**time**picker:

https://github.com/Eonasdan/bootstrap-datetimepicker

You can see requirements with *moment.js* on this page:

https://github.com/Eonasdan/bootstrap-datetimepicker/wiki/Installation

**Comment by stefwalter** [comment]
Aha. So @rhamilto note the above ... bootstrap-datetimepicker has lots more dependencies than bootstrap-datepicker, in case you're looking at either for inclusion in Patternfly. But obviously bootstrap-datetimepicker can do time selection as well.

The issue i'm trying to figure out, is that this pretty much requires that we include moment.js in Cockpit, as a global library, than anyone can use. I haven't figured out a way to make moment.js available to just bootstrap-datetimepicker.

**Comment by stefwalter** [comment]
It seems like moment.js fills in for the new APIs that have not landed in all browsers yet, such as ```Intl.DateTimeFormat``` and ```date.toLocaleDateString(with options) ```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

**Comment by stefwalter** [comment]
Good news. Both moment.js and bootstrap-datetimepicker are loadable via AMD. This makes it easier to have them as dependencies.

**Comment by stefwalter** [comment]
Because we're updating patternfly we changed the location of glyph fonts. I've added glyphicons in #1855.

**Comment by stefwalter** [comment]
I've added bootstrap-datetimepicker in #1864, so we need to get that merged first. I'd like to add it to the shell package first, until patternfly adds it, and then perhaps we can make it more public API in the base package.

The ```GetServerTime``` API has been removed from ```cockpitd``` in commit e79850eaeefc2f700676d36cc5942f3b261559d8. We're trying to move away from ```cockpitd``` completely. But such an API is useful, and general purpose, and I've added a similar API to the ```cockpit-bridge``` internal DBus bus. This is in pull request #1864. The pull request contains instructions on how to make that call.

Once the above are merged, please rebase on top of them.

In addition the following things should to be fixed before merging:

 * When I bring up the 'Change System Time' the first time, the time field defaults to the current system time. However if I then change time field, Cancel the dialog, and bring it up again, the current system time is not displayed in the field.
 * The included timezone on the button is not the server TimeZone, but the browser timezone. Suggest displaying the time in the server TimeZone.
 * Suggest not including the seconds in the display, that's distracting. You can use moment.js to format the time without the seconds.

**Comment by mvollmer** [comment]
Both #1863 and #1864 have been merged.

**Comment by stefwalter** [comment]
I've rebased and migrated to the GetWallTime() API in the branch here: https://github.com/stefwalter/cockpit/tree/systime_v2

**Comment by andreasn** [comment]
These labels should be left aligned

screenshot from 2015-03-03 10 38 13

**Comment by andreasn** [comment]
This string is really long and a bit of information overload. The seconds are a bit too detailed information.

screenshot from 2015-03-03 10 40 06

The mockups had Month, Number, hour:minute, like "January 12 10:15"
I think all other info is overload, but I'm happy to discuss where to draw the line.

**Comment by andreasn** [comment]
Is it possible to use only the date part from datepicker?
It would be common to change from summer time to winter time twice a year (for admins located in countries that implements that), but changing dates wouldn't happen unless something went wrong. Therefore it would be great to have the time part of it more visible and not hidden way down in a submenus submenu.

**Comment by andreasn** [comment]
screenshot from 2015-03-03 11 01 31

Is the editable parts actually editable? I tried to put April 45 (yes, 45 :). It would work better if it was all a button instead of the little clock button in the corner.

**Comment by andreasn** [comment]
Updated mockup

Mockup

**Comment by stefwalter** [comment]
So @andreasn are you suggesting we don't use a time picker at all, but simply type in the fields? In that case I would use bootstrap-datepicker instead of bootstrap-date*time*picker.

CC @rhamilto

**Comment by andreasn** [comment]
@stefwalter I didn't realize before that bootstrap-datepicker and bootstrap-datetimepicker was different things.
Yes, I would advice using bootstrap-datepicker in that case.
The input controls would need some kind of validation checks for valid times as well of course

**Comment by fridex** [comment]
In the original mockup, there was a possibility to set time using NTP by entering URL of an NTP server. It could be easily implemented using ntpdate. Nevertheless, it would add additional dependency on ntpdate utility. I can imagine an option there to let user enter custom NTP server when updating time.

https://raw.githubusercontent.com/cockpit-project/cockpit-design/08fe40537052e6cc33051c986c635ce0fdc3beaf/timendate/timendate.png

I don't see current server timezone in the current mockup. This information could be useful in some situations in my opinion (especially when server time will be displayed in server's timezone). On mouse over could be helpful there. What are your opinions?

**Comment by stefwalter** [comment]
> In the original mockup, there was a possibility to set time using NTP by entering URL of an NTP server. It could be easily implemented using ntpdate. Nevertheless, it would add additional dependency on ntpdate utility. I can imagine an option there to let user enter custom NTP server when updating.

I would suggest that if we're going to have such a feature feature, (setting specific NTP servers) it first be submitted for inclusion in timedated, and then we can call it there.

http://www.freedesktop.org/wiki/Software/systemd/timedated/

**Comment by andreasn** [comment]
> In the original mockup, there was a possibility to set time using NTP by entering URL of an NTP server.

Oh crap, that was what it was of course. I was like "huh? did I do that wrong? did I forget that control in there?" Yes, the field would make sense. Will update.

**Comment by andreasn** [comment]
> it first be submitted for inclusion in timedated, and then we can call it there.

Ah, it wasn't in there? Ok, lets just disable the field for now then

**Comment by andreasn** [comment]
Stef asked me on IRC to write down my thoughts on the different date pickers.
For this server time, [the redesigned journal](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/journal/journal-v3.png) and [systemd timers](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/services/timers.png) I think we would be better served by bootstrap-datepicker than [bootstrap 3 datetimepicker 3] (http://eonasdan.github.io/bootstrap-datetimepicker/) or [DateTime Picker](http://www.malot.fr/bootstrap-datetimepicker/demo.php).
The time selection in both those are so deep down and fiddly to navigate, that we're better served by boostrap-datepicker and setting time in a separate control.

**Comment by fridex** [comment]
> The GetServerTime API has been removed from cockpitd in commit e79850e. We're trying to move
> away from cockpitd completely. But such an API is useful, and general purpose, and I've added a
> similar API to the cockpit-bridge internal DBus bus. This is in pull request #1863. The pull request
> contains instructions on how to make that call.

What about using output of date from coreutils? Output can be formatted and there can be passed info about timezone.

**Comment by rhamilto** [comment]
Thanks, @andreasn.  I agree with your assessment.

**Comment by stefwalter** [comment]
> What about using output of date from coreutils? Output can be formatted and there can be passed info about timezone.

The timedated API has Timezone information. As far as time, we can use the cockpit.Time DBus API, I' referenced in #1863

**Comment by fridex** [comment]
Implementation adjusted according to suggestions. Sorry for removing Bootstrap Datetimepicker in commits, I didn't see separate pull request.

**Comment by fridex** [comment]
Moment timezone was added to be able to show time in the server timezone.

**Comment by andreasn** [comment]
The dropdown seems to cover the input.

screenshot from 2015-03-17 15 50 49

**Comment by andreasn** [comment]
The dialog is very wide, so I wonder if we should considerer a patternfly override of 400px for this one. @stefwalter ?

**Comment by stefwalter** [comment]
Sounsd good to me. Do we have a standard class for a narrow dialog?

**Comment by andreasn** [comment]
There is a modal-sm class in bootstrap, http://getbootstrap.com/javascript/#modals-sizes
As far as I can see, it doesn't exist in Patternfly though, so we might need to create that class ourselves for now.

**Comment by andreasn** [comment]
The class only sets width: 300px

**Comment by andreasn** [comment]
These controls doesn't look great on Firefox under Linux. Looks OK in Chrome. Might need to skip the steppers.

screenshot from 2015-03-17 16 12 50

**Comment by andreasn** [comment]
I'm having issues understanding the string "Invalid absolute time". What about "Invalid date", would mean the corresponding time error string would be "Invalid time"

**Comment by andreasn** [comment]
Modified screenshot for the error state:
screenshot from 2015-03-17 16 46 04

Made it say "Invalid date format", since it could also be the case that you turned the numbers around somehow, or just mistyped a letter in there.
The "Invalid time format" would go in the same place (since it won't fit directly under the time controls). In the cases that you mistyped both the date and time, it could say "Invalid time format and Invalid date format" on the same row. It needs to only populate these when the "Change" button is pressed.
Check out the Administrator accounts, "Create New Account" for good prior art there.

**Comment by fridex** [comment]
> The dropdown seems to cover the input

I can reproduce this only on Firefox (Fedora) when page is zoomed out in one particular scale. I don't know what could be a problem maker there. Bootstrap datepicker has an option "orientation" that can be passed to adjust position of the picker, but it does not solve this issue for me.

> I'm having issues understanding the string "Invalid absolute time".

Where did you find this string?

**Comment by andreasn** [comment]
If I set the date to something wrong.

**Comment by andreasn** [comment]
Patternfly issue for modal-sm https://github.com/patternfly/patternfly/issues/51

**Comment by stefwalter** [comment]
Depends on #1926

**Comment by andreasn** [comment]
So Patternfly actually have support for modal-sm, but only in Patternfly 1.1.3.
There is no way we can have only this dialog use the new patternfly without migrating all of shell over to it (that we of course will do sooner or later anyway) to it, right?
Could just add the modal-sm class in there for now, and then it will start working at some point :)

**Comment by andreasn** [comment]
> Where did you find this string?

If I hand edit the date and set it to 03/18/55 and press "Change" this string shows up.

**Comment by andreasn** [comment]
> So Patternfly actually have support for modal-sm, but only in Patternfly 1.1.3.

Found that for pre-patternfly1.1.3 there is the cockpit-modal-sm class

**Comment by stefwalter** [comment]
Continuing this work in #1955

**Pull request closed without merging**
