### PR TITLE
test: system_before() tweaks

### PR DESCRIPTION
**Pull request by marusak**

### CODE REVIEW

**Comment by marusak** [comment]
Also triggering test for https://github.com/cockpit-project/bots/pull/1960

**Comment by marusak** [comment]
ja, ja, rhel-9-0 ist kaput

**Comment by marusak** [comment]
https://github.com/cockpit-project/bots/pull/1961

**Review by martinpitt — APPROVED** [review]
Thanks for the cleanups!

**Comment by marusak** [comment]
`return int(v[1]) < release` ehm

**Comment by martinpitt** [comment]
@marusak : Heh, yes -- I wonder why it even does that:
```
❱❱❱ rpm -q --qf '%{V}\\n' cockpit-system
241\n
```
The `\\n` seems unnecessary. I suppose it meant to use `%{V}.%{R}` to get a release? But do we even need that release bit? Checking for the version seems enough for me.

**Review by martinpitt — APPROVED** [review]
Cheers! LGTM, once green.

**Pull request merged**
