### PR TITLE
Sidebar: collapsible tools menu

### LINKED ISSUE #1868: Slide up tools menu
In the new navigation design, tools should be in a slide up tools menu. Tools are components you don't use very often, and shouldn't be always visible in the sidebar.

### PR DESCRIPTION
**Pull request by dperpeet**
Closes #1868

### CODE REVIEW

**Comment by dperpeet** [comment]
@andreasn here are screenshots of the current version
I'm not sure about indentation et cetera. Also, I fixed the width of the panel in absolute pixels - should we keep it that way?
screenshot from 2015-03-10 11 09 56
screenshot from 2015-03-10 11 10 00
screenshot from 2015-03-10 11 10 03

**Comment by dperpeet** [comment]
updated css

**Comment by stefwalter** [comment]
Is it possible for the tools expander to sit at the bottom of the sidebar pane, and then expand upwards? Obviously I would defer to @andreasn on this though.

**Comment by andreasn** [comment]
I see some small differences compared to the version here: https://www.patternfly.org/wp-content/uploads/patternfly/tests/form.html

* Tools header and childrens text don't line up.
* The text "Tools" jumps back and forth with a couple of pixels
* In Chrome the whole area is extra tall

I also wonder if we might as well make the whole area clickable. Like if Tools gets translated to a two letter word in some language (not sure that is the actual case). I'll file a Patternfly issue about that.

**Comment by andreasn** [comment]
I haven't quite made up my mind if the menu should go at the bottom or not. It would feel tucked away in a corner a bit, but maybe that's the intent.
I would say it depends a bit of what we expect to show up there. I don't want random, half-baked tools that brings down a nice user experience to get too much prominence, but I don't want to tuck them away too much either.

**Comment by andreasn** [comment]
Chrome screenshot.

screenshot from 2015-03-10 16 28 42

**Comment by andreasn** [comment]
I think this alignment would work better.
The hierarchy is already clear from the header, so no need to do extra indentation.
Unfortunately the examples on the Patternfly website doesn't have any good examples with a mixed menu. I'll keep looking.

screenshot from 2015-03-10 16 29 46

**Comment by andreasn** [comment]
> Also, I fixed the width of the panel in absolute pixels - should we keep it that way?

It depends a bit on how it affects the different screen resolutions.

**Comment by stefwalter** [comment]
> I haven't quite made up my mind if the menu should go at the bottom or not. It would feel tucked away in a corner a bit, but maybe that's the intent.

Yes, that was the intent. But if it's a bad idea, I'm not stuck on it.

**Comment by dperpeet** [comment]
> I would say it depends a bit of what we expect to show up there. I don't want random, half-baked tools that brings down a nice user experience to get too much prominence, but I don't want to tuck them away too much either.

If they're collapsed inside the "tools"-container, they're visually separated already. Why move them somewhere else on the screen as well? We already have several menus - enough complexity without splitting them up even further. Typically the "fixed" parts (corners, borders) of the screen are more valuable. At the bottom of the sidebar we could add user-defined quick-links or such things sometime in the future...

**Comment by mvollmer** [comment]
My bureaucratic contribution: We use `Fixes #...` to mark the bugs that a pull request fixes, and `Closes #...` to mark the pull request itself.

**Comment by dperpeet** [comment]
> My bureaucratic contribution: We use Fixes #... to mark the bugs that a pull request fixes, and Closes #... to mark the pull request itself.

Noted. I chose "Closes" here because it is a feature request and not about a bug or something broken. "Fix" on all issues and close on the pull request?

**Comment by andreasn** [comment]
Sorry for being slow on this review.
I think it's good where it is now. Having it attached to the bottom will make the whole open and close all wonky due to moving around (unless it expands upwards). Since it's closed by default on every fresh login it keeps out of the way enough that it feels appropiate for these second level elements that it hosts.

**Comment by dperpeet** [comment]
@andreasn sounds good! What behavior do we want for small screen resolutions? Or should we wait until you've updated patternfly on this page?

**Comment by andreasn** [comment]
I'm going to do the patternfly of this on Monday.

**Comment by dperpeet** [comment]
depends on #788

**Comment by stefwalter** [comment]
@dperpeet Why does this depend on #788? index.html already uses the new patternfly.

**Comment by dperpeet** [comment]
> @dperpeet Why does this depend on #788? index.html already uses the new patternfly.

There are some strange effects with the expanding box on lower resolutions.
@andreasn needs to look at that anyway with the new patternfly - especially shell.css. Once he has a workable general solution, we can apply that here or see if this is an even more special case. No use solving it here first only to change it again once most of cockpit is migrated to the new patternfly.

**Comment by stefwalter** [comment]
Depends on #2058

**Comment by stefwalter** [comment]
@andreasn Is this ready to go in now that the new Patternfly is in use?

**Comment by andreasn** [comment]
there was a missing "}", so added that, and a bit of margin so it didn't glue to the left side of the screen. https://github.com/andreasn/cockpit/tree/tools_menu-heightfix

**Pull request closed without merging**
