### PR TITLE
Debian networking

### PR DESCRIPTION
**Pull request by mvollmer**
Continuation of #5318

### CODE REVIEW

**Comment by stefwalter** [comment]
Marking as priority for the next release.

**Comment by stefwalter** [comment]
Seems like this needs another fixup commit on debian-unstable:

```
# testBasic (check_networking.TestNetworking)
#
52:54:00:9e:00:F2 -> ens6
52:54:00:9e:00:F2 -> ens6
Page error: TypeError: undefined is not an object (evaluating 's.main_connection.Masters.length')
http://10.111.126.77:9090/cockpit/$3b1bf030f6c5421fea2096ddce8a3509b8254d0c/network/network.js 2 t
http://10.111.126.77:9090/cockpit/$3b1bf030f6c5421fea2096ddce8a3509b8254d0c/network/network.js 2 update
http://10.111.126.77:9090/cockpit/$3b1bf030f6c5421fea2096ddce8a3509b8254d0c/network/network.js 1 enter
http://10.111.126.77:9090/cockpit/$3b1bf030f6c5421fea2096ddce8a3509b8254d0c/network/network.js 1 B
http://10.111.126.77:9090/cockpit/$3b1bf030f6c5421fea2096ddce8a3509b8254d0c/network/network.js 1 e
http://10.111.126.77:9090/cockpit/$3b1bf030f6c5421fea2096ddce8a3509b8254d0c/base1/jquery.js 2 dispatch
http://10.111.126.77:9090/cockpit/$3b1bf030f6c5421fea2096ddce8a3509b8254d0c/base1/jquery.js 2 handle
http://10.111.126.77:9090/cockpit/$3b1bf030f6c5421fea2096ddce8a3509b8254d0c/base1/cockpit.js 1 f
http://10.111.126.77:9090/cockpit/$3b1bf030f6c5421fea2096ddce8a3509b8254d0c/base1/cockpit.js 1 o
http://10.111.126.77:9090/cockpit/$3b1bf030f6c5421fea2096ddce8a3509b8254d0c/base1/cockpit.js 1 
Wrote TestNetworking-testBasic-FAIL.png
Journal extracted to TestNetworking-testBasic-10.111.126.77-FAIL.log
not ok 20 testBasic (check_networking.TestNetworking) duration: 65s
Traceback (most recent call last):
  File "./verify/check-networking", line 110, in testBasic
    b.wait_visible("#network-interface")
  File "/build/cockpit/test/common/testlib.py", line 226, in wait_visible
    return self.wait_js_func('ph_is_visible', selector)
  File "/build/cockpit/test/common/testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 698, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 721, in _invoke
    raise Error(res['error'])
Error: TypeError: undefined is not an object (evaluating 's.main_connection.Masters.length')
```

**Comment by stefwalter** [comment]
And also:

```
# testTeam (check_networking.TestNetworking)
#
52:54:00:12:34:56 -> ens6
52:54:00:12:34:56 -> ens6
52:54:00:12:34:57 -> ens7
52:54:00:12:34:57 -> ens7
Wrote TestNetworking-testTeam-FAIL.png
Journal extracted to TestNetworking-testTeam-10.111.126.81-FAIL.log
not ok 25 testTeam (check_networking.TestNetworking) duration: 215s
Traceback (most recent call last):
  File "./verify/check-networking", line 322, in testTeam
    b.wait_present("#network-interface-slaves tr[data-interface='%s']" % iface1)
  File "/build/cockpit/test/common/testlib.py", line 217, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 211, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 698, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 721, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by stefwalter** [comment]
If the tests pass, I can rebase this while merging.

**Comment by stefwalter** [comment]
Needs a rebase ... in addition the fedora-25 failures seem related.

**Comment by stefwalter** [comment]
Ditto for debian-unstable failure seems related.

**Comment by mvollmer** [comment]
`check-networking` is passing locally on both debian-unstable and fedora-25.

**Comment by stefwalter** [comment]
Will resolve an conflict between this an #5321, #5329 and #5322 while merging ... where check-networking ```testOther``` needs to be disabled for Ubuntu.

**Pull request closed without merging**
