### PR TITLE
shell: Change host key dialogs to match the login page

### PR DESCRIPTION
**Pull request by mvollmer**
The Shell has to handle the same situations as the login page when
connecting to remote machines, so they should use the same dialogs.

### CODE REVIEW

**Comment by mvollmer** [comment]
(Tests haven't been run yet at all, so let's see what needs to change.)

**Comment by mvollmer** [comment]
Hmm, we should probably move pkg/base1/test-machines to pkg/shell/machines as well.

**Comment by mvollmer** [comment]
> Hmm, we should probably move pkg/base1/test-machines to pkg/shell/machines as well.

Done.

**Review by martinpitt — APPROVED** [review]
This is super nice, thank you! I tested this interactively, and it is so much more informative now.

**Pull request merged**
