### PR TITLE
Image refresh for fedora-27

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-27
 * [x] image-refresh fedora-27

### CODE REVIEW

**Comment by martinpitt** [comment]
Something apparently changed in kubernetes:
```
error: current-context must exist in order to minify

> received invalid kubectl config SyntaxError: JSON Parse error: Unexpected EOF
```

@petervo, is that something for you?

**Comment by petervo** [comment]
That error message is normal when the config file is blank. So if something changed it's not related to that.

**Comment by martinpitt** [comment]
Oh, ok. Let's see what a retry thinks about it then.

**Comment by petervo** [comment]
I'll look into this

**Comment by petervo** [comment]
This looks like an instance of https://github.com/openshift/origin/issues/15038. Caused by a change in the docker version. So looks like a known issue is needed.

**Comment by petervo** [comment]
We can work around this by removing the default container secrets. Seems better to me than a known issue that stops the tests from running at all.

**Pull request closed without merging**
