### PR TITLE
bots: Do not show unnecessary information in terminal

### PR DESCRIPTION
**Pull request by marusak**
* [x] image-refresh debian-stable
 * [x] image-refresh debian-testing
 * [x] image-refresh ubuntu-1804
 * [x] image-refresh ubuntu-stable

When logged in as admin into Ubuntu 18.04 image a message
`To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.` is displayed on first two lines.

This makes testing terminal harder, as on other distros we expect first
line to contain prompt and other lines to be empty.

After this commit mentioned lines are not displayed anymore.

Blocks #11125 (Only ubuntu-1804 is affected but I thought refreshing all images that the change affects would be better)

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-2hq8q.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11141-20190209-064343/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-stable-20190209-072525

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-w036t.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11141-20190209-072424/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-testing-20190209-074545

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-f6fhl.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11141-20190209-074646/

**Comment by cockpituous** [comment]
image-refresh ubuntu-1804 done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-1804-20190209-080303

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-d4tl3.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11141-20190209-080606/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-mjctf.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11141-20190209-080606/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-stable-20190209-083232

**Comment by martinpitt** [comment]
TBH I think it would have been more efficient to do this touch command in the test itself, or in bots/images/scripts/lib/debian.install . This would avoid a full image rebuild, and is more flexible.

But it's ok, if you want to go ahead with this. -- Add the images to this PR, and add a Closes #, then we can land this swiftly.

**Comment by marusak** [comment]
I wanted to avoid touching that file in test and did not realize we can put it in install script. Next time will be smarter :)

I decided to continue with this as it was already done. I've picked all updated images and added closes line.

**Pull request merged**
