### PR TITLE
test: Drop rhel-8-2 special cases

### PR DESCRIPTION
**Pull request by martinpitt**
- [x] Add special cases for rhel-8-3-distropkg: PR #14178
 - [x] Drop rhel-8-2 tests: https://github.com/cockpit-project/bots/pull/934
 - [x] Fix naughty pattern: https://github.com/cockpit-project/bots/pull/946

### CODE REVIEW

**Comment by martinpitt** [comment]
[check-system-info failure on fcos](https://logs.cockpit-project.org/logs/pull-14187-20200604-080906-0593dbc0-fedora-coreos/log.html_), [weird failures on d-testing](https://logs.cockpit-project.org/logs/pull-14187-20200604-072030-0593dbc0-debian-testing/log.html#147-2), retrying for comparison

**Comment by KKoukiou** [comment]
> [check-system-info failure on fcos](https://logs.cockpit-project.org/logs/pull-14187-20200604-080906-0593dbc0-fedora-coreos/log.html_), [weird failures on d-testing](https://logs.cockpit-project.org/logs/pull-14187-20200604-072030-0593dbc0-debian-testing/log.html#147-2), retrying for comparison

[check-system-info](https://logs.cockpit-project.org/logs/pull-14187-20200604-094702-0593dbc0-fedora-coreos/log.html) failed again.

**Comment by martinpitt** [comment]
FTR, I can reproduce the fedora-coreos crash.  It's not related to the changes here, it happens on master as well. It's apparently a regression from yesterday's image refresh. The `chattr` call causes a kernel panic:
```
[   25.672050] general protection fault, probably for non-canonical address 0x3b656c7469742e65: 0000 [#1] SMP PTI
[   25.674650] CPU: 0 PID: 1127 Comm: sshd Not tainted 5.6.14-300.fc32.x86_64 #1
[   25.676459] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.13.0-2.fc32 04/01/2014
[   25.678671] RIP: 0010:__cgroup_bpf_run_filter_skb+0x155/0x1d0
[   25.680172] Code: 48 8b 4c 24 08 4c 01 ab c8 00 00 00 48 89 4b 18 48 83 c4 10 5b 5d 41 5c 41 5d 41 5e 41 5f c3 31 c0 c3 c3 48 8b 86 20 06 00 00 <48> 8b 78 10 4c 8d 70 10 48 85 ff 74 5f 31 ed 49 8b 46 08 65 48 89
[   25.685046] RSP: 0018:ffffbd6500443b30 EFLAGS: 00010246
[   25.686417] RAX: 3b656c7469742e65 RBX: ffffa07eb894b4e0 RCX: 0000000000000034
[   25.688298] RDX: 0000000000000000 RSI: ffffa07ec2785000 RDI: ffffa07ebc0b3600
[   25.690214] RBP: ffffa07ebc0b3600 R08: ffffbd6500443aa8 R09: 0000000000000000
[   25.692205] R10: 0000000000010000 R11: ffffa07eb898f640 R12: 0000000000000000
[   25.694147] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000001
[   25.696077] FS:  00007f989765a900(0000) GS:ffffa07ec6a00000(0000) knlGS:0000000000000000
[   25.698102] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   25.699689] CR2: 0000562e7d4c4000 CR3: 000000002e9fc005 CR4: 0000000000160ef0
[   25.701416] Call Trace:
[   25.702277]  ip_finish_output+0x68/0xa0
[   25.703355]  __ip_queue_xmit+0x17d/0x420
[   25.704771]  ? set_fd_set.part.0+0x40/0x40
[   25.706299]  __tcp_transmit_skb+0x4d6/0xb40
[   25.707711]  tcp_write_xmit+0x391/0x11e0
[   25.709081]  __tcp_push_pending_frames+0x32/0xf0
[   25.710533]  tcp_sendmsg_locked+0x789/0xb00
[   25.711921]  tcp_sendmsg+0x28/0x40
[   25.713097]  sock_sendmsg+0x57/0x60
[   25.714218]  sock_write_iter+0x89/0xd0
[   25.715343]  new_sync_write+0x18c/0x1a0
[   25.716518]  vfs_write+0xb6/0x1a0
[   25.718220]  ksys_write+0x87/0xc0
[   25.719472]  do_syscall_64+0x5b/0xf0
[   25.720588]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[   25.722086] RIP: 0033:0x7f9897a005e7
[   25.723339] Code: 0d 00 f7 d8 64 89 02 48 c7 c0 ff ff ff ff eb b7 0f 1f 00 f3 0f 1e fa 64 8b 04 25 18 00 00 00 85 c0 75 10 b8 01 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 51 c3 48 83 ec 28 48 89 54 24 18 48 89 74 24
[   25.728233] RSP: 002b:00007ffe10655b48 EFLAGS: 00000246 ORIG_RAX: 0000000000000001
[   25.730354] RAX: ffffffffffffffda RBX: 0000000000000024 RCX: 00007f9897a005e7
[   25.732345] RDX: 0000000000000024 RSI: 0000558e81c958b0 RDI: 0000000000000005
[   25.734534] RBP: 0000558e81c634d0 R08: 00000008e8f0722e R09: 00007ffe10655bd8
[   25.736541] R10: 0000000000000008 R11: 0000000000000246 R12: 0000000000000000
[   25.738650] R13: 0000558e807c6788 R14: 0000000000000005 R15: 0000558e8077af80
[   25.740800] Modules linked in: xt_conntrack iptable_filter xt_MASQUERADE xt_comment iptable_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 veth overlay rfkill vfat fat intel_rapl_msr intel_rapl_common kvm_intel kvm irqbypass snd_pcsp snd_pcm snd_timer snd joydev soundcore virtio_balloon i2c_piix4 br_netfilter bridge drm stp llc ip_tables xfs dm_multipath crct10dif_pclmul crc32_pclmul ghash_clmulni_intel virtio_net virtio_blk serio_raw ata_generic virtio_scsi net_failover failover pata_acpi qemu_fw_cfg btrfs blake2b_generic xor zstd_compress raid6_pq libcrc32c crc32c_intel zstd_decompress fuse
[   25.755205] ---[ end trace 2d4a5b09e94bf464 ]---
[   25.756648] RIP: 0010:__cgroup_bpf_run_filter_skb+0x155/0x1d0
[   25.758399] Code: 48 8b 4c 24 08 4c 01 ab c8 00 00 00 48 89 4b 18 48 83 c4 10 5b 5d 41 5c 41 5d 41 5e 41 5f c3 31 c0 c3 c3 48 8b 86 20 06 00 00 <48> 8b 78 10 4c 8d 70 10 48 85 ff 74 5f 31 ed 49 8b 46 08 65 48 89
[   25.764367] RSP: 0018:ffffbd6500443b30 EFLAGS: 00010246
[   25.766067] RAX: 3b656c7469742e65 RBX: ffffa07eb894b4e0 RCX: 0000000000000034
[   25.771208] RDX: 0000000000000000 RSI: ffffa07ec2785000 RDI: ffffa07ebc0b3600
[   25.773236] RBP: ffffa07ebc0b3600 R08: ffffbd6500443aa8 R09: 0000000000000000
[   25.775275] R10: 0000000000010000 R11: ffffa07eb898f640 R12: 0000000000000000
[   25.777662] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000001
[   25.779719] FS:  00007f989765a900(0000) GS:ffffa07ec6a00000(0000) knlGS:0000000000000000
[   25.782019] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   25.784006] CR2: 0000562e7d4c4000 CR3: 000000002e9fc005 CR4: 0000000000160ef0
[   25.797703] general protection fault, probably for non-canonical address 0x6761702e75203d20: 0000 [#2] SMP PTI
[   25.800203] CPU: 0 PID: 10 Comm: ksoftirqd/0 Tainted: G      D           5.6.14-300.fc32.x86_64 #1
[   25.802090] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.13.0-2.fc32 04/01/2014
[   25.805376] RIP: 0010:__cgroup_bpf_run_filter_skb+0xca/0x1d0
[   25.808448] Code: 48 89 83 c8 00 00 00 48 01 c8 48 89 14 24 48 89 43 50 41 83 ff 01 0f 84 92 00 00 00 44 89 fa 48 8d 84 d6 18 06 00 00 48 8b 00 <48> 8b 78 10 4c 8d 78 10 48 85 ff 0f 84 df 00 00 00 bd 01 00 00 00
[   25.813616] RSP: 0018:ffffbd650005ba78 EFLAGS: 00010297
[   25.815659] RAX: 6761702e75203d20 RBX: ffffa07ec5e58500 RCX: 000000000000005c
[   25.819016] RDX: 0000000000000000 RSI: ffffa07ec2785000 RDI: ffffa07ebc0b0000
[   25.821816] RBP: ffffa07ec5e58500 R08: 0000000000000001 R09: 0000000000000001
[   25.824133] R10: 00000000000098a5 R11: ffffa07eb898f3c0 R12: 0000000000000014
[   25.826842] R13: 0000000000000014 R14: 0000000000000000 R15: 0000000000000000
[   25.828994] FS:  0000000000000000(0000) GS:ffffa07ec6a00000(0000) knlGS:0000000000000000
[   25.831817] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   25.833794] CR2: 00007fa187b1b9d0 CR3: 000000003c2e8001 CR4: 0000000000160ef0
[   25.836255] Call Trace:
[   25.837225]  sk_filter_trim_cap+0x105/0x200
[   25.838847]  ? tcp_v4_inbound_md5_hash+0x4c/0x160
[   25.840329]  tcp_v4_rcv+0xae6/0xd00
[   25.841575]  ? nf_hook_slow+0x3f/0xb0
[   25.843492]  ip_protocol_deliver_rcu+0x2b/0x1b0
[   25.845135]  ip_local_deliver_finish+0x44/0x50
[   25.846593]  __netif_receive_skb_core+0x462/0xed0
[   25.848266]  ? csum_partial+0xd/0x20
[   25.849562]  ? __skb_checksum+0x6c/0x2f0
[   25.850974]  ? __napi_alloc_skb+0x9d/0xe0
[   25.852413]  __netif_receive_skb_list_core+0x128/0x2c0
[   25.854142]  netif_receive_skb_list_internal+0x1bc/0x2d0
[   25.855557]  napi_complete_done+0x93/0x150
[   25.856531]  virtqueue_napi_complete+0x2b/0x80 [virtio_net]
[   25.857736]  virtnet_poll+0x2c0/0x306 [virtio_net]
[   25.858961]  net_rx_action+0x13c/0x3e0
[   25.860183]  ? __switch_to_asm+0x34/0x70
[   25.861521]  __do_softirq+0xe9/0x2dc
[   25.862620]  run_ksoftirqd+0x26/0x40
[   25.863703]  smpboot_thread_fn+0xc5/0x160
[   25.865021]  ? smpboot_register_percpu_thread+0xf0/0xf0
[   25.866812]  kthread+0x115/0x140
[   25.868105]  ? __kthread_bind_mask+0x60/0x60
[   25.869580]  ret_from_fork+0x35/0x40
[   25.870785] Modules linked in: xt_conntrack iptable_filter xt_MASQUERADE xt_comment iptable_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 veth overlay rfkill vfat fat intel_rapl_msr intel_rapl_common kvm_intel kvm irqbypass snd_pcsp snd_pcm snd_timer snd joydev soundcore virtio_balloon i2c_piix4 br_netfilter bridge drm stp llc ip_tables xfs dm_multipath crct10dif_pclmul crc32_pclmul ghash_clmulni_intel virtio_net virtio_blk serio_raw ata_generic virtio_scsi net_failover failover pata_acpi qemu_fw_cfg btrfs blake2b_generic xor zstd_compress raid6_pq libcrc32c crc32c_intel zstd_decompress fuse
[   25.887148] ---[ end trace 2d4a5b09e94bf465 ]---
[   25.888669] RIP: 0010:__cgroup_bpf_run_filter_skb+0x155/0x1d0
[   25.890517] Code: 48 8b 4c 24 08 4c 01 ab c8 00 00 00 48 89 4b 18 48 83 c4 10 5b 5d 41 5c 41 5d 41 5e 41 5f c3 31 c0 c3 c3 48 8b 86 20 06 00 00 <48> 8b 78 10 4c 8d 70 10 48 85 ff 74 5f 31 ed 49 8b 46 08 65 48 89
[   25.896526] RSP: 0018:ffffbd6500443b30 EFLAGS: 00010246
[   25.898409] RAX: 3b656c7469742e65 RBX: ffffa07eb894b4e0 RCX: 0000000000000034
[   25.900755] RDX: 0000000000000000 RSI: ffffa07ec2785000 RDI: ffffa07ebc0b3600
[   25.902958] RBP: ffffa07ebc0b3600 R08: ffffbd6500443aa8 R09: 0000000000000000
[   25.905175] R10: 0000000000010000 R11: ffffa07eb898f640 R12: 0000000000000000
[   25.907772] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000001
[   25.910077] FS:  0000000000000000(0000) GS:ffffa07ec6a00000(0000) knlGS:0000000000000000
[   25.912517] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   25.914465] CR2: 00007fa187b1b9d0 CR3: 000000003c2e8001 CR4: 0000000000160ef0
[   25.916456] Kernel panic - not syncing: Fatal exception in interrupt
[   25.918005] Kernel Offset: 0x12000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[   25.921103] ---[ end Kernel panic - not syncing: Fatal exception in interrupt ]---
```

**Comment by martinpitt** [comment]
[This failure](https://logs.cockpit-project.org/logs/pull-14187-20200604-140523-0593dbc0-fedora-32/log.html#244-2) is an actual issue - the naughty pattern is wrong. I sent a fix to https://github.com/cockpit-project/bots/pull/946

**Comment by martinpitt** [comment]
debian-testing: [TestJournal.testBasic](https://logs.cockpit-project.org/logs/pull-14187-20200604-155933-0593dbc0-debian-testing/log.html#136-2) failure happens on master as well, presumably some systemd changed behaviour. 

The `no network with matching name 'default'` failures are more mysterious, I can't reproduce them locally yet. I'll retry for comparison.

**Pull request merged**
