### PR TITLE
branding: use new Ubuntu logo in favicon

### PR DESCRIPTION
**Pull request by logonoff**
The favicon for Ubuntu uses the old logo which was changed back in 22.04. In this PR, I grabbed the latest favicons from ubuntu.com and combined them into an ico

### CODE REVIEW

**Comment by jelly** [comment]
The new icon size is 180x180 pixels while the old one was 48x48px. @martinpitt  did we have permission to copy the favicon to Cockpit?

**Comment by martinpitt** [comment]
@jelly I don't know, this was before my time. But commit 05cbc6bc3011aa5c6989f521377444e3e891d749 says it was taken from the plymouth package, which according to debian/copyright is GPL-v2.

@logonoff indeed we need to be sure that we have the right to redistribute this icon, and need to add a copyright statement. For example, the official downloads on https://design.ubuntu.com/resources?metadata=element-logo+brand-ubuntu are distinctively different.

(Yes, I know that is annoying, but we want to be careful here)

**Comment by martinpitt** [comment]
There are currently two logos in Ubuntu's latest plymouth package, this:

ubuntu-logo

That one has a white "Ubuntu" text after the orange icon, which you can't see in GitHub (so open it separately).

and this without text:

bgrt-fallback

This would be fine as favicon I think? These are both GPL-v2+

**Comment by logonoff** [comment]
> There are currently two logos in Ubuntu's latest plymouth package, this:
> 
> ubuntu-logo
> 
> That one has a white "Ubuntu" text after the orange icon, which you can't see in GitHub (so open it separately).
> 
> and this without text:
> 
> bgrt-fallback
> 
> This would be fine as favicon I think? These are both GPL-v2+

I've just updated my PR to use a scaled down, converted-to-ico version of the Ubuntu logo found in its plymouth package. In the copyright file it seems like it's licensed under GPL-2.0-or-later:

```
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: Plymouth
Upstream-Contact: plymouth@lists.freedesktop.org
Source: http://www.freedesktop.org/software/plymouth/releases/

Files: *
Copyright: 2006-2008 Red Hat, Inc.
           2007-2008 Ray Strode <halfline@gmail.com>
           2003 University of Southern California
           2003 Charlie Brej <cbrej@cs.man.ac.uk>
License: GPL-2+

Files: debian/*
Copyright: 2009-2014 Daniel Baumann <mail@daniel-baumann.ch>
License: GPL-2+

Files: debian/local/debian-logo.png
Copyright: 1999 Software in the Public Interest, Inc.
License: other

License: other
 Debian Open Use Logo License
[omitted]

License: GPL-2+
[omitted]
```
Are there any other places where I need to put this acknowledgement?

**Review by martinpitt — APPROVED** [review]
Thank you! No, structurally nothing changed now, we just updated the existing logo from the Plymouth package.

**Pull request merged**
