### PR TITLE
docker: Refactor pull request code

### PR DESCRIPTION
**Pull request by stefwalter**
Migrate the pull functionality into docker.js
    
This allows the logic to be moved away from the presentation layer. Also gets this ready for reuse outside of the containers page, such as with the Atomic App Entity work.

### CODE REVIEW

**Comment by stefwalter** [comment]
@sub-mod This is relevant to app spec work if we end up pulling a docker meta image directly from Cockpit.

**Comment by stefwalter** [comment]
Fixes #2272

**Comment by dperpeet** [comment]
Download status is very tiny... it would help to have the full text as a popup/hover info for the field. The elided version isn't that helpful.
docker_download_status
I think this should be a follow-up issue though.

**Comment by stefwalter** [comment]
Yes, agree with a follow up issue. This pull request does not change design.

**Pull request closed without merging**
