### PR TITLE
base: Show numbers with more precision

### LINKED ISSUE #8361: show disk usage with more precision
Dear,

I have a disk of 1.1TB and Cockpit report it as 0.2 / 1.1 TiB, incrementing by 0.1TB.
So disk usage is reported 10% per 10% and is not accurate at all.

how can I report thoses value in GB instead ?
if not possible how can I add more numbers after the dot? (report 0.159TB instead of rounding it to 0.2TB)

I use the version provided in ubuntu server artful repo  :

> $ cockpit-bridge --version
> Version: 151
> Protocol: 1
> Payloads: dbus-json3 http-stream1 http-stream2 stream fsread1 
>     fsreplace1 fswatch1 fslist1 null echo websocket-stream1 
> Authorization: crypt1

in the picture attached, the difference with eSM for example which is more accurate
storagediff

best regards,

thanks.
Kurairaito

### PR DESCRIPTION
**Pull request by mvollmer**
Now we use 3 digits of precision (for non-integers), instead of 1
digit after the comma.

This should help especially when showing usage numbers for
filesystems, where we might show a small number (used bytes) with a
unit that is appropriate for a big number (total bytes).

Fixes #8361

### CODE REVIEW

**Comment by martinpitt** [comment]
Lots of test failures like

    FAIL: dist/base1/test-format.html 6 - format_number(123.4) = 123.4, expected: "123.4", got: "123", test: format_number, module: , source: http://localhost:59277/dist/base1/qunit.js:2194:17

**Comment by mvollmer** [comment]
@andreasn, @garrett, any thoughts?  This changes how numbers are displayed all over Cockpit.  I think the previous way wasn't all that bad, but it was very precise about small numbers.  People want to see `0.123` instead of just `0.1`.  See #8361.

Technically, the problem with using `toPrecision` is that it might produce scientific notation `123e-2`, and I think we really want to keep that out of the UI.  I think I got that right, however.

**Comment by mvollmer** [comment]
When in doubt, I am totally happy to keep the current behavior, and mabye make it easier for people to get the real, unrounded number, maybe in a tooltip.

**Comment by martinpitt** [comment]
Semantically I think something like "always show 3 significant digits" makes much more sense than "always show one digit after decimal dot", as we have different magnitudes of numbers in cockpit.

```
> n = 123.456
123.456
> n.toPrecision(3)
'123'

> n = 0.123456
0.123456
> n.toPrecision(3)
'0.123'
```

However, it seems `toPrecision()` is a bit unexpected when there are further zeros after the decimal dot:
```
> n = 0.002
0.002
> n.toPrecision(3)
'0.00200'
```
This is not right, as the "00" after the dot are just as significant as the "12", and at least in our cases we want this interpreted as such, not as a magnitude. But all in all this is IMHO still a better default than `toFixed(1)`, so +1 from me.

**Comment by mvollmer** [comment]
> This is not right, as the "00" after the dot are just as significant as the "12",

Hmm, I think it is right, but it looks a bit funny.  The "00" after the dot represents the exponent, and the "200" is the mantissa.  We could make another special case for this, but I think this case ought to be rare with real world numbers.

**Comment by martinpitt** [comment]
https://fedorapeople.org/groups/cockpit/logs/pull-8382-20180118-112424-10592824-verify-rhel-7-5/log.html#88 looks relevant:
```
  File "/build/cockpit/bots/../test/verify/check-storage-vdo", line 75, in testVdo
    self.content_tab_wait_in_info(1, 1, "Used", "of 5.0 GiB")
[..]
Error: timed out waiting for predicate to become true
```
as we test vdo only on rhel-7-5, this sounds real, presumably it's "5.00" now or so. Unfortunately attaching the dumped .html didn't work here.

**Pull request merged**
