### PR TITLE
storage: Remove "Partition" content tab

### PR DESCRIPTION
**Pull request by mvollmer**
Cockpit does not allow setting or changing any of the information shown in this content tab, and the "Name" can easily be confused with the "Name" in the "Filesystem" content tab.

Also, the less tabs we have, the easier the move to a new layout without any tabs will be.

### CODE REVIEW

**Comment by mvollmer** [comment]
See #19170 for an example of the "Name" confusion.

**Comment by martinpitt** [comment]
Indeed there isn't too much information there:

image

The size is already shown in the row header (progress bar), and the GPT UUIDs are indecipherable for a human as well. The type might be more useful on a classic MSDOS partition, though? Could this be moved as "Partition type" into the filesystem tab perhaps?

**Comment by mvollmer** [comment]
I have no strong opinion here... we can also leave it as it is until we get to it during the redesign.

**Comment by mvollmer** [comment]
We will probably want to eventually offer resizing of partitions, so we need a partition specific place for that... hmm.

**Comment by mvollmer** [comment]
Let's not do this.

**Pull request closed without merging**
