### PR TITLE
Image refresh for fedora-24

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for fedora-24 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-24-2016-07-01/

### CODE REVIEW

**Comment by mvollmer** [comment]
´settroubleshootd` seems to be broken, it doesn't return any alerts via `get_all_alerts`.

**Comment by mvollmer** [comment]
> `settroubleshootd` seems to be broken, it doesn't return any alerts via `get_all_alerts`.

https://bugzilla.redhat.com/attachment.cgi?id=1176064

**Comment by mvollmer** [comment]
(I gave the wrong link to the bug. it's corrected now.)

**Comment by stefwalter** [comment]
Merged an update to fedora-24 elsewhere.

**Pull request closed without merging**
