### PR TITLE
An interframe JSON cache

### PR DESCRIPTION
**Pull request by stefwalter**
An interframe JSON cache which allows implementations of objects to share their state across frames. The first consumer of this is the package loading stuff, but the discovery stuff should also use this.

### CODE REVIEW

**Comment by stefwalter** [comment]
Ready. Just needs documentation.

**Comment by stefwalter** [comment]
Documentation added.

**Comment by stefwalter** [comment]
Depends on #2346

**Comment by stefwalter** [comment]
Coding complete. Needs testing, bug fixing.

**Comment by petervo** [comment]
Made the tests pass here. 

https://github.com/petervo/cockpit/tree/json-cache

**Comment by stefwalter** [comment]
@petervo Thanks.

By the way i'm removing the unused argument to machines.instance(). Hope that's okay.

**Comment by stefwalter** [comment]
@petervo I only put in the minimal amount of cleanup now and squashed ... split up a lot of issues into separate pull requests, and I'll do a follow up later.

**Pull request closed without merging**
