### PR TITLE
testlib.py: Add gensnippet_if crash to allowed_messages

### PR DESCRIPTION
**Pull request by Gundersanne**
See https://bugzilla.redhat.com/show_bug.cgi?id=1884236.

### CODE REVIEW

**Comment by Gundersanne** [comment]
Ugh forgot the no-test label, anyway triggering `fedora-coreos@bots#1267`

**Comment by marusak** [comment]
Wouldn't this be better as known issue? Much easier to track this. Or it happens way too often?

**Comment by Gundersanne** [comment]
@marusak  Happens pretty much on every single fedora-coreos test, as it happens when cockpit is started :/

**Review by marusak — APPROVED** [review]
Right, then it makes sense here. Thanks!
Please make sure that `fedora-coreos@bots#1267` is happy before landing.

**Comment by Gundersanne** [comment]
fedora-coreos@bots#1267 is green so landing

**Pull request merged**
