### PR TITLE
ws: Add machine field to login.html

### PR DESCRIPTION
**Pull request by petervo**
Needs tests, but @andreasn and @stefwalter can you see what you think about how it looks/works.

### CODE REVIEW

**Comment by stefwalter** [comment]
screenshot from 2016-10-27 10-58-46

screenshot from 2016-10-27 10-58-57

**Comment by stefwalter** [comment]
Eventually we want two additional inputs in this expanded mode:

```
Server: [____________________]
 [x] Use my password for privileged tasks and to connect to other machines.

**Comment by andreasn** [comment]
mockup

What about something like this?

**Comment by petervo** [comment]
Brought in font-awesome for the caret but skipped doing the (i) with the tooltip and used a title attribute instead. Made the label and help text a little shorter.

**Comment by stefwalter** [comment]
Some tests failures happening:

```
# testBasic (check_login.TestLogin)
#
> Authentication failed
Page error: #login-button is disabled or somehow not clickable
phantomjs://code/phantom-lib.js 127 ph_click
 1 
 1 
Wrote TestLogin-testBasic-FAIL.png
Journal extracted to TestLogin-testBasic-10.111.114.14-FAIL.log
not ok 50 testBasic (check_login.TestLogin) duration: 17s
Traceback (most recent call last):
  File "./verify/check-login", line 70, in testBasic
    login ("user", "abcdefg")
  File "./verify/check-login", line 59, in login
    b.click('#login-button')
  File "/build/cockpit/test/common/testlib.py", line 156, in click
    self.call_js_func('ph_click', selector, force)
  File "/build/cockpit/test/common/testlib.py", line 141, in call_js_func
    return self.phantom.eval("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 689, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 712, in _invoke
    raise Error(res['error'])
Error: #login-button is disabled or somehow not clickable
```

I'd also like to look at using an inline SVG instead of the entire font-awesome font being loaded twice by Cockpit during start up.

**Comment by stefwalter** [comment]
Here's a commit using SVG https://github.com/stefwalter/cockpit/commit/d2934d094e2ab28f9bb5ec2f7d568b2138d8edd5

**Comment by stefwalter** [comment]
Fixup for the SVG https://github.com/stefwalter/cockpit/commit/e23be665f244e38affd40dc1298d68cc6e6b1072

**Comment by stefwalter** [comment]
This adds the clear block in the design: https://github.com/stefwalter/cockpit/commit/b5fb1dcc487d46d993ec544382f4dce0cb16fc07

**Pull request closed without merging**
