### PR TITLE
Fix rhel-x image

### LINKED ISSUE #10042: Image refresh for rhel-x
Image refresh for rhel-x
 * [ ] FAIL: image-refresh rhel-x

### PR DESCRIPTION
**Pull request by martinpitt**
Fixes #10042 

 * [x] image-refresh rhel-x
 * [x] ignore SELinux errors about sshd/agetty motd read denial (https://bugzilla.redhat.com/show_bug.cgi?id=1629588)
 * [x] override `check-connection testSocket` regresssion (known issue #10084)
 * [x] override `testIpa` regression (known issue #10086)
 * [x] override `testOtherSettings` SELinux violation

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh rhel-x done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-x-20180916-220202

**Comment by martinpitt** [comment]
Bwah, I filed https://bugzilla.redhat.com/show_bug.cgi?id=1629588 for the new SELinux denial. This is too noisy for a naughty.

**Comment by martinpitt** [comment]
Reported and overrode two more SELinux regressions.

**Comment by martinpitt** [comment]
Pushed another flake fix. This is unrelated to this PR, and I've seen it before, but this is a good place to verify it.

**Comment by martinpitt** [comment]
[One failure on rhel-x](https://209.132.184.41:8493/logs/pull-10074-20180917-123030-b92995ee-verify-rhel-x/log.html#56), which I just investigated and fixed in #10081. Retrying harder in the meantime.

**Comment by martinpitt** [comment]
priority, the last commit here is a flake fix that also helps with other PRs.

**Comment by larskarlitski** [comment]
Thanks!

**Pull request merged**
