### PR TITLE
po: Add Japanese translation to RHEL 7.4 branch

### PR DESCRIPTION
**Pull request by stefwalter**
This translation is ready for use on Zanata and is at 100%
translated.

### CODE REVIEW

**Comment by stefwalter** [comment]
screenshot from 2017-06-20 09-53-13

**Comment by dperpeet** [comment]
In case someone else is wondering why `SELinux` isn't translated - it also isn't when used as part of other messages. Apparently that's kept verbatim.

The other menu entries only appear on dev builds.

**Comment by dperpeet** [comment]
We need the known issues in #7025 to get the tests green

**Comment by petervo** [comment]
Can we push this to master on zanta as well?

**Comment by stefwalter** [comment]
> Can we push this to master on zanta as well?

I couldn't figure out how to copy on the Zanata website/service ... Is it a manual thing?

**Pull request merged**
