### PR TITLE
Glyphicons

### PR DESCRIPTION
**Pull request by stefwalter**
Add missing glyphicons halflings font. This is part of patternfly and bootstrap.

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #1854

**Comment by mvollmer** [comment]
This also adds `lib/glyphicons-halflings.v1.009.ttf` but I think we only use woff files now, no?

**Comment by stefwalter** [comment]
> This also adds lib/glyphicons-halflings.v1.009.ttf but I think we only use woff files now, no?

We don't install ttf files, but they're still in the lib/ directory for use while developing cockpit. You can install them, use charmap on them, etc.

**Comment by stefwalter** [comment]
Rebased.

**Pull request closed without merging**
