### PR TITLE
bots: Drop obsolete subscription copying in image builder scripts

### PR DESCRIPTION
**Pull request by martinpitt**
Commit 523e9dcbcf dropped the consumption of the subscription
credentials from rhel.setup. Also drop the corresponding copying of them
into the VM, so that they don't stay around in the final image.

This was also the only usage of libguestfs in the entire project. This
is a really heavy dependency (it pulls in an entire kernel, SELinux, and
other fun stuff), and does not work at all in podman containers, so
let's get rid of this. Even if we want to put back subscriptions into
our images some day, this doesn't require libguestfs -- these can be
copied in the kickstart file instead.

 * [x] image-refresh rhel-8-0
 * [x] image-refresh fedora-30
 * [x] image-refresh centos-7

### CODE REVIEW

**Comment by martinpitt** [comment]
In theory this affects all images, but as it affects them all in the same way, I just triggered one virt-builder-fedora (centos-7), and a virt-install-fedora fedora+rhel (one that never had subscriptions, and one that did).

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-12543-20190811-192525/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-05.
Log: https://209.132.184.41:8493/logs/image-refresh-12543-20190811-192626/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-9.
Log: https://209.132.184.41:8493/logs/image-refresh-12543-20190811-192626/

**Comment by cockpituous** [comment]
image-refresh rhel-8-0 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-0-20190811-195050

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-12543-20190811-195050/

**Comment by cockpituous** [comment]
image-refresh fedora-30 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-30-20190811-204949

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://209.132.184.41:8493/logs/image-refresh-12543-20190811-195050/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-12543-20190811-205252/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-12543-20190811-205252/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-04.
Log: https://209.132.184.41:8493/logs/image-refresh-12543-20190812-054848/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-12543-20190812-054848/

**Comment by martinpitt** [comment]
Argh, I didn't realize that virt-builder is part of libguestfs. But there's only three images left that actually use it, it shouldn't be too hard to replace these. So let's dim down the description to just drop the leaked subscriptions.

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20190812-062828

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://209.132.184.41:8493/logs/image-refresh-12543-20190812-054848/

**Comment by martinpitt** [comment]
@henrywang : The 
[composer edge test](https://209.132.184.41:8493/logs/pull-12543-20190812-094949-d3f29828-weldr-cockpit-composer-fedora-30-edge/log) keeps failing in /root/end-to-end/specs/createUserAccount.test.js . Can you please have a look?

**Comment by martinpitt** [comment]
@henrywang : Apparently this was just a flake.

**Pull request merged**
