### PR TITLE
shell: Don't allow sub-minute steps in the dashboard plots.

### LINKED ISSUE #1762: Duplicate timestamps on dashboard graph?
duplicates of 17:56, 17:57 etc.
screenshot from 2015-01-30 17 59 20

Is this actually 17:56:00 and 17:56:30?

### PR DESCRIPTION
**Pull request by mvollmer**
Fixes #1762

### CODE REVIEW

**Comment by stefwalter** [comment]
@andreasn can you review this? It seems to needelessly add ```:00``` and ```:30``` noise all over the place. But maybe that's the intent?

**Comment by mvollmer** [comment]
> It seems to needelessly add :00 and :30 noise all over the place. But maybe that's the intent?

It should only add the seconds when the the ticks are less than a minute apart.

**Comment by andreasn** [comment]
screenshot from 2015-02-17 11 37 20

**Comment by andreasn** [comment]
12:30:30 is going to hurt us in slimmer resolutions, and also on the server page.
There are a couple of ways to fix this:
* Removing the hour mark - you end up with times like 12:30 as a shortform of 13:12:30. Really unclear
* Skip the 30-second labels and their lines - less precise, but the main job is to detect big disturbances in the force, so having it be harder to tell when within a minute something happended is probably ok.

**Comment by mvollmer** [comment]
> Skip the 30-second labels and their lines 

Alright, I'll do this.

**Pull request closed without merging**
