### PR TITLE
systemd, tools: Rename cockpit-motd to cockpit-issue

### PR DESCRIPTION
**Pull request by martinpitt**
This tool handles both dynamic /etc/issue and /etc/motd. We soon want to tone down the motd handling. As preparation, rename the script, systemd unit, and files to "issue". This gets the intrusive parts out of the way without changing the user experience yet.

Take care to adjust the existing links in /etc on package upgrades.

----

 - [x] manually test /etc symlink upgrade on Fedora
 - [x]  manually test /etc symlink upgrade on Debian

### CODE REVIEW

**Comment by martinpitt** [comment]
@jelly Does "real" Arch have the motd/issue links? I don't see any kind of "post-install" script in our tools/arch.

**Review by mvollmer — APPROVED** [review]
No issues, hurr hurr.

**Comment by jelly** [comment]
> @jelly Does "real" Arch have the motd/issue links? I don't see any kind of "post-install" script in our tools/arch.

No postinstall indeed, but locally I have:

```
/etc/issue.d/cockpit.issue -> ../../run/cockpit/motd
```

```
lrwxrwxrwx 1 root root 22 Nov 20 19:06 /etc/motd.d/cockpit -> ../../run/cockpit/motd
```

**Comment by martinpitt** [comment]
@jelly Right, in Debian and rpm the packaging removes the /etc/motd.d/ and /etc/issue.d links from `make install` and replaces them with dynamic postinstall code, for technical reasons (I can elaborate if you are interested, it's a bit complicated). With this version, the package will just ship new symlinks. Will upgrading the package take the new one, or are files in /etc "holy" and won't be upgraded? If you can test this, I'd appreciate -- otherwise I'm also happy to test, build the new arch package, and you tell me how to upgrade it on an existing arch image?

**Comment by martinpitt** [comment]
Tested on arch. Original issue with cockpit 329-1:
```
# ls -l /etc/motd.d/cockpit /etc/issue.d/cockpit.issue  /run/cockpit/
lrwxrwxrwx 1 root root  22 Nov 20 18:06 /etc/issue.d/cockpit.issue -> ../../run/cockpit/motd
lrwxrwxrwx 1 root root  22 Nov 20 18:06 /etc/motd.d/cockpit -> ../../run/cockpit/motd

/run/cockpit/:
total 4
-rw-r----- 1 root wheel  0 Dec  9 14:08 active.motd
-rw-r----- 1 root wheel 70 Nov 20 18:06 inactive.motd
lrwxrwxrwx 1 root root  13 Dec  9 14:08 motd -> inactive.motd
```

Then upgrading:
```
pacman -U /tmp/cockpit-330.dev36+ge04fc6285-1-x86_64.pkg.tar.zst
```

This correctly updates the symlinks (we don't clean the old files in /run):
```
ls -l /etc/motd.d/cockpit /etc/issue.d/cockpit.issue  /run/cockpit/
lrwxrwxrwx 1 root root  23 Dec  9 14:03 /etc/issue.d/cockpit.issue -> ../../run/cockpit/issue
lrwxrwxrwx 1 root root  23 Dec  9 14:03 /etc/motd.d/cockpit -> ../../run/cockpit/issue

/run/cockpit/:
total 8
-rw-r----- 1 root wheel  0 Dec  9 14:13 active.issue
-rw-r----- 1 root wheel  0 Dec  9 14:08 active.motd
-rw-r----- 1 root wheel 70 Dec  9 14:03 inactive.issue
-rw-r----- 1 root wheel 70 Nov 20 18:06 inactive.motd
lrwxrwxrwx 1 root root  14 Dec  9 14:13 issue -> inactive.issue
lrwxrwxrwx 1 root root  13 Dec  9 14:08 motd -> inactive.motd
```

after reboot I see the "Activate the web console" in the VM console (issue) and in ssh (motd).

So that works correctly :heavy_check_mark:

**Review by jelly — APPROVED** [review]
Seal of approval!

**Pull request merged**
