### PR TITLE
tests: Drop old and obsolete hacks

### PR DESCRIPTION
**Pull request by marusak**
Issues for them are resolved.

Really just quick grep, not tested at all, lets see what CI has to say. Very likely I'll need to roll back some of those.

### CODE REVIEW

**Comment by marusak** [comment]
First iteration, nothing interesting, [ubuntu-2004](https://logs.cockpit-project.org/logs/pull-14879-20201106-165415-4db319e7-ubuntu-2004/log.html) unhappy, [8.4](https://logs.cockpit-project.org/logs/pull-14879-20201106-175948-4db319e7-rhel-8-4/log.html) one failure as well as  [debian-testing](https://logs.cockpit-project.org/logs/pull-14879-20201106-165415-4db319e7-debian-testing/log.html). Seems not related. Spinning up all tests once again.

**Comment by marusak** [comment]
[2004](https://logs.cockpit-project.org/logs/pull-14879-20201106-192123-4db319e7-ubuntu-2004/log.html#230) was fine, so was [8.4](https://logs.cockpit-project.org/logs/pull-14879-20201106-192101-4db319e7-rhel-8-4/log.html) as well as [debian-testing](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-14879-20201106-192119-4db319e7-debian-testing/log.html).
Now failed [f-32](https://logs.cockpit-project.org/logs/pull-14879-20201106-192057-4db319e7-rhel-8-3-distropkg/log.html#312-2), [8-3](https://logs.cockpit-project.org/logs/pull-14879-20201107-131345-4db319e7-rhel-8-3/log.html#300) and [coreos[(https://logs.cockpit-project.org/logs/pull-14879-20201106-192103-4db319e7-fedora-coreos/log.html).

Once more, for now it all looks fine.

**Comment by marusak** [comment]
Seems all fine to me, ready for review :)

**Review by KKoukiou — APPROVED** [review]
Nice cleanup

**Pull request merged**
