### PR TITLE
Replace all PF3 Tooltips that are using the React Component with PF4

### PR DESCRIPTION
**Pull request by KKoukiou**
The workaround we were using for Tooltips to work with disabled buttons
does not work anymore.
Wrap disabled elements with a span when the these are children of a
tooltip.
See: https://github.com/patternfly/patternfly-react/issues/1894

### CODE REVIEW

**Comment by martinpitt** [comment]
They still look completely black to me:

tooltip


tooltip2

And more importantly, this makes them inconsistent with our remaining bootstrap tooltips, like on the accounts page:

tooltip-bootstrap

Can we override the style to be a bit translucent? In our  discussions with @garrett it actually seemed like the PF4 notifications were *intended* to have a gray/semi-translucent background, but for some reason they don't in Cockpit?

**Comment by KKoukiou** [comment]
> They still look completely black to me:
> 
> tooltip
> 
> tooltip2
> 
> And more importantly, this makes them inconsistent with our remaining bootstrap tooltips, like on the accounts page:
> 
> tooltip-bootstrap
> 
> Can we override the style to be a bit translucent? In our discussions with @garrett it actually seemed like the PF4 notifications were _intended_ to have a gray/semi-translucent background, but for some reason they don't in Cockpit?
> 
> Also, the font should be bigger.

They are completely black on PF4 documentation as well, nothing weird on our side. https://www.patternfly.org/v4/documentation/react/components/popover

I will make sure they are consistent all across cockpit definitely.

**Comment by garrett** [comment]
> In our discussions with @garrett it actually seemed like the PF4 notifications were intended to have a gray/semi-translucent background, but for some reason they don't in Cockpit?

Nope. This must be a misunderstanding. They're not translucent in the official PF4 docs.

I said something where we could override the opacity and also bump up the font size in a PF4 override. We can either do this temporarily, until all the tooltips are ported over, or it can be a Cockpit-specific thing.

Personally, I think the PF4 test is too small. That's one override we should definitely keep, and we should make the case that PF4 itself should update the size of the text (but not wait for the PF team to update).

For the opacity, there's definitely a case of being internally consistent until we drop the PF3 tooltips. Afterward, it's either being internally consistent with our own settings or consistent with other PF4 apps. 

(As tooltips are transient, I doubt anyone would notice if Cockpit is not exactly the same.)

Summary: At least for the time being, we should:
1. Bump up the font size
2. Match background opacity to the existing tooltips

**Comment by garrett** [comment]
Note: Popovers and tooltips are different things.

- Tooltips are transient and appear on hover
- Popovers are interactive widgets that show up on a click and can contain interactive widgets inside (and this may include copyable text)

Due to their different usages, they're styled differently.

**Comment by garrett** [comment]
It took me way too long (99% of the time just waiting on the computer), but I have figured out how to restyle the tooltips to have larger fonts (easy), similar opacity to existing tooltips (difficult), and discover that PF4 React does something different from HTML (very hard), and debug the transient tooltips (impossible level difficulty).

It's all in e6bb065.

**Comment by martinpitt** [comment]
Nice work, thanks @garrett! This makes them consistent enough with the bootstrap ones indeed.

The horizontal tips work well, but the vertical ones are pointing into the wrong direction:

tooltip-kdump

The second tooltip on the kdump page, as well as the "realm" label on the Overview page use the opposite direction and are also upside down.

Thus `tools/webpack-watch kdump` is an excellent tool for twiddling with this. 

With this patch, the arrows are correct:
```diff
--- pkg/lib/patternfly-4-overrides.scss
+++ pkg/lib/patternfly-4-overrides.scss
@@ -55,13 +55,13 @@
   // as the arrow is pointing to the opposite direction as stated
   // (so: up is down, left is right, etc.)
   &[data-placement=top],
-  &.pf-m-bottom { --arrow-direction: 3; }
+  &.pf-m-bottom { --arrow-direction: -1; }
 
   &[data-placement=right],
   &.pf-m-left { --arrow-direction: 1; }
 
   &[data-placement=bottom],
-  &.pf-m-top { --arrow-direction: -1; }
+  &.pf-m-top { --arrow-direction: 3; }
 
   &[data-placement=left],
   &.pf-m-right { --arrow-direction: -3; }

```

Left and right ones are used on the Services page and are correct.

So that plus fixing the tests → good to go! :tada:

**Comment by marusak** [comment]
tooltip-kdump

Is this our overwrite or is this official version? Asking as I find it rather difficult to read with that kind-of-too-much translucent popup background.

**Comment by martinpitt** [comment]
@marusak : That's the overwrite -- clearly as the arrow is wrong :)

**Comment by garrett** [comment]
> The horizontal tips work well, but the vertical ones are pointing into the wrong direction

Yeah, I didn't have the up/down arrows on the same place and wasn't sure where to see the tooltip. It took literal _hours_ of recompilation (as changing the overrides causes all of Cockpit to be rebuilt and the tooltips go away when you do anything but hover over the element, making it impossible to actually do in-browser changes, which means tweak and recompile again and again) to get to this point and I was already working late and wanted to push something, so I'm not surprised it's wrong.

**Comment by martinpitt** [comment]
Thanks @garrett! They look close enough now indeed. So now this needs:

 - [ ] adjust tests
 - [ ] squash the two CSS commits into one
 - [ ] add Closes #

I'm happy to help with the tests.

**Comment by martinpitt** [comment]
I think I fixed all test failures now. Pushing (also with rebasing) to get a fresh set of results.

I still want to finish the porting, as a parallel PR brought in one more instance:

    pkg/users/account-roles.js:import { OverlayTrigger, Tooltip } from 'patternfly-react';

**Comment by martinpitt** [comment]
Oh wow -- that went straight to (almost) green :partying_face: 

I pushed the porting of the accounts page.

**Comment by martinpitt** [comment]
I had a quick look at the `#dashboard-add` tooltip, and it's annoyingly non-trivial to fix that. It conflicts with the `update_privileged()` call which destroys the original tooltip.

**Pull request merged**
