### PR TITLE
kubernetes: Refactor create logic

### PR DESCRIPTION
**Pull request by stefwalter**
Refactor a KubernetesClient.create() function
    
This is a general function that tries to create any kind of item in the right namespace. This is refactored out of the deploy.js logic, so that it can be tested and reused.

### CODE REVIEW

**Comment by stefwalter** [comment]
@sub-mod This is the remaining work on the Deploy dialog, to make it testable.

**Comment by sub-mod** [comment]
@stefwalter thanks

**Comment by stefwalter** [comment]
Priority because blocking openshift connectivity.

**Comment by stefwalter** [comment]
Rebased.

**Comment by sub-mod** [comment]
@stefwalter what is the behaviour when k8 is not running ? Currently i see the spinner running for ever.

**Comment by stefwalter** [comment]
> what is the behaviour when k8 is not running ? Currently i see the spinner running for ever.

Thanks for catching that. There was an exception occuring. I've fixed this here so at least the error is shown. However there are more fixes for the display of the error in #2271

**Comment by sub-mod** [comment]
Namespaces are not updated when one tries to deploy an app in already created app.
Scenario:
1)deploy app with namespace aa
2)click on deploy button again 
3)cannot see aa in drop down.

**Comment by sub-mod** [comment]
screenshot from 2015-05-12 16-28-15
message should come after the alert icon.

**Comment by stefwalter** [comment]
Both of these are fixed in #2271

**Comment by sub-mod** [comment]
@stefwalter  LGTM

**Comment by stefwalter** [comment]
Thanks for the review. Merged into git master.

**Pull request closed without merging**
