### PR TITLE
bots: Unify rhel-7*.setup scripts

### PR DESCRIPTION
**Pull request by martinpitt**
rhel-7-4.setup contains mostly the same code as rhel-7.setup except for
the pre-installation of cockpit packages from base (the only difference
we are interested in) and some now obsolete noise. Conditionalize the
former on a new "image name" positional argument.
    
Change image-create to call the setup script with the destination image
name, so that it can do specific changes based on that. This will also
be useful to unify the fedora setup scripts later on.

----

This is similar to the existing factorization of `debian.setup`. After this I plan to do this for our plethora of `fedora*.setup` too, this will be a bit more involved as this has diverted more over time. With the new `$IMAGE` parameter we can also adjust this in the future to pin down the `rhel-7-4` image to 7.4 (not to "float over" to 7.5 once it exists), once we know exactly how to do that.

 * [x] image-refresh rhel-7
 * [x] image-refresh rhel-7-4

### CODE REVIEW

**Comment by stefwalter** [comment]
Bots won't touch a pull request that's marked WIP. We mark stuff WIP when we don't want or need anyone else getting involved ... that includes bots.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7479-20170810-115858/

**Comment by cockpituous** [comment]
image-refresh rhel-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-20170810-122323

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7479-20170810-135050/

**Comment by cockpituous** [comment]
image-refresh rhel-7-4 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-4-20170810-141717

**Pull request merged**
