### PR TITLE
Journal layout

### PR DESCRIPTION
**Pull request by dperpeet**
preliminary pull request without new features, just a side by side comparison of the journal layouts for easier review (don't merge!)

### CODE REVIEW

**Comment by andreasn** [comment]
apart from the notes above, the layout works really great!

**Comment by andreasn** [comment]
Avahi is awesome :)

screenshot from 2015-07-14 16-28-27

**Comment by stefwalter** [comment]
> Avahi is awesome :)

Can you report a bug in bugzilla.redhat.com that avahi is spamming logs based on network traffic? This could easily be a DOS or security issue to cause other logs to be rotated away by filling them up with silly messages about packets.

**Comment by andreasn** [comment]
Seems this started happening again.
screenshot from 2015-07-15 12-06-19

Probably need to increase .cockpit-log-message to calc(100%-300px)

**Comment by andreasn** [comment]
Storage looks a bit misaligned.
screenshot from 2015-07-15 12-08-45

**Comment by andreasn** [comment]
with .cockpit-logmsg-reboot margin-left: -45px; straightens it up a bit.

screenshot from 2015-07-15 12-11-57

**Comment by andreasn** [comment]
What error levels does the embedded journals pick up on?

**Comment by andreasn** [comment]
This is how it would look if .cockpit-log-warning was set to "none" in the embedded journals.

screenshot from 2015-07-15 12-34-52

**Comment by dperpeet** [comment]
> with .cockpit-logmsg-reboot margin-left: -45px; straightens it up a bit.

why would we want to align the "Reboot" message with the time field?

**Comment by dperpeet** [comment]
> This is how it would look if .cockpit-log-warning was set to "none" in the embedded journals.

The class is for the "column" - if there's an actual warning, that field will contain ``<i class="fa fa-exclamation-triangle"></i>``

**Comment by andreasn** [comment]
> why would we want to align the "Reboot" message with the time field?
To get it to align up nicely to the right, since it doesn't have a specific time, so that's it's entire message.

**Comment by dperpeet** [comment]
> To get it to align up nicely to the right, since it doesn't have a specific time, so that's it's entire message.

do you mean align on the left? I would consider this to be a message... but if you want it this way, I can change it

**Comment by andreasn** [comment]
> The class is for the "column" - if there's an actual warning, that field will contain <i class="fa fa-exclamation-triangle"></i>

Ah, ok. All mine was all empty, so I wondered if they didn't show at all. Lets keep this column then.

**Comment by andreasn** [comment]
> do you mean align on the left? I would consider this to be a message... but if you want it this way, I can change it

Yeah, probably best to change it. Sorry for going back and forth a bit on this, but I felt something had to be done about the alignment of these embedded journals.

**Comment by dperpeet** [comment]
> Yeah, probably best to change it. Sorry for going back and forth a bit on this, but I felt something had to be done about the alignment of these embedded journals.

this affects all journals, I'll change it so "Reboot" aligns with the time

**Comment by dperpeet** [comment]
all above issues are fixed/addressed

**Comment by andreasn** [comment]
Apart from the tiny issue above, all looks good now!

**Comment by dperpeet** [comment]
> While -moz-calc and -webkit-calc are 300px, it seems calc is still 290px

good catch, fixed!

**Comment by petervo** [comment]
The test failure is because you are requiring a system/journal.js, but you don't build a non debug version of journal.js. It's included with system/bundle.js but you aren't loading that on system/journal.html. So it's getting a not found and failing to load the JS.

**Pull request closed without merging**
