### PR TITLE
Image refresh for selenium

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for selenium

 * [x] image-refresh selenium

### CODE REVIEW

**Comment by martinpitt** [comment]
No tests triggered.. whoops, image-refresh is missing selenium triggers, I sent PR #12232 to fix that.

**Comment by martinpitt** [comment]
Still the same [chromium error](https://chromium.googlesource.com/chromium/src/+/851c021e01671de4dce737ddf65efa225e4f3a98), that still wasn't released.. what a shame!

**Comment by marusak** [comment]
Needs to rebase to master since #12367 changed tests names

**Comment by martinpitt** [comment]
Timed out long ago, let's build a new one.

**Pull request closed without merging**
