### PR TITLE
Image refresh for fedora-25

### PR DESCRIPTION
**Pull request by dperpeet**
Replaces #5072

### CODE REVIEW

**Comment by dperpeet** [comment]
once the tests have run, we need to see how many known issues are fixed

**Comment by dperpeet** [comment]
#5010, #5027 and #5041 are still happening

**Comment by mvollmer** [comment]
#5041 _should_ have been fixed, I think, but obviously hasn't.  I'll check.

**Comment by dperpeet** [comment]
> #5041 should have been fixed, I think, but obviously hasn't. I'll check.

Package selinux-policy-3.13.1-214.fc25.noarch is installed on the test image, that is supposed to fix the bug in #5041

**Comment by mvollmer** [comment]
(Trying out the new "rebase and merge" button.)

**Pull request merged**
