### PR TITLE
test: Add CentOS install script

### PR DESCRIPTION
**Pull request by stefwalter**
Otherwise the tests don't actually work.

### CODE REVIEW

**Comment by dperpeet** [comment]
You beat me to this.
Next we need to adapt the spec file - centos doesn't have a recent enough setroubleshoot-server.

**Comment by stefwalter** [comment]
I have a patch for that.

**Comment by stefwalter** [comment]
Priority since this is causing everything to be red.

**Comment by dperpeet** [comment]
openshift / kubernetes tests need to be skipped as well
A list of skips for rhel:
```
git grep "rhel" verify | grep -i "skip"
verify/check-kubernetes:@unittest.skipIf("rhel-7" == os.environ.get("TEST_OS", ""), "Skipping check-kubernetes on rhel-7.")
verify/check-kubernetes:@unittest.skipIf("rhel-7" == os.environ.get("TEST_OS", ""), "Skipping check-kubernetes on rhel-7.")
verify/check-kubernetes:@unittest.skipIf("rhel-7" == os.environ.get("TEST_OS", ""), "Skipping check-nulecule on rhel-7.")
verify/check-metrics:    @unittest.skipIf("rhel" in os.environ.get("TEST_OS", ""), "No PCP on RHEL.")
verify/check-openshift:@unittest.skipIf("rhel-7" == os.environ.get("TEST_OS", ""), "Skipping check-openshift on rhel-7.")
verify/check-openshift:@unittest.skipIf("rhel-7" == os.environ.get("TEST_OS", ""), "Skipping check-registry on rhel-7.")
verify/check-setroubleshoot:@unittest.skipIf("rhel" in os.environ.get("TEST_OS", ""), "DBUS API of setroubleshoot too old.")
verify/check-storage-iscsi:@unittest.skipIf("rhel-7" in os.environ.get("TEST_OS", ""), "No storaged-iscsi on RHEL-7.")
verify/check-subscriptions:@unittest.skipIf("rhel-7" != os.environ.get("TEST_OS", ""), "Only testing subscriptions on RHEL systems.")
verify/check-system-info:    @unittest.skipIf("rhel-7" == os.environ.get("TEST_OS", ""), "No NTP servers config on rhel-7.")
verify/check-system-info:    @unittest.skipIf("rhel-atomic" == os.environ.get("TEST_OS", ""), "No NTP servers config on rhel-atomic.")
```

**Comment by stefwalter** [comment]
Disabled those for now.

**Comment by stefwalter** [comment]
Needs more disabled

**Comment by stefwalter** [comment]
Enabled kubernetes and openshift tests on RHEL and CentOS. Tested running both of those locally here for both operating systems.

**Comment by stefwalter** [comment]
Accounting for NTP

**Comment by stefwalter** [comment]
Need to figure this out: 

teststorage-testlvm-fail

**Comment by stefwalter** [comment]
Accounted for changes in naughty file.

**Pull request closed without merging**
