### PR TITLE
base1: Bring on/off widget closer to the Patternfly styling

### PR DESCRIPTION
**Pull request by andreasn**
Our On/Off widget was looking a bit different from the patternfly
one. This commit fixes that.

### CODE REVIEW

**Comment by andreasn** [comment]
This is the patternfly widget for reference https://www.patternfly.org/widgets/#bootstrap-switch

**Comment by dperpeet** [comment]
By bring it closer, what is missing to get it there? Should it remain different from PatternFly now or is it pretty much the same? A screenshot might help.

**Comment by andreasn** [comment]
screenshot from 2016-05-30 16-46-07

Top to bottom:
 * Patternfly widget - bootstrap-switch.
 * Current cockpit on/off widget
 * Proposed cockpit on/off widget.

The differences between the Patternfly and the proposed one is the Off state and the little shadow. I was unable to get the shadow working, but I can fix the white off state.

**Comment by andreasn** [comment]
Made some more changes, so the widgets looks like this now:
screenshot from 2016-05-30 17-36-56

The last bit would be to have it switch state when clicked anywhere on the widget, but as far as I know, there is no good way of doing that.

**Comment by dperpeet** [comment]
> The last bit would be to have it switch state when clicked anywhere on the widget, but as far as I know, there is no good way of doing that.

I'm glad you said this. I just realized that this is how I implemented the switch in react - check out the selinux troubleshooting page for that.

Thanks for the screenshots, looks good!

**Pull request closed without merging**
