### PR TITLE
add container development env instructions

### PR DESCRIPTION
**Pull request by aweiteka**

### CODE REVIEW

**Comment by petervo** [comment]
We might want to move this to the readme here: https://github.com/cockpit-project/cockpit/blob/master/containers/kubernetes/README.md. As this is really only relevent to the kubernetes container atm, also don't want all the packages, maybe just kubernetes, base1, and shell.

**Comment by stefwalter** [comment]
Agree this should be moved into containers/README.md ... with a link in HACKING.md. Should I do that while merging?

**Comment by dperpeet** [comment]
> Agree this should be moved into containers/README.md ... with a link in HACKING.md. Should I do that while merging?

Sounds good, I agree.

**Comment by stefwalter** [comment]
Updated and merged into master.

**Pull request closed without merging**
