### PR TITLE
storage: Use decimal unit prefixes

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by dperpeet** [comment]
blocked on #3944

**Comment by mvollmer** [comment]
Size input needs to use decimal prefices as well.

**Comment by mvollmer** [comment]
> Size input needs to use decimal prefixes as well.

Done.

**Comment by stefwalter** [comment]
I'd suggest a modification to the integration tests here.

**Comment by mvollmer** [comment]
> I'd suggest a modification to the integration tests here. 

Done.

**Comment by mvollmer** [comment]
We will use IEC units for storage.

**Pull request closed without merging**
