### PR TITLE
test: Update run-tests to skip retry on check-image test

### PR DESCRIPTION
**Pull request by henrywang**
Image building test takes too long and most of time do not spend on testing but image building
Skip test file update retry

### CODE REVIEW

**Review by marusak — COMMENTED** [review]
This is getting out of hand. We can start to introduce names that will conflict in other projects. Like for example I can imagine that we could have `check-image` in cockpit-podman`.
Can we do this anyway smarter? That a test would declare it should not be retried?

**Comment by martinpitt** [comment]
Yes, I think we should use a decorator for this.

**Comment by Gundersanne** [comment]
Made a composer PR https://github.com/osbuild/cockpit-composer/pull/1118, which is blocked on https://github.com/cockpit-project/cockpit/pull/14680

**Comment by martinpitt** [comment]
Thanks @Gundersanne ! So this one is obsolete. I reviewed #14680, I think we can get this in today.

**Pull request closed without merging**
