### PR TITLE
Check for NPM dependency updates

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [ ] FAIL: npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```webpack.config.js:    "angular-route": "angular-route/angular-route.js",
```

**Comment by cockpituous** [comment]
npm-update in progress on cockpit-tests-6db07.
Log: http://fedorapeople.org/groups/cockpit/logs/npm-update-7312-20170718-064040/

**Comment by cockpituous** [comment]
npm-update angular-gettext done: https://github.com/cockpituous/cockpit/commits/npm-update-angular-gettext-20170718-064040

**Comment by cockpituous** [comment]
Task threw an exception: http://fedorapeople.org/groups/cockpit/logs/npm-update-7312-20170718-064040/

**Comment by cockpituous** [comment]
npm-update d3 done: https://github.com/cockpituous/cockpit/commits/npm-update-d3-20170718-064040

**Comment by cockpituous** [comment]
Task threw an exception: http://fedorapeople.org/groups/cockpit/logs/npm-update-7312-20170718-063939/

**Comment by martinpitt** [comment]
duplicate of #7311

**Pull request closed without merging**
