### PR TITLE
containers: Build and test containers on fedora-29

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh fedora-29
 * [x] image-refresh openshift

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-z8cd7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10539-20181108-202727/

**Comment by cockpituous** [comment]
image-refresh fedora-29 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-29-20181108-211919

**Comment by cockpituous** [comment]
image-refresh fedora-29 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-29-20181108-221313

**Comment by martinpitt** [comment]
[test failure](https://fedorapeople.org/groups/cockpit/logs/pull-10539-20181109-043939-25285956-container-kubernetes/log.html) looks like the cockpit/base container is fedora:28 based. Need to investigate, I flipped everything to fedora:29.

**Comment by martinpitt** [comment]
Oh right, need to rebuild the openshift image to rebuild its cockpit/base container for f-29.

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-j1ksw.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10539-20181109-085454/

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-20181109-091818

**Comment by martinpitt** [comment]
@Gundersanne: The two cockpit/* test jobs without a project are bogus. Not sure what's up with the collision in verify/ubuntu-stable, but this PR doesn't change anything that touches the Ubuntu image testing. So I think this is good enough.

**Pull request merged**
