### PR TITLE
base: Add react listing pattern component

### PR DESCRIPTION
**Pull request by dperpeet**
TODO
- [x] move listing pattern to base1
- [x] add provision for listing actions

### CODE REVIEW

**Comment by andreasn** [comment]
Looks good!
Only thing I would change is for the can't-navigate-one to turn get a gray background on hover, similar to how it gets a gray background when hovering the caret, to imply that the actions are the same, just with a bigger hit target.

**Comment by larsu** [comment]
Good work! Looks awesome so far.

You allow setting any cell to be a header. Do we really need that? I assume we either want a column to be all header items or no header items, and probably that column will always be the first one. How about adding a prop on `Listing` (`headerColumn` or so, which is the header column number or `-1`).

Passing in the columns as props is not very declarative. Can we make the rows children? I imagine something like this:

```jsx
    React.render(
        <Listing title="Demo Listing Pattern with expandable rows">
            <Row tab_renderers={tab_renderers} navigate_to_item={navigate_to_item.bind(this, 'frontend')}>
                <Cell header="true">standard</Cell>
                <Cell>aoeuaoeu</Cell>
                <Cell>127.30.168.10</Cell>
                <Cell>Running</Cell>
            </Row>
            <Row tab_renderers={tab_renderers} navigate_to_item={navigate_to_item.bind(this, 'frontend')}>
                <Cell header="true">can't navigate</Cell>
                <Cell>aoeuaoeu</Cell>
                <Cell>127.30.168.10</Cell>
                <Cell>Running</Cell>
            </Row>
        </Listing>);
```

We could also move `tab_renderers` out to the `Listing`, no? Do we ever ever rows with different items in the same listing?

React (and most of JavaScript) use mixedCamelCase property names. So does Crockford. I think we should use them as well.

**Comment by dperpeet** [comment]
> Passing in the columns as props is not very declarative. Can we make the rows children? I imagine something like this:

Indeed it's not - but (apart from the playground) we usually want to display data we get from somewhere else, no hardcoded tables. How would the children approach scale for a list of docker images or services?

**Comment by dperpeet** [comment]
> We could also move tab_renderers out to the Listing, no? Do we ever ever rows with different items in the same listing?

Then the listing would decide how each child renders... that feels anti-react patternlike to me. I could live with setting default tab renderers on the listing that automatically gets passed to the rows, but it feels clumsy. How would you design the row render call if the listing has the tab renderers?

**Comment by dperpeet** [comment]
> React (and most of JavaScript) use mixedCamelCase property names. So does Crockford. I think we should use them as well.

I have to admit I let that slip in when reviewing your terminal code. Most of cockpit uses underscore notation: https://github.com/cockpit-project/cockpit/wiki/Cockpit-Coding-Guidelines#jsstyle

We can agree to change property names, but I think everything else should remain the way it is (and maybe fixup the terminal code). Do you want to rewrite Cockpit?

**Comment by dperpeet** [comment]
blocked on #4305

**Comment by larsu** [comment]
> Indeed it's not - but (apart from the playground) we usually want to display data we get from somewhere else, no hardcoded tables. How would the children approach scale for a list of docker images or services?

You can put arrays as children similarly to props. It's pretty neat: 

```jsx
var rows = [
    <Row>
        <Cell>one</Cell>
        <Cell>two</Cell>
    </Row>,
    <Row>
        <Cell>one</Cell>
        <Cell>two</Cell>
    </Row>,
]

React.render(
    <Listing title="Demo Listing Pattern with expandable rows">
        {rows}
    </Listing>
);
```

**Comment by larsu** [comment]
> Then the listing would decide how each child renders... that feels anti-react patternlike to me. I could live with setting default tab renderers on the listing that automatically gets passed to the rows, but it feels clumsy. How would you design the row render call if the listing has the tab renderers?

Oh right, that's indeed not very good. We could put the property on the list anyway and make that the default. This way we keep flexible when we want to override a renderer, but don't need to specify them all the time in the 90% case when they're all the same. This should be possible with the `...` operator:

https://facebook.github.io/react/docs/transferring-props.html

**Comment by larsu** [comment]
>  We can agree to change property names, but I think everything else should remain the way it is (and maybe fixup the terminal code). Do you want to rewrite Cockpit?

No :)

This is unfortunate. Working with 3rd party libraries feels a bit jarring because of the mismatched conventions.

**Comment by dperpeet** [comment]
> You can put arrays as children similarly to props. It's pretty neat:

I added `{ this.props.children }` to the listing render method so the rows can be added either way.

**Comment by dperpeet** [comment]
> Oh right, that's indeed not very good. We could put the property on the list anyway and make that the default. This way we keep flexible when we want to override a renderer, but don't need to specify them all the time in the 90% case when they're all the same. This should be possible with the ... operator:

I know that operator (we extended react-lite to get this). The question remains: Where would you put this? The listing doesn't instantiate the children, they are passed either via props.entries or props.children. If the rows are generated, that's usually in a loop somewhere, so you put it in one place either way.

**Comment by larsu** [comment]
> I added { this.props.children } to the listing render method so the rows can be added either way.

You meant `entries`, right? Because I'd really like to see `this.props.children` in there instead of `this.props.entries`. I don't think passing components in props is a good approach. This case is perfect for `children`.

**Comment by dperpeet** [comment]
> You meant entries, right? Because I'd really like to see this.props.children in there instead of this.props.entries. I don't think passing components in props is a good approach. This case is perfect for children.

No, I do mean that I added `this.props.children` per your suggestion. React handles the children as a props entry, too, so the other case isn't really different. I haven't convinced myself to remove `entries` yet, I'll try it out and see if I like it.

**Comment by larsu** [comment]
> No, I do mean that I added this.props.children per your suggestion.

Oh, I was looking at an old diff then? Weird, I had just opened the page on github before commenting.

**Comment by dperpeet** [comment]
Reworked in consideration of all comments and discussions up to this point, rebased.

**Comment by larsu** [comment]
Good work, thanks!

**Pull request closed without merging**
