### PR TITLE
testlib: change approach for --sit and log captures, take two

### PR DESCRIPTION
**Pull request by martinpitt**
Commit 2cfcdacee ("Create attachments and sit before cleanup handlers") accomplished its goal by monkeypatching some deep internals of unittest.

Instead of trying to monkeypatch unittest, handle attachments and sit() from from tearDown(). It also gets called before cleanups, and we already have similar failure-checking code present there for us to use.

Update from Martin Pitt: The first attempt was reverted in commit 94369d95bee1 as it did not print tracebacks properly, which broke both `--sit` mode (not showing the error) and naughty matching (as they match on the traceback). To fix that, change the boolean checkSuccess() to getError() which returns traceback object if there was any error. tearDown() can use that to print the error before calling the cleanup handlers.

---

I tested this locally with `TEST_OS=centos-8-stream test/verify/check-storage-stratis TestStorageStratis.testEncrypted`, and I do get the traceback again, so it should match the naughty. I also intentionally broke a test and ran it with `--sit`, and it looks useful again.

### CODE REVIEW

**Comment by martinpitt** [comment]
[works](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18992-20230622-130504-669a54a4-centos-8-stream-storage/log.html)! Time to run the full test suite.

**Comment by martinpitt** [comment]
[single failed test](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18992-20230622-141833-5770d0e3-fedora-38-pybridge-networkingm/log.html#31) with [pixel noise](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18992-20230622-141833-5770d0e3-fedora-38-pybridge-networking/pixeldiff.html#TestTeam-testBasic-networking-team-settings-dialog-mobile). If you zoom in closely, there's a handful of red  pixels around the dialog's "X" close button. 

@mvollmer , I believe you looked at similar cases before. Chromium 114 may have made this a little more brittle, in another run I saw similar noise in other tests.  What do we do in these cases? Increase the allowed fuzz?

**Review by allisonkarlitskaya — APPROVED** [review]
Uh, looks great!  :sweat_smile:

I agree with the approach.  Thanks.

Random note: type annotations would be nice on new/changed code (like `getError()`.  We're going to have a heck of a job ahead of ourselves soon when we decide to turn those on...

**Comment by allisonkarlitskaya** [comment]
I tested this locally with

    pytest test/verify -n4

and it seems to be working.

**Pull request merged**
