### PR TITLE
WIP - build: Gather code coverage information

### PR DESCRIPTION
**Pull request by mvollmer**
Lot's of stuff to do still:
- [ ] Don't write a million .js.cov files, write just one.
- [ ] Make it all optional
- [ ] Make CSP work, maybe by filtering out the header in cdp-driver.
- [ ] Create a summary report at the end
- [ ] Have some npm script that makes a html report

### CODE REVIEW

**Comment by mvollmer** [comment]
To try this out:
```
$ ./bots/image-prepare --quick
$ ./test/verify/check-accounts
$ ./node_modules/.bin/istanbul report --include='*.js.cov' html
$ firefox ./coverage/index.html
```

**Comment by mvollmer** [comment]
Rebased, but note that all builds will fail since there is a HACK here re CSP that makes the unit tests fail.

**Comment by marusak** [comment]
Needs to rebase to master since #12367 changed tests names

**Comment by martinpitt** [comment]
@mvollmer: Is that something that you want to continue working on in the next weeks? Or should we close this for now?

**Comment by mvollmer** [comment]
> Is that something that you want to continue working on in the next weeks?

No.

**Pull request closed without merging**
