### PR TITLE
systemd: Rename "crypto policy" to "cryptographic policy"

### PR DESCRIPTION
**Pull request by Akshat2Jain**

### CODE REVIEW

**Comment by Akshat2Jain** [comment]
Hey @marusak, Can you review this?

**Review by marusak — DISMISSED** [review]
Thank you! (I think we need to update pixel tests so I am running tests now)

**Comment by marusak** [comment]
Official documentation is changing as well:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening#setting-up-system-wide-crypto-policies-in-the-web-console_using-the-system-wide-cryptographic-policies

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_systems_using_the_rhel_8_web_console/setting-up-system-wide-crypto-policies-in-the-web-console_system-management-using-the-rhel-8-web-console

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening#setting-up-system-wide-crypto-policies-in-the-web-console_using-the-system-wide-cryptographic-policies

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_systems_using_the_rhel_9_web_console/setting-up-system-wide-crypto-policies-in-the-web-console_system-management-using-the-rhel-9-web-console

**Comment by marusak** [comment]
@Akshat2Jain can you please update strings in tests as well?

**Comment by Akshat2Jain** [comment]
@martinpitt , I have changed the test. can you review it?

**Review by martinpitt — COMMENTED** [review]
Thank you! We have some CI infrastructure problem right now, so it's hard to get tests run to the end. But I'll deal with this.

This will also need a pixel update at least, but I'll deal with this (you can't do that bit anyway).

**Comment by Akshat2Jain** [comment]
> Thank you! We have some CI infrastructure problem right now, so it's hard to get tests run to the end. But I'll deal with this.
> 
> This will also need a pixel update at least, but I'll deal with this (you can't do that bit anyway).

Thanks!

**Comment by Akshat2Jain** [comment]
> @Akshat2Jain Yes -- please see the two failed (red) tests in https://cockpit-logs.us-east-1.linodeobjects.com/pull-18925-20230619-124755-85317d9a-rhel-9-3/log.html for where exactly to change the strings. Thanks!

How to run these tests?

**Comment by Akshat2Jain** [comment]
> @Akshat2Jain See https://github.com/cockpit-project/cockpit/blob/main/HACKING.md and https://github.com/cockpit-project/cockpit/blob/main/test/README.md

Yeah I have run these tests in my local machine but like how to see this https://cockpit-logs.us-east-1.linodeobjects.com/pull-18925-20230619-124755-85317d9a-rhel-9-3/log.html

**Review by martinpitt — DISMISSED** [review]

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
