### PR TITLE
bots: Extract more features from tests for machine learning

### PR DESCRIPTION
**Pull request by stefwalter**
Now we can track whether a particular cluster of test failures
corresponds to a praticularly named set of tests, or tracked known
issues, or contexts on which operating system is running.

I've pushed this as a standalone pull request so that folks working on analysis and visualization of the clustered data have something to work with. 

 * [x] learn-tests

### CODE REVIEW

**Comment by cockpituous** [comment]
learn-tests in progress on cockpit-tasks-mrr3b.
Log: http://fedorapeople.org/groups/cockpit/logs/learn-tests-9079-20180502-062828/

**Comment by cockpituous** [comment]
learn-tests in progress on cockpit-tasks-tbr3f.
Log: http://fedorapeople.org/groups/cockpit/logs/learn-tests-9079-20180502-110606/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
learn-tests in progress on cockpit-tasks-p00zq.
Log: http://fedorapeople.org/groups/cockpit/logs/learn-tests-9079-20180502-143333/

**Comment by martinpitt** [comment]
The tests ran. The failures are mostly around failing `image-download` which is not considered a flake. That's fair enough, as this was a recent regression due to the image stores becoming ENOSPC. So this looks good to go, and improves the situation a lot already. Thanks!

**Pull request closed without merging**
