### PR TITLE
lib: support 'pmcd' source in plot

### PR DESCRIPTION
**Pull request by ioguix**
Plot helper class is only supporting "internal" and "direct" source for metrics1 channel. A third source called "pcmd" exists and allows to query the pmcd daemon directly for metrics.

This patch adds "pmcd" as source in the Plot helper class.

- [x] Fix playground and add test: PR #11427

### CODE REVIEW

**Comment by martinpitt** [comment]
Thanks! Can this be tested somehow? It seems it's not being used by anything right now, so this is just dead code. I suggest adding some example usage to pkg/playground/plot.js, then it can be tested by check-metrics. Do you want to try this yourself? Maybe @Gundersanne can help out with this?

We don't currently seem to use playground/plot in our tests?

**Comment by ioguix** [comment]
@martinpitt, indeed, I was wondering how this could be tested as well. Thank you for the pointers.

In my dev topic, I need it to access postgresql metrics collected from `pmdapostgresql.python`. I suppose I could do it the hard way using `cockpit.metrics`, `cockpit.grid` and flot, but I haven't found sample code about this yet, I'm not that fluent with internal code yet and doc doesn't help as far as I can see.

I suppose we can test with same metrics than the one accessible though the "direct" source, so adding a second metric to the existing  one in the playground graph might do the trick. However, This might need to wait for the fix from @Gundersanne as the plot page is broken in the playground.

**Comment by martinpitt** [comment]
I mark this as blocked on PR #11427, which sets the groundwork here: fix the playground and add an initial test.

**Comment by martinpitt** [comment]
#11427 landed, so there's now a basic test for this on the playground.

**Comment by martinpitt** [comment]
Adding needswork for the test case. Can you please work with @Gundersanne to cover this? Thanks!

**Comment by Gundersanne** [comment]
Added a test: https://github.com/Gundersanne/cockpit/tree/pmcd-test

**Comment by martinpitt** [comment]
@Gundersanne: Thanks! Note you should be able to directly push to @ioguix 's branch here.

**Comment by ioguix** [comment]
I tested @Gundersanne patch.

After some issues on my side to run the tests correctly, Plot tests are working correctly on the vagrant VM (fedora 29) and on my local machine (Debian 10).

**Comment by Gundersanne** [comment]
@ioguix This looks good now.  Can you add the line "Closes #11425" to your commit's commit message? I'm happy to do it as well in case you prefer that.

**Pull request merged**
