### PR TITLE
Image refresh for rhel-7-7

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-7-7
 * [x] image-refresh rhel-7-7

### CODE REVIEW

**Comment by marusak** [comment]
```
Error downloading packages:
  systemd-devel-219-62.el7_6.9.x86_64: Caching enabled but no local cache of /var/lib/mock/epel-7-x86_64/root/var/cache/yum/updates/packages/systemd-devel-219-62.el7_6.9.x86_64.rpm from updates
```
fails always with this message. I thought it was just internet related, but seems like real issue.

**Comment by Gundersanne** [comment]
Honestly this sounds like an image-create failure. During `*.setup` the yum cache inside the mock shouldn't get cleared.

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-12787-20190917-090808/

**Comment by cockpituous** [comment]
image-refresh rhel-7-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-7-20190917-093636

**Comment by marusak** [comment]
@Gundersanne thanks, I triggered all needed tests, lets see :)

**Comment by marusak** [comment]
@Gundersanne nope, the same :(

**Pull request closed without merging**
