### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by marusak** [comment]
`FileNotFoundError: [Errno 2] No such file or directory: '/build/cockpit/bots/image-prepare': '/build/cockpit/bots/image-prepare'` are bots broken? I'll give it one more retry, just to see

**Comment by martinpitt** [comment]
@marusak: See PR #12105, perhaps I forgot some piece somewhere?

**Comment by martinpitt** [comment]
Oh, this branch was created in parallel, so it needs to be rebased to current master.

**Comment by martinpitt** [comment]
Rebased, should work better now.

**Comment by martinpitt** [comment]
The image is gone, so let's just re-do this.

**Pull request closed without merging**
