### PR TITLE
subscriptions: Avoid PackageKit when installing insights-client

### PR DESCRIPTION
**Pull request by mvollmer**
PackageKit is missing even more than the insights-client in a default
install.

### CODE REVIEW

**Comment by mvollmer** [comment]
This removes some nice features, such as announcing the download size and the list of additional packages that need to be installed. I don't think that matters much, especially since we didn't have those in the "Register" dialog to begin with, only in the "Connect" dialog.

**Comment by martinpitt** [comment]
Let's mention https://bugzilla.redhat.com/show_bug.cgi?id=1768917 in the commit message on merging.

**Comment by martinpitt** [comment]
[some failures](https://209.132.184.41:8493/logs/pull-13269-20191210-135050-72bc0ba2-cockpit-project-cockpit--rhel-7-8/log.html), retrying

**Comment by mvollmer** [comment]
Wow, did none of the existing tests need adjustment?

**Comment by martinpitt** [comment]
@mvollmer: Our tests avoid testing transient states like spinners, so no :)

**Pull request merged**
