### PR TITLE
WIP: debug non-working inject-nmi

### PR DESCRIPTION
**Pull request by mareklibra**
Debugging in progress, trying to find root cause of the issue mentioned in [1].
    
Findings:
    
  - `virsh inject-nmi` called directly on machine from `check-machines` (bypasing javascript) **works fine**
  - with recent changes, the flow reaches cockpit.spawn() reliably (logging proves that)
    
To simplify debugging, following temporar changes are made:
    
  - the `onSendNMI()` on-click handler calls LIBVIRT_PROVIDER.SENDNMI_VM() directly - to bypass redux middleware
  - to demonstrate the issue, I replaced `virsh` call by simple `touch` command (see SENDNMI_VM() in libvirt.es6)
  - cockpit.spawn() call is reached (based on logging)
  - the `touch` is not actually executed. **Why??**
    
`window.debugging='all'` is set (config.es6), showing that cockpit.spawn() hangs
  - `send control` is passed
  - no `recv control` is received
    
In addition to the hardcoded call simplification made just for debugging, I've further simplified middleware code around getVirtProvider() - no need for such complexity after avoiding external provider API.
    
[1] https://github.com/cockpit-project/cockpit/pull/6722

### CODE REVIEW

**Comment by mareklibra** [comment]
TL/DR; Even simple cockpit.spawn(['touch', '/tmp/touch_succeeded'], ...) hangs up

Any idea why?

**Comment by petervo** [comment]
@mareklibra 

When i run this i get

```
---- hardcoded NMI call  machines.js:4946:26
Libvirt.SENDNMI_VM(miq) called  machines.js:4004:10
-- SENDNMI_VM before cockpit.spawn  machines.js:26531:14
send control: {"payload":"stream","spawn":["touch","/tmp/touch_succeeded"],"err":"message","pty":true,"environ":["LC_ALL=C","VIRSH_DEBUG=0"],"command":"open","channel":"1:4!43","host":"localhost"}  cockpit.js:205:9
-- after cockpit.spawn()  machines.js:26564:14
recv control: {"command":"ready","channel":"1:4!43"}  cockpit.js:205:9
recv control: {"command":"done","channel":"1:4!43"}  cockpit.js:205:9
recv control: {"exit-status":0,"command":"close","channel":"1:4!43"}  cockpit.js:205:9
process closed: {"exit-status":0,"command":"close","channel":"1:4!43"}  cockpit.js:2697:13
-- touch always
````

**Comment by stefwalter** [comment]
I can reproduce here.

**Comment by stefwalter** [comment]
Oh my @mareklibra. Thanks for the reproducer. This helped me find the problem but I missed it for a long time.

This is caused by ```self.browser.wait()``` vs. wait() in the tests :S The global ```wait()``` function doesn't let the browser run while it waits. The use of redux exacerbates this since it delays actions and processes them in the main loop.

@petervo @martinpitt Should we just drop the global ```testlib.py``` ```wait()``` function? It has confusing behavior ... or perhaps just fall through to ```self.browser.wait()``` in ```wait()``` if ```self.browser``` is open and not None? Multiple people having spent hours on figuring this out is a sign that the functions are messed up.

**Comment by petervo** [comment]
Falling through to self.browser.wait seems like a good solution to me.

**Pull request closed without merging**
