### PR TITLE
test: Delete old ostree deployment after setup

### PR DESCRIPTION
**Pull request by petervo**

### CODE REVIEW

**Comment by petervo** [comment]
bot: Image refresh for fedora-atomic

**Comment by cockpituous** [comment]
Image creation for fedora-atomic in process on host37-rack09.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-atomic-ef1b4226acd0ebe266ab34a9025ba868e247a88c/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-fedora-atomic-ef1b4226acd0ebe266ab34a9025ba868e247a88c

**Comment by petervo** [comment]
Bot Image creation didn't work. Will try generating and uploading

**Comment by petervo** [comment]
This fixes the immediate issue. By deleting the old one before creating the new we free up enough space to make running out of space very unlikely.

I'd prefer to delete the old one in setup, that would also make the final atomic images smaller. However for that to work we'd need to run commands after the reboot as we can't delete the booted deployment. So we'd need to delete the deployment and run zero-disk.setup. We used to have a mechnism for running scripts post reboot in vm-create the comments make it sound like it's still there but @dperpeet removed it.

@dperpeet what were the reasons for removing it? Is it worth bringing that back?

**Pull request closed without merging**
