### PR TITLE
Get rid of webpack-jumpstart

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
TODO (after merging):
 - [ ] bring down the git repository: https://github.com/cockpit-project/cockpit-dist/
 - [ ] cockpit-project/bots#4552
 - [ ] remove the environment: https://github.com/cockpit-project/cockpit/settings/environments
 - [ ] remove webpack-jumpstart as a required run from branch protection rules: https://github.com/cockpit-project/cockpit/settings/branch_protection_rules/3810068

### CODE REVIEW

**Review by martinpitt — DISMISSED** [review]
:footprints: :fist_oncoming: Agreed, and this will give us some extra motivation to land esbuild soon :grin: 

FWIW, no-test would have been fine here.

**Comment by allisonkarlitskaya** [comment]
> FWIW, no-test would have been fine here.

I thought about this.

My logic:  This touches a fairly fundamental part of the build process, so I wasn't sure.  When I'm not sure, I default to better-safe-than-sorry.

**Comment by allisonkarlitskaya** [comment]
Missed a spot!

**Comment by allisonkarlitskaya** [comment]
:cry: goodbye, old friend

**Pull request merged**
