### PR TITLE
Image refresh for fedora-25

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-25
 * [x] image-refresh fedora-25

### CODE REVIEW

**Comment by martinpitt** [comment]
The three ABRT tests repeatedly fail, needs to be investigated.

**Comment by martinpitt** [comment]
The journal message is
```
Jul 05 15:51:39 f4 systemd-coredump[1368]: Process 1360 (sleep) of user 0 dumped core.
                                           
                                           Stack trace of thread 1360:
                                           #0  0x00007f94daa1e7b0 __nanosleep (libc.so.6)
                                           #1  0x000056383060f4cf rpl_nanosleep (sleep)
                                           #2  0x000056383060f330 xnanosleep (sleep)
                                           #3  0x000056383060c86d main (sleep)
                                           #4  0x00007f94da972401 __libc_start_main (libc.so.6)
                                           #5  0x000056383060c95a _start (sleep)
```
But the test searches for

        sel = "#journal-box .cockpit-logline .cockpit-log-message:contains('crashed in __nanosleep()')"

i. e. the "crashed in" is missing. This is a string that comes from ABRT, I can see it on our current F26 image:

    Jul 05 16:46:54 localhost.localdomain abrt-notification[1429]: Process 1379 (sleep) crashed in __nanosleep()

 But on this refreshed F25 image nor the current one that we have in master there is no abrt package, while on the current F25 image there still is. PR #6423 aka commit 36f2538e added it to the F26 image, but not to any other - but PR #6189 aka commit f0ffc99e079c514 lets the ABRT tests run on all Fedoras except for F26. It just didn't turn up as a failure as we don't regularly run tests on fedora-25 or fedora-testing. So we need to add the packages there too.

**Comment by martinpitt** [comment]
I provided a fix and rebuild in PR #7166. I'll close this once that lands, as otherwise the bots tend to immediately refresh again, in vain.

**Comment by martinpitt** [comment]
#7166 was a dead end, Fedora 25 just doesn't support this yet. So I just added a commit to blacklist the ABRT tests on fedora-{25,testing} as well.

**Comment by mvollmer** [comment]
> Fedora 25 just doesn't support this yet. So I just added a commit to blacklist the ABRT tests on fedora-{25,testing} as well.

Yes, thanks.  I missed this when merging the ABRT code, sorry.

**Pull request closed without merging**
