### PR TITLE
Fix some network test flakes

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by martinpitt** [comment]
We currently see these flaking a lot, like [here](https://logs.cockpit-project.org/logs/pull-13996-20200430-055921-ceef4d59-fedora-coreos/log.html), [here](https://logs.cockpit-project.org/logs/pull-13996-20200430-055925-ceef4d59-rhel-8-2/log.html), or [here](https://logs.cockpit-project.org/logs/pull-13996-20200430-055921-ceef4d59-debian-testing/log.html). Essentially every test run in CI has some, but I can't reproduce that locally so far.

**Comment by martinpitt** [comment]
This looks promising, not a single check-networking flake \o/. Re-pushing with updated commit message and the full OS range.

**Comment by martinpitt** [comment]
Hmm, I think it's a bit better, but  [still](https://logs.cockpit-project.org/logs/pull-14000-20200430-075150-94d58bd2-debian-stable/log.html#131) [a couple](https://logs.cockpit-project.org/logs/pull-14000-20200430-075150-94d58bd2-fedora-32/log.html#155) [of](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-14000-20200430-075150-94d58bd2-fedora-31/log.html#155) [flakes](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-14000-20200430-075150-94d58bd2-ubuntu-stable/log.html#153-1)

**Comment by martinpitt** [comment]
I found the bug in check-networking-vlan, which was one of the worst issues. Still looking at others.

**Comment by martinpitt** [comment]
Getting closer.. several failures of `testBondActive` [here](https://logs.cockpit-project.org/logs/pull-14000-20200430-102434-09e7cc15-debian-testing/log.html#3-2) or [here](https://logs.cockpit-project.org/logs/pull-14000-20200430-102434-09e7cc15-rhel-8-2/log.html), and [testBondNonDefaultSettings](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-14000-20200430-102434-09e7cc15-fedora-32/log.html#6-2) which is just general NM slowness again.

**Comment by martinpitt** [comment]
Amazing -- all tests (except for the still running f31) were green, and most of them had *zero retries*. The single retry is on [firefox](https://logs.cockpit-project.org/logs/pull-14000-20200430-153514-b24d6d9a-fedora-31-firefox/log.html#13) where it failed on `wait_for_iface()` right at the initialization. The new debugging kicked in, and shows that the interface is in fact up, just that our page doesn't show it; in fact, the HTML dump shows absolute no interface at all. But this is for another day...

**Comment by martinpitt** [comment]
[ubuntu-2004](https://logs.cockpit-project.org/logs/pull-14000-20200501-072621-8a5705c7-ubuntu-2004/log.html) failed again on the aforementioned bonding testNonDefaultSettings problem, I retry that one.

For the green tests, [fedora-32](https://logs.cockpit-project.org/logs/pull-14000-20200501-072632-8a5705c7-fedora-32/log.html#143) had retries due to issue #13821, and [debian-testing](https://logs.cockpit-project.org/logs/pull-14000-20200430-183301-8a5705c7-debian-testing/log.html#258) and -stable for the testBondActive mentioned above; all others had no retries. I'd like to address these in separate PRs, as this already makes tests significantly better, so let's land this.

**Comment by mvollmer** [comment]
Looks good, thanks for entering this dungeon!

**Comment by mvollmer** [comment]
https://logs.cockpit-project.org/logs/pull-14000-20200501-085633-8a5705c7-ubuntu-2004/log.html#261-2 looks related, unfortunately.

**Pull request merged**
