### PR TITLE
Adjust tests for services image refresh

### PR DESCRIPTION
**Pull request by martinpitt**
This needs to go in lockstep with https://github.com/cockpit-project/bots/pull/4885 . There's lots of red here for the changes which don't work on main (sorry, some are incompatible), I triggered them on `@bots#4885`.

### CODE REVIEW

**Comment by martinpitt** [comment]
To avoid landing this with so much red and ruining our test stats, we could do this: Someone (@jelly ?) reviews this, then lands #4885, and then I rebase/push this PR again so that we get a clean run. WDYT?

**Review by jelly — APPROVED** [review]

**Comment by martinpitt** [comment]
As discussed, I landed the bots change, and now force-pushed to have a clean test run.

**Comment by martinpitt** [comment]
Interesting, your approval is still valid, GitHub is clever enough to realize that it was just a rebase :+1:

**Comment by martinpitt** [comment]
[This test](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19611-20231115-213214-175ae070-fedora-39-firefox-networking/log.html#34) is 'orribly flaky. I can't reproduce it yet, but I'll have a look tomorrow. I'll land this anyway, as otherwise main is even more broken with the new services image.

**Pull request merged**
