### PR TITLE
Use Fedora 22 for the "ipa" flavor.

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
The image has been installed already, so this PR should be using it.

**Comment by stefwalter** [comment]
I can't tell if the disk size was increased. We need to make sure this happens to stop having the sporadic IPA failures.

**Comment by dperpeet** [comment]
info on the image:
image: ipa-fedora-22-x86_64.qcow2
file format: qcow2
virtual size: 4.0G (4294967296 bytes)
disk size: 1.7G

inspecting the filesystem yields the following info on blocks in /:
capacity 3,139,636 
used 1,389,720 (47%)
available 1,570,716

This should be plenty of free space!

**Comment by dperpeet** [comment]
This also replaces the last magic tarball image, so we can finally get rid of quite a bit of conditional code in testvm

**Comment by stefwalter** [comment]
We probably need 6G

**Pull request closed without merging**
