### PR TITLE
Cleanup distribution of Development and Build dependencies

### PR DESCRIPTION
**Pull request by stefwalter**
To make developers and packagers lives easier and more transparent lets cleanup the way we distribute development and build dependencies. 

 * Development dependencies is the Node.js javascript necessary to build Cockpit from raw sources. These are files in the ```node_modules``` directory. Cockpit does not depend on Node.js at runtime.
 * Build dependencies are also necessary during the build, but represent things that are built into Cockpit, such as jquery, or react. These are in the ```bower_components``` directory.

To be clear, none of these dependencies are necessary to build a release tarball. In a tarball we distribute pregenerated files, much like Bison, Yacc, or Flex generated C files are distributed. These pregenerated files live in the ```dist/``` directory of the tarball. One may run 'make clean' on an extracted release tarball to remove all these pregenerated files.

Neither ```node_modules``` or ```bower_components``` are checked into the git repo. They are populated from the network by ```autogen.sh``` when initializing the repo. One may also use the usual ```npm install``` and ```bower update``` commands to populate these directories.

In addition these development and build dependencies are distributed in an auxiliary ```cockpit-cache-$version.tar.xz``` tarball for packagers that wish to populate these directories without hitting the network.

### CODE REVIEW

**Comment by stefwalter** [comment]
Blocked on #5241

**Comment by dperpeet** [comment]
needs rebase

**Comment by dperpeet** [comment]
the commit messages sounds like this is a WIP

**Comment by stefwalter** [comment]
Blocked on https://github.com/cockpit-project/cockpit/pull/5284

**Comment by stefwalter** [comment]
Blocked on #5291

**Comment by stefwalter** [comment]
Needs work for the semaphore script to pass. Strange stuff is happening with POTFILES.in checks.

**Comment by dperpeet** [comment]
needs rebase

**Comment by stefwalter** [comment]
Need to change the container-terminal dependency version.

**Comment by stefwalter** [comment]
We want this for the next release ... marking as priority.

**Comment by mvollmer** [comment]
`lib/cockpit-components-tooltip.jsx` has been added in the meantime.  I think it also needs to be moved to `pkg/lib/`, right?

**Comment by stefwalter** [comment]
> lib/cockpit-components-tooltip.jsx has been added in the meantime. I think it also needs to be moved to pkg/lib/, right?

Yup. If that's the only change will you do it while merging? Or should I do that while merging, after your review? I can run 'make distcheck' to make sure things still work.

**Comment by mvollmer** [comment]
> If that's the only change will you do it while merging?

Yes.

**Pull request closed without merging**
