### PR TITLE
bots: Fix rpmlint script in fedora installs

### PR DESCRIPTION
**Pull request by Gundersanne**
First copy the the script into the chroot, then execute it.

### CODE REVIEW

**Comment by martinpitt** [comment]
Thanks! What error does that fix? From just the diff it seems that this should be by and large the same, running shell commands via stdin or via copying in a script?

**Comment by Gundersanne** [comment]
@martinpitt So the current approach doesn't work anymore on fedora-31, as there's some error happening with 

```
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
```

Running it non-interactively mitigates this.

**Comment by martinpitt** [comment]
Ah, makes sense, thanks! So that ioctl error went away, but it still fails:

```
====== rpmlint on srpm =====
sh: /usr/bin/python: No such file or directory
0 packages and 0 specfiles checked; 0 errors, 0 warnings.
(none): E: no installed packages by name /builddir/build/SRPMS/*.src.rpm

====== rpmlint binary rpms (advisory) =====
sh: /usr/bin/python: No such file or directory
0 packages and 0 specfiles checked; 0 errors, 0 warnings.
(none): E: no installed packages by name /builddir/build/RPMS/
```

Does that block landing Fedora 31? If so, it's fine to land, otherwise let's keep this open and fix it properly (I'm happy to have a look -- at first sight, rpmlint is missing a python2 dependency?)

**Comment by Gundersanne** [comment]
oh wow, I totally missed that. this does block fedora-31 but I can do it :)

**Pull request merged**
