### PR TITLE
Checkbox alignment v2

### PR DESCRIPTION
**Pull request by andreasn**
Builds on top of the work in issue #2276

### CODE REVIEW

**Comment by andreasn** [comment]
After:
screenshot from 2015-05-13 11-54-58

**Comment by dperpeet** [comment]
@andreasn vertical alignment looks a bit off ("Access" and "Lock Account")

The first entries in the first column appear to be centered vertically, whereas "Lock Account" is a bit higher up.

**Comment by stefwalter** [comment]
Split into two commits and fixed the quoting on the label attributes.

**Comment by andreasn** [comment]
> The first entries in the first column appear to be centered vertically, whereas "Lock Account" is a bit higher up.

I measured it in GIMP and "Lock Account" is actually one pixel higher up. Will fix in a separate pull request.

**Pull request closed without merging**
