### PR TITLE
storage: Sort tables first by category

### LINKED ISSUE #19747: storage: Table sorting is wrong
Tables should be sorted by category: physical, then virtual, then network. Within each category, sorting is alphabetically by ID.

### PR DESCRIPTION
**Pull request by mvollmer**
Fixes #19747

image

### CODE REVIEW

**Comment by mvollmer** [comment]
upps, iscsi is missing a category.

**Comment by mvollmer** [comment]
> upps, iscsi is missing a category.

fixed

**Comment by garrett** [comment]
Thanks for the quick changes!

I can't tell the difference here, as the sorting on my local system is coincidentally the same. (My laptop storage is rather simple: just local and NFS, and sometimes temporary.) 

image

Could you share a screenshot please? Thanks!

**Comment by mvollmer** [comment]
> Could you share a screenshot please? Thanks!

In the description now. This could be used for the release notes as well.

**Review by garrett — APPROVED** [review]
Thanks again for the quick changes!

**Pull request merged**
