### PR TITLE
Update login.html

### PR DESCRIPTION
**Pull request by NeftaliYagua**
Remove spaces, required for Webplate i10n

Captura desde 2023-12-13 22-46-59

### CODE REVIEW

**Comment by martinpitt** [comment]
Argh, that's a sad bug. Sad because all existing translations already look like this:
```
msgid "            Bypass browser check          "
msgstr "            ბრაუზერის შემოწმების გამოტოვება          "
```

i.e. they faithfully reproduce the spaces. I checked our source code and fortunately that's the only case. 

But let's fix this more robustly -- it may happen again in the future.  How about this:

```diff
--- pkg/lib/html2po.js
+++ pkg/lib/html2po.js
@@ -171,7 +171,7 @@ function extract(children) {
             str.push(node.data);
     });
 
-    return str.join("");
+    return str.join("").trim();
 }
 
```

That does the right thing in my quick test here. That said, it is fine to keep your commit as well for cleanliness. Can you please add a second one with the above change?

Also, please improve your commit messages; the short summary should describe the change more specifically, not just "Update foo". Perhaps something like "static: Avoid leading/trailing space on browser check message", and the detailed commit message then says that this makes localization easier.

Thanks!

**Comment by NeftaliYagua** [comment]
> ```
> msgid "            Bypass browser check          "
> msgstr "            ბრაუზერის შემოწმების გამოტოვება          "
> ```
> 
> es decir, reproducen fielmente los espacios. Revisé nuestro código fuente y afortunadamente ese es el único caso.
> 
> Pero solucionemos esto de manera más contundente: puede volver a suceder en el futuro. Qué tal esto:
> 
> ```diff
> --- pkg/lib/html2po.js
> +++ pkg/lib/html2po.js
> @@ -171,7 +171,7 @@ function extract(children) {
>              str.push(node.data);
>      });
>  
> -    return str.join("");
> +    return str.join("").trim();
>  }
>  
> ```
> 
> Eso hace lo correcto en mi prueba rápida aquí. Dicho esto, también está bien mantener su compromiso con la limpieza. ¿Puedes agregar un segundo con el cambio anterior?
> 
> Además, mejore sus mensajes de confirmación; el breve resumen debe describir el cambio de manera más específica, no solo "Actualizar foo". Quizás algo como "estático: evite los espacios iniciales/finales en el mensaje de verificación del navegador", y el mensaje de confirmación detallado diga que esto facilita la localización.
> 
> ¡Gracias!



> Argh, that's a sad bug. Sad because all existing translations already look like this:
> 
> ```
> msgid "            Bypass browser check          "
> msgstr "            ბრაუზერის შემოწმების გამოტოვება          "
> ```
> 
> i.e. they faithfully reproduce the spaces. I checked our source code and fortunately that's the only case.
> 
> But let's fix this more robustly -- it may happen again in the future. How about this:
> 
> ```diff
> --- pkg/lib/html2po.js
> +++ pkg/lib/html2po.js
> @@ -171,7 +171,7 @@ function extract(children) {
>              str.push(node.data);
>      });
>  
> -    return str.join("");
> +    return str.join("").trim();
>  }
>  
> ```
> 
> That does the right thing in my quick test here. That said, it is fine to keep your commit as well for cleanliness. Can you please add a second one with the above change?
> 
> Also, please improve your commit messages; the short summary should describe the change more specifically, not just "Update foo". Perhaps something like "static: Avoid leading/trailing space on browser check message", and the detailed commit message then says that this makes localization easier.
> 
> Thanks!

Correct the code, I undertake to correct the translation on the web board for each of the languages.

**Comment by NeftaliYagua** [comment]
> Argh, that's a sad bug. Sad because all existing translations already look like this:
> 
> ```
> msgid "            Bypass browser check          "
> msgstr "            ბრაუზერის შემოწმების გამოტოვება          "
> ```
> 
> i.e. they faithfully reproduce the spaces. I checked our source code and fortunately that's the only case.
> 
> But let's fix this more robustly -- it may happen again in the future. How about this:
> 
> ```diff
> --- pkg/lib/html2po.js
> +++ pkg/lib/html2po.js
> @@ -171,7 +171,7 @@ function extract(children) {
>              str.push(node.data);
>      });
>  
> -    return str.join("");
> +    return str.join("").trim();
>  }
>  
> ```
> 
> That does the right thing in my quick test here. That said, it is fine to keep your commit as well for cleanliness. Can you please add a second one with the above change?
> 
> Also, please improve your commit messages; the short summary should describe the change more specifically, not just "Update foo". Perhaps something like "static: Avoid leading/trailing space on browser check message", and the detailed commit message then says that this makes localization easier.
> 
> Thanks!

Correct the code, I undertake to correct the translation on the web board for each of the languages.

**Comment by martinpitt** [comment]
> Correct the code

Did you mean to push some update here? (Because you didn't).

**Comment by martinpitt** [comment]
@NeftaliYagua You closed this without explanation -- was this an accident, or you don't have time/motivation to work on this any more? I'm happy to pick this up, it's a good bug fix, thanks for spotting.

**Comment by martinpitt** [comment]
@NeftaliYagua I rescued your fix in #19779 and added an extra validation commit.

**Pull request closed without merging**
