### PR TITLE
DBG: testsuite-prepare -v

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
@martinpitt, this is a run with `testsuite-prepare -v`.  Maybe you can figure out from this why lintian doesn't fail here.

**Comment by martinpitt** [comment]
That doesn't seem to be the "right" kind of verbosity, or the test runners just behave differently wrt. showing stderr. The test output isn't helpful either, I'm afraid:
```
+ lintian /var/tmp/build-results/cockpit_0-1_amd64.changes
warning: the authors of lintian do not recommend running it with root privileges!
   dh_strip
```
I. e. it should at least show a bunch of `W:` warnings.

**Comment by martinpitt** [comment]
The `--verbose` flag is indeed triggering this: It gets passed to `testvm.py` `Machine.execute()`, which shovels the install script's stderr to its stderr only if verbosity is on.

The "W:" actually do appear in this log, just way later -- it seems there is some stdout/stderr buffering going on. Python already does its own (`PYTHONUNBUFFERED=x` might help), and production probably redirects stdout/err which moves from line to block buffering. Indeed I can reproduce this locally:
```
 test/verify/testsuite-prepare -v 2>&1 | cat
+ lintian /var/tmp/build-results/cockpit_0-1_amd64.changes
warning: the authors of lintian do not recommend running it with root privileges!
+ [ -n t ]
[... way later, after package install ...]
+ dpkg --install [...]
I: pbuilder-time-stamp: 1485955601
W: cockpit-system: new-package-should-close-itp-bug
```
So this is completely out of order (both lintian and pbuilder finish before dpkg --install).

I see two options here:
 * Make `Machine.execute()` print the executed process' stderr to its stderr also without `--verbose` (but still ignore it with `--quiet`); this is a bit intrusive, but might generally give us more useful debug output in logs everywhere.
 * Run `testsuite-prepare` with `--verbose` in GitHub CI.

**Comment by martinpitt** [comment]
I pushed a commit to PR #5827 which should improve this a lot already.

**Pull request closed without merging**
