### PR TITLE
test: Kubernetes not installed or installable on atomics

### PR DESCRIPTION
**Pull request by stefwalter**
The kubernetes and registry functiontality is not available
or installable on atomics. The way to use this functionality
is via a container.

That container is tested separately, so we shouldn't test this
other non-installable case on the atomics.

### CODE REVIEW

**Comment by stefwalter** [comment]
The ostree tests use cockpit-kubernetes as a test case ... lets fix that.

**Comment by petervo** [comment]
```kubernetes.setup``` should probably be removed from ```images/scripts/lib/atomic.setup```

On continuous atomic we are currently installing kubernetes using containers, and testing that way. Do we want to keep that setup and keep running those tests on at least that atomic? If not not we should probably remove all that install stuff from the repo.

**Comment by stefwalter** [comment]
Should we have the container/kubernetes tests test against the containerized kube setup? Or is that not worth it? 

The main thing: is that layering cockpit-kubernetes on top of Atomic itself is not something users are expected to do. At least not that I know of, and so we're spending time testing a non-real-world setup.

**Comment by petervo** [comment]
Ok, I'm fine removing those tests.

**Comment by stefwalter** [comment]
Rebuilt the continuous-atomic image.

**Pull request closed without merging**
