### PR TITLE
Strict Content-Security-Policy for docker package

### PR DESCRIPTION
**Pull request by stefwalter**
Does what it says on the tin. 

 * Add a fork of term.js that includes Content-Security-Policy support
 * Removes bootstrap-select usage from docker component.

### CODE REVIEW

**Comment by stefwalter** [comment]
Needs a bit more work to get everything in place.

**Comment by stefwalter** [comment]
Fixed tests.

**Comment by dperpeet** [comment]
why does this remove the less license if the package stays in bower as a requirement?

**Comment by stefwalter** [comment]
Added back less LICENSE which was accidentally removed.

**Pull request closed without merging**
