### PR TITLE
systemd: Rewrite serverTime et al in React

### PR DESCRIPTION
**Pull request by mvollmer**
- [x] #14202

### CODE REVIEW

**Comment by mvollmer** [comment]
The "NTP Servers" list now looks like this:
image

It's just a <table>... We might want to find something better.

**Comment by martinpitt** [comment]
#14202 landed, I force-pushed a (clean) rebase here.

**Comment by marusak** [comment]
Rebased, fix conflict, fixed test, tested manually. Now remembered it won't most likely work with  distropkg as it needs spacial cases. Will tweak that as well

**Comment by marusak** [comment]
Ha, nice!
Tests are failing a lot, but on [second](https://logs.cockpit-project.org/logs/pull-14174-20200618-123158-ee6d69be-fedora-32/log.html#296-2) or [third](https://logs.cockpit-project.org/logs/pull-14174-20200618-123158-ee6d69be-fedora-32/log.html#296-2) try! It shows that the tests are actually flaky, and the new retry logic helped to find it!

**Comment by marusak** [comment]
The flakyness is due to opening dialog for changing of time before "backend" (represented by `ServerTime`) is ready and thus the current timezone is set to `null`. This ideally would be adjusted in the code, so the dialog cannot be opened.

**Comment by marusak** [comment]
I am confused by this bug a bit.
When I disable the "time button" which opens the dialog until `server_time.get_time_zone()` is truth-y, it can wait for a bit, but correctly resolves. But when the `onClick` callback calls the same function it can sometimes get `undefined`. It seems like the API can change its mind over the time.

Simple hack would be to pass timezone information into the callback.

**Comment by martinpitt** [comment]
Thanks @mvollmer and @marusak ! I don't actually think it's a hack, it's a rather clean solution to avoid a TOCTOU race.

**Pull request merged**
