### PR TITLE
Vagrantfile: Add support for virtualbox

### PR DESCRIPTION
**Pull request by stefwalter**
It seems that the image we were using didn't have support for
virtualbox. Lets try and fix that.

Issue #3405

### CODE REVIEW

**Comment by stefwalter** [comment]
This seems to work but using 0.89 binaries with the current git checkout of Cockpit packages doesn't work. This is because of #3408

**Comment by stefwalter** [comment]
Getting this working properly is blocking on the 0.90 release

**Comment by stefwalter** [comment]
Actually this can be merged. Lets just not close #3405 until 0.90

**Comment by stefwalter** [comment]
All 4 test failures here have been accounted for: http://fedorapeople.org/groups/cockpit/logs/pull-3416-01f334a3-fedora-23/log.html

**Comment by stefwalter** [comment]
Ideally we would have someone with a Mac or Windows test this:

```
$ git clone https://github.com/cockpit-project/cockpit
$ cd cockpit
$ git fetch origin pull/3416/head
$ git checkout FETCH_HEAD
$ vagrant destroy
$ vagrant up
```

**Comment by smirnovigor** [comment]
I've tested on Mac, the vm is booted, but it failed on vagrant configuration setup. I'm getting following error:

```
NFS requires a host-only network to be created.
Please add a host-only network to the machine (with either DHCP or a
static IP) for NFS to work.
``` 

In case you use NFS, you should setup the private network. From [documentation](http://docs.vagrantup.com/v2/synced-folders/nfs.html):

```
If you're using the VirtualBox provider, you'll also need to make sure you have a private network set up. 
This is due to a limitation of VirtualBox's built-in networking.
``` 

After adding ``config.vm.network "private_network", ip: "192.168.50.10"`` to vagrantfile, cockpit was successful booted.

After login to the web console, I got error from cockpit.js:

```
Refused to connect to 'wss://localhost:9090/cockpit/socket' because it violates the following Content
Security Policy directive: "default-src 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'connect-src' was not
explicitly set, so 'default-src' is used as a fallback.
```

I don't know whether or not this error a result of my private network configuration, but is big progress to me to setup a cockpit on Mac.

**Comment by stefwalter** [comment]
> After adding config.vm.network "private_network", ip: "192.168.50.10" to vagrantfile, cockpit was successful booted.

Great will add this.

> Refused to connect to 'wss://localhost:9090/cockpit/socket' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

This is a bug in the current git master when used with cockpit 0.89 in the vagrant VM. Cockpit 0.90 should be released shortly and should work well with git master.

**Comment by smirnovigor** [comment]
I already checked master version and managed to run cockpit. It seems that pull 3416 has some web socket bug

**Comment by stefwalter** [comment]
Added the private network. Release 0.90 is happening now ... so the CSP stuff should work better after that.

**Comment by stefwalter** [comment]
0.90 has been released.

**Pull request closed without merging**
