### PR TITLE
shell: remove patternfly 3 *last* import

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Review by garrett — APPROVED** [review]
This looks great! Thanks!

**Comment by KKoukiou** [comment]
This is a bit blocked on some stupid pixel tests almost impossible to notice differences.

**Review by marusak — APPROVED** [review]
Awesome, thank you!

**Review by martinpitt — APPROVED** [review]
Thanks! The pixel diffs are very subtle indeed, I only saw a slight shift in the terminal one.

**Comment by martinpitt** [comment]
Note that there is one place left [here](https://github.com/KKoukiou/cockpit/blob/7c8c45c0008cf1b64485ce43d76799e0629e640e/pkg/shell/shell.html#L12):
```html
        <div class="blank-slate-pf-icon">
            <span class="fa fa-meh-o"></span>
        </div>
```
This icon will be broken now. It's very obscure, and I'm not even sure it's still relevant, and not having an icon there is certainly not a big deal. So it can certainly become a follow-up, without blocking the pixel tests.

**Comment by martinpitt** [comment]
I sent PR #16690 to clean up the above leftover.

**Pull request merged**
