### PR TITLE
Image refresh for fedora-31

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-31

 * [x] image-refresh fedora-31

### CODE REVIEW

**Comment by marusak** [comment]
testTime and testCreateTimer failed. The second one says that there is no `ntp`, first has problem with permissions. Seems like a real change in F31, I'll take a look.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-01.
Log: https://209.132.184.41:8493/logs/image-refresh-12837-20190918-073333/

**Comment by marusak** [comment]
package `ntp` is missing. I added it into list of packages we need to install. We use `ntp` directly in tests, but we test also that cockpit works just fine without `ntp`.

**Comment by cockpituous** [comment]
image-refresh fedora-31 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-31-20190918-081111

**Pull request merged**
