### PR TITLE
Corrected some german translations

### PR DESCRIPTION
**Pull request by julianmetza-asmi**

### CODE REVIEW

**Comment by marusak** [comment]
Thank you!
We use [weblate](https://translate.fedoraproject.org/projects/cockpit/master/) to manage our translations.
Since you already have the changes, weblate also supports `file upload` functionality which merges your changes into what is currently available there. If you are interested to upload it there, that would be awesome. If not, no worries, I'll gladly do that in your stead. (and if you give me your email address I can point you even as author).

**Comment by julianmetza-asmi** [comment]
Looks like i am not allowed to upload it, without being an author? You can add me via julian.metza@asmi.de <mailto:julian.metza@asmi.de> 

 

Some additinal questions:

Can you give me an estimate, how long it takes for the changes to be merge into ubuntu-18.04-mainstream and ubuntu-20.04-mainstream?

Whats the best way to participate in the development of cockpit-machines?

Do you know if there is a plugin in work to manage smb?

Whats the best way to publish a cockpit-plugin for APC-UPSes (using apcupsd/apcaccess)?

 

Mit freundlichen Grüßen,

Julian Metza

 



 

DURIA Supportcenter seit 1992.

Taunusstraße 19a

65760 Eschborn

Tel.: (069) 333412 Fax 3088188

E-Mail:  <mailto:julian.metza@asmi.de> julian.metza@asmi.de

 <http://www.asmi.de/> www.asmi.de

Ust.IdNr. DE 114314462

St.Nr. 04686701675

 

Von: Matej Marusak <notifications@github.com> 
Gesendet: Sonntag, 17. Mai 2020 12:52
An: cockpit-project/cockpit <cockpit@noreply.github.com>
Cc: julianmetza-asmi <julian.metza@asmi.de>; Author <author@noreply.github.com>
Betreff: Re: [cockpit-project/cockpit] Corrected some german translations (#14095)

 

Thank you!
We use weblate <https://translate.fedoraproject.org/projects/cockpit/master/>  to manage our translations.
Since you already have the changes, weblate also supports file upload functionality which merges your changes into what is currently available there. If you are interested to upload it there, that would be awesome. If not, no worries, I'll gladly do that in your stead. (and if you give me your email address I can point you even as author).

**Comment by marusak** [comment]
> Looks like i am not allowed to upload it, without being an author? You can add me via julian.metza@asmi.de <mailto:julian.metza@asmi.de>

I thought it was publicly available. Anyway, I'll upload it there.

> Can you give me an estimate, how long it takes for the changes to be merge into ubuntu-18.04-mainstream and ubuntu-20.04-mainstream?

We release every two weeks, next release with these changes will be on 27. May.
I am not sure about 18.04 if we still release there (I don't think so). It should be in 20.04 day after the release or so. I am not completely familiar with releasing into ubuntu/debian, but I think we release updates only to backports and not to mainstream? @martinpitt can you please correct me if I am talking nonsense here?

> Whats the best way to participate in the development of cockpit-machines?

cockpit-machines live in this repo - https://github.com/cockpit-project/cockpit/tree/master/pkg/machines
Contributions are always welcomed! If you have questions, the team talks on freenode #cockpit IRC channel, so feel free to join and we will be happy to have you involved.

> Do you know if there is a plugin in work to manage smb?

if `smb` stands for samba, then https://github.com/enira/cockpit-smb-plugin there is this plugin.

> Whats the best way to publish a cockpit-plugin for APC-UPSes (using apcupsd/apcaccess)?

What do you mean by "publish"?  You can use [starter-kit](https://github.com/cockpit-project/starter-kit/) to create a new plugin. Then releasing it into distribution is other thing. Every distro has different workflows, rules...

**Comment by marusak** [comment]
Updated in weblate, it was propagated into:
https://github.com/cockpit-project/cockpit-weblate/commit/3db874fd9f998b46b9525ab8eb84a16820cde618

**Pull request closed without merging**
