### PR TITLE
ws: Lower cache time-to-live to one day

### PR DESCRIPTION
**Pull request by martinpitt**
Treat `COCKPIT_WEB_RESPONSE_CACHE_FOREVER` as "one day". Otherwise, if
browsers actually would take the value literally (which they don't,
fortunately), we would never be able to clean up after responses with
wrong cache parameters. The most prominent case for this is #8610
(serving `po.js`).

### CODE REVIEW

**Comment by martinpitt** [comment]
The [packit/c8s failure](https://artifacts.dev.testing-farm.io/fe0e566a-ce5e-4bd0-b991-718a0ff430f9/) is unrelated, it started to happen this morning (broken c8s update?). We see it in other PRs as well, e.g. #17067

**Review by allisonkarlitskaya — COMMENTED** [review]
imho, our use of "public" here is questionable.  I'd rather we fold the number of possibilities to two (yes or no) and use "24h private" for the yes case.

**Comment by martinpitt** [comment]
@allisonkarlitskaya : Happy to do that. Follow-up, or do it in one commit?

**Comment by martinpitt** [comment]
Replaced by PR #17100. Agreed that it makes more sense to clean this up more thoroughy.

**Pull request closed without merging**
