### PR TITLE
machines: Improve the user's experience when installation is seperate from VM creation

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
@martinpitt I added release-blocker, they are pretty ugly bugs and I would like to get them fixed in this release.

**Review by martinpitt — APPROVED** [review]
Very nice, thanks a lot for attention to details! There are some check-machines flakes, retrying.

**Comment by KKoukiou** [comment]
Meh, seems like the https://logs.cockpit-project.org/logs/pull-15154-20210119-145441-ddb634c7-rhel-8-4-distropkg/log.html captured a really race condition. I know how to fix it (I think) but I will need to repost :/

**Review by martinpitt — APPROVED** [review]
Nice to fix an oops along the way \o/

**Comment by martinpitt** [comment]
This has a really hard time with getting [testAddDiskPool](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-15154-20210120-084422-fedec0d8-ubuntu-2004/log.html#269) to succeed :cry:

**Comment by KKoukiou** [comment]
> This has a really hard time with getting [testAddDiskDirPool](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-15154-20210120-084422-fedec0d8-ubuntu-2004/log.html#269) to succeed cry

Failed again :( I just can't reproduce it locally though, this is a bit annoying :unamused:

**Comment by martinpitt** [comment]
Ah, but at least ubuntu-stable succeeded now. @KKoukiou : Might take running several machines tests in a permanently running VM? But let's force this through for the release, and investigate in the next days.

**Comment by martinpitt** [comment]
I ran all check-machines tests on master on my machine, and `TestMachines.testAddDiskDirPool` several times (single and in parallel), and so far I could not reproduce our [top flake](https://images-frontdoor.apps.ocp.ci.centos.org/failure-stats.html).

But I don't have any luck with reproducing this failure with this branch on my machine either. Need to try it on the official infra.

**Comment by martinpitt** [comment]
I rebased this after landing #15182, the conflict was easy to fix.

**Comment by martinpitt** [comment]
Whoops, [rebase error](https://logs.cockpit-project.org/logs/pull-15154-20210120-183149-6e245f91-rhel-8-4/log.html#312)

**Comment by martinpitt** [comment]
Two simple conflicts after landing #15158, rebased.

**Comment by martinpitt** [comment]
One [testCreateUrlSource](https://logs.cockpit-project.org/logs/pull-15154-20210121-072506-82218719-rhel-8-4-distropkg/log.html#313) failure, which is a top flake on rhel-8-4-distropkg. Retrying.

**Comment by KKoukiou** [comment]
> One [testCreateUrlSource](https://logs.cockpit-project.org/logs/pull-15154-20210121-072506-82218719-rhel-8-4-distropkg/log.html#313) failure, which is a top flake on rhel-8-4-distropkg. Retrying.

It failed 4th time, it's really persistent but I can't reproduce locally. That's bad :/

**Comment by KKoukiou** [comment]
Wi looks it passed now https://logs.cockpit-project.org/logs/pull-15154-20210121-121105-980b7e66-rhel-8-4-distropkg/log.html

**Comment by martinpitt** [comment]
Nice, that looks a lot better! Still [two](https://logs.cockpit-project.org/logs/pull-15154-20210121-121106-980b7e66-centos-8-stream/log.html) [flakes](https://logs.cockpit-project.org/logs/pull-15154-20210121-121105-980b7e66-ubuntu-stable/log.html), but they are different now.

**Review by martinpitt — APPROVED** [review]
Yay, fully green!

**Pull request merged**
