### PR TITLE
network: Only disable on/off switch for unknown interfaces

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by stefwalter** [comment]
Is it possible to add something to the integration test for this?

**Comment by mvollmer** [comment]
> Is it possible to add something to the integration test for this?

Yes, I'll do that.

**Comment by mvollmer** [comment]
Priority because https://bugzilla.redhat.com/show_bug.cgi?id=1329954 is urgent.

**Comment by stefwalter** [comment]
Will be a part of 0.113

**Pull request closed without merging**
