### PR TITLE
machines: Remove status icons in VMs list

### PR DESCRIPTION
**Pull request by bond95**
Made simple removing of status icons in machines.
screenshot from 2017-08-31 16-18-59

### CODE REVIEW

**Comment by petervo** [comment]
@bond95 can you explain the reason for doing this?

@andreasn or @mareklibra thoughs?

**Comment by andreasn** [comment]
Thanks for the fix, @bond95 !
I'll try it out and do a review later today.

> can you explain the reason for doing this?

We use text-only labels for states pretty much everywhere else in Cockpit, so removing them makes things more consistent across the product.
I filed issue #7140 about it in July, and @mareklibra said he's OK with the change there.

**Comment by mareklibra** [comment]
right @andreasn , this PR is a response to it

**Comment by petervo** [comment]
@bond95, thanks added the issue number to the commit message and merged.

**Pull request closed without merging**
