### PR TITLE
Kubernetes Containers View

### PR DESCRIPTION
**Pull request by stefwalter**
Initial implementation of pods details view
    
https://github.com/cockpit-project/cockpit/wiki/Feature:-Kubernetes:-Containers-View

### CODE REVIEW

**Comment by stefwalter** [comment]
* Doesn't update sidebar
     * Shows all pods running, rather than limiting to selection
     * No tests.

**Comment by stefwalter** [comment]
Depends on #2344

**Comment by stefwalter** [comment]
Done implementation.

**Comment by stefwalter** [comment]
Depends on #2359

**Comment by stefwalter** [comment]
Rebased.

**Comment by stefwalter** [comment]
Rebased.

**Comment by mvollmer** [comment]
When switching between "Overview" and "Containers", I somtimes get this error message:

```
"Error: requests[body].close is not a function
close@https://f22:9090/cockpit/@localhost/kubernetes/client.js:1534:17
close_singleton@https://f22:9090/cockpit/@localhost/kubernetes/client.js:1352:25
close/<@https://f22:9090/cockpit/@localhost/kubernetes/graphs.js:277:17
close@https://f22:9090/cockpit/@localhost/kubernetes/graphs.js:276:13
close@https://f22:9090/cockpit/@localhost/kubernetes/graphs.js:504:17
.link/<@https://f22:9090/cockpit/@localhost/kubernetes/graphs.js:516:25
createEventHandler/eventHandler@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:3017:9
jqLiteRemoveData@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:2576:9
jqLiteDealoc@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:2527:7
jqLiteRemove@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:2718:18
JQLite.prototype[name]@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:3255:17
$AnimateProvider</this.$get</<.leave@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:4691:9
cleanupLastView@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:27095:38
update/clone<@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:27124:15
publicLinkFn@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:6959:29
createBoundTranscludeFn/boundTranscludeFn@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:7099:1
controllersBoundTransclude@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:7759:18
update@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:27117:25
$RootScopeProvider/this.$get</Scope.prototype.$broadcast@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:14723:15
commitRoute/<@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:26800:15
processQueue@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:13192:27
scheduleProcessQueue/<@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:13208:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:14404:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:14220:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:14509:13
$LocationProvider/this.$get</<@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:11367:13
createEventHandler/eventHandler@https://f22:9090/cockpit/@localhost/kubernetes/angular.js:3017:9
"1 angular.js:11610:17
consoleLog/<() angular.js:11610
<anonymous> app.js:283
$RootScopeProvider/this.$get</Scope.prototype.$broadcast() angular.js:14725
commitRoute/<() angular.js:26800
processQueue() angular.js:13192
scheduleProcessQueue/<() angular.js:13208
$RootScopeProvider/this.$get</Scope.prototype.$eval() angular.js:14404
$RootScopeProvider/this.$get</Scope.prototype.$digest() angular.js:14220
$RootScopeProvider/this.$get</Scope.prototype.$apply() angular.js:14509
$LocationProvider/this.$get</<() angular.js:11367
createEventHandler/eventHandler() angular.js:3017
```

**Comment by mvollmer** [comment]
details.css is not installed.

**Comment by mvollmer** [comment]
Random observation: when pods come and go, it is easy to get confused on that page.

It might look as if some details of a pod have changes, while in fact the box now represents a whole different pod.

**Comment by stefwalter** [comment]
> Random observation: when pods come and go, it is easy to get confused on that page.

Yes, that's interesting. I don't know what to do about this. @andreasn This is something we should discuss.

**Comment by stefwalter** [comment]
> Yes, that's interesting. I don't know what to do about this. @andreasn This is something we should discuss.

Maybe we should do a little animation on the boxes pods when they go away or appear. That way it'll be clear when it's happening.

**Comment by stefwalter** [comment]
> details.css is not installed.

Fixed.

> When switching between "Overview" and "Containers", I somtimes get this error message:

Fixed.

**Comment by stefwalter** [comment]
Fixed to actually make shells connect to right hosts.

**Comment by mvollmer** [comment]
Clicking on a link in a Service row will both open that link and switch to the details view for that row.

**Comment by mvollmer** [comment]
It would help me if the things on the Container page are labelled according to whether they are a pod, container, service, node, etc.

**Comment by stefwalter** [comment]
> It would help me if the things on the Container page are labelled according to whether they are a pod, container, service, node, etc.

There are no services or nodes on the "Containers" page. In the future we should have more details views, and I'd like to revisit how things are split out. For now this view is all about the containers ... the grouping into pods is not a focus (yet), even though it's there.

**Comment by stefwalter** [comment]
> Clicking on a link in a Service row will both open that link and switch to the details view for that row.

Thanks for catching that. Fixed.

**Comment by stefwalter** [comment]
r7 test failure is false positive.

**Pull request closed without merging**
