### PR TITLE
test: Change container names to avoid pulling

### PR DESCRIPTION
**Pull request by petervo**
Fix continuous-atomic to work without registry access. 

Blocked on https://github.com/projectatomic/atomic/pull/721

### CODE REVIEW

**Comment by petervo** [comment]
bot: Image refresh for continuous-atomic

**Comment by cockpituous** [comment]
Image creation for continuous-atomic in process on cockpit-10.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-continuous-atomic-32f40759b67273ea82ca122a2a0b6df47d148171/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-continuous-atomic-32f40759b67273ea82ca122a2a0b6df47d148171

**Comment by petervo** [comment]
Atomic patch was merged and is available in continuous-atomic.

**Pull request closed without merging**
