### PR TITLE
storaged: harmonize sizes of disks in storage dialogs

### PR DESCRIPTION
**Pull request by andreasn**
Make the list of disks in the storage dialogs the same size as the ones
in the network dialogs.

### CODE REVIEW

**Comment by dperpeet** [comment]
While you're at this, how should longer text behave here?
screenshot from 2016-02-12 09-23-56_raid_dialog

**Comment by dperpeet** [comment]
The lines sizes in the dialogs seem to fit now, but the top level lists ("Interfaces" vs. "Filesystems") have different line heights.

**Comment by dperpeet** [comment]
(accidental close)

**Comment by andreasn** [comment]
> While you're at this, how should longer text behave here?

Ellipsis the text I think. I'll create a fix for that.

**Pull request closed without merging**
