### PR TITLE
WIP - shell: Allow menu entry targets to include hashes

### PR DESCRIPTION
**Pull request by mvollmer**
- [ ] Integration test

### CODE REVIEW

**Comment by mvollmer** [comment]
This would be used by the menu entries for generic AppStream "service" components.  They could have entries like

```
{
   "tools": {
       "ui#/org.cockpit-project.mock.app-service": {
          "label": "Demo Service"
       }
   }
}
```

where "apps/ui.html" will construct a UI based on the data found in `/usr/share/metainfo/org.cockpit-project.mock.app-service.metainfo.xml`.

**Comment by mvollmer** [comment]
The plans have changed and we don't need this anymore for "services".  @petervo, what do you think, is this useful on its own?

**Comment by petervo** [comment]
It's a pretty simple change, and I'm not opposed, but if it's not needed then maybe lets wait until we have a use case for it before merging.

**Comment by mvollmer** [comment]
> It's a pretty simple change, and I'm not opposed, but if it's not needed then maybe lets wait until we have a use case for it before merging.

Agreed.

**Pull request closed without merging**
