### PR TITLE
test: Update openshift kubeconfig

### LINKED ISSUE #5968: logging into test openshift VM is refused: x509: certificate signed by unknown authority
I was going to get back to some openshift integration bugs, but it seems with some image refresh or cockpit code rework the instructions in `pkg/kubernetes/README.md` stopped working:
```
$ test/vm-run openshift  # works fine
$ cp ./test/verify/files/openshift.kubeconfig ~/.kube/config
$ kubectl get pods
Unable to connect to the server: x509: certificate signed by unknown authority
```
Similarly, the web UI at http://localhost:9090/kubernetes says "Couldn't connect to server: unknown-hostkey".

### PR DESCRIPTION
**Pull request by martinpitt**
Fixes #5968

### CODE REVIEW

**Comment by martinpitt** [comment]
Our tests obviously don't cover this, so can we land this without getting fully green?

**Comment by petervo** [comment]
Better to add a test for this to make sure it doesn't happen again. Pushed a commit here that does that. Feel free to merge after review and confirmation that the test does pass.

**Comment by martinpitt** [comment]
Nice one, thanks @petervo! This should at least prevent green test and thus merging the atomic image updates without updating the credentials. 👍

**Comment by dperpeet** [comment]
Adding priority because this fixes access to the test image and prevents future problems with the `openshift` image.

**Comment by martinpitt** [comment]
Remaining test failures are unrelated, and the new test passed everywhere.

**Pull request merged**
