### PR TITLE
 	package.json: Update angular package dependency 

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```pkg/kubernetes/styles/main.less:@import (less) "../../../node_modules/angular/angular-csp.css";
pkg/kubernetes/styles/registry.less:@import (less) "../../../node_modules/angular/angular-csp.css";
webpack.config.js:    "angular": "angular/angular.js",
```

**Comment by cockpituous** [comment]
npm-update in progress on cockpit-tests-lc632.
Log: http://fedorapeople.org/groups/cockpit/logs/npm-update-7263-20170715-063131/

**Comment by cockpituous** [comment]
npm-update react-lite done: https://github.com/cockpituous/cockpit/commits/npm-update-react-lite-20170715-063131

**Comment by cockpituous** [comment]
Task threw an exception: http://fedorapeople.org/groups/cockpit/logs/npm-update-7263-20170715-063131/

**Comment by cockpituous** [comment]
npm-update requirejs done: https://github.com/cockpituous/cockpit/commits/npm-update-requirejs-20170715-063232

**Comment by cockpituous** [comment]
Task threw an exception: http://fedorapeople.org/groups/cockpit/logs/npm-update-7263-20170715-063131/

**Comment by martinpitt** [comment]
@stefwalter: It seems three different bots tried to update three different dependencies here (angular, react-lite, and require), and apparently angular "won". Is that how it's currently intended to work (and we just run the bot often enough to keep up), or is there something to fix here?

**Comment by stefwalter** [comment]
@martinpitt Normally the bots check for conflict after 60 seconds of starting a task. However it's likely that the task took less than 60 seconds here. It also seemed to occur at a time when no other tasks were outstanding. 

In the end, the intent of the bots is to update a single dependency every 3 days. So the result here matches the intent, even though the conflict resolution between multiple bots ended up with a different outcome.

**Pull request merged**
