### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing
 * [x] fix NTP test race (PR #9693)

### CODE REVIEW

**Comment by stefwalter** [comment]
I see a verify strange failure under ```cockpit/fedora-28```

https://fedorapeople.org/groups/cockpit/logs/pull-9613-20180709-123939-33bc09ec-cockpit-fedora-28/log

```
http://fedorapeople.org/groups/cockpit/logs/pull-9613-20180709-123939-33bc09ec-cockpit-fedora-28/log
From https://github.com/cockpit-project/starter-kit
 * branch                master     -> FETCH_HEAD
From https://github.com/cockpit-project/starter-kit
 * branch                master     -> FETCH_HEAD
 * branch                master     -> FETCH_HEAD
Testing 33bc09ec1d0d8b4c494e61777476a07bf8c6dc8e for pull-9613-20180709-123939 with cockpit/fedora-28 on 109629126d72...
Rebasing onto test/master ...
First, rewinding head to replay your work on top of it...
Applying: tools: Add temporary python2 build dependency
.git/rebase-apply/patch:23460: trailing whitespace.
    
.git/rebase-apply/patch:24886: trailing whitespace.
A ```*``` challenge requests whatever credentials the parent process has. Most auth commands will want to begin by issuing a ```*``` challenge. 
.git/rebase-apply/patch:44347: trailing whitespace.
    
.git/rebase-apply/patch:49463: space before tab in indent.
      	    "volumes": [{
.git/rebase-apply/patch:57605: trailing whitespace.
      
warning: squelched 88 whitespace errors
warning: 93 lines add whitespace errors.
error: Failed to merge in the changes.
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
Auto-merging webpack.config.js
CONFLICT (add/add): Merge conflict in webpack.config.js
Auto-merging po/po2json
CONFLICT (add/add): Merge conflict in po/po2json
Auto-merging po/po.empty.js
CONFLICT (add/add): Merge conflict in po/po.empty.js
Auto-merging po/de.po
CONFLICT (add/add): Merge conflict in po/de.po
Auto-merging package.json
CONFLICT (add/add): Merge conflict in package.json
Auto-merging Vagrantfile
CONFLICT (add/add): Merge conflict in Vagrantfile
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
Auto-merging .travis.yml
CONFLICT (add/add): Merge conflict in .travis.yml
Auto-merging .gitignore
CONFLICT (add/add): Merge conflict in .gitignore
Auto-merging .eslintrc.json
CONFLICT (add/add): Merge conflict in .eslintrc.json
Patch failed at 0001 tools: Add temporary python2 build dependency
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

Traceback (most recent call last):
  File "bots/tests-invoke", line 180, in rebase
    subprocess.check_call([ "git", "rebase", remote_base ])
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'rebase', 'test/master']' returned non-zero exit status 128.
```

**Comment by martinpitt** [comment]
I'm debugging the timesyncd regressions. Apparently booting hangs for quite a while on NetworkManager-wait-online.service, blocking later things like network-online.target, exim, multi-user.target. After it times out, NTP sync starts properly. NM is waiting (in vain) for getting a connection on eth1:
```
# nmcli d
DEVICE      TYPE      STATE                                  CONNECTION         
docker0     bridge    connected                              docker0            
virbr0      bridge    connected                              virbr0             
eth1        ethernet  connecting (getting IP configuration)  Wired connection 1 
eth0        ethernet  unmanaged                              --                 
lo          loopback  unmanaged                              --                 
virbr0-nic  tun       unmanaged                              --              
```
On top of that, after network-online.target, exim4.service takes a lot of time to start up, presumably also because it does not have an internet connection.

However, all these already the case on the current debian-testing image. Still, disabling and re-enabling NTP will have to wait for these pending jobs to finish, as these systemd transactions get serialized. So apparently we've just been lucky before.

So in the end I think this is all just a red herring. Apparently the property just needs a few seconds until it actually changes, maybe that's either an architectural change of systemd 239 or just a timing difference.

**Comment by martinpitt** [comment]
> I see a verify strange failure under cockpit/fedora-28

@stefwalter : Yes, this was an intermediate broken test from #9617, please ignore (see that PR for details). I'll soon force-push this PR to fix the debian-testing refresh, then this noise will disappear.

**Comment by martinpitt** [comment]
I pushed a fix for two of the regressions. The [testTimeServers](https://fedorapeople.org/groups/cockpit/logs/pull-9613-20180709-055050-33bc09ec-verify-debian-testing/log.html#196) failure still evades me, though, that needs some deeper debugging.

**Comment by martinpitt** [comment]
#9693 landed, and this image is almost two weeks old. Let's build a fresh one, and see what's left.

**Pull request closed without merging**
