### PR TITLE
bots: Use OS specific containers as cockpit/ws base

### PR DESCRIPTION
**Pull request by petervo**
Instead of using the one from dockerhub that doesn't match the rpm that gets installed inside.

This will need regenerated images, but will wait on feedback before triggering the builds.

 * [x] image-refresh fedora-atomic
 * [x] image-refresh rhel-atomic

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-1mhwh.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170809-171818/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170809-171818/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-9gmd4.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170809-173939/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170809-173939/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170809-180707/

**Comment by cockpituous** [comment]
image-refresh rhel-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-atomic-20170809-183131

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-64b10.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170809-184040/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-9kgxz.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170809-184040/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170809-184040/

**Comment by stefwalter** [comment]
This commit needs to be added  c3a4c141ba7ec71578b5c5ca54a1b403c436cd77

**Comment by petervo** [comment]
@stefwalter is the failure here, https://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170809-184040/log, something you've seen before.

**Comment by stefwalter** [comment]
The failure is:

```
+ ostree checkout fedora-atomic:fedora-atomic/25/x86_64/updates/docker-host /var/local-tree
error: Refspec 'fedora-atomic:fedora-atomic/25/x86_64/updates/docker-host' not found
image-create: setup failed with code 1
```

Either we fix the failure or fix #7444 and merge that first, which should fix this failure.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-25j81.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170809-233131/

**Comment by cockpituous** [comment]
image-refresh fedora-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-atomic-20170809-234646

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-l68xd.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170810-013434/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-xst7t.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170810-013434/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170810-013434/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-86zpl.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170810-014949/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170810-014949/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170810-042626/

**Comment by cockpituous** [comment]
image-refresh rhel-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-atomic-20170810-044848

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-l68xd.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170810-200909/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170810-200909/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170810-205353/

**Comment by cockpituous** [comment]
image-refresh rhel-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-atomic-20170810-211515

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-f4xdx.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170810-214444/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170810-214444/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-64b10.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170810-223333/

**Comment by cockpituous** [comment]
image-refresh fedora-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-atomic-20170810-225151

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170810-234747/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7464-20170811-004141/

**Comment by cockpituous** [comment]
image-refresh rhel-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-atomic-20170811-010303

**Pull request closed without merging**
