### PR TITLE
accounts: Update tooltip

### LINKED ISSUE #10104: Accounts page has wrong popups
The tooltip bubbles on Accounts are the standard black browser ones, not our usual semi-transparent bootstrap ones:

accounts-notifications

### PR DESCRIPTION
**Pull request by leomoty**
Hey @martinpitt, first of all, the updated HACKING.md works. Secondly, this should fix #10104.

### CODE REVIEW

**Comment by martinpitt** [comment]
Thanks! This is a good start indeed, but the placement is off:

accounts-notifications

They are usually centered on the element they get placed at, and the surrounding `<div>` is just that wide.

If the popup doesn't work on the `<label>`, then wrap that into a `<span>` that gets the tooltip. I tried to fiddle around with this for a while, but for some reason then the tooltip doesn't appear. It's likely that you have to call `.tooltip()` on the element, to get the bootstrap tool tip to set up properly?

**Comment by leomoty** [comment]
I will update it after work.

**Comment by leomoty** [comment]
@martinpitt can you give me some help with the `.tooltip()` portion? `pkg/users/` only has `local.js`, that gets compiled to `dist/users/users.js` and it is not included in that iframe. Am I missing something?

Also reverted the tooltip to the `label`, it looks good except it is not being triggered right now. I was only able to do it by hand.

**Comment by leomoty** [comment]
@martinpitt I am not sure if edits trigger a notification, can you take another look?

**Comment by martinpitt** [comment]
@leomoty : Force-pushes indeed don't trigger a notification, so indeed send a comment to do that.

**Comment by martinpitt** [comment]
(will review/test tomorrow, just started the tests for now)

**Pull request merged**
