### PR TITLE
Rename the pkg/ directory to assets/

### PR DESCRIPTION
**Pull request by stefwalter**
The directory name 'assets' is a pretty standard nomenclature for where the web assets are stored. Although in Cockpit these files are the actual meat ... such a change allows people to dive right in and find what they're looking for.

The directory 'pkg' is used by golang projects for their Go packages, so this causes a bit of confusion.

### CODE REVIEW

**Comment by stefwalter** [comment]
I'm not completely sure about this pull request, but figured I'd see what other regular contributors to Cockpit think.

**Comment by dperpeet** [comment]
I like the idea that cockpit consists of valuable, little packages that are held together by some framework glue. I also agree, though, that `pkg` might imply dependencies.
What concerns me more is that we have `src`, but most actual content is delivered from `pkg`.

**Comment by stefwalter** [comment]
> What concerns me more is that we have src, but most actual content is delivered from pkg.

src is a typical directory for keeping C sources.

**Comment by stefwalter** [comment]
testBridge failure is #2916

**Comment by stefwalter** [comment]
Travis failure is Travis overloaded and timed out.

**Comment by petervo** [comment]
I agree that using pkg like go isn't ideal. Though I do like the implication of pkg everything in there is distinct packages. We could just use the long form packages. Or have base and shell be assets and rest in modules or plugins or something like that.

**Comment by stefwalter** [comment]
Rebased.

**Comment by mvollmer** [comment]
I think keeping our packages in `pkg/` is just fine, but I have no strong opinion.

**Comment by mvollmer** [comment]
One idea would be to move the packages into `src/`, as siblings of `bridge` etc, but that would make it harder to separate frontend from backend code.

**Comment by stefwalter** [comment]
Okay. Since this is a tumultuous change, without consensus lets leave it as is.

**Pull request closed without merging**
