### PR TITLE
playground: Give it a index page

### LINKED ISSUE #12847: Group all pages related to Cockpit development into one navigation entry
Cockpit keeps growing main navigation on the side for new developer-only features.

Instead of having a navigation item for every entry, there should be one called something like "Developer" or "Developer Playground".

All the pages that come from pkg/playground/ should be listed there.

Benefits:
1. We can have Cockpit feel closer to what we ship
2. Any developer-related videos or screenshot will be closer to what people will see, instead of having a bunch of debug entries

### PR DESCRIPTION
**Pull request by mvollmer**
Fixes #12847

### CODE REVIEW

**Comment by mvollmer** [comment]
As mentioned in #12847, we could additionally remove "Development" from the shell navigation entirely.  Typing "/playground" into the URL bar is something that developers can easily learn.

**Comment by garrett** [comment]
1. No padding
2. Links don't have the pointer cursor
3. Browser's back button needs to be pressed twice to go back
4. Perhaps we should group these into subsections?
5. Some of the names of the pages (in the links) are not very descriptive.

So I think 2 and 3 are related. In looking at the code, there are naked `<a>` tags. They don't have href, whereas they should. Is JavaScript being used by adding an event and then watching for the link or something? Why? HTML anchors are supposed to be used for links and the browser takes care of everything.

We should eventually merge all the UI patterns into one page. But that's out of scope of this PR.

**Comment by marusak** [comment]
Also tests are failing, because it expects some things that are not there anymore :)

**Comment by garrett** [comment]
I tried to figure out the link thing, but using `cockpit.jump` seems to be just fundamentally broken.

**Comment by mvollmer** [comment]
>  3. Browser's back button needs to be pressed twice to go back

I think that's a general problem with Cockpit navigation, see for example #1043.

> Is JavaScript being used by adding an event and then watching for the link or something? Why? HTML anchors are supposed to be used for links and the browser takes care of everything.

There is a `onclick` handler on the `a` element that calls `cockpit.jump`.  hrefs don't really work (as far as I know) for navigating between pages since each page is in their own iframe.  We don't want to change the content of a particular iframe, we want to make a different one visible.

**Comment by mvollmer** [comment]
> I tried to figure out the link thing, but using `cockpit.jump` seems to be just fundamentally broken.

In this case, or in general?

**Comment by garrett** [comment]
I meant in general. It has a bunch of issues.

It's more noticeable here as the CSS that makes the cursor correct isn't loaded. It appears to be in `lib/page.css` and also the legacy `cockpit.css`.

Does this not page not load the `page.css` file though? I see CSS variables in `:root {}` — and they're even loaded twice... so where are these coming from? Are they from PF4? Is PF4 loaded twice?

**Comment by garrett** [comment]
> I think that's a general problem with Cockpit navigation, see for example #1043.

It's probably due to cockpit.jump being problematic.

If we need to intercept, construct, and then visit links — why not just use `<a href="GENERATED_LINK_HERE">` instead?

I understand there are cases we might want to change pages without using a link or requiring someone to click on a link, but those should be the corner cases. For everything else, shouldn't we leverage what the browser does natively instead of trying to recreate it poorly?

**Comment by mvollmer** [comment]
> For everything else, shouldn't we leverage what the browser does natively instead of trying to recreate it poorly?

But does the Browser do natively what we want?  We want to switch between existing iframes (or create a new iframe and then switch to it).

**Comment by garrett** [comment]
> But does the Browser do natively what we want? We want to switch between existing iframes (or create a new iframe and then switch to it).

Yes?

I guess the create a new iframe part is probably the problematic part. But that could probably be done in the event before the link is followed.

**Comment by mvollmer** [comment]
> 2. Links don't have the pointer cursor

That's because the `a` element doesn't have a `href` attribute.

**Comment by garrett** [comment]
But `lib/page.css` and `cockpit.css` have `a { cursor: pointer; }`, meaning that we're not pulling in `lib/page.css` (or `cockpit.css`, but that's old and shouldn't be used, if I understand correctly).

**Comment by mvollmer** [comment]
> But `lib/page.css` and `cockpit.css` have `a { cursor: pointer; }`, meaning that we're not pulling in `lib/page.css` (or `cockpit.css`, but that's old and shouldn't be used, if I understand correctly).

Ah, yes, I forgot to include `index.css`.  Now it should work.

**Comment by mvollmer** [comment]
> Also tests are failing, because it expects some things that are not there anymore :)

Should be fixed now.  I have moved the "notifications" page stuff into the index page, since we need a shell menu entry to see the page status icon.

**Comment by garrett** [comment]
> Ah, yes, I forgot to include index.css. Now it should work.

...Where? I don't see it.

**Comment by garrett** [comment]
OK, the latest commit fixed it.

**Comment by garrett** [comment]
Another nice-to-have: Breadcrubs on the top of all sub-pages to get back to the main page.

**Comment by martinpitt** [comment]
It's a bit suspicious that all three semaphore tests fail on the same thing:

    FAIL: dist/base1/test-http.html 4 - returned right data, expected: {

I'm afraid this also needs adjustment. `make check TESTS=dist/base1/test-http.html` should be a quick way to reproduce.

**Comment by mvollmer** [comment]
> I'm afraid this also needs adjustment.

Right, that test uses `pkg/playground/manifest.json.in` as test data... it could use any other file, I guess...  Fixed now.

**Comment by mvollmer** [comment]
>     * New index page is using jQuery, should port to React.

Does it?  I have used the raw DOM API since the page is so simple.

>     * Playground sub-page on Playground page is confusing.

Yes, I agree.  That's our original playground before we started making new pages for specific things.
 
>     * The notification sender page is not indexed -- how to test the Notification receiver?

The index page is now the sender.  The sending page needs to have a menu entry so that we can see the status icon there.
 
>     * The "Packages" page seems obsolete, AFAIR we auto-reload the manifests for some time (but this requires more confirmation).

It is used by the tests.

**Comment by martinpitt** [comment]
> I have used the raw DOM API since the page is so simple.

Of course, sorry! I mis-read it this morning :)

> The index page is now the sender. 

Makes sense.

Thanks!

**Pull request merged**
