### PR TITLE
images: Add udisks2-lvm2 to debian-testing

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
This package was recently added to debian-testing.  Add it to our image
setup so that we can run some more of the tests there.

 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-xbsvd.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9006-20180418-103131/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-testing-20180418-105757

**Comment by martinpitt** [comment]
Looks like one of the [libvirt](https://fedorapeople.org/groups/cockpit/logs/pull-9006-20180418-125555-e3f8fe6c-verify-debian-testing/log.html#12) tests uncovered a new AppArmor profile regression, this needs to be investigated.

**Comment by allisonkarlitskaya** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testLibvirt (__main__.TestMachines)
#
ls: cannot access '/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_NESTED': No such file or directory
[0424/125928.626023:ERROR:gpu_process_transport_factory.cc(1009)] Lost UI shared context.
[0424/125928.627585:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
[0424/125928.627598:ERROR:service_manager.cc(890)] Failed to resolve service name: metrics

DevTools listening on ws://127.0.0.1:9822/devtools/browser/5384b1ee-c990-4c01-b6e4-569b8f2332e7
[0424/125928.851704:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib/chromium/swiftshader/libGLESv2.so: /usr/lib/chromium/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0424/125928.854986:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
[0424/125928.855003:ERROR:service_manager.cc(890)] Failed to resolve service name: metrics
[0424/125928.856325:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[0424/125928.962632:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib/chromium/swiftshader/libGLESv2.so: /usr/lib/chromium/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0424/125928.964713:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
[0424/125928.964728:ERROR:service_manager.cc(890)] Failed to resolve service name: metrics
[0424/125928.965259:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[0424/125929.066383:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib/chromium/swiftshader/libGLESv2.so: /usr/lib/chromium/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0424/125929.068181:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[0424/125929.068423:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
[0424/125929.068438:ERROR:service_manager.cc(890)] Failed to resolve service name: metrics
[0424/125929.068985:ERROR:service_manager_context.cc(219)] Attempting to run unsupported native service: /usr/lib/chromium/content_gpu.service
[0424/125929.141001:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib/chromium/swiftshader/libGLESv2.so: /usr/lib/chromium/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0424/125929.142892:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
[0424/125929.142904:ERROR:service_manager.cc(890)] Failed to resolve service name: metrics
[0424/125929.143384:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
Synchronizing state of libvirtd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable libvirtd
Removed /etc/systemd/system/sockets.target.wants/virtlockd.socket.
Removed /etc/systemd/system/sockets.target.wants/virtlogd.socket.
Synchronizing state of libvirtd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable libvirtd
Created symlink /etc/systemd/system/sockets.target.wants/virtlockd.socket -> /lib/systemd/system/virtlockd.socket.
Created symlink /etc/systemd/system/sockets.target.wants/virtlogd.socket -> /lib/systemd/system/virtlogd.socket.
Unexpected journal message 'audit: type=1400 audit(1524567576.724:40): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1197 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"'
Unexpected journal message 'audit: type=1400 audit(1524567586.808:41): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1295 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"'
Wrote JS log to TestMachines-testLibvirt-debian-testing-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachines-testLibvirt-debian-testing-127.0.0.2-2301-FAIL.log
Traceback (most recent call last):
  File "/home/lis/code/cockpit/test/common/testlib.py", line 665, in tearDown
    self.check_journal_messages()
  File "/home/lis/code/cockpit/test/common/testlib.py", line 817, in check_journal_messages
    raise Error(first)
Error: audit: type=1400 audit(1524567576.724:40): apparmor="DENIED" operation="signal" profile="/usr/sbin/libvirtd" pid=1197 comm="libvirtd" requested_mask="send" denied_mask="send" signal=hup peer="unconfined"

not ok 7 testLibvirt (__main__.TestMachines) # duration: 40s
Wrote screenshot to TestMachines-testLibvirt-debian-testing-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestMachines-testLibvirt-debian-testing-127.0.0.2-2301-FAIL.html
Wrote JS log to TestMachines-testLibvirt-debian-testing-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachines-testLibvirt-debian-testing-127.0.0.2-2301-FAIL.log
```
First occurrence: 2018-04-24T13:00:00.389853
Times recorded: 1
Latest occurrences:

- 2018-04-24T13:00:00.389853

**Pull request merged**
