### PR TITLE
Port some pages to PF4 modal

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
This has a lot of tests failing but other than that I believe it's ok.

**Comment by KKoukiou** [comment]
ah Close buttons don't work.

**Comment by marusak** [comment]
https://logs-https-cockpit.apps.ci.centos.org/logs/pull-14740-20201014-103335-c3dd9155-debian-stable/TestStoragePartitions-testSizeSlider-debian-stable-127.0.0.2-2201-FAIL.png

Is this suposted to happen?

**Comment by KKoukiou** [comment]
> https://logs-https-cockpit.apps.ci.centos.org/logs/pull-14740-20201014-103335-c3dd9155-debian-stable/TestStoragePartitions-testSizeSlider-debian-stable-127.0.0.2-2201-FAIL.png
> 
> Is this suposted to happen?

If you are talking about the slider value I realy don't know why it changes,
If you mean the width, I am trying to address it, locally it worked for some reason, I am debugging it.

**Comment by marusak** [comment]
> If you mean the width

Yeah, I meant the width :)

**Comment by KKoukiou** [comment]
@marusak the screenshots in chromium are showing full width dialog, though (again) locally they have limited width.
Do you want to check it in your environment just to make sure I am not alone here again? Danke!

**Comment by marusak** [comment]
I've tested this and here are some find:
1. Switch to limited mode dialog is too wide and in the middle of the page:
switchmodal
2. The X button in ^ does not close the dialog

(I am now building VM to also test that storage think, I don't have environment for that locally)

**Comment by marusak** [comment]
> Do you want to check it in your environment just to make sure I am not alone here again?

I neither can reproduce that storage one, but the switcher one is persistent across browsers. So when you figure out what is problem with that one, you maybe can check if the same problem is not in other places as well.

**Comment by marusak** [comment]
The switch to limited access dialog is still in the middle of the page :( Checked with cleaned up tree, firefox, chromium, different browser sizes also prepared F33 VM and the same behaviour. I am on commit 7fbe328b8

**Comment by KKoukiou** [comment]
> The switch to limited access dialog is still in the middle of the page :( Checked with cleaned up tree, firefox, chromium, different browser sizes also prepared F33 VM and the same behaviour. I am on commit [7fbe328](https://github.com/cockpit-project/cockpit/commit/7fbe328b8a157595dfe9316c8e3b1cd2483e53f3)

You are right - again :) That need PF 4.60.0 which I had installed locally, but it's not on the package.json.

**Review by marusak — DISMISSED** [review]
Nice, thanks!

**Comment by marusak** [comment]
[TestMachines.testCreateUrlSource](https://logs.cockpit-project.org/logs/pull-14740-20201019-082355-bb6ef843-ubuntu-stable/log.html#81) fails at 6 OSes. I wonder if it is broken on master or in this PR...
@KKoukiou could you please take a look? It is also machines tests, so you are the ideal person for this :laughing:

**Comment by marusak** [comment]
> TestMachines.testCreateUrlSource fails at 6 OSes. I wonder if it is broken on master or in this PR...

It is. Lets fix that ASAP out o this PR. Should be rather simple, we just need some non-EOL OS

**Comment by marusak** [comment]
Argh:
```
Conflicting files
pkg/lib/patternfly/patternfly-4-overrides.scss
```

Can you please rebase? But tests are good so it will lend right away. Thanks!

**Comment by marusak** [comment]
On firefox ` TestStoragePartitions.testSizeSlider` fails constantly and it happens in a dialog. I'll check tomorrow if I can reproduce locally.

**Comment by KKoukiou** [comment]
> On firefox ` TestStoragePartitions.testSizeSlider` fails constantly and it happens in a dialog. I'll check tomorrow if I can reproduce locally.


Oh, I saw this test failing in ALL Oses when I limited the width of the midals to 50% of the original. When I use max-width: somenumber[em] limitation it works, but aparently not on firefox. From what I had seen in the screenshots, it was expecting the value of the slider to be 25, and not 25.1 which the test expects. I really don't understand the logic of this test, but I am confident that this is the case here as well.

**Review by marusak — APPROVED** [review]

**Pull request merged**
