### PR TITLE
users: Fix conversation with passwd re "you have to wait longer"

### PR DESCRIPTION
**Pull request by mvollmer**
The conversation goes something like this:

    $ passwd
    Changing password for anton.
    Current password:
    You must wait longer to change your password
    Current Password:
    passwd: Authentication token manipulation error
    passwd: password unchanged

Note that there is a second "Current Password" prompt, and that it has
different capitalization.  Previously, we would miss that prompt, but
often enough the "\n" that was sent as a reaction to "You must wait
longer" would answer it.  But often not, since passwd very likely
drains its input before reading a password.

Also, we make sure that a timeout is shown with the intended error
message, and not "Your session has been terminated", which is
misleading.

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Thanks a lot for fixing this!

**Comment by martinpitt** [comment]
This seems to [fail](https://logs.cockpit-project.org/logs/pull-14681-20200929-165733-e9f0109d-centos-8-stream/log.html#4-2) on centos-8-stream at least.

**Comment by mvollmer** [comment]
> This seems to [fail](https://logs.cockpit-project.org/logs/pull-14681-20200929-165733-e9f0109d-centos-8-stream/log.html#4-2) on centos-8-stream at least.

This had to do how the buffering works.  Our code assumed to get each line delivered separately to the stream handler, but that wasn't guaranteed and wasn't true for centos-8-stream.

**Comment by mvollmer** [comment]
Yeah, our code for holding a conversation with a command line utility was a bit naive. It might be worthwhile to factor this out into a robust utility and use it across the pages.

**Comment by mvollmer** [comment]
(I don't think this needs to be a release blocker. This was unreliable for a long time in CI but hasn't caused much real harm apparently. No need to rush a fix.)

**Review by martinpitt — APPROVED** [review]
Yay, thank you!

**Pull request merged**
