### PR TITLE
A few changes split out from #15420

### PR DESCRIPTION
**Pull request by marusak**

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Dakujem!

**Comment by marusak** [comment]
> qemu-img: /tmp/_n811sa0.qcow2: Could not write qcow2 header: No space left on device

on `1-cockpit-11`

**Comment by martinpitt** [comment]
@marusak: Interesting -- our tasks containers have a 10 GB tmpfs on /tmp. In https://github.com/cockpit-project/cockpituous/pull/393 I made the /tmp/ clean up more aggressive, and indeed that task container is currently clean. So I can only imagine that there was a particularly expensive combination of parallel tests running that really did use up so much space on all the overlays (that'd be pretty ginormous, though..)

**Comment by marusak** [comment]
Hmm, again the same problem. This smells like something is wrong there.

**Comment by martinpitt** [comment]
Retrying, and I'm following the test run now. In virsh list and df I indeed see a VM which is really large:

```
 Id   Name                       State
------------------------------------------
 2    fedora-33-127.0.0.2-2201   running
 3    fedora-33-127.0.0.2-2301   running
 90   fedora-33-127.0.0.2-2601   running
 91   fedora-33-127.0.0.2-2401   running
 92   fedora-33-127.0.0.2-2501   running
 93   fedora-33-127.0.0.2-2502   running

580K    /tmp/1624xat2.qcow2
324K    /tmp/5jegb0yx.qcow2
39M     /tmp/6c7nb4od.qcow2
1.2G    /tmp/9uy8rr_9.qcow2
324K    /tmp/9vky1b1b.qcow2
6.1G    /tmp/xb_jbfkt.qcow2
7.2G    total
```

And after a while, with check-multi-machine:
```
 2     fedora-33-127.0.0.2-2201   running
 3     fedora-33-127.0.0.2-2301   running
 111   fedora-33-127.0.0.2-2401   running
 112   fedora-33-127.0.0.2-2402   running
 113   fedora-33-127.0.0.2-2403   running
 114   fedora-33-127.0.0.2-2601   running
 115   fedora-33-127.0.0.2-2602   running
 116   fedora-33-127.0.0.2-2603   running
 117   fedora-33-127.0.0.2-2501   running
 118   fedora-33-127.0.0.2-2502   running
 119   fedora-33-127.0.0.2-2503   running

38M     /tmp/0jn2gxz4.qcow2
39M     /tmp/58k299jh.qcow2
324K    /tmp/5nqkt7fa.qcow2
196K    /tmp/9n010aq6.qcow2
1.3G    /tmp/9uy8rr_9.qcow2
324K    /tmp/aei9d6jf.qcow2
39M     /tmp/aqs4tb9m.qcow2
72M     /tmp/m9ngrdqr.qcow2
39M     /tmp/rkvojhwg.qcow2
39M     /tmp/ulb91mnd.qcow2
6.1G    /tmp/xb_jbfkt.qcow2
7.6G    total
```

That big VM is our ND@0 machine, so it just keeps piling up stuff. The second biggest 9uy8rr_9 is ND@1.

So I think the best fix is to simply increase the size of /tmp, to adjust with current test growth. I sent https://github.com/cockpit-project/cockpituous/pull/398 to do that. Restarting now.

**Pull request merged**
