### PR TITLE
Fix  a11y eslint rules

### PR DESCRIPTION
**Pull request by marusak**

### CODE REVIEW

**Review by martinpitt — DISMISSED** [review]
Nice!

**Comment by marusak** [comment]
Hmm, buttons are now blue and not gray: https://logs.cockpit-project.org/logs/pull-16793-20220110-065937-630ab4f4-fedora-35/pixeldiff.html#TestServices-testBasic-text-filter-test

@garrett should they be gray or is blue correct as well? :thinking:

**Comment by marusak** [comment]
Ok, I've restyled our fake tabs to look like real tabs. Now it looks like this:
TestServices-testBasic-text-filter-test-pixels
before it looked like this:
TestServices-testBasic-text-filter-test-reference

Guidelines: https://www.patternfly.org/v4/components/tabs/design-guidelines

**Review by martinpitt — APPROVED** [review]
Nice, thank you!

**Pull request merged**
