### PR TITLE
Image refresh for continuous-atomic

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for continuous-atomic in process on cockpit-11.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-continuous-atomic-2017-05-13/

### CODE REVIEW

**Comment by martinpitt** [comment]
The actual image build seems to have succeeded, but the log doesn't contain "Saving" or "Uploading". I'm not sure what's wrong here; @stefwalter , do you happen to have an idea?

**Comment by stefwalter** [comment]
@martinpitt Not sure where you're seeing that. I see:

```
waiting for machine poweroff timed out
```

The upload doesn't seem to be invoked.

**Comment by martinpitt** [comment]
Oh, I missed that, thanks. Let's see if that was just a glitch or something systematic.

**Comment by martinpitt** [comment]
bot: Image refresh for continuous-atomic

**Comment by cockpituous** [comment]
Image creation for continuous-atomic in process on cockpit-tests-7xwpz.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-continuous-atomic-4d8636d9f6425502d600f1b13dd0f735f07cc21b/

**Comment by stefwalter** [comment]
Looks like the container disk ran out of space:

```
[stef@falcon verify]$ oc rsh cockpit-tests-7xwpz
df -h
sh-4.3$ df -h
Filesystem                                                                                          Size  Used Avail Use% Mounted on
/dev/mapper/docker-8:3-1075961678-3e7015482d556a7e5d77f3bee56e2c985fa0532f8f47d0557020e93ca102c2ba   10G   10G   20K 100% /
tmpfs                                                                                                63G     0   63G   0% /dev
tmpfs                                                                                                63G     0   63G   0% /sys/fs/cgroup
tmpfs                                                                                                63G   52K   63G   1% /secrets
/dev/sda3                                                                                           621G  103G  519G  17% /cache
shm                                                                                                  64M     0   64M   0% /dev/shm
tmpfs                                                                                                63G   16K   63G   1% /run/secrets/kubernetes.io/serviceaccount
```

**Comment by stefwalter** [comment]
We need to run ./vm-reset in pullimagetask.py

**Comment by stefwalter** [comment]
Disk space issue should be solved by #6554

**Comment by cockpituous** [comment]
Image creation aborted

**Comment by martinpitt** [comment]
bot: Image refresh for continuous-atomic

**Comment by cockpituous** [comment]
Image creation for continuous-atomic in process on cockpit-tests-wt7q3.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-continuous-atomic-4d8636d9f6425502d600f1b13dd0f735f07cc21b/

**Comment by cockpituous** [comment]
Image creation aborted

**Comment by stefwalter** [comment]
> Image creation aborted

Currently we're overloading the GitHub API. Looks like there's more work to do here. But I'd like to land a bunch of the other changes first. Too many open pull requests waiting for review.

**Pull request closed without merging**
