### PR TITLE
bridge: Finish making CockpitDBusJson handle multiple names

### PR DESCRIPTION
**Pull request by stefwalter**
This makes a CockpitDBusJson channel capable of talking to multiple DBus names. We do introspection, watching and rules per DBus name.
    
"name" fields are specified along with messages like "call" in order to direct that call to a specific name. If no "name" is specified, then the default "name" in the "open" message is used.

It is possible to specify no "name" in the open message, in which case a "name" must be specified along with messages like "call".

Depends on:

 * [x] #5468
 * [x] #5500

### CODE REVIEW

**Comment by stefwalter** [comment]
check-realms needs another fix.

**Comment by stefwalter** [comment]
The way that the networking page started failing here needs looking into.

**Comment by stefwalter** [comment]
Rebased and split pull request.

**Comment by mvollmer** [comment]
Can you motivate this a bit?  Why is this better than opening multiple channels?

**Comment by stefwalter** [comment]
> Can you motivate this a bit? Why is this better than opening multiple channels?

The motivation is secondary. This naturally follows from the idea of publishing interfaces on a DBus bus:

 1. If we publish an DBus interface, we make it available for calls from the entire bus, not just a single DBus name (ie: service).
 2. It doesn't "make sense" that the DBus client channel on which we publish a DBus interface is thought of as limited to a single DBus name.
 3. Therefore we change the concept: a DBus client channel is no longer limited to a single name ... rather it often has a "default" name to contact instead.

Additionally, this enables the concept of sharing a DBus client among multiple callers in the same page. I have later work which allows this to happen ... and is effective particularly for short lived uses of DBus.

**Comment by mvollmer** [comment]
> This naturally follows from the idea of publishing interfaces on a DBus bus

Thanks!

**Pull request merged**
