### PR TITLE
test: New "daily" scenario for dnf and udisks2 daily builds

### PR DESCRIPTION
**Pull request by mvollmer**
This extends and replaces the existing "dnf-copr" scenario.

- [x] https://github.com/storaged-project/libblockdev/pull/862
- [x] https://github.com/cockpit-project/cockpit/pull/18679
- [x] https://github.com/storaged-project/libblockdev/issues/880

### CODE REVIEW

**Comment by martinpitt** [comment]
"fatal error -- couldn't initialize XFS library", hmm.. Should these failures be handled as naughties? Or perhaps a separate `udisks-copr` scenario in `_manual`, so that you can run it for debugging, but it doesn't block image refreshes?

**Comment by martinpitt** [comment]
To unblock that awkward lockstep PR with bots, I suggest to only do the renaming in this PR, and then extend it to udisks in a separate one.

**Comment by mvollmer** [comment]
TestStorageStratis.testBasic should be fixed by https://github.com/storaged-project/libblockdev/pull/862, let's wait for that.

**Comment by mvollmer** [comment]
Hmm, testFormatCancel takes much longer to actually cancel... there might be something broken there.

**Comment by mvollmer** [comment]
> Hmm, testFormatCancel takes much longer to actually cancel... there might be something broken there.

Yes, mkfs.xfs is not actually cancelled anymore... Thus, the foramt runs to completion, which makes the cancel operation look slow. The test for "Unrecognized data" succeeds regardless because of a race: the udev info will change eventually to "xfs filesystem", but only very slowly.

**Comment by mvollmer** [comment]
> TestStorageStratis.testBasic should be fixed by [storaged-project/libblockdev#862](https://github.com/storaged-project/libblockdev/pull/862), let's wait for that.

It's fixed now.

**Comment by mvollmer** [comment]
Green!

**Comment by mvollmer** [comment]
The normal tests should run here as well, but it's not happening...

**Comment by martinpitt** [comment]
@mvollmer You may have triggered the manual test before a bot got around to `test-scan` this? Or it was a victim of yesterday's GitHub outage? I think you'll need to manually trigger the tests now (or just force-push).

The TF failures are some "over midnight" time zone confusion in our timer tests, and unrelated. (Retry, or if you force-push they shuold succeed)

**Comment by mvollmer** [comment]
> Or it was a victim of yesterday's GitHub outage?

I guess so, it pushed this twice yesterday with no effect.

**Comment by mvollmer** [comment]
Ah, pixels.

**Comment by mvollmer** [comment]
> Unlocking of encrypted stratis pools has regressed. I'll have a look.

https://github.com/stratis-storage/stratisd/issues/3324

Not sure what to do about this yet.

**Comment by mvollmer** [comment]
> > Unlocking of encrypted stratis pools has regressed. I'll have a look.
> 
> [stratis-storage/stratisd#3324](https://github.com/stratis-storage/stratisd/issues/3324)
> 
> Not sure what to do about this yet.

#18679 should work around the bug.

**Comment by martinpitt** [comment]
Still some failures. Moving to draft to clear up the "to review" list. @mvollmer , can you please re-ask for my review once this is done? Thanks!

**Comment by mvollmer** [comment]
Yay, `dnf-copr` is green.

**Comment by mvollmer** [comment]
TestStorageFormat.testAtBoot needs investigation

**Comment by mvollmer** [comment]
> TestStorageFormat.testAtBoot needs investigation

I can't easily get it to fail locally, and it's green now here... good enough, I'd say.

**Review by martinpitt — APPROVED** [review]
Nice! Then we can also land https://github.com/cockpit-project/bots/pull/4634 along with this.

**Pull request merged**
