### PR TITLE
Image refresh for fedora-24

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for fedora-24 in process on host32-rack06.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-24-2016-05-23/

### CODE REVIEW

**Comment by stefwalter** [comment]
SELinux regression. Will file upstream.

**Comment by mvollmer** [comment]
I have a plan for the LUKS storage failure.  It's a regression in storaged.  I'll file a known issue.

**Comment by mvollmer** [comment]
> I have a plan for the LUKS storage failure. It's a regression in storaged. I'll file a known issue.

We already had a know issue for Debian. See #4475

**Comment by dperpeet** [comment]
bot: Image refresh for fedora-24

**Comment by cockpituous** [comment]
Image creation for fedora-24 in process on host32-rack06.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-24-9300d3bcc3f5aa40c86c261407331fd014b4e350/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-fedora-24-9300d3bcc3f5aa40c86c261407331fd014b4e350

**Comment by stefwalter** [comment]
Replaced by a new update.

**Pull request closed without merging**
