### PR TITLE
storage: Don't treat unsupported filesystems as unrecognized data for resize

### PR DESCRIPTION
**Pull request by mvollmer**
If udev tells us that this device has a filesystem, but UDisks2 doesn't know anything about it, refuse to resize it with a clear "unsupported" message.

This was caught on fedora-26.

### CODE REVIEW

**Comment by mvollmer** [comment]
This also includes a new fedora-26 image, and we should test it here.

**Comment by mvollmer** [comment]
I have also enabled testResizeNtfs on all other Oses.  let's see what happens there.

**Comment by martinpitt** [comment]
Test failed on [centos-7](https://fedorapeople.org/groups/cockpit/logs/pull-8590-20180209-124242-87bbe526-verify-centos-7/log.html#139), [rhel-7](https://fedorapeople.org/groups/cockpit/logs/pull-8590-20180209-124646-87bbe526-verify-rhel-7/log.html#145), and [rhel-7-4](https://fedorapeople.org/groups/cockpit/logs/pull-8590-20180209-124242-87bbe526-verify-rhel-7-4/log.html#186).

**Comment by mvollmer** [comment]
> Test failed on centos-7, rhel-7, and rhel-7-4.

Silly me, we can't even format NTFS there.  See #8511.

**Pull request closed without merging**
