### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by marusak** [comment]
[3 tests failed](https://209.132.184.41:8493/logs/pull-11608-20190415-201919-03ebcc40-verify-debian-testing/log.html) and the same 3 failed in the [previous run](https://209.132.184.41:8493/logs/pull-11608-20190415-174646-03ebcc40-verify-debian-testing/log.html) as well. One more retry

**Comment by marusak** [comment]
testTime (check_system_info.TestSystemInfo)
testTimeServers (check_system_info.TestSystemInfo)

Both failed 3/3 times, needs work

**Comment by KKoukiou** [comment]
Regarding the testTime and testTimeServers....

It's because the timedate1.service has changed from being enabled to being static.

See: 
These are ran on debian-testing with systemd-241:
```
root@unassigned-hostname:~# busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
b false
root@unassigned-hostname:~# systemctl list-unit-files | grep timedate
dbus-org.freedesktop.timedate1.service     static         
systemd-timedated.service                  static         
````
And these on fedora-29 with system 239:
````
[root@localhost ~]# busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 NTP
b true
[root@localhost ~]# systemctl list-unit-files | grep timedate
dbus-org.freedesktop.timedate1.service      enabled  
systemd-timedated.service                   masked   
timedatex.service                           enabled  
 ```

Static services are enabled as well, as a dependency of some other service. Looks like this is broken on the new systemd for timedate1 not being able to be discovered as active if it's statically enabled.

**Comment by KKoukiou** [comment]
Hmm, with further investigation it looks like that new systemd just can't figure out that NTP service (chronyd) is running:
``` bash
# systemctl status chronyd
● chrony.service - chrony, an NTP client/server
   Loaded: loaded (/lib/systemd/system/chrony.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-04-16 08:55:05 EDT; 11s ago
     Docs: man:chronyd(8)
           man:chronyc(1)
           man:chrony.conf(5)
  Process: 451 ExecStart=/usr/sbin/chronyd $DAEMON_OPTS (code=exited, status=0/SUCCESS)
  Process: 463 ExecStartPost=/usr/lib/chrony/chrony-helper update-daemon (code=exited, status=0/SUCCESS)
 Main PID: 461 (chronyd)
    Tasks: 2 (limit: 1145)
   Memory: 1.2M
   CGroup: /system.slice/chrony.service
           ├─461 /usr/sbin/chronyd -F -1
           └─462 /usr/sbin/chronyd -F -1

Apr 16 08:55:05 unassigned-hostname systemd[1]: Starting chrony, an NTP client/server...
Apr 16 08:55:05 unassigned-hostname chronyd[461]: chronyd version 3.4 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP +SCFILTER +SIGND +ASYNCDNS +SECHASH +IPV6 -DEBUG)
Apr 16 08:55:05 unassigned-hostname chronyd[461]: Frequency 0.000 +/- 1000000.000 ppm read from /var/lib/chrony/chrony.drift
Apr 16 08:55:05 unassigned-hostname chronyd[461]: Loaded seccomp filter
Apr 16 08:55:05 unassigned-hostname systemd[1]: Started chrony, an NTP client/server.
root@unassigned-hostname:~# timedatectl show
Timezone=America/New_York
LocalRTC=no
CanNTP=yes
NTP=no
NTPSynchronized=no
TimeUSec=Tue 2019-04-16 08:55:27 EDT
RTCTimeUSec=Tue 2019-04-16 08:55:26 EDT
root@unassigned-hostname:~# timedatectl -p NTP
               Local time: Tue 2019-04-16 08:55:33 EDT
           Universal time: Tue 2019-04-16 12:55:33 UTC
                 RTC time: Tue 2019-04-16 12:55:32
                Time zone: America/New_York (EDT, -0400)
System clock synchronized: no
              NTP service: inactive
          RTC in local TZ: no
root@unassigned-hostname:~# dpkg -l | grep systemd
ii  dbus-user-session                    1.12.12-1                       amd64        simple interprocess messaging system (systemd --user integration)
ii  libnss-systemd:amd64                 241-3                           amd64        nss module providing dynamic user and group name resolution
ii  libpam-systemd:amd64                 241-3                           amd64        system and service manager - PAM module
ii  libsystemd0:amd64                    241-3                           amd64        systemd utility library
ii  systemd                              241-3                           amd64        system and service manager
ii  systemd-coredump                     241-3                           amd64        tools for storing and retrieving coredumps
ii  systemd-sysv                         241-3                           amd64        system and service manager - SysV links
```

**Comment by martinpitt** [comment]
I haven't looked into this in full detail, but a couple of random notes:

 - timedated is only a d-bus api for changing timezone, and an abstraction for getting/setting NTP status -- but it doesn't do NTP (by itself)
 - NTP == timesyncd | chrony | ntpd
 - systemd-timedated supports a `$SYSTEMD_TIMEDATED_NTP_SERVICES` variable which is a list of services which provides NTP. That's how it decides if ntp is "on" -- apparently in Fedora, chronyd.service is in that list.
 - The first surprise in that image build is that chrony gets installed in the first place; we expect timesyncd as the OS default. I can purge the package without removing anything else, so it seems there's some `Recommends: chrony` of some package which we install. But this is already the case on the current image.
 - There was a recent change in Debian which might be related: https://salsa.debian.org/systemd-team/systemd/commit/e1b3868e8b297a

**Comment by KKoukiou** [comment]
> I haven't looked into this in full detail, but a couple of random notes:
> 
>     * timedated is only a d-bus api for changing timezone, and an abstraction for getting/setting NTP status -- but it doesn't do NTP (by itself)
> 
>     * NTP == timesyncd | chrony | ntpd
> 
>     * systemd-timedated supports a `$SYSTEMD_TIMEDATED_NTP_SERVICES` variable which is a list of services which provides NTP. That's how it decides if ntp is "on" -- apparently in Fedora, chronyd.service is in that list.
> 
>     * The first surprise in that image build is that chrony gets installed in the first place; we expect timesyncd as the OS default. I can purge the package without removing anything else, so it seems there's some `Recommends: chrony` of some package which we install. But this is already the case on the current image.
> 
>     * There was a recent change in Debian which might be related: https://salsa.debian.org/systemd-team/systemd/commit/e1b3868e8b297a

Last link was the issue here. Thanks a lot! See commit in the PR.

**Comment by KKoukiou** [comment]
Yay, the testTime, testTimeServers regressions went away. All the tests failures now looked like old time classic flakes so just retrying to get the verify/debian-testing completely green.

**Pull request merged**
