### PR TITLE
test: Remove tang cache updating hacks

### PR DESCRIPTION
**Pull request by mvollmer**
All images now have the fix.

### CODE REVIEW

**Comment by mvollmer** [comment]
This is optiomistic, let's see what the tests say.  https://github.com/cockpit-project/bots/pull/1446 and https://github.com/cockpit-project/bots/pull/1445 will bring the fixes for fedora-33 and fedora-32, respectively.

**Comment by mvollmer** [comment]
Hmm fedora-coreos might still have the bug...

**Comment by marusak** [comment]
I would say you want to trigger tests with related `@bots@...` parts for fedora-32, fedora-33 and fedora-testing

**Comment by mvollmer** [comment]
Too late for release-blocker... all other tests for the new fedora-23 and fedora-33 were green.

**Comment by mvollmer** [comment]
> Hmm fedora-coreos might still have the bug...

Heh, it doesn't even have the Storage page...

**Comment by marusak** [comment]
`fedora-33@bots@1446` and `fedora-33@bots@c620d4e77b4befafa8c21f2bf9dd98852d0709bb` are both invalid contexts. Let me trigger the ones we need.

**Comment by marusak** [comment]
I did `./bots/tests-trigger 15026 fedora-32@bots#1445 fedora-33@bots#1446 fedora-testing@bots#1450` FWIW.

**Comment by mvollmer** [comment]
> `fedora-33@bots@1446` and `fedora-33@bots@c620d4e77b4befafa8c21f2bf9dd98852d0709bb` are both invalid contexts. Let me trigger the ones we need.

Thanks!  Can we make it easier to get the syntax right?  Maybe some options to tests-trigger thta re explained in the help output.  I use this so occasionally that I don't even know where to look this up...

**Comment by marusak** [comment]
> Can we make it easier to get the syntax right? Maybe some options to tests-trigger that are explained in the help output. I use this so occasionally that I don't even know where to look this up...

It is documented in https://github.com/cockpit-project/bots/blob/master/README.md#test-contexts
I guess we could put it also into `tests-trigger` help, but not sure if it is the place where we want to explain how contexts are constructed.

**Review by marusak — APPROVED** [review]
Thanks!
It breaks the current F32 and F33, so it needs to land together with those bots PRs. f-testing has one failed tests, unrelated to this, but since we test f-testing just on refreshes, I suggest just retrying that one in bots again.

**Pull request merged**
