### PR TITLE
storage: Allow removal of fstab entries

### PR DESCRIPTION
**Pull request by mvollmer**
Now unmounting always goes via a dialog which contains the "clear fstab"
option.

image

### CODE REVIEW

**Comment by garrett** [comment]
"Clear" is a strange word here. Should't we use "Remove"? Also, it should not be default.

This UI feels odd to be too, but nothing really jumps out as an alternate solution.

**Comment by mvollmer** [comment]
> Also, it should not be default.

Yes, that's just in the screenshot.

**Comment by mvollmer** [comment]
> "Clear" is a strange word here. Should't we use "Remove"?

What about "Also remove permanent mount point configuration".  We already say "The filesystem has no permanent mount point" once the fstab entry is removed.

**Comment by garrett** [comment]
This just doesn't feel right to me and I'm trying to figure out why.

In my own experience (which might or might not align with our users):
- adding mount points is infrequent
- removing mount points is even less frequent than adding them
- mounting and unmounting devices happens _all the time_ (usually automatic on boot up / shut down, but not always)

Therefore, I don't think this is the right place for removing `fstab` entries.

Also:
- actions buttons should reflext the action that they are about to do... in this case, checking the box would make it unmount and remove the filesystem configuration — but the button just says "unmount" instead of "unmount and remove" or somesuch
- if we're doing a removal action that isn't easily undoable, we'd need a confirmation dialog — and adding a dialog on top of a dialog is very bad form

I've been looking around Cockpit on my own system and am unsure where this would come from.

Is it from the expanded partition view like here?

Screenshot_2019-11-21 Storage - Rain(1)

(This is some weird SD card I used on my old Mac for backing up years ago, apparently, hence "hfsplus".)

Note: That three line menu button should actually be a mount/unmount button with [a kebab](https://www.patternfly.org/v4/documentation/react/components/dropdown#with-kebab) (vertical dots menu ⠇) ([another kebab example](https://www.patternfly.org/v4/documentation/core/components/dropdown#kebab-align-right))

If so, wouldn't a better place for this be in this dialog:

Screenshot_2019-11-21 Storage - Rain

But change "Apply" to "Save" (as it should be, most likely, unless I misunderstand what's going on) and add "Remove" as a danger class button all the way to the left of the dialog (in the same row as the other buttons, but furthest away possible as it's dangerous)? (However, ensure that remove doesn't become the default action when enter is pressed when in the entry. That would be bad.)

...and also a "Remove mount configuration" under the kebab menu entry (mentioned above) too?

**Comment by mvollmer** [comment]
> If so, wouldn't a better place for this be in this dialog:

Yes, that's where we had it originally.  I'll change this PR as you propose.  Thanks this was very valuable feedback!

**Comment by andreasn** [comment]
Sounds good to me!

**Comment by mvollmer** [comment]
Now we have a new menu entry:

image

And a second action button in the edit dialog:

image

**Comment by mvollmer** [comment]
When placing the "Remove" button on the left, it conflicts with the spinner that appears there when the dialog gets busy.  Should we resolve that conflict? How?

**Comment by mvollmer** [comment]
Nobody seems to need this, so let's archive this.

**Pull request closed without merging**
