### PR TITLE
Image refresh for continuous-atomic

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for continuous-atomic
 * [x] image-refresh continuous-atomic
 * [x] image-refresh fedora-27
 * [x] #9880
 * [x] #9906 
 * [ ] #9941

### CODE REVIEW

**Comment by martinpitt** [comment]
@Gundersanne, this still smells a lot like the libssh issue? That fix got in, another corner case?

**Comment by Gundersanne** [comment]
This is due to a mistake I made in #9796, pushed a fix at #9880.

**Comment by martinpitt** [comment]
#9880 landed. Insert coin and try it again.

**Comment by martinpitt** [comment]
Hmm, no joy, tests are still freaking out :-(

**Comment by Gundersanne** [comment]
Totally missed that, thanks :)

**Comment by martinpitt** [comment]
#9906 worked and landed, so it's apparently something new/unrelated in the image refresh.

**Comment by martinpitt** [comment]
I originally thought that the installing of cockpit-ssh was somehow a workaround for trying to install the upstream master cockpit-bridge packages on a stable image. However, in the cockpit-ostree vm.install we use the *official* cockpit/ws container from Dockerhub -- so it does seem to me that this combination is broken (in production), and our .install file just hides this by hacking around this.

So it seems to me the only long-term would be to actually install cockpit-ssh and libssh in [our ws Docker container](https://github.com/cockpit-project/cockpit/blob/master/containers/ws/install-package.sh). When [moving cockpit-ssh from -dashboard to -bridge](https://github.com/cockpit-project/cockpit/commit/14527b8f57452c0e) I also adjusted that docker container back then.

Conceptually this should be right -- cockpit-bridge ships cockpit-ssh and should depend on libssh. So any *explicit* install of libssh just hides a dependency bug.

However, I just noticed that we still build the container from fedora:27. The moving of cockpit-ssh into -bridge happened in Cockpit 171, and Fedora 27 [ships cockpit 166](https://ftp-stud.hs-esslingen.de/pub/fedora/linux/updates/27/x86_64/Packages/c/).

As Fedora 27 won't be supported that long any more anyway, and we stopped updating Cockpit there a while ago, I think the best and cleanest fix would be to bump cockpit/ws to Fedora 28. This should then install a current cockpit-bridge with cockpit-ssh and correct libssh dependencies.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-4np2l.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9865-20180829-164343/

**Comment by cockpituous** [comment]
image-refresh fedora-27 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-27-20180829-174646

**Comment by martinpitt** [comment]
This still needs #9941 to land, then we should close this and let the bots build a fresh image, which should then work without further changes.

**Comment by martinpitt** [comment]
Actually that was supposed to mean #9920. This landed now, so closing.

**Pull request closed without merging**
