### PR TITLE
Image refresh for fedora-30

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-30
 * [x] image-refresh fedora-30

### CODE REVIEW

**Comment by marusak** [comment]
[podman](https://209.132.184.41:8493/logs/pull-12361-20190719-065555-0985a3bb-cockpit-project-cockpit-podman-cockpit-fedora-30/log) one fail, [lorax](https://209.132.184.41:8493/logs/pull-12361-20190719-065555-0985a3bb-weldr-lorax-cockpit-fedora-30-openstack/log) as well. Rerunning to compare.

**Comment by martinpitt** [comment]
FTR, I'm currently investigating podman lockups in https://github.com/containers/libpod/issues/3602 and https://github.com/containers/libpod/issues/3603. These may need a naughty or other workaround.

**Comment by marusak** [comment]
> FTR, I'm currently investigating podman lockups in containers/libpod#3602 and containers/libpod#3603. These may need a naughty or other workaround.

Nice reports!! Awesome :)
I suspect that https://github.com/cockpit-project/cockpit-podman/issues/128 could be very likely result of those behaviors.

**Comment by martinpitt** [comment]
@larskarlitski , @atodorov : The lorax openstack test [repeatedly fails](https://209.132.184.41:8493/logs/pull-12361-20190719-082020-0985a3bb-weldr-lorax-cockpit-fedora-30-openstack/log) with 

    [   FAIL   ] :: check_root_account: Missing user or machine parameter. 

Is this a current "expected" failure? Or does the new Fedora 30 image actually break something?

**Comment by larskarlitski** [comment]
> Is this a current "expected" failure? Or does the new Fedora 30 image actually break something?

We have seen this on previous images as well.

**Comment by martinpitt** [comment]
@henrywang : The [composer edge test](https://209.132.184.41:8493/logs/pull-12361-20190719-154949-0985a3bb-weldr-cockpit-composer-cockpit-fedora-30-edge/log) keeps failing. Does that ring a bell?

**Comment by martinpitt** [comment]
Edge failure happens because this image now switched to cockpit 198 with PF4 and larger fonts. This causes some elements to get scrolled off, triggering a similar bug as worked around in https://github.com/cockpit-project/cockpit/commit/b960b0fc7

**Comment by martinpitt** [comment]
cockpit-composer/edge should be fixed now, retrying.

**Pull request merged**
