### PR TITLE
Backported fixes for rhel-8-appstream

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by martinpitt** [comment]
[fails](https://209.132.184.41:8493/logs/pull-12519-20190808-073838-efc7fee0-cockpit-project-cockpit-rhel-8-0-distropkg/log.html#187): `name 'prepareDisk' is not defined` . Apparently I am missing some backport.

**Comment by martinpitt** [comment]
This keeps crashing the machines tests, same issue as we have on master (but apparently more persistent?)

**Comment by martinpitt** [comment]
I backported another commit for https://bugzilla.redhat.com/show_bug.cgi?id=1731865

**Comment by martinpitt** [comment]
Backported the fix from #12525 .

**Comment by martinpitt** [comment]
@kkoukiou: I'm afraid that last fix [wasn't it](https://209.132.184.41:8493/logs/pull-12519-20190808-144040-1cf75b2a-cockpit-project-cockpit-rhel-8-0-distropkg/log.html#) :crying_cat_face:

**Comment by marusak** [comment]
I backported one more commit. It fixed it for me, but I had a few more commits picked in my testing branch so if tests won't work, I'll add some more.

**Comment by martinpitt** [comment]
That's it, thank you! :star:

**Pull request merged**
