### PR TITLE
storage: Remove two obsolete clevis workarounds

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
> Failed almost everywhere.. still applies after all?

One bit is still needed I think: `pty: true`. I guess clevis-luks-unbind calls cryptsetup in the same way as our workaround did, which for some reason requires a tty on stdin. *shrug*

**Comment by mvollmer** [comment]
Oi, missed the "-f" flag.

**Review by martinpitt — APPROVED** [review]
Nice, thanks! Tests looked good, just retried debian-stable for some usual suspects.

**Pull request merged**
