### PR TITLE
registry: Update the image view to match new designs

### PR DESCRIPTION
**Pull request by stefwalter**
Among other things this shows the description, url, build-date
labels inline in the appropriate places.

 * [x] Implementation
 * [x] Integration tests

### CODE REVIEW

**Comment by stefwalter** [comment]
screenshot from 2016-03-16 12-06-47

@aweiteka FYI

**Comment by aweiteka** [comment]
@stefwalter nice. A few nits...

- "Source" could is whatever the author puts in the url label, which could be documentation, a project site, or a github repo. Maybe just label it URL?
- Can you display the "Summary" field with the short description if available? I would put this top-most.
- Digest and Identifier are pretty low-level constructs more closely associated with tags. I still struggle with how these might be used and what they actually refer to. I suggest putting those below the general author and build date.

**Comment by stefwalter** [comment]
> "Source" is whatever the author puts in the url label, which could be documentation, a project site, or a github repo. Maybe just label it URL?

Well this is a hard one. What does 'URL' mean by itself? It's not the URL to the image, but rather the URL that the image came from, related to? Maybe 'Source URL' is better?

> Can you display the "Summary" field with the short description if available? I would put this top-most.

Done.

> Digest and Identifier are pretty low-level constructs more closely associated with tags. I still struggle with how these might be used and what they actually refer to. I suggest putting those below the general author and build date.

We'll they're the only way to actually identify an image. They're very important because of that. But yes, moved them down.

**Comment by stefwalter** [comment]
screenshot from 2016-03-16 15-56-41

**Comment by aweiteka** [comment]
@stefwalter looks good!

**Comment by petervo** [comment]
Closed by 7bf11a138606141966108ac79fd595290ee05a3c

**Pull request closed without merging**
