### PR TITLE
registry: Implement a basic dashboard

### PR DESCRIPTION
**Pull request by stefwalter**
Implement a basic dashboard with lots of placeholders for stuff yet to be implemented.
    
By bringing this in early, we can parallelize work on the various tasks. There are TODO included for each part that still needs work.

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #3451

**Comment by stefwalter** [comment]
screenshot from 2016-01-13 13-52-49

**Comment by stefwalter** [comment]
Rebased, and fixed some minor issues in display.

**Comment by stefwalter** [comment]
Fixed issue with including date.js in test-images.html

**Comment by petervo** [comment]
Looks good, dashboard-page.html needs a translatable pass.

**Comment by stefwalter** [comment]
Fixed translations in dashboard-page.html

**Pull request closed without merging**
