### PR TITLE
Reorganize check-metrics, fix "current memory" metric flake

### PR DESCRIPTION
**Pull request by martinpitt**
Fixes our #2 top flake on https://images-frontdoor.apps.ocp.ci.centos.org/failure-stats.html

### CODE REVIEW

**Comment by martinpitt** [comment]
Of course this PR is really hard, as all tests have to succeed three times -- but nevertheless I think I caused at least some regression here.

**Comment by martinpitt** [comment]
I fixed the one regression; [this failure](https://logs.cockpit-project.org/logs/pull-15152-20210115-103719-a154056a-ubuntu-stable/log.html#310-1) has been there before, the [lo-hog unit fails](https://logs.cockpit-project.org/logs/pull-15152-20210115-103719-a154056a-ubuntu-stable/TestCurrentMetrics-testNetwork-ubuntu-stable-127.0.0.2-2301-FAIL.log.gz) for some unknown reason. I couldn't reproduce this locally yet.

**Comment by martinpitt** [comment]
Still some bug on Debian/Ubuntu [log](https://logs.cockpit-project.org/logs/pull-15152-20210115-173645-56039111-debian-testing/log.html#310-1), the *second* time `testNetwork` runs is broken.

**Comment by martinpitt** [comment]
One more robustification. This works well enough for me, I can't get it to break locally any more. Let's see what the bots say.

**Comment by martinpitt** [comment]
Argh, so close! [just one failure](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-15152-20210116-120145-5ce2fc20-ubuntu-2004/log.html#310):
```
Jan 16 12:20:25 ubuntu systemd[1]: Started /usr/bin/sh -ec nc -vv -l 2000 > /dev/null & sleep 1; nc -vv localhost 2000 </dev/zero.
Jan 16 12:20:26 ubuntu sh[25670]: nc: getnameinfo: Temporary failure in name resolution
Jan 16 12:20:26 ubuntu PackageKit[10203]: get-updates transaction /67_ebccaaae from uid 0 finished with success after 666ms
Jan 16 12:20:26 ubuntu sh[25677]: nc: connect to localhost port 2000 (tcp) failed: Connection refused
```
Not sure what this is trying to say.. the `Temporary failure in name resolution` is the *server*, it should just open a listening port..

**Comment by martinpitt** [comment]
Yay, that did the trick! The failures are in check-machines and networking, unrelated.

**Comment by marusak** [comment]
What about [this](https://logs.cockpit-project.org/logs/pull-15152-20210116-170234-256c8b8b-ubuntu-2004/log.html#314-1) metrics failure? Or is that for some other time?

**Comment by martinpitt** [comment]
@marusak: I haven't seen this yet, but given how badly the `TetMetrics` flakes bites us I'd like to handle it in a separate PR. There is no code overlap with this one (destructive `TestMultiCPU` class)

**Review by marusak — APPROVED** [review]
nice, thanks!

**Comment by martinpitt** [comment]
@marusak: I took a quick look at the [TestMultiCPU.testCPUUsage](https://logs.cockpit-project.org/logs/pull-15123-20210115-073403-44eb2a33-ubuntu-2004/log.html#81-2) failure on ubuntu-2004. This is indeed our 7th top flake right now.

I can reproduce this locally if I start two tests in parallel (with one it works fine). Bumping the `self.browser.wait()` timeout to 5 minutes does not help, it still fails with `log: Channel is not ready: not-found` hundreds of times.

This is because pmlogger failed to start:
```
an 18 06:35:03 ubuntu pmlogger[1071]: Starting pmlogger ...
Jan 18 06:35:03 ubuntu systemd[1]: pmlogger.service: Can't open PID file /run/pcp/pmlogger.pid (yet?) after start: Operation not permitted
Jan 18 06:35:08 ubuntu systemd[1]: pmlogger.service: Succeeded.
Jan 18 06:35:08 ubuntu systemd[1]: Stopped Performance Metrics Archive Logger.
```

**Comment by martinpitt** [comment]
I sent a fix for that remaining failure in PR #15163

**Pull request merged**
