### PR TITLE
kubernetes: Improve node status messages

### PR DESCRIPTION
**Pull request by petervo**
Surface schedulable status and known error conditions when present.

### CODE REVIEW

**Comment by stefwalter** [comment]
Some fixups here: 

https://github.com/stefwalter/cockpit/commit/5a257a2816762ba0abb78d8efa4b7b51ba14a114
https://github.com/stefwalter/cockpit/commit/854706f154223d9522a338aa3a3b2da1031dd707

**Comment by petervo** [comment]
Fixed the tags, but i'm not sure about adding the alert for the ready status, it's already on the page elsewhere. @andreasn do you think we should display an alert for it? And if so should it be warning or error? We are using the error icon elsewhere when the node is not ready and warning for disk and memory errors.

**Comment by stefwalter** [comment]
The fact that the node has gone away is pretty important. Likely more important that out of disk space. Agree that it might make more sense to use the alert error style and icon.

**Comment by petervo** [comment]
Added the alert, if @andreasn has objections we can follow up later

**Comment by andreasn** [comment]
How can I test this in action?

**Comment by petervo** [comment]
Add a node with garbage for an address. After about a min it will be marked as failed and you will see the alert.

**Pull request closed without merging**
