### PR TITLE
images: Use a Dockerfile for kubernetes image

### PR DESCRIPTION
**Pull request by petervo**
In order to work with docker hub and other automatic container build tools we have to build from a
Dockerfile and can't use a script to prepare the docker context before building.

Since this adds a go builddep, all the mock caches need to be updated. Will keep updating the pr as the new images build.

### CODE REVIEW

**Comment by petervo** [comment]
bot: Image refresh for rhel-7

**Comment by petervo** [comment]
bot: Image refresh for rhel-7

**Comment by petervo** [comment]
All the images are created still need to upload them.

**Comment by aweiteka** [comment]
Keeping in mind I'm not clear on the full scope of this part of the project, it seems that "kubernetes" is not a good name. For my use case I would suggest cockpit/registry. A more broad name might be cockpit/origin or cockpit/openshift.

**Comment by aweiteka** [comment]
See comments in related PR https://github.com/openshift/origin/pull/7484

**Comment by mvollmer** [comment]
`openshift.setup` also calls out to `lib/images.setup` so it might need to be regenerated.

On the other hand, should openshift.setup actually call images.setup?

**Comment by mvollmer** [comment]
> Keeping in mind I'm not clear on the full scope of this part of the project, it seems that "kubernetes" is not a good name. 

This PR does not introduce or change any names, so I'd say we decide this separately.  This PR changes a lot of images and I'd rather have it in sooner than later so that they don't get stale.

**Pull request closed without merging**
