### PR TITLE
Prevent search engine indexing with robots.txt

### LINKED ISSUE #17401: My panel is listed by search engine.
### Explain what happens

Hello,
The web panel is lacking a robots.txt file to avoid search engine to list my panel.

Even if I will/can add one with my webserver configuration (caddy) it is annoying.

Interestingly, my Cockpit web panel is not listed on Google and Yahoo but on Bing and Duckduckgo.
withdns
locally
veryduckwow

Thank you,
I really enjoy the web panel since many years.
Have a good day.
Ertuit.

### Version of Cockpit

239 (Debian)

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Debian

### Server operating system version

Debian 10 (up to date)

### What browsers are you using?

Firefox

### System log

_No response_

### PR DESCRIPTION
**Pull request by garrett**
Fixes #17401

### CODE REVIEW

**Comment by garrett** [comment]
The robots.txt file isn't showing up in my VM file. I don't think I added it to the right place in the build file.

@martinpitt, can you please look and suggest (or make) a fix?

**Comment by garrett** [comment]
Added blocked label and set as draft, as this shouldn't be merged until it's fixed.

**Comment by garrett** [comment]
Rebased. Still requires review.

**Comment by martinpitt** [comment]
Thanks! I implemented that in #21430

**Pull request closed without merging**
