### PR TITLE
[no-test] bots: Don't register rhel-7-7 image

### LINKED ISSUE #11967: [no-test] Image refresh for rhel-7-7
Image refresh for rhel-7-7
 * [ ] FAIL: image-refresh rhel-7-7

### PR DESCRIPTION
**Pull request by martinpitt**
We use nighty repositories there instead of the CDN, which does not need
a subscription. This unblocks the image until our team subscription
works again.

Fixes #11967

 * [x] image-refresh rhel-7-7

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-11982-20190603-075757/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-11982-20190603-075757/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-11982-20190603-091212/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-11982-20190603-091212/

**Comment by cockpituous** [comment]
image-refresh rhel-7-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-7-20190603-094242

**Comment by martinpitt** [comment]
[two common flakes](https://209.132.184.41:8493/logs/pull-11982-20190603-123131-1e8f5a0a-verify-rhel-7-7/log.html), retrying for comparison.

**Pull request merged**
