### PR TITLE
test: Use virt-builder for fedora-25

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
bot: Image refresh for fedora-25

**Comment by cockpituous** [comment]
Image creation for fedora-25 in process on cockpit-9.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-25-ea19b1114e160c35c9735ac9ff56dac5340c10a0/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-fedora-25-ea19b1114e160c35c9735ac9ff56dac5340c10a0

**Comment by stefwalter** [comment]
Unfortunately this needs a rebase.

**Comment by stefwalter** [comment]
Seems like the docker images didn't get pulled properly into the VM:

```
Digest: sha256:f8cdcf3eb8fac77a9b24f37bc440feea024a5d3ec9a33f1d0a4c42c5df6a49c3
Status: Downloaded newer image for docker.io/busybox:buildroot-2014.02
Trying to pull repository gcr.io/google_containers/pause ... 
Trying to pull repository gcr.io/google_containers/pause ... 
Trying to pull repository gcr.io/google_containers/pause-amd64 ... 
BDB2053 Freeing read locks for locker 0x790: 31200/140249643050752
BDB2053 Freeing read locks for locker 0x792: 31200/140249643050752
```

**Comment by mvollmer** [comment]
> Seems like the docker images didn't get pulled properly into the VM:

I see this when trying this manually:

```
# docker pull gcr.io/google_containers/pause:2.0
[  320.082005] audit: type=2500 audit(1483626717.956:223): pid=1142 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:container_runtime_t:s0 msg='exe=? hostname=? reason=api op=create vm=? vm-pid=? user=root auid=0  exe="/usr/bin/dockerd-current" hostname=? addr=? terminal=? res=success'
Trying to pull repository gcr.io/google_containers/pause ... 
Pulling repository gcr.io/google_containers/pause
Error while pulling image: Get http://gcr.io/v1/repositories/google_containers/pause/images: dial tcp 127.0.0.1:80: getsockopt: connection refused
```

Also, some kubernetes tests fail with

```
bash: /etc/kubernetes/start-kubernetes: No such file or directory
```

@stefwalter, any idea what's going on?

**Comment by mvollmer** [comment]
I start to think that we should stick with virt-install for Fedora 25 and maybe in general.  Virt-install gives us lvm2 for / by default and in general allows more control.  Virt-builder can not be as flexible since it needs to avoid the limitations of virt-resize, which is probably why the images produced by virt-builder don't use lvm2 for /.

The reason to prefer virt-builder is that it is faster and more more reliable, but we had very good experience with virt-install and fedora-25.

**Comment by mvollmer** [comment]
As discussed on IRC, let's abandon this.

**Pull request closed without merging**
