### PR TITLE
bots: Use official distro Debian/Ubuntu cloud images

### PR DESCRIPTION
**Pull request by martinpitt**
Stop using the virt-builder ones, so that we test more official images.
They can be used for bootstrap as-is. Plus, we don't need libguestfs for
building these images any more. This also reduces the image size by 30%.

Move the disabling of udev network names, installation of eatmydata, and
the copying of root's .ssh key into the .setup script. The former
requires some cleanup from cloud-init generated network configuration
scripts.

Also fix all images to not block on the disconnected eth1 at boot in
NetworkManager-wait-online.target. This mirrors what we do on the
Fedora/RHEL images, where the sysconfig scripts set `ONBOOT=no`. This
means that NetworkManager now considers "eth1" as "disconnected", and
does not automatically tell firewalld to enable that for the default
zone. Do that manually in the *.install script so that our firewalld
tests work (which expect an active zone).

 * [x] image-refresh debian-stable
 * [x] image-refresh debian-testing
 * [x] image-refresh ubuntu-stable
 * [x] image-refresh ubuntu-1804
 * [x] Fix check-journal to not require kernel RTC support: PR #12672

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-21cn5.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190830-153737/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-stable-20190830-155050

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-12669-20190830-155252/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-testing-20190830-163737

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://209.132.184.41:8493/logs/image-refresh-12669-20190830-155252/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-12669-20190830-164141/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-stable-20190830-165858

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://209.132.184.41:8493/logs/image-refresh-12669-20190830-164141/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-pm53s.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190830-170000/

**Comment by cockpituous** [comment]
image-refresh ubuntu-1804 done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-1804-20190830-171212

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190830-170000/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-12669-20190901-195959/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-stable-20190901-203838

**Comment by martinpitt** [comment]
@Gundersanne: The [firewall tests fail](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-12669-20190901-204646-756b7e7a-cockpit-project-cockpit--debian-stable/log.html#132-2) with this, not just on debian-stable, but on debian-testing and the two ubuntus as well (in a previous build round). At first sight I can't see any difference, just that on this image all zones are empty.  Both use iptables (not nftables), same packages are installed, `firewall-cmd --state` is running for both. Do you have some hints how to compare the behaviour on the CLI?

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-12669-20190902-065050/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-12669-20190902-065050/

**Comment by Gundersanne** [comment]
@martinpitt I think the distributions themselves decide what's in the default zones. `firewall-cmd --list-all` should list all active zones with their active services.

If this is the new default behaviour for these images we'll just have to adapt the tests.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-12669-20190902-072727/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-stable-20190902-075656

**Comment by martinpitt** [comment]
@Gundersanne: Current image:
```
# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth1
  sources: 
  services: dhcpv6-client ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```

This image:
```
# firewall-cmd --list-all
public
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```

So it seems there are no active zones by default? I wonder how this can be a function of how to build an image

**Comment by Gundersanne** [comment]
@martinpitt That is weird. Does it throw any errors when you try to activate it?

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-21cn5.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190902-091818/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-testing-20190902-093232

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190902-091818/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-21cn5.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190902-093434/

**Comment by cockpituous** [comment]
Task failed: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190902-093434/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-21cn5.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190902-093737/

**Comment by cockpituous** [comment]
Task failed: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190902-093737/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-pm53s.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190902-100000/

**Comment by cockpituous** [comment]
Task failed: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190902-100000/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-n1r4n.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190902-103030/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-stable-20190902-104747

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-n1r4n.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190902-104848/

**Comment by cockpituous** [comment]
image-refresh ubuntu-1804 done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-1804-20190902-110404

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190902-104848/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-wvwxv.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190902-123636/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-stable-20190902-130000

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-wvwxv.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190902-130000/

**Comment by cockpituous** [comment]
image-refresh ubuntu-1804 done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-1804-20190902-131414

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12669-20190902-130000/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-12669-20190902-151414/

**Comment by cockpituous** [comment]
image-refresh ubuntu-1804 done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-1804-20190902-154747

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://209.132.184.41:8493/logs/image-refresh-12669-20190902-151414/

**Pull request merged**
