### PR TITLE
Add a data-key attribute to Kubernetes Listing

### PR DESCRIPTION
**Pull request by stefwalter**
This allows code like action buttons to correctly identify the item that a row in the listing refers to.

### CODE REVIEW

**Comment by stefwalter** [comment]
@sub-mod This should help with the delete and modify buttons.

**Comment by stefwalter** [comment]
#2712 Should depend on this.

**Comment by stefwalter** [comment]
Added data-key check to check-kubernetes integration test.

**Comment by sub-mod** [comment]
LGTM

**Comment by stefwalter** [comment]
This was not properly merged. The first commit was missed.

FYI @sub-mod

**Pull request closed without merging**
