### PR TITLE
shell: On/Off for pmlogger

### PR DESCRIPTION
**Pull request by mvollmer**
Depends on #2020.

### CODE REVIEW

**Comment by stefwalter** [comment]
Needs a rebase.

**Comment by mvollmer** [comment]
I redo this once we the #services talks directly to systemd.

**Comment by mvollmer** [comment]
Ok, if we restrict ourselves to the unit file state, using the D-Bus API directly is pretty unproblematic.

**Comment by stefwalter** [comment]
Verified that this turns on/off the pmlogger. I see no effect on the Dashboard, but I guess that's not done yet.

**Comment by mvollmer** [comment]
> Verified that this turns on/off the pmlogger. I see no effect on the Dashboard, but I guess that's not done yet.

The dashboard and server plots would need to dynamically detect that archives have become available.  Currently they only check once during initialization.  This could maybe be done with a directory watcher..

**Pull request closed without merging**
