### PR TITLE
WIP: Rpm OSTree updates

### PR DESCRIPTION
**Pull request by petervo**
Here's the start of the rpm ostree daemon. Still a work in progress and a few things are missing but should be mostly functional.

Most development workflows with ember use watchers and transpilers to covert templates and non standard javascript to something that will run in the browser. Without doing that we can't run their resolver (it also interferes with our requirejs)  so bringing everything together is going to be a little non standard. Right now i'm passing around an instantiated application and running everything off that. But it has some down sides like it will be hard to use their injection api with this setup. Another option that might be better is to break each class / component out into it's own named requirejs block and use exports (from ember) to bring it all together, though that's going to be pretty verbose.  We will probably need to precompile the templates, move them out of the html but still be able to use them uncompiled in development, i'm about half way there on that but the way we compose our apps with have a say in what the final there will look like. So i figured i'd wait for some feedback.

I opted not to use ember-data, it's pretty widely used but technically still in beta, ember itself changes so much so i'm not sure that matters. It's really mainly focused around REST workflows though, but if we end up doing more ember pieces it might be worth reconsidering and and maybe writing our own adapter. I did not test translations, ember has their own thing there too but i don't think we'll want it. Ember is very opinionated about a lot of things and doesn't work all well that when you mix straight up jquery with it's events and runloop so i'm interested in others opinions on this.

Anyways for the cockpit side, I need to work on what happens during reboot and i'd like to add a bus owner change notifications to our dbus-json3 api.

### CODE REVIEW

**Comment by stefwalter** [comment]
> Anyways for the cockpit side, I need to work on what happens during reboot and i'd like to add a bus owner change notifications to our dbus-json3 api.

Can you use the ```track: true``` option to do this?

**Comment by petervo** [comment]
track closes the the proxies, i don't really want that. I just want to know that if i'm waiting for a signal it will not come so it doesn't just spin forever.

**Comment by stefwalter** [comment]
> track closes the the proxies, i don't really want that. I just want to know that if i'm waiting for a signal it will not come so it doesn't just spin forever.

Ah yes, makes senes. NameOwnerChanged signals are a good addition to dbus-json3 itself as a high level concept.

**Comment by petervo** [comment]
I addressed most of the style and loading issues and reworked the loading to be more standard AMD like. The one todo from the last review that wasn't fixed here is a message for the permission denied errors since currently rpmostreed will only talk to root.

**Comment by andreasn** [comment]
This paragraph will need some padding of 10px above and below.

screenshot from 2015-05-18 19-51-33

**Comment by andreasn** [comment]
To fix the padding issue above, this css should do the trick

```
#action-dialog div.modal-body {
    height: 260px;
    padding-top: 10px;
}
```

**Comment by andreasn** [comment]
if you set
```
#rpm-diff {
display: block;
}
```
you can get rid of the height in #action-dialog div.modal-body and not have to update them both when needed

**Comment by petervo** [comment]
@andreasn pushed this changes to files so you can pull and see them. Not sure i like it better, but see what you think.

**Comment by andreasn** [comment]
Looks very good now!

screenshot from 2015-05-27 15-36-06
adding "word-break: keep-all;" to the version class will fix that.

**Comment by petervo** [comment]
made the change

**Comment by petervo** [comment]
replaced by #2884

**Pull request closed without merging**
