### PR TITLE
HACK: try to fetch corrupt user journal files

### PR DESCRIPTION
**Pull request by jelly**
https://github.com/systemd/systemd/issues/24150

### CODE REVIEW

**Comment by jelly** [comment]
@martinpitt Hey, I'm trying to download_dir `/var/log/journal` but this doesn't seem to succeed, do you have any idea why it wouldn't work on packit?

Locally I get:

```
receiving incremental file list
created directory /home/jelle/projects/cockpit/tf-debug-systemd-user-journal/test/TestSystemInfo-testMotd-fedora-36-127.0.0.2-2201-FAIL
journal/
journal/cc8b84b1dda84fd18876e2aff2c3ffd1/
journal/cc8b84b1dda84fd18876e2aff2c3ffd1/system.journal
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject
sent 74 bytes  received 16,781,571 bytes  33,563,290.00 bytes/sec
total size is 16,777,216  speedup is 1.00
Failed to generate debug artifact:
Traceback (most recent call last):
  File "/home/jelle/projects/cockpit/tf-debug-systemd-user-journal/test/common/testlib.py", line 1205, in failureHandler
    test_case.copy_journal("FAIL")
  File "/home/jelle/projects/cockpit/tf-debug-systemd-user-journal/test/common/testlib.py", line 1900, in copy_journal
    print("files", os.listdir(directory))
FileNotFoundError: [Errno 2] No such file or directory: 'TestSystemInfo-testMotd-fedora-36-127.0.0.2-2201-FAIL'
```

**Comment by martinpitt** [comment]
@jelly : `download()` and `download_dir()` are a bit "strange" historically, they download relative destination paths into `test/`. So either adjust your listdir call accordingly, or set `relative_dir='`.` or specify an absolute destination dir.

**Comment by martinpitt** [comment]
@jelly btw, there's no difference -- your local output and the [one on testing farm](https://artifacts.dev.testing-farm.io/0b4c050c-65a8-47bc-a303-3974ab76032c/) fail on exactly the same issue.

**Comment by jelly** [comment]
I don't recall seeing this in a while so I'll close this PR.

**Pull request closed without merging**
