### PR TITLE
lib/page: Improve color contrast for list errors

### LINKED ISSUE #13944: services: Incorrect color usage for error state rows (needs better contrast)
It's hard to read the text in the new services page on units with errors:

Screenshot_2020-04-22 Services - debian

The colors of the `.service-unit-failed` class needs updating, as does `.service-unit-status-failed` (most likely).

Alternatively (or additionally), `--color-ct-list-critical-bg` is currently used and might need lightening.

### PR DESCRIPTION
**Pull request by garrett**
Fixes #13944

### CODE REVIEW

**Comment by garrett** [comment]
I believe this should work.

However, I haven't tested it yet... it's late today and I wanted to share what I had... so I've marked it as a draft.

**Comment by garrett** [comment]
(Meanwhile, when digging around in page.scss I see we still have a lot of custom colors, so I've opened up https://github.com/cockpit-project/cockpit/issues/15174 to remove all the unused ones.)

**Comment by garrett** [comment]
I've checked this in-browser and it's much better to look at. Additionally, browser testing now reports it passes AA level.

Screenshot:

Screenshot_2021-01-20 Services - garrett Rain

It previously looked like this:

Screenshot, previous

**Comment by garrett** [comment]
I might want to update the border colors, where they're used.

Screenshot_2021-01-20 Software Updates - admin localhost localdomain

**Comment by garrett** [comment]
I've updated the border colors and removed special-case hovering (which we turned off anyway, as of upgrading to PF4).

**Review by martinpitt — APPROVED** [review]
Thank you! Better *and* simpler :+1:

**Pull request merged**
