### PR TITLE
Image refresh for ubuntu-1604

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for ubuntu-1604
 * [x] image-refresh ubuntu-1604

### CODE REVIEW

**Comment by martinpitt** [comment]
Package fails to build

**Comment by martinpitt** [comment]
Ah, this is pbuilder being too dense to use alternative build dependencies; fallout from commit 771104e55d4ff
```
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 9.20160709) | dh-systemd
```

It's not entirely clear though why this happens now, given that in PR #7805 which introduced that change everything [worked fine](https://fedorapeople.org/groups/cockpit/logs/pull-7805-20171004-083939-664cb14b-verify-ubuntu-1604/log.html)

**Comment by martinpitt** [comment]
I pushed a commit to manually install dh-systemd into pbuilder on ubuntu-1604, to work around that bug. This doesn't affect later releases, so let's not waste more work on this. Rebuilding image.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-gpp24.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7875-20171015-092727/

**Comment by cockpituous** [comment]
image-refresh in progress on verifymachine5.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7875-20171015-092525/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-xwzn8.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7875-20171015-092828/

**Comment by cockpituous** [comment]
image-refresh ubuntu-1604 done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-1604-20171015-100202

**Comment by martinpitt** [comment]
Sorry @stefwalter, this was a bit premature - I didn't commit the image refresh to the PR yet. I'll open a new PR for that.

**Comment by martinpitt** [comment]
PR #7885 fixes the quoting to make this actually work, and will rebuild the image. I now keep the needswork tag until after all is done, sorry for the confusion.

**Pull request merged**
