### PR TITLE
lib: Use inline-flex for btn-group to ensure group sticks together

### LINKED ISSUE #11601: Button groups break in narrow widths
Button groups break in narrow widths:

thumb0034

Solution seems to be to add:
```css
.btn-group, .btn-group-vertical {
  display: inline-flex;
}
```

Switching to ct-form-layout would also help with the layout in Services details:

Screen Shot 2019-04-15 at 11 24 41

### PR DESCRIPTION
**Pull request by garrett**
Fixes #11601

### CODE REVIEW

**Comment by garrett** [comment]
This affects all btn-groups, including (many of) our custom toggles, buttons + dropdowns, and even a log dropdown (_why does it have this class???!?!?_).

I've looked all over Cockpit, and everything looks and acts as expected — even in places where using this class doesn't seem to make sense.

PatternFly uses an old Bootstrap, which uses `display: inline-block`; new Bootstrap also happens to use `inline-flex`, like this commit.

**Comment by stefwalter** [comment]
I don't remember why everything has these classes. But I'm glad you're working on fixing the problem. I'll remove myself from the list of reviewers for this one.

**Comment by garrett** [comment]
Note: I added support for `.btn-group-vertical`, as it's part of PatternFly via Bootstrap, and didn't want to break it by changing `.btn-group` to flex without addressing the vertical variant.

Cockpit doesn't currently use the vertical version, but we do already pull in code for it (via PF via BS) and I didn't want to break it — especially as it's basically a 1-line fix.

**Comment by martinpitt** [comment]
According to the tests above, this needs a rebase to current master.

**Comment by marusak** [comment]
> According to the tests above, this needs a rebase to current master.

Not really :) This is because I am testing new tests-scan tool and this is unwanted side-effect.

**Pull request merged**
