### PR TITLE
pf4: Remove description list responsive override

### PR DESCRIPTION
**Pull request by garrett**
TODO:

- [ ] Find description lists in Cockpit that need a responsive override and add a pf-m-horizontal-on-sm (or similar) class

### CODE REVIEW

**Comment by garrett** [comment]
Oh, we should use a standard PF variable, not 640px. I'm looking and will change this in a force-push.

Additionally, I think the summary I wrote here should be in the git commit itself.

**Review by KKoukiou — CHANGES_REQUESTED** [review]
There is already an official PF way to do this. I think we should fix it my using their classes now.

**Comment by garrett** [comment]
Updated PR to remove the section and add a note about using a class instead. 

Also: I converted it to draft, while we round up the parts of Cockpit that need to be adapted.

**Comment by garrett** [comment]
I guess someone, someday will work on this. Perhaps.

**Comment by garrett** [comment]
(But we have some other stuff to do right now...)

**Pull request closed without merging**
