### PR TITLE
test: base selenium testsuite splitted to more files

### PR DESCRIPTION
**Pull request by jscotka**
We needs better control which part of testsuite should be scheduled.

### CODE REVIEW

**Comment by dperpeet** [comment]
This moves tests out from somewhere else, right?
Is there a way to combine them smartly upstream without replicating code?

**Comment by jscotka** [comment]
Fixed, I've forgot to commit also change on seleniu-login.py. I've expected that git mv automatically commit this renaming file.

**Comment by stefwalter** [comment]
The changes don't pass pyflakes:

```
test/avocado/selenium-storage.py:11: 'process' imported but unused
test/avocado/selenium-base.py:12: 'libdisc' imported but unused
test/avocado/selenium-docker.py:11: 'process' imported but unused
test/avocado/selenium-docker.py:12: 'libdisc' imported but unused
```

**Comment by martinpitt** [comment]
@jscotca: Run `tools/static-code-tests` to quickly see/verify the pyflakes results.

**Comment by jscotka** [comment]
pyflakes issues solved. Should be good  now

**Pull request closed without merging**
