### PR TITLE
test: Retry every failure, not just the ones we deem flakes

### PR DESCRIPTION
**Pull request by mvollmer**
Because that's what we do manually anyway.

### CODE REVIEW

**Comment by marusak** [comment]
So we hope this would get much greener than usual on the first try, right? :)
I am although not that convinced that it is a great idea, especially since @Gundersanne is getting the flake stuff back again.
@Gundersanne WDYT?

**Comment by Gundersanne** [comment]
I'm good with this actually. At least it's a good stop-gap until we have a reliable/fast flake machine learn thingy. And it will speed up testing a lot.

**Comment by mvollmer** [comment]
The accounting is off, and retried tests still count as failures in the summary.

**Comment by mvollmer** [comment]
Dang, now it doesn't retry at all...

**Comment by mvollmer** [comment]
Ok, seems to work now.  I'll add a bit of polish to log.html...

**Comment by mvollmer** [comment]
Except, it retries skipped tests... oh man.

**Comment by marusak** [comment]
It does not retry external and selenium tests. Is that a thing right now as well?

Also can you describe how can I see the new logs.html locally? Thanks :)

**Comment by mvollmer** [comment]
> It does not retry external and selenium tests.

True.  Those tests don't use testlib.test_main and need to have their own retry logic.

**Comment by mvollmer** [comment]
> Also can you describe how can I see the new logs.html locally? Thanks :)

Something like this:

```
# mkdir XXX; cd XXX
# curl -k -o log https://209.132.184.41:8493/logs/pull-12588-20190816-125858-c58f6de8-cockpit-project-cockpit--debian-testing/log
# curl -k -o log.html https://raw.githubusercontent.com/cockpit-project/cockpit/c58f6de88b2f1f655a95c2f63bf7029522a73e7e/bots/task/log.html
# python3 -m http.server &
# xdg-open http://localhost:8000/log.html
```

**Comment by mvollmer** [comment]
I have fixed log.html to not get confused about retries when collapsing/expanding panels.  We need to keep the HTML ids unique. This was already broken on master for a long time.

**Comment by mvollmer** [comment]
Yay, looks like all the Cockpit tests passed on first try.

**Comment by mvollmer** [comment]
> semaphore fails

Fixed!  Thanks for spotting that in the sea of red.

**Pull request merged**
