### PR TITLE
Typofix "Kofferraum"

### PR DESCRIPTION
**Pull request by derkahless**
Change
msgstr "Am Kofferraum montieren"
to
msgstr "Beim starten einhängen"

Kofferraum is a cars trunk :)

### CODE REVIEW

**Comment by marusak** [comment]
Thank you for this contribution!
This however (also) needs to be updated in [zanata](https://fedora.zanata.org/iteration/view/cockpit/master/languages/de?dswid=-3666) otherwise on the next refresh it is going to be rewritten back.

I cannot update it in Zanata (not for German). Either someone who is in german translator group can do it (If you would be interested [how to become german translator](https://fedoraproject.org/wiki/L10N/Translate_on_Zanata#Find_your_language_team_and_join_in)) or someone who manages cockpit project in zanata. I think both of these hats wears @martinpitt. Or a few days ago @stefanleh become translator.

**Comment by derkahless** [comment]
I'm new to all of this github stuff.
Trying to figure out how to contact them. :)

**Comment by stefanleh** [comment]
Hi, iv'e changed it to "beim Start einhängen". Hope thats fine. Greetings, Stefan

**Comment by derkahless** [comment]
Nice, thx :)

**Comment by marusak** [comment]
Thanks both of you! :)

**Pull request closed without merging**
