### PR TITLE
Use rpmspec

### PR DESCRIPTION
**Pull request by marusak**
This PR introduces `rpmspec` for parsing of build requires from spec file. It can deal with macros and in general is more robust. To parse only really needed build requires an opsys-release is needed. I parse this from image name.

Also in this PR I picked commit by @KKoukiou from  #12128 since it needs image refresh as well.

This PR should fix building on rhel-8-0, so fixing #12110.

Note to myself: When picking up images add closes to both my and @KKoukiou commits.

Refreshing rhel-8-0 for obvious reason, 7.7 for @KKoukiou and to see if it picks kubernetes build requires (and does not pick these requires for rhel-8-0), fedora-30 and centos-7 to see if those work as well. If something else should be tried, please feel free to add it to the list.

 * [x] image-refresh rhel-8-0
 * [x] image-refresh rhel-7-7
 * [x] image-refresh rhel-8-1
 * [x] image-refresh fedora-30
 * [x] image-refresh centos-7

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-9.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-143838/

**Comment by cockpituous** [comment]
image-refresh rhel-8-0 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-0-20190622-150000

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-151818/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-151414/

**Comment by cockpituous** [comment]
image-refresh rhel-7-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-7-20190622-154242

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-151414/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-154141/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-153131/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-154040/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-154040/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-10.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-161010/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-162323/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-162323/

**Comment by martinpitt** [comment]
The rebuild tasks fail uploading to the image server, due to https://bugs.centos.org/view.php?id=16208 . I don't want to spend much time now, but I temporarily disabled the public image server and bots. Then the uploads ought to be done by and go to the internal one.

**Comment by martinpitt** [comment]
I added a refresh task for rhel-8-1 as well.

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-185757/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-185757/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-05.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-192929/

**Comment by cockpituous** [comment]
image-refresh rhel-8-1 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-1-20190622-194848

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-192929/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-194444/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-194444/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-200101/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-12130-20190622-200101/

**Comment by martinpitt** [comment]
Ah, thinko, bots/image-upload doesn't upload to the RedHat store by default, only image-refresh does based on the image type.

I'm currently debugging why our fallback image server doesn't work:
```
curl -vvv --cacert bots/images/files/ca.pem --fail --resolve cockpit-tests:8493:209.132.184.41 https://cockpit-tests:8493
[...]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, decrypt error (563):
* error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
* Closing connection 0
curl: (35) error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
```

**Comment by martinpitt** [comment]
I fixed our alternate image store. Insert coin and try it again!

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-9.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190623-084141/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-05.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190623-084949/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190623-085555/

**Comment by cockpituous** [comment]
image-refresh fedora-30 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-30-20190623-101111

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://209.132.184.41:8493/logs/image-refresh-12130-20190623-085555/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-04.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190623-124646/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190623-123636/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190623-125252/

**Comment by martinpitt** [comment]
@marusak: Nice, the last built image is currently being uploaded. So that should cover all rebuilds, happy pushing/testing!

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190623-153535/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-12130-20190623-153939/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20190623-160404

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://209.132.184.41:8493/logs/image-refresh-12130-20190623-153939/

**Comment by martinpitt** [comment]
@marusak: This needs a rebase due to some conflict with the "drop ovirt" PR, sorry. Also, not sure why image-download is acting up on the fallback image server, I'll have a look.

**Comment by martinpitt** [comment]
A local  `bots/image-download fedora-30` downloads it from 209.132.184.41:8493/ just fine.. Same when I try it from the container on the infra. So, retrying.

**Comment by martinpitt** [comment]
The cockpit-ssh failure on [rhel-8-1](https://209.132.184.41:8493/logs/pull-12130-20190624-072020-c6c0b0fe-verify-rhel-8-1/log.html) looks real.  libssh 0.8.91 landed in 8.1 recently, and apparently it has a regression. This version isn't in Fedora/bodhi yet.

**Comment by martinpitt** [comment]
@marusak, @KKoukiou : To avoid blocking/entangling this, I think it'd be acceptable to drop the 8.1 rebuild from this PR, and land the rest.

**Comment by KKoukiou** [comment]
> @marusak, @KKoukiou : To avoid blocking/entangling this, I think it'd be acceptable to drop the 8.1 rebuild from this PR, and land the rest.

Makes sense. My changes don't affect the 8-1 image.

**Comment by marusak** [comment]
dropped 8-1 rebuild. Triggered only f-30 tests, as only some of those were not yet successful.

**Comment by martinpitt** [comment]
This [fedora-30 failure](https://209.132.184.41:8493/logs/pull-12130-20190624-134040-d1378408-verify-fedora-30/log.html#85) also looks like a major issue -- @kkoukiou, there are now *two* myPoolTwo pools, one active, one inactive. That maybe some regression/behaviour change in a newer libvirt from this f30 refresh? This also seems to genuinely break cockpit-podman. :crying_cat_face:

**Comment by martinpitt** [comment]
Thanks @marusak for the updates, this looks good now! Removing needswork.

There are a few invalid tests (like "cockpit/fedora-30/chrome" without a project or "verify/rhel-8-0cockpit/centos-7@cockpit-project/starter-kit"). I'll trigger the right ones and retry the podman and edge flakes.

**Comment by martinpitt** [comment]
[one edge failure](https://209.132.184.41:8493/logs/pull-12130-20190627-082323-932d6402-selenium-edge/log.html#48), retrying *again*

**Comment by martinpitt** [comment]
[different edge failure](https://209.132.184.41:8493/logs/pull-12130-20190627-095858-932d6402-selenium-edge/log.html) now, good enough.

**Pull request merged**
