### PR TITLE
remove various build cruft/hacks

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**

### CODE REVIEW

**Review by martinpitt — DISMISSED** [review]
Nice cleanup, thanks!

packit/c9s is a network flake. Let's wait for the other results, we probably don't need to restart that one.

**Comment by allisonkarlitskaya** [comment]
```
2021-12-13T08:49:12.1361630Z ==4662== Warning: unimplemented fcntl command: 1033
2021-12-13T08:49:12.1446098Z test-jsonfds: src/common/cockpitjsonprint.c:227: cockpit_json_print_finish_memfd: Assertion `r == 0' failed.
2021-12-13T08:49:12.4184637Z timeout: the monitored command dumped core
2021-12-13T08:49:12.4187605Z Aborted
2021-12-13T08:49:12.4192643Z ERROR: test-jsonfds process failed: 134
```

The version of valgrind in the unit-tests container is `valgrind-3.16.1` and the `git-describe` for the commit in question is `VALGRIND_3_15_0-443-gdec305065` so I would have assumed it was included... :/

**Comment by allisonkarlitskaya** [comment]
So bookworm isn't coming out any time soon, and unless we want to switch to testing, or another distribution, or request a valgrind SRU, I guess we're stuck here.  I'll drop the memfd hack removal for now.

**Review by martinpitt — APPROVED** [review]
Too bad.. but I actually wouldn't mind to change our unit-tests container to Debian testing. This would also allow us to enable `-fanalyzer`.

**Comment by allisonkarlitskaya** [comment]
> Too bad.. but I actually wouldn't mind to change our unit-tests container to Debian testing. This would also allow us to enable `-fanalyzer`.

Let's see what  #16719 says.

**Pull request merged**
