### PR TITLE
bots: Drop firewalld hack again on rhel-x

### PR DESCRIPTION
**Pull request by martinpitt**
The bug got fixed in latest images.

 * [x] image-refresh rhel-x

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-s2kkv.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9828-20180814-055252/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9828-20180814-055252/

**Comment by martinpitt** [comment]
Image build failed with `No match for argument: atomic`.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-l4g91.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9828-20180814-064949/

**Comment by cockpituous** [comment]
image-refresh rhel-x done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-x-20180814-072828

**Comment by martinpitt** [comment]
Fixed the test failures, now everything passes locally.

**Pull request merged**
