### PR TITLE
Various test fixes

### PR DESCRIPTION
**Pull request by martinpitt**
- "test: Increase timeout for resizing storage" fixes [this common flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19297-20230908-145603-5b9e5645-ubuntu-2204-storage/log.html#46) (this is *not* known issue #5090!)
 - "test: Increase timeout for changing system time" fixes [this common flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19246-20230908-090032-b82c60f7-fedora-38-firefox-other/log.html#104-2)
- "test: Robustify TestClient" fixes [this common flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19286-20230906-081844-3e7ba9e2-fedora-38-devel/log.html#13-2)
- "test: Fix unpin check in TestServices.testBasic" fixes [this flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19304-20230911-052007-aabbad2c-ubuntu-stable-other/log.html#102-2)

### CODE REVIEW

**Comment by martinpitt** [comment]
Haha, [amazing bug](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19304-20230911-044951-7f22c408-fedora-38-firefox-other/log.html#86-2). Fixed.

**Comment by martinpitt** [comment]
Hmm, I'm not sure any more that I like the verbose/trace thing, it makes it rather hard to scroll around in test logs. I'll revert that. But this also found some new flakes, [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19304-20230911-052007-aabbad2c-ubuntu-stable-other/log.html#102-2) is easy to fix and [this goes on my todo list](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19304-20230911-052007-aabbad2c-fedora-39-networking/log.html).

**Comment by martinpitt** [comment]
Nice, all tests other than f38/devel went green on first try. [f38/devel](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19304-20230911-061219-b3442096-fedora-38-devel/log.html#303) has one old and one new failure now, looking.

**Review by jelly — DISMISSED** [review]

**Comment by martinpitt** [comment]
Oh, I understand [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19304-20230911-093650-f9c76792-fedora-38-devel/log.html#348) -- we disable preloading for devel builds. Fixed.

**Pull request merged**
