### PR TITLE
Build package and lib javascript unit tests using webpack

### PR DESCRIPTION
**Pull request by stefwalter**
We automatically generate HTML files, and build the javascript and CSS for everything needed in the test using webpack.
    
This doesn't affect any code in src, since that's not webpack related.

### CODE REVIEW

**Comment by stefwalter** [comment]
Blocked on #5182

**Comment by stefwalter** [comment]
No String.prototype.repeat() function in all node versions ... will fix.

**Comment by stefwalter** [comment]
Removed use of repeat function.

**Comment by larskarlitski** [comment]
Great work. Thanks!

**Pull request merged**
