### PR TITLE
Image refresh for fedora-testing - fixed in PR #8297, close after that

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-testing-20171017-141212

**Comment by petervo** [comment]
@martinpitt looks like auto updates needs adjusting for fedora-testing.

**Comment by martinpitt** [comment]
The logs are gone by now, and the image from October is outdated, so rebuilding image.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-72s98.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7849-20171218-093636/

**Comment by cockpituous** [comment]
Task threw an exception: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7849-20171218-093636/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-kxd9f.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7849-20171218-102121/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-t78lg.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7849-20171218-125757/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-p0xn8.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7849-20171218-125757/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-testing-20171218-133131

**Comment by martinpitt** [comment]
dnf-automatic is missing on the image. Fix in #8297. Don't close this yet, as otherwise the bots will immediately open a new one.

**Pull request closed without merging**
