### PR TITLE
machines: redesign VM error messages

### PR DESCRIPTION
**Pull request by mareklibra**
Rendering of error message for a virtual machine has been improved.

The user can now
- dismiss the message
- show farther details by clicking on `more` button

Fixes: https://github.com/cockpit-project/cockpit/issues/7978

### CODE REVIEW

**Comment by mareklibra** [comment]
There is a change compared to the design within #7978: the user can click to expand for farther details:

01_errormsgs

02_errormsgs

**Comment by petervo** [comment]
Looks good to me, anyway we can add a test for it?

**Comment by mareklibra** [comment]
@petervo , test is added

**Comment by mareklibra** [comment]
@andreasn , can you have a look, please?

**Pull request merged**
