### PR TITLE
storaged: remove unused onlyNarrow option Storage menu's

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Review by KKoukiou — COMMENTED** [review]
Are you sure it's not used? 
```js
kkoukiou@fedora:~/repos/cockpit$ git grep show-only-when-narrow pkg/storaged/
pkg/storaged/storage-controls.jsx:    <DropdownItem className={(onlyNarrow ? "show-only-when-narrow" : "") + (danger && !excuse ? " delete-resource-dangerous" : "")}
pkg/storaged/storage-controls.jsx:        <Dropdown className={onlyNarrow ? "show-only-when-narrow" : null}
pkg/storaged/storage.scss:  .show-only-when-narrow {
```

**Review by mvollmer — CHANGES_REQUESTED** [review]
Thanks! What an unexpected gift. :-)

There is also `onlyWide` and the `show-only-when-wide` class. They can be removed as well.

**Comment by mvollmer** [comment]
> Are you sure it's not used?

Yes, no code passes the `onlyNarrow` or `onlyWide` properties anymore to the various storage controls.

After the redesign, the Storage page uses the `useIsNarrow` hook to react to layout changes.

**Review by mvollmer — APPROVED** [review]
Thanks!

**Pull request merged**
