### PR TITLE
css: Remove unused PF component imports

### PR DESCRIPTION
**Pull request by garrett**
I removed as many `@import`s as I could and re-added the imports where things were broken.

I'm adding this as a draft to see what the tests (especially pixel tests) do.

### CODE REVIEW

**Comment by garrett** [comment]
This should hopefully fix #17613.

The remaining imports would serve as a guide for where we might want to port to PF React components. (It might not always be possible to port, but I'm sure some of them would be straightforward.)

**Comment by martinpitt** [comment]
This [pixel diff failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17614-20220801-150332-5d05b4ce-fedora-36/pixeldiff.html#TestFirewall-testAddServices-firewall-add-services-to-zone-modal) looks genuinely broken, it's what you described in #17615.

And we ran into that weird [storage dialog](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17614-20220801-150332-5d05b4ce-fedora-36/pixeldiff.html#TestStorageUsed-testUsed-popover) jumping close button issue again. Unrelated to this PR.

**Comment by martinpitt** [comment]
I'm not convinced any more that the regression is due to this PR. It failed the same way in https://github.com/cockpit-project/bots/pull/3685 which has absolutely nothing to do with the firewall page. Retrying once to compare results.

**Comment by garrett** [comment]
I'm marking this as blocked. I don't trust this getting merged until we fix the pixel tests. I don't want another regression.

**Comment by martinpitt** [comment]
The pixel test fixes landed, and I pushed a clean rebase. This ought to work now.

**Review by martinpitt — APPROVED** [review]

**Comment by martinpitt** [comment]
Petunia bowl.. [oh no, not again!](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17614-20220803-052318-bdd91803-fedora-36/log.html#80). This PR doesn't even touch the firewall. But it failed in PR #17617 again as well, even though it succeeded three times in #17616.

**Comment by martinpitt** [comment]
The most recent cockpit test runs mysteriously succeeded now, including this one. :man_shrugging: Thanks @garrett!

**Pull request merged**
