### PR TITLE
Subscriptions: Use the new dialog behavior patterns

### PR DESCRIPTION
**Pull request by stefwalter**
This updates the subscriptions dialog to the new dialog behavior patterns.

This depends on #2225 and #2223

### CODE REVIEW

**Comment by stefwalter** [comment]
Setting needswork until dependencies merged.

**Comment by andreasn** [comment]
Seems to work as expected when I tested, but I would like to hear what @dperpeet thinks too.

**Comment by stefwalter** [comment]
Rebased. Depends on #2225

**Comment by stefwalter** [comment]
Rebased.

**Comment by dperpeet** [comment]
There are references to removed elements, specifically the updating spinner/message: [pkg/subscriptions/subscriptions.js](https://github.com/stefwalter/cockpit/blob/13c4583316d172fe1937793371f83b99b2c7aa52/pkg/subscriptions/subscriptions.js#L210) and in the [css](https://github.com/cockpit-project/cockpit/blob/6e58571197bc49d4c971fde5a3f1dc4352a01dfc/pkg/subscriptions/subscriptions.css#L52)
The function `action_in_progress` needs to be resolved using info on the new mechanism. This stems from the idea that registration should be a singleton.

**Comment by dperpeet** [comment]
Othat than that my manual testing went well, it works.

**Comment by stefwalter** [comment]
> The function action_in_progress needs to be resolved using info on the new mechanism.

Done.

**Pull request closed without merging**
