### PR TITLE
Image refresh for fedora-atomic

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-atomic
 * [x] image-refresh fedora-atomic

### CODE REVIEW

**Comment by marusak** [comment]
[this test](https://209.132.184.41:8493/logs/pull-11527-20190404-033939-512ea381-verify-fedora-atomic/log.html#269) failed already twice, lets give it one more chance.

**Comment by KKoukiou** [comment]
> [this test](https://209.132.184.41:8493/logs/pull-11527-20190404-033939-512ea381-verify-fedora-atomic/log.html#269) failed already twice, lets give it one more chance.

It's broken because of the change in the selects we did recently. We use now option element, before we were using underordered list. I will post a fix.

**Comment by KKoukiou** [comment]
> > [this test](https://209.132.184.41:8493/logs/pull-11527-20190404-033939-512ea381-verify-fedora-atomic/log.html#269) failed already twice, lets give it one more chance.
> 
> It's broken because of the change in the selects we did recently. We use now option element, before we were using underordered list. I will post a fix.

Oh, that was a Red herring. We didn't port this at all to the new selects. In fact locally in passes consistently for me. Retriggering?

**Comment by martinpitt** [comment]
@KKoukiou : I retried it again, still the same failure.

**Comment by KKoukiou** [comment]
> @KKoukiou : I retried it again, still the same failure.

Right, I can reproduce.(wondering if I forgot to use new new atomic the other day)
Anyway, it's because timesyncd service is not running, I am able to start it, but I guess it shoul be started by default. Checking

**Comment by KKoukiou** [comment]
Moving the check in the tests that timedated had ntp support bellow the cockpit login fixes the issue for me. However I don't understand why:
``` diff
$ git diff --cached
diff --git a/test/verify/check-system-info b/test/verify/check-system-info
index 8093d0d5f..4421a647e 100755
--- a/test/verify/check-system-info
+++ b/test/verify/check-system-info
@@ -282,10 +282,10 @@ class TestSystemInfo(MachineCase):
         # org.freedesktop.timedate1 instead of timedatex.
         m.execute("systemctl disable timedatex; systemctl stop timedatex; systemctl unmask systemd-timedated")
 
-        wait(can_ntp)
-
         self.login_and_go("/system")
 
+        wait(can_ntp)
+
         # Wait until everything is ready to go...
         b.wait_text_not("#system_information_systime_button", "")

```

**Comment by marusak** [comment]
So it seems that when we create `proxy` everything is undefined for a short bit. Let`s have
```
   var client = cockpit.dbus('org.freedesktop.timedate1');                     
   var timedate = client.proxy();
```
and calling straight away `timedate.NTP` (or any other property) is `undefined` on all OSes. The difference between `f30` and this `f-atomic` is that for how long the values are undefined. I used this silly piece of code:
```
    var client = cockpit.dbus('org.freedesktop.timedate1');                     
    var timedate = client.proxy();
    var self = this;                                 
    self.timedate = timedate;                                                                                                           
    self.count_i = 0;                                                           
    self.count = function argh() {                                              
        if (self.timedate.CanNTP === undefined) {                               
            self.count_i++;                                                                                               
            window.setTimeout(function() {                                      
                self.count();                                                   
            }, 500);                                                            
        } else {                                                                
            console.warn("~~~~~~~~~~~~~~~~~~~~~~~~~~");                         
            console.warn(self.count_i);                                         
            console.warn("~~~~~~~~~~~~~~~~~~~~~~~~~~");                         
        }                                                                       
    };    
```
This code for `f30` prints `1` or very few times `2` but for `fedora-atomic` it is on average `4`, very few times went to `3`. I know this is stupid code, but I think it demonstrates the problem. And yes, when I look into what the testing machine is doing, between 2nd and 3th recursion of this function the dialog is opened. And when the dialog is opened the values of `self.timedate` are used - which for f-atomic are still all `undefined`.

**Comment by martinpitt** [comment]
@marusak : That's correct. Like pretty much everything else, that proxy is async, and only starts to have correct data once it sends the initial `changed` signal. I haven't looked too deeply at the code, but I guess the problem is that the test opens the dialog *before* the proxy is initialized, and thus the dialog shows the state as "manual". This fits perfectly with why `wait(can_ntp)` *after* logging and showing the page fixes it. So this is IMHO a good enough workaround for the image refresh, feel free to commit that @KKoukiou.

However, this just hides a real bug. I think the time link should be disabled initially, and only enabled once we get a first status from the proxy. Then the test can just wait on the link to become enabled.

**Comment by martinpitt** [comment]
> feel free to commit that @KKoukiou.

I. e. if you commit this, please add a `# HACK:` comment that explains the race.

**Comment by marusak** [comment]
> I guess the problem is that the test opens the dialog before the proxy is initialized

correct, that was what I was trying to say

> This fits perfectly with why wait(can_ntp) after logging and showing the page fixes it. So this is IMHO a good enough workaround for the image refresh, feel free to commit that @KKoukiou.

Oh, right, I did not realize that after login we are at the right (system) page. Does executing `busctl get-property org.freedesktop.timedate1 /org/freedesktop/timedate1 org.freedesktop.timedate1 CanNTP` somehow affect the proxy or it just buys us just enough time before we open the dialog?

**Comment by martinpitt** [comment]
@marusak : It would have an influence as it systemd-activates the service (it's started on demand), so that the service proxy doesn't have to wait for "something else" to activate it, but it would return pretty quickly with the "running" state.

**Comment by KKoukiou** [comment]
> Thanks!

@martinpitt sorry, I had to re-push since I forgot the Closes + I had a typo in the comment.

**Comment by martinpitt** [comment]
The constant failure of cockpit-ostree is worrying, this needs to be investigated.

**Comment by marusak** [comment]
Lets retry it once more time, if the [fail](https://209.132.184.41:8493/logs/pull-11527-20190411-202626-5826fa24-cockpit-project-cockpit-ostree-cockpit-fedora-atomic/log) is the same, I cannot reproduce it yet locally.

**Pull request merged**
