### PR TITLE
Create a lib directory for bundled components

### PR DESCRIPTION
**Pull request by stefwalter**
These are components that are bundled into other packages, and used during development and not installed.
    
This is the part of a bigger move to having a base bundle which only contains completely stable API, and per package bundles which contain varying components.
    
Although the changes to Makefile.am are pretty verbose right now, the plan is that webpack or other build tools will solve that in later pull requests.
    
The debuginfo for the React related code was already not working, so this pull request is not a regression in that regard.

### CODE REVIEW

**Comment by stefwalter** [comment]
Rebased

**Comment by larsu** [comment]
I wonder why, but this doesn't work in my setup (building in-tree). It tries to load 

http://localhost:9090/cockpit/@localhost/performance/cockpit-components-dialog.js and
http://localhost:9090/cockpit/@localhost/performance/react.js,

even though it should get them from the bundle.

**Comment by dperpeet** [comment]
after cleaning out `/usr/share/cockpit` I get an oops on the system page - requirejs error in base1/bundle

**Comment by stefwalter** [comment]
@dperpeet Did you run 'make clean'? Whenever there's heavy changes to Makefile.am in the build system, it's necessary to perform that step.

**Comment by dperpeet** [comment]
> @dperpeet Did you run 'make clean'? Whenever there's heavy changes to Makefile.am in the build system, it's necessary to perform that step.

I cleaned everything, but the system page opens with an Ooops: `Error: Script error for: performance/cockpit-components-dialog`

**Comment by stefwalter** [comment]
Okay, made things more ugly and they should cover those cases for now.

**Comment by dperpeet** [comment]
check fails:
```
make[1]: Entering directory `/home/travis/build/cockpit-project/cockpit'
./tools/check-dist cockpit-0.108.x
cockpit-0.108.x/pkg/systemd/cockpit-components-terminal.js
cockpit-0.108.x/pkg/selinux/cockpit-components-listing.js
cockpit-0.108.x/pkg/tuned/cockpit-components-dialog.js
Refusing to distribute minified files without original
```

**Comment by stefwalter** [comment]
Fixed the 'make dist' problems.

**Comment by dperpeet** [comment]
more check errors:
```
ERROR: files left in build directory after distclean:
./pkg/systemd/cockpit-components-terminal.min.js
./pkg/selinux/cockpit-components-listing.min.js
./pkg/tuned/cockpit-components-dialog.min.js
make[1]: *** [distcleancheck] Error 1
make[1]: Leaving directory `/home/travis/build/cockpit-project/cockpit/cockpit-0.108.x/_build'
make: *** [distcheck] Error 1
```

Also, I still get an oops (after cleaning everything):
`Error: Script error for: performance/cockpit-components-dialog` in `https://192.168.122.243:9090/cockpit/$ccb4664f0b07dc8a6908a1725d7628c47b714b3e/base1/bundle.js`

**Comment by stefwalter** [comment]
> more check errors:

Lets see if those are fixed now.

**Comment by dperpeet** [comment]
same error

**Comment by dperpeet** [comment]
works for me now

**Pull request closed without merging**
