### PR TITLE
kubernetes: Topology View

### PR DESCRIPTION
**Pull request by stefwalter**
Just a simple force directed graph.

Sharing code with Openshift for the details pane, via this project: https://github.com/kubernetes-ui

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #2345

**Comment by stefwalter** [comment]
Needs some more work:

 * Legend
 * Clicking on a node should show details side pane.

screenshot from 2015-05-27 23-05-09

**Comment by stefwalter** [comment]
This doesn't display "processes", "images" or "clusters" like https://github.com/GoogleCloudPlatform/kubernetes/pull/8716 does. That's by design.

**Comment by stefwalter** [comment]
Rebased.

**Comment by stefwalter** [comment]
Some fixing needed:
 * Dashboard page margins are shot.

**Comment by mvollmer** [comment]
topology.css is not installed.

**Comment by mvollmer** [comment]
After selecting an object, there is no way to unselect everything so that one can read the legend again.

**Comment by mvollmer** [comment]
Selecting an object to see details will also make it stick in its place and there is no way to unstick it again.

**Comment by mvollmer** [comment]
(I guess the graph is only for show right now, and we replace it with something else, right?)

**Comment by stefwalter** [comment]
> topology.css is not installed.

Fixed.

> After selecting an object, there is no way to unselect everything so that one can read the legend again.

Fixed, clicking background does this.

> Selecting an object to see details will also make it stick in its place.

Fixed, now you have to move to stick something.

> and there is no way to unstick it again.

Drag it off the screen.

> (I guess the graph is only for show right now, and we replace it with something else, right?)

I think of it as the "guts" view. Not sure how useful it will be long term.

When it comes down to it: Kubernetes is about automation. In theory, all user-servicable operations should be able to be performed  from the dashboard. All the other pages are about meddling with that automation and inspecting it. In theory superfluous, but reality usually doesn't play along nicely.

**Comment by stefwalter** [comment]
When built as a bundle, I get this error: "Error: [$injector:unpr] http://errors.angularjs.org/1.3.14/$injector/unpr?p0=eProvider%20%3C-%20e%20%3C-%20kubernetesObjectDescriberDirective

**Comment by stefwalter** [comment]
Fixed the above angular error. The issue was a problem in the openshift code: https://github.com/kubernetes-ui/object-describer/pull/20

**Comment by eparis** [comment]
The kuberenetes and kubernetes-ro services have a nil selector. However in the topo view they match against everything in the namespace, instead of against nothing.

**Comment by stefwalter** [comment]
Another exception, harder to figure out:

Error: [$injector:unpr] http://errors.angularjs.org/1.3.14/$injector/unpr?p0=eProvider%20%3C-%20e

**Comment by stefwalter** [comment]
Another exception:

Uncaught TypeError: Cannot read property 'request' of null

**Comment by stefwalter** [comment]
> Error: [$injector:unpr] http://errors.angularjs.org/1.3.14/$injector/unpr?p0=eProvider%20%3C-%20e

Another object-describer bug: https://github.com/kubernetes-ui/object-describer/pull/20

**Comment by stefwalter** [comment]
> The kuberenetes and kubernetes-ro services have a nil selector. However in the topo view they match against everything in the namespace, instead of against nothing.

Fixed.

**Comment by bgrant0607** [comment]
cc @jackgr

**Comment by stefwalter** [comment]
@bgrant0607 @jackgr By the way the code here has moved to https://github.com/kubernetes-ui/topology-graph and has is being reused by a couple other projects.

**Pull request closed without merging**
