### PR TITLE
test: Code coverage for the PR diff

### PR DESCRIPTION
**Pull request by mvollmer**
https://cockpit-logs.us-east-1.linodeobjects.com/pull-17418-20220602-161656-1dd16e0c-fedora-36-devel/Coverage/work/bots/make-checkout-workdir/github-pr.diff.gcov.html

### CODE REVIEW

**Comment by mvollmer** [comment]
Diff coverage for the diff is here, for example: https://cockpit-logs.us-east-1.linodeobjects.com/pull-17418-20220601-172147-f32c2ad9-fedora-36-devel/Coverage/work/bots/make-checkout-workdir/github-pr.diff.gcov.html

**Comment by martinpitt** [comment]
This is nice! An important step for providing this as direct feedback on PRs. This is harmless to land without too much logic review, but not with the "DBG" commit. Moving to draft for now, please move back to "ready" and ask for review once this gets dropped.

**Comment by marusak** [comment]
Looks awesome! Now it is rather hidden but I know that we want to promote this in annotations or so. Agree with pitti that it is landable as soon as you drop the DBG commit.

**Comment by martinpitt** [comment]
As @mvollmer is on PTO, I dropped the DBG commit.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
