### PR TITLE
machines: Use iframe download workaround on all browsers

### PR DESCRIPTION
**Pull request by martinpitt**
Chromium 65 refuses to download the generated .vv file as well now:

```
CDP: {"source":"other","level":"error","text":"Refused to frame '' because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1527156936689.5,"url":"http://127.0.0.2:9091/cockpit/$0021b50df7588e9af173d46d5eda7bdac26be09b97f000fec7a55dda9228c356/machines/machines.js","lineNumber":6126}
CDP: executionContextDestroyed 11
```

And after that one just gets a blank page with a sad face. Use the
workaround of wrapping this in a dynamic iframe on all browsers now.

 - [ ] drop `@expectedFailure` marking once PR #9283 lands

### CODE REVIEW

**Comment by martinpitt** [comment]
Example log with Chromium 65: https://fedorapeople.org/groups/cockpit/logs/pull-9225-20180524-080505-04a1e0d2-verify-rhel-7-5/log.html#26

**Comment by mareklibra** [comment]
Unfortunately, this generates an extremely ugly file download dialog (the filename is hacked there).

I'm wondering if we can
- find a better HTML/JavaScript way (I don't know it)
- generate the content and let it be served via cockpit-ws
- ease CSP for this particular case

I think there are many ways how to implement the "cockpit-ws approach", not sure if any reasonable.

An idea: the `cockpit-ws` can serve content of a pre-defined directory, i.e. under `/tmp/cockpit` or whatever. There will be no way to list the content, proper filname must be requested.

If so, a plugin (like `/pkg/machines`) can just generate a file of sufficiently long name consisting of random characters. 
The browser will then be navigated to this content. 
The file will be removed either by the plugin (preferred) or after certain time-to-live period by cockpit-ws (as a backup).

**Comment by garrett** [comment]
Ordinarily, I'd recommend a data URI or using blob for generating a file on the fly, but I guess our CSP doesn't allow for this, right? (Or would it?)

**Comment by mareklibra** [comment]
> I guess our CSP doesn't allow for this

Exactly.

**Comment by martinpitt** [comment]
> Ordinarily, I'd recommend a data URI or using blob for generating a file on the fly, but I guess our CSP doesn't allow for this

It aims to; cockpit-machine's [manifest](https://github.com/cockpit-project/cockpit/blob/master/pkg/machines/manifest.json.in) has a custom C-S-P for that very reason. But it seems to have stopped with current Chromium and apparently never worked for Firefox.

So surely this is a quick hack to unbreak external consoles for Chromium. But I don't know a good *and* quick solution, I'm afraid.

**Comment by martinpitt** [comment]
I'm marking this test as expected failure in PR #9283 , as this is genuinely broken right now. Once this lands, this PR should be updated to remove the `@expectedFailure` again. If the test succeeds, it will appear as failed otherwise :-)

**Comment by mareklibra** [comment]
Does the workaround above with involving cockpit-ws make sense?
Or any idea how to ease CSP for that?

**Comment by martinpitt** [comment]
> Does the workaround above with involving cockpit-ws make sense?

Remember, the administered machine isn't necessarily the same as the one that runs ws, so all data and actions need to happen on/from the JavaScript code. So I'm not sure if that workaround would also work for that scenario.

> Or any idea how to ease CSP for that?

I did play around with this for a while, and by my understanding of C-S-P it should already work. So I'm out of ideas here :-(

**Comment by mareklibra** [comment]
> the administered machine isn't necessarily the same as the one that runs ws,

Good point. I think the idea can be extended even for this scenario, but would complicate things.


>> Or any idea how to ease CSP for that?

> I did play around with this for a while, and by my understanding of C-S-P it should already work. So I'm out of ideas here :-(

Similar experience.

To move forward, let's merge this and file new issue to rework once a solution is found. I still believe there must be a way via the CSP. 
I like that the code is just commented out, revert will be easier.

Filing https://github.com/cockpit-project/cockpit/issues/9338 to track this.

**Comment by martinpitt** [comment]
All machines tests succeeded, remaining few are the currently known broken ones on our infra.

**Pull request merged**
