### PR TITLE
kubernetes: Display status icon for services and nodes

### PR DESCRIPTION
**Pull request by stefwalter**
The design for this is described in the basic dashboard feature page.

https://github.com/cockpit-project/cockpit/wiki/Feature:-Kubernetes:-Basic-Dashboard

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #2252 and #2248

**Comment by stefwalter** [comment]
Testing info:

 * Add a bad node to kubernetes, like the example. Set a bad ip address in the ```node.json``` file

```
$ kubectl create -f pkg/kubernetes/examples/node.json
```
 * The node should be listed with spinner first, while waiting, then fail after a few minutes when Kubernetes gives up waiting.
 * Deploy a new service, you should see spinners as the containers start up.
 * Increase replicas on a service, you should see spinners as the containers  start up.

**Comment by stefwalter** [comment]
Rebased.

**Comment by mvollmer** [comment]
The spinner is behind the edit button, and only visible when the edit buttons are hidden.

Also, its animation is really jerky.

**Comment by mvollmer** [comment]
> Also, its animation is really jerky.

That was some local effect.  It doesn't happen anymore.

**Comment by stefwalter** [comment]
> The spinner is behind the edit button, and only visible when the edit buttons are hidden.

Yes, this is by design. You can see similar UI on the containers page in Cockpit.

**Comment by stefwalter** [comment]
Rebased.

**Pull request closed without merging**
