### PR TITLE
Image refresh for ubuntu-stable

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for ubuntu-stable
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by marusak** [comment]
Needs to rebase to master since #12367 changed tests names

**Comment by martinpitt** [comment]
rebased

**Comment by martinpitt** [comment]
[testRaid failure](https://209.132.184.41:8493/logs/pull-12396-20190723-093434-bad0ef5b-cockpit-project-cockpit-ubuntu-stable/log), retrying.

@marusak: Where are my .html logs? :-)

**Comment by martinpitt** [comment]
@marusak: HTML logs fixed in PR #12398.

**Comment by martinpitt** [comment]
Only testResizeXfs flaked now, together with the previous log all tests succeeded.

**Pull request merged**
