### PR TITLE
[no-test] bots: Add qemu-block-extra to debian-testing image

### PR DESCRIPTION
**Pull request by skobyda**
Preparation for: https://github.com/cockpit-project/cockpit/pull/11516

 * [x] image-refresh debian-testing
 * [x] image-refresh debian-stable

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-11997-20190604-104040/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-95wk3.
Log: https://209.132.184.41:8493/logs/image-refresh-11997-20190604-102727/

**Comment by martinpitt** [comment]
Confirmed that ubuntu-{1804,stable} images already have qemu-block-extra, so no need to rebuild these. But debian-stable doesn't and needs a rebuild.

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-testing-20190604-104848

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-11997-20190604-110808/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://209.132.184.41:8493/logs/image-refresh-11997-20190604-105555/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-stable-20190604-111919

**Comment by martinpitt** [comment]
Just in case you didn't see IRC:

Now please add a Closes # to your commit, grab the two bot-generated commits that update the image, and push them to the PR. I usually click on the branch, then the commit, append ".patch" to the URL, and download it, then git am. IMHO this is easier/faster than messing aound with git fetch/git cherry-pick, but you can do either of course.

Then trigger the two verify/debian-* tests (no need to run all of them)

**Pull request merged**
