### PR TITLE
users: debounce getLogins call

### PR DESCRIPTION
**Pull request by jelly**
On page load getLogins is called twice with the initial watch() callback. As getLogins is super expensive on RHEL/Fedora due to the lack of `passwd --all` debounce the call to improve the loading performance.

---

This should help a ton, otherwise there is also this hack https://github.com/cockpit-project/cockpit/pull/20086

### CODE REVIEW

**Comment by martinpitt** [comment]
[This may be related](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20087-20240222-173832-110f9378-rhel4edge-other/log.html#133)? I.e. missing an event? The arch failures are known flakes.

**Comment by jelly** [comment]
> [This may be related](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20087-20240222-173832-110f9378-rhel4edge-other/log.html#133)? I.e. missing an event? The arch failures are known flakes.

Don't think it is, but requires investigation on Monday.

**Review by martinpitt — APPROVED** [review]
OK -- but let's retry the test to be sure.

**Comment by jelly** [comment]
So this test fails pretty reliably on rhel4edge, some obversations:

* We don't wait on Robert to appear when we run `createUser`
* Logging the accounts info I get:
```
gecos
: 
"Robert Robertson"
gid
: 
1001
groups
: 
[]
home
: 
"/var/home/robert"
isLocked
: 
true
lastLogin
: 
null
loggedIn
: 
false
name
: 
"bin"
password
: 
"x"
shell
: 
"/bin/true"
uid
: 
1001
```

And then after a while:

```
gecos
: 
"Robert Robertson"
gid
: 
1001
groups
: 
[]
home
: 
"/var/home/robert"
isLocked
: 
false
lastLogin
: 
null
loggedIn
: 
false
name
: 
"robert"
password
: 
"x"
shell
: 
"/bin/true"
uid
: 
1001
```

Likely this is the curlpit as the accounts page matches on name? Either way the data is suspiciously different regarding the name so we are parsing something wrong.
```

**Pull request merged**
