### PR TITLE
bots: Fix candlepin image refresh

### LINKED ISSUE #11325: Image refresh for candlepin
Image refresh for candlepin
 * [ ] FAIL: image-refresh candlepin

### PR DESCRIPTION
**Pull request by martinpitt**
Even with Ansible 2.7 the ansible-role-candlepin playbooks don't work.
Reported as <https://bugzilla.redhat.com/show_bug.cgi?id=1688153>.

Cowboy-apply a fix to the playbooks to avoid a rubygem update. This
doesn't work any more with current gems, as these need ruby >= 2.3.

Fixes #11325

 * [x] image-refresh candlepin

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-trc09.
Log: https://209.132.184.41:8493/logs/image-refresh-11387-20190313-102424/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-nbf7k.
Log: https://209.132.184.41:8493/logs/image-refresh-11387-20190313-101616/

**Comment by cockpituous** [comment]
image-refresh candlepin done: https://github.com/cockpituous/cockpit/commits/image-refresh-candlepin-20190313-105353

**Comment by martinpitt** [comment]
@KKoukiou : Test flakes are unrelated, this only affects check-packagekit and check-subscriptions. Please let me know if you prefer turning this green, though.

**Comment by KKoukiou** [comment]
I managed to get the role running , please see commit here, https://github.com/KKoukiou/cockpit/commit/e81eaf929c319eae36d2ecd0fb0e624fd1beffa5
But it fails later, which makes me wonder about the following:

I notice the we use to run some tasks as root by specyfying , although the default user is candlepin, which in my case results in the following command failing the playbook:
/usr/bin/bundle install --without proton
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.

Second problem is that even when I ran as candlepin user I get the following error:
TASK [candlepin : Run Bundle install] ******************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/bundle install --without proton", "msg": "", "rc": 10, "stderr": "", "stderr_lines": [], "stdout": "Could not locate Gemfile\n", "stdout_lines": ["Could not locate Gemfile"]}

I am not familiar with ruby, so maybe this rings a bell?

**Comment by martinpitt** [comment]
@KKoukiou : Many thanks for figuring out how to correctly invoke that playbook! That error just seems like something is running in the wrong directory? The playbook switches back and forth between user and root, so maybe it's checking out the gems into some user dir and then does something as root?

**Comment by martinpitt** [comment]
And yes, this PR is a gross hack, let's not merge it if there's a better way. Thanks! :hugs:

**Comment by martinpitt** [comment]
PR #11394 is so much better (thanks @KKoukiou !), and sufficiently far along that we really want to go that route. Closing this one.

**Pull request closed without merging**
