### PR TITLE
kubernetes: Shared imagestream widget from registry-image-widgets

### PR DESCRIPTION
**Pull request by stefwalter**
Move the imagestream widgets into registry-image-widgets repository and start using them here.

Depends on: 
 - [x] https://github.com/openshift/registry-image-widgets/pull/3

### CODE REVIEW

**Comment by stefwalter** [comment]
Due tomorrow, so setting priority.

**Comment by stefwalter** [comment]
Fixed check-openshift for new tag name.

**Comment by stefwalter** [comment]
Rebased.

**Comment by petervo** [comment]
The look of the lock changed for me, I don't know if that intentional or not. But i merged anyways, but will need a follow up if it wasn't intentional.

**Comment by stefwalter** [comment]
@petervo No it wasn't intentional. Can you point out which parts changed?

**Comment by petervo** [comment]
This is what it looks like for me after this change. Before they looked more like the designs here: https://github.com/cockpit-project/cockpit-design/blob/master/kubernetes/image-registry.png?raw=true

untitled

**Pull request closed without merging**
