### PR TITLE
test: Add storaged 2.0 to Fedora 22 images.

### PR DESCRIPTION
**Pull request by mvollmer**
This doesn't work right now since COPR is down: http://status.fedoraproject.org/

Maybe it works when hubbot gets to it, so I mark it WIP to push it back in the queue.

### CODE REVIEW

**Comment by mvollmer** [comment]
COPR is back up, so let's go.

**Comment by stefwalter** [comment]
Shouldn't this be done in Fedora 23 images? We're going to be using storaged on Fedora 23 right? Not Fedora 22. I know that brings in a bunch of overhead for creating new images. But is that the reason that we're cramming this into our Fedora 22 testing?

**Comment by mvollmer** [comment]
> Shouldn't this be done in Fedora 23 images?

Yes, that would be the alternative, setting up F23/rawhide testing.  But wasn't there a chance that storaged 2.0 goes to F22?

I am fine either way.  (This PR is catching some regressions, so it is helpful in that sense at least. :)

**Comment by stefwalter** [comment]
> But wasn't there a chance that storaged 2.0 goes to F22?

Fedora 22 is frozen and going to be released shortly. I don't think we should ask them to do such a big change without really good reason.

**Comment by mvollmer** [comment]
> Fedora 22 is frozen and going to be released shortly. I don't think we should ask them to do such a big change without really good reason.

However, we might include storaged 2 in our backport COPR, as we used to do... But yeah let's wait until we have a plan.   I close this and start setting up rawhide testing.

**Pull request closed without merging**
