### PR TITLE
kubernetes: New listing patterns

### PR DESCRIPTION
**Pull request by petervo**
@stefwalter and @andreasn even though this is still a WIP can you take a look, at least at the playground examples (https://github.com/cockpit-project/cockpit/commit/ded9181e3ff6a5bbdc3e1bcd2b2b6703ada08ffd) to avoid too much churn on the all the html that needs to change.

@andreasn I'm going to need your help with the images listings.

### CODE REVIEW

**Comment by stefwalter** [comment]
Blocked on #4264

**Comment by petervo** [comment]
This is almost there except for the inner pages for the containers. @andreasn are you able to take a look, I have a couple questions for you related to the inner pages for containers and/or pods.

**Comment by petervo** [comment]
@andreasn, this is ready for review.

I'm marking as blocked as merging this will require some changes to the listing in setroubleshoot. Since @dperpeet is working on re-factoring that now this PR doesn't include any changes there. Once this is ready to merge we can see where that work is at and if it isn't ready yet, I can add a basic fix for setroubleshoot here.

**Comment by stefwalter** [comment]
Talked with @dperpeet. He'll make a new pull request in parallel with this that fixes setroubleshoot.

**Pull request closed without merging**
