### PR TITLE
WIP - add trigger-verify tool

### PR DESCRIPTION
**Pull request by mvollmer**
This is very crude. @dperpeet, would you like to take this further?

### CODE REVIEW

**Comment by stefwalter** [comment]
WIP so -> needswork

**Comment by dperpeet** [comment]
I'm working on the TODOs and will post a follow-up

**Comment by stefwalter** [comment]
At some point in the future, I'll convert this script into the scanning setup we've planned. Where we have a scanner that marks stuff as 'Not yet tested' and then check-verify --github=next just pulls from there.

**Comment by dperpeet** [comment]
continued in #3144

**Pull request closed without merging**
