### PR TITLE
test: Build cockpit/base on setup

### PR DESCRIPTION
**Pull request by petervo**
The openshift image regressed with #3940

### CODE REVIEW

**Comment by petervo** [comment]
bot: Image refresh for fedora-24

**Comment by petervo** [comment]
bot: Image refresh for openshift

**Comment by cockpituous** [comment]
Image creation for fedora-24 in process on host32-rack06.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-24-fce59116671515bbfd775fa3f06095e1da7ad266/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-fedora-24-fce59116671515bbfd775fa3f06095e1da7ad266

**Comment by stefwalter** [comment]
Needs image ids included next, right?

**Comment by petervo** [comment]
Waiting for the openshift build as well.

**Comment by petervo** [comment]
bot: Image refresh for openshift

**Comment by petervo** [comment]
bot: Image refresh for openshift

**Comment by petervo** [comment]
Closing to regenerate image

**Pull request closed without merging**
