### PR TITLE
Make the shell responsive to window size changes

### PR DESCRIPTION
**Pull request by stefwalter**
Do basic work to make the shell responsive to window size
changes. As we get smaller, reduce the size of the sidebar,
and cleanup how the navbar renders.

### CODE REVIEW

**Comment by stefwalter** [comment]
Test failure should be fixed by #2759

**Comment by petervo** [comment]
This looks good to me, @andreasn can you check to see if you are good with the behavior.

**Comment by stefwalter** [comment]
Rebased.

**Comment by andreasn** [comment]
I'll take it for a test ride!

**Comment by stefwalter** [comment]
Test failure caused by #2841

**Comment by stefwalter** [comment]
Rebased.

**Comment by stefwalter** [comment]
Latest test failure is unrelated and fixed here: #2852

**Comment by stefwalter** [comment]
r7 check-pages failure fixed in #2856 and check-docker fixed by #2854

**Comment by stefwalter** [comment]
The null when send test failure fixed by #2870

**Comment by andreasn** [comment]
Looks good to me!

**Pull request closed without merging**
