### PR TITLE
Fix msgstr detection logic

### PR DESCRIPTION
**Pull request by stefwalter**
Update translations from Fedora Zanata
 * [x] po-refresh

### CODE REVIEW

**Comment by cockpituous** [comment]
po-refresh in progress on bos-tasks-1343l.
Log: http://fedorapeople.org/groups/cockpit/logs/po-refresh-10437-20181026-050404/

**Comment by cockpituous** [comment]
po-refresh  done: https://github.com/cockpituous/cockpit/commits/po-refresh-20181026-050606

**Comment by cockpituous** [comment]
po-refresh in progress on bos-tasks-jpzkd.
Log: http://fedorapeople.org/groups/cockpit/logs/po-refresh-10437-20181026-051919/

**Comment by cockpituous** [comment]
po-refresh  done: https://github.com/cockpituous/cockpit/commits/po-refresh-20181026-052222

**Comment by cockpituous** [comment]
po-refresh in progress on bos-tasks-f5srf.
Log: http://fedorapeople.org/groups/cockpit/logs/po-refresh-10437-20181026-061212/

**Comment by cockpituous** [comment]
po-refresh  done: https://github.com/cockpituous/cockpit/commits/po-refresh-20181026-061414

**Comment by stefwalter** [comment]
This now works correctly according to the bot self-check above. And all the translated strings are included in the log.

**Comment by stefwalter** [comment]
Merged and triggered  #10444

**Pull request merged**
