### PR TITLE
Implement angular modal dialog patterns

### PR DESCRIPTION
**Pull request by stefwalter**
This works with the (awkward) UI bootstrap $modal implementation.
Currently there is a demo on the registry dashboard where this
can be tried out.

Documentation in dialogs.js

### CODE REVIEW

**Comment by stefwalter** [comment]
@sub-mod Could you take a look at this. This both uses the angular bootstrap ```$modal``` service, and then implements a ```<dialog>``` directive on top of that with the Cockpit dialog HIG behavior.

Unfortunately (as is often the case with angular) the $modal service is somewhat convoluted. I hope that the example code makes sense.

**Comment by stefwalter** [comment]
As @sub-mod reported on IRC, the install of dialog.js and the template file was broken when installing (worked fine when loading the registry module from git repo directory). Fixed now.

**Comment by stefwalter** [comment]
Fixed conflict with the ```<dialog>``` tag in Chrome (and Opera).

**Comment by stefwalter** [comment]
Whoops. Accidentally closed this.

**Comment by stefwalter** [comment]
Added select control example to this pull request instead of opening a new one.

**Comment by stefwalter** [comment]
Rebased.

**Comment by sub-mod** [comment]
LGTM

**Comment by stefwalter** [comment]
This is ready for further review and merging.

**Pull request closed without merging**
