### PR TITLE
package.json: Update xterm and bootstrap dependencies

### PR DESCRIPTION
**Pull request by Gundersanne**
New versions fix vulnerabilities pointed out by GitHub security alerts.

### CODE REVIEW

**Comment by martinpitt** [comment]
Thanks! Did you go through the pages to check for visual regressions due to the new bootstrap? (Particularly, tooltips, date pickers and so on)

**Comment by Gundersanne** [comment]
@pitti just noticed a visual difference; 

image
vs 
image

Same zoom level. Something with the padding on the user changed.

**Comment by Gundersanne** [comment]
bootstrap 3.4 without css changes:
image

bootstrap 3.3 (reference)
image

bootstrap 3.4 with css changes:
image

**Comment by Gundersanne** [comment]
bootstrap 3.4 without css changes:
image

bootstrap 3.3 (reference)

image


bootstrap 3.4 with css changes:
image

**Pull request merged**
