### PR TITLE
WIP: Debug openshift test

### PR DESCRIPTION
**Pull request by martinpitt**
With Chromium we often get failures on the infra in `TestOpenshift.testLogin()` where the expected brand is Openshift but the actual brand in the HTML is "Atomic Registry". Add some debugging output in the failure case to verify the configuration state of the container.

Using a separate PR for this so that I can only trigger the container test, without causing too much noise on #8069.

### CODE REVIEW

**Comment by martinpitt** [comment]
Yesterday evening I ran this test in a loop on a container on cockpit-11, but it didn't fail. That might have been because both of our sinks were broken and thus the infra was quiet and not loaded.

**Comment by martinpitt** [comment]
@petervo: That's interesting, so the container configuration seems to be correct:
```
lrwxrwxrwx. 1 1000000000 root 26 Dec  8 07:56 /container/os-release -> /container/openshift-brand
REGISTRY_ONLY=false
LoginTitle = Openshift Cockpit
```

**Comment by martinpitt** [comment]
Added debugging to `setup_brand()`, let's see what's in `window.localStore` and that it's called as expected.

**Comment by martinpitt** [comment]
So `setup_brand()` is being called and it apparently has the correct data in windowStore:

    setup_brand(id:  #index-brand , default_title: Openshift Cockpit ) windowStore:  {"NAME":"Openshift","ID":"kubernetes","PRETTY_NAME":"Openshift"}

**Comment by martinpitt** [comment]
Log from a successful run with the additional debugging: http://209.132.184.41/logs/pull-8233-20171208-120000-a5cd6334-container-kubernetes/log.html:
```
CDP: Security.certificateError {"eventId":1,"errorType":"ERR_CERT_AUTHORITY_INVALID","requestURL":"https://127.0.0.2:8744/oauth/authorize?client_id=cockpit-oauth-client&response_type=token&redirect_uri=http%3A%2F%2F127.0.0.2%3A30301%2F"} (ignoring)
> warning: XXXXXXX setup_brand(id:  #index-brand , default_title: Openshift Cockpit ) windowStore:  {"NAME":"Openshift","ID":"kubernetes","PRETTY_NAME":"Openshift"}
> warning: fatal: Logout Successful
> warning: fatal: AError
> warning: XXXXXXX setup_brand(id:  #index-brand , default_title: Openshift Cockpit ) windowStore:  {"NAME":"Openshift","ID":"kubernetes","PRETTY_NAME":"Openshift"}
Killing browser (pid 33257)
```
So `setup_brand()` is being called twice, with correct values. I pushed a commit to enable `opts.trace = True`, but apparently that didn't have any effect. I enabled this harder now, so let's run this another round.

**Comment by petervo** [comment]
@martinpitt This is really looking like a cache issue to me. The css is setting the wrong title, but a direct curl shows the correct css with the right title. I added code for force the XDG vars to use the tmp dir and triggered the tests 4 times without error. My best guess is that chrome doesn't respect HOME dir when figuring out the XDG values.

**Comment by martinpitt** [comment]
@petervo: Ooh, thanks for figuring that out! And indeed:

    $ git grep XDG_
    tests/Dockerfile:    XDG_CACHE_HOME=/build

that explains why the temporary `$HOME` isn't sufficient, as setting `$XDG_*` explicitly trumps `$HOME` (by design).

**Comment by martinpitt** [comment]
For sure I can reproduce the error now by setting `XDG_CACHE_HOME=/tmp/c` and running `testRegistry.testLogin` and then `testOpenshift.testLogin`. Closing, will push the fix to #8069.

**Pull request closed without merging**
