### PR TITLE
ovirt flake fix

### PR DESCRIPTION
**Pull request by Gundersanne**

### CODE REVIEW

**Comment by martinpitt** [comment]
Seems it still [failed on centos-7](https://fedorapeople.org/groups/cockpit/logs/pull-10044-20180911-151515-b2c70fd0-verify-centos-7/log.html#128)? 

@Gundersanne: For these fixes it's IMHO better to not retry, but see how tests look at the first iteration. It's enough for the kubevirt tests to succeed everywhere, any other failure can be ignored.

Thanks for looking into this!

**Comment by Gundersanne** [comment]
@martinpitt This fix is just for `check-ovirt`, `check-openshift` is not affected. So far I haven't seen `check-ovirt` fail.

**Comment by martinpitt** [comment]
@Gundersanne : Of course, my bad.. Nice! What's left to un-WIP this?

**Comment by Gundersanne** [comment]
@pitti a better commit message and removing the unused time import, I just wanted to run the test a good number of times before un-WIPping it :D

**Comment by martinpitt** [comment]
ovirt passed everywhere \o/ nice job!

**Pull request merged**
