### PR TITLE
kdump: Port page and dialog to ct-form-layout

### PR DESCRIPTION
**Pull request by martinpitt**
Also add missing `htmlFor` attributes to the labels in the location
configuration  dialog.

 - [x] Fix crash dump location span width on page
 - [x] Fix On/Off button height on page
 - [x] Fix "compress dumps" label vertical alignment
 - [x] Fix missing `key=` in SSH settings (spotted by test failure)
 - [x] Fix spinner alignment and service status line break (optional)
 - [x] Fix test case regression

### CODE REVIEW

**Comment by martinpitt** [comment]
This is a first attempt with a "clean" port to the new form CSS that drops all CSS fiddling. There are still two issues left (I created TODO checkboxes in the description):

Page on master:
kdump-page-old

Page on this PR: The On/Off button is too large, and the location label is too narrow and causes a line break.
kdump-page-new

Dialog on master:
kdump-old

Dialog on this PR: The compress checkbox label is misaligned with the left-hand label:
kdump-new

@garrett, do you want to fix some of that generically in  pkg/lib/form-layout.less, or should I fix this up locally in pkg/kdump?

**Comment by martinpitt** [comment]
@garrett: The vertical  label vs. span alignment issue is actually also visible in PR #10929

**Comment by garrett** [comment]
I found the following, which probably messes up the layout for checkboxes:

```css
.checkbox input[type="checkbox"] {
    margin-top: 7px;
}
```

My plan is to check out the branches and make fixes directly to the form-layout LESS. Then, these ports can be rebased on top and everything should work.

**Comment by martinpitt** [comment]
@garrett: I dropped this (locally), and it visually makes absolutely zero difference. So on the next push (when I fixed the tests) I'll clean it up, as less CSS is always better :)

But the vertical alignment between label and the text in the <span> is still wrong. At first sight we need to vertically center <spans> in the "control" column? (Assuming that the labels are vertically centered).

**Comment by martinpitt** [comment]
Pushed fixes for the missing "key" and the vertical alignment. Now looks better, I updated the screenshot in the above comment.

**Comment by martinpitt** [comment]
I added @garrett's form-control fixes, now the page looks fine. There is one remaining issue when enabling the service -- the spinner is slightly off. It still looks much better than on master (where the spinner and label move to the next line!), but while we are at it, we should fix that too.

**Comment by martinpitt** [comment]
The test case fails due to a most curious thing -- the conversion of the page form to form-table-ct causes the "Crash system" dialog (opened by the "Test Configuration" button) to immediately close again, but only (1) the first time it's clicked, and (2) only in Chromium (not in Firefox). Locally reverting just this hunk unbreaks this again (and makes the test succeed).

**Comment by martinpitt** [comment]
I added a fix for the above dialog bug, and also roped in @garrett's layout fix for the spinner and error message (thanks again!). So now everything works and looks fine.

**Comment by martinpitt** [comment]
Remaining test failures are unrelated.

**Pull request merged**
