### PR TITLE
test: Use real mouse events with Chromium in the shell

### PR DESCRIPTION
**Pull request by martinpitt**
BiDi mouse events work fine on the top-level document (i.e. not in frames). So let's use them to test the shell.

### CODE REVIEW

**Comment by martinpitt** [comment]
[First attempt](https://github.com/cockpit-project/cockpit/commit/18e9f4574a4d9a0766105145ff5a42c0347dc6f2) had [many](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21419-18e9f457-20241210-145523-fedora-41-networking/log.html) [random](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21419-18e9f457-20241210-145513-fedora-41-other/log.html) [pixel failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21419-18e9f457-20241210-145519-fedora-41-storage/log.html) due to the mouse being in a random place and highlighting UI elements. Plus the [HostSwitching](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21419-18e9f457-20241210-145516-fedora-41-expensive/log.html) regression.

With moving the mouse away it looks better -- networking and storage pass, and some [other](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21419-1ce54dd2-20241211-011452-fedora-41-other/log.html) and [expensive](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21419-1ce54dd2-20241211-011451-fedora-41-expensive/log.html) failures.

**Comment by martinpitt** [comment]
Now it's down to [host switcher failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21419-abd3b3f9-20241211-022956-fedora-41-expensive/log.html), the rest passes. This is [due to the animations](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21419-abd3b3f9-20241211-022956-fedora-41-expensive/TestHostSwitching-testBasic-fedora-41-127.0.0.2-2201-FAIL.png) -- see that utterly compressed menu in the screenshot. We need to wait  for that to settle.

**Comment by martinpitt** [comment]
The precise combination of affected retries here brings back [this tracer crash](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21419-7ba1bd20-20241211-034403-fedora-40-other/log.html) ([second instance](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21419-7ba1bd20-20241211-082944-fedora-40-other/log.html)). While that's unrelated, it makes this PR unbecomingly red, looking.

**Comment by martinpitt** [comment]
Looking good! [This](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21419-c7bdffce-20241211-103032-fedora-41-firefox-expensive/log.html#58) is a known flake, I sent https://github.com/cockpit-project/bots/pull/7211 to fix it.

[This failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21419-c7bdffce-20241211-103030-fedora-41-other/log.html#33) is an unrelated known flaky pixel test, #21422

**Review by mvollmer — APPROVED** [review]
Thanks!

**Pull request merged**
