### PR TITLE
bridge: Don't error if no os-release available

### PR DESCRIPTION
**Pull request by petervo**

### CODE REVIEW

**Comment by petervo** [comment]
Tests don't pass in this state, because we test to make sure that we get os-release data. I can adapt them to pass, but honestly systems should not be like this. So I'd almost rather the test fail if you run them on a broken system. But since we know someone in the wild somehow ended up in this state like that at minimum we shouldn't crash.

**Comment by martinpitt** [comment]
@petervo: I was just thinking of a new check in e. g. test/verify/check-system-info that would delete `/etc/os-release`, start cockpit, and assert that you get at least some minimal info. There should be no need to adjust other tests?

**Comment by petervo** [comment]
oh ok, thought you meant unit tests.

**Comment by martinpitt** [comment]
@petervo: I'm fine with merging with unrelated failures on f-27, as long as they are just due to the pcp SELinux errors. Let's just let this run finish.

**Comment by martinpitt** [comment]
@petervo: actually, it wasn't you retrying the test, it just has been stuck since yesterday morning..

**Pull request merged**
