### PR TITLE
bots: Update rhel-7-7 URL

### LINKED ISSUE #12651: Image refresh for rhel-7-7
Image refresh for rhel-7-7
 * [ ] FAIL: image-refresh rhel-7-7

### PR DESCRIPTION
**Pull request by martinpitt**
The nightly one does not exist any more.

Fixes #12651

 * [x] image-refresh rhel-7-7

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-10.
Log: https://209.132.184.41:8493/logs/image-refresh-12666-20190830-060404/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-10.
Log: https://209.132.184.41:8493/logs/image-refresh-12666-20190830-060505/

**Comment by cockpituous** [comment]
image-refresh rhel-7-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-7-20190830-063333

**Comment by marusak** [comment]
[testPcp](https://209.132.184.41:8493/logs/pull-12666-20190830-063838-71a7c49e-cockpit-project-cockpit-rhel-7.7-rhel-7-7/log.html) failed, once more.

**Comment by martinpitt** [comment]
@marusak: testPcp succeeded now, can you please review?

**Pull request merged**
