### PR TITLE
kubernetes: Update the image layer display designs

### PR DESCRIPTION
**Pull request by stefwalter**
This updates the layer designs to those made by @andreasn here:

https://trello-attachments.s3.amazonaws.com/56fd33b21eb21b85aab54804/1600x2500/048910dbe019883845c1de470b7fb3a2/images-metadata.png

CC @aweiteka

### CODE REVIEW

**Comment by andreasn** [comment]
This arrow looks a bit odd with regards to the line.

screenshot from 2016-05-02 17-29-29

**Comment by andreasn** [comment]
The tags for CentOS Base Image disappear off the screen. If I add some margin-bottom to listing-body it looks better.

screenshot from 2016-05-02 17-33-34

**Comment by andreasn** [comment]
`li:first-child:before { background-color: #fff; }`
helped some, but has some issues.

**Comment by andreasn** [comment]
Managed to fix it by changing the colors of the line rather than of the symbol:
4af0b8242330f3754a2b85c66c367dfd5b57edfd

**Comment by dperpeet** [comment]
needs a rebase

**Pull request closed without merging**
