### PR TITLE
WIP - multi machine sudo

### PR DESCRIPTION
**Pull request by mvollmer**
These are some fixes to make sudo on remote machines work, see #13233.

We might or might not need this, depending on how much we want to change logging into remote machines.  But I think we will very likely want to keep the "luxury convenience package" where upon login into Cockpit, we immediately log into (selected) remote machines and start sudo on them.

### CODE REVIEW

**Comment by mvollmer** [comment]
Video with terrible sound: https://www.youtube.com/watch?v=A_MU1wdt6JA

**Comment by mvollmer** [comment]
Let's archive this.

**Comment by Ferryistaken** [comment]
We could just make it so that it prompts for the password on the remote system instead of just showing `Failed to obtain authentication.`

**Comment by martinpitt** [comment]
@Ferryistaken That's exactly what happens now with current versions.

**Comment by Ferryistaken** [comment]
@martinpitt Then I thing that I don't get anything because I'm managin an Ubuntu node from an Arch node, so they are very different versions

**Pull request closed without merging**
