### PR TITLE
shell: prevent empty input in datepicker

### PR DESCRIPTION
**Pull request by fridex**
Fixes https://github.com/cockpit-project/cockpit/issues/2241

### CODE REVIEW

**Comment by stefwalter** [comment]
What situations does this occur in? Wouldn't it be an error rather than automatically choosing the current time?

**Comment by fridex** [comment]
Based on https://github.com/cockpit-project/cockpit/issues/2241

So an error message is preferred?

**Comment by stefwalter** [comment]
No, that's fine. If @andreasn said it should go back to default, then that's good.

**Comment by andreasn** [comment]
The issue in #2241 is still present when running with this branch.
There is also some dropdown box with cities that I'm unsure where it came from.

**Comment by andreasn** [comment]
(Hehe, accidentally ran the wrong branch. Deleted the confused comment I posted earlier.)

This indeed fixes #2241, but when trying to input 2015-04-45 several times over, it jumps forward month after month, alternating between xxxx-xx-14 and xxxx-xx-15.
Could we do reset on empty box, but show and error for incorrect input, in the case for example "2015-23-12" (could happen if someone is used to US date format)

**Comment by andreasn** [comment]
@stefwalter mentioned I had been a bit unclear here, so I'll try to explain better the expected behavior:
 * When clicking on the box, and then outside again - reset the date to the one before you clicked it.
 * In every other case of wrong input - give an error

**Comment by fridex** [comment]
I did some work in https://github.com/cockpit-project/cockpit/pull/2303

> when trying to input 2015-04-45 several times over, it jumps forward month after month, alternating between xxxx-xx-14 and xxxx-xx-15.

This looks like datepicker issue. But when you finish editing, there should be always valid date, isn't there?

**Comment by andreasn** [comment]
Is this fixed now?

**Comment by fridex** [comment]
Should be fixed in https://github.com/cockpit-project/cockpit/pull/2303 except datetime picker "jumping" issue.

**Comment by andreasn** [comment]
should we keep this one open for that, or should I create a new issue for that?

**Comment by fridex** [comment]
I think it deserves a new issue since it is not related to https://github.com/cockpit-project/cockpit/issues/2241

**Comment by andreasn** [comment]
closing this one then

**Pull request closed without merging**
