### PR TITLE
bots: Drop docker resolv.conf hack

### PR DESCRIPTION
**Pull request by martinpitt**
https://bugzilla.redhat.com/show_bug.cgi?id=1448331 apparently got fixed
a while ago, and the hack is not necessary on any of our images any 
more. Also, the resolv.conf creation hack was duplicated in a lot of
places.

Should this still happen in some special case, let's only do this in the 
tests, not on the images, as they are much harder to change and clean
up.

Remove the hack from the Atomic images for now. It is still present in
{debian,fedora,openshift,rhel,selenium}.setup, these will be rebuilt and 
cleaned up in separate pull requests.

 * [x] image-refresh continuous-atomic
 * [x] image-refresh rhel-atomic
 * [x] image-refresh fedora-atomic

### CODE REVIEW

**Comment by martinpitt** [comment]
Wow, that actually worked everywhere. Triggering continuous-atomic, fedora-26, and fedora-testing to have the full spectrum.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-sh8tm.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9040-20180425-064343/

**Comment by martinpitt** [comment]
I forgot, fedora-atomic is blocked by #9002. So let's only rebuild the other two atomics.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-mrr3b.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9040-20180425-065050/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-fckv7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9040-20180425-065050/

**Comment by cockpituous** [comment]
image-refresh fedora-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-atomic-20180425-070202

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-sh8tm.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9040-20180425-070202/

**Comment by cockpituous** [comment]
image-refresh continuous-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-continuous-atomic-20180425-070404

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-npcrk.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9040-20180425-070505/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-zj9p4.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9040-20180425-070505/

**Comment by cockpituous** [comment]
image-refresh rhel-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-atomic-20180425-072828

**Comment by cockpituous** [comment]
image-refresh rhel-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-atomic-20180425-074242

**Pull request merged**
