### PR TITLE
Use HTML form instead of div for login screen.

### PR DESCRIPTION
**Pull request by rhwood**
This allows Firefox, the only browser I tested that did not offer to save the login credentials using `<div role="form">...</div>` to offer to save login credentials.

Addresses #6399

### CODE REVIEW

**Comment by martinpitt** [comment]
Thanks for this! Looks good, but the selenium  and container/bastion tests are repeatedly failing, I suppose they need to be adjusted. I'll have a look soon.

**Comment by rhwood** [comment]
@martinpitt Do you understand why these tests failed?

**Comment by martinpitt** [comment]
I can reproduce the failure locally. It seems that turning this into a form triggers some kind of extra security checking. In particular:
```
08:41:30 INFO |       {u'timestamp': 1529239228479, u'message': u'Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.', u'level': u'WARNING'}
08:41:30 INFO |       {u'timestamp': 1529239229468, u'message': u'1529239229467\tBrowser.SelfSupportBackend\tERROR\t_loadSelfSupport - Non HTTPS URL provided: ', u'level': u'INFO'}
```
The screen shot shows that the login didn't work, it still shows a (non-filled) login page. I'm not yet sure if that is a consequence of the above warnings, or just a red herring.

**Comment by martinpitt** [comment]
I'm testing this change on my own machine (Fedora 28, Firefox) and trying to log in fails with "fatal: error (system:80:29)" in the console. There is no journal entry from cockpit.service, seems this already fails on the js side. Did that change even work for you?

So it seems the Selenium test just reproduces this regression. 

Also, you cannot press "Enter" after the login name any more to get to the next field, you need to use Tab. The former must be fixed, the latter should.

**Comment by rhwood** [comment]
It worked for me when I first tested it using browsers on macOS, I don’t recall if I tried just using a keyboard for complete entry.

**Comment by rhwood** [comment]
Closing to rework in branch (instead of my fork's master). Will open new PR when ready.

**Pull request closed without merging**
