### PR TITLE
Image refresh for fedora-27

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-27
 * [x] image-refresh fedora-27

### CODE REVIEW

**Comment by petervo** [comment]
Same error as f26

**Comment by martinpitt** [comment]
Debugging `test/verify/check-connection TestConnection.testBasic` regression:

 * Version of systemd is the same in current and this new image.
 * /proc/sys/kernel/core_pattern properly points to systemd-coredump
 * Killing a process does not trigger systemd-coredump to pick up  the crash. (coredumpctl is empty, and no journal entries other than systemd itself noticing the demise of the crashed service.
 * With `setenforce 0` it starts working.

So this is not a race condition, but a "proper" regression, something SELinux-y broke coredumpctl.

**Comment by martinpitt** [comment]
Most SELinux-y packages  did not change, but container-selinux updated from 2.29-1 to 2.36-1. However, copying its files into the new image, running the %post script and rebooting doesn't  fix the issue, and removing the package does not either; so it's probably something else. The kernel version differs (4.13.16-302.fc27.x86_64 vs. 4.14.3-300.fc27.x86_64) so it could be a regression there.

There is this audit message on the crash:

    audit[7800]: ANOM_ABEND auid=4294967295 uid=0 gid=0 ses=4294967295 subj=system_u:system_r:systemd_hostnamed_t:s0 pid=7800 comm="systemd-hostnam" exe="/usr/lib/systemd/systemd-hostnamed" sig=11 res=1

But that also happens when disabling selinux and s-coredump works.

**Comment by martinpitt** [comment]
Confirmed that it is a kernel regression. Updating just the kernel on the current image causes this. It still works for "default namespace" processes like "sleep 100" and SEGV'ing that, but not any more for processes which are in a systemd unit, i. e. a different namespace.

I filed downstream bug https://bugzilla.redhat.com/show_bug.cgi?id=1525974 with the details, and filed a known issue #8272 about it. I pushed naughty overrides for Fedora 26 and 27, so once this lands, #8262 should succeed too.

**Pull request merged**
