### PR TITLE
Drop cockpit-docker, packaging cleanups

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by marusak** [comment]
There is still `doc/guide/api-container.xml`

**Comment by marusak** [comment]
Seems all good to me except I think there is one forgotten file?

**Comment by martinpitt** [comment]
@marusak: Well spotted! Removed that as well.

**Review by marusak — APPROVED** [review]
Thanks! and :tada:

**Comment by marusak** [comment]
Adding release-note as we should mention that it is now officially dead.

**Comment by martinpitt** [comment]
@marusak: Wrt release-notes, we already announced it in https://cockpit-project.org/blog/cockpit-215.html . This PR just drops some dead source, the built binary packages do not change at all. But we can certainly mention it again for people who build from source, or other distributions.

**Pull request merged**
