### PR TITLE
base: The "ping" should reply with "pong" in cockpit.js

### PR DESCRIPTION
**Pull request by stefwalter**
This was an oversight of an earlier pull request.

### CODE REVIEW

**Comment by stefwalter** [comment]
@martinpitt This probably to go in before the next release, in order to fix the previous ping/pong pull request.

**Comment by martinpitt** [comment]
I tried to test this in the JS console like this:
```
>> c = cockpit.channel({"payload": "echo"}); c.addEventListener("message", console.log); c.addEventListener("control", console.log);
undefined
>> c.control({command: "ping"}) 
undefined

>> c.send("ping") 
undefined
message { target: null, isTrusted: false, detail: "ping", eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, composed: false, timeStamp: 78887, cancelBubble: false, … }
ping
```
The "ping" on the last line is just the echo.

Then I realized that it doesn't really seem possible to test that way - `processControl()` is only being called if `!channel`, and by nature of the API I can only send channel messages, not raw control messages - or am I missing something?

**Comment by stefwalter** [comment]
Use the undocumented ```cockpit.transport.control(command, options)``` to send non channel control messages.

**Comment by martinpitt** [comment]
Thanks, that works, but I still haven't figured out how to see the responses to it. But anyway, with `window.debugging = "all"`, I see these regularly on master:
```
recv control: {"command":"ping"}
send control: {"command":"ping"}
```

with this PR it actually pongs instead of ping back:
```
recv control: {"command":"ping"}
send control: {"command":"pong"}
```
So this looks as intended.

**Comment by stefwalter** [comment]
The integration tests (running elsewhere) found one more issue:

```
Unexpected journal messages:
Can only send messages when WebSocket is open
Process 1477 (cockpit-ws) of user 980 dumped core.
```
https://fedorapeople.org/groups/cockpit/logs/pull-9586-20180705-072525-965b4fb9-verify-fedora-28/log.html#140

I have pushed an additional commit to this pull request.

**Comment by martinpitt** [comment]
Current failures look unrelated, so retrying. Re-approving, thanks!

**Comment by martinpitt** [comment]
rhel-x keeps [failing](https://fedorapeople.org/groups/cockpit/logs/pull-9585-20180705-131414-ff4a9b53-verify-rhel-x/log.html#191) `testConnection` looking for `Process.*systemd-hostnam.*of user.*dumped core.`. The only things that do appear in journal are:
```
Jul 05 09:27:34 localhost.localdomain systemd[1]: systemd-hostnamed.service: Main process exited, code=dumped, status=11/SEGV
Jul 05 09:27:34 localhost.localdomain systemd[1]: systemd-hostnamed.service: Failed with result 'core-dump'.
```
But I don't see  how this could possibly be related to this PR, as this happens between the kernel and systemd; cockpit is not at all involved here. I'll do another retry.

**Comment by martinpitt** [comment]
I can reproduce the check-connection failure on  rhel-x on master. So let's not block this PR on this.

**Comment by martinpitt** [comment]
> I can reproduce the check-connection failure on rhel-x on master. 

FTR, fixed in PR #9597.

**Pull request closed without merging**
