### PR TITLE
bots: Move avocado/selenium tests to Fedora 30

### PR DESCRIPTION
**Pull request by martinpitt**
- Drop the now unnecessary python2 modules, all our tests use Python 3.
- Stop using the upstream RPM repo in favor of the module stream in
  Fedora 30 proper.

 * [x] image-refresh fedora-30

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-j0mrb.
Log: https://209.132.184.41:8493/logs/image-refresh-11676-20190426-153939/

**Comment by cockpituous** [comment]
image-refresh fedora-30 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-30-20190426-160404

**Comment by martinpitt** [comment]
On [rhel-8.0](https://209.132.184.41:8493/logs/pull-11681-20190426-192424-467a4cf9-verify-rhel-8-0/log.html#271) too

**Comment by marusak** [comment]
> On rhel-8.0 too

I think this comment belongs to #11681, I'll move it there

**Comment by martinpitt** [comment]
@marusak : Right, we can clean up the f-29 image, but I wanted to do that in two steps. Thanks!

**Pull request merged**
