### PR TITLE
machines: Fix XTerm.js crash in addMinWidth()

### LINKED ISSUE #9641: testSerialConsole fails on XTerm.js crash: Cannot read property 'dimensions' of undefined
Since last night `test/verify/check-machines TestMachines.testSerialConsole` consistently fails on CI like this:
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-machines", line 780, in testSerialConsole
    b.wait_not_present("div.terminal canvas.xterm-text-layer")
  File "/build/cockpit/test/common/testlib.py", line 279, in wait_not_present
    return self.wait_js_func('!ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 270, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 267, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit/test/common/testlib.py", line 167, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("div.terminal canvas.xterm-text-layer")): condition did not become true
```

This happens on every OS and every PR. It is most likely triggered by landing the throttling patches, as this introduced subtle timing differences - although these by themselves don't (or shouldn't) break this particular behaviour. The test succeeds locally for both @stefwalter and me.

The screenshot shows an oops. In #9639 I was able to expose that properly, and now it fails more meaningfully:
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-machines", line 770, in testSerialConsole
    b.click("#console-type-select li > a:contains(Serial Console)")
  File "/build/cockpit/test/common/testlib.py", line 205, in click
    self.call_js_func('ph_click', selector, force)
  File "/build/cockpit/test/common/testlib.py", line 187, in call_js_func
    return self.eval_js("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 171, in eval_js
    silent=False, awaitPromise=True, returnByValue=True, no_trace=no_trace)
  File "/build/cockpit/test/common/cdp.py", line 85, in invoke
    res = self.command(cmd)
  File "/build/cockpit/test/common/cdp.py", line 112, in command
    raise RuntimeError(res["error"])
RuntimeError: TypeError: Cannot read property 'dimensions' of undefined
    at t.value (http://127.0.0.2:9691/cockpit/$cc054f3e8f7b5502a050e87c2a638ab986b32d17204453ec8b43e171639feeae/machines/machines.js:39420:66)
    at t.value (http://127.0.0.2:9691/cockpit/$cc054f3e8f7b5502a050e87c2a638ab986b32d17204453ec8b43e171639feeae/machines/machines.js:39414:29)
    at t.value (http://127.0.0.2:9691/cockpit/$cc054f3e8f7b5502a050e87c2a638ab986b32d17204453ec8b43e171639feeae/machines/machines.js:39362:73)
    at E (http://127.0.0.2:9691/cockpit/$cc054f3e8f7b5502a050e87c2a638ab986b32d17204453ec8b43e171639feeae/machines/machines.js:555:46)
    at P (http://127.0.0.2:9691/cockpit/$cc054f3e8f7b5502a050e87c2a638ab986b32d17204453ec8b43e171639feeae/machines/machines.js:571:18)
    at t.forceUpdate (http://127.0.0.2:9691/cockpit/$cc054f3e8f7b5502a050e87c2a638ab986b32d17204453ec8b43e171639feeae/machines/machines.js:1035:21)
    at I (http://127.0.0.2:9691/cockpit/$cc054f3e8f7b5502a050e87c2a638ab986b32d17204453ec8b43e171639feeae/machines/machines.js:617:62)
    at R.updateComponent (http://127.0.0.2:9691/cockpit/$cc054f3e8f7b5502a050e87c2a638ab986b32d17204453ec8b43e171639feeae/machines/machines.js:996:17)
    at R.emitUpdate (http://127.0.0.2:9691/cockpit/$cc054f3e8f7b5502a050e87c2a638ab986b32d17204453ec8b43e171639feeae/machines/machines.js:991:85)
    at b (http://127.0.0.2:9691/cockpit/$cc054f3e8f7b5502a050e87c2a638ab986b32d17204453ec8b43e171639feeae/machines/machines.js:521:85)
```

Our own code doesn't actually access any `.dimensions` property anywhere; this comes from the [PatternFly react-console](https://github.com/patternfly/patternfly-react/tree/master/packages/react-console), in particular the [addMinWidth() function](https://github.com/patternfly/patternfly-react/blob/master/packages/react-console/src/SerialConsole/XTerm.js#L161). Obviously `this.state.terminal.renderer` is null or undefined. This *sort of* makes sense, as in that test it happens after clicking the "Disconnect" button.

### PR DESCRIPTION
**Pull request by martinpitt**
Apply the fix from
https://github.com/patternfly/patternfly-react/pull/471 to PatternFly
react-console.

Fixes #9641

### CODE REVIEW

**Comment by martinpitt** [comment]
This is an utter hack, but I at least want to throw this at CI to validate the fix in https://github.com/patternfly/patternfly-react/pull/471 .

**Comment by martinpitt** [comment]
It works! :-) Question is how ashamed we are to keep that seddery for a while, as opposed to commenting out the check until there is a new upstream release.

**Comment by stefwalter** [comment]
> It works! :-) Question is how ashamed we are to keep that seddery for a while, as opposed to commenting out the check until there is a new upstream release.

This should be a knownissue in our tracker. All the mechanisms are therte to so we can know when it goes awayy.

Plus we can CC the patternfly developers on our knownissue, so they get reminded of it happening, and see how often it happens.

**Comment by martinpitt** [comment]
Agreed, I'll send a PR with a naughty override instead.

**Pull request closed without merging**
