### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by martinpitt** [comment]
[testPrivateKeys](https://fedorapeople.org/groups/cockpit/logs/pull-9920-20180829-023131-b2faada4-verify-fedora-testing/log.html#47) failure, retrying

**Comment by martinpitt** [comment]
Yep, seems testPrivateKeys is busted, presumably some crypto lib change. @Gundersanne, do you have time to do some investigation?

**Comment by martinpitt** [comment]
In particular, if it's a real regression, it's beneficial to -1 the corresponding bodhi update, to avoid the regresssion to hit fedora-updates.

**Comment by Gundersanne** [comment]
Default key format changed in openssh 7.8 https://www.openssh.com/txt/release-7.8 and that causes the standard comment to be different which causes some elements on the page not to be named as expected.

So we could generate PEM formatted keys explicitly as an easy fix.

**Comment by martinpitt** [comment]
@Gundersanne : IMHO we should not override the default system behaviour, as then we don't test what happens in reality. Either make the test accept either output/format, or make a case distinction like
```
if m.image in ["fedora-testing", ...]:
    # new SSH bogoFillMeIn format with OpenSSH 7.8+
else:
    # old PEM SSH format
```
Then we move stuff from "else" to "then" over time, and eventually the old PEM format will disappear. Can cockpit actually deal with the new format properly, or does that need code changes?

**Comment by Gundersanne** [comment]
@martinpitt So the new openssh also breaks our key parsing in  `pkg/lib/credentials.js`. So this just needs to be fixed and handle multiple formats.

**Comment by martinpitt** [comment]
@Gundersanne: This also landed in fedora-i386 (PR #9962) and fedora-28 now, so is urgent. If this functionality just cannot be provided for openssh 7.8, then I think it's okay to just  test on these OSes that the behaviour is acceptable (i. e. functionality is hidden, or proper error message).

**Comment by martinpitt** [comment]
Looks good, thank you! Triggering fedora-testing test, and spinning the others.

**Pull request merged**
