### PR TITLE
test: Remove journal at the end of image setup.

### PR DESCRIPTION
**Pull request by mvollmer**
So that we can debug problems with docker more easily.

### CODE REVIEW

**Comment by mvollmer** [comment]
This master check

http://files.cockpit-project.org/hubbot/6857b8fcd9d5eeadf1f50770a3b33972ed1e93de_f22_x86-64/hubbot.html

has mysteriously failed to start docker before pulling images.  I can't reproduce that locally and there are no logs...

**Comment by mvollmer** [comment]
Priority so that the next master check uses this already.

**Comment by mvollmer** [comment]
> I can't reproduce that locally and there are no logs...

It might have been a timeout.  Docker takes a long time to start sometimes.

**Comment by stefwalter** [comment]
When running TEST_OS=fedora-22:

```
+ docker pull busybox:latest
/var/tmp/SETUP: line 49: docker: command not found
+ docker pull busybox:buildroot-2014.02
/var/tmp/SETUP: line 50: docker: command not found
+ docker pull submod/helloapache
/var/tmp/SETUP: line 51: docker: command not found
+ docker pull submod/atomicapp
/var/tmp/SETUP: line 52: docker: command not found
+ rm -rf /var/log/journal/54a4de4aaf294e01aebf56eda9649b25
+ echo 'kernel.core_pattern=|/usr/lib/systemd/systemd-coredump %p %u %g %s %t %e'
```

**Comment by stefwalter** [comment]
Hmmm, I also see:

```
passwd: all authentication tokens updated successfully.
+ dnf -y copr enable phatina/storaged
('Connection aborted.', gaierror(-2, 'Name or service not known'))
+ dnf -y upgrade dnf
Error: Failed to synchronize cache for repo 'fedora' from 'https://mirrors.fedoraproject.org/metalink?repo=fedora-22&arch=x86_64': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-22&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
+ dnf -y upgrade
Error: Failed to synchronize cache for repo 'fedora' from 'https://mirrors.fedoraproject.org/metalink?repo=fedora-22&arch=x86_64': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-22&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
+ dnf -y install systemtap-runtime-virtguest valgrind gdb udisks2 json-glib realmd glib-networking libssh selinux-policy-targeted docker pcp-libs pcp kubernetes etcd subscription-manager storaged storaged-lvm2 device-mapper-multipath atomic freeipa-client oddjob oddjob-mkhomedir sssd
Error: Failed to synchronize cache for repo 'fedora' from 'https://mirrors.fedoraproject.org/metalink?repo=fedora-22&arch=x86_64': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-22&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
+ systemctl start docker
Failed to start docker.service: Unit docker.service failed to load: No such file or directory.
```

**Comment by mvollmer** [comment]
`TEST_OS=fedora-22 ./vm-create -f cockpit -v --force --no-save`...

**Comment by stefwalter** [comment]
Needs rebase.

**Comment by mvollmer** [comment]
Rebased.

**Pull request closed without merging**
