### PR TITLE
test: Store coredumps in the journal

### PR DESCRIPTION
**Pull request by stefwalter**
So we can see them when we extract the journal.

Together with running the tests as fatal-criticals, we should be able to find the source of some of the more sporadic problems that we find.

### CODE REVIEW

**Comment by mvollmer** [comment]
@stefwalter, tests have failed, as expected I think.  Could you verify that the journals contain the expected coredumps?  I tried but failed...

**Comment by stefwalter** [comment]
FYI: https://bugzilla.redhat.com/show_bug.cgi?id=1253319

**Comment by stefwalter** [comment]
Ok. This is ready. I've verified that it works. The *.journal/*/*.journal files in the test output are now readable and contain core dumps and backtraces.

**Comment by stefwalter** [comment]
I'm bumping the image numbers by two because the first time they built images that missed some of the necessary changes.

**Comment by mvollmer** [comment]
This got merged although hubbot found the  `Unexpected journal message '-- No entries --'` errors, #2571.

**Pull request closed without merging**
