### PR TITLE
Exclude pkg lib coverage projects

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
This looks fine to me, thanks! Not sure if we should wait for @mvollmer for this, though -- although of course we can always revert/change this if he doesn't like this.

Please do make sure that the /devel run has proper coverage info for pkg/lib still.

**Comment by jelly** [comment]
> Please do make sure that the /devel run has proper coverage info for pkg/lib still.

It's there https://cockpit-logs.us-east-1.linodeobjects.com/pull-19166-20230802-122057-a06c3135-fedora-38-devel/Coverage/pkg/lib/index.html

**Review by mvollmer — APPROVED** [review]
No objections. I don't think we lose anything by excluding pkg/lib/.

**Review by martinpitt — APPROVED** [review]
I dropped the first commit, which already went in earlier and caused a conflict.

**Comment by martinpitt** [comment]
Whoa, that's new and unrelated -- the [tox test](https://github.com/cockpit-project/cockpit/actions/runs/5923738526/job/16059953379?pr=19166) seems to use the latest ruff.
```
not ok 9 /static-code/test-ruff
# test/common/testlib.py:595:35: E721 Do not compare types, use `isinstance()`
# test/verify/check-bots-api:111:18: PT027 [*] Use `pytest.raises` instead of unittest-style `assertRaises`
# test/verify/check-connection:230:9: PT027 Use `pytest.raises` instead of unittest-style `assertRaises`
# test/verify/check-shell-menu:105:14: PT027 [*] Use `pytest.raises` instead of unittest-style `assertRaisesRegex`
# test/verify/check-shell-menu:117:14: PT027 [*] Use `pytest.raises` instead of unittest-style `assertRaisesRegex`
```

**Comment by martinpitt** [comment]
This affects all PRs, and lcov.py doesn't have complaints, so let's sort this out separately.

**Pull request merged**
