### PR TITLE
test: Update new IPA image based on Fedora 25

### PR DESCRIPTION
**Pull request by stefwalter**
Hopefully this will help us start to solve some of the
crashes and hangs that we have in check-realm.

In addition, and perhaps most crucially, doing this made
it clear that the IPA image needs more than 1024 MB of
memory to run reliably.

### CODE REVIEW

**Comment by stefwalter** [comment]
Priority because other pull requests are failing  due to this issue.

**Comment by stefwalter** [comment]
Doesn't seem to have fixed anything, at least not yet.

**Comment by stefwalter** [comment]
Lets wait on this to see if the memory increase alone solves the problem.

**Comment by mvollmer** [comment]
I think we should continue with this, just to stop using fedora-22 as the base for the ipa image.

**Comment by mvollmer** [comment]
Let's get a fresh test run, and then I'll merge.

**Comment by mvollmer** [comment]
`check-realms` is failing, which I guess is related...

**Comment by mvollmer** [comment]
The image seems to have disappeared.  I have made a new one in #6107.

**Pull request closed without merging**
