### PR TITLE
static: rename login.css to login.scss to allow esbuild to flatten it properly

### LINKED ISSUE #18652: Dark theme will not apply in firefox for login page
### Explain what happens

If you check dist/login.css you can notice that it contains nested CSS rules, which actually firefox can parse.
Normally the bundler should transpile the css into something firefox could read, and it actually does it for other pages.

Pixel tests actually verify this problem.

### Version of Cockpit

289

### Where is the problem in Cockpit?

None

### Server operating system

None

### Server operating system version

_No response_

### What browsers are you using?

_No response_

### System log

_No response_

### PR DESCRIPTION
**Pull request by Ragavendaran**
Fixes #18652 

Nested CSS was not flattened by esbuild, rendering FireFox unable to read it,

However, Esbuild does flatten nested SCSS into its final dist/.../login.css

This change renames `login.css` to `login.scss`

### CODE REVIEW

**Review by martinpitt — DISMISSED** [review]
As discussed in chat, this is a good fix. We don't want to assume browser support for nested CSS especially on the login page, as that's still too new. Thank you!

**Comment by martinpitt** [comment]
The [test_branding pixel test failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18677-20230420-090510-dda4af0c-fedora-37/log.html#28) is relevant (the metrics one is a race condition, ignore). The [new one](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18677-20230420-090510-dda4af0c-fedora-37/TestConnection-test_branding-login-screen-dark-pixels.png) has better contrast for "Other options", but a much more dimmed background image, compared to the [reference](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18677-20230420-090510-dda4af0c-fedora-37/TestConnection-test_branding-login-screen-dark-reference.png).

It seems naïvely okay, but I'd rather have @garrett and @jelly sign off on this, as I don't know much about dark mode. Thanks!

**Comment by Ragavendaran** [comment]
It seems the [new one](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18677-20230420-090510-dda4af0c-fedora-37/TestConnection-test_branding-login-screen-dark-pixels.png) is the intended look, both CSS that cause this are under `.pf-theme-dark`

- The better contrast for 'other options'
https://github.com/cockpit-project/cockpit/blob/52ffd30cc308847d6768bcc52c16d567b0ce5a97/pkg/static/login.css#L953-L959

- The dimmer background
https://github.com/cockpit-project/cockpit/blob/52ffd30cc308847d6768bcc52c16d567b0ce5a97/pkg/static/login.css#L1000-L1005

Even-though Chrome did switch to dark theme with nested CSS, it did not apply these before.

**Review by martinpitt — DISMISSED** [review]
That makes perfect sense, thanks! I pushed the pixel update and re-run the two relevant tests (the others passed already). Cheers! :tada:

**Comment by martinpitt** [comment]
Sorry, conflict on the pixel update from a parallel PR, so I had to re-push and re-run.

**Pull request merged**
