### PR TITLE
WIP -  login: Show a message with the CA link 

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by garrett** [comment]
I tried getting this to work with my testing iPhone.

However, it still loads a blank page.

Do I need to do anything special? I restarted cockpit.socket. After that didn't work, I tried the bind mount suggestions in https://cockpit-project.org/external/source/HACKING — but then got an "Internal Server Error".

**Comment by mvollmer** [comment]
> I tried getting this to work with my testing iPhone.
> 
> However, it still loads a blank page.

This PR here does not include the error message about the failing WebSocket, that is in #12493.

This PR just puts a permanent message on the login page that is supposed to allow people to download and import the self signing CA cert.  That way, they wont run into the failing WebSocket connection at all.

**Comment by mvollmer** [comment]
image

**Comment by marusak** [comment]
Like the message wording! :laughing:

**Comment by garrett** [comment]
> This PR here does not include the error message about the failing WebSocket

Aha, OK!

> Like the message wording! :laughing: 

Yeah, it's funny in the PR. We'll definitely want to change it before merging, of course. :wink:

**Comment by mvollmer** [comment]
I have merged this back into #12493.  The message on the login page is gone, but the message on the error page is more specific.

**Pull request closed without merging**
