### PR TITLE
Content Security Policy

### PR DESCRIPTION
**Pull request by stefwalter**
Start implementing Content Security Policy. Any package will by default be served with strict Content-Security-Policy unless it overrides it with a value in its manifest.json file.

In addition migrate the new registry package to strict Content Security Policy, and bring in the angular changes necessary to make this work.

### CODE REVIEW

**Comment by petervo** [comment]
Ran through this and seems good. 

Not sure where we landed on versioning. but as discussed earlier i think we should make sure everything in base/ works well with this before merging.

**Comment by stefwalter** [comment]
Fixed up base1 and playground to work with CSP.

**Comment by stefwalter** [comment]
Looks like 'make distcheck' is broken.

**Comment by stefwalter** [comment]
Added content-security-policy to ostree

**Pull request closed without merging**
