### PR TITLE
pf: Make SVG icon selector more specific

### LINKED ISSUE #15132: Icon offset override should only apply to icons, not all SVGs
We need to class this override:
https://github.com/cockpit-project/cockpit/blob/8ea9d250d99be240c5a27ea77ae9091a57857de6/pkg/lib/patternfly/patternfly-4-overrides.scss#L28-L33

...As we're now using SVGs that are not icons, such as in the performance page, the SVG graphs, etc.

### PR DESCRIPTION
**Pull request by garrett**
Fixes #15132

### CODE REVIEW

**Comment by garrett** [comment]
This is a temporary fix for our override. I made it only apply to SVGs with a height of "1em" that have an inline style applied. It should not apply to any other sized SVGs or any without inline styles.

Once we get the upstream fix, this will no longer match anything in Cockpit — but we should remove it anyway, of course.

Note: PatternFly SVG icons do not have a class right now—and the class they're getting is an offset one, not one that can identify them as icons.

**Review by KKoukiou — CHANGES_REQUESTED** [review]
This will break the icons in the main VM page I think. We All PF4 icons expose the size property, and we use that in that page, I see in the dev tools height="1.5em"

Also I would like that we are able to use that size property, it's quite useful.

**Comment by garrett** [comment]
Do you mean the larger icons at the top? They're not affected anyway. Vertical-align is only applied to inline or table-cell elements, and they're not.

Screenshot, in action:
cockpit-vm-icon

Specifically, this part:
cockpit-vm-icon-excerpt

**Comment by garrett** [comment]
So it only affects:
- SVG icons
- at their default size
- with display:inline or display:table-cell
- (that have an inline style)

These are inside a flex and positioned that way, so the vertical-align setting will never apply, regardless of being inline or not.

**Review by KKoukiou — APPROVED** [review]
Hadn't realized it's only related to some of the icons. So let's merge this, just so that we can undo the workarounds in the new plots, and let's hope we won't need to use PF4 icons in tables with size :)

**Comment by garrett** [comment]
I also realized the plots are not inline, so the workaround still wouldn't happen. :laughing:

**Comment by garrett** [comment]
Yeah, I think we don't _really_ need this. Technically, we do need the specificty, but in practice (as it only actually applies to inline SVGs), nope.

Closing this now. The proper fix will land soon. And we can just keep our SVGs ignoring the offset when they're not specifically inline.

**Pull request closed without merging**
