### PR TITLE
TestHistoryMetrics fixes

### PR DESCRIPTION
**Pull request by martinpitt**
- Blocked on https://github.com/cockpit-project/bots/pull/2930

### CODE REVIEW

**Comment by martinpitt** [comment]
While running all the history tests locally, I ran into another bug:

```
+ nmcli con add type dummy con-name fake ifname fake0 ip4 1.2.3.4/24
Error: NetworkManager is not running.
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/var/home/martin/upstream/cockpit/test/verify/check-metrics", line 650, in testPmProxySettings
    m.execute("""set -eux
  File "/var/home/martin/upstream/bots/machine/machine_core/ssh_connection.py", line 363, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'set -eux
                     firewall-cmd --permanent --remove-service pmproxy
                     firewall-cmd --permanent --new-zone=comeandgo
                     nmcli con add type dummy con-name fake ifname fake0 ip4 1.2.3.4/24
                     firewall-cmd --permanent --zone public --remove-interface fake0
                     firewall-cmd --permanent --zone comeandgo --add-interface fake0
                     firewall-cmd --reload
                  ' returned non-zero exit status 8.
```

I added another commit to fix that.

**Comment by martinpitt** [comment]
@TomasTomecek, @csomh : Please see the packit comment above -- there currently seems to be some bouncing back and forth what "fedora-development" means; since yesterday, sometimes PRs run on "fedora-36", sometimes on "fedora-rawhide".

**Comment by csomh** [comment]
Apologies for the trouble @martinpitt! It seems our strategy to keep everything up to date as Fedora goes through it's life cycle is not perfect. See my comment on the PR above for an explanation why this happened.

**Comment by martinpitt** [comment]
@csomh : No worries, it's no trouble for us at all; I just wasn't sure if that were "interesting" or "expected" for you.

**Review by jelly — APPROVED** [review]

**Comment by jelly** [comment]
Did I just approve it while it still has issues on debian-stable? https://logs.cockpit-project.org/logs/pull-16979-20220211-050939-20777ac8-debian-stable/log.html#301

**Review by jelly — APPROVED** [review]

**Comment by martinpitt** [comment]
I give up, running out of ideas. I filed https://bugzilla.redhat.com/show_bug.cgi?id=2013937 , reopened [the known issue](https://github.com/cockpit-project/bots/issues/2518), and added a naughty pattern in https://github.com/cockpit-project/bots/pull/2930 . Once that lands, I'll drop that commit and just land the other two side issues (which are still nice fixes)

**Review by marusak — APPROVED** [review]

**Pull request merged**
