### PR TITLE
python: Avoid pending dbus tasks

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
This helps a lot already, but isn't completely water tight: https://cockpit-logs.us-east-1.linodeobjects.com/pull-18274-20230201-133522-679ec153-fedora-37-pybridge/log.html#124

**Comment by mvollmer** [comment]
> This helps a lot already, but isn't completely water tight: https://cockpit-logs.us-east-1.linodeobjects.com/pull-18274-20230201-133522-679ec153-fedora-37-pybridge/log.html#124

Those messages very likely happened when a GC happened during exit of the bridge and the Bridge object was collected. Let's try to close all channels explicitly when the Bridge is done.

**Comment by allisonkarlitskaya** [comment]
I think I prefer the approach in #18292.  I've marked you there for review.

**Comment by martinpitt** [comment]
@mvollmer , @allisonkarlitskaya  Is there still something relevant here? I'm asking because we still get a lot of these on RHEL 8 with py3.6, e. g. [this log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18318-20230216-213009-d96acad0-centos-8-stream-pybridge/log.html#136).

**Comment by martinpitt** [comment]
Interesting, we even get that on [fedora-37](https://cockpit-logs.us-east-1.linodeobjects.com/pull-960-20230222-075223-9dce209d-fedora-37-pybridge/log.html#44), not just on RHEL 8.

**Comment by martinpitt** [comment]
I sent PR #18385 to bring back the expected message. This PR should remove it again then.

**Comment by mvollmer** [comment]
This is obsolete.

**Pull request closed without merging**
