### PR TITLE
bots: Update URLs to rhel-x repositories

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh rhel-x
 * [x] `check-kdump` regression
 * [x] `check-setroubleshoot TestSelinux.testTroubleshootAlerts` regression
 * [x] `check-packagekit TestUpdatesSubscriptions.testNoUpdates` regression

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-8lzf0.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10173-20180927-121212/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10173-20180927-121212/

**Comment by martinpitt** [comment]
I can reproduce the failure locally. Looks like it's just genuinely broken, let's wait a few days. This isn't urgent at all.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-29m20.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10173-20180930-205454/

**Comment by cockpituous** [comment]
image-refresh rhel-x done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-x-20180930-211717

**Comment by martinpitt** [comment]
Several real regressions, making a TODO list.

**Pull request merged**
