### PR TITLE
WIP: Listing View V2 CSS

### PR DESCRIPTION
**Pull request by stefwalter**
Including the basics of the changes from here: 

https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/patterns/listing-v2.png

### CODE REVIEW

**Comment by stefwalter** [comment]
@andreasn I don't think that the expanded fields should be gray in the row. They look disabled. Can we keep them black.

**Comment by stefwalter** [comment]
CC @larsu @dperpeet Here's the listing view CSS changes that @petervo worked on with a few fixups from me.

**Comment by andreasn** [comment]
>  I don't think that the expanded fields should be gray in the row. They look disabled. Can we keep them black.

You're probably right. My intention with that was to make it feel less cluttered, but it would indeed communicate that things are disabled. Lets keep them black.

**Comment by andreasn** [comment]
Is the "Navigate to details" popup a temporary measure? Will it be fixed in a followup?

**Comment by stefwalter** [comment]
> Is the "Navigate to details" popup a temporary measure? Will it be fixed in a followup?

That's just in the example. In real implementation, navigation would happen at that point.

**Comment by stefwalter** [comment]
Calling it 'listing-toggle' instead of 'listing-item-toggle' because this same location will be used for checkboxes in select mode so it's a toggle, but it doesn't necessarily expand the item.

**Comment by stefwalter** [comment]
@petervo This is ready to be folded back into #4262

**Comment by petervo** [comment]
thanks @stefwalter pulled into #4262

**Pull request closed without merging**
