### PR TITLE
Image refresh for debian-stable

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-stable
 * [x] image-refresh debian-stable

### CODE REVIEW

**Comment by marusak** [comment]
[testNetworkingPage (check_networking_firewall.TestFirewall)](https://209.132.184.41:8493/logs/pull-11650-20190423-044343-9de4d294-verify-debian-stable/log.html) failed 3/3 times, needs work

**Comment by KKoukiou** [comment]
> [testNetworkingPage (check_networking_firewall.TestFirewall)](https://209.132.184.41:8493/logs/pull-11650-20190423-044343-9de4d294-verify-debian-stable/log.html) failed 3/3 times, needs work

It's fixed from https://github.com/cockpit-project/cockpit/pull/11658

I didn't include the fix in this PR since it affect more PRs which might go inside faster.

**Comment by marusak** [comment]
Blocked by #11658

**Comment by martinpitt** [comment]
#11658 landed, retrying

**Pull request merged**
