### PR TITLE
docker: Depend on either docker, docker-latest, or docker-engine in RPMs

### LINKED ISSUE #5769: Allow cockpit working with official docker-engine
Hello,

I'm on CentOS 7 and I'm using cockpit to do some monitoring. 

Since I have some troubles with the centos-docker package, I remove it and install the offcial docker-engine package.

But It seems that cockpit-docker is only compatible with the centos-docker package. 

Is there any solution / hack to install cockpit-docker along to docker-engine?

**Try to install cockpit-docker**

```sh
└─ ▶ yum install cockpit-docker --nodeps
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.quelquesmots.fr
 * epel: mirrors.ircam.fr
 * extras: centos.quelquesmots.fr
 * updates: centos.mirror.fr.planethoster.net
Resolving Dependencies
--> Running transaction check
---> Package cockpit-docker.x86_64 0:122-3.el7.centos will be installed
--> Processing Dependency: docker >= 1.3.0 for package: cockpit-docker-122-3.el7.centos.x86_64
--> Running transaction check
---> Package docker.x86_64 2:1.10.3-59.el7.centos will be installed
--> Processing Dependency: docker-common = 2:1.10.3-59.el7.centos for package: 2:docker-1.10.3-59.el7.centos.x86_64
--> Processing Dependency: container-selinux >= 2:1.10.3-59.el7.centos for package: 2:docker-1.10.3-59.el7.centos.x86_64
--> Running transaction check
---> Package container-selinux.x86_64 2:1.10.3-59.el7.centos will be installed
---> Package docker-common.x86_64 2:1.10.3-59.el7.centos will be installed
--> Processing Conflict: docker-engine-1.13.0-1.el7.centos.x86_64 conflicts docker
--> Processing Conflict: docker-engine-1.13.0-1.el7.centos.x86_64 conflicts docker-io
--> Processing Conflict: docker-engine-selinux-1.13.0-1.el7.centos.noarch conflicts docker-selinux
--> Finished Dependency Resolution
Error: docker-engine conflicts with 2:docker-1.10.3-59.el7.centos.x86_64
Error: docker-engine-selinux conflicts with 2:container-selinux-1.10.3-59.el7.centos.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Docker version**

```sh
└─ ▶ docker --version
Docker version 1.13.0, build 49bf474
```

**CentOS version**

```sh
└─ ▶ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
```

### PR DESCRIPTION
**Pull request by stefwalter**
This allows alternate packages that provide the same file.

Fixes #5769

### CODE REVIEW

**Comment by stefwalter** [comment]
Not sure if the version dependency works here. But lets try this out on all our verify machines.

**Comment by stefwalter** [comment]
So we're left with a conundrum. We need a later version of docker ... but we cannot depend on just the filename in that case:

```
error: line 565: Versioned file name not permitted: Requires: /usr/bin/docker >= 1.3.0
```

Not sure what to do.

**Comment by stefwalter** [comment]
Do the alternate packages of Docker have a ```Provides: docker``` or similar?

**Comment by johanwasserman** [comment]
Hi,
I tried;
cockpit-docker-126-1.el7.centos.x86_64
cockpit-docker-131-1.fc25.x86_64

Both fails with:
Requires: docker >= 1.3.0

docker version
Client:
Version: 1.13.1
API version: 1.26
Go version: go1.7.5
Git commit: 092cba3
Built: Wed Feb 8 06:38:28 2017
OS/Arch: linux/amd64
Server:
Version: 1.13.1
API version: 1.26 (minimum version 1.12)
Go version: go1.7.5
Git commit: 092cba3
Built: Wed Feb 8 06:38:28 2017
OS/Arch: linux/amd64
Experimental: false

Running on Red Hat Enterprise Linux Server 7.3 (Maipo)

Thanks for all your hard work and effort,
much appreciated.

J

**Comment by stefwalter** [comment]
What does ```rpm -q docker``` say?

**Comment by stefwalter** [comment]
Well, what does ```rpm -qi docker``` say?

**Comment by johanwasserman** [comment]
$ rpm -q docker
package docker is not installed
$ docker --version
Docker version 1.13.1, build 092cba3

**Comment by stefwalter** [comment]
I suspect ```rpm -qi docker-latest``` works?

If so hopefully the above fix works. We now depend on 'docker-engine' instead. This package name is Provided by all of docker, docker-latest, and upstream Docker.

This highlights another issue. We need to be testing against docker-latest as well. So I'm bumping to that in the latest Fedora test images.

**Comment by johanwasserman** [comment]
nope... I have a airgapped server so I installed docker from these rpm's
$ yum list installed | grep docker
docker-engine.x86_64                    1.13.1-1.el7.centos        installed
docker-engine-selinux.noarch            1.13.1-1.el7.centos        installed

**Comment by johanwasserman** [comment]
$ rpm -qi docker-engine
Name        : docker-engine
Version     : 1.13.1
Release     : 1.el7.centos
Architecture: x86_64
Install Date: Tue 21 Feb 2017 22:33:22 AEDT
Group       : Tools/Docker
Size        : 67793232
License     : ASL 2.0
Signature   : RSA/SHA512, Wed 08 Feb 2017 19:32:31 AEDT, Key ID f76221572c52609d
Source RPM  : docker-engine-1.13.1-1.el7.centos.src.rpm
Build Date  : Wed 08 Feb 2017 17:41:49 AEDT
Build Host  : 1b0d6163fdc2
Relocations : (not relocatable)
Packager    : Docker <support@docker.com>
Vendor      : Docker
URL         : https://dockerproject.org
Summary     : The open-source application container engine
Description :
Docker is an open source project to build, ship and run any application as a
lightweight container.

**Comment by stefwalter** [comment]
New image uploaded.

**Comment by stefwalter** [comment]
@martinpitt Any similar changes needed on the Debian side?

**Comment by stefwalter** [comment]
This needs some research on rhel-7

**Comment by stefwalter** [comment]
This won't work on rhel-7 or centos-7 because neither one has a ```Provides: docker-engine``` type line in their spec file. :S

**Comment by stefwalter** [comment]
@johanwasserman If this is important to you, could you open a bug at bugzilla.redhat.com asking the RHEL docker packagers to include a ```Provides: docker-engine``` in their RHEL package?

**Comment by johanwasserman** [comment]
@stefwalter it's not a REL problem, I got the rpm directly from the docker repos as per these instructions:
https://docs.docker.com/engine/installation/linux/rhel/#install-using-the-repository

Logged an issue with docker:
https://github.com/docker/docker/issues/31463

Hope this helps.
J.

**Comment by stefwalter** [comment]
> @stefwalter it's not a REL problem, I got the rpm directly from the docker repos as per these instructions.

But where did you get Cockpit from? From RHEL, from Fedora, from CentOS, from Ubuntu?

**Comment by johanwasserman** [comment]
Apologies for the late reply;
https://mirror.aarnet.edu.au/pub/fedora/linux/updates/25/x86_64/c/

**Comment by agross** [comment]
Please consider adding `docker-ce` as well. (#6225)

**Comment by petervo** [comment]
Since we don't seem to be able to come up with a better solution should we just go to requiring /usr/bin/docker? We loose the ability to pin to a version, but with docker, docker-engine and docker-ce and no common provides between them all i don't see any other way forward. At least that way people will be able to install.

**Comment by stefwalter** [comment]
That's fine with me. Some versions of docker are just broken and incompatible. But it's probably better that people can use cockpit-docker ... even if it breaks on some strange versions of docker.

**Comment by alancnet** [comment]
@stefwalter I'm very much awaiting this PR to go though. Could you revisit this today?

Thanks!

**Comment by petervo** [comment]
#6340 was merged instead

**Pull request closed without merging**
