### PR TITLE
add Catalan

### PR DESCRIPTION
**Pull request by rbuj**
cd cockpit/po
curl https://fedora.zanata.org/rest/file/translation/cockpit/master/ca/po?docId=cockpit > ca.po

### CODE REVIEW

**Comment by stefwalter** [comment]
@petervo What's the plan for pulling new translations from Zanata? I can see tons of new translations there. Also why do we have the list of LINGUAS duplicated in zanata.xml?

**Comment by rbuj** [comment]
You can remove locales section from tools/zanata.xml.

This change is described in https://bugzilla.redhat.com/show_bug.cgi?id=1156236

**Comment by petervo** [comment]
@stefwalter we have no policy about when we should pull in a new language. 

Are you ok with just pulling in whatever is on zanata? Do we want to curate the available languages at all? Is there a threshold you want languages to reach before we start pulling them in?

**Comment by rbuj** [comment]
You can use ' --min-doc-percent' option in zanata-cli pull. I added -B option for non-interactive (batch) mode. Example:
<pre>zanata-cli -B pull --min-doc-percent 60 --project-config ./tools/zanata.xml -s ./po -t ./po
[INFO] Loading project config from ./tools/zanata.xml
[WARN] Source directory in zanata.xml is set to [.] but is now given as [./po]
[WARN] You are overriding your Source directory defined in zanata.xml
[WARN] Translation directory in zanata.xml is set to [.] but is now given as [./po]
[WARN] You are overriding your Translation directory defined in zanata.xml
[INFO] Loading user config from /home/robert/.config/zanata.ini
[INFO] client API version: 3.7.3, server API version: 3.7.3
[INFO] Server: https://fedora.zanata.org/
[INFO] Project: cockpit
[INFO] Version: master
[INFO] Username: rbuj
[INFO] Project type: gettext
[INFO] Enable modules: false
[INFO] Using ETag cache: true
[INFO] Purging ETag cache beforehand: false
[INFO] Locales to pull: [sq, ar, as, ast, bal, eu, bn, bn-IN, brx, bs, br, bg, ca, zh-CN, zh-HK, zh-TW, kw, kw-GB, cs, da, nl, en-GB, eo, et, fi, fr, gl, ka, de, el, gu, he, hi, hu, is, id, ia, it, ja, kn, kk, km, ky, ko, lt, nds, mk, mai, ms, ml, mr, mn, ne, nb, nn, or, pa, fa, pl, pt, pt-BR, ro, ru, sr, sr@latin, si, sk, sl, es, sv, tg, ta, te, bo, tr, uk, ur, wba, cy, lv, kw@uccor, kw@kkcor, af, am, be, hr, de-CH, th, vi, zu, ilo, nso, tw, yo, anp, ga]
[INFO] Encode tab as \t: true
[INFO] Current directory: /home/robert/cockpit
[INFO] Pulling target documents (translations) only
[INFO] Target-language base directory (translations): ./po
[INFO] Minimum accepted translation percentage (message based): 60%
[INFO] Create skeletons for untranslated messages/files: false
[INFO] Pulling 1 of 1 docs for this module from the server
[INFO] Setting minimum document completion percentage may potentially increase the processing time.
[INFO] No changes in translations for locale ca and document cockpit
[INFO] No changes in translations for locale pl and document cockpit
[INFO] No changes in translations for locale uk and document cockpit
[INFO] Translation file for document cockpit for locales [sq, ar, as, ast, bal, eu, bn, bn-IN, brx, bs, br, bg, zh-CN, zh-HK, zh-TW, kw, kw-GB, cs, da, nl, en-GB, eo, et, fi, fr, gl, ka, de, el, gu, he, hi, hu, is, id, ia, it, ja, kn, kk, km, ky, ko, lt, nds, mk, mai, ms, ml, mr, mn, ne, nb, nn, or, pa, fa, pt, pt-BR, ro, ru, sr, sr@latin, si, sk, sl, es, sv, tg, ta, te, bo, tr, ur, wba, cy, lv, kw@uccor, kw@kkcor, af, am, be, hr, de-CH, th, vi, zu, ilo, nso, tw, yo, anp, ga] are skipped due to insufficient completed percentage</pre

**Comment by stefwalter** [comment]
> Are you ok with just pulling in whatever is on zanata? Do we want to curate the available languages at all? Is there a threshold you want languages to reach before we start pulling them in?

I think for upstream (and likely Fedora) we should pull them in once they reach a threshhold. We do have a long way to go with localization and especially marking things as translatable. So having this alive upstream will help us get further ...

Other distros may have different policy on what languages they choose to ship. Perhaps CentOS or RHEL would disable localization until there's a solid body of languages.

@petervo What do you think?

**Comment by rbuj** [comment]
<pre>diff --git a/pkg/shell/manifest.json b/pkg/shell/manifest.json
index 4363334..56d989a 100644
--- a/pkg/shell/manifest.json
+++ b/pkg/shell/manifest.json
@@ -3,6 +3,7 @@
 
     "linguas": {
         "en": "English",
+        "ca": "Catalan",
         "de": "Deutsch",
         "da": "Dansk",
         "pl": "Polski"</pre>

**Comment by petervo** [comment]
Thanks @rbuj, Included your commits here #2913.

**Pull request closed without merging**
