### PR TITLE
Fix rhel-8 image build

### PR DESCRIPTION
**Pull request by martinpitt**
rhel-8 nightlies changed in several ways which broke the image build.

 * [x] image-refresh rhel-8
 * [x] work around/adjust/naughty-override https://bugzilla.redhat.com/show_bug.cgi?id=1574565

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-npcrk.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9083-20180502-094242/

**Comment by cockpituous** [comment]
image-refresh rhel-8 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-20180502-095656

**Comment by martinpitt** [comment]
Yay, new SELinux violation:
```
Error: audit: type=1400 audit(1525256748.402:124): avc:  denied  { create } for  pid=870 comm="nft" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=netlink_netfilter_socket permissive=0
```

**Comment by martinpitt** [comment]
This is already known as https://bugzilla.redhat.com/show_bug.cgi?id=1573501 . I pushed a hack to ignore this.

**Comment by martinpitt** [comment]
check-networking-checkpoints still fails.

**Comment by martinpitt** [comment]
@mvollmer, do you happen to know some background about the checkpoint failures?

**Comment by martinpitt** [comment]
NM on that image definitively supports checkpoints. `busctl introspect org.freedesktop.NetworkManager /org/freedesktop/NetworkManager | grep Checkpoint` gives me the expected methods, and I see
```
<info>  [1525352533.4548] audit: op="checkpoint-create" arg="/org/freedesktop/NetworkManager/Checkpoint/1" pid=1200 uid=0 result="success"
<info>  [1525352548.4598] checkpoint[0x55d6a13433c0]: rollback of /org/freedesktop/NetworkManager/Checkpoint/1
<info>  [1525352560.6682] audit: op="checkpoint-destroy" arg="/org/freedesktop/NetworkManager/Checkpoint/1" pid=1200 uid=0 result="success"
```
When I click on "Off" on the network interface, I get a screen "Testing connection.." with a spinner for about 10 seconds, then a "Restoring connection..." for about 2 seconds, and then it's back to on. In other words, it just seems to automatically recover after switching it off instead of asking for confirmatino. It seems checkpoint behaviour actually did change somewhat here? @mvollmer, does that make sense?

**Comment by martinpitt** [comment]
Indeed on Fedora-28 I get this instead:
```
<info>  [1525357125.9438] audit: op="checkpoint-destroy" arg="/org/freedesktop/NetworkManager/Checkpoint/1" pid=1914 uid=0 result="fail" reason="checkpoint /org/freedesktop/NetworkManager/Checkpoint/1 does not exist"
```
I see in pkg/networkmanager/interfaces.js the `manager.checkpoint_create()` handler calls `checkpoint_destroy()` and only fires up the dialog when that fails (as until NM 1.10 it actually went away).

But wit NM 1.11, the checkpoint properties during the rollback don't give a clue about the rollback actually happening:
```
org.freedesktop.NetworkManager.Checkpoint interface -         -                 
NAME                                      TYPE      SIGNATURE RESULT/VALUE                             FLAGS
org.freedesktop.NetworkManager.Checkpoint interface -         -                                        -
.Created                                  property  x         426575                                   emits-change
.Devices                                  property  ao        1 "/org/freedesktop/NetworkManager/De…2" emits-change
.RollbackTimeout                          property  u         15                                       emits-change
.PropertiesChanged                        signal    a{sv}     -                                        -
```

So I'll file this as an upstream bug report. I don't see how we could fix this on the JS side.

**Comment by martinpitt** [comment]
Filed https://bugzilla.redhat.com/show_bug.cgi?id=1574565

**Comment by martinpitt** [comment]
Turns out the issue (almost surely) got fixed around the same time I reported it: https://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=30a4fa454d89

So I just added a naughty override for now.

**Pull request closed without merging**
