### PR TITLE
build: Drop ESLint from esbuild

### PR DESCRIPTION
**Pull request by martinpitt**
Similar to what commit c9ac6736b3e2ccdf90d6065 did for stylelint, move ESLint to static code checks as well. It already runs from there (and actually correctly since the previous commit).

### CODE REVIEW

**Review by allisonkarlitskaya — APPROVED** [review]
Great!

**Comment by jelly** [comment]
Less favorable opinion here, I need to first setup some pre commit hook which is fast enough. A LSP is fun and all but my editor is full of red on any normal Cockpit project or with warnings.

So maybe we can instead disable eslint by default?

**Comment by martinpitt** [comment]
@jelly Just to make sure -- this isn't related to esbuild vs. static-code invocation, right? That's your LSP config?

**Comment by jelly** [comment]
> @jelly Just to make sure -- this isn't related to esbuild vs. static-code invocation, right? That's your LSP config?

Yup, it's the typescript.

But my editor does give me warnings which I don't get in eslint for example:

image

This might be due to typescript-lang-server honestly.

**Comment by martinpitt** [comment]
@jelly Yeah, your editor doesn't care about static-code vs. build.js, it just reads .eslintrc.json etc. directly.

**Pull request merged**
