### PR TITLE
bots: Install iproute2 package on Debian and fix timeout in image building

### LINKED ISSUE #8530: Image refresh for debian-testing
Image refresh for debian-testing
 * [ ] FAIL: image-refresh debian-testing

### PR DESCRIPTION
**Pull request by martinpitt**
iproute has been a transitional package for iproute2 for a looong time,
and finally got removed. Use the current package name everywhere.

Fixes #8530

 * [x] image-refresh debian-testing
 * [x] image-refresh debian-stable
 * [x] image-refresh ubuntu-1604
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by martinpitt** [comment]
Turns out image builds were also broken due to fixing the `TestVm.execute()` timeout. I pushed a fix for that as well, and tagging priority.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-d09dd.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8555-20180205-165151/

**Comment by martinpitt** [comment]
The actual image build is done, and the VM is already shut down. But qemu-img convert has been stuck for almost an hour:
```
user      14031  0.4  0.0 190728 14116 ?        S    17:15   0:19 qemu-img convert -c -O qcow2 /build/tmp/debian-stablew45ixlln.qcow2 /build/images/debian-stable.partial

$ date
Mon Feb  5 18:34:04 UTC 2018

$ ls -lh /build/images/debian-stable.partial
-rw-r--r--. 1 user user 140M Feb  5 17:16 /build/images/debian-stable.partial
```
This doesn't seem to make any progress. I'll try to kill it and reattempt the build.

**Comment by martinpitt** [comment]
Ah, it wasn't due to qemu-img itself, but due to `packet_write_wait: Connection to 152.19.134.199 port 22: Broken pipe` on the bot. I. e. the sink caused some trouble.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-p4bzz.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8555-20180205-184545/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-xqnd3.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8555-20180205-193232/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-stable-20180205-191616

**Comment by cockpituous** [comment]
image-refresh ubuntu-1604 done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-1604-20180205-195959

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-9tl3b.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8555-20180205-201010/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-stable-20180205-203838

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-j8nqh.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8555-20180205-205858/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-testing-20180205-213535

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-cz849.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8555-20180205-223333/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-stable-20180205-230303

**Comment by martinpitt** [comment]
I pushed the image SHAs.

**Comment by martinpitt** [comment]
The new debian-testing image apparently has a new udisks crash:
https://fedorapeople.org/groups/cockpit/logs/pull-8555-20180206-062626-925e5548-verify-debian-testing/log.html#114

This needs to be reported and overridden.

**Pull request merged**
