### PR TITLE
machines: port to PF4 modals

### PR DESCRIPTION
**Pull request by KKoukiou**
For showing in progress in modals start using the isLoading variant of buttons
instead of showing spinner in the footer which is the suggested way from
PF4 to show in progress dialogs.

It will have one trivial merge conflict with https://github.com/cockpit-project/cockpit/pull/14740 but I want to see the tests since it will be probably a massacre.

### CODE REVIEW

**Comment by marusak** [comment]
The tests don't seem bad (from that minimum that ran) but there is conflict as you predicted. Can you please rebase? Thanks!

**Comment by marusak** [comment]
Ehm, again needs rebase :/ Too many machines things moving around

**Comment by KKoukiou** [comment]
I will convert it to draft and check the tests in CI, the merge conflict was not really trivial.

**Review by marusak — APPROVED** [review]
Nice, thanks!

**Pull request merged**
