### PR TITLE
packagekit: Don't load all package details at once 

### LINKED ISSUE #13535: TeXlive update breaks Cockpit
Cockpit version: 208
OS: Fedora 31

When a lot of packages have updates, Cockpit will make a GetUpdateDetails request to PackageKit that exceeds the maximum websocket frame size of 128 KiB.

In my case, texlive has been updated or rebuild in Fedora, and I suddenly had about 2800 pending updates.  This resulted in a monster D-Bus call of about 150KiB.  Cockpit-ws will reject such a frame and will disconnect the client.

### PR DESCRIPTION
**Pull request by marusak**
Fixes #13535

### CODE REVIEW

**Comment by marusak** [comment]
What, why are all statuses aborted?

**Comment by martinpitt** [comment]
@marusak : Sorry, I just did some e2e machine maintenance. I thought a sunny Sunday morning was a good time to not disturb anyone, but the cockpit team never sleeps! :wink:

**Review by martinpitt — APPROVED** [review]
That's a clever fix, thank you!

**Comment by marusak** [comment]
> Sorry, I just did some e2e machine maintenance. 

I just saw https://github.com/cockpit-project/cockpituous/pull/390 so that explains that :) I've force pushed to get rid of those aborted statuses in our weather reports.

> I thought a sunny Sunday morning was a good time to not disturb anyone, but the cockpit team never sleeps!

:) Not so sunny here.Yesterday it was super nice outside, today it is rather gray.

**Pull request merged**
