### PR TITLE
bots: Robustify yum install

### PR DESCRIPTION
**Pull request by martinpitt**
Make `yum install` fail when it encounters missing packages, instead of
silently succeeding and creating broken images. This replaces the
explicit check in rhel.setup, but apply it more broadly.

 * [x] fix candlepin refresh: PR #11394
 * [x] image-refresh candlepin
 * [x] image-refresh rhel-8-0
 * [x] image-refresh centos-7

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-qbpxb.
Log: https://209.132.184.41:8493/logs/image-refresh-11386-20190313-085858/

**Comment by martinpitt** [comment]
I'm triggering some image refreshes to ensure the scripts still work. Note that ovirt image has been broken for months, so I'm not rebuilding that.

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-11386-20190313-085858/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-52zc1.
Log: https://209.132.184.41:8493/logs/image-refresh-11386-20190313-090000/

**Comment by martinpitt** [comment]
Oh right,  candlepin was broken as well.. issue #11325

**Comment by cockpituous** [comment]
image-refresh rhel-8-0 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-0-20190313-092323

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-52zc1.
Log: https://209.132.184.41:8493/logs/image-refresh-11386-20190313-092323/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-sh7f3.
Log: https://209.132.184.41:8493/logs/image-refresh-11386-20190313-092323/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20190313-094242

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-7g546.
Log: https://209.132.184.41:8493/logs/image-refresh-11386-20190313-095252/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-2kqnn.
Log: https://209.132.184.41:8493/logs/image-refresh-11386-20190313-095252/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20190313-101818

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-qwzr2.
Log: https://209.132.184.41:8493/logs/image-refresh-11386-20190314-220101/

**Comment by cockpituous** [comment]
image-refresh candlepin done: https://github.com/cockpituous/cockpit/commits/image-refresh-candlepin-20190314-225050

**Comment by martinpitt** [comment]
Hmm, the centos-7 image already timed out and is gone. But the build clearly worked, so I think that's enough.

**Comment by martinpitt** [comment]
@larskarlitski : The point is, it doesn't fail; only if you install a single package.
```
# yum -y install bash foo
Package bash-4.2.46-33.el7.x86_64 already installed and latest version
No package foo available.
Nothing to do
[root@m1 ~]# echo $?
0
```
This is really unintuitive and a trap. With the option it fails with exit code 1.

dnf behaves like that by default. The "yum" compatibility wrapper ignores the option. On Fedora:

```
# yum --setopt=skip_missing_names_on_install=False -y install bash-doc foo
Main config did not have a skip_missing_names_on_install attr. before setopt
Main config did not have a skip_missing_names_on_install attr. before setopt
No match for argument: foo
Error: Unable to find a match
# echo $?
1
```
But same behaviour without the option. So an install script that uses `yum` should always use that option IMHO, to avoid hard to debug issues.

**Comment by larskarlitski** [comment]
Right, that's what I would have expected from this option. However, I get this on our latest rhel-8 image:

```
[admin@m1 ~]$ sudo yum install -y cockpit foo
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Last metadata expiration check: 0:30:53 ago on Fri 15 Mar 2019 05:20:40 AM EDT.
Package cockpit-185-2.el8.x86_64 is already installed.
No match for argument: foo
Error: Unable to find a match
[admin@m1 ~]$ echo $?
1
```

**Comment by martinpitt** [comment]
@larskarlitski : Right, because RHEL 8 uses dnf, and just calls it yum. In other words, that "not quite yum, but we don't tell ya" version does the right thing by default. :-) But we use the shared rhel.setup for rhel/centos 7 as well.

**Pull request merged**
