### PR TITLE
Update OpenShift image to Fedora 27, replace deprecated oadm command

### PR DESCRIPTION
**Pull request by martinpitt**
Fedora 25 has been EOL for quite a while.
    
Work around "docker cp" out-of-memory bug [1] by calling tar in a
running container instead, and clean it up afterwards.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1489505

 * [x] image-refresh openshift

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-nl5ff.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-154040/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-154040/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-kb1dv.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-163636/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-163636/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-1hj38.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-164848/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-mnx9r.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-164949/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-164949/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-w3dmd.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-174747/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-r5xnq.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-174747/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-c8k9v.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-174747/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-kb1dv.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-174747/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-1zkx2.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-174848/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-hs5hf.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-174848/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-174848/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-khmck.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-201515/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-bwd85.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-201515/

**Comment by martinpitt** [comment]
The refresh was broken  due to some fallout from the testvm.py move. Fix pushed.

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-rx3wf.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-225959/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-639m0.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8628-20180215-225959/

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-20180215-234444

**Comment by martinpitt** [comment]
Image build and tests work now, so ready for review/landing. @larskarlitski , can you please have a look?

**Comment by martinpitt** [comment]
I can locally reproduce the container/kubernetes failure; in the VM, openshift doesn't seem to respond at all on port 30000 even though it's listening:
```
tcp   LISTEN     3      128                                                :::30000                                                          :::*                   users:(("openshift",pid=1341,fd=160)) ino:34638 sk:1a v6only:0 <->
```

**Comment by martinpitt** [comment]
Some observations wrt. the failing container/kubernetes test:
 * Running `curl http://127.0.0.1:30000` in the openshift VM works fine; it gets passed on to the cockpit-ws process in the k8s_openshift-cockpit_* docker container.
 * Running `curl http://127.0.0.2:30001` on the host  hangs; strace shows that cockpit-ws does not get the request.
 * QEMU command looks fine, it has the `hostfwd=tcp:127.0.0.2:30001-:30000` forwarding rule. The exact same rule works fine with the previous openshift image.
 * tcpdump is no help, it doesn't work on the QEMU user network.

**Comment by martinpitt** [comment]
Argh, still three failures.

**Comment by martinpitt** [comment]
They were flakes, tests pass now \o/

**Pull request merged**
