### PR TITLE
test: Re-enable and fix TestStorageLvm2.testRaidRepair on fmf

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Review by martinpitt — DISMISSED** [review]
Kiitos!

**Comment by mvollmer** [comment]
Bollocks, this didn't work... I am sure we had one amplified run with big disks that was completely green.

**Comment by mvollmer** [comment]
> Bollocks, this didn't work... I am sure we had one amplified run with big disks that was completely green.

Here: https://artifacts.dev.testing-farm.io/4a5b1766-aea9-4d0b-8f9e-1158706f33b1/

**Comment by mvollmer** [comment]
> > Bollocks, this didn't work... I am sure we had one amplified run with big disks that was completely green.
> 
> Here: https://artifacts.dev.testing-farm.io/4a5b1766-aea9-4d0b-8f9e-1158706f33b1/

The test here also passed on retry.  I run them all again, for kicks.

**Comment by mvollmer** [comment]
> The test here also passed on retry. I run them all again, for kicks.

And it ran into the race again... I'll try even bigger disks, but maybe the whole theory is bogus...

**Comment by mvollmer** [comment]
>  I'll try even bigger disks,

First run has passed.

**Comment by mvollmer** [comment]
> > I'll try even bigger disks,
> 
> First run has passed.

Second one as well. Good enough?

**Review by martinpitt — APPROVED** [review]
OK, let's try! I triggered some /storage tests, and the required fcos/other.

**Comment by martinpitt** [comment]
I'm sick of retrying TestReauthorize, landing as-is.

**Comment by martinpitt** [comment]
We have to revert this, see PR #19811

**Pull request merged**
