### PR TITLE
package.json: Update @patternfly/react-table package dependency

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Review by marusak — APPROVED** [review]

**Comment by KKoukiou** [comment]
I think this completely broke TestMachines.testStoragePools :(

**Comment by marusak** [comment]
Ah crap :/ I am sorry, do you want to revert?

**Comment by KKoukiou** [comment]
> Ah crap :/ I am sorry, do you want to revert?

No worries - I have a fix - that's easy. I will combine it in the general test fixing commit.

**Comment by marusak** [comment]
Thank you :heart:

**Pull request merged**
