### PR TITLE
Image refresh for fedora-24

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for fedora-24 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-24-2017-01-13/

### CODE REVIEW

**Comment by stefwalter** [comment]
The atomic storage reset command is now broken:

```
# rpm -q atomic
atomic-1.14.1-1.fc25.x86_64
# atomic storage reset
/usr/bin/atomic storage reset: too few arguments
Try '/usr/bin/atomic storage reset --help' for more information.
```

Filed this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1413862

**Comment by stefwalter** [comment]
Added a known issue for the regression on Fedora 24

**Comment by mvollmer** [comment]
I guess check-storage-luks is still broken.  I'll check (finally).

**Comment by mvollmer** [comment]
> I guess check-storage-luks is still broken. I'll check (finally).

Another case of #4181.

**Comment by mvollmer** [comment]
Tomas is kicking https://bodhi.fedoraproject.org/updates/FEDORA-2016-126de75eb5, that should resolve these issues.  We dropped that ball, unfortunately.

**Comment by stefwalter** [comment]
Should have someone besides me or @mvollmer merge this.

**Pull request closed without merging**
