### PR TITLE
Patternfly versions bumps - superseded by #19111

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by garrett** [comment]
The first dropdown is a select toggle; the following ones are form selects.

I've adjusted it based on guidelines and noticed that the select control HTML structure must've changed from `select.pf-v5-c-form-control` to `.pf-v5-c-form-control  > select` (that is: it's now nested in a wrapper instead of having the class applied on the widget directly).

I'm assuming it _changed_, instead of having two different versions. If this breaks other pixel tests, we can have both with `select.pf-v5-c-form-control, .pf-v5-c-form-control  > select {}` — but I doubt that we need the older version.

Let's see what happens. :crossed_fingers: :four_leaf_clover:

**Comment by jelly** [comment]
There are a lot of pixel flakes, so we might want to wait till this is merged https://github.com/cockpit-project/cockpit/pull/19015

**Comment by jelly** [comment]
# Test failures

* [ ] TestKeys-testPrivateKeys
* [ ] TestStoragePartitions.testSizeSlider
* [ ] TestUpdates.testBasic
* [ ] TestUpdates.testFailServiceRestart

# UI issues

Dark theme regression.
image

**Comment by jelly** [comment]
RTL fixes from @garrett which might be useful. https://github.com/cockpit-project/cockpit/commit/843ac226e3d585e71120d0a197ff331db0d49f7a

**Comment by jelly** [comment]
Before the recent changes:

```
 357 tests, 286 passed, 32 failed, 39 skipped, 0 to go (21 retries of failures, 0 retries of successes), took 51 minutes to run.
 ```
 
 After
 ```
  357 tests, 288 passed, 30 failed, 39 skipped, 0 to go (17 retries of failures, 4 retries of successes), took 47 minutes to run.
 ```

**Comment by jelly** [comment]
Our RTL implementation in main is broken and is actually correct in this PF update.

image

**Pull request closed without merging**
