### PR TITLE
bots: Install rpmlint into build mock on Fedora 27

### PR DESCRIPTION
**Pull request by martinpitt**
We will soon use this to spot errors in our spec file and RPM packaging
during CI.

 - [x] image-refresh fedora-27

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-s5lmm.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7862-20171011-093838/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7862-20171011-093838/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-crnjx.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7862-20171011-095151/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7862-20171011-095151/

**Comment by martinpitt** [comment]
Not sure about the fedora-27 build error on the bots, that looks weird and temporary. It works fine with a local bots/image-create, so I uploaded that instead.

**Pull request merged**
