### PR TITLE
shell: Add OS name to the dashboard

### PR DESCRIPTION
**Pull request by petervo**

### CODE REVIEW

**Comment by stefwalter** [comment]
I think that operating system information should hide when the rows become editable (ie: the checkbox button is clicked).

**Comment by petervo** [comment]
updated

**Comment by stefwalter** [comment]
I have a problem where machines are not getting their info filled in. This quite likely depends on the json-cache work (which I'm almost done with).

**Comment by petervo** [comment]
But the host names are? That would be strange because they are updated in the same place.

**Comment by stefwalter** [comment]
Actually, lets merge this and then I can include it in the json cach ework.

**Pull request closed without merging**
