### PR TITLE
package.json: Update xterm package dependency

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "xterm": "3.11.0"
pkg/docker/docker.js:import { Terminal } from "xterm";
pkg/lib/cockpit-components-terminal.jsx:import { Terminal as Term } from "xterm";
pkg/lib/console.css:@import "~xterm/lib/xterm.css";
pkg/machines/machines.less:@import "~xterm/lib/xterm.css";
pkg/systemd/terminal.jsx:                    "TERM=xterm-256color",
test/avocado/selenium-base.py:        terminal = self.wait_xpath("//*[contains(@class, 'terminal xterm')]")
test/verify/check-active-pages:                return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-realms:                return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-terminal:                return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/machineslib.py:        b.wait_present("div.terminal canvas.xterm-text-layer") # if connected the xterm canvas is rendered
test/verify/machineslib.py:        b.wait_present("div.terminal canvas.xterm-text-layer")
test/verify/machineslib.py:        b.wait_not_present("div.terminal canvas.xterm-text-layer")
test/verify/machineslib.py:        b.wait_present("div.terminal canvas.xterm-text-layer")
```

**Comment by martinpitt** [comment]
@marusak, can you please review this? For this kind of PR we shouldn't rely on automated tests solely, as this kind of dependency update often has a visual impact that tests can't see. I. e. can you test the main, docker, and machine serial console terminal to make sure that everything is okay with this version? Thanks!

**Comment by marusak** [comment]
I can make terminal crash (`TypeError: Cannot read property '_data' of undefined` or `Uncaught TypeError: Cannot read property 'copyCellsFrom' of undefined`). I will investigate if this is not well tested old problem or this is really cause of the new version (it happens on horizontal resizing, so possibly it is xterm.js bug as new version deals with horizontal resizing).

**Comment by marusak** [comment]
Seems we are not the only one who see this problem https://github.com/xtermjs/xterm.js/issues/1932

**Comment by marusak** [comment]
This version is broken. Lets wait for some fix.

**Pull request closed without merging**
