### PR TITLE
bots: Add sscg to Fedora images

### PR DESCRIPTION
**Pull request by martinpitt**
We need to test sscg mode to ensure that it actually works. It does not
right now (see issue #12499)

 * [x] image-refresh fedora-29
 * [x] image-refresh fedora-30

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-12500-20190806-085555/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-12500-20190806-085656/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-12500-20190806-085656/

**Comment by cockpituous** [comment]
image-refresh fedora-29 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-29-20190806-094646

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-hgznf.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12500-20190806-094747/

**Comment by cockpituous** [comment]
image-refresh fedora-30 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-30-20190806-101313

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12500-20190806-094747/

**Comment by martinpitt** [comment]
Two [check-machines](https://209.132.184.41:8493/logs/pull-12500-20190806-153232-6e2477ff-cockpit-project-cockpit-fedora-30/log.html) failures, which is unusual -- they have been fairly robust lately. Retrying.

**Pull request merged**
