### PR TITLE
Fedora 22 branding

### PR DESCRIPTION
**Pull request by stefwalter**
Some branding cleanup ahead of Fedora 22 release.

### CODE REVIEW

**Comment by stefwalter** [comment]
@andreasn In case you're interested ...

**Comment by andreasn** [comment]
will test!

**Comment by stefwalter** [comment]
@andreasn you need --with-branding=fedora in your autogen.sh argument list.

**Comment by andreasn** [comment]
Looks good as far as I can see. Also good to see the stable/unstable message being a flag, since that can differ between distros a lot. What Fedora considerer super stable, an Enterprise-10-year-support-ish distro might not.

**Pull request closed without merging**
