### PR TITLE
shell: changed sidebar border width from 7px to 3px

### LINKED ISSUE #6286: sidebar border width is very thick
screenshot from 2017-04-05 16-06-45

@garrett I think we discussed to make this 3px rather than 7px, but I didn't file an issue about it.

### PR DESCRIPTION
**Pull request by garrett**
fixes #6286

### CODE REVIEW

**Comment by stefwalter** [comment]
Could you include a screenshot?

**Comment by garrett** [comment]
I'm not able to add additional systems to be able to test this change or take a screenshot, unfortunately. (My local build of Cockpit refuses to add remote systems or even 127.0.0.1. Not sure why...)

**Comment by andreasn** [comment]
Here you go:
screenshot from 2017-04-07 21-25-59

**Comment by stefwalter** [comment]
The text of the machine name and the text of the various tasks in the sidebar do not line up. The design says they should.

https://github.com/cockpit-project/cockpit-design/blob/master/navigation/unified-sidebar-host.png

So that's a minor step backwards. Can we fix it in this CSS change?

**Comment by petervo** [comment]
We are redoing the nav instead

**Pull request closed without merging**
