### PR TITLE
TestMenu improvements

### PR DESCRIPTION
**Pull request by martinpitt**
I'm trying to get to the bottom of the [TestMenu.testBasic failure](https://logs.cockpit-project.org/logs/pull-17043-20220224-094403-fd5a366e-rhel-8-6/log.html#138-2) which happens very often. It's our current [top flake](https://logs-https-frontdoor.apps.ocp.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit&days=7) -- it fails in [2 out of 3 cases on centos-8-stream](https://logs-https-frontdoor.apps.ocp.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit&days=7&test=test%2Fverify%2Fcheck-shell-menu+TestMenu.testBasic)!

[example 2](https://logs.cockpit-project.org/logs/pull-17043-20220224-094403-fd5a366e-centos-8-stream/log.html#138-2), [example 3](https://logs.cockpit-project.org/logs/pull-17059-20220228-131339-7b5d1203-centos-8-stream/log.html)

### CODE REVIEW

**Review by marusak — APPROVED** [review]
Thanks!
The 75s check was there to validate that the 60s behavior was not happening always. But I guess if we would happen to break it, then we would notice random log outs in different tests.

**Comment by martinpitt** [comment]
@marusak : Right, I know -- but what makes 60s special if the option isn't set at all? (We used to default to 15 minutes, for example)

**Comment by mvollmer** [comment]
Maybe "test: Avoid override files in /usr where possible" should be its own PR?  It seems rather general and unrelated.

**Comment by mvollmer** [comment]
Which change makes TestMenu more reliable?  Splitting out the session timeout test?

**Comment by martinpitt** [comment]
> Maybe "test: Avoid override files in /usr where possible" should be its own PR?

I initially thought that I could use it for the check-menu setup of the changed manifests. But turns out I can't yet. So it is unrelated indeed, but then it didn't hurt to just piggy-back it here.

> Which change makes TestMenu more reliable? Splitting out the session timeout test?

Mostly yes, at least that's my theory. Showing the "About" dialog takes some considerable time on CI due to all the package querying that happens. My guess is that this already took a significant portion of the idle timeout and thus broke the rather carefully tuned sleeps.

**Comment by mvollmer** [comment]
> > Which change makes TestMenu more reliable? Splitting out the session timeout test?
> 
> Mostly yes, at least that's my theory. Showing the "About" dialog takes some considerable time on CI due to all the package querying that happens. My guess is that this already took a significant portion of the idle timeout and thus broke the rather carefully tuned sleeps.

Makes sense, thanks!

**Pull request merged**
