### PR TITLE
kubernetes: Use topology-graph component

### PR DESCRIPTION
**Pull request by stefwalter**
The code has been factored out so it can be reused
    
https://github.com/kubernetes-ui/topology-graph

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #2382

**Comment by mvollmer** [comment]
I think `topology-graphs.css` is not installed.

**Comment by stefwalter** [comment]
Fixed up topology-graph.css and distribute it.

**Comment by mvollmer** [comment]
The service and node icons have disappeared.  The following patches fixes it, but I don't know what I am doing.

topo

```
diff --git a/pkg/kubernetes/topology-graph.css b/pkg/kubernetes/topology-graph.css
index 1e5b1a3..64166d0 100644
--- a/pkg/kubernetes/topology-graph.css
+++ b/pkg/kubernetes/topology-graph.css
@@ -25,13 +25,13 @@ kubernetes-topology-graph {
 }
 
 .kube-topology g.Node text {
+    font-family: FontAwesome;
     fill: #636363;
-    font-size: 22px;
 }
 
 .kube-topology g.Service text {
+    font-family: FontAwesome;
     fill: #ff7f0e;
-    font-size: 24px;
 }
 
 .kube-topology g.ReplicationController text {
```

**Comment by stefwalter** [comment]
Updated patternfly font. @andreasn @dperpeet. I cherry-picked a patternfly woff font from the latest patternfly. When you update patternfly this will come back into sync.

**Comment by stefwalter** [comment]
This blocks on the patternfly update.

**Pull request closed without merging**
