### PR TITLE
Image refresh for rhel-7

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
`check-kubernetes` looks like it might have regressed.

**Comment by mvollmer** [comment]
@stefwalter, @petervo, check-kubernetes fails consistently. I guess you are much faster debugging this than me.

**Comment by martinpitt** [comment]
Debugging notes:
 * Reliably reproduces locally with our test case.
 * Reliably reproduces manually: On /kubernetes#/nodes/a-mynode pressing the Delete icon and button in the dialog box shows the "could not find the requested resource" error.
 * Running `kubectl delete node a-mynode` works.
 * No journal messages or JS console messages (other than "could not find requested resource") during this.
 * That string is from kubernetes, not Cockpit.

Now need to learn how to debug what cockpit is doing (like logging the REST requests that it makes)

**Comment by martinpitt** [comment]
Stepping through nodes.js `performDelete()` → kube-client.js `deleteResource()` I see that `path == "/api/v1/nodesa-mynode?timeout=120s"`. This is a missing `/` -- if I manually add it in the debugger, the node gets deleted fine.

`resourcePath()` just takes it from the first `Node` argument which has `metadata.selfLink == "/api/v1/nodesa-mynode"`. This comes straight from kubernetes itself: `kubectl get nodes -o yaml` shows:
```yaml
- apiVersion: v1
  kind: Node
  metadata:
    creationTimestamp: 2017-03-08T13:53:22Z
    name: b-mynode
    namespace: ""
    resourceVersion: "128"
    selfLink: /api/v1/nodesb-mynode
```
The above is with this proposed rhel-7 image (fbb203c) with kubernetes 1.5.2-0.2.gitc55cf2b.el7.

It's still correct with the current rhel-7 image (208093) with kubernetes 1.4.0-0.1.git87d9d8d.el7:
```yaml
- apiVersion: v1
  kind: Node
  metadata:
    creationTimestamp: 2017-03-08T14:34:24Z
    name: b-mynode
    resourceVersion: "34"
    selfLink: /api/v1/nodes/b-mynode
```

I'll create a reproducer with only kubectl, report this against kubernetes. Should we ignore this automatic update for now, or add a "naughty" override with the pointer to bugzilla (once it exists)?

**Comment by petervo** [comment]
bugzilla, though i think we already reported this. I could be wrong though

**Comment by martinpitt** [comment]
I filed https://bugzilla.redhat.com/show_bug.cgi?id=1430427 with a trivial CLI reproducer.

**Comment by martinpitt** [comment]
Meh, https://bugzilla.redhat.com/show_bug.cgi?id=1413997 was filed by @stefwalter a while ago already, and got fixed in Fedora-25 in January already (hence I didn't see it when looking for existing bugs), but the regression made it into RHEL only just now :-(

**Comment by mvollmer** [comment]
> but the regression made it into RHEL only just now :-(

This happens way too often, IMO.

**Pull request closed without merging**
