### PR TITLE
bots: Always keep mock cache for Fedora images

### LINKED ISSUE #12836: Image refresh for fedora-testing
Image refresh for fedora-testing
 * [ ] image-refresh fedora-testing

### PR DESCRIPTION
**Pull request by marusak**
Fedora 31 needs this cache, Fedora testing needs it so soon also
Fedora-30 will need it. I think it is just more maintainable to always
keep it.

 * [x] image-refresh fedora-testing

Fixes #12836

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-tests-pw1qz.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12839-20190918-071717/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-testing-20190918-074141

**Comment by marusak** [comment]
Some stats:

original size: 1860543488
original refresh in #12836: 1737843200
this refresh:                        2204400128

**Comment by martinpitt** [comment]
This is really a sad workaround -- we really don't need the mock cache for anything "real". Would it suffice to just keep the empty directory? Entering the mock shouldn't install anything. Perhaps we need to call it with `--offline`?

(Good enough to unblock the image refreshes for now, though)

**Comment by marusak** [comment]
It is sad indeed.
We call mock with `--offline` now.

> Would it suffice to just keep the empty directory?
Maybe it would, I'll try it.

**Pull request merged**
