### PR TITLE
Build: set bower update to non-interactive mode

### PR DESCRIPTION
**Pull request by dperpeet**
Otherwise (if not in CI mode) bower will ask about collecting usage statistics.

### CODE REVIEW

**Comment by stefwalter** [comment]
I'm fine with this, but why is this target being run in CI? It's a make target that should be only manually run.

**Comment by dperpeet** [comment]
We're not setting CI mode anywhere - just mentioning that this config option is automatically set by bower if it's being run in CI mode.

Not including this config option can block scripts that set up virtual machines, as happened to me. The alternative would be to set other flags in environments that depend on the scripts to run (i.e. pretend they're CI). Always setting the flag seems to be the cleaner solution.

**Comment by stefwalter** [comment]
Yeah, fine with me. But the question is why this is being run by a script? The update-bower and update-lib targets should be run manually.

**Comment by dperpeet** [comment]
It happened to me with my scripts for the build process. You're right, it's probably not worth removing possibly useful interaction for the sake of automated runs.

**Pull request closed without merging**
