### PR TITLE
test: Don't run images.setup for the openshift image.

### PR DESCRIPTION
**Pull request by mvollmer**
It is not needed, and the openshift image was not recreated after the
most recent change to images.setup in 507a4c10f11e5843727b1465c19ac1e3e12a07a5.

### CODE REVIEW

**Comment by mvollmer** [comment]
bot: Image refresh for openshift

**Comment by mvollmer** [comment]
> bot: Image refresh for openshift

Ahh, this wont work since openshift is not in DEFAULT_IMAGE_REFRESH...

**Comment by petervo** [comment]
images.setup needs to run on openshift because openshift needs the cockpit/base container built on it so that the other containers can be installed on it with vm-install. 507a4c1 only recreated images that needed the new builddep golong installed inside of mock.

**Comment by mvollmer** [comment]
> images.setup needs to run on openshift because openshift needs the cockpit/base container built on it so that the other containers can be installed on it with vm-install.

I see, thanks!

**Pull request closed without merging**
