### PR TITLE
bots: Remove `Recommends` before parsing `BuildRequires`

### LINKED ISSUE #12217: Image refresh for rhel-7-6
Image refresh for rhel-7-6
 * [ ] FAIL: image-refresh rhel-7-6

### LINKED ISSUE #12220: Image refresh for rhel-7-7
Image refresh for rhel-7-7
 * [ ] FAIL: image-refresh rhel-7-7

### LINKED ISSUE #12221: Image refresh for centos-7
Image refresh for centos-7
 * [ ] FAIL: image-refresh centos-7

### PR DESCRIPTION
**Pull request by marusak**
Recommends: has never been supported by RHEL/CentOS 7. Until recently these
were %if'ed out on RHEL 7, but commit dedd6f7 cleaned that up.

Just remove `Recommends:` with sed as they are not not needed for build
dependencies anyway.

 * [x] image-refresh rhel-7-6
 * [x] image-refresh rhel-7-7
 * [x] image-refresh centos-7

Closes #12217 
Closes #12220 
Closes #12221

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-12225-20190704-075959/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-12225-20190704-075959/

**Comment by martinpitt** [comment]
rhel-7-6 failed:
```
CRITICAL: You must specify a package list to install.
image-create: setup failed with code 50
```

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-01.
Log: https://209.132.184.41:8493/logs/image-refresh-12225-20190704-081515/

**Comment by marusak** [comment]
> rhel-7-6 failed:
`
error: line 363: Unknown tag: Recommends: polkit`

The same error. Ehm, what? Is the sed incorrect?

**Comment by martinpitt** [comment]
Dropping bots for now, as (1) this still needs fixing (please try to build an image locally with the fix, I suggest using `image-create -sv` for better debugging), and (2) our task AMQP stuff still needs some fixing.

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-12225-20190704-081515/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-9.
Log: https://209.132.184.41:8493/logs/image-refresh-12225-20190704-112323/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-12225-20190704-112323/

**Comment by martinpitt** [comment]
PR #12231 has landed. Wash, rinse, repeat.

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-12225-20190704-123333/

**Comment by cockpituous** [comment]
image-refresh rhel-7-6 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-6-20190704-130808

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-12225-20190704-130909/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-12225-20190704-132828/

**Comment by cockpituous** [comment]
image-refresh rhel-7-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-7-20190704-135858

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-12225-20190704-134040/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-12225-20190704-134040/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-12225-20190704-134848/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20190704-141414

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://209.132.184.41:8493/logs/image-refresh-12225-20190704-134848/

**Comment by martinpitt** [comment]
@marusak: all builds done \o/

**Pull request merged**
