### PR TITLE
Image refresh for fedora-i386

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-i386
 * [x] image-refresh fedora-i386

### CODE REVIEW

**Comment by martinpitt** [comment]
Tons of new SELinux regressions:
```
audit: type=1400 audit(1545957638.464:291): avc:  denied  { getattr } for  pid=1381 comm="find" path="/proc/irq" dev="proc" ino=4026531861 scontext=system_u:system_r:pcp_pmlogger_t:s0 tcontext=system_u:object_r:sysctl_irq_t:s0 tclass=dir permissive=0
```

**Comment by martinpitt** [comment]
Pushed a fix. The external tests are irrelevant here, but the bots add them back too aggressively :)

**Comment by martinpitt** [comment]
More violations:
```
audit: type=1400 audit(1546414462.035:582): avc:  denied  { execute } for  pid=1678 comm="which" name="setfiles" dev="vda4" ino=12835245 scontext=system_u:system_r:pcp_pmlogger_t:s0 tcontext=system_u:object_r:setfiles_exec_t:s0 tclass=file permissive=0
```
I reported a downstream bug and pushed a fix.

There also seems to be an [OpenSSL/FreeIPA regression](https://fedorapeople.org/groups/cockpit/logs/pull-10886-20190102-072020-5c709344-verify-fedora-i386/log.html#152), but I can't investigate this right now.

**Comment by KKoukiou** [comment]
There are some reminders, https://fedorapeople.org/groups/cockpit/logs/pull-10886-20190102-093232-cc946a05-verify-fedora-i386/log.html#54

I opened separate bz for that https://bugzilla.redhat.com/show_bug.cgi?id=1662983

I am not force pushing the hack till we figure out the FreeIPA regression as well.

``` diff
diff --git a/test/common/testlib.py b/test/common/testlib.py
index 4fe1047f5..c9e50b071 100644
--- a/test/common/testlib.py
+++ b/test/common/testlib.py
@@ -884,6 +884,9 @@ class MachineCase(unittest.TestCase):
             self.allowed_messages.append('audit: type=1400 audit(.*): avc:  denied  { getattr } for .* comm="find" path="/proc.*')
             # HACK: https://bugzilla.redhat.com/show_bug.cgi?id=1662866
             self.allowed_messages.append('audit: type=1400 audit(.*): avc:  denied  { execute } for .* comm="which" .*pcp_pmlogger_t.*')
+            # HACK: https://bugzilla.redhat.com/show_bug.cgi?id=1662983
+            self.allowed_messages.append('audit: type=1400 audit(.*): avc:  denied  { mount } for .* comm="find" .*pcp_pmlogger_t.*')
+
```

**Comment by martinpitt** [comment]
I investigated and reported the IPA regression, pushed a naughty override.

**Comment by martinpitt** [comment]
For $deity's sake, there is *yet another* IPA regression, exposed in ``TestRealms.testIpaUnqualifiedUsers`.

**Comment by martinpitt** [comment]
I investigated this in https://bugzilla.redhat.com/show_bug.cgi?id=1663123 . Turns out that the crash is already fixed, so rebuilding the image.

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-m06nn.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10886-20190103-091717/

**Comment by cockpituous** [comment]
image-refresh fedora-i386 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-i386-20190103-094040

**Pull request merged**
