### PR TITLE
login: Use form on login page

### LINKED ISSUE #15335: Login page is not a proper HTML form
Cockpit version: 215
OS: Ubuntu 20.04
Page: -

The login form is not a html `<form>` element.
This leads to bad accessibility but also a degraded experience in general. For example my browser does not prompt to save the password.

Steps to reproduce

1. Open the cockpit website (without being logged in) in - you should see the login page
2. Inspect the DOM - there is no `<form>` element but only a `<div role="form">`
3. Login with your username/password - in Chrome at least you will not be prompted to save the password

I assume the autofill issue is also due to not using a proper form element. By looking at the code it seems that the login process is for some reason implemented mostly client side in JS for some reason unknown to me. However HTML5 also allows form elements with no action attribute which could be used instead of the current div.

### PR DESCRIPTION
**Pull request by marusak**
Fixes #15335

### CODE REVIEW

**Comment by martinpitt** [comment]
I think that's about the third PR that tries that, and they always have failed. Somehow it refuses to be that simple :cry:

**Comment by martinpitt** [comment]
Interesting! Seems the integration tests are actually happy for the most part, and it's only selenium which needs updating. So apparently we got over whatever was breaking it in the past with some intermediary redesign. Yay!

**Comment by marusak** [comment]
When I compare with your last try:  https://github.com/cockpit-project/cockpit/issues/6399#issuecomment-544405791
The difference mainly seems to be submit on button.

**Comment by marusak** [comment]
Meh, why is firefox and edge unhappy? I'll try locally firefox.

**Comment by marusak** [comment]
Indeed, firefox breaks

**Comment by marusak** [comment]
With the new version also works on firefox. And now it even remembers user name, which it did not before (before it only remembered password).

**Comment by marusak** [comment]
Works like a charm!

**Review by martinpitt — APPROVED** [review]
Thanks for figuring out the magic incantation!

**Pull request merged**
