### PR TITLE
Rewrite ssh keys fingerprints modal into React and PF4 and other fixes

### PR DESCRIPTION
**Pull request by marusak**

### CODE REVIEW

**Review by KKoukiou — DISMISSED** [review]
Retriggered the unit tests - once they pass this is good to go in

**Comment by marusak** [comment]
needs rebase :/ We had that broken npm update and unit tests don't rebase

**Review by KKoukiou — APPROVED** [review]

**Comment by marusak** [comment]
sorry, by mistake pushed one more commit which broke tuned

**Comment by marusak** [comment]
Ok, now tests are really happy, @KKoukiou can I ask you for one more ack? :)

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
