### PR TITLE
RHEL 7.8 backports

### PR DESCRIPTION
**Pull request by martinpitt**
See individual commits for details.

 - [x] fix testAddDisk
 - [x] add korean translation
 - [x] pull translations again, they got updated to 100%
 - [x] enable libvirt-dbus dependency, after landing https://github.com/cockpit-project/bots/pull/136

### CODE REVIEW

**Comment by marusak** [comment]
Can we also please test centos-7 due to https://github.com/cockpit-project/bots/pull/104

**Comment by martinpitt** [comment]
@marusak : I already triggered that right after landing that :)

**Comment by martinpitt** [comment]
@skobyda , @KKoukiou : This breaks [testAddDisk](https://209.132.184.41:8493/logs/pull-12974-20191014-112727-302a5cb8-cockpit-project-cockpit--rhel-7-8/log.html#1-2) -- does that ring a bell? Am I missing another commit that needs to be backported?

**Comment by KKoukiou** [comment]
> @skobyda , @KKoukiou : This breaks [testAddDisk](https://209.132.184.41:8493/logs/pull-12974-20191014-112727-302a5cb8-cockpit-project-cockpit--rhel-7-8/log.html#1-2) -- does that ring a bell? Am I missing another commit that needs to be backported?

Probably this 34b13a00b1422bf59990f575aa48e7167d72e00c?

**Comment by martinpitt** [comment]
@KKoukiou : That's the obvious one (part of the original PR, I got all of them); that one is [included here](https://github.com/cockpit-project/cockpit/pull/12974/commits/4e1c5012c72ab).

**Comment by KKoukiou** [comment]
> @KKoukiou : That's the obvious one (part of the [original PR](https://github.com/cockpit-project/cockpit/pull/12120), I got all of them); that one is [included here](https://github.com/cockpit-project/cockpit/pull/12974/commits/4e1c5012c72ab).

Right, didn't notice. I will need to checkout this branch to figure this out. Will get back here.

**Comment by KKoukiou** [comment]
> @KKoukiou : That's the obvious one (part of the [original PR](https://github.com/cockpit-project/cockpit/pull/12120), I got all of them); that one is [included here](https://github.com/cockpit-project/cockpit/pull/12974/commits/4e1c5012c72ab).

First thing I noticed is that we run the virsh tests against the rhel-7-8 image - this should not be the case since libvirt-dbus is available in extras rhel-7-8.
Still debugging the failing test though.

**Comment by martinpitt** [comment]
Just testNodeNavigation now. I'll retry for a while, but that's a known flake. Ready for reviewing.

**Pull request merged**
