### PR TITLE
Don't clear dashboard plots all the time

### LINKED ISSUE #1760: Dashboard graphs discard already loaded data, when you change graph tabs
The dashboard graphs now discard any already loaded data when you change graph tabs. It used to be the case that this data remained available. Now, each time I click to a new tab, everything starts again from the right.

### PR DESCRIPTION
**Pull request by mvollmer**
Fixes #1760

### CODE REVIEW

**Comment by mvollmer** [comment]
Depends on #1778 for bug fixes that should make the tests pass.

**Comment by stefwalter** [comment]
Depends on #1778

**Comment by mvollmer** [comment]
(I think I found a way to reproduce the real time resampling bug...)

**Comment by mvollmer** [comment]
> (I think I found a way to reproduce the real time resampling bug...)

Ok, to reproduce, click about 10 times on "1 week" in short succession.  This will keep the bridge busy enough that the real time sampling will miss its tick deadline and the rate conversion in the client will be off, because it assumes a constant interval.

I'll split this out into a separate pull request.

**Pull request closed without merging**
