### PR TITLE
bots: Replace in fedora libvirt package requirement with libvirt-daemon-kvm

### PR DESCRIPTION
**Pull request by KKoukiou**
* [x] image-refresh fedora-28
 * [x] image-refresh fedora-29
 * [x] image-refresh fedora-i386
 * [x] image-refresh fedora-testing
 * [x] update spec dependencies: PR #10203

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-6d2qr.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10205-20181002-162020/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10205-20181002-162020/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-z753z.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10205-20181002-164040/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10205-20181002-164040/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-6d2qr.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10205-20181002-171212/

**Comment by cockpituous** [comment]
image-refresh fedora-i386 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-i386-20181002-173333

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-6d2qr.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10205-20181002-173434/

**Comment by martinpitt** [comment]
@KKoukiou : Note that PR #10142 tries to refresh the fedora-29 image, it needs some adjustments. Feel free to haul over the extra commits from there to here. But tests are very unstable for fedora-29 right now, so it's hard to get that green :-(

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-4v0t0.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10205-20181003-053737/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-testing-20181003-062323

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-d61cv.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10205-20181004-060202/

**Comment by cockpituous** [comment]
image-refresh fedora-28 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-28-20181004-064747

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-cjn9x.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10205-20181004-064949/

**Comment by cockpituous** [comment]
image-refresh fedora-29 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-29-20181004-071919

**Comment by martinpitt** [comment]
@KKoukiou : All refreshes are done. Please grab the commits, and the extra fixes for f-29 (see above).

Also, if you want to untangle this from rebuilding all images, I suggest to temporarily leave an alternative "libvirt" dependency, land the dep fix PR, then rebuild all images, and once they are all done, drop the libvirt dependency again. This seems a lot less painful. But your call :)

**Comment by martinpitt** [comment]
This [breaks the machines tests](https://fedorapeople.org/groups/cockpit/logs/pull-10205-20181004-150909-d1f01cc5-verify-fedora-28/log.html#33) due to a missing "default" libvirt network. Presumably this is provided by a dependency of libvirt, which is now gone?

**Comment by KKoukiou** [comment]
> This [breaks the machines tests](https://fedorapeople.org/groups/cockpit/logs/pull-10205-20181004-150909-d1f01cc5-verify-fedora-28/log.html#33) due to a missing "default" libvirt network. Presumably this is provided by a dependency of libvirt, which is now gone?

Indeed. Added libvirt-daemon-config-network which bring default network. It's only test dependency so no changes in the spec file.

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-h5v1g.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10205-20181005-074141/

**Comment by cockpituous** [comment]
image-refresh fedora-28 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-28-20181005-081010

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-lfdjj.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10205-20181005-081414/

**Comment by cockpituous** [comment]
image-refresh fedora-29 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-29-20181005-090404

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-d2llw.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10205-20181005-090101/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-testing-20181005-100707

**Comment by martinpitt** [comment]
I reported the grub2-mkconfig regression (https://bugzilla.redhat.com/show_bug.cgi?id=1637055) and added a naughty override for it.

**Pull request merged**
