### PR TITLE
shell: Wrap account in standard container

### PR DESCRIPTION
**Pull request by petervo**
Accounts needs a little work at some point, but to avoid blocking other work, for now this just makes the detail table look like the other containers on the site.

### CODE REVIEW

**Comment by andreasn** [comment]
Since "Server Administrator" is the only role we have right now (if I recall correctly), can we make that a checkbox instead?
[x] Server Administrator

**Comment by andreasn** [comment]
the table containing the controls needs a margin of 15px

**Comment by petervo** [comment]
I was hoping to avoid redoing the roles as part of this, but here you go.

**Comment by andreasn** [comment]
> I was hoping to avoid redoing the roles as part of this, but here you go.

Thanks for fixing that as part of this pull. It's been bugging me for quite a while in general.

**Comment by andreasn** [comment]
Apart from the col-sm-5 thing, this looks good from a UI point of view!

**Comment by stefwalter** [comment]
Merged into master.

**Pull request closed without merging**
