### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-6lpk6.
Log: https://209.132.184.41:8493/logs/image-refresh-11610-20190415-214646/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-11610-20190415-214646/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-6lpk6.
Log: https://209.132.184.41:8493/logs/image-refresh-11610-20190416-035555/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-testing-20190416-043535

**Comment by marusak** [comment]
Stiiiiil the same issue

**Comment by martinpitt** [comment]
@marusak: Wait, this is different now:

   etcd                                         x86_643.2.16-6.fc29                      updates         11 M

This image didn't actually use etcd from updates-testing? I also tried to run this on our clean F-29 VM:

```
# dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2019-049b108f40
Nothing to do.

# dnf upgrade --enablerepo=updates-testing etcd
Nothing to do.
```
Apparently it's not published yet?

I used `koji download-build` for that, upgraded manually, and it still fails (but differently now). I'll report on the bodhi update.

So it seems that weird `!<arch>' issue comes from something else in fedora-testing?

**Comment by martinpitt** [comment]
There is a new build: https://bodhi.fedoraproject.org/updates/FEDORA-2019-219b0b0b6a

I validated this manually. As soon as it's  available in updates-testing, we can close this PR and build a new image.

**Comment by martinpitt** [comment]
bodhi update is finally published, let's try again -- 4th time is the charm!

**Pull request closed without merging**
