### PR TITLE
test: Drop rhel-8* from supported OSes, fix for ruff 0.3.1 (fixes failing "tox" test)

### PR DESCRIPTION
**Pull request by martinpitt**
That doesn't work any more, RHEL 8 testing now happens on the `rhel-8` branch.

----

This is primarily an excuse to work out our shiny new job-runner CI.

### CODE REVIEW

**Comment by martinpitt** [comment]
Ah, the [tox failure](https://github.com/cockpit-project/cockpit/actions/runs/8191059370/job/22399422289?pr=20149#step:5:19) is due to new ruff 0.3.1, similar to what I just fixed in https://github.com/cockpit-project/bots/pull/6035 . I'll fix it here.

**Comment by martinpitt** [comment]
The [/devel failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20149-0b27d12c-20240308-034758-fedora-39-devel/log.html#386-1) is a flake, but only in the 2nd retry. But primarily it is a failure with job-runner to upload coverage attachment, see https://github.com/cockpit-project/bots/issues/6042 . This doesn't need to block landing this PR.

**Comment by martinpitt** [comment]
Re-running, as the "directory attachments" fix landed.

**Review by allisonkarlitskaya — APPROVED** [review]
Just out of curiosity: was that a case of `--fix` or did you do it?

**Comment by martinpitt** [comment]
@allisonkarlitskaya I did it manually. I tried `--fix` on the bots PR, and it didn't want to do anything.

**Pull request merged**
