### PR TITLE
Glib build cleanup

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**

### CODE REVIEW

**Comment by martinpitt** [comment]
Still fails on semaphore and debian-stable: `gdbus-codegen: error: no such option: --output-directory`

**Comment by allisonkarlitskaya** [comment]
lol.  there's always tomorrow.

**Comment by allisonkarlitskaya** [comment]
This is beautiful:

https://www.gnu.org/software/automake/manual/html_node/Multiple-Outputs.html

**Comment by martinpitt** [comment]
@allisonkarlitskaya : I force-pushed this PR to rebase against latest master, to get the bots → test migration bits and avoid the obsolete RHEL 7 test statuses.

**Pull request merged**
