### PR TITLE
Rework the machine loader and behavior

### PR DESCRIPTION
**Pull request by stefwalter**
* Rework the machine json loader
 * Show a spinner in navbar and curtains for failure

### CODE REVIEW

**Comment by stefwalter** [comment]
This shouldn't be trying to connect to 10.0.0.0 even though the test tells it to. Will fix.

**Comment by stefwalter** [comment]
That should do the trick.

**Comment by stefwalter** [comment]
This isn't right: 

check-multi-machine-testbasic-fail

**Comment by stefwalter** [comment]
Depends on #2767

**Comment by stefwalter** [comment]
@petervo I think this is ready for review and merging. The TestShutdownRestart failure is being fixed by @dperpeet

**Comment by petervo** [comment]
Before a side effect of the way things were loading was that it wasn't really possible to get to the dashboard on a secondary server, now it is.  Don't think this is really a problem necessarily, but it is a change in behavior. Are we ok with that? Or should we implement something to kick users from secondary server dashboards.

**Comment by petervo** [comment]
Is compatibility with old servers a separate PR?

**Comment by petervo** [comment]
The expect restart behavior doesn't work. Now that we are doing the curtains with the reconnect button instead, should we just drop that feature? Doesn't seem needed anymore.

**Comment by stefwalter** [comment]
> Before a side effect of the way things were loading was that it wasn't really possible to get to the dashboard on a secondary server, now it is. Don't think this is really a problem necessarily, but it is a change in behavior. Are we ok with that? 

How did you get to a different dashboard? Via editing the URL? If so, then I think that's fine.

**Comment by stefwalter** [comment]
> Is compatibility with old servers a separate PR?

Yes, working on that. It is already broken in git master.

>  The expect restart behavior doesn't work. Now that we are doing the curtains with the reconnect button instead, should we just drop that feature? Doesn't seem needed anymore.

I'll try and fix it.

**Comment by petervo** [comment]
Secondary dashboard was manual navigation. The current automatic jumps should all be ok.

We can probably fix the restart stuff in a different pr.

**Comment by stefwalter** [comment]
Fixed the curtains to respect restarting, and show a relevant message. In addition, do the redirect to the dashboard.

**Pull request closed without merging**
