### PR TITLE
Image refresh for rhel-8-0

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-0
 * [x] image-refresh rhel-8-0

### CODE REVIEW

**Comment by marusak** [comment]
There are 10 failed tests (I've retried and 10 fails are the same). Marking as needs works. Will try to run it locally and create TODO list.

**Comment by martinpitt** [comment]
@marusak : Eww, yes. See e. g. [this journal](https://fedorapeople.org/groups/cockpit/logs/pull-11288-20190304-060606-82baaf83-verify-rhel-8-0/TestUpdates-testBasic-rhel-8-0-127.0.0.2-2901-FAIL.log). There's core dumps as well in the parent dir, btw, but I suppose these are easy enough to reproduce. For reporting, please enable the debuginfo repo (ask me on IRC), then you can use `coredumpctl debug`.

**Comment by marusak** [comment]
Blocking on downstream bug https://bugzilla.redhat.com/show_bug.cgi?id=1685037
Hopefully this gets fixed fast enough so we don't need to naughty-fy it.

**Comment by martinpitt** [comment]
@marusak: Are you able to reproduce this with a standalone recipe/script? I'm trying with http://piware.de/tmp/u.py , but I just can't get it to crash.

**Comment by martinpitt** [comment]
@marusak: Nevermind, I found a standalone reproducer, I'll send it to the downstream bug.

**Comment by martinpitt** [comment]
@marusak: A fix just landed upstream, and I suppose it will be uploaded to RHEL today. So waiting until then is completely fine.

**Comment by martinpitt** [comment]
Fixed subscription-manager is now in the nightlies, so let's try a new image build.

**Pull request closed without merging**
