### PR TITLE
backport: 7.3.6 branch

### PR DESCRIPTION
**Pull request by dperpeet**
Two commits we need downstream:

- ssh hookup channel callbacks
- dashboard/ssh dependencies

The dependencies need to be changed, because the necessary patches beyond 138 are included in the downstream 138 release.

### CODE REVIEW

**Comment by martinpitt** [comment]
I believe I found why testing is broken here and in #7147. I filed issue #7255 about it.

**Comment by martinpitt** [comment]
I finally managed to unbreak testing for backport branches, so the "failed to download images.." is gone. However, there now are an afwul number of failures on centos-7 and rhel-7 :(

**Comment by martinpitt** [comment]
I did a force-push here with no actual changes, but just a `git co --amend` to change the topmost SHA. Otherwise github can't tell apart this PR from #7147 as they both have the same commit SHAs (but different target branches). This should work around the confusion.

**Comment by martinpitt** [comment]
Like in #7147, the vast majority of test failures are due to the recent `perms=transition` audit messages. They got ignored in https://github.com/cockpit-project/cockpit/commit/b870d04a6223 and harder in https://github.com/cockpit-project/cockpit/commit/0b0068447c so we need to backport these too. I squashed the two together and put them on top here.

**Comment by dperpeet** [comment]
obsoleted by 7.4 release

**Pull request closed without merging**
