### PR TITLE
WIP - storaged: Allow changing of iSCSI initiator name.

### PR DESCRIPTION
**Pull request by mvollmer**
Depends on #2807.

### CODE REVIEW

**Comment by mvollmer** [comment]
@andreasn, I have just added one more ugly global storage button.  I think we need to figure out a better way for this.

**Comment by andreasn** [comment]
Do I need any specific service in order to test this out? I see the "Change iSCSI name.." button, but it doesn't work.

**Comment by mvollmer** [comment]
> Do I need any specific service in order to test this out?

You need to install the `stroaged-iscsi` package.

> I see the "Change iSCSI name.." button, but it doesn't work.

Heh, you shouldn't see that button at all unless storaged-iscsi is installed.  I fix that.

**Comment by mvollmer** [comment]
> you shouldn't see that button at all unless storaged-iscsi is installed. I fix that.

Done.

**Comment by stefwalter** [comment]
Could you add a note in the features-storaged.xml about iSCSI on which commands to use to accomplish similar tasks from the command line? Are there fundamental limitations (auth?) that someone troubleshooting or deploying Cockpit might want to know about the internals?

**Comment by mvollmer** [comment]
> Could you add a note in the features-storaged.xml [...]

I think this should be done in #2807.

**Comment by mvollmer** [comment]
>> Could you add a note in the features-storaged.xml [...]

> I think this should be done in #2807.

Done.

**Comment by mvollmer** [comment]
Folded into #2807.

**Pull request closed without merging**
