### PR TITLE
test: Fix embed-cockpit.html

### PR DESCRIPTION
**Pull request by martinpitt**
- Fix css and script links to use actually existing URLs. This turns
   the page from "completely broken" to "mostly pleasant with a few
   quirks" (but good enough for our test case).

 - Declare encoding to avoid browser complaint.

 - Drop the navbar menu, none of the menu items are actually working as
   they all point to nonexisting files.

----

I noticed this while debugging the failed `check-embed` test case in #8069 (due to "Blocked a frame with origin "null" from accessing a cross-origin frame"). This PR doesn't fix it, but turns the page from this:

broken

into this:

fixed

and fixes the folllowing log messages:
```
GET https://rawgit.com/patternfly/patternfly/master/dist/css/patternfly.min.css [HTTP/2.0 404 Not Found 32ms]
GET https://rawgit.com/patternfly/patternfly/master/dist/css/patternfly-additions.min.css [HTTP/2.0 404 Not Found 35ms]
GET https://rawgit.com/patternfly/patternfly/master/dist/js/patternfly.min.js [HTTP/2.0 404 Not Found 34ms]
The resource from “https://rawgit.com/patternfly/patternfly/master/dist/css/patternfly.min.css” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).[Learn More]  (unknown)
The resource from “https://rawgit.com/patternfly/patternfly/master/dist/css/patternfly-additions.min.css” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).[Learn More]  (unknown)
The resource from “https://rawgit.com/patternfly/patternfly/master/dist/js/patternfly.min.js” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).[Learn More]  (unknown)
GET https://rawgit.com/patternfly/patternfly/master/dist/js/patternfly.min.js [HTTP/2.0 404 Not Found 31ms] The resource from “https://rawgit.com/patternfly/patternfly/master/dist/js/patternfly.min.js” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).[Learn More]  (unknown)
Loading failed for the <script> with source “https://rawgit.com/patternfly/patternfly/master/dist/js/patternfly.min.js”.  embed-cockpit.html:13
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.  embed-cockpit.html
```

### CODE REVIEW

**Comment by petervo** [comment]
Tests are broken

```
Resource Error: Error opening /build/cockpit/dist/base1/patternfly.min.css: No such file or directory file:///build/cockpit/dist/base1/patternfly.min.css
Resource Error: Error opening /build/cockpit/dist/base1/patternfly-additions.css: No such file or directory file:///build/cockpit/dist/base1/patternfly-additions.css
Resource Error: Error opening /build/cockpit/dist/base1/jquery.min.js: No such file or directory file:///build/cockpit/dist/base1/jquery.min.js
Page error: Error: Bootstrap's JavaScript requires jQuery
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js 6 global code
```

**Comment by martinpitt** [comment]
Wow, it passes locally, so the different build path on the bots seems to make a difference.

It's actually quite inexplicable to me how check-embed could *ever* work on a VM without network access, given that it downloads jquery and bootstrap from an external URL. Test in master yells
```
-> open('file:///home/martin/upstream/cockpit/test/verify/files/embed-cockpit.html')
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8): No such file or directory
Resource Error: Error downloading https://rawgit.com/patternfly/patternfly/master/dist/css/patternfly-additions.min.css - server replied: Not Found https://rawgit.com/patternfly/patternfly/master/dist/css/patternfly-additions.min.css
Resource Error: Error downloading https://rawgit.com/patternfly/patternfly/master/dist/js/patternfly.min.js - server replied: Not Found https://rawgit.com/patternfly/patternfly/master/dist/js/patternfly.min.js
Resource Error: Error downloading https://rawgit.com/patternfly/patternfly/master/dist/css/patternfly.min.css - server replied: Not Found https://rawgit.com/patternfly/patternfly/master/dist/css/patternfly.min.css
Resource Error: Error downloading https://rawgit.com/patternfly/patternfly/master/dist/img/brand.svg - server replied: Not Found https://rawgit.com/patternfly/patternfly/master/dist/img/brand.svg
('<-', 'None')
```
but curiously it doesn't yell about `<script src="//code.jquery.com/jquery-2.1.4.min.js"></script>`.

**Comment by stefwalter** [comment]
Pushed an additional commit to this to remove use of jQuery.

**Comment by martinpitt** [comment]
LGTM, thanks! I'll land once the tests get green.

**Pull request merged**
