### PR TITLE
WIP: machines: Add after-installation configuration file

### PR DESCRIPTION
**Pull request by mareklibra**
Optional configuration can be provided by administrator
once the cockpit-machines package is installed.
    
Defaults or effective configuration is printed to log for review
or easy copy&paste setup.
    
The expected use-case is especially to configure Libvirt's
connection URI or turn on/off debug messages.
    
Location: `/etc/cockpit/virtual-machines.config`

Fixes: https://github.com/cockpit-project/cockpit/issues/7484

---
- [ ] Tests

### CODE REVIEW

**Comment by Antique** [comment]
I'm not sure wether exposing URI configuration to admins is good idea, it might encourage them to configure remote URI or some other from Cockpit POV crazy ideas.

In addition this will not work well with libvirt-dbus. Currently the concept of libvirt-dbus is that for each driver you have a connection object, for example '/org/libvirt/QEMU' or '/org/libvirt/LXC' and whether you are using session or system connection depends on the system/session D-Bus message bus.

**Comment by mareklibra** [comment]
> I'm not sure wether exposing URI configuration to admins is good idea, it might encourage them to configure remote URI or some other from Cockpit POV crazy ideas.

If remote libvirt connection is the use-case the user is looking for, there's still simple way to hack it via scripts, i.e. by renaming `/usr/bin/virsh` or so.

Motivation behind this PR is mostly in allowing the user to switch the datasource as simply as he can do it recently on command-line by just providing different connection URI.
Why? To optionally add i.e. LXC, to remove `session` if misleading in particular setup or to meet local "weird" configuration where i.e. `qemu:///system` must be replaced by network connection.

There's still `migration` as a planed feature. Additional connection URI might help here.

And sure, management of remote libvirt systems will become possible, no matter this is not the motivation for this PR and probably will not be officially claimed as supported.
But if the user is willing to connect this way, why to block it? The administrator needs to do an extra step via i.e. terminal to configure it. If so, he can already do a lot of other weird things, not only related to Cockpit.

On the other hand, this is not completely new concept to Cockpit - we can already connect to other hosts and manage them from single Cockpit instance.

> In addition this will not work well with libvirt-dbus. Currently the concept of libvirt-dbus is that for each driver you have a connection object, for example '/org/libvirt/QEMU' or '/org/libvirt/LXC' and whether you are using session or system connection depends on the system/session D-Bus message bus.

Good point. Looking forward to see this released. Do you have any estimation when will this happen?

Transformation from `virsh` to `libvirt-dbus` will require much more changes. 
Such a config file will need to be changed, but the user should still have option to select where to connect. Since the config file change will be probably incompatible, time-frame of `libvirt-dbus` adoption is important for this PR.

**Comment by Antique** [comment]
> > I'm not sure wether exposing URI configuration to admins is good idea, it might encourage them to configure remote URI or some other from Cockpit POV crazy ideas.
> 
> If remote libvirt connection is the use-case the user is looking for, there's still simple way to hack it via scripts, i.e. by renaming `/usr/bin/virsh` or so.

In this case if something breaks don't expect any support from cockpit.

> Motivation behind this PR is mostly in allowing the user to switch the datasource as simply as he can do it recently on command-line by just providing different connection URI.
> Why? To optionally add i.e. LXC, to remove `session` if misleading in particular setup or to meet local "weird" configuration where i.e. `qemu:///system` must be replaced by network connection.

I see the motivation and having an option to select default hypervisor is desirable, however having an option to select the current hypervisor from the GUI would be event better.

In the cockpit configuration file we can have the hypervisor name and possibly session/system selection but I would avoid using the URI itself.  This way it would be compatible with libvirt-dbus once we start using it in cockpit.

> There's still `migration` as a planed feature. Additional connection URI might help here.

In order to build migration URI it should be sufficient to know the remote host name or IP address and the transport layer and the URI will be generated.

> And sure, management of remote libvirt systems will become possible, no matter this is not the motivation for this PR and probably will not be officially claimed as supported.
> But if the user is willing to connect this way, why to block it? The administrator needs to do an extra step via i.e. terminal to configure it. If so, he can already do a lot of other weird things, not only related to Cockpit.

The reason why not to export URI directly is that it might look like we support it and users will definitely try to use it and they will report bugs for it.

> On the other hand, this is not completely new concept to Cockpit - we can already connect to other hosts and manage them from single Cockpit instance.

This should be the correct way how to manage machines on a different host.

> > In addition this will not work well with libvirt-dbus. Currently the concept of libvirt-dbus is that for each driver you have a connection object, for example '/org/libvirt/QEMU' or '/org/libvirt/LXC' and whether you are using session or system connection depends on the system/session D-Bus message bus.
> 
> Good point. Looking forward to see this released. Do you have any estimation when will this happen?

I hope that in two weeks I'll release new libvirt-dbus version with stable APIs and management application may start using it.

**Comment by mareklibra** [comment]
From my perspective, ability to configure datasource (connection URI) is important to meet needs of various deployment setups.

Anyway, #7484 issue can wait a little bit, if libvirt-dbus release is so close and the change here would be incompatible.

**Comment by KKoukiou** [comment]
I think we can close this as WONT DO.
 I am exposing the connection URI where needed in the UI so no need for configuration for it for local connection. From dbus we don't support remote connections, so this should not be allowed anyway.
The debug messages I think are not important enough to introduce this config file.

**Pull request closed without merging**
