### PR TITLE
package.json: Update angular-bootstrap-npm package dependency

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```package.json:    "angular-bootstrap-npm": "0.13.4",
pkg/kubernetes/scripts/app.js:    require('angular-bootstrap-npm/dist/angular-bootstrap.js');
pkg/kubernetes/scripts/charts.js:    require('angular-bootstrap-npm/dist/angular-bootstrap.js');
pkg/kubernetes/scripts/main.js:    require('angular-bootstrap-npm/dist/angular-bootstrap.js');
pkg/kubernetes/scripts/registry.js:    require('angular-bootstrap-npm/dist/angular-bootstrap.js');
pkg/lib/angular-dialog.js:    require('angular-bootstrap-npm/dist/angular-bootstrap.js');
pkg/ostree/app.js:    require('angular-bootstrap-npm/dist/angular-bootstrap.js');
```

**Comment by martinpitt** [comment]
Force-pushed a rebase to fix the conflict.

**Comment by martinpitt** [comment]
[previous test run](https://fedorapeople.org/groups/cockpit/logs/pull-7351-20170721-133434-72605468-verify-rhel-7/log.html#63) on centos/rhel-7 failed `testImagestreamImport (check_openshift.TestRegistry)`. Log looks like a flake, but retrying to be sure.

**Comment by stefwalter** [comment]
@martinpitt This is likely a race with the browser ... testing.

**Comment by stefwalter** [comment]
Found an incompatibility between tests and angular-bootstrap-npm. Fixed.

**Pull request closed without merging**
