### PR TITLE
Fix f22 master tests

### PR DESCRIPTION
**Pull request by mvollmer**
Hopefully.

### CODE REVIEW

**Comment by mvollmer** [comment]
```
+ systemctl start docker
Job for docker.service failed. See "systemctl status docker.service" and "journalctl -xe" for details.
```

**Comment by mvollmer** [comment]
> Job for docker.service failed

That was probably a time out.  Docker creates it's storage pool on first startup, and that might take quite long, maybe.

**Comment by stefwalter** [comment]
> That was probably a time out. Docker creates it's storage pool on first startup, and that might take quite long, maybe.

Then it's a real world bug, no?

**Comment by mvollmer** [comment]
> Then it's a real world bug, no?

Yes.  I'll collect some data and then file a bug. 

"Real-time timeouts in a non-real-time system are bogus."  -- me

**Pull request closed without merging**
