### PR TITLE
package.json: Update @patternfly/react-table package dependency

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
npm-update @patternfly/react-core done: https://github.com/cockpituous/cockpit/commits/npm-update-@patternfly/react-core-20200920-052828

**Comment by cockpituous** [comment]
Error accessing /repos/cockpit-project/cockpit/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value"None,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}: https://logs.cockpit-project.org/logs/npm-update-14640-20200920-052626/

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "@patternfly/react-table": "4.16.20",
pkg/lib/cockpit-components-table.jsx:} from '@patternfly/react-table';
pkg/networkmanager/firewall.jsx:import { cellWidth } from '@patternfly/react-table';
pkg/storaged/fsys-panel.jsx:import { cellWidth, SortByDirection } from '@patternfly/react-table';
pkg/storaged/nfs-panel.jsx:import { cellWidth, SortByDirection } from '@patternfly/react-table';
pkg/systemd/hwinfo.jsx:import { SortByDirection } from "@patternfly/react-table";
```

**Comment by cockpituous** [comment]
npm-update in progress on centosci-tasks-c2ltb.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/npm-update-14640-20200920-052626/

**Comment by mvollmer** [comment]
> Do we need to update react-core at the same time? Does that mean react-table declares wrong dependencies?

We need to udpate it, and react-table declares the right dependency. I guess this just is how npm works.

**Comment by mvollmer** [comment]
Let's make a new one without conflicts.

**Pull request closed without merging**
