### PR TITLE
networking:  Use textual API variant for addresses

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
Debian 8 doesn't have this API yet.

**Comment by stefwalter** [comment]
It seems unlilkely that Debian Jessie will upgrade to NetworkManager 1.0 doesn't it?

**Comment by mvollmer** [comment]
> It seems unlilkely that Debian Jessie will upgrade to NetworkManager 1.0 doesn't it?

Yes, that's what I think, too.  Should we simply wait with this until we stop releasing for Debian 8?

The motivation to switch to it was to remove some of our buggy code, instead of fixing the bugs in it  (IPv6 address parsing).  However, the new API will silently ignore strings that can't be parsed, so we need to do our own validation anyway.

So, now I think I should just fix the bugs.

**Comment by mvollmer** [comment]
The bugs:

https://bugzilla.redhat.com/show_bug.cgi?id=1402309
https://bugzilla.redhat.com/show_bug.cgi?id=1402736

**Comment by stefwalter** [comment]
> So, now I think I should just fix the bugs.

Makes sense.

**Comment by mvollmer** [comment]
This is history...

**Pull request closed without merging**
