### PR TITLE
Drop rhel-7 image in favor of *-distropkg test mode

### PR DESCRIPTION
**Pull request by martinpitt**
The rhel-7 and rhel-7-5 images are almost identical, except for the
preinstalled cockpit distro packages. This is rather expensive to
maintain and does not generalize well, so use a different approach:

 - Introduce "$image-distropkg" test names, which run on $image.

 - The only new thing for the -distropkg tests is an appropriate
   .install script; it does not need a .bootstrap or .setup script as
   this is not really a separate image, just a separate install overlay.

 - The new "rhel-7-5-distropkg" test now takes the role of the previous
   "rhel-7-5" image, i. e. run with the distribution's "cockpit"
   package. The "rhel-7-5" test now takes the role of the old "rhel-7"
   test, i. e. running with all cockpit packages built from master.
   This gets reflected in their .install scripts, where rhel-7-5.install
   now removes the preinstalled cockpit packages.

Drop the now obsolete rhel-7 image.

This approach also makes it easy to test other operating systems in
"distribution cockpit package" mode in the future.

 - [x] declare the new test name (PR #9673)

### CODE REVIEW

**Comment by martinpitt** [comment]
This can be demonstrated like this:

    TEST_OS=rhel-7-5-distropkg  bots/image-prepare -sv
    TEST_OS=rhel-7-5 bots/image-prepare -sv

This produces two install overlays in test/images, which use the same rhel-7-5 underlay. `test/vm-run rhel-7-5` will then show that all cockpit packages are version 172.x (`rpm -qa | grep cockpit`), while `test/vm-run rhel-7-5-distropkg` shows that cockpit{,-ws,-bridge,-system} are version 154, while the rest is 172.x.

**Comment by stefwalter** [comment]
Why are these images almost identical? I thought that the rhel-7 image would be targetting RHEL 7.6 delivery?

**Comment by martinpitt** [comment]
@stefwalter: So far the purpose of rhel-7 vs. rhel-7-5 was really just "all cockpit packages from master" vs. "preinstalled cockpit packages from 7.5 Base". We have a rhel-7-6 image for 7.6. It's confusing indeed, and this PR is also aiming at simplifying and clarifying this.

**Comment by stefwalter** [comment]
The only reason we preinstalled cockpit on the rhel-7-5 (and now rhel-7-6) images was that it was how those systems were delivered. Once RHEL 7.6 is delivered we have no opportunity to update base Cockpit packages in RHEL 7.6.z Extras releases.

So I guess another question: Why not delete the rhel-7-5 image without replacement, if we're no longer going to deliver on any further RHEL 7.5.z releases?

**Comment by martinpitt** [comment]
> The only reason we preinstalled cockpit on the rhel-7-5 (and now rhel-7-6) images was that it was how those systems were delivered.

I think what you mean is this: The rhel-7-5 (so far) / -distropkg (new name) test's main purpose is to test Cockpit JS code from master against an older bridge/ws from that RHEL release, to make sure we don't break ABI. This reflects the version difference between base and extras packages downstream, and we need to ensure that they work together.

> Once RHEL 7.6 is delivered we have no opportunity to update base Cockpit packages in RHEL 7.6.z Extras releases.

Correct. We can still deliver patches though, and then need a way to install built cockpit RPMs from a branch onto that image. This is what we previously did with the rhel-7 test on e. g. the rhel-7.5 branch. But running the rhel-7 (old name) / rhel-7-5 test (new name here) is useful for master as well, as we don't deliberately want to break buildability and functionality of cockpit-bridge on these stable RHELs; this would only lead to difficulties for the next 7.y release, where we usually rebase.

> Why not delete the rhel-7-5 image without replacement, if we're no longer going to deliver on any further RHEL 7.5.z releases?

We will do that once 7.6 gets released. We already did the same for the rhel-7-4 image, which got dropped once 7.5 gets released. But there is always an overlap (like right now) where we support one y and already want to test on y+1, so having just a single "rhel-7" image is not enough.

**Comment by stefwalter** [comment]
Bikeshed fest names: preinstall or partial

**Comment by martinpitt** [comment]
Fixed image-customize and tests-policy to use the correct image name.

**Comment by martinpitt** [comment]
[rhel-7-5 check-docker-storage failure](https://fedorapeople.org/groups/cockpit/logs/pull-9672-20180719-044747-ccd719a3-verify-rhel-7-5/log.html#201) is sticky, taking a look.  I see the error - rhel-7 and rhel-7-5 were built slightly differently (virt-builder upgrade from 7.4 vs. virt-install), and `rootfs_not_in_volume_group_images` *only* has rhel-7, not rhel-7-5. I shouldn't have renamed that. Fix pushed.

**Comment by martinpitt** [comment]
All green except for the expected rhel-7 failure. Yay `images--` :)

**Pull request merged**
