### PR TITLE
kubernetes: Display blank slate and blank pane

### PR DESCRIPTION
**Pull request by stefwalter**
Add blank slate to the services in dashboard
    
This shows a reason why no services are listed. 

Display a full screen curtain before connected
    
We display a full screen curtain before connected. The screen displays a spinner while connecting, and reconnection options if failed to connect.
    
The screen waits for 1 second to show, so we don't have too much flicker.

### CODE REVIEW

**Comment by stefwalter** [comment]
@andreasn @dperpeet This depends on the patternfly update

**Comment by stefwalter** [comment]
Depends on #2406

**Comment by stefwalter** [comment]
Blank slate screen when we can't connect. We don't yet have support for configuring kubernetes, so any further "help" or "magic" in this screen needs to wait until later.

screenshot from 2015-06-08 16-14-25

**Comment by stefwalter** [comment]
Pane shown when no services are present:

screenshot from 2015-06-08 16-12-24

**Comment by stefwalter** [comment]
Pane shown when access is denied. The ugly message comes from kubernetes. There's not much we can do about it's verbosity. We can't hide it because it shows useful information.

screenshot from 2015-06-08 16-17-22

**Comment by stefwalter** [comment]
Found bug, where there's a race in displaying the services blank slate.

**Comment by stefwalter** [comment]
Fixed bug with services blank slate.

**Comment by stefwalter** [comment]
This is the fix that @jeffvance has been waiting for :)

**Comment by mvollmer** [comment]
Needs a rebase.

**Comment by stefwalter** [comment]
Rebased.

**Comment by stefwalter** [comment]
@sub-mod Could you take a look at this? It should be merged before we do any work on endpoints, since some related code in the client changes.

**Pull request closed without merging**
