### PR TITLE
networkmanager: More precise slave detection

### PR DESCRIPTION
**Pull request by mvollmer**
Only look at the main connection for a interface when determining
whether it is a slave.

### CODE REVIEW

**Comment by mvollmer** [comment]
This needs a test.

**Comment by mvollmer** [comment]
Test added, but needs debugging.

**Comment by mvollmer** [comment]
Depends on #5687 now

**Comment by dperpeet** [comment]
closed accidentally in https://github.com/cockpit-project/cockpit/commit/8970dc140c7b3727872c6cb6ba501106019321c1

**Pull request closed without merging**
