### PR TITLE
No more bootstrap-select

### PR DESCRIPTION
**Pull request by stefwalter**
Removes the last remaining uses of bootstrap-select. We keep using the styling, just not the implementation, as it conflicts with several goals:

 * Content-Security-Policy
 * Templating of components, including React

### CODE REVIEW

**Comment by dperpeet** [comment]
time tests failing

**Comment by stefwalter** [comment]
Fixed test failures in check-system-info and check-multi-machine

**Comment by petervo** [comment]
Multimachine key also needs fixing.

**Comment by dperpeet** [comment]
I think this could be a bit clearer: We're just getting rid of the bootstrap-select js, not the CSS code (since that's still in PatternFly).

**Pull request closed without merging**
