### PR TITLE
bots: Run various tasks in verbose mode by default

### PR DESCRIPTION
**Pull request by stefwalter**
This means more nice info in the logs.

 - [ ] po-refresh

### CODE REVIEW

**Comment by stefwalter** [comment]
> Do you have a concrete case where verbose logs would have been useful? E. g. we now already run image-prepare in verbose mode (commit cb54acb) which was one thing where non-verbosity was annoying.

Non-verbosity is annoying during learn-data, or image-refresh tasks. In general the size of logs are dominated by tests by far. Other stuff should happen rarely enough to not make a dent.

**Comment by martinpitt** [comment]
Triggering one task to be 100% sure this works.

**Comment by cockpituous** [comment]
po-refresh  done: https://github.com/cockpituous/cockpit/commits/po-refresh-20180705-080000

**Comment by cockpituous** [comment]
po-refresh  done: https://github.com/cockpituous/cockpit/commits/po-refresh-20180705-080101

**Comment by cockpituous** [comment]
po-refresh  done: https://github.com/cockpituous/cockpit/commits/po-refresh-20180705-080303

**Pull request merged**
