### PR TITLE
Packagekit list to PF4 table component

### PR DESCRIPTION
**Pull request by KKoukiou**
- [x] fix mobile mode

### CODE REVIEW

**Comment by KKoukiou** [comment]
@garrett when you have time can you take a look on this?

**Comment by garrett** [comment]
It looks quite good!

I've noticed a few minor things...

Screenshot_2020-07-21 Software Updates - admin debian

Zoom ×4 (since it's really not obvious at 1:1):
Screenshot_2020-07-21 Software Updates - admin debian-zoom×4

1. Alignment of ˅ icon is not quite right
2. There's a bottom-border under the ˅ icon when it's expanded
3. Changelog has odd spacing

However, 1 & 2 are most likely covered by PR #14358 (PF4 version bump) and 3 is a minor thing that's most likely outside of the scope of this PR.

Once #14358 is in master and also in this PR, I'd like to look again to make sure the first two are solved.

**Comment by garrett** [comment]
Oh yeah, mobile... I should also fix that. :wink:

**Comment by garrett** [comment]
OK, I merged in the PF4 upgrade branch locally and rebuilt it into a VM for testing. 

The focus ring in both WebKit and Blink is quite odd. Here's Blink (Chromium):

Screenshot from 2020-07-21 18-00-17

Firefox doesn't show a focus ring when simply clicked; it shows a focus ring when tabbed to (and then also when clicked).

But all browsers do show a ring that invades the text area and they all have a caret that has too much padding on the left as well. Perhaps this is a PF4 problem? :shrug:

**Comment by martinpitt** [comment]
Lots of test failures and still being worked on, so moving to Draft.

**Comment by KKoukiou** [comment]
Just rebased and reposted to check the test status since all these are expired.

**Comment by KKoukiou** [comment]
@martinpitt @marusak any of you can review? Design wise there are no regressions I believe, plus now the tables are keyboard accessible.

**Comment by KKoukiou** [comment]
> OK, I merged in the PF4 upgrade branch locally and rebuilt it into a VM for testing.
> 
> The focus ring in both WebKit and Blink is quite odd. Here's Blink (Chromium):
> 
> Screenshot from 2020-07-21 18-00-17
> 
> Firefox doesn't show a focus ring when simply clicked; it shows a focus ring when tabbed to (and then also when clicked).
> 
> But all browsers do show a ring that invades the text area and they all have a caret that has too much padding on the left as well. Perhaps this is a PF4 problem? shrug

The focus ring does not overlap any more. The design of it (how it shows in chromium) is not ours, it's coming directly from PF.

**Review by marusak — DISMISSED** [review]
code-wise looks good, thanks!
Design seem the same (to me, but I think we don't regress compared to any other place where we would use this component).
I would love to see this page also converted to the `<Page>` thingy with grey background an white cards, but that is surely out of scope for this PR, just saying :)
Retried tests as some were not the happiest to compare.

**Review by martinpitt — APPROVED** [review]
This looks really nice, thanks! It's good to have these tables be less of a snowflake.

One thing that caught my eye is that on narrow screen widths, the update history table is now too hesitant to flow to two or three columns:

image

But that's minor, and mobile mode/keyboard nav work well now. :+1:

**Comment by KKoukiou** [comment]
> This looks really nice, thanks! It's good to have these tables be less of a snowflake.
> 
> One thing that caught my eye is that on narrow screen widths, the update history table is now too hesitant to flow to two or three columns:
> 
> image
> 
> But that's minor, and mobile mode/keyboard nav work well now. +1

Good catch, it's really like that in mid sized screens, for even smaller it works again because it wraps. I will hapilly post a follow up and fix it.

**Pull request merged**
