### PR TITLE
test: Fix call to download_dir

### PR DESCRIPTION
**Pull request by dperpeet**
Also properly check results without resorting to exception handling.

Using exceptions for this is just bad design.

@jscotka This enabled the download of the full avocado results directory. Screenshots aren't generated in every case, but this needs to happen in a different place.

### CODE REVIEW

**Comment by dperpeet** [comment]
This will be too verbose on regular tests that fail, since they don't have the avocado_results directory.

**Comment by dperpeet** [comment]
@stefwalter  Note that I changed the behavior of quiet-mode command.
Is this ok? Or should we just live with this command for every failed test?

**Comment by stefwalter** [comment]
What does the output look like now? We shouldn't complain about avocado output on non-avocado tests.

**Comment by dperpeet** [comment]
With the changed `quiet=True` behavior of execute, non avocado tests are silent regarding avocado.

If I don't patch it and use the same test to see if the remote directory exists, I get something like
```
Journal database copied to TestLogin-testRaw-10.111.117.222-FAIL.journal
Journal extracted to TestLogin-testRaw-10.111.117.222-FAIL.log
+ if test -d '/root/avocado_results'; then echo exists; fi
```
for all non-avocado test failures.

**Pull request closed without merging**
