### PR TITLE
Image refresh for fedora-30 [no-test]

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-30
 * [x] image-refresh fedora-30

### CODE REVIEW

**Comment by marusak** [comment]
[some](https://209.132.184.41:8493/logs/pull-11738-20190504-031919-e1835c75-verify-fedora-30/log.html) [flakes](https://209.132.184.41:8493/logs/pull-11738-20190504-031919-e1835c75-cockpit-project-cockpit-podman-cockpit-fedora-30/log), running again to compare

**Comment by marusak** [comment]
[podman fails](https://209.132.184.41:8493/logs/pull-11738-20190504-031919-e1835c75-cockpit-project-cockpit-podman-cockpit-fedora-30/log), needs to be looked at

**Comment by marusak** [comment]
And also new [selinux violation](https://209.132.184.41:8493/logs/pull-11738-20190504-031919-e1835c75-verify-fedora-30/log.html#87) which we have for rhel-8-1 in #11724, but needs to added for F30 as well. Also new BZ needs to opened for it, as this seem like a regression, since it was [reported for F28](https://bugzilla.redhat.com/show_bug.cgi?id=1553759) some time ago and fixed in there.

**Comment by KKoukiou** [comment]
> [podman fails](https://209.132.184.41:8493/logs/pull-11738-20190504-031919-e1835c75-cockpit-project-cockpit-podman-cockpit-fedora-30/log), needs to be looked at, there is some [coredump](https://209.132.184.41:8493/logs/pull-11738-20190505-045959-df9b92f2-cockpit-project-cockpit-podman-cockpit-fedora-30/TestApplication-testDownloadImage-fedora-30-127.0.0.2-2501-FAIL.log) from podman

Sent fix, see this PR for details.

**Comment by martinpitt** [comment]
Dropping no-test to also let weldr and friends run.

**Pull request merged**
