### PR TITLE
lib/table: Align table form style to PF & ct-form-layout

### PR DESCRIPTION
**Pull request by garrett**

### CODE REVIEW

**Comment by garrett** [comment]
## Before

Screenshot_2019-03-13 Sunny(1)

## After

Screenshot_2019-03-13 Sunny

**Comment by andreasn** [comment]
What is the problem you're solving with this solution?

**Comment by garrett** [comment]
This doesn't alter the style; it just makes the `th`s use the same style as the first `td` would otherwise use. It also fixes the vertical alignment as a result.

As we're not using `table-ct` in many places anymore, we may also want to consider changing the style to match `ct-form-layout` and/or simply porting these lists to `ct-form-layout`.

**Comment by garrett** [comment]
> What is the problem you're solving with this solution?

Mentioned in previous comment and shown in screenshots.

But simply: Table headers should use `th`, not `td`. This table uses `th` as it should, but it is not styled properly. Alignment is off too. This fixes that.

**Comment by garrett** [comment]
I'm happy to change the style to match `ct-form-layout too`, for the sake of consistency, and roll that into this PR if you'd like.

**Comment by andreasn** [comment]
> but it is not styled properly. Alignment is off too
Ah, I see. Thanks!

Fixing the style as well sounds good to me!

**Comment by garrett** [comment]
I'll fix in in this PR. It's simple enough.

**Comment by martinpitt** [comment]
Thanks @garrett ! Can you please add a Closes # so that we can land this?

**Comment by andreasn** [comment]
This might have broken the networkmanager page actually, will need to verify

**Comment by andreasn** [comment]
Network Interface before:
Screenshot from 2019-03-13 17-24-30

Network Interface after:
Screenshot from 2019-03-13 17-31-44

**Comment by andreasn** [comment]
And Services:
Screenshot from 2019-03-13 17-32-09

**Comment by andreasn** [comment]
I like that, because it makes sure we're more consistent. I agree that it's less obvious to us that it's doing the wrong thing, but that's a problem for us, not the people using the product.
I'm happy to make fixes for a couple of the places using TDs where it should be using TH across the pages as a followup to this PR.

**Comment by garrett** [comment]
It's even better if we port them to ct-form-layout (probably in most or all cases), but doing the `<th>` and `<label>` fixes are still good otherwise (and are possibly easier ports).

I'll add the change in style to this PR and squash it all down.

**Pull request merged**
