### PR TITLE
Image refresh for continuous-atomic

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for continuous-atomic in process on cockpit-10.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-continuous-atomic-2017-03-27/

### CODE REVIEW

**Comment by mvollmer** [comment]
```
rsync: write failed on "/project/cockpit/images/continuous-atomic-967a79005ea4f9c145a2682eba6c63565bf04873.qcow2.xz": No space left on device (28)
```

I'll prune fedorapeople.

**Comment by martinpitt** [comment]
bot: Image refresh for continuous-atomic

**Comment by cockpituous** [comment]
Image creation for continuous-atomic in process on cockpit-10.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-continuous-atomic-eaa0e8a32686c29dddfa26c3ea80492a08f6960b/

**Comment by cockpituous** [comment]
Image creation done.
Branch creation failed.

**Comment by martinpitt** [comment]
I force-pushed the new image link manually.

**Comment by martinpitt** [comment]
This error seems to be persistent:
```
error: Remote "local" not found
subprocess.CalledProcessError: Command '['rpm-ostree', 'rebase', 'local:centos-atomic-host/7/x86_64/devel/continuous']' returned non-zero exit status 1
```

**Comment by petervo** [comment]
The python based ```SimpleHTTPServer``` was having issues serving the ostree data and would die part way through the process. Switched to using a file based remove to get passed this. But now selinux is preventing any user from logging in. Need to debug that was well as verify the ostree tests still work.

**Comment by petervo** [comment]
This is a regression in ostree. https://github.com/ostreedev/ostree/pull/769. Closing for now as the fix should get in soon. I'll open the move to file:/// remotes when installing as a separate PR.

**Comment by cgwalters** [comment]
Will the bot try again?

**Pull request closed without merging**
