### PR TITLE
package.json: drop explicit Red Hat font depend

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
This should get pulled in by PatternFly, and lets us avoid npm requiring
git.

### CODE REVIEW

**Comment by martinpitt** [comment]
@TomasTomecek , @lachmanfrantisek : Any idea what happened here? SRPM builds are shown as failed, but the [COPR log](https://copr-be.cloud.fedoraproject.org/results/packit/cockpit-project-cockpit-17218/srpm-builds/03986199/builder-live.log.gz) looks successful to me, and the [directory](https://copr-be.cloud.fedoraproject.org/results/packit/cockpit-project-cockpit-17218/srpm-builds/03986199/) has the .src.rpm. Still fallout from this morning's outage? (But this smells more like an API break, not infra)

**Comment by allisonkarlitskaya** [comment]
For the record:


```
Only in @redhat/redhat-font/webfonts/RedHatDisplay/: RedHatDisplay-Black.eot
Only in @redhat/redhat-font/webfonts/RedHatDisplay/: RedHatDisplay-BlackItalic.eot
Binary files @redhat/redhat-font/webfonts/RedHatDisplay/RedHatDisplay-BlackItalic.woff and @patternfly/patternfly/assets/fonts/RedHatDisplay/RedHatDisplay-BlackItalic.woff differ
Binary files @redhat/redhat-font/webfonts/RedHatDisplay/RedHatDisplay-BlackItalic.woff2 and @patternfly/patternfly/assets/fonts/RedHatDisplay/RedHatDisplay-BlackItalic.woff2 differ
Binary files @redhat/redhat-font/webfonts/RedHatDisplay/RedHatDisplay-Black.woff and @patternfly/patternfly/assets/fonts/RedHatDisplay/RedHatDisplay-Black.woff differ
Binary files @redhat/redhat-font/webfonts/RedHatDisplay/RedHatDisplay-Black.woff2 and @patternfly/patternfly/assets/fonts/RedHatDisplay/RedHatDisplay-Black.woff2 differ
Only in @redhat/redhat-font/webfonts/RedHatDisplay/: RedHatDisplay-Bold.eot
Only in @redhat/redhat-font/webfonts/RedHatDisplay/: RedHatDisplay-BoldItalic.eot
Binary files @redhat/redhat-font/webfonts/RedHatDisplay/RedHatDisplay-BoldItalic.woff and @patternfly/patternfly/assets/fonts/RedHatDisplay/RedHatDisplay-BoldItalic.woff differ
Binary files @redhat/redhat-font/webfonts/RedHatDisplay/RedHatDisplay-BoldItalic.woff2 and @patternfly/patternfly/assets/fonts/RedHatDisplay/RedHatDisplay-BoldItalic.woff2 differ
Binary files @redhat/redhat-font/webfonts/RedHatDisplay/RedHatDisplay-Bold.woff and @patternfly/patternfly/assets/fonts/RedHatDisplay/RedHatDisplay-Bold.woff differ
Binary files @redhat/redhat-font/webfonts/RedHatDisplay/RedHatDisplay-Bold.woff2 and @patternfly/patternfly/assets/fonts/RedHatDisplay/RedHatDisplay-Bold.woff2 differ
Only in @redhat/redhat-font/webfonts/RedHatDisplay/: RedHatDisplay-Italic.eot
Binary files @redhat/redhat-font/webfonts/RedHatDisplay/RedHatDisplay-Italic.woff and @patternfly/patternfly/assets/fonts/RedHatDisplay/RedHatDisplay-Italic.woff differ
Binary files @redhat/redhat-font/webfonts/RedHatDisplay/RedHatDisplay-Italic.woff2 and @patternfly/patternfly/assets/fonts/RedHatDisplay/RedHatDisplay-Italic.woff2 differ
Only in @redhat/redhat-font/webfonts/RedHatDisplay/: RedHatDisplay-Medium.eot
Only in @redhat/redhat-font/webfonts/RedHatDisplay/: RedHatDisplay-MediumItalic.eot
Binary files @redhat/redhat-font/webfonts/RedHatDisplay/RedHatDisplay-MediumItalic.woff and @patternfly/patternfly/assets/fonts/RedHatDisplay/RedHatDisplay-MediumItalic.woff differ
Binary files @redhat/redhat-font/webfonts/RedHatDisplay/RedHatDisplay-MediumItalic.woff2 and @patternfly/patternfly/assets/fonts/RedHatDisplay/RedHatDisplay-MediumItalic.woff2 differ
Binary files @redhat/redhat-font/webfonts/RedHatDisplay/RedHatDisplay-Medium.woff and @patternfly/patternfly/assets/fonts/RedHatDisplay/RedHatDisplay-Medium.woff differ
Binary files @redhat/redhat-font/webfonts/RedHatDisplay/RedHatDisplay-Medium.woff2 and @patternfly/patternfly/assets/fonts/RedHatDisplay/RedHatDisplay-Medium.woff2 differ
Only in @redhat/redhat-font/webfonts/RedHatDisplay/: RedHatDisplay-Regular.eot
Binary files @redhat/redhat-font/webfonts/RedHatDisplay/RedHatDisplay-Regular.woff and @patternfly/patternfly/assets/fonts/RedHatDisplay/RedHatDisplay-Regular.woff differ
Binary files @redhat/redhat-font/webfonts/RedHatDisplay/RedHatDisplay-Regular.woff2 and @patternfly/patternfly/assets/fonts/RedHatDisplay/RedHatDisplay-Regular.woff2 differ
```

but apparently not enough to impact pixel tests.

**Review by martinpitt — APPROVED** [review]
Trivially approved, but this smells a bit wrong -- like, we didn't actually use the fonts from there, or the changes are subtle enough to pass the wiggle room in our pixel tests?

**Comment by lachmanfrantisek** [comment]
> Any idea what happened here? SRPM builds are shown as failed, but the [COPR log](https://copr-be.cloud.fedoraproject.org/results/packit/cockpit-project-cockpit-17218/srpm-builds/03986199/builder-live.log.gz) looks successful to me, and the [directory](https://copr-be.cloud.fedoraproject.org/results/packit/cockpit-project-cockpit-17218/srpm-builds/03986199/) has the .src.rpm. Still fallout from this morning's outage? (But this smells more like an API break, not infra)

This shouldn't be anyhow affected by the morning outage. There were some `50x` coming from Copr an hour or so ago. @mfocko, you were checking that. Can this be related?

**Comment by martinpitt** [comment]
@mfocko, @lachmanfrantisek : The retry worked, so -- nevermind, I guess? Thanks!

**Comment by TomasTomecek** [comment]
Yeah, Copr team was doing a release yesterday, I saw in their chat there was an outage.

**Pull request merged**
