### PR TITLE
metrics: Don't show duplicate events

### LINKED ISSUE #14809: Duplicated events
At 3:38 PM, "net i/o spike" is shown twice, and at 3:53 PM same for "disk i/o":

image

Reproducer: [/var/log/pcp/pmlogger](https://github.com/martinpitt/performance-graphs/files/5369629/pcp.zip)  data to reproduce this. Select "Saturday, October 10" as the day.

Copied from https://github.com/martinpitt/performance-graphs/issues/81

### PR DESCRIPTION
**Pull request by marusak**
If one type of event happens in one minute block more then once, show it
just once.

Fixes #14809

### CODE REVIEW

**Review by martinpitt — COMMENTED** [review]
Cheers! Any chance to turn your [reproducer](https://github.com/cockpit-project/cockpit/issues/14809#issuecomment-781138294) into a test?

**Comment by marusak** [comment]
> Any chance to turn your reproducer into a test?

I might try. When I recreated that zip into tar.gz the timestamps were broken and pcp refused to read it. I hope there are some options how to preserve timestamp. Or then teach `archivePrepare` to work with zips as well.
Also the host name is different, but I can just teach `archivePrepare` to set the right hostname.

**Comment by martinpitt** [comment]
Hmm, normally tar tries to restore original time stamps, you explicitly have to disable that with `--touch`. zip most likely can't do that. But anyway, if it's too complicated then nevermind.

**Comment by marusak** [comment]
Ok, so unzipping and tarring was not working for me. Maybe some of those millions of options that these tools provide would do the trick, but meh, zip will work, right?

**Comment by martinpitt** [comment]
That test indeed did [cause](https://logs.cockpit-project.org/logs/pull-15371-20210218-192910-c7405934-debian-stable/log.html#303) [failures](https://logs.cockpit-project.org/logs/pull-15371-20210218-192910-c7405934-ubuntu-2004/log.html#303) due to timestamps :/

**Comment by martinpitt** [comment]
Marking release-blocker for 238.1 next Monday, this is good polishing matter.

**Comment by marusak** [comment]
In ubuntu and debian `systemctl start pmlogger` hangs until it is eventually killed by timeout. It seems to be somewhat related to changing of hostname

**Comment by martinpitt** [comment]
@KKoukiou ^ FYI -- that sounds like the same issue that killed your /livetest?

**Comment by KKoukiou** [comment]
> @KKoukiou ^ FYI -- that sounds like the same issue that killed your /livetest?

Maybe :) I did not investigate that really.

**Comment by marusak** [comment]
Meh, I don't know. That archive just does not want to play along with ubuntu/debian.
I've check other archives but neither has any double events.

**Comment by martinpitt** [comment]
@marusak : How about just running the test on `TEST_OS_DEFAULT` then? should be sufficient. Not worth drilling down into this quirk..

**Review by martinpitt — APPROVED** [review]
Thanks! Weird that this requires zip, but :man_shrugging:

**Pull request merged**
