### PR TITLE
shell: drop privileged state

### PR DESCRIPTION
**Pull request by jelly**
In e45d47f0efe1f17 editing hosts was allowed for non admin privileges
which was the last user of this.state.privileged.

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Cheers!

**Comment by martinpitt** [comment]
Eww:

    pkg/systemd/overview-cards/configurationCard.jsx:240: warning: unterminated character constant

**Review by martinpitt — CHANGES_REQUESTED** [review]
Nevermind, the above was "just" a warning. This is the real issue:

   10:10  error  'superuser' is defined but never used  no-unused-vars

**Review by martinpitt — APPROVED** [review]

**Review by mvollmer — APPROVED** [review]
Yay!

**Pull request merged**
