### PR TITLE
debian: add systemd as a build dependency

### PR DESCRIPTION
**Pull request by larsu**
It seems like pbuilders don't have systemd installed anymore. Add it as a build dependency.

Also check for systemd during configure. I can't think of a reason why anyone would want to set the systemunitdir to /tmp, and hopefully making this check fatal will prevent issues like this in the future.

### CODE REVIEW

**Comment by larsu** [comment]
bot: Image refresh for debian-unstable

**Comment by cockpituous** [comment]
Image creation for debian-unstable in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-unstable-b6b336fd64f46f77980b6da6f9946dc768ad6c0e/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by larsu** [comment]
Revert the part that checks for systemd. We can't have that, because travis doesn't have a recent enough ubuntu with systemd.

**Comment by larsu** [comment]
bot: Image refresh for debian-unstable

**Comment by cockpituous** [comment]
Image creation for debian-unstable in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-unstable-5f1e3b511714424f580ea3fe25fb01555cffc503/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by larsu** [comment]
bot: Image refresh for debian-unstable

**Comment by cockpituous** [comment]
Image creation for debian-unstable in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-unstable-5f1e3b511714424f580ea3fe25fb01555cffc503/

**Comment by cockpituous** [comment]
Image creation for debian-unstable in process on cockpit-8.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-unstable-5f1e3b511714424f580ea3fe25fb01555cffc503/

**Comment by mvollmer** [comment]
```
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/p/procps/libprocps6_3.3.12-2_amd64.deb  Error reading from server. Remote end closed connection [IP: 5.153.231.35 80]
```

This happens all the time, and I think it is caused by using `httpredir.debian.org`.  What about using a known good mirror, like `http://ftp.uk.debian.org/debian`.

**Comment by cockpituous** [comment]
Image creation aborted

**Comment by cockpituous** [comment]
Image creation aborted

**Comment by larsu** [comment]
bot: Image refresh for debian-unstable

**Comment by cockpituous** [comment]
Image creation for debian-unstable in process on cockpit-8.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-unstable-e142ebd0b1a790cf903c0f88286eca583b940040/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-debian-unstable-e142ebd0b1a790cf903c0f88286eca583b940040

**Comment by stefwalter** [comment]
Seems like further debian fixes are needed. Unfortunately I don't have time right now to investigate each one.

**Comment by larsu** [comment]
> Seems like further debian fixes are needed. Unfortunately I don't have time right now to investigate each one.

Yeah, I'm looking into those.

**Comment by larsu** [comment]
Replaced by #4845.

**Pull request closed without merging**
