### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by martinpitt** [comment]
This seems to break image-prepare:

```
+ lintian /var/tmp/build-results/cockpit_168.x-1_amd64.changes
warning: the authors of lintian do not recommend running it with root privileges!
cannot parse tar output from src-orig-index: -rw-r--r-- user/user         6 2018-05-22 05:56:38.9773435   .tarball at /usr/share/lintian/checks/cruft.pm line 450.
internal error: cannot run cruft check on package source:cockpit/168.x-1
```

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-bz6cd.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9149-20180522-064040/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-54n8g.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9149-20180522-101919/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-9zk5x.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9149-20180522-101919/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9149-20180522-082323/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-testing-20180522-105050

**Comment by cockpituous** [comment]
Task aborted.

**Pull request merged**
