### PR TITLE
kubernetes: Initial integration test

### PR DESCRIPTION
**Pull request by stefwalter**
Not much tested. Ideally all following pull requests will add integration tests here.

Did this in the virtualized tests, since we want this to be usable on Atomic (ideally) and the new avocado based tests don't seem to be workabl ethere.

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #2262 and #2261

**Comment by stefwalter** [comment]
Rebased.

**Comment by stefwalter** [comment]
Blocking openshift connectivity.

**Comment by stefwalter** [comment]
Fixed up the test name.

**Comment by mvollmer** [comment]
Depends on #2268.

**Comment by sub-mod** [comment]
LGTM i think this needs to be rebased

**Comment by stefwalter** [comment]
This is also blocking on images being created by @dperpeet and @mvollmer. I think this is blocking most of the other stuff labels that say 'blocking' at the present time.

**Comment by mvollmer** [comment]
r7 image has been fixed manually, I'll install the f22 image and then we run this again without "--clean".

**Comment by mvollmer** [comment]
f22 images have been installed.

**Comment by mvollmer** [comment]
manual verification of r7 has passed.

**Comment by mvollmer** [comment]
As discussed on irc, check-kubernetes needs to be added to check-verify.

**Comment by stefwalter** [comment]
Rebased, added check-kubernetes to check-verify.

**Comment by stefwalter** [comment]
Removed docker pull from the test.

**Comment by mvollmer** [comment]
Tested manually.  (Let's hope I tested the right thing...)

**Pull request closed without merging**
