### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for fedora-testing in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-testing-2016-12-31/

### CODE REVIEW

**Comment by stefwalter** [comment]
@larskarlitski Could you look at the Atomic Scan failure here? It seems like our tests are conflicting with the next version of Atomic.

**Comment by larskarlitski** [comment]
Ya, atomic's D-Bus API broke. I've submitted pull request [#817](https://github.com/projectatomic/atomic/pull/817/files).

Should we wait for that to land (testing should get stuff faster, right) or skip the test for now?

**Comment by stefwalter** [comment]
If this is just fedora-testing that's broken, then go ahead and merge this now. The idea for the ```fedora-testing``` image is that we get early notice of breakages and can react to them. But other than that we don't do routine testing against it.

**Comment by larskarlitski** [comment]
You mean merge this image update without disabling the test for it?

**Comment by stefwalter** [comment]
> You mean merge this image update without disabling the test for it?

Yup. Since this is a 'canary' image, not used regularly we just let things fail, and see if they have been fixed the next time the image is used. At least that's the current way of doing it.

**Pull request closed without merging**
