### PR TITLE
Users page improvements

### PR DESCRIPTION
**Pull request by KKoukiou**
Split out from PR #18136

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Thanks! FTR, if this gets green, or at least green-ish (unrelated flakes), this should already help!

**Comment by martinpitt** [comment]
Meh @ [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18390-20230222-162253-cc8e08a9-arch/log.html#338) and [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18390-20230222-162253-cc8e08a9-debian-stable/log.html#333), which are the two examples of failures that these commits were supposed to fix. I'll think about that tomorrow morning.

**Comment by martinpitt** [comment]
[These two flakes](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18390-20230222-162253-cc8e08a9-ubuntu-2204/log.html#112-2) are an easy unrelated fix, I'll send one tomorrow.

**Comment by martinpitt** [comment]
Actually, now I believe that commit cc8e08a92 is redundant. I take it out, and do a test run without it. If this comes back, I'll add it back.

**Comment by martinpitt** [comment]
@KKoukiou : Should hopefully be all sorted out, see my [detailed analysis above](https://github.com/cockpit-project/cockpit/pull/18390#issuecomment-1440444481) if you are curious. /me feeds the test hamsters

**Comment by martinpitt** [comment]
So far, all TestAccounts ran 3x and passed. [Unrelated failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18390-20230223-070007-ab70ebd5-fedora-37/log.html#28-2), retrying.

@KKoukiou : I'll approve this, but as I messed around with this, please cross-review and land yourself, or ask me about clarifications/fixes. Thanks!

**Review by martinpitt — APPROVED** [review]

**Review by KKoukiou — COMMENTED** [review]
Thank you so much!

**Pull request merged**
