### PR TITLE
bots: Add RHEL 8 nightly image

### PR DESCRIPTION
**Pull request by martinpitt**
In rhel.setup:
 - Enable nightly RHEL 8 BaseOS and AppStream repositories for the 
   "rhel-8" image.
 - Invert the storaged vs. udisks2 condition, to avoid having to extend
   the affected OS list in the future.
 - Don't install some packages which are not yet available.

Refresh the image every week to stay on top of current development, but 
don't run this for every PR for the time being (i. e. similar to
continuous-atomic or fedora-testing).

As we don't yet have EPEL for RHEL-8 and thus no "mock" package, use the 
fedora-27 image to build packages for rhel-8 for the time being. This
should be reasonably close right now, as RHEL 8 currently auto-imports
from Fedora 28.

Add naughty overrides and SELinux filters (for bugs that affect many/all
tests) as appropriate.

 - [x] declare rhel-8 image (PR #8872)
 - [x] land PR #8878 to get along with missing e1000 driver
 - [x] land PR #8897 to work around d-bus disconnect on systemd daemon reload
 * [x] image-refresh rhel-8

Failing tests:
 - [x] `avc:  denied  { create } for  pid=1 comm="systemd" name="bpf"` ([downstream bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1559820))
 - [x] PackageKit is broken ([no working backend](https://bugzilla.redhat.com/show_bug.cgi?id=1559414))
 - [x] copy relevant test skips from rhel-7
 - [x] skip kubernetes/machines/ovirt tests
 - [x] udisks2 extensions are missing ([bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1559810)); skip tests
 - [x] `check-system-info TestSystemInfo.testTime`, `check-journal TestJournal.testBasic`: [timedated crash](https://bugzilla.redhat.com/show_bug.cgi?id=1559830), known issue #8880
 - [x] all networking tests fail on missing net interface ([rhel 8 missing e1000 driver](https://bugzilla.redhat.com/show_bug.cgi?id=1559791)) - fixed in PR #8878  
  - [x]  check-storage-used, check-accounts, check-realms, check-metrics: cracklib-dicts, libsss_sudo, and nmap-ncat missing, and in fact *all* recommended packages are ([bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1559839) and [other bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1559810))
 - [x] `test/verify/check-connection TestConnection.testBasic`: [systemd-coredump broken](https://bugzilla.redhat.com/show_bug.cgi?id=1559851) (known issue #8881)
 - [x] ipa-client-install fails ([bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1560452)): worked around
 - [x] kinit fails with sssd-kcm installed ([bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1559815)): worked around
 - [x] `test/verify/check-services TestServices.testApi`, `check-tuned`: systemd `Reload()` call broken ([downstream systemd bug](https://bugzilla.redhat.com/show_bug.cgi?id=1560549)); work around in PR #8897
 - [x] `test/verify/check-services TestServices.testBasic`: timer unit does not update automatically; does work on reload (missing signal?)
 - [x] `test/verify/check-session TestSession.testBasic`: session gets stuck forever in `closing` state; ([downstream systemd bug](https://bugzilla.redhat.com/show_bug.cgi?id=1560885), known issue #8903)

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-zd4gx.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8874-20180322-121414/

**Comment by martinpitt** [comment]
As a first milestone, I have the  image build working locally, and booting it works in general: I get a running cockpit, most pages work, and some verify tests also succeed. But tests will have to be adjusted heavily, at least due to the missing packages (libvirt, kubernetes, etc.) and due to PackageKit not working (will file a bug about it).

**Comment by cockpituous** [comment]
image-refresh rhel-8 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-20180322-122828

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-xvqcj.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8874-20180323-123636/

**Comment by cockpituous** [comment]
image-refresh rhel-8 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-20180323-125353

**Comment by martinpitt** [comment]
Rebuilding again to install libsss_sudo (another victim of https://bugzilla.redhat.com/show_bug.cgi?id=1559839)

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-zbcnv.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8874-20180326-085959/

**Comment by cockpituous** [comment]
image-refresh rhel-8 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-20180326-091313

**Comment by martinpitt** [comment]
Rebuilding again for missing netcat. https://bugzilla.redhat.com/show_bug.cgi?id=1559839 is really breaking a lot, but I think this should be the last missing one - the remaining four test case failures look unrelated to missing packages.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-tn84s.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8874-20180326-102121/

**Comment by cockpituous** [comment]
image-refresh rhel-8 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-20180326-103636

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-try-38rtl.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8874-20180326-104848/

**Comment by martinpitt** [comment]
New failures on bond/bridge networking tests, need to copy the recent new naughty overrides from #8893. Pushed.

**Comment by martinpitt** [comment]
OMG green! @larskarlitski or @mvollmer, can you please have a look?

**Comment by mvollmer** [comment]
\o/

**Pull request merged**
