### PR TITLE
pcp: Remove garbage bits produced by bug in pmda_linux

### PR DESCRIPTION
**Pull request by mvollmer**
The three disk.dev.*_bytes metrics are declared as PM_TYPE_U64 but
pmda_linux only stores into the "ul" part of the value.  Thus, the
high 32 bits of the "ull" part are garbage.

This mostly doesn't actually matter since by good luck the garbage
bits seem to be mostly constant and we only plot differences between
values.  Thus, the plots are mostly correct, with good luck.

PCP tools like pmval and pmlogger don't seem to run into trouble.
There is no garbage in the archives as far as I can see, for example.

See https://github.com/performancecopilot/pcp/pull/1137/files

### CODE REVIEW

**Comment by mvollmer** [comment]
We might not want to do this, actually. The damage seems to be very very small, and we need to have a plan for taking this out again once upstream is fixed, etc.

**Comment by marusak** [comment]
It propagates itself by some random spikes, right?
If it is really not that intrusive I think we can just wait for upstream. If those graphs show random values, then we should go with this.

**Comment by mvollmer** [comment]
> It propagates itself by some random spikes, right?
> If it is really not that intrusive I think we can just wait for upstream. If those graphs show random values, then we should go with this.

We pick up values from uninitialized memory in the upper 32 bits of the values, but by chance we always get the same values in those 32 bits. And since we plot the difference between samples, the plots still work as intended. Thus, we don't actually see any spikes.
However, anything at all might cause those 32 garbage bits to fluctuate. On the other hand, this is quite unlikely.

We have been living with those garbage bits for a long time already, this is the commit that broke it: https://github.com/performancecopilot/pcp/commit/24626d9f0982f24d0dfedb4f6e40eadba646bc09

The fix was just merged: https://github.com/performancecopilot/pcp/pull/1137

So, +1 from me for not installing this workaround.

**Comment by mvollmer** [comment]
(We could however have code that looks for unreasonable spikes and filter them out, like anything above 100 GiB/s.)

**Comment by mvollmer** [comment]
Let's close this then.

**Pull request closed without merging**
