### PR TITLE
session: Store krb credentials before fork()

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
We currently store forwarded Kerberos credentials in what is effectively
a "child setup" function in cockpit-session, after we fork() but before
we exec() cockpit-bridge.
    
Let's try to reduce the amount of stuff we do after fork():
    
 - after fork() but before exec() is an implementation detail of how
   processes are spawned on unix systems
  
 - POSIX specifies a very small number of functions (mostly syscalls)
   that are unconditionally safe to call at this point.  The number goes
   up if you're on Linux (which we always are), and if the original
   process is single-threaded (which it probably currently is), but none
   of these things are well-specified anywhere.  In any case, it's best
   practice to exec() ASAP after a fork().
    
 - we want to move to a new spawn helper in the future without support
   for callbacks, which would prevent "child setup" tasks like this one
    
Fortunately, sshd gives us some useful input here: it also supports
storing forwarded Kerberos credentials, and it manages to avoid doing
too much work between fork() and exec(), by temporarily changing its
uid/gid in order to store the credentials, before returning to root
permissions.  Let's copy this approach for cockpit.
    
A note: depending on exactly what backend is being used as the default
Kerberos credentials cache, it can be either the real or the effective
UID which is used to determine the "current user".  We must therefore
use setresuid() to change both, leaving only the saved UID as root.
    

  - [x] Land after 224 release

### CODE REVIEW

**Comment by allisonkarlitskaya** [comment]
Fair enough on the "gross": I'll remove that.  But even your comment is showing one of the dangers of fork() without exec(): you assume that once we call setuid(), we're completely safe, but it's not so: it could easily be the case that there are various things (like the content of /etc/shadow, or handles to other databases) hanging around in the process image.  You're never truly safe until you call exec().  This is why processes that change their UID can't be dumped or ptraced until they call exec().

I actually don't know if the krb stuff is safe, and indeed, that's something that should be reviewed, but if it is unsafe, then it already had no business being where it was (because of the above).  Of course, now that we have root hanging out in the saved UID field, this problem would become much more serious...

All this code is doing, though, is (a) determining the default ccache filename (eg: `/tmp/krb5cc_1000`) and then writing the credentials to that file.

**Comment by allisonkarlitskaya** [comment]
On the advantage side, we do this to facilitate switching over to a spawn() helper function, without need for a child setup callback, like the current code has.  That is motivated, in turn, by the fact that we need to spawn two subprocesses in the future (because of the shell check).

I've had cleaning this code up on my TODO list for a long time for other reasons, though: it's the classic problem of it being completely unspecified what you're allowed to do after `fork()` and before `exec()`.  POSIX specifies a very small list of functions (mostly syscalls, no stdio, no memory allocation), and glibc *seems* to allow more to work, but I've never been able to find a single place that this is actually documented and promised not to change in the future.

**Comment by martinpitt** [comment]
Right, I'm aware of the potential unsafe things between fork() and exec(), but at least this has been field-tested for a long time already. In terms of robustness this seems to move towards the wrong direction (i.e. towards the more privileged process). But right, it's not really doing any negotiation, just storing an existing credential. That's most often *not* a file BTW, but the user's kernel keyring or the caching daemon -- so I hope that's really attached to the processes' *current* UID, not related to its original UID, pid, or cgroup.

So again, the only thing which calms me down is "ssh does it", and if it's alright with you I'd like to postpone landing this until after Wednesday, so that we don't risk a late breakage of RHEL 8.3.

I leave it up to you to repush with a changed commit message, or just post it here for using it on squash&merge.

Thanks!

**Comment by allisonkarlitskaya** [comment]
> That's most often _not_ a file BTW, but the user's kernel keyring or the caching daemon -- so I hope that's really attached to the processes' _current_ UID, not related to its original UID, pid, or cgroup.

I've done a lot of debugging on this code, and as far as I can tell, it's really the file in `/tmp/krb5cc_{uid}`.  Is this different per distro?

**Comment by martinpitt** [comment]
@allisonkarlitskaya : Right, kcm is the default for Fedora, so that it can be shared with containers. On my system (I don't have kcm), it's the kernel keyring:

```
❱❱❱ klist
Ticket cache: KEYRING:persistent:1000:1000
```
But in that case it's also fine -- the keyring is per uid, not associated to pids or cgroups. (The latter is actually a bug/missing feature)

**Comment by martinpitt** [comment]
@allisonkarlitskaya: BTW, that's controlled by `default_ccache_name` in /etc/krb5.conf.

**Comment by allisonkarlitskaya** [comment]
Force push only rebased the branch and changed the commit message.

**Pull request merged**
