### PR TITLE
storage: Fix makedirs() invocation for Python 2

### PR DESCRIPTION
**Pull request by martinpitt**
Revert this part of commit a61672abcbe so that it continues to work on
RHEL 7, i. e. with Python 2.

### CODE REVIEW

**Comment by martinpitt** [comment]
This currently causes the [NFS tests to fail](https://209.132.184.41:8493/logs/pull-11978-20190603-133737-e1a6ffbb-verify-rhel-7-7/log.html) on all rhel/centos-7 images. Thus priority. Fortunately this didn't yet make it into the latest 195 release.

**Comment by martinpitt** [comment]
Huh, this slipped through: 
```
test/avocado/testlib_avocado/seleniumlib.py:292:5: E303 too many blank lines (2)
PASS: tools/test-static-code 1 pyflakes bots pkg tools
FAIL: tools/test-static-code 2 pyflakes test
```
Pushed a fix for this as well.

**Comment by Gundersanne** [comment]
FAIL: tools/test-static-code 2 pyflakes test

Pyflakes still fails it seems.

**Comment by martinpitt** [comment]
Ah, locally pyflakes is happy, but our old selenium's pyflakes does not yet recognize f-strings. Fixed.

**Pull request merged**
