### PR TITLE
Patches to 122 for RHEL 7.3.1

### PR DESCRIPTION
**Pull request by dperpeet**
These fix a number of bugs.

### CODE REVIEW

**Comment by stefwalter** [comment]
I'm using this as a test for non-master rebasing. The above debian-8 test is what i'm trying it out with.

**Comment by stefwalter** [comment]
As noted above, we can disregard the failure notice for ```verify/debian-8``` above. The rebase testing worked.

**Comment by stefwalter** [comment]
Removing bot tag so we can get verify machines interested ... now that the correct rebase stuff is in master.

**Comment by stefwalter** [comment]
Is that last commit 1e1dad2 cherry-picked to help @jscotka out later? The verify machines don't need that commit here.

**Comment by stefwalter** [comment]
Filed issue for debian-unstable systemd init failure: https://github.com/cockpit-project/cockpit/pull/5375

**Comment by dperpeet** [comment]
> Is that last commit 1e1dad2 cherry-picked to help @jscotka out later? The verify machines don't need that commit here.

will remove, picked that out before it was merged on master

**Comment by stefwalter** [comment]
Filed #5377 and #5375 for unrelated debian-unstable test failures.

**Comment by stefwalter** [comment]
Filed known issue for related Fedora 25 crash #5379

**Comment by stefwalter** [comment]
Need to think about how to prevent images that didn't exist at the time of the branch from being tested. Such as ubuntu-1604.

**Comment by dperpeet** [comment]
Each commit references at least one bug URL and has a list of master commits that it uses/combines

**Comment by dperpeet** [comment]
> I don't see how this bug could affect Cockpit 122: "kubernetes: container-terminal incompatible stock kubernetes" Other that that, this looks good to merge once the tests pass.

Cockpit 122 will be used for quite a while. I thought this fixes an issue users would be confronted with.
Also, the following commit `kubernetes: Only set websocket protocols if we actually have them` is based on changes from this one.

**Comment by stefwalter** [comment]
> Cockpit 122 will be used for quite a while. I thought this fixes an issue users would be confronted with.

The issue arose due to updating the container-terminal bower component. Until 123 this hadn't happened yet.

> Also, the following commit kubernetes: Only set websocket protocols if we actually have them is based on changes from this one.

Yup, makes sense to squash the minimum number of changes over into this one.

**Comment by dperpeet** [comment]
@stefwalter As discussed, we can also leave out the last two commit and discuss them in a follow-up. I assume the rest is less controversial?

**Comment by stefwalter** [comment]
Will follow up with last two patches in their own pull request.

**Comment by dperpeet** [comment]
The first six commits were merged, starting with https://github.com/cockpit-project/cockpit/commit/617a72b055743fcf2c286531c50fd7ef93e0f7aa

**Pull request closed without merging**
