### PR TITLE
Fix check-accounts flake

### PR DESCRIPTION
**Pull request by martinpitt**
Hunting down #13870 which I can't reproduce locally.

### CODE REVIEW

**Comment by martinpitt** [comment]
This effing session [just doesn't want to die](https://logs.cockpit-project.org/logs/pull-13871-20200408-101918-401e04e9-debian-testing/log):
```
loginctl terminate-session 16 
loginctl terminate-session 17 
> warning: transport closed: disconnected
Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket
# Result testExpire (__main__.TestAccounts) succeeded
# 1 TEST PASSED [13s on 3-cockpit-7]
ok 2 test/verify/check-accounts TestAccounts.testExpire [ND]
[...]
anton       3849  0.0  0.9  17880  9264 ?        Ss   10:26   0:00 /lib/systemd/systemd --user
anton       3850  0.0  0.3 103792  3484 ?        S    10:26   0:00 (sd-pam)
XXXX all logind users
 UID USER 
   0 root 
1002 admin
1003 anton

3 users listed.

XXXX all logind sessions
SESSION  UID USER  SEAT TTY        
     16 1003 anton      web console
     19    0 root                  
     20 1002 admin      web console

3 sessions listed.

> warning: userdel: user anton is currently used by process 3849
```
Re-trying with kill-session  now.

**Comment by martinpitt** [comment]
[Meh](https://logs.cockpit-project.org/logs/pull-13871-20200408-103227-bcb8ef47-debian-testing/log.html), so terminate-session does not help to terminate the user systemd instance apparently. That hammer is useful in general, but I suppose we need to apply a scalpel to this particular test.

**Comment by martinpitt** [comment]
[finally](https://logs.cockpit-project.org/logs/pull-13871-20200408-122848-da4cba1c-debian-testing/log.html) [clean](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-13871-20200408-122848-da4cba1c-fedora-testing/log.html)!

**Comment by martinpitt** [comment]
There's still a [different flake](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-13871-20200408-124901-e43535cb-ubuntu-2004/log.html#263), I didn't look at that one yet.

**Comment by martinpitt** [comment]
check-accounts succeeded everywhere, although there are a few other flakes -- the one I mentioned above, and a [page crash](https://logs.cockpit-project.org/logs/pull-13871-20200408-124901-e43535cb-debian-testing/log.html#260)

**Comment by martinpitt** [comment]
I spent about an hour trying to debug these other two issues, but I can't make sense of them yet. For the `null` name crash It seems as if the click action to the "Delete" button is executed twice -- the test doesn't even get to the confirmation dialog yet, so it's not clear at all why the user would be removed underneath it. The file watches on the Accounts page could certainly get confused by our backup/restore, but that happens in between tests when cockpit is not running. So, none the wiser yet..

**Comment by marusak** [comment]
> For the null name crash It seems as if the click action to the "Delete" button is executed twice 

This can be that we attach onClick listener twice. Something I was fighting with in the navigation, that if you init dialog, close it and open again, we set up the listener twice. And sometimes in tests we do this "try something -> if failed, try again" dance and if that would be the case here as well, we may actually open the dialog twice? (this is just random thinking)

**Pull request merged**
