### PR TITLE
test: Try to hobble along when "useradd -D" fails

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
This is to get a meaningful failure for https://github.com/cockpit-project/bots/pull/6426

**Comment by martinpitt** [comment]
TBH I'm not a fan of this -- the current failure should be meaningful/expressive enough for a naughty surely?

**Comment by mvollmer** [comment]
> TBH I'm not a fan of this -- the current failure should be meaningful/expressive enough for a naughty surely?

With this, we can actually see the failure when Cockpit itself runs "useradd -D". (Changes in /etc/defaults/useradd are not picked up during account creation.) When the test runs "useradd -D", it is just to figure out that HOME is /home so having it fail there and torpedo the whole test seems harsh.

**Comment by mvollmer** [comment]
> > TBH I'm not a fan of this -- the current failure should be meaningful/expressive enough for a naughty surely?
> 
> With this, we can actually see the failure when Cockpit itself runs "useradd -D". (Changes in /etc/defaults/useradd are not picked up during account creation.) When the test runs "useradd -D", it is just to figure out that HOME is /home so having it fail there and torpedo the whole test seems harsh.

Like this: https://cockpit-logs.us-east-1.linodeobjects.com/pull-20512-a747cb9b-20240527-104105-ubuntu-stable-others-bots%236426/log.html#146

But yeah, maybe a broken useradd is not worth this trouble.

**Comment by mvollmer** [comment]
A fix for useradd -D is on its way and we are blocking the image update for it.

**Pull request closed without merging**
