### PR TITLE
storaged: Rewrite sidebar with React

### PR DESCRIPTION
**Pull request by mvollmer**
- [x] https://github.com/cockpit-project/cockpit/pull/6110
- [x] https://github.com/cockpit-project/cockpit/pull/6172
- [x] update tests, probably

### CODE REVIEW

**Comment by mvollmer** [comment]
Needs a rebase.

**Comment by mvollmer** [comment]
Messed up the rebase.

**Comment by dperpeet** [comment]
I will post a fixup commit with some suggestions

**Comment by mvollmer** [comment]
> I would have preferred a solution that re-renders the component via props on change, that way the react component wouldn't have to listen to the client's changed events and would work completely without jquery.

Yes, good point.  I copied how the content-views work, but this is clearly not nice.  Let's get this right when the whole page is done via React.

**Comment by mvollmer** [comment]
> Proposed changes:

Thanks!  Now details.jsx really needs to be redone in React....

**Comment by cockpituous** [comment]
[storage: Rewrite sidebar in React](https://trello.com/c/Q2f7AD4i/479-storage-rewrite-sidebar-in-react)

**Comment by mvollmer** [comment]
fedora-26 actually passed after a few retries, but the process still exited with 1, probably we do our exit status accounting wrong.  I'll look at that.

**Comment by mvollmer** [comment]
> fedora-26 actually passed after a few retries, but the process still exited with 1, probably we do our exit status accounting wrong. I'll look at that.

No, it was this:

```
# ----------------------------------------------------------------------
# testConnect (check_kubernetes.TestConnection)
#
bash: /etc/kubernetes/start-kubernetes: No such file or directory
Job for kube-apiserver.service failed because the control process exited with error code.
See "systemctl  status kube-apiserver.service" and "journalctl  -xe" for details.
Ignoring known issue #6327
Traceback (most recent call last):
  File "check-kubernetes", line 58, in testConnect
    self.start_kubernetes()
  File "kubelib.py", line 53, in start_kubernetes
    self.machine.execute("systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet")
  File "testvm.py", line 414, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet' returned non-zero exit status 1
ok 9 testConnect (check_kubernetes.TestConnection) duration: 53s # SKIP Known issue #6327
Unexpected journal message 'http://localhost:8080/api: couldn't connect: Connection refused'
Unexpected journal message 'http://localhost:8080/api: couldn't connect: Connection refused'
Unexpected journal message 'https://localhost:8443/api: couldn't connect: Connection refused'
Unexpected journal message 'https://localhost:6443/api: couldn't connect: Connection refused'
Journal extracted to TestConnection-testConnect-10.111.126.165-FAIL.log
not ok 9 testConnect (check_kubernetes.TestConnection) duration: 53s
Traceback (most recent call last):
  File "/build/cockpit/test/common/testlib.py", line 537, in tearDown
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 693, in check_journal_messages
    raise Error(first)
Error: http://localhost:8080/api: couldn't connect: Connection refused
Wrote TestConnection-testConnect-FAIL.png
Journal extracted to TestConnection-testConnect-10.111.126.165-FAIL.log
```

Somehow this test both passed and failed.

**Comment by petervo** [comment]
@dperpeet did you finish reviewing this? Is it good to in?

**Comment by dperpeet** [comment]
The change is ok. Like I said I would have preferred a cleaner React solution that uses props instead of state more, but I can live with this.

**Pull request closed without merging**
