### PR TITLE
Fedora 24

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
Building and unit tests should work now.

**Comment by mvollmer** [comment]
New image has been uploaded.

**Comment by stefwalter** [comment]
Needs a rebase.

**Comment by mvollmer** [comment]
Fedora 24 test results are here: https://mvo.fedorapeople.org/logs/test-529c789a-verify-fedora-24/log.html

**Comment by mvollmer** [comment]
check-docker, check-multi-machine-key, and check-connection are fixed, waiting for image upload  check-kubernetes, check-openshift, and check-system-info might be real regressions.

**Comment by mvollmer** [comment]
check-networking hangs.

**Comment by mvollmer** [comment]
> check-networking hangs.

Fixed, but it still fails.

**Comment by mvollmer** [comment]
Current results: https://mvo.fedorapeople.org/logs/test-2a0b6628-verify-fedora-24/log.html

**Comment by stefwalter** [comment]
Two more commits for this branch 21ac5b2c621fbded1badbbd06379eefc75ec9750 618b0a6cd7f88c5e2bd6895b315d9d119bde1220

**Comment by mvollmer** [comment]
Current results: https://mvo.fedorapeople.org/logs/test-77ba4603-verify-fedora-24/log.html

**Comment by mvollmer** [comment]
There is a regression in NetworkManager that causes all kinds of confusion with Cockpit (and with itself): https://bugzilla.redhat.com/show_bug.cgi?id=1316488

I'll make known issues for that.

**Comment by mvollmer** [comment]
> I'll make known issues for that.

Hmm, now it passes....

**Pull request closed without merging**
