### PR TITLE
[rhel-8.4] Test backports and translations update

### PR DESCRIPTION
**Pull request by marusak**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1899681
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1934958

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Cheers!

**Comment by martinpitt** [comment]
Fun! the tests [spotted a regression](https://logs.cockpit-project.org/logs/pull-15503-20210311-081913-968d8375-rhel-8-4/log.html#140-2), and indeed the German translation now fuzzified the ["Not ready" string](https://github.com/cockpit-project/cockpit/pull/15503/files#diff-6686c8173bf4fa70e9c9755259206f2c5c4fa9fde6269d36e5262dcc09abcf25R5779), because we changed the capitalization.

**Comment by martinpitt** [comment]
I fixed the German and Portugese translations of "Not ready" in weblate for master and rhel-8. So if you re-import, they should get fixed. I'm not sure about the [Japanese error](https://logs.cockpit-project.org/logs/pull-15503-20210311-081913-968d8375-rhel-8-4/log.html#278-2), though

**Comment by marusak** [comment]
I am MMoron™- https://github.com/cockpit-project/bots/blob/master/po-refresh#L144

I was debugging this once before, then created ^ workaround. Of course, now I havn't used `po-refresh` just `make download-po` which havn't done this workaround. Well, there go two or so hours. So I'll just resync properly with `po-refresh` and should be fine

**Comment by martinpitt** [comment]
I'm quite sure [this is a flake](https://logs.cockpit-project.org/logs/pull-15503-20210311-140006-3e7f90fa-rhel-8-4-distropkg/log.html#291-2), retrying.

**Review by martinpitt — APPROVED** [review]
Dakujem!

**Pull request merged**
