### PR TITLE
ws: Allow hiding hostname from login page

### PR DESCRIPTION
**Pull request by petervo**

### CODE REVIEW

**Comment by stefwalter** [comment]
I hate to say this, but can we just have LoginTitle be a configuration field? And if not set it defaults to the hostname?

**Comment by petervo** [comment]
That was my first version of this, but then i thought that less arbitrary might be better. I can change it, do we want the cockpit_conf_bool stuff anyways, or should I drop it till we actually use it somewhere?

**Comment by stefwalter** [comment]
> That was my first version of this, but then i thought that less arbitrary might be better. I can change it, do we want the cockpit_conf_bool stuff anyways, or should I drop it till we actually use it somewhere?

Lets keep it, it's tested. It's hard to get right.

**Comment by stefwalter** [comment]
Added documentation when merging.

**Pull request closed without merging**
