### PR TITLE
package.json: Update @patternfly/react-console package dependency

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```package.json:    "@patternfly/react-console": "1.4.0",
pkg/machines/components/serialConsole.jsx:import { SerialConsole } from '@patternfly/react-console';
pkg/machines/machines.less:// For patternfly-react and @patternfly/react-console
pkg/machines/machines.less:@import "~@patternfly/react-console/dist/less/console.less";
```

**Comment by martinpitt** [comment]
I cannot reproduce this on my Fedora 28 system, but I get it in a cockpit/tests container.

**Comment by martinpitt** [comment]
I keep getting this in the container:
```
$ NODE_ENV=production SRCDIR=/build/cockpit BUILDDIR=. ./tools/webpack-make -d dist/machines/Makefile.deps ./webpack.config.js
Hash: 22b018da1d711d0f280a
Time: 27259ms
chunk    {0} machines/machines.min.js, machines/machines.css, machines/machines.min.js.map, machines/machines.css.map (machines/machines) 3.28 MB [rendered]
chunk    {1} machines/test-machines.min.js, machines/test-machines.css, machines/test-machines.min.js.map, machines/test-machines.css.map (machines/test-machines) 150 kB [rendered]
chunk    {2} machines/vnc.min.js, machines/vnc.min.js.map (machines/vnc) 344 kB [rendered]

ERROR in machines/machines.min.js from UglifyJs
SyntaxError: Unexpected token: keyword (function) [./~/@novnc/novnc/core/util/logging.js:20,0]
```
A quick google search sems to [indicate](https://github.com/pubkey/rxdb/issues/172) that this might  be related to wrong Babel settings - but why does that work on Fedora 28 (my host) and not Fedora 27 (the container).. Both have the same npm (5.6.0) and node (8.11.3) version, and pretty much all the rest (in particular, Uglify.js, babel, and webpack) are used from npm.

**Comment by martinpitt** [comment]
I tried building cockpit with a [newer uglify](https://gist.github.com/martinpitt/c6fa29e3adc2fe055d207d18630e1006), which works well by itself. But together with the react-console bump, it fails again, but now the error looks different:
```
chunk    {0} machines/machines.min.js, machines/machines.css, machines/machines.min.js.map, machines/machines.css.map (machines/machines) 3.28 MB [rendered]
chunk    {1} machines/test-machines.min.js, machines/test-machines.css, machines/test-machines.css.map (machines/test-machines) 150 kB [rendered]
chunk    {2} machines/vnc.min.js (machines/vnc) 344 kB [rendered]

ERROR in machines/machines.min.js from UglifyJs
Export statement may only appear at top level [machines/machines.min.js:87082,1]
```

Indeed in machines.min.js the `export function init_logging (level)` is not at the top level, due to the webpack nesting. But it *is* at the top-level in the original node_modules/@novnc/novnc/core/util/logging.js.

I noticed that this function is also being called from react-console:
```
node_modules/@patternfly/react-console/dist/esm/VncConsole/VncConsole.js:      NovncLog.init_logging(vncLogging);
node_modules/@patternfly/react-console/dist/js/VncConsole/VncConsole.js:      NovncLog.init_logging(vncLogging);
```
This is new in 1.4.0, and most certainly is the relevant change here. Before that, the function was only being called from within noVNC.

**Comment by mareklibra** [comment]
The change is actually needed by #8894, which includes upgrade of `patternfly/react-console` to 1.4.1 (recently) as well. The #8894 builds well (locally).

I think this PR can be closed.

**Comment by martinpitt** [comment]
@mareklibra : OK, good to know. Then I figure we don't need to bother with tracking this down further. But it seems to me that moving to react still needs quite some work? A lot of PRs went in already, but I've lost track.

**Comment by mareklibra** [comment]
@martinpitt , right, still something to do. I'll rebase the "top-level" react patch so it will be more clear what remains.
Unfortunately, I was busy with other projects last weeks so was not able to work on this.

**Pull request closed without merging**
