### PR TITLE
bots: Update CentOS Atomic cloud image download

### LINKED ISSUE #9971: Image refresh for continuous-atomic
Image refresh for continuous-atomic
 * [ ] FAIL: image-refresh continuous-atomic

### PR DESCRIPTION
**Pull request by martinpitt**
The file name dropped the "-7". Also move to https:// URL.

Fixes #9971 

 - [ ] image-refresh continuous-atomic

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-llzk8.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9973-20180904-071313/

**Comment by martinpitt** [comment]
cockpit-ostree still failed on the dreaded "Internal error in login process". Argh!

**Comment by martinpitt** [comment]
To fix this properly, centos needs to rebuild the container with current cockpit-dashboard (for cockpit-ssh) and libssh included, right?

**Comment by martinpitt** [comment]
Trying this again.

**Pull request closed without merging**
