### PR TITLE
machines: Show disks of virtual machines

### PR DESCRIPTION
**Pull request by dperpeet**
Suggested replacement for #6019

### CODE REVIEW

**Comment by mareklibra** [comment]
Changes: Commit messages and cockpit-components-listing.jsx where trinary operator is replaced by "if"

**Comment by dperpeet** [comment]
@garrett @andreasn 
This is what the listing pattern looks like without a caption:
screenshot from 2017-03-10 09-23-28

**Comment by dperpeet** [comment]
I reviewed the listing patterns in `React Patterns`, `Subscriptions` and `SELinux` - they looked good with the CSS changes.

**Comment by andreasn** [comment]
css looks good to me!

**Comment by dperpeet** [comment]
on ubuntu the new test failed with
```
# testDisks (check_machines.TestMachines)
#
Ignoring Resource Error: Operation canceled http://10.111.115.147:9090/cockpit/$5d170f08e379ddb5f8e5e53ba512315ebef9150c/machines/provider/index.js
WARNING  The guest's network configuration does not support PXE
chown: invalid user: 'qemu:qemu'
not ok 95 testDisks (check_machines.TestMachines) duration: 39s
Traceback (most recent call last):
  File "./verify/check-machines", line 135, in testDisks
    m.execute("qemu-img create -f raw {0} 128M && chown qemu:qemu {0}".format(self.vm1_img3))
  File "/build/cockpit/test/common/testvm.py", line 414, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'qemu-img create -f raw /var/lib/libvirt/images/subVmTest1_3.img 128M && chown qemu:qemu /var/lib/libvirt/images/subVmTest1_3.img' returned non-zero exit status 1
```

**Comment by dperpeet** [comment]
I also added @mareklibra's commit https://github.com/mareklibra/cockpit/commit/6ca2a7f3a6cbce4e469908d67811489ea67b24af to fix the integration test on debian based systems

**Comment by mareklibra** [comment]
on Debian:
```
Mar 10 06:09:07 unassigned-hostname libvirtd[1464]: libvirt version: 1.2.9, package: 9+deb8u3 (buildd 2016-07-01-18:17:10 x86-grnet-01)
Mar 10 06:09:07 unassigned-hostname libvirtd[1464]: internal error: QEMU / QMP failed: Could not access KVM kernel module: Permission denied
                                                    failed to initialize KVM: Permission denied
Mar 10 06:09:07 unassigned-hostname libvirtd[1464]: Failed to probe capabilities for /usr/bin/kvm: internal error: QEMU / QMP failed: Could not access KVM kernel module: Permission denied
                                                    failed to initialize KVM: Permission denied
Mar 10 06:09:07 unassigned-hostname libvirtd[1464]: internal error: QEMU / QMP failed: Could not access KVM kernel module: Permission denied
                                                    failed to initialize KVM: Permission denied
Mar 10 06:09:07 unassigned-hostname libvirtd[1464]: Failed to probe capabilities for /usr/bin/kvm: internal error: QEMU / QMP failed: Could not access KVM kernel module: Permission denied
                                                    failed to initialize KVM: Permission denied
```

**Comment by dperpeet** [comment]
replaced by #6072

**Pull request closed without merging**
