### PR TITLE
Add Debian 8 image and adapt tests

### PR DESCRIPTION
**Pull request by stefwalter**
* [x] Build images
* [x] Update control files
* [x] Add to testing cycle
* [x] Adapt tests

### CODE REVIEW

**Comment by stefwalter** [comment]
The question is whether we should disable automatic testing on 'debian-unstable' similar to 'fedora-testing'.

The only issue there would be related to tests like 'freeipa' which won't run on 'debian-8' but will run on 'debian-unstable'

**Comment by stefwalter** [comment]
Blocked on #5323 and #5322 and #5318

**Comment by stefwalter** [comment]
Need other handling of bad password during change:

```
Nov 09 00:55:19 unassigned-hostname cockpit-ws[1317]: cockpit-session: unable to change expired account or password: admin: Authentication token manipulation error
Nov 09 00:55:19 unassigned-hostname cockpit-ws[1317]: cockpit-session: Writing error pam-error
Nov 09 00:55:19 unassigned-hostname cockpit-ws[1317]: cockpit-session: Writing message Sorry, passwords do not match
Nov 09 00:55:19 unassigned-hostname cockpit-ws[1317]: cockpit-session: wrote result 20 to cockpit-ws
```

**Comment by stefwalter** [comment]
This is ready to go. If #5325 gets merged first then this will need a rebase ... lets see.

**Comment by stefwalter** [comment]
Updated known issues.

**Comment by stefwalter** [comment]
Adapted check-docker testRestart test.

**Comment by stefwalter** [comment]
Rebased.

**Comment by stefwalter** [comment]
More work needed now that Debian networking stuff is merged.

**Comment by stefwalter** [comment]
Skipped relevant networking tests.

**Comment by mvollmer** [comment]
This should fix `check-networking basic`: https://github.com/mvollmer/cockpit/commit/fdac3a01308cf48317e7faa755abb85bfa5cf660

**Comment by stefwalter** [comment]
> this should fix check-networking basic: mvollmer@fdac3a0

Thanks. Squashed that in.

**Comment by dperpeet** [comment]
needs rebase

**Comment by stefwalter** [comment]
Rebased.

**Pull request merged**
