### PR TITLE
test: Fix vm-create for debian-unstable

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
bot: Image refresh for debian-unstable

**Comment by cockpituous** [comment]
Image creation for debian-unstable in process on host32-rack06.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-unstable-086b7b34c7806088448a80bdfc56a5d75c56791a/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-debian-unstable-086b7b34c7806088448a80bdfc56a5d75c56791a

**Comment by stefwalter** [comment]
Triggering tests again.

**Pull request closed without merging**
