### PR TITLE
realmd: Convert Join dialog to ct-form-layout, use standard bootstrap form validation

### PR DESCRIPTION
**Pull request by martinpitt**
Also associate the labels to their inputs for accessibility. This
requires converting the class names to IDs, so adjust the selectors in
operation.js and the tests accordingly.

- [x] Fix width of domain input field
- [x] Adjust tests to work on rhel-7-6-distropkg

### CODE REVIEW

**Comment by martinpitt** [comment]
This is some preparatory work for issue #10063. Screenshot from master:

join-master

With this PR it looks like this:

join-pr

Obviously the input line length needs to be adjusted. @garrett, we do some nasty hack there with negative-width spinner and error indicator to make them appear inside the input line. form-layout does not know about this, and needs some help. When I add `size="47"`, it's almost right, but that is most probably resolution dependent and just a hack. I also tried to add `size="0"` or 1 to the spinner and indicator, that doesn't help either.

Or we move the spinner outside, and move the error text into the diagnostics section below, which might make more sense for a11y anyway?

**Comment by martinpitt** [comment]
I reworked this as per @andreasn's design guide. Initially it looks like this, at least on systems where `realm discover` does not show anything (i. e. no default domain):

no-default-domain

When typing a domain, it starts validating:

validating

and then it's either succeeding

valid

or invalid:

invalid

It still needs a tiny bit of CSS to add some spacing between the help block and the input line, but it's much better than before. :-)

**Comment by mvollmer** [comment]
Just for my records, we have issue #4541, which might be fixed by this.

**Comment by martinpitt** [comment]
Right, I didn't touch the error section at all. As this is nice and green, I'd like to look at that in a separate PR.

**Comment by martinpitt** [comment]
@andreasn : OK, I changed this to keep a non-breaking space in the error text instead of setting it to empty (which makes it disappear). Screenshot updated.

**Pull request merged**
