### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for fedora-testing in process on cockpit-11.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-testing-2017-03-03/

### CODE REVIEW

**Comment by martinpitt** [comment]
This one keeps failing:
```
not ok 78 testBasic (check_connection.TestConnection) duration: 138s
Traceback (most recent call last):
  File "./verify/check-connection", line 112, in testBasic
    self.assertNotEqual(cores, "")
AssertionError: '' == ''
```
We don't currently run "regular" PRs against fedora-testing, so I'm not sure if that is a regression or whether this just needs to be added to naughty (but we don't have an override of that test for any other OS).

**Comment by mvollmer** [comment]
I'll try to debug this a bit.

**Comment by mvollmer** [comment]
From the journal:

```
Mar 07 08:43:06 localhost.localdomain systemd-coredump[1839]: Core Dumping has been disabled for process 908 (crond).
Mar 07 08:43:06 localhost.localdomain systemd-coredump[1839]: Process 908 (crond) of user 0 dumped core.
```

**Comment by mvollmer** [comment]
This is https://bugzilla.redhat.com/show_bug.cgi?id=1341829, I think.

We use the proposed work around for fedora-25, but not for fedora-testing.  Hmm.

**Comment by mvollmer** [comment]
We check the crash dumper functionality because we want to get cores of the processes that crash during testing.  Thus, we should also use the workaround in fedora-testing.  I'll do that.

**Pull request closed without merging**
