### PR TITLE
bots: Bump admin password expiry on IPA image

### LINKED ISSUE #8086: check-realms tests started to fail due to expired admin password
Just about every integration test now fails like this:
```
# testIpa (check_realms.TestRealms)
#
> Failed to join domain: cockpit.lan: Running ipa-client-install failed
```

This is blocking every PR now, so marking priority. @petervo and I started to look into this.

Summary from @petervo:

 * ~Rebuilding the image did not help.~ - pitti: Rebuilding the *ipa* image does help.
 * He does not get the error on every run (I do)
 * Since the IPA image hasn't changed in months, this appears to be something external to the VM.

### PR DESCRIPTION
**Pull request by martinpitt**
The default password expiry of 90 days is impractial for our testing,
and we only refresh the ipa image every 120 days (and there is not much
reason to refresh it more often). Bump the expiry to 1000 days.

Fixes #8086

 * [x] image-refresh ipa

### CODE REVIEW

**Comment by martinpitt** [comment]
I tested this locally, and the image rebuild now shows this information:
```
+ ipa user-show --all admin
  dn: uid=admin,cn=users,cn=accounts,dc=cockpit,dc=lan
  [...]
  krblastpwdchange: 20171114094236Z
  krblastsuccessfulauth: 20171114094238Z
  krbpasswordexpiration: 20200810094236Z
```
That should be more than enough. Tests succeed locally with this image.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-vphzl.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8090-20171114-104040/

**Comment by cockpituous** [comment]
image-refresh ipa done: https://github.com/cockpituous/cockpit/commits/image-refresh-ipa-20171114-113535

**Comment by martinpitt** [comment]
Pushed the bot's image rebuild commit, and added a Closes #

**Pull request closed without merging**
