### PR TITLE
bots: Install socat on RHEL images

### PR DESCRIPTION
**Pull request by martinpitt**
This will be used in PR #11813, and it's a generally useful swiss army
knife for testing network related things.

 * [x] image-refresh rhel-7-6
 * [x] image-refresh rhel-7-7
 * [x] image-refresh rhel-8-0
 * [x] image-refresh rhel-8-1

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-ljz35.
Log: https://209.132.184.41:8493/logs/image-refresh-11816-20190513-154747/

**Comment by cockpituous** [comment]
image-refresh rhel-7-6 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-6-20190513-164141

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-qrj95.
Log: https://209.132.184.41:8493/logs/image-refresh-11816-20190513-165353/

**Comment by cockpituous** [comment]
image-refresh rhel-7-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-7-20190513-173232

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-6knb7.
Log: https://209.132.184.41:8493/logs/image-refresh-11816-20190513-173535/

**Comment by cockpituous** [comment]
image-refresh rhel-8-0 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-0-20190513-181212

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-sbkzh.
Log: https://209.132.184.41:8493/logs/image-refresh-11816-20190513-181313/

**Comment by cockpituous** [comment]
image-refresh rhel-8-1 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-1-20190513-184949

**Comment by martinpitt** [comment]
[This rhel-8-0 failure](https://209.132.184.41:8493/logs/pull-11816-20190513-213434-98c7b8e6-verify-rhel-8-0/log.html#109) may be persistent -- we don't normally run rhel-8-0 in integration tests, so this is probably just genuinely broken in master. May be same for [rhel-7-6](https://209.132.184.41:8493/logs/pull-11816-20190513-214444-98c7b8e6-verify-rhel-7-6/log.html), I'll check.

**Comment by martinpitt** [comment]
I can reproduce this [firewall flake](https://209.132.184.41:8493/logs/pull-11816-20190513-213434-98c7b8e6-verify-rhel-8-0/log.html#109) locally on master, so it's not a regression in this image refresh. I'm investigating this, but this doesn't need to block this update.

**Pull request merged**
