### PR TITLE
test: Prune the image store when refreshing images

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
The space we use for private images overflows quite frequently.

**Comment by martinpitt** [comment]
Will that somehow keep the current ID from master and other PRs too? A cockpituous automatic update must not remove every image but the newly produced one.

**Comment by mvollmer** [comment]
> Will that somehow keep the current ID from master and other PRs too?

Not specifically, It will keep the images referenced from the current commit, plus those that are less than two weeks old.

**Comment by martinpitt** [comment]
Hm, that seems bad, no? E. g. we don't update the ipa or stock-fedora-22 image very often, and even for the others two weeks is cutting it a bit close -- one round of missed/failed auto-update and  they might get removed underneath pending PRs?

**Comment by dperpeet** [comment]
it would have been nice to talk about this beforehand, the pruning code doesn't consider branches at all

**Comment by dperpeet** [comment]
I don't think this is a good idea. As we do with the logs, this should be a decision left to specific image stores.

**Comment by mvollmer** [comment]
> it would have been nice to talk about this beforehand, the pruning code doesn't consider branches at all

It didn't run yet via this PR, but I did a manual `vm-upload --prune`.

**Comment by mvollmer** [comment]
@dperpeet, what work is needed?

**Comment by dperpeet** [comment]
blocked on a decision

**Comment by dperpeet** [comment]
I'm afraid that with the current state of how pruning is decided, the client may not have information to prune correctly for the image store it's uploading to. The client may be creating a new image (that went missing?) for an older branch.

**Comment by mvollmer** [comment]
> Hm, that seems bad, no? E. g. we don't update the ipa or stock-fedora-22 image very often, and even for the others two weeks is cutting it a bit close -- one round of missed/failed auto-update and they might get removed underneath pending PRs?

Yes.

**Comment by mvollmer** [comment]
What about making `--prune` keep a maximum size?  It would delete the oldest images until the store is below that size.  The size would be configured in testinfra.py and separately for the private image store, or maybe via a file in the store directory.

**Comment by mvollmer** [comment]
Okay, we are not ready to switch this on, I guess.

**Comment by mvollmer** [comment]
Also, I just realized that cockpituous has not enough permissions to run the pruning code against the private store.

**Pull request closed without merging**
