### PR TITLE
test: bump reference-image to fedora-37

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Comment by martinpitt** [comment]
Test is still running, but at least [testBranding](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18217-20230123-081845-236b8413-fedora-37/TestConnection-test_branding-login-screen-delta.png) needs an updated screenshot, unsurprisingly. :grin:

**Comment by jelly** [comment]
RTL pixel test flaked.

**Review by martinpitt — APPROVED** [review]
Dankjewel!

**Comment by martinpitt** [comment]
Hmm, [that](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18217-20230123-140001-f6937a2d-fedora-37/log.html#86) is the RTL flake, retrying.

**Comment by jelly** [comment]
> Hmm, [that](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18217-20230123-140001-f6937a2d-fedora-37/log.html#86) is the RTL flake, retrying.

It flaked a few times and I retried already. So I don't think we can get this green.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
