### PR TITLE
test: enable dark theme pixel tests

### PR DESCRIPTION
**Pull request by jelly**
This introduces a new "layout" for the dark theme. The theme switching is implemented using the media emulation api of CDP and we always set it on set_layout. The reason the dark theme pixel tests are a layout, is that we don't want to implement a new (costly) scenario.

### CODE REVIEW

**Comment by jelly** [comment]
`ImportError: cannot import name 'Literal'` in TF, so we can't use fancy features :)

**Comment by jelly** [comment]
Firefox CDP does not seem to support `Emulation.setEmulatedMedia` which means we most likely we need to skip it.

**Comment by garrett** [comment]
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1549434, there's `emulateMedium` and `stopEmulatingMedium`. Perhaps it might work?

**Comment by jelly** [comment]
> According to https://bugzilla.mozilla.org/show_bug.cgi?id=1549434, there's `emulateMedium` and `stopEmulatingMedium`. Perhaps it might work?

Hmmm, I tried Page.setEmulatedMedia which is what [playright](https://github.com/microsoft/playwright/blob/cb1dcccbe6def06a6d55c5e28e7223daf68befdb/packages/playwright-core/src/server/firefox/ffPage.ts#L377) does, but calling that in our CDP code returns function not found...

Firefox documents absolutely nothing about their CDP API, so I'll leave this as is.

**Comment by jelly** [comment]
This was part of the main dark theme PR, can be closed.

**Pull request closed without merging**
