### PR TITLE
NetworkManager - first connection

### PR DESCRIPTION
**Pull request by tomasxiv**
It will create first connection if any connection does not exist.

### CODE REVIEW

**Comment by stefwalter** [comment]
Nice @tomasxiv. Could you describe what bug this fixes, and on what operating system? 

I'm running it  through the full suite of tests against the usual Linuxes ... to make sure it works.

**Comment by tomasxiv** [comment]
It is on Debian 8. The problem occured after click on IPv settings (PageNetworkIpSettings) when connections did not exist. 
1. It readed "null" from var "PageNetworkIpSettings.connection" -> therefore it did not be able to set "this.settings" in PageNetworkIpSettings.
2. Then it needs to get information about new connection after click on Apply, I've used the "create_ghost_connection_settings()" function and few needed parameter such as connection type, ethernet property, uuid, id.
obrazek

**Comment by tomasxiv** [comment]
Indeed, it does not solve other connection types, just Ethernet connection.

**Comment by stefwalter** [comment]
Aha, so it simulates an ethernet connection so things like the graphs work? 

CC @mvollmer This patch needs a little bit of cleanup before merging ... but it seems to make sense, no?

**Comment by mvollmer** [comment]
Thanks!  I have to admit I am confused by my own code, so I'll have to look at bit closer before I can say much about this...

**Comment by tomasxiv** [comment]
I thing the code calculates with connections, which it gets from NetworkManager (like command "nmcli con show"). When any connection for the concrete interface is missing the code cries. 

My fix creates first connection and then you can modify whatever without error. The first connection could be even inactive, therefore it does not simulate, it just create any connection for the selected interface.

I think, slave-connections are correct, because as far as I know there connections exist in NM, or you can create them by add button and it works, I think so. Another case is connection of wireless interfaces..

So, you are welcome, I corrected it for my needs, but I think this fix could be helpful also for you.

**Comment by mvollmer** [comment]
> So, you are welcome, I corrected it for my needs, but I think this fix could be helpful also for you.

Yes, I completely believe that there is a bug.  We just need to haggle about where to put the fix a bit. :-)

**Comment by mvollmer** [comment]
> It is on Debian 8. 

By default, Cockpit should not let you manage eth0 on Debian.  Did you do anything special to let Cockpit/NetworkManager manage it?

**Comment by mvollmer** [comment]
This bug is caused by a regression introduced by 1c2d0445dbcaba7c463003205cead8005acb825b.  It affects all operating systems, not just Debian 8.

This patch should fix it:

```
diff --git a/pkg/networkmanager/interfaces.js b/pkg/networkmanager/interfaces.js
index ecbac33..b045047 100644
--- a/pkg/networkmanager/interfaces.js
+++ b/pkg/networkmanager/interfaces.js
@@ -2364,7 +2364,7 @@ PageNetworkInterface.prototype = {
             function configure_ip_settings(topic) {
                 PageNetworkIpSettings.model = self.model;
                 PageNetworkIpSettings.connection = con;
-                PageNetworkIpSettings.settings = null;
+                PageNetworkIpSettings.settings = self.ghost_settings;
                 PageNetworkIpSettings.topic = topic;
                 PageNetworkIpSettings.done = reactivate_connection;
                 $('#network-ip-settings-dialog').modal('show');
```

However, the code is convoluted enough now that it's time to clean that up.  I'll come up with something better.

**Comment by mvollmer** [comment]
(And, yes, another instance of "there is only two kinds of code, covered by tests or soon broken.)

**Comment by tomasxiv** [comment]
Cockpit should not let you manage eth0 on Debia

**Comment by tomasxiv** [comment]
> By default, Cockpit should not let you manage eth0 on Debian. Did you do anything special to let Cockpit/NetworkManager manage it?
The server is not desktop and I've installed the NM with Cockpit, Network was configurable by network/interfaces, ifconfig .. there are 4 interfaces and wifi. I''ve just commented interfaces in network/interfeces to let Cockpit/NetworkManager manage it. I suppose, it is reason why no connection was created before and then the issue occured in Cockpit/NM.

**Comment by mvollmer** [comment]
> I''ve just commented interfaces in network/interfeces to let Cockpit/NetworkManager manage it. I suppose, it is reason why no connection was created before and then the issue occured in Cockpit/NM.

Yes, exactly.  Cockpit is supposed to deal just fine with such devices, but I unfortunately broke that a while ago.  The proposed fix is in #5511.  And I added a test which found another regression...

Are you able to test #5511?

**Comment by mvollmer** [comment]
To be continued in #5511...

@tomasxiv, thanks a lot for your efforts, this was a really good catch!

**Pull request closed without merging**
