### PR TITLE
shell: Implement minimal part of new switcher design

### PR DESCRIPTION
**Pull request by stefwalter**
Adopt the colors and layout concepts from the new switcher design.
This is about all we can get in for this release.

This also migrates parts of the shell CSS to Less.

### CODE REVIEW

**Comment by stefwalter** [comment]
New look.

screenshot from 2017-03-12 18-20-26

Small size

screenshot from 2017-03-12 18-20-18

Alternate color

screenshot from 2017-03-12 18-20-11

**Comment by dperpeet** [comment]
A login test is failing in a lot of places:
```
# testBasic (check_login.TestLogin)
#
> Authentication failed
> Authentication failed
Resource Error: Error downloading http://10.111.117.187:9090/cockpit/login - server replied: Permission denied http://10.111.117.187:9090/cockpit/login
Resource Error: Error downloading http://10.111.117.187:9090/cockpit/login - server replied: Permission denied http://10.111.117.187:9090/cockpit/login
Ignoring Resource Error: Operation canceled http://10.111.117.187:9090/page.css
Ignoring Resource Error: Operation canceled http://10.111.117.187:9090/table.css
Ignoring Resource Error: Operation canceled http://10.111.117.187:9090/table.css
Ignoring Resource Error: Operation canceled http://10.111.117.187:9090/page.css
Ignoring Resource Error: Operation canceled http://10.111.117.187:9090/cockpit/$734d5c16787614dabd7321616a181d9d235d0971/base1/fonts/patternfly.woff
Ignoring Resource Error: Operation canceled http://10.111.117.187:9090/cockpit/$734d5c16787614dabd7321616a181d9d235d0971/base1/fonts/fontawesome.woff?v=4.2.0
Ignoring Resource Error: Operation canceled http://10.111.117.187:9090/page.css
not ok 64 testBasic (check_login.TestLogin) duration: 31s
Traceback (most recent call last):
  File "./verify/check-login", line 93, in testBasic
    b.reload()
  File "/build/cockpit/test/common/testlib.py", line 122, in reload
    self.phantom.reload()
  File "/build/cockpit/test/common/testlib.py", line 729, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 755, in _invoke
    raise Error(res['error'])
Error: fail
```
Related?

**Comment by stefwalter** [comment]
> A login test is failing in a lot of places:

Good catch. Should be fixed now.

**Comment by dperpeet** [comment]
For reference, the feature page is: https://github.com/cockpit-project/cockpit/wiki/Feature:-Task-Switcher

**Comment by dperpeet** [comment]
I want to point out this is a huge win: the menu can now scroll!

**Comment by garrett** [comment]
For a first pass at porting the style over, it's looking good! :+1:

**Pull request merged**
