### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by KKoukiou** [comment]
The [testNetworkingPage error](https://209.132.184.41:8493/logs/pull-11654-20190423-125656-36969138-verify-debian-testing/log.html#226) is libvirt complaining about firewall getting stopped while libvirtd is still running. This was already discussed [here](https://bugzilla.redhat.com/show_bug.cgi?id=1348434) and won't be fixed. I suggest that we just ignore this error in this test since it's harmless.

**Comment by KKoukiou** [comment]
> The [testNetworkingPage error](https://209.132.184.41:8493/logs/pull-11654-20190423-125656-36969138-verify-debian-testing/log.html#226) is libvirt complaining about firewall getting stopped while libvirtd is still running. This was already discussed [here](https://bugzilla.redhat.com/show_bug.cgi?id=1348434) and won't be fixed. I suggest that we just ignore this error in this test since it's harmless.

Fixed here https://github.com/cockpit-project/cockpit/pull/11658 since it affect more PRs than this one.

**Comment by marusak** [comment]
Blocked by #11658

**Comment by martinpitt** [comment]
#11658 landed, retrying

**Pull request merged**
