### PR TITLE
storage: Listen on changed fs sizes

### PR DESCRIPTION
**Pull request by marusak**
This approach is copied from `pkg/storaged/fsys-panel.jsx` or `pkg/storaged/fsys-tab.jsx`.

### CODE REVIEW

**Comment by marusak** [comment]
As seen in https://github.com/cockpit-project/bots/pull/3488

**Comment by marusak** [comment]
`TypeError: 'str' object is not callable` how have I broke that?

**Comment by marusak** [comment]
All green, including `rhel-9-1@bots#3488` :tada:

**Review by martinpitt — APPROVED** [review]
Dakujem!

**Pull request merged**
