### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by martinpitt** [comment]
This image breaks kubernetes, needswork.

**Comment by marusak** [comment]
Image is missing, retriggering

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-qkfp4.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11304-20190311-121414/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-testing-20190311-124242

**Comment by martinpitt** [comment]
Collides with #11367

**Pull request closed without merging**
