### PR TITLE
Image refresh for fedora-atomic

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for fedora-atomic in process on host37-rack09.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-atomic-2016-04-05/

### CODE REVIEW

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by dperpeet** [comment]
bot: Image refresh for fedora-atomic

**Comment by cockpituous** [comment]
Image creation for fedora-atomic in process on host32-rack06.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-atomic-2d67d50b22c143f95b85fa8b035c51ea2583128c/

**Comment by cockpituous** [comment]
Image creation done.
Branch creation failed.

**Comment by mvollmer** [comment]
We get a new one tomorrow.

**Pull request closed without merging**
