### PR TITLE
branding: use generic opensuse branding

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by Gundersanne** [comment]
I just checked opensuse's `/etc/os-release` and it seems the ID field includes the variant. So ID is "opensuse-(leap|tumbleweed|..)" correct? In which case the generic one won't work. 

If all opensuses don't share one of these:
```
    $prefix/share/cockpit/branding/$ID-$VARIANT_ID
    $prefix/share/cockpit/branding/$ID
```
this will default to branding/default.


Sorry about that, my bad, really should've checked first if the ID field includes the variant before giving that advice. So we will need the separate directories: opensuse-tumbleweed, and opensuse-microos. I guess -leap not, is cockpit packaged on leap?

Because they don't share an $ID, https://github.com/Gundersanne/cockpit/commit/252c99c09891430b52d7561c7d40ceb56f21dfce  should be correct.

**Comment by lnussel** [comment]
No worries, I tried it. It works :smiley: cockpit also walks ID_LIKE and there's `opensuse`

**Comment by lnussel** [comment]
https://github.com/cockpit-project/cockpit/blob/4b158ac07771fda3ee4f0e92ee6195e5b4401f7e/src/ws/cockpitbranding.c#L75

**Review by Gundersanne — APPROVED** [review]
Well I learned something new today :D 

Thank you!

**Pull request merged**
