### PR TITLE
WIP: Permission lookups

### PR DESCRIPTION
**Pull request by petervo**
This is a companion PR to #1645. 

There is still work to do here and this commit will probably be squashed out of existence, but i figured I'd ask for a early review of what is there so far particularly the way i'm going about testing.

### CODE REVIEW

**Comment by stefwalter** [comment]
Looks really good to me.

**Comment by stefwalter** [comment]
What remains to be done on this pull request, besides, squashing, documenting, merging?

**Comment by stefwalter** [comment]
Oh, we need to separate out the UI changes.

**Comment by petervo** [comment]
I might be missing something but In testing this I've found that making CheckAuthorization calls without the AllowUserInteraction flag returns also return False, True for unprivileged users. with the flag I get False, False. Although according to the docs we aren't supposed to pass that unless the call is being made in response to a user action. For now this doesn't result in a blocked call although that could change with #1596.

**Comment by petervo** [comment]
Does pulling out all the UI changes mean leaving all the check_admin calls for a different PR. Or should I just replace them all with permission.allowed checks in this PR and leave the enabled/disabled state for another PR?

**Comment by stefwalter** [comment]
> Does pulling out all the UI changes mean leaving all the check_admin calls for a different PR. Or should I just replace them all with permission.allowed checks in this PR and leave the enabled/disabled state for another PR?

I would say the latter.

**Comment by petervo** [comment]
OK, i'm not sure how well that is going to work in practice, because of the async nature of the permission calls, allowed might not be at it's correct value at the time of the check. But it's ok for now i think.

**Comment by stefwalter** [comment]
> OK, i'm not sure how well that is going to work in practice, because of the async nature of the permission calls, allowed might not be at it's correct value at the time of the check. But it's ok for now i think.

Agreed.

**Comment by petervo** [comment]
Pushed some updates

Still need to remove ui code and replace all the check_admin calls.

**Comment by stefwalter** [comment]
Merged into #1645

**Pull request closed without merging**
