### PR TITLE
Revert removal of 'data' AMD loader

### PR DESCRIPTION
**Pull request by stefwalter**
It turns out that this was a backwards incompatibility issue.
We still keep the 'raw' loader defined, since this was included
in a release too.

### CODE REVIEW

**Comment by mvollmer** [comment]
But we could still use 'raw' in our own code, no?  Which is the recommended name?

**Comment by stefwalter** [comment]
> But we could still use 'raw' in our own code, no? Which is the recommended name?

Not if you expect that code to work on older (now stable) versions of Cockpit. Once things are bundled with webpack, then the 'raw' is resolved at build time, so it's not a problem. However with AMD modules, whether bundled or not, the 'data' vs. 'raw' was resolved at runtime.

**Comment by stefwalter** [comment]
> But we could still use 'raw' in our own code, no? Which is the recommended name?

Thus 'data!./xxxx.txt' is the recommended name for AMD modules, until migration to webpack, where they get switched to 'raw!./xxxx.txt'

**Comment by mvollmer** [comment]
>> But we could still use 'raw' in our own code, no? Which is the recommended name?

> Not if you expect that code to work on older (now stable) versions of Cockpit.

Ahh, thanks, that makes sense.

**Comment by stefwalter** [comment]
Removed priority temporarily so we can get test fixes in.

**Comment by stefwalter** [comment]
Priority since regression. Needs to go into next release.

**Pull request closed without merging**
