### PR TITLE
test: Sort PRs with equal priority by name

### PR DESCRIPTION
**Pull request by mvollmer**
To make things a little bit more stable and predictable.

### CODE REVIEW

**Comment by stefwalter** [comment]
Shouldn't this be by number? As in the more recent ones have a bit of priority? Or vs versa?

**Comment by mvollmer** [comment]
> Shouldn't this be by number? As in the more recent ones have a bit of priority? Or vs versa?

Yeah, by number would be better, altough it only makes a difference once we reach #10000... :)

**Comment by stefwalter** [comment]
Well, the pull request number is a number, not a string.

Also, isn't python sort stable? We get the pulls in the right order already:

https://developer.github.com/v3/pulls/#list-pull-requests

**Comment by stefwalter** [comment]
Python sorts are stable. So the code already does what we want, right? https://wiki.python.org/moin/HowTo/Sorting/

So I guess we just need to change the sort ```direction``` of the ```pulls``` request to be ```desc```

https://developer.github.com/v3/pulls/#list-pull-requests

**Comment by mvollmer** [comment]
> Also, isn't python sort stable? We get the pulls in the right order already:

You are right.  I must have gotten confused when checking whether things were already in the right order.  I thought they weren't, but they indeed are.

**Pull request closed without merging**
