### PR TITLE
Image refresh for rhel-8-0

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-0
 * [x] image-refresh rhel-8-0

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-10.
Log: https://209.132.184.41:8493/logs/image-refresh-12219-20190704-073535/

**Comment by cockpituous** [comment]
image-refresh rhel-8-0 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-0-20190704-075858

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://209.132.184.41:8493/logs/image-refresh-12219-20190704-073535/

**Comment by martinpitt** [comment]
I triggered the missing rhel-8-0-distropkg test. Fixed in PR #12226

**Comment by marusak** [comment]
[8-0-distro](https://209.132.184.41:8493/logs/pull-12219-20190704-080505-bc2c1b00-verify-rhel-8-0-distropkg/log.html#27) one failure. Retrying.

**Comment by martinpitt** [comment]
All different flakes, good enough.

**Pull request merged**
