### PR TITLE
Image refresh for fedora-29

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-29
 * [x] image-refresh fedora-29

### CODE REVIEW

**Comment by martinpitt** [comment]
This breaks a selenium test.

**Comment by martinpitt** [comment]
The issue is that `dbus.service` now got renamed to `dbus-daemon.service`. I don't just want to change it though, as this would break the tests when running them on RHEL 7. So how about we check for sshd.service instead?

**Comment by martinpitt** [comment]
@henrywang : All the [fedora-29 welder-tests](https://fedorapeople.org/groups/cockpit/logs/pull-11045-20190129-121414-e8d2bd92-weldr-welder-web-cockpit-fedora-29-chrome/log) fail with that new image. Do you see something obvious here?

**Comment by henrywang** [comment]
@martinpitt, all failed cases are about "create image". Normally there should have an "In Progress" list item after clicking "create image". In this case, there's no this item in 2 minutes. So the test reports timeout error.

**Comment by martinpitt** [comment]
@henrywang : Nevermind, was just a flake again.

**Pull request merged**
