### PR TITLE
test: Fully check filesystem types 

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
ubuntu-1604 actually has the same problem...

**Comment by mvollmer** [comment]
I'll add a test.

**Comment by mvollmer** [comment]
bot: Image refresh for ubuntu-1604

**Comment by cockpituous** [comment]
Image creation for ubuntu-1604 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-ubuntu-1604-b4a221869cb5f2844d4c0c1da37ab642b02bc2af/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-ubuntu-1604-b4a221869cb5f2844d4c0c1da37ab642b02bc2af

**Comment by stefwalter** [comment]
Unfortunately the added test fails on centos-7.

**Comment by mvollmer** [comment]
> Unfortunately the added test fails on centos-7.

And rhel-7.

**Comment by mvollmer** [comment]
bot: Image refresh for rhel-7

**Comment by mvollmer** [comment]
bot: Image refresh for centos-7

**Comment by cockpituous** [comment]
Image creation for centos-7 in process on cockpit-9.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-centos-7-fb2aa0072aa18776b2703e75d7f1c7779b019dbb/

**Comment by cockpituous** [comment]
Image creation for rhel-7 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-7-fb2aa0072aa18776b2703e75d7f1c7779b019dbb/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-centos-7-fb2aa0072aa18776b2703e75d7f1c7779b019dbb

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by mvollmer** [comment]
rhel-7 image has been uploaded manually.

**Comment by mvollmer** [comment]
There is no "ntfsprogs" package on centos-7 or rhel-7, but yum doesn't think that is an error...

**Pull request closed without merging**
