### PR TITLE
test: Add fedora-i386 image

### PR DESCRIPTION
**Pull request by martinpitt**
This is useful for running integration tests on a 32 bit platform.

 - [x] land PR #6196 to make the image known
 - [x] fix Y2K38 test failure in `check-journal TestJournal.testBasic`
 - [x] fix networkmanager to check for "Team" module on non-x86 arches (caught by check-networking-team)
 - [x] fix `test/verify/check-connection TestConnection.testTls` (handshake failure instead of "wrong version number")
- [x] fix `check-ostree` ("Command requires a --repo argument" and others)
 - [x] docker is not really a thing on !x86_64, disable the image setup part and skip `check-docker*`
 - [x] rebuild/reupload clean image (current one has broken docker images installed and was not built from latest setup scripts)
 - [x] rebuild Fedora 25 image with updated script

### CODE REVIEW

**Comment by martinpitt** [comment]
Awesome, tests passed! I'll trigger a clean image build now on the infra to make sure everything works there too, and then re-run the full set of tests.

**Comment by martinpitt** [comment]
bot: Image refresh for fedora-i386

**Comment by martinpitt** [comment]
Hmm, the bot does not like that yet; did I forget to add  something to test/common/testinfra.py? Building fresh image locally for the time being.

**Comment by martinpitt** [comment]
bot: Image refresh for fedora-i386

**Comment by dperpeet** [comment]
Looks great! Technically the fedora-25 setup script has changed... The changes *shouldn't* matter, but usually we'd build a new fedora-25 image just to make sure.

**Comment by dperpeet** [comment]
bot: Image refresh for fedora-25

**Comment by cockpituous** [comment]
Image creation for fedora-25 in process on cockpit-8.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-25-537c1ba517d494c3799fdf494fe571f5de0410a9/

**Comment by dperpeet** [comment]
> Hmm, the bot does not like that yet; did I forget to add something to test/common/testinfra.py? Building fresh image locally for the time being.

You need to add the bot label first.

**Comment by dperpeet** [comment]
let's use the new image just to make sure

**Comment by martinpitt** [comment]
> You need to add the bot label first.

I did, you can still see it from the history here. But even after half an hour I didn't get a response from cockpituous. But right, let's update fedora-25 alongside, thanks for triggering.

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-fedora-25-537c1ba517d494c3799fdf494fe571f5de0410a9

**Comment by petervo** [comment]
bot: Image refresh for fedora-i386

**Comment by petervo** [comment]
Looks like there is something wrong with building the new fedora-i386 on the bots.

**Comment by martinpitt** [comment]
All green now, so this should be good.

**Pull request closed without merging**
