### PR TITLE
WIP - Support "no discard" during format

### PR DESCRIPTION
**Pull request by mvollmer**
This is just a quick UI mockup for now, it doesn't do anything real.

### CODE REVIEW

**Comment by mvollmer** [comment]
screenshot from 2017-11-21 12-00-45

**Comment by andreasn** [comment]
It's usually recommended to keep checkboxes positive, so they are not backwards. [This book I stumbled upon has a longer explanation](https://books.google.se/books?id=cIY0JOAkLoYC&pg=PA105&lpg=PA105&dq=checkboxes+positive+negative&source=bl&ots=uYtmVk5UuD&sig=BBE5YlCAWUj2dHGNREWr8tQefJs&hl=en&sa=X&ved=0ahUKEwiX0pDZuc_XAhUlEpoKHVzHAVMQ6AEIZTAM#v=onepage&q=checkboxes%20positive%20negative&f=false)
So in this case it would instead be [x] Send discard requests during formatting (making the checkbox checked by default).
I'm not certain what the actual implication will be of checking vs unchecking this box will be, so I think we'll need to explain that somehow. I'll try to figure some string out.

**Comment by mvollmer** [comment]
> It's usually recommended to keep checkboxes positive, so they are not backwards.

Right, much better.

**Comment by andreasn** [comment]
"[x] Discard old blocks" - does that sound sane? Less about the process, and more about the outcome.

**Comment by mvollmer** [comment]
> "[x] Discard old blocks" - does that sound sane?

I think in this case we should stick to something that is as technically accurate as possible, aimed at experts.  This is in the advanced section, and not intended to explain things.

**Comment by andreasn** [comment]
"[x] Send discard requests"?
"[x] Send discard requests during formatting" - I like this one less, because it doesn't say formatting anywhere else in the dialog, but I think I'm fine with this as well, as long as discard is without "-characters around it. Makes it sound fake or ironic in my ears.

**Comment by maryclarke** [comment]
Just a few comments:
1. For the scale, if possible, it would be good to add the two end points for reference. Those end points can update depending on what is selected from the associated dropdown.
2. It would be good to add some space between all of the dropdowns so that they have some distinction from each other
3. Will there ever be more than one advanced option?  If not, probably don't need a whole section and could just have the checkbox visible at all times.
4. I agree with @andreasn on the positive statement on the checkbox and having it checked by default.
5. Title of the dialog should be headline case, so probably in this case at least Partition should be capitalized.

**Comment by andreasn** [comment]
> Title of the dialog should be headline case, so probably in this case at least Partition should be capitalized.

Oh, good call. Hadn't seen that. Filed #8146 about it.

**Comment by andreasn** [comment]
We discussed this some more in the standup today, and the conclusion is that this shouldn't be an option ideally.
Regular partitions and VDO partitions needs different defaults. VDO volumes needs discard to be turned off, while other partitions don't. So it would be better to always pass -k to partitions on VDO volumes, and never on regular volumes. So just have the setting done in the background, with less opportunity for people to shoot themselves in the foot.

**Comment by martinpitt** [comment]
We discussed that during the standup today. Summary:
 * Discard option during mount is painful, hard to explain, and there is no real technical justification for it:
   * discards should happen in the background, not block the user/mkfs
   * running it (just) for mkfs is useless, as you still need something that regularly calls `fstrim` during actually using the VDO.
 * There should be a systemd timer or cron job which regularly calls `fstrim`. This will "clean up" after a mkfs, deletions, and general operation without making mkfs or deletions slow.

Thus cockpit should just intelligently use `mkfs -K` on VDO fs creation and document that in doc/guide/.

There is a case to be made for offering a discard option button *independent* of fs creation, and *independent* of VDO (applies to SSO drives, too). This can be used if your disk becomes slow or faulty. This would essentially just start the systemd timer manually.

**Comment by mvollmer** [comment]
> For the scale, if possible, it would be good to add the two end points for reference. Those end points can update depending on what is selected from the associated dropdown.

@maryclarke, can you elaborate a bit?  Do you want to spell out the minimum and maximum size of the new partition as text?  Maybe you can link to a Patternfly example that shows what you have in mind, or share a screenshot of some existing UI.

**Comment by maryclarke** [comment]
@mvollmer, I mean something more in-line with what PatternFly shows here: http://www.patternfly.org/pattern-library/forms-and-controls/slider/

Here is a screenshot of the slider on that page: 
screen shot 2017-11-22 at 10 00 18 am

This page shows detents on the slider at different points, but I was suggesting that the numeric value may only needed at the low and high ends. If we feel that all users will know what the min and max numbers are, maybe this wouldn't be necessary.  I was only trying to point out that it is best practice to give context to users for the slider.  Nothing else about what you have would need to change.

**Comment by andreasn** [comment]
@mvollmer @maryclarke let's break the slider into a separate issue and keep this one for the discard action. Filed #8156 about the slider.

**Comment by mvollmer** [comment]
#7817 now silently uses "no-discard" for vdo volumes.

**Pull request closed without merging**
