### PR TITLE
test: Disable packagekit preloading in some more cases

### PR DESCRIPTION
**Pull request by mvollmer**
Otherwise, the CDP protocol might just hang and cause the test run to
timeout globally.

### CODE REVIEW

**Comment by martinpitt** [comment]
Needs fixing on [fedora-atomic](https://209.132.184.41:8493/logs/pull-12941-20191009-101414-da8b468a-cockpit-project-cockpit--fedora-atomic/log.html#239-2). Perhaps we should restrict this to fedora-30 for now, where we build with debug infos enabled?

**Comment by mvollmer** [comment]
> Perhaps we should restrict this to fedora-30 for now, where we build with debug infos enabled?

Yes, I think that makes sense.  Done.

**Comment by martinpitt** [comment]
The [fedora-30 test run](https://209.132.184.41:8493/logs/pull-12941-20191009-131515-2dfa89d6-cockpit-project-cockpit--fedora-30/log.html) is still hanging;  I went into the pod, and there are three libvirt machines from a single test, but I can't say which test it belongs to. 

Indeed I see a chromium process that seems rogue:

```
user       99810  100  0.8 1640656 1083088 ?     Rl   18:34 103:28 /usr/lib64/chromium-browser/headless_shell --type=renderer --disable-seccomp-filter-sandbox --no-sandbox --use-gl=swiftshader-webgl --ozone-platform=headless --field-trial-handle=12226985224205361781,1134011
```

I tried to virsh destroy the three VMs, but that didn't make the test stop. I then did `pkill headless_shell`, and finally the cdp-driver.js process, that finally gave it away:
```
Traceback (most recent call last):
  File "test/verify/check-dashboard", line 188, in testBasic
    b.wait_present("#dashboard-hosts .failed[data-address='10.111.113.3']")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 352, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 346, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 340, in wait_js_cond
    silent=False, awaitPromise=True, trace="wait: " + cond)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 85, in invoke
    res = self.command(cmd)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 102, in command
    raise RuntimeError("CDP broken")
RuntimeError: CDP broken
```

But that's one of the test where you applied the hack?

**Comment by mvollmer** [comment]
> But that's one of the test where you applied the hack?

Yes... It has two extra machines, but I had disabled pre-loading only for one of them.  Now both are disabled.  Let's see...

**Pull request merged**
