### PR TITLE
PCP improvements

### PR DESCRIPTION
**Pull request by marusak**
This PR brings two changes:
1) Dropping hack from install script which is not needed and brings pmlogger into stuck state
2) Disable switch while pmlogger is starting

This is just result of investigation why when switch for storing metrics is on no metrics are stored. Problem is that pmlogger can be in state `starting`/`activating`. Often this takes a few seconds to start but it can be indefinite (reproducible by stop pmcd, start pmlogger). We should somehow indicate that logger is trying to start - @garrett suggested disabling the switch.

Note:

- No tests yet, will write some when design is sattled

### CODE REVIEW

**Comment by garrett** [comment]
_**Disclaimer**: I've never managed to get Cockpit to resume PCP state or show the widgets at the top-right. (I'm not sure if it is storing it.) However, I've successfully toggled the toggle and nothing happens._

My impressions:

1. The toggle doesn't flip when I click "OFF"
   - The widget seems to only respond to clicking the slider part of the widget (on the left).
   - My guess is that this is probably a problem in the widget itself, not this PR.
   - It's not accessible or even navigatable via keyboard (this is widget-level, for a different PR).
2. It would probably be best to use an intermediate state version of the widget while the progress is pending.
   - Perhaps this is even the disabled state?
   - It would turn toggleable again when the process is done.
   - The switch should have transitions between disabled and non-disabled. (Probably an enhancement in another PR, using CSS transition for the color & background.)

As PCP either doesn't save state or show state, I might be missing some additional feedback.

---

**Summary**: I think out of all of the above items I brought up, what's suitable for this PR is to have an intermediate (probably disabled) state when the process is running.

(Also, I should open up issues for everything not covered in this PR.)

**Comment by marusak** [comment]
> I've never managed to get Cockpit to resume PCP state or show the widgets at the top-right

Check is both `pcmd` and `pmlogger` services are running.

> The toggle doesn't flip when I click "OFF" 

This is confusing and I was first time really baffled with this, but that's how the on/off switch is implemented in cockpit. But I agree this can should be improved.

> Perhaps this is even the disabled state?

This makes sense! I will do it that way.

**Comment by garrett** [comment]
I've opened the relevant issues:

- Accessibility: https://github.com/cockpit-project/cockpit/issues/11225 (It would need manual changing in the Overview, of course, as it's not React.)
- Animation transition: https://github.com/cockpit-project/cockpit/issues/11226

Neither of these should block this PR, however.

**Comment by marusak** [comment]
@garrett I've changed it into disabling the switch

**Comment by martinpitt** [comment]
There's one failure on rhel-7-6-distropkg: https://fedorapeople.org/groups/cockpit/logs/pull-11224-20190224-172121-72ecee03-verify-rhel-7-6-distropkg/log.html#259

Might be a flake, or the test is missing another conditional?

**Comment by marusak** [comment]
Ah, good point, it was bug. distropkg switcher still reacts to enabled service and not to running service. Pushed updated test.

**Pull request merged**
