### PR TITLE
test: Fix multi-os test for newer centos

### PR DESCRIPTION
**Pull request by petervo**

### CODE REVIEW

**Comment by stefwalter** [comment]
Hmmm, the whole point of these tests is to test against an old version of cockpit no? It seems like we shouldn't be rebuilding these images. Or am I misunderstanding that?

**Comment by petervo** [comment]
I didn't specifically rebuild, my images were broken so i deleted them and reran ./testsuite-prepare it downloaded and this was what i got.

**Comment by stefwalter** [comment]
> I didn't specifically rebuild, my images were broken so i deleted them and reran ./testsuite-prepare it downloaded and this was what i got.

I'll upload mine. The ones rebuilt on hubbot are broken. We should discuss this later and  figure out what to do, but for now lets just use the old ones.

**Comment by mvollmer** [comment]
The point of the tests is to test against the version of Cockpit that people get when they install CentOS 7, no?

**Comment by stefwalter** [comment]
> The point of the tests is to test against the version of Cockpit that people get when they install CentOS 7, no?

The point is to test for regressions across versions of Cockpit and make sure we still interoperate with old versions. If centos updates Cockpit in old versions, then we should probably just stick with testing against Fedora here.

In addition @jscotka was pointing out another test that could take its place: Test an old cockpit-ws against a newer cockpit-bridge/cockpit-shell. This is the case in Atomic Host where people don't update the privileged container.

**Comment by stefwalter** [comment]
I've put the old centos stock image into #3037. So this should resolve itself once we're there. We shouldn't update the centos stock image after that. Alternatively we can remove it, if it doesn't represent a test target for this test.

**Comment by stefwalter** [comment]
Replaced by #3066

**Pull request closed without merging**
