### PR TITLE
sosreport: Install and test on fedora-atomic

### PR DESCRIPTION
**Pull request by mvollmer**
This works just as well as on fedora-23.  (I.e., we run into
https://bugzilla.redhat.com/show_bug.cgi?id=1278807)

### CODE REVIEW

**Comment by stefwalter** [comment]
Is sosreport present on Fedora and RHEL atomic?

**Comment by mvollmer** [comment]
> Is sosreport present on Fedora and RHEL atomic?

No, good point.  (Hrr.)

Should we start testing rhel-atomic as well?  I give it a shot.

**Comment by stefwalter** [comment]
The OSTree test is failing. It's timed out waiting for |sos_pkg| so seems related.

**Comment by mvollmer** [comment]
> The OSTree test is failing. It's timed out waiting for |sos_pkg| so seems related.

Yes.  The test needs a top-level package to remove and "sos" was an essentially arbitrary choice.  I have changed it to use "cockpit-sosreport" instead, which is now top-level.

**Pull request closed without merging**
