### PR TITLE
tests: Add some more localhost → 127.0.0.1 workarounds

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**

### CODE REVIEW

**Comment by martinpitt** [comment]
@allisonkarlitskaya : We still want the first two commits, but drop the localhost→127.0.0.1 one, and rather wait for the glib fix, right? So should we land the other two?

**Comment by allisonkarlitskaya** [comment]
@martinpitt those were already merged as part of #11910.  I only included them here to see if we could get semaphore to go all the way through with both of them.

**Comment by martinpitt** [comment]
@allisonkarlitskaya : Oh right, so it seems this is pretty much obsolete, and we can close this? (If needed, it can easily be reopened)

**Comment by allisonkarlitskaya** [comment]
Ya, sure... chances of this ever landing are pretty slim.

**Pull request closed without merging**
