### PR TITLE
Image refresh for fedora-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-testing
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by martinpitt** [comment]
Still wrong tests, manually triggering fedora-testing.

**Comment by marusak** [comment]
`systemctl start etcd kube-apiserver kube-controller-manager kube-scheduler kube-proxy kubelet` failed pretty much on every kubernetes test. [10 fails](https://209.132.184.41:8493/logs/pull-11595-20190415-074444-6f078131-verify-fedora-testing/log.html)

**Comment by marusak** [comment]
Same issue https://github.com/cockpit-project/cockpit/pull/11572#issuecomment-482889892

**Comment by marusak** [comment]
So I suspected that the new version just did not get into the new image, but it did.
```
$ rpm -q etcd
etcd-3.3.12-2.20190413gitf29b1ad.fc29.x86_64
```
@eclipseo

**Comment by martinpitt** [comment]
Submitted feedback to https://bodhi.fedoraproject.org/updates/FEDORA-2019-185e366042

**Comment by martinpitt** [comment]
There's a new etcd: https://bodhi.fedoraproject.org/updates/FEDORA-2019-049b108f40

Let's roll the dice again!

**Pull request closed without merging**
