### PR TITLE
change about dialog to mention license and project website. Fixes issue #2213

### PR DESCRIPTION
**Pull request by andreasn**

### CODE REVIEW

**Comment by andreasn** [comment]
Fixes #2213

**Comment by dperpeet** [comment]
Since we remove the span `about-build-info`, we should also remove the reference in https://github.com/cockpit-project/cockpit/blob/926dd06c6b919dfe19f4b48a0b5bce8ad367c99e/pkg/shell/index.js#L131.

**Comment by andreasn** [comment]
I removed that line. Is that enough or do I need to delete other lines as well?

**Comment by stefwalter** [comment]
* Don't link to github internals for LGPL license
     * Open links in new tab/window

**Pull request closed without merging**
