### PR TITLE
tools: Make sure PCP namespace exists

### PR DESCRIPTION
**Pull request by mvollmer**
Depends on #1743

### CODE REVIEW

**Comment by stefwalter** [comment]
@fche Out of interest, why do these namespace files have to be built at install time ... and then again a second time compiled using pmcpp at pmNewContext() time? Should we file a bug about simplifying that, or is it by design?

**Comment by stefwalter** [comment]
Tried running this workaround manually on a fresh machine, and it did fix the regression of no graphs showing up.

@mvollmer a simple integration test that checks for the presence of graph data, would allow us to look for regressions here in the future. But I don't think this pull request needs to block on that.

**Comment by fche** [comment]
> @fche Out of interest, why do these namespace files have to be built at install
> time ... and then again a second time compiled using pmcpp at pmNewContext()
> time? Should we file a bug about simplifying that, or is it by design?

No idea, that's a weird one.  It seems like we should be able to run
pmcpp solely at pmns-rebuild time, and not each PM_CONTEXT_LOCAL open.
Please open a bug.

**Comment by stefwalter** [comment]
> > @fche Out of interest, why do these namespace files have to be built at install time ... and then again a second time compiled using pmcpp at pmNewContext() time? Should we file a bug about simplifying that, or is it by design?

> No idea, that's a weird one. It seems like we should be able to run pmcpp solely at pmns-rebuild time, and not each PM_CONTEXT_LOCAL open. Please open a bug.

Filed here: https://bugzilla.redhat.com/show_bug.cgi?id=1187159

**Pull request closed without merging**
