### PR TITLE
machines: Serial console

### PR DESCRIPTION
**Pull request by mareklibra**
New subtab is added for in-browser access to serial console of a virtual machine.

Video: https://youtu.be/nT2EA6wYkKI

### CODE REVIEW

**Comment by mareklibra** [comment]
serialconsole

**Comment by mareklibra** [comment]
serialconsole

**Comment by stefwalter** [comment]
This is awesome wortk!

**Comment by petervo** [comment]
LGTM

@andreasn since only one person can connect to a console at a time, do we need a disconnect button to free up the console.

**Comment by andreasn** [comment]
> since only one person can connect to a console at a time, do we need a disconnect button to free up the console.

Sure.

What's the difference between a graphics console and a serial console exactly?
Doesn't this show the exact same stuff as the Graphics console?

**Comment by mareklibra** [comment]
>>  since only one person can connect to a console at a time, do we need a disconnect button to free up the console.

> Sure.

Good point, I'll add it within this PR.


> What's the difference between a graphics console and a serial console exactly?
Doesn't this show the exact same stuff as the Graphics console?

The output is different. Internally, Graphics Console (VNC/SPICE) is served via internally executed server, providing graphical output, sort of graphic card connected to monitor.

Serial console is much more light-weight, recently mimicking the ancient (but still used) dummy hardware to interact with servers. It simply sends in/out text only. It expects some support from OS and hypervisor to properly listen and write. It's biggest benefit over Graphics Console is during initial machine boot and general better acceptance for head-less servers. It can be used similar way as `ssh` is, but even right after power-on of the machine.

**Comment by mareklibra** [comment]
The `Diconnect` button added:

disconnected

**Comment by petervo** [comment]
@andreasn I reviewed and this seems good to me. Are you ok with it?

**Comment by andreasn** [comment]
Conceptually serial console feels like just another kind of console, next to the Web based serial console and Serial Console via the Desktop Viewer that we already have to me.

As someone who's a bit more of a noob when it comes to handling VMs (I run VMs daily, but I don't know enough about the underlying technology), I've found that virt-manager does this too, and I found it pretty nice:
screenshot-virtman.

Could we in a similar way have another console type next to the two serial consoles we have now?
I feel that would simplify the navigation a lot. It's starting to become a bit crowded with all the tabs, and I think there will be even more tabs in the future.

mockup

**Comment by mareklibra** [comment]
@andreasn , done. Please have a look at recent screenshots:

01_consoles

02_consoles

03_consoles

**Comment by mareklibra** [comment]
Once this is agreed, I can record a video showing changes in the `Consoles` subtab

**Comment by andreasn** [comment]
Looks mostly good to me!

The only little error I found was that the dropdown doesn't fit the whole string.
screenshot from 2017-12-18 16-14-03

I think this is due to this class:
```
.bootstrap-select:not([class*="col-"]):not([class*="form-control"]):not(.input-group-btn) {
width: 220px; }
```

Overriding this with `width: auto; `should do the trick I think. Apart from that, good to merge from a UI point of view.

**Comment by mareklibra** [comment]
@andreasn , done. I've added fixed `width: 19em` to avoid size changes while different items are being selected.

**Comment by mareklibra** [comment]
Video recorded: https://youtu.be/nT2EA6wYkKI

**Comment by serenamarie125** [comment]
@andreasn I'm curious how the design in this PR affects what we suggested [here](https://github.com/cockpit-project/cockpit/wiki/Product-Integration) for accessing consoles

**Pull request closed without merging**
