### PR TITLE
Image refresh for ubuntu-stable

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for ubuntu-stable
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by marusak** [comment]
[testCreate](https://209.132.184.41:8493/logs/pull-12243-20190706-100909-8c6dd516-verify-ubuntu-stable/log.html#89) failed 3 times in a row.

**Comment by KKoukiou** [comment]
> [testCreate](https://209.132.184.41:8493/logs/pull-12243-20190706-100909-8c6dd516-verify-ubuntu-stable/log.html#89) failed 3 times in a row.

I can't reproduce this. I wonder if it fails the same way in the previous two failures. I will re-trigger to monitor the exact failure.

**Comment by KKoukiou** [comment]
@marusak  testCreate didn't fail when I re-triggered one time. I bet it's a bad flake but it shouldn't block this. 
testRaid fails now again, same as in the link you pasted above.

**Comment by martinpitt** [comment]
Green now :)

**Pull request merged**
