### PR TITLE
Implement new image and imagestream listing

### PR DESCRIPTION
**Pull request by petervo**
Depends on https://github.com/openshift/registry-image-widgets/pull/15

### CODE REVIEW

**Comment by thomasmckay** [comment]
ACK tested w/ https://github.com/openshift/registry-image-widgets/pull/15

**Comment by martinpitt** [comment]
Temporarily removing priority - we want #7400 to land first and then re-run the tests against OpenShift 1.7, so this will be using the bots more efficiently.

**Comment by stefwalter** [comment]
Did another smoke test of this. It works.

**Comment by martinpitt** [comment]
#7401 with the new OpenShift image landed. I retriggered the tests which run check-openshift.

**Comment by martinpitt** [comment]
Screenshot from local testing, also for the release notes:

kubernetes-imagestreams

**Pull request closed without merging**
