### PR TITLE
bots: Add libvirt-dbus to rhel-7-7 image

### PR DESCRIPTION
**Pull request by martinpitt**
This exists in extras now, and we want to use it.

Preparation for https://bugzilla.redhat.com/show_bug.cgi?id=1712911

 * [x] image-refresh rhel-7-7

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-11907-20190523-064242/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-06.
Log: https://209.132.184.41:8493/logs/image-refresh-11907-20190523-083535/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-8.
Log: https://209.132.184.41:8493/logs/image-refresh-11907-20190523-082222/

**Comment by cockpituous** [comment]
image-refresh rhel-7-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-7-20190523-085757

**Comment by martinpitt** [comment]
The composer failure was most probably introduced in #11889 when moving Extras to 7.7. @henrywang , do you have some time to look into this? Thanks!

**Comment by henrywang** [comment]
@martinpitt, I found the same issue on [PR#639](https://github.com/weldr/cockpit-composer/pull/639) and [PR#667](https://github.com/weldr/cockpit-composer/pull/667). I'm working on it. The issue looks not related with repo, but with new lorax-composer. I'll figure this issue out.

**Comment by martinpitt** [comment]
@KKoukiou : It looks like there's a new regression here with a ramdisk, could you please have  a look?

https://209.132.184.41:8493/logs/pull-11907-20190523-120909-65e22580-verify-rhel-7-7/log.html#89

**Comment by KKoukiou** [comment]
> @KKoukiou : It looks like there's a new regression here with a ramdisk, could you please have a look?
> 
> https://209.132.184.41:8493/logs/pull-11907-20190523-120909-65e22580-verify-rhel-7-7/log.html#89

Right, contacted libvirt devs, their answer was that liblkid in rhel7 cant cope with the ramdisk.
I will probably replace the ramdisk in the tests with the other solution you suggested the other day.

**Comment by henrywang** [comment]
@martinpitt, I think [PR #677](https://github.com/weldr/cockpit-composer/pull/677) has this issue fixed.

**Comment by martinpitt** [comment]
@henrywang : Thanks! Retrying.

**Comment by martinpitt** [comment]
Thanks @KKoukiou , looks good! I force-pushed to trigger all tests, as this needs to be verified everywhere now.

**Comment by martinpitt** [comment]
Hmpf, there's now a new failure of [testStoragePoolsCreate](https://209.132.184.41:8493/logs/pull-11907-20190523-202727-f2b4a9cc-verify-rhel-7-7/log.html#260):
```
testlib.Error: type=1400 audit(1558644566.651:4): avc:  denied  { getattr } for  pid=3874 comm="iscsid" path="/dev/dm-0" dev="devtmpfs" ino=9216 scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:object_r:fixed_disk_device_t:s0 tclass=blk_file permissive=0
```
This is a new violation, which needs to be reported and naughtied.

**Comment by martinpitt** [comment]
I added a naughty for the above [SELinux regression](https://bugzilla.redhat.com/show_bug.cgi?id=1698702).

**Comment by martinpitt** [comment]
I went back to only triggering the two directly affected tests. The previous ones for the adjusted storage pool ones work, and  can still be seen above.

**Pull request merged**
