### PR TITLE
bots: Switch rhel-7-6 to released repository

### PR DESCRIPTION
**Pull request by martinpitt**
Move the nightly repo setup to 7.7. We don't have that image yet, but
with that it will be easy to add.

 * [x] image-refresh rhel-7-6

### CODE REVIEW

**Comment by martinpitt** [comment]
Note that this will still leave the rhel-7-6 external tests broken. The 7.6 nightly repository now requires a subscription, just like the released one, so you can't just yum install anything on these. We need to think about what to do there.

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-7vn8x.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10473-20181030-164545/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-wlp1m.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10473-20181030-165353/

**Comment by martinpitt** [comment]
I pushed another commit to add gcc-c++ to the rhel-7-6 image for welder-web. This is the only package it yum installs, and it's not too much of a burden.

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-m1rcd.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10473-20181030-185858/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-dwzgb.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10473-20181030-185858/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-1mlmr.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10473-20181030-185858/

**Comment by cockpituous** [comment]
image-refresh rhel-7-6 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-6-20181030-191111

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10473-20181030-185858/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-h6g82.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10473-20181030-202020/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-s2g2f.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10473-20181030-202020/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-mjpwk.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10473-20181030-202121/

**Comment by cockpituous** [comment]
image-refresh rhel-7-6 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-6-20181030-205656

**Pull request merged**
