### PR TITLE
Fix Debian/Ubuntu image builds

### PR DESCRIPTION
**Pull request by martinpitt**
This unbreaks Debian/Ubuntu image builds with our current way of
invoking QEMU (where interface names start at ens14) and brings the
Debian virt-builder invocation in line with virt-builder-fedora.

 * [x] image-refresh debian-stable
 * [x] image-refresh debian-testing
 * [x] image-refresh ubuntu-stable
 * [x] image-refresh ubuntu-1604
 * [x] move to non-obsolete AppStream metadata format (PR #7612)

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-mmjqt.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170904-144141/

**Comment by cockpituous** [comment]
Task threw an exception: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170904-144141/

**Comment by martinpitt** [comment]
Local build worked; bot build timed out on uploading, so retrying that.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-x6t6m.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170904-151717/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-stable-20170904-154242

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-x6t6m.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170904-154343/

**Comment by cockpituous** [comment]
Task threw an exception: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170904-154343/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-ps164.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170904-160606/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-stable-20170904-162929

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-64b10.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170904-163131/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-testing-20170904-165959

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-9mk9t.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170904-172828/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-f4xdx.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170904-172929/

**Comment by cockpituous** [comment]
image-refresh ubuntu-1604 done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-1604-20170904-180303

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-11.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170904-180808/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-testing-20170904-183636

**Comment by martinpitt** [comment]
On debian-testing, package build now fails due to a new lintian error:
```
W: cockpit: appstream-metadata-in-legacy-location usr/share/appdata/cockpit.appdata.xml
E: cockpit: appstream-metadata-legacy-format usr/share/appdata/cockpit.appdata.xml
```
@mvollmer, can we use the current format/location for that?

**Comment by martinpitt** [comment]
PR #7612 updates the AppStream metadata, with that lintian is happy.

**Comment by martinpitt** [comment]
debian-testing is still broken - during image build docker actually pulls down the busybox (and other) images, but on the booted image `docker images` is emtpy. This is due to aufs not yet being ready the first time:
```
Sep 05 08:48:47 unassigned-hostname docker[731]: time="2017-09-05T08:48:47-04:00" level=warning msg="Graphdriver aufs selected. Your graphdriver directory /var/lib/docker already contains data managed by other graphdrivers: devicemapper"
```

**Comment by martinpitt** [comment]
I know why this happens: On package installation, `aufs-dkms` just builds for the kernel that is marked as current for the next boot (`/vmlinuz` symlink), but *not* for the currently running kernel. debian-9 has kernel 4.9, the dist-upgrade moves to 4.12. So indeed it would be better to upgrade and reboot before running the setup script, thus revert the [commit that moved it](https://github.com/cockpit-project/cockpit/pull/7606/commits/8762b17b8568dde92773e943b16adc00df44e8dc).

**Comment by martinpitt** [comment]
> So indeed it would be better to upgrade and reboot before running the setup script, thus revert the [commit that moved it](https://github.com/cockpit-project/cockpit/pull/7606/commits/8762b17b8568dde92773e943b16adc00df44e8dc).

No, that doesn't work either, as `--run-command` doesn't have proper networking - that's the main reason for broken image builds in the first place. So I think the next best thing is to build the aufs module for the currently running kernel too, so that the image setup can pull docker containers into aufs without needing a reboot.

**Comment by martinpitt** [comment]
> the next best thing is to build the aufs module for the currently running kernel too

... and that does not work as the aufs source is kernel specific, so we would need to first install the source from the virt-builder base image. Argh! I really wonder what caused `--run-command` to suddenly not have networking any more ☹

**Comment by martinpitt** [comment]
`--run-command 'ip a; ip route; cat /etc/resolv.conf'` actually looks reasonable, it routes to 10.111.112.1 and uses that as a DNS server, too. But this network does not actually seem to work any more, same reason why `test/vm-run --network` ceased to actually work.

**Comment by martinpitt** [comment]
PR #7617 fixes `vm-run --network`, and after running that once locally (to fix my definition of the `cockpit1` network), `vm-create` starts to work locally too, i. e. `--run-command` then has networking. Without the `cockpit1` virsh network, `vm-create` fails:
```
[  24,0] Opening the new disk
virt-builder: error: libguestfs error: bridge 'cockpit1' not found.  Try running:
[...]
```
Some of the bots still have the `cockpit1` network with a `<nat>`, presumably from "the old times" when we still had `vm-prep`. But more recent containers don't have a `cockpit1` network at all any more, and I suppose these are the ones where `vm-create debian..` fails. I'm not sure how they are configured to avoid the error above, though.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170905-200404/

**Comment by martinpitt** [comment]
Seems I mis-looked, and bots actually *do* have a `cockpit1` virsh network with NAT. Thus the commit for moving the disabling of the udev network names into `--run-command` is actually sufficient, at least locally image building works then. I triggered an image build on the bots to confirm.

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170905-200404/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-mmjqt.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170905-201212/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170905-201212/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-zph4p.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170905-202222/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170905-202222/

**Comment by martinpitt** [comment]
Meh, this isn't my lucky day.. Three [virt-builder image download checksum failures](https://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170905-202222/log) in a row..

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-csjnc.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170905-203535/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170905-203535/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-xst7t.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170905-204141/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-stable-20170905-211111

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-csjnc.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7606-20170906-041111/

**Comment by cockpituous** [comment]
image-refresh ubuntu-1604 done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-1604-20170906-043535

**Pull request merged**
