### PR TITLE
ws: Support Content-Encoding with external channels

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by petervo** [comment]
Test is failing.

Do we need some sort of validation of incoming Content-Encoding values. Generally with incoming Content-Encoding headers the server is supposed to ensure that the repsonse matches the requested encoding and reply with a 415 if it can't. Are we expecting the server to gzip or is this only supposed to be used with already gzipped files. Accept-Encoding might be a less strict alternative. Does it give us what we need?

**Comment by mvollmer** [comment]
> Test is failing.

Fixed.

**Comment by mvollmer** [comment]
> Do we need some sort of validation of incoming Content-Encoding values.

This is for the response, not the request, so I am confused by you saying "incoming".

This is supposed to be used to describe the content delivered by an external channel, and cockpit-ws can just believe that it is correct.  This is just like content-type, I'd say.

**Comment by petervo** [comment]
>This is for the response, not the request, so I am confused by you saying "incoming".

Yes you are right, I needed to brush up on how external channels work.

**Pull request closed without merging**
