### PR TITLE
machines: Enable interface type "direct" in NIC configuration

### PR DESCRIPTION
**Pull request by skobyda**

### CODE REVIEW

**Comment by skobyda** [comment]
optimized-Screenshot from 2019-08-13 17-07-03

**Comment by skobyda** [comment]
optimized-Screenshot from 2019-08-13 17-12-24

**Comment by KKoukiou** [comment]
The code looks good, but there some test related failures that need attention,
https://209.132.184.41:8493/logs/pull-12567-20190813-151212-6b8c4c6d-cockpit-project-cockpit-fedora-30-selenium-edge/log.html#48
https://209.132.184.41:8493/logs/pull-12567-20190813-151212-6b8c4c6d-cockpit-project-cockpit-rhel-8-0-distropkg/log.html
https://209.132.184.4https://209.132.184.41:8493/logs/pull-12567-20190813-151212-6b8c4c6d-cockpit-project-cockpit-fedora-30-selenium-edge/log.html#481:8493/logs/pull-12567-20190813-151212-6b8c4c6d-cockpit-project-cockpit-rhel-8-1/log.html#229

**Comment by KKoukiou** [comment]
@skobyda I think you need
```
diff --git a/pkg/machines/components/nicEdit.jsx b/pkg/machines/components/nicEdit.jsx
index dd5a82e6f..ef16e7767 100644
--- a/pkg/machines/components/nicEdit.jsx
+++ b/pkg/machines/components/nicEdit.jsx
@@ -207,7 +207,7 @@ export class EditNICAction extends React.Component {
                 if (value == 'network')
                     availableSources = this.props.networks.map(network => network.name);
                 else if (['direct'].includes(value))
-                    availableSources = this.props.interfaces.map(iface => iface.name);
+                    availableSources = getNetworkDevices(this.props.vm.connectionName, this.props.nodeDevices, this.props.interfaces);
 
                 if (availableSources.length > 0) {
                     this.setState({ 'networkSource': availableSources[0] });

```

**Pull request merged**
