### PR TITLE
test: Sort non-destructive tests

### PR DESCRIPTION
**Pull request by martinpitt**
Running tests in a more or less random order has already bit us more
than once (at least PR #13843 and #13598): A new test that succeeded in
a PR just because it happened to run late, and then it fails later on
when it runs earlier.

 - [x] failed tests need `[ND]` marker, too: PR #13855
 - [x] fix TestNondestructiveExample to work in any order: PR #13855

### CODE REVIEW

**Comment by mvollmer** [comment]
Hmm.  Tests should be independent of each other, and this will hide any accidental dependencies.  What about running them in reverse sorted order on some images, but in normal sorted order on others?

**Comment by martinpitt** [comment]
@mvollmer: That's a nice idea! Some ideas:

1. Run tests on reverse order for `TEST_OS_DEFAULT` (fedora-31 at the moment). We already use that to enable debug mode. But I'm afraid that makes fedora-31 too special -- it already fails a lot more as it's slower (due to debug mode) and picks up React failures. But at least it would be obvious.

2. Determine sorting order via one bit of hash(TEST_OS). It wouldn't be quite obvious beforehand which order an image uses, but at least it's still stable, and doesn't depend on extra configuration. It also has the advantage that we evenly spread forward and reverse between tests.

3. Explicitly set the sorting order via an env var in test/run. A bit too much effort IMHO.

Given that so far we have lived with pretty much a random order, I'm leaning towards 2. @mvollmer, @marusak , opinions?

**Comment by marusak** [comment]
I lean more to 1. as I like that it is obvious from the test name that we use different order.
2. is more robust, but I am not convinced that we need to test the order that much. Also `check-testlib` would be a bit more complex.

**Comment by martinpitt** [comment]
> Also check-testlib would be a bit more complex.

It's going to be more complex either way, as we need to take `$TEST_OS` into account regardless of which particular algorithm we use.

**Comment by martinpitt** [comment]
I pushed an implementation of solution 2. Most work really was adjusting check-testlib, but it's easy to adjust if we want to use a different algorithm now.

I also added an additional commit to label nondestructive tests in the log, so that it's easier to visually see or grep for them.

**Comment by martinpitt** [comment]
[debian-testing](https://logs.cockpit-project.org/logs/pull-13844-20200404-061221-ba3e19fb-debian-testing/log.html#159) has some funny failures, retrying once to compare. There's also something funky going on with [TestNondestructiveExample](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-13844-20200404-061224-ba3e19fb-debian-stable/log.html#49) -- these just can't be run in reverse order.

**Comment by martinpitt** [comment]
I fixed the order-dependent packagekit and services failures spotted by [debian-testing](https://logs.cockpit-project.org/logs/pull-13844-20200406-135856-c97ad7ae-debian-testing/log.html#151) [and](https://logs.cockpit-project.org/logs/pull-13844-20200406-135852-c97ad7ae-rhel-8-2/log.html) [others](https://logs.cockpit-project.org/logs/pull-13844-20200406-135847-c97ad7ae-ubuntu-stable/log.html).

**Comment by martinpitt** [comment]
Genuinely broken on [ubuntu-1804](https://logs.cockpit-project.org/logs/pull-13844-20200407-113716-98820c25-ubuntu-1804/log.html#160). Now `TestUpdates` runs as one of the last things, and something before breaks access to local port 12345. (Firewall?)

**Comment by marusak** [comment]
Could you please also run 'fedora-testing'? (it is the only fedora that has reverse order and fedora tests are the most complex ones)

Just for interest, here are images and if they have reverse order(1 is reverse):
```
debian-stable: 1
debian-testing: 1
fedora-testing: 1
rhel-7-7: 1
rhel-8-2: 1
ubuntu-stable: 1
centos-7: 0
centos-8-stream: 0
fedora-31: 0
fedora-32: 0
fedora-coreos: 0
rhel-7-8: 0
rhel-8-2-distropkg: 0
ubuntu-1804: 0
ubuntu-2004: 0
```

**Comment by martinpitt** [comment]
[f-testing](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-13844-20200408-055623-bff9470a-fedora-testing/log.html#1) has a single failure, a known flake (some process keeps the user busy that's about to be deleted). Retrying to be sure, though.

**Comment by martinpitt** [comment]
The [f-testing retry](https://logs.cockpit-project.org/logs/pull-13844-20200408-084921-bff9470a-fedora-testing/log.html) has some other well-known flakes, but check-accounts passed now. I'm debugging this in  #13870, but let's not block the other test fixes on that.

**Pull request merged**
