### PR TITLE
test: Refactor check-networking

### PR DESCRIPTION
**Pull request by mvollmer**
Split it into multiple files, supported by the new netlib.py.

Also, the initial state and the NetworkManager policy regarding
automatic activation is made consistent across OSes.

### CODE REVIEW

**Comment by dperpeet** [comment]
Networking tests are failing on different distros.
It's difficult to tell what exactly changed since the split and behavior changes are in a single commit, but did you make sure that we aren't getting static IP conflicts between the tests? I think that was one reason we didn't refactor this earlier. We also moved a lot of tests to just use DHCP, so I'm not sure if that's an actual problem.

**Comment by mvollmer** [comment]
rhel-atomic and debian-8 don't have "nmcli dev ... set managed yes".

check-networking-unmanaged needs a full NM restart, apparently, not just a "nmcli con reload".

**Comment by stefwalter** [comment]
5 check-networking test failures. I imagine @mvollmer will want to examine these individually, and if they are fixed elsewhere rerun the tests so they're green.

**Comment by mvollmer** [comment]
I have some hopes that the updated test runners cause less disconnections.  Let's see.

**Comment by mvollmer** [comment]
Rebased.

**Comment by dperpeet** [comment]
The semaphore failure has been fixed in https://github.com/cockpit-project/cockpit/commit/5954da9fc733676a340e41b567c479e51fd73f46

**Comment by dperpeet** [comment]
I feel like the networking tests are more flaky now than they used to be before these changes.
```
# testBasic (check_networking_basic.TestNetworking)
#
52:54:00:12:34:56 -> ens6
52:54:00:12:34:56 -> ens6
> Invalid prefix or netmask 255.255.0.8
> health check failure ignored
Wrote TestNetworking-testBasic-FAIL.png
Journal extracted to TestNetworking-testBasic-10.111.116.129-FAIL.log
not ok 67 testBasic (check_networking_basic.TestNetworking) duration: 95s
Traceback (most recent call last):
  File "./verify/check-networking-basic", line 50, in testBasic
    b.wait_popdown("network-ip-settings-dialog")
  File "/build/cockpit/test/common/testlib.py", line 267, in wait_popdown
    self.wait_not_visible('#' + id)
  File "/build/cockpit/test/common/testlib.py", line 239, in wait_not_visible
    return self.wait_js_func('!ph_is_visible', selector)
  File "/build/cockpit/test/common/testlib.py", line 209, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 719, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 742, in _invoke
    raise Error(res['error'])
Error: timeout
health check failure ignored

```

**Comment by mvollmer** [comment]
Removing `needswork` so that we get this tested.

The flakyness looks like general connectivity problems to me.  I have removed the `switch_off_rpfilter` hack, maybe this is still needed after all.

**Comment by stefwalter** [comment]
Seems to need a rebase in order to pass Semaphore CI now that other pull requests have been merged.

**Comment by mvollmer** [comment]
This blocks a couple of other requests and is in constant danger of merge conflicts, so let's try to get this in.

**Comment by mvollmer** [comment]
Quick!  It's green!  :-)

**Pull request closed without merging**
