### PR TITLE
test: Drop duplicated Debian build dependencies

### LINKED ISSUE #3298: Building on Debian uses a expliclit list of build dependencies
instead of getting them from `debian/control`.

Pbuilder does not have a straightforward way to install builddeps.

One idea would be to do a proper build (maybe abridged), but there is no `--save-after-build` option.

Another idea is to replicate what puilder-satisfydepends does, or use it directly.

Another idea is to just grep the build-depends out of debian/control (maybe with the help of /usr/lib/pbuilder/pbuilder-satisfydepends-funcs) and discard the version requirements.

### PR DESCRIPTION
**Pull request by martinpitt**
Use adjust-for-release and pbuilder-satisfydepends to determine the
build dependencies to install into the pbuilder chroots instead of
duplicating them in the three setup scripts.

Also minimize the diff in that area of the scripts for easier future
maintenance.

Fixes #3298

This also adds some optimizations to the build process.

### CODE REVIEW

**Comment by martinpitt** [comment]
bot: Image refresh for ubuntu-1604

**Comment by cockpituous** [comment]
Image creation for ubuntu-1604 in process on cockpit-10.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-ubuntu-1604-95be48399a595dd92818682b42989ac350d27046/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-ubuntu-1604-95be48399a595dd92818682b42989ac350d27046

**Comment by martinpitt** [comment]
bot: Image refresh for debian-8

**Comment by martinpitt** [comment]
bot: Image refresh for debian-testing

**Comment by cockpituous** [comment]
Image creation for debian-8 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-8-95be48399a595dd92818682b42989ac350d27046/

**Comment by cockpituous** [comment]
Image creation for debian-testing in process on cockpit-11.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-debian-testing-95be48399a595dd92818682b42989ac350d27046/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-debian-8-95be48399a595dd92818682b42989ac350d27046

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-debian-testing-95be48399a595dd92818682b42989ac350d27046

**Comment by martinpitt** [comment]
The Debian-ish tests all succeeded, just retrying some unrelated failures now. So this is ready for review/landing.

**Pull request closed without merging**
