### PR TITLE
system: Correctly write names of crypto policies

### LINKED ISSUE #18790: Correctly write names of crypto policies
Right now it looks like this:
Screenshot from 2023-05-11 11-17-36

We should always write FIPS and not Fips, also SHA1 not sha1, OSPP instead of ospp and AD-support rather than ad-support. Also we name the policy Default but in description we use DEFAULT. We should be consistent about this.

### PR DESCRIPTION
**Pull request by Pushkarm029**
replaced few words in test/verify/check-system-info. 

Fixes #18790

### CODE REVIEW

**Comment by Pushkarm029** [comment]
This is my first open source contribution; if I made a mistake, please let me know.

**Comment by martinpitt** [comment]
Hello @Pushkarm029 , thanks for your interest! You fixed the integration test, but not the actual place in the code where these words are produced. I. e. `testCryptoPolicies` will now fail and indicate the desired state (which is good). You should be able to run the test locally and confirm.

**Review by martinpitt — CHANGES_REQUESTED** [review]
See above.

**Comment by Pushkarm029** [comment]
Screenshot from 2023-05-14 11-56-35


@martinpitt i setted up the project locally , but i am not able to find the Change Crypto Policy Option.

**Comment by martinpitt** [comment]
@Pushkarm029 : Are you still interested in fixing this, or should somebody else take over? Thanks!

**Comment by Pushkarm029** [comment]
@martinpitt I apologize for the delay. I have set up the project locally, but I am not able to run the tests locally. Please allow me some more time (around 2-3 days). Thank you

**Comment by Akshat2Jain** [comment]
@martinpitt  how to run tests locally?

**Comment by martinpitt** [comment]
@Pushkarm029 : See https://github.com/cockpit-project/cockpit/blob/main/HACKING.md and https://github.com/cockpit-project/cockpit/blob/main/test/README.md

**Comment by martinpitt** [comment]
@Narcos101 At this point I'd say yes. Thanks!

**Comment by Akshat2Jain** [comment]
> hey @martinpitt Is this issue open to take?

@Narcos101 
I could help you solve this issue.

**Comment by Narcos101** [comment]
hey @Akshat2Jain Lets connect on discord:-Narc#4975

**Comment by Akshat2Jain** [comment]
> hey @Akshat2Jain Lets connect on discord:-Narc#4975

which Linux dist are you using?

**Comment by martinpitt** [comment]
This is stale, and issue #18790 was fixed in PR #18907 in the meantime. Thanks anyway!

**Pull request closed without merging**
