### PR TITLE
Rename ct-form-layout to ct-form

### PR DESCRIPTION
**Pull request by garrett**
This is a simple regex across our codebase to change `ct-form-layout` to `ct-form`.

We talked about it in our team meeting around two weeks ago and agreed it made sense to rename it. So... here's the PR. :wink:

### CODE REVIEW

**Comment by martinpitt** [comment]
A lot of the tests fail now, so something went wrong here. Some of them refer to the form layout, so your sed also needs to be applied to these:
```
test/verify/check-machines-dbus:        b.wait_in_text("div.modal-dialog div.modal-body div.ct-form-layout", "Its content will not be deleted.")
test/verify/check-storage-multipath:            return '#detail-header div.ct-form-layout label:nth-of-type(%s)' % index
test/verify/check-storage-multipath:            return '#detail-header div.ct-form-layout label:nth-of-type(%s) + div' % index
test/verify/check-storage-vdo:            return '#detail-header div.ct-form-layout label:nth-of-type(%s) + div' % index
test/verify/storagelib.py:            cell = tab + " div.ct-form-layout label:contains(%s) + *" % title
test/verify/storagelib.py:        return tab + " div.ct-form-layout label:contains(%s)" % title
```

**Comment by garrett** [comment]
@martinpitt: Oh drat. Right. I'll apply the fix and force-push back here in a jiffy or two. (Waiting for another branch to finish compiling so I can test it, then switch back, fix this, then switch back again.)

**Comment by garrett** [comment]
Now includes tests. Also: rebased on master.

**Comment by garrett** [comment]
Reworded. Added closes to this PR and fixes #11966.

**Pull request merged**
