### PR TITLE
machines: Fix lost of configuration changes made before installation

### PR DESCRIPTION
**Pull request by skobyda**
If user tries to configure memory params, vcpus, bootorder, autostart
or vNICs param before installing VM, they would loose changes after
installation.
The reason is that we pass all the important VM's settings to
virt-install script. We were not passing all of the mentioned options,
virt-install would default them.
    
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1780449

### CODE REVIEW

**Comment by martinpitt** [comment]
Looks good in general, thanks! However, the new test case fails everywhere.

**Comment by martinpitt** [comment]
Also, can you please fix the typo in the commit message? It's "loss", not "lost"

**Comment by skobyda** [comment]
@KKoukiou 
I cannot reproduce your vNIC bootorder bug. Can you show me your bootorder configuration before and after you alter it?
It's true that for redirected devices a bootorder option will be lost, since we do not pass redirected devices to installation script.

Also, for --memory I pass option `--memory memory=$currentMemory maxmemory=$memory`, where $currentMemory is from `vm.currentMemory` and memory is from `vm.memory`
from virt-install man page for --memory option: `The memory parameter is mapped to <currentMemory> element, the 'maxmemory' sub-option is mapped to <memory> element`.

**Comment by KKoukiou** [comment]
> @KKoukiou
> I cannot reproduce your vNIC bootorder bug. Can you show me your bootorder configuration before and after you alter it?
> It's true that for redirected devices a bootorder option will be lost, since we do not pass redirected devices to installation script.

Ah, ok. Maybe that was what I noticed. I didn't manage to reproduce again any problem without redirected devices.
> 
> Also, for --memory I pass option `--memory memory=$currentMemory maxmemory=$memory`, where $currentMemory is from `vm.currentMemory` and memory is from `vm.memory`
> from virt-install man page for --memory option: `The memory parameter is mapped to <currentMemory> element, the 'maxmemory' sub-option is mapped to <memory> element`.

You are right - I checked also `ps aux | grep virt-install` output and the options are correct. I was misled because for some reason when the VM is installing the currentMemory and memory options in the (! non inactive) XML  are both equal to memory value, regardless what currentMemory is. Inactive XML is correct so after installation the memory values are again correct. I am not sure why this behavior exists but it's definitely not an issue of this PR.

**Comment by KKoukiou** [comment]
@skobyda there is [one failure on the new test](https://209.132.184.41:8493/logs/pull-13312-20200108-094848-43bdd2fb-cockpit-project-cockpit--rhel-8-1-distropkg/TestMachinesDBus-testConfigureBeforeInstall-rhel-8-1-distropkg-127.0.0.2-2401-FAIL.png) - retrigerring

**Pull request merged**
