### PR TITLE
test: Pull cockpit/ws docker image when setting up the Atomics

### PR DESCRIPTION
**Pull request by mvollmer**
This was accidentally dropped by c4c528b.

### CODE REVIEW

**Comment by mvollmer** [comment]
Image is in the making.

**Comment by mvollmer** [comment]
> Image is in the making.

Made.

**Comment by dperpeet** [comment]
> This was accidentally dropped by c4c528b.

oops :)

**Comment by dperpeet** [comment]
Note: this only requires a fedora atomic image because rhel-atomic hasn't been remade since that change.

**Comment by dperpeet** [comment]
@mvollmer fedora-atomic has testing failures

**Comment by mvollmer** [comment]
> @mvollmer fedora-atomic has testing failures

Yes, that image was somehow broken, I think.

**Comment by mvollmer** [comment]
>> @mvollmer fedora-atomic has testing failures

> Yes, that image was somehow broken, I think.

I made a new one.  No idea what went wrong.

**Comment by mvollmer** [comment]
debian-unstable has trouble, but it is very likely unrelated to the fedora-atomic image update.

**Pull request closed without merging**
