### PR TITLE
[rhel-8] test: Drop obsolete compat test cases for RHEL/CentOS 7, adjust for TEST_OS_DEFAULT moving to F40

### PR DESCRIPTION
**Pull request by martinpitt**
On June 30, CentOS 7 is EOL and RHEL 7 reaches end-of-maintenance [1]. We haven't changed anything on our rhel-7.9 branch in years, we can put these images to rest.

This also means that we can stop supporting the old "implicit superuser" backwards compatibility, as all supported OSes now use the explicit dialog. Drop the various TestSuperuserOld* tests.

Also drop TestCentos7 -- we already have a TestRHEL8 for testing connectivity to the C bridge.

Drop the `wait_popdown()` testlib API. It's not being used anywhere any more, so vulture complains. External projects don't use it either, and it's too trivial to keep around.

[1] https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux/rhel-7-end-of-maintenance

Cherry-picked from main commit 78ca8545902252f

----

Blocks https://github.com/cockpit-project/bots/pull/6311

### CODE REVIEW

**Comment by martinpitt** [comment]
The [kdump regression](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20393-ce5a48c1-20240429-043528-rhel-8-10-distropkg-storage/log.html) is currently being investigated in https://github.com/cockpit-project/bots/pull/6262 . This seems to be some change in our CI.

**Comment by martinpitt** [comment]
But [this on the other hand](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20393-ce5a48c1-20240429-043527-rhel-8-10-other/log.html#82-2) is new -- it happens in https://github.com/cockpit-project/bots/pull/6311 but how did it break? it still passed in the previous refresh in https://github.com/cockpit-project/bots/pull/6255.

Well, *shrug*, I'll adjust the tests.

**Comment by martinpitt** [comment]
Ah, I know! This is due to the change of TEST_OS_DEFAULT to F40.

**Comment by jelly** [comment]
CI is still unhappy :( I fear this requires some debugging on my side.

**Review by jelly — APPROVED** [review]

**Pull request merged**
