### PR TITLE
tests: Increase timeout in check-sosreport

### PR DESCRIPTION
**Pull request by Gundersanne**
This test keeps running into the timeout on rhel-atomic.

See cockpit-project/bots#1271

### CODE REVIEW

**Comment by Gundersanne** [comment]
I'm not sure if this should go in as it isn't needed on master. I thought that maybe any backport we make for stabilized branches should also be visible in master.

**Comment by marusak** [comment]
Thanks @Gundersanne, I am back after a few days off and I am still going through all email so I am not familiarzed with everything that happened in the meantime. Therefore I have a few questions and this PR seems like a good place to ask them :) 

1. You are mentioning this is a backport (is there something like forwardport? :wondering:). Can you point to the PR that landed it in a stable branch?
2. No tests ran. I saw some comments like "force pushing to run tests" on other PRs. Is/was there some issue with our CI (webhook) or github outage?

**Comment by Gundersanne** [comment]
> Thanks @Gundersanne, I am back after a few days off and I am still going through all email so I am not familiarzed with everything that happened in the meantime. Therefore I have a few questions and this PR seems like a good place to ask them :)
> 
>     1. You are mentioning this is a backport (is there something like forwardport? :wondering:). Can you point to the PR that landed it in a stable branch?

As the PRs for both the main and stable branches got made simultaneously I do think it's a Schrödinger's port. #14712 

> 
>     2. No tests ran. I saw some comments like "force pushing to run tests" on other PRs. Is/was there some issue with our CI (webhook) or github outage?

Nah, just the `no-test` label. I'll trigger the relevant test though.

**Comment by Gundersanne** [comment]
Oh wait actually since this is for the main branch i should just trigger them all and rhel-atomic is decidedly not one of the ones that I should run.

**Review by marusak — APPROVED** [review]

**Pull request merged**
