### PR TITLE
bots: Do not use '--no-bootstrap-chroot' for rhel-like systems

### LINKED ISSUE #12117: Image refresh for centos-7
Image refresh for centos-7
 * [ ] FAIL: image-refresh centos-7

### PR DESCRIPTION
**Pull request by marusak**
This was introduced in #12055 and it seems to break when older versions
of mock are used, such as in centos-7 (see #12117).

I don't know why this option was introduced, it seems bit like a copy-paste error from fedora.setup.
I try rebuilds to see if it is really necessary.

This should be able to create centos-7 and therefore fix #12117 and still work with rhel-8-(0/1). (note, rhel-8-0 (and 8-1 most like as well) is gonna fail, see https://github.com/cockpit-project/cockpit/issues/12110#issuecomment-504350579)

 * [ ] FAIL: image-refresh rhel-8-0
 * [x] image-refresh rhel-8-1
 * [x] image-refresh centos-7

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-12125-20190621-150606/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-12125-20190621-151010/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-12125-20190621-151010/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-11.
Log: https://209.132.184.41:8493/logs/image-refresh-12125-20190621-150707/

**Comment by KKoukiou** [comment]
@marusak do you mind if I cherry-pick the commit from https://github.com/cockpit-project/cockpit/pull/12128 here? So that we will do a single image-refresh?

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-12125-20190621-150707/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-03.
Log: https://209.132.184.41:8493/logs/image-refresh-12125-20190621-153737/

**Comment by cockpituous** [comment]
image-refresh rhel-8-1 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-1-20190621-160000

**Comment by cockpituous** [comment]
image-refresh in progress on 4-ci-srv-05.
Log: https://209.132.184.41:8493/logs/image-refresh-12125-20190621-155656/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20190621-163131

**Comment by cockpituous** [comment]
Failed to confirm the presence of all triggers: https://209.132.184.41:8493/logs/image-refresh-12125-20190621-155656/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-12125-20190621-213636/

**Comment by marusak** [comment]
@martinpitt rhel-8-0 is expected to fail (see the PR comment), no need to retrigger.

@KKoukiou the image refreshes are already done. I am going to open another PR (most likely tommorow morning) where is fix for this rhel-8-0. I'll pick your commits from  #12128 there and do image refreshes together.

**Comment by marusak** [comment]
I cherry-picked only centos-7, rhel-8* was just test if it is going to work. This effectively fixes #12117.

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-12125-20190621-213636/

**Comment by marusak** [comment]
The image is missing. @martinpitt is it fishable? It kinda makes sense that this image would not survive, if image prune is done with `--force`, since before I cherrypick it into this PR, it wasn't in any PR, therefore prunable. But if pruning is done without `--force`, then there is another problem somewhere, since it should be protected by those 14 days.

**Comment by martinpitt** [comment]
@marusak : Reuploaded. The problem is that the /cache/images volume on CentOS CI is full, there is something weird -- 39 GB files, but df claims they are using 187 GB. I need to send a ticket for that, I can't solve that from our end.

**Comment by mvollmer** [comment]
> I don't know why this option was introduced,

Originally, it was to workaround this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1447627

**Pull request merged**
