### PR TITLE
Image refresh for openshift - dupe of/fixed in #8414

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for openshift
 * [x] image-refresh openshift

### CODE REVIEW

**Comment by petervo** [comment]
There seems to be an issue with kubvirt on the refreshed image. Is this a space issue again?

@mareklibra or @jniederm can you take a look.

**Comment by mareklibra** [comment]
The `virt-api` pod is no more present, so this depends on: https://github.com/cockpit-project/cockpit/pull/8414

**Comment by mareklibra** [comment]
Regarding the 2nd issue with `testImagestreamImport`: the `registry:2` image is being pulled but missing at the end of openshift image creation.

**Comment by mareklibra** [comment]
the `registry:2` image has been updated 2 days ago, this might be related. Let's try to refresh the image once again.

**Comment by mareklibra** [comment]
WIP in #8414

**Comment by martinpitt** [comment]
Looks like this gets fixed in #8414. Don't  close this yet, as otherwise the bots will just open a new one. I adjusted the title accordingly.

**Comment by martinpitt** [comment]
#8414 landed, closing.

**Pull request closed without merging**
