### PR TITLE
shell: Strict CSP for the shell

### PR DESCRIPTION
**Pull request by stefwalter**
Strictly enforce Content-Security-Policy in the shell component. This is a bit more complex than some of the other migrations, since some of the code needs to run very early in the load process and synchronously before loading other iframes, etc.

### CODE REVIEW

**Comment by stefwalter** [comment]
Blocked on #4276

**Comment by petervo** [comment]
Needs rebase

**Comment by stefwalter** [comment]
Rebased.

**Comment by petervo** [comment]
Was not changing the manifest here intentional?

**Comment by stefwalter** [comment]
Marking priority so we can get CSP done for this release.

**Pull request closed without merging**
