### PR TITLE
systemd: Always use reportd on the system bus

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by martinpitt** [comment]
Marking as no-test for the next round. I still see that failing, e.g. [run from yesterday](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18188-20230117-124433-a4f6fc85-fedora-37-pybridge/log.html#270)

**Comment by mvollmer** [comment]
> Yep, [failed here as well](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18199-20230118-105943-411e1ea2-fedora-37-pybridge/log.html#328).

Right, now I can reproduce it locally as well... must have made a mistake the last time.  (Well, at least something fails, but there are too many duplicated warnings from React to make sense of the output... :-)

**Comment by martinpitt** [comment]
@mvollmer My #1 reason is to forget `--python` in the image-prepare call :grin:

**Review by martinpitt — APPROVED** [review]
Ugh, "how did that ever work before"... Thanks!

**Comment by martinpitt** [comment]
Hang on..

    # test/verify/check-system-journal:21:1: F401 'testlib.todoPybridge' imported but unused

I also dropped the no-test label, the next round should run everywhere.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
