### PR TITLE
Image refresh for rhel-8-1

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-1
 * [x] image-refresh rhel-8-1

### CODE REVIEW

**Comment by martinpitt** [comment]
[several flakes](https://209.132.184.41:8493/logs/pull-11655-20190424-042424-10df0b35-verify-rhel-8-1/log.html#86), retrying

**Comment by marusak** [comment]
`testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus)` failed again and from [screenshot](https://209.132.184.41:8493/logs/pull-11655-20190424-052323-10df0b35-verify-rhel-8-1/TestMachinesDBus-testStoragePoolsCreate-rhel-8-1-127.0.0.2-2201-FAIL.png) it looks familiar. It need naughty from #11614 for rhel-8-1 as well. I'll put it here and comment on BZ that it affects rhel-8-1 as well.

**Comment by martinpitt** [comment]
[resize test failure](https://209.132.184.41:8493/logs/pull-11655-20190424-073434-f721d331-verify-rhel-8-1/log.html#250), retrying for comparison

**Comment by marusak** [comment]
[resize failed again along with some other tests](https://209.132.184.41:8493/logs/pull-11655-20190424-110909-f721d331-verify-rhel-8-1/log.html) so one more retry

**Pull request merged**
