### PR TITLE
Fix and validate AppStream metadata

### PR DESCRIPTION
**Pull request by martinpitt**
- Add missing `<?xml>` headers.
- Add missing `<url>` and `<update_contact>` tags.
- Add missing category to cockpit.appdata.xml
- Update extension IDs to not contain hyphens (§2.1.3)
- Remove line breaks from summaries
- Update `<update_contact>` for cockpit to the mailing list.
- Validate all shipped metadata during distcheck. (Don't yet do it in
  cockpit.spec as our VM images lack libappstream-utils in their mocks)

### CODE REVIEW

**Comment by martinpitt** [comment]
Note: Not all issues get picked up by `appstream-util validate`; Debian's scanner also shows a few:  https://appstream.debian.org/sid/main/issues/cockpit-machines.html and https://appstream.debian.org/sid/main/issues/cockpit.html

**Comment by martinpitt** [comment]
Without the metadata fixes, the new validation fails like this in distcheck:

```
cockpit-190.x/pkg/kdump/org.cockpit-project.cockpit-kdump.metainfo.xml: FAILED:
• tag-missing           : <update_contact> is not present
• markup-invalid        : <?xml> header not found
• tag-missing           : <url> is not present
cockpit-190.x/pkg/machines/org.cockpit-project.cockpit-machines.metainfo.xml: FAILED:
• tag-missing           : <update_contact> is not present
• markup-invalid        : <?xml> header not found
• tag-missing           : <url> is not present
cockpit-190.x/pkg/selinux/org.cockpit-project.cockpit-selinux.metainfo.xml: FAILED:
• tag-missing           : <update_contact> is not present
• markup-invalid        : <?xml> header not found
• tag-missing           : <url> is not present
cockpit-190.x/pkg/sosreport/org.cockpit-project.cockpit-sosreport.metainfo.xml: FAILED:
• tag-missing           : <update_contact> is not present
• markup-invalid        : <?xml> header not found
• tag-missing           : <url> is not present
Validation of files failed
make[1]: *** [Makefile:9646: distcheck-hook] Error 123
```

**Comment by martinpitt** [comment]
Needs appstream-util in the unit-tests container.

**Comment by martinpitt** [comment]
Container update committed and pushed.

**Comment by mvollmer** [comment]
This error from Debian might be the culprit: "The component is a GUI web application, but it either has no icon set in its metainfo file, or we could not find a matching icon for this application."

If the Fedora machinery behaves the same and excludes cockpit.desktop from its collection data, then all our other "apps" will likely be excluded as well, since they reference cockpit.desktop in their `extends` tag.

**Comment by martinpitt** [comment]
@mvollmer: I didn't update the icon yet indeed. But that's just a warning, and (hopefully) not a reason to not export the data at all in appstream-data?

**Pull request merged**
