### PR TITLE
amplify testSudo flake

### PR DESCRIPTION
**Pull request by jelly**
https://cockpit-logs.us-east-1.linodeobjects.com/pull-19308-20230913-142519-facee1fc-fedora-coreos-other/log.html#60
https://cockpit-logs.us-east-1.linodeobjects.com/pull-19318-20230913-133009-d662e758-fedora-coreos-other/log.html
https://cockpit-logs.us-east-1.linodeobjects.com/pull-19304-20230911-105855-919cc0ba-rhel4edge-other/log.html#53-2

### CODE REVIEW

**Comment by jelly** [comment]
@allisonkarlitskaya wew, this reproduces quite a lot. We have debug logs of the bridge now in the journal.

**Comment by martinpitt** [comment]
Recent case: https://cockpit-logs.us-east-1.linodeobjects.com/pull-19391-20230926-053034-8ec5062e-rhel4edge-other/log.html#59-2

**Comment by martinpitt** [comment]
This is our top flake ATM:

image

Current examples:
 - https://cockpit-logs.us-east-1.linodeobjects.com/pull-19458-20231009-162534-6a7d8502-fedora-coreos-other/log.html
 - https://cockpit-logs.us-east-1.linodeobjects.com/pull-19451-20231006-052502-3a9f5732-fedora-coreos-other/log.html
 - https://cockpit-logs.us-east-1.linodeobjects.com/pull-19453-20231006-205126-07a38066-rhel4edge-other/log.html
 - https://cockpit-logs.us-east-1.linodeobjects.com/pull-19449-20231006-051706-da7314c0-rhel4edge-other/log.html

**Comment by martinpitt** [comment]
@allisonkarlitskaya says that this will completely change with her ongoing work to use the current FernyTransport API in cockpit and unify the implementation of our SSH and sudo channels. Let's put this on the shelf and revisit when it still happens afterwards.

**Comment by martinpitt** [comment]
For the record: This flake [still happens](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19668-20231211-145412-3d568bf8-fedora-coreos-other/log.html#61) with @allisonkarlitskaya 's FernyTransport rewrite in PR #19668.

**Pull request closed without merging**
