### PR TITLE
Refresh f24

### PR DESCRIPTION
**Pull request by mvollmer**
Continuation of #4147

### CODE REVIEW

**Comment by stefwalter** [comment]
Do you think a known issue would be better? It seems that this prevents kubernetes from actually working.

**Comment by dperpeet** [comment]
> Do you think a known issue would be better? It seems that this prevents kubernetes from actually working.

I agree with stef on this - we shouldn't just ignore these messages. We need them to be a known issue to track them. They are a blocker on a release actually working.

**Comment by dperpeet** [comment]
added known issue #4270

**Comment by petervo** [comment]
replaced by #4269

**Pull request closed without merging**
