### PR TITLE
base1: Use IEC names for binary unit prefixes

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by stefwalter** [comment]
What does this do?

**Comment by mvollmer** [comment]
Right now we use "MB" for both 10^6 bytes and 2^20 bytes.

After this change, the storage UI will start talking in "MiB", "GiB", etc.  If we don't like this, we can go further with #3945, which changes the storage UI to talk in "MB", "GB", etc, by making it use decimal prefixes.

**Comment by mvollmer** [comment]
I quite strongly believe that the status quo is not acceptable.  We should merge either this or #3945.

**Comment by stefwalter** [comment]
FYI @vpodzime @julienlim @cmurf

**Comment by dperpeet** [comment]
I agree with @mvollmer on this. Either we use SI units or we don't, but using the same label for different numbers is just plain confusing.

**Comment by mvollmer** [comment]
@vpodzime @julienlim @cmurf, there are three choices:

 - Use binary prefixes in the UI, and say things like "2 GiB" for 2199023255552 bytes.
 - Use decimal prefixes in the UI, and say things like "2.2 GB" for  2199023255552 bytes.
 - Ignore SI and IEC and say things like "2 GB" for 2199023255552 bytes.

Which one shall it be?

**Comment by mvollmer** [comment]
My personal opinions about the choices:

> Use binary prefixes in the UI, and say things like "2 GiB" for 2199023255552 bytes.

This is viable, and the more we show the silly "GiB" units the more people will get used to them.

> Use decimal prefixes in the storage UI, and say things like "2.2 GB" for 2199023255552 bytes.

This is also viable and I think most common in the storage domain.  I prefer this.

> Ignore SI and IEC and say things like "2 GB" for 2199023255552 bytes.

Not viable and makes us look stupid.

**Comment by mvollmer** [comment]
I didn't yet catch all necessary places.

**Comment by mvollmer** [comment]
> I didn't yet catch all necessary places.

Done.

**Comment by dperpeet** [comment]
not yet all:
http://files.cockpit-project.org/logs/pull-3944-bf171a62-verify-fedora-23/log.html#12
```
 File "./verify/check-storage-used", line 76, in testUsed
     b.wait_in_text("#content", "50 MB Free Space")
```

**Comment by mvollmer** [comment]
> Either change it to 50 MiB Free Space 

Done.

**Comment by dperpeet** [comment]
it seems there is one more...
```
File "/tmp/avocado_tests/selenium-login.py", line 123, in test60ChangeTabStorage
    self.wait_text("1000 MB", element="td")
```

**Comment by cmurf** [comment]
My suggestion for cockpit going forward:

- Networking, use SI.
- Physical drives, report both SI/IEC or flip coin. Products still prominently use SI units but increasingly also include IEC units.
- Everything else (PV, VG, LV, pools, arrays, filesystem volumes), use IEC.


GUI behaviors:

- Windows 10 uses IEC values with SI unit labels.
- OS X 10.11 uses SI values and labels.
- Gnome uses neither, it starts with 1024-byte blocks (1KiB) but then to get larger units it uses base10, so it's a mix of both IEC and SI. Ick.

Fedora 23 behaviors^:

- parted > SI
- fdisk > IEC
- gdisk > IEC
- lvm tools > IEC
- mdadm > IEC
- btrfs > IEC
- df -h > IEC
- du -sh > IEC

^ Where IEC means it reports IEC values. But often the label is messed up; uses either SI unit labels, or a single letter M, G, T, or even lowercase m, g, t.

Summary: Messy. But trend appears to be moving toward IEC, so go ahead and use IEC. The SI unit label is ambiguous because it's misused; whereas IEC unit is generally trustworthy. Since consumption of storage is only in IEC units (minimum practical consumption size is 4096 bytes which is an IEC unit), it doesn't make much sense referring to whole devices or free space with SI units.

**Comment by vpodzime** [comment]
We switched to binary units in the Anaconda installer's UI with the UI rewrite and I still consider that a good decision. Thus I can only suggest the same for Cockpit.

**Comment by mvollmer** [comment]
> it seems there is one more...

Fixed.

**Comment by mvollmer** [comment]
> My suggestion for cockpit going forward:
>
>   Networking, use SI.
>    Physical drives, report both SI/IEC or flip coin. Products still prominently use SI units but increasingly also include IEC units.
>    Everything else (PV, VG, LV, pools, arrays, filesystem volumes), use IEC.

Thanks a lot!  We will go with IEC for storage (including memory) and SI for networking.
 
I will go over our code and make sure it is consistent.

**Comment by mvollmer** [comment]
> We switched to binary units in the Anaconda installer's UI with the UI rewrite and I still consider that a good decision. Thus I can only suggest the same for Cockpit.

Thanks for the input!

**Pull request closed without merging**
