### PR TITLE
Polish translations - Wip

### PR DESCRIPTION
**Pull request by Armstrong1992**
Work in progress of Polish translation.

### CODE REVIEW

**Comment by stefwalter** [comment]
@Armstrong1992  Should we merge this ... even if it's a partial translation?

**Comment by Armstrong1992** [comment]
@stefwalter It will be done in one week. This merge request is just to let know, that translation is in progress, so there is no need to make one. My mistake, wrong description.

**Comment by stefwalter** [comment]
No worries. Thanks for letting us know. Will set the needswork label. Let us know when it's ready to merge.

**Comment by Armstrong1992** [comment]
@stefwalter Ready to merge.

**Comment by stefwalter** [comment]
@Armstrong1992 Thanks. Will merge. Unfortunately not even half of the strings in Cockpit are marked properly as translatable.

**Comment by stefwalter** [comment]
Filed follow up issue #1983

**Pull request closed without merging**
