### PR TITLE
Enable going from journal box into full logs

### LINKED ISSUE #8271: [services] Visualizing more than 10 lines for services logs
Hallo,

I was having a look at Cockpit for giving some power users access to system journals and services restart over a webinterface, and it seems a really cool tool! On thing which is puzzling me atm is that only the latest 10 lines of the service journal are displayed: is there a way to configure a different default? I had a quick look at the code, and it seems that a `lines` parameter is passed to the `journal` function, but javascript is really not my strongest skill :) Any idea how to do this, either through a configuration parameter or hacking the code?

Thanks!

### PR DESCRIPTION
**Pull request by marusak**
Fixes #8271

This is in services details and in networking overview. I hope I haven't forgotten about some other logs.

No sure about what would be the best wording (I like 'go to' since it jumps to different page), location (maybe under the logs?) or if it should look like button or anchor (I picked button that is styled like anchor, because it goes somewhere so it should be anchor, but there is this problem that we don't know the url, so we need to do this in onClick handler) @andreasn WDYT?
alllogs

### CODE REVIEW

**Comment by marusak** [comment]
There are logs also in storage. How did I miss it?

**Comment by marusak** [comment]
> When I go to the logs, it says it's showing All services

Ach, good point! In the services select we show `SYSLOG_IDENTIFIER`, while here we need `_SYSTEMD_UNIT` (or possibly `UNIT`).

So currently the select looks like this:
current
And if we would show `_SYSTEMD_UNIT` it would look like this:
withnewthingy
A good example that shows the difference is for example this log:
systemdlog
`SYSLOG_IDENTIFIER` is `systemd`. So when you want to see this log in logs page, you need to pick `systemd` from the dropdown. However, you would see this log in services details for both `cockpit.service` and `init.scope` (yes I know we don't show .scope, but technically).

What should we show in the dropdown? 
1. Should it be identifier as it is now? (identifier is something that you can pick when you log into journal. There is no restriction. Example:
`echo 'I logged this' | systemd-cat -t MyIdentifier -p emerg`
myidentifier
Of course, you can also omit `-t` and not having any identifier. Also mind you, there is no `_SYSTEMD_UNIT` (these cannot be faked, you need to create service that would log it).
2. Should it be really `_SYSTEMD_UNIT`  which would match `Service` label much better?
3. Should we show both of them in the dropdown and then match by `identifier=<selected> or systemd_unit=<selected>`?
4. Should we have two dropdown? One for service and one for identifier? And then do (if selected) `identifier=<identifier_selected> and systemd_unit=<unit_selected>`?

**Comment by marusak** [comment]
@andreasn so I implemented filtering by both identifier and service as we talked about.
There may be some rough edges since I haven't tested it that much, some things are not tested, most likely I broke some tests, I introduced another custom dropdown, some functions and variables don't have confusing names... but I think it is good to show how this works :)
Can you please try it and let me know if this approach makes sense? Now when you go from some service into logs, you should be able to get to full logs easily.
bothselectors

**Comment by marusak** [comment]
So this got a bit more complicated. Storage shows logs from more services - that means we would need enable filtering by more services - thus not using select but [multi select]( https://www.patternfly.org/v4/documentation/react/components/select/#checkbox-select-input). That would be possible, but I would prefer to use PF4 component - which would mean rewriting log filtering into react.

Another option I though of would be not to introduce filtering by service at all but just enable passing string for matching in url (such string is something like `_SYSTEMD_UNIT="cockpit.service"`) and then show somewhere button to clear this filter. This would solve any possible problems, since every log uses something different (storage filters by 5 services, networking by one service but also checks `UNIT` and `COREDUMP_UNIT`). A usability problem is that user would not see anywhere in the UI what is being filtered. @andreasn WDYT?

**Comment by mvollmer** [comment]
> I hope I haven't forgotten about some other logs.

Storage.

**Comment by marusak** [comment]
Obsoleted by https://github.com/cockpit-project/cockpit/pull/13905

**Pull request closed without merging**
