### PR TITLE
Image refresh for rhel-atomic

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for rhel-atomic in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-atomic-2017-01-30/

### CODE REVIEW

**Comment by petervo** [comment]
#5798 needs to be merged for this to work

**Comment by dperpeet** [comment]
> #5798 needs to be merged for this to work

done

**Comment by martinpitt** [comment]
Hmm, I've re-run this several times, and `testDevmapper (check_docker_storage.TestDockerStorage)` failed several times in a row. Might be coincidence, but I'd rather not merge that just yet without further investigation.

**Comment by petervo** [comment]
@martinpitt that's probably this, https://github.com/cockpit-project/cockpit/blob/master/test/verify/naughty-fedora-atomic/5750-atomic-storage-reset-regressed. We generally don't do naughty files for this one, so if you agree that's the failure this is probably good to go in.

**Comment by martinpitt** [comment]
Yes, it's the same failure, except on rhel instead of fedora atomic. So if there's a policy to not do naughty overrides for rhel, and this is not a regression, I of course don't object to landing this -- I just wanted to avoid breaking CI for all PRs due to some behaviour change.

**Comment by petervo** [comment]
You're right, I thought it was continuous-atomic for some reason, in that can the naught file should be copied to https://github.com/cockpit-project/cockpit/tree/master/test/verify/naughty-rhel-atomic then this should be good to go.

**Comment by martinpitt** [comment]
I pushed a copy of that known issue on top of this branch, now let's wait for the CI verdict.

**Comment by martinpitt** [comment]
Force-pushed again. I typoed the commit message (RHEL-7 is not the same as rhel-atomic), and I also added the quirk for continuous-atomic to unblock PR #5820.

**Comment by dperpeet** [comment]
Hm, originally we didn't want to add naughty issues to continuous-atomic. But considering this is a shared issue, I think I'm ok with it.

**Comment by stefwalter** [comment]
> Hm, originally we didn't want to add naughty issues to continuous-atomic. But considering this is a shared issue, I think I'm ok with it.

We should think about this again. It's become tedious each time to go through and manually check that all the problems are known issues in another image.

**Pull request merged**
