### PR TITLE
kubernetes v1 api support

### PR DESCRIPTION
**Pull request by sub-mod**
Support kubernetes v1 api

### CODE REVIEW

**Comment by sub-mod** [comment]
@petervo kindly review

**Comment by petervo** [comment]
You need to change the integration tests as well.

**Comment by petervo** [comment]
Also we need to know what the newest package that supports this api is and update tools/cockpit.spec as well.

**Comment by stefwalter** [comment]
@sub-mod Can you work with @dperpeet to get the integration tests running on your machine ... he should be available during your time zone. That'll help you get unblocked here.

**Comment by petervo** [comment]
portalIP is still used in the kubernetesAddress directive in dashboard.js.
The readme needs to be updated to refer to v1 instead of v1beta3

**Comment by petervo** [comment]
I've tested this with version 0.20. And it works, @sub-mod  was suggesting we hold off until 1.0 lands in fedora and then update the spec and file merge.

**Comment by stefwalter** [comment]
kubernetes package version 1.0 is not the first release with the v1 API. I think we can merge this before 1.0 lands in Fedora since 0.20 and other versions support the v1 API.

**Comment by sub-mod** [comment]
@stefwalter ok np. that sounds good.

**Comment by ibotty** [comment]
And besides, kubernetes-1 already landed.

**Comment by stefwalter** [comment]
Merged into git master.

**Pull request closed without merging**
