### PR TITLE
build: Switch to @xterm/xterm and @xterm/addon-canvas

### PR DESCRIPTION
**Pull request by mvollmer**
These are the new names, and they have more recent releases.

### CODE REVIEW

**Comment by martinpitt** [comment]
Please adjust .github/dependabot.yml pattern as well. Thanks!

**Comment by mvollmer** [comment]
> Please adjust .github/dependabot.yml pattern as well. Thanks!

Ah, didn't know about that, thanks!

**Comment by mvollmer** [comment]
This will cause some disturbance when external projects update their pkg/lib, so I guess I trigger that explicitly once this has landed.

**Review by martinpitt — APPROVED** [review]
Nice that this goes straight through!

**Pull request merged**
