### PR TITLE
login: Restyle login page to look like PatternFly 4

### PR DESCRIPTION
**Pull request by garrett**
Related to #11987

### CODE REVIEW

**Comment by garrett** [comment]
I've included the RH font commit from #11987. Once that PR lands, we'll rebase this on master and that commit should fall out from this PR.

I'm not done yet, but wanted to share my efforts on this early. Things will change.

All the style changes are isolated in CSS `@supports`, except for bumping up the base font size to browser default (which is 16px by default in most browsers).

To see the PF4 style, browsers need to support:
- `@supports`
- CSS grid
- CSS variables

If browsers do not support all three features, they will get the current look and feel. The only major browsers that are not included in the above are:

1. Internet Explorer
2. Very old versions of other browsers

I intentionally decided to handle the reskinning of the login page using this method of progressive enhancement, so that we can handle the error messages that we have already put into place and also to not break any of the features of the login page.

We should _eventually_ redo the main login page, but I think this works for now. :wink:

**Comment by garrett** [comment]
- [PF4 login design guideline](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/login)
- [PF4 login documentation](https://www.patternfly.org/v4/documentation/react/components/loginpage/
)
- [PF4 example login page](https://www.patternfly.org/v4/documentation/react/components/loginpage/simpleloginpage/)

**Comment by garrett** [comment]
The login page is special. It doesn't refresh like the rest of Cockpit.

To test, run the following command, which will replace your system-installed Cockpit login page:

```sh
make && sudo cp dist/static/login.min.* /usr/share/cockpit/static/ && sudo systemctl restart cockpit.socket
```

...and then reload your browser page.

(The above command will not work on Silverblue systems.)

**Comment by martinpitt** [comment]
"The PR" landed now, so this can now be rebased. Thanks!

**Comment by martinpitt** [comment]
FTR, you can test the login page, or any cockpit-ws static file from the build tree without modifying /usr:
```
mkdir dist/static/fonts
sudo mount -o bind dist/static/ /usr/share/cockpit/static/
sudo mount -o bind dist/fonts/ /usr/share/cockpit/static/fonts/
sudo systemctl stop cockpit.service
```

**Comment by martinpitt** [comment]
Screenshot FTR:

login

I find this contrast to be way too intense on the eyes. Could we lighten up the background a bit? Or is this some official PF4 design?

**Comment by garrett** [comment]
What's the contrast issue? White box on a black background?

This is the official PF4 design. See the links above.

Also, your background is not correct. Perhaps if you see it with the correct background, it won't look as contrasty.

Screenshot_2019-07-02 sunny(1)

**Comment by martinpitt** [comment]
Indeed, I fixed up the "local test" instructions above, I see it now. That looks much better indeed!

**Comment by martinpitt** [comment]
I triggered a test yesterday, and it [has some failures](https://209.132.184.41:8493/logs/pull-12196-20190702-211010-1d0d9681-verify-fedora-30/log.html); they look unrelated though, retriggering.

**Comment by garrett** [comment]
I'll merge commits and add a closes # too... then I think it'll be ready to land, unless people say otherwise. :wink:

**Comment by martinpitt** [comment]
@garrett: We could do that on landing, but let's push anyway to trigger all the tests. Thanks!

**Comment by garrett** [comment]
There's a bug in Edge where the button doesn't have its own row and expand.

I'll fix that and do the squashing.

**Comment by garrett** [comment]
@martinpitt: I was thinking about squashing this down to 2 commits; the csso optimization one (as it changes a lot and could _theoretically_ introduce bugs...) and the PF4 styling.

If they were one commit, it looks like I rewrote the whole file and it's not clear what is PF4-specific styling.

**Comment by andreasn** [comment]
Looks good in general to me!
Doesn't the alerts usually [look more like this](https://www.patternfly.org/v4/documentation/react/components/alert/#danger-alert)? Or is that another kind of element?
Still getting familiar with PF4

**Comment by martinpitt** [comment]
@andreasn: Which alerts do you mean, failed login attempts? I'm not sure that they should be popups. But IMHO this can be tweaked (if necessary) in a follow-up IMHO.

**Comment by garrett** [comment]
Yeah, they're not popups. I tried the PF4 version, but it looked wrong, so I left it as-is. Agreed; we can address it in a follow-up.

**Pull request merged**
