### PR TITLE
Make this work (again)

### PR DESCRIPTION
**Pull request by mbalmer**
Include jquery.js, since jQuery syntax is being used on display.html.
Encrypt the websocket connection, since cockpit is access over an encrypted https connection.  Modern browser don't allow unencrypted websocket connections when the page was loaded using https.

With both changes applied, the VNC viewer works like a charm.

### CODE REVIEW

**Comment by dperpeet** [comment]
Some of the included files don't have copyright info or an attribution... Where are they from? Should we include them differently?

**Comment by stefwalter** [comment]
> Some of the included files don't have copyright info or an attribution... Where are they from? Should we include them differently?

LICENSE.txt is included.

**Comment by stefwalter** [comment]
Thanks @mbalmer 

Finished this work, squashed, rebased and made sure it runs without javascript errors. See pull request #5087

**Comment by dperpeet** [comment]
closed in #5087

**Comment by dperpeet** [comment]
@mbalmer thanks for your work on this!

**Pull request closed without merging**
