### PR TITLE
test: Centralize test decorator for distropkg

### PR DESCRIPTION
**Pull request by martinpitt**
It is annoying and noisy having to bump the same thing in umpteen tests
each time we add or drop a new -distropkg image. Introduce a new
@skipDistroPackage decorator and use that everywhere.

### CODE REVIEW

**Comment by martinpitt** [comment]
FTR, if anyone knows how to make this a non-functional decorator (`@skipDistroPackage` instead of `skipDistroPackage()`), please tell me. I've tried for half an hour, and I am just too stupid for it... It works just fine for the "run" case, but the "skip" one always fails with `TypeError: decorator() missing 1 required positional argument: 'test_item'` deep in unittest's loader.

**Comment by marusak** [comment]
> if anyone knows how to make this a non-functional decorator (@skipDistroPackage instead of skipDistroPackage()), please tell me

hmm, not me. I've tried as well and does not work what I though that should. But this is completely fine so no need to dwell on that.

**Comment by marusak** [comment]
I've triggered `rhel-8-5-distropkg` so that we actually run some distropkg context to verify this.

**Review by marusak — APPROVED** [review]
Thanks!
Please lets make sure distropkg context works. Also would be nice if we would test this in test/verify/check-testlib

**Comment by martinpitt** [comment]
@marusak : Oops, thanks for triggering the test -- indeed it seems I sent this before the bots PR landed which enabled them by default.

**Pull request merged**
