### PR TITLE
debian: add systemd as a build dependency

### PR DESCRIPTION
**Pull request by stefwalter**
And Update the image and fix various bugs.

Replaces #4811

### CODE REVIEW

**Comment by dperpeet** [comment]
did that last commit sneak in from #4846 or is it on purpose?

**Comment by stefwalter** [comment]
Must have snuck in. I'm not against these being merged together though.

**Comment by stefwalter** [comment]
SSH keys still failing.

**Comment by stefwalter** [comment]
That should fix ssh keys

**Comment by stefwalter** [comment]
```
+ LC_ALL=C timedatectl
      Local time: Thu 2016-08-11 10:00:08 EEST
  Universal time: Thu 2016-08-11 07:00:08 UTC
        RTC time: Fri 2020-01-24 06:03:00
       Time zone: Europe/Helsinki (EEST, +0300)
 Network time on: no
NTP synchronized: no
 RTC in local TZ: no
+ LC_ALL=C date
Thu Aug 11 10:00:08 EEST 2016
-> show('TestSystemInfo-testTime-FAIL.png')
Wrote TestSystemInfo-testTime-FAIL.png
<- None
+ journalctl
Journal extracted to TestSystemInfo-testTime-10.111.123.219-FAIL.log
Traceback (most recent call last):
  File "./check-system-info", line 216, in testTime
    self.assertIn("Fri Jan 24 08:03:", m.execute("LC_ALL=C date"))
AssertionError: 'Fri Jan 24 08:03:' not found in 'Thu Aug 11 10:00:08 EEST 2016\n'
```

**Comment by stefwalter** [comment]
That last commit should fix the ntpd related testing issues on debian.

**Comment by dperpeet** [comment]
`test: Remove SELinux systemd-nologin workaround ` already got merged via https://github.com/cockpit-project/cockpit/pull/4846

**Pull request closed without merging**
