### PR TITLE
Image refresh for fedora-30

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-30
 * [x] image-refresh fedora-30

### CODE REVIEW

**Comment by martinpitt** [comment]
Rebased to  current master for the bots → test move.

**Comment by marusak** [comment]
This image cannot be found on the main server. I force pushed to stop tests retrying. Can you @martinpitt copy this image or we need to create a new image refresh?

btw. I've noticed that once a test failed, it was picked up again. Is this a new behavior?

**Comment by martinpitt** [comment]
I reuploaded the fedora-30 image from ci-srv-03 (where it was built according to the log). We currently have an annoying bug that something cleans up images from PRs like this on the official image server :-(

@marusak: We don't normally retry failed tests, maybe it was because it failed much ealier? I've seen at least 4 parallel failures today (sink ssh stopped working, tests-invoke failure due to outdated branches, missing images, missing AMQP credentials on cockpit-9). Slowly crawling out of this hole.. :-)

**Comment by martinpitt** [comment]
Image reuploaded.

**Pull request merged**
