### PR TITLE
system: Improve terminal toolbar on mobile

### PR DESCRIPTION
**Pull request by mvollmer**
The existing test ignores almost everything and is thus not very
useful.  The ".xterm-cursor-layer" is probably intended to catch the
cursor only, but does in fact covers the whole terminal area.

Also, the exact scrollbar position seems to vary, which has started to
cause random failures.

Thus, let's test the header and actual text area (without scrollbar)
separately.

### CODE REVIEW

**Comment by mvollmer** [comment]
New reference images: https://github.com/cockpit-project/pixel-test-reference/compare/dba18567f57691d3e0e4db3f3c1d5789f7a7853c..befb7a1dfeefa8d781328fba6ac2144633b0a006

**Comment by marusak** [comment]
This is probably one of the places where we should notice that the screenshot looks bad and fix it before we commit to testing it? :) (mobile header)

**Comment by mvollmer** [comment]
> This is probably one of the places where we should notice that the screenshot looks bad and fix it before we commit to testing it? :) (mobile header)

No objections :-)

**Comment by marusak** [comment]
> Group terminal toolbar items

And also maybe space between lines when it wraps?

**Comment by mvollmer** [comment]
> > Group terminal toolbar items
> 
> And also maybe space between lines when it wraps?

That would be a Patternfly bug, I guess: https://www.patternfly.org/v4/components/toolbar

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
