### PR TITLE
docker: Add appstream

### LINKED ISSUE #13416: Add AppStream data to cockpit-docker
Cockpit version: 202.1
OS: Ubuntu 19.10
Page: Applications

When installing the plugin 'cockpit-docker' the plugin doesn't show up under the 'Applications' tab in the webinterface. Even after clicking the refresh button the plugin does NOT appear in the list.
However the plugin DOES show up 'Docker Containers' in the upper list.

Steps to reproduce:
1. apt install cockpit-docker docker-compose
2. Go to Webinterface 'Applications'
3. Refresh the listed applications

I hope this is the right place to post this issue. If not please tell me, I am new to GitHub.

### PR DESCRIPTION
**Pull request by leomoty**
Tested locally by adding the file to `usr/share/metainfo/org.cockpit-project.cockpit-docker.metainfo.xml`

Fixes #13416.

### CODE REVIEW

**Comment by leomoty** [comment]
Should `<name>` be a single word?

**Comment by leomoty** [comment]
I'll take a look soon and report back.

**Comment by leomoty** [comment]
@martinpitt PTAL

**Comment by martinpitt** [comment]
Thanks, LGTM now! Triggering tests.

**Comment by leomoty** [comment]
Clearly broken:

```
DEBUG: RPM build errors:
DEBUG: error: Installed (but unpackaged) file(s) found:
DEBUG:    /usr/share/metainfo/org.cockpit-project.cockpit-docker.metainfo.xml
DEBUG:     Macro expanded in comment on line 22: %{centos} explicitly
DEBUG:     Installed (but unpackaged) file(s) found:
DEBUG:    /usr/share/metainfo/org.cockpit-project.cockpit-docker.metainfo.xml
DEBUG: Child return code was: 1
```

@martinpitt, help? :)

**Comment by martinpitt** [comment]
@leomoty : Ah, that's because the `%package cockpit-docker` is guarded by `%if 0%{?fedora}`, so on RHEL/CentOS you wouldn't build that package and the .metainfo is a leftover. The file needs to be removed in line 212 and 216.

At that point it's probably cleaner to factor out the "if [archlist]" and "if fedora" into a conditional `%define build_docker`, which simplifies the .spec and adjustments to it. If you don't want to touch that, then I'm happy to clean this up in a follow-up, though.

**Comment by leomoty** [comment]
@martinpitt If you show me how to build the packages, I can give it a try. Worst case scenario i'll just rm the file as you suggested.

**Comment by martinpitt** [comment]
@leomoty : you can test with `test/image-prepare -vB centos-8-stream` for example. Or run `tools/make-srpm` and build with mock or other tool of your choice.

**Comment by leomoty** [comment]
@martinpitt : This is what you mean right?

```
%ifarch x86_64 %{arm} aarch64 ppc64le i686 s390x
%if 0%{?fedora}
%define build_docker 1
%endif
%endif

%if 0%{?build_docker}
echo '%dir %{_datadir}/cockpit/docker' > docker.list
find %{buildroot}%{_datadir}/cockpit/docker -type f >> docker.list
%else
rm -rf %{buildroot}/%{_datadir}/cockpit/docker
rm -f %{buildroot}/%{_prefix}/share/metainfo/org.cockpit-project.cockpit-docker.metainfo.xml
touch docker.list
%endif
```

Can also simplify the condition in line 631-632.

I'll test when I get home and then update the PR.

**Comment by martinpitt** [comment]
@leomoty : Right. Note that `build_optional 0` shoudl also disable build_docker.

**Comment by leomoty** [comment]
@martinpitt: but that should only be true in the 631 check, right? Since this first portion runs regardless.

**Comment by leomoty** [comment]
@martinpitt: my point is, it is already guarded by a build_optional check from line 542 that closes in 661

**Comment by martinpitt** [comment]
@leomoty : Right, the `build_optional` guards the `%package cockpit-docker`, but it also needs to guard the definition of `build_docker 1` so that you correctly remove the .metainfo when optional is not built.

**Comment by leomoty** [comment]
@martinpitt: okay, makes sense, so this should be:

```
%ifarch x86_64 %{arm} aarch64 ppc64le i686 s390x
%if 0%{?fedora} && 0%{?build_optional}
%define build_docker 1
%endif
%endif
```

**Comment by martinpitt** [comment]
@leomoty : Yep, works for me! Thanks

**Comment by leomoty** [comment]
@martinpitt should be ready for a proper review, I did build centos-8-stream successfully locally.

**Comment by martinpitt** [comment]
@leomoty : Semaphore fails due to a regression in less, which we fixed yesterday. Do you mind rebasing to current master to fix this? Thanks!

**Comment by leomoty** [comment]
@martinpitt: thanks again and sorry for all the noise, and ~4 hours ago was a bit too early for me.

**Pull request merged**
