### PR TITLE
Add CentOS CI image store

### PR DESCRIPTION
**Pull request by martinpitt**
See individual commits for details.

 * [x] image-refresh rhel-8
 * [x] image-refresh ubuntu-stable

### CODE REVIEW

**Comment by martinpitt** [comment]
I tested image-download and upload to the new store, as well as to/with the old ones by commenting out the new store.

**Comment by stefwalter** [comment]
I see an error in the Semaphore tests that probably needs to be fixed:

```
ERROR: tools/test-static-code Invalid test number: pyflakes bots pkg tools
PASS: tools/test-static-code 2 pyflakes test
PASS: tools/test-static-code 3 js-translatable-strings
PASS: tools/test-static-code 4 unsafe-security-policy
PASS: tools/test-static-code 5 patternfly-font-paths
```

**Comment by stefwalter** [comment]
In addition, there should be a bunch of self-test ```image-create``` lines here for bots to try this new code out and upload the results to CentOS CI.

**Comment by martinpitt** [comment]
@stefwalter: Fixed the pyflakes thing. Indeed due to the store order I expect the bots to mostly pull from the local cache, or not at all; maybe the ovirt image. I'll just fake this by removing an image from the cache and immediately trigger a test, then it should pull from CentOS CI.

I'll trigger the image rebuilds once I'm done figuring out the commit message wording with @allisonkarlitskaya .

**Comment by martinpitt** [comment]
Pushed again with a more explanatory commit log. The new store also finished to sync all images, so once the current backlog drains a bit I can do the "remove from local cache and rebuild" trick. Triggering an image refresh now.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-7d2j1.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9321-20180606-154848/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9321-20180606-154848/

**Comment by martinpitt** [comment]
Need to fix this case:

    curl: (51) SSL: certificate subject name 'cockpit-tests' does not match target host name 'cockpit-11.e2e.bos.redhat.com'

**Comment by martinpitt** [comment]
The image upload actually worked in the previous attempt, this was just a stupid bug in the return code handling. Fixed, and retriggering build.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-chttx.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9321-20180606-165555/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9321-20180606-165555/

**Comment by martinpitt** [comment]
Bah, timeout. The bots have behaved really weird recently :-( Trying again.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-h0msv.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9321-20180606-202020/

**Comment by cockpituous** [comment]
image-refresh rhel-8 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-20180606-203939

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-8skm5.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9321-20180606-212020/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-stable-20180606-215656

**Comment by martinpitt** [comment]
The private rhel-8 image was correctly uploaded to the private store. But the public ubuntu-stable image went to the old verifymachine4:

    image-upload: unable to upload image: https://images-cockpit.apps.ci.centos.org/

This should be more verbose to get the reason for the failure.

**Comment by martinpitt** [comment]
Fixed the bug, missing comma in the store list, argh. I reformatted that after testing. Rebuilding image.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-dpv8k.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9321-20180607-093232/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-stable-20180607-100606

**Comment by martinpitt** [comment]
ubuntu-stable refresh was uploaded correctly: https://images-cockpit.apps.ci.centos.org/ubuntu-stable-aba8b2d55f5fe4ea617423cf00d1d3b5f9ad61b674c5c2e337a6d1053722c7a5.qcow2

I pushed it onto the PR, the test should then download it from CentOS CI (as that's the only place where this new image lives) and cache it locally. I don't push the rhel-8 image refresh. It succeeded, but it collides with the "real" refresh/update in PR #9329.

**Comment by martinpitt** [comment]
The [ubuntu-stable image was downloaded successfully from CentOS CI store](https://fedorapeople.org/groups/cockpit/logs/pull-9321-20180607-105151-fd3438a5-verify-ubuntu-stable/log.html):

     > http://10.128.5.195:80/ubuntu-stable-aba8b2d55f5fe4ea617423cf00d1d3b5f9ad61b674c5c2e337a6d1053722c7a5.qcow2

The [rhel-7](https://fedorapeople.org/groups/cockpit/logs/pull-9321-20180607-101717-fd3438a5-verify-rhel-7/log) build log also shows that other items are successfully downloaded from the local cluster:

     > http://10.130.5.184:80/tests-learn-5-3.model

So I believe that this now sufficiently demonstated that this works on our existing infra.

**Comment by martinpitt** [comment]
@allisonkarlitskaya , @stefwalter : Are you ok with landing this with the unrelated kubevirt failures? It's impossible right now to get any Fedora/RHEL test to green unfortunately, we need to continue to investigate this next week. But I'd like to go forward with the CentOS CI migration.

**Comment by martinpitt** [comment]
Actually it got green now :-)

**Comment by allisonkarlitskaya** [comment]
I'm happy for this to land, but only because of your stated intention to keep this minimal and get it landed.  More cleanups are needed here.

**Pull request merged**
