### PR TITLE
test: Add known issue for setroubleshootd

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by stefwalter** [comment]
This needs an upstream bug that it can be cross referenced with, right @dperpeet?

**Comment by mvollmer** [comment]
The know issue is #4679, and the upstream bug is  https://bugzilla.redhat.com/show_bug.cgi?id=1352611

**Comment by mvollmer** [comment]
I will check whether the new audit version fixes the bug and give karma.

**Comment by mvollmer** [comment]
> The know issue is #4679

#4678, sorry....

**Pull request closed without merging**
