### PR TITLE
overview: Breakpoint optimizations

### PR DESCRIPTION
**Pull request by garrett**
- Adjust the shell to provide more space for VM resolutions (<= 1024×768)
- Tweak layout, headings, and cards for various common resolutions, including:
  - various typical mobile sizes
  - VM <= 1024×768
  - 1600×1200
  - 2560×1440
  - 1280×1440 (half-tiled browser window in 2560×1440)
  - 1920×1080
  - 960×1080 (for half-tiled browser windows in 1920×1080)
  - and a lot of various widths in-between (to make sure elements are sized in a pleasant enough manner)

### CODE REVIEW

**Comment by garrett** [comment]
This PR should fix https://github.com/cockpit-project/cockpit/issues/13326.

Please test in your typical usage on your machines (as well as whatever sizes you'd like). Thanks!

**Comment by garrett** [comment]
BTW: I optimized these changes with https://github.com/cockpit-project/cockpit/pull/13395 baked-in. (I removed the other PR's commit before squashing this down, of course.)

Basically, _if_ the usage bars and text still shift around for you with _just_ this PR, it should be solved when both this PR and the usage string update PR land.

**Comment by martinpitt** [comment]
Neat, thanks! I tested this on the entire available range of resolutions available to me right now (up to 1280x800, only have my laptop this week). In particular, at half-tiled, i. e. 640x800, at which current master looks pretty bad. Now Machine ID doesn't overflow any more, 640 width uses mobile mode already, and for most resolutions it works fine now.

The only way I can break it now is with `/usr/libexec/cockpit-desktop /`, i. e. webkit, at window widths between 680 and 768 pixels:

webkit

But I don't get that with Firefox, the Machine ID properly wraps there (the card width is the same).

So from my POV that's definitively a big improvement! :+1:  Thanks!

**Comment by garrett** [comment]
> The only way I can break it now is with /usr/libexec/cockpit-desktop /, i. e. webkit, at window widths between 680 and 768 pixels (on webkit)

Oops! I think I know what's going on and how to fix that, but we could have a simple bugfix patch for webkit later too.

I can try to craft a patch on the train Monday. (If it's possible to do so.)

**Comment by marusak** [comment]
Nice, however I found some issue: (I have dashboard, haven't tried without it yet)

1. On width 761 the UI is broken. It happens only on this one width, so maybe somewhere the maths does not add up?
761brokenalltogether

2. It still can have these super thin columns and they can break. It happens only on widths 1158-1162 and only when there is scroll bar. If I give it more height, the problem does not exist.
betterviewof3columns

3. There is only one column up to width 952, which was the original issue (but it was that it is happening on 1024, now it is a few pixels down). Is this definitive decision that at this width there cannot be two columns?  (It seems like it could fit two, but I can be wrong, in which case please ignore :) )
952stillonecolumn

**Comment by garrett** [comment]
> On width 761 the UI is broken. It happens only on this one width, so maybe somewhere the maths does not add up?

Ah, it's probably a min-width / max-width thing where they're both 760px. Yeah, that should be fixed. Thanks for spotting it!

> It still can have these super thin columns and they can break. It happens only on widths 1158-1162 and only when there is scroll bar. If I give it more height, the problem does not exist.

Since you mention height, that means your browser's (emulated) device height is < 768. (And I see this in the screenshot.) I guess this must be the result of optimizing for 1024×768. 

I made the sizing have some "wiggle room" due to being in an iframe. This wouldn't happen under any normal circumstances, as the browser would be taller on a desktop (even if narrower width), would be portrait on a phone, etc.

Try resizing the browser itself to approximately this height (without using the mobile preview).

> There is only one column up to width 952, which was the original issue (but it was that it is happening on 1024, now it is a few pixels down). Is this definitive decision that at this width there cannot be two columns? (It seems like it could fit two, but I can be wrong, in which case please ignore :) )

This is also probably due to your browser's emulated device height being artificially short.

**Comment by AdamWill** [comment]
I hate to be awkward. No, wait, that's a lie, I *love* to be awkward. So I'll just point out that devices with the native resolution 1280x600 do, or at least did, [exist](http://kryz.org/vaio.html) :) I had one, once...

This is where you tell me to go away, btw. :P

**Comment by garrett** [comment]
> I'll just point out that devices with the native resolution 1280x600 do, or at least did, exist 

Then provided it can somehow run a modern enough browser that can sign into Cockpit (perhaps via X over the network to a more powerful computer), it should still be OK, as:

> It happens only on widths 1158-1162

So you should be fine with that old laptop, unless you have a very wide side panel. 😉

**Comment by AdamWill** [comment]
Dangit, time to do some more hardware research...:P

**Comment by garrett** [comment]
I accidentally broke some things with a regular expression in a previous commit. Fixed it where I broke things, bumped up a magic number (that makes the cards wide enough, but not too wide in places where it is used) for sizing the cards based on approximate content width, and rebased.

It now looks good here and fixes the above issues. Please test again. :wink:

**Comment by marusak** [comment]
> 2. It still can have these super thin columns and they can break. 

Does not happen anymore, nice!

> 1. On width 761 the UI is broken.

Still persists unfortunately. It is due to my device(?) size, as when I make it smaller (ctlr+ -) or bigger (ctrl + +) it does not happen.

**Comment by mvollmer** [comment]
Green enough, thanks!

**Pull request merged**
