### PR TITLE
Revert "shell: Deprecate host switcher in current OS releases"

### LINKED ISSUE #20823: Address issues with host switcher removal before releasing Cockpit with this feature
Hey, I wasn't consulted about the design upfront, during the process, or even at the end of this PR... I was told that the technical details and what we can do were still being discussed, even as recent as _yesterday_, and that we haven't decided what will be done. It was also not obvious that this would be merged when it was.

From a user point of view, this is also very problematic for several reasons:

- Firstly, it mysteriously breaks things for anyone who has used Cockpit ever before, even if that would be another machine.
- It doesn't change the UI properly for the top-level switcher component, so it looks broken on a machine without hosts.
- On a machine with hosts, it has some very weird and clunky UI that is nonstandard and doesn't explain why this is now "broken".
- There has been no warning whatsoever. The functionality is suddenly broken. There hasn't been a grace period.
- It's not obvious within Cockpit on how to get the functionality back meanwhile.
- We were specifically told, many times, that people use this functionality and depend upon it. Even as recently as the call we had with a customer.
- If this was meant to fly under the radar for a RHEL release, then the defaults for RHEL should be different from the defaults overall. This instantly breaks it for everyone.

We need to address all these points before making a release with this PR merged.

_Originally posted by @garrett in https://github.com/cockpit-project/cockpit/issues/20749#issuecomment-2260033909_

### PR DESCRIPTION
**Pull request by martinpitt**
This gets challenged/debated heavily, see #20823

Reopens https://issues.redhat.com/browse/COCKPIT-1149 and https://issues.redhat.com/browse/COCKPIT-870

This reverts commit ee3262ee919a862ddb522f1a162d5a8f47c2945d.

Fixes #20823 

----

I give up. Whoever else wants to take this up, I'm not that any more. I the past and following weeks I'm unfortunately unable health-wise to contribute anything significant to this.

### CODE REVIEW

**Comment by garrett** [comment]
I think you might misunderstand?

The discussion isn't to not deprecate it; the discussion is to not immediately break the feature for everyone, and to quickly adjust the configuration file to apply to RHEL10 only for now, so Cockpit would land in RHEL10 (specifically) without the host switcher by default.

And after the next release (due to time constraints), then work on messaging this in a better way (in Cockpit itself, in addition to the website and Mastodon) so people know that it's coming and can prepare. As it stands in main right now, without these adjustments, when people upgrade Cockpit (on their non-RHEL systems), they'll find out that the feature they depended on is semi-broken with no explanation as to why or what to do next. The discussion is to prevent that confusion for everyone on non-RHEL systems, and to prevent Cockpit from looking broken or acting in a semi-broken state.

**Comment by martinpitt** [comment]
@garrett I didn't closely follow the discussion. Do with this as you may, it's just one option. Thanks!

**Comment by mvollmer** [comment]
> I give up.

Nah, just take some rest.

**Comment by garrett** [comment]
I agree with @mvollmer. @martinpitt, please do get some rest and I'm sorry for causing distress over this. We're handling it.

We're not tossing away your work on this; we're revising it and making sure the RHEL case is covered immediately and we're working to cover everything else too, hopefully making everyone happy enough in the longer run.

**Comment by martinpitt** [comment]
OK! Don't worry, this wasn't much work, I just wasn't sure if you rather wanted to start from scratch or from current main.

**Pull request closed without merging**
