### PR TITLE
Drop fedora-26 image

### PR DESCRIPTION
**Pull request by martinpitt**
Fedora 28 is released now, so Fedora 26 will soon be EOL.

 - [x] Move avocado/selenium tests to Fedora 27 (PR #9163) 
 - [x] Move selenium image to Fedora 28 (PR #9167)
 - [x] Move container tests to Fedora 27 (PR #9172)

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-n2zj8.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9088-20180502-150101/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-qr8q2.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9088-20180502-150000/

**Comment by cockpituous** [comment]
image-refresh selenium done: https://github.com/cockpituous/cockpit/commits/image-refresh-selenium-20180502-153232

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-qr8q2.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9088-20180502-153333/

**Comment by cockpituous** [comment]
image-refresh fedora-28 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-28-20180502-165050

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-qr8q2.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9088-20180502-213838/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-s31sh.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9088-20180502-213939/

**Comment by cockpituous** [comment]
image-refresh fedora-28 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-28-20180502-222424

**Comment by martinpitt** [comment]
I can locally reproduce the "internal error during login" with the bastion container. When trying to log in, the journal from the docker container says
```
[Invalid UTF-8] DEBUG: cockpit-ws: invalid or unsupported cookie: u\xe9^
DEBUG: cockpit-ws: received unknown/invalid credential cookie
DEBUG: cockpit-ws: spawning /container/cockpit-auth-ssh-key
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: output queue empty
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: reading input 1
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: want more data 2
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: reading input 1
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: received a 83 byte payload
DEBUG: cockpit-ws: received authorize challenge
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: queued 97 byte payload
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: want more data
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: wrote 4 bytes
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: wrote 97 bytes
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: output queue empty
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: reading input 1
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: received a 1759 byte payload
DEBUG: cockpit-ws: received authorize challenge
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: want more data
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: reading input 1
WARNING: cockpit-protocol: /container/cockpit-auth-ssh-key: incorrect protocol: received invalid length prefix
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: closing pipe: protocol-error
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: killing child: 55
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: child process quit: closed:  55 15
DEBUG: cockpit-protocol: /container/cockpit-auth-ssh-key: closed: protocol-error
DEBUG: cockpit-ws: cockpit-auth-ssh-key: authentication process exited: 15
DEBUG: cockpit-protocol: /cockpit+=10.111.113.1/login: returning error: 500 Internal error in login process
```
At this point I have absolutely no idea what the "invalid length prefix" is about..

**Comment by martinpitt** [comment]
I split out the avocado/selenium bits to #9120, to get the image refreshes out of the way.

**Pull request merged**
