### PR TITLE
package.json: Update xterm package dependency

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "xterm": "3.14.5"
pkg/docker/docker.js:import { Terminal } from "xterm";
pkg/lib/cockpit-components-terminal.jsx:import { Terminal as Term } from "xterm";
pkg/lib/console.css:@import "~xterm/lib/xterm.css";
pkg/lib/context-menu.css:    /* xterm accessibility tree has z-index 100 and we need to be in front of it
pkg/machines/machines.less:@import "~xterm/lib/xterm.css";
pkg/systemd/terminal.css:.xterm-accessibility {
pkg/systemd/terminal.jsx:                    "TERM=xterm-256color",
test/selenium/selenium-base.py:        terminal = self.wait_xpath("//*[contains(@class, 'terminal xterm')]")
test/selenium/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer')
test/selenium/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer', cond=invisible)
test/selenium/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer')
test/selenium/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer', cond=invisible)
test/selenium/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer')
test/verify/check-active-pages:                return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-pages:            return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-realms:                return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-setroubleshoot:        b.wait_in_text(".xterm-accessibility-tree", "semanage import <<EOF")
test/verify/check-setroubleshoot:        b.wait_in_text(".xterm-accessibility-tree", "boolean -D")
test/verify/check-setroubleshoot:        b.wait_in_text(".xterm-accessibility-tree", "boolean -m -1 zebra_write_config")
test/verify/check-setroubleshoot:        b.wait_in_text(".xterm-accessibility-tree", "fcontext -a -f a -t samba_share_t -r 's0' '/var/tmp/'")
test/verify/check-terminal:                return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-terminal:            b.wait_attr(".xterm-viewport", "style", style)
test/verify/check-terminal:        b.wait_attr(".xterm-viewport", "style", white_style)
test/verify/machineslib.py:        b.wait_present("div.terminal canvas.xterm-text-layer") # if connected the xterm canvas is rendered
test/verify/machineslib.py:        b.wait_present("div.terminal canvas.xterm-text-layer")
test/verify/machineslib.py:        b.wait_not_present("div.terminal canvas.xterm-text-layer")
test/verify/machineslib.py:        b.wait_present("div.terminal canvas.xterm-text-layer")
```

**Comment by cockpituous** [comment]
npm-update in progress on centosci-tasks-ncc2c.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/npm-update-12736-20190909-090101/

**Comment by marusak** [comment]
This needs work, tests should catch that

**Comment by cockpituous** [comment]
npm-update @patternfly/react-console done: https://github.com/cockpituous/cockpit/commits/npm-update-@patternfly/react-console-20190909-090202

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "@patternfly/react-console": "1.12.6",
pkg/machines/components/serialConsole.jsx:import { SerialConsole } from '@patternfly/react-console';
pkg/machines/components/vnc.jsx:import { VncConsole } from '@patternfly/react-console';
pkg/machines/machines.less:// For patternfly-react and @patternfly/react-console
pkg/machines/machines.less:@import "~@patternfly/react-console/dist/less/console.less";
```

**Comment by marusak** [comment]
There is finally xterm-4.0.0!
However we cannot upgrade to it, since react-console needs xterm < 3.14. I opened [issue](https://github.com/patternfly/patternfly-react/issues/2912) to patternfly react, so lets see if it moves and unblocks us.

**Comment by marusak** [comment]
I've created https://github.com/patternfly/patternfly-react/pull/3030 to unblock us.

**Comment by marusak** [comment]
Duplicate of #13331

**Pull request closed without merging**
