### PR TITLE
storage: Use a single dialog for creating logical volumes

### PR DESCRIPTION
**Pull request by mvollmer**
The dialog will get more fields and more interesting behavior as we
implement more of the features offered by LVM2, such as the various
RAID levels, as indicated by the hidden options for the "Purpose" and
"Layout" fields.

### CODE REVIEW

**Comment by mvollmer** [comment]
@andreasn, @mulkieran, @cmurf, what do you think of the general direction of this?

Is "Purpose" and "Layout" clear?

The reason to combine all this into one dialog is that you might want a raid5 pool, for example.

**Comment by cmurf** [comment]
It's clear. My opinion is that this is easier if you resist making UI that merely exposes the CLI to the user. The GUI should help the user achieve a goal for a particular use case, and abstract as much detail as possible. Otherwise it's going to quickly turn into a mess because there's really way too much that can be done between mdadm and lvm, and most users have no idea what the difference is. Even experts aren't that aware of LVM raid.

Once on linux-raid@ Neil Brown said he's been wanting LVM raid to get good enough to replace mdadm but it still has nowhere near the features (of course both use the same md driver in the kernel). 

So what you could do is have a very top down UI where the user picks top features first like what filesystem, level of redundancy, hot swap, and gray out incompatible options as they check the ones they want. And then build the lower layers for them. That's sorta what you're describing by having a dialog of features rather than drop down of actions.

Since you're creating the software, whether mdadm or LVM raid is used I think becomes more Cockpit developer domain than the user. The user is ceding this choice by using Cockpit, and Cockpit is in a sense becoming an intelligent sysadmin, and via Cockpit you're the sysadmin of everyone using Cockpit. So I will be skeptical of users asking for GUI feature parity with the CLI. I think the idea of putting this in Cockpit vs the installer (e.g. Anaconda custom storage config) is Cockpit also modifies and manages. Create is only right now. Modify and manage is drives dying, volumes getting full and needing to be grown, getting notifications before things are problems, etc. This is a huge weak area in CLI world.

BTW where should storaged feature requests go? There probably should be automatic checking of SCT ERC and the kernel's SCSI command timer to make sure they're compatible and if not change them so they are - and not involve the user in this (except maybe by summary if you want to inform them). Except enterprise/NAS drives, this is always misconfigured by default and eventually leads to data loss so getting it right for the user would be cool.

**Comment by mulkieran** [comment]
In principle, I agree with @cmurf, about not duplicating the CLI, and so forth.
In practice, it's a little hard to know what, if any general concepts actually exist to map to specifics of underlying tools.

I think that this direction is better than the distinct menu items of the previous version.

Be aware that lvm is supporting the notion of a cache: https://rwmj.wordpress.com/2014/05/22/using-lvms-new-cache-feature/. Obviously, the cache should be located on a faster device...generally an SSD. This requires either that the user exercise some choice about what goes on what device, or that Cockpit/storaged get really smart about selecting devices for particular purposes.

**Comment by cmurf** [comment]
Yeah it's hard to know how your target audience will handle UI/Ux. Anaconda folks went for top down approach where the user picks physical drives (most bottom step is unavoidable) but the very next step is choosing a mount point, raid, encryption, label, and filesystem. It's been really confusing for old school types who expect to explicitly partition each drive individually, and build every layer in their specific sequence, because only that sequence is right. I think that's archaic. People have better things to do these days. So anytime you get into the GUI boxing ring, prepare to get punched by someone and not take it personally. It's almost literally a thankless job. In storage, I'd say the best outcome is no one experiences unintended data loss. Because there's probably no awards for storage UIs. 

In GUIs, you can pretty much blatantly lie and even sometimes inconvenience the user, just don't make it easy to accidentally lose data. The very prominent Format action button right now concerns me for that reason, especially when the next dialog popdown says it's not going to erase data, except that it is, it's just not going to zero out the drive first (which is probably an archaic option; better to support ATA Security Erase in some other part of the storage UI, with appropriate scary warnings of complete, NSA irretrievable data destruction. And the ATA Security Erase is good for HDD and SSD whereas zeroing is not really appropriate for SSDs, and takes longer for both drive types than the ATA command.)

**Comment by jbrassow** [comment]
I'm with mulkieran.  It becomes difficult to handle RAID + cache + thinpool and be able to specify all the different options.  If a user is specifying cache, they will definitely want to choose fast storage for it.  (Optionally, you could add a feature request that LVM be smart enough to use fast storage for cache on it's own.)

**Comment by mvollmer** [comment]
@andreasn says to go ahead with the dialog.

**Comment by mvollmer** [comment]
> I'm with mulkieran. It becomes difficult to handle RAID + cache + thinpool and be able to specify all the different options. If a user is specifying cache, they will definitely want to choose fast storage for it. 

Yes.  Do you have a list of use cases that you would like to see addressed in Cockpit?

I am approaching this from the top, expanding the UI as I learn more about how LVM2 actually works.  I haven't yet looked at "man lvcache", for example...

**Comment by mvollmer** [comment]
I will also include raidy block volumes here to give this some substance, but not raidy pools.

**Comment by mvollmer** [comment]
Okay, well, I now think that anything beyond linear layout is a can of worms that I don't want to open right now. I am afraid I am too naive right now to do a good job in a reasonable time. The docker storage setup and fedora-24 server storage use cases are more worthwhile, IMO.

(For example, already for mirrors we really need to allow people to select the pvs that the copies should go on, and deal with disk failures sensibly.  Mirrors seem to have a small "mirror log" that also needs to go somewhere and complicates the size caclulations.  And sll the additional complexity also spills over into resizing, I guess.  Certainly all very interesting, but...)

**Comment by mulkieran** [comment]
@mvollmer 

> (For example, already for mirrors we really need to allow people to select the pvs that the copies should go on, and deal with disk failures sensibly. Mirrors seem to have a small "mirror log" that also needs to go somewhere and complicates the size caclulations. And all the additional complexity also spills over into resizing, I guess. Certainly all very interesting, but...)

How much of this do you expect Cockpit to have to do, how much storaged?

**Comment by mvollmer** [comment]
> How much of this do you expect Cockpit to have to do, how much storaged?

I don't know, but I am sure we can figure out a reasonable split.

**Comment by stefwalter** [comment]
@andreasn Is this ready to go in?

**Comment by andreasn** [comment]
Didn't get around to testing this one yet.

**Comment by andreasn** [comment]
Screenshot
screenshot from 2016-04-05 17-45-05

In most dialogs on the Storage and Network sections "Name" is at the top, so I think it makes sense here too.

**Comment by jbrassow** [comment]
> On Apr 1, 2016, at 1:34 AM, Marius Vollmer <notifications@github.com> wrote:
> 
> Okay, well, I now think that anything beyond linear layout is a can of worms that I don't want to open right now. I am afraid I am too naive right now to do a good job in a reasonable time. The docker storage setup and fedora-24 server storage use cases are more worthwhile, IMO.
> 
> (For example, already for mirrors we really need to allow people to select the pvs that the copies should go on, and deal with disk failures sensibly. Mirrors seem to have a small "mirror log" that also needs to go somewhere and complicates the size caclulations. And sll the additional complexity also spills over into resizing, I guess. Certainly all very interesting, but...)

BTW, If we can avoid adding support for the “mirror” type, we should do so.  The better solution is to use the “raid1” segment type.  The “raid1” segment type has a superblock/metadata area for each device.  The “mirror” segment type has the separate log that can go on a separate device.

The “raid1” segment type is significantly better than “mirror”.

Thanks,
 brassow

**Comment by mvollmer** [comment]
> BTW, If we can avoid adding support for the “mirror” type, we should do so. The better solution is to use the “raid1” segment type. 

That's the idea. I think lvcreate already prefers the "raid1" segment type to "mirror" when you specify "--type mirror", no?

**Comment by mvollmer** [comment]
> In most dialogs on the Storage and Network sections "Name" is at the top, so I think it makes sense here too.

Good point, done.

**Comment by mvollmer** [comment]
Test failures seem unrelated.

**Comment by jbrassow** [comment]
> On Apr 7, 2016, at 2:48 AM, Marius Vollmer <notifications@github.com> wrote:
> 
> BTW, If we can avoid adding support for the “mirror” type, we should do so. The better solution is to use the “raid1” segment type.
> 
> That's the idea. I think lvcreate already prefers the "raid1" segment type to "mirror" when you specify "--type mirror", no?

As of RHEL7

 brassow

**Comment by mvollmer** [comment]
>> That's the idea. I think lvcreate already prefers the "raid1" segment type to "mirror" when you specify "--type mirror", no?

> As of RHEL7

Do you think the UI code needs to be aware of the distinction between "mirror" and "raid1"?

**Comment by jbrassow** [comment]
> On Apr 8, 2016, at 1:53 AM, Marius Vollmer <notifications@github.com> wrote:
> 
> That's the idea. I think lvcreate already prefers the "raid1" segment type to "mirror" when you specify "--type mirror", no?
> 
> As of RHEL7
> 
> Do you think the UI code needs to be aware of the distinction between "mirror" and "raid1"?

No.  The “mirror” type can be ignored.

 brassow

**Comment by mvollmer** [comment]
Screenshot:
lvm-dialog

**Pull request closed without merging**
