### PR TITLE
Missing 'class=active' for Journal Page #1646

### PR DESCRIPTION
**Pull request by Aayush-Kasurde**
Replace data-page-id to data-task-id for journal page in order to highlight "Journal Page" on dashboard

### CODE REVIEW

**Comment by mvollmer** [comment]
This was merged.

**Comment by mvollmer** [comment]
Should we include this fix in a F20 branch as well?

**Comment by stefwalter** [comment]
I don't think either of us are maintaining an F21 or stable branch at this point. But if someone were to maintain such a branch, then this would be a good candidate.

**Comment by stefwalter** [comment]
Actually, not sure this is relevant to Cockpit 0.27. I could be wrong.

**Pull request closed without merging**
