### PR TITLE
Image refresh for centos-7 - fixed in #8943

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-7
 * [x] image-refresh centos-7

### CODE REVIEW

**Comment by martinpitt** [comment]
[testDevmapper fails](https://fedorapeople.org/groups/cockpit/logs/pull-8837-20180316-161717-d24a72e7-verify-centos-7/log.html#191), supposedly CentOS-7 caught up with RHEL 7 and now also uses overlayfs. Will have a look on Monday.

**Comment by martinpitt** [comment]
Actually it's so simple, I pushed the fix right away.

**Comment by martinpitt** [comment]
Gah, why can't *anything* ever be easy.. Just marking centos-7 to have overlayfs (like for rhel-7) didn't do the trick. Trying to initialize the docker storage from the newly created /dev/sda for the first time just silently fails. It does not appear at all in the "Storage Pool" list and appears (unticked) in the "Additional Storage", even though it is now busy.

Trying to initialize it again then yields this:

Could not add all disks
```
/dev/sda: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
/dev/sda: calling ioclt to re-read partition table: Success
INFO: Volume group backing root filesystem could not be determined
  WARNING: Device for PV FvjUaT-uRYG-xzFY-7WmW-GtLE-vqYh-bWNPmd not found or rejected by a filter.
Return Code: 5
INFO: Volume group backing root filesystem could not be determined
docker-storage-setup failed
Failure: INFO: Volume group backing root filesystem could not be determined
  WARNING: Device for PV FvjUaT-uRYG-xzFY-7WmW-GtLE-vqYh-bWNPmd not found or rejected by a filter.
Warning: The resulting partition is not properly aligned for best performance.
INFO: Device node /dev/sda1 exists.
  Can't initialize physical volume "/dev/sda1" of volume group "atomic-storage" without -ff
  /dev/sda1: physical volume not initialized.

Traceback (most recent call last):
  File "<stdin>", line 550, in <module>
  File "<stdin>", line 535, in cmd_create_vgroup
  File "<stdin>", line 91, in check_call
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['atomic', 'storage', 'modify', '--vgroup', 'atomic-storage', '--add-device', '/dev/sda']' returned non-zero exit status 1
```

But this is just a follow-up error as the VG already exists, it just does not get shown:

```
# pvs
  PV         VG             Fmt  Attr PSize  PFree 
  /dev/sda1  atomic-storage lvm2 a--  96.00m 96.00m

# vgs
  VG             #PV #LV #SN Attr   VSize  VFree 
  atomic-storage   1   0   0 wz--n- 96.00m 96.00m

# cat /etc/sysconfig/docker-storage-setup 
STORAGE_DRIVER=overlay2
MIN_DATA_SIZE=80M
VG="atomic-storage"
DEVS="/dev/sda"
```

When I `sit()` the test right after adding /dev/sda, and try to initialize the pool manually, it works too:
```
# printf 'VG="atomic-storage"\nDEVS="/dev/sda"\n' >> /etc/sysconfig/docker-storage-setup 
# docker-storage-setup 
INFO: Volume group backing root filesystem could not be determined
Warning: The resulting partition is not properly aligned for best performance.
INFO: Device node /dev/sda1 exists.
  Physical volume "/dev/sda1" successfully created.
  Volume group "atomic-storage" successfully created
```

However, `docker info` does not really change (not sure if it's supposed to, need to compare to other OSes):
```
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
```

**Comment by mvollmer** [comment]
I can have a look.

**Comment by mvollmer** [comment]
Okay, I think this is the first case where the rootfs is _not_ in a volume group and the driver is overlayfs2.  We shouldn't offer to add disks in this case.  Currently Cockpit has the wrong assumption that devicemapper is used in such a scenario.  It makes a dedicated volume group when adding the first disk because with devicemapper this would stop using the ugly loopback setup.  With overlayfs2, it doesn't make any sense.

A useful operation is to switch to the devicemapper driver with a dedicated volume group.  This would be a significant change, and I think we should re-think the whole topic carefully before doing that.

But this doesn't explain why DISK1 is not listed as part of the pool.  I'll dig more.

**Comment by mvollmer** [comment]
This needs to be tested everywhere since the `cockpit-docker-storage` tool has changed.

**Comment by martinpitt** [comment]
@mvollmer: This now fails on centos-7 *and* on rhel-7; I retried several times, it's apparently not just a flake.

**Comment by martinpitt** [comment]
#8943 went in, closing.

**Pull request closed without merging**
