### PR TITLE
bots: Move fedora-i386 image to Fedora 27

### PR DESCRIPTION
**Pull request by martinpitt**
Fedora 25 is EOL now. Since Fedora 26 the mirrors don't publish i386
repositories any more, just a bi-arch x86_64/ repository. As this is not
straightforward to use with virt-install, move to virt-builder instead;
that still offers an i386 image and is faster, too.

Port fedora-25.setup's `HAVE_KUBERNETES` and conditional cockpit/base
docker build logic to fedora-27.setup to share it between 32 and 64 bit
images. Install docker explicitly as on 32 bit it won't get pulled in by
kubernetes.

Drop obsolete test skip in check-packagekit which now works on a Fedora
27 based image.

 * [x] image-refresh fedora-i386

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-p1rbp.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8137-20171121-093131/

**Comment by cockpituous** [comment]
image-refresh fedora-i386 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-i386-20171121-100505

**Comment by martinpitt** [comment]
Forgot to update the naughty symlink, pushed.

**Comment by martinpitt** [comment]
kdump tests fail as kdump.service fails to start:
```
Nov 21 06:06:16 localhost.localdomain kdumpctl[1136]: No memory reserved for crash kernel
Nov 21 06:06:16 localhost.localdomain kdumpctl[1136]: Starting kdump: [FAILED]
Nov 21 06:06:16 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=kdump comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Nov 21 06:06:16 localhost.localdomain systemd[1]: kdump.service: Main process exited, code=exited, status=1/FAILURE
Nov 21 06:06:16 localhost.localdomain systemd[1]: Failed to start Crash recovery kernel arming.
```

**Comment by martinpitt** [comment]
I successfully ran the kdump test locally four times, and a retry on the infra worked as well, so it was just a flake and not related to bumping the image.

**Pull request merged**
