### PR TITLE
selenium test fixes and Firefox 3 update

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh selenium
 * [x] various test fixes (PR #10090)
 * [x] fix `test50ChangeTabLogs` failure

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-jf5qv.
Log: https://209.132.184.41:8493/logs/image-refresh-10089-20180917-163434/

**Comment by cockpituous** [comment]
image-refresh selenium done: https://github.com/cockpituous/cockpit/commits/image-refresh-selenium-20180917-165656

**Comment by martinpitt** [comment]
I can locally reproduce the `test50ChangeTabLogs` failure as well, I mostly just wanted to see that the other tests succeed in CI.

**Comment by martinpitt** [comment]
As for the `set_page_load_timeout()` regression, I reported that to https://github.com/SeleniumHQ/selenium/issues/6420 and debug it there. An alternative workaround is

```diff
--- a/bots/images/scripts/selenium.setup
+++ b/bots/images/scripts/selenium.setup
@@ -37,7 +37,10 @@ systemctl enable docker
 # docker images that we need for integration testing
 docker pull selenium/hub:3
 docker pull selenium/node-chrome:3
-docker pull selenium/node-firefox:3
+#docker pull selenium/node-firefox:3
+# HACK: 3.14.0-europium (v62.0) breaks set_page_load_timeout(): https://github.com/SeleniumHQ/selenium/issues/6420
+docker pull selenium/node-firefox:3.14.0-dubnium
+docker tag selenium/node-firefox:3.14.0-dubnium selenium/node-firefox:3
 
 # reduce image size
 dnf clean all
```

I tested this successfully as well, and we can use it if the default page load timeout isn't enough. But I verified that this is *not* related to test50ChangeTabLogs, i. e. this does not fail due to the lower default page timeout.

**Comment by martinpitt** [comment]
The test50ChangeTabLogs keeps failing here, and I've already wasted 6 hours of debugging on this.  At some point, `def wait()0` just stops like this:

```
04:26:39 DEBUG| ('XXXXX wait exception:', 'Message: Failed to convert data to an object\n')
04:26:41 DEBUG| ('XXXXX wait exception:', 'Message: Failed to decode response from marionette\n')
04:26:42 DEBUG| ('XXXXX wait exception:', 'Message: Tried to run command without establishing a connection\n')
04:26:43 DEBUG| ('XXXXX wait exception:', 'Message: Session [4f18d6e1-5322-405d-9367-b33872dd4e59] was terminated due to BROWSER_TIMEOUT
```
The internet is full of people [with the same problem](https://www.google.com/search?q=selenium+session+was+terminated+due+to+BROWSER_TIMEOUT), but unfortunately going through the search results there is not very insightful.

**Pull request merged**
