### PR TITLE
bridge: Add the option for the host field to be expanded

### PR DESCRIPTION
**Pull request by petervo**
This introduces ! as a separator to allow us to include an additional key/value parameter along with the host parameter.

If present the key/value pair is added to the json open command. This allows us to use those additional parameters to route incoming requests for available in alternate bridges correctly.

### CODE REVIEW

**Comment by stefwalter** [comment]
What about another '@' sign to separate host from container:

```@host@container```

Wheee bikeshedding is fun

**Comment by petervo** [comment]
we use @ for usernames. So I don't think we can do that.

**Comment by petervo** [comment]
To explain why I chose !. I wanted to use a character that isn't encoded by encodeURIComponent in javascript and isn't valid in a domain name or ip address that leaves us with ```! ~ * ' ( )```

Of those ! seemed the best to me. But we can pick something else. Also it doesn't have to be a non encodeURIComponent if we really want something else, we'll just have to make more changes to skip encoding it. However we can't choose @ or : as those already have special meaning in hosts strings. For ssh usernames and ports.

**Comment by mvollmer** [comment]
Does this need documentation?

**Comment by petervo** [comment]
Ok reworked to use + instead of !. I tried to use > that's not allowed as we have to stick to what's allowed in path segments. So between that and not using anything allowed in host names or ip address it's got to be one of 

``` ; , / ? : @ & = + $ ! ~ * ' ( )```

This looks alot nicer. I thought + might be a problem because frequently + is used for space. But we already use it for application so I think we are pretty safe the way we use it here. If it's too risky, we could go to =. 

Downside is here is this requires extra encoding/decoding in cockpit.js, If we chose ~ or ! then we don't need that step.

**Comment by petervo** [comment]
Also added some docs

**Pull request closed without merging**
