### PR TITLE
test: Build cockpit/base on setup

### PR DESCRIPTION
**Pull request by petervo**

### CODE REVIEW

**Comment by petervo** [comment]
bot: Image refresh for openshift

**Comment by stefwalter** [comment]
Blocked on #3999

**Comment by dperpeet** [comment]
this is still missing the new openshift image

**Comment by petervo** [comment]
@mvollmer any idea why the bot isn't picking this up?

@dperpeet, we all realize the image is needed, since needs work messes with the priority can you leave it off for now please

**Comment by petervo** [comment]
bot: Image refresh for openshift

**Comment by petervo** [comment]
Turns out the bot is not configured to build openshift image, building and uploading now.

**Comment by stefwalter** [comment]
Building openshift image.

**Pull request closed without merging**
