### PR TITLE
Make OnOff switch generally available

### PR DESCRIPTION
**Pull request by dperpeet**
This work is split out of #5587

### CODE REVIEW

**Comment by stefwalter** [comment]
CC @mvollmer Would you be interested in reviewing this? I know you have future ideas for a "switching in progress" design concept. Hopefully that can be layered on top of work like this to move OnOff into a React component.

**Comment by dperpeet** [comment]
> CC @mvollmer Would you be interested in reviewing this? I know you have future ideas for a "switching in progress" design concept. Hopefully that can be layered on top of work like this to move OnOff into a React component.

Note that this isn't a new component, it was already used in SELinux troubleshooting and I added the option to disable the component.

**Comment by dperpeet** [comment]
@andreasn should we gray out the OnOff when disabled?

**Comment by stefwalter** [comment]
> @andreasn should we gray out the OnOff when disabled?

See the patterns page for a disabled OnOff.

**Comment by dperpeet** [comment]
> @andreasn should we gray out the OnOff when disabled?
> 
> See the patterns page for a disabled OnOff.

Right, added.
screenshot from 2017-01-17 15-36-16

**Comment by larskarlitski** [comment]
Great work, thanks!

**Pull request closed without merging**
