### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by martinpitt** [comment]
Seems upstream already found the issue and stopped the [Fedora 29 update](https://bodhi.fedoraproject.org/updates/FEDORA-2019-1381778f11).

**Comment by Gundersanne** [comment]
@martinpitt so I guess we wait for the fix to get into debian as well?

**Comment by martinpitt** [comment]
@Gundersanne : Depends how fast it gets fixed upstream and the fix gets applied downstream. Right now there's no fix in master yet. This will block Debian uploads until then, unless we extend the version blacklist in configure.ac.

**Comment by martinpitt** [comment]
In other  words, fine to give upstream a few days and skip the next release (tomorrow) on Debian. If it's still broken in two weeks, let's apply the configure.ac blacklist. Sounds ok?

**Comment by Gundersanne** [comment]
perfect :)

**Comment by martinpitt** [comment]
https://git.libssh.org/projects/libssh.git/log/ now has a bunch of new commits, possibly one of them fixes the regression? Worth trying, bisecting, and filing a Debian bug about.

**Comment by Gundersanne** [comment]
@martinpitt I'll do that

**Comment by Gundersanne** [comment]
confirmed that `27fe6095` fixes it

**Comment by martinpitt** [comment]
I uploaded the fix to Debian: https://tracker.debian.org/news/1021133/accepted-libssh-086-2-source-into-unstable/

It should go into testing in about three days, then we can close this and let the bots build a new  image.

**Comment by martinpitt** [comment]
libssh 0.8.6-2 is in testing now, so let the bots build a new image.

**Pull request closed without merging**
