### PR TITLE
Superuser optional and fallback to sudo

### PR DESCRIPTION
**Pull request by stefwalter**
Add concept of optional superuser channels.

We queue the messages until we know that the other portal bridge has started. In the case of a failure and an optional channel, we send the messages to the usual bridge.

### CODE REVIEW

**Comment by stefwalter** [comment]
Needs testing and squashing.

**Comment by petervo** [comment]
I'm good with this, tested and it works for me. 

Do we need to do anything to suppress errors in the logs related to failed auth when in "try" mode. I see error level logs: 

testing : user NOT in sudoers ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/cockpit-bridge
sudo: bridge program failed: Child process exited with code 1

Or are we ok with that?

**Comment by stefwalter** [comment]
> Or are we ok with that?

I can f ix that as a follow up.

**Comment by mvollmer** [comment]
With this, check-journal passes on rhel-7 as "admin":

```
diff --git a/test/check-journal b/test/check-journal
index fa25136..fb7d0a4 100755
--- a/test/check-journal
+++ b/test/check-journal
@@ -26,10 +26,6 @@ class TestJournal(MachineCase):
         b = self.browser
         m = self.machine
 
-        # TODO: Make this work with non-root
-
-        b.default_user = "root"
-
         def inject_extras():
             b.eval_js("""
             ph_get_log_lines = function () {
```

**Comment by stefwalter** [comment]
>  sudo: bridge program failed: Child process exited with code 1

Removed this message. I think the message from sudo goes directly to the journal. Not sure we can do anything about that one @petervo. Or am I confused?

**Comment by petervo** [comment]
yes i agree, the one from sudo there isn't much we can do about

**Comment by stefwalter** [comment]
> yes i agree, the one from sudo there isn't much we can do about

At present we only try to escalate privileges once per login ... for better or worse. That means this won't be spamming to the logs constantly.

**Comment by stefwalter** [comment]
Fixed check-docker.

**Pull request closed without merging**
