### PR TITLE
Update fedora images now that f24 is EOL

### PR DESCRIPTION
**Pull request by petervo**
Bumps containers and testing to fedora 26 and removed fedora 24.

 * [x] image-refresh fedora-25
 * [x] image-refresh fedora-26
 * [x] image-refresh fedora-testing
 * [x] image-refresh openshift

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-x6t6m.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170905-000404/

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-20170905-003939

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170905-004444/

**Comment by cockpituous** [comment]
image-refresh fedora-25 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-25-20170905-011515

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170905-011515/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170905-011515/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-ps164.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170905-014646/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170905-014646/

**Comment by petervo** [comment]
Blocked on https://bugzilla.redhat.com/show_bug.cgi?id=1483553

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-9kgxz.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170906-210808/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-l68xd.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170906-210808/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170906-210808/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-ghxcx.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170906-215454/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170906-215454/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-9gmd4.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170906-230707/

**Comment by cockpituous** [comment]
image-refresh fedora-25 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-25-20170906-235252

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-csjnc.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170906-235656/

**Comment by cockpituous** [comment]
image-refresh fedora-26 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-26-20170907-004040

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-csjnc.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170907-004141/

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-20170907-010909

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-csjnc.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170907-010909/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-testing-20170907-015555

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170907-033737/

**Comment by cockpituous** [comment]
image-refresh fedora-25 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-25-20170907-041010

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-9mk9t.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7607-20170907-041111/

**Comment by petervo** [comment]
Added a work around for the overlay fs docker regression that prevented new images from being created. Also a few more test fixes

**Comment by martinpitt** [comment]
@petervo: Wouldn't it make sense to move to avocado/fedora-26 right away? Or was that deliberate, is avocado broken in F26?

**Comment by petervo** [comment]
@martinpitt I was just trying to keep the OS coverage we have now where PRs get tested over 3 fedora versions. If we move selenium/avocado to 26 we'll be down to 2.

**Comment by martinpitt** [comment]
It looks like [testNodes (check_kubernetes.TestKubernetes](https://fedorapeople.org/groups/cockpit/logs/pull-7607-20170907-111111-77e5ac22-verify-rhel-7-4/log.html#47) always fails, but I'll retry the lot again.

**Comment by martinpitt** [comment]
@petervo: `testFedora23Direct` fails awfully often with `Error: received unsupported version in init message: undefined`. Do you happen to have a clue what's wrong there?

**Comment by petervo** [comment]
> Do you happen to have a clue what's wrong there?

It's a race that I haven't tracked down the cause yet. But i don't think this the place to solve it.

**Comment by petervo** [comment]
Just FYI avocado/fedora-24 is supposed to fail as this PR is replacing it.

**Comment by martinpitt** [comment]
Nice, all green now!

**Pull request closed without merging**
