### PR TITLE
RHEL/CentOS image updates

### PR DESCRIPTION
**Pull request by martinpitt**
See individual commits for details. In particular this fixes the current rhel-x image build failure.

 * [x] image-refresh rhel-7-5
 * [x] image-refresh rhel-7-6
 * [x] image-refresh centos-7
 * [x] image-refresh rhel-x

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-ll7bp.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9894-20180823-101919/

**Comment by cockpituous** [comment]
image-refresh rhel-7-5 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-5-20180823-110303

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-hpm74.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9894-20180823-110606/

**Comment by cockpituous** [comment]
image-refresh rhel-7-6 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-6-20180823-113838

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-ll7bp.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9894-20180823-114141/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9894-20180823-114141/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-fc0hg.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9894-20180823-114141/

**Comment by cockpituous** [comment]
image-refresh rhel-x done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-x-20180823-121111

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-gr0n9.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9894-20180823-121313/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-pb42h.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9894-20180823-122121/

**Comment by martinpitt** [comment]
Pulling in the change from #9800 too, and rebuilding.

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20180823-125151

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-lg83p.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9894-20180823-125656/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-fc0hg.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9894-20180823-125656/

**Comment by cockpituous** [comment]
image-refresh rhel-7-5 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-5-20180823-130909

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-24b9n.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9894-20180823-131212/

**Comment by cockpituous** [comment]
image-refresh rhel-7-5 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-5-20180823-134141

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-0xbh5.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9894-20180823-134545/

**Comment by cockpituous** [comment]
image-refresh rhel-7-6 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-6-20180823-134949

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-lg83p.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9894-20180823-135050/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-9cwml.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9894-20180823-143232/

**Comment by cockpituous** [comment]
image-refresh rhel-x done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-x-20180823-144949

**Comment by cockpituous** [comment]
image-refresh rhel-x done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-x-20180823-150303

**Comment by martinpitt** [comment]
@mvollmer: Apparently a lot of storage tests fail on rhel-x; can you please have a look?

**Comment by martinpitt** [comment]
rhel-7-6-distropkg exposes a few forgotten test skips, will fix.

**Comment by martinpitt** [comment]
@mvollmer: Oh, is it possible that all the LUKS tests fail on rhel-x due to the switch to LUKS2? Then I think we should temporarily skip the tests to unblock the image refreshes, and then fix them in the LUKS v2 PR.

**Comment by martinpitt** [comment]
rhel-x has more regressions, *sigh*. Seems FreeIPA client got broken (sudo never starts working), firewall  page never appears, and check-login behaves weirdly too. I can reproduce these locally. testLvm is just a flake.

**Comment by martinpitt** [comment]
I pushed fixes for the rhel-7-6-distropkg regressions and naughty overrides for the networking and FreeIPA regressions (I reported the latter to bugzilla).

**Comment by mvollmer** [comment]
I haven't checked whether rhel-x now indeed creates LUKSv2 by default, but the test failures are consistent with that, except one.

testClevisTang and testSlots should be skipped, they will be fixed in #9852.

testHiddenLuks expects a particualr clear text size, but LUKSv2 gives us a different size.

testResizeLuks makes me think that rhel-x now has a newer version of UDisks2 that actually does support LUKS resizing -> we need to activate the other branch of the test for rhel-x.

I'll confirm this and push some fixes once I have downloaded the image.

**Comment by mvollmer** [comment]
Okay, LUKSv2 is the new default on rhel-x, and what I said earlier was correct.

However, resizing LUKSv2 might need a passphrase and since Cockpit doesn't provide one, it fails.  Thus, I have skipped that test on rhel-x as well, to be fixed in #9902.

**Comment by martinpitt** [comment]
The rhel-7-6-distropkg commit was missing a spot, pushed.

**Comment by martinpitt** [comment]
Yay, all green now, just a semaphore flake. Restarting that.

**Pull request merged**
