### PR TITLE
bots: Install socat on Debian/Ubuntu images [no-test]

### PR DESCRIPTION
**Pull request by martinpitt**
This will be used in PR #11813, and it's a generally useful swiss army
knife for testing network related things.

 * [x] image-refresh debian-stable
 * [x] image-refresh debian-testing
 * [x] image-refresh ubuntu-stable
 * [x] image-refresh ubuntu-1804

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-r42wl.
Log: https://209.132.184.41:8493/logs/image-refresh-11815-20190513-155656/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-stable-20190513-163333

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-0jpkq.
Log: https://209.132.184.41:8493/logs/image-refresh-11815-20190513-162323/

**Comment by cockpituous** [comment]
image-refresh debian-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-testing-20190513-164545

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-twhgs.
Log: https://209.132.184.41:8493/logs/image-refresh-11815-20190513-164646/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-stable-20190513-170606

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-hptzj.
Log: https://209.132.184.41:8493/logs/image-refresh-11815-20190513-171515/

**Comment by cockpituous** [comment]
image-refresh ubuntu-1804 done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-1804-20190513-182929

**Comment by martinpitt** [comment]
The [xterm crash](https://209.132.184.41:8493/logs/pull-11815-20190514-055555-9d57bc61-verify-ubuntu-stable/log.html#106) is most likely fallout from the recent xterm update, and happens in [other places](https://209.132.184.41:8493/logs/pull-11812-20190514-061212-8f42f5ca-verify-rhel-8-1/log.html#104) as well. @marusak is investigating this now, so this doesn't need to block this refresh.

**Pull request merged**
