### PR TITLE
lib: Remove plot.css

### PR DESCRIPTION
**Pull request by mvollmer**
The new SVG plots have their own CSS.

### CODE REVIEW

**Review by martinpitt — CHANGES_REQUESTED** [review]
Oh, that easy, nice! Note you need to rebase, there's a conflict now. Sorry for the collision.

I didn't visually test this, I assume you did.

**Review by martinpitt — CHANGES_REQUESTED** [review]
Looks like a git pilot error, you now don't drop the file any more.

**Comment by mvollmer** [comment]
> Looks like a git pilot error, you now don't drop the file any more.

Woops, re4solving merge

**Review by martinpitt — APPROVED** [review]
Cheers!

**Pull request merged**
