### PR TITLE
test: Ignore "**" journal messages.

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by stefwalter** [comment]
I don't think this makes sense. What does it try to fix? These are usually messages we should be on the lookout for, no?

**Comment by mvollmer** [comment]
This should only catch messages that are exactly two stars "**".

 This run has one:
http://files.cockpit-project.org/hubbot/c945b899da8ecab8a31f66c28b5399c53e82c4de_f22_x86-64.1/hubbot.html

```
Unexpected journal message '**'
```

I am not sure where they come from.  I tried to quickly find the source in glib, but couldn't.

**Comment by dperpeet** [comment]
@petervo wants to research the source of the messages a bit more before we merge the workaround

**Comment by stefwalter** [comment]
The source of the stars are in the g_log_default_handler in Glib ... when a message is logged with out a domain (such as from an application itself, rather than a library) ... it has stars at the front.

However, for them to appear on their own line they would need their own write() ... and stderr would need to be connected to the journal. That's not the case in glib as far as I can see:

https://git.gnome.org/browse/glib/tree/glib/gmessages.c#n1438

@mvollmer I would like to see the message following the stars. Have you been able to reproduce this? That would give us clues as to where it's from. Having these stars show up in the logs as a result of Cockpit wouldn't be a good thing if it happens regularly, so I'm hesitant just to ignore this in our tests and forget about it.

**Comment by mvollmer** [comment]
> However, for them to appear on their own line they would need their own write()

Yes, exactly.  I found the stars but couldn't explain how they ended up on their own line.

> I would like to see the message following the stars. 

It was this pattern, if I remember correctly:

```
GLib-GIO:ERROR:gdbusobjectmanagerserver\\.c:.*:g_dbus_object_manager_server_emit_interfaces_.*: assertion failed \\(error == NULL\\): The connection is closed \\(g-io-error-quark, 18\\)",
        "Error sending message: The connection is closed
```

I think the stars appeared in the journal after merging #2489, and this was a quick fix to get the tests to pass again.  I haven't seen the stars since then, so maybe we don't need to do anything, actually.
Odd....

**Comment by stefwalter** [comment]
Interesting. This message in question is really a broken error and we should fix it upstream:

```
GLib-GIO:ERROR:gdbusobjectmanagerserver\\.c:.*:g_dbus_object_manager_server_emit_interfaces_.*: assertion failed \\(error == NULL\\): The connection is closed \\(g-io-error-quark, 18\\)",
        "Error sending message: The connection is closed
```

**Comment by stefwalter** [comment]
Filed patch upstream: https://bugzilla.gnome.org/show_bug.cgi?id=753278

**Comment by stefwalter** [comment]
The actual source of the error: 

https://git.gnome.org/browse/glib/tree/glib/gtestutils.c#n2326

This is using g_printerr() which prints out bits one at a time to the file descriptor and ends up as separate log entries. Will post a fix at least for our own cockpit processes.

**Comment by mvollmer** [comment]
> This is using g_printerr() which prints out bits one at a time to the file descriptor and ends up as separate log entries. Will post a fix at least for our own cockpit processes.

Ahh, interesting.  Great that you have figured this out.

**Comment by stefwalter** [comment]
>> This is using g_printerr() which prints out bits one at a time to the file descriptor and ends up as separate log entries. Will post a fix at least for our own cockpit processes.

> Ahh, interesting. Great that you have figured this out.

Except that was wrong. The newline is explicitly added in glib/gtestutils.c

**Comment by mvollmer** [comment]
I don't see tests failing because of this anymore.  Let's close this.

**Pull request closed without merging**
