### PR TITLE
[no-test] bots: Update fedora-i386 to Fedora 30

### LINKED ISSUE #11359: Image refresh for fedora-i386
Image refresh for fedora-i386
 * [ ] image-refresh fedora-i386

### PR DESCRIPTION
**Pull request by martinpitt**
Switch to virt-install, so that we build it in the same way as the
x86_64 Fedora images.

Fixes #11359

 * [x] image-refresh fedora-i386

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-jn8br.
Log: https://209.132.184.41:8493/logs/image-refresh-11952-20190528-200505/

**Comment by cockpituous** [comment]
image-refresh in progress on 4-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-11952-20190528-202222/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-02.
Log: https://209.132.184.41:8493/logs/image-refresh-11952-20190528-201818/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-ci-srv-04.
Log: https://209.132.184.41:8493/logs/image-refresh-11952-20190528-203535/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-10.
Log: https://209.132.184.41:8493/logs/image-refresh-11952-20190528-202424/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-11952-20190528-201818/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-cockpit-9.
Log: https://209.132.184.41:8493/logs/image-refresh-11952-20190528-204747/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-9.
Log: https://209.132.184.41:8493/logs/image-refresh-11952-20190528-204747/

**Comment by cockpituous** [comment]
image-refresh fedora-i386 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-i386-20190528-212828

**Comment by cockpituous** [comment]
image-refresh fedora-i386 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-i386-20190528-212929

**Comment by martinpitt** [comment]
My locally built image seems to behave quite fine, I was hopeful that the reboot woes would be gone. But apparently they aren't on the infra :sob:

**Comment by martinpitt** [comment]
@KKoukiou : I think these two test failures are real. But I'm still a bit eager to land this, as f-i386 doesn't run on PRs, and it's at least a lot better than the ancient image that we have right now. I. e. it's a better basis from which to start fixing  things.

**Pull request merged**
