### PR TITLE
Image refresh for fedora-26

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for fedora-26 in process on cockpit-10.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-26-2017-04-20/

### CODE REVIEW

**Comment by martinpitt** [comment]
```
# testNegotiate (check_realms.TestKerberos)
Unexpected journal message 'sudo: unable to load /usr/lib64/libsss_sudo.so: /usr/lib64/libsss_sudo.so: cannot open shared object file: No such file or directory'
Unexpected journal message 'sudo: unable to initialize SSS source. Is SSSD installed on your machine?'
```
That seems to be an actual regression on the image, I'll take a look.

**Comment by martinpitt** [comment]
This library is provided by the `libsss_sudo` package which exists on the F25 image, but it's not installed on the F26 image any more. It's not a dependency of `sssd`, and can be removed, so supposedly it's just a recommends of something. I pushed a fix, will rebuild the image now.

**Comment by martinpitt** [comment]
bot: Image refresh for fedora-26

**Comment by cockpituous** [comment]
Image creation for fedora-26 in process on cockpit-10.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-26-297e4c311820f302fd3a6efd195467a26fb06cfd/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-fedora-26-297e4c311820f302fd3a6efd195467a26fb06cfd

**Comment by martinpitt** [comment]
The test succeeded, but was misattributed as "failed" due to PR #6354 again.

**Comment by martinpitt** [comment]
We are back to the test succeeding, but the kubernetes known issue being (mis)counted as a failure. @petervo, do you mind reviewing/landing this? Thanks!

**Comment by petervo** [comment]
Good enough, merging

**Pull request closed without merging**
