### PR TITLE
machines: rewrite VM delete dialog to use unsorted list html elements

### LINKED ISSUE #11374: machines: delete image dialog text overflows
Cockpit version: 183
OS: Fedora Server 29
Page: Machines

The text in the delete image dialog overflows if the text strings are very long.

Steps to reproduce
1. Create a VM with a very long name
2. Delete that VM

Screenshot from 2019-03-12 10-47-02

### PR DESCRIPTION
**Pull request by KKoukiou**
Previously it was using tables, which are behaving bad in small screens.

Fixes #11374

### CODE REVIEW

**Comment by KKoukiou** [comment]
@garrett I don't know how to get the label stretch and tsake 100% width of the line, so that I can use float: right on the disk file path elements.
Can you please give me a css hint?

**Comment by garrett** [comment]
I'm looking at this and have different suggestions depending on circumstances.

1. Firstly, the container for the row is set to display: `flex-inline`, which wouldn't span across. `display: flex` would.
2. Secondly, after fixing the container to be a block element instead of an inline one, we'd want to adjust the positioning at that level or change one or more of the flex values for the immediate children.

Now this is what I mean by "depends":

- If there's more than one item, then we cannot align the labels, unless:
  - we fix the size
  - use grid and a trick to have nested inheriting grids down the elements (as there's no subgrid yet and `display: contents` breaks accessibility everywhere)... so there are grids in grids in grids, but the `grid-template` and `grid-gap` are at the top level where it is computed and the inherits on each of the children should then pull down the same sizing 😲

...so... will there be more than 1 item in the list?

**Comment by garrett** [comment]
I've added a disk on one test VM from another and it didn't make the list longer. But that's expected, as it's only the ones from the VM.

Then, I created a new disk specific to that VM... and when going to delete it, I still see just 1 disk. Should this one be added to the list of disks that it should delete in the dialog? I should see two disks now, right?

**Comment by garrett** [comment]
Inherit demo: https://codepen.io/garrett/pen/RdxLYa

After playing with it, I think having a specified width for the labels and using flex is probably better, as then we can (easily) slide the path under.

Or we could just have the path under the label too. :thinking:

**Comment by garrett** [comment]
Here's a much simpler alternate using grid for alignment so the name & path are aligned to each other and the checkbox is vertically aligned to the name:

https://codepen.io/garrett/pen/RdxLYa

Screenshot:

Screenshot_2019-03-14 grid inherit experiment 2

**Comment by garrett** [comment]
**Note**: I tried the inherit trick and also using CSS to trick the elements into being "table"s, "table-row"s, and "table-cells" — and neither worked. I think we'd have to flatten the HTML out to make either work... or wait for CSS subgrid support.

Changing the design so the label is at the bottom let us not have to worry about the horizontal alignment where the widths would line up. We now only need to worry that the checkboxes are the same width (and they are, of course).

**Comment by garrett** [comment]
## Screenshots in action

### Standard

Screenshot_2019-03-14 Virtual Machines - Sunny

### Extreme narrow mobile (iPhone SE size)

Screenshot_2019-03-14 Virtual Machines - Sunny(1)

---

I removed `ct-form-layout` from the mix, as we don't need special layout here. As a result, I had to unbreak the checkboxes from PF manually. (They normally do some weird absolute positioning & negative margin hacks.)

**Comment by garrett** [comment]
BTW: This _should_ support more than one item in the list, but even after adding an additional disk, I do not see it listed, so I cannot test it here.

**Comment by KKoukiou** [comment]
Squashed @garrett s commits to the initial one, and added the test fix. @garrett can you reapprove?

**Comment by martinpitt** [comment]
A similar change needs to happen to the selenium tests:
```
testlib_avocado.exceptions.SeleniumElementFailure: Unable to locate name: #vm-staticvm-delete-modal-dialog tbody tr:nth-of-type(1) input
```
Otherwise this LGTM!

**Comment by KKoukiou** [comment]
Is this expected to fail? https://209.132.184.41:8493/logs/pull-11390-20190315-122222-9d3dadef-selenium-firefox/log.html#24

I am not really familiar with these tests yet.

**Comment by martinpitt** [comment]
@KKoukiou : that's a bug in our HTML log wrapper. These "0 seconds" tests get skipped, but are shown as failed.

**Pull request merged**
