### PR TITLE
unit-tests: Install python3-flake8 from unstable

### PR DESCRIPTION
**Pull request by mvollmer**
Fixes: #19725 

Refresh run: https://github.com/cockpit-project/cockpit/actions/runs/7166956574

### CODE REVIEW

**Comment by mvollmer** [comment]
Oh, I thought there is a difference with reposchutz when I make a PR from origin. I guess not.

**Comment by mvollmer** [comment]
I don't know how to trigger a unit-tests-refresh run with the changes in this PR.

**Comment by martinpitt** [comment]
Nice, thanks! After that lands, we need to refresh the real container on https://github.com/cockpit-project/cockpit/actions/workflows/unit-tests-refresh.yml . On the "Run workflow" button you can also select a non-main branch FYI.

**Review by martinpitt — APPROVED** [review]
Could have been no-test.

**Comment by mvollmer** [comment]
> Nice, thanks! After that lands, we need to refresh the real container on https://github.com/cockpit-project/cockpit/actions/workflows/unit-tests-refresh.yml . On the "Run workflow" button you can also select a non-main branch FYI.

Ah, right, but only from "origin", but now this _is_ in origin (for a different reason).

**Comment by martinpitt** [comment]
The production refresh run succeeded, and this is mostly green, so: go! :rocket: Thanks!

**Pull request merged**
