### PR TITLE
bots: Move container/ tests to Fedora 30

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh openshift
 * [x] image-refresh fedora-30

### CODE REVIEW

**Comment by martinpitt** [comment]
Damn you, rpmlint -- missing dependencies?
```
====== rpmlint on srpm =====
sh: /usr/bin/python: No such file or directory
```
Will retry this after #11676.

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-2fd63.
Log: https://209.132.184.41:8493/logs/image-refresh-11677-20190428-105858/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-0l9sc.
Log: https://209.132.184.41:8493/logs/image-refresh-11677-20190428-105858/

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-20190428-112121

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-fjlh6.
Log: https://209.132.184.41:8493/logs/image-refresh-11677-20190428-112323/

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-8bqxn.
Log: https://209.132.184.41:8493/logs/image-refresh-11677-20190428-112323/

**Comment by cockpituous** [comment]
image-refresh fedora-30 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-30-20190428-114848

**Comment by martinpitt** [comment]
Oh meh, we don't actually build cockpit-kubernetes on  Fedora 30 any more, so we can't actually run container/kubernetes test there. container/bastion would work, but it's difficult to mix versions there. Let's just bin that for a while until we stop supporting Fedora 29, then we can drop the kubernetes container at all.

**Pull request closed without merging**
