### PR TITLE
test: Refactor accounts test

### PR DESCRIPTION
**Pull request by skobyda**
TestAccouts.testBasic way too big. Split it into several smaller tests. Additionally, abstract account creation dialog handling into a separate method.

Split from https://github.com/cockpit-project/cockpit/pull/18234

### CODE REVIEW

**Review by martinpitt — DISMISSED** [review]
Thanks! This looks good to me in general. @KKoukiou is also working on the accounts page and tests quite heavily, can you please coordinate with her?

**Comment by skobyda** [comment]
If you mean `https://github.com/cockpit-project/cockpit/pull/18348/`, then it looks like those 2 PRs should not collide, as they change different fix. Perhaps only 1-2 simple merge conflicts

**Review by KKoukiou — APPROVED** [review]

**Comment by martinpitt** [comment]
Landing. The accounts tests are still notoriously flaky, and this at least helps to make them easier to debug. The TF failures usually happen with out of date branches (this one is 14 commits behind main).

**Comment by martinpitt** [comment]
I'm afraid this is a very likely candidate for having broken the accounts tests on the TF  in general, like [here](https://artifacts.dev.testing-farm.io/6c941e8d-aa6b-4967-8cc4-24cc64592f8c/) or [here](https://artifacts.dev.testing-farm.io/2126f39f-d12c-4261-900d-19678f3dcf3f/). So in the future, let's not land this much red any more, and rebase our branches.

**Pull request merged**
