### PR TITLE
shell: Catch up with docker changes

### PR DESCRIPTION
**Pull request by mvollmer**
No more "docker" group: Access docker via 'sudo' and adapt tests that assume the "Container Administrator" role.
    
No more "docker.socket" unit: Just use "docker.service".

Depends on #1751.

### CODE REVIEW

**Comment by mvollmer** [comment]
(This might actually need the new docker version to pass the tests.)

**Comment by stefwalter** [comment]
Do we need to disable the 'Container admin' stuff in the 'Admin Accounts' Roles UI, if there's no docker group on the system?

**Comment by mvollmer** [comment]
> Do we need to disable the 'Container admin' stuff in the 'Admin Accounts' Roles UI, if there's no docker group on the system?

It disables itself automatically, but we can clean up the code.

**Comment by stefwalter** [comment]
> It disables itself automatically, but we can clean up the code.

No that's perfect. We want it to show up if the docker group exists.

**Comment by mvollmer** [comment]
The storage failure also seems genuine.

**Comment by mvollmer** [comment]
> The storage failure also seems genuine.

Regression in lvm2app: https://www.redhat.com/archives/lvm-devel/2015-January/msg00075.html

**Comment by stefwalter** [comment]
The Docker changes look good.

**Comment by mvollmer** [comment]
Included in #1755.

**Pull request closed without merging**
