### PR TITLE
bots: Move OpenShift image to Fedora 29

### PR DESCRIPTION
**Pull request by martinpitt**
* [ ] FAIL: image-refresh openshift

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-cx7nw.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10533-20181108-083030/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10533-20181108-083030/

**Comment by martinpitt** [comment]
Hmm, behaviour of "oc" changed significantly in Fedora 29, I see this locally as well when controlling our CI cluster.

**Comment by martinpitt** [comment]
The `wait endpoint_has_address docker-registry` times out, and the endpoint never gets created:
```
# oc get endpoints docker-registry
NAME              ENDPOINTS   AGE
docker-registry   <none>      33m

# oc describe pod docker-registry-1-deploy
[...]
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  4m (x107 over 35m)  default-scheduler  0/1 nodes are available: 1 NodeNotReady.
```

What's really odd is that there are *zero* running docker containers. I would have expected at least some.

The logs have a bunch of recurring errors:
```
Nov 14 06:41:36 f1.cockpit.lan openshift-run[9628]: I1114 06:41:36.208758    9630 kubelet.go:1779] skipping pod synchronization - [Failed to start ContainerManager Delegation not available for unit type]
Nov 14 06:41:36 f1.cockpit.lan openshift-run[9628]: E1114 06:41:36.374800    9630 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
Nov 14 06:41:36 f1.cockpit.lan openshift-run[9628]: W1114 06:41:36.376491    9630 reflector.go:341] github.com/openshift/origin/vendor/k8s.io/client-go/informers/factory.go:86: watch of *v1beta1.PodDisruptionBudget ended with: The resourceVersion for the provided watch is too old.
```

There are some [related](https://bugzilla.redhat.com/show_bug.cgi?id=1558425) [issues](https://github.com/openshift/origin/issues/18928), but I didn't manage to get it to work with setting the cgroup driver to `cgroupfs` instead of `systemd`. This is apparently fixed in later OpenShift releases, I'll check if these work.

**Comment by martinpitt** [comment]
I tried with OpenShift 3.11, and no better. So let's skip this for now. Maybe it makes more sense to run this on CentOS, then we don't need to update the base image so often.

**Pull request closed without merging**
