### PR TITLE
test: Prevent grub2-mkconfig from clobbering BLS entries

### PR DESCRIPTION
**Pull request by mvollmer**
Running grub2-mkconfig will execute /etc/grub.d/10_linux, which will update /boot/loader/entries with the kernel command line from /etc/default/grub.  On at least rhel-9, /etc/default/grub contains a empty GRUB_CMDLINE_LINUX (while /etc/kernel/cmdline is correct), and grub2-mkconfig would thus clobber the BLS entries.

Concretely, "net.ifnames=0" would be lost, and the inter-VM network 10.111.112.0 would not be available anymore since it has been configured using the old name of the interface.

This has only recently become a actual problem since earlier versions of grub2-mkconfig would only look at BLS entries that match the current machine ID.  Our rhel images have entries like

    ffffffffffffffffffffffffffffffff-4.18.0-458.el8.x86_64.conf

that would be missed earlier.  Now all entries are processed.

The fundamental issue is probably that /etc/default/grub does not have the correct cmdline in it, but it is easier to stop this clobbering by moving the files away temporarily than to fix GRUB_CMDLINE_LINUX in /etc/default/grub.

### CODE REVIEW

**Comment by mvollmer** [comment]
I would file a bug but I don't know where.

**Comment by martinpitt** [comment]
The approach is okay for me, but it does not work on [CentOS 8](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18382-20230221-121356-9a1f1955-centos-8-stream/log.html#181-2) and [RHEL 8](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18382-20230221-121356-9a1f1955-rhel-8-8/log.html#181-2)

**Comment by martinpitt** [comment]
We already encountered similar bugs before, they were filed against [grub2](https://bugzilla.redhat.com/show_bug.cgi?id=1785460) or [distribution](https://bugzilla.redhat.com/show_bug.cgi?id=1646976) if the file isn't owned by a package. I'd start with grub2, and people there will know better where to reassign.

**Comment by martinpitt** [comment]
@mvollmer : Can you please rebase in your next round to get the TF tests green?

**Review by martinpitt — APPROVED** [review]
Thanks, this ought to work now. bots have the last word, but LGTM!

**Comment by martinpitt** [comment]
You didn't rebase, so TF failures are expected; at least for this PR I am very sure that it does not affect gating tests, so I'm willing to let it slide. (The last time I did that we got burned and actually broke the tests..)

**Pull request merged**
