### PR TITLE
users: Port password dialogs to ct-form-layout

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by martinpitt** [comment]
pkg/users has two more dialogs, but they don't have labels in front:

expire-old

@garrett, as per IRC discussion they can't be ported to `ct-form-layout` yet, right?

The password dialogs now look slightly different, but mostly the labels look not disabled.

master:
create-old
set-password-old

This PR:
create-new
set-password-new

**Comment by garrett** [comment]
> as per IRC discussion they can't be ported to ct-form-layout yet, right?

It _might_ work. I haven't tried it. It could be the case where the label column collapses and isn't relevant here. So it might just automatically work. 

However, I _think_ I set a min-width on the labels, so there might be space. I can either check for `:empty` or remove the min-width constraint. 

> The password dialogs now look slightly different, but mostly the labels look not disabled.

Expected behavior. This is how PatterFly upstream does labels. @andreasn and I discussed this in IRC last year and decided to go with the upstream style instead of persisting with our own.

(FWIW: Right now, Cockpit has a mix of styles, even before porting to the new layout.)

**Comment by garrett** [comment]
Hmm, label for the "Lock Account" checkbox label is incorrect. Is the HTML correct? (Checking...)

**Comment by martinpitt** [comment]
`<label className="checkbox-inline"` should help with the alignment, let's try that.

**Comment by martinpitt** [comment]
I pushed the `checkbox-inline` fix and updated the screenshot, the alignment is correct now.

**Pull request merged**
