### PR TITLE
kubernetes: Use filtered namespace when deploying

### PR DESCRIPTION
**Pull request by petervo**
Fixes: #2739

### CODE REVIEW

**Comment by stefwalter** [comment]
This looks good. Just needs a test.

**Comment by petervo** [comment]
Test is in

**Comment by stefwalter** [comment]
Talking to openshift here and I see 'Namespace' as a control label:

screenshot from 2015-09-15 11-18-43

In addition, I believe that the namespace should default to the current namespace if one is already selected.

After deploying to a new namespace I didn't see a switch to the new namespace.

**Comment by stefwalter** [comment]
I must have been on the wrong branch when I tested this.

**Pull request closed without merging**
