### PR TITLE
Image refresh for fedora-24

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for fedora-24 in process on host32-rack06.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-24-2016-03-11/

### CODE REVIEW

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by stefwalter** [comment]
Adding virt-install to the verify docker image.

**Comment by stefwalter** [comment]
The following is needed on each verify machine:

```
sudo docker pull cockpit/infra-verify
sudo systemctl restart cockpit-verify
```

Note that the latter command will kill any running tests.

@dperpeet This is something we need to get right before scaling out the verify machines further.

**Comment by stefwalter** [comment]
@dperpeet How do you think we should do this in the future?

**Comment by stefwalter** [comment]
@mvollmer How do we trigger this build again?

**Comment by mvollmer** [comment]
> How do we trigger this build again?

`./github-trigger --image fedora-24`

I just did that: #3993.

**Comment by dperpeet** [comment]
> @dperpeet How do you think we should do this in the future?

discussion on updating verifiers moved to #3996

**Comment by dperpeet** [comment]
@petervo can we close this, since you built a newer one in #3990?

**Comment by stefwalter** [comment]
Image creation failed, closing and will wait for next one to kick in.

**Pull request closed without merging**
