### PR TITLE
Fix races in container tests waiting for Cockpit running

### PR DESCRIPTION
**Pull request by stefwalter**
This function is used for more than just atomic images. Move the check for the atomic image into the caller.
    
In addition, make the check for cockpit running to be far more resilient, timeout hung connections, and setup a longer default.
    
This fixes a whole slew of testing races

### CODE REVIEW

**Comment by stefwalter** [comment]
Previously this was hanging on the *-atomic tests. So I woludn't merge this until both those, and the container/kubernetes tests pass.

**Comment by petervo** [comment]
This seems to have drastically slowed down the running of the container and atomic tests. Needs more investigation.

**Comment by stefwalter** [comment]
Simplified the change.

**Comment by petervo** [comment]
Container is still really slow or failing. The issue seems to be that connections are accepted before the container is actually ready. Adding ```--max-time 2``` to the curl command fixes it for me.

**Comment by stefwalter** [comment]
Added max-time.

**Pull request closed without merging**
