### PR TITLE
DBG - see what happens with the global machines

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
The new code seems to work fine, but the first test run didn't have any global machine resets in it, so the interesting part hasn't been tested yet.

**Comment by mvollmer** [comment]
`check-testlib` has found a bug, nice.

**Comment by martinpitt** [comment]
@mvollmer: You need to rebase bots #1240 to have it pick up the new services image. The previous one is actually still available, so I'm not entirely sure why image-download fails. (Yet another bug..)

**Comment by mvollmer** [comment]
I don't see any output from things like `self.assertEqual` failing...

**Comment by mvollmer** [comment]
```
qemu-img: /tmp/q0vg7qvy.qcow2: Could not write qcow2 header: No space left on device
```

Oho, what did I do.

**Comment by mvollmer** [comment]
The stress test with a 30 second timeout for each non-destructive test was successful. A lot of global machines were restarted, and did so cleanly.

**Comment by mvollmer** [comment]
Job done, thanks!

**Pull request closed without merging**
