### PR TITLE
packagekit: Fix dnf-autmatic timer parsing, port to standard Promise

### PR DESCRIPTION
**Pull request by martinpitt**
https://bugzilla.redhat.com/show_bug.cgi?id=1829685

### CODE REVIEW

**Comment by martinpitt** [comment]
whoops, need to [fix the cleanup](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-14035-20200505-193210-b40fc1db-ubuntu-2004/log.html#252-2)

**Comment by martinpitt** [comment]
Remaining failures are unrelated. I sent a fix for the [iptables-restore crash on debian-testing](https://logs.cockpit-project.org/logs/pull-14035-20200506-042636-7f01329f-debian-testing/log.html#151-2) to https://github.com/cockpit-project/bots/pull/836 , and the others are the usual testDetachDisk machines failures, which isn't changed here.

**Comment by martinpitt** [comment]
@mvollmer, @KKoukiou : Friendly reminder?

**Comment by mvollmer** [comment]
"packagekit: Fix dnf-autmatic timer parsing" -> "dnf-automatic"

**Comment by martinpitt** [comment]
Pushed the typo fix without any changes (see interdiff link above)

**Pull request merged**
