### PR TITLE
bots: Retry tests when flakey

### PR DESCRIPTION
**Pull request by stefwalter**
Lets retry tests when they are seen as flaky by the clustering logic.
    
This adjusts the TAP output from the tests somewhat for retried tests
so that these still get registered as failures for the clustering logic
but don't apply to the success or failure of the entire test suite.

 * [x] learn-tests
 * [x] Look through the log output

### CODE REVIEW

**Comment by cockpituous** [comment]
tests-data command failed: http://fedorapeople.org/groups/cockpit/logs/learn-tests-9014-20180419-132121/

**Comment by cockpituous** [comment]
learn-tests in progress on cockpit-tasks-jbc21.
Log: http://fedorapeople.org/groups/cockpit/logs/learn-tests-9014-20180419-134242/

**Comment by cockpituous** [comment]
learn-tests in progress on cockpit-tasks-0z2d6.
Log: http://fedorapeople.org/groups/cockpit/logs/learn-tests-9014-20180419-134242/

**Comment by cockpituous** [comment]
tests-data command failed: http://fedorapeople.org/groups/cockpit/logs/learn-tests-9014-20180419-134242/

**Comment by cockpituous** [comment]
learn-tests in progress on cockpit-tasks-fckv7.
Log: http://fedorapeople.org/groups/cockpit/logs/learn-tests-9014-20180419-142424/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
learn-tests in progress on cockpit-tasks-zj02v.
Log: http://fedorapeople.org/groups/cockpit/logs/learn-tests-9014-20180419-175050/

**Comment by cockpituous** [comment]
learn-tests in progress on cockpit-tasks-c0x63.
Log: http://fedorapeople.org/groups/cockpit/logs/learn-tests-9014-20180419-175050/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
learn-tests in progress on cockpit-tasks-kts6h.
Log: http://fedorapeople.org/groups/cockpit/logs/learn-tests-9014-20180419-210303/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
learn-tests in progress on cockpit-tasks-zj02v.
Log: http://fedorapeople.org/groups/cockpit/logs/learn-tests-9014-20180420-001616/

**Comment by stefwalter** [comment]
These jobs are aborting due to the logs timing out.

```
...
21688: Items to train
packet_write_wait: Connection to 152.19.134.199 port 22: Broken pipe
```

**Comment by stefwalter** [comment]
Added a ServerKeepAliveInterval option to ssh to fix that problem too.

**Comment by cockpituous** [comment]
learn-tests in progress on cockpit-tasks-gsmc2.
Log: http://fedorapeople.org/groups/cockpit/logs/learn-tests-9014-20180420-055353/

**Comment by stefwalter** [comment]
Successful run here: https://fedorapeople.org/groups/cockpit/logs/learn-tests-9014-20180420-055353/

**Comment by stefwalter** [comment]
Just one more tweak to make the log.html sink view a little more clear, as to which tests were retried.

**Comment by stefwalter** [comment]
Thanks. Merged.

**Pull request closed without merging**
