### PR TITLE
bridge: Implement minimum package version checks

### PR DESCRIPTION
**Pull request by stefwalter**
This is so packages can check that the Cockpit bridge and base package are at least a given version. We expect the bridge and base package to be shipped together.

### CODE REVIEW

**Comment by stefwalter** [comment]
screenshot from 2016-09-05 16-59-41

**Comment by larsu** [comment]
Cool!

I agree that versions should be strings, but that might look awkward when we switch to having only major versions.

Will the `requires` object ever have something other than `cockpit` in it?

Does `410 Gone` mess with caches? Isn't this a server error, which would suggst `5XX`?

Should we maybe mention the version that the package requires on the error page?

**Comment by stefwalter** [comment]
> I agree that versions should be strings, but that might look awkward when we switch to having only major versions.

We also use a nomenclature of "120.x" to indicate a version number between "120" and "121" during development. In addition I'd like to keep this flexible and allow dots. Lastly we need to support the fact that "0.114" is when our API went stable.

> Will the requires object ever have something other than cockpit in it?

Yes. At some point in the future it could. Hence the check ... if there's anything unrecognized in it, we treat the package as incompatible.

> Does 410 Gone mess with caches? Isn't this a server error, which would suggst 5XX?

Will look for a better number.

> Should we maybe mention the version that the package requires on the error page?

Sure.

**Comment by stefwalter** [comment]
>  Should we maybe mention the version that the package requires on the error page?

Done and updated screenshot above.

> Will look for a better number.

Using 503

**Comment by larsu** [comment]
Some of the selenium tests fail with

> This package requires cockpit 0.114 or later

**Comment by dperpeet** [comment]
atomic failures also seem significant

**Comment by stefwalter** [comment]
Updated the failure message to more clearly diagnose the issue that @dperpeet is referring too. Lets see.

**Comment by stefwalter** [comment]
This fix on the verify machines is needed: https://github.com/cockpit-project/cockpituous/pull/35

**Comment by dperpeet** [comment]
> This fix on the verify machines is needed: cockpit-project/cockpituous#35
> 
> Alternatively a 'git fetch origin' on each of the verify machines is work around.

all verify machines have the new verify container

**Pull request closed without merging**
