### PR TITLE
pf4: Add override to draw input group focus ring above other elements

### PR DESCRIPTION
**Pull request by garrett**
This is being tracked upstream at:
https://github.com/patternfly/patternfly/issues/3926

### CODE REVIEW

**Comment by garrett** [comment]
This PR fixes problems like the following:

Screenshot from 2021-03-15 11-50-21 entry issue
Screenshot from 2021-03-15 13-13-14
Screenshot from 2021-03-15 13-12-53
Screenshot from 2021-03-15 13-12-58
Screenshot from 2021-03-15 13-13-01

And here's the first one with the fix in Cockpit:

Screenshot from 2021-03-15 15-29-19

**Comment by garrett** [comment]
Whoops! _The URL itself_ to the upstream PF issue was originally truncated. Fixed. :wink:

**Review by KKoukiou — APPROVED** [review]
I am not very familiar with the z-index, but it fixes the issue indeed.

**Pull request merged**
