### PR TITLE
tools: Fix make-source running from a developer checkout

### PR DESCRIPTION
**Pull request by stefwalter**
One of the conditions for rerunning autogen.sh in tmp-dist
was inverted

### CODE REVIEW

**Comment by larsu** [comment]
I believe this is correct as it is right now. We want to build out-of-tree if a top-level Makefile doesn't exist or if it is merely the redirect Makefile for another out-of-tree build. We only build in tree when there's already an in-tree build configured.

**Comment by stefwalter** [comment]
> I believe this is correct as it is right now. We want to build out-of-tree if a top-level Makefile doesn't exist or if it is merely the redirect Makefile for another out-of-tree build. 

Why wouldn't we want to use the Makefile even when it's for an out-of-tree build? Especially now that I've fixed the logic to find the dist tarball.

**Comment by larsu** [comment]
> Why wouldn't we want to use the Makefile even when it's for an out-of-tree build? Especially now that I've fixed the logic to find the dist tarball.

Ah that changes things of course :)

We can get rid of the whole second term of the condition, then, and change the comment.

I kept it separate because I thought we might want a default configure. I only reused an existing configure in the in-tree case, because we can't add an out-of-tree one to it.

**Comment by stefwalter** [comment]
Updated comment.

**Comment by larsu** [comment]
Sorry, when I said "we can get rid of the second condition" I meant that we _have to_. Otherwise we'll break the alread-configured-in-tree case.

Or put differently: If we decide that we don't care how a previous build was configured, we only need to check if Makefile exist or not. If it does, use it, otherwise use tmp-dist.

Honestly, I'd prefer keeping it the way it was. I don't know what could go wrong when reusing an existing build, but if something does go wrong, it might be hard to track down if it happened because the developer's machine had a differently configured build lying around.

**Comment by stefwalter** [comment]
Removed the second condition.

> Honestly, I'd prefer keeping it the way it was. I don't know what could go wrong when reusing an existing build, but if something does go wrong, it might be hard to track down if it happened because the developer's machine had a differently configured build lying around.

For those of us who run the tests on our own machine, not having to rebuild everything is a massive time saver, and is the reason that this ```make dist``` approach is tenable for this use case. 

The build config shouldn't affect building a tarball. That's a mitigating factor. If it does affect making a tarball, then we need to fix that issue.

**Comment by larsu** [comment]
> For those of us who run the tests on our own machine, not having to rebuild everything is a massive time saver, and is the reason that this make dist approach is tenable for this use case.

> The build config shouldn't affect building a tarball. That's a mitigating factor. If it does affect making a tarball, then we need to fix that issue.

Fair points. Thanks for the fix. I'll wait for CI and merge it.

**Pull request closed without merging**
