### PR TITLE
add admonition for hacking with vagrant on osx

### PR DESCRIPTION
**Pull request by aweiteka**

### CODE REVIEW

**Comment by petervo** [comment]
@larsu, is this right thing to say? Or everyone need to do this to get the links in tools to be populated?

**Comment by larsu** [comment]
> @larsu, is this right thing to say? Or everyone need to do this to get the links in tools to be populated?

You actually need a full in-tree build to work properly with the vargant vm, because the build system needs to compile jsx and less files. So I think we should mention to call `./autogen.sh` and `make`. (`autogen.sh` calls `npm install`.)

Also, this issue is in no way OSX specific. It applies to all systems.

**Comment by aweiteka** [comment]
So this isn't a pure vagrant type of workflow. `npm install` then `vagrant up` seemed to support my UI work. Running `./autogen.sh` required automake pkg, then I hit this[1]. It's starting to feel pretty deep. Could we do some of this in the vagrant box? Or can I add a disclaimer to the admonition that this is for UI work only?

[1] https://paste.fedoraproject.org/365340/90940146/

**Comment by stefwalter** [comment]
> It's starting to feel pretty deep. Could we do some of this in the vagrant box? Or can I add a disclaimer to the admonition that this is for UI work only?

It is indeed. The workflow you described there  regressed recently with the React work from @dperpeet and @larsu ... but it's a necessary step. In addition @larsu is working on separating the build system of the UI parts from the backend.

**Pull request closed without merging**
