### PR TITLE
machines: Translate strings

### PR DESCRIPTION
**Pull request by marusak**
I noticed these two string that they are not translated.

### CODE REVIEW

**Comment by skobyda** [comment]
Thanks for catching this, while we have this PR open, we could also add translation to this places:

pkg/machines/components/storagePools/storageVolumeDelete.jsx - line 68
pkg/machines/components/create-vm-dialog/createVmDialog.jsx - line 417
pkg/machines/components/create-vm-dialog/createVmDialog.jsx - line 382

**Comment by marusak** [comment]
> pkg/machines/components/storagePools/storageVolumeDelete.jsx - line 68

Hmm, how should I fix this? I thought that `cockpit.ngettext` would deal with it automatically. But it is not in `po/cockpit.pot`.

**Comment by skobyda** [comment]
> Hmm, how should I fix this? I thought that `cockpit.ngettext` would deal with it automatically. But it is not in `po/cockpit.pot`.

You are right, I didn't notice that ngettext does translation for you.

**Comment by marusak** [comment]
> You are right, I didn't notice that ngettext does translation for you.

It should but in this case it does not. I dig into it and found the issue. I'll send separate PR that fixes that.

**Pull request merged**
