### PR TITLE
networking: Disable automatic switches in IP settings dialogs

### LINKED ISSUE #14290: Networking page fails to disable parts of the IPv[46] settings dialogs when selecting Shared/Disabled/Link local/Ignore
Cockpit version: 195.8 and 220 at least
OS: CentOS 7 and Fedora Workstation 32
Page: "Network"

When configuring IPv4/IPv6 settings for a device and selecting Link local, Shared, or Disabled for IPv4 or Link local or Ignore for IPv6 the switches for the DNS and Routes settings are not properly disabled. The [+] buttons are disabled though.

[NetworkingDisabledButNotReally.mov.gz](https://github.com/cockpit-project/cockpit/files/4854508/NetworkingDisabledButNotReally.mov.gz)
Steps to reproduce can be seen in the attached video.

Problem appears to have been introduced in https://github.com/cockpit-project/cockpit/commit/a2b0d7d38677f7e082fea91034f95960082be253#diff-3a1f1abbe951411135d59dc9fab529a3 when the enabled/disabled change was missed for this bit of UI.

This change seems to work in my *very* quick tests on 195.8 but I haven't tried it in the current code or tried writing an automated test or anything like that yet.
```diff
diff --git a/pkg/lib/cockpit-components-onoff.jsx b/pkg/lib/cockpit-components-onoff.jsx
index b4022fec9..4d9f65197 100644
--- a/pkg/lib/cockpit-components-onoff.jsx
+++ b/pkg/lib/cockpit-components-onoff.jsx
@@ -24,7 +24,7 @@ import "./cockpit-components-onoff.scss";
 /* Component to show an on/off switch
  * state      boolean value (off or on)
  * onChange   triggered when the switch is flipped, parameter: new state
- * enabled    whether the component is enabled or not, defaults to true
+ * disabled   whether the component is disabled or not, defaults to false
  * id         optional string, ID of the top-level HTML tag (only necessary
  *            when embedding this into a non-React page)
  * text       optional string that appears to the right of the button
diff --git a/pkg/networkmanager/interfaces.js b/pkg/networkmanager/interfaces.js
index e0dee6aad..b4eb4c531 100644
--- a/pkg/networkmanager/interfaces.js
+++ b/pkg/networkmanager/interfaces.js
@@ -3135,18 +3135,18 @@ function PageNetworkInterface(model) {

 function switchbox(val, callback) {
     var onoff = $('<span>');
-    var enabled = true;
+    var disabled = false;
     function render () {
         ReactDOM.render(
             React.createElement(OnOffSwitch, {
                 state: val,
-                enabled: enabled,
+                disabled: disabled,
                 onChange: callback
             }),
             onoff[0]);
     }
     onoff.enable = function (val) {
-        enabled = val;
+        disabled = !val;
         render();
     };
     render();
```

It also feels like the code in `inverted_switchbox` might need to change but in a quick test that seemed to invert the intended logic and I'm not sure why (not familiar with React enough to have gotten my head around how this all works yet).

### PR DESCRIPTION
**Pull request by deryni**
The direction of this state flag was reversed a while back but this one
was missed which caused the Automatic switches for the DNS, DNS Search
Domains, and Routes settings weren't getting disabled correctly.

Fixes #14290

### CODE REVIEW

**Comment by deryni** [comment]
I was able to test this with cockpit 220 now and this seems to work there as well. I was a bit confused by the fact that the Automatic switch for Routes gets disabled in the Shared and Link local modes but the `[+]` button does _not_. I looked into whether that was something I could fix but I _think_ the comments in the code tell me that this is actually working as expected that way.

I looked into writing an automated test for this but there don't seem to be a lot of tests for this stuff and, as always, I've had great trouble getting the tests actually running correctly.

**Comment by martinpitt** [comment]
Whoops, thanks a lot @deryni for spotting and fixing this! I can help with writing a test case, and I'd also like to split your commit in two. Do you mind if I force-push into your PR, or would you rather I open my own PR and cherry-pick your commit?

**Comment by martinpitt** [comment]
I force-pushed this. I split the commits, and added an integration test to the fix. Thanks @deryni ! As I dabbled with this now, I'll ask someone else to review.

**Comment by deryni** [comment]
Thanks for running with this. Glad I could help.

**Pull request merged**
