### PR TITLE
Start Angular Kubernetes dashboard

### PR DESCRIPTION
**Pull request by stefwalter**
Bring in the rough design of the dashboard
    
The basis for the angular application.
    
We don't yet fill in all the data, but this is a start. Watch for changes and rerender when things happen

For now angular will be hosted directly in the kubernetes package. If things turn out well, and we need this in more than one place we can move this to the base package.
    
Include angular-route as well, and make angular loadable via AMD.

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #1894

**Comment by stefwalter** [comment]
@sub-mod, @jeffvance, CC

**Comment by stefwalter** [comment]
Implements some of #1687

Doesn't yet implement the count of containers per service/node or the status icons. Will tackle those in a separate pull request.

**Comment by stefwalter** [comment]
Follow up commits will:
 * Fill in correct container information
 * Filter out kubernetes internal services
 * Put status icons in place

**Comment by sub-mod** [comment]
@stefwalter LGTM

**Pull request closed without merging**
