### PR TITLE
pybridge: Asynchronously send package files in chunks

### PR DESCRIPTION
**Pull request by martinpitt**
Don't synchronously send the whole document in a single channel data
block. They are often quite large (especially in `NODE_ENV=development`
mode, but even in production). The synchronous send_data() blocked the
bridge for too long, broke flow control, and stalled parallel package
channel downloads for too long. That often led to

    Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING

browser errors.

This got aggravated a lot when going through cockpit-ssh (as it happens
on our OSTree images with the cockpit/ws container), but even
occasionally happened with the standard setup.

Send them in 4K blocks instead, like the C bridge does. Use the same
threading approach as our http-stream2 channel to avoid blocking.

### CODE REVIEW

**Comment by martinpitt** [comment]
The frame timeouts [happen](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19136-20230725-145337-44e6f564-fedora-coreos-networking/log.html) [a lot](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19136-20230725-145354-44e6f564-rhel4edge-expensive/log.html) here as well.

**Comment by martinpitt** [comment]
and e.g. [this run](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19136-20230725-145351-44e6f564-rhel4edge-networking/log.html#7) is only saved because networkmanager isn't affected.

This concludes the experiment, see https://github.com/cockpit-project/cockpit/pull/19111#issuecomment-1649922598 for summary.

**Comment by martinpitt** [comment]
Re-purposed this to be #19111 with #19134 included.

**Comment by martinpitt** [comment]
Meh, [disaster](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19136-20230725-173954-6cc11a96-centos-8-stream-pybridge-expensive/log.html#17-2), [bad](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19136-20230725-173954-6cc11a96-fedora-coreos-networking/log.html), [disaster](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19136-20230725-173954-6cc11a96-rhel4edge-networking/log.html#7), [disaster](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19136-20230725-173954-6cc11a96-rhel4edge-other/log.html#147-1).

**Comment by martinpitt** [comment]
Next run, same as #19111 but with reverting the py bridge on F38 and C9S/RHEL 9.

**Comment by martinpitt** [comment]
Okay, so C bridge works. Let's try with commit f4be9066c9d3f5dbad0316231b5ad98c117394cf reverted then, to see if that changes anything.

**Comment by martinpitt** [comment]
The Py bridge has two important differences compared to the C bridge, which could explain these "Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING" and subsequent "terminated" errors:
 * The C bridge decompresses .gz files and sends them as plain text, the Py bridge 
 * The C bridge sends the data in ~ 4 kB chunks, the Py bridge sends the whole file in a single giant channel message.

Compare the output of these commands:
```
cpf packages /system/services.js : sleep 1  | cockpit-bridge | less
cpf packages /system/services.js : sleep 1  | cpy | less
```

C bridge (extra line breaks added before the packet length for readability):
```
{"command":"ready","channel":"ch1"}
400
ch1
{"status":200,"reason":"OK","headers":{"Referrer-Policy":"no-referrer","X-Frame-Options":"sameorigin","Cross-Origin-Resource-Policy":"same-origin","X-Cockpit-Pkg-Checksum":"f1b147a20348a0955afa60fe2645f0e7c6ad6526bf851180e79e9a568f168516","X-Content-Type-Options":"nosniff","Content-Type":"application/javascript","Access-Control-Allow-Origin":"https://localhost","X-DNS-Prefetch-Control":"off"}}

4100
ch1
(()=>{var gq=O[...]

4100
ch1
s===-1)&&([...]
```

Py bridge:
```
82
ch1
{
  "status": 200,
  "reason": "OK",
  "headers": {
    "Cache-Control": "no-cache, no-store",
    "Content-Type": "application/javascript",
    "Content-Encoding": "gzip"
  }
}

256933
ch1
^_<8B>^H [...]
```

**Comment by martinpitt** [comment]
So let's test the second point, and chunk the data. I seriously hope that it's not triggered by sending binary gz data, as that's a really nice improvement that I wouldn't want to lose.

**Comment by martinpitt** [comment]
yay, no errors! But let me provoke a 3x affected retry with networking.

**Comment by martinpitt** [comment]
[this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19136-20230726-055111-b3d60baf-arch-networking/log.html) is something different, otherwise the "3x affected" runs on commit b3d60baffe892571e50ea841d648f33971a85b7e are a blasting success :sweat_smile: 

So I'll turn this into something that can land, and it should really go into today's release as it unbreaks the py bridge.

**Review by jelly — APPROVED** [review]
I wonder if the Thread startup could be a bit heavy, but then again special casing this also sounds a bit too much of a premature optimisation.

**Comment by martinpitt** [comment]
@jelly Indeed if we *had* an async API for sending data in channels, we wouldn't need threads. I discussed that with @allisonkarlitskaya back then when I wrote https://github.com/cockpit-project/cockpit/blob/main/src/cockpit/channels/http.py , and right now all of the `do_done()` etc. handlers are sync. So she recommended using a thread instead.

Also, threads should be fairly lightweight, and we are talking about maybe a dozen parallel package downloads at the beginning, not thousands. That should be below any measurement noise.

I just realized that the solution was right, but the explanation was wrong/incomplete. I force-pushed again to update the description. As the code didn't change, GitHub kept your approval, but please re-read it so that I don't go behind your back :grin:

**Comment by allisonkarlitskaya** [comment]
This probably would have been better with [`GeneratorChannel`](https://github.com/cockpit-project/cockpit/blob/main/src/cockpit/channel.py#L486) in a similar way to the implementation of the [`fsread1`](https://github.com/cockpit-project/cockpit/blob/main/src/cockpit/channels/filesystem.py#L91) channel.  These are both basically the same case: read this file from disk and send it to me.

As a general rule, I think we should avoid threads if at all possible.  If the problem is about filling the send queue and marring up flow control then the above solution is the right one.  If it's rather about waiting on the blocking disk IO when accessing the packages files then we do indeed need to figure out something more clever.  The APIs in this area aren't great, but I feel like we could probably do something better than threads...

**Comment by martinpitt** [comment]
@allisonkarlitskaya This was admittedly a knee-jerk PR to unbreak us in between "that PF update PR really needs to land", "we enabled the py bridge on F38" and "release is today". Thanks for pointing out! I'll see to changing packages to GeneratorChannel, this looks much nicer! I don't think it'll work for http-stream2 though, as the http API is fundamentally sync.

**Comment by martinpitt** [comment]
Done in PR #19145 -- so much nicer indeed! :+1:

**Pull request merged**
