### PR TITLE
Make the iSCSI tests run on RHEL-7

### PR DESCRIPTION
**Pull request by stefwalter**

### CODE REVIEW

**Comment by petervo** [comment]
iSCSI tests are failing saying introspection data is not available on ISCSIinitiator.DiscoverSendTargets

**Comment by stefwalter** [comment]
This call just hangs on a test system. One can get to thihs point by running the ```check-storage-iscsi``` test:

```
# gdbus call --system --dest=org.storaged.Storaged --object-path=/org/storaged/Storaged/Manager --method=org.storaged.Storaged.Manager.ISCSI.Initiator.DiscoverSendTargetsChap "127.0.0.1" 0 "admin" "foobar" "" "" "{}"
Error: Timeout was reached
```

**Comment by mvollmer** [comment]
On it.

**Comment by mvollmer** [comment]
We need both a newer version of storaged and add a patch to iscsi-initiator-utils.

The hang disappears with this https://github.com/storaged-project/storaged/commit/2c1a208dea4591ecfb04e50a3cfd3481581ff54a.  I haven't investigated what it is exactly that needs to be changed.

I think no released version of storaged after 2.3 compiles on rhel-7 without some (trivial) fixes.

Without this newer storaged, the disk is properly attached, but the session is not listed because iscsi-initiator-utils doesn't have session support on rhel.  On Fedora, this support was added as a downstream patch in the rpm: https://bugzilla.redhat.com/show_bug.cgi?id=1262279

**Comment by stefwalter** [comment]
Issue filed on RHEL: https://bugzilla.redhat.com/show_bug.cgi?id=1341006

So @mvollmer the question is whether we should disable all certain iSCSI functionality on RHEL until the API issue is fixed?

**Comment by mvollmer** [comment]
> So @mvollmer the question is whether we should disable all certain iSCSI functionality on RHEL until the API issue is fixed?

I say yes.  I'll work on that.  My plan is to enable the test, but let them check that there is no iSCSI panel on rhel-7.

**Pull request closed without merging**
