### PR TITLE
list: compact mode

### PR DESCRIPTION
**Pull request by garrett**

### CODE REVIEW

**Comment by garrett** [comment]
This PR is based on and blocked by #10335. Once it lands, there should only be two commits:

- 65cb429: actual implementation of compact mode for lists, as requested by @andreasn in https://github.com/cockpit-project/cockpit/pull/10335#issuecomment-436289502
- 5feb13c: enables compact mode for the volumes in storage pools

The first is a site-wide modification, the second is an enhancement follow-up to #10335.

**Comment by KKoukiou** [comment]
@garrett please rebase, otherwise looks good, thanks!

**Comment by andreasn** [comment]
I wonder if it would be worth syncing this up to the style that we use inside the storage dialogs. Would lend itself well to also do inline scrolling for when the list of images gets too long (not sure what too long here is though. 15 images? 20?)

screenshot from 2018-11-21 17-46-59

**Comment by andreasn** [comment]
But this PR improves what we have right now drastically, so I wouldn't mind merging as-is, and then do any visual and behavioural sync-ups with the storage dialogs as a followup.

**Comment by garrett** [comment]
> I wonder if it would be worth syncing this up to the style that we use inside the storage dialogs.

It's suuuuuuper-simple to switch to the compact mode. Just add `compact`. See c0d04145a6f2990070df40cb1725ecec9aee072c for an example.

> Would lend itself well to also do inline scrolling for when the list of images gets too long (not sure what too long here is though. 15 images? 20?)

Debatable. The issue would be the use of 2 scrollbars instead of just 1. This would be a little problematic for scroll wheels but especially an issue in mobile. (If we decide to have the 2 lists, then it would have to have a breakpoint, in other words.)

That said, the way to do it is to have an overflow when height is 15 or 20 em + all padding + all borders. So it would probably be something like:

- ( line * line height + (compact padding * 2) + border line ) * number of lines
- which, in our case, is basically: (1em * 1.6 + (5px * 2) + 1px) * 15

This would be a prime example where CSS variables would be great. We could use LESS variables to pull in the defined line height (which is probably a constant really, so it's not essential here, but why not? the variable would help explain) and then use the rest in CSS and a CSS variable for the number of lines, which could default to 15. The React could use JavaScript set the CSS property for the lines and the CSS would calculate it accordingly.

...Or we could just do it old-school and fudge the number.

**Comment by andreasn** [comment]
> Debatable. The issue would be the use of 2 scrollbars instead of just 1. This would be a little problematic for scroll wheels but especially an issue in mobile.

Right. Maybe pagination is better in that case. Lets split that off in another issue then, and not block this one.
Ok, let's go with this!

**Comment by martinpitt** [comment]
Do you have a screenshot of how it looks now, for the release notes?

**Comment by garrett** [comment]
> Force-pushed with adding a Closes # and fixing a few small issues in the commit messages.

Thanks! I often seem to forget those #s. Also, thanks for the commit message fixups! :+1:

**Pull request merged**
