### PR TITLE
Image refresh for continuous-atomic

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for continuous-atomic in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-continuous-atomic-2016-11-25/

### CODE REVIEW

**Comment by cockpituous** [comment]
Image creation done.

**Comment by stefwalter** [comment]
@petervo, looks like a vaild OSTree GPG signing test failure here. Either Cockpit needs adjusting, or we should report it as an upstream bug:

```
https://fedorapeople.org/groups/cockpit/logs/pull-5480-488deb49-verify-continuous-atomic/OstreeRestartCase-testOstree-FAIL.png
```

**Comment by petervo** [comment]
Filed upstream bug here: https://github.com/projectatomic/rpm-ostree/issues/527.

Known issue here?

**Comment by stefwalter** [comment]
I think that's good enough. continuous-atomic is a canary image ... we don't test against it regularly, it's for highlighting problems that we're going to experience elsewhere. So we'd add the known issue when this issue shows up in fedora-atomic or rhel-atomic.

**Comment by petervo** [comment]
Merged, 27d67cb01f69c521509cd60f97c603e1cdd603c9

**Pull request closed without merging**
