### PR TITLE
New F22 images, plus tweaks.

### PR DESCRIPTION
**Pull request by mvollmer**
Actually, "minus tweaks".

### CODE REVIEW

**Comment by mvollmer** [comment]
Ouch, hubbot can't update the kernel...

**Comment by mvollmer** [comment]
Depends on #2111.

**Comment by mvollmer** [comment]
Hmm, the kernel isn't updated anymore...

**Comment by mvollmer** [comment]
> dnf update -y
> Error: The operation would result in removing the following protected packages: dnf.

What the... is it still Monday?

**Comment by dperpeet** [comment]
> What the... is it still Monday?

technically, the options should come first. It might be trying to interpret the `-y` as some kind of package. I recommend `dnf -y upgrade`, since [docs for dnf](http://dnf.readthedocs.org/en/latest/command_ref.html#update-command) indicate that `update` is deprecated.

Also, `yes | dnf` seems redundant when using the `-y` option. I think the integrated `-y` is cleaner.

**Comment by mvollmer** [comment]
> technically, the options should come first. It might be trying to interpret the -y as some kind of package. I recommend dnf -y upgrade, since docs for dnf indicate that update is deprecated.

Yes, let's do this, but dnf interprets "-y" correctly after the sub-command.

> Also, yes | dnf seems redundant when using the -y option. I think the integrated -y is cleaner.

Yes, let's remove it.  I am quite sure we needed back in the F20 days in some scenario (maybe a prompt from a %post script?), but let's try without.

**Pull request closed without merging**
