### PR TITLE
WIP: machines: Implement filtering of VMs by name, connection and state

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
Search field here is empty: all VMs are visible.
filter-input


Search field here limits search to VMs whose name has prefix the string 'fedora':
filter-input2

@garrett @andreasn I am sure you can suggest some much better approach regarding the design for the search input.

Also I would like to mention that I would like to implement also searching by all three columns that are visible on the page. Aka filter by **name**, **connection** and **state**.
Can you please suggest some idea of how to allow filtering by these three different attributes in the UI?

Let me know if you have any questions regarding the functionality.

**Comment by KKoukiou** [comment]
Rebased on top of @mareklibra PR to move to react from react-lite because the code I used from patternfly-react didn't work with react-lite.

@garrett @andreasn these are the updated screenshots, I used patternfly toolbar. https://www.patternfly.org/pattern-library/forms-and-controls/toolbar/
What do you think? Do you have any improvement suggestions?

filter-by-connection
filter-by-name-1
filter-by-name-2
filter-by-state
multiple-filters

Once I get the ACK for the design I 'll write the tests.

**Comment by KKoukiou** [comment]
>> Also, I think it's always useful to be able to filter by name, even if there are other types of filters happening.

@garrett one comment, filtering by Name is already supported by this PR.

If we can integrate the filtering somehow on the table itself I agree it should look better. Thanks!

**Comment by garrett** [comment]
What I had in mind is not on PatternFly's site, but I dug around the PF blog and found some examples.

I was thinking of something more like the placement of the filter bar from Foreman's host area in the [advanced filter blog post](https://blog.patternfly.org/patternfly/advanced-filter/):
mockup of forman's filter bar
(That is: under the title)

But possibly with widgets more similar to the [quick filter blog post](https://blog.patternfly.org/forms/quick-filter-improvement-for-the-current-filter-pattern/):
mockup from RH customer portal

So, for us, something like:

> ## Virtual Machines
> 
> [___________] [Filter]  State: [ All ▾ ] Type: [ All ▾ ]

or, using combo buttons (where only one button of the group is selected):

> ## Virtual Machines
> 
> [___________] [Filter]  State: [ Running | Off | **All** ] Type: [ System | Session | **All** ]

Directly under the virtual machines header, the filter should be on the left of the items and the create new VM action should be on the far right. However, with the second text-based mockup above, it might be a bit too wide.

The biggest changes:

1. Text filter is always available, and without a dropdown
2. Filter states are indicated either in dropdowns (first mockup) or a group of toggle button filters (second), so no tags or other secondary widgets are needed
3. The filtering is part of the list instead of the page's header
   - oVirt's version of the page already uses a header, IIRC

---

(Due to a migraine I'm suffering from at the moment, I'm not currently sure which is best, and I also apologize for a text-based mockup instead of a higher fidelity one at the moment. Hopefully it's understandable. If not, and if I'm feeling better tomorrow, I'll make better looking mockup. :wink:)

**Comment by garrett** [comment]
Notes from what we talked about in IRC:

- No line of active filters; the state of the filters is already represented in the UI
- string + type + state (in that order) probably makes more sense than what I wrote yesterday :wink:

Just recording it here too, so it's not forgotten in the IRC backlog.

**Comment by garrett** [comment]
@KKoukiou: It's looking great! Just a few little tweaks, as discussed in IRC:

Mentioned in IRC:

- use a `btn-group` without space around the buttons
- buttons should not be marked as primary
- selected should have `active` class applied and also have an `aria-current="true"` attribute
- "All" should be the first item in the group, and it should be selected by default.

See `pkg/systemd/services.html` for an example implementation.

Thanks for putting up with me and my migraine! I'm sorry for writing things iffy and backwards (all being at the end instead of the start) and for leaving out important details. :smile:

**Comment by KKoukiou** [comment]
filters-button-default

**Comment by KKoukiou** [comment]
Closing this PR because it outdated. We should reconsider the design considering that new resources will get introduces ( aka Storage Pools/Volumes and Libvirt Networks) which also require filtering.

**Pull request closed without merging**
