### PR TITLE
test: added avocado html plugin output to install dependecies

### PR DESCRIPTION
**Pull request by jscotka**

### CODE REVIEW

**Comment by stefwalter** [comment]
We're only doing avocado and selenium test runs online on fedora-23 ... in fact @mvollmer will be removing the Avocado stuff, including phantomjs, from all the other images ... to save space.

**Comment by stefwalter** [comment]
This doesn't take effect by itself. Images need to be rebuilt, perhaps @mvollmer could you include that one line in the fedora-23 image when you rebuild it with tuned?

**Comment by jscotka** [comment]
Yes, I've discussed it it with @dperpeet , and He promised to rebuild images, with that stuff.
I think that we can remove these depencencies from other images, but it causes me troubles when testing on whole matrix, I had to install it manually there, It is acceptable for me. Because I'm rebuilding images from scratch internally.
There could be some special option for that, like, install these extra  dependencies when creating new images, to be able use directly vm-create instead of vm-create and then vm-customize to adde there these extra dependencies

**Comment by mvollmer** [comment]
> This doesn't take effect by itself. Images need to be rebuilt, perhaps @mvollmer could you include that one line in the fedora-23 image when you rebuild it with tuned?

Too late, but I can make images for this PR as well.

**Comment by mvollmer** [comment]
> Yes, I've discussed it it with @dperpeet , and He promised to rebuild images, 

Ahh, ok.

**Comment by mvollmer** [comment]
I continue this in #3547

**Pull request closed without merging**
