### PR TITLE
naughty: Close 4001: Atomic: lastlog broken for non-root

### LINKED ISSUE #4001: Atomic: lastlog broken for non-root
On Atomic Host the 'lastlog' command is broken for non-root users. The `/var/lib/lastlog` file has inappropriate permissions.

https://bugzilla.redhat.com/show_bug.cgi?id=1317773

CC @walters

### PR DESCRIPTION
**Pull request by cockpituous**
Known issue which has not occurred in 51.0 days

Atomic: lastlog broken for non-root

Fixes #4001

### CODE REVIEW

**Comment by cockpituous** [comment]
Please comment on the upstream distro bug manually before accepting this pull request.

If you wish to keep this known issue open, then update it

**Comment by martinpitt** [comment]
@stefwalter : ok, sorry - the previous runs *here* on [rhel-atomic](http://fedorapeople.org/groups/cockpit/logs/pull-7286-20170717-233434-e218d0a9-verify-rhel-atomic/log.html) and [fedora-atomic](http://fedorapeople.org/groups/cockpit/logs/pull-7286-20170717-230505-e218d0a9-verify-fedora-atomic/log.html) don't show this problem, did you see it in another PR? But this doesn't appear like the kind of problem that would only happen sometimes.

**Comment by stefwalter** [comment]
This is still the case on fedora-atomic and rhel-atomic.

```
[admin@m1 ~]$ lastlog
/var/log/lastlog: Permission denied
```

and

```
[admin@m1 roothome]$ lastlog
/var/log/lastlog: Permission denied
[admin@m1 roothome]$ lastlog -u admin
/var/log/lastlog: Permission denied
```

**Comment by stefwalter** [comment]
Very likely our test doesn't test this feature properly :S

**Pull request closed without merging**
