### PR TITLE
Say updates will be installed "every day" not "everyday"

### PR DESCRIPTION
**Pull request by AdamWill**
The former is better English style.

Signed-off-by: Adam Williamson <awilliam@redhat.com>

### CODE REVIEW

**Comment by AdamWill** [comment]
2020-12-15T18:54:42.5353300Z FAIL: dist/base1/test-dbus-address.html 120 - correct data, expected: {

don't see how that has anything to do with the PR.

**Comment by marusak** [comment]
Thanks!
I've triggered tests. Don't worry about that unit test, that is unrelated.
The commit message should not contain `Signed off by` message, but it should contain `Fixes #15048` instead of having the issue number in commit header. The commit message can be fixed on squashing, so I would not worry about it either.

**Comment by AdamWill** [comment]
You seem to have an internal project war between "Closes X" and "Fixes X", actually...:D

**Comment by marusak** [comment]
> You seem to have an internal project war between "Closes X" and "Fixes X", actually...:D

Not really, those two are different for different things :) 
- `Closes X` is in at least one commit for __every PR__ and __references to itself__. So this PR would have `Closes #15049` and it is used so you can find the original PR from commit message. But just the last week we agreed we will stop doing that, as github can show you this info even without closes.
- `Fixes X` on the other hand is when you want to reference __issue__ that the commit fixes. Therefore a lot of commits (and thus PRs) don't require this.

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
