### PR TITLE
networkmanager: Tell model about type_Settings.

### PR DESCRIPTION
**Pull request by mvollmer**
How did this ever work?

### CODE REVIEW

**Comment by mvollmer** [comment]
Without this, a inactive bond (for example) would not be listed since without the Settings object we don't process all the connection settings, which in turn means we are missing the existence of the bond interface, because the connection settings are the only place where it is mentioned.

**Comment by stefwalter** [comment]
Is it possible to add a test for this?

**Comment by stefwalter** [comment]
Does this fix a test failure?

**Comment by mvollmer** [comment]
> Is it possible to add a test for this?

That would indeed be the right thing to do.

**Comment by mvollmer** [comment]
> Does this fix a test failure?

I don't think so.  I found this while manually testing bonds.

**Comment by mvollmer** [comment]
> Is it possible to add a test for this?

Done.

**Pull request closed without merging**
