### PR TITLE
Correctly match selectors for RCs (Kube-Topology)

### PR DESCRIPTION
**Pull request by martynd**
Resolves an issue stopping RCs from correctly gaining their relationship with Pods.

When a RC has multiple selectors and its Pods have matching selectors (plus additional labels) and the final required matching label is last on the Pod, the relationship does not get created. This leaves stray RCs in these circumstances.

Before
After

### CODE REVIEW

**Comment by martynd** [comment]
Unlike the previous fail, I am unable to identify anything the cause to make an appropriate change.

**Comment by stefwalter** [comment]
@martynd Could you paste a Replication Controller and Pod JSON examples of this issue?

**Comment by martynd** [comment]
@stefwalter 
These are the pod and rc definitions used for
http://dev.prbrds.com/m/f0xPualxFB.png
to
http://dev.prbrds.com/m/hM4R7UABSB.png

`{
    "kind": "Pod",
    "apiVersion": "v1",
    "metadata": {
        "name": "replication-controller-eujst",
        "namespace": "kube-system",
        "labels": {
            "k8s-app": "replication-controller",
            "kubernetes.io/cluster-service": "true",
            "nickname": "replication-controller",
            "version": "v3"
        }
    },
    "spec": {
         "containers":
         [{
             "name": "replication-controller",
             "image": "beta.gcr.io/google_containers/pause:2.0"
         }]
    }
}`

`{
    "kind": "ReplicationController",
    "apiVersion": "v1",
    "metadata": {
        "name": "replication-controller",
        "namespace": "kube-system",
        "labels": {
            "k8s-app": "replication-controller",
            "kubernetes.io/cluster-service": "true",
            "nickname": "replication-controller",
            "version": "v3"
        }
    },
    "spec": {
        "replicas": 1,
        "selector": {
            "k8s-app": "replication-controller",
            "version": "v3"
        },
        "template": {
            "metadata": {
                "creationTimestamp": null,
                "labels": {
                    "k8s-app": "replication-controller",
                    "kubernetes.io/cluster-service": "true",
                    "nickname": "replication-controller",
                    "version": "v3"
                }
            },
            "spec": {
                "containers": [{
                        "name": "replication-controller",
                        "image": "beta.gcr.io/google_containers/pause:2.0"
                }]
            }
        }
    }
}`

**Comment by stefwalter** [comment]
Looking more at the screen ... those are actually DeploymentConfigs. Could you dump the output of the deployment configs too? Then we can figure out why they're not linking up.

**Comment by martynd** [comment]
That would fit. There are no DeploymentConfigs.
After working with the K8s guys yesterday, it seems the RH RPMs are incomplete. It says they are 1.2, however they do not have any of the new default enabled 1.2 options such as DeploymentConfigs, nor does it even have them as extensions.

**Comment by martinpitt** [comment]
Reviewing old pull requests -- is this still relevant? Are you still interested in fixing this?

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode, and this is very stale, so I'm closing this now. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/

Thanks!

**Pull request closed without merging**
