### PR TITLE
systemd: Fix up L10N

### LINKED ISSUE #9439: Systemd: active timers Next Run and Last Trigger sporadically fail to get filled
Test in check-pages merged in Pull #9417 exosed this issue.

### PR DESCRIPTION
**Pull request by marusak**
Fixes #9439

Really no idea about this. It was reported 2.5 years ago. Since then we've rewritten the whole services page. Lets see if it still happens. I'll let all tests run and if does not reproduce, I'll retry all of them up to 3 times. If it fails, then I'll try to take a look how it behaves and what can be the problem there.

### CODE REVIEW

**Comment by marusak** [comment]
Ha, this actually was hiding issue - we do not translate last/next trigger strings :) Will fix it here

**Comment by marusak** [comment]
Ok, so it indeed fails sometimes to print the next run: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-14876-20201107-152908-39efcef7-ubuntu-2004/TestPages-testBasic-ubuntu-2004-127.0.0.2-2301-FAIL.png

**Comment by marusak** [comment]
ok, so this seems like systemd issue. After asking `org.freedesktop.systemd1.Timer` for `/org/freedesktop/systemd1/unit/test_2etimer`
Reply we should get:
```
{"Unit":"test.service","TimersMonotonic":[],"TimersCalendar":[["OnCalendar","*-*-* 00:00:00",1604811600000000]],"OnClockChange":false,"OnTimezoneChange":false,"NextElapseUSecRealtime":1604811600000000,"NextElapseUSecMonotonic":0,"LastTriggerUSec":0,"LastTriggerUSecMonotonic":0,"Result":"success","AccuracyUSec":60000000,"RandomizedDelayUSec":0,"Persistent":false,"WakeSystem":false,"RemainAfterElapse":true}
```

Reply we get: (sometimes on some OSes):
```
{"Unit":"test.service","TimersMonotonic":[],"TimersCalendar":[["OnCalendar","*-*-* 00:00:00",0]],"NextElapseUSecRealtime":-1,"NextElapseUSecMonotonic":-1,"LastTriggerUSec":0,"LastTriggerUSecMonotonic":0,"Result":"success","AccuracyUSec":60000000,"RandomizedDelayUSec":0,"Persistent":false,"WakeSystem":false,"RemainAfterElapse":true}
```

**Comment by marusak** [comment]
Hmm, or not? Example [here](https://logs.cockpit-project.org/logs/pull-14876-20201107-182841-ceacbce2-centos-8-stream/log.html#304) that cockpit gets `"NextElapseUSecRealtime":-1,` yet in introspect I see `.NextElapseUSecRealtime        property  t         1604793600000000`

Using command:
```
"busctl introspect org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/test_2etimer org.freedesktop.systemd1.Timer"
```
but only after it fails. Maybe we need to subscribe to changes?

**Comment by marusak** [comment]
Weird, so at the setUp:
```
* test.timer - Test timer
   Loaded: loaded (/etc/systemd/system/test.timer; static; vendor preset: disabled)
   Active: active (waiting) since Sat 2020-11-07 15:30:38 EST; 64ms ago
  Trigger: Sun 2020-11-08 00:00:00 EST; 8h left

Nov 07 15:30:38 localhost.localdomain systemd[1]: Started Test timer.

NAME                           TYPE      SIGNATURE RESULT/VALUE                             FLAGS
.AccuracyUSec                  property  t         60000000                                 const
.LastTriggerUSec               property  t         0                                        emits-change
.LastTriggerUSecMonotonic      property  t         0                                        emits-change
.NextElapseUSecMonotonic       property  t         0                                        emits-change
.NextElapseUSecRealtime        property  t         1604811600000000                         emits-change
.Persistent                    property  b         false                                    const
.RandomizedDelayUSec           property  t         0                                        const
.RemainAfterElapse             property  b         true                                     const
.Result                        property  s         "success"                                emits-change
.TimersCalendar                property  a(sst)    1 "OnCalendar" "*-*-* 00:00:00" 16048... emits-invalidation
.TimersMonotonic               property  a(stt)    0                                        emits-invalidation
.Unit                          property  s         "test.service"                           const
.WakeSystem                    property  b         false                                    const
```

but then when the page then tries to get this info, it gets:
```
{"Unit":"test.service","TimersMonotonic":[],"TimersCalendar":[["OnCalendar","*-*-* 00:00:00",0]],"NextElapseUSecRealtime":-1,"NextElapseUSecMonotonic":-1,"LastTriggerUSec":0,"LastTriggerUSecMonotonic":0,"Result":"success","AccuracyUSec":60000000,"RandomizedDelayUSec":0,"Persistent":false,"WakeSystem":false,"RemainAfterElapse":true}
```

Are we using this wrongly?

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit/pull/14876/commits/71737be6aadaf5d4434e6885147e39756e04141d#diff-89896d45c6fef41008f972ac87238d1302db8f8fb6122ec99512675216f4944aR605 so this helped :unamused: So does `wait()` not working as expected?

**Comment by marusak** [comment]
I give up, I'll send the real fixes in separate PR and will comment into the issue about these steps I did here.

**Review by KKoukiou — APPROVED** [review]

**Pull request merged**
