### PR TITLE
tests: Merge test files machines and address one test failure

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by martinpitt** [comment]
Still a `testCreate` failure:
```
Traceback (most recent call last):
  File "test/verify/check-machines", line 1715, in testCreate
    "echo \"{0}\" > /var/lib/libvirt/pxe-config/pxe.cfg".format(PXE_SERVER_CFG),
NameError: name 'PXE_SERVER_CFG' is not defined
```

**Comment by martinpitt** [comment]
[ubuntu-stable](https://logs.cockpit-project.org/logs/pull-14015-20200504-141149-fc35db7d-ubuntu-stable/log.html) is too red, retrying.

**Comment by martinpitt** [comment]
[ubuntu-stable](https://logs.cockpit-project.org/logs/pull-14015-20200504-164433-2882f551-ubuntu-stable/log.html) still seems broken :/

**Comment by KKoukiou** [comment]
Reposted because it had merge conflicts.

**Comment by KKoukiou** [comment]
There are some of the usual flakes - testConfigureBeforeInstall, testAddDisk but these fail everywhere.

**Pull request merged**
