### PR TITLE
Image refresh for fedora-30

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-30
 * [x] image-refresh fedora-30

### CODE REVIEW

**Comment by marusak** [comment]
[podman](https://209.132.184.41:8493/logs/pull-11878-20190520-191313-31195308-cockpit-project-cockpit-podman-cockpit-fedora-30/log) and [f30](https://209.132.184.41:8493/logs/pull-11878-20190520-191313-31195308-verify-fedora-30/log.html) failed, retrying.

**Comment by martinpitt** [comment]
Still [testLvm failure](https://209.132.184.41:8493/logs/pull-11878-20190521-123939-31195308-verify-fedora-30/log.html#196), re-retrying.

**Comment by marusak** [comment]
I added naughty for podman which is now green, also F30 itself is green. Lorax has timed out with lots of `command not found`. Not sure about lorax, @martinpitt @larskarlitski  ?

**Comment by martinpitt** [comment]
Wrt. weldr/lorax, it almost feels like our current fedora-30 image had beakerlib pre-installed, while this new one doesn't any more. Supposedly it was previously dragged in as a dependency. This is a regression from https://github.com/weldr/lorax/commit/4783f6562ffe4e85ed7840838ba671be653ab1e4 , I'll send a patch.

**Comment by martinpitt** [comment]
I sent https://github.com/weldr/lorax/pull/730 to fix lorax. Moving this from needswork to blocked.

**Comment by marusak** [comment]
I just came to block it, but @martinpitt blocked it faster. I want to postpone it a bit (like until tommorow) because the naughty is not gonna be needed. API changed and when we address these changes we should be fine without any naughty.

**Comment by martinpitt** [comment]
The lorax one isn't a regression from this image, it's just plainly broken. So no need to block on this.

**Pull request merged**
