### PR TITLE
storage: Make adding to fstab optional during Format

### PR DESCRIPTION
**Pull request by mvollmer**
This covers the "I want to format a block device but don't want to add it to fstab" case.

This doesn't give us "I want to remove an entry from fstab but want to keep the formatted block device".

image

### CODE REVIEW

**Comment by mvollmer** [comment]
We probably need to keep the "Mount now" option since it is coupled to "Unlock at boot" for encrypted block devices. I hope we can clean that up further down the road when we combine encryption and filesystems in the UI.  Then "unlocking" can maybe be part of "mounting".  (I.e., mounting automatically unlocks, and unmounting will lock.)

**Comment by martinpitt** [comment]
#12647 landed, please rebase.

**Comment by mvollmer** [comment]
> This doesn't give us "I want to remove an entry from fstab but want to keep the formatted block device".

See #13168 for an idea of how to tackle this.

**Comment by martinpitt** [comment]
Having two check boxes for "Mount this" seems weird indeed. I suppose the relation is that once you enable mounting, that auto-enables unlock-at-boot? And conversely, disabling unlock-at-boot disables mounting? That would be acceptable IMHO.

**Comment by mvollmer** [comment]
>  I suppose the relation is that once you enable mounting, that auto-enables unlock-at-boot? And conversely, disabling unlock-at-boot disables mounting? That would be acceptable IMHO.

Yes, exactly, and similarly for the read-only flag.

**Comment by garrett** [comment]
What happens when you say "mount filesystem" and not have "mount now" enabled? Does it _not_ mount the filesystem when you're still telling it to "mount filesystem"? That's quite confusing.

Meanwhile, I'd suggest dropping "mount" from all the places you can.

So it would look like this:

- Mount filesystem
  - Mount point
  - Options
    - Mount now (???)
    - Read-only
    - Custom options

I'm not sure what to do with "Mount filesystem" & "Mount now" at the moment, hence the "???" above.

**Comment by mvollmer** [comment]
> What happens when you say "mount filesystem" and not have "mount now" enabled? Does it _not_ mount the filesystem when you're still telling it to "mount filesystem"?

It will add an entry to fstab with the mount point and all the options, also add the "noauto" option to fstab, and not mount the filesystem.

**Comment by mvollmer** [comment]
> What happens when you say "mount filesystem" and not have "mount now" enabled? Does it _not_ mount the filesystem when you're still telling it to "mount filesystem"? That's quite confusing.

What if we change the top checkbox to "Configure mount point"?  That is much closer to what it does under the hood and doesn't semantically conflict with "Mount now".

**Comment by mvollmer** [comment]
Nobody seems to need this, lso let's archive this.

**Pull request closed without merging**
