### PR TITLE
bots, test: Introduce rhel-7-6-distropkg mode

### PR DESCRIPTION
**Pull request by martinpitt**
Similar to commit b738b0947f, preinstall the basic cockpit packages onto
the rhel-7-6 (and all future rhel-7*) image now. Remove them  for the
verify/rhel-7-6 test to keep its current behaviour (test all packages
from master), and introduce a new verify/rhel-7-6-distropkg test that
runs the Extra packages against the cockpit Base packages from RHEL 7.6.

 * [x] image-refresh rhel-7-6
 - [x] declare the new test (PR #9768)

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-d3hmb.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9769-20180731-105757/

**Comment by cockpituous** [comment]
image-refresh rhel-7-6 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-6-20180731-120303

**Comment by martinpitt** [comment]
This was green already, not sure why the test suddenly re-ran. Landing.

**Comment by martinpitt** [comment]
For the record: The previous test run hung, I forced a new one which succeeded, but the previous hung one then "overwrote" the result of the good one. @Gundersanne then re-triggered manually. So no mystery here, just bad luck.

**Pull request merged**
