### PR TITLE
shell: Improve about modal responsiveness

### LINKED ISSUE #18722: shell, PF5: Fix about screen for mobile
> While reworking the about screen for #18721, I realized the PF5 about screen is broken in mobile.
> 
> Screenshot 2023-04-26 at 11-48-39 Networking - garrett@Bolt
> 
> But I don't want to block this PR; we can handle it in a follow-up.
> 
> Oddly, the PF5 about screen — at least the HTML version — seems to handle mobile. But it's also different from the React one in at least one way (the larger X instead of the circle button), so this _might_ even be a PF5+React issue?
> 
> Screenshot 2023-04-26 at 11-50-42 PatternFly • Basic
> 
> Again: This should be fixed outside of this PR. Everything else looks great!

_Originally posted by @garrett in https://github.com/cockpit-project/cockpit/issues/18672#issuecomment-1523124149_

### PR DESCRIPTION
**Pull request by garrett**
Fixes #18722

### CODE REVIEW

**Comment by garrett** [comment]
I realized the original way I was solving this is no longer needed, as the newer trimming the padding/margin method also makes it fit on an iPhone SE (smallest target size) without having to reflow the key-value pairs of the definiton list.

Therefore, I dropped that part. https://github.com/cockpit-project/cockpit/compare/761c3f4a6bde277987f2f011c734ab7afe951a9b..464b1e6f1f6e5ecda30129396c5c1fcba9ec33fc

**Review by KKoukiou — COMMENTED** [review]
The example from Patternfly 5 docs works fine, https://patternfly-react-v5.surge.sh/components/about-modal/react/basic/
So it's really on our react usage that this breaks.

Let check first if this is wrong usage of the react component before overriding the CSS.

**Comment by KKoukiou** [comment]
@garrett so we are using the TextList correctly and the reason it collapses on the Patternfly examples but not on our side is the breakpoints overrides. The problem is that we have these breakpoint overrides, assuming that we are including in the width calculation the shell, but for widths < 768px this does not actually exist. 

So I believe the correct appoach here is to stop overriding the mobile breakpoints.

**Comment by garrett** [comment]
> So I believe the correct appoach here is to stop overriding the mobile breakpoints.

But we never had mobile size breakpoint changes? I specifically calculated the overrides for the shell navigation changes for the desktop modes.

**Pull request closed without merging**
