### PR TITLE
networkmanager: Fix null settings connection access

### PR DESCRIPTION
**Pull request by stefwalter**
There are races in the code (which fail during testing) due to:

TypeError: null is not an object (evaluating 'i.Settings.connection')

In addition there are tons of places where we have to do this
repetitive check and get it wrong. Replace with an accessor function.

### CODE REVIEW

**Comment by stefwalter** [comment]
Networking tests are failing regularly.

**Comment by mvollmer** [comment]
Wasn't this fixed by #4619?

**Comment by stefwalter** [comment]
No. It's happening in lots of tests.

**Comment by stefwalter** [comment]
Fixed some cases I screwed up the first time during refactoring.

**Comment by stefwalter** [comment]
Priority because this is causing test failures.

**Pull request closed without merging**
