### PR TITLE
po: Fix file reading in manifest2po

### PR DESCRIPTION
**Pull request by marusak**
`html2po` does the same.
Noticed on #12617, from logs it executes `bots/make-source update-po`

Works both with : 
- `bots/make-source update-po` (how bots do it on refresh)
- `./autogen && make po-update` (how normally one would do it locally)

Hopefully this can be tests:
 * [x] po-refresh

### CODE REVIEW

**Comment by cockpituous** [comment]
po-refresh in progress on 4-ci-srv-04.
Log: https://209.132.184.41:8493/logs/po-refresh-12618-20190822-075050/

**Comment by cockpituous** [comment]
po-refresh in progress on 2-cockpit-8.
Log: https://209.132.184.41:8493/logs/po-refresh-12618-20190822-075050/

**Comment by cockpituous** [comment]
po-refresh  done: https://github.com/cockpituous/cockpit/commits/po-refresh-20190822-075252

**Comment by marusak** [comment]
Nice, worked.
Notice those manifests in `.po` files :)
I checked czech and it looks correct.
And just let run `fedora-30` since it can check if some translations break cockpit.

**Pull request merged**
