### PR TITLE
Adding Expose and VOLUME

### PR DESCRIPTION
**Pull request by frank-dspeed**
This are Needed Infos sure it works without but it helps to know whats going on

### CODE REVIEW

**Comment by mvollmer** [comment]
Doesn't EXPOSE give the impression that you can remap the port via "docker run --publish"?  As far as I know, this doesn't work here.

**Comment by stefwalter** [comment]
Agreed with @mvollmer about EXPOSE.

The VOLUME seems to make sense. What is the new command for running the container?

**Comment by frank-dspeed** [comment]
Its Easy EXPOSE and VOLUME are only in for informational use the command stays exactly as it is.
I Will Add Some Checks and msges soon DOSN't EXPOSE brings nothing EXPOSING only Shows that the App Inside the container offers that port so its needed info that you get for example via docker ps that the running container can be connected at port 9090 you can still do all remaping as you like EXPOSE only Shows that info and if you would link this container it will supply this infos to the linked container too for example i can link in this img into a HAPROXY img that will automaticly add routing to this port but i am planning to do a production ready img so the needed task remaining are:

- Refine CAPS so that only the needed caps are givin that are the SYS_ADMIN CAPS for systemd.
see my systemd container as example: https://registry.hub.docker.com/u/dockerimages/docker-systemd/

- Add checks and infos to the start (run script) for checking if /host is mounted later we will only mount directly the cgroups fs like in my systemd container and maybe proc is needed i don't know all dependencys but i am working on that because mounting whole /host is not a good idea :D

**Comment by stefwalter** [comment]
As discussed on IRC, EXPOSE will likely not work since we nsenter the host network namespace so we have access to the loopback device. We do this so we can log into the host machine via ssh locally. I haven't been able to find another clean way to authenticate host machine users from within a container (among other things, SELinux, audit subsystem, and other issues cause it to fail).

The VOLUME change seems to make sense. Please post the new command that would be used to invoke a container with the VOLUME change.

**Comment by stefwalter** [comment]
@frank-dspeed are you planning on reworking this patch for the review above? If not, we can close this pull request.

**Comment by frank-dspeed** [comment]
this can be closed this will never ever work as suggested complet rewrite is probally the only way for people like me.

i also droped the idea that cockpit can solve my monitoring needs i will switch back to remonit

**Pull request closed without merging**
