### PR TITLE
Image refresh for fedora-26

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-26
 * [x] image-refresh fedora-26
 * [x] known issue for selinux/tang  
 * [x] fix [testDisks](https://fedorapeople.org/groups/cockpit/logs/pull-8940-20180404-085454-e758fcc9-verify-fedora-26/log.html#207) race (affects all OSes, race/flake)

### CODE REVIEW

**Comment by martinpitt** [comment]
the new clevis test [fails](https://fedorapeople.org/groups/cockpit/logs/pull-8940-20180404-085454-e758fcc9-verify-fedora-26/log.html#214) on fedora-26. It needs to be blacklisted there, as the image does not have tang.

**Comment by martinpitt** [comment]
Also, testDisks (check_machines.TestMachines) often 
[fails like this](https://fedorapeople.org/groups/cockpit/logs/pull-8940-20180404-085454-e758fcc9-verify-fedora-26/log.html#207):
```
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-machines", line 469, in testDisks
    b.wait_in_text("#vm-subVmTest1-disks-hda-used", "0.00")
```

The [screenshot](https://fedorapeople.org/groups/cockpit/logs/pull-8940-20180404-085454-e758fcc9-verify-fedora-26/TestMachines-testDisks-fedora-26-127.0.0.2-2201-FAIL.png) shows that this actually uses 0.02 or sometimes 0.04 GB, perhaps some file system metadata .

**Comment by martinpitt** [comment]
@mvollmer, can you please look into these two issues?

**Comment by mvollmer** [comment]
> the new clevis test fails on fedora-26. It needs to be blacklisted there, as the image does not have tang.

I think it has tang.  The error is:

```
Apr 04 05:52:46 localhost.localdomain audit[1]: AVC avc:  denied  { create } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=tcp_socket permissive=0
Apr 04 05:52:46 localhost.localdomain systemd[1]: tangd.socket: Failed to listen on sockets: Permission denied
Apr 04 05:52:46 localhost.localdomain systemd[1]: Failed to listen on Tang Server socket.
Apr 04 05:52:46 localhost.localdomain systemd[1]: tangd.socket: Unit entered failed state.
```

**Comment by mvollmer** [comment]
kdump might be broken for real:

```
Apr 04 10:11:05 localhost.localdomain kdumpctl[803]: Can't find kernel text map area from kcore
Apr 04 10:11:05 localhost.localdomain kdumpctl[803]: Cannot load /boot/vmlinuz-4.15.14-200.fc26.x86_64
Apr 04 10:11:06 localhost.localdomain kdumpctl[803]: kexec: failed to load kdump kernel
Apr 04 10:11:06 localhost.localdomain kdumpctl[803]: Starting kdump: [FAILED]
```

**Comment by mvollmer** [comment]
> kdump might be broken for real:

it's a flake, but what a huge one.

**Comment by mvollmer** [comment]
One more try for fedora-26, but I think it doesn't get any greener than this.

**Pull request closed without merging**
