### PR TITLE
HACKING.md: remove `sudo` from vagrant command lines

### PR DESCRIPTION
**Pull request by larsu**
Vagrant's underlying VM provider asks for credentials when needed.

### CODE REVIEW

**Comment by stefwalter** [comment]
Is this in a specific vagrant version? It didn't used to do this properly.

**Comment by larsu** [comment]
> Is this in a specific vagrant version? It didn't used to do this properly.

I don't know since when this is, but it works (for me) now. Vagrant's documentation also doesn't specify running commands as root.

**Comment by stefwalter** [comment]
Okay, I'll trust your judgement here. It doesn't work for me on fedora-24. I get:

```
/usr/share/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/requests/compute/list_volumes.rb:32:in `info': Call to virStorageVolGetInfo failed: Storage volume not found: no storage vol with matching path '/tmp/tmphktjb5mr' (Libvirt::RetrieveError)
```

**Comment by larsu** [comment]
I got this as well when I did the transition, but it worked after I removed "cockpit_default" and its associated storage with virt-manager. Does that make it work for you?

**Pull request closed without merging**
