### PR TITLE
Multiple WebSocket Origins

### PR DESCRIPTION
**Pull request by stefwalter**
cockpit-ws should support multiple WebSocket origins to support callers into the websocket other than HTML delivered by cockpit-ws itself.

### CODE REVIEW

**Comment by stefwalter** [comment]
This would be driven by a configuration item in cockpit.conf: The list of Origins allowed to access the WebSocket.

**Comment by stefwalter** [comment]
@petervo Is this something you're interested in finishing up? It needs a bunch of stuff:
 
 * Second commit needs to be finished
 * Reworking the cockpit.conf configuration
 * The location of config file should likely be ```/etc/cockpit/cockpit.conf```
 * Tests for both commits

**Comment by petervo** [comment]
Still working on tests, the code changes are here if you want to review them now. https://github.com/petervo/cockpit/pull/1

**Comment by stefwalter** [comment]
Thanks. Looks good. Just added a few comments.

**Comment by petervo** [comment]
Updated that PR with fixes and tests.

**Comment by stefwalter** [comment]
Merge in Peter's work. Ready for review.

**Comment by stefwalter** [comment]
Peter and I have reviewed each other's work here. We both worked on this together. Since this has just been sitting here ready for nearly a week, I'll merge with that as review.

**Pull request closed without merging**
