### PR TITLE
test: Add toggling SELinux enforcing to integration test

### PR DESCRIPTION
**Pull request by stefwalter**

### CODE REVIEW

**Comment by stefwalter** [comment]
Had to add a workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1346364

**Comment by dperpeet** [comment]
this won't work right now because the state doesn't show if there are no alerts, working on it

**Comment by stefwalter** [comment]
Indeed, I hadn't run this as its own test yet.

**Comment by stefwalter** [comment]
Closed in favor of #4618

**Pull request closed without merging**
