### PR TITLE
bots: Fix rhel-8-0 image build

### LINKED ISSUE #11329: Image refresh for rhel-8-0
Image refresh for rhel-8-0
 * [ ] FAIL: image-refresh rhel-8-0

### PR DESCRIPTION
**Pull request by martinpitt**
Replace the obsolete go-toolset build root with the standard one. We
don't need Go for RHEL 8.0 builds.

Fixes #11329

 * [x] image-refresh rhel-8-0

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-9g14n.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11354-20190310-220404/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-px1kb.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11354-20190310-220404/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11354-20190310-220404/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-3p9zs.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11354-20190311-065555/

**Comment by cockpituous** [comment]
image-refresh rhel-8-0 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-0-20190311-071818

**Comment by martinpitt** [comment]
This [VDO failure](https://fedorapeople.org/groups/cockpit/logs/pull-11354-20190311-073030-ce1c50c1-verify-rhel-8-0/log.html#210) seems to be real.

**Comment by martinpitt** [comment]
I want to make some further cleanups, especially *before* we add an 8.1 image. Re-pushed, rebuilding.

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-9g14n.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11354-20190311-100707/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-3p9zs.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11354-20190311-100101/

**Comment by cockpituous** [comment]
image-refresh rhel-8-0 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-8-0-20190311-102424

**Comment by martinpitt** [comment]
Same [vdo failure](https://fedorapeople.org/groups/cockpit/logs/pull-11354-20190311-104343-c0f1fb65-verify-rhel-8-0/log.html#210), unsurprisingly. @mvollmer, do you know what's gong on there?

**Comment by mvollmer** [comment]
> This [VDO failure](https://fedorapeople.org/groups/cockpit/logs/pull-11354-20190311-073030-ce1c50c1-verify-rhel-8-0/log.html#210) seems to be real.

Yes.  Creating a VDO volume re-uses some validation code from LVM2 apparently, and LVM2 doesn't seem to allow recursion.  `pvcreate /dev/vdo_vgroup/lvol` fails with the same error.

Sandwiching VDO between LVM2 is a recommended setup, I think, so this looks like a regression.

Either LVM2 is now newly rejecting recursive setups, or VDO is now newly using the LVM2 validation code.  I'll go ask around.

**Comment by mvollmer** [comment]
Bug re VDO: https://bugzilla.redhat.com/show_bug.cgi?id=1687391

**Comment by martinpitt** [comment]
Thanks @mvollmer: This was a duplicate of https://bugzilla.redhat.com/show_bug.cgi?id=1684249 . So let's naughty it for now.

**Comment by martinpitt** [comment]
Meh, another flake
```
testlib.Error: audit: type=1400 audit(1552315932.977:4): avc:  denied  { search } for  pid=5070 comm="qemu-kvm" name="1647" dev="proc" ino=33765 scontext=system_u:system_r:svirt_tcg_t:s0:c183,c488 tcontext=system_u:system_r:virtd_t:s0-s0:c0.c1023 tclass=dir permissive=0
```

https://fedorapeople.org/groups/cockpit/logs/pull-11354-20190311-142222-f51d60c3-verify-rhel-8-0/log.html#70

**Comment by martinpitt** [comment]
Pushed a fix for the above flake.

**Comment by mvollmer** [comment]
Here is a workaround for the VDO issue: https://github.com/mvollmer/cockpit/commit/d0f3de23c21ae134c036504ae5a22fc3a25a8dee

We might to use that instead of the naughty skip, just to get more test coverage for VDO.

**Pull request merged**
