### PR TITLE
Finish removing jQuery from cockpit.js

### PR DESCRIPTION
**Pull request by stefwalter**
This mainly includes work adding a more real version of promises, rather than the non-standard jQuery ones. We do retain jQuery compatibility on most promise related functions.

### CODE REVIEW

**Comment by dperpeet** [comment]
tests failing

**Comment by dperpeet** [comment]
failures seem to be like this one:
```
Page error: TypeError: undefined is not a function (evaluating 'i[t].promise().done(s(t,u,i)).fail(a.reject).progress(s(t,f,l))')
```

**Comment by stefwalter** [comment]
> failures seem to be like this one:

Fixed that one. There was a missing jQuery like function in the promise.

**Comment by dperpeet** [comment]
setting time still seems to have errors

**Comment by stefwalter** [comment]
The problem here is that $.when doesn't work with non jQuery promises. I'll need to look into why that's the case.

**Pull request closed without merging**
