### PR TITLE
RHEL 7.5 fixes

### PR DESCRIPTION
**Pull request by martinpitt**
I just created a rhel-7.5 branch starting from tag 154 (what we currently ship in the [upcoming 7.5](https://bugzilla.redhat.com/show_bug.cgi?id=1470780)).

### CODE REVIEW

**Comment by petervo** [comment]
Looks like a lot of test exceptions need to be moved in.

Ostree tests shouldn't be running on this os. and some of the storage tests need to be skipped on run differently.

**Comment by martinpitt** [comment]
Hmm, the rhel-7-5 image was added to master on October 13, before version 154 (which landed in rhel-7-5) in commit 42ef1b8c12e. But indeed that commit isn't in the rhel-7.5 branch and it really landed in version 155 only. So indeed these test adjustments need to be backported.

**Comment by martinpitt** [comment]
I backported a few necessary test fixes, somewhat squashed to avoid too many downstream patches. The remaining three failures:

 - `check-openshift TestOpenshift.testConnect` reproduces locally; probably some missing test update from the move to OpenShift 3.7
 - `check-openshift TestRegistry.testProjectUsers` reproduces locally; this also smells related to "Use RBAC apiGroup when policybinds is not available", will dig through test history
- `check-ovirt TestOVirtMachines.testBasic` passes locally, so that's just the usual flake

**Comment by martinpitt** [comment]
I backported the updates for OpenShift 3.7 (which we ought to have in RHEL 7.5 anyway) and the `$destroy` fix, and it's working much better now.

**Comment by martinpitt** [comment]
... and green. @petervo, can you please review?

**Pull request merged**
