### PR TITLE
package.json: Update @patternfly/patternfly, @patternfly/react-table, @patternfly/react-styles, @patternfly/react-core

### PR DESCRIPTION
**Pull request by martinpitt**
Replaces #16181 which I accidentally closed (and can't be reopened)

### CODE REVIEW

**Review by martinpitt — COMMENTED** [review]
I went through all pages, looking fine.

**Comment by martinpitt** [comment]
@marusak : As I filed this PR (as a clone of #16181) I can't approve this. I visually tested it, can you please formally ack? Dakujem!

**Review by marusak — APPROVED** [review]
Thanks!

**Comment by martinpitt** [comment]
Tests are all green, just the current GitHub API flakiness prevented a proper statuses update.

**Pull request merged**
