### PR TITLE
Networking: Better autoconnect

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by stefwalter** [comment]
Lots of check-networking test failures. I imagine @mvollmer will want to examine these individually or if they are fixed elsewhere, rerun the tests until they succeed.

**Comment by mvollmer** [comment]
I got convinced in https://bugzilla.redhat.com/show_bug.cgi?id=1395108 that a bond and its slaves should all be active and have autoconnect=yes right after creation.  I'l update this PR to reflect that.

**Comment by mvollmer** [comment]
Depdends on #5687

**Comment by mvollmer** [comment]
Some failures are new and genuine.

**Comment by mvollmer** [comment]
> Some failures are new and genuine.

Got at least one in check-networking-vlan... removing needswork to get this tested again.

**Comment by dperpeet** [comment]
needs a rebase

**Comment by dperpeet** [comment]
Adding priority because we want to tackle these networking issues soon and this change seems good to go.

**Comment by stefwalter** [comment]
There is a networking failure in the fedora-25 test above:

https://fedorapeople.org/groups/cockpit/logs/pull-5702-4bdc3ea2-verify-fedora-25/TestNetworking-testBasic-FAIL.png

**Comment by mvollmer** [comment]
> There is a networking failure in the fedora-25 test above:

This is 'known' and unrelated.  #5809 was supposed to help.

**Pull request closed without merging**
