### PR TITLE
storage: Leave LUKS devices open in Anaconda mode

### PR DESCRIPTION
**Pull request by mvollmer**
Since Anaconda will want to mount them and write to them.

Also, resizing partitions, creating encrypted PV, etc work better when LUKS is open.

### CODE REVIEW

**Comment by martinpitt** [comment]
@mvollmer: [This is intentional](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20016-20240213-153838-dafe0a7e-fedora-39-storage/pixeldiff.html#TestStorageAnaconda-testBasic-page), right?

**Review by martinpitt — DISMISSED** [review]

**Comment by mvollmer** [comment]
@KKoukiou, Anaconda tests need to be updated for this change: https://cockpit-logs.us-east-1.linodeobjects.com/pull-20016-20240219-113200-0bb2b99a-fedora-rawhide-boot-cockpit-pr-20016-rhinstaller-anaconda-webui/log.html#21-2

What do you think?

**Comment by mvollmer** [comment]
This is blocked on Anaconda. We want to land a PR that fixes Anaconda tests at the same time as this PR.

**Review by KKoukiou — DISMISSED** [review]

**Comment by mvollmer** [comment]
Had to resolve a ptest conflict.

**Review by martinpitt — APPROVED** [review]
+1, and another +2 just in case you need to push again :grimacing:

**Comment by mvollmer** [comment]
One more retry for Arch, but then this goes in.

**Pull request merged**
