### PR TITLE
Image refresh for fedora-30

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-30
 * [x] image-refresh fedora-30

- [x] testBasic (check_sosreport.TestSOS)

### CODE REVIEW

**Comment by marusak** [comment]
[this test](https://209.132.184.41:8493/logs/pull-11496-20190330-193636-a493d9c1-verify-fedora-30/log.html#222) failed already twice. One more retry

**Comment by marusak** [comment]
**There is a new sos version, which runs for way too long and also one command of dnf timeouts**

    $ rpm -q sos
    sos-3.7-1.fc30.noarch

    # time sosreport --batch
    ...
    [plugin:dnf] command 'dnf module list --installed' timed out after 300s
    ...
    real	10m38.718s
    user	8m18.028s
    sys	0m49.866s

`dnf module list --installed` timeouts because it is waiting for `dnf makecache` to end which is started automatically after boot. (also dnf plugin runs the longest)
<hr>

**The same version but with `dnf` excluced from plugins in `/etc/sos.conf`**

    # time sosreport --batch
    ...
    real	1m50.683s
    user	1m33.035s
    sys	0m11.078s

Therefore I propose to disable dnf from plugins. Also it makes sense to disable most of the things or ideally disable everything and enable just one or two modules so it is fast. I will push some commit that does one of those things.

<hr>

**Just to compare speed with the previous version**

    $rpm -q sos
    sos-3.6-5.fc30.noarch

    # time sosreport --batch
    ...
    real	1m7.312s
    user	0m25.940s
    sys	0m8.674s

**Comment by marusak** [comment]
Opened PR #11499 that is fixing this. Once merged, this needs rebase and should be good to go. Opened as separate PR to be sure that the specific plugin is present everywhere where we test SOS.

**Comment by martinpitt** [comment]
Marking this as blocked instead.

**Comment by martinpitt** [comment]
#11499 landed, retrying.

**Pull request merged**
