### PR TITLE
Fix up the tuned prototype

### PR DESCRIPTION
**Pull request by stefwalter**
This replaces #3279

### CODE REVIEW

**Comment by dperpeet** [comment]
Should this work on a current f23 system? I get the following error:
screenshot from 2015-12-22 21 36 48 tuned

**Comment by stefwalter** [comment]
That's a tuned bug that will need to be fixed in tuned dbus access policy. Logging in as root should work around the issue for now. Since we're not packaging the tuned stuff, I don't think this is a blocker.

**Comment by dperpeet** [comment]
confirmed, logging in as root works

**Comment by dperpeet** [comment]
wrong Closes in commit https://github.com/cockpit-project/cockpit/commit/74312c813193a4d403b3658ce9130b99b1e9f825

**Pull request closed without merging**
