### PR TITLE
Distribute more, and rebuild after clean

### PR DESCRIPTION
**Pull request by stefwalter**
Distribute everything committed in certain directories: @jscotka requested that we distribute test/ ... in addition this makes distributing other stuff simpler.

Re-minify files from dependencies: Debian has requested that we rebuild minified files (including the ones that we get from our deps).

Fix up the way we use less.js in registry, and distribute license for less.js.

Fix tuned manifest.json on 'make clean'

Distribute po/*.po files.

### CODE REVIEW

**Comment by stefwalter** [comment]
Ideally this would be included in the next release.

**Comment by stefwalter** [comment]
Fixes #3165

**Comment by dperpeet** [comment]
After a fresh make + install I can't see the registry in Cockpit anymore.

**Comment by stefwalter** [comment]
Fixed issue installing broken link.

**Comment by dperpeet** [comment]
`make install` fails with
```
/usr/bin/install -c -m 644 `dirname doc/guide/html/index.html`/* /usr/share/doc/cockpit
tools/ \
test/ \

make[3]: tools/: Command not found
Makefile:8972: recipe for target 'install-data-local' failed
make[3]: *** [install-data-local] Error 127
make[3]: Leaving directory '/home/dev/build'
Makefile:8580: recipe for target 'install-am' failed
make[2]: *** [install-am] Error 2
make[2]: Leaving directory '/home/dev/build'
Makefile:7859: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/dev/build'
Makefile:8574: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by dperpeet** [comment]
This looks good, but I'm having trouble merging.

**Pull request closed without merging**
