### PR TITLE
test: Only remove a loopback device file once its done

### PR DESCRIPTION
**Pull request by mvollmer**
Removing it early breaks newer LVM2 versions, see
https://bugzilla.redhat.com/show_bug.cgi?id=1969408

### CODE REVIEW

**Comment by mvollmer** [comment]
Needed for the rhel-9-0 image refresh.

**Review by martinpitt — DISMISSED** [review]
Yeah, well, hmmkay. But thanks for tracking down the cause and bz!

**Comment by mvollmer** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1969408 has suggestions for workarounds, but I think it is best for us not to modify the lvm2 configuration. We actually want to find bugs like this.

But I'll mark this as a HACK so that we might remove it laterish.

**Comment by martinpitt** [comment]
packit tests [failed](http://artifacts.dev.testing-farm.io/0b55015b-1ed8-482e-8d02-3647833115c6/) with

    ‘/root/ARTIFACTS/work-all8oa21B/plans/all/discover/default/tests/test/run-verify-host-user.sh’: Permission denied

This.. is new..

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
