### PR TITLE
lib: stop overriding the mobile breakpoint as for width < 768px the left nav is hidden

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by garrett** [comment]
Thanks! This looks correct. I'll review it out locally now.

**Comment by garrett** [comment]
I think we have some unintended consequences...

image

image

image

**Review by garrett — APPROVED** [review]
All the issues I spotted are on main too, and we're working on solving some of them outside of this PR already.

As for the breakpoints, this looks correct from what I see. Thanks! :+1:

**Comment by KKoukiou** [comment]
Closing in favor of https://github.com/cockpit-project/cockpit/pull/18729 which has this commit cherry-picked.

**Pull request closed without merging**
