### PR TITLE
Prevent the spinner from jumping around on login page

### PR DESCRIPTION
**Pull request by stefwalter**
This happens on smaller screens.

Also make it more consistent with the other forms in Cockpit as to the positioning of the spinner.

### CODE REVIEW

**Comment by stefwalter** [comment]
Would be ideal to have this in the next release.

**Comment by stefwalter** [comment]
This happens (for example) at a browser width of 1680 pixels and a zoom of %120

**Comment by stefwalter** [comment]
Screenshot example of spinner reflowing the screen:

screenshot from 2016-06-20 10-40-51
screenshot from 2016-06-20 10-40-53

**Comment by mvollmer** [comment]
I can't reproduce the layout bug.  With the fix, the spinner looks like this:

screenshot from 2016-06-20 11-46-29

**Comment by mvollmer** [comment]
The layout bug happens when the screen size is just a little bigger than where it switches to the "mobile" layout.

**Comment by mvollmer** [comment]
With this change, the spinner moves relative to the "Password" label when the window is resized.  I think the intention is that it stays left aligned with the labels above it.

**Comment by stefwalter** [comment]
Fixed spinner left alignment.

**Pull request closed without merging**
