### PR TITLE
machines: add ImageMagick dependency to the test images

### PR DESCRIPTION
**Pull request by mareklibra**

### CODE REVIEW

**Comment by stefwalter** [comment]
See discussion in #5651

**Comment by mvollmer** [comment]
bot: Image refresh for fedora-25

**Comment by cockpituous** [comment]
Image creation for fedora-25 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-25-acaf6df000df6d710b09b4edcdab7500610b0eb8/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-fedora-25-acaf6df000df6d710b09b4edcdab7500610b0eb8

**Comment by stefwalter** [comment]
So we discussed on IRC and in #5651 that installing ImageMagick everywhere is not a good way to approach this.

**Pull request closed without merging**
