### PR TITLE
Image refresh for debian-testing

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-testing
 * [x] image-refresh debian-testing

### CODE REVIEW

**Comment by martinpitt** [comment]
[previous log](https://fedorapeople.org/groups/cockpit/logs/pull-9955-20180904-120101-1fe579ca-verify-debian-testing/log.html#203) for comparison

**Comment by Gundersanne** [comment]
Right now I'm selceting the key based on hostname, which isn't consistent over images. Maybe I should just select the last one added, or the one key without data-name in it.

**Comment by martinpitt** [comment]
Oh, thanks @Gundersanne for the fix! There's nothing in the commit log, I'll fix that on squashing.

**Comment by martinpitt** [comment]
Actually there is, nevermind :)

**Pull request merged**
