### PR TITLE
Explicitly activate the "TEST" connection in check-networking

### LINKED ISSUE #3338: check-networking doesn't cope with multiple settings
The TestNetworking.testBasic test is careful to explicitly create connection settings for the hot plugged interface, but it doesn't cope with a scenario where another connection setting already exists for the new interface.

This happens on fedora-atomic where the new iface gets the "eth0" name, and there already is a ifcfg-eth0 network script.

Rather than avoid multiple connection settings, or just be able to pass in their presence, I think we should actively create multiple ones, explicitly activate one of them, and expect Cockpit to work on the active one.

This increases test coverage.

### PR DESCRIPTION
**Pull request by mvollmer**
Depends on #3381 

Fixes #3338

### CODE REVIEW

**Comment by mvollmer** [comment]
This should allow us to get rid of the workaround in `test/guest/fedora-atomic.setup`, but I had trouble creating new images, so I left it in for now.

**Comment by stefwalter** [comment]
Needs rebase

**Comment by mvollmer** [comment]
Rebased, and improved the comments.

**Comment by petervo** [comment]
@mvollmer I need to create new atomic images anyways, do you want me to create some without the hack you can try out here?

**Comment by mvollmer** [comment]
> I need to create new atomic images anyways, do you want me to create some without the hack you can try out here?

Yes, that would work.

**Comment by petervo** [comment]
New images are uploading with the following change

```
diff --git a/test/guest/fedora-atomic.setup b/test/guest/fedora-atomic.setup
index ffdf00d..a888461 100755
--- a/test/guest/fedora-atomic.setup
+++ b/test/guest/fedora-atomic.setup
@@ -18,12 +18,6 @@
 # You should have received a copy of the GNU Lesser General Public License
 # along with Cockpit; If not, see <http://www.gnu.org/licenses/>.
 
-# HACK - https://github.com/cockpit-project/cockpit/issues/3338
-# Use mac's in name policy, prevents interference from network-scripts
-mkdir -p /etc/systemd/network
-printf "[Link]\nNamePolicy=kernel database onboard mac\nMACAddressPolicy=persistent" > /etc/systemd/network/99-default.link
-rm /etc/udev/rules.d/80-net-setup-link.rules
-
 # fully upgrade host first
 atomic host upgrade
 
diff --git a/test/images/fedora-atomic b/test/images/fedora-atomic
index 16ece08..fd66ee8 120000
--- a/test/images/fedora-atomic
+++ b/test/images/fedora-atomic
@@ -1 +1 @@
-fedora-atomic-da42ff7d38639746c0b06bcc47a2f97f04a498c6.qcow2
\ No newline at end of file
+fedora-atomic-6260f86fc3892d7a77d4911f891d0516ec06d7e7.qcow2
\ No newline at end of file
```

**Comment by mvollmer** [comment]
> New images are uploading with the following change

Thanks, I added a commit with those changes.

**Comment by stefwalter** [comment]
Fedora Atomic is now failing above when looking for "HelloMessage". in testExpose: http://fedorapeople.org/groups/cockpit/logs/pull-3382-5f4f90a0-fedora-atomic/log.html

**Comment by mvollmer** [comment]
> Fedora Atomic is now failing above when looking for "HelloMessage". in testExpose: 

This might be the known issue #3360.

**Comment by stefwalter** [comment]
> This might be the known issue #3360.

If it is, then we should add a known issue file for it.

**Pull request closed without merging**
