### PR TITLE
test: Make sure there really is no connection

### PR DESCRIPTION
**Pull request by mvollmer**
when testing ghost settings.

### CODE REVIEW

**Comment by stefwalter** [comment]
This test failure seems related:

```
# testNoConnectionSettings (check_networking.TestNetworking)
#
52:54:00:12:34:56 -> ens6
52:54:00:12:34:56 -> ens6
Wrote TestNetworking-testNoConnectionSettings-FAIL.png
Journal extracted to TestNetworking-testNoConnectionSettings-10.111.121.7-FAIL.log
not ok 84 testNoConnectionSettings (check_networking.TestNetworking) duration: 87s
Traceback (most recent call last):
  File "./verify/check-networking", line 573, in testNoConnectionSettings
    con_id = wait(lambda: iface_con_id(iface))
  File "/build/cockpit/test/common/testlib.py", line 1154, in wait
    raise Error(msg or "Condition did not become true.")
Error: Condition did not become true.
```

**Comment by stefwalter** [comment]
Possibly related failure?

```
# testBasic (check_networking.TestNetworking)
#
52:54:00:9e:00:F2 -> ens6
52:54:00:9e:00:F2 -> ens6
Wrote TestNetworking-testBasic-FAIL.png
Journal extracted to TestNetworking-testBasic-10.111.120.159-FAIL.log
not ok 59 testBasic (check_networking.TestNetworking) duration: 83s
Traceback (most recent call last):
  File "./verify/check-networking", line 129, in testBasic
    b.wait_popdown("network-ip-settings-dialog")
  File "/build/cockpit/test/common/testlib.py", line 272, in wait_popdown
    self.wait_not_visible('#' + id)
  File "/build/cockpit/test/common/testlib.py", line 244, in wait_not_visible
    return self.wait_js_func('!ph_is_visible', selector)
  File "/build/cockpit/test/common/testlib.py", line 214, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 721, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 744, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by stefwalter** [comment]
Related failure:

```
# testNoConnectionSettings (check_networking.TestNetworking)
#
52:54:00:12:34:56 -> eth0
52:54:00:12:34:56 -> eth0
Resource Error: Connection refused http://10.111.117.229:9090/network
Restarting browser...
Wrote TestNetworking-testNoConnectionSettings-FAIL.png
Journal extracted to TestNetworking-testNoConnectionSettings-10.111.117.229-FAIL.log
not ok 73 testNoConnectionSettings (check_networking.TestNetworking) duration: 136s
Traceback (most recent call last):
  File "./verify/check-networking", line 588, in testNoConnectionSettings
    self.assertEqual(cons.strip(), "")
AssertionError: '/org/freedesktop/NetworkManager/Settings/{3}' != ''
```

**Comment by mvollmer** [comment]
The test now configures NM so that it doesn't automatically creates connections instead of deleting the unwanted ones.

**Comment by stefwalter** [comment]
Related failure:

```
# testNoConnectionSettings (check_networking.TestNetworking)
#
Resource Error: Connection refused http://10.111.119.146:9090/network
Restarting browser...
52:54:00:12:34:56 -> eth0
52:54:00:12:34:56 -> eth0
Wrote TestNetworking-testNoConnectionSettings-FAIL.png
Journal extracted to TestNetworking-testNoConnectionSettings-10.111.119.146-FAIL.log
not ok 106 testNoConnectionSettings (check_networking.TestNetworking) duration: 140s
Traceback (most recent call last):
  File "./verify/check-networking", line 594, in testNoConnectionSettings
    self.assertEqual(cons.strip(), "")
AssertionError: '/org/freedesktop/NetworkManager/Settings/{0}' != ''
```

**Comment by mvollmer** [comment]
On fedora-atomic there was a left-over connection setting that accidentally matched the newly hotplugged interface.

**Pull request closed without merging**
