### PR TITLE
[no-test] Update translations from Fedora Weblate

### PR DESCRIPTION
**Pull request by cockpituous**

### CODE REVIEW

**Comment by marusak** [comment]
@82ghost82 FYI Italian translations are now being updated and will be included in tomorrows release.

**Review by marusak — APPROVED** [review]

**Comment by martinpitt** [comment]
Weird, I did a lot of German translation updates yesterday morning and was hoping they'd be included. *shrug*

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit-weblate/commit/180ec22aef19b24c8de2de51a9f472c51060192c

There is this 'Commit' button to commit pending changes. Your changes were pending.
I have no idea how this works. Weblate somehow recognizes when translator is done and then commits changes. Or maybe it commits once a day? I don't know, usually when I am done, I just commit it. But it is also possible that normal users don't have commit button.

**Comment by 82ghost82** [comment]
Thank you Matej!
I will look into it as soon as the stable repository of manjaro will update the cockpit package (I think in a couple of weeks or so).
If it won't update it in a reasonable time I will install it myself.

Again thank you for all.

**Pull request merged**
