### PR TITLE
systemd: Show package updates status on front page

### LINKED ISSUE #7758: There is no indicator in cockpit that there are updates available
Downstream RHEL bug https://bugzilla.redhat.com/show_bug.cgi?id=1495543

> Currently, cockpit supports managing subscriptions downstream, but there is no obvious indicator from the cockpit dashboard whether or not there are updates pending.
> 
> It would be ideal if there was some 'globally' visible indicator for whether or not the host being managed had updates visible from PackageKit.

### PR DESCRIPTION
**Pull request by martinpitt**
Show a summary indicator on the system front page whether the host has
available package updates.
    
https://bugzilla.redhat.com/show_bug.cgi?id=1495543
Fixes #7758

 - [x] land some refactorings - PR #8820 
 - [x] blacklist tests on [rhel-7-4](https://fedorapeople.org/groups/cockpit/logs/pull-8822-20180313-223131-3b3a0993-verify-rhel-7-4/log.html)
 - [x] reproduce and fix Andreas' `TypeError: self.refresh_os_updates_state is not a function`
 - [x] fix rhsmd SELinux violations on fedora-27
 - [x] report and naughty rhsmd SELinux violations on RHEL Atomic ([#1556763](https://bugzilla.redhat.com/show_bug.cgi?id=1556763))
 - [x] fix missing `Promise` polyfill for IE (PR #8838)

follow-ups:
 - [ ] add tooltips (blocked on fixing tooltips in general, issue #8829)
 - [ ] improve update availability string on dnf where we don't have correct severities

### CODE REVIEW

**Comment by martinpitt** [comment]
Screenshot from my system:

system-update-indicator

**Comment by andreasn** [comment]
I tested it on my system, and the Server page said "Bug Fix Updates Available", but when I went to the Software Updates page, it showed me a bunch security updates. I do get and "Oops", so something might be janky.

**Comment by andreasn** [comment]
The registration notification works as expected!

**Comment by martinpitt** [comment]
@andreasn: You are on Fedora? cockpit-packagekit has a rather expensive workaround for https://bugs.freedesktop.org/show_bug.cgi?id=101070 . The current system page doesn't currently load all the details from all the updates, so it can't figure this out (it's also just a heuristics by parsing changelogs for CVEs). This should work fine on RHEL.

I don't have known oopses here, can you please post the log of it?

**Comment by andreasn** [comment]
TypeError: self.refresh_os_updates_state is not a function[Learn More] system.js:3911:14

**Comment by martinpitt** [comment]
@andreasn: I could reproduce your bug at last. subscription-manager is broken in Fedora 27, I just filed https://bugzilla.redhat.com/show_bug.cgi?id=1555384 . Once I fixed that locally, I got the crash as well, stupid typo :-) Thanks for finding! Fix pushed.

**Comment by martinpitt** [comment]
Several tests fail on unexpected SELinux violations from rhsmd ([example 1](https://fedorapeople.org/groups/cockpit/logs/pull-8822-20180314-165050-1f270d58-verify-fedora-27/log.html#194), [example 2](https://fedorapeople.org/groups/cockpit/logs/pull-8822-20180314-165050-1f270d58-verify-rhel-atomic/log.html#19)):
```
audit: type=1400 audit(1521046773.361:302): avc:  denied  { write } for  pid=1850 comm="rhsmd" name="nss" dev="dm-0" ino=12642789 scontext=system_u:system_r:rhsmcertd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_var_lib_t:s0 tclass=sock_file permissive=1
audit: type=1400 audit(1521046773.361:302): avc:  denied  { connectto } for  pid=1850 comm="rhsmd" path="/var/lib/sss/pipes/nss" scontext=system_u:system_r:rhsmcertd_t:s0-s0:c0.c1023 tcontext=system_u:system_r:sssd_t:s0 tclass=unix_stream_socket permissive=1
type=1400 audit(1521047735.710:5): avc:  denied  { write } for  pid=1506 comm="rhsmd" name="encodings" dev="dm-0" ino=6446470 scontext=system_u:system_r:rhsmcertd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:lib_t:s0 tclass=dir
type=1400 audit(1521047735.744:6): avc:  denied  { write } for  pid=1506 comm="rhsmd" name="dbus" dev="dm-0" ino=12816715 scontext=system_u:system_r:rhsmcertd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:lib_t:s0 tclass=dir
```
These need to be reported downstream and naughty-ed.

**Comment by martinpitt** [comment]
rhsm is broken on our fedora-27 image due to a missing dependency, I filed that as <https://bugzilla.redhat.com/show_bug.cgi?id=1556738>. But I cannot reproduce the various SELinux violations manually, with either a busctl, or directly starting /usr/libexec/rhsmd or even with logging in on cockpit and have that do the d-bus call.

I do get the violations with running testAbrtReport locally, but that's not yet helpful for downstream. At least after sitting after that test cases' failure, the violations happen again straight after logging in. So that test triggers some change on the system.

**Comment by martinpitt** [comment]
I [reported](https://bugzilla.redhat.com/show_bug.cgi?id=1556763) the rhsmd SELinux violations downstream, and added a naughty override. I also removed  some obsolete SELinux disablings in the tests.

**Comment by martinpitt** [comment]
Ugh, on Windows 8 (with Edge) we get page oopses like mad due to `Promise` not being defined. Seems we need some polyfills here.. This is only being picked up by the tests now because the front page now calls this.

**Comment by martinpitt** [comment]
I fixed the Promise oopses with IE in #8838, and included this here to already confirm with CI (tests run fine locally now, and I verified that the subscription/updates status works in IE). Setting to blocked until that PR lands.

**Pull request merged**
