### PR TITLE
bots: add podman package to fedora-{29,testing,i386} test images

### PR DESCRIPTION
**Pull request by KKoukiou**
* [x] image-refresh fedora-29
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-bgp2p.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11367-20190311-180303/

**Comment by cockpituous** [comment]
image-refresh fedora-29 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-29-20190311-190202

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-34cd2.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11367-20190311-190000/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-testing-20190311-200707

**Comment by martinpitt** [comment]
@KKoukiou : I removed the fedora-i386 image refresh. It's currently terminally broken, see PR #11359.

**Comment by KKoukiou** [comment]
The podman failures are expected. The API changed and needs fix in the source code and tests.

**Comment by martinpitt** [comment]
fedora-testing shows a [reboot failure in timer test](https://209.132.184.41:8493/logs/pull-11367-20190312-134646-4f8096da-verify-fedora-testing/log.html#209). As this was roughly the fourth retry now, let's look at the next retry more closely. This might  be a real regression.

**Comment by martinpitt** [comment]
@KKoukiou : Installing podman onto the f-testing image clearly works. So I'm fine with dropping the f-testing update from this PR, land it, and let us figure out the f-testing regressions on the next auto-update.

**Comment by KKoukiou** [comment]
> @KKoukiou : Installing podman onto the f-testing image clearly works. So I'm fine with dropping the f-testing update from this PR, land it, and let us figure out the f-testing regressions on the next auto-update.

Ok , I 'll repost by just remove the fedora testing commit.

**Pull request merged**
