### PR TITLE
Adjust tests on rhel-7-8

### PR DESCRIPTION
**Pull request by marusak**

### CODE REVIEW

**Comment by martinpitt** [comment]
[TestAtomicScan failure](https://209.132.184.41:8493/logs/pull-12662-20190829-144949-ecbe9f59-cockpit-project-cockpit--rhel-7-8/log.html#189) may also be due to missing `atomic` tool?

**Comment by marusak** [comment]
> TestAtomicScan failure may also be due to missing atomic tool?

Yes, I already have skipImage locally, but want to push once all tests finish up

**Comment by martinpitt** [comment]
The [nfs failure](https://209.132.184.41:8493/logs/pull-12662-20190829-144949-ecbe9f59-cockpit-project-cockpit--rhel-7-8/log.html#129) looks a little weird, as it's looking for "Mounts" but has "mount". But that may also just be a flake.

**Comment by marusak** [comment]
> The nfs failure looks a little weird, as it's looking for "Mounts" but has "mount". But that may also just be a flake.

I think it is flake. This test passed on the image-refresh. Lets see in the next run.

**Comment by martinpitt** [comment]
Same [testNfsBusy](https://209.132.184.41:8493/logs/pull-12662-20190829-154848-16dca8d8-cockpit-project-cockpit--rhel-7-8/log.html#129) failure. However, it's fine to land, it makes things dramatically better already. And container-kubernetes still needs to land, too. just waiting on semaphore.

**Comment by martinpitt** [comment]
Hah, green now, thanks!

**Pull request merged**
