### PR TITLE
common: Always require a non-loopback address in tests

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by stefwalter** [comment]
I have a feeling this may break testing in koji and brew.

**Comment by mvollmer** [comment]
> I have a feeling this may break testing in koji and brew.

But shouldn't that be broken already because of `test_webserver_noredirect_exception `?  That test crashes without a non-loopback address, no?

**Comment by stefwalter** [comment]
I'd like to double check (and make it easy to do so) so we don't break our release tomorrow.

**Comment by stefwalter** [comment]
Works fine, scratch build passed.

**Pull request closed without merging**
