### PR TITLE
kubernetes: Support for sessions machines

### PR DESCRIPTION
**Pull request by petervo**

### CODE REVIEW

**Comment by petervo** [comment]
Still need to make this work with the simple index for the containerized version

**Comment by petervo** [comment]
This is ready for review. I ended up having to change a bit more than I was hoping to to get things to work in the kube container

**Comment by stefwalter** [comment]
I get this failure when clicking through to a node, and going past the key hash troubleshoot dialog:

```
Error: style is null
getPadding@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:52:13
getSize@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:60:17
getSizeInfo@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:155:36
refresh@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:248:36
.link/<@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:305:29
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:14243:23
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:14506:13
tick@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:10389:25
 undefined angular.js:11607:18

Error: style is null
getPadding@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:52:13
getSize@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:60:17
updateSize@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:349:36
.link/<@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:521:29
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:14243:23
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:14506:13
tick@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:10389:25
 undefined angular.js:11607:18

Error: style is null
getPadding@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:52:13
getSize@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:60:17
getSizeInfo@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:155:36
refresh@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:248:36
.link/<@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:293:25
$watchCollectionAction@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:14110:13
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:14243:23
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:14506:13
scheduleApplyAsync/applyAsyncId<@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:14796:11
completeOutstandingRequest@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:4905:7
Browser/self.defer/timeoutId<@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:5285:7
 undefined angular.js:11607:18

Error: style is null
calFontSize@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:382:29
styleFunction@http://localhost:9090/cockpit/@localhost/kubernetes/d3.js:756:15
d3_selectionPrototype.each/<@http://localhost:9090/cockpit/@localhost/kubernetes/d3.js:962:7
d3_selection_each@http://localhost:9090/cockpit/@localhost/kubernetes/d3.js:968:30
d3_selectionPrototype.each@http://localhost:9090/cockpit/@localhost/kubernetes/d3.js:961:1
d3_selectionPrototype.style@http://localhost:9090/cockpit/@localhost/kubernetes/d3.js:746:12
updateTitle@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:396:1
.link/<@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:509:25
watchGroupAction@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:13938:13
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:14401:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:14217:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:14506:13
scheduleApplyAsync/applyAsyncId<@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:14796:11
completeOutstandingRequest@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:4905:7
Browser/self.defer/timeoutId<@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:5285:7
 undefined angular.js:11607:18

Error: style is null
getPadding@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:52:13
getSize@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:60:17
getSizeInfo@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:155:36
refresh@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:248:36
.link/<@http://localhost:9090/cockpit/@localhost/kubernetes/scripts/charts.js:293:25
$watchCollectionAction@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:14110:13
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:14243:23
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:14506:13
scheduleApplyAsync/applyAsyncId<@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:14796:11
completeOutstandingRequest@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:4905:7
Browser/self.defer/timeoutId<@http://localhost:9090/cockpit/@localhost/kubernetes/angular.js:5285:7
 undefined
```

**Comment by petervo** [comment]
FF bug related the charts code. Opened #4484

**Pull request closed without merging**
