### PR TITLE
Fix fedora-28 image

### PR DESCRIPTION
**Pull request by martinpitt**
See individual commits for details.

 * [x] image-refresh fedora-28
 * [x] image-refresh fedora-27

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-3hwcj.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9230-20180524-150303/

**Comment by cockpituous** [comment]
image-refresh fedora-28 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-28-20180524-160202

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-vhqjf.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9230-20180524-170000/

**Comment by martinpitt** [comment]
I pushed fixes for the ABRT and clevis failures.

**Pull request merged**
