### PR TITLE
Avoid nodejs when building for integration tests

### PR DESCRIPTION
**Pull request by stefwalter**
This led to masking certain build failures when later building the RPMs from the same spec file.
    
We just rebuild the fedora-23 image here. Many other basic images currently have regressions and will be updated asynchronously. This update is enough to indicate tarball build failures for now.

### CODE REVIEW

**Comment by stefwalter** [comment]
Uploading new fedora-23 image.

**Comment by stefwalter** [comment]
Test a test build of this against mock for fedora-24 as well ... and that passed.

**Comment by stefwalter** [comment]
http://koji.fedoraproject.org/koji/taskinfo?taskID=14471440

**Comment by dperpeet** [comment]
this should pass additional tests before merging:

- [ ] koji/fedora-23
- [ ] koji/fedora-24
- [ ] verify/fedora-23

**Comment by stefwalter** [comment]
I'm working on the koji/fedora-xx fix for the verify machines.

**Pull request closed without merging**
