### PR TITLE
test: Put back QEMU into Ubuntu VMs

### LINKED ISSUE #6267: check-machines started failing two tests: Host does not support any virtualization options
In PR #6250, PR #6266, and presumably all other current ones there are two test regressions on ubuntu-1604 in `check-machines`:
```
# testBasic (__main__.TestMachines)
#
Ignoring Resource Error: Operation canceled http://10.111.126.106:9090/cockpit/$d812d37ebe0c26f5244a228b9356f74f2318da2a/machines/provider/index.js
ERROR    Host does not support any virtualization options 
error: failed to get domain 'subVmTest1'
error: Domain not found: no domain with matching name 'subVmTest1'
``` 
same for `TestMachines.testDisks`.

I can reproduce that regression on master, so it's not due to the current PRs.

### PR DESCRIPTION
**Pull request by martinpitt**
Commit 6c09ef7 dropped the qemu test dependency on Ubuntu images
mistakenly, as the Debian image setup scripts don't have it either. But
on Debian libvirt-daemon has a Recommends: for it, so it gets pulled in
that way.

This is required for check-machines.

Fixes #6267

### CODE REVIEW

**Comment by martinpitt** [comment]
bot: Image refresh for ubuntu-1604

**Comment by cockpituous** [comment]
Image creation for ubuntu-1604 in process on cockpit-10.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-ubuntu-1604-4efa677d09afe354ce8b9c4ba6b7bf2040bfe762/

**Comment by martinpitt** [comment]
Note that I added "qemu-kvm", which pulls in 25 MB (unpacked) of packages. The full "qemu" also contains support for all other architectures and pulls in 232 MB (unpacked). The tests are fine with just x86 support.

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-ubuntu-1604-4efa677d09afe354ce8b9c4ba6b7bf2040bfe762

**Pull request merged**
