### PR TITLE
Test nm team plugin

### PR DESCRIPTION
**Pull request by dperpeet**
follow-up to #4568

### CODE REVIEW

**Comment by dperpeet** [comment]
if this works, it also obsoletes #4575 (and fixes #4574)

**Comment by mvollmer** [comment]
It's not the test machine that is blocked, but the browser.

**Comment by dperpeet** [comment]
> It's not the test machine that is blocked, but the browser.

The browser isn't being updated while testvm is stuck in exec, so this should free up cycles.

**Comment by dperpeet** [comment]
improved commit message: `test: Don't block browser while waiting for write op`

**Comment by mvollmer** [comment]
This didn't help.

**Pull request closed without merging**
