### PR TITLE
RHEL/CentOS image cleanup, fixes, and improvements

### PR DESCRIPTION
**Pull request by martinpitt**
These are various changes to make downstream testing for @jscotka a lot less hackish.

This will need some rounds of image builds and force-pushes, so don't review this just yet.

 * [x] image-refresh rhel-7
 * [x] image-refresh rhel-7-4
 * [x] image-refresh rhel-7-5
 * [x] image-refresh centos-7
 * [x] image-refresh ipa
 * [x] image-refresh ovirt

Note that this affects more images in principle, but I'd like to avoid having to rebuild all of them in this single PR. That lot ought to prove enough that the changes are not (too) broken. After this I'll update candlepin and ovirt, which are still using CentOS 7.3 - I'll lift them to 7.4 while I'm at it.

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-1g0sk.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8617-20180214-085959/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-26mrp.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8617-20180214-085959/

**Comment by cockpituous** [comment]
image-refresh rhel-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-20180214-094242

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-3gm3q.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8617-20180214-094646/

**Comment by cockpituous** [comment]
Task aborted.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-v27b0.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8617-20180214-122626/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-5ldzp.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8617-20180214-122626/

**Comment by cockpituous** [comment]
image-refresh rhel-7-5 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-5-20180214-131010

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-5ldzp.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8617-20180214-131010/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-6lsn2.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8617-20180214-131010/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-v27b0.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8617-20180214-131111/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-5ldzp.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8617-20180214-134848/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20180214-144242

**Comment by cockpituous** [comment]
image-refresh in progress on verifymachine4.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8617-20180214-145858/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-6j9xd.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8617-20180214-145959/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-s3z4j.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8617-20180214-150000/

**Comment by cockpituous** [comment]
image-refresh ipa done: https://github.com/cockpituous/cockpit/commits/image-refresh-ipa-20180214-154545

**Comment by cockpituous** [comment]
image-refresh ovirt done: https://github.com/cockpituous/cockpit/commits/image-refresh-ovirt-20180214-155252

**Comment by mvollmer** [comment]
The changes to `virt-builder-fedora` affect more images than what we have tested here, but we will test that eventually.

**Pull request merged**
