### PR TITLE
storaged: remove please from dialogs

### PR DESCRIPTION
**Pull request by jelly**
Remove please from all confirmation dialogs.

image

### CODE REVIEW

**Review by garrett — APPROVED** [review]
:+1: Thanks! Looks good.

**Review by garrett — CHANGES_REQUESTED** [review]
It might be better to follow PF guidelines a little more:

https://www.patternfly.org/v4/components/modal/design-guidelines/#confirm-a-destructive-action

https://www.patternfly.org/v4/components/modal/design-guidelines/#content

> 1.  **Headline:** A headline introduces a modal’s purpose, usually as a question. Use important key words like “permanently” to contextualize an action and its impact.
>     
> 2.  **Body text:** Body text provides additional information about an action’s consequence in three lines or less, typically concerning changes to a user’s workflow or access to information. If a modal’s headline fully communicates an action’s context and consequences, body text isn’t needed.
>     
> 3.  **Buttons:** Buttons allow a user to answer the headline prompt or question. Write button labels as action-based verbs to clearly communicate their function and consequence, and keep them to 1–3 words. Often, verbs for buttons can be pulled directly from a modal’s headline to increase scannability.
>     Example headline: *Permanently delete database?*
>     Example buttons: *Delete* and *Cancel*
>     For more button guidance, see our [button label guidelines](https://www.patternfly.org/v4/components/button/design-guidelines#content).
>

**Comment by marusak** [comment]
@jelly can you please update pixel tests? Thanks!

**Review by garrett — APPROVED** [review]
@jelly and I talked about it and the scope of this PR is to remove the word please from the dialogs.

Further aligning our modal's to PF's guidelines will be more work, across all of Cockpit.

Therefore: Back to approving, based on the scope. Thanks! :+1:

**Review by garrett — DISMISSED** [review]
Approving again.

**Pull request merged**
