### PR TITLE
[rhel-8.5] po: Update from Fedora Weblate

### PR DESCRIPTION
**Pull request by martinpitt**
PO refresh run: https://github.com/cockpit-project/cockpit/runs/3530259411?check_suite_focus=true

### CODE REVIEW

**Comment by marusak** [comment]
This does not seem fully translated:
```
$ msgfmt --statistics zh_CN.po 
1711 translated messages, 73 fuzzy translations, 32 untranslated messages.
```

**Comment by marusak** [comment]
@martinpitt it is always a good idea to force sync in weblate when doing these updates. Notice how there are > 600 changes waiting to be synced:
Screenshot from 2021-09-07 08-02-16

I commited and pushed it, now there are 7 more commits with translations: https://github.com/cockpit-project/cockpit-weblate/commits/rhel-8.5

Can you please update this PR?

**Comment by martinpitt** [comment]
@marusak : Right, I was wondering about that.. This was mostly me trying whether our workflows even work for stable branches, and figuring out the steps to set up weblate (for rhel-9.0). Moving this to draft to do the re-import.

**Comment by martinpitt** [comment]
That's better:
```
❱❱❱ msgfmt --statistics po/zh_CN.po
1816 translated messages.
```

**Review by marusak — APPROVED** [review]
Thanks!

**Comment by marusak** [comment]
oh nice, I was about to comment that we don't test translations on rhels, but seems that we do:
```
        if m.image not in [TEST_OS_DEFAULT] and not m.image.startswith("rhel-"):
            return   
```

**Pull request merged**
