### PR TITLE
fedora-24 image refresh

### PR DESCRIPTION
**Pull request by dperpeet**

### CODE REVIEW

**Comment by dperpeet** [comment]
bot: Image refresh for fedora-24

**Comment by cockpituous** [comment]
Image creation for fedora-24 in process on host32-rack06.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-24-7cccce63207195f1ecebce04e44670839ec05cc8/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by dperpeet** [comment]
@mvollmer 
do you have time to look at the failure?
```
ERROR: Command failed: 
 # /usr/bin/dnf builddep --installroot /var/lib/mock/fedora-24-x86_64/root/ --releasever 24 cockpit-wip-1.fc24.src.rpm --setopt=tsflags=nocontexts
Package gdb-7.11-66.fc24.x86_64 is already installed, skipping.
Package sed-4.2.2-15.fc24.x86_64 is already installed, skipping.
Error: package npm-3.5.4-5.fc24.noarch requires nodejs(engine), but none of the providers can be installed
(try to add '--allowerasing' to command line to replace conflicting packages)
```

**Comment by dperpeet** [comment]
bot: Image refresh for fedora-24

**Comment by cockpituous** [comment]
Image creation for fedora-24 in process on host32-rack06.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-24-7cccce63207195f1ecebce04e44670839ec05cc8/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by dperpeet** [comment]
testing a possible fix in #4269

**Comment by dperpeet** [comment]
looks like that one worked

**Pull request closed without merging**
