### PR TITLE
Image refresh for rhel-atomic

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-atomic
 * [x] image-refresh rhel-atomic

### CODE REVIEW

**Comment by martinpitt** [comment]
`testRegister (check_subscriptions.TestSubscriptions)`
[failed](https://fedorapeople.org/groups/cockpit/logs/pull-7989-20171107-060707-c83de9a2-verify-rhel-atomic/log.html#87):
```
> Subscription status update failed: EntitlementStatus.check_status() failed:
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-subscriptions", line 119, in testRegister
    b.wait_present(register_button_sel)
[...]
Error: timeout
```
Giving this a retry to see if it is a flake.

**Comment by martinpitt** [comment]
subscription-manager indeed seems to be broken on this new image:
```
# subscription-manager status
Error updating system data on the server, see /var/log/rhsm/rhsm.log for more details.

[root@m1 ~]# cat /var/log/rhsm/rhsm.log
2017-11-07 10:40:40,219 [INFO] subscription-manager:2177:MainThread @managercli.py:518 - X-Correlation-ID: a35c61cb05f94efb9f7b408332f61a64
2017-11-07 10:40:40,219 [INFO] subscription-manager:2177:MainThread @managercli.py:407 - Client Versions: {'python-rhsm': '1.19.10-1.el7_4', 'subscription-manager': '1.19.23-1.el7_4'}
2017-11-07 10:40:40,219 [INFO] subscription-manager:2177:MainThread @connection.py:821 - Connection built: host=subscription.rhsm.redhat.com port=443 handler=/subscription auth=identity_cert ca_dir=/etc/rhsm/ca/ insecure=True
2017-11-07 10:40:40,220 [INFO] subscription-manager:2177:MainThread @connection.py:821 - Connection built: host=subscription.rhsm.redhat.com port=443 handler=/subscription auth=none
2017-11-07 10:40:40,225 [ERROR] subscription-manager:2177:MainThread @cache.py:178 - Error updating system data on the server
2017-11-07 10:40:40,225 [ERROR] subscription-manager:2177:MainThread @cache.py:179 - [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/subscription_manager/cache.py", line 170, in update_check
    self._sync_with_server(uep, consumer_uuid)
  File "/usr/lib/python2.7/site-packages/subscription_manager/cache.py", line 522, in _sync_with_server
    content_tags=self.tags)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 1001, in updateConsumer
    ret = self.conn.request_put(method, params)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 654, in request_put
    return self._request("PUT", method, params, headers=headers)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 671, in _request
    info=info, headers=headers)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 527, in _request
    conn.request(request_type, handler, body=body, headers=final_headers)
  File "/usr/lib64/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1227, in connect
    HTTPConnection.connect(self)
  File "/usr/lib64/python2.7/httplib.py", line 807, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
```

**Comment by martinpitt** [comment]
I am comparing `test/vm-run rhel-atomic` from current master and from this PR. this does have networking, so that subscription.rhsm.redhat.com can actually be resolved. There is no chance of resolving it during test runs as the VM does not have an internet connection.

 * subscription-manager RPM is the same (1.19.23-1.el7_4.x86_64), same for python-rhsm (1.19.10-1.el7_4.x86_64)
 * `subscription-manager status; echo $?` differs:
   * master: `Overall Status: Unknown`, status 1
   * this PR: `Consumer profile "8c[...]" has been deleted from the server. You can use command clean or unregister to remove local profile.`, status 69.
* `atomic host status` differs:
```
* rhel-atomic-host-ostree:rhel-atomic-host/7/x86_64/standard
                   Version: 7.4.2-1 (2017-10-19 20:34:49)
                    Commit: 36d9eb2d9b734e5e8552dcdbbe029bb250c00262dffc49f614b1c7a61eb53555

  rhel-atomic-host-ostree:rhel-atomic-host/7/x86_64/standard
                   Version: 7.4.2 (2017-10-17 02:47:56)
                    Commit: 2eceacd73c4de494ff3f90448467934614cf9f72cb316693db2cad47bd79015e
```

The first layer is new from this PR, so apparently this contains the regression. When I roll back to 7.4.2, it works again.

**Comment by martinpitt** [comment]
I just manually updated the ostree on our (not so) current rhel-atomic image to 7.4.3, and subscription-manager is happy after update and reboot. So let's try this again.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-cz849.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7989-20180119-082626/

**Comment by cockpituous** [comment]
image-refresh rhel-atomic done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-atomic-20180119-084545

**Comment by martinpitt** [comment]
Refreshing a PR doesn't work that way, let's just create a fresh one.

**Pull request closed without merging**
