### PR TITLE
test: Don't disable preload for nonexisting packages

### LINKED ISSUE #14133: test: Don't disable preload when package not installed
Now we disable preloading on Fedora 31 images for systemd and packagekit. This is problematic if these packages don't exists. Do it somehow more clever, like check if package exists or at least wrap it into try/except block so it does not break tests.

See https://github.com/cockpit-project/starter-kit/pull/317

### PR DESCRIPTION
**Pull request by martinpitt**
Fixes #14133

### CODE REVIEW

**Comment by martinpitt** [comment]
I tested this with starter-kit with dropping the `mkdir` workaround:
```
+ if test -e /usr/share/cockpit/packagekit; then echo yes; fi
+ if test -e /usr/share/cockpit/systemd; then echo yes; fi
yes
+ cat > '/usr/share/cockpit/systemd/override.json'
```

Marking release blocker, as that blocks https://github.com/cockpit-project/bots/pull/1407 and will obsolete the hacks in starter-kit and co.

**Comment by martinpitt** [comment]
This only affects the default OS (fedora-32), but triggering another one as well for good measure.

**Comment by martinpitt** [comment]
Grrr, [nothing works right](https://logs.cockpit-project.org/logs/pull-14943-20201123-050437-afa3e157-fedora-32/log.html#184-2).. this breaks `check-packagekit TestUpdates.testBasic`, which is certainly related, just not obvious how.

**Review by marusak — APPROVED** [review]
Thanks :)

**Pull request merged**
