### PR TITLE
Update spec file for fedora changes

### PR DESCRIPTION
**Pull request by stefwalter**

### CODE REVIEW

**Comment by mvollmer** [comment]
This needs a new image with the new dependency.

**Comment by mvollmer** [comment]
Depends on #1745, to make the magic hubbot label work.

**Comment by mvollmer** [comment]
Hubbot makes new images now (http://files.cockpit-project.org/hubbot/2ac22885ed66c3cfed1b84aaa198d8abe8b4e324.3), but `cockpit.setup` still needs to be updated.

(We could change the setup procedure to take the dependencies from the actual rpm....)

**Comment by stefwalter** [comment]
Added pcp. I think that the images stuff changes significantly with the work @jscotka  is doing. So I'm fine with just patching in 'pcp' manually for now.

**Comment by mvollmer** [comment]
Fun with image updates again... Docker has been updated, there is no "docker.socket" and no "docker" group anymore.

**Comment by stefwalter** [comment]
> Fun with image updates again... Docker has been updated, there is no "docker.socket" and no "docker" group anymore.

So this depends on: #1595

**Comment by mvollmer** [comment]
I'll remove the hubbot label because it wastes a lot of time and we know it fails.

**Comment by mvollmer** [comment]
Depends on #1755.

**Pull request closed without merging**
