### PR TITLE
vagrant: Improve docs

### PR DESCRIPTION
**Pull request by mvollmer**
and simplify the Vagrantfile

### CODE REVIEW

**Comment by dperpeet** [comment]
Does it make sense to remove the port forwarding just because something *might* already be listening on that port?

**Comment by mvollmer** [comment]
> Does it make sense to remove the port forwarding just because something might already be listening on that port?

Good question.  We can keep the port forwarding, but then we should tell people to stop anything that is listening there, I'd say.  We could also forward to  a different port that is less likely to have someone listen on it.  What about 9999?

**Comment by dperpeet** [comment]
> Good question. We can keep the port forwarding, but then we should tell people to stop anything that is listening there, I'd say. We could also forward to a different port that is less likely to have someone listen on it. What about 9999?

The point is also that once the config is there, it's a lot easier for a developer to change that port. Let's keep the forwarding!
If we have to change the port, why not to 9091? I think it's arbitrary and not entirely sure that we need to change it away from 9090 at all - isn't the likelihood of one or the other being taken pretty much the same?

**Comment by mvollmer** [comment]
> I think it's arbitrary and not entirely sure that we need to change it away from 9090 at all - isn't the likelihood of one or the other being taken pretty much the same?

Well, Cockpit listens on 9090 by default in Fedora, no? :-)

**Comment by mvollmer** [comment]
I have removed the Vagrantfile changes from this PR.

**Pull request closed without merging**
