### PR TITLE
Ubuntu 1604

### PR DESCRIPTION
**Pull request by mvollmer**
This continues #4901.

### CODE REVIEW

**Comment by stefwalter** [comment]
Looks like 8 remaining Ubuntu 16.04 tests are failing. We're nearly there :)

**Comment by mvollmer** [comment]
Last test run: https://fedorapeople.org/groups/cockpit/logs/pull-5285-a4a07a56-verify-ubuntu-1604/log.html

**Comment by mvollmer** [comment]
@petervo, can you check `check-multi-machine-key`?  It's probably much faster for you than for me.

**Comment by stefwalter** [comment]
@mvollmer Does this need a fix on Ubuntu?

```
> Using older 'udisks2' implementation: 2.1.7
Page error: TypeError: undefined is not a function (evaluating 'e.mdraids[t].Delete({"tear-down":{t:"b",v:!0}})')
http://10.111.117.150:9090/cockpit/$18b7af83ad8ba46cbba50f3980d3a89626430259/storage/storage.js 8 action
http://10.111.117.150:9090/cockpit/$18b7af83ad8ba46cbba50f3980d3a89626430259/storage/storage.js 7 
http://10.111.117.150:9090/cockpit/$18b7af83ad8ba46cbba50f3980d3a89626430259/base1/jquery.js 2 dispatch
http://10.111.117.150:9090/cockpit/$18b7af83ad8ba46cbba50f3980d3a89626430259/base1/jquery.js 2 handle
 0 dispatchEvent
phantomjs://code/phantom-lib.js 121 ph_click
 1 
 1 
Wrote TestStorage-testRaid-FAIL.png
```

**Comment by petervo** [comment]
@mvollmer libssh on ubuntu is too old. 0.6.3-4.3 doesn't support what we need for key auth. So we disable it. I think the test is safe to skip for now.

**Comment by mvollmer** [comment]
> I think the [check-multi-machine-key] test is safe to skip for now.

Thanks, makes sense.

**Comment by mvollmer** [comment]
> `undefined is not a function (evaluating 'e.mdraids[t].Delete`

Indeed!  I am so used to races and stuff and the tests so rarely gets to this point without running into a known issue, that I completely missed that UDisks2 doesn't have a Delete method for raids...

**Comment by stefwalter** [comment]
Needs this patch:

```
diff --git a/test/verify/naughty-rhel-7/4978-docker-selinux-broken-12 b/test/verify/naughty-rhel-7/4978-docker-selinux-broken-12
deleted file mode 100644
index bbf696d..0000000
--- a/test/verify/naughty-rhel-7/4978-docker-selinux-broken-12
+++ /dev/null
@@ -1,3 +0,0 @@
-Traceback (most recent call last):
-  File "./verify/check-docker", line 396, in testRestart
-    b.wait_popdown("containers_run_image_dialog")
diff --git a/test/verify/naughty-rhel-7/4978-docker-selinux-broken-6 b/test/verify/naughty-rhel-7/4978-docker-selinux-broken-6
index 1b3f780..0849d43 100644
--- a/test/verify/naughty-rhel-7/4978-docker-selinux-broken-6
+++ b/test/verify/naughty-rhel-7/4978-docker-selinux-broken-6
@@ -1,3 +1,3 @@
 Traceback (most recent call last):
-  File "./verify/check-docker", line 398, in testRestart
+  File "./verify/check-docker", line 397, in testRestart
     b.wait_popdown("containers_run_image_dialog")
```

**Comment by stefwalter** [comment]
Priority for next release.

**Pull request closed without merging**
