### PR TITLE
Remove hard realmd dependency

### PR DESCRIPTION
**Pull request by stefwalter**
Talk directly to realmd.

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #2073 

Ready for review.

**Comment by stefwalter** [comment]
Fixed bundling.

**Comment by stefwalter** [comment]
VERIFY passed here locally.

**Comment by mvollmer** [comment]
The default domain is discovered, but it doesn't appear in the text field.  (The administrator name appears.)

**Comment by mvollmer** [comment]
This makes the default realm appear.  (But l10n is broken, as with the default admin.)

```
diff --git a/pkg/realmd/operation.js b/pkg/realmd/operation.js
index e34ee03..2739bab 100644
--- a/pkg/realmd/operation.js
+++ b/pkg/realmd/operation.js
@@ -197,6 +197,10 @@ define([
             if (mode != 'join')
                 return;
 
+            if (realm && realm.Name && !$(".realms-op-address")[0].placeholder) {
+                $(".realms-op-address")[0].placeholder = _('e.g. "' + realm.Name + '"');
+            }
+
             var placeholder = "";
             if (kerberos) {
                 if (kerberos.SuggestedAdministrator)
```

**Comment by stefwalter** [comment]
Fixed l10n of placeholders. Added domain placeholder.

**Comment by mvollmer** [comment]
Needs a rebase.

**Comment by stefwalter** [comment]
Rebased.

**Comment by stefwalter** [comment]
@mvollmer has already reviewed this. VERIFY has passed.

**Pull request closed without merging**
