### PR TITLE
shell: Allow for content being "null" in file watching callbacks.

### PR DESCRIPTION
**Pull request by mvollmer**
This happened consistently with hubbot here: https://github.com/cockpit-project/cockpit/pull/2096 but I couldn't reproduce it locally.

### CODE REVIEW

**Comment by stefwalter** [comment]
This is really weird. What kind of messages or back traces were present? This seems like a bug elsewhere. Why would the passwd file ever be empty?

**Comment by mvollmer** [comment]
> This is really weird. What kind of messages or back traces were present? This seems like a bug elsewhere. Why would the passwd file ever be empty?

The callback is called with content == null when the file does not exist, or when there was a read error.
I did not find any other messages.

I'll make this more noisy as part of #2096...

**Comment by mvollmer** [comment]
> I'll make this more noisy as part of #2096...

Now it doesn't happen anymore, of course...

**Comment by mvollmer** [comment]
In any case, we need to do better than crash when `content === null`.  There can always be errors, such as a network disconnection.

**Pull request closed without merging**
