### PR TITLE
storage: Re-order format dialog fields

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
Looks like this now:

image

image

**Review by martinpitt — APPROVED** [review]
Looks fine to me, thanks! But also requesting review from @garrett , in case he has some  opinion there.

**Comment by mvollmer** [comment]
> But also requesting review from @garrett , in case he has some opinion there.

Yes, and there are many more fixes coming, which we probably should all be in the same release, so that the Format dialog doesn't change a little bit in each of the next five releases.

**Comment by mvollmer** [comment]
Part of #15937 now.

**Pull request closed without merging**
