### PR TITLE
bots: Remove unnecessary files from Debian/Ubuntu images

### PR DESCRIPTION
**Pull request by martinpitt**
- Drop pbuilder apt cache (> 300 MB compressed debs), we pre-install
   cockpit's build dependencies into the chroot tar.
 - Drop docker devicemapper images (~ 230 MB); aufs-dkms usually gets
   installed later so that first time docker starts in devmapper mode.
 - Drop apt binary caches (~ 50 MB) if present; they get regenerated on
   demand and are not necessary for functionality, only to speed up
   "apt-cache show" (which we don't need for testing).

This saves about 200 MB on the resulting .qcow.

 - [x] image-refresh debian-stable
 - [x] image-refresh debian-testing
 * [x] image-refresh ubuntu-stable
 * [x] image-refresh ubuntu-1604

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-x6t6m.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7629-20170908-100101/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7629-20170908-100101/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-l68xd.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7629-20170908-100606/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7629-20170908-100606/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-9gmd4.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7629-20170908-102828/

**Comment by martinpitt** [comment]
```
❱❱❱ du -s debian-*
1023164	debian-stable-b6a3a310358546cc8721398ca75108d93bfa6af6f2152073cefc1cbf72610e35.qcow2
1177408	debian-stable-e5711db797f7c92cdddf6955a97968f964baebd1ea74411ae1f2da1f5c87263a.qcow2
1625348	debian-testing-22c09aa767a351d409d8686b703ea0f549d075a569811a1abdf8e4bb7b0c2b81.qcow2
1390604	debian-testing-ba2a6c738b0c177b0e7f77f750a8916aecb29c72604fdf3b1f63f17a3adb5cb3.qcow2
```
So even more savings (250 MB) on debian-testing.

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7629-20170908-102828/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-x6t6m.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7629-20170908-105252/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-9mk9t.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7629-20170908-105252/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-11.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7629-20170908-105555/

**Comment by cockpituous** [comment]
image-refresh ubuntu-1604 done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-1604-20170908-112626

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-86zpl.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7629-20170908-112525/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-stable-20170908-115353

**Pull request closed without merging**
