### PR TITLE
Check for NPM dependency updates: requirejs

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update requirejs

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```src/base1/Makefile.am:	cat $(srcdir)/src/base1/deprecated.js $(srcdir)/src/base1/require-config.js $(srcdir)/node_modules/requirejs/require.js $(srcdir)/src/base1/require-loaders.js > $@.tmp && $(MV) $@.tmp $@
tools/build-debian-copyright:                    # https://github.com/requirejs/requirejs/issues/1645
```

**Comment by cockpituous** [comment]
npm-update c3 done: https://github.com/cockpituous/cockpit/commits/npm-update-c3-20170718-063131

**Comment by cockpituous** [comment]
Task threw an exception: http://fedorapeople.org/groups/cockpit/logs/npm-update-7310-20170718-063131/

**Comment by cockpituous** [comment]
npm-update c3 done: https://github.com/cockpituous/cockpit/commits/npm-update-c3-20170718-063131

**Comment by cockpituous** [comment]
Task threw an exception: http://fedorapeople.org/groups/cockpit/logs/npm-update-7310-20170718-063131/

**Comment by stefwalter** [comment]
Nothing in our code uses requirejs, we just ship it for compatibility.

**Pull request merged**
