### PR TITLE
terminal: Update to xterm v4

### PR DESCRIPTION
**Pull request by marusak**
Was there a good reason that resetting would disconnect channel and create new? 

Fixes #12948

### CODE REVIEW

**Comment by marusak** [comment]
I am giving up on selenium tests. When I run it locally (in local browser) it works just fine. Anyone has any idea what could help? The issue is that it does not type anything into the terminal.
I also noticed this is happening sometimes with current master as well, for example [here](https://209.132.184.41:8493/logs/pull-12948-20191015-125151-fcaa9d48-cockpit-project-cockpit--fedora-30-selenium-chrome/screenshot-tearDown-356035.png)

**Comment by marusak** [comment]
@jscotka when I run `LOCAL=yes BROWSER=firefox avocado run test/selenium/selenium-base.py` it passes just nicely, but in CI it does not do anything. You seem to understand selenium, can you please give me some ideas/hints what should I try?

**Comment by martinpitt** [comment]
I force-pushed this to rebase to current master and resolve the conflicts, and to update to latest react-console and xterm. The old logs are gone, I'd like to get some current ones.

**Comment by martinpitt** [comment]
There is still a [check-terminal failure](https://209.132.184.41:8493/logs/pull-12948-20191229-090808-13b120b4-cockpit-project-cockpit--rhel-8-2/log.html#263-2). Maybe I screwed up the rebase?

**Comment by marusak** [comment]
> There is still a check-terminal failure. Maybe I screwed up the rebase?

I think you bumped xterm from `3.1.0` to `3.4.0`. I think I know what could be the issue, I'll take a look.

**Pull request merged**
