### PR TITLE
storage: Hide breadcrumbs on Overview

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Review by garrett — APPROVED** [review]
Thanks! It works here.

**Review by jelly — APPROVED** [review]

**Comment by KKoukiou** [comment]
I see the anaconda webui tests are broken in all storage PRs. Let's check it tomorrow to continue testing this.

**Comment by mvollmer** [comment]
> I see the anaconda webui tests are broken in all storage PRs. Let's check it tomorrow to continue testing this.

Yes, it seems to always be `mkdir: cannot create directory ‘/var/tmp/build/SRPMS’: Permission denied`.

**Comment by jelly** [comment]
> > I see the anaconda webui tests are broken in all storage PRs. Let's check it tomorrow to continue testing this.
> 
> Yes, it seems to always be `mkdir: cannot create directory ‘/var/tmp/build/SRPMS’: Permission denied`.

FYI: this is started by `.github/workflows/trigger-anaconda.yml` which from reading just triggers a copr build for Cockpit and then triggers `bots/tests-trigger $prid fedora-rawhide-boot/cockpit-pr-$prid@rhinstaller/anaconda-webui

So we are trying to build an Anaconda webui with the current Cockpit-storaged. What I don't quite follow is where the `mkdir` comes from as it's not in our `test/vm.install`

**Comment by jelly** [comment]
> > I see the anaconda webui tests are broken in all storage PRs. Let's check it tomorrow to continue testing this.
> 
> Yes, it seems to always be `mkdir: cannot create directory ‘/var/tmp/build/SRPMS’: Permission denied`.

FYI: this is started by `.github/workflows/trigger-anaconda.yml` which from reading just triggers a copr build for Cockpit and then triggers `bots/tests-trigger $prid fedora-rawhide-boot/cockpit-pr-$prid@rhinstaller/anaconda-webui

So we are trying to build an Anaconda webui with the current Cockpit-storaged. What I don't quite follow is where the `mkdir` comes from as it's not in our `test/vm.install`

> > > I see the anaconda webui tests are broken in all storage PRs. Let's check it tomorrow to continue testing this.
> > 
> > 
> > Yes, it seems to always be `mkdir: cannot create directory ‘/var/tmp/build/SRPMS’: Permission denied`.
> 
> FYI: this is started by `.github/workflows/trigger-anaconda.yml` which from reading just triggers a copr build for Cockpit and then triggers `bots/tests-trigger $prid fedora-rawhide-boot/cockpit-pr-$prid@rhinstaller/anaconda-webui
> 
> So we are trying to build an Anaconda webui with the current Cockpit-storaged. What I don't quite follow is where the `mkdir` comes from as it's not in our `test/vm.install`
> 
> Edit: I forgot the webui code was split up: https://github.com/rhinstaller/anaconda-webui/blob/main/test/vm.install#L57
> 
> Reading the code we should not even hit this, so that's where the problem is.
> 
> https://github.com/rhinstaller/anaconda-webui/blob/main/test/vm.install#L53
> 
> Our TEST_SCENARIO is:
> 
> ```
> Command:       /bin/sh -c 'PRIORITY=0005 ./make-checkout --verbose --repo=rhinstaller/anaconda-webui main && cd make-checkout-workdir && TEST_OS=fedora-rawhide-boot BASE_BRANCH=main COCKPIT_BOTS_REF=main TEST_SCENARIO=cockpit-pr-19828 ../tests-invoke --pull-number 19828 --revision 6c2b981c2d41bc1ea953bf802ace8205d9982fa9 --repo cockpit-project/cockpit'
> ```
> 
> Anaconda expects something completely different and thus does not download the copr's.
> 
> @KKoukiou I believe the latest refactor of `test/vm.install` introduced this breakage:
> 
> https://github.com/rhinstaller/anaconda-webui/blob/main/test/vm.install#L53
> 
> ```
>         if not scenario or not scenario.startswith("anaconda-webui-pr-"):
> ```
> 
> Should probably be `if scenario is None` ? But I guess in this case we need to build anaconda itself so we should enter this condition no?
> 
> Last succesful scenario run seems to be this one so 16 December: https://cockpit-logs.us-east-1.linodeobjects.com/pull-19722-20231211-131923-711c6701-fedora-rawhide-boot-cockpit-pr-19722-rhinstaller-anaconda-webui/log

So 16 December, so ignore everything I said before...

**Pull request merged**
