### PR TITLE
docker: default to showing only running containers

### LINKED ISSUE #3965: Containers view should default to "running"
The way it is now:

Containers view defaults to "All", showing all containers on stored on the machine.  If there are a lot of dead containers, this is quite cluttered.

The way it should be:

The default view should be "running" containers.

### PR DESCRIPTION
**Pull request by larsu**
Fixes #3965

### CODE REVIEW

**Comment by stefwalter** [comment]
Looks like the file ```test/verify/check-docker``` needs a change:

```
Error: #containers-containers tr:contains("PROBE2") is not visible
```

http://fedorapeople.org/groups/cockpit/logs/pull-3987-150058cb-verify-rhel-atomic/log.html

**Comment by dperpeet** [comment]
Regarding the case we touched on in irc: restarting containers

I think it would detract if containers disappeared and then reappeared in a short time frame. Maybe the can be greyed out and disappear after a few seconds, unless they become active again. @andreasn Is it worth the effort of creating such a transitory state? If so, what is a sensible length of time? 5-10 seconds?

**Comment by andreasn** [comment]
Yeah, I think it would help ease that specific state where you need to restart something again. It would work especially well if it gained less and less opacity as it fades out, so it doesn't just pop away suddenly.

**Comment by stefwalter** [comment]
dperpeet Do the containers actually disappear from the running list during a restart?

**Comment by dperpeet** [comment]
> dperpeet Do the containers actually disappear from the running list during a restart?

I didn't test this, @larsu mentioned this as something that he didn't like when applying the proposed change

**Comment by dperpeet** [comment]
After trying this locally on fedora 23, I couldn't create a case where restart caused the container entry to disappear from the list. @larsu did you speculate or did you actually see an entry disappear?

**Comment by larsu** [comment]
> After trying this locally on fedora 23, I couldn't create a case where restart caused the container entry to disappear from the list.

There's a way to restart the container from the list view? I meant that it immediately disappears for me when clicking the ⏹ (stop) button.

**Comment by stefwalter** [comment]
I tihnk having the container disappear from the list of running containers isn't really that bad. It's the same as on the command line 'docker ps'. 

We could have a summary somewhere that shows 'N stopped containers'. But I would suggest making that a separate pull request.

**Comment by stefwalter** [comment]
Thanks! Merged.

**Pull request closed without merging**
