### PR TITLE
test: Adapt TestStorageLuks.testReboot for recent changes

### PR DESCRIPTION
**Pull request by mvollmer**
We missed this when merging #13192.

### CODE REVIEW

**Comment by martinpitt** [comment]
It needs a [special case for distropkg](https://logs.cockpit-project.org/logs/pull-16277-20210830-101943-c670d7a0-rhel-8-5-distropkg/log.html#287) apparently?

**Comment by martinpitt** [comment]
I also saw a failure of [TestStorageMounting.testEncryptedMountingHelp](https://logs.cockpit-project.org/logs/pull-16276-20210830-084427-3f4267f9-debian-testing/log.html#279-2), but that could just be a genuine new bug/race from #13192, instead of a conflict with another PR.

**Comment by mvollmer** [comment]
> It needs a [special case for distropkg](https://logs.cockpit-project.org/logs/pull-16277-20210830-101943-c670d7a0-rhel-8-5-distropkg/log.html#287) apparently?

No, that looks like a independent bug/flake.

**Comment by martinpitt** [comment]
For this PR we probably need to land with red tests, as the new tests are flaky and often [fail on the third retry](https://logs.cockpit-project.org/logs/pull-16277-20210830-121814-c670d7a0-rhel-8-5-distropkg/log.html#287-2).

But [this failure](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-16277-20210830-121811-c670d7a0-centos-8-stream/log.html#287) happened on the first retry, so I'm retrying that again.

**Comment by martinpitt** [comment]
@mvollmer: [testLuks on centos-8-stream](https://logs.cockpit-project.org/logs/pull-16277-20210830-132517-c670d7a0-centos-8-stream/log.html#287) failed three times in  a row. I land this now to break "most" other PRs, but I think this one is sticky.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
