### PR TITLE
lib: Fix DynamicListForm state confusion on removals

### PR DESCRIPTION
**Pull request by martinpitt**
When deleting an item, set it to `undefined` (i.e. keep it as a hole in
`list`) instead of completely removing it. Before, removing the first
item shifted all the indexes around, which broke keys/ids and the state
handling, so that it appeared as if the wrong element got deleted.

With that, `list.length` becomes meaningless. Adjust the emptiness check
in the render function. Entirely drop `itemCount` -- nothing uses that,
and it's a bit expensive to compute, so let's only introduce this when
there is an actual use case.

https://issues.redhat.com/browse/RHEL-19598

----

no-test, as we don't use this component anywhere in cockpit. This is for cockpit-machines. https://github.com/cockpit-project/cockpit-machines/pull/1381 adds an integration test for that bug, and runs against that branch for the time. I tested it locally interactively, but I want to see green machines tests before we land this.

### CODE REVIEW

**Comment by martinpitt** [comment]
Works, first run in https://github.com/cockpit-project/cockpit-machines/pull/1381 is green (on our CI, anyway, TF still running)

**Comment by jelly** [comment]
Podman also uses this component, as the TF tests are green this should introduce no issues for cockpit-podman right?

**Review by jelly — APPROVED** [review]
Thanks! That was a very subtle bug which we never caught in cockpit-podman!

**Comment by martinpitt** [comment]
@jelly this is a build-time change, runtime is okay. I'll send a podman PR similar to https://github.com/cockpit-project/cockpit-machines/pull/1381 afterwards to mop up the API change. But I did confirm that podman also doesn't use the `itemCount` property.

**Pull request merged**
