### PR TITLE
shell: Only display 'Account Settings' menu item when ready

### PR DESCRIPTION
**Pull request by stefwalter**
We need user information to load before the 'Account Settings'
menu item is ready. In the tests sometimes we race with this.
Fix the race, and real world corner case.

### CODE REVIEW

**Comment by stefwalter** [comment]
Fixes this issue:

```
Traceback (most recent call last):
  File "./verify/check-keys", line 83, in testAuthorizedKeys
    login("user", "foobar", "User")
  File "./verify/check-keys", line 57, in login
    b.expect_load()
  File "/build/cockpit/test/common/testlib.py", line 126, in expect_load
    self.phantom.expect_load()
  File "/build/cockpit/test/common/testlib.py", line 689, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 712, in _invoke
    raise Error(res['error'])
```

**Comment by stefwalter** [comment]
Updated rhel-7 SELinux known issue #5010

**Comment by dperpeet** [comment]
> Updated rhel-7 SELinux known issue #5010

This issue is also in the naughty section for centos-7, fedora-24, fedora-25 and fedora-testing.

**Comment by stefwalter** [comment]
Updated other naughty files.

**Pull request closed without merging**
