### PR TITLE
bots: Use same NPM registry for npm install in VM as on the host

### LINKED ISSUE #12790: Image refresh for fedora-30
Image refresh for fedora-30
 * [ ] FAIL: image-refresh fedora-30

### PR DESCRIPTION
**Pull request by martinpitt**
The fedora-* image installs chrome-remote-interface for the Selenium
tests. Our internal CI now has npmjs.com access firewalled off, and sets
an internal NPM registry mirror. Make sure to use that in the VM as
well.

Fixes #12790

 * [x] image-refresh fedora-30

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-tests-hmx0v.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12799-20190913-143232/

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-05.
Log: https://209.132.184.41:8493/logs/image-refresh-12799-20190913-143232/

**Comment by martinpitt** [comment]
Warning, this is totally untested (I'm a bit under time crunch right now, so letting our CI exercise this)

**Comment by martinpitt** [comment]
I pushed a little cleanup. @marusak , perhaps you can take over next week, while I'm on PTO?

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-91tqh.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12799-20190913-150909/

**Comment by martinpitt** [comment]
Interrupting manually -- for this I actually want a bos machine, as centosci doesn't have an npm mirror.

**Comment by cockpituous** [comment]
image-refresh in progress on 2-ci-srv-04.
Log: https://209.132.184.41:8493/logs/image-refresh-12799-20190913-151010/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-12799-20190913-143232/

**Comment by cockpituous** [comment]
Task failed: https://209.132.184.41:8493/logs/image-refresh-12799-20190913-151010/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-7.
Log: https://209.132.184.41:8493/logs/image-refresh-12799-20190922-075555/

**Comment by cockpituous** [comment]
image-refresh fedora-30 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-30-20190922-083030

**Comment by martinpitt** [comment]
This image somehow breaks the [container/bastion test](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-12799-20190922-142828-b8740553-cockpit-project-cockpit--fedora-30-container-bastion/log.html)

**Comment by martinpitt** [comment]
Replaced with https://github.com/cockpit-project/bots/pull/29

**Pull request closed without merging**
