### PR TITLE
machines: fix string translations in status cards

### LINKED ISSUE #12503: Machines: "Virtual Networks" is plural when there's only one.
When there's 1 virtual network, the string should say "1 Virtual Network". Everything else should be "# Virtual Networks".

Screenshot_2019-08-06 Virtual Machines - Rain

This _might_ also be the same for storage pool / storage pools. I'm not sure.

### PR DESCRIPTION
**Pull request by KKoukiou**
Fixes #12503

### CODE REVIEW

**Comment by marusak** [comment]
Thanks :) Could we also have some simple test for this?

**Comment by KKoukiou** [comment]
> Thanks :) Could we also have some simple test for this?

Sure, I will add it tomorrow.

**Comment by KKoukiou** [comment]
> > Thanks :) Could we also have some simple test for this?
> 
> Sure, I will add it tomorrow.

It was quick - done.

**Comment by martinpitt** [comment]
This looks good, but other parts of the tests now also need to be adjusted to expect the singular instead of plural.

**Pull request merged**
