### PR TITLE
playground: Port React Demo dialog to ct-form-layout

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by garrett** [comment]
Great idea!

I'd suggest also porting [my demo page](https://garrett.github.io/cockpit-mockweb/forms/grid) over, but it'd be better to include those in the actual dialogs they replicate. (And we've ported a few over already.)

So porting the playground over and porting the dialogs in the demo should be enough?

Notes:
1. There's [a bunch of documentation in the LESS file](https://github.com/cockpit-project/cockpit/blob/master/pkg/lib/form-layout.less#L11-L47).
2. `<label for="unique-form-element-id">Label text</label>` is important for a11y (keyboard nav and screen readers) and general usability (clicking on a label will focus the widget it refers to). In React, it's `htmlFor=""`.

**Comment by martinpitt** [comment]
@garrett: I tried to add `for=` to the `<Select>` inputs, and it does absolutely nothing. I also tried to addit to the button, and there it actively makes things worse: Clicking on the label causes a click to the button (!). Apparently this only works for text inputs, so I'd rather not change it. (Note that this PR does not change the ID → for mapping at all).

**Comment by garrett** [comment]
Using for with a dropdown should focus the dropdown, as shown in this example: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

Oh... right. Our selects aren't actually selects. That's why it's problematic. :roll_eyes:

I guess that means we cannot use `for`?

(I wish PF used native dropdowns, like https://www.filamentgroup.com/lab/select-css.html)

**Comment by martinpitt** [comment]
> I guess that means we cannot use for?

At least not for standard buttons and Cockpit's select, yes. Which is probably the reason why only the input has a `for` in the current playground dialog.

**Comment by garrett** [comment]
Yep, totally.

This sparked the discussion about porting our select to HTML's native select, with some style to match our current selects (and PF3's selects). But that's outside the scope of this PR. :wink:

Speaking of this PR: LGTM! :+1:

**Pull request merged**
