### PR TITLE
Stop disting node_modules/ fragments

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
This is the branch to stop disting fragments of node_modules/ for copyright and dependency purposes.

I'm currently locally inspecting in detail the difference between the generated tarballs, but it looks pretty promising so far...

### CODE REVIEW

**Comment by allisonkarlitskaya** [comment]
Some stats collected locally (I hacked the version to always be 300 to make comparisons easier):

```
toolbox:~/src/cockpit$ ls -l */cockpit-300.tar.xz
-rw-r--r--. 1 lis lis 15015500 Feb 11 10:57 main/cockpit-300.tar.xz
-rw-r--r--. 1 lis lis 13833964 Feb 11 10:57 scan-copyright/cockpit-300.tar.xz
```

```
toolbox:~/src/cockpit$ ls */cockpit-300*/node_modules
main/cockpit-300/node_modules:
bootstrap		 commander   json-stable-stringify-without-jsonify  mustache	      prop-types  react      redux	  sizzle	     ws
bootstrap-datepicker	 deep-equal  js-sha1				    patternfly	      qunit	  react-dom  redux-thunk  throttle-debounce  xterm
chrome-remote-interface  jquery      moment				    patternfly-react  qunit-tap   README     remarkable   uuid

scan-copyright/cockpit-300/node_modules:
chrome-remote-interface  commander  README  sizzle  ws
```

```
toolbox:~/src/cockpit$ du -hs */cockpit-300*/node_modules
7.5M	main/cockpit-300/node_modules
1.9M	scan-copyright/cockpit-300/node_modules
```

```
toolbox:~/src/cockpit$ ls -l */cockpit-300/COPYING.node
-rw-r--r--. 1 lis lis  72856 Feb 11 10:56 main/cockpit-300/COPYING.node
-rw-r--r--. 1 lis lis 230872 Feb 11 10:57 scan-copyright/cockpit-300/COPYING.node
```

```
toolbox:~/src/cockpit$ ls -l */cockpit-300*/tools/debian/cop*
-rw-r--r--. 1 lis lis 42009 Feb 11 10:58 main/cockpit-300/tools/debian/copyright
-rw-r--r--. 1 lis lis 11738 Nov 24 00:48 main/cockpit-300/tools/debian/copyright.template
-rw-r--r--. 1 lis lis 41208 Feb 11 10:58 scan-copyright/cockpit-300/tools/debian/copyright
-rw-r--r--. 1 lis lis 13895 Feb 11 09:26 scan-copyright/cockpit-300/tools/debian/copyright.template
```

Meanwhile, the main changes to the generated tarballs (other than the direct code changes here) are that the included `Makefiles.deps` files no longer have the `node_modules/` files listed in them, but get the `included-modules` entry added instead.

**Review by martinpitt — APPROVED** [review]
This looks great to me, thanks for the cleanups!

**Review by martinpitt — CHANGES_REQUESTED** [review]
Lis spotted that at the last minute: d/copyright has top-level dir prefixes like

    Files: cockpit-237.24.gfce8fdf90/dist/machines/*

That needs to be stripped off to comply with d/copyright format.

**Review by martinpitt — APPROVED** [review]
Superb, merci beaucoup !

**Pull request merged**
