### PR TITLE
Make breadcrumbs sticky in all pages that can get 'tall' enough

### LINKED ISSUE #1523: Breadcrumb bar needs to be in fixed frame
The breadcrumb bar at the top of various pages needs to be in a fixed frame, so it doesn't scroll when you scroll the page. Having basic navigation scroll out of view is broken.

### PR DESCRIPTION
**Pull request by KKoukiou**
Fixes #1523

### CODE REVIEW

**Comment by KKoukiou** [comment]
Oh I broke hwinfo tests, will repost.

**Comment by marusak** [comment]
Nice work!
Firewall looks a bit weird though: (to my eyes at least)
weirdfirewall

**Comment by KKoukiou** [comment]
> Nice work!
> Firewall looks a bit weird though: (to my eyes at least)
> weirdfirewall

Oh right, the firewall header should also be part of the sticky component. So I can either repost and split or post the firewall fix right after we merge this, since it's not too bad. Let me know what you prefer.

**Comment by marusak** [comment]
> Oh right, the firewall header should also be part of the sticky component. So I can either repost and split or post the firewall fix right after we merge this, since it's not too bad. Let me know what you prefer.

In an ideal world I would like to see this PR updated :) But if it is realistically too hard to get green, then we can merge this and have follow up.

**Comment by KKoukiou** [comment]
> > Oh right, the firewall header should also be part of the sticky component. So I can either repost and split or post the firewall fix right after we merge this, since it's not too bad. Let me know what you prefer.
> 
> In an ideal world I would like to see this PR updated :) But if it is realistically too hard to get green, then we can merge this and have follow up.

It is really hard. I retried already at least 3 times. Anyway, i see some failures that seem unrelated but are not common flakes so I would actually rather split it.

**Review by marusak — APPROVED** [review]
Thanks!
The firewall thingy will be a follow up.

**Pull request merged**
