### PR TITLE
test: Let all Browser.wait_*() methods wait for the selector first

### PR DESCRIPTION
**Pull request by martinpitt**
A lot of Cockpit's own pages and extensions use React, so elements
appear and disappear all the time. This leads to a lot of redundant and 
error prone test code that has to remember to always wait for an element
before doing an action on it or waiting for a property of it; this has 
been the source of many flakes.

Take a page out of cypress.io's book and just always wait for the 
selector to be present first. This is only negligible practical
overhead, as waiting for an existing element is very cheap, and we can 
in return clean up a lot of explicit `wait_present()` calls from our 
tests.

### CODE REVIEW

**Comment by martinpitt** [comment]
I've only cleaned up two tests here. I plan to do this on a mass-scale with the help of [RedBaron](https://redbaron.readthedocs.io/en/latest/).

Also, we should do a similar thing to `wait_visible()`, and also wait  for an element to be/become enabled, but step by step.

**Comment by martinpitt** [comment]
There [are](https://209.132.184.41:8493/logs/pull-11492-20190329-094141-cc0d920a-verify-centos-7/log.html) [a](https://209.132.184.41:8493/logs/pull-11492-20190329-094141-cc0d920a-verify-fedora-29/log.html) [bunch](https://209.132.184.41:8493/logs/pull-11492-20190329-094141-cc0d920a-verify-fedora-30/log.html) [of](https://209.132.184.41:8493/logs/pull-11492-20190329-094141-cc0d920a-verify-rhel-7-6-distropkg/log.html) [flakes](https://209.132.184.41:8493/logs/pull-11492-20190329-094141-cc0d920a-verify-rhel-8-0/log.html), but they look like our usual suspects and none are related to not finding an element.

**Comment by mvollmer** [comment]
> I think we've had this discussion before though, so I'd like to get @mvollmer's opinion as well.

I agree that we should "auto-wait" for presence, also for clicks and everything else. In addition, click should auto-wait for visibility.

Way in the past, we had a synchronous relationship between the test code and the code under test: The code under test was paused while the test code was running, and it would only progress when the test code was waiting.  This means that we could assume that between waits, the DOM wouldn't change.  This is no longer true (and we have fixed the very few flakes we got from that), so randomly waiting doesn't violate any assumptions of the DOM being constant.

**Comment by mvollmer** [comment]
`test: Let all Browser.wait_*() methods wait for the selector first`, this changes more than just the `wait_*` functions.

**Comment by martinpitt** [comment]
@mvollmer: Agreed. I plan to add auto-waiting for visibility and similar stuff too, just one step at a time.

**Pull request merged**
