### PR TITLE
package.json: Update @patternfly/patternfly, @patternfly/react-styles, @patternfly/react-core, @patternfly/react-table

### PR DESCRIPTION
**Pull request by cockpituous**

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "@patternfly/patternfly": "4.102.1",
package.json:    "@patternfly/react-core": "4.115.1",
package.json:    "@patternfly/react-styles": "4.10.1",
package.json:    "@patternfly/react-table": "4.26.6",
pkg/apps/application-list.jsx:} from "@patternfly/react-core";
pkg/apps/application.jsx:} from "@patternfly/react-core";
pkg/apps/utils.jsx:import { Button, Progress, Split, SplitItem, Spinner } from "@patternfly/react-core";
pkg/base1/cockpit.js:import "@patternfly/patternfly/components/Button/button.css";
pkg/kdump/kdump-view.jsx:} from "@patternfly/react-core";
pkg/kdump/kdump.scss:@import "@patternfly/patternfly/components/Page/page.scss";
pkg/lib/_global-variables.scss:@import "@patternfly/patternfly/base/patternfly-variables.scss";
pkg/lib/cockpit-components-dialog.jsx:import { Alert, Button, Modal, Popover, Spinner } from "@patternfly/react-core";
pkg/lib/cockpit-components-empty-state.jsx:} from '@patternfly/react-core';
pkg/lib/cockpit-components-file-autocomplete.jsx:import { Select, SelectVariant, SelectOption } from "@patternfly/react-core";
pkg/lib/cockpit-components-inline-notification.jsx:import { Alert, AlertActionCloseButton, Button } from '@patternfly/react-core';
pkg/lib/cockpit-components-listing-panel.jsx:import { Nav, NavItem, NavList } from '@patternfly/react-core';
pkg/lib/cockpit-components-logs-panel.jsx:import { Badge, Button, Card, CardHeader, CardActions, CardTitle, CardBody } from '@patternfly/react-core';
pkg/lib/cockpit-components-modifications.jsx:} from '@patternfly/react-core';
pkg/lib/cockpit-components-password.jsx:import { FormGroup, Popover, Progress, ProgressSize, ProgressMeasureLocation, TextInput } from '@patternfly/react-core';
pkg/lib/cockpit-components-plot.jsx:} from '@patternfly/react-core';
pkg/lib/cockpit-components-plot.jsx:import '@patternfly/patternfly/patternfly-charts.scss';
pkg/lib/cockpit-components-privileged.jsx:import { Button, Tooltip, TooltipPosition } from '@patternfly/react-core';
pkg/lib/cockpit-components-shutdown.jsx:} from '@patternfly/react-core';
pkg/lib/cockpit-components-table.jsx:} from '@patternfly/react-table';
pkg/lib/cockpit-components-table.jsx:} from '@patternfly/react-core';
pkg/lib/cockpit-components-table.scss:@import "@patternfly/patternfly/base/patternfly-variables.scss";
pkg/lib/cockpit-components-table.scss:@import "@patternfly/patternfly/components/Table/table.scss";
pkg/lib/cockpit-components-table.scss:@import "@patternfly/patternfly/components/Table/table-grid.scss";
pkg/lib/cockpit-components-terminal.jsx:import { Modal, Button } from "@patternfly/react-core";
pkg/lib/listing.scss:@import "@patternfly/patternfly/sass-utilities/colors.scss";
pkg/lib/page.scss:@import "@patternfly/patternfly/base/patternfly-themes.scss";
pkg/lib/page.scss:@import "@patternfly/patternfly/components/Page/page.scss";
pkg/lib/patternfly/patternfly-4-cockpit.scss:@import '@patternfly/patternfly/patternfly-base.scss';
pkg/lib/serverTime.js:import { Button, Popover, Select, SelectOption, SelectVariant } from '@patternfly/react-core';
pkg/metrics/metrics.jsx:} from '@patternfly/react-core';
pkg/metrics/metrics.jsx:import { Table, TableHeader, TableBody, TableGridBreakpoint, TableVariant, TableText, RowWrapper, cellWidth } from '@patternfly/react-table';
pkg/metrics/metrics.scss:@import "@patternfly/patternfly/components/Table/table.scss";
pkg/networkmanager/app.jsx:import { Button } from "@patternfly/react-core";
pkg/networkmanager/firewall-switch.jsx:import { Switch, Tooltip } from "@patternfly/react-core";
pkg/networkmanager/firewall.jsx:} from '@patternfly/react-core';
pkg/networkmanager/interfaces.js:import { Switch } from "@patternfly/react-core";
pkg/networkmanager/network-interface-members.jsx:} from '@patternfly/react-core';
pkg/networkmanager/network-interface.jsx:} from "@patternfly/react-core";
pkg/networkmanager/network-main-dialogs.jsx:} from "@patternfly/react-core";
pkg/networkmanager/network-main.jsx:} from "@patternfly/react-core";
pkg/networkmanager/networking.scss:@import "../../node_modules/@patternfly/react-styles/css/components/Alert/alert.css";
pkg/networkmanager/networking.scss:@import "../../node_modules/@patternfly/patternfly/components/Button/button.css";
pkg/networkmanager/networking.scss:@import "../../node_modules/@patternfly/patternfly/components/Page/page.css";
pkg/networkmanager/networking.scss:@import "../../node_modules/@patternfly/patternfly/components/Breadcrumb/breadcrumb.css";
pkg/networkmanager/networking.scss:@import "../../node_modules/@patternfly/patternfly/layouts/Gallery/gallery.css";
pkg/networkmanager/networking.scss:@import "../../node_modules/@patternfly/patternfly/components/Card/card.css";
pkg/networkmanager/networking.scss:@import "../../node_modules/@patternfly/patternfly/components/Table/table.css";
pkg/networkmanager/networking.scss:@import "../../node_modules/@patternfly/patternfly/components/Table/table-grid.css";
pkg/networkmanager/networking.scss:@import "../../node_modules/@patternfly/patternfly/components/Toolbar/toolbar.css";
pkg/networkmanager/networking.scss:@import "../../node_modules/@patternfly/patternfly/components/Backdrop/backdrop.css";
pkg/networkmanager/networking.scss:@import "../../node_modules/@patternfly/patternfly/layouts/Bullseye/bullseye.css";
pkg/networkmanager/networking.scss:@import "../../node_modules/@patternfly/patternfly/components/ModalBox/modal-box.css";
pkg/networkmanager/plots.js:import { Split, SplitItem, Grid, GridItem } from '@patternfly/react-core';
pkg/packagekit/autoupdates.jsx:} from '@patternfly/react-core';
pkg/packagekit/history.jsx:import { Tooltip } from "@patternfly/react-core";
pkg/packagekit/updates.jsx:} from '@patternfly/react-core';
pkg/packagekit/updates.jsx:import { cellWidth, TableText } from "@patternfly/react-table";
pkg/playground/journal.jsx:import "../../node_modules/@patternfly/patternfly/components/Page/page.css";
pkg/playground/jquery-patterns.js:import "../../node_modules/@patternfly/patternfly/components/Button/button.css";
pkg/playground/jquery-patterns.js:import "../../node_modules/@patternfly/patternfly/components/Page/page.css";
pkg/playground/react-demo-cards.jsx:} from '@patternfly/react-core';
pkg/playground/react-patterns.js:import "../../node_modules/@patternfly/patternfly/components/Page/page.css";
pkg/playground/speed.js:import "../../node_modules/@patternfly/patternfly/components/Button/button.css";
pkg/playground/speed.js:import "../../node_modules/@patternfly/patternfly/components/Page/page.css";
pkg/playground/test.js:import "../../node_modules/@patternfly/patternfly/components/Button/button.css";
pkg/playground/test.js:import "../../node_modules/@patternfly/patternfly/components/Page/page.css";
pkg/selinux/setroubleshoot-view.jsx:} from "@patternfly/react-core";
pkg/shell/active-pages-dialog.jsx:import { Label, Split, SplitItem } from '@patternfly/react-core';
pkg/shell/credentials.js:import { Switch } from "@patternfly/react-core";
pkg/shell/hosts.jsx:import { PageSidebar, Button } from '@patternfly/react-core';
pkg/shell/hosts.jsx:import "../../node_modules/@patternfly/patternfly/components/Select/select.css";
pkg/shell/nav.jsx:} from '@patternfly/react-core';
pkg/shell/shell-modals.jsx:} from '@patternfly/react-core';
pkg/shell/shell.scss:@import "@patternfly/patternfly/components/Button/button.scss";
pkg/shell/superuser.jsx:import { Button, FormSelect, FormSelectOption, Modal } from '@patternfly/react-core';
pkg/sosreport/sosreport.scss:@import "@patternfly/patternfly/components/Alert/alert.scss";
pkg/sosreport/sosreport.scss:@import "@patternfly/patternfly/components/Button/button.scss";
pkg/sosreport/sosreport.scss:@import "@patternfly/patternfly/components/Page/page.scss";
pkg/sosreport/sosreport.scss:@import "@patternfly/patternfly/components/EmptyState/empty-state.scss";
pkg/sosreport/sosreport.scss:@import "@patternfly/patternfly/components/Backdrop/backdrop.scss";
pkg/sosreport/sosreport.scss:@import "@patternfly/patternfly/layouts/Bullseye/bullseye.scss";
pkg/sosreport/sosreport.scss:@import "@patternfly/patternfly/components/ModalBox/modal-box.scss";
pkg/storaged/block-details.jsx:} from "@patternfly/react-core";
pkg/storaged/content-views.jsx:import { Card, CardHeader, CardTitle, CardBody, CardActions, Spinner, Text, TextVariants } from "@patternfly/react-core";
pkg/storaged/crypto-keyslots.jsx:} from "@patternfly/react-core";
pkg/storaged/crypto-panel.jsx:import { cellWidth, SortByDirection } from '@patternfly/react-table';
pkg/storaged/crypto-tab.jsx:} from "@patternfly/react-core";
pkg/storaged/details.jsx:import { Page, PageSection, Grid, GridItem, Breadcrumb, BreadcrumbItem } from "@patternfly/react-core";
pkg/storaged/dialog.jsx:} from "@patternfly/react-core";
pkg/storaged/drive-details.jsx:} from "@patternfly/react-core";
pkg/storaged/fsys-panel.jsx:import { cellWidth, SortByDirection } from '@patternfly/react-table';
pkg/storaged/fsys-tab.jsx:} from "@patternfly/react-core";
pkg/storaged/iscsi-panel.jsx:import { Button } from "@patternfly/react-core";
pkg/storaged/jobs-panel.jsx:} from "@patternfly/react-core";
pkg/storaged/lvol-tabs.jsx:} from "@patternfly/react-core";
pkg/storaged/mdraid-details.jsx:} from "@patternfly/react-core";
pkg/storaged/multipath.jsx:} from "@patternfly/react-core";
pkg/storaged/nfs-details.jsx:} from "@patternfly/react-core";
pkg/storaged/nfs-panel.jsx:import { cellWidth, SortByDirection } from '@patternfly/react-table';
pkg/storaged/optional-panel.jsx:} from "@patternfly/react-core";
pkg/storaged/overview.jsx:import { Page, Grid, GridItem, Card, CardBody, Gallery } from "@patternfly/react-core";
pkg/storaged/part-tab.jsx:} from "@patternfly/react-core";
pkg/storaged/plot.jsx:import { Split, SplitItem, Grid, GridItem } from '@patternfly/react-core';
pkg/storaged/pvol-tabs.jsx:} from "@patternfly/react-core";
pkg/storaged/side-panel.jsx:import { Button, Spinner, EmptyState, EmptyStateVariant, EmptyStateBody, Flex, FlexItem } from '@patternfly/react-core';
pkg/storaged/storage-controls.jsx:} from '@patternfly/react-core';
pkg/storaged/storage.scss:@import "../../node_modules/@patternfly/patternfly/components/Card/card.css";
pkg/storaged/swap-tab.jsx:} from "@patternfly/react-core";
pkg/storaged/unrecognized-tab.jsx:} from "@patternfly/react-core";
pkg/storaged/vdo-details.jsx:} from "@patternfly/react-core";
pkg/storaged/vgroup-details.jsx:} from "@patternfly/react-core";
pkg/systemd/abrtLog.jsx:} from '@patternfly/react-core';
pkg/systemd/hwinfo.jsx:} from '@patternfly/react-core';
pkg/systemd/hwinfo.jsx:import { SortByDirection } from "@patternfly/react-table";
pkg/systemd/hwinfo.scss:@import "../../node_modules/@patternfly/patternfly/components/Page/page.css";
pkg/systemd/logDetails.jsx:} from '@patternfly/react-core';
pkg/systemd/overview-cards/configurationCard.jsx:} from '@patternfly/react-core';
pkg/systemd/overview-cards/configurationCard.scss:@import "../../../node_modules/@patternfly/patternfly/components/Backdrop/backdrop.css";
pkg/systemd/overview-cards/configurationCard.scss:@import "../../../node_modules/@patternfly/patternfly/layouts/Bullseye/bullseye.css";
pkg/systemd/overview-cards/configurationCard.scss:@import "../../../node_modules/@patternfly/patternfly/components/ModalBox/modal-box.css";
pkg/systemd/overview-cards/healthCard.jsx:import { Card, CardBody, CardFooter, CardTitle } from '@patternfly/react-core';
pkg/systemd/overview-cards/insights.jsx:import { Button } from '@patternfly/react-core';
pkg/systemd/overview-cards/motdCard.jsx:import { Alert, AlertActionCloseButton, Button, Modal, TextArea } from '@patternfly/react-core';
pkg/systemd/overview-cards/systemInformationCard.jsx:import { Card, CardBody, CardFooter, CardTitle } from '@patternfly/react-core';
pkg/systemd/overview-cards/usageCard.jsx:} from '@patternfly/react-core';
pkg/systemd/overview.jsx:} from '@patternfly/react-core';
pkg/systemd/overview.scss:@import "@patternfly/patternfly/components/Table/table.scss";
pkg/systemd/page-status.jsx:import { Button } from "@patternfly/react-core";
pkg/systemd/reporting.jsx:import { Button, Card, CardBody, CardTitle, Split, SplitItem, Spinner } from "@patternfly/react-core";
pkg/systemd/services/service-details.jsx:} from "@patternfly/react-core";
pkg/systemd/services/service-tabs.jsx:import { Nav, NavList, NavItem } from '@patternfly/react-core';
pkg/systemd/services/service.jsx:} from '@patternfly/react-core';
pkg/systemd/services/services-list.jsx:} from '@patternfly/react-core';
pkg/systemd/services/services.jsx:} from '@patternfly/react-core';
pkg/systemd/services/services.scss:@import "@patternfly/patternfly/components/Toolbar/toolbar.scss";
pkg/systemd/services/timer-dialog.jsx:} from '@patternfly/react-core';
pkg/systemd/superuser-alert.jsx:} from '@patternfly/react-core';
pkg/systemd/terminal.jsx:} from "@patternfly/react-core";
pkg/systemd/terminal.scss:@import "../../node_modules/@patternfly/patternfly/components/Button/button.css";
pkg/systemd/terminal.scss:@import "../../node_modules/@patternfly/patternfly/components/Toolbar/toolbar.scss";
pkg/tuned/change-profile.jsx:import { Label, Split, SplitItem } from '@patternfly/react-core';
pkg/users/account-create-dialog.js:import { Checkbox, Form, FormGroup, TextInput } from '@patternfly/react-core';
pkg/users/account-details.js:} from '@patternfly/react-core';
pkg/users/account-roles.js:import { Alert, Checkbox, Tooltip, TooltipPosition } from '@patternfly/react-core';
pkg/users/accounts-list.js:import { Button, Badge, Card, CardBody, Gallery, Page, PageSection, PageSectionVariants } from '@patternfly/react-core';
pkg/users/authorized-keys-panel.js:import { Button, TextArea } from '@patternfly/react-core';
pkg/users/delete-account-dialog.js:import { Checkbox } from '@patternfly/react-core';
pkg/users/expiration-dialogs.js:import { Form, FormGroup, FormHelperText, Radio, TextInput } from '@patternfly/react-core';
pkg/users/password-dialogs.js:import { Form, FormGroup, TextInput } from '@patternfly/react-core';
pkg/users/users.scss:@import "@patternfly/patternfly/components/DataList/data-list.scss";
pkg/users/users.scss:@import "@patternfly/patternfly/components/Form/form.scss";
webpack.config.js:                        stylesheet.includes('@patternfly/react-styles/css/components/Table/') ||
webpack.config.js:                        stylesheet.includes('@patternfly/react-styles/css/components/Page/') ||
webpack.config.js:                        stylesheet.includes('@patternfly/react-styles/css/components/Toolbar/')
```

**Comment by martinpitt** [comment]
This somehow [breaks the time inputs](https://logs.cockpit-project.org/logs/pull-15731-20210422-031034-42b3892c-rhel-8-5/log.html), needswork. Specifically, it now defaults to a placeholder "hh:mm":

image

Instead of the current time, like on master:

image

That seems like a legit change. However, the bottom frame part is missing, which is either a PF bug or a bug in our CSS overrides.

**Comment by martinpitt** [comment]
I went through the other pages, and they seem fine.

**Comment by martinpitt** [comment]
@KKoukiou Can I hand this one to you? I'm happy to adjust the tests to the hh:mm placeholder, but that sounds trivial. I'm more worried about the missing bottom border.

**Comment by KKoukiou** [comment]
* The timepicker should stay with the previous functionality
* The borders were broken indeed - same issue with cssnano as we fixed in cockpit-machines a few days ago

**Comment by KKoukiou** [comment]
Just rebased - it was running these old distcheck unit tests

**Comment by martinpitt** [comment]
Thanks @KKoukiou ! This looks great to me. The unit tests are very prone to failing, so we'll need to rebase that after #15770 lands.

**Comment by KKoukiou** [comment]
Please don't merge - bottom border does not seem fixed. Seems this is another issue.

**Comment by KKoukiou** [comment]
There seems to be some issue with the produced CSS order. Namely,

applying `background-color: var(--pf-c-select__toggle-typeahead--BackgroundColor);` to the component with `pf-c-select__toggle-typeahead` class fixes the issue. However this rule exists already, it's just overriden from a rule from pf-c-form-control which sets `background-color: var(--pf-c-form-control--BackgroundColor);`

These rules seems to have the same specificity, I wonder what makes the problem now persistent. 
@garrett any idea?

**Comment by KKoukiou** [comment]
This is again issue only in the production mode, so it's the minifier doing something weird.

**Comment by garrett** [comment]
Both `css-minimizer-webpack-plugin` and `optimize-css-assets-webpack-plugin` seem to use `cssnano`, which is based on `PostCSS`.

Does swapping one out for the other produce different results?

**Comment by KKoukiou** [comment]
> Both `css-minimizer-webpack-plugin` and `optimize-css-assets-webpack-plugin` seem to use `cssnano`, which is based on `PostCSS`.
> 
> Does swapping one out for the other produce different results?
> 
> (It is, of course, great to use the same package everywhere.)

Nope, I was just trying out.

**Comment by garrett** [comment]
I wonder if there's an option that we should turn off.

I guess a good first test would be to see if things work with all the options turned off, just to see if it's a problem with an option or we're hitting an issue with the minifier itself? (If it's just a feature issue, we could turn it off, but if it's a problem with cssnano that we cannot work around, then we'd have to find another minimizer. Right?)

**Comment by garrett** [comment]
We already have this dropdown issue on production.

Here are screenshots from a production build of Cockpit on Fedora IoT (on my little home server):

Screenshot 2021-06-02 at 09-48-24 Storage - garrett Snow

Screenshot 2021-06-02 at 09-47-29 Overview - garrett Snow

**Comment by garrett** [comment]
Have we tried to set the CSS minimizer to a minimum of features?

For example, https://cssnano.co/docs/optimisations says there's a 'lite' mode. 

I've changed `'default'` to `'lite'` in `webpack.config.js` and am rebuilding now with `NODE_ENV=production ./test/image-prepare -q fedora-34` (is that right?) on this PR and will try running the VM again to see what happens.

**Comment by garrett** [comment]
After looking at that list of optimizations; I think a lot of them are overoptimizations. Basically things that don't matter at all for filesize, but have the risk of breaking things. What we really care about is the squishing together of files and removal of whitespace. 

Browsers, our users, and ourselves don't care if something is sorted one way or another (for example). I get that it's useful for working on CSS to change it in the source files... but unnecessarily messing with the CSS between source and production can (and apparently does) cause bad things to happen.

**Comment by garrett** [comment]
If `NODE_ENV=production ./test/image-prepare -q fedora-34` is correct, then that "fixes" (really: sidesteps) the problem:

Screenshot 2021-06-02 at 14-17-35 Overview - admin fedora

If this is right, we might want to consider a custom list of options, either opt-in or opt-out. I'd suggest nothing except the space-saving ones (and even then, try to stay away from rewriting, as it would probably be extremely marginal gains at best... _especially_ if the files are gzipped anyway).

**Comment by KKoukiou** [comment]
@garrett I wonder how it worked for you; I just pulled this PR and changed default with lite - and I get 'Error: Cannot load preset "lite".'

**Review by allisonkarlitskaya — DISMISSED** [review]
This PR is too old to have the new `node_modules` checks, but if it did, it would have a failing status.  We need to regenerate `node_modules` before attempting to land this.

**Comment by garrett** [comment]
On IRC, @KKoukiou said a new version of cssnano fixes the problem.

We should update all of PatternFly and cssnano, have it all rebased, and use the new node_modules stuff... and try to get this in before the release, please.

**Comment by garrett** [comment]
Reasoning for getting it in for this release:
- I keep hitting issues where I try to use something from PF, but our PF is too old. I'm sure others have this issue too. It's blocking some PRs already.
- The issue shown due to missing CSS has been found in previous releases of Cockpit as well. (I showed some screenshots of the bug from Fedora packages from a previous release.)

**Comment by garrett** [comment]
Removed blocker tag, as:

>    I keep hitting issues where I try to use something from PF, but our PF is too old. I'm sure others have this issue too. It's blocking some PRs already.

PF isn't too old; the CSS just lacked proper imports where needed. :facepalm: Thanks, @KKoukiou for pointing this out.

> The issue shown due to missing CSS has been found in previous releases of Cockpit as well. (I showed some screenshots of the bug from Fedora packages from a previous release.)

cssnano, the culprit, has been updated interdependently and it should hopefully resolve the missing rectangles. Thanks, again, @KKoukiou for updating cssnano.

---

It'd still be nice to upgrade PF at some point soon, but the issues have been resolved elsewhere, so this doesn't block it.

**Review by KKoukiou — APPROVED** [review]
Please squash on merge.

**Review by martinpitt — APPROVED** [review]
Danke! I'm glad that this is finally unstuck.

**Pull request merged**
