### PR TITLE
bots: Put back lorax-composer to CentOS 7 image

### PR DESCRIPTION
**Pull request by martinpitt**
Commit 76e4d94389e conditionalized the installation of lorax-composer on
`$SKIP_REPO_FLAG`, but this was wrong: This flag file exists on CentOS 7
to disable subscriptions, but this is independent from whether we want
lorax-composer.

 * [x] image-refresh centos-7
 * [x] image-refresh rhel-7
 * [x] image-refresh rhel-7-5
 * [x] image-refresh rhel-7-4

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-vz6n9.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8332-20180101-155050/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20180101-162525

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-dc3rc.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8332-20180101-163131/

**Comment by martinpitt** [comment]
Both images have lorax-composer again.

**Comment by cockpituous** [comment]
image-refresh rhel-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-20180101-170404

**Comment by petervo** [comment]
@martinpitt 7.4 and 7.5 also use the same setup script. Are these changes going to cause problems there? Should we rebuild those as well here?

**Comment by martinpitt** [comment]
@petervo: They use the same code paths, but for extra scrutiny I'll request rebuilds.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-b06lw.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8332-20180102-160404/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8332-20180102-173636/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-5vprj.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8332-20180103-072424/

**Comment by cockpituous** [comment]
image-refresh rhel-7-4 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-4-20180103-075454

**Comment by martinpitt** [comment]
RHEL 7.4 and 7.5 images built and included into the commits here, and I hauled over the RHEL 7.5 test adjustments from PR #8289.

**Comment by martinpitt** [comment]
Tests on the new rhel-7-5 image are quite hard to get green.. Most of the time it seems `testNodeNavigation` fails, but in other logs it's different tests. So basically just a giant flake. This one almost succeeded: https://fedorapeople.org/groups/cockpit/logs/pull-8332-20180104-113838-6ac7a3b4-verify-rhel-7-5/log.html (but got stuck at the very end for some reason), so it's not a hard regression.

**Comment by martinpitt** [comment]
@stefwalter : Thanks; I hope that wasn't premature, but we might need to fix the tests on rhel-7-5 either way.

**Pull request closed without merging**
