### PR TITLE
various updates for main

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
- [x] cockpit-project/bots#2177

### CODE REVIEW

**Comment by martinpitt** [comment]
All tests fail with

      FETCH    bots  [ref: master]
    fatal: couldn't find remote ref master

Did you rename that already?

**Review by martinpitt — COMMENTED** [review]
The changes here look good, but are obviously blocked on the bots/cockpituous renamings.

**Comment by allisonkarlitskaya** [comment]
```
  FETCH    bots  [ref: master]
fatal: couldn't find remote ref master
Test run finished, return code: 128
```

running on old bots that set a ref to its own no-longer-existing `master` branch.  No big surprise there.  Let's land cockpit-project/bots#2177 and try this again.

**Comment by allisonkarlitskaya** [comment]
```
  FETCH    bots  [ref: main]
  CLONE    bots  [ref: main]
```

Looks nicer :)

**Review by martinpitt — APPROVED** [review]
Dependencies now seem in place.

**Pull request merged**
