### PR TITLE
Image refresh for rhel-7-5

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-7-5
 * [x] image-refresh rhel-7-5

### CODE REVIEW

**Comment by martinpitt** [comment]
Test failure:
```
# testOtherSettings (check_networking_settings.TestNetworking)
#
Warning: Permanently added '[127.0.0.2]:2301' (ECDSA) to the list of known hosts.
Warning: Permanently added '[127.0.0.2]:2302' (ECDSA) to the list of known hosts.
NAME         UUID                                  TYPE      DEVICE 
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
virbr0       704b4a47-8da5-49d3-910e-b9499b3ef2bb  bridge    virbr0 
System eth1  9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     

52:54:01:00:00:03 -> eth2
52:54:01:00:00:03 -> eth2

(process:1863): GLib-GIO-WARNING **: gdbusobjectmanagerclient.c:1588: Processing InterfaceRemoved signal for path /org/freedesktop/NetworkManager/DHCP4Config/2 but no object proxy exists

(process:1863): GLib-GIO-WARNING **: gdbusobjectmanagerclient.c:1588: Processing InterfaceRemoved signal for path /org/freedesktop/NetworkManager/IP4Config/8 but no object proxy exists

(process:1863): GLib-GIO-WARNING **: gdbusobjectmanagerclient.c:1588: Processing InterfaceRemoved signal for path /org/freedesktop/NetworkManager/IP6Config/7 but no object proxy exists
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-networking-settings", line 107, in testOtherSettings
    "foo")
AssertionError: '' != 'foo'
```
Retrying.

**Comment by martinpitt** [comment]
The errors is persistent, so this needs investigation.

**Comment by martinpitt** [comment]
I can't reproduce this locally even after 20 iterations, so retrying on the infra again.

**Comment by martinpitt** [comment]
@mvollmer, do you have an idea what this is failing on?

**Comment by mvollmer** [comment]
The new version of NM resets ipv4.dhcp-hostname when setting ipv4.method to "shared": https://bugzilla.redhat.com/show_bug.cgi?id=1519299 . I am not sure whether that is a bug or a feature.

We only need a setting that is not explicitly handled by Cockpit for this test, so let's try to use connection.gateway-timeout instead.

**Comment by martinpitt** [comment]
Apparently the image timed out and got pruned, so rebuilding it.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-tkkjb.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8093-20171130-170707/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-ccc04.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8093-20171130-170808/

**Comment by cockpituous** [comment]
image-refresh rhel-7-5 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-5-20171130-174141

**Pull request merged**
