### PR TITLE
overview: remove some custom styling from our superuser alert 

### PR DESCRIPTION
**Pull request by KKoukiou**
Before:
Screen Shot 2021-04-01 at 14 06 22

After:
Screen Shot 2021-04-01 at 14 18 23

### CODE REVIEW

**Comment by garrett** [comment]
When we made the overrides, the inline alerts looked quite different.

Also, it's more like a banner... https://www.patternfly.org/v4/components/banner/react-demos/basic-sticky-banner/ but PF banners are too small and don't support buttons.

The last login banner clashes with this too. But That should probably be in the system information card under uptime. (IIRC: The login notification was added without consulting either Andreas or myself. It just appeared one day.)

**Comment by KKoukiou** [comment]
> When we made the overrides, the inline alerts looked quite different.

This PR just removes the custom CSS to make the superuser not look different from other alerts at least. 

> 
> Also, it's more like a banner... https://www.patternfly.org/v4/components/banner/react-demos/basic-sticky-banner/ but PF banners are too small and don't support buttons.
>

So let's keep it an info alert.
 
> The last login banner clashes with this too. But That should probably be in the system information card under uptime. (IIRC: The login notification was added without consulting either Andreas or myself. It just appeared one day.)

I agree, and I can move it but separately from this.

**Comment by garrett** [comment]
>> login notification
> I agree, and I can move it but separately from this.

Yep, totally! I didn't mean in this PR; just pointing out that the two notifications clash. Happy you agree!

> This PR just removes the custom CSS

Happy about dropping all the custom stuff that is no longer needed.

---

OK, so I like this PR in general, but I do have the following issues with the results at the moment:

The sides should line up. This would require interior padding on the left and right of the banner/alert. As it doesn't have padding outside (nor should it), we need special casing here. It's on both sides.

Screenshot from 2021-04-08 16-22-54

Here's the right side:

Screenshot from 2021-04-08 16-23-08

Also the vertical alignment is odd. There's 48px above the bottom and 60px below. It should be equal. Some of this is due to the line at the top, which is unnecessary in this case (as it blends in too much with the dark background of shell above). When the line is counted, there is 55px above the button. But with the line, even with equal padding above and below, it may look visually "off". 

This vertical spacing issue is a problem with the text on the left too, but it's easier to see it with the button (and the text and the button should be vertically aligned to one another already).

(There are also some vertical alignment issues with the icons by a few pixels. I think we still have a longstanding issue open in the PF repos about this, so I'm ignoring it here... and it also affects the icons outside the notification too, so it's definitely not specific to this PR.)

**Comment by garrett** [comment]
A fix for the padding on the sides would be to use the PF utilitity classes for padding: `pf-u-pl-lg` `pf-u-pr-lg`, as seen on https://www.patternfly.org/v4/utilities/spacing/

It might need to be handled differently for responsive modes too. But there's (the same) + `-on-lg` for that too, etc.

**Comment by KKoukiou** [comment]
* @garrett In the current master the button on the right is far from aligned as well. It did not break here. Here is a screenshot from master.
Screenshot from 2021-04-09 12-03-24

I will try to fix the right side alignment issue however.

* The icons are indeed some pixes of vertically, this is broken everywhere on master since ever and I have created an issue upstream as well. https://github.com/patternfly/patternfly/issues/3959

* Regarding the left side it looks correct to me with the current PR, the center of the icons should be used to alignment base . https://www.patternfly.org/v4/guidelines/icons/
Previously we had the left side aligned from the left of the icons, which is wrong.

**Comment by garrett** [comment]
> In the current master the button on the right is far from aligned as well. It did not break here. Here is a screenshot from master.

Right, it's a regression. It wasn't like this before some point in time when PF was updated. Just bringing it up as it impacts this PR somewhat, as the overrides had assumptions that are no longer true and this is affecting the overrides.

> I will try to fix the right side alignment issue however.

Thanks!

> The icons are indeed some pixels of vertically, this is broken everywhere on master since ever and I have created an issue upstream as well.

Ah, this issue is actually for the buttons, not the icons. But button vertical alignment in cards is a problem too. Thanks for opening that issue!

For reference, alignment issues:

- SVG: https://github.com/patternfly/patternfly/issues/3628
- pficon: https://github.com/patternfly/patternfly/issues/3536

**Review by garrett — APPROVED** [review]
(Apologies for taking a while to respond on this one. I had it in an open tab and lost it between all the other PRs. Whoops.)

Looks good at normal (and even mobile) sizes. Thanks!

Screenshot_2021-04-14 Overview - garrett Rain

However, when it's quite wide (at >= 1440px viewport, but this includes the shell), the margin at the left isn't right. (The right side is right though.)

Screenshot_2021-04-14 Overview - garrett Rain(1)

Anyway, it's an improvement overall. If you can easily fix the left side in larger sizes, please include that in this PR too. But it might be tricky, with icon padding or something else mysteriuous. If so, a follow-up is OK.

Marking as "approve", as my guess is that it's trickier (as the right side is doing the right thing and the left includes an icon and such).

**Comment by KKoukiou** [comment]
@garrett I have no clear idea for fixing about the left spacing but I can take a look when I have time as a followup.

**Comment by garrett** [comment]
Yeah, it wasn't clear to me either, but I didn't look at it closely. I'm happy to work together to figure it out. At least it's not a big deal and doesn't show up under many circumstances.

**Pull request merged**
