### PR TITLE
bots: Drop hack in run-queue, always specify repo

### PR DESCRIPTION
**Pull request by Gundersanne**
This is currently causing trouble, because I'm simulating standalone-bots still. This should fix the issue.

### CODE REVIEW

**Comment by marusak** [comment]
`issue-scan` would never get repo specified. Would that be fine?

**Comment by Gundersanne** [comment]
@marusak nope, I was a little bit too zealous with pushing :p

**Comment by Gundersanne** [comment]
@marusak Actually it's fine, as issue-scan uses the issue_data to get the repository. Tests-scan does not.

**Comment by martinpitt** [comment]
I don't immediately see any cockpit special cases in tests-scan any more (other than triggering external tests), so at first sight this seems fine. Thanks!

**Pull request merged**
