### PR TITLE
WIP: add x of y for pod container display

### PR DESCRIPTION
**Pull request by jeffvance**
When looking at the console.log it appears that there are 2 extraneous objects (since the status is undefined). Maybe my filtering of the kubernetes and kubnertes-ro objects is incorrect?

### CODE REVIEW

**Comment by stefwalter** [comment]
This looks correct to me and appears to work.

**Comment by jeffvance** [comment]
Stef, here's the console.log I see when I refresh the k8 page:
 Failed to load resource: the server responded with a status of 404 (Not Found)
2http://localhost:9090/cockpit/static/fonts/OpenSans-Regular-webfont.woff Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9090/cockpit/static/fonts/OpenSans-Semibold-webfont.woff Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:22 client= KubernetesClient
app.js:38 status= undefined
:9090/cockpit/@localhost/kubernetes/app.js:56 default: status= undefined
:9090/cockpit/@localhost/kubernetes/app.js:38 status= Unknown
:9090/cockpit/@localhost/kubernetes/app.js:38 status= undefined
:9090/cockpit/@localhost/kubernetes/app.js:56 default: status= undefined
:9090/cockpit/@localhost/kubernetes/app.js:22 client= KubernetesClient
:9090/cockpit/@localhost/kubernetes/app.js:38 status= undefined
:9090/cockpit/@localhost/kubernetes/app.js:56 default: status= undefined
:9090/cockpit/@localhost/kubernetes/app.js:38 status= Unknown
:9090/cockpit/@localhost/kubernetes/app.js:38 status= undefined
:9090/cockpit/@localhost/kubernetes/app.js:56 default: status= undefined
:9090/cockpit/@localhost/kubernetes/app.js:22 client= KubernetesClient
:9090/cockpit/@localhost/kubernetes/app.js:22 client= KubernetesClient

The 404s are new after I pulled master last night. My original concern is the status= undefined log.

**Comment by stefwalter** [comment]
> The 404s are new after I pulled master last night. 

Check the journal for related messages. Off the top of my head, you may need to:

```
sudo restorecon -Rv /usr/share/cockpit
```

> My original concern is the status= undefined log.

If I were you, I would add more ```console.log()``` lines to see where undefined value is coming from.

**Comment by jeffvance** [comment]
I cannot get my pods running on my laptop, can someone verify that the "x of y" containers counts are correct?

**Comment by stefwalter** [comment]
Looks good. Will merge in a bit.

**Comment by stefwalter** [comment]
This works well. When I scale up a replication controller I see '1 of 10' and so on until all the containers have started.

**Pull request closed without merging**
