### PR TITLE
WIP amplify/debug testQualifiedUsers

### PR DESCRIPTION
**Pull request by martinpitt**
Trying to debug [this common flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19290-20230907-041527-579e2f5b-rhel-9-3-networking/log.html#37). I don't get it locally, and there's nothing useful in the journal.

### CODE REVIEW

**Comment by martinpitt** [comment]
Interesting - - so there is [no ipaclient-uninstall.log at all](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19294-20230907-143204-7beaf2c2-rhel-9-3-networking/log.html#4). So this smells like the "closed connection" is from realmd when cockpit tries to call `.leave()`.

At first sight this smells like a race condition with an idle timer. But I sit()ed right before clicking the Leave button, and realmd.service still stays alive after several minutes. And neither does the journal show that the service stopped. Also, if I stop realmd.service manually and then continue the test, it fails differently:

> warning: Failed to leave domain: No such interface “org.freedesktop.realmd.Realm” on object at path /org/freedesktop/realmd/Sssd/cockpit_lan_2

As the next step I'll enable D-Bus debugging.

**Comment by mvollmer** [comment]
I'll take over for a while.

First let's disable the D-Bus logging again and start tracing backwards from the dialog error. :)

**Comment by mvollmer** [comment]
Ok, the issue is a race between the Superuser level, RealmdClient, and LeaveDialog.  RealmdClient listens to superuser level changes and will call its own initProxy method twice during every login, once when constructed, and once when `superuser.allowed` changes from `null` to `true` or `false`. If a LeaveDialog is open when initProxy is called, the internal state of the dialog will become invalid. It will call Deconfigure on a DBusProxy that has been closed by initProxy.

The LeaveDialog could do `useEvent(realmd_client, "changed")` but that would just expose another race: There is a time where initProxy has already closed the old proxies but the new proxies have not been installed and have not been announced with a "changed" signal.  That could be fixed, by closing the old proxies only once the new ones are available.

Another fix is to only call initProxy when `superuser.allowed` is not `null`.  This is the usual pattern to avoid initializing things twice during page load that depend on the superuser level. I make a PR for that.

**Comment by mvollmer** [comment]
> . But [that log](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19294-20230908-041441-9a799987-rhel-9-3-networking/log.html) shows no realmd related D-Bus methods _at all_

This is the truth: the `Deconfigure` method call was never made since the channel was closed when the code tried to make that call. This was super helpful information, thanks!

**Comment by mvollmer** [comment]
> `> debug: dbus close(): org.freedesktop.realmd  have channel: true     `

This is `initProxy` in realmd.jsx closing the old DBusClient before opening a new one. The LeaveDialog was already open at that time but didn't update itself with the new proxies.

**Pull request closed without merging**
