### PR TITLE
bots: Move avocado tests to Fedora 27

### PR DESCRIPTION
**Pull request by martinpitt**
Fedora 28 is released now, so Fedora 26 will soon be EOL.

Keep the container tests at Fedora 26 for now, as on Fedora 28 they
cause a weird protocol error that needs more time to debug.

Also add the missing container/bastion to triggered tests of fedora-26
refreshes.

---

This is split out from #9088.

 * [x] image-refresh fedora-27

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-27 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-27-20180514-110909

**Comment by martinpitt** [comment]
kube-apiserver.service fails to start due to `Error: unknown flag: --service_account_key_file`. We use that flag in bots/images/scripts/lib/kubernetes.setup. Apparently that odd spelling got fixed to `--service-account-key-file`, and the old name finally dropped. I checked that even fedora-26 (our oldest image using fedora.setup and thus kubernetes.setup) supports the current spelling, so it's fine to change it.

**Comment by cockpituous** [comment]
image-refresh in progress on verifymachine4.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9163-20180514-125858/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9163-20180514-125858/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-15shg.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9163-20180514-130505/

**Comment by cockpituous** [comment]
image-refresh fedora-27 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-27-20180514-142727

**Pull request merged**
