### PR TITLE
test: Add test for cancelling sosreport

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by martinpitt** [comment]
Bwah, some [npm update](https://semaphoreci.com/cockpit-project/cockpit/branches/pull-request-14355/builds/4) threw a spanner in the works again.

**Comment by martinpitt** [comment]
Rebased after landing the novnc fix in #14356

**Comment by marusak** [comment]
Hmm, this feels racy, isn't it? There is always chance that it finishes before you manage to click the cancel button.
All tests succeeded, but still feels like it is going to backfire one day. Isn't there some way, in which we could make sure it would not finish on time? (like having plugin that would do `sleep 5m` or so)

**Comment by martinpitt** [comment]
@marusak : Note that this test does *not* use the reduced set of modules that we use in testPcp(). The reduced set takes some 10s, while the full set takes more than 1.5 minutes. I. e. IMHO that's already a sufficiently long "busy sleep". If it finishes before it's able to click cancel, then something in the process is seriously broken..

**Pull request merged**
