### PR TITLE
test: firewalld - zones: basic tests for selenium

### PR DESCRIPTION
**Pull request by jscotka**
tests for firewalld zones abilities, to be able to test them via various browsers

### CODE REVIEW

**Comment by martinpitt** [comment]
Thanks! Can you please rebase to latest master to  fix semaphore?

**Comment by martinpitt** [comment]
[Edge](https://209.132.184.41:8493/logs/pull-12285-20190710-131616-280263eb-selenium-edge/log.html) has some errors, but in the existing firewall tests. They should be fixed, but they are not necessary related to this PR.

**Comment by jscotka** [comment]
> Thanks! Can you please rebase to latest master to fix semaphore?

Hi @martinpitt , rebased

**Comment by martinpitt** [comment]
pyflakes failure:

    test/avocado/selenium-firewalld-zones.py:7: 'testlib_avocado.seleniumlib.invisible' imported but unused

Please do 

    ln -s ../../tools/test-static-code .git/hooks/pre-push

to prevent that (also mentioned in HACKING).

**Comment by jscotka** [comment]
> pyflakes failure:
> 
> ```
> test/avocado/selenium-firewalld-zones.py:7: 'testlib_avocado.seleniumlib.invisible' imported but unused
> ```
> 
> Please do
> 
> ```
> ln -s ../../tools/test-static-code .git/hooks/pre-push
> ```
> 
> to prevent that (also mentioned in HACKING).

Sorry @martinpitt  for that. I've reinstalled my Laptop and reinitialized all git repos without  reinitializing all hooks.

Otherwise these edge issues are strange and more less random, it seems that JS executions on edge is different or there are some another or some unimplemented JS functions what causes that.

**Pull request merged**
