### PR TITLE
WIP: Display NVDIMM info

### PR DESCRIPTION
**Pull request by akidua4**
Displays information about NVDIMMS via ndctl with respect to PR: 12140

### CODE REVIEW

**Comment by marusak** [comment]
Is this WIP or ready for review? Do you need some help from us with this? Adding `needswork` label since WIP in title.

**Comment by marusak** [comment]
@akidua4 ping

**Comment by akidua4** [comment]
@marusak Hey Matej. I don't have access to the servers with NVDIMM slots anymore since I was working with Dell as an intern and were using their machines. By the time I pushed the code., it was working fine but I don't have access to servers now. So I request you to take this forward since adding NVDIMM module would be good for the cockpit project. Please let me know if I can help in anyway possible.

**Comment by marusak** [comment]
>  I don't have access to the servers with NVDIMM slots anymore since I was working with Dell as an intern and were using their machines.

Well, I don't have such access neither. But we could fake it (and we will need for tests anyway) but we would need some data dump from someone whose machine has nvdimm.

**Comment by amitinator** [comment]
Akshit pinged me offline and I meant to chime in earlier but just never got around to it. I might be able to setup a machine with NVDIMM. Can someone articulate what needs to be tested here?

**Comment by martinpitt** [comment]
This really needs integration tests, in the form of installing a fake /usr/local/bin/ndctl that prints a representative static output from a machine that actually has that kind of RAM. I'm afraid nobody in the team has access to such a machine, and thus we can't review/test this properly nor adopt this and provide continued support.

As this is very stale, I close this PR now. Of course feel free to re-open if you want to give this another attempt. Thank you!

**Pull request closed without merging**
