### PR TITLE
TEST - image creation on pr

### PR DESCRIPTION
**Pull request by mvollmer**
Don't merge this, of course.

### CODE REVIEW

**Comment by mvollmer** [comment]
bot: Image refresh for fedora-23

**Comment by cockpituous** [comment]
Image creation for fedora-23 in process on host32-rack06.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-23-2ff5984ef58187c7adcff89328788c3cd14a6c5d/

**Comment by cockpituous** [comment]
Image creation failed.

**Comment by mvollmer** [comment]
Works.

**Pull request closed without merging**
