### PR TITLE
test: Use the REST engine in the sink for pull tasks.

### PR DESCRIPTION
**Pull request by mvollmer**
Depends on https://github.com/cockpit-project/cockpituous/pull/19

### CODE REVIEW

**Comment by mvollmer** [comment]
In action here: http://mvo.fedorapeople.org/logs/pull-3608-83c0f022-verify-fedora-23/log.html

**Comment by stefwalter** [comment]
Commented here: https://github.com/cockpit-project/cockpituous/pull/19

**Comment by mvollmer** [comment]
This should also use "onaborted" to update the badge since the sink doesn't do this anymore in the presence of "onaborted".

**Comment by mvollmer** [comment]
> This should also use "onaborted" to update the badge since the sink doesn't do this anymore in the presence of "onaborted".

Done.

**Comment by mvollmer** [comment]
In action here: https://mvo.fedorapeople.org/logs/pull-3649-d2c4e48b-verify-fedora-atomic/log.html

**Comment by mvollmer** [comment]
The `testBasic (check_embed.TestEmbed)` failue on `debian-unstable` is fixed in #3659.

**Comment by stefwalter** [comment]
I see this failure trying to run with this:

```
Traceback (most recent call last):
  File "sink", line 316, in push
    reporter.push(data)
  File "sink", line 164, in push
    result = self.req(token, method, resource, data)
  File "sink", line 142, in req
    response.status, response.reason, output.strip()))
RuntimeError: Couldn't update GitHub: 422 Unprocessable Entity
{"message":"Validation Failed","errors":[{"resource":"Status","code":"custom","field":"state","message":"state is not included in the list"}],"documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}
```

**Comment by mvollmer** [comment]
> I see this failure trying to run with this:

Works for me.
```
https://mvo.fedorapeople.org/logs/pull-3697-06960f63-avocado-fedora-23/log.html
```

Did you use the new sink?

**Comment by mvollmer** [comment]
> Works for me.

No, it doesn't.  I see your error when the tests fail.

**Comment by mvollmer** [comment]
> No, it doesn't. I see your error when the tests fail.

Fixed.

**Pull request closed without merging**
