### PR TITLE
Image refresh for fedora-30

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-30
 * [x] image-refresh fedora-30
 * [x] Adjust podman tests to new Services page: https://github.com/cockpit-project/cockpit-podman/pull/157

### CODE REVIEW

**Comment by Gundersanne** [comment]
both  cockpit-podman and cockpit-composer failed twice in the same way.

**Comment by martinpitt** [comment]
The [testNotRunning](https://209.132.184.41:8493/logs/pull-12445-20190730-105454-aab6d3bf-cockpit-project-cockpit-podman-fedora-30/log) failure is due to redesigning the Services page, and the c-podman test making assumptions about pages other than its own. It's warranted here, but occasionally leads to such issues. So that one is unrelated.

The testRunImage failure looks like another instance of https://github.com/containers/libpod/issues/3526

**Comment by martinpitt** [comment]
Fixed podman in https://github.com/cockpit-project/cockpit-podman/pull/157, setting to blocked.

**Comment by martinpitt** [comment]
[edge test failed](https://209.132.184.41:8493/logs/pull-12445-20190801-063434-aab6d3bf-weldr-cockpit-composer-fedora-30-edge/log) with "couldn't connect to selenium server". Retrying.

**Pull request merged**
