### PR TITLE
storaged: Provide a default name also for new thin volumes

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
Depends on #5097, for convenience.

**Comment by mvollmer** [comment]
Snapshots also should get default names, but that should be more clever than just `lvol15`.

**Comment by stefwalter** [comment]
Needs a rebase.

**Comment by stefwalter** [comment]
There's at least one relevant failure here:

```
Page error: TypeError: undefined is not an object (evaluating 'this.props.client')
http://10.111.116.254:9090/cockpit/$bc3604d3c568d79e9bfe0b3af91a006ee174dd14/storage/storage.js 5825 e
http://10.111.116.254:9090/cockpit/$bc3604d3c568d79e9bfe0b3af91a006ee174dd14/storage/storage.js 6067 onClick
 0 
http://10.111.116.254:9090/cockpit/$bc3604d3c568d79e9bfe0b3af91a006ee174dd14/storage/storage.js 4561 z
```

**Comment by stefwalter** [comment]
This failure on Ubuntu seems related:

```
10+0 records out
10485760 bytes (10 MB, 10 MiB) copied, 0.0188522 s, 556 MB/s
Page error: button:contains(Create partition table) not found
phantomjs://code/phantom-lib.js 17 ph_only
phantomjs://code/phantom-lib.js 26 ph_find
phantomjs://code/phantom-lib.js 97 ph_click
 1 
 1 
Wrote TestStorage-testPartitions-FAIL.png
```

**Comment by mvollmer** [comment]
> Page error: button:contains(Create partition table) not found

I think this was fixed by #5467

**Pull request closed without merging**
