### PR TITLE
retrofit our own lists to match a PatternFly style

### PR DESCRIPTION
**Pull request by garrett**
By adopting PatternFly's look, our own lists should appear more clickable.

### CODE REVIEW

**Comment by garrett** [comment]
TODO:

- [ ] Split out color highlighting (possibly? although it does fix our list hovering — see #10088)
- [ ] Fix animation on tab switch
- [ ] Fix caret animation (optional, but nice to have)

**Comment by garrett** [comment]
@andreasn: As is, right now, I'd like you to take a look and share your thoughts.

It was tricky, as re-compiling and reloading took a very long time, but I think I have everything tamed.

A very good place to test it out is on the storage page, when you look at the filesystems of a device, such as https://localhost:9090/storage#/sda — but anywhere where lists are is a good place to check.

---

The last items that remain:
- do we want to have hover state recoloring for lists be a separate commit and/or PR — or consider that a part of realigning to the PatternFly list look?
- re-test this again in browsers other than Firefox (Chrome, Safari, Edge).

**Comment by garrett** [comment]
I've checked these URLs:
- https://localhost:9090/storage#/sda
- https://localhost:9090/playground/jquery-patterns
- https://localhost:9090/playground/react-patterns
- https://localhost:9090/network/firewall
- https://localhost:9090/selinux/setroubleshoot

... in:
- Firefox 62.0.3
- Chromium 69.0.3497.100
- Epiphany 3.28.5
- Safari 11.1.2 (apparently last version for OS X El Capitan / 10.11.6)
- Edge 42.17134.1.0

And it works fine in testing everywhere, thankfully.

**Comment by garrett** [comment]
_One small thing_: Updating the highlight color made the hover contrast for logs not-so-great. That will need to be changed. Everything else seems fine.

I think it's from `pkg/lib/journal.css:77` @ https://github.com/cockpit-project/cockpit/pull/10116/commits/6f2bc7210f1b2511a0dbe06ba7ac9662f7576179#diff-9edccf8c1fcbab7ceea61630c24417acR77

**Comment by andreasn** [comment]
Comparing to [Patternfly](https://www.patternfly.org/pattern-library/content-views/list-view/#code) and [Patternfly React](http://patternfly-react.surge.sh/patternfly-3/index.html?knob-bordered=true&knob-Bordered=true&knob-Selection%20Type=none&knob-Wrap%20Style=wrap&knob-textCollapsed=Show%20Advanced%20Options&knob-Leeway=2&knob-textExpanded=Hide%20Advanced%20Options&knob-Max%20Shown=5&selectedKind=patternfly-react%2FContent%20Views%2FList%20View&selectedStory=List%20of%20expandable%20items&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

 * The animation when expanding feels very slow.
 * The expander arrow doesn't turn blue on hover, but only when expanded in Patternfly (but only in React)
 * It seems the arrows are slightly bigger in Cockpit than in Patternfly.
 * The space above the tabs in Storage is bigger and the action buttons are no longer positioned in the middle 
screenshot from 2018-10-16 12-52-17

Apart from that, looks good to me!
I really enjoy how the content animates in!

**Comment by andreasn** [comment]
> Regardless, I'll make sure the action buttons are properly aligned.

Thanks!

**Comment by garrett** [comment]
In reviewing the lists yet again to get the icon size right, I realized the border is for the checkbox, not the expander icon. As a result, an upcoming patch will drop the separator line.

**Comment by martinpitt** [comment]
@garrett:
- Does this replace #10088 ? I. e. should that be closed? (At first sight it looks like it)
- Should some of the commits get squashed, or are they really all independent? If all of them should be squashed into one, I can land it. Otherwise, please rebase and add a `Closes #10116` to the commit log of the topmost one.

**Comment by garrett** [comment]
@martinpitt: 

1. Yes, it probably replaces that.

2. Yep, I should squash down some commits. I left them this way for review purposes. I'll finalize and rebase/squash today. (I think there should probably be more than one commit, but not many more. 2 or 3 at most... it will most likely be 2 commits, and will just deprecate #10088.)

**Comment by andreasn** [comment]
> I guess it should probably go on the first non-checkbox, non-expander row, however, instead of the expander.

Well spotted, I thought it was only for the checkbox as well.
Makes sense to put it on the row indeed.

**Comment by garrett** [comment]
@andreasn: Please check system logs hovering versus logs in the various sub-components.

1. I have a direct descendant selector between the log panel and logline which selects only system logs for hovering. They're the only clickable ones (afaict) — but it feels a little hackish to select them this way. I'd rather select on actual clickability... but we might need to modify the code for that.
2. The style of the clickable log entries is now a better blue for the background and it now also makes the text look like a link (blue + underline) when hovering. Is that too much or do you like it?

(BTW: I noticed that the default link color is _not_ a PatternFly blue from the palette, even if it is a bit close. Perhaps we should make a separate PR to align its color... unless PF itself doesn't use the color for links. It's worth checking.)

**Comment by andreasn** [comment]
It seems the SELinux separators are a bit off.
screenshot from 2018-10-22 15-27-08

In Software Updates the arrows seems slightly off.
screenshot from 2018-10-22 15-29-40

Apart from that, all looks good!

**Comment by garrett** [comment]
@andreasn: OK, I've adjusted the lists to address the issues you pointed out and also fixed a few problems I spotted in the PackageKit update list. (Some issues were related to the changes I made here, others are list-related in general and affect PackageKit in master.)

Please re-check on your end; I'll check it out in all the various browsers again.

**Comment by garrett** [comment]
I've tested all the various pages in:

- Firefox
- Chrome
- Epiphany (so Safari probably works too)

I am currently setting up my Windows testing VM again to see if Edge throws us a curveball. (It was fine before, but there have been a bunch of changes since the last round of browser testing on this PR.)

**Comment by martinpitt** [comment]
This breaks [testPrivateKeys](https://fedorapeople.org/groups/cockpit/logs/pull-10116-20181024-061212-d27c2012-verify-rhel-x/log.html#3) everywhere. The ssh key list is not visible (see [screenshot](https://fedorapeople.org/groups/cockpit/logs/pull-10116-20181024-061212-d27c2012-verify-rhel-x/TestKeys-testPrivateKeys-rhel-x-127.0.0.2-2301-FAIL.png))

**Comment by garrett** [comment]
@martinpitt Oh... I haven't seen that dialog before... that has issues. What is it supposed to look like?

(I don't even know how the changes would prevent a list from showing. Weird.)

**Comment by garrett** [comment]
By "that has issues". I mean outside of lists. Is that a huge checkbox to the side? Is it a random, disconnected **×** button? :man_shrugging: 

I found the dialog (under authentication on the user dropdown in the top-right)... and adding keys is problematic as the dialog is set to `overflow: auto` and the dropdown drops down into the overflowed space, so the interaction is quite bad.

**Comment by garrett** [comment]
I'm looking at the changed CSS and the UI in-browser and don't see how the patch can affect it.

This calls for heavier debugging with a morning coffee. :coffee:

Thanks for pointing out the issue — I don't think we would've found it otherwise. It's not an obvious use of `listing-ct` and it's hidden away quite well.

**Comment by garrett** [comment]
I think I've fixed the auth dialog issue in b476b3e by special-casing it. It's a **HACK**, as something like this does _not_ belong in widget CSS — but undoing it in the local CSS might not be trivial, as the code probably makes wrong assumptions. Ideally, we'd fix it in the local code.

**Comment by garrett** [comment]
> I found the dialog (under authentication on the user dropdown in the top-right)... and adding keys is problematic as the dialog is set to overflow: auto and the dropdown drops down into the overflowed space, so the interaction is quite bad.

This is a problem on master as well. I'll open an issue.

**Comment by martinpitt** [comment]
I tested this, and it seems to work fine. I trust @garrett and @andreasn to have worked out the finer details of design, I'm not good at that :-) Before/after comparison of software updates, also for release notes:

Current master:
swupdates-before

This PR:
swupdates-after

I also verified that the SSH keys in the Authorization dialog continue to work fine. The spacing is marginally (haha) different, but otherwise they look the same:

master:
keys-before

This PR:
keys-after

**Comment by garrett** [comment]
@martinpitt: Great!

---

Unrelated to this PR, but related to some of the above comments and screenshots:

I do have to say that the way the widget is used in the auth dialog needs a re-work. (And the design overall needs at least a small re-think.) If there's a list there that is expandable, it should have expanders. It also should ideally use the React widget instead of custom HTML. (I'm assuming it uses custom HTML just because of how weird it is overall.)

...And the contents of the dialog needs reworking for other reasons, such as dropdown scroll bug.

**Pull request merged**
