### PR TITLE
selinux: Migrate to webpack

### PR DESCRIPTION
**Pull request by stefwalter**

### CODE REVIEW

**Comment by stefwalter** [comment]
Finished this off (still has other pull requests blocking it) ... so that I can take a look at babel + es6 + webpack.

**Comment by stefwalter** [comment]
Blocked on #4674 and #4638

**Comment by dperpeet** [comment]
needs rebase

**Comment by stefwalter** [comment]
Rebased.

**Comment by larsu** [comment]
Awesome. Looks good. I'll merge it once the checks have passed.

**Comment by stefwalter** [comment]
Blocked on #4729

**Comment by stefwalter** [comment]
Rebased

**Comment by stefwalter** [comment]
Making sure fedora-24 passes before this is ready to merge.

**Comment by stefwalter** [comment]
This fail is related to #4732 

```
    b.wait_text("#service-list tr[data-name='mock'] td.containers", "1")
```

**Pull request closed without merging**
