### PR TITLE
test: Wait default time for machine to reboot 

### PR DESCRIPTION
**Pull request by marusak**
This is just lazy way how to get logs. When I get logs, then I'll push here proper commit.

### CODE REVIEW

**Comment by marusak** [comment]
Huh, so the test succeeded - [log](https://209.132.184.41:8493/logs/pull-13517-20200207-170505-934eabe6-fedora-31-selenium-firefox-bots-501/log.html)
Is it just timing thing and with my sleep it has enough time?

**Comment by marusak** [comment]
Without the sleep it [failed](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-13517-20200207-175050-b3de12f2-fedora-31-selenium-firefox-bots-501/log.html) again. I however don't understand why we want to have less retries there, so I just removed it and we can go with the default setting. That should work.

**Comment by marusak** [comment]
edge is freaking out. This is not related to this PR, but it is related to the move to F31.
I'll try to take a look and if possible, push the change into this PR as well.

**Comment by marusak** [comment]
So I have theory that once we hit skipped test, all subsequent tests freak out. I removed all skipped tests and it seems to [help](https://209.132.184.41:8493/logs/pull-13517-20200210-094343-a97d5e02-fedora-31-selenium-edge-bots-501/log.html) a lot. I'll retry to see if these 3 are persistent or it was just bad luck. (Or possibly one failed and all subsequent hit the same fate).

**Comment by marusak** [comment]
Ok, so it was not it.
But it seems that there is pattern - from some random time all tests fail.
It is only happening on edge. It was introduced with F31.
@henrywang do you have some idea?

**Comment by marusak** [comment]
So the issue was not dhcp timing out related as the issue persists: https://209.132.184.41:8493/logs/pull-13517-20200211-080202-d100d3d2-fedora-31-selenium-edge-bots-501/log.html
It takes 30 minutes and then edge VM seems to not be accessible.

**Comment by martinpitt** [comment]
@marusak: Nice, now that [starts to look promising](https://209.132.184.41:8493/logs/pull-13517-20200212-052323-d100d3d2-fedora-31-selenium-edge-bots-501/log.html)! I restart it once to see if the login-special.py failure is a flake or needs fixing on f31, but it seems disabling the auto-suspend did the trick. :tada:

**Pull request merged**
