### PR TITLE
networkmanager: add Modem, OpenVPN and WiFi interface handlers

### PR DESCRIPTION
**Pull request by artur-rs**
Patch changes:
  * General:
    - moved "Add ..." buttons to dropdown list "Add new"
    - improved "Interfaces" summary table
    - unified general settings dialog UI
    - added new general settings (conn ID, aut-connect priority, auto-connect vpn)
  * added modem settings dialog
  * added OpenVPN settings dialog
  * added Wifi settings dialog:
    - enabled security options ("none", "wpa-psk", "wpa-eap"(TLS and PEAP))

Here is the doc with screenshots: [changes.pdf](https://cloud.3mdeb.com/index.php/s/554bytDo5wTszWZ)

### CODE REVIEW

**Comment by andreasn** [comment]
I would prefer if this was broken out into separate PRs for each interface.
It's becomes a lot of UI to review, and will mean that any requested change on one of them, will block the others.

Also, scope-wise I feel VPN is natural for server class hardware, but wifi and modems I've only seen on laptop class hardware, so I'm not sure it's as good of a fit for a server UI such as Cockpit.

**Comment by jnettlet** [comment]
> Thanks for the PR!
> 
> I would prefer if this was broken out into separate PRs for each interface.
> It's becomes a lot of UI to review, and will mean that any requested change on one of them, will block the others.
> 
> Also, scope-wise I feel VPN is natural for server class hardware, but wifi and modems I've only seen on laptop class hardware, so I'm not sure it's as good of a fit for a server UI such as Cockpit.

Well edge compute is going to be changing the definition of "Server" hardware quite quickly.  As are other devices such as IoT gateways other 5G based connectivity solutions.  I understand if the mainline project wants to limit the scope of their work, however we are hoping that this work will open the concept of what cockpit can be to a wider scope.

**Comment by artur-rs** [comment]
@martinpitt @mvollmer @andreasn @jnettlet separated patches:
* [#12526 - General settings](https://github.com/cockpit-project/cockpit/pull/12526) (should be merged first, next patches include these changes that are necessary for each interface below)
* [#12527 - Modem interface](https://github.com/cockpit-project/cockpit/pull/12527) (review only 2nd commit, first is from General settings)
* [#12528 - WiFi interface](https://github.com/cockpit-project/cockpit/pull/12528) (review only 2nd commit, first is from General settings)
* [#12529 - OpenVPN interface](https://github.com/cockpit-project/cockpit/pull/12529) (review only 2nd commit, first is from General settings)

**Comment by martinpitt** [comment]
Thanks for splitting them out! Closing in favor of the separated ones.

**Pull request closed without merging**
