### PR TITLE
test: Add Qemu disks sequentially in TestStorageMdRaid

### LINKED ISSUE #19765: Nightly tests did not succeed on fedora-39/daily: TestStorageMdRaid.testRaid pixel failure (DISK4 instead of DISK3)
Tests failed on d3ec1fd8ede7bcad0b8c72395950ed1f1679c136, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231220-011736-d3ec1fd8-fedora-39-daily/log.html)

### PR DESCRIPTION
**Pull request by mvollmer**
So that a given device in /dev always has the same serial.

Fixes #19765

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Clever!

**Comment by mvollmer** [comment]
A "proper" fix could be to wait in `add_disk` until the disk has actually turned up. We should be able to find in by its serial. But I was afraid that this might disturb other tests...

**Comment by martinpitt** [comment]
Most of the failures here are completely unrelated. [This one](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20093-20240226-080924-ee4bfe12-rhel-9-4-storage/log.html#99) isn't a regression from this PR, but still interesting, see [screenshot](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20093-20240226-080924-ee4bfe12-rhel-9-4-storage/TestStorageMdRaid-testRaid-rhel-9-4-127.0.0.2-2201-FAIL.png):

> Error removing '/dev/md127' from RAID array '/dev/sda': Process reported exit code 1: mdadm: set /dev/sda faulty in /dev/md127 mdadm: hot remove failed for /dev/sda: Device or resource busy

**Comment by martinpitt** [comment]
That same error also happened in #20095 Good enough, landed.

**Pull request merged**
