### PR TITLE
Various small cleanups for TLS redirection

### PR DESCRIPTION
**Pull request by martinpitt**
Split out from PR #12141 for easier review and landing.

### CODE REVIEW

**Comment by mvollmer** [comment]
I think the commit messages need to be clearer.

```
Most tests don't disable redirection explicitly, and don't expect it to
happen even though it's enabled by default. It does not happen because
most tests run from a localhost IP, but this is about to change.
```

What exactly is about to change?  Tests running from localhost?  Redirection not happening when running from localhost?  Why is that going to change?  I thought we want to keep existing behavior?

```
Our test case is not prepared, nor meant to handle TLS redirection. It
is currently implicitly off due to a bug in CockpitWebServer, but let's
not count on that.
```

What is that bug?

**Comment by martinpitt** [comment]
> What exactly is about to change?

Indeed this "about to change" was a leftover from a previous attempt.  Before I force-push several times, this is how I changed them now:
```
    common: Explicitly test redirection in test-webserver
    
    Most tests don't disable redirection explicitly, and don't expect it to
    happen even though it's enabled by default. Redirection just does not
    happen because most tests run from a localhost IP, but this isn't
    obvious when looking at the test.
    
    Introduce a TestFixture flag for it and explicitly set redirection for
    each test case.
```

```
    bridge: Disable TLS redirection in test-httpstream
    
    Our test case is not prepared, nor meant to handle TLS redirection. It
    is currently implicitly off due to a too strict assumption in
    CockpitWebServer: ws currently disables redirection if certificates are
    disabled, which is wrong when running behind procies). Let's not count
    on that behaviour.
```

@mvollmer, is that clearer?

**Comment by mvollmer** [comment]
> @mvollmer, is that clearer?

Excellent, thanks!

**Comment by martinpitt** [comment]
Tests were completely green before the force-push to update the commit logs, so good enough.

**Pull request merged**
