### PR TITLE
bots: debian-stable is now 10 (buster)

### PR DESCRIPTION
**Pull request by martinpitt**
Debian 10 (buster) got released yesterday, so our debian-stable image
now moves from 9 (stretch) to 10 (buster). It is essentially identical
to debian-testing right now, so synchronize the build script, naughties,
and test special cases.

 * [x] image-refresh debian-stable
 * [x] add naughty for libvirt apparmor complaint: PR #12251

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-v4h89.
Log: https://logs-https-cockpit.apps.ci.centos.org/logs/image-refresh-12248-20190707-204949/

**Comment by cockpituous** [comment]
image-refresh debian-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-debian-stable-20190707-210808

**Comment by martinpitt** [comment]
@Gundersanne: The firewall tests fail because there are apparently no active zones, even after the `firewall-cmd --permanent --zone=public --add-interface=eth1` dance.

The debs on this image and debian-testing are now exactly the same. I don't immediately know where the difference would be.

Can you please have a quick look and check what's wrong there? Thanks!

**Comment by martinpitt** [comment]
I looked at the [check-multi-machine TestMultiMachineAdd.testBasic](https://209.132.184.41:8493/logs/pull-12248-20190707-213838-f4166036-verify-debian-stable/log.html#203) failure, and it's similarly firewalld related. If I add

    self.machine3.execute("systemctl disable --now firewalld; iptables -F")

to the setup, machine1 can talk to machine 3 on port 2222 again. Reloading firewalld does something funky there.

**Comment by martinpitt** [comment]
Still [some failures](https://209.132.184.41:8493/logs/pull-12248-20190708-083333-2217ce94-verify-debian-stable/log.html), retrying for comparision.

**Comment by martinpitt** [comment]
OMG green! There is one [flake on debian-testing](https://209.132.184.41:8493/logs/pull-12248-20190708-094747-2217ce94-verify-debian-testing/log.html#224). Retrying for protocol's sake, but this PR doesn't really touch that.

**Comment by martinpitt** [comment]
Argh, it wasn't a flake, it was a stupid typo of mine. Commas -- so important!

**Pull request merged**
