### PR TITLE
Update to Patternfly 3.2.0

### PR DESCRIPTION
**Pull request by stefwalter**
Patternfly stopped shipping dependencies, and instead loads them via Bower. Which is more inline with how we do it anyway, so that's a nice change but is the cause of many of the lines of changes here.

### CODE REVIEW

**Comment by stefwalter** [comment]
@andreasn @petervo So even though some of the names of the styles for the new sidebar navigation were in the old version of patternfly 2.8.0 ... they didn't actually do what we expected. So here's updating to 3.2.0

**Comment by petervo** [comment]
This looks good to me, @andreasn do you want to take look before I merge.

**Comment by andreasn** [comment]
Yeah, I'll take a look.

**Comment by andreasn** [comment]
I don't see any major problems. There are some alignment issues in the Network dialog, but I think those were there since before.

**Pull request closed without merging**
