### PR TITLE
bots: Add node to rhel-7-6 image

### PR DESCRIPTION
**Pull request by martinpitt**
This is being used by current welder-web/composer tests. Downloading the
GPG keys is rather brittle and downloading/installing node takes a
significant amount of time. Let's  move that from every test run into
our image.

 - [x] image-refresh rhel-7-6
 - [x] fix welder-web to do proper cross-project bots/ testing: https://github.com/weldr/welder-web/pull/383
 - [x] fix welder-web to get along with this new image: https://github.com/weldr/welder-web/pull/382

### CODE REVIEW

**Comment by martinpitt** [comment]
CC @henrywang

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-7d7d6.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10319-20181016-153838/

**Comment by cockpituous** [comment]
image-refresh rhel-7-6 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-6-20181016-161414

**Comment by martinpitt** [comment]
The welder-web tests ought to have failed, as long as https://github.com/weldr/welder-web/pull/382 hasn't landed yet. But they succeed because welder-web always checks out the master version of bots/ by itself. I fixed this in https://github.com/weldr/welder-web/pull/383 , let's land this first, then see this fail, land #382, see this succeed again (and land), and finally drop the node download stuff from welder-web entirely.

**Comment by martinpitt** [comment]
The "cockpit/continuous-atomic"  test task is bogus, so please ignore that noise.

**Pull request merged**
