### PR TITLE
machines: Fix padding for actions in VM list

### PR DESCRIPTION
**Pull request by skobyda**
This was blocking me on https://github.com/cockpit-project/cockpit/pull/14283.

### Before:
Screenshot from 2020-07-31 14-43-38

### After:
Screenshot from 2020-07-31 14-45-55

### CODE REVIEW

**Comment by skobyda** [comment]
Also, the width calculation for columns in VM listing seems to be broken in general, but I would like to get this in so I could unblock #14283 and work on other issues later.

**Comment by KKoukiou** [comment]
@skobyda can you try on mobile as well?

**Comment by skobyda** [comment]
Screenshot from 2020-08-03 11-06-32
Screenshot from 2020-08-03 11-06-23

**Comment by KKoukiou** [comment]
> It doesn't seem to be the best on mobile:
> 
> Screenshot from 2020-08-03 11-06-32
> Screenshot from 2020-08-03 11-06-23

Let's leave it to @garrett to fix it better :)

**Comment by garrett** [comment]
The after in this PR still has lots of problems, including:

- Misalignment of action buttons
- Too much padding on the side of the actions
- Wrong spacing in the columns (in general)
- Lack of spacing around action buttons in the embedded lists
- Various mobile issues too

**Comment by garrett** [comment]
Was everything fine when the PF4 update branch landed or is this a result of that? Or did it show up later?

**Comment by garrett** [comment]
Even without 41cdbad0d, the other issues remain:

Screenshot_2020-08-04 Virtual Machines - garrett Rain

Screen Shot 2020-08-04 at 16 12 56

**Comment by garrett** [comment]
I've pushed some commits that stack on top of @skobyda's commit should help solve everything except being too wide in desktop mode when the page gets a bit narrow. I think that's out of scope for this PR and will probably be solved when we move VMs to sub-pages anyway.

**Comment by KKoukiou** [comment]
@garrett i just tested it - it looks good thanks.
Can you please add also a fix for the VM connection column which breaks on each letter on small screens? It's rather ugly.

**Comment by KKoukiou** [comment]
> @garrett i just tested it - it looks good thanks.
> Can you please add also a fix for the VM connection column which breaks on each letter on small screens? It's rather ugly.

Feel free to create another PR for this actually.

**Comment by garrett** [comment]
> a fix for the VM connection column which breaks on each letter on small screens?

This... isn't a problem anymore?

I saw something like that before, but I fixed it. Unless it's something else. Please provide a screenshot; everything looks correct to me here. But I'll happily fix it if it's still an issue.

**Comment by KKoukiou** [comment]
> > a fix for the VM connection column which breaks on each letter on small screens?
> 
> This... isn't a problem anymore?
> 
> I saw something like that before, but I fixed it. Unless it's something else. Please provide a screenshot; everything looks correct to me here. But I'll happily fix it if it's still an issue.

Screen Shot 2020-08-05 at 10 20 30

**Comment by garrett** [comment]
Right. I fixed that??? Please make sure you branch is up to date?

**Comment by garrett** [comment]
OH, it's a different part. I see. And with iPhone SE sizes. Sorry. I'll fix.

**Comment by garrett** [comment]
I have a fix nearly done, but I'll move it to a new PR and share it after lunch.

**Pull request merged**
