### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by andhe**
A couple of minor fixes in the build system for cockpit.

### CODE REVIEW

**Comment by stefwalter** [comment]
As noted in #1991 we're still depending on systemd 208 and later. So the second patch here can't be merged (at least for the forseeable future).

**Comment by andhe** [comment]
Hi @stefwalter and thanks for looking at this so quickly. I've pushed a new version of the second patch which incorporates fallback to the old names to support building on older systemd releases still. Feel free to ignore the libsystemd patch. The first one should hopefully still be useful to you none the less.

(Unfortunately can't test this right now. Hopefully Travis CI testing should be good enough for this.)

**Comment by stefwalter** [comment]
@andhe That looks like a good way to do it. Lets see if it passes the CI tests here, and then I'll double check a systemd 208 system.

**Comment by andhe** [comment]
fwiw, the Travis CI seems to be running on Ubuntu Trusty which has systemd 204. The old patch failed and this one now apparently succeeds, so should be good on systemd <= 208. Additional checking on systemd >= 209 would be useful.

**Comment by stefwalter** [comment]
@dperpeet @mvollmer How do I run the full CI suite against this pull request? Is there something I type here or a label I set?

**Comment by stefwalter** [comment]
Thanks. Merged into git master.

**Pull request closed without merging**
