### PR TITLE
kubernetes: Tests for and fix behavior of deploy dialog

### PR DESCRIPTION
**Pull request by stefwalter**
* Add integration tests.
 * Use the new dialog behavior patterns
 * Build our own better bootstrap-combobox that you can actually type in.
 * Close the KubernetesClient when we're done
 * Remove about half the code.

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #2266 and #2265

**Comment by stefwalter** [comment]
@sub-mod Further work on the deploy dialog should be branched from here ... at least until this pull request is merged.

**Comment by stefwalter** [comment]
Rebased.

**Comment by sub-mod** [comment]
@stefwalter I see a difference in the dialog and the design.

**Comment by sub-mod** [comment]
screenshot from 2015-05-12 21-08-49
scenario
1)deploy an app with a namespace
2)click on deploy button again
3)the fields should be reset

The above scenario is not working.
The old values still exists and even without selecting any fields if i click on deploy button the old app is deployed again(which fails).

**Comment by stefwalter** [comment]
> I see a difference in the dialog and the design. The dialog window is supposed to close and the spinner is to be shown in the service table column.

The spinner is shown in the dialog while the initial objects in the manifest are being created in kubernetes. This is obviously more visible when you have a slow connection to kubernetes.

The spinner in the services column is for when the containers are starting up.

> 1)deploy an app with a namespace 2)click on deploy button again 3)the fields should be reset. The above scenario is not working.

Thanks. Good Catch. Will fix this.

**Comment by stefwalter** [comment]
Fixed to clear namespace when dialog opens.

**Comment by stefwalter** [comment]
Rebased.

**Pull request closed without merging**
