### PR TITLE
package.json: Update xterm package dependency

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
npm-update in progress on 1-cockpit-11.
Log: https://209.132.184.41:8493/logs/npm-update-12143-20190625-032222/

**Comment by cockpituous** [comment]
npm-update in progress on 3-cockpit-8.
Log: https://209.132.184.41:8493/logs/npm-update-12143-20190625-030909/

**Comment by cockpituous** [comment]
npm-update in progress on 3-ci-srv-03.
Log: https://209.132.184.41:8493/logs/npm-update-12143-20190625-032424/

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "xterm": "3.14.2"
pkg/docker/docker.js:import { Terminal } from "xterm";
pkg/lib/cockpit-components-terminal.jsx:import { Terminal as Term } from "xterm";
pkg/lib/console.css:@import "~xterm/lib/xterm.css";
pkg/lib/context-menu.css:    /* xterm accessibility tree has z-index 100 and we need to be in front of it
pkg/machines/machines.less:@import "~xterm/lib/xterm.css";
pkg/systemd/terminal.jsx:                    "TERM=xterm-256color",
test/avocado/selenium-base.py:        terminal = self.wait_xpath("//*[contains(@class, 'terminal xterm')]")
test/avocado/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer')
test/avocado/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer', cond=invisible)
test/avocado/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer')
test/avocado/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer', cond=invisible)
test/avocado/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer')
test/verify/check-active-pages:                return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-pages:            return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-realms:                return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-terminal:                return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-terminal:            b.wait_attr(".xterm-viewport", "style", style)
test/verify/check-terminal:        b.wait_attr(".xterm-viewport", "style", white_style)
test/verify/machineslib.py:        b.wait_present("div.terminal canvas.xterm-text-layer") # if connected the xterm canvas is rendered
test/verify/machineslib.py:        b.wait_present("div.terminal canvas.xterm-text-layer")
test/verify/machineslib.py:        b.wait_not_present("div.terminal canvas.xterm-text-layer")
test/verify/machineslib.py:        b.wait_present("div.terminal canvas.xterm-text-layer")
```

**Comment by cockpituous** [comment]
npm-update in progress on 4-ci-srv-05.
Log: https://209.132.184.41:8493/logs/npm-update-12143-20190625-032121/

**Comment by cockpituous** [comment]
npm-update in progress on 1-cockpit-8.
Log: https://209.132.184.41:8493/logs/npm-update-12143-20190625-031010/

**Comment by cockpituous** [comment]
npm-update @patternfly/react-console done: https://github.com/cockpituous/cockpit/commits/npm-update-@patternfly/react-console-20190625-032323

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "@patternfly/react-console": "1.11.2",
pkg/machines/components/serialConsole.jsx:import { SerialConsole } from '@patternfly/react-console';
pkg/machines/components/vnc.jsx:import { VncConsole } from '@patternfly/react-console';
pkg/machines/machines.less:// For patternfly-react and @patternfly/react-console
pkg/machines/machines.less:@import "~@patternfly/react-console/dist/less/console.less";
```

**Comment by cockpituous** [comment]
npm-update patternfly-react done: https://github.com/cockpituous/cockpit/commits/npm-update-patternfly-react-20190625-032626

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "patternfly-react": "2.36.2",
pkg/kdump/kdump-view.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/lib/cockpit-components-inline-notification.jsx:import { Alert } from 'patternfly-react';
pkg/machines/app.jsx:import { ToastNotificationList, ToastNotification } from 'patternfly-react';
pkg/machines/components/aggregateStatusCards.jsx:} from 'patternfly-react';
pkg/machines/components/create-vm-dialog/createVmDialog.jsx:import { Button, FormGroup, HelpBlock, Modal } from 'patternfly-react';
pkg/machines/components/deleteDialog.jsx:import { Modal, Button } from 'patternfly-react';
pkg/machines/components/diskAdd.jsx:import { Button, Modal } from 'patternfly-react';
pkg/machines/components/diskRemove.jsx:import { Tooltip, OverlayTrigger } from 'patternfly-react';
pkg/machines/components/infoRecord.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/machines/components/networks/network.jsx:import { Button } from 'patternfly-react';
pkg/machines/components/networks/networkList.jsx:import { Breadcrumb } from 'patternfly-react';
pkg/machines/components/nicEdit.jsx:} from 'patternfly-react';
pkg/machines/components/storagePools/createStoragePoolDialog.jsx:import { Button, FormGroup, HelpBlock, Modal } from 'patternfly-react';
pkg/machines/components/storagePools/storagePool.jsx:import { Button, Tooltip, OverlayTrigger, UtilizationBar } from 'patternfly-react';
pkg/machines/components/storagePools/storagePoolDelete.jsx:import { Button, Modal } from 'patternfly-react';
pkg/machines/components/storagePools/storagePoolList.jsx:import { Breadcrumb } from 'patternfly-react';
pkg/machines/components/storagePools/storageVolumeDelete.jsx:} from 'patternfly-react';
pkg/machines/components/vcpuModal.jsx:import { Button, Modal } from 'patternfly-react';
pkg/machines/components/vm/bootOrderModal.jsx:} from 'patternfly-react';
pkg/machines/components/vm/memoryModal.jsx:} from 'patternfly-react';
pkg/machines/components/warningInactive.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/machines/machines.less:// For patternfly-react and @patternfly/react-console
pkg/machines/machines.less:@import "~patternfly-react/dist/less/patternfly-react.less";
pkg/networkmanager/firewall.jsx:} from "patternfly-react";
pkg/packagekit/history.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/packagekit/updates.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/storaged/dialog.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/storaged/storage-controls.jsx:import { OverlayTrigger, Tooltip } from "patternfly-react";
pkg/systemd/hwinfo.jsx:import { Alert, Button, ListView, Modal, OverlayTrigger, Tooltip } from 'patternfly-react';
```

**Comment by martinpitt** [comment]
I built this locally, and like the first thing it does is to crash with

    TypeError: this.state.terminal._core.renderer is undefined 

The [CI tests](https://209.132.184.41:8493/logs/pull-12143-20190625-060000-bd7aea48-verify-fedora-30/log.html#230) also fail, but with yet another error.

@marusak, could you please have a look? This should at least result in an upstream bug report, or maybe the API changed and needs adjustment in our code?

**Comment by marusak** [comment]
New version of xterm.js changed it a bit. It is a bit annoying, because when another new version is released, we need to adjust this once more as in xterm.js master it is already renamed again.

I also squashed the refresh and the fix into one commit, as every commit should be fully working.

I also pushed some bots fix, which my push hook caught.

**Comment by martinpitt** [comment]
Reopening. This shouldn't have landed yet, as it causes a regression with "disconnect". After the manual test I somehow completely forgot to check the automatic tests, sorry!

**Comment by martinpitt** [comment]
Err, it seems I can't actually reopen this.. @marusak, can you please file a new PR instead? I revert this in PR #12159.

**Pull request merged**
