### PR TITLE
metrics: use gradient for marking graph area when load/saturation is over 80% limit

### PR DESCRIPTION
**Pull request by KKoukiou**
n the gradient we don't use 80% but 70% since it takes 10% to actually transcend to the new color.

### CODE REVIEW

**Comment by KKoukiou** [comment]
The new looks will be something like:
Screenshot from 2023-03-22 11-08-40

**Comment by garrett** [comment]
Excellent! Thanks for splitting this out.

I'll work on the colors in general (they should probably be aligned to PF chart colors and ideally also be more colorblind friendly — I think these are still based on some colors I chose in the mockup and never got back to, as they look pretty nice otherwise), and also specifically the extreme amount in this PR.

**Comment by garrett** [comment]
Tons of fixes... I still haven't actually addressed what this PR is about though. :wink: But it's all necessary to actually get there (tomorrow). And now the metrics (in this PR) works cross-browser again. (It doesn't in main. :cry:)

**Comment by garrett** [comment]
How's this?

It's now using PF Chart colors, and I think I optimized it for color blindness. (I uses a color blind emulator for Protanopia, Deuteranopia, and Tritanopia — and also in normal colors.)

image

Oh, and this is WebKit. I got both it (which wasn't working at all for the graphs) and Chrome (which wasn't displaying them correctly) working in this PR also.

What's debatable is the color selection and which parts are which colors. We could try different palettes (which would need more work checking) or remap these.

**Comment by marusak** [comment]
@KKoukiou want to take a look?

**Review by garrett — APPROVED** [review]
Looks good, although it's kind of weird to be approving my own work. But I'm approving on behalf of @KKoukiou approving my changes. :wink:

**Pull request merged**
