### PR TITLE
bots: Bump VM shutdown timeout to five minutes in image-create

### LINKED ISSUE #7982: Image refresh for rhel-7-5
Image refresh for rhel-7-5
 * [ ] FAIL: image-refresh rhel-7-5

### PR DESCRIPTION
**Pull request by martinpitt**
One minute does not seem to be enough for current rhel-7-5 on the bots,
so increase the timeout to five minutes.

Fixes #7982 

 * [x] image-refresh rhel-7-5

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-js71f.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8041-20171107-153838/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-6p3lt.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8041-20171107-153838/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-t6hwx.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8041-20171107-153838/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8041-20171107-153838/

**Comment by martinpitt** [comment]
That didn't help, still no error message at all. I pushed a commit that adds some debug  output.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-rvjlj.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8041-20171107-161515/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-3991c.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8041-20171107-161515/

**Comment by cockpituous** [comment]
image-refresh rhel-7-5 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-5-20171107-164242

**Comment by martinpitt** [comment]
So that extra debugging doesn't actually show anything (like the output of `virsh event`), but the image build did succeed this time. So re-trying with just a longer timeout.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-wxb6s.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8041-20171107-174343/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-5kx5m.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8041-20171107-174444/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-wx97l.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8041-20171107-174444/

**Comment by cockpituous** [comment]
image-refresh rhel-7-5 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-5-20171107-181717

**Comment by martinpitt** [comment]
OK, this seems to work fine.

**Pull request merged**
