### PR TITLE
Textual branding

### PR DESCRIPTION
**Pull request by mvollmer**
Instructions for testing:

- Compile with ./configure --with-branding=auto
- Edit /etc/os-release.  Change ID and VARIANT_ID.  After each change, restart cockpit and then reload the login page.

### CODE REVIEW

**Comment by andreasn** [comment]
* The bar at the top seems to get some extra padding, so that needs to be set to 2px.
 * text-transform: uppercase; also needs to be set
 * hover needs to remain white, and not turn gray.

**Comment by stefwalter** [comment]
We don't need to parse /etc/os-release twice. I'll do a fix up for this.

**Comment by stefwalter** [comment]
Removing some of the #ifdefs to make the code more manageable.

**Comment by andreasn** [comment]
https://github.com/andreasn/cockpit/tree/textual-branding-stylefixes

**Comment by stefwalter** [comment]
* Using sessionStorage instead of localStorage.
 * Using cockpit.format to do the style content substitution (which is very cool by the way).

**Comment by stefwalter** [comment]
Replaced by #2322

**Comment by stefwalter** [comment]
Closed by #2322

**Pull request closed without merging**
