### PR TITLE
Image refresh for fedora-30

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-30
 * [x] image-refresh fedora-30

### CODE REVIEW

**Comment by marusak** [comment]
[selenium-edge](https://209.132.184.41:8493/logs/pull-12296-20190711-053737-c08de404-selenium-edge/log.html) and [podman](https://209.132.184.41:8493/logs/pull-12296-20190711-053737-c08de404-cockpit-project-cockpit-podman-cockpit-fedora-30/log) are acting up, lets try them again

**Comment by martinpitt** [comment]
I retried cockpit-podman three times, looks like it's again broken differently :(

**Comment by marusak** [comment]
This is so typical, I wrote down on piece of paper which lines exactly failed to compare, retried and it succeeded :D Anyway I noticed that it fails on commit and remembered @KKoukiou opened issue and added naughty for that. So I picked the naughty and put it here as well. Now lets run the tests again and I'll check the other test that was failing.

**Comment by marusak** [comment]
```
  File "test/check-application", line 318, in testLifecycleOperations
    self.check_container('swamped-crate', ['swamped-crate', 'busybox:latest', 'sh', 'stopped'])
```
This is the other test that fails very regularly on F29 and F30. It is not broken with this update for sure, but it just happens way too often. We should do some investigation.

**Comment by martinpitt** [comment]
Yay, all green!

**Pull request merged**
