### PR TITLE
Refactor machines listing and logic into its own module

### PR DESCRIPTION
**Pull request by stefwalter**
This is used by both index.js and the dashboard in shell.js

### CODE REVIEW

**Comment by mvollmer** [comment]
Machines don't get a nice initial color anymore.

Log out, remove /var/lib/cockpit/machines, log into dashboard: localhost is grey.
Add a second machine: also grey.

**Comment by mvollmer** [comment]
Removing a machine from the dashboard triggers a JavaScript exception:
```
TypeError: handleObj.handler.apply is not a function
```

**Comment by stefwalter** [comment]
> TypeError: handleObj.handler.apply is not a function

Fixed by #2021

**Comment by stefwalter** [comment]
Fixed color selection.

**Comment by stefwalter** [comment]
Loaded the pretty names properly per machine.

**Comment by mvollmer** [comment]
> Fixed color selection.

Works.

**Comment by mvollmer** [comment]
If I add two machines, they both show up with the same pretty name.
wrong-pretty-name
wrong-pretty-name-2

**Comment by stefwalter** [comment]
> If I add two machines, they both show up with the same pretty name.

Duh, I know what went wrong.

**Comment by stefwalter** [comment]
Fixed accessing pretty host name from wrong machine.

**Pull request closed without merging**
