### PR TITLE
Drop obsolete expected messages filters

### PR DESCRIPTION
**Pull request by martinpitt**
The corresponding bugs got fixed a while ago.

### CODE REVIEW

**Comment by martinpitt** [comment]
Nice, this works! On [fedora-30](https://209.132.184.41:8493/logs/pull-11733-20190503-062020-b85fe2a8-verify-fedora-30/log.html) there is one known/unrelated flake, I deliberately didn't retry here.

**Comment by martinpitt** [comment]
On merging this needs to add `Fixes #8871` to the commit log.

**Comment by marusak** [comment]
It failed today [here](https://209.132.184.41:8493/logs/pull-11732-20190503-021010-5140df32-container-kubernetes/log.html). It was in `container/kubernetes` so I tried it here.

**Comment by marusak** [comment]
I am sorry @martinpitt, but it is still needed, see [here](https://209.132.184.41:8493/logs/pull-11733-20190503-090101-b85fe2a8-container-kubernetes/log.html#15). Maybe it can drop just some messages?

**Comment by martinpitt** [comment]
Oops, thanks for catching! It's a bit weird, as container tests run on Fedora 30 now, and I only removed the naughty on fedora-29 (and rhel-8).

Anyway, I reopened https://bugzilla.redhat.com/show_bug.cgi?id=1559324 and reduced this PR to only drop the other two.

**Pull request merged**
