### PR TITLE
storage: Allow truncation of ID column

### LINKED ISSUE #19767: Layout problem with new storage view
### Explain what happens

grafik

### Version of Cockpit

307

### Where is the problem in Cockpit?

Storage

### Server operating system

Debian

### Server operating system version

12.3

### What browsers are you using?

Firefox

### System log

_No response_

### PR DESCRIPTION
**Pull request by mvollmer**
Thanks a lot to @MohdMohsin97 for the initial version of this!

Fixes #19767

### CODE REVIEW

**Comment by martinpitt** [comment]
The [pixel changes](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19913-20240130-163903-8e918159-fedora-39-storage/log.html) need review here. Is it really intended to leave [so much space](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19913-20240130-163903-8e918159-fedora-39-storage/pixeldiff.html#TestStorageLvm2-testLvm-pool-page) between the columns? Makes them a bit harder to read IMHO. On [this one](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19913-20240130-163903-8e918159-fedora-39-storage/pixeldiff.html#TestStorageStratis-testBasic-fsys-rows), neither the old nor the new version are ideal, though.

But I suppose the real impact of this PR is with *long* identifiers. Could we have a new pixel test for that, to see how it behaves? And a manual "before" screenshot?

**Comment by mvollmer** [comment]
> Is it really intended to leave [so much space](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19913-20240130-163903-8e918159-fedora-39-storage/pixeldiff.html#TestStorageLvm2-testLvm-pool-page) between the columns?

Hmm, no, the intention was to constrain the "ID" column to not take more than 40% of the table width, so that very long ids don't squash the remaining columns. I'll see if I can get this better under control.

**Comment by mvollmer** [comment]
> Could we have a new pixel test for that, to see how it behaves? And a manual "before" screenshot?

Yes, let's do that.

**Comment by mvollmer** [comment]
> > Is it really intended to leave [so much space](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19913-20240130-163903-8e918159-fedora-39-storage/pixeldiff.html#TestStorageLvm2-testLvm-pool-page) between the columns?
> 
> Hmm, no, the intention was to constrain the "ID" column to not take more than 40% of the table width, so that very long ids don't squash the remaining columns. I'll see if I can get this better under control.

Ok, what I really wanted was to now have the remaining columns wrap, of course, so I did that.

There was some funny business with the ID text moving into the next column when it was indented. 

image

I think I fixed that so that there is a nuice gap:

image

But the warning icons still crash into the next column instead of leaving a gap. No idea how to fix that.

image

I think the `TruncateMiddle` element is always 100% width of its parent element, so there can be nothing else next to it.

**Comment by mvollmer** [comment]
RTL is also broken. Bah, this is cursed.

**Comment by mvollmer** [comment]
> RTL is also broken. Bah, this is cursed.

Mixing RTL and LTR can probably not be fixed for everyone. We can not get all combinations correct, I am afraid: RTL layout with LTR device names, LTR layout with RTL device names, RTL layout with RTL device names, LTR layout with LTR device names.

Right now I have "decided" that device names are probably LTR, even for RTL layout users.

The best option might be to give up truncation in the middle. But at least I found some bugs.

**Comment by mvollmer** [comment]
Middle truncation can't be done this way: https://github.com/patternfly/patternfly/issues/6268

**Pull request closed without merging**
