### PR TITLE
test: Download external Atomic packages during setup

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
This is intended to be used with a snippet like this in fedora-atomic.setup, for example:
```
( mkdir /var/external-packages
  cd /var/external-packages
  curl -O http://www.nic.funet.fi/pub/mirrors/fedora.redhat.com/pub/fedora/linux//updates/23/x86_64/p/python2-pyudev-0.20.0-2.fc23.noarch.rpm
)
```

Maybe we can find a way to avoid hard coding the full URL to the package.  Maybe we can download it on the host?

**Comment by stefwalter** [comment]
This is a high risk patch.

It encourages us to test a system that users cannot duplicate. The point of our integration testing is to test stuff as close as possible to what users will really have on their systems.

I imagine the only reason to ever use this would be when something is committed to being included upstream, but isn't yet in the atomic ostree trees available for use? How do we make sure that's the case?

**Comment by mvollmer** [comment]
> This is a high risk patch.

Hmm, we already have that functionality, although we don't use it.  See for example the change to atomic.install in https://github.com/cockpit-project/cockpit/pull/4350/commits/0a0e72251c3878496e998b27b4d191cec60295ac

This PR moves the downloading from atomic.install to atomic.setup to avoid network access during a test run, just as we do for the non-atomic distributions.

> I imagine the only reason to ever use this would be when something is committed to being included upstream, but isn't yet in the atomic ostree trees available for use? How do we make sure that's the case?

Technically, I assume that atomic works like any other distribution: We add a dependency in cockpit.spec, and once that reaches Atomic via the Fedora repositories, the atomic ostree will automatically include the new dependency.  Is that not true?

(And I haven't considered until now what this means for our external packages.  We should probably ignore all external packages that are already installed, and output a warning.)

**Comment by stefwalter** [comment]
> Technically, I assume that atomic works like any other distribution: We add a dependency in cockpit.spec, and once that reaches Atomic via the Fedora repositories, the atomic ostree will automatically include the new dependency. Is that not true?

Sorta. But not really. One of the things that we're working on is containerizing Cockpit further. That means moving everything but the cockpit-bridge out of Atomic Host. The cockpit packages then live in the container, and are served from there, once the system and its version is identified.

That means the various cockpit-xxx packages can't pull in dependencies just via RPMs. Specific packages would obviously only be loaded when talking to a relevant Atomic system, with the given capabilities. However the packages themselves wouldn't be able to pull in dependencies, or place stuff on the target system at install time. Only at runtime, from within the browser, via the standard cockpit.xxx() functions.

**Comment by mvollmer** [comment]
> That means the various cockpit-xxx packages can't pull in dependencies just via RPMs.

So we add the dependencies to cockpit-bridge on the Atomics?

**Comment by mvollmer** [comment]
> So we add the dependencies to cockpit-bridge on the Atomics?

That was tongue-in-cheek... :-)  I try to do without python-pyudev.

**Comment by mvollmer** [comment]
> This is a high risk patch.

The risk, as I see it now, is that Cockpit acquires additional dependencies that would make it a lot harder to eventually move its components (like cockpit-docker) into containers, right?

Do we have any formal way to influence what is available to be used via cockpit.spawn, cockpit.dbus, etc?

**Pull request closed without merging**
