### PR TITLE
Image refresh for rhel-7

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for rhel-7 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-rhel-7-2017-03-06/

### CODE REVIEW

**Comment by martinpitt** [comment]
No useful error message in the failure log:
```
Uploading...
Traceback (most recent call last):
  File "./vm-create", line 201, in <module>
    subprocess.check_call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./vm-upload', '--store', 'mvollmer@file.rdu.redhat.com:', 'rhel-7']' returned non-zero exit status 1
```
@mvollmer: What's the best practice for those? Close PR and wait for the next one, or re-trigger a rebuild via a bot command, or something else?

**Comment by martinpitt** [comment]
@mvollmer: PR #6037 for rhel-atomic failed in the same way, so this might be systematic, not just a fluke?

**Comment by mvollmer** [comment]
The error is some way up in the log:

```
rsync: write failed on "/home/remote/mvollmer/public_html/images/rhel-7-f4c616b385825bf7446933b29bbb486bc3327bfd.qcow2.xz": Disk quota exceeded (122)
```

Output is weirdly interleaved in our logs sometimes, but I couldn't figure out how to fix that after spending all of 10 minutes on it.... maybe it's worth attacking this in earnest.

I have removed some old images.

Should we add `--prune` to the upload command, or is that too dangerous?

**Comment by mvollmer** [comment]
> What's the best practice for those? Close PR and wait for the next one, or re-trigger a rebuild via a bot command, or something else?

I'll retrigger this and #6037 .

**Comment by mvollmer** [comment]
Retriggered as #6043 and #6044.

**Pull request closed without merging**
