### PR TITLE
Adjust for CentOS 7.5

### LINKED ISSUE #9159: CentOS 7.5 storaged conflict
It seems cockpit-storaged depends on several storaged modules which are unavavailible on CentOS 7.5, due to storaged being obsoleted by udisks2. Not sure how to proceed here - any thoughts?

```
Error: Package: cockpit-storaged-167-1.el7.centos.noarch (centos-cockpit)
           Requires: storaged-lvm2 >= 2.1.1
           Available: storaged-lvm2-2.1.2-1.el7.centos.x86_64 (centos-cockpit)
               storaged-lvm2 = 2.1.2-1.el7.centos
           Available: storaged-lvm2-2.5.2-4.el7.x86_64 (extras)
               storaged-lvm2 = 2.5.2-4.el7
Error: Package: cockpit-storaged-167-1.el7.centos.noarch (centos-cockpit)
           Requires: storaged-iscsi >= 2.1.1
           Available: storaged-iscsi-2.1.2-1.el7.centos.x86_64 (centos-cockpit)
               storaged-iscsi = 2.1.2-1.el7.centos
           Available: storaged-iscsi-2.5.2-4.el7.x86_64 (extras)
               storaged-iscsi = 2.5.2-4.el7
Error: Package: cockpit-storaged-167-1.el7.centos.noarch (centos-cockpit)
           Requires: storaged >= 2.1.1
           Available: storaged-2.1.2-1.el7.centos.x86_64 (centos-cockpit)
               storaged = 2.1.2-1.el7.centos
           Available: storaged-2.5.2-4.el7.x86_64 (extras)
               storaged = 2.5.2-4.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@hell01-serv01 ~]# yum install storaged-2.5.2-4.el7.x86_64
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.coreix.net
 * centos-php71: rpms.remirepo.net
 * centos-php71-safe: rpms.remirepo.net
 * epel: mirrors.coreix.net
 * extras: mirror.freethought-internet.co.uk
 * updates: mirrors.coreix.net
Package storaged-2.5.2-4.el7.x86_64 is obsoleted by udisks2-2.7.3-6.el7.x86_64 which is already installed
Nothing to do
```

### PR DESCRIPTION
**Pull request by martinpitt**
See individual commits for details

Fixes #9159 

 * [x] image-refresh centos-7

### CODE REVIEW

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9160-20180513-192020/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-kx0k7.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9160-20180513-194040/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-px44l.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9160-20180513-194040/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20180513-200303

**Comment by mvollmer** [comment]
Green enough, thanks!

**Pull request merged**
