### PR TITLE
Translate the kubernetes component

### PR DESCRIPTION
**Pull request by stefwalter**
Now that the angular-gettext support is done. Translate the kubernetes component.

Depends on:

* [x] https://github.com/openshift/registry-image-widgets/pull/2
* [x] registry-image-widgets 0.0.3
* [x] #5326 
* [x] #5418 
* [x] #5420 
* [x] #5421 
* [ ] #4792

### CODE REVIEW

**Comment by petervo** [comment]
In kube-client-cockpit.js we still have the unfinished CockpitTranslate that's used via KubeTranslate. Is there a different way existing JS code needs to use? Or do we need to finish up that implementation?

**Comment by stefwalter** [comment]
> In kube-client-cockpit.js we still have the unfinished CockpitTranslate that's used via KubeTranslate. Is there a different way existing JS code needs to use? Or do we need to finish up that implementation?

Currently I've left the javascript code being translated via cockpit.gettext(), and the angular side of things via angular-gettext. I know it's not amazing, but it also seems to work well.

**Comment by petervo** [comment]
That's the point, the kubernetes code is not using cockpit.gettext. It needs to be added it to the CockpitTranslate factory.

**Comment by stefwalter** [comment]
Ok. I'll try and make that happen.

**Comment by stefwalter** [comment]
> That's the point, the kubernetes code is not using cockpit.gettext. It needs to be added it to the CockpitTranslate factory.

Done in #4792

**Comment by stefwalter** [comment]
Rebased.

**Comment by petervo** [comment]
This needs a rebase and the same gettextLocale change as #5420

**Comment by stefwalter** [comment]
Rebased on an updated #4792

**Pull request closed without merging**
