### PR TITLE
Image refresh for debian-stable

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for debian-stable
 * [x] image-refresh debian-stable

### CODE REVIEW

**Comment by martinpitt** [comment]
[Two failures](https://fedorapeople.org/groups/cockpit/logs/pull-10649-20181123-075151-d0b766a7-verify-debian-stable/log.html), retrying

**Comment by martinpitt** [comment]
It seems [testCreate](https://fedorapeople.org/groups/cockpit/logs/pull-10649-20181123-090909-d0b766a7-verify-debian-stable/log.html#80) for virsh is consistently broken now. @KKoukiou , can you please have a look?

**Comment by KKoukiou** [comment]
Increasing memory didn't work, I am running out of ideas..

@Antique since you are more familiar with qemu code, does this make any sense to you?
This test, which is trying to create VM with > 100 memory fails with inconsistent way.
Sometimes we get from virt-install the following error which is what we expect:
```
> warning: ERROR    internal error: process exited while connecting to monitor: Could not allocate dynamic translator buffer
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start subVmTestCreate8
otherwise, please restart your installation.
```
However sometimes the detail is missing and we see the following like here https://fedorapeople.org/groups/cockpit/logs/pull-10649-20181123-201414-6acf8bc7-verify-debian-stable/log.html#41
```
> warning: ERROR    internal error: process exited while connecting to monitor
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start subVmTestCreate8
otherwise, please restart your installation.
```

I have no idea what might cause this issue though :( Ideas?

**Comment by Antique** [comment]
> Increasing memory didn't work, I am running out of ideas..
> 
> @Antique since you are more familiar with qemu code, does this make any sense to you?
> This test, which is trying to create VM with > 100 memory fails with inconsistent way.
> Sometimes we get from virt-install the following error which is what we expect:
> 
> ```
> > warning: ERROR    internal error: process exited while connecting to monitor: Could not allocate dynamic translator buffer
> Domain installation does not appear to have been successful.
> If it was, you can restart your domain by running:
>   virsh --connect qemu:///system start subVmTestCreate8
> otherwise, please restart your installation.
> ```
> However sometimes the detail is missing and we see the following like here https://fedorapeople.org/groups/cockpit/logs/pull-10649-20181123-201414-6acf8bc7-verify-debian-stable/log.html#41
> 
> ```
> > warning: ERROR    internal error: process exited while connecting to monitor
> Domain installation does not appear to have been successful.
> If it was, you can restart your domain by running:
>   virsh --connect qemu:///system start subVmTestCreate8
> otherwise, please restart your installation.
> ```
> I have no idea what might cause this issue though :( Ideas?
> 
> (It looks like it fails only on the centosci but I am not 100% and also I don't know what's the difference there)

Hi, so the issue here is that debian-stable has old version of QEMU (2.8.1) which contains a bug that is probably fixed in newer versions.  If the host is under a load QEMU binary crashes in TCG code which will result in not printing any error and only the libvirt warning.

I'm not sure whether there is any easy way how to fix it from cockpit side, I guess the only reliable solution would be to report a BZ for debian to get the crash fixed in QEMU.

**Comment by martinpitt** [comment]
Such a report with some details how to reproduce it would be most helpful. Then we can accept this error message *only* on debian-stable (to ensure that we don't crash with unknown errors on any other distribution). Thanks!

**Comment by martinpitt** [comment]
@KKoukiou : What do you think about allowing this alternative error message only for this test case and only on debian-stable, with a comment? This is much more limited than the "allow this error message everywhere" PR that you had a while ago, and that would be fine and justified IMHO.

**Comment by KKoukiou** [comment]
> @KKoukiou : What do you think about allowing this alternative error message only for this test case and only on debian-stable, with a comment? This is much more limited than the "allow this error message everywhere" PR that you had a while ago, and that would be fine and justified IMHO.

I posted patch on top of the debian-stable image update commit, which skips the debian-stable test if not error from qemu is present.

**Pull request merged**
