### PR TITLE
added disabled html attribute in place of class name at relevant places

### PR DESCRIPTION
**Pull request by Sonam3107**

### CODE REVIEW

**Comment by KKoukiou** [comment]
> May I ask, why do you want to remove the class and add the element attribute?

@andreasn maybe you can answer here since you created the original issue.
TBH I was not able to find the preferred method in any documentation.

**Comment by martinpitt** [comment]
AFAIK, mostly because `disabled=` is a standard HTML tag attribute that will be rendered correctly without additional CSS, and it is also accessible -- i. e. screen readers etc. handle it correctly. Where as a "disabled" class is a cockpit specific thing, so we also need additional CSS rules, which may again break e. g. PatternFly components and such.

**Comment by andreasn** [comment]
Patternfly4 uses the disabled property, rather than a class on their examples page, I can't tell for sure, but the disabled class might be an old bootstrap thing that predates the disabled html property.
https://www.patternfly.org/v4/documentation/core/components/button

I think we first found the disabled class thing here https://github.com/cockpit-project/cockpit/pull/11987#issuecomment-505391746

Yes, as @martinpitt says, it's for accessibility. Marking it as disabled will make sure that a screen-reader, such as JAWS or NVDA will skip reading those buttons or fields.
https://stackoverflow.com/a/38059790

**Comment by marusak** [comment]
> I'm not able to check the test details. Can you please provide more information?

There are currently no tests results. You can run it locally, but I would just run it here and then see what needs to be fixed.

But firstly I would just really go through the code and fix it everywhere. I quickly took a look and I see some places still, like `pkg/docker/containers-view.jsx` or `pkg/lib/patterns.js`, `pkg/shell/indexes.js` (and more). Also in `pkg/docker/util.js` we toggle class `disabled` which means we set it somewhere.

**Comment by marusak** [comment]
... and has conflicts already :( @Sonam3107 do you need some advice/help with this?

**Comment by marusak** [comment]
Being replaced by #13552

**Pull request closed without merging**
