### PR TITLE
tests: remove unnecessary waits from the storage tests

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by martinpitt** [comment]
[rhel-8-3 timed out](https://logs.cockpit-project.org/logs/pull-14911-20201117-100729-3698c460-rhel-8-3/log.html), same error as [here](https://github.com/cockpit-project/cockpit/pull/14892#issuecomment-726622313) and [here](https://github.com/cockpit-project/cockpit/pull/14899#issuecomment-728706856) -- this `TestMachines.testBasic` failure is quite nasty, unfortunately it doesn't reproduce on my system. Need to investigate on a CI machine.

The [distropkg crash](https://logs.cockpit-project.org/logs/pull-14911-20201117-100729-3698c460-rhel-8-3-distropkg/log.html#300) is quite interesting, not sure if that is related -- it could be triggered because some operations now happen earlier? Anyway, this doesn't really break the test, so a bugzilla with a symbolic backtrace plus a naughty would do the job.

**Comment by KKoukiou** [comment]
> [rhel-8-3 timed out](https://logs.cockpit-project.org/logs/pull-14911-20201117-100729-3698c460-rhel-8-3/log.html), same error as [here](https://github.com/cockpit-project/cockpit/pull/14892#issuecomment-726622313) and [here](https://github.com/cockpit-project/cockpit/pull/14899#issuecomment-728706856) -- this `TestMachines.testBasic` failure is quite nasty, unfortunately it doesn't reproduce on my system. Need to investigate on a CI machine.
> 
> The [distropkg crash](https://logs.cockpit-project.org/logs/pull-14911-20201117-100729-3698c460-rhel-8-3-distropkg/log.html#300) is quite interesting, not sure if that is related -- it could be triggered because some operations now happen earlier? Anyway, this doesn't really break the test, so a bugzilla with a symbolic backtrace plus a naughty would do the job.

It's missing the actual core file actually, and the bt from the journal is not very helpful.

```
Nov 17 05:39:45 localhost.localdomain systemd-coredump[56759]: Process 56719 (lvm) of user 0 dumped core.
                                                               
                                                               Stack trace of thread 56719:
                                                               #0  0x00007fd3068f1d52 __strcmp_avx2 (libc.so.6)
                                                               #1  0x00005577689bbde5 validate_hints (lvm)
                                                               #2  0x00005577689b93cb label_scan (lvm)
                                                               #3  0x000055776898df04 lvmcache_label_scan (lvm)
                                                               #4  0x0000557768977570 process_each_pv (lvm)
                                                               #5  0x000055776896c08a _do_report (lvm)
                                                               #6  0x000055776896c2ab _report (lvm)
                                                               #7  0x00005577689561ad lvm_run_command (lvm)
                                                               #8  0x00005577689574d3 lvm2_main (lvm)
                                                               #9  0x00007fd3067bc7b3 __libc_start_main (libc.so.6)
                                                               #10 0x000055776893187e _start (lvm)
```

Link to these logs: https://logs.cockpit-project.org/logs/pull-14911-20201117-100729-3698c460-rhel-8-3-distropkg/log.html#300
Will retry once more.

**Review by mvollmer — APPROVED** [review]
Seems to work... :-)

**Comment by KKoukiou** [comment]
I will merge it after tomorrows release.

**Pull request merged**
