### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Chen-Leon**

### CODE REVIEW

**Comment by marusak** [comment]
Thank you for these changes!
We use [Weblate](https://translate.fedoraproject.org/projects/cockpit/master/) to manage our translations. Of course, it is totally fine to use different tools (as you did with poedit), but we want to upload these changes back into weblate.
Weblate has file upload functionality, which is ideal for this case.
Please let me know if you want to do it yourself or if I should do it. In the latter case if you provide me with your email address I can keep you as author of these changes.

**Comment by Chen-Leon** [comment]
OK
MY EMAIL ADDRESS
cwk545@gmail.com

**Comment by marusak** [comment]
Thanks, I upload it into weblate and made sure it was correctly propagated.
(In our intermediate repo it is now commit https://github.com/cockpit-project/cockpit-weblate/commit/68fa92587fc8934c4c3964d4a01fc5a275f1b407 created on your behalf)

**Comment by Chen-Leon** [comment]
Thank`s

**Comment by Chen-Leon** [comment]
How can i create cockpit-project/cockpit-weblate account?

**Comment by marusak** [comment]
> How can i create cockpit-project/cockpit-weblate account?

`cockpit-project/cockpit-weblate` is just internal thing for automatic pulling of translations.
To become translator, you want to do so in weblate. https://translate.fedoraproject.org/
You can login there by using your Fedora account. https://admin.fedoraproject.org/accounts/

**Comment by Chen-Leon** [comment]
OK Thanks

**Comment by marusak** [comment]
FYI now your changes got into Cockpit via https://github.com/cockpit-project/cockpit/pull/13846 and they will be included in the next release.

**Pull request closed without merging**
