### PR TITLE
bots: Add registry IP to insecure-registry options for docker

### PR DESCRIPTION
**Pull request by petervo**
* [x] image-refresh openshift

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tests-ps164.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-7401-20170802-164545/

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-20170802-172323

**Comment by petervo** [comment]
The testImages failure is fixed by #7400. But I don't really want to hold off on getting the new 1.6 image merged while waiting for that PR.

Should we add a tmp known-issue? Or if someone is really to review quickly I can combine these 2 PRs together.

**Comment by martinpitt** [comment]
As #7400 is blocked by more things, and the changes here are good by themselves, I vote for landing this with a temp known issue. After all, we haven't really run the openshift tests for months, so running all of them but one is already a major improvement.

**Comment by martinpitt** [comment]
Force-pushed with adding a Closes # and a known issue for the one failure (#7452), and rebasing to master.

**Comment by martinpitt** [comment]
Test failures are unrelated.

**Pull request merged**
