### PR TITLE
networkmanager: reimplement dropdowns to use select native html element

### LINKED ISSUE #12441: Dropdowns in IP config dialogs too narrow for text
Cockpit version: 199
Page: Networking

image

### PR DESCRIPTION
**Pull request by KKoukiou**
Previously, the text for Addresses options was not fiting inside the
select button.

Fixes #12441

(Clearly that's an lazy fix - this dropdown has more problems (aka accessibility) and should be probably be ported to use <select> <option>... like our custom component for selects.
But I would get this fix in anyway - and maybe in the long term fix it properly with some reactification of the network page.

### CODE REVIEW

**Comment by marusak** [comment]
Well, two things:
1. This won't help when different language then English is used
2. Networking uses a few custom dropdowns and they should be replaced. They also cause problems in https://github.com/cockpit-project/cockpit/issues/12954

I think the better approach would be to replace them straight away without fixing them. It should be simple. The following code works (it needs a bit of style to fit better into the page and to check if the value is correctly propagated on change).
```
--- a/pkg/networkmanager/interfaces.js
+++ b/pkg/networkmanager/interfaces.js
@@ -69,18 +69,10 @@ function select_btn(func, spec, klass) {
     var choice = spec[0].choice;
 
     function option_mapper(opt) {
-        return $('<li>', { value: opt.choice }).append($("<a tabindex='0'>").text(opt.title));
+        return $('<option>', { value: opt.choice }).text(opt.title);
     }
 
-    var toggle = $('<button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">').append(
-        $('<span class="pull-left"></span>'),
-        $('<div class="caret"></div>')
-    );
-
-    var btn = $('<div class="btn-group bootstrap-select dropdown">').append(
-        toggle,
-        $('<ul class="dropdown-menu">').append(spec.map(option_mapper))
-    );
+    var btn = $('<select>').append(spec.map(option_mapper));
 
     btn.on('click', 'li', function() {
         choice = $(this).attr('value');
```

**Comment by KKoukiou** [comment]
> Well, two things:
> 
>     1. This won't help when different language then English is used
> 
>     2. Networking uses a few custom dropdowns and they should be replaced. They also cause problems in #12954
> 
> 
> I think the better approach would be to replace them straight away without fixing them. It should be simple. The following code works (it needs a bit of style to fit better into the page and to check if the value is correctly propagated on change).
> 
> ```
> --- a/pkg/networkmanager/interfaces.js
> +++ b/pkg/networkmanager/interfaces.js
> @@ -69,18 +69,10 @@ function select_btn(func, spec, klass) {
>      var choice = spec[0].choice;
>  
>      function option_mapper(opt) {
> -        return $('<li>', { value: opt.choice }).append($("<a tabindex='0'>").text(opt.title));
> +        return $('<option>', { value: opt.choice }).text(opt.title);
>      }
>  
> -    var toggle = $('<button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">').append(
> -        $('<span class="pull-left"></span>'),
> -        $('<div class="caret"></div>')
> -    );
> -
> -    var btn = $('<div class="btn-group bootstrap-select dropdown">').append(
> -        toggle,
> -        $('<ul class="dropdown-menu">').append(spec.map(option_mapper))
> -    );
> +    var btn = $('<select>').append(spec.map(option_mapper));
>  
>      btn.on('click', 'li', function() {
>          choice = $(this).attr('value');
> ```

Good point - I will repost!

**Comment by KKoukiou** [comment]
Tests are broken all over thus added needswork.

**Comment by martinpitt** [comment]
Current screenshot with updated "Search..." field (the above still has "Type to search..")

image

**Comment by KKoukiou** [comment]
> Thanks for doing it the right way:)
> Looks good.
> Two things:
> 
>     1. Not related change in `pkg/lib/page.css` (but I am fine with it, because also my editor adds newlines and it is annoying to be careful not to pick them in commits)
> 
>     2. Changing address in IPv4 dialog (the one that the referenced issue is showing) with arrows (navigate to it with tab and than arrows down and up should change values in select) looses focus after every single change. This is super user/a11y unfriendly. You think you can take a look? (But I am bit afraid this may be hard to fix as it looses focus since it redraws the dialog. But maybe if the change is triggered by changing value in select, it can focus it back on?)

Hmm, adding a simple focus() in the select_btn does not seem to work and I am also not sure why only in this dialog it loses focus whilst in all the other dialogs that I affected with this PR things work as expected. I am really not confident with jquery - if you have an idea about the fix I would appreciate a feedback :)

**Comment by KKoukiou** [comment]
> Thanks for doing it the right way:)
> Looks good.
> Two things:
> 
>     1. Not related change in `pkg/lib/page.css` (but I am fine with it, because also my editor adds newlines and it is annoying to be careful not to pick them in commits)
> 
>     2. Changing address in IPv4 dialog (the one that the referenced issue is showing) with arrows (navigate to it with tab and than arrows down and up should change values in select) looses focus after every single change. This is super user/a11y unfriendly. You think you can take a look? (But I am bit afraid this may be hard to fix as it looses focus since it redraws the dialog. But maybe if the change is triggered by changing value in select, it can focus it back on?)

@marusak from what it seems there is not really simple solution to this but will require a whole rewriting of the dialog. Since it's not a regression do you mind getting this in as is and consider some reactification of this dialog for the future, something that will solve this issue and much more.

**Comment by marusak** [comment]
> Since it's not a regression do you mind getting this in

Sure, please go ahead with this, thanks :)

**Pull request merged**
