### PR TITLE
test: Fix UnicodeDecodeError during OpenShift image build, refresh OpenShift image

### PR DESCRIPTION
**Pull request by martinpitt**
https://api.github.com/repos/openshift/origin/releases contains fancy
non-ASCII quotes which aren't representable in the ASCII "C" locale. Run
python under C.UTF-8 to fix an UnicodeDecodeError during image build.

----
This replaces the broken PR #6140. After the image gets built, need to update openshift.kubeconfig (at some point we should automate that).

### CODE REVIEW

**Comment by martinpitt** [comment]
bot: Image refresh for openshift

**Comment by cockpituous** [comment]
Image creation for openshift in process on cockpit-9.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-openshift-f2e8c3a44c9ade015fe5cdd9eb2a21fd97e1fd73/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-openshift-f2e8c3a44c9ade015fe5cdd9eb2a21fd97e1fd73

**Comment by martinpitt** [comment]
While I'm at it, I want to automatically update `test/verify/files/openshift.kubeconfig` with cockpituous' weekly image updates, as it's getting annoying to having to do that manually. Testing the fix locally.

**Comment by martinpitt** [comment]
This works nicely locally now, let's try it on the machinery.

**Comment by martinpitt** [comment]
bot: Image refresh for openshift

**Comment by cockpituous** [comment]
Image creation for openshift in process on cockpit-11.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-openshift-50fe7ad0f4c89275c77e558f2a3b4bb412f6a32f/

**Comment by cockpituous** [comment]
Image creation done: https://github.com/cockpituous/cockpit/commits/refresh-openshift-50fe7ad0f4c89275c77e558f2a3b4bb412f6a32f

**Comment by martinpitt** [comment]
Nice, it worked: https://github.com/cockpituous/cockpit/commit/21fa4469f826a3 . Pulled that in, let's verify with CI now.

**Pull request closed without merging**
