### PR TITLE
Logs improvements

### PR DESCRIPTION
**Pull request by marusak**
Found this while playing with https://github.com/cockpit-project/cockpit/pull/16091
These two changes were unrelated, so sending separate PR.

### CODE REVIEW

**Review by KKoukiou — DISMISSED** [review]

**Comment by marusak** [comment]
Rebased to work around `The cached package-lock.json doesn't match our own`

**Review by martinpitt — APPROVED** [review]
Danke!

**Comment by marusak** [comment]
packit is stuck. Maybe I can re-trigger it?

**Comment by martinpitt** [comment]
@marusak : FYI, "/packit build" re-does the whole srpm+copr build. If it was just the tests, then `/packit test` re-runs only these, that's faster. If `build` is stuck, then that's usually because our jumpstart build/publish failed (but that's not what happened here). Just FYI, all green now.

**Pull request merged**
