### PR TITLE
machines: Show `Used by` column for Storage Volumes

### PR DESCRIPTION
**Pull request by KKoukiou**
This will allow us to see if some volume is used by some guest as a disk.

### CODE REVIEW

**Comment by KKoukiou** [comment]
This was split out from https://github.com/cockpit-project/cockpit/pull/10783 because it's a more simple feature and doesn't need to get for the Volume Deletion.

**Comment by KKoukiou** [comment]
used-by-storage-volumes

**Comment by martinpitt** [comment]
LGTM, except for the build failure:

```
  1105:41  error  A space is required after '{'   object-curly-spacing
  1105:65  error  A space is required before '}'  object-curly-spacing
```

**Comment by KKoukiou** [comment]
st-volumes-used

**Pull request merged**
