### PR TITLE
system: Add CPU security mitigations dialog

### PR DESCRIPTION
**Pull request by martinpitt**
Cherry-picked from master commits 16c7c8e8f, 2e82a200, and de2dc4f6.

https://bugzilla.redhat.com/show_bug.cgi?id=1678956
(FIXME: use bug clone for 8.0.1)

### CODE REVIEW

**Comment by martinpitt** [comment]
Hmm, I did two backports to attempt to fix unit tests, but this will require a lot more to be able to build on Fedora 30. As we are not really interested in that for RHEL 8.0, I'm leaning towards ignoring the avocado/selenium tests here, and re-drop the glib bump and strv fix. I'll wait until the rhel-8-0 test finishes, though.

**Comment by martinpitt** [comment]
Some more backporteria, and I think I fixed the unit tests on Fedora 30 now.

**Comment by martinpitt** [comment]
Yet another backport to fully fix selenium.

**Comment by marusak** [comment]
[semaphore fail](https://semaphoreci.com/cockpit-project/cockpit/branches/pull-request-11875/builds/5) looks suspicious:
```
test/verify/check-system-info:45:1: E302 expected 2 blank lines, found 1
test/verify/check-system-info:537:1: E302 expected 2 blank lines, found 1
PASS: tools/test-static-code 1 pyflakes bots pkg tools
PASS: tools/test-static-code 2 pyflakes test
PASS: tools/test-static-code 3 js-translatable-strings
PASS: tools/test-static-code 4 unsafe-security-policy
PASS: tools/test-static-code 5 patternfly-font-paths
PASS: tools/test-static-code 6 json-verify
FAIL: tools/test-static-code 7 pep8 test
ERROR: tools/test-static-code process failed: 1
```

[avocado](https://209.132.184.41:8493/logs/pull-11875-20190520-181313-4834b00e-verify-rhel-8-0/log.html) and [rhel-8-0]( https://209.132.184.41:8493/logs/pull-11875-20190520-174242-4834b00e-avocado-fedora/log.html) both failed, but for both I am getting 404, which is weird. Avocado is most likely related to https://github.com/cockpit-project/cockpit/commit/ee31728674e .

**Comment by martinpitt** [comment]
@marusak: You can get the logs by moving from /log.html to /log. The HTML is a literal file with "404 not found", which is indeed confusing. The html wrapper doesn't work for backbranches just as it doesn't work for external projects -- yet another little thing to fix.

I'll fix pyflakes/pep8  and avocado. I'll look at the testNegotiate failure, but I'll limit the time that I spend on it. testKdump is just a flake, it worked in a previous test run.

**Pull request merged**
