### PR TITLE
test: Add another known issue for storaged crashing on CentOS

### PR DESCRIPTION
**Pull request by stefwalter**

### CODE REVIEW

**Comment by stefwalter** [comment]
Filed known issue for related Fedora 25 crash #5379

**Comment by stefwalter** [comment]
Fixed unrelated Semaphore CI failure here: https://github.com/cockpit-project/cockpit/pull/5382

**Comment by mvollmer** [comment]
Can we match on the actual crash?  It can happen anywhere.  Maybe apply the patterns also to the journal?

**Comment by stefwalter** [comment]
> Can we match on the actual crash? It can happen anywhere. Maybe apply the patterns also to the journal?

Sure. Go for it. But perhaps a follow up pull request?

**Pull request closed without merging**
