### PR TITLE
pybridge: Fix ssh-agent cleanup for setgid, enable on on current Ubuntu releases

### PR DESCRIPTION
**Pull request by martinpitt**
This picks up the remaining issue on #18757.

 - [x] Builds on top of #18757

https://issues.redhat.com/browse/COCKPIT-938

### CODE REVIEW

**Comment by martinpitt** [comment]
@allisonkarlitskaya : This is still blocked, but I'd appreciate your opinion about the ssh-agent cleanup. That could land independently too, of course, but we don't see the effect until we enable the pybridge on ubuntu or arch.

**Comment by martinpitt** [comment]
* Move it to remote.py
 * Lazily do this when opening the first remote channel

**Review by allisonkarlitskaya — DISMISSED** [review]
Thanks for all the iteration on this.  Now that we've implemented it, the chosen approach seems very natural.

**Comment by martinpitt** [comment]
@allisonkarlitskaya : I unconflicted this, and removed the FIXME in the recent client tests, to prove that cleanup now works :tada: Also, c-client tests work perfectly on ubuntu-stable, I enabled them.

**Review by allisonkarlitskaya — APPROVED** [review]
:taco: :tada:

**Pull request merged**
