### PR TITLE
Second batch of replace `wait_present` with `wait_visible`

### PR DESCRIPTION
**Pull request by marusak**
And one more batch left after this one will follow

### CODE REVIEW

**Comment by marusak** [comment]
A lot of failed tests in machines. It seems the the problem is elements being ambiguous. Will need some fun debugging and looking for better selectors.

**Comment by KKoukiou** [comment]
> A lot of failed tests in machines. It seems the the problem is elements being ambiguous. Will need some fun debugging and looking for better selectors.

I will push here a commit to fix this.

**Comment by marusak** [comment]
Thank you @KKoukiou for these fixes!
Two more places to fix, I'll push soon.
I see that we cannot open selects in our tests - this seems broken. Made me wonder, why are we using `cockpit-component-select` an not always using PF4 select component?

**Review by KKoukiou — APPROVED** [review]

**Comment by KKoukiou** [comment]
> Thank you @KKoukiou for these fixes!
> Two more places to fix, I'll push soon.
> I see that we cannot open selects in our tests - this seems broken. Made me wonder, why are we using `cockpit-component-select` an not always using PF4 select component?

Not any reason, we can just port it to PF4 select.

**Pull request merged**
