### PR TITLE
storage: Support resizing of LUKSv2

### PR DESCRIPTION
**Pull request by mvollmer**
Resizing a LUKSv2 volume might need a passphrase, and Cockpit should either get one from clevis or ask for one.

- [x] #9852

### CODE REVIEW

**Comment by mvollmer** [comment]
Because of the interaction with Clevis, we need #9852 first.

**Comment by martinpitt** [comment]
This is unblocked now. But still marked as WIP, does that need a rebase?

**Comment by mvollmer** [comment]
> But still marked as WIP, does that need a rebase?

The WIP was for the test, I think...

**Comment by martinpitt** [comment]
I retried the tests umpteen times, they won't succeed.

**Comment by mvollmer** [comment]
Oops, `RuntimeError: TypeError: Cannot read property 'IdType' of undefined`

**Comment by mvollmer** [comment]
> Oops, `RuntimeError: TypeError: Cannot read property 'IdType' of undefined`

`block` is null for thin pools, fixed.

**Pull request merged**
