### PR TITLE
Image refresh for centos-7

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for centos-7
 * [x] image-refresh centos-7

### CODE REVIEW

**Comment by martinpitt** [comment]
The [image build log](https://fedorapeople.org/groups/cockpit/logs/image-refresh-9010-20180418-213131/log) shows the problem:

    No package atomic-openshift-clients available.

and again yum just silently ignores that error :-( So for the time being we'll continue with installing "kubernetes" on centos-7.

**Comment by martinpitt** [comment]
Pushed fix, rebuilding image.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-sh8tm.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9010-20180422-194444/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20180422-201111

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-jrt1g.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9010-20180423-062727/

**Comment by cockpituous** [comment]
image-refresh centos-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-centos-7-20180423-064949

**Pull request merged**
