### PR TITLE
[rhel-9.0] Update translations from Fedora Weblate, and fix tests

### PR DESCRIPTION
**Pull request by cockpituous**
From [this workflow run](https://github.com/cockpit-project/cockpit/runs/3542214399?check_suite_focus=true)

### CODE REVIEW

**Review by martinpitt — DISMISSED** [review]
This looks correct now. :+1:

**Comment by martinpitt** [comment]
[unrelated failure](https://logs.cockpit-project.org/logs/pull-16325-20210908-091218-dadb41dc-rhel-9-0/log.html#212). There is no significant difference to main, maybe the recently refreshed rhel-9-0 image? Retrying.

**Comment by martinpitt** [comment]
Found the missing commit, and I also backported the recent unit test fixes while I was at it.

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
