### PR TITLE
machines: replace usage of ct-form-split with PF4 grid as suggested in the docs

### PR DESCRIPTION
**Pull request by KKoukiou**
See https://www.patternfly.org/v4/components/form/html-demos/#grid

### CODE REVIEW

**Review by garrett — CHANGES_REQUESTED** [review]
The label for the split feels too far away from the dropdown (or the dropdown could be too small... stretching it could be a fix)

Screenshot_2021-02-25 Virtual Machines - garrett Rain

Same issue for disk adding:

Screenshot_2021-02-25 Virtual Machines - garrett Rain(2)

**Comment by KKoukiou** [comment]
@garrett the distance between the labels is the same in master I think. It did not really change from the looks at all.

**Review by garrett — APPROVED** [review]
Oh, I didn't check master.

I still think the labels are a little off, but if this PR doesn't change the look, I'm all for it!

:+1: 

(I guess next up, outside of this PR, is `pkg/storaged/dialog.jsx`, which is the last part of Cockpit where we're using ct-form-split? And perhaps then Cockpit-Podman, if it's using it?)

**Comment by KKoukiou** [comment]
> Oh, I didn't check master.
> 
> I still think the labels are a little off, but if this PR doesn't change the look, I'm all for it!
> 
> +1
> 
> (I guess next up, outside of this PR, is `pkg/storaged/dialog.jsx`, which is the last part of Cockpit where we're using ct-form-split? And perhaps then Cockpit-Podman, if it's using it?)

Right, I did not touch storage to not have conflicts with the storage PR :)

**Comment by martinpitt** [comment]
This is conflict-y now, needs rebasing.

**Comment by KKoukiou** [comment]
@garrett can you please reapprove? I rebased and repushed because it was conflicty.

**Review by martinpitt — APPROVED** [review]
Interdiff looks clean, thanks! (Garrett is on PTO today)

**Pull request merged**
