### PR TITLE
Image refresh for continuous-atomic

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for continuous-atomic
 * [x] image-refresh continuous-atomic

### CODE REVIEW

**Comment by martinpitt** [comment]
Triggering the continuous-atomic test. @Gundersanne, @marusak: Is either of you interested in fixing image refreshes to actually triggering the right tests?

**Comment by martinpitt** [comment]
@Gundersanne: [This firewall zones failure](https://209.132.184.41:8493/logs/pull-11899-20190522-063636-4673c61c-verify-continuous-atomic/log.html#136) sounds like it needs to add continuous-atomic to the special cases?

**Comment by marusak** [comment]
Added continuous-atomic into special cases. Triggered two needed tests.

**Comment by marusak** [comment]
Ehm `cockpit/continuous-atomic@cockpit-project/cockpit-ostree` fails with `image-download: couldn't find file anywhere: continuous-atomic-202d6c2847ec4b5d822b8803dc8dc6b79798785a6fcfd5b7739bae96499358d1.qcow2`. But `verify/continuous-atomic` found it. There is something weird happening here.

**Comment by martinpitt** [comment]
That's a bit weird indeed -- according to the [log](https://209.132.184.41:8493/logs/image-refresh-11899-20190521-233232/log) it was uploaded to https://images-cockpit.apps.ci.centos.org/ , but it's not there. I have the feeling the image-prune job sometimes does the wrong thing and removes freshly updated images. I reuploaded it from cockpit-10, so we can retry it.

**Pull request merged**
