### PR TITLE
bots: Install system-logos on Fedora images, fix fedora-29 rebuild

### PR DESCRIPTION
**Pull request by martinpitt**
cockpit-ws will depend on it soon. See commit d9b47a6ddd7 for details.

 * [x] image-refresh fedora-28
 * [x] image-refresh fedora-29
 * [x] `check-connection` regression on Fedora 29 (https://bugzilla.redhat.com/show_bug.cgi?id=1629732)
 * [x] `check-login` regression on Fedora 29

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh fedora-28 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-28-20180917-070303

**Comment by cockpituous** [comment]
image-refresh fedora-29 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-29-20180917-082121

**Comment by stefwalter** [comment]
@martinpitt Can we have system-logos be just Recommends? Because it's massive. I'm very cautious about dependencies.

Cockpit's dependencies are starting to approach two orders of magnitude bigger that Cockpit.

**Comment by martinpitt** [comment]
> @martinpitt Can we have system-logos be just Recommends? Because it's massive. I'm very cautious about dependencies.

We could. I also noticed the massive-ness, it's being addressed at least here: https://bugzilla.redhat.com/show_bug.cgi?id=1626388 and should also trickle back into Fedora.

**Comment by martinpitt** [comment]
Note, PR #10083 reduces the Requires: to Recommends. But I still think it's a good idea to have the logo package on our test VMs, to make sure the logo works.

**Comment by martinpitt** [comment]
This change would at most cause image preparation failures. The remaining failures are known flakes, IMHO it's good enough.

**Comment by martinpitt** [comment]
Sorry, the previous comment was for a different PR. This PR refreshes the fedora-29 image, so it should be green.

**Comment by martinpitt** [comment]
I pushed a flake fix for check-login and adjustment for new OpenSSL to fix check-connection.

**Pull request merged**
