### PR TITLE
bots: Add clevis and tang to the Fedora images

### PR DESCRIPTION
**Pull request by mvollmer**
* [x] image-refresh fedora-27
 * [x] image-refresh fedora-26
 * [x] image-refresh fedora-i386
 * [x] image-refresh fedora-testing

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-75klp.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8832-20180315-121919/

**Comment by mvollmer** [comment]
I want to add a simple test to #8785

**Comment by cockpituous** [comment]
image-refresh fedora-27 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-27-20180315-125858

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-75klp.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8832-20180315-125858/

**Comment by cockpituous** [comment]
image-refresh fedora-i386 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-i386-20180315-134444

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-75klp.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8832-20180315-134444/

**Comment by cockpituous** [comment]
image-refresh fedora-testing done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-testing-20180315-142525

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-gkt1l.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-8832-20180315-142525/

**Comment by cockpituous** [comment]
image-refresh fedora-26 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-26-20180315-150707

**Comment by martinpitt** [comment]
Needs the images committed here at least, so setting "needswork" for now

**Pull request merged**
