### PR TITLE
misc: move to new tasks container location

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**

### CODE REVIEW

**Comment by martinpitt** [comment]
We need to pin the tasks container to a previous version, and/or fix ruff

**Comment by allisonkarlitskaya** [comment]
```
cockpit-bridge:ERROR:src/bridge/test-router.c:531:test_sharable_processing: {"command":"open","channel":"a","payload":"host","session":"private"} != {"command": "open", "channel": "a", "payload": "host", "user": "user", "session": "private"}
not ok /router/sharable-processing - cockpit-bridge:ERROR:src/bridge/test-router.c:531:test_sharable_processing: {"command":"open","channel":"a","payload":"host","session":"private"} != {"command": "open", "channel": "a", "payload": "host", "user": "user", "session": "private"}
Bail out!
FAIL test-router (exit status: 134)
```

...huh?

**Comment by allisonkarlitskaya** [comment]
> ```
> cockpit-bridge:ERROR:src/bridge/test-router.c:531:test_sharable_processing: {"command":"open","channel":"a","payload":"host","session":"private"} != {"command": "open", "channel": "a", "payload": "host", "user": "user", "session": "private"}
> not ok /router/sharable-processing - cockpit-bridge:ERROR:src/bridge/test-router.c:531:test_sharable_processing: {"command":"open","channel":"a","payload":"host","session":"private"} != {"command": "open", "channel": "a", "payload": "host", "user": "user", "session": "private"}
> Bail out!
> FAIL test-router (exit status: 134)
> ```
> 
> ...huh?

Okay, this is entertaining: this test has always been broken if it runs under an account with the username "user" (which it now does).

That should be easy enough to fix.

**Review by martinpitt — APPROVED** [review]
Thanks!

**Pull request merged**
