### PR TITLE
Support old UDisks2, kinda.

### PR DESCRIPTION
**Pull request by mvollmer**
This is my version of old UDisks2 support, based on @stefwalter:s.

The biggest thing is that I have completely removed support for fstab and crypttab.  Storaged does a lot more in that area.  See the 'config-items', 'track-parents', and 'tear-down' options in its documentation.  I think these options are important to have viable fstab and crypttab support.

### CODE REVIEW

**Comment by stefwalter** [comment]
I think you need this commit: https://github.com/stefwalter/cockpit/commit/ced4aad2aa9a405cb9b17f0de4ac67aa8c851702

**Comment by stefwalter** [comment]
The documentation needs to be updated: https://github.com/cockpit-project/cockpit/commit/854427502a7d0ffa32f923f2b55c36dc958b4beb

**Comment by stefwalter** [comment]
I agree with disabling unstable features. As long as we document why, which I've done in the documentation commit above.

**Comment by mvollmer** [comment]
> I agree with disabling unstable features. As long as we document why, which I've done in the documentation commit above.

Thanks!

**Comment by mvollmer** [comment]
> I think you need this commit: stefwalter@ced4aad

Thanks!

**Comment by mvollmer** [comment]
The tests need more adaptation, which will happen as part of #4901

**Pull request closed without merging**
