### PR TITLE
Gather all PF import files to seperate directory to ease copying them to external projects

### PR DESCRIPTION
**Pull request by KKoukiou**
This will allow external projects to copy PF files automatically like https://github.com/cockpit-project/starter-kit/pull/357

### CODE REVIEW

**Review by martinpitt — COMMENTED** [review]
Looks ok, but while we are touching this: I'd rather we moved this to pkg/lib/patternfly/. This is really not part of our "base1" API any more, so it shouldn't be in src/base1/. Would you consider moving it there, or is that somehow more complicated?

**Comment by KKoukiou** [comment]
> Looks ok, but while we are touching this: I'd rather we moved this to pkg/lib/patternfly/. This is really not part of our "base1" API any more, so it shouldn't be in src/base1/. Would you consider moving it there, or is that somehow more complicated?

Sure - I don't see why this would be an issue - I will adjust.

**Review by martinpitt — CHANGES_REQUESTED** [review]
> Sure - I don't see why this would be an issue - I will adjust.

Thanks! Marking as "request changes" then.

**Comment by martinpitt** [comment]
All builds fail now:

    make[1]: *** No rule to make target 'lib/patternfly/patternfly-cockpit.scss', needed by 'distdir-am'.  Stop.

**Review by martinpitt — CHANGES_REQUESTED** [review]
Please also fix the "seperate" typo in the commit message and add a Closes#.

**Review by martinpitt — APPROVED** [review]
Thanks! And let's ignore the typo in the commit message then, not important. :wink:

**Pull request merged**
