### PR TITLE
WIP: devices: update test images

### PR DESCRIPTION
**Pull request by mareklibra**
Update of test images for new 'devices' plugin.
Following new packages are installed:
  pciutils
  usbutils

### CODE REVIEW

**Comment by stefwalter** [comment]
This needs help. @mvollmer Do you have a moment to tag this pull request so it starts creating new images?

**Comment by martinpitt** [comment]
Is that still actually relevant? IMHO udev/hwdb present devices and their tree in a more consistent and accessible form, and hwdb has all the names that {pci,usb}utils have as well (it's built from the same original database).

**Comment by mareklibra** [comment]
There will be rework, but I would keep this open till #5523 design is finished and scope is clear.
It conforms the so far existing implementation.

**Comment by mareklibra** [comment]
No more needed

**Pull request closed without merging**
