### PR TITLE
test: Add test case for Overview page's memory usage indicator

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by marusak** [comment]
https://209.132.184.41:8493/logs/pull-13297-20191216-111111-131eddbf-cockpit-project-cockpit--centos-8-stream/log.html#261-2

**Comment by martinpitt** [comment]
@marusak : Right, I saw. Presumably the same error on [rhel-8-2](https://209.132.184.41:8493/logs/pull-13297-20191216-111111-131eddbf-cockpit-project-cockpit--rhel-8-2/log.html#261-2) (it didn't finish yet, so no screenshot yet) Not sure why that OS has less RAM than the others, presumably we just can't assert the total size then :-(

Repushed, also with skipping the new test on -distropkg.

**Comment by martinpitt** [comment]
[This](https://209.132.184.41:8493/logs/pull-13297-20191216-124545-cef19b8f-cockpit-project-cockpit--fedora-coreos/log.html#261-2) is a race condition. Fix pushed.

**Comment by martinpitt** [comment]
The new test now succeeded everywhere.

**Pull request merged**
