### PR TITLE
image-prepare: symlink only when image complete

### LINKED ISSUE #12781: `image-prepare` should use a tmpfile and rename it when done
Right now, `image-prepare fedora-30` will create `test/images/fedora-30.qcow2` straight away and link it into place.  That means that if the process is interrupted, you end up with a `fedora-30` link in the `test/images` directory, and the tests will try to run against that.

We should use a tempfile instead and rename it into place only when everything has run to the end successfully.

Alternatively: we could put `fedora-30.qcow2` in place, but not symlink it until the end.

### PR DESCRIPTION
**Pull request by smwltr**
Fixes #12781

I am not 100% sure this is the best improvement. I felt like rewriting much of it, but as I don't yet know all the ways in which the tests images can be used, this is probably the least intrusive and does what #12781 requests: creates the symlink to the image file only after building it has been completed.

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Thanks! I had probably moved it to the end with `if completed:`, instead of calling it twice. But that's total bikeshedding, and we can do that if we touch the code again. Thank you!

**Comment by martinpitt** [comment]
Whoops, this caused a regression, see https://github.com/cockpit-project/bots/pull/2114 . I'll send a PR.

**Comment by smwltr** [comment]
On 6/15/21 12:59 PM, Martin Pitt wrote:
> Whoops, this caused a regression, see cockpit-project/bots#2114 
> <https://github.com/cockpit-project/bots/pull/2114> . I'll send a PR.
> 

Ah, ya. I see the problem. I'll have another go at it.

**Comment by smwltr** [comment]
On 6/15/21 12:59 PM, Martin Pitt wrote:
> Whoops, this caused a regression, see cockpit-project/bots#2114 
> <https://github.com/cockpit-project/bots/pull/2114> . I'll send a PR.

I see your change with the new finalize_image function. So please 
disregard my last comment. Thanks!

**Pull request merged**
