### PR TITLE
Implement a better switch control

### PR DESCRIPTION
**Pull request by stefwalter**
Based on bootstrap radio buttons.
    
 * Fix styling
 * Clicking on a selected side should not unselect
 * No extra javascript involved in display, only to retrieve/change values.

### CODE REVIEW

**Comment by stefwalter** [comment]
Example here: 

screenshot from 2015-09-24 14-00-07

**Comment by andreasn** [comment]
Looks good! I'll try it out in action

**Comment by stefwalter** [comment]
This needs a fix for the disabled state.

**Comment by stefwalter** [comment]
screenshot from 2015-09-25 15-23-49

Added disabled mode, and lots of other fixes for the code.

**Comment by stefwalter** [comment]
@rhamilto FYI

**Comment by stefwalter** [comment]
The test failure is #2841, rebasing on that to pass tests.

**Pull request closed without merging**
