### PR TITLE
pcp: More robust and complete archive finding

### PR DESCRIPTION
**Pull request by mvollmer**
Updated description: This ignores broken archives and is able to find and read compressed archives.

### CODE REVIEW

**Comment by mvollmer** [comment]
Oho, pcp itself can open directories full of archives, and even handle compressed archives in there, so we should drop our naive code in favor of letting pcp do it.

**Comment by mvollmer** [comment]
> Oho, pcp itself can open directories full of archives, and even handle compressed archives in there, so we should drop our naive code in favor of letting pcp do it.

PCP also aborts when finding a single broken archive, so that wouldn't improve robustness.  Also, I couldn't get this to work immediately in a trivial test with clean archives, so let's keep our current explicit archive finding code.

However, simply by looking for *.index instead of *.meta we can find and read compressed archives.  Hurray!

**Comment by marusak** [comment]
The code make sense. Seems to work and also pcp team acked that it is correct change. Thanks!

Do we test it? Or can we test it? Test could be just touching empty file in the given directory and checking that it still works.

Also semaphore is suspiciously red - I've retried it and it is still red. Can this be related? Or Is this old branch? (there has been some change that required all branches to rebase so sempahore worked)

**Comment by mvollmer** [comment]
> Do we test it? Or can we test it?

We test archives in `src/bridge/test-pcp.c` and indeed we can add a broken one and expect it to be ignored.  Also, we can compress one of them.

**Comment by mvollmer** [comment]
> Also semaphore is suspiciously red

Yes, valgrind found a memory leak...

```
==29241== 101 (16 direct, 85 indirect) bytes in 1 blocks are definitely lost in loss record 461 of 518
==29241==    at 0x10083874F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==29241==    by 0x100ACB4E0: g_malloc (gmem.c:99)
==29241==    by 0x100AE3582: g_slice_alloc (gslice.c:1024)
==29241==    by 0x100AAF3EC: g_error_new_valist (gerror.c:412)
==29241==    by 0x100AAF7CA: g_set_error (gerror.c:586)
==29241==    by 0x100AAEBEA: g_dir_open (gdir.c:153)
==29241==    by 0x111224: prepare_archives (cockpitpcpmetrics.c:732)
==29241==    by 0x111224: cockpit_pcp_metrics_prepare (cockpitpcpmetrics.c:1003)
==29241==    by 0x10EA2F: setup_metrics_channel_json (test-pcp-archives.c:139)
==29241==    by 0x10EDC2: test_metrics_single_archive (test-pcp-archives.c:238)
==29241==    by 0x100AED39D: test_case_run (gtestutils.c:2597)
==29241==    by 0x100AED39D: g_test_run_suite_internal (gtestutils.c:2685)
==29241==    by 0x100AED143: g_test_run_suite_internal (gtestutils.c:2697)
==29241==    by 0x100AED861: g_test_run_suite (gtestutils.c:2772)
==29241==    by 0x100AED880: g_test_run (gtestutils.c:2007)
==29241==    by 0x10E475: main (test-pcp-archives.c:383)
==29241== 
```

Nice!

**Pull request merged**
