### PR TITLE
Split testHidden into two tests

### PR DESCRIPTION
**Pull request by stefwalter**
These race with and affect each other.

### CODE REVIEW

**Comment by dperpeet** [comment]
For all the new tests we agreed to have one test per file, unless they're very interdependent. This is for future changes and to support parallelization. I think you should move one of the tests to its own file.

**Comment by stefwalter** [comment]
Was this decision documented anywhere? Perhaps in meeting notes?

The very fact that we use ```parallel``` to accomplish parallelization is pretty buggy, when we should be using a custom unittest test runner.

**Comment by dperpeet** [comment]
I don't think it was in a recorded meeting. Our goal is to have a better runner - e.g. running our tests with avocado. Perhaps this is a good topic for an irc meeting. Since the tests themselves are fine, I think this pull request is good to go. Refactoring can happen once we've agreed on a policy in writing.

**Comment by stefwalter** [comment]
Interesting. Good point that avocado would prefer to run tests as individual scripts.

**Pull request closed without merging**
