### PR TITLE
bots: Install packaged node on rhel-x

### PR DESCRIPTION
**Pull request by martinpitt**
node.js is packaged on rhel-x, so skip the brittle manual download and
use that. This will get node.js 10, which is an LTS version.

 * [x] image-refresh rhel-x
 * [x] fix welder-web to get  along with node 10: https://github.com/weldr/welder-web/pull/393

### CODE REVIEW

**Comment by martinpitt** [comment]
@henrywang: FYI

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-tk8mq.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-10484-20181031-085151/

**Comment by cockpituous** [comment]
image-refresh rhel-x done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-x-20181031-091313

**Comment by martinpitt** [comment]
Ugh, looks like known issue #9970 got unfixed

**Comment by martinpitt** [comment]
I reopened the downstream bug and known issue, and pushed the naughty override.

**Comment by martinpitt** [comment]
@mvollmer: The "cockpit/rhel-atomic" test is bogus (that's an occasional glitch in tests-trigger, when it omits the external project name). The other tests are green.

**Comment by martinpitt** [comment]
The two welder-web fedora 29 failures are new, we recently enabled fedora-29 testing and that's not working yet.

**Comment by henrywang** [comment]
@martinpitt, sent PR [#396](https://github.com/weldr/welder-web/pull/396) to address this issue.

**Pull request merged**
