### PR TITLE
base1: Build with webpack

### PR DESCRIPTION
**Pull request by martinpitt**
This avoids replicating a good chunk of what webpack does in the
Makefiles, and more cleanly separates the "web"y bits from the C engine.

The main difficulty is how to build the legacy
cockpit.css/patternfly.css. Webpack rules only consider *.js files, so
include cockpit/patternfly.scss sources into cockpit.js so that they go
through the already existing patternfly-cockpit.scss rule. Once we drop
that for good (Fedora 34/RHEL 9) we can drop this again. Thanks to
Katerina Koukiou for this solution!

patternfly.css is very similar to cockpit.css, it just doesn't have the
CSS for page/listing. As patternfly.css is deprecated anyway, and the
extra rules don't hurt, just treat both files as identical from now on,
and just create a patternfly.css symlink for the OS releases where we
still want it.

base1/qunit-template.html worked slightly differently than
lib/qunit-template.html (mostly due to how imports work), so adjust the
qunit tests accordingly.

### CODE REVIEW

**Comment by martinpitt** [comment]
I found some more obsolete stuff. Yay more removals!

**Comment by martinpitt** [comment]
Found some copy&paste pilot error in pkg/base1/test-locale.js , cleaned that up.

**Review by KKoukiou — APPROVED** [review]
The cockpit.js now includes some CSS files, but it's just that imports that are present, not the actual CSS code. it's a bit confusing to be honest, but this is a really nice cleanup, so I am happy with the trade off.

**Comment by martinpitt** [comment]
@KKoukiou : Is this visible anywhere in the final product or could get in the way? If it's "bleeding through" the product, I'd rather find another solution. Also, I'm looking forward to the day when we can drop this completely!

**Comment by martinpitt** [comment]
@KKoukiou : You wanted some webpack size comparison AFAIR. Unfortuantely webpack builds are not reproducible, so a `diff -Nur` between the two dist/ directories is completely useless.

I built current master in cockpit/ and this branch in base1-webpack/, and the only non-noise difference is dist/base1/:

```
❱❱❱ diff -u <(cd cockpit; du -sc dist/*) <(cd base1-webpack; du -sc dist/*)
--- /dev/fd/63	2020-11-25 06:38:29.702895567 +0100
+++ /dev/fd/62	2020-11-25 06:38:29.703895529 +0100
@@ -1,22 +1,22 @@
 20496	dist/apps
-3488	dist/base1
+26188	dist/base1
 5388	dist/dashboard
 748	dist/guide
-21156	dist/kdump
+21160	dist/kdump
 38600	dist/machines
 21276	dist/metrics
-39868	dist/networkmanager
-23824	dist/packagekit
+39872	dist/networkmanager
+23828	dist/packagekit
 8	dist/pcp
-61228	dist/playground
+61236	dist/playground
 4	dist/README.md
 23072	dist/selinux
-23140	dist/shell
+23144	dist/shell
 2740	dist/sosreport
 8	dist/ssh
 1760	dist/static
-28480	dist/storaged
-90732	dist/systemd
+28488	dist/storaged
+90744	dist/systemd
 19120	dist/tuned
 20588	dist/users
-445724	total
+468468	total
```

Of these, cockpit.{js,css} get a little smaller:
```
-148	dist/base1/cockpit.js
+136	dist/base1/cockpit.js

-1168	dist/base1/cockpit.min.css
+1132	dist/base1/cockpit.css
```
The main difference is that dist/base1/test-*.map files now exist with webpack, we didn't build them with Makefiles. Admittedly they are fairly useless, but we don't ship them in rpms/debs, and they also don't really hurt. The test-*.js files themselves also get bigger as they now get webpack'ed, and qunit gets bundled into each of them. That was also a deliberate change.

**Pull request merged**
