### PR TITLE
Robustify machines tests

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by marusak** [comment]
:heart: You took it seriously with those tests! Thank you :)

**Review by marusak — CHANGES_REQUESTED** [review]
all unit tests failed on code style :/

**Comment by KKoukiou** [comment]
Need more work - tests are failing now really - looking into that.

**Review by marusak — CHANGES_REQUESTED** [review]
It seems it helped with flakes but now there are  3 tests that fail constantly:
`TestMachines.testAddDiskNFS`, `TestMachines.testAddDiskPool` and `TestMachines.testAddDiskSCSI`.
[debian-stable](https://logs.cockpit-project.org/logs/pull-14778-20201021-071902-5a868d65-debian-stable/log.html#269)
[debian-testing](https://logs.cockpit-project.org/logs/pull-14778-20201021-071902-5a868d65-debian-testing/log.html)
[ubuntu-stable](https://logs.cockpit-project.org/logs/pull-14778-20201021-071902-5a868d65-ubuntu-stable/log.html)
[fedora-33](https://logs.cockpit-project.org/logs/pull-14778-20201021-071902-5a868d65-fedora-33/log.html)

**Comment by KKoukiou** [comment]
> It seems it helped with flakes but now there are 3 tests that fail constantly:
> `TestMachines.testAddDiskNFS`, `TestMachines.testAddDiskPool` and `TestMachines.testAddDiskSCSI`.
> [debian-stable](https://logs.cockpit-project.org/logs/pull-14778-20201021-071902-5a868d65-debian-stable/log.html#269)
> [debian-testing](https://logs.cockpit-project.org/logs/pull-14778-20201021-071902-5a868d65-debian-testing/log.html)
> [ubuntu-stable](https://logs.cockpit-project.org/logs/pull-14778-20201021-071902-5a868d65-ubuntu-stable/log.html)
> [fedora-33](https://logs.cockpit-project.org/logs/pull-14778-20201021-071902-5a868d65-fedora-33/log.html)

It's because of Simons PR which got merged, touched the same tests, changing 'running' to 'Running' which my PR reverted back and now it's failing. Easy one - reposting

**Comment by marusak** [comment]
> Easy one - reposting

Nice, thanks!
I don't see commit with 'Closes' :/ But if green, I guess we can omit it?

**Comment by KKoukiou** [comment]
> > Easy one - reposting
> 
> Nice, thanks!
> I don't see commit with 'Closes' :/ But if green, I guess we can omit it?

Sure. There has not been so much discussion in this PR anyway, in a way that it can be useful for the future. Hopefully it will get green enough now :)

**Comment by KKoukiou** [comment]
@marusak Conflicting now and there is testAddDiskSCSI which is still flaky, thus I will need to repost anyway - and will add 'Closes'. sorry :( I will not send any more PRs to machines page till everything we have is merged.

**Comment by KKoukiou** [comment]
I reposted with one more fix - because unfortunately  we broke one more test with:

commit c1b1e83ea812b3b3e56605de15d1d4cdf82279d2
Author: Katerina Koukiou <kkoukiou@redhat.com>
Date:   Wed Oct 21 11:01:17 2020 +0200

    machines: Replace PF4 Cards and other components with PF4 equivalent

**Review by marusak — APPROVED** [review]
Thanks!

**Pull request merged**
