### PR TITLE
Image refresh for fedora-26

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-26
 * [x] image-refresh fedora-26

### CODE REVIEW

**Comment by stefwalter** [comment]
@martinpitt Did your patch to glib-networking make it into fedora-26? Something strange happened here with the client certificate test:

```
# testReconnectChangeCert (check_openshift.TestOpenshift)
#
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 23: warning: setlocale: LC_MESSAGES: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 26: warning: setlocale: LC_NUMERIC: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 29: warning: setlocale: LC_TIME: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 23: warning: setlocale: LC_MESSAGES: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 26: warning: setlocale: LC_NUMERIC: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 29: warning: setlocale: LC_TIME: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 23: warning: setlocale: LC_MESSAGES: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 26: warning: setlocale: LC_NUMERIC: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 29: warning: setlocale: LC_TIME: cannot change locale (en_US.UTF-8): No such file or directory
The connection to the server 10.111.112.101:8443 was refused - did you specify the right host or port?
The connection to the server 10.111.112.101:8443 was refused - did you specify the right host or port?
No resources found.
Traceback (most recent call last):
  File "/build/cockpit/bots/image-naughty", line 241, in <module>
    sys.exit(main())
  File "/build/cockpit/bots/image-naughty", line 53, in main
    post_github(api, number, trace, opts.image)
  File "/build/cockpit/bots/image-naughty", line 238, in post_github
    update_known_issue(api, number, trace, link, context)
  File "/build/cockpit/bots/image-naughty", line 194, in update_known_issue
    return api.patch("issues/comments/{0}".format(comment['id']), { "body": body })
  File "/build/cockpit/bots/task/github.py", line 244, in patch
    response = self.request("PATCH", resource, json.dumps(data), { "Content-Type": "application/json" })
  File "/build/cockpit/bots/task/github.py", line 183, in request
    self.conn.request(method, self.qualify(resource), data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 858, in send
    self.sock.sendall(data)
  File "/usr/lib64/python2.7/ssl.py", line 753, in sendall
    v = self.send(data[count:])
  File "/usr/lib64/python2.7/ssl.py", line 719, in send
    v = self._sslobj.write(data)
socket.error: [Errno 32] Broken pipe
not ok 58 testReconnectChangeCert (check_openshift.TestOpenshift) duration: 210s
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-openshift", line 379, in testReconnectChangeCert
    b.wait_present("#service-list")
  File "/build/cockpit/test/common/testlib.py", line 225, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 219, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 777, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 803, in _invoke
    raise Error(res['error'])
Error: timeout

Wrote TestOpenshift-testReconnectChangeCert-FAIL.png
Wrote TestOpenshift-testReconnectChangeCert-FAIL.html
Journal extracted to TestOpenshift-testReconnectChangeCert-10.111.125.237-FAIL.log
Journal extracted to TestOpenshift-testReconnectChangeCert-10.111.112.101-FAIL.log
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 20: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 23: warning: setlocale: LC_MESSAGES: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 26: warning: setlocale: LC_NUMERIC: cannot change locale (en_US.UTF-8): No such file or directory
/etc/profile.d/lang.sh: line 29: warning: setlocale: LC_TIME: cannot change locale (en_US.UTF-8): No such file or directory

```

**Comment by martinpitt** [comment]
@stefwalter : No, the patch still hasn't been applied upstream. The trace seems to match the [naughty override](https://github.com/cockpit-project/cockpit/blob/master/bots/naughty/fedora-26/6359-glib-networking-change-cert) exactly, hmm..

**Comment by stefwalter** [comment]
Oh this is just GitHub being flakey.

**Comment by stefwalter** [comment]
Filed #7230

**Pull request merged**
