### PR TITLE
Enable several lorax checks

### PR DESCRIPTION
**Pull request by atodorov**
All of the pieces on the lorax side have been merged so enabling these now.

### CODE REVIEW

**Comment by martinpitt** [comment]
Triggering fedora-30/tar@weldr/lorax to verify. The [live-iso](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-12768-20190911-112525-731a0f8d-weldr-lorax--fedora-30-live-iso/log), [aws](https://209.132.184.41:8493/logs/pull-12768-20190911-112525-731a0f8d-weldr-lorax--fedora-30-aws/log), and [vmware](https://209.132.184.41:8493/logs/pull-12768-20190911-112525-731a0f8d-weldr-lorax--fedora-30-vmware/log) tests all failed, is that expected? (even though it's unrelated to this PR).

**Comment by martinpitt** [comment]
The [tar test failed](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-12768-20190911-153636-731a0f8d-weldr-lorax--fedora-30-tar/log) with
```
AttributeError: type object 'TestCloud' has no attribute 'test_tar'
```

So this needs more work in test/run in lorax first?

**Comment by atodorov** [comment]
@martinpitt this should be ready for review. The failing pieced on lorax side have been resolved. So if you restart all the @weldr/lorax test scenarios they should now pass.

**Comment by marusak** [comment]
Martin is today out of office, so I triggered all these scenarios. Lets see :)

**Comment by marusak** [comment]
One failed test - [rhel-8-1/openstack](https://209.132.184.41:8493/logs/pull-12768-20190916-115454-5b7a72fb-weldr-lorax-rhel8-branch-rhel-8-1-openstack/log) in rhel8 branch. I'll spin it out once more

**Comment by atodorov** [comment]
> One failed test - [rhel-8-1/openstack](https://209.132.184.41:8493/logs/pull-12768-20190916-115454-5b7a72fb-weldr-lorax-rhel8-branch-rhel-8-1-openstack/log) in rhel8 branch. I'll spin it out once more

Internal Server Error, duh. From what I can see there is enough free capacity.

**Comment by marusak** [comment]
> Internal Server Error, duh. From what I can see there is enough free capacity.

Does it connect to outside world?

**Pull request merged**
