### PR TITLE
tests: update selector to match grafana from the new services image

### PR DESCRIPTION
**Pull request by KKoukiou**
To be landed in lockstep with https://github.com/cockpit-project/bots/pull/4542

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Epharisto!

**Comment by martinpitt** [comment]
Hmm, I think these tests are stuck.

**Comment by martinpitt** [comment]
.. I restarted them

**Comment by martinpitt** [comment]
Sorry, Grafana tests still fail

**Review by martinpitt — DISMISSED** [review]
Assuming green

**Comment by KKoukiou** [comment]
The single 'stratis' failing test on fedora - is because I merged the fedora-37 image refresh, but the bots PR 4542 is not rebased on top of the fedora-37 image refresh. Please ignore.

**Pull request merged**
