### PR TITLE
Check for NPM dependency updates: angular-route

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update angular-route

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```webpack.config.js:    "angular-route": "angular-route/angular-route.js",
```

**Comment by cockpituous** [comment]
npm-update in progress on cockpit-tests-nhbgs.
Log: http://fedorapeople.org/groups/cockpit/logs/npm-update-7311-20170718-063131/

**Comment by cockpituous** [comment]
npm-update d3 done: https://github.com/cockpituous/cockpit/commits/npm-update-d3-20170718-063131

**Comment by cockpituous** [comment]
Task threw an exception: http://fedorapeople.org/groups/cockpit/logs/npm-update-7311-20170718-063131/

**Comment by stefwalter** [comment]
Checked kubernetes interface for angular working.

**Pull request merged**
