### PR TITLE
networking: Fix interface renaming

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by stefwalter** [comment]
Seems like a related failiure:

```
# testNoConnectionSettings (check_networking.TestNetworking)
#
52:54:00:12:34:56 -> eth1
52:54:00:12:34:56 -> eth1
Error: -- - no such connection profile.
Wrote TestNetworking-testNoConnectionSettings-FAIL.png
Journal extracted to TestNetworking-testNoConnectionSettings-10.111.127.228-FAIL.log
not ok 90 testNoConnectionSettings (check_networking.TestNetworking) duration: 20s
Traceback (most recent call last):
  File "./verify/check-networking", line 547, in testNoConnectionSettings
    self.assertEqual(m.execute('nmcli -m tabular -t -f ipv4.method con show "%s"' % con_id).strip(),
  File "/build/cockpit/test/common/testvm.py", line 412, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
CalledProcessError: Command 'nmcli -m tabular -t -f ipv4.method con show "--"' returned non-zero exit status 10
```

**Comment by stefwalter** [comment]
Another related failure:

```
# testBond (check_networking.TestNetworking)
#
52:54:00:12:34:56 -> ens6
52:54:00:12:34:56 -> ens6
52:54:00:12:34:57 -> ens7
52:54:00:12:34:57 -> ens7
Page error: TypeError: null is not an object (evaluating 't.dev.disconnect')
http://10.111.112.92:9090/cockpit/$91aa60c9e824cc6e49a1277f629d5471708a659b/network/network.js 1368 e
http://10.111.112.92:9090/cockpit/$91aa60c9e824cc6e49a1277f629d5471708a659b/network/network.js 824 
http://10.111.112.92:9090/cockpit/$91aa60c9e824cc6e49a1277f629d5471708a659b/base1/jquery.js 1670 f
http://10.111.112.92:9090/cockpit/$91aa60c9e824cc6e49a1277f629d5471708a659b/base1/jquery.js 1763 fireWith
http://10.111.112.92:9090/cockpit/$91aa60c9e824cc6e49a1277f629d5471708a659b/base1/jquery.js 1819 
http://10.111.112.92:9090/cockpit/$91aa60c9e824cc6e49a1277f629d5471708a659b/network/network.js 678 
http://10.111.112.92:9090/cockpit/$91aa60c9e824cc6e49a1277f629d5471708a659b/base1/jquery.js 1670 f
http://10.111.112.92:9090/cockpit/$91aa60c9e824cc6e49a1277f629d5471708a659b/base1/jquery.js 1763 fireWith
http://10.111.112.92:9090/cockpit/$91aa60c9e824cc6e49a1277f629d5471708a659b/base1/jquery.js 1819 
http://10.111.112.92:9090/cockpit/$91aa60c9e824cc6e49a1277f629d5471708a659b/network/network.js 115 
http://10.111.112.92:9090/cockpit/$91aa60c9e824cc6e49a1277f629d5471708a659b/base1/cockpit.js 876 P
http://10.111.112.92:9090/cockpit/$91aa60c9e824cc6e49a1277f629d5471708a659b/base1/cockpit.js 888 
http://10.111.112.92:9090/cockpit/$91aa60c9e824cc6e49a1277f629d5471708a659b/base1/cockpit.js 805 x
Wrote TestNetworking-testBond-FAIL.png
Journal extracted to TestNetworking-testBond-10.111.112.92-FAIL.log
not ok 22 testBond (check_networking.TestNetworking) duration: 158s
Traceback (most recent call last):
  File "./verify/check-networking", line 248, in testBond
    b.reload()
  File "/build/cockpit/test/common/testlib.py", line 126, in reload
    self.phantom.reload()
  File "/build/cockpit/test/common/testlib.py", line 721, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 744, in _invoke
    raise Error(res['error'])
Error: TypeError: null is not an object (evaluating 't.dev.disconnect')
```

**Comment by stefwalter** [comment]
Related:

```
# testTeam (check_networking.TestNetworking)
#
52:54:00:12:34:56 -> ens6
52:54:00:12:34:56 -> ens6
52:54:00:12:34:57 -> ens7
52:54:00:12:34:57 -> ens7
Wrote TestNetworking-testTeam-FAIL.png
Journal extracted to TestNetworking-testTeam-10.111.112.98-FAIL.log
not ok 31 testTeam (check_networking.TestNetworking) duration: 164s
Traceback (most recent call last):
  File "./verify/check-networking", line 322, in testTeam
    b.wait_present("#network-interface-slaves tr[data-interface='%s']" % iface1)
  File "/build/cockpit/test/common/testlib.py", line 220, in wait_present
    return self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit/test/common/testlib.py", line 214, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 721, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 744, in _invoke
    raise Error(res['error'])
Error: timeout
```

**Comment by mvollmer** [comment]
> # testNoConnectionSettings (check_networking.TestNetworking)

This fails reliably on debian-8 now.  Probably not related to this exact change, though.

**Comment by mvollmer** [comment]
> This fails reliably on debian-8 now. Probably not related to this exact change, though.

It was related.  The automatically generated connections settings have no interface-name, and this code here would treat each new setting as a rename, which wouldn't work.

**Pull request closed without merging**
