### PR TITLE
Remove moment.js from the base package

### PR DESCRIPTION
**Pull request by stefwalter**
We're working on stabilizing the API, and this isn't part of it. Future work will fix up the bundling into the single page applications.

### CODE REVIEW

**Comment by petervo** [comment]
Shouldn't the moment.js files still be links to the file in bower_components?

**Comment by stefwalter** [comment]
Whoops.

**Comment by stefwalter** [comment]
Fixed symlinks.

**Comment by stefwalter** [comment]
```
# testImages (check_openshift.TestRegistry)
#
The connection to the server 10.111.112.101:8443 was refused - did you specify the right host or port?
The connection to the server 10.111.112.101:8443 was refused - did you specify the right host or port?
The connection to the server 10.111.112.101:8443 was refused - did you specify the right host or port?
The connection to the server 10.111.112.101:8443 was refused - did you specify the right host or port?
The connection to the server 10.111.112.101:8443 was refused - did you specify the right host or port?
> WARNING: Tried to load angular more than once.
Page error: Error: Can't find variable: moment
http://10.111.126.243:9090/cockpit/$dbd5a22782f13af04891dc2e0f22fc0d59a1de77/kubernetes/registry.js:34:144
o@http://10.111.126.243:9090/cockpit/$dbd5a22782f13af04891dc2e0f22fc0d59a1de77/base1/angular.js:3:11021
```

**Comment by stefwalter** [comment]
The failures may have been caused by #4454. Lets see.

**Comment by stefwalter** [comment]
Rebased.

**Pull request closed without merging**
