### PR TITLE
test: Remove HACK for known issue #5529

### LINKED ISSUE #5529: NetworkManager resets connection settings to defaults during checkpoint rollback
https://bugzilla.redhat.com/show_bug.cgi?id=1400540

### PR DESCRIPTION
**Pull request by mvollmer**
Fixes #5529

### CODE REVIEW

**Comment by martinpitt** [comment]
Looks like RHEL/CentOS 7 are still affected, so perhaps conditionalize the hack to these images?

**Comment by martinpitt** [comment]
Pushed a fix. @mvollmer, want to cross-check?

**Comment by martinpitt** [comment]
@mvollmer: This failed/flaked on fedora-29: https://209.132.184.41:8493/logs/pull-11290-20190313-081515-c7c04bc5-verify-fedora-29/log.html#266

**Comment by mvollmer** [comment]
The failure on fedora-29 is due to https://bugzilla.redhat.com/show_bug.cgi?id=1690389, I have put a workaround in.  (A workaround is appropriate here since the bug affects the test setup, not the actual behavior of Cockpit.)

Maybe that bug was also the reason for the failures on Centos 7 and RHEL 7.

**Comment by mvollmer** [comment]
> Maybe that bug was also the reason for the failures on Centos 7 and RHEL 7.

Looks like it, all green now.

Interestingly, rhel-8-0 was always green, also without the old hack and without the new hack.  I'll take a quick look.

**Comment by mvollmer** [comment]
> Interestingly, rhel-8-0 was always green,

This happened because rhel-8-0 uses dhcp=internal by default, which breaks our method of slowing down the checkpoint rollback by hacking /usr/sbin/dhclient. Thus, we didn't need the longer dhcp_timeout on rhel-8-0 for the test to pass.  But neither did it test whether cockpit switches off its global health check correctly.

The new bug 1690389 is also present in rhel-8-0.

But even with a wrong timeout of 45 seconds, the test still passes.  NetworkManager 1.16 in rhel-8-0 seems to have a 480 seconds "grace period" for dhcp, which has the same effect as increasing the timeout...

**Comment by mvollmer** [comment]
> NetworkManager 1.16 in rhel-8-0 seems to have a 480 seconds "grace period" for dhcp, which has the same effect as increasing the timeout...

The grace period is nothing new; it happens or not according to some internal NM logic.  The thing that triggers it for me when checking rhel-8-0 is a new "systemctl restart NetworkManager" at the top of the test.  With that "restart", the grace period also happens on fedora-29.

The "restart" is necessary to get NM to accept the new "dhcp=dhclient" config setting.

Soooo.  I think we shouldn't rely on the grace period happening and should still increase the dhcp timeout.  I am afraid that a "restart" of NM will lead to flakes.  NM sometimes doesn't pick up its config correctly and fails to associate devices with connections.

So, I think I'll move all the dhcp=dhclient stuff to a new PR, and only do it for the one test where we need it.

**Comment by mvollmer** [comment]
> I am afraid that a "restart" of NM will lead to flakes.

Seems like the current tests on https://github.com/cockpit-project/cockpit/commits/92017501116d8e2810e3f89902c301b13c7377e5 already show some NM flakes.

**Comment by mvollmer** [comment]
> Okay like that, but I figure over time we want to conditionalize the new hack on some operating systems only? Do you already want to do this right now and e. g. exclude rhel-8-0?

With #11435, the explicit HACK here is replaced with a restart of NM. We might consider making the restart in #11435 conditioned on the image since only rhel-8-0 actually requires it right now.

**Pull request merged**
