### PR TITLE
bridge: Send SIGHUP to spawned daemons if cockpit-bridge dies

### PR DESCRIPTION
**Pull request by stefwalter**
This prevents leaking various ssh-agent processes. A symptom of this
was mock complaining about processes running in the chroot.

Symptom:

WARNING: Process ID 17028 still running in chroot. Killing...

### CODE REVIEW

**Comment by mvollmer** [comment]
There is a new journal message: `dbus-daemon didn't send us a dbus address`.  Could this be related?

**Comment by stefwalter** [comment]
Yup, very likely. I'll fix it so we just deal with the ssh-agent specifically.

**Comment by stefwalter** [comment]
Fixed and Rebased.

**Comment by stefwalter** [comment]
This has known issues: http://files.cockpit-project.org/logs/pull-3068-0c94ef09-fedora-23-x86_64/log

**Pull request closed without merging**
