### PR TITLE
po: Extract HTML trantslations properly

### PR DESCRIPTION
**Pull request by stefwalter**
This now supports most angular-gettext extractions. We support extracting title translations, as well as prefering the newer form HTML translate attributes.
    
This implements support in cockpit.translate().
    
The playground translate page has been updated to clearly denote what forms of translate syntax are supported and where.
    
The tests have been updated both unit tests and integration test.

Depends on:

* [x] #5326

### CODE REVIEW

**Comment by stefwalter** [comment]
Rebased

**Comment by stefwalter** [comment]
Rebased.

**Comment by stefwalter** [comment]
Fixed missing translation of word we're testing, that was lost during the rebase.

**Comment by mvollmer** [comment]
Needs a rebase.

**Comment by petervo** [comment]
Closing in favor of #5420. It's hard to validate this without the ostree and translation commits and these commits are already there

**Pull request closed without merging**
