### PR TITLE
systemd: Show /etc/motd

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
Needs a test.

**Comment by mvollmer** [comment]
@andreasn, check this out.  Put some text into /etc/motd and open "System" in Cockpit.

**Comment by andreasn** [comment]
Thanks for getting this together. I'll test it out ASAP!

**Comment by andreasn** [comment]
This is really good!

How long are these messages supposed to be, normally?
It behaves a bit weird if it's a long message.
screenshot from 2017-02-28 17-21-25

**Comment by martinpitt** [comment]
@andreasn : motd is being shown verbatim for console and ssh logins, so normally the lines shoudn't be too wide (max 80 chars). However, it usually *is* multiple lines. So IMHO we don't need to be concerned about wide motd, but ~ 10 lines should look nice.

**Comment by andreasn** [comment]
Yeah, multiline looks better.
screenshot from 2017-02-28 17-41-38

Are people who are programmers actually enough concerned with the 80 line width "limit" that they would be strict about it?
Something machine-generated, say, Sattellite I believe would be even less strict with the character limit.
I'll see if I can do something with regards to the css.

**Comment by martinpitt** [comment]
It's not really about programmers, motd is more of an "admin or OS wants to notify her users" thing. I wouldn't attempt auto-wrapping the contents, as it often contains ASCII art or other column-aligned things, so displaying it verbatim in a fixed font width is best IMHO. E. g. check fedorapeople.org :-)

Your screenshot link is broken BTW, it just shows a 500 Internal Server Error.

**Comment by stefwalter** [comment]
@garrett Could you try this pull request out? ... you probably need to:

 ```$ printf "Here is my message\nof the day\n" | sudo tee /etc/motd``` 

If I refresh the page after dismissing the message of the day, it comes back. If I log out after dismissing the message of the day ... it comes back.

Should we track which message was dismissed (eg: in ```localStorage```) and then only display it again if it changes?

**Comment by andreasn** [comment]
So if the string will only reach 80+ chars in very extreme cases, what about something like this?

screenshot from 2017-03-01 11-48-49

This was done by adding these lines to #motd
overflow: hidden;
text-overflow: ellipsis;

@garrett what's your thoughts?

**Comment by garrett** [comment]
I suggest:

```css
white-space: pre-wrap;
```

So it has the normal properties of `<pre>`, but wraps long lines if it needs to.

**Comment by andreasn** [comment]
@garrett thanks! Fixed that here:
https://github.com/andreasn/cockpit/tree/motd-wrap

**Comment by mvollmer** [comment]
> https://github.com/andreasn/cockpit/tree/motd-wrap

Added to this PR.

**Comment by mvollmer** [comment]
@andreasn, @garrett, what about Stefs question?

> Should we track which message was dismissed (eg: in localStorage) and then only display it again if it changes?

**Comment by andreasn** [comment]
> Should we track which message was dismissed (eg: in localStorage) and then only display it again if it changes?

Yes, I think this sounds like a good idea.

**Comment by mvollmer** [comment]
> Yes, I think this sounds like a good idea.

Done.

**Comment by petervo** [comment]
Worth adding a test to check-system?

**Comment by mvollmer** [comment]
> Worth adding a test to check-system?

Yes, indeed.

**Comment by mvollmer** [comment]
>> Worth adding a test to check-system?

> Yes, indeed.

Done.

**Pull request closed without merging**
