### PR TITLE
shell: Zooming

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
@andreasn, the icons need consideration, I'd say.  Also, the whole interaction experience needs to be checked carefully.

**Comment by mvollmer** [comment]
> @andreasn, the icons need consideration, I'd say.

And the colors and styling of the zoom box... so, pretty much everything. :-)

**Comment by mvollmer** [comment]
Zooming should be disabled when there are no archives.

**Comment by stefwalter** [comment]
Needs rebase.

**Comment by mvollmer** [comment]
We should limit the zoom range.  Minimum 5 minutes, say.  Something goes wrong when you zoom out a lot.

**Comment by andreasn** [comment]
> We should limit the zoom range. Minimum 5 minutes, say. Something goes wrong when you zoom out a lot.

Sounds like a good idea.

**Comment by andreasn** [comment]
Got it running after we figured out the minified issue! \o/

Will need to play around with this some more, but looks like a good start.

**Comment by andreasn** [comment]
This yellow selection color would work better as blue, similar to what we use for other elements.
screenshot from 2015-02-18 16 16 58

**Comment by andreasn** [comment]
None of the font-icon fonts have any good zoom out icon, so I'll fix up a custom icon

**Comment by andreasn** [comment]
As @mvollmer noted on IRC, it's possible to zoom out to a point where the whole canvas goes blank, so it would be good to have a upper cap, like at a week.
screenshot from 2015-02-19 11 49 06

**Comment by andreasn** [comment]
I'm also having some troubles getting a good sense of what the zoom out parameter is, and I don't think we came to any exact conclusion when we spoke about this in Brno.
I think it would either need to work as a reset of the zoom-in-action you just did, or mapped to one of the predefined time steps. Having a third one makes me lose direction of where I am right now.

**Comment by andreasn** [comment]
Improved icon here https://github.com/andreasn/cockpit/tree/metrics-zoom-icon

**Comment by mvollmer** [comment]
Ok, more IRC discussion with @andreasn has lead to this:

 * Dropdown instead of button group.  "Go to now", separator, "5 minutes", "30 minutes", "1 hour", "6 hours", "1 week"

 * Cursor change on hover of graphs (to be drawn)

 * Dropdown shows some pleasantly rounded version of the current rage

 * Zoom out is undo for zoom in.  If there is no history, zoom out goes to next largest range from dropdown list.  Scrolling (including "go to now") does not change zoom history.  Direct zoom via dropdown item first removes items from the zoom history as appropriate and then adds on zoom-in step.

**Comment by mvollmer** [comment]
> Improved icon here https://github.com/andreasn/cockpit/tree/metrics-zoom-icon

The actual icon is unfortunately missing...

**Comment by mvollmer** [comment]
@andreasn, this is ready for design re-review.

**Comment by andreasn** [comment]
Good progress! This is getting closer!
A couple of small items:
* The time picker is missing a little dropdown arrow.
* The buttons grows and shrinks depending on the content
* 1 month sounds better than one week and "about 1 year" sounds better than 51 weeks, at least for these two preset steps. I can see how it could be hard to calculate though, so might be all right anyway.

**Comment by mvollmer** [comment]
> 1 month sounds better than one week and "about 1 year" sounds better than 51 weeks, at least for these two preset steps. I can see how it could be hard to calculate though, so might be all right anyway.

No, my pseudo-scientific mind just wasn't happy that "one month" and "one year" is not a fixed number of seconds, unlike "one week" (modulo DST and leap seconds, and...).  But it's all approximate anyway, so we can just use 1 month = 30 days and 1 year = 365 days.

**Comment by mvollmer** [comment]
> A couple of small items:

Fixed!

**Comment by andreasn** [comment]
Yay! This works really well now! Thanks for all the hard work!
Final nit is that the label is centered, and we don't do this anywhere else in this kind of control. Apart from that should be good to go!

**Comment by andreasn** [comment]
Fixed the alignment of the dropdown here https://github.com/mvollmer/cockpit/pull/3

**Comment by mvollmer** [comment]
Ready for review.

**Comment by stefwalter** [comment]
I installed this ... I see the cursor <->, and drag on the dashboard graph, but nothing happens. No javascript error either.

**Comment by mvollmer** [comment]
> I installed this ... I see the cursor <->, and drag on the dashboard graph, but nothing happens. No javascript error either.

Hmm, the minimum range is 5 minutes, and if you try to zoom in below that, it will just stay at 5 minutes.  Is that what you see?

Can you zoom out, via the zoom-out button or the menu?

In any case, we should not offer to zoom when we have reached the minimum, that is just confusing.  Good point.

**Comment by andreasn** [comment]
> In any case, we should not offer to zoom when we have reached the minimum, that is just confusing. 

Agreed.

**Comment by mvollmer** [comment]
Continued in #2020.

**Pull request closed without merging**
