### PR TITLE
bots: Refer to next version of RHEL as 'x'

### PR DESCRIPTION
**Pull request by stefwalter**
This is how we can refer to the next version of RHEL, always in development,
without the specific version number.

 - [x] Declare rhel-x image: PR #9367

### CODE REVIEW

**Comment by allisonkarlitskaya** [comment]
Why not -unstable or -prerelease or something more descriptive?

**Comment by stefwalter** [comment]
RHEL uses an X.Y.Z version numbering system. New major versions are 'X' versions.

**Comment by martinpitt** [comment]
This collided with #9329 , sorry.

**Comment by martinpitt** [comment]
I force-pushed a rebase, adjusted the image link to the current version, and made sure that this is on the private store.

**Comment by martinpitt** [comment]
#9367 landed. Rebased, and adjusted the new check-storage-luks tests accordingly.

**Comment by martinpitt** [comment]
Tests are good enough.

**Pull request merged**
