### PR TITLE
firewall: Change order of aattributes to make tests happy

### PR DESCRIPTION
**Pull request by marusak**
One test checks that `<div id="firewall"` exists.
This was introduced in 9113eb5f.

### CODE REVIEW

**Comment by martinpitt** [comment]
Ugh, we landed #15277 without any integration tests, bummer. Not sure if the [edge test](https://logs.cockpit-project.org/logs/pull-15285-20210205-072520-008bd2c4-fedora-32-selenium-edge/log.html#3) is a random flake (it's usually rather stable these days), or related as well. I'll retry.

**Review by KKoukiou — APPROVED** [review]

**Comment by martinpitt** [comment]
That selenium/edge failure is real, I'm afraid.

**Comment by marusak** [comment]
> That selenium/edge failure is real, I'm afraid.

Maybe these new changes to page fill don't play nicely along with edge?

**Comment by martinpitt** [comment]
Plausibly -- edge has the tendency of hiding off-screen elements

**Review by martinpitt — APPROVED** [review]
Anyway, that damage is already in master, and that PR at least fixes one failure. So let's land it anyway (ruining @marusak 's statistics)

**Pull request merged**
