### PR TITLE
Image refresh for fedora-27

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-27
 * [x] image-refresh fedora-27

### CODE REVIEW

**Comment by mvollmer** [comment]
Almost all tests are skipped because of known issue #7636, does that make sense?

**Comment by mvollmer** [comment]
Maybe we should make this a "allowed journal message" if it doesn't lead to actual user visible bugs.

**Comment by martinpitt** [comment]
Well, the tests still actually run and would fail if anything else than the unexpected message would turn up. So they are not "really" skipped, it's just how it's shown in our parsed HTML. So I think it's ok for now.
I prefer known issues/naughty overrides over static lists as the former provide automatic tracking when and where these issues get fixed.

**Comment by mvollmer** [comment]
>  So I think it's ok for now.

Agreed.

**Pull request merged**
