### PR TITLE
Update the topology graph component

### PR DESCRIPTION
**Pull request by stefwalter**
* This prevents various nodes from leaving the view

### CODE REVIEW

**Comment by stefwalter** [comment]
This is known issue #3102 http://files.cockpit-project.org/logs/pull-3007-5a6cf76e-fedora-23-x86_64/log

**Comment by petervo** [comment]
This breaks the topology ReplicationController icon for me.

**Comment by stefwalter** [comment]
> This breaks the topology ReplicationController icon for me.

I don't see this. Perhaps you had an old version of this branch?

**Comment by stefwalter** [comment]
screenshot from 2015-11-03 16-12-21

**Comment by petervo** [comment]
rc

This is what I see

**Pull request closed without merging**
