### PR TITLE
package.json: Update patternfly and redux to current versions

### PR DESCRIPTION
**Pull request by martinpitt**
The upcoming integration of welder-web is going to need never versions
of those.

patternfly changed the path of its variables.less, adjust
pkg/lib/variables.less accordingly.

---
I went through all our pages, Dashboard, and the Openshift view to ensure that the new patternfly doesn't introduce visual oddities. Our CI tests should give us good confidence about the redux bump.

### CODE REVIEW

**Comment by stefwalter** [comment]
@martinpitt For patternfly updates we usually had a designer take a look across Cockpit too? Does that still seem like a good plan?

**Comment by martinpitt** [comment]
You mean like @garrett or @andreasn signing this off? Sure, that does sound like a good idea. Before I bother them I wanted to make sure all the tests pass, though.

**Comment by martinpitt** [comment]
Tests look good. @andreasn, would you have some time to sign this off? I already did a first pass through all the pages, but I figure you have a more trained eye to spot visual oddities.

**Comment by martinpitt** [comment]
Rebased to master to fix the conflict (react-lite was bumped recently).

**Pull request merged**
