### PR TITLE
Image refresh for fedora-30

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for fedora-30
 * [x] image-refresh fedora-30

### CODE REVIEW

**Comment by martinpitt** [comment]
@marusak : No tests got triggered here. According to the history, the branch did get renamed before force-pushing, so this could be some race condition in the GitHub API? Triggering test manually now.

**Comment by martinpitt** [comment]
Logs from webhook:
```
INFO:root:repo: cockpit-project/cockpit; title: WIP: centosci-tasks-lq9xz: [no-test] Image refresh for fedora-30; number: 11541; action: opened
INFO:root:repo: cockpit-project/cockpit; title: Image refresh for fedora-30; number: 11541; action: edited
INFO:root:repo: cockpit-project/cockpit; title: Image refresh for fedora-30; number: 11541; action: labeled
INFO:root:repo: cockpit-project/cockpit; title: Image refresh for fedora-30; number: 11541; action: synchronize
INFO:root:repo: cockpit-project/cockpit; title: Image refresh for fedora-30; number: 11541; action: edited
```

This actually looks perfectly alright, so it rather seems to be another instance of "webhook triggers sometimes get ignored".

**Comment by martinpitt** [comment]
[several failures](https://209.132.184.41:8493/logs/pull-11541-20190408-124141-2b736635-verify-fedora-30/log.html), retrying.

**Comment by martinpitt** [comment]
@mvollmer: We get a lot of failures in [testGrowShrinkHelp](https://209.132.184.41:8493/logs/pull-11541-20190408-134545-2b736635-verify-fedora-30/log.html#244). This also happens on [fedora-29](https://209.132.184.41:8493/logs/pull-11540-20190408-121313-8613be22-verify-fedora-29/log.html#250), it's a rather major flake. Do you have some time to take a look? Thanks!

**Comment by martinpitt** [comment]
[new SELinux violation](https://209.132.184.41:8493/logs/pull-11541-20190408-134545-2b736635-verify-fedora-30/log.html#106) in FIPS test

**Comment by marusak** [comment]
> new SELinux violation in FIPS test

It seems like a flake. I cannot reproduce it locally and also I retried it now and it passed (with one retry).

**Comment by martinpitt** [comment]
Indeed, retry --harder then :-)

**Comment by martinpitt** [comment]
This [SELinux](https://209.132.184.41:8493/logs/pull-11541-20190412-152424-2b736635-verify-fedora-30/log.html#254) violation is also new. Let's please just fix that and the one in FIPS.

**Comment by martinpitt** [comment]
I'll take a closer look on Monday.

FTR, SELinux messages are often easier to reproduce when adding a `sit()` at the end of the test, then ssh'ing in, and waiting a bit longer for the journal to catch up. Or at least report them to bugzilla and naughty them -- they may not appear every time, but are still a bug somewhere.

**Comment by martinpitt** [comment]
It's already reported, and there's a pending fix: https://bugzilla.redhat.com/show_bug.cgi?id=1698200

If that lands fast enough, we can just rebuild the image, otherwise do the naughty dance.

**Comment by martinpitt** [comment]
Bug got fixed, let's let the bots build a new  image.

**Pull request closed without merging**
