### PR TITLE
Image refresh for continuous-atomic

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for continuous-atomic in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-continuous-atomic-2017-01-30/

### CODE REVIEW

**Comment by martinpitt** [comment]
Similarly to PR #5815 this failed several times in a row with the same tests, so not merging for now. Needs further investigation.

**Comment by martinpitt** [comment]
I'm working on PR #5815 and pushed the quirk for continuous-atomic there. Let's re-run this once that lands.

**Comment by martinpitt** [comment]
OK, this needs more work. The `testDevmapper (check_docker_storage.TestDockerStorage)` failure is gone now, but the two others (`testBasic (check_docker.TestAtomicScan))` and `testBasic (check_kdump.TestKdump))` still fail consistently.

**Comment by stefwalter** [comment]
@dperpeet Should we run kdump tests on continuous-atomic image?

**Comment by dperpeet** [comment]
newer image in #5852

**Pull request closed without merging**
