### PR TITLE
machines: add method signatures to all dbus calls

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
@martinpitt I am not sure actually if this change brought some huge improvement, when connecting with admin privileges and polkit as access driver for libvirt, the loading of the page for 10 VMs takes 15seconds on my system.
On the other hand I was never able to reproduce that huge delays mentioned in the BZ description even when I added 15 extra VMs on my system, the loading of the page never hit that time delays.

**Comment by martinpitt** [comment]
@KKoukiou : No problem - we can do a scratch build for RHEL 7 with this and ask the reporter/libvirt QE team to give it a try. Once this lands, could you please backport this to the rhel-7.8 branch? (unless it cleanly applies, then I can just do it myself)

**Comment by martinpitt** [comment]
Still failing tests

**Comment by martinpitt** [comment]
[f31/firefox fails testCreate](https://logs.cockpit-project.org/logs/pull-13642-20200304-100443-de109fbc-fedora-31-firefox/log.html#84-2), retrying that one again.

**Comment by martinpitt** [comment]
So the [testAddDisk failure](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-13642-20200304-111559-de109fbc-fedora-31/log.html#245-2) is my fault, I'll look at this ASAP. But the [testConfigureBeforeInstall failure](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-13642-20200304-111559-de109fbc-fedora-31/log.html#249-2) is quite persistent, even after several retries.

**Pull request merged**
