### PR TITLE
Storage space unit consistency

### LINKED ISSUE #1562: Filesystem, used and total size based on different units
screen shot 2014-12-05 at 12 27 39 pm

See the first line for mount point /boot. The first value is for used, and is based on binary prefix (the number is in mebibytes); the second value is for total, and is based in SI prefix (the number is in megabytes).

Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/sda2         487652  188894    269062  42% /boot
/dev/sda2       477M  185M  263M  42% /boot                     ## -h

I don't care whether cockpit uses binary or SI prefix, but it should pick one, and show the correct unit. The easiest fix right now is for the first (used) size value to be based on SI units, and then the MB and GB don't need to be changed to MiB and GiB, etc.

### PR DESCRIPTION
**Pull request by dperpeet**
fixes #1562

### CODE REVIEW

**Comment by stefwalter** [comment]
@dperpeet Could you set your ```git config --global user.name``` and ```user.email``` and then do a ```git commit --reset-author --amend```?

**Comment by dperpeet** [comment]
this should do it

**Comment by stefwalter** [comment]
Verified:

screenshot from 2015-01-05 14 14 42

```
Filesystem                 Size  Used Avail Use% Mounted on
/dev/sdb1                   39G   23G   15G  61% /
devtmpfs                    16G     0   16G   0% /dev
tmpfs                       16G  416K   16G   1% /dev/shm
tmpfs                       16G  1,1M   16G   1% /run
tmpfs                       16G     0   16G   0% /sys/fs/cgroup
tmpfs                       16G  2,3M   16G   1% /tmp
/dev/mapper/storage-data   345G   24G  303G   8% /data
/dev/mapper/storage-extra 1008G  145G  812G  16% /opt
tmpfs                      3,2G   28K  3,2G   1% /run/user/1000
```

**Comment by stefwalter** [comment]
Rebased squashed

**Comment by stefwalter** [comment]
Merged. Thanks.

**Pull request closed without merging**
