### PR TITLE
test: Clean up fedora-30 special cases

### PR DESCRIPTION
**Pull request by martinpitt**
We stopped releasing to Fedora 30 and supporting that in CI.

### CODE REVIEW

**Comment by marusak** [comment]
Thanks!
In `test/selenium/README.md` we say `Currently, these tests run on Fedora 30.`, which is not true even now. Can you please also update it with this PR as well? Other than then ack from me.

**Comment by martinpitt** [comment]
@marusak: Well spotted, thanks! Updated.

**Comment by martinpitt** [comment]
[This is an interesting failure](https://logs.cockpit-project.org/logs/pull-13733-20200317-111307-46d55973-rhel-8-2/log.html#72):
```
error: Tried changing state of a disconnected RFB object
warning: ERROR    operation failed: domain 'VmNotInstalled' is already being removed
Domain installation does not appear to have been successful.
```
and all subsequent tests then fail because /mnt/libvirt is busy. Clearly unrelated to this PR, but it's similar to a lot of failures that we are seeing right now.

**Comment by marusak** [comment]
Pattern I can see:
1. Some machine test fails it also fails to log out what happened with this traceback:
```
Traceback (most recent call last):
  File "test/verify/check-machines-dbus", line 2235, in <module>
    test_main()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1433, in test_main
    ret = runner.run(suite)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1324, in run
    result = self.runOne(test)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1289, in runOne
    sys.stderr.write(traceback.print_exc())
TypeError: write() argument must be str, not None
```
2. All following machine tests fails with `/mnt/libvirt` existing.

I have at least three examples: [1](https://logs.cockpit-project.org/logs/pull-13739-20200317-163428-7d991af3-fedora-32/log.html#82-2) [2](https://logs.cockpit-project.org/logs/pull-13735-20200317-140956-90073eb7-debian-testing/log.html#82-2) [3](https://logs.cockpit-project.org/logs/pull-13733-20200317-111307-46d55973-rhel-8-2/log.html#74-2)

**Pull request merged**
