### PR TITLE
Make networking page less bootstrap dependent and usable on mobile devices

### PR DESCRIPTION
**Pull request by KKoukiou**
Screen Shot 2020-08-06 at 19 13 46

### CODE REVIEW

**Comment by martinpitt** [comment]
This either needs disabling or adjusting the networking tests for [rhel-8-3-distropkg](https://logs.cockpit-project.org/logs/pull-14454-20200807-143820-97f8c2fe-rhel-8-3-distropkg/log.html)

**Comment by marusak** [comment]
@garrett can you please take a look? I'll adjust tests in the meantime.

**Comment by marusak** [comment]
[8-3-distro](https://logs.cockpit-project.org/logs/pull-14454-20200812-160829-24512ad5-rhel-8-3-distropkg/log.html#304-2) 3 failures in `check-metrics`. This OS seems rather unhappy..

**Comment by garrett** [comment]
Added a bunch of fixes to journal, which was causing the page to overflow. This actually affects the journal, storage, and networking pages. And I've added some mobile support. It needs a few more fixes, but is already a lot better.

Committing now, as it's the end of the workweek and I want to make sure it's here in the PR.

**Comment by KKoukiou** [comment]
I just force pushed, just to squash garretts commits.

**Review by martinpitt — APPROVED** [review]
Brilliant, thank you! This looks/works nicely.

**Pull request merged**
