### PR TITLE
bots: Adjust ubuntu-stable scripts for 18.04

### LINKED ISSUE #9094: Image refresh for ubuntu-stable - fixed in #9130
Image refresh for ubuntu-stable
 * [ ] FAIL: image-refresh ubuntu-stable

### PR DESCRIPTION
**Pull request by martinpitt**
See commit messages for details.

Fixes #9094 

 * [x] image-refresh ubuntu-stable
 * [x] fix `check-storage-lvm2 TestStorage.testLvm`
 * [x] fix broken locale on image

### CODE REVIEW

**Comment by martinpitt** [comment]
ATM I can't build any images locally due to https://bugzilla.redhat.com/show_bug.cgi?id=1575640 . Ideas how to fix/work around this appreciated!

So I'll probably need some iterations to do this on the bots instead.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-5b4w0.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9130-20180508-141717/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9130-20180508-141717/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-wd7g8.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9130-20180508-143535/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9130-20180508-143535/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-s50rl.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9130-20180508-173232/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9130-20180508-173232/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-h3v66.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9130-20180509-064343/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-zz9dv.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9130-20180509-064242/

**Comment by cockpituous** [comment]
Task failed: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9130-20180509-064242/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-f3w2w.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9130-20180509-083232/

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-61s3h.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9130-20180509-083232/

**Comment by cockpituous** [comment]
image-refresh ubuntu-stable done: https://github.com/cockpituous/cockpit/commits/image-refresh-ubuntu-stable-20180509-090707

**Comment by martinpitt** [comment]
The newly enabled lvm2 tests now actually mostly work, except for [one](https://fedorapeople.org/groups/cockpit/logs/pull-9130-20180509-113434-bc6ad287-verify-ubuntu-stable/log.html#168). Investigating.

**Comment by martinpitt** [comment]
Fixed. Letting all tests run now, as this PR changes two tests, so validating on the other OSes.

**Comment by martinpitt** [comment]
Meh, the `testIpa` failure is also real:

    ipa: ERROR: System encoding must be UTF-8, 'ISO-8859-1' is not supported. Set LC_ALL="C.UTF-8", or LC_ALL="" and LC_CTYPE="C.UTF-8".

and indeed:
```
# cat /etc/default/locale 
#  File generated by update-locale
LANG="en_US"
```
This 18.04 virt-builder image is *really* sloppy :-(

**Comment by martinpitt** [comment]
[testIpa](https://fedorapeople.org/groups/cockpit/logs/pull-9130-20180509-131111-279e86f2-verify-ubuntu-stable/log.html#103) fails differently now, looking

**Comment by martinpitt** [comment]
Fixed testIpa; Ubuntu 18.04 now actually does contain the `ipa` command line tool, so the expected failure wasn't failing any more :-)

**Comment by martinpitt** [comment]
ubuntu-stable tests succeeded, and a few other OSes too (to prove that the changes work there). Still fighting unrelated flakes, but I think this is ready for review now.

**Pull request merged**
