### PR TITLE
bots: Retry GPG retrieval on rhel-7-* images

### LINKED ISSUE #11520: Image refresh for rhel-7-6
Image refresh for rhel-7-6
 * [ ] FAIL: image-refresh rhel-7-6

### LINKED ISSUE #11526: Image refresh for rhel-7-7
Image refresh for rhel-7-7
 * [ ] FAIL: image-refresh rhel-7-7

### PR DESCRIPTION
**Pull request by martinpitt**
This often fails with
```
gpg --keyserver pool.sks-keyservers.net --recv-keys 94AE36675C464D64BAFA68DD7434390BDBE9B9C5
gpg: requesting key DBE9B9C5 from hkp server pool.sks-keyservers.net
gpgkeys: key 94AE36675C464D64BAFA68DD7434390BDBE9B9C5 can't be retrieved
gpg: no valid OpenPGP data found.
```

Fixes #11526
Fixes #11520

 * [x] image-refresh rhel-7-6
 * [x] image-refresh rhel-7-7

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-zxjlf.
Log: https://209.132.184.41:8493/logs/image-refresh-11532-20190404-103535/

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-33dpv.
Log: https://209.132.184.41:8493/logs/image-refresh-11532-20190404-103535/

**Comment by cockpituous** [comment]
image-refresh rhel-7-6 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-6-20190404-111111

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-g5tj5.
Log: https://209.132.184.41:8493/logs/image-refresh-11532-20190404-105959/

**Comment by cockpituous** [comment]
image-refresh rhel-7-7 done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-7-7-20190404-113232

**Comment by martinpitt** [comment]
I reported https://bugzilla.redhat.com/show_bug.cgi?id=1697227 and adjusted the naughty pattern.

**Comment by martinpitt** [comment]
@KKoukiou , this is now ready for review. Can you please have a look?

**Pull request merged**
