### PR TITLE
firewall: Fix layout in form to add custom services

### PR DESCRIPTION
**Pull request by Gundersanne**
updated screenshot:
image

### CODE REVIEW

**Comment by marusak** [comment]
I think there was some good reasoning why we should use `fieldset` instead of div. I guess something with accessibility or at least using semantic elements. We use `fieldset` on other places as well, so I would be in favor of keeping it.

**Comment by martinpitt** [comment]
The code change makes sense, but visually I'm not sure what exactly the problem/fix is. Current master looks like

firewall

which is only marginally diffent (right vs. left adjustment of the labels). Could the commit message clarify this a bit, please?

**Comment by marusak** [comment]
> The code change makes sense, but visually I'm not sure what exactly the problem/fix is. Current master looks like

It is only on chrome/ium

**Comment by Gundersanne** [comment]
Completely removing the fieldset works best.

**Comment by martinpitt** [comment]
One [firewall related failure](https://209.132.184.41:8493/logs/pull-11788-20190513-081313-fdc84576-verify-rhel-8-1/log.html#113), triggering round of retries.

**Pull request merged**
