### PR TITLE
Image refresh for fedora-24

### PR DESCRIPTION
**Pull request by cockpituous**
Image creation for fedora-24 in process on cockpit-7.
Log: http://fedorapeople.org/groups/cockpit/logs/refresh-fedora-24-2016-12-09/

### CODE REVIEW

**Comment by stefwalter** [comment]
@mvollmer Could you check that this is either a known issue or its okay to proceed merging this image?

```
# testDosParts (check_storage_msdos.TestStorage)
#
> Using older 'storaged' API: org.storaged.Storaged
Page error: #detail-content tbody:nth-of-type(3) .listing-ct-item :nth-child(2) not found
phantomjs://code/phantom-lib.js 17 ph_only
phantomjs://code/phantom-lib.js 26 ph_find
phantomjs://code/phantom-lib.js 67 ph_text
phantomjs://code/phantom-lib.js 156 ph_in_text
 1 
 1 
Wrote TestStorage-testDosParts-FAIL.png
Journal extracted to TestStorage-testDosParts-10.111.127.57-FAIL.log
not ok 15 testDosParts (check_storage_msdos.TestStorage) duration: 86s
Traceback (most recent call last):
  File "./verify/check-storage-msdos", line 79, in testDosParts
    self.content_row_wait_in_col(3, 1, "xfs File System")
  File "/build/cockpit/test/verify/storagelib.py", line 79, in content_row_wait_in_col
    self.browser.wait_in_text(col, val)
  File "/build/cockpit/test/common/testlib.py", line 247, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit/test/common/testlib.py", line 214, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit/test/common/testlib.py", line 721, in <lambda>
    return lambda *args: self._invoke(name, *args)
  File "/build/cockpit/test/common/testlib.py", line 744, in _invoke
    raise Error(res['error'])
Error: #detail-content tbody:nth-of-type(3) .listing-ct-item :nth-child(2) not found
```

**Comment by mvollmer** [comment]
This looks like https://bugzilla.redhat.com/show_bug.cgi?id=1135493 of yore, but it should have long been fixed in Fedora.  Also I can't reproduce this locally.

**Comment by stefwalter** [comment]
Since Fedora 24 is a 'canary' image ... one to tell us about new regressions or upcoming brokenness ... If you think that these failures were already broken before, then we can go ahead and merge. Up to you.

**Comment by mvollmer** [comment]
> If you think that these failures were already broken before, then we can go ahead and merge.

The bug is probably in the new storage tests for the content list view.  So let's merge this, and I make a PR to fix that bug, which might hit us on all OSes.

**Pull request closed without merging**
