### PR TITLE
Use node modules instead of bower components

### PR DESCRIPTION
**Pull request by stefwalter**
Bower is unreliable, and we have to clear out the whole thing in autogen.sh. Now that we're using webpack for bundling, we can just bundle from nodejs modules instead.
    
This should solve bot problems that timeout when updating the modules as well as allow automatically updating dependencies. Makes us use one less technology.

 * [x] Fix license generation and distribution #6872 
 * [x] Create node modules for our remaining bower-only modules
 * [x] Remove bower support completely
 * [x] Update for new noVNC bower component from #5932

### CODE REVIEW

**Comment by martinpitt** [comment]
"Move as many packages to bower_components as possible" -- ITYM "node_modules" in that commit message :-)

**Comment by martinpitt** [comment]
Needs a rebase now that the depending PR has landed.

**Comment by martinpitt** [comment]
Several tests now fail with:

Error: You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

**Comment by martinpitt** [comment]
@stefwalter : FYI, I locally have the conflicts resolved and I am working on a FIXUP to port the new noVNC to npm. I might not finish that today though, my first version isn't working yet.

**Comment by martinpitt** [comment]
Actually it did work, it helps to have ~/.local/share/cockpit point to the right directory *brown paperbag*. I force-pushed: I changed your commit to fix the conflicts and revert some parts of tools/build-debian-copyright (it still needs to check a module's `bower.json` for license detection, but of course *also* check `package.json` -- that's unrelated to how *we* pull it in). I pushed the FIXME on top for actually moving over noVNC. Manual and automatic tests work fine here.

**Comment by stefwalter** [comment]
> Looks good to me, and apparently tests are happy now. @stefwalter , do you mind reviewing my part? This should be squashed into the first commit, of course.

Reviewed and squashed.

**Comment by martinpitt** [comment]
The `testDockerCommandInfo (check_openshift.TestRegistry)` failure on centos-7 is pretty resilient - this move bumped the version of registry-image-widgets from 0.0.4 to 0.0.7, which changed strings.

The test does
```
    b.wait_in_text("body", "push to an image to this image stream")
```
but the current text is "To push an image..." according to the screenshot. So this needs to be adjusted.

**Comment by martinpitt** [comment]
Pushed a FIXUP, let's see how it fares on all the OSes.

**Comment by stefwalter** [comment]
Thanks. Squashed that fixup in.

**Comment by petervo** [comment]
@stefwalter, @martinpitt This broke some layout on the kubernetes page because of the bump from registry-image-widget from 0.0.4 to 0.0.7. Do either of you have permission to push 0.0.4 to npm. If so we can just revert that change as a quick fix, and properly fix when we move image listing to registry-image-widget.

**Comment by martinpitt** [comment]
I don't, but a quick fix could just be to check out [the 0.0.4 tag of registry-image-widgets](https://github.com/openshift/registry-image-widgets/tree/0.0.4) instead of the npmjs.org version in package.json? I can put up a PR.

**Comment by martinpitt** [comment]
Hmm, even though the [documentation](https://docs.npmjs.com/files/package.json) says that one can check out a particular tag or commit, this seems to be broken in npm :-(

    "registry-image-widgets": "git+https://github.com/openshift/registry-image-widgets.git",

works fine, but appending "#0.0.4" or a commit sha fails with "ERR! No version provided in package.json". I also tried with appending " 0.0.4", same result.

**Comment by martinpitt** [comment]
Sorry, this isn't npm's fault (see https://github.com/npm/npm/issues/7105). The problem is that 
[0.0.4's package.json](https://github.com/openshift/registry-image-widgets/blob/0.0.4/package.json) is lacking a "version" field, it was only added in 0.0.7. So indeed we just can't use 0.0.4 as an npm package.

**Comment by petervo** [comment]
@martinpitt, yes we can, if you have permission to push, we can push 0.0.4 while adding the needed field.

**Comment by petervo** [comment]
Oh, i replied without seeing your earlier message, yes we need someone with permission to push

**Pull request merged**
