### PR TITLE
bridge: Implement 'packet' payload

### PR DESCRIPTION
**Pull request by stefwalter**
This is for SeqPacket Unix sockets and SCTP connections.
It relays messages with the same framing as sent over
the connections. There is a maximum size above which the
messages are truncated.

### CODE REVIEW

**Comment by stefwalter** [comment]
@marusak @larskarlitski What do you think? Worked a bit on this over the weekend.

**Comment by marusak** [comment]
Awesome stuff!
I quickly built it, connected to podman and it works!
I will do further testing later today.

**Comment by stefwalter** [comment]
Split this into multiple commits, and moved one change into its own pull request.

**Comment by allisonkarlitskaya** [comment]
I'm afraid I don't really understand what this is for.

**Pull request merged**
