### PR TITLE
Remove angular from the base package

### PR DESCRIPTION
**Pull request by stefwalter**
Angular is currently not base package material. It's only used in two components and currently there's no goal for more broad based usage.

### CODE REVIEW

**Comment by stefwalter** [comment]
This is probably the most controversial of these changes due to the large size of angular, and loading it twice if you go between the ostree and kubernetes components.

However this is part of stabilizing the base package, and it's far easier to put stuff back, and make it public API, than it is to take things out.

In addition this makes @larsu webpack work much easier, and gets us around the concept of a SPA apps with large bundles of javascript rather than lots of little files.

**Comment by petervo** [comment]
Travis is failing and needs rebase

**Comment by stefwalter** [comment]
Rebased.

**Comment by petervo** [comment]
Travis is still failing with 

```
make[2]: *** No rule to make target `pkg/kubernetes/angular.js', needed by `pkg/kubernetes/angular.min.js'
```

**Comment by stefwalter** [comment]
Fixed up the bower_components.

**Pull request closed without merging**
