### PR TITLE
Fix openshift image build and tests

### PR DESCRIPTION
**Pull request by martinpitt**
- Drop kubevirt for now. It has been broken for many months now (#9479,
   #9638), and we must rebuild openshift to finally unbreak our cockpit/ws
   container (#9941). kubevirt tests continue to run on the
   openshift-prerelease image, which is sufficient for nw.

 - Move image to fedora-28, so that we can move cockpit/ws and cockpit/base to
   fedora-28.

 - Drop workaround for [certificate bug](https://github.com/openshift/origin/issues/18715),
   the fix is in latest OpenShift 3.9.0 now.

 * [x] image-refresh openshift

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-991kn.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9975-20180904-083737/

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-20180904-090202

**Comment by martinpitt** [comment]
[rhel-7-5-distropkg](https://fedorapeople.org/groups/cockpit/logs/pull-9975-20180904-093131-d1d31142-verify-rhel-7-5-distropkg/log.html) looks worrying, that needs a closer look.

**Comment by martinpitt** [comment]
Turns out the GnuTLS bug is still in RHEL 7.5, so putting the workaround back in and fixing it.

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-991kn.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9975-20180904-124242/

**Comment by cockpituous** [comment]
image-refresh openshift done: https://github.com/cockpituous/cockpit/commits/image-refresh-openshift-20180904-130909

**Comment by martinpitt** [comment]
openshift tests don't run on ubuntu-1604 (thus the flake is irrelevant), and fedora-28 passed all Test{Openshift,Registry} tests.

**Pull request merged**
