### PR TITLE
storage: Improve side panels on Details page

### PR DESCRIPTION
**Pull request by mvollmer**
Now they use the same layout as the Devices, Drives, etc panels on the
Storage Overview page.

### CODE REVIEW

**Comment by mvollmer** [comment]
I guess the tests wont be happy about the layout change.

**Comment by mvollmer** [comment]
Before:
image

After:
image

**Comment by mvollmer** [comment]
tests seem happy.

**Comment by martinpitt** [comment]
Nice cleanup! Code changes look good, leaving final  design review to @andreasn . :+1:

**Comment by allisonkarlitskaya** [comment]
```
+ make -j 8 NO_BUILD_WEBPACK=1
make  all-am
make[1]: Entering directory '/home/lis/src/cockpit'
  WEBPACK  storaged
(node:17534) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Hash: 0efadbdac5ce0a098de1
Version: webpack 4.43.0
Time: 19004ms
Built at: 05/19/2020 2:16:26 PM
                        Asset      Size  Chunks         Chunk Names
         storaged/storage.css   194 KiB       0         storaged/storage
     storaged/storage.css.map   315 KiB                 
      storaged/storage.min.js  1.23 MiB       0         storaged/storage
  storaged/storage.min.js.map  4.82 MiB       0  [dev]  storaged/storage
       storaged/test-util.css  6.16 KiB       1         storaged/test-util
   storaged/test-util.css.map  11.1 KiB                 
    storaged/test-util.min.js   363 KiB       1         storaged/test-util
storaged/test-util.min.js.map  1.25 MiB       1  [dev]  storaged/test-util
Entrypoint storaged/storage = storaged/storage.css storaged/storage.min.js storaged/storage.min.js.map
Entrypoint storaged/test-util = storaged/test-util.css storaged/test-util.min.js storaged/test-util.min.js.map
  [0] ./node_modules/react/index.js 190 bytes {0} [built]
  [2] external "cockpit" 42 bytes {0} {1} [built]
  [3] ./node_modules/moment/moment.js 170 KiB {0} {1} [built]
  [4] ./pkg/storaged/utils.js + 1 modules 30.5 KiB {0} {1} [built]
      | ./pkg/storaged/utils.js 21.6 KiB [built]
      | ./pkg/lib/service.js 8.95 KiB [built]
  [9] ./node_modules/react-dom/index.js 1.33 KiB {0} [built]
[232] ./pkg/lib/page.scss 39 bytes {0} [built]
[284] ./node_modules/qunit/qunit/qunit.js 186 KiB {1} [built]
[285] ./node_modules/@patternfly/react-icons/dist/esm/index.js 147 KiB [built]
[365] ./pkg/lib/journal.css 39 bytes {0} [built]
[390] ./node_modules/qunit-tap/lib/qunit-tap.js 10.8 KiB {1} [built]
[397] multi ./pkg/storaged/devices.jsx 28 bytes {0} [built]
[398] ./pkg/lib/polyfills.js 1.26 KiB {0} [built]
[709] ./pkg/lib/table.css 39 bytes {0} [built]
[714] ./pkg/storaged/devices.jsx + 154 modules 692 KiB {0} [built] [1 error]
      | ./pkg/storaged/devices.jsx 4.22 KiB [built]
      | ./pkg/lib/cockpit-components-empty-state.jsx 2.23 KiB [built]
      | ./pkg/storaged/client.js 24.2 KiB [built]
      | ./pkg/storaged/multipath.jsx 2.69 KiB [built]
      | ./pkg/storaged/details.jsx 4.94 KiB [built]
      | ./pkg/storaged/overview.jsx 2.44 KiB [built]
      | ./node_modules/@patternfly/react-icons/dist/esm/common.js 696 bytes [built]
      | ./node_modules/@patternfly/react-icons/dist/esm/icons/exclamation-circle-icon.js 773 bytes [built]
      | ./pkg/lib/superuser.jsx 3.59 KiB [built]
      | ./pkg/lib/packagekit.js 15.9 KiB [built]
      | ./pkg/lib/python.js 1.19 KiB [built]
      | ./node_modules/raw-loader/dist/cjs.js!./pkg/lib/inotify.py 2.66 KiB [built]
      | ./node_modules/raw-loader/dist/cjs.js!./pkg/storaged/nfs-mounts.py 9.99 KiB [built]
      | ./node_modules/raw-loader/dist/cjs.js!./pkg/storaged/vdo-monitor.py 4.24 KiB [built]
      | ./pkg/storaged/dialog.jsx 34.7 KiB [built]
      |     + 140 hidden modules
[715] ./pkg/storaged/test-util.js + 1 modules 3.8 KiB {1} [built]
      | ./pkg/storaged/test-util.js 2.75 KiB [built]
      | ./pkg/lib/qunit-tests.js 1.03 KiB [built]
    + 3490 hidden modules

ERROR in ./pkg/storaged/side-panel.jsx
Module Error (from ./node_modules/eslint-loader/dist/cjs.js):

/home/lis/src/cockpit/pkg/storaged/side-panel.jsx
  100:17  error  Static HTML elements with event handlers require a role  jsx-a11y/no-static-element-interactions

✖ 1 problem (1 error, 0 warnings)

 @ ./pkg/storaged/things-panel.jsx 22:0-45 63:44-53
 @ ./pkg/storaged/overview.jsx
 @ ./pkg/storaged/devices.jsx
 @ multi ./pkg/storaged/devices.jsx
Child HtmlWebpackCompiler:
                          Asset      Size  Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  5.57 KiB       0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./pkg/lib/qunit-template.html 1.98 KiB {0} [built]
make[1]: *** [Makefile:10157: dist/storaged/stamp] Error 1
make[1]: Leaving directory '/home/lis/src/cockpit'
make: *** [Makefile:3394: all] Error 2
```

Not sure why I'm the only one seeing this, but I've tried `npm install` (even after completely removing `node_modules/`) and I continue to get this error.  Reverting 7cb2bed9ef3d2d26241ee4179d779ddac8c4379a fixes it.

**Comment by allisonkarlitskaya** [comment]
This was caused by 4fb3ec76a793bcd87a01c86d3b8e59e2067fb0cb landing between when the CI bots ran against this commit and when it landed on master.  Matej is on the case :)

**Pull request merged**
