### PR TITLE
Image refresh for rhel-8-1

### PR DESCRIPTION
**Pull request by cockpituous**
Image refresh for rhel-8-1
 * [x] image-refresh rhel-8-1

### CODE REVIEW

**Comment by marusak** [comment]
7 failed tests, 6 of them due to:
```
audit: type=1400 audit(1563371925.700:5): avc:  denied  { search } for  pid=1904 comm="sssd_be" name="krb5" dev="dm-0" ino=25486347 scontext=system_u:system_r:sssd_t:s0 tcontext=system_u:object_r:krb5_keytab_t:s0 tclass=dir permissive=0
```
or:
```
audit: type=1400 audit(1563372302.428:5): avc:  denied  { search } for  pid=2019 comm="cockpit-ssh" name="krb5" dev="dm-0" ino=25486347 scontext=system_u:system_r:cockpit_session_t:s0 tcontext=system_u:object_r:krb5_keytab_t:s0 tclass=dir permissive=0
```
I'll send a naughty.

**Comment by marusak** [comment]
Chm, one more avc:
```audit: type=1400 audit(1563442930.272:5): avc:  denied  { search } for  pid=5487 comm="qemu-kvm" name="1630" dev="proc" ino=33731 scontext=system_u:system_r:svirt_tcg_t:s0:c37,c881 tcontext=system_u:system_r:virtd_t:s0-s0:c0.c1023 tclass=dir permissive=0```

**Comment by martinpitt** [comment]
[testMultipleZones failed again](https://209.132.184.41:8493/logs/pull-12348-20190718-115151-ac5e242d-verify-rhel-8-1/log.html), once more.

**Comment by martinpitt** [comment]
testMultipleZones failed again, needs work. @Gundersanne, can you please have a look?

**Comment by marusak** [comment]
Needs to rebase to master since #12367 changed tests names

**Comment by Gundersanne** [comment]
Outdated refresh, sorry about this.

**Pull request closed without merging**
