### PR TITLE
Check for NPM dependency updates: update xterm to 3.14.5

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [x] npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
npm-update redux done: https://github.com/cockpituous/cockpit/commits/npm-update-redux-20190719-074343

**Comment by cockpituous** [comment]
Error accessing /repos/cockpit-project/cockpit/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value"None,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}: https://209.132.184.41:8493/logs/npm-update-12363-20190719-074242/

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "xterm": "3.14.5"
pkg/docker/docker.js:import { Terminal } from "xterm";
pkg/lib/cockpit-components-terminal.jsx:import { Terminal as Term } from "xterm";
pkg/lib/console.css:@import "~xterm/lib/xterm.css";
pkg/lib/context-menu.css:    /* xterm accessibility tree has z-index 100 and we need to be in front of it
pkg/machines/machines.less:@import "~xterm/lib/xterm.css";
pkg/systemd/terminal.css:.xterm-accessibility {
pkg/systemd/terminal.jsx:                    "TERM=xterm-256color",
test/avocado/selenium-base.py:        terminal = self.wait_xpath("//*[contains(@class, 'terminal xterm')]")
test/avocado/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer')
test/avocado/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer', cond=invisible)
test/avocado/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer')
test/avocado/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer', cond=invisible)
test/avocado/selenium-machines-consoles.py:        self.wait_css('div.terminal canvas.xterm-text-layer')
test/verify/check-active-pages:                return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-pages:            return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-realms:                return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-setroubleshoot:        b.wait_in_text(".xterm-accessibility-tree", "semanage import <<EOF")
test/verify/check-setroubleshoot:        b.wait_in_text(".xterm-accessibility-tree", "boolean -D")
test/verify/check-setroubleshoot:        b.wait_in_text(".xterm-accessibility-tree", "boolean -m -1 zebra_write_config")
test/verify/check-setroubleshoot:        b.wait_in_text(".xterm-accessibility-tree", "fcontext -a -f a -t samba_share_t -r 's0' '/var/tmp/'")
test/verify/check-terminal:                return '.terminal .xterm-accessibility-tree div:nth-child(%d)' % i
test/verify/check-terminal:            b.wait_attr(".xterm-viewport", "style", style)
test/verify/check-terminal:        b.wait_attr(".xterm-viewport", "style", white_style)
test/verify/machineslib.py:        b.wait_present("div.terminal canvas.xterm-text-layer") # if connected the xterm canvas is rendered
test/verify/machineslib.py:        b.wait_present("div.terminal canvas.xterm-text-layer")
test/verify/machineslib.py:        b.wait_not_present("div.terminal canvas.xterm-text-layer")
test/verify/machineslib.py:        b.wait_present("div.terminal canvas.xterm-text-layer")
```

**Comment by martinpitt** [comment]
Clearly broken:

   TypeError: Cannot read property 'dimensions' of undefined

@marusak, does that ring a bell?

**Comment by marusak** [comment]
> does that ring a bell?

yes it does. Also the fix is fairly simple, but there is another issue behind this. xterm should have released a new version and I wanted to work with that one as it brings one more change. But as it seems they are busy, maybe I should work on this version and let this in.

**Comment by martinpitt** [comment]
There's no hurry, we can also let this sit around for a while :-)

**Comment by marusak** [comment]
Needs to rebase to master since #12367 changed tests names

**Comment by marusak** [comment]
Closing in favor of #12736

**Pull request closed without merging**
