### PR TITLE
overview: start using <h2> in CardTitles and stop overriding the default CSS

### PR DESCRIPTION
**Pull request by KKoukiou**
This came up in the review of https://github.com/cockpit-project/cockpit/pull/14513

Dont merge yet!!! This might need h3

### CODE REVIEW

**Comment by martinpitt** [comment]
@KKoukiou : Converting to draft for now -- please mark "ready for review" once you are sure about h2 vs. h3. Thanks!

**Comment by KKoukiou** [comment]
@garrett since you asked for this change can you suggest if we actually need h3 or override of the font size?

**Comment by garrett** [comment]
Yeah, we need to rework the navigation too. Those are currently `<h2>` as well.

I think the page layout should be something like:

```
<h1> Cockpit - page name (align to title)
    <h2> Navigation
        <h3> System (currently <h2>)
        - Overview
        - Logs... etc.

    ... ↓ in the iframe ↓ ...

    <h2> Networking (visibly hidden, screen readers only)
        <h3> In-page heading (including cards)
```

**Comment by garrett** [comment]
https://www.patternfly.org/v4/documentation/core/utilities/accessibility

```html
<span class="pf-u-screen-reader">
  This content is intended to be announced by assistive technologies, 
  but not visually presented.
</span>
```

**Comment by KKoukiou** [comment]
> Yeah, we need to rework the navigation too. Those are currently `<h2>` as well.
> 
> I think the page layout should be something like:
> 
> ```
> <h1> Cockpit - page name (sync to title)
>     <h2> Navigation (visibly hidden, screen readers only)
>         <h3> System (currently <h2>)
>         - Overview
>         - Logs... etc.
> 
>     ... ↓ in the iframe ↓ ...
> 
>     <h2> Networking (visibly hidden, screen readers only)
>         <h3> In-page heading (including cards)
> ```

The navigation part is the side nav?

**Comment by garrett** [comment]
> The navigation part is the side nav?

Yes.

**Comment by KKoukiou** [comment]
There are some higher priority things going on, I will reopen in the future.

**Pull request closed without merging**
