### PR TITLE
playground: Fix crashes and React errors

### PR DESCRIPTION
**Pull request by martinpitt**
- Fix missing `<tbody>`s
 - Fix "actions" property in Listing -- it must be a list, not an object
    
Add a shallow test case that ensures that the "React Patterns" page
loads and does not throw any oopses and React errors.

Also fix the `selected` property of `ListingRow`, a bug which got uncovered by this.

 - [x] Allow Listing `actions` to not be a list (PR #10313)

### CODE REVIEW

**Comment by martinpitt** [comment]
priority as this fixes regressions.

**Comment by martinpitt** [comment]
As expected, the [current test run fails the new test](https://fedorapeople.org/groups/cockpit/logs/pull-10324-20181017-095757-5eee98cd-verify-fedora-29/log.html#247) due to

    Invalid prop `actions` of type `object` supplied to `Listing`, expected an array

The next run should succeed, as #10313 landed now.

**Comment by mvollmer** [comment]
This still crashes, unfortunately: `TypeError: "selected" is read-only`.  This was actually a long-standing block to moving to React, and I forgot about it totally.

And now I have finally figured it out: the code that crashes is bogus and can be removed.  @mareklibra did that way in the beginning and I told him that would be wrong.  But he was right, sorry. 

The basic rule is: Any ListingRow that should be selectable needs to have "selected" be true or false, but not undefined. There is code in Listing that tries to force undefined "selected" props of children to false as soon as there is one child that is selectable.  But it only does it when there is a header. We don't need this convenience and can just tell the user to make sure to set "selected" propery when they construct ListingRows.

The are only two places that use the "selected" prop of Listing: the playground and the "Active Pages" dialog.  The dialog doesn't have a header, so it doesn't trigger this bug.

**Comment by martinpitt** [comment]
Delta in [pkg/subscriptions/subscriptions-view.jsx](https://github.com/cockpit-project/cockpit/pull/10321/files#diff-0e66daba31c414084a40361705239881) is the

    import * as cockpitListing from "cockpit-components-listing.jsx";

**Comment by martinpitt** [comment]
This now [breaks testAddDisk](https://fedorapeople.org/groups/cockpit/logs/pull-10324-20181017-120101-d6c42e51-verify-debian-testing/log.html#28), the button disappeared.

**Comment by martinpitt** [comment]
When I run the test locally, I get an useful error:
```
> error: Warning: Failed prop type: Invalid prop `actions` of type `object` supplied to `VmDisksTab`, expected an array.
    in VmDisksTab (created by VmDisksTabLibvirt)
    in VmDisksTabLibvirt (created by ListingRow)
    [...]
```
Indeed this `actions` property is not the Listing one, so I'll revert that bit for now.

**Comment by martinpitt** [comment]
@mvollmer: This all works now, can you please have another look? Thanks!

**Pull request merged**
