### PR TITLE
bots: Move container/ tests to Fedora 30

### PR DESCRIPTION
**Pull request by martinpitt**
* [x] image-refresh fedora-30

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on centosci-tasks-vsq1s.
Log: https://209.132.184.41:8493/logs/image-refresh-12041-20190611-091313/

**Comment by cockpituous** [comment]
image-refresh in progress on 1-cockpit-9.
Log: https://209.132.184.41:8493/logs/image-refresh-12041-20190611-091313/

**Comment by cockpituous** [comment]
image-refresh fedora-30 done: https://github.com/cockpituous/cockpit/commits/image-refresh-fedora-30-20190611-095656

**Comment by martinpitt** [comment]
The cockpit-podman and composer/edge tests are failing everywhere right now (e. g. PR #12023), and debian-testing/rhel-7-7 aren't being touched here, so these are all unrelated. selenium/edge also started to time out everywhere else, but I retry that a few times.

**Pull request merged**
