### PR TITLE
Ship compressed HTML files

### PR DESCRIPTION
**Pull request by stefwalter**
And put the uncompressed, unminified files in the debug directory.

### CODE REVIEW

**Comment by stefwalter** [comment]
Depends on #1992

**Comment by stefwalter** [comment]
Rebased.

**Comment by mvollmer** [comment]
check-multi-machine is sad.  Probably trivial to fix.

**Comment by stefwalter** [comment]
I'm testing a fix.

**Comment by stefwalter** [comment]
This should do the trick.

**Pull request closed without merging**
