### PR TITLE
Fix rhel-x image

### PR DESCRIPTION
**Pull request by martinpitt**
The latest batch. On the positive side, PackageKit works at last \o/

 * [x] image-refresh rhel-x
 * [x] fix `checkKeys` (#9920)

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on cockpit-tasks-5n02p.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-9968-20180903-103434/

**Comment by cockpituous** [comment]
image-refresh rhel-x done: https://github.com/cockpituous/cockpit/commits/image-refresh-rhel-x-20180903-110101

**Comment by martinpitt** [comment]
I pushed another set of fixes, this now should take care of the remaining failures, except check-keys. But this touches tests in a way that also affects other OSes, so after #9920 lands this needs to run and pass everywhere.

**Comment by martinpitt** [comment]
Two more SELinux errors, meh

**Comment by martinpitt** [comment]
I got a green test run at last. Re-starting to cover all OSes for cross-checking the test changes. But this is ready for review now.

**Pull request merged**
