### PR TITLE
storage: Ignore traditional LVM2 snapshots

### PR DESCRIPTION
**Pull request by mvollmer**
Cockpit does not really account for the idiosyncrasies of traditional
snapshots, including:

 - Deleting the origin will delete all snapshots.

 - Activating/deactivating the origin will do the same to all
   snapshots, and vice versa.

 - The size of a snaphot does not correspond to the size of its block
   device, and resizing a snapshot does not resize the block device.

 - Writing to the origin might cause the snapshot to run out of space,
   but Cockpit doesn't allow to monitor this.

Snapshots of thin volumes are different as they are truly independent
of their origin after creation and function just like any other thin
volume.  To emphasize this, we call the action of creating them
"cloning".

### CODE REVIEW

**Comment by martinpitt** [comment]
That is a really confusing terminology then.. A "thin" snapshot sounds like a delta overlay on top of an origin, i. e. that would be the one which *is* dependent on the origin, and specifically it's not a clone. I thought that the traditional snapshots would be an actual clone, independent of the origin? 

Anyway, can you please add/adjust tests here, to demonstrate the difference? I suppose you know this, but if you need to test snapshots on our images, you can steal the approach from https://github.com/cockpit-project/cockpit/pull/11201/files#diff-17015dc6ed05c4c1082a10f7523e2b30R760

**Comment by mvollmer** [comment]
> That is a really confusing terminology then.. 

From a user point of view and only looking at the contents of the actual block devices, both traditional and thin snapshots behave the same.  Both are a straight copy of the origin volume that use some implementation tricks to achieve a CoW optimization.

So, yeah, changing the terminology doesn't really improve things.  I'll revert that bit.

**Comment by martinpitt** [comment]
Makes sense, thanks! Could we still get a test case which makes sure that both cases keep working? I can help you with this if you want.

**Comment by mvollmer** [comment]
> Could we still get a test case which makes sure that both cases keep working?

We had a test for snapshots in `check-storage-lvm2`, for catching #11032.  I have extended it a bit to check that traditional snapshots are indeed ignored.

**Comment by martinpitt** [comment]
[this failure](https://209.132.184.41:8493/logs/pull-11714-20190502-090808-58f776d5-verify-rhel-7-7/log.html#256) could be relevant?

**Comment by mvollmer** [comment]
> this failure could be relevant?

Yes, that's also #11032, with a different symptom.  Apparently, LVM2 can create a trad snap for a thin vol.  This will happen by accident almost always due to #11032, which passes a random size down the stack.

If that random size is < 1024, it gets rounded down to zero and we get an error: "--size can't be zero".  If it is larger, it gets rounded up to the next extent, and we get no error but a trad snap.

Since trad snaps are not shown, the test fails.

I'll add another naughty pattern.

**Comment by mvollmer** [comment]
ubuntu-1804 is also subject to #11032

**Comment by martinpitt** [comment]
Dropping needswork, I figure with the additional naughty it should work?

**Comment by martinpitt** [comment]
[testLvm](https://209.132.184.41:8493/logs/pull-11714-20190503-053838-f83780db-verify-centos-7/log.html#271) failure on centos-7, retrying for comparison.

**Comment by martinpitt** [comment]
Now [testSnapshots](https://209.132.184.41:8493/logs/pull-11714-20190503-065959-f83780db-verify-centos-7/log.html#272) failed on centos-7. In between the last two runs, all tests succeeded, but there's still a lot of race conditions here. :sob:

**Comment by mvollmer** [comment]
```
Logical volume TEST/lvol1 in use.
Unable to deactivate pool metadata spare LV. Manual intervention required.
```

Yeah, I have seen this. This thing is, there is no lvol1, right?  So this must be a volume that is created by lvcreate itself as part of setting up the thinpool...

**Comment by mvollmer** [comment]
> So this must be a volume that is created by lvcreate itself as part of setting up the thinpool...

Let's make a naughty pattern for this for centos-7 at least.  Does it happen elsewhere?

**Comment by martinpitt** [comment]
Is that an actual bug? If so, it should be reported. If it's expected behaviour, it shouldn't be a naughty, but the test should just be changed to get along with it.

**Comment by mvollmer** [comment]
> Is that an actual bug?

I say yes, if this is indeed lvcreate and udev fighting. From the users point of view, lvm2 and udev have to work seamlessly together since they are both part of the core OS.

(However, almost nothing explicitly coordinates with udev in the storage stack, I have the feeling, and we are slowly putting retry loops into every layer of our code because of that.)

However, if we only see this bug on centos-7, I am inclined to assume that it is already fixed in later versions.

There is also the fact that we have had this exact lvcreate call in the this test and other tests for a long time, and it never failed like this... I'll try moving things around a bit to see whether that helps.

**Comment by mvollmer** [comment]
> There is also the fact that we have had this exact lvcreate call in the this test and other tests for a long time, and it never failed like this... I'll try moving things around a bit to see whether that helps.

Alright, I moved the trad snap creation after the thin pool creation, and that seems to avoid the bug. *sigh*

**Pull request merged**
