### PR TITLE
Update Patternfly to version 2.8.0

### PR DESCRIPTION
**Pull request by stefwalter**
We need this for the various dashboards that we're trying to implement. Those need Patternfly 2.5.0 or later, so might as well update to the latest.
    
Lock down the jQuery version or else bower decides to downgrade it as part of this update.

### CODE REVIEW

**Comment by stefwalter** [comment]
@andreasn Have you had a chance to take a look at this?

**Comment by andreasn** [comment]
Since it's a new version, it would be a good opportunity to get rid of some of the HACKs in pkg/base1/cockpit.css
332 is fixed https://github.com/patternfly/patternfly/issues/75
453 is fixed https://github.com/patternfly/patternfly/issues/65
558 is fixed https://github.com/patternfly/patternfly/issues/122

**Comment by andreasn** [comment]
I've been going over all pages and everything else looks good visually

**Comment by andreasn** [comment]
on the server that is, didn't test cluster or registry yet.

**Comment by stefwalter** [comment]
> Since it's a new version, it would be a good opportunity to get rid of some of the HACKs in pkg/base1/cockpit.css

I agree. Would you be able to make a commit, and I can include it in this pull request.

**Comment by andreasn** [comment]
yup, coming up!

**Comment by dperpeet** [comment]
you could reword the first commit to "make: Fix the 'update-lib' target"

**Comment by andreasn** [comment]
> Would you be able to make a commit, and I can include it in this pull request.

Fixed here 71ee97071baca65ee71abf644db288d49d29e0d9

**Comment by stefwalter** [comment]
> Fixed here 71ee970

Included

> you could reword the first commit to "make: Fix the 'update-lib' target"

Done

Also fixed alert display.

**Comment by dperpeet** [comment]
The warning icon in the ostree package (I looked at the design patterns page) is misaligned in this branch, works on master:
ostree_error

**Comment by dperpeet** [comment]
Otherwise this looks good.

**Comment by stefwalter** [comment]
Fixed icon position.

**Comment by stefwalter** [comment]
Lets wait on merging this until after 0.91 is tagged.

**Comment by andreasn** [comment]
All looks good. I found a misalignment issue in the docker run dialog, but I think that's independent of this change.

**Pull request closed without merging**
