### PR TITLE
bots: Enable sudo rule on IPA server

### PR DESCRIPTION
**Pull request by martinpitt**
Unfortunately it was decided that the IPA sudo rule would not get
enabled by default. The way to go was to use the new
"enable-admins-sudo" ipa-advise, which got introduced in FreeIPA 4.7.1.
So update the documentation accordingly.

As this is not a temporary hack any more, move it to the ipa image
setup script, to save some time on running the tests.

 * [x] image-refresh ipa

### CODE REVIEW

**Comment by cockpituous** [comment]
image-refresh in progress on bos-tasks-8h3hl.
Log: http://fedorapeople.org/groups/cockpit/logs/image-refresh-11001-20190118-085555/

**Comment by cockpituous** [comment]
image-refresh ipa done: https://github.com/cockpituous/cockpit/commits/image-refresh-ipa-20190118-092828

**Comment by martinpitt** [comment]
breaks `testNegotiate`.

**Comment by martinpitt** [comment]
Fixed.

**Comment by martinpitt** [comment]
IPA tests succeeded everywhere.

**Pull request merged**
