### PR TITLE
selinux: Move modifications above alerts

### LINKED ISSUE #12283: selinux: System modifications is never seen
System modifications is under a very, very long list of SELinux warnings/errors. As a result, it will never be seen, unless someone already knows to scroll to the bottom of the page to look for it.

It should probably be moved above the logs.

### PR DESCRIPTION
**Pull request by marusak**
Fixes #12283
Closes #12292

### CODE REVIEW

**Comment by marusak** [comment]
@garrett I have moved it to the top. I am not really sure it is the best solution, because if this list gets too big it can move alerts way to down - and I think the more important use case is seeing alerts than exporting modifications.

**Comment by garrett** [comment]
> I have moved it to the top.

Do you mean the very top? Or sandwiched between the main heading + toggle and the list?

(Checking out and building the PR now...)

**Comment by garrett** [comment]
So this is what it looks like on my system, with:
- the infinite spinner that's "fixed" (with error handling) in the other PR
- an error message
- an SELinux toggle where it's permissive in a config file, but toggled on in Cockpit, with the warning message

Basically, it's all tricked out and _not_ default. :wink:

Screenshot_2019-07-11 SELinux - Sunny(1)

**Comment by garrett** [comment]
I wonder if the enforce policy should be swapped vertically with the error message... or if it should be integrated into the header, like we do in Software Updates and Firewall.

If the latter, we could give the switch labels like "Permissive" when it's off and "Enforcing" when it's on.

The "Setting deviates..." message should then be a little string below the heading with an info icon (probably, as it's not necessarily an error or warning) preceding it. The error would then go below that. And then the rest of the page, with the changes and list.

**Comment by marusak** [comment]
> So this is what it looks like on my system

You have there pretty much everything there can be :D 

> or if it should be integrated into the header, like we do in Software Updates and Firewall

That would be great. I like how you described that. I can make another commit for that into this PR (since this PR is just moving order anyway).

**Comment by marusak** [comment]
@garrett so I implemented it and pushed (I am now preparing testing vm to see if I need to adjust tests as well)

Normally a user would see this:
normalstyle
And when would toggle the switch:
changedmessage
And this is how it looks like with full set of warnings and errors:
garretstyle

**Comment by garrett** [comment]
That's nicer overall... but the spacing is wrong. And why are your fonts weird? Do you disable 3rd party fonts (and if so, then why are the icon fonts working still)?!

...And why is your computer's name localhost.localdomain?

(I'll try it locally to see what happens here.)

**Comment by marusak** [comment]
> but the spacing is wrong

expected that :) Can you please push fixed spacing?

> And why are your fonts weird? Do you disable 3rd party fonts

I havn't done anything special. It is just at it is without any interfering. 

> And why is your computer's name localhost.localdomain?

Also default, I never bothered to change it. (why would I?)

**Comment by marusak** [comment]
@garrett I've moved the items a bit around and used flex. Here are some screenshots:

allright
justmessage
jsuterror
abitdifferent

Can you please review?

**Comment by garrett** [comment]
It's nice, but the spacing is off. I guess the spacing is off before this PR too.

I would help fix the spacing, but I have no way of actually doing so, because — _surprise_ — there's still an error on my machine. Yay?
 
Screenshot_2019-07-17 SELinux - Sunny

I guess I can fix the spacing for what I currently see and hope it fixes it under the usual non-errored state too.

How long can the system modifications box get? Is there a height limit set on it (perhaps something like 25vh — a quarter of the viewport maximum) with an `overflow: auto`?

**Comment by marusak** [comment]
> ... but I have no way of actually doing so ...

Pushed another tmp commit for you - now you won't see any errors or messages.

> How long can the system modifications box get?

Infinitely long. Setting max height would make sense with scrollbar when gets too long.

**Comment by marusak** [comment]
@garrett did some style fixes. Tests were green before, now I triggered just two to give bots a chance. Ready for review (not that there is much to review).

**Comment by marusak** [comment]
Possible release note? Not that modifications moved above alerts, but maybe that the top panel was restyled a bit as well? Not sure though.
Screenshot just in case:
screnn12345

**Pull request merged**
