### PR TITLE
test: Improve image pruning logic

### PR DESCRIPTION
**Pull request by dperpeet**
We want to be able to keep images that are used in pull requests as well.

### CODE REVIEW

**Comment by dperpeet** [comment]
I'm not sure about all the extra command line options... should we just use the defaults and skip args for the rest?

**Comment by stefwalter** [comment]
> I'm not sure about all the extra command line options... should we just use the defaults and skip args for the rest?

I think so. We can always add them later.

**Comment by dperpeet** [comment]
rebasing, since I originally intended this to be quiet with a `--verbose` cli option, but https://github.com/cockpit-project/cockpit/commit/eb662521daa14fb8a22eb0d9726dc9b0cbc0a8d8 made `--quiet` an option instead

**Comment by martinpitt** [comment]
Reverted on origin as this breaks tests. Can you please create a new PR for this?

**Comment by stefwalter** [comment]
This commit was included in #6511 instead of creating a new PR a second time around.

**Pull request merged**
